### PR TITLE
docs: fix typo in `CHANGELOG.md` (find-tuned --> fine-tuned)

### PR DESCRIPTION
**Pull request by raj2033**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ✓ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The typo was find-tuned. It should now read as fine-tuned.
Issue Number: N/A

## What is the new behavior?
It should now read as fine-tuned.

## Does this PR introduce a breaking change?

- [ ] Yes
- [✓ ] No

### CODE REVIEW

**Comment by raj2033** [comment]
@googlebot I signed it!

**Review by gkalpak — APPROVED** [review]
Good catch! Thx, @raj2033 :+1:

Can you please update the commit message to more closely follow our [commit message guidelines](https://github.com/angular/angular/blob/1d9e56eba06958e37ef8062ae7b65afa85f90632/CONTRIBUTING.md#commit). For example:

> docs: fix typo in \`CHANGELOG.md\` (find-tuned --> fine-tuned)

Reviewed-for: global-docs-approvers

**Comment by raj2033** [comment]
@gkalpak updated the commit message. Pls check.

**Comment by gkalpak** [comment]
LGTM - thx, @raj2033 :+1:

**Review by IgorMinar — APPROVED** [review]
Thanks!

Reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Pull request closed without merging**
