### PR TITLE
docs(forms): fix incorrect punctuation

### PR DESCRIPTION
**Pull request by Hossein13M**
change the incorrect punctuation from ':' to ','.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #45538 45538

## What is the new behavior?
Replacing ':' with ',' which is the correct punctuation.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AlirezaEbrahimkhani** [comment]
@hossein13m 
would you please update your commit message and add `resolve angular#44338` in the commit message footer (per angular [guidelines](https://github.com/angular/angular/blob/1c11a5715576632a4fb7170202395cf95dfbce09/CONTRIBUTING.md#commit-message-footer)), so that the issue will be auto-closed once the PR is merged?

To update the commit message you can use the `git commit --amend` command.

Thanks :pray:

**Comment by hossein13m** [comment]
Thanks, @AlirezaEbrahimkhani, for the notice.
However, you have mentioned the wrong issue number. The correct one is #45539.

**Comment by AlirezaEbrahimkhani** [comment]
@hossein13m 
Yeah :sweat_smile: you're right
but there is another problem with your commits you add 4 more redundant commit messages please drop them and edit your last commit message and please avoid merging and instead use rebase.

you can use rebase doc I think it will help you do this.
Rebasing docs: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by devversion** [comment]
Hi @hossein13m: This PR includes a lot of commits which are not actually authored as part of this PR. This is because your changes are not properly rebased on the upstream `master` branch. Can you please fix that so the PR can be merged?

**Comment by hossein13m** [comment]
Sure @devversion I will fix it as soon as possible

**Comment by jessicajaniuk** [comment]
@hossein13m This is super close. Just some file formatting lint issues. If you can fix and push, we can land this asap!

**Pull request closed without merging**
