### PR TITLE
build(browserstack): add all supported browsers

### PR DESCRIPTION
**Pull request by marclaval**
The job should fail as some tests are currently broken.

### CODE REVIEW

**Comment by mlaval** [comment]
Same legitimate failures as in Sauce Labs.
Flakes and performances to be monitored once the situation is greener.

**Comment by IgorMinar** [comment]
keep in mind that we only have 10 licenses from BS so we'll never make this green with the current setup and constraints

**Comment by IgorMinar** [comment]
we could ask for more resources from BS

**Comment by mlaval** [comment]
The 10 VMs limit doesn't seem to be a problem, jobs are queued accordingly.

Though we are facing errors which make a number of browsers to fail: 
`Error: 403 Forbidden (Rate Limit Exceeded)`

This is being addressed in https://github.com/karma-runner/karma-browserstack-launcher/pull/40

**Pull request closed without merging**
