### PR TITLE
chore(dart) Update dev dependency on code_tranformers

### LINKED ISSUE #6665: Dart: update pkg/code_transformers to ^0.4.0

### PR DESCRIPTION
**Pull request by kevmoo**
Closes https://github.com/angular/angular/issues/6665

### CODE REVIEW

**Comment by kegluneq** [comment]
Why is this necessary? Seems like we should leave this wider unless it's necessary to constrain.

**Comment by vicb** [comment]
@kevmoo what is the status of this PR ?

**Comment by kevmoo** [comment]
@vicb Sent an updated pull request (that addresses comment from @kegluneq ) – pending CI

**Comment by kegluneq** [comment]
LGTM if LGT Travis

**Comment by kevmoo** [comment]
@vsavkin  @kegluneq I tried a rebase against something recent – any items?

**Comment by vikerman** [comment]
Manually merged to master.

**Pull request closed without merging**
