### PR TITLE
docs(DynamicComponentLoader): move examples to ngOnInit

### PR DESCRIPTION
**Pull request by ericmartinezr**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features) (no need to but I had to mark it so it doesn't show as an incomplete task)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Documentation update

**What is the current behavior? (You can also link to an open issue here)**

The [current state](https://angular.io/docs/ts/latest/api/core/DynamicComponentLoader-class.html) of the examples in the doc shows that we can use DynamicComponentLoader in the constructor. 
This is causing issues, see https://github.com/angular/angular/issues/7334 and this [SO question](http://stackoverflow.com/q/35508458/4933038)

**What is the new behavior (if this is a feature change)?**

This changed in beta.1, the view is no longer accessible in the constructor. 
See [breaking changes section](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-beta1-catamorphic-involution-2016-01-08).

**Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)**

Not a breaking change regarding DCL functionality, but the user has to move the code from the constructor to ngOnInit.

**Other information:** -

### CODE REVIEW

**Comment by ericmartinezr** [comment]
Updated the original message to follow the [PR template](https://github.com/angular/angular/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166471.
------------------------------------------------------------------------------------------------------------


[[f2196271d8146cb570c0366000b951f1d6a9f2a3-673073433]]

**Comment by vsDizzy** [comment]
Omg I spent an hour because devs are too lazy to merge PR or fix their samples.

**Comment by ericmartinezr** [comment]
I'm too stupid to fix the conflicts, I'll open a new PR that adds an example of using loadNextToLocation, I can't reproduce this error message with loadAsRoot in the constructor.

**Pull request closed without merging**
