### PR TITLE
docs: split CLI subcommands in separate doc page

### LINKED ISSUE #54768: CLI sub commands are not listed correctly in adev
### Describe the problem that you experienced

Sub commands of the Angular CLI are not listed in adev

Example

|ADEV|AIO|
|------------------------------	|-------------	|
| https://angular.dev/cli/generate | https://angular.io/cli/generate|
|https://angular.dev/cli/cache | https://angular.io/cli/cache|
|https://angular.dev/cli/analytics |  https://angular.io/cli/cache|

### PR DESCRIPTION
**Pull request by JeanMeche**
Pending angular/dev-infra#1945

Fixes #54768

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]

**Comment by sonukapoor** [comment]
@JeanMeche I see the PR is in draft. Is there still anything pending for it before it can be converted to a regular PR?

**Comment by JeanMeche** [comment]
Yes, it's pending another PR on `dev-infra` as mentionned in the 1st message 🙂

**Comment by sonukapoor** [comment]
Sorry, I didn't see that. Thanks!

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by atscott** [comment]
This PR was merged into the repository by commit 323611141b361274cde7c195e5381494a0e5f145.

**Pull request closed without merging**
