### PR TITLE
build: update to TypeScript 5.6 final

### PR DESCRIPTION
**Pull request by crisbeto**
Updates the repo to the final version of TypeScript 5.6.

### CODE REVIEW

**Review by devversion — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit c51c0f23bb8add55cf933489ecafdc85b475ba76.

The changes were merged into the following branches: main

**Comment by huehnerlady** [comment]
Hi, any idea when the typescript update will be released?

**Comment by JeanMeche** [comment]
@huehnerlady With v19, around mid-november.

**Pull request closed without merging**
