### PR TITLE
docs: convert the last `my-app` components to `app-root'

### LINKED ISSUE #20235: <my-app> in angular documentation
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In some places you write my-app for the root selector, while in others you use app-root. This even happens on the same page, in particular at https://angular.io/guide/displaying-data
This is clearly a copying error
I suggest you do a search for other examples of this, in particular the Tour of Heroes

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by petebacondarwin**
Most of these were fixed in other PRs but there were are couple of stragglers.
Note that `my-app` components in non-documentation facing code, such as
compliance tests have not been changed.

Fixes #20235

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by gkalpak** [comment]
Minor commit message typo:
```diff
-`app-root'
+`app-root`
```

**Review by gkalpak — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Review by gkalpak — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by petebacondarwin** [comment]
Googler: this is a docs-only commit so it should not need a presubmit.

**Review by gkalpak — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
LGTM, also forced g3 status to "green" since it's a docs-only change.

**Pull request closed without merging**
