### PR TITLE
test: remove unused utility class

### PR DESCRIPTION
**Pull request by crisbeto**
Removes the `MockNgZone` class since it isn't being used anywhere.

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
[presubmit](http://test/OCL:383436124:BASE:383436336:1625677513770:b36c8278)

**Comment by AndrewKushnir** [comment]
@crisbeto the presubmit indicated that the `MockNgZone` is used in Google's codebase in a few places (in tests). I believe there is a chance this is used outside of Google as well. Should we just keep it in this case?

**Comment by crisbeto** [comment]
It doesn't hurt to keep it, but my thinking was that since it's referenced inside `testing/internal`, people would be discouraged from using it.

**Comment by AndrewKushnir** [comment]
@crisbeto yeah, it looks like there are some deep imports and it would probably take more time to clean them up than keeping the mock for now...

**Comment by crisbeto** [comment]
Alright, let's leave this for now, it's not much of a maintenance cost.

**Pull request closed without merging**
