### PR TITLE
fix(change_detection): expose values when detecting changes in key-value...

### LINKED ISSUE #1118: Can't access values from KVChangeRecord
I'm working on the binding to the classList (#876) and shaping my directive as follows:

```javascript
@Decorator({
  selector: '[class]',
  bind: {
    iterableChanges: 'class | keyValDiff'
  }
})
export class CSSClass {
  set iterableChanges(changes) {
    changes.forEachItem((record) => {
      if (record._currentValue) {
        DOM.addClass(this._domEl, record.key);
      } else {
        DOM.removeClass(this._domEl, record.key);
      }
    });
  }
}
```

This works fine in JS but it looks like I'm accessing "private" variable `record._currentValue`. It seems to me that both `_previousValue` and `_currentValue` should be public - otherwise we can't really access values of the individual change records.

@vicb it seems like you've written this part - does my request make sense to you, or am I doing sth wrong?

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
... pairs

Fixes #1118

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@vicb as discussed in #1118, could you OK this one for me?

**Comment by vicb** [comment]
Actually as this is exposed to the user, do we want to have getters instead ?
what do you think @vsavkin ?

**Comment by pkozlowski-opensource** [comment]
Yeh, was asking myself the same question, but since [iterable_changes](https://github.com/angular/angular/blob/edc3709451c7e72c4d2714fd1ebbd734a793a7b3/modules/angular2/src/change_detection/pipes/iterable_changes.js#L519) just has a field and the `key` is already exposed as a field....

**Comment by vicb** [comment]
if we add getters we should add them everywhere... 
let's go with this for now and we can discuss about getters later.
LGTM

**Comment by pkozlowski-opensource** [comment]
Ok, good.

**Pull request closed without merging**
