### PR TITLE
fix(aio): api search input fix and style

### PR DESCRIPTION
**Pull request by sjtrimble**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Although we can now click on the filter input, the fact that I cannot click on the magnifying glass to focus the input box really jars with me.
Would it be an easy fix to allow that?

**Comment by gkalpak** [comment]
I've typically used `pointer-events: none` for these types of things (but it won't work on older IEs I think - which is probably OK).

**Comment by sjtrimble** [comment]
@petebacondarwin I went with George's recommendation - that seemed to have addressed what you were after.

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Nice one @sjtrimble - I have added my approval.

**Pull request merged**
