### PR TITLE
refactor(compiler-cli): optimize extra import generation in local com…

### PR DESCRIPTION
**Pull request by pmvald**
…pilation mode

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by devversion — APPROVED** [review]

**Comment by devversion** [comment]
@pmvald can you rebase and mark for merge then?

**Comment by AndrewKushnir** [comment]
FYI, removing the "merge" label for now, please re-add when the PR is ready for merge.

**Comment by pmvald** [comment]
Caretaker note: p1 test failures are tool failures and unrelated to Angular as far as it shows

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 1f2e791c57535eef4c97c89a2d6da9a0a09f16c8.

**Pull request closed without merging**
