### PR TITLE
feat(router): add routing to async components

### PR DESCRIPTION
**Pull request by btford**
This lays the groundwork for lazy loading in Angular 2.

I'm still working on the API + Docs.

### CODE REVIEW

**Comment by mhevery** [comment]
@IgorMinar please review

**Comment by btford** [comment]
We're going to prioritize #2001 over this, so hold off until after the router is typescriptified since I'll have to rewrite/rebase this.

**Comment by btford** [comment]
Landed as 548f3dd5cc902179304ee7b3d50d793a46c646c2 and cd95e078fe98e288feea54ed0fe849f77348ad4f.

**Comment by jpsfs** [comment]
Hi,

Sorry to dig up this.

I'm doing some experiences with routing and lazy loaded components. Right now the only examples I'm seeing require something like:

´´´
import {MyComponent} from "mypackage";

@RouteConfig([
  { path: '/', component: MyComponent, as 'start'}
])
´´´

Now, what I don't want to load MyComponent until I absolutely need to. Is there any way of doing something like:

´´´
@RouteConfig([
  { path: '/', component: 'mypackage/MyComponent', as 'start'}
])
´´´

Cheers,

**Pull request closed without merging**
