### PR TITLE
docs: add HeroService to code tabs and fix headers

### PR DESCRIPTION
**Pull request by kapunahelewong**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #22359

## What is the new behavior?
Adds `HeroService` to code tabs in Final Code Review.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Hey @petebacondarwin could you help me figure out what I've done wrong? The one page I edited doesn't render. Here's the preview: [https://pr22373-69186bc.ngbuilds.io/tutorial/toh-pt5](https://pr22373-69186bc.ngbuilds.io/tutorial/toh-pt5). It does this locally except that it renders for the first 2 or 3 seconds, then it goes blank.

**Comment by kapunahelewong** [comment]
Hey @petebacondarwin could you help me figure out why the page I've edited won't render? https://pr22373-1053568.ngbuilds.io/tutorial/toh-pt5 Maybe some spacing is off?

**Comment by jenniferfell** [comment]
Master/Detail Components and Routing aren't loading right now. Blank pages. @petebacondarwin do you have any ideas? I've checked routing line-for-line, and I don't recognize anything that would break it. Thanks!

**Review by jenniferfell — DISMISSED** [review]
Master/Detail Components and Routing aren't loading. Blank pages.

**Comment by gkalpak** [comment]
This is a known issue #22493. Will be fixed by #22504 (which is marked for merge). Make sure to rebase on master once that's merged.

**Comment by ralshammrei2** [comment]
add HeroService to code tabs and fix headers #22373

**Comment by kapunahelewong** [comment]
Hey @jenniferfell want to take a look? Rebased after #22504 was merged.

**Review by gkalpak — APPROVED** [review]

**Pull request closed without merging**
