### PR TITLE
Add ng-india conference to upcoming events

### PR DESCRIPTION
**Pull request by aayushgoyal**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Build related changes
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation content changes
- [ ] CI related changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Added the Ng-India Conference to upcoming events.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by aayushgoyal** [comment]
@googlebot I signed it!

**Comment by santoshyadav198613** [comment]
Already raised https://github.com/angular/angular/pull/33656

**Comment by santoshyadav198613** [comment]
Hey @aayushgoyal , thanks for the PR but it is duplicate and you can close this one.let me know if you think something is needed to be changed in description you can review the existing PR.

**Comment by aayushgoyal** [comment]
> Hey @aayushgoyal , thanks for the PR but it is duplicate and you can close this one.let me know if you think something is needed to be changed in description you can review the existing PR.

**Comment by aayushgoyal** [comment]
@santoshyadav198613 I have closed the PR.

**Comment by santoshyadav198613** [comment]
> @santoshyadav198613 I have closed the PR.

Thank you in case you need more issues to work on refer https://github.com/angular/angular/labels/hotlist%3A%20community-help

**Pull request closed without merging**
