### PR TITLE
docs: fix broken image links in tutorial

### PR DESCRIPTION
**Pull request by rflemerson**
This is to fix broken image links in the first-app tutorial documentation with functional links that match the working examples.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

If you followed the links provided in the tutorial, you would encounter broken images.

Issue Number: N/A

## What is the new behavior?
The broken image links in the tutorial documentation have been fixed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM! Thanks.

**Comment by jessicajaniuk** [comment]
@rflemerson You'll need to sign the CLA in order for us to merge this code. Thanks for your contribution!

**Comment by rflemerson** [comment]
Sorry, my commit email was wrong.

**Review by MarkTechson — APPROVED** [review]
Thanks for catching this, LGTM!

**Review by JeanMeche — APPROVED** [review]
LGTM

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 4b3d1c82e3b0839345bb5b2b75c23436f3373dea.

**Pull request closed without merging**
