### PR TITLE
docs(core):providing description for Output

### PR DESCRIPTION
**Pull request by aloksingh3112**
As no description is provided for Output in docs so i have added one please review
you can check the fault here https://angular.io/api/core/Output 

i am also ready for further changes so plzz tell i will do

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by aloksingh3112** [comment]
This is my first github commit to an OSS so plzz help if i am anywhere wrong.

**Comment by aloksingh3112** [comment]
there is some issue with my commit-message will you please tell what should be the correct commit-message

**Comment by aloksingh3112** [comment]
still example is missing in the description for Output I can add that just what want to know what should be 
the idea behind example(i mean is there any decided steps)

**Comment by brandonroberts** [comment]
This change has already landed in master. If you see something else, feel free to open a new PR.

**Pull request closed without merging**
