### PR TITLE
docs(guide): Updated event-listeners.md doc to use correct term, even -> every

### PR DESCRIPTION
**Pull request by Zetsword**
event time -> every time

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, could you please reword your commit and make it a `docs: ...` commit. This is to follow our guidelines & satisfy the linting job.

**Comment by JeanMeche** [comment]
The `guide` scope isn't valid, we're fine with no scope for docs changes. 
Also make sure to drop the merge commit, we'd like this change to be a single commit. Thank you.

**Review by JeanMeche — APPROVED** [review]
Thanks for this

**Comment by devversion** [comment]
@JeanMeche should we add `action: review` if the PR still has pending reviewers?

**Comment by devversion** [comment]
This PR was merged into the repository by commit a89fd30690ef34e2c80cf4e4266e7f2e74d28e3b.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
