### PR TITLE
docs: separate template syntax into multiple docs

### PR DESCRIPTION
**Pull request by kapunahelewong**
This is part of a refactor of template syntax and structure. The first phase (this PR) breaks out template syntax into multiple documents. The second phase will be a rewrite of each doc (forthcoming PR after this one lands).

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently all info is all in one long document.

Issue Number: N/A

## What is the new behavior?

There is a new section in the same location of the NAV of template syntax. This new section expands to show new documents. Each doc is from a section of the current template syntax.

Specifically, this PR does the following:

- Breaks sections of the current template syntax document each into their own page.
- Corrects the links to and from these new pages.
- Adds template syntax subsection to the left side NAV which contains all the new pages.
- Adds the new files to pullapprove.

This PR does not rewrite content for the sub-pages beyond making them standalone pages with the example link and making sure the language doesn't refer to a non-existent "above" or "below" section. The original template-syntax.md file now only retains the intro (slightly reworked to refer correctly to the other pages rather than "below") and a list of the new pages and what those pages offer.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Preview: https://pr36954-ff6050d.ngbuilds.io/guide/template-syntax

### CODE REVIEW

**Comment by jbogarthyde** [comment]
I think you could put all the Binding Syntax topics into one longer page - it will not be as long when we have tightened up the language and organization. The first one would be the Overview section, with links to the topic sections in the table that already lists the binding types.

The three Directives topics (Built-in, Attribute, Structure) could be combined into a sibling section of Template Syntax
- The  parent section landing page (currently Displaying Data in Views) would point to those major sections (Binding Syntax and Directives)
- The Template Syntax landing page could point to Directives as the last of the  Next Steps -- another aspect of how templates are related to components.

**Comment by jbogarthyde** [comment]
You could have a "Template logic" section after "Binding syntax", which would include reference vars, operators and type-casting (are there any other built-in template functions?).

`@Input` and `@Output` seems to be part of Component Interaction, and seem more related to Directives than Template Syntax.
The current Component Interaction is a hodgepodge "cookbook", but the last one is a demo of `@Input.) Those need to be sorted into task-oriented topics - - perhaps "Sharing data between components"?
I think we need to emphasize the "view-hierarchy" concept and demonstrate it more clearly. As I understand it, there is no actual parent-child relationship between components, the hierarchy is all in the templates, and is established with directives.

**Comment by jbogarthyde** [comment]
- The User Input topic needs to be combined somehow with Event Binding, at least with links.

- Event Binding ends with the section "Template statements have side effects" - that section should be moved to the Template Statements topic, and Event Binding can have simple reference note.

**Comment by rockument69** [comment]
Here's a comment...

**Review by aikithoughts — APPROVED** [review]
LGTM. Thanks for doing this.

Reviewed-for: global-docs-approvers

**Review by jelbourn — APPROVED** [review]
LGTM - using global approval for the files in pullapprove.yml

Reviewed-for: global-approvers

**Comment by jelbourn** [comment]
@kapunahelewong it does look like the commit message needs a slight tweak

**Pull request closed without merging**
