### PR TITLE
feat(bazel): expose explicit mapping from closure to devmode files

### PR DESCRIPTION
**Pull request by hybrist**
This feature is aimed at development tooling that has to translate
production build inputs into their devmode equivalent. The current
process involves guessing the devmode filename based on string
replace patterns. This allows consuming build actions to read the
known mappings instead.

This is a change in anticipation of an update to the general
Typescript build rules to consume this data.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

This is the helper method called by the TSC compilation logic to determine the output files for a given `ctx`. It only provides a list of outputs of various types with no information about how they relate to each other.

## What is the new behavior?

This adds a new field (`.transpilation_infos`) to the returned struct that allows to correlate a `closure_js` file to its corresponding `devmode_js` file.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by IgorMinar** [comment]
@josephperrott & @gregmagolan can you please help with the code review here and ensure that this is aligned with our other ongoing work?

**Comment by IgorMinar** [comment]
@jkrems is there a bigger context behind this change? can you please share?

**Comment by jkrems** [comment]
> Is there a bigger context behind this change? can you please share?

The overall context is that @eatingw recently wrapped up the work to extend the JavaScript provider in our build rules with official support for devmode information ("library-level transpiled sources"). This includes the set of devmode files per target but also a mapping between "production JS" and "devmode JS". By exposing this relationship here, the Typescript compilation action in `rules_typescript` can add it to the "typescript" provider which in turn can then by forwarded to a more general JavaScript provider.

The ultimate goal is to have a unified view on "devmode" JavaScript outputs, no matter the source language, and a way to unambiguously find the devmode equivalent of a known production input.

**Review by gregmagolan — APPROVED** [review]
LGTM. This doesn't affect anything I'm working on in rules_nodejs.
Is there a similar change coming for ts_library?

**Comment by jkrems** [comment]
> Is there a similar change coming for ts_library?

Yes, I prepped that change and it should hopefully be coming in the next days. This PR should likely not be merged before the change landed in `ts_library` to make sure the API actually matches.

**Comment by jkrems** [comment]
Update: The change to `rules_typescript` has landed. https://github.com/bazelbuild/rules_typescript/commit/df3afdb31b0486af670a2c87cbc8770abf5c1f7d

So this should be good to go from my side. :)

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by jkrems** [comment]
Anything I can do to move this along? Or will the triage process eventually come to this?

**Comment by josephperrott** [comment]
I will trigger the g3 presubmit now, but it looks like its just waiting on @IgorMinar's review

**Review by IgorMinar — APPROVED** [review]
Thanks a lot for the context info! This looks like an interesting effort. Is there a design doc covering the overall change? I don't need it to approve this change but I'd be curious to read it if there was one. Thanks!

**Comment by jkrems** [comment]
> Is there a design doc covering the overall change?

This was part of a larger effort to provide better (and consistent) mappings between original sources and their transpiled equivalents generated by closure compiler or tsc that @EatingW has been working on.

These changes are tied to the JS provider so the design doesn't translate 1:1 to the current state of bazel's JS provider which likely doesn't have a concept of transpilation mappings. The documents I'm aware of focus on the integration with the internal provider only.

**Pull request closed without merging**
