### PR TITLE
fix(core): inherit host directives

### LINKED ISSUE #51203: HostDirectives doesnt provide the hosted directives when inherited
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Hi,

I have encountered an issue where `hostDirectives` doesn't provide with inheritance:

1. Create a standalone `CustomDirective`:
image

2. Create `BaseComponent` that uses the `CustomDirective` via `hostDirectives`:
image

3. Inject the `CustomDirective` in BaseClass via `inject()` method:
image

4. Create `ExtendsComponent` that extends via inheritence the `BaseComponent`:
image

If you try to run the application, it complains about missing provision for said directive:
image

If manually provides the CustomDirective inside the `ExtendsComponent` it works:
image

### Please provide a link to a minimal reproduction of the bug

https://stackblitz-starters-icp5kn.stackblitz.io

### Please provide the exception or error you saw

```true
ERROR NullInjectorError: R3InjectorError(Standalone[App])[CustomDirective -> CustomDirective -> CustomDirective]: 
  NullInjectorError: No provider for CustomDirective!
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.4
Node: 18.16.1
Package Manager: npm 6.14.17
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1601.4
@angular-devkit/core         16.1.4
@angular-devkit/schematics   16.1.4
@schematics/angular          16.1.4
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by crisbeto**
Adds support for inheriting host directives from the parent class. This is consistent with how we inherit other features like host bindings.

Fixes #51203.

### CODE REVIEW

**Comment by crisbeto** [comment]
[Passing TGP](http://test/OCL:583320976:BASE:583347432:1700225674042:71031e55)

**Comment by crisbeto** [comment]
I realized that this will need a bit more work on the compiler side to properly support template type checking. Putting it back to draft.

**Comment by crisbeto** [comment]
Okay, _now_ everything should be covered.

**Review by jessicajaniuk — APPROVED** [review]
LGTM!

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit c7c7ea9813f6dcf91c096bb37d36bfe0c715a04f.

**Pull request closed without merging**
