### PR TITLE
docs(ivy): Typo fix, ContentChildred => ContentChildren

### PR DESCRIPTION
**Pull request by pankajparkar**
This PR is made to correct typo Status.md page of Render3 

## PR Type
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Review by vicb — APPROVED** [review]

**Comment by vicb** [comment]
Please fix the commit message (see CONTRIBUTING.md)

**Comment by pankajparkar** [comment]
@vicb can you please take a look at it again?

**Comment by pankajparkar** [comment]
@vicb can you please some one look into this? It ready to merge.

**Review by gkalpak — APPROVED** [review]

**Review by vicb — APPROVED** [review]

**Comment by vicb** [comment]
fixed in #22888

**Pull request closed without merging**
