### PR TITLE
build: enable forms tests on IE

### PR DESCRIPTION
**Pull request by crisbeto**
Enables running the `forms` unit tests against IE on Saucelabs. It seems like original failures have been resolved.

**Note:** these tests usually don't run against PRs, but I've verified that they pass by:
1. Running them against IE on my local machine.
2. Enabling them for PRs temporarily (see the first commit).

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
LGTM, thanks @crisbeto 👍

**Comment by AndrewKushnir** [comment]
FYI, it looks like @IgorMinar was added by PullApprove because there was a BUILD file modified in the original set of changes to run the tests on windows. The BUILD file was reverted, so I removed Igor from reviewers list. Thank you.

**Comment by AndrewKushnir** [comment]
Sorry, my previous message is incorrect. Igor was added because the `*.bazel` file was changed, so we still need an approval from @IgorMinar (adding "review" label for now).

**Review by IgorMinar — APPROVED** [review]
Lgtm

**Pull request closed without merging**
