### PR TITLE
build: update dependency terser to 5.16.3 [security] 

### PR DESCRIPTION
**Pull request by devversion**
See individual commits.

Fixed up version of: #48990 

For concrete examples of the Terser diff/investigation:

**Before**:

Screenshot 2023-02-08 at 16 49 06

Screenshot 2023-02-08 at 16 49 15

**After**

Screenshot 2023-02-08 at 16 49 20

Screenshot 2023-02-08 at 16 49 26

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

Can you include more context for what is happening in either the pull request description or in one of the commits?

**Comment by devversion** [comment]
for what change? all commit except for the one from renovate have a commit message (+ the in depth screenshots in the PR)

**Review by alan-agius4 — APPROVED** [review]

**Review by dylhunn — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
👍 

Just an observation: since there are no payload size golden file changes, it looks like there are no major effects on DCE (tree-shaking) and those extra symbols were just missing in the symbol tests in the first place.

**Comment by devversion** [comment]
One note: Terser update here does not affect size integration tests or AIO, because those tests depend on Terser from the Angular devkit. We updated devkit w/ terser also a few days ago and it caused an increase of around 600 bytes. The same change is here reflected in terms of symbol goldens.

**Comment by devversion** [comment]
I've looked a little more just to track the terser commit. It's: https://github.com/terser/terser/commit/7f6187a461340451c2f6bfd2cfd6544de24844a8. In my screenshots above, notice how the constants are in a `var` but the accesses in a function definition. Terser made a correctness change here, even if it avoids inlining. It's still re-using the variables (which is the correct thing)

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit b97d591ff4e3b5705476b2d45d07133b3f2f5613.

**Pull request closed without merging**
