### PR TITLE
Delete files which are copies of TypeScript files

### PR DESCRIPTION
**Pull request by alexeagle**
This is the real deal for changing Angular to Typescript.
I've merged WIP from @IgorMinar and @zzo and some other fixes @rkirov helped with, so now the build succeeds and some tests can run.
We are still missing something in the rx module loading...

### CODE REVIEW

**Comment by zzo** [comment]
cool I'll take this and try to fixup the karma stuff

**Comment by rkirov** [comment]
add back modules/angular2/src/reflection/reflector.js, you should only remove '.es6' files. That's why dart tests fail on Travis.

**Comment by alexeagle** [comment]
It's the only file in this set not shadowed by a .dart file. It's because karma-dart still has the preprocessors. So we can't go on to more directories until it is fixed :( :( :(

**Comment by alexeagle** [comment]
But, it's a good suggestion, we can get at least part of this working. Trying the build again with reflector.js still duplicated.

**Pull request merged**
