### PR TITLE
docs(aio): add a French onsite training ressource

### PR DESCRIPTION
**Pull request by cyrilletuzi**
## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by cyrilletuzi** [comment]
The lint issue doesn't seem to be mine.

**Review by StephenFluin — CHANGES_REQUESTED** [review]
The linked site doesn't follow our branding guidelines, it should be "Angular" instead of "Angular 4". (v5 will be released soon for example). The number will keep going up, but the content will be substantially the same.

**Comment by cyrilletuzi** [comment]
Hi @StephenFluin ,

I'm aware of your branding guidelines, but unfortunately, they don't fit to this case.

Please consider that not everybody is a JavaScript expert in a Silicon Valley startup, up to date with every details about recent tools (especially when communication about this detail has been quite discreet).

Most people I have in trainings in France are : 
- back-end developers who don't know anything about JS yet,
- people still working on AngularJS (v1).

So, the title of a page is for SEO, and what people search for now is : "Angular 2 training" or "Angular 4 training". Having a "AngularJS training" and "Angular training" would be very confusing (and that confusion is not my fault ;).

Consider also that in the business process, there are non-technical people, and good luck to make them understand this nuance.

Rest assured that once people are in the course, it's one of the first things I explain, and that all the course material respect the branding guidelines, with just "Angular". I do so in my Medium posts too.

I try to explain that in the pages (there are also pages for "Angular 2" and "Angular 5"), even if you can't check as it's in French. There is even [a specific page](https://formationjavascript.com/angular-4-angular-5/) to explain that : but I can only explain to people once they are on my website, not _before_.

2017 is clearly too early to just say "Angular" in this particular case, we may change that in 2018. And so you know : all French training centers do the same, because we have no choice.

I put the Angular 4 link as v5 was not yet stable at time of the PR, but the [page for v5 is already there](https://formationjavascript.com/formation-angular-5/) and I can modify the PR.

If that's not OK to you, I can rethink the presentation and do a general "Formation Angular" page (but not sure it would be good for SEO).

**Comment by cyrilletuzi** [comment]
@StephenFluin I reorganized my website content to match the branding guidelines (while managing the issues I mentioned elsewhere).

**Review by StephenFluin — APPROVED** [review]

**Comment by cyrilletuzi** [comment]
@juleskremer ?

**Review by juleskremer — APPROVED** [review]

**Comment by juleskremer** [comment]
@cyrilletuzi apologies for the delay; I've been out of the office since AngularConnect :)

**Comment by cyrilletuzi** [comment]
No problem, thanks!

**Pull request closed without merging**
