### PR TITLE
refactor(core): avoid repeated views in serialized data

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit updates the serialization logic to recognized similar repeated views and instead of including the same info over and over again, a special field is added to the serialized view object with a number of repetitions. The hydration logic also recognizes the flag and creates the necessary number of dehydrated views in a container.

This optimization should help minimize the amount of extra annotations required for cases like `*ngFor` with large number of items.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
This looks great! LGTM!

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:518028137:BASE:518028178:1679337150595:80b22742).

**Comment by AndrewKushnir** [comment]
**Caretaker note**: this PR is ready for merge, the `post_approval_changes` check got stuck for some reasons.

**Review by jessicajaniuk — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit a0c289cbac54b4869e932689e307deaf5d319ed8.

**Pull request closed without merging**
