### PR TITLE
Update clang format

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
This is update and cleanup after fixing https://github.com/angular/clang-format/issues/6

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@mprobst could you please review / OK this one?

**Comment by pkozlowski-opensource** [comment]
@mprobst so, the inital build on Travis failed and after digging into it it seems like new version of the clang-format enforces different formatting, have a look at this diff: https://github.com/pkozlowski-opensource/angular/commit/8a9c26b54d3189f5f9cf06063d2017348a7e3243#diff-a33c1ac3c4d4d8f6d630fa838c40868fL35

Not sure if this is a proper behaviour or is there something fishy still going on here....

**Comment by mprobst** [comment]
I'm not quite sure what caused this change (though a change did touch function literal handling, but shouldn't cause this).

But in any case, I think this formatting is fine and in line with what clang-format usually does, lining up parameters on open parenthesis, so this LGTMS.

**Comment by pkozlowski-opensource** [comment]
OK, will wait for Travis and if it is green I'm going to merge this. Thnx for your input!

**Pull request closed without merging**
