### PR TITLE
docs: fix typos in 'Httpclient' docs

### PR DESCRIPTION
**Pull request by rafaelss95**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Fix some typos:

- Construct a OPTIONS -> Construct an OPTIONS
- Construct a GET (in HEAD method) -> changed to `HEAD`
- Construct a PATCH (in POST method) -> changed to `POST`

## Does this PR introduce a breaking change?
```
[ ] Yes
[X ] No
```

## Other information
**The all format changes are all responsability of `gulp format`.**

### CODE REVIEW

**Comment by aravindfz** [comment]
does this PR refer any issue?

**Comment by rafaelss95** [comment]
@aravindfz no, why?

**Comment by aravindfz** [comment]
I believe there are a lot code changes in this PR. so hard to review, please correct the formatting

**Comment by rafaelss95** [comment]
As I said: "*The all format changes are all responsability of `gulp format.`*". 

[I just ran `gulp format` as specificied in `DEVEPOPER.md` file](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#-formatting-your-source-code).

**Comment by trotyl** [comment]
Then why you're failing the `lint` test?

**Comment by rafaelss95** [comment]
The same question I'm asking myself. I just didn't change any line of this format. You can test yourself... run `gulp format` and see the output you get.

**Comment by trotyl** [comment]
Frankly it's doing well, that could be some problem of local environment.

image

**Comment by rafaelss95** [comment]
You mean that it's a possible in my local env?

**Comment by gkalpak** [comment]
I did run `gulp format` (and our CI runs it on every build) and I didn't get any changes 😕

**Comment by trotyl** [comment]
@rafaelss95 I mean I ran the `gulp format` based on your PR, and it reverted all your formats back, then getting the same result as `lint` task suggested.

**Comment by rafaelss95** [comment]
Ok, idk what's happening then. I just ran `gulp -v` and that's the output:

```
$ gulp -v
[19:30:08] CLI version 3.9.1
[19:30:08] Local version 3.9.1
```

Also, I forgot to mention that when I ran `gulp format`, it formats 400+ files, not only this.

Anyway, I've updated the commit to include only the typo changes, without `gulp format`.

**Comment by rafaelss95** [comment]
@gkalpak can you review?

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
LGTM, but one of the `common` owners needs to approve it.
(I assume we need to "pass over" `common/http` to `http` owners, but for now it belongs to `common`.)

**Comment by rafaelss95** [comment]
Hey, is there anything stopping this PR to be merged?

**Comment by rafaelss95** [comment]
bump :(

**Comment by rafaelss95** [comment]
bump...

**Comment by rafaelss95** [comment]
@gkalpak can you ping the person responsible to review this PR? It's open for almost an year...

**Review by mhevery — APPROVED** [review]

**Pull request closed without merging**
