### PR TITLE
docs: correct typo in description of runTask method

### PR DESCRIPTION
**Pull request by shayan-ghzl**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows the guidelines outlined here: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Fixed a typo in the description of the `runTask` method.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by kirjs — APPROVED** [review]
Thanks for contributing

**Comment by AndrewKushnir** [comment]
@shayan-ghzl thanks for creating this PR. It looks like the `lint` CI check is failing due to the commit message, which contains incorrect scope (`doc(fix):`). Could you please update the commit message (using `git commit --amend`) to start with `docs:` instead? Than you.

**Comment by shayan-ghzl** [comment]
@AndrewKushnir yes, of course
it's my pleasure
thank you for your kindness.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 38b090a747f256c1bd6e1f27553dbfa0a81e450e.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
