### PR TITLE
refactor(http): remove most of the typescript overloads and infer the response from the options instead

### PR DESCRIPTION
**Pull request by sod**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Return types for common/http are done via overloads which results in complex code completion. And not all valid values are immediately obvious.

image

## What is the new behavior?

Return type is inferred from options, so the method signature stays lean

image

My intention was to keep all prior defaults intact so this is not a breaking change - e.g. if prior infer was `any`, it stays `any`. If it was `Object` (with a capital O?), it stays `Object`.

Also trying to get rid of the not very helpful ~15 overloads below each method on https://angular.io/api/common/http/HttpClient

All methods (apart from `request`) now look like

```typescript
  post<R = Object, O extends HttpRequestOptions = object>(url: string, body: any, options?: O):
      Observable<InferHttpResponse<O, R>> {
    return this.request<any>('POST', url, addBody(options || {}, body));
  }
```

where `InferHttpResponse<O, R>` infers the response type from the options and wraps it accordingly.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sod** [comment]
no interest?

**Comment by petebacondarwin** [comment]
@sod sorry this never got picked up. I believe the reason for these overloads is that it makes the IDE intellisense clearer. @alxhub could shed more light and make a call on whether this approach actually works.

**Comment by alxhub** [comment]
> @sod sorry this never got picked up. I believe the reason for these overloads is that it makes the IDE intellisense clearer. @alxhub could shed more light and make a call on whether this approach actually works.

Yeah, back in the early days of `@angular/common/http`, we didn't have conditional types, and the language service for TS wouldn't "expand" many complex type aliases and show a real, concrete type to the user, so overrides offered the best IDE experience.

I don't think this is true any longer - I played around with the overrides here a fair bit and the editor experience seems to be on par with the previous.

This code is certainly more maintainable. However, one of the biggest challenges with `HttpClient` has been documenting the APIs - I think it'd be worth looking at which API form produces more usable/readable documentation.

**Comment by alxhub** [comment]
Unfortunately I don't think this is the direction we want to go, as the documentation generated for each request method in `HttpClient` would not be as clear as it is today, where it shows each signature with specific request and response types separately.

**Pull request closed without merging**
