### PR TITLE
fix(MetadataResolver): throw Component.moduleId is not a string

### LINKED ISSUE #11590: Uncaught TypeError: uri.match is not a function
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting


**Current behavior** 
When running the application with web pack at start the app throws Uncaught TypeError: uri.match is not a function.

RC.6 or RC.7 both using web pack when I compile and run the app. I get Uncaught TypeError: uri.match is not a function. I do not have module:module.Id in my .ts file.

When I change Split() function under Compiler.ts file, the app works. Two possible workarounds I m doing every time when I do npm install.

Fix this code in compiler.umd.js

function _split(uri) {
// put condition to check if not != ""
return uri.match(_splitRe);
}

or

function componentModuleUrl(reflector, type, cmpMetadata) {
if (isStaticSymbol(type)) {
return staticTypeModuleUrl(type);
}
if (isPresent(cmpMetadata.moduleId)) {
var moduleId = cmpMetadata.moduleId;
var scheme = getUrlScheme(moduleId.toString());
return isPresent(scheme) && scheme.length > 0 ? moduleId :
"package:" + moduleId + MODULE_SUFFIX;
}
return reflector.importUri(type);
}

Can we have permanent fix for this?

**Expected behavior**
The app shouldn't throw this error.

**Reproduction of the problem**

Use the following packages to reproduce the issue. 

Package.JSON

"dependencies": {
    "@angular/common": "2.0.0-rc.7",
    "@angular/compiler": "2.0.0-rc.7",
    "@angular/core": "2.0.0-rc.7",
    "@angular/forms": "2.0.0-rc.7",
    "@angular/http": "2.0.0-rc.7",
    "@angular/platform-browser": "2.0.0-rc.7",
    "@angular/platform-browser-dynamic": "2.0.0-rc.7",
    "@angular/router": "3.0.0-rc.3",
    "angular2-toaster": "0.5.2-rc.6",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "intl": "^1.2.4",
    "jquery": "^3.1.0",
    "jquery-ui": "^1.12.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.21"
  },
  "devDependencies": {
    "angular2-template-loader": "^0.5.0",
    "copy-webpack-plugin": "^3.0.1",
    "css-loader": "^0.24.0",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.22.0",
    "raw-loader": "^0.5.1",
    "ts-loader": "^0.8.2",
    "typescript": "^1.8.10",
    "typings": "^1.3.2",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.15.1"
  }


**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**
MAC, WEB PACK DEV SERVER

* **Angular version:** 2.0.0-rc.6 & Angular version:** 2.0.0-rc7


* **Browser:** [all] 

 
* **Language:** [TypeScript ES5]
 
* **Node (for AoT issues):** `node --version` =   


NPM Version : 3.10.3
Node Version : v6.5.0

### PR DESCRIPTION
**Pull request by vicb**
fixes #11590

### CODE REVIEW

**Comment by robwormald** [comment]
This LGTM, other than you might want to say "inline the styles in JiT mode" (since its unnecessary in AoT?)

**Comment by vicb** [comment]
@robwormald Not sure let's discuss that

**Comment by alexeagle** [comment]
merged in bd4045b

**Pull request closed without merging**
