### PR TITLE
docs(compiler): Fix compiler option 'skipTemplateCodegen' name reference

### PR DESCRIPTION
**Pull request by lincolnthree**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ X ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ X ] Tests for the changes have been added (for bug fixes / features)
- [ X ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ X ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
The `skipTemplateCodegen` option was incorrectly referenced using camelcase `skipTemplateCodeGen`. This PR corrects the issue.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ X ] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@lincolnthree thanks for improving Angular docs! The change looks good 👍 

Could you please update commit message (`git commit --amend`) to split the body into 2 lines so that they are less than 120 chars (the "lint" CI job is failing because of that)?

Thank you.

**Comment by lincolnthree** [comment]
@AndrewKushnir Of course. Lovely GitHub adding the full PR text by default :) I opted to removed the second line entirely as it is irrelevant in the context of a commit.

**Comment by AndrewKushnir** [comment]
@lincolnthree great, everything looks good and I've added this PR to the merge queue.

Thank you for improving Angular docs! 👍

**Comment by lincolnthree** [comment]
@AndrewKushnir Hmm... not sure I got it right?

**Comment by lincolnthree** [comment]
@AndrewKushnir Awesome! Thanks so much. You're welcome. Keep up the great work. Your big push to take care of the issue backlog is being noticed (and appreciated.)

**Pull request closed without merging**
