### PR TITLE
fix(animations): make sure that the animation function delay is applied

### LINKED ISSUE #47283: Delay option ignored in animation function
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No (at least I don't think it is)

### Description

The [animation](https://angular.io/api/animations/animation) function accepts a `delay` option which should delay the animation, but the option seems to be ignored (there are no errors thrown/displayed, the option simply doesn't produce any effect).

You can see the issue in this [stackblitz reproduction](https://stackblitz.com/edit/angular-ivy-mtumzm), there if the `delay` is provided via the [transition](https://angular.io/api/animations/transition) function then the animation works as expected, but it does not when the `delay` is provided via  [animation](https://angular.io/api/animations/animation).

Peek 2022-08-28 12-51

Note: The [useAnimation](https://angular.io/api/animations/useAnimation) function seems to present the same exact issue.

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
make sure that when an animation is defined via the `animation` function
(and used via `useAnimation`) and a delay has been provided then that
delay gets correctly applied

resolves #47283

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #47283

As you can see from the stackblitz in the issue, the delay of animations defined using `animation` is not correctly applied:

before

## What is the new behavior?

The delay gets correctly applied:

after

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
 - `useAnimation` can also take a delay option, and that is also not being applied, I haven't dealt with that in this PR, if ok I thought of looking into it in a follow up PR

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM Thanks Dario!

**Comment by dylhunn** [comment]
merge-assistance: I will run a TGP overnight.

**Comment by dylhunn** [comment]
TGP is [running](https://test.corp.google.com/OCL:473934943:BASE:473935360:1663050388124:cf7949a2).

**Comment by jessicajaniuk** [comment]
TGP is greeeeeen! 🟢

**Pull request closed without merging**
