### PR TITLE
Update to nodejs rules 0.27.10

### PR DESCRIPTION
**Pull request by gregmagolan**
Also,

* adds `configuration_env_vars = ["compile"]` to `generated @npm//@angular/bazel/bin:ngc-wrapped` nodejs_binary using new `bazelBin` `additionalAttributes` yarn_install & npm_install feature. This is required to be able to compile with Ivy using ng_module by setting `build --define=compile=aot` in `.bazelrc`.

* /integration/bazel: removes umd, ngfactory & ngsummary scripts that no longer need to be explicitly specified in ts_devserver & ts_web_test_suite in

### CODE REVIEW

**Comment by gregmagolan** [comment]
Generated ngc-wrapped binary target in `/integration/bazel` now looks like this:

```
# Wire up the `bin` entry `ngc-wrapped`
nodejs_binary(
    name = "ngc-wrapped__bin",
    entry_point = "@angular/bazel/src/ngc-wrapped/index.js",
    install_source_map_support = False,
    data = [":bazel__pkg"],
    configuration_env_vars = ["compile"],
)
```

with the added `configuration_env_vars` attribute.

**Review by kyliau — COMMENTED** [review]
Please also remove the scripts from https://github.com/angular/angular/blob/master/packages/bazel/src/builders/files/src/BUILD.bazel.template

**Comment by gregmagolan** [comment]
> Please also remove the scripts from https://github.com/angular/angular/blob/master/packages/bazel/src/builders/files/src/BUILD.bazel.template

Done. Good catch.

**Comment by alexeagle** [comment]
CI failure looks legit:
https://github.com/angular/angular-bazel-example/pull/352

**Comment by gregmagolan** [comment]
> My guess is that something has `importHelpers: true` in tsconfig, which is fine, and then deps on tslib, but we are missing the third-party-lib getting included in devSources still.

Seems like. I added tslib back to ts_devserver & ts_web_test_suite here. We can fix this is another PR.

**Review by kyliau — APPROVED** [review]

**Review by alexeagle — APPROVED** [review]

**Pull request closed without merging**
