### PR TITLE
fix(common): allow interceptors to inject HttpClient

### LINKED ISSUE #18224: Cyclic dependency error with HttpInterceptor
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Trying to do the same example of AuthInterceptor like in [official doc](https://angular.io/guide/http#intercepting-all-requests-or-responses), to add a Authorization header on all requests.

```ts
@Injectable()
export class AuthInterceptor implements HttpInterceptor {
  constructor(private auth: AuthService) {}
 
  intercept(req: HttpRequest<any>, next: HttpHandler) {
    const authHeader = this.auth.getAuthorizationHeader();
    const authReq = req.clone({headers: req.headers.set('Authorization', authHeader)});
    return next.handle(authReq);
  }
}
```

Problem : with real code, the `AuthService` needs to request the server on login, signin, etc., so it itself inject `HttpClient`.

```ts
@Injectable()
export class AuthService {

  constructor(private http: HttpClient) {}

}
```

It creates this fatal error in console :

```
Uncaught Error: Provider parse errors:
Cannot instantiate cyclic dependency! InjectionToken_HTTP_INTERCEPTORS ("[ERROR ->]"): in NgModule AppModule in ./AppModule@-1:-1
```

## Expected behavior

Should work, as it's a very common case. Otherwise interceptors are limited to use services without Http.

## Environment

<pre><code>
Angular version: 4.3.0
</code></pre>

### PR DESCRIPTION
**Pull request by alxhub**
Previously, an interceptor attempting to inject HttpClient directly
would receive a circular dependency error, as HttpClient was
constructed via a factory which injected the interceptor instances.
Users want to inject HttpClient into interceptors to make supporting
requests (ex: to retrieve an authentication token). Currently this is
only possible by injecting the Injector and using it to resolve
HttpClient at request time.

Either HttpClient or the user has to deal specially with the circular
dependency. This change moves that responsibility into HttpClient
itself. By utilizing a new class HttpInterceptingHandler which lazily
loads the set of interceptors at request time, it's possible to inject
HttpClient directly into interceptors as construction of HttpClient no
longer requires the interceptor chain to be constructed.

Fixes #18224.

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
nice fix!

I suggest that you change the commit message to: "fix(common): allow HttpInterceptors to inject HttpClient" - the current subject that will appear in the changelog is a bit ambiguous.

**Comment by alxhub** [comment]
g3 failure is unrelated (already broken tests)

**Comment by peterdeme** [comment]
Hi, when is this getting released?

**Comment by mlc-mlapis** [comment]
@peterdeme ... it was already.

**Pull request closed without merging**
