### PR TITLE
docs(http): fix em-dashes not displaying correctly

### LINKED ISSUE #38662: Special character rendering mistake
# 📚 Docs or angular.io bug report

### Description

Section of docs contains &emdash; character that renders as a string instead of actual dash.

### What's the affected URL?**

https://angular.io/guide/http#optimizing-server-interaction-with-debouncing

### Reproduction Steps**

Go to page.

### Expected vs Actual Behavior**

Expected: shown long dash
Actual: shown &emdash; 

## 📷Screenshot

image
image

### Browser info

Mac OS, Google Chrome 84.0.4147.135

### Anything else relevant?

image

### PR DESCRIPTION
**Pull request by gkalpak**
Fixes #38662.

### CODE REVIEW

**Comment by JoostK** [comment]
But hey, this duplicates #38397!

**Comment by gkalpak** [comment]
No, no, this is an alternative approach 😛
(Plus you should have commented that on #38662 😛)

Nonetheless, #38397 is red on CI and we haven't heard from the author in the last 7 days (so the PR's future is uncertain) :grin:
Therefore, I am leaving this open in case we don't hear back on #38397.

But definitely happy to go with #38397 if it gets updated.

**Comment by JoostK** [comment]
Haha, I wanted to comment on #38662 but then saw your PR, so you beat me to linking the dup there :)

**Review by IgorMinar — APPROVED** [review]
LGTM! Thank you!

Reviewed-for: global-approvers

**Pull request closed without merging**
