### PR TITLE
docs: update to standalone and routing by default

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit covers several changes:
 - routing enabled by default
 - standalone by default

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Review by MarkTechson — COMMENTED** [review]
Everything LGTM but a small few nits:

- Can we update the "reviewed" date on the MD files?

**Comment by alan-agius4** [comment]
@MarkTechson, added the "reviewed" dates. PTAL

**Review by MarkTechson — APPROVED** [review]
Thanks for making this update, cheers!

LGTM

**Comment by dylhunn** [comment]
@alan-agius4 This needs a rebase, sorry!

**Comment by alan-agius4** [comment]
@dylhunn, rebased.

**Comment by dylhunn** [comment]
@alan-agius4 WDYT of the failing aio test?

**Comment by alan-agius4** [comment]
> @alan-agius4 WDYT of the failing aio test?

Should be a flake, I re-ran the failed job.

**Comment by alan-agius4** [comment]
@dylhunn, it was indeed a flake as it’s now green.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 3598d212a6587b6fdffa40d9adc2ee5b48ae8c3f.

**Pull request closed without merging**
