### PR TITLE
Extract router providers into functions that could be tree-shakeable in the future (patch)

### PR DESCRIPTION
**Pull request by atscott**
Patch target for https://github.com/angular/angular/pull/46215/commits

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
👍

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

Let me know when you want me to merge this! :)

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit ca043987c80306cd351e593ed84603e05ea135e2.

**Pull request closed without merging**
