### PR TITLE
[WIP] Use chrome headless

### PR DESCRIPTION
**Pull request by filipesilva**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Chrome is ran with Xvfb in order to simulate a screen.

## What is the new behavior?
Chrome Headless headless is used instead, which does not need Xfvb.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by filipesilva** [comment]
@vicb an unintended consequence of this PR is that it seems that protractor 5 doesn't work well with using `"protractor": "file:../../../node_modules/protractor",` as the install path, failing with the following message:

```
[1] [08:57:18] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
[1] [08:57:18] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
```

For this reason each of the integration tests is now re-rerunning `webdriver-manager update`.

It also required a fair bit of code changes to draw upon the correct config items for karma/protractor.

**Comment by IgorMinar** [comment]
@filipesilva I remember that I we discussed this PR in person/over a chat and I had some objections. Do you recall the details? Was it just that we wanted to have full control over the browser version used or also something else?

**Comment by filipesilva** [comment]
@IgorMinar I don't quite remember myself. But using Chrome Headless should be unrelated to using a specific chrome version, since the installed chrome is still used.

Some things can't be adequately run using headless though:
- lighthouse scores were lower without it
- protractor can't change window size

I think I ultimately stopped working on this because there was no significant interest to move in Angular core and I had other things to work on.

**Comment by IgorMinar** [comment]
let's close this for now. we can revisit later.

**Pull request closed without merging**
