### PR TITLE
docs(aio): typo & update the bio

### PR DESCRIPTION
**Pull request by asnowwolf**
ThoughWorks => ThoughtWorks

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Can you please change the commit message to `docs(aio): ...`?

**Comment by trotyl** [comment]
> He is looking forward to the birth of his baby.

AFAIK your baby has already been released, right? Shouldn't that be updated as well? 😃

**Comment by asnowwolf** [comment]
@gkalpak Ok, I will change it.

**Comment by asnowwolf** [comment]
Done. Thank you! @gkalpak @trotyl

**Review by gkalpak — APPROVED** [review]

**Pull request merged**
