### PR TITLE
docs(aio): Added resources to UI Components

### PR DESCRIPTION
**Pull request by bmarkov**
docs(aio): Added resources to UI Components. Added jQWidgets Angular Components

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by juleskremer** [comment]
Please edit your submission to remove reference to the Angular version.  Thanks.

**Comment by bmarkov** [comment]
Removed the reference to the angular version with the latest commit

**Comment by wardbell** [comment]
A change to a marketing page such as this requires @juleskremer permission

**Review by juleskremer — APPROVED** [review]

**Comment by jasonaden** [comment]
@wardbell Please approve this PR.

**Review by juleskremer — APPROVED** [review]

**Comment by StephenFluin** [comment]
@bmarkov It looks like the code samples don't work. Example: https://www.jqwidgets.com/angular/angular-textarea/angular-textarea-autocomplete.htm

I'm getting an error that it's rejecting API calls because of the API only uses http. Can you fix?

**Comment by bmarkov** [comment]
The link should be with http:// instead of https://. I added a pull https://github.com/angular/angular/pull/17875 about that.

**Pull request merged**
