### PR TITLE
Fixed doc class name mismatches with code

### PR DESCRIPTION
**Pull request by jordan-amman**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Class name mismatch to code.

Issue Number: N/A

## What is the new behavior?
Class names are now correct.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

### CODE REVIEW

**Comment by jordan-amman** [comment]
Is there anything else I need to do for this pull request? Thank you for your time.

**Comment by kapunahelewong** [comment]
Oh, @jordan-amman, this fix had just made it in (#31815)  when you submitted your PR: https://github.com/angular/angular/blob/2abbe98e337fecabedb17e09d612bf0db760ed94/packages/router/src/config.ts#L336

Thank you for this though. If you'd still like to contribute, I'm happy to help you find something of similar scope. 🙂

**Comment by jordan-amman** [comment]
Hey @kapunahelewong, I would love to find another fix I can help with. I picked this simple change because I'm trying to get better using git source control. Once I get my first pull request in I'd also love to look into more challenging issues. Thank you for your time!

**Comment by kapunahelewong** [comment]
Perfect, @jordan-amman! Docs language fixes are a good place to do just that. How about this? In the Lifecycle Hooks doc: https://angular.io/guide/lifecycle-hooks, the second sentence is:

> Angular creates it, renders it, creates and renders its children, checks it when its data-bound properties change, and destroys it before removing it from the DOM.

But "it/its" isn't very clear and occurs too many times. How about changing it to:

> Angular creates and renders components and their children, checks when their data-bound properties change, and destroys them before removing them from the DOM.

What do you think? Would that one appeal to you? That file is here: https://github.com/angular/angular/blob/master/aio/content/guide/lifecycle-hooks.md

If you decide to do it, please tag me in your PR. Thank you for your time, too! 🌸

**Comment by kapunahelewong** [comment]
Hey @jordan-amman, I'd like to close this just to keep things tidy. If you'd like to re-open it for any reason, please feel free to do so and to tag me with any questions. 🙂 🌻

**Pull request closed without merging**
