### PR TITLE
fix(devtools): check for all new DI debug APIs before trying to determine resolution path providers

### LINKED ISSUE #52786: devtools ɵgetInjectorMetadata is not a function
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

```

  "dependencies": {
        "@angular/animations": "^16.1.8",
        "@angular/cdk": "^16.1.8",
        "@angular/common": "^16.1.8",
        "@angular/compiler": "^16.1.8",
        "@angular/core": "^16.1.8",
        "@angular/forms": "^16.1.8",
        "@angular/material": "^16.1.8",
        "@angular/platform-browser": "^16.1.8",
        "@angular/platform-browser-dynamic": "^16.1.8",
        "@angular/router": "^16.1.8",
        "material-icons": "^1.13.12",
        "path-browserify": "^1.0.1",
        "roboto-fontface": "^0.10.0",
        "rxjs": "~6.6.0",
        "tslib": "^2.3.0",
        "zone.js": "~0.13.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^16.1.8",
        "@angular/cli": "^16.1.8",
        "@angular/compiler-cli": "^16.1.8",
        "@types/jasmine": "~3.8.2",
        "@types/node": "^16.18.60",
        "autoprefixer": "^10.4.16",
        "jasmine-core": "~3.8.0",
        "karma": "~6.3.4",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage": "~2.0.3",
        "karma-jasmine": "~4.0.1",
        "karma-jasmine-html-reporter": "^1.7.0",
        "postcss": "^8.4.31",
        "prettier": "^3.0.3",
        "tailwindcss": "^3.3.5",
        "typescript": "~4.9.5"
    },

```

-

-

image

-

-

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

_No response_

### Please provide a screenshot if possible [Bug Report only]

```
zone.js:1681 Uncaught TypeError: F(...).ɵgetInjectorMetadata is not a function
    at rt (component-tree.ts:61:20)
    at Jo (component-tree.ts:436:20)
    at De (component-tree.ts:234:7)
    at component-tree.ts:105:50
    at Array.map (<anonymous>)
    at nn (component-tree.ts:104:83)
    at client-event-subscribers.ts:101:21
    at n (same-page-message-bus.ts:41:12)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Zone.runTask (zone.js:173:47)
rt @ component-tree.ts:61
Jo @ component-tree.ts:436
De @ component-tree.ts:234
(anonymous) @ component-tree.ts:105
nn @ component-tree.ts:104
(anonymous) @ client-event-subscribers.ts:101
n @ same-page-message-bus.ts:41
invokeTask @ zone.js:402
runTask @ zone.js:173
invokeTask @ zone.js:483
invokeTask @ zone.js:1631
globalCallback @ zone.js:1674
globalZoneAwareCallback @ zone.js:1695
postMessage (async)
emit @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1
s @ content_script_bundle.js:1
Show 9 more frames
Show less
```

### Please provide the exception or error you saw [Bug Report only]

_No response_

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

_No response_

### Description [Feature Request only]

_No response_

### Proposed solution [Feature Request only]

_No response_

### Alternatives considered [Feature Request only]

_No response_

### PR DESCRIPTION
**Pull request by AleksanderBodurri**
Previously, some versions of Angular 16.1.x that had 3/4 of the new DI debug APIs would enter a code path that required them to have access to the 4th.

Now DevTools checks for the existence of all 4 explicitly before going down this code path.

closes #52786

### CODE REVIEW

**Comment by AleksanderBodurri** [comment]
Most line changes are from the formatter. The only code changes are here.
Screenshot 2023-11-10 at 12 28 45 PM

Screenshot 2023-11-10 at 12 28 58 PM

**Review by dgp1130 — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 3cf18bb6f2798020cbe8633fae79f920cf98816b.

**Comment by NachmanBerkowitz** [comment]
When will the roll out of the fixed dev tools be?

**Comment by dgp1130** [comment]
We just released DevTools 1.0.9 which should contain this fix.

**Pull request closed without merging**
