### PR TITLE
docs: formate ng-container code

### PR DESCRIPTION
**Pull request by danielsogl**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Sure nothing great but the code is not that great formatted.

## What is the new behavior?
Code is now formatted.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by brandonroberts** [comment]
@danielsogl I don't see where this example is being shown publicly.

**Comment by danielsogl** [comment]
But is that a reason to not refactor code?

**Comment by brandonroberts** [comment]
@danielsogl I suppose it will come in handy when if/when we do use it.

**Review by brandonroberts — APPROVED** [review]

**Comment by danielsogl** [comment]
@brandonroberts fixed

**Pull request closed without merging**
