### PR TITLE
docs(aio): added link to ngRuAir podcast

### PR DESCRIPTION
**Pull request by irustm**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]

**Comment by kapunahelewong** [comment]
@irustm could you rebase and tag me when you're ready? I'd like to help you get this in. :)

**Comment by irustm** [comment]
@kapunahelewong ping)

**Comment by kapunahelewong** [comment]
Hi @irustm, thanks for the ping. It still looks like the PR is behind. Here's what I'm referencing:
image

If we can get it up-to-date, hopefully it will pass all the tests and we can mark it for merge. In case you'd find a reference helpful, here are my [own notes on rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase). And please do tag me again with any questions or whenever you're ready. Thank you!

**Comment by irustm** [comment]
@kapunahelewong thanks! I am update

**Review by kapunahelewong — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Thank you, @irustm!!

**Pull request closed without merging**
