### PR TITLE
refactor(devtools): migrate devtools to prettier formatting

### PR DESCRIPTION
**Pull request by sheikalthaf**
Added html and scss to ng-dev formatter. This will reduce the formatting changes coming in PRs.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: dev-infra

This is fine from a dev-infra perspective, up to the devtools folks on if they would like to make this change for the formatting itself.

**Review by dgp1130 — APPROVED** [review]

**Comment by dgp1130** [comment]
This sounds fine to me, we can try to merge this once the commit freeze lifts to reduce the potential of merge conflicts with other changes.

**Comment by dgp1130** [comment]
I retargetted this to `minor` now that v19 is out. This doesn't apply cleanly to the `patch` branch, so we should consider formatting `19.0.x` as well just to reduce conflicts in future PRs that target `patch`.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit f8e51194355914fb766bfe9bd0aca047bc7ac7b3.

The changes were merged into the following branches: main

**Comment by AndrewKushnir** [comment]
> we should consider formatting 19.0.x as well just to reduce conflicts in future PRs that target patch.

+1, that'd be great to have a version of this change for the `19.0.x` branch to avoid conflicts with future changes.

**Comment by sheikalthaf** [comment]
> > we should consider formatting 19.0.x as well just to reduce conflicts in future PRs that target patch.
> 
> +1, that'd be great to have a version of this change for the `19.0.x` branch to avoid conflicts with future changes.

@AndrewKushnir so do i need to create another PR for `19.0.x` branch and format the code right?

**Comment by sheikalthaf** [comment]
I create another PR #58766 for branch `19.0.x` and formatted the devtools folder.

**Pull request closed without merging**
