### PR TITLE
build: update to Bazel 0.27

### PR DESCRIPTION
**Pull request by alexeagle**
This fixes managed directories so it's usable for us

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by gregmagolan — APPROVED** [review]
🎉

**Review by gregmagolan — COMMENTED** [review]
...

**Review by gregmagolan — CHANGES_REQUESTED** [review]
Still have an issue if you rm -rf node_modules and then manually yarn install and run the bazel build. Repository rule doesn't run because node_modules is there but there are no BUILD files generated so the build fails.

See https://github.com/bazelbuild/rules_nodejs/issues/802#issuecomment-501491707 and https://github.com/bazelbuild/bazel/issues/8487#issuecomment-501492745 for more info.

**Comment by filipesilva** [comment]
@gregmagolan this problem sounds super easy to get into. Reading through the options in https://github.com/bazelbuild/rules_nodejs/issues/802#issuecomment-501491707, I don't quite understand how 1 can work on this repository, mas we have Bazel installed through node_modules. Option 2 sounds like something that people would end up doing anyway as a general solution to a lot of weird Bazel problems.

**Pull request closed without merging**
