### PR TITLE
docs: change screenshot in setup-local for version 9

### PR DESCRIPTION
**Pull request by donhuvy**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by donhuvy** [comment]
@kapunahelewong , I follow your guide at https://github.com/angular/angular/pull/33982 . Thank you, long time I don't use `rebase`, you help me remember this.

**Review by IgorMinar — APPROVED** [review]
looks good to me. but can you please compress the image? it's huge right now. thanks!

maybe @kapunahelewong can help with that?

**Comment by IgorMinar** [comment]
huge == 370% bigger than the original. it's expected that it's going to be bigger because the content is much more busy, but it seems too big right now.

**Comment by kapunahelewong** [comment]
Hey, @donhuvy, I tried it in Affinity Photo and couldn't get it below about 51kb. I tried [https://tinypng.com/](https://tinypng.com/) though and got it down to 21kb. How small are you able to get yours and what method are you using?

**Comment by kapunahelewong** [comment]
Hey, you got that image a lot smaller, @donhuvy! Well done! So the next step is to squash. Doing [a rebase squash](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) should get it down to one commit and get rid of the merge commits. Could you try that? I'm happy to help if that's not your usual workflow.

**Comment by kapunahelewong** [comment]
Hi @donhuvy! I've rebased, squashed, and amended the commit message because I'd love to get this merged. Would you like to check to make sure I've done everything as you intend? When you're ready, will you tag me? Thanks again for this!

**Review by kapunahelewong — APPROVED** [review]

**Comment by donhuvy** [comment]
@kapunahelewong thank you!  I also would love to get this merged.

**Pull request closed without merging**
