### PR TITLE
docs: change host preference in style guide 06-03

### PR DESCRIPTION
**Pull request by rlmestre**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #52561

## What is the new behavior?
The style guide was updated to reflect the new preference as described in:
- https://angular.dev/guide/components/host-elements
- angular/components [CODING_STANDARDS.md](https://github.com/angular/components/blob/main/CODING_STANDARDS.md#host-bindings)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
This PR is a redo of #52816

### CODE REVIEW

**Comment by rlmestre** [comment]
cc @twerske @jessicajaniuk

this is a redo of #52816 which got messed up during rebase! sorry for possibly having spammed a few folks 😬

**Comment by JeanMeche** [comment]
Hi Rafael, can you have a look at that failing linting job. 

The commit message has an invalid scope. We would be find without any for a docs commit !

**Comment by JeanMeche** [comment]
Can you squash that 2nd commit, we'd like this change to be a single commit.

**Comment by jelbourn** [comment]
Hey, thanks for taking the initiative on this having seen the beta content on angular.dev

I would probably want to hold off on landing this just yet; it's my hope to do a more comprehensive update of the style guide to land when angular.dev exits beta. Even though this isn't a code change, it's something I'm inclined to include as part of a major semver release

**Comment by JeanMeche** [comment]
I'll close the PR a keep a reference in the #54284 umbrella issue. 
Thank you for you suggestions, we'll keep them warm until we land the rewrite of the style guide !

**Pull request closed without merging**
