### PR TITLE
Router standalone directives

### PR DESCRIPTION
**Pull request by atscott**
See individual commits

### CODE REVIEW

**Comment by atscott** [comment]
[presubmit](https://fusion2.corp.google.com/presubmit/tap/459834109/OCL:459834109:BASE:460779569:1657740864085:1748f001;groups=PossiblyNewlyFailing/targets)

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by atscott** [comment]
[TGP](https://fusion2.corp.google.com/presubmit/tap/459834109/OCL:459834109:BASE:461020749:1657825873994:ac6891af;groups=PossiblyNewlyFailing/targets) after some fixes. Should run regular presubmit as a sanity check

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api, size-tracking

**Comment by atscott** [comment]
[sanity presubmit](https://fusion2.corp.google.com/presubmit/tap/459834109/OCL:459834109:BASE:461027078:1657827691625:5b24e231/targets)

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 26ea97688cba5850588d8da83abaf8b539577241.

**Pull request closed without merging**
