### PR TITLE
docs: fix spelling

### PR DESCRIPTION
**Pull request by jayvdb**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No
- [x] Very very minor ones, which I can revert if deemed too breaking in nature

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
@jayvdb LGTM and thanks for the fixes. It looks like some files need to be formatted. You can do this by running `yarn ng-dev format changes`

**Review by dgp1130 — APPROVED** [review]
Thanks for all these fixes! I see at least a couple in there which were probably my fault. 🙈

**Comment by jayvdb** [comment]
Rebased to resolve conflict in `packages/core/src/application_ref.ts`.

`$ yarn ng-dev format files packages/compiler-cli/src/ngtsc/reflection/src/host.ts` keeps toggling between two indent positions.  is that a known bug?

On the last test run, `//packages/router:router_api                                             FAILED in 2 out of 2 in 14.7s` - i'm looking into reproducing this locally.

**Comment by atscott** [comment]
@jayvdb The router API test is meant to check for public API changes. Since the argument of a public function got its spelling changed, you'll have to regenerate the API golden with `yarn bazel run //packages/router:router_api.accept`. This doesn't constitute a true public API change, but the golden file has to be updated nontheless.

**Review by jessicajaniuk — APPROVED** [review]
Thaks for teh fixess! LTGM!

reviewed-for: fw-core, fw-animations, fw-upgrade

**Comment by jessicajaniuk** [comment]
@jayvdb You'll need to do 2 things to get this green. Fetch and rebase on main, as the sha fix for that test suite is there. You'll also need to run `yarn lint` and have it reformat the one file. That should do it.

**Comment by jessicajaniuk** [comment]
@jayvdb I added a fixup that fixes the lint and rebases to main.

**Comment by jessicajaniuk** [comment]
@jayvdb After playing around with this, it looks like our linter is having issues. I've removed the fixup commits since at present the linter seems to fail for that file regardless of the format changes.

**Comment by jayvdb** [comment]
I had mentioned the linter problem earlier at https://github.com/angular/angular/pull/46713#issuecomment-1176824057

I don't mind if this PR has to wait until the linter gets fixed.  It shouldn't be to hard to find what part of that file is triggering this toggling behaviour.

**Comment by jessicajaniuk** [comment]
@jayvdb OK, so the issue is actually with the file containing a reserved word and clang getting confused. We're just going to merge since that issue is with clang and not us.

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-forms, fw-migrations, fw-core, fw-common

**Comment by jessicajaniuk** [comment]
Caretakers note: This doesn't affect functionality and is only spelling fixes. I'm going to merge this.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit c14c701775c900ce9ac8781c08fc76da067910c5.

**Comment by jessicajaniuk** [comment]
@jayvdb This had merge conflicts with `14.0.x`. I switched to `target: minor` to get this in to `main`. If you'd like to have it land in `14.0.x` as well, please create a second PR targeting that branch, and we'll land it.

**Pull request closed without merging**
