### PR TITLE
docs: fix transpiles link in dependency injection

### PR DESCRIPTION
**Pull request by beegotsy**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

transpiles link in dependency injection was not working, there was a double bracket typo
Issue Number: N/A

## What is the new behavior?
transpiles link is now working

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by beegotsy** [comment]
I signed it!

**Review by jenniferfell — APPROVED** [review]

**Comment by jenniferfell** [comment]
@beegotsy I apologize for not noticing this yesterday. Would you please change your commit message to: 

`docs: fix transpiles link in dependency injection`

The Angular team asks that all commit messages follow the guidelines here: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

If you need more information about how to change commit messages, I recommend this GitHub help page: https://help.github.com/articles/changing-a-commit-message/

Thanks!

**Comment by beegotsy** [comment]
Sorry, I apologize for the mistake, fixed it

**Review by mhevery — APPROVED** [review]

**Comment by jasonaden** [comment]
@beegotsy Thanks for the PR. The commit message actually wasn't updated. I think you changed the PR title, but not the commit itself.

I went ahead and made that change for you and force pushed back to your PR. Once everything is green again, we can get this merged. The commit message issue was causing a lint failure in CI.

**Pull request closed without merging**
