### PR TITLE
Backport of incremental correctness fixes to patch branch

### PR DESCRIPTION
**Pull request by alxhub**

### CODE REVIEW

**Review by ayazhafiz — APPROVED** [review]
LGTM for language service

**Comment by mhevery** [comment]
merged as adeeb84a35

**Comment by rekna1** [comment]
Will Angular 10 get this fix as well ? (Have some dependencies that does not allow me to update to 11 yet)

**Comment by mhevery** [comment]
No, we usually usually port only security fixes to older versions.

**Comment by rekna1** [comment]
I'm not very happy with that answer ... I can understand you don't update older versions for ever, but 11 was only released very very recently. You can't expect everyone to upgrade within a month and also, some dependencies need time to upgrade as well...

**Comment by sebastianvog** [comment]
Is there a workaround for people being on 10 and running into this issue? We can't also be on 11 yet, because of dependencies that are still working on supporting 11. For larger projects it can be difficult to keep up and we would appreciate some/more fixes being backported to the most recent LTS release.

**Pull request closed without merging**
