### PR TITLE
refactor(platform-browser): remove deprecated `BrowserTransferStateModule` symbol

### PR DESCRIPTION
**Pull request by AndrewKushnir**
The `TransferState` class was updated in v14 in a way that the `BrowserTransferStateModule` was no longer required. The `BrowserTransferStateModule` was deprecated in v14.1 and it's currently empty. This commit removes the `BrowserTransferStateModule`.

BREAKING CHANGE: The deprecated `BrowserTransferStateModule` was removed, since it's no longer needed. The `TransferState` class can be injected without providing the module. The `BrowserTransferStateModule` was empty starting from v14 and you can just remove the reference to that module from your applications.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring

## Does this PR introduce a breaking change?

- [x] Yes, the `BrowserTransferStateModule` was removed as no longer needed, see commit description.
- [ ] No

### CODE REVIEW

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-core, public-api

**Comment by AndrewKushnir** [comment]
Important note: this is a cherry-picked commit from PR that @JeanMeche created: https://github.com/angular/angular/pull/49674. The reason for extracting this commit is that we want to avoid extra complexity of having a schematic, since the migration is trivial (just drop the module reference) and since the module was deprecated 2 major version ago, we expect that a lot of apps already removed this symbol anyway.

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:522112676:BASE:522112716:1680720341945:61f340c5).

**Comment by AndrewKushnir** [comment]
@dylhunn yeah, it'd be great to land it before the release today. Running a presubmit now (though it should mostly be a noop since there are no references to the `BrowserTransferStateModule` symbol in g3).

**Comment by dylhunn** [comment]
Presubmit looks good.

**Comment by AndrewKushnir** [comment]
**Caretaker note**: presubmit looks good, this PR is ready for merge.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 9bd9a11f4e21e5a7cc9da18f150f6dd520e7cd1e.

**Pull request closed without merging**
