### PR TITLE
fix(platform-browser): Prevent closure compiler from removing hammer EVENT_NAMES properties

### PR DESCRIPTION
**Pull request by jermowery**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

#16701

**What is the new behavior?**

The map is no longer reduced to nothing

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jasonaden** [comment]
LGTM

@vicb or @tbosch quick one to review.

**Review by tbosch — CHANGES_REQUESTED** [review]
I don't think this is the right fix. This change relies on TS producing side effects that closure cannot analyze anymore. I.e. why is closure removing the flags here and not somewhere else?

A better fix would be either to add a closure specific comment, or investigate the closure flags that are used.

@alexeagle  Do you know mere here?

**Comment by alexeagle** [comment]
@jermowery sent me an example:
This is the code at head when compiled: http://shortn/_HFX4tgoraq
And this is with the change: http://shortn/_tFKZduE99P
which shows this workaround with computed properties does solve the issue.

I suspect there's a closure bug here, it should not remove quoted properties on an object. But I'm fine with merging this to unblock gestures for closure compiler users.

**Comment by jermowery** [comment]
Is this unblocked?

**Comment by tbosch** [comment]
the problem here is that doing this will prevent tools like uglify from removing this in case it actually isn't used. Independent on whether we merge this or not, we need a test.

@alexeagle could you give guidance on how to add a test to https://github.com/angular/angular/tree/master/integration

**Comment by tbosch** [comment]
Regarding uglify: The version with quoted properties results in this (after TypeScript):
```
var EVENT_NAMES = (_a = {},
    _a['swipe'] = true,
    _a);
var _a;
```

@mprobst Isn't there a closure compiler hint to prevent this property removal?

**Comment by mprobst** [comment]
You can put an `/** @export */` on each property, though that only works if you have the right Closure Compiler flags. Alternatively you can write a `declare interface X { prop1: string, prop2: string; ... }` and tsickle will generate externs that prevent the renaming. The latter is probably the more robust solution.

**Comment by alexeagle** [comment]
Note that the tsickle externs generation is only hooked up in the google3
tsc_wrapped right now, not the external one.

**Comment by splincode** [comment]
@jermowery what is the status of your pull request? is it still relevant? please fix conflicts if they exist

**Comment by jermowery** [comment]
Deleting this pull request as it is no longer needed see the issue for details

**Pull request closed without merging**
