### PR TITLE
build: remove vendored Babel typings

### PR DESCRIPTION
**Pull request by alexeagle**
These were getting included in the @angular/localize package.
Instead, patch the upstream files to work with TS typeRoots option

See bazelbuild/rules_nodejs#1033

### CODE REVIEW

**Comment by alexeagle** [comment]
@petebacondarwin  looks like some version mismatch - the now-removed README didn't say where you vendored the typings from so I think the type errors are because this now brings in the latest ones.

I'll let you take over the PR, let me know if you need more help!

**Review by petebacondarwin — APPROVED** [review]
LGTM (especially as I have now had a hand in it :-) )

**Comment by petebacondarwin** [comment]
Caretaker: CLA is signed by both committers

**Review by IgorMinar — APPROVED** [review]

**Comment by matsko** [comment]
Unfortunately this had to be reverted because it was causing the windows tests on CI to fail.

**Comment by matsko** [comment]
Closed in favor of https://github.com/angular/angular/pull/33226

**Pull request closed without merging**
