### PR TITLE
feat(upgrade): support the `$doCheck()` lifecycle hook in `UpgradeComponent`

### PR DESCRIPTION
**Pull request by gkalpak**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
The `$doCheck()` lifecycle hook is ignored in upgraded components.

**What is the new behavior?**
The `$doCheck()` lifecycle hook works as expected in upgraded components.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by chuckjaz** [comment]
Please change the commit message prefix to "feat(upgrade):"

**Comment by gkalpak** [comment]
@chuckjaz, should it be `feat(upgrade)` or `feat(upgrade/static)` (since it is about `upgrade/static`)?

**Comment by chuckjaz** [comment]
We are standardizing identifier in the parens must be a module so the reference needs to be upgrade.

I am going to work on a tool to enforce this on commit and in CI probably next week or after.

**Comment by vicb** [comment]
@gkalpak @petebacondarwin what is the status here ?

**Comment by gkalpak** [comment]
It needs to be reviewed :smiley:

**Comment by petebacondarwin** [comment]
Great work @gkalpak.

**Review by petebacondarwin — APPROVED** [review]

**Pull request merged**
