### PR TITLE
feat(zone.js): remove legacy browsers support

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Drop support for legacy browsers.
- IE11
- Android 4.4, 4.5
- Old Safari
- Old Firefox

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Breaking changes:

- `zone-legacy` bundle is removed.
- `zone.js` will not support the browsers above.
- `registerElement` will not be patched.

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Reviewed-for: dev-infra

**Comment by JiaLiPassion** [comment]
It seems the `presubmit` failed, maybe some apps in `g3` still rely on the `legacy patch`?

**Comment by JiaLiPassion** [comment]
@AndrewKushnir , it seems this PR breaks `g3`, could you help me to check the errors? Thank you.

**Comment by AndrewKushnir** [comment]
@JiaLiPassion I took a quick look and it seems like removing `packages/zone.js/lib/browser/define-property.ts` file causes the issue.

I see errors in the logs like this:
```
Error: <spyOnProperty> : db is not declared configurable
```
The code looks like:

```
  const mockWindow = window;
  Object.defineProperty(mockWindow, 'db', {
    set: (db: unknown) => {},
    get: () => undefined,
  });
  const windowSpy = spyOnProperty(mockWindow, 'db', 'set'); // errors here...
```

Is it possible to keep it for now? In this case I can run another test in Google's codebase and we can land the PR if everything looks good. After that, we can have a separate PR that removes `define-property.ts` (if it's no longer needed) and do some cleanup in Google's codebase to land the change.

Thank you.

**Comment by JiaLiPassion** [comment]
@AndrewKushnir , thank you for the information, I will update the PR.

**Comment by AndrewKushnir** [comment]
[TGP](https://test.corp.google.com/OCL:476249809:BASE:476251893:1663898815387:27d50c04).

**Review by devversion — APPROVED** [review]

**Pull request closed without merging**
