### PR TITLE
build: preparation for primary branch rename in the Angular repos

### PR DESCRIPTION
**Pull request by devversion**
Preparation for the framework repo as outlined our planning
document.

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

reviewed-for: size-tracking

**Review by josephperrott — APPROVED** [review]
LGTM

Approved-for: global-approvers

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: global-approvers

**Comment by devversion** [comment]
Caretaker note: I'm unable to remove the pending unneeded reviews.

**Comment by dylhunn** [comment]
Merging into major; this has conflicts with 13.3.x. Let me know if you'd like to do a patch port.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 0231a363fea7e10335edc8820e196dab4562f96b.

**Pull request closed without merging**
