### PR TITLE
docs(changelog): remove unnecessary entries

### PR DESCRIPTION
**Pull request by cerkiner**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Unnecessary, repeating entries in the changelog

Issue Number: N/A

## What is the new behavior?
Remove unnecessary, repeating entries in the changelog

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
The earliest mention of each entry is kept and duplicate entries mentioned in newer versions are removed.

### CODE REVIEW

**Review by hanna1ritu — APPROVED** [review]

**Comment by cerkiner** [comment]
Is anyone interested in this fix? @filipesilva @atscott

**Comment by cerkiner** [comment]
Is anyone interested in this fix? @kara

**Comment by kapunahelewong** [comment]
Hi @cerkiner, thank you for this PR. I'm sorry for the delay. We are working on catching up with the issues and PRs backlog. I have added the appropriate labels, including `PR action: review`, which puts it in the queue for engineering to review. Just so you know, ultimately you will need to [rebase](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase). If that's not part of your regular workflow, I can help you with it. If you have any questions in the meantime, just tag me.

**Review by IgorMinar — CHANGES_REQUESTED** [review]
the second commit looks good, but the first one has removals which I don't understand.

Can you please explain what key you used to determine which entries to keep and which to remove?

Also, can you please follow our commit message convention and ensure that the CI lint checks pass? thanks

**Review by IgorMinar — DISMISSED** [review]
Reviewed-for: public-api

**Comment by cerkiner** [comment]
@IgorMinar I first realised there are duplicate entries for same changes and fixes, while I am fixing the issue, I realised there are some titles with no entries. 

[6972401](https://github.com/angular/angular/pull/36264/commits/6972401923091e464d7c8010448726e7e682cde9) Removes duplicate entries by keeping the earliest mention of each entry.
[d24de59](https://github.com/angular/angular/pull/36264/commits/d24de5915524ef1f977616228201b106933bef4f) Removes the empty titles

**Comment by jelbourn** [comment]
@cerkiner would you mind squashing your changes into just two commits? 
```markdown
docs(changelog): remove duplicate entries

Remove duplicate entries in the changelog, keeping only the earliest instance of changes that appear multiple times.
```
```markdown
docs(changelog): remove empty sections

The changelog contains some empty sections (such as `### Bug Fixes`). This change removes these empty sections.
```

**Comment by cerkiner** [comment]
@jelbourn Thank you for the copy, I used it exactly as is. I also applied the same changes to recent changelog entries.

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: global-approvers

**Pull request closed without merging**
