### PR TITLE
build: enable the branch manager action in the repo

### PR DESCRIPTION
**Pull request by josephperrott**
Set up the branch manager action to automatically monitor if a pull request is able to merge into its target branches

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM, but have you considered splitting into different workflows- or is there a downside? (the benefit would be clearer triggers)

**Comment by josephperrott** [comment]
I have considered it, the downside is that we would create even more "pollution" of the github statuses on a pull request.  With having them all be `DevInfra` they at least show together nicely.

**Comment by devversion** [comment]
Wouldn't it still show a status per job? (or do I miss something)

image

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit ad8ccedeca82a834802ccd8d4720ab7550c40c64.

**Pull request closed without merging**
