### PR TITLE
fix(HtmlParser): allow ng-content elements regardless the namespace

### PR DESCRIPTION
**Pull request by vicb**
relates to #5547

### CODE REVIEW

**Comment by vicb** [comment]
Should be rebased once #5745 is in (`splitHtmlTagNamespace ` is renamed)

**Comment by IgorMinar** [comment]
@vicb is this good to be merged? if so, please apply the label

**Comment by vicb** [comment]
As per my last comment, I'll apply the label when 5745 is in and this is rebased

**Comment by vicb** [comment]
merged into #5745

**Pull request closed without merging**
