### PR TITLE
chore(changelog): fix formatting for alpha.49 

### PR DESCRIPTION
**Pull request by valorkin**

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
nit: commit message would be better as `docs(changelog): fix formatting for alpha.49` but it can go as-is as well

**Comment by valorkin** [comment]
@pkozlowski-opensource https://github.com/angular/angular/pull/4724
last time was asked to use `chore` by @PascalPrecht :)

**Comment by valorkin** [comment]
@pkozlowski-opensource commit and PR renamed
@vicb title added

**Comment by vicb** [comment]
Thanks !

**Pull request closed without merging**
