### PR TITLE
docs(aio): add Made with Angular

### PR DESCRIPTION
**Pull request by lalithpolepeddi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Add [Made with Angular](https://www.madewithangular.com/), a showcase of web apps built with Angular, to the [Resources page](https://angular.io/resources). CC @StephenFluin 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by StephenFluin — CHANGES_REQUESTED** [review]
To adhere with our branding guide, can you update the favicon at the top to use the new logo, and call any applications `AngularJS` if they are on 1.X?

**Comment by lpolepeddi** [comment]
Thanks @StephenFluin. Made the following changes to [Made with Angular](https://www.madewithangular.com/):
1. Changed the favicon to be the one color logo from the [presskit](https://angular.io/presskit)
1. Displaying `AngularJS` when the version is 1.x and `Angular` when the version is 2.x +

**Comment by StephenFluin** [comment]
@lpolepeddi I thought this was already approved. Can you rebase the PR and then I'll approve?

Thanks!

**Comment by StephenFluin** [comment]
I think you'll want to squash these too.

**Comment by lpolepeddi** [comment]
@StephenFluin I think I squashed the commits. Please let me know if this is what you were expecting.

**Review by StephenFluin — APPROVED** [review]

**Review by StephenFluin — APPROVED** [review]

**Pull request closed without merging**
