### PR TITLE
build(docs-infra): upgrade cli command docs sources to 70a36d5df

### PR DESCRIPTION
**Pull request by gkalpak**
[Changed files](https://github.com/angular/cli-builds/compare/b50950b97...70a36d5df):
- help/add.json
- help/build.json
- help/config.json
- help/e2e.json
- help/generate.json
- help/lint.json
- help/new.json
- help/run.json
- help/serve.json
- help/test.json
- help/xi18n.json

### CODE REVIEW

**Review by IgorMinar — COMMENTED** [review]
What branch is 70a36d5df on? We shouldn't be pulling from cli master and merging it into framework patch branch. Can you please clarify?

**Review by petebacondarwin — APPROVED** [review]

**Comment by hansl** [comment]
Why shouldn't you pull from master for master, latest minor for minor? We're about to release 7.1 and might be decoupled from Angular itself.

**Comment by hansl** [comment]
Also, the commits (there were 10 IIRC) that contains the docs changes were not merged onto the patch.

**Comment by gkalpak** [comment]
Last time I asked, there were no `cli-builds` for 7.x (only for master) and there wasn't a final plan on how to handle cli docs updates.
My previous PRs (e.g. #26741, #26915) were merged on both master and patch.

We need to decide what cli version do the docs on each `*.angular.io` page correspond to and also mention that in the docs imo (so people know which cli version the docs apply to).

**Pull request closed without merging**
