### PR TITLE
refactor: removing unused import in core & animations

### PR DESCRIPTION
**Pull request by aanchal88**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by alan-agius4** [comment]
Can you please change the commit message type to `refactor` as this change does not effect docs?


Thanks.

**Comment by aanchal88** [comment]
Hii @alan-agius4 , updated the changes. Please have a look.

**Comment by alan-agius4** [comment]
CI is failing due to incorrect commit message.

```
Examining 1 commit(s) in the provided range: a5bd5ddbaace240610f0fef537ca759ab7241e35..8480899ff484a7592437856030e9ff3e599a5cb1
✘  Invalid commit message
refactor: remove unused imports
  Error:
    The commit message body does not meet the minimum length of 20 characters
  
  The expected format for a commit is: 
  <type>(<scope>): <summary>
  
  <body>

```

**Comment by JeanMeche** [comment]
You still have the same issue, your commit message does not follow the guidelines. 

`refactor` requires a scope. `core` for example.

**Comment by alan-agius4** [comment]
@JeanMeche, the refactor commit message does not require a scope.

**Comment by aanchal88** [comment]
Hii @alan-agius4 , CI is succeeded now. Please have a look.

**Comment by JeanMeche** [comment]
The commit mesage is not correct you changed it back to `docs: ...`. 

It should be something like: 

```
refactor: remove unused imports. 

Removing unused import in core & animations. 
```

**Comment by jessicajaniuk** [comment]
@aanchal88 The commit message is fine, but there's no commit message body. If you can update that, it should be safe to merge.

**Comment by jessicajaniuk** [comment]
Closing this since no updates. Please open a new PR if you want this to land.

**Pull request closed without merging**
