### PR TITLE
refactor(benchmarks): remove imports from 'angular2/angular2'

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**

### CODE REVIEW

**Comment by jeffbcross** [comment]
Looks like flakes on Travis?

**Comment by jeffbcross** [comment]
LGTM but assigning back to @pkozlowski-opensource to keep track of Travis.

**Comment by pkozlowski-opensource** [comment]
YEp, this Travis failure was a flake, let's get this one in.

**Comment by jeffbcross** [comment]
@pkozlowski-opensource I dunno, the same two jobs failed both times.

**Comment by pkozlowski-opensource** [comment]
@jeffbcross hmm, I had it green at one point today and Travis seems to time out. Let me restart the travis job once again, if it fails I will investigate.

**Comment by vsavkin** [comment]
Could you fix travis?

**Comment by pkozlowski-opensource** [comment]
Sent a simpler patch, TravisCI seems to be happy now.

**Pull request closed without merging**
