### PR TITLE
docs: describe your change...

### PR DESCRIPTION
**Pull request by danday74**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by danday74** [comment]
> I signed it!

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
thanks for the PR! @danday74

**Comment by IgorMinar** [comment]
caretaker note: unrelated ci failure

**Comment by alfaproject** [comment]
Are you going to accept this git commit message? o:

**Pull request closed without merging**
