### PR TITLE
docs: add damian sire to GDE resources

### PR DESCRIPTION
**Pull request by damiansire**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by damiansire** [comment]
I have just signed the CLA

**Comment by JeanMeche** [comment]
You probably didn't it with the right email. The commit was authored with `dam*****re​@hotmail.com`.

**Comment by damiansire** [comment]
Thanks @JeanMeche! I've updated the email address to match the one on the signed CLA

**Review by MarkTechson — APPROVED** [review]
LGTM and welcome!

**Comment by JeanMeche** [comment]
Hi Damian, with the release of v18 coming soon, angular.io entered maintenance mode and won't accept updates. 
On the new angular.dev site, we directly pointing to global GDE directory, so this change isn't needed anymore. 

Thank you for your understanding.

**Pull request closed without merging**
