### PR TITLE
docs(security): mark the various DomAdapters as unsafe.

### PR DESCRIPTION
**Pull request by mprobst**
Part of #8511.

### CODE REVIEW

**Comment by mprobst** [comment]
@koto FYI

**Comment by IgorMinar** [comment]
`*Adapter` symbols are not public API, so none of these changes will be published anywhere on angular.io

**Comment by mprobst** [comment]
I think it might still make sense to mark the code with @security, in case somebody reads the source itself?

**Comment by rjamet** [comment]
The warning is useful, and it might help set the example: if you manage to get third party developers to follow that lead, that would be awesome. So even when that's not going to surface in docs, I'd be in favor of adding these.

**Comment by IgorMinar** [comment]
@mprobst sure but can you then reword the warning to target Angular framework developers rather than application developers?

**Comment by mprobst** [comment]
@IgorMinar done.

**Comment by IgorMinar** [comment]
lgtm. please squash.

**Comment by mprobst** [comment]
@IgorMinar apparently I lost collaborator rights on angular/angular (what's up with that?). Could you re-add me, and/or merge?

**Comment by mprobst** [comment]
Squashing done.

**Comment by kara** [comment]
@mprobst  Is this ready to merge or does it still have cleanup?  Conflicting labels.

**Comment by IgorMinar** [comment]
ready

**Pull request merged**
