### PR TITLE
docs: fix builder section of generated angular.json file for libs

### PR DESCRIPTION
**Pull request by IxquitilisSaid**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

On the Getting started section, the generated angular.json snippet shows:

```
"builder": "@angular-devkit/build-ng-packagr:build",
```

when it should be:

```
"builder": "@angular-devkit/build-angular:ng-packagr",
```

Issue Number: #39887

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by petebacondarwin** [comment]
Please can you rebase this on top of the latest commit of the `master` branch? Thanks!

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Can you also please add `Closes #39887`  as commit message footer?

Thanks.

**Comment by IxquitilisSaid** [comment]
Hopefully I didn't mess up the rebase 😞

**Review by alan-agius4 — APPROVED** [review]
Thanks, LGTM

**Pull request closed without merging**
