### PR TITLE
ci(aio): fix PR preview pre-verification

### PR DESCRIPTION
**Pull request by gkalpak**
With fdfeaaf, `deploy-staging.sh` has been changed to run rght after building (to make the preview available as early as possible), but failed to account that the pre-verification script (that runs before deploying previews) wasn't built. Previously, this wasn't an issue (coincidentally), because the deployment was run after `test.sh`, which happened to build the necessary scripts in `aio-builds-setup`.

This bug in fdfeaaf would normally fail the build (so we would notice), but didn't due to another bug:
Previously, `aio/aio-builds-setup/scripts/travis-preverify-pr.sh` was supposed to exit with 1 if a PR did not meet the preconditions and 2 if an error occurred during pre-verification.
It relied on the exit codes of the node script that did the actual work, but didn't account for errors that would be thrown in the `sh` script itself (e.g. if the node script was not available). This caused such errors to appear as non-verified PRs, instead of real errors that should fail the build.
(This has now changed, so that 2 means non-verified PR and 1 (or any other exit code) designates an error.)

##
<sub>(This PR also includes a small refactoring commit, just because...)</sub>

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]

**Comment by gkalpak** [comment]
(Fixed `aio/aio-builds-setup/scripts/*` not being executable.)

**Comment by gkalpak** [comment]
This now passes on Travis (and creates previews - yay!), but for some reason the PWA score results aren't printed 😕: https://travis-ci.org/angular/angular/jobs/231493355#L1067

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Something is still not right: https://travis-ci.org/angular/angular/jobs/231543509#L1097

**Comment by gkalpak** [comment]
Fixed. PTAL.

**Review by petebacondarwin — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]

**Pull request merged**
