### PR TITLE
fix(upgrade): Address Trusted Types violations in @angular/upgrade

### PR DESCRIPTION
**Pull request by bjarkler**
Angular applications that are AngularJS hybrids are currently unable to adopt Trusted Types due to violations eminating from an innerHTML assignment in the @angular/upgrade package. This commit allows developers of such applications to optionally ignore this class of violations by configuring the Trusted Types header to allow the new angular#unsafe-upgrade policy.

Note that the policy is explicitly labeled as unsafe as it does not in any way mitigate the security risk of using AngularJS in an Angular application, but does unblock Trusted Types adoption enabling XSS protection for other parts of the application.

The implementation follows the approach taken in @angular/core; see packages/core/src/util/security.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The @angular/upgrade package emits Trusted Types violations, blocking adoption of the security feature.

Issue Number: N/A

## What is the new behavior?

The Trusted Types violations can be ignored by allowing the new `angular#unsafe-upgrade` Trusted Types policy. There are no functional changes.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by bjarkler** [comment]
[Presubmit (TGP)](https://test.corp.google.com/OCL:661331807:BASE:664896221:1724091811064:4be88b7f).

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Review by thePunderWoman — APPROVED** [review]
LGTM

**Comment by alxhub** [comment]
This PR was merged into the repository by commit c9d90786d0a6421bbb21b9d1649d031b34e3fa5d.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
