### PR TITLE
fix(localize): update ng add schematic to support Angular CLI version 15

### LINKED ISSUE #47677: `$localize` is not found after `ng add` with cli v15.0.0-next.4 and ng v15.0.0-next.5
### Command

add

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.5

### Description

Angular v15.0.0-next.5 contains the fix from @alan-agius4 to properly add the `@angular/localize` polyfill in a CLI app now that the `polyfills.ts` file is gone. https://github.com/angular/angular/commit/400a6b5e3707f3939d84c659a115b75ef15d2c09

The polyfill is added when running `ng add`, but it looks like using `$localize` still doesn't work.

```
Error: src/app/app.component.ts:9:11 - error TS2304: Cannot find name '$localize'.

9   title = $localize`i18n-next`;
```

### Minimal Reproduction

```
npx @angular/cli@15.0.0-next.4 new i18n-next --defaults
cd i18n-next
npm i
ng add @angular/localize@15.0.0-next.5 --skip-confirmation
```

then update `app.component.ts` with:
```ts
title = $localize`i18n-next`;
```

and run:
```
ng extract-i18n --output-path src/locale/
```

The same repro using the stable release of the CLI and fwk works out of the box.

### Exception or Error

```text
Error: src/app/app.component.ts:9:11 - error TS2304: Cannot find name '$localize'.

9   title = $localize`i18n-next`;
```

### Your Environment

```text
Angular CLI: 15.0.0-next.4
Node: 16.17.0
Package Manager: npm 6.14.17
OS: darwin arm64

Angular: 15.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0-next.4
@angular-devkit/build-angular   15.0.0-next.4
@angular-devkit/core            15.0.0-next.4
@angular-devkit/schematics      15.0.0-next.4
@angular/cli                    15.0.0-next.4
@schematics/angular             15.0.0-next.4
rxjs                            7.5.7
typescript                      4.7.4
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
Prior to this, the `@angular/localize/init` was added as a polyfill which caused the `@angular/localize` types not to be included in the TypeScript program which caused errors such as the below:

```
Error: src/app/app.component.ts:9:11 - error TS2304: Cannot find name '$localize'.
```

With the recent changes in the CLI (https://github.com/angular/angular-cli/pull/24032), adding `@angular/localize/init` as polyfil or in the `main.server.ts` is no longer necessary. Instead we add this as a TypeScript type. When users are running in JIT mode, we add `@angular/localize/init` as an additional entrypoint.

This change also exposes the `$localize` method as a global when importing `@angular/localize`.

Closes #47677

### CODE REVIEW

**Comment by alan-agius4** [comment]
Blocked on https://github.com/angular/angular/pull/47717

**Review by jessicajaniuk — APPROVED** [review]
LGTM!

reviewed-for: integration-tests, public-api

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: integration-tests, public-api

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit c9541f4c49f6924658ea6b555923cbe2bdd2dfa2.

**Pull request closed without merging**
