### PR TITLE
Remove deprecated support for IE 9, 10, and IE mobile

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This PR contains a few commits to remove deprecated support for IE 9, 10, and IE mobile from docs and CI.
Additional code cleanup to remove the code specific to IE 9/10 will happen in followup PRs.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Angular framework stops IE 9, 10, and IE mobile support.

### CODE REVIEW

**Review by atscott — APPROVED** [review]
LGTM
// cc @StephenFluin

**Review by aikithoughts — APPROVED** [review]
Reviewed-for: required-docs-approvers

**Review by StephenFluin — APPROVED** [review]

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: docs-packaging-and-releasing

**Review by IgorMinar — APPROVED** [review]
looks great! thank you

**Review by IgorMinar — APPROVED** [review]
Reviewed-for: docs-packaging-and-releasing

**Pull request closed without merging**
