### PR TITLE
docs: clarify sentence in lifecycle hooks doc

### PR DESCRIPTION
**Pull request by jordan-amman**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Confusing verbiage.

Issue Number: N/A

## What is the new behavior?
Easier to read verbiage.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by jordan-amman** [comment]
@kapunahelewong Hey, I believe I messed the squash up in the other branch so I created a new branch and by setting reword on the top changeset and fixup on the second changeset the rebase worked successfully for me. Thank you for the documentation and help!

**Comment by kapunahelewong** [comment]
I totally understand, @jordan-amman. The Files Changed section looks good, but for some reason the commit is unusual, as if GitHub thinks there are two authors. 🤔I don't know how to fix it...

Do you access github with two different email addresses by chance? If you can figure out why it thinks you're two people, you might be able to fix it. Here's [a stackoverflow question](https://stackoverflow.com/questions/48536030/github-shows-that-my-commits-have-been-pushed-by-2-authors-me-and-me) that might be helpful (scroll to the second answer about the email address).

If you don't feel like troubleshooting (also understandable 😅) you could start a new branch and simply copy/paste your edit, rather than dealing with any sort of history that might be making github think you're two people. Then you'd have a new clean PR to work with. What do you think?

**Comment by jordan-amman** [comment]
@kapunahelewong When I commit the changes I use --author to set my github name and email so it doesn't by default add my work email, could this have something to do with it thinking there are 2 authors? Because then I think it still shows the committer as my work email...

**Comment by kapunahelewong** [comment]
Ohhhh, that sounds like it could have something to do with it, but I haven't noticed it happening on your other PRs. Hm... But yes, I think you might be right about why it's happening here. I've seen a number of examples where someone has two email addresses that they use with github (maybe  work and personal) and the CLA gets confused, thinking there were two authors. It also happened to me once when I cherry picked from someone else's PR. Hope this helps. :)

**Comment by jordan-amman** [comment]
@kapunahelewong So, my forked branch from angular says it is 2 commits ahead, which are my changes I was trying to make and had to squash. So, how do I get rid of them so I can redo the commit, or do I need to re fork the angular repo entirely?

**Comment by kapunahelewong** [comment]
Hi @jordan-amman it looks like you fixed the cla issue. 🎉Now, the only thing to do is rebase. I bet/hope that that will make it pass the tests. You might like the [steps I have in my notes](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) for rebasing. Please tag me with questions or when you're ready.

**Comment by kapunahelewong** [comment]
Oh I see https://github.com/angular/angular/pull/32860 now. Got it!

**Comment by kapunahelewong** [comment]
Hey, @jordan-amman, I'll close this one out since #32860 made it in. Thanks again!

**Pull request closed without merging**
