### PR TITLE
docs(forms): fix typo in removeValidators usage notes

### PR DESCRIPTION
**Pull request by Wooshaah**
Fixed a typo in the `abstract_model.ts`'s `removeValidators` and `hasValidator` functions usage notes.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
There is a typo

Issue Number: N/A

## What is the new behavior?
Typo is fixed

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — COMMENTED** [review]
@Wooshaah thanks for improving Angular docs, the change looks good 👍 

Could you please merge both commits into one and update the commit message to start with `docs(forms): ` (without an extra space between `docs` and `(forms)` - this should resolve the `lint` CI job failure)?

**Comment by Wooshaah** [comment]
I've merged both commits and fixed the commit message

**Review by AndrewKushnir — APPROVED** [review]
@Wooshaah thanks for addressing the feedback, I'm adding this PR to the merge queue.

**Comment by AndrewKushnir** [comment]
Caretaker note: presubmit is "green" (only pre-existing failing targets), we can proceed with the merge.

**Pull request closed without merging**
