### PR TITLE
style: Remove use of `String` as type and use `string` instead.

### PR DESCRIPTION
**Pull request by mhevery**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
LGTM - except for typo in commit message: used => use

**Review by kara — APPROVED** [review]
LGTM

**Comment by mhevery** [comment]
> LGTM - except for typo in commit message: used => use

fixed

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:280032983:BASE:280033034:1573592009287:8aa1c3ec)

**Comment by mhevery** [comment]
MERGE_ASSISTANCE: unrelated CI flake

**Pull request closed without merging**
