### PR TITLE
docs: remove outdated docs change log

### PR DESCRIPTION
**Pull request by jenniferfell**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

change-log.md is a log of documentation changes and updates (no code changes)
change-log.md exists in the AIO documentation set
change-log.md is not in the navigation but can be found via search
change-log.md has not been updated since 2017-03
https://angular.io/guide/change-log

Issue Number: N/A

## What is the new behavior?
We need to do one of the following:
- Remove it entirely, ensure doc changes are listed in Angular change log
- Update it and add it to the navigation
- Create a formal release note, in the doc nav, with reader-friendly code and doc changes

For now, this PR is partial. It removes out-of-date information and begins a list of recent doc changes. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[X ] No
```

### CODE REVIEW

**Comment by jenniferfell** [comment]
Updated PR to remove the old docs change log, rather than rewrite it to be current. 

Change of plan: Instead of maintaining a hand-crafted change log for docs, hidden in AIO, we're looking into creating a docs change log based on doc commits.

**Comment by jenniferfell** [comment]
@IgorMinar @brandonroberts : When you get a moment, can you review and approve? Thanks!

**Comment by brandonroberts** [comment]
There is a link in the navigation that refers to this guide that needs to be removed also.

**Comment by petebacondarwin** [comment]
Also do we need to add in a redirect?

**Comment by jenniferfell** [comment]
@brandonroberts @petebacondarwin Good catches! Thanks!

Added redirect. Also updated an older redirect that sent readers to this change-log.md for information about a TS-JS file that's in the v2 docs, so I updated the redirect to be that v2 doc. 

Also found mentions of that older redirect in a .txt file, so I updated that. Not one I've updated before for redirects. Do we still use it? Should I be adding more new redirects there?

Thx!

**Comment by brandonroberts** [comment]
LGTM. Yes, we should add redirects there, as they get verified with the E2E tests. I added some in the getting start/nav PR.

**Review by brandonroberts — APPROVED** [review]

**Comment by jenniferfell** [comment]
Caretaker: This PR removes a file that has been invisible but present for many releases. It's also extremely out of date. We're looking into a semi-automated solution for doc change log that is more like the code changelog.md. We've discussed with Igor. Brandon has the ability to approve.

**Comment by benlesh** [comment]
Be sure to mark it for `Caretarker assistance` for global approval :+1:

**Pull request closed without merging**
