### PR TITLE
docs: focus on the respective card of the current active line while scrolling

### PR DESCRIPTION
**Pull request by Ahmed-Hakeem**
focus on the respective card of the current active line even while scrolling
image

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@Ahmed-Hakeem `feat(animations)` implies this is a feature for the animations package. Can you change this to `docs: ` instead?

**Comment by Ahmed-Hakeem** [comment]
> @Ahmed-Hakeem `feat(animations)` implies this is a feature for the animations package. Can you change your commit message to `docs: ` instead? You can do this by running `git commit --amend` and changing the commit. Then you can push your change with `--force-with-lease` to update the PR here. I've updated the PR header already for you.

Sure thing : )

**Review by jessicajaniuk — APPROVED** [review]
This is quite nice! Thank you!

**Comment by Ahmed-Hakeem** [comment]
> This is quite nice! Thank you!

It's my pleasure : ) .... Thank you

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 6ec2f07f5d8dacde727e3b944fd44e555c48e37b.

**Pull request closed without merging**
