### PR TITLE
fix(router): allow UrlMatcher to return null

### LINKED ISSUE #29824: URLMatchResult type should include null
# 🐞 bug report

### Affected Package
URLMatcher is part of **@angular/router**

### Is this a regression?
No

### Description
Even in the example, is shown, that `null`, is to express that matcher didn't match.

## 🔬 Minimal Reproduction
	export function myMatcher(segments: UrlSegment[]): UrlMatchResult {
		return null;
	}

## 🔥 Exception or Error
`Type 'null' is not assignable to type 'UrlMatchResult'.`

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.1.2
Node: 9.11.1
OS: win32 x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.2
@angular-devkit/build-angular     0.11.2
@angular-devkit/build-optimizer   0.11.2
@angular-devkit/build-webpack     0.11.2
@angular-devkit/core              7.1.2
@angular-devkit/schematics        7.1.2
@angular/cli                      7.1.2
@ngtools/webpack                  7.1.2
@schematics/angular               7.1.2
@schematics/update                0.11.2
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.23.1
</code></pre>

### PR DESCRIPTION
**Pull request by mbward**
The matcher is allowed to return null per
https://angular.io/api/router/UrlMatcher#usage-notes

Fixes #29824

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Incorrect type error

```
error TS2322: Type '(url: UrlSegment[]) => UrlMatchResult | null' is not assignable to type 'UrlMatcher'.
  Type 'UrlMatchResult | null' is not assignable to type 'UrlMatchResult'.
    Type 'null' is not assignable to type 'UrlMatchResult'.
```

Issue Number: 29824

## What is the new behavior?

No type error.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
FYI - lint is failing because we recently updated clang. Please run `yarn gulp format` to fix this.

**Comment by mbward** [comment]
> FYI - lint is failing because we recently updated clang. Please run `yarn gulp format` to fix this.

Done.

Odd that it didn't reformat `goldens/public-api/router/router.d.ts`.

**Comment by atscott** [comment]
[global presubmit](https://test.corp.google.com/ui#id=OCL:304420903:BASE:304394689:1585861710873:efe59d7e) passed with no failures.

**Review by IgorMinar — APPROVED** [review]
LGTM, but please document this as a minor breaking change affecting those that implemented the `UrlMatcher` type. This should be easy to fix and doesn't require a migration, all we need is a documentation in the form of a commit message block in the format: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#footer

**Comment by mbward** [comment]
> please document this as a minor breaking change affecting those that implemented the `UrlMatcher` type

Since we're widening the type, don't all existing implementations already satisfy the new type?

I think the concern would be for anybody implementing their own Router and assuming `matcher` couldn't return null. Which is unlikely to be the case, since it already could return null. But I'll happily mention that in the commit message footer.

**Comment by sod** [comment]
i guess you can reject @trshafer contribution in https://github.com/angular/angular/pull/22898 now

**Pull request closed without merging**
