### PR TITLE
docs(docs-infra): Add deployment info for Layer0

### PR DESCRIPTION
**Pull request by adebiyi-al**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by mgechev** [comment]
@adebiyi-al thanks for the PR! This doesn't seem to be an Angular CLI `deploy` builder.

**Comment by adebiyi-al** [comment]
No @mgechev, it's just a docs link on how to deploy Angular on Layer0.

**Comment by mgechev** [comment]
On this page we share only providers which have implementation of a deployment builder (i.e. functional `ng deploy` command for their service).

The guide for Layer0 does not seem like a good fit for this page in the docs.

**Comment by adebiyi-al** [comment]
Got it @mgechev 🙏

**Pull request closed without merging**
