### PR TITLE
feat(di): throw on sync bindings with async dependencies

### LINKED ISSUE #1111: Async binding onto an async dependency should throw an error regardless of dependency resolution
We have the following pattern in application.js:

```js
      bind(appViewToken).toAsyncFactory(...),

      bind(appChangeDetectorToken).toFactory((rootView) => rootView.changeDetector,
          [appViewToken]),
```

The change detector is bound with a **sync** dependency on the root view while the root view is **async**.

It works because the root view has been instantiated before the change detector is instantiated, as demonstrated with the test added in #1101:

```js
      // expect behavior, was there before 1101
      it('should throw when instantiating a sync binding with an async dependency', function () {
        var injector = new Injector([
          bind(UserList).toAsyncFactory(fetchUsers),
          UserController
        ]);

        expect(() => injector.get(UserController))
          .toThrowError('Cannot instantiate UserList synchronously. It is provided as a promise! (UserController -> UserList)');
      });

      // added in 1101
      it('should not throw when instantiating a sync binding with a resolved async dependency',
        inject([AsyncTestCompleter], (async) => {
        var injector = new Injector([
          bind(UserList).toAsyncFactory(fetchUsers),
          UserController
        ]);

        injector.asyncGet(UserList).then(() => {
          expect(() => { injector.get(UserController); }).not.toThrow();
          async.done();
        });
      }));
```

As demonstrated by the tests above, with the **same DI config**, the behavior is different according to the order in which the classes are instantiated.

While this is easy to understand in a simple example like this one, I believe it could be the source of interim and hard to debug bugs when the dependency graph gets more complex - there could be an error which gets triggered depending on a timing of an async function.

@vsavkin what about throwing an error in such a case ? It would make the behavior reproducible and avoid potential errors.

/cc @juliemr

### PR DESCRIPTION
**Pull request by vicb**
fixes #1111

This PR triggers (legitimate) errors that should be fixed before the PR can be merged.

TODO:
- [ ] fix the errors from #2408,
- [ ] we probably only want to check in dev mode ? #112

[Review on Reviewable](https://reviewable.io/reviews/angular/angular/2407)

### CODE REVIEW

**Comment by vsavkin** [comment]
Is it blocked or WIP? If blocked, could you provide a short description of what is blocking this PR.

**Comment by vsavkin** [comment]
@vicb ping

**Comment by vicb** [comment]
As indicated in the PR description above this is blocked: the code is ready to review but it triggers errors which must be fixed before we can merge this PR.

**Comment by tbosch** [comment]
After the merge of app injector with element injector, the async support was removed. Closing this PR.

**Pull request closed without merging**
