### PR TITLE
docs: update analytics gathering documentation

### PR DESCRIPTION
**Pull request by alan-agius4**
Currently there are 3 pages for analytics gathering information. Most of the information is duplicate.

With this change we remove the duplicate pages and outdated content to reflect the changes in version 15. 
Content will be located in https://angular.io/cli/analytics.

Related to https://github.com/angular/angular-cli/pull/24118

### CODE REVIEW

**Comment by alan-agius4** [comment]
Blocked on https://github.com/angular/angular-cli/pull/24118

**Comment by alan-agius4** [comment]
Blocked on https://github.com/angular/angular/pull/47870

**Review by twerske — APPROVED** [review]
LGTM - is there any risk that we're removing urls? I don't see redirects added to the deleted routes.

**Comment by alan-agius4** [comment]
> LGTM - is there any risk that we're removing urls? I don't see redirects added to the deleted routes.

Redirects added.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit c9a6f95c9d750871d6bfaf0cc98811084ef5c582.

**Pull request closed without merging**
