### PR TITLE
docs: use `ValidationErrors` interface in Form validation examples

### PR DESCRIPTION
**Pull request by swseverance**
* Updates example to use `ValidationErrors` interface instead
  of defining a custom interface.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@swseverance thanks for improving Angular docs, the change looks good 👍 

I noticed that the `lint` CI job is failing due to the commit message that contains `aio` as a scope. For docs-related commits you can just drop the scope, so the commit message ,ight look like:

```
docs: use `ValidationErrors` interface in Form validation examples
```

Could you please update the commit message (using `git commit --amend`) command? Once it's updated, please let us know (by leaving a comment in this thread) and we'll move the PR to the merge queue.

Thank you.

**Comment by swseverance** [comment]
@AndrewKushnir updated. thank you

**Comment by AndrewKushnir** [comment]
Thanks for the update @swseverance, I've added the "merge" label and this PR will be ready for merge once CI is completed.

**Comment by gkalpak** [comment]
For future PRs (:wink:), if a docs change affects a specific package, you can use it as the commit message scope. (In this case, for example, `docs(forms)` would be appropriate.)

**Pull request closed without merging**
