### PR TITLE
docs(core): fix typo in directive.ts [life-cycle hoooks] -> [life-cyc…

### PR DESCRIPTION
**Pull request by philipszdavido**
…le hooks]

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/pull/25359

**Comment by philipszdavido** [comment]
Check

**Comment by philipszdavido** [comment]
Check

**Comment by philipszdavido** [comment]
Check

**Comment by brandonroberts** [comment]
Fixed in https://github.com/angular/angular/pull/25377

**Pull request closed without merging**
