### PR TITLE
docs: correct browserslist behavior docs

### PR DESCRIPTION
**Pull request by Char2sGu**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Wrong/Incomplete documentation, as mentioned in the following issue.

Issue Number: #56020

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]
LGTM, just one NIT

**Comment by Char2sGu** [comment]
Updated @alan-agius4

**Comment by alan-agius4** [comment]
@Char2sGu can you please sign the CLA and also squash the commit? Thanks.

**Comment by Char2sGu** [comment]
Hey @alan-agius4 I've signed the CLA, but I believe it can be more convenient to squash the commits on merge. The edits were made via GitHub Web.

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 400b47ebb153a03c4d29fbd443cf01c3880baf9d.

**Pull request closed without merging**
