### PR TITLE
docs: add Andrew Grekov to GDE resources

### PR DESCRIPTION
**Pull request by thekiba**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

cc @StephenFluin

### CODE REVIEW

**Review by kapunahelewong — CHANGES_REQUESTED** [review]
Thanks for this, @thekiba and congratulations! We just need to get the tests passing. Try this for your commit message To meet the 100 character minimum requirement in the body:

```
docs: add Andrew Grekov to GDE resources

This commit adds Andrew Grekov to the GDE 
resources page and describes his work as a software 
engineer using angular and .NET.

```

Notice the blank line before and after the body.

Rebasing should also help you pass the tests.

Here are my notes on [amending commit](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) and [rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash), but if you need help with anything just let me know and I can help from this end.

**Comment by thekiba** [comment]
Thanks for your help, @kapunahelewong! I have updated this pr and force pushed it. Hope that it's good now 🦊

**Review by kapunahelewong — APPROVED** [review]
LGTM! Thank you, @thekiba!

Reviewed-for: global-docs-approvers

**Review by StephenFluin — APPROVED** [review]

**Comment by thekiba** [comment]
@kapunahelewong it seems that I should make a rebase and force push it again, right?

**Comment by kapunahelewong** [comment]
Yes, @thekiba, that would be great. Here are [my notes on rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) if you'd like to refer to them. If you have any questions just let me know and I can help you. Once it's rebased and passing all the tests we can mark it for merge!

**Comment by thekiba** [comment]
Thanks for your help, @kapunahelewong! Hope that it's good now 🦊

**Comment by thekiba** [comment]
@kapunahelewong I waited until the tests on the master were successful and rebased again. And now the sauce labs test is not passed. Could you please look at this? 😅

**Comment by petebacondarwin** [comment]
It's most likely a flakey test. I have restarted the failing job.

**Pull request closed without merging**
