### PR TITLE
docs(docs-infra): move CLI docs to ADEV

### PR DESCRIPTION
**Pull request by JeanMeche**
Previously located in the `aio` directory, the commit moves the docs file into `adev` and also moves the `script` used to generated them from the `angular-cli` repo.

### CODE REVIEW

**Review by alan-agius4 — COMMENTED** [review]
Is adev actually using these docs?

**Comment by JeanMeche** [comment]
Yes, it's the same behaviour that was ported from aio.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by atscott** [comment]
This PR was merged into the repository by commit f8d59211acb6509958f942ac2d27156c69081797.

**Pull request closed without merging**
