### PR TITLE
fix(common): server-side rendering error when using in-memory scrolling

### LINKED ISSUE #53682: `ERROR ReferenceError: window is not defined` when using withInMemoryScrolling with SSR
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I migrated an Angular v16 app to v17. When attempting to prerender it, an error occurs: ERROR ReferenceError: 'window' is not defined. 

To replicate run `npm run dev:ssr` and then hit http://localhost:4200 or run `npm run prerender`

The prerender would run with no errors if you comment this lines https://github.com/kuncevic/v17-withIn-memory-scrolling-issue/blob/master/projects/consulting/src/app/app.config.ts#L16-L19

### Please provide a link to a minimal reproduction of the bug

https://github.com/kuncevic/v17-withIn-memory-scrolling-issue

### Please provide the exception or error you saw

```true
ReferenceError: window is not defined
    at factory (webpack:///node_modules/@angular/common/fesm2022/common.mjs:5184:72)
    at callback (webpack:///node_modules/@angular/core/fesm2022/core.mjs:6168:43)
    at runInInjectorProfilerContext (webpack:///node_modules/@angular/core/fesm2022/core.mjs:867:9)
    at hydrate (webpack:///node_modules/@angular/core/fesm2022/core.mjs:6167:17)
    at get (webpack:///node_modules/@angular/core/fesm2022/core.mjs:6037:33)
    at injectInjectorOnly (webpack:///node_modules/@angular/core/fesm2022/core.mjs:911:40)
    at ɵɵinject (webpack:///node_modules/@angular/core/fesm2022/core.mjs:917:60)
    at inject (webpack:///node_modules/@angular/core/fesm2022/core.mjs:1001:12)
    at useFactory (webpack:///node_modules/@angular/router/fesm2022/router.mjs:6476:48)
    at factory (webpack:///node_modules/@angular/core/fesm2022/core.mjs:6267:38)


the error indicate the below line

class ViewportScroller {
    // De-sugared tree-shakable injection
    // See #23917
    /** @nocollapse */
    static { this.ɵprov = ɵɵdefineInjectable({
        token: ViewportScroller,
        providedIn: 'root',
        factory: () => new BrowserViewportScroller(ɵɵinject(DOCUMENT), window) <--error here
    }); }
}
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.7
Node: 18.18.2
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 17.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.7
@angular-devkit/build-angular   17.0.7
@angular-devkit/core            17.0.7
@angular-devkit/schematics      17.0.7
@angular/cdk                    17.0.4
@angular/material               17.0.4
@schematics/angular             17.0.7
ng-packagr                      17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the `BrowserViewportScroller` was throwing an error during server-side rendering because it was accessing `window` directly. Also removes some assertions that aren't necessary anymore.

Fixes #53682.

### CODE REVIEW

**Comment by alan-agius4** [comment]
Shouldn't actually `withInMemoryScrolling` be nooped instead when platform is server by returning null? I don't see why this feature should be even enabled for non browser platforms. 

https://github.com/angular/angular/blob/d315e2c4fa178dfbd41bc25259605bb999fa302e/packages/router/src/provide_router.ts#L183:L188

**Comment by crisbeto** [comment]
In that case we would have to provide a noop implementation of the class. The current class already has all the necessary checks in place, the only missing one was in the factory.

**Comment by alan-agius4** [comment]
@crisbeto, I don't quite see the necessity for creating a noop implementation. Since `ROUTER_SCROLLER` is an optional token, returning null is acceptable. You can find the relevant code https://github.com/angular/angular/blob/d315e2c4fa178dfbd41bc25259605bb999fa302e/packages/router/src/provide_router.ts#L211

Therefore, the following code should be adequate. The advantage here is that it avoids the creation and subscription to unused router events and  can also contribute to better future-proofing, preventing potential regressions if a feature isn't utilized in SSR.

```diff
const providers = [{
  provide: ROUTER_SCROLLER,
  useFactory: () => {
+    const platformId = inject(PLATFORM_ID);
+    if (!isPlatformBrowser(platformId)) {
+       return null;
+    }
+
    const viewportScroller = inject(ViewportScroller);
    const zone = inject(NgZone);
    const transitions = inject(NavigationTransitions);
    const urlSerializer = inject(UrlSerializer);
    return new RouterScroller(urlSerializer, transitions, viewportScroller, zone, options);
  },
}];
```

I'm not strongly attached to this suggestion, but I lean towards not enabling unnecessary features.

**Comment by crisbeto** [comment]
My concern was that this is still going to error if somebody tries to inject `ViewportScroller`. Since it's `providedIn: 'root'`, it doesn't necessarily have to be provided by the router in order to be injectable. The other problem is that the `ROUTER_SCROLLER` doesn't know how it's going to be injected. E.g. currently the only place we use it's optional, but if another place injects it later on, it'll be misleading to return `null`.

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
This PR was merged into the repository by commit dd052dc0d6116b0a42b33d6456efaf9c234239dc.

**Pull request closed without merging**
