### PR TITLE
style(router): fix syntax in code example of comment block

### PR DESCRIPTION
**Pull request by davidcraddock**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x ] Other... Please describe: fixed code examples in comment blocks
```

**What is the current behavior?** (You can also link to an open issue here)
code examples have formating error in them

**What is the new behavior?**
code examples work

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

fixed router code examples.

### CODE REVIEW

**Comment by Codebacca** [comment]
I signed it!

**Comment by vicb** [comment]
> The commit message follows our guidelines:

Are you sure ?

**Comment by Codebacca** [comment]
Yeah, just corrected the code example within the comment block.

**Comment by vicb** [comment]
It does not

**Comment by Codebacca** [comment]
From the current comment block code examples you can see there is an opening [ but no closing ]. That's what this pull request will correct.

**Comment by vicb** [comment]
You've replied
```
[ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
```

it doesn't follow the guidelines, please update the commit message (content is fine)

**Comment by Codebacca** [comment]
thanks, fixed commit message.

**Pull request merged**
