### PR TITLE
chore: add types to a number of members

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Waiting on green bots – seeing some weird issues.

**Comment by kevmoo** [comment]
@mhevery Any clue why adding types would cause such errors in JS?

https://travis-ci.org/angular/angular/jobs/59335453#L451

**Comment by tbosch** [comment]
Can you reproduce this locally? Then the console log of the browser that is
running karma gives a real stack trace (which we don't log in Travis :-(
)...

**Comment by kevmoo** [comment]
Talk about an annoying pile of weird...

screen shot 2015-04-20 at 8 58 39 pm

**Comment by kevmoo** [comment]
@tbosch @mhevery Gah! it was `:num` instead of `:number`.

We need *much* earlier, clearer warnings about these types of issues.

I hit something very similar with `:bool` vs `:boolean`

**Comment by kevmoo** [comment]
I managed to get this green...

**Comment by kevmoo** [comment]
Closed in f7f06c5

**Pull request closed without merging**
