### PR TITLE
refactor(docs-infra): use reactive APIs in shared components

### PR DESCRIPTION
**Pull request by sheikalthaf**
Migrated the input, output and queries to reactive APIs for better support of zoneless.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
I'm curious did you use the migrations schematics for this ?

**Comment by sheikalthaf** [comment]
@JeanMeche No, it is manually migrated. I don't know how to run the migration in this repo.

**Comment by JeanMeche** [comment]
@pkozlowski-opensource was actually experimenting it in #58415. Not sure which PR to chose.

**Comment by sheikalthaf** [comment]
@pkozlowski-opensource I think this kinda work can be given to community, so that angular team members can focus on the feature implementation. Already updated the same refactoring to Devtools.

**Comment by pkozlowski-opensource** [comment]
> @pkozlowski-opensource I think this kinda work can be given to community, so that angular team members can focus on the feature implementation. Already updated the same refactoring to Devtools

@sheikalthaf absolutely agree in general. Having said this I'm not making those changes by hand but rather testing our automated migration on the adev - and catching some bugs in those (!).

So my preferred way of progressing here would be to run the automated migrations first and only then follow up with manual changes.

How does it sound?

**Comment by sheikalthaf** [comment]
@pkozlowski-opensource yes, this kinda work should be automated.

I'll also try to do the same using migrations. Let me try the same.

**Comment by pkozlowski-opensource** [comment]
@sheikalthaf thnx. As an example, here is the PR resulting from the automated output migration: #58447 

Feel free to send separate PRs for each migration, ex.:
* control flow
* inputs
* queries
_without_ doing _any_ manual changes - it is important for us to understand if the migrations can be improved - changing the adev code is a secondary goal.

Also, for the self-closing tags - we shouldn't be doing those changes manually, there is a PR in flight that adds automated migration for that.

**Comment by pkozlowski-opensource** [comment]
> inputs migration not updating the html templates

@sheikalthaf oh, this does sound like a bug, I will try on my side

> if an input value is updated inside the component then it is not handled properly (we can use model for that)

I don't think the migration should automatically use `model` to migrate inputs for which we write. More generally, `model` is not meant to be a "writable input". I _think_ this is the same use-case I was looking at in https://github.com/angular/angular/pull/58415/files ?

**Comment by sheikalthaf** [comment]
> > inputs migration not updating the html templates
> 
> @sheikalthaf oh, this does sound like a bug, I will try on my side
> 
> >

@pkozlowski-opensource it is only happen for this repo, works fine on apps created with angular cli.

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM. 

It will need a rebase before we can merge.

**Comment by sheikalthaf** [comment]
@pkozlowski-opensource rebased the PR with main.

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit 53341a3b8fc20c7f78982a5bbb41c7f457c45892.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
