### PR TITLE
docs: remove an extra "and" in tutorial

### PR DESCRIPTION
**Pull request by newshahn**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

There was an extra "and" in the sentence which is removed now.
https://angular.io/guide/dependency-injection#injecting-services
The sentence: For more information, see and Providing dependencies in modules and Hierarchical injectors.

Issue Number: N/A

## What is the new behavior?
The extra and is removed like so: For more information, see Providing dependencies in modules and Hierarchical injectors.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Thanks for this fix @newshahn.
Can you tweak the commit message. The target is not `docs-infra` since `docs(docs-infra)` is used for docs "about" the AIO website.
Also could you add quotes around the `and` to make the message easier to read?
In other words:

```
docs: remove an extra "and" in the tutorial
```

**Comment by newshahn** [comment]
> Thanks for this fix @newshahn.
> Can you tweak the commit message. The target is not `docs-infra` since `docs(docs-infra)` is used for docs "about" the AIO website.
> Also could you add quotes around the `and` to make the message easier to read?
> In other words:
> 
> ```
> docs: remove an extra "and" in the tutorial
> ```

Thanks @petebacondarwin.
The commit message is now changed to what you requested :)

**Review by petebacondarwin — APPROVED** [review]
Close enough :-)

Reviewed-for: global-docs-approvers

I suspect you did the change via `git commit --message` where the `"` characters were stripped by the shell?

**Comment by newshahn** [comment]
> Close enough :-)
> 
> Reviewed-for: global-docs-approvers
> 
> I suspect you did the change via `git commit --message` where the `"` characters were stripped by the shell?

So sorry about this @petebacondarwin .
Hopefully, this time it's really fixed.

**Comment by petebacondarwin** [comment]
No problem! Great. Thanks.

**Comment by petebacondarwin** [comment]
The CI failures appear to be because CircleCI is undergoing maintenance.

**Comment by newshahn** [comment]
> The CI failures appear to be because CircleCI is undergoing maintenance.

Do I need to do anything...?

**Comment by gkalpak** [comment]
@newshahn, I restarted the CI jobs and everything seems fine now. Thx!

**Pull request closed without merging**
