### PR TITLE
docs(aio): change title of guide/http to `HTTP`

### PR DESCRIPTION
**Pull request by lacolaco**
## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The guide for HTTP is called `Server Communication` in sidenav, and there is no `HTTP` word in sidenav. 

image

## What is the new behavior?

new title `HTTP`. simple and intuitive.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Foxandxss** [comment]
We changed it to http in the past, then the decision was to change it back to server communication.

**Comment by petebacondarwin** [comment]
@wardbell why put this in the AIO project?

**Review by petebacondarwin — DISMISSED** [review]

**Comment by petebacondarwin** [comment]
@IgorMinar can you comment on whether this change makes sense.

**Comment by petebacondarwin** [comment]
This guide was completely rewritten and renamed for the new `HttpClient` library.

**Pull request closed without merging**
