### PR TITLE
[i18n] Adds Occitan language

### PR DESCRIPTION
**Pull request by Mejans**
In its general form, oc_FR

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #37061

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by Mejans** [comment]
@googlebot I signed it!

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Hand coding a locale data file is not a viable solution here, I'm afraid.
It would not be possible to keep it updated automatically.
The only option I could foresee us accepting would be if we could change the extraction tooling (i.e. angular/tools/gulp-tasks/cldr/extract.js) to be able to bring in this locale from the CLDR data.

**Comment by Mejans** [comment]
I totally agree but at the moment it's the only way =/
Or maybe consider adding locales that are in seeds and that have the required data?

**Comment by petebacondarwin** [comment]
Is it not possible to include this file in your own application and then load it manually using the `registerLocaleData()` method?

**Comment by Chocobozzz** [comment]
> Is it not possible to include this file in your own application and then load it manually using the registerLocaleData() method?

I can try, but Occitan could be used in other Angular projects :)

**Comment by petebacondarwin** [comment]
> Occitan could be used in other Angular projects :)

That is possible, but you are the first so far, and once it becomes common enough it will leave the CLDR seed and enter the main repository, in which case we will get it here for free.

**Comment by petebacondarwin** [comment]
I'm going to close this PR, since we won't land it as-is. The workaround is to provide a custom locale in your own project.

**Pull request closed without merging**
