### PR TITLE
[WIP]docs(aio): add GraphQL doc

### PR DESCRIPTION
**Pull request by kapunahelewong**
## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Adds a doc explaining how to use GraphQL with Angular.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

This is @Urigo's GraphQL doc. Copy is ready. Needs a couple of missing code snippets and plunkr link fixed.

### CODE REVIEW

**Comment by Urigo** [comment]
@kapunahelewong I'm so happy it's back!  
I have a few questions about the new setup but the first thing is -  
I'm not sure where do we add the new dependencies to examples.
where do we specify that the examples needs to npm install apollo-angular or any other 3rd party libraries?  
we used to have package.json file for the examples but I can't find it here

**Comment by Foxandxss** [comment]
We only have one package.json (at `tools/examples/shared/package.json`) with all the packages for all the demos.

**Comment by Urigo** [comment]
@Foxandxss thanks!  another general question, all the examples now are using system.js, is there a plan to change them to Webpack or should I just stay with system.js for now?

**Comment by Foxandxss** [comment]
We are doing some planning for CLI, but the examples will remain system.js for the time being.

**Pull request closed without merging**
