### PR TITLE
docs: angular.kr link added

### PR DESCRIPTION
**Pull request by han41858**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

No problem about this pull request.

## What is the new behavior?

angular.io have new link to angular.kr, Angular Korean Guide

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by han41858** [comment]
I signed it!

**Comment by jenniferfell** [comment]
@IgorMinar @StephenFluin Please approve. Thanks!

**Comment by StephenFluin** [comment]
@han41858 Hi there! This is awesome and we'd love to link to you. Thank you for translating the site.

Before we approve it fully, I would love to understand your plans for the future with this translated site? Do you have plans to keep it up to date? Who controls the domain name / hosting (in case you get compromised/hacked)

Thanks!

**Review by jenniferfell — APPROVED** [review]
Changed target to master & patch, so it shows up on stable and next.

**Comment by han41858** [comment]
@StephenFluin
Hi!! Thank you for liking what I did. angular.io project is super cool project I have been seen.

My goal is to translate angular.io fully and to keep it up to date.
The domain(angular.kr) owner is me & it hosted on GitHub Pages using my repository(https://github.com/han41858/angular-kr).

If you have any other question, please tell me :)

Thanks!

**Review by StephenFluin — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]

**Pull request closed without merging**
