### PR TITLE
docs: architecture overview, fix bad link

### PR DESCRIPTION
**Pull request by jbogarthyde**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Comment by jbogarthyde** [comment]
FIxed a typo - please try again.

**Comment by jbogarthyde** [comment]
FIxed a typo in a link  - please approve. 
@mhevery @jenniferfell

**Review by jenniferfell — APPROVED** [review]

**Comment by jenniferfell** [comment]
LGTM

@brandonroberts : Will you be our pull-approver? Formerly missing a ] so the URL for the link showed up as plain text in the doc. Judy fixed, so now it's a proper linked phrase.

**Review by brandonroberts — APPROVED** [review]

**Comment by mhevery** [comment]
Is this ready to merge? The merge label has been removed...

**Comment by brandonroberts** [comment]
@mhevery it's ready but we can't get CI green. Saucelabs keeps failing.

**Comment by jenniferfell** [comment]
caretaker: This PR has approval from @brandonroberts, he appears to be in the pull-approve group for the PR, and the PR was not submitted by him, so I would expect code-review-pullapprove to be passing, not stuck pending.  Suggestions? Thanks.

**Pull request closed without merging**
