### PR TITLE
No args

### PR DESCRIPTION
**Pull request by mhevery**

### CODE REVIEW

**Comment by alexeagle** [comment]
One of these commits has messed up the indent in the resulting file - class members are left-aligned.
note that the whitespace in the dgeni template has to be very precise, since we don't run the output through a formatter (that might be worth doing, though.)

**Comment by alexeagle** [comment]
as discussed on hangout: the documentation for decorator arguments now appears only in the *Annotation class, eg. "Specifies an inline template for an angular component" is only in `ViewAnnotation` and that is not seen by TS coder.

**Comment by mhevery** [comment]
@petebacondarwin is working on the indentation issue.

**Comment by alexeagle** [comment]
otherwise LGTM

**Pull request closed without merging**
