### PR TITLE
refactor: added HTML <!DOCTYPE> Declaration in the html files

### PR DESCRIPTION
**Pull request by alkavats1**
…with the em tag

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@alkavats1 thanks for improving Angular docs!

**Comment by alkavats1** [comment]
Hi, @pkozlowski-opensource  any suggested changes? You change the tag from merge to review.
Please suggest
Thanks

**Review by josephperrott — CHANGES_REQUESTED** [review]
Can you rewrite the commit message to be a `refactor` or `fix` as this is not a actually `docs` change in the sense of our documentation.

Additionally, the commit message should explain why this change is being done.

**Comment by alkavats1** [comment]
Hi @crisbeto @AndrewKushnir @josephperrott please review this PR 
Thanks

**Comment by alkavats1** [comment]
Hi, @crisbeto and @AndrewKushnir, and @josephperrott  could you please review and merge this PR? It is pending since last week
Thanks :)

**Review by josephperrott — CHANGES_REQUESTED** [review]
It looks like the commit message for the second commit does not match our commit message guidelines.  Please read through our [contributing guide's commits section](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit) about the structure and styling of commit messages we expect.

**Pull request closed without merging**
