### PR TITLE
docs: move old changelog entries to a separate file

### LINKED ISSUE #45635: Changelog got too big, cannot be viewed anymore
### Description

Angular's changelog in github now shows this:

image

which cannot quench my thirst for juicy Angular updates

Can you guys come up with something?
Thanks

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit moves all release notes for everything before v11.0.0 to a separate file, so that the changelog can be rendered correctly via GitHub UI.

Closes #45635.

## PR Type
What kind of change does this PR introduce?

- [x] Documentation content changes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by alan-agius4 — APPROVED** [review]
Nit: the commit has a typo `cna` -> `can`

Can you also please do a similar change for the patch changelog?

**Comment by AndrewKushnir** [comment]
@alan-agius4 thanks for the review, I've created PR #45639 with a similar change for the patch (13.3.x) branch.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 6444a02620d025ddd7b55758eb5704a4706fb153.

**Pull request closed without merging**
