### PR TITLE
docs(core): fix typo in hierarchical injectors

### LINKED ISSUE #34953: Typo in Hierarchical Injectors Doc
# 📚 Docs or angular.io bug report

### Description

There's a small typo in the Hierarchical Injectors doc.

### What's the affected URL?**
 https://angular.io/...

### Reproduction Steps**
Do a find for the following sentence:
> Using viewProviders makes services visibile in the <#VIEW>.

It is the second sentence in the [Using the viewProviders](https://angular.io/guide/hierarchical-dependency-injection#using-the-viewproviders-array) array section.

### Expected vs Actual Behavior**

"visibile"  should be "visible"

## 🔥 Exception or Error
<pre><code>

</code></pre>

### PR DESCRIPTION
**Pull request by tortuvshin**
Fixes #34953

### CODE REVIEW

**Comment by tortuvshin** [comment]
@googlebot I signed it!

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx, @tortuvshin :+1:
Can you please update the commit message to mention the issue it is fixing (in the special format that will let GitHub know to auto-close the issue once the PR is merged)? 🙏

> docs(core): fix typo in hierarchical injectors
>
> Fixes #34953

<sub>In case you've missed it, you can find more details on our commit messagr guidelines [here][1].

[1]: https://github.com/angular/angular/blob/be8d06c6ea11d5bfe1bfd19a9cfc0a21a5507861/CONTRIBUTING.md#commit

**Comment by tortuvshin** [comment]
> Thx, @tortuvshin 👍
> Can you please update the commit message to mention the issue it is fixing (in the special format that will let GitHub know to auto-close the issue once the PR is merged)? 🙏
> 
> > docs(core): fix typo in hierarchical injectors
> > Fixes #34953
> 
> In case you've missed it, you can find more details on our commit messagr guidelines [here](https://github.com/angular/angular/blob/be8d06c6ea11d5bfe1bfd19a9cfc0a21a5507861/CONTRIBUTING.md#commit).

@gkalpak I'm updated the commit message.

**Comment by gkalpak** [comment]
Thx for following up, @tortuvshin. Unfortunately, I'm afraid you have changed the PR title/description, not the commit message :grin:

To change the commit message, you would have to check out your branch locally, amend the last commit and force-push to your origin.

(Based on the brach name, I assume you have created the PR in GitHub's UI, so let me fix the commit message for you.)

**Comment by gkalpak** [comment]
@caretaker: Global approval for this docs-only change.

**Review by gitworkshoptoday — APPROVED** [review]
makes sense

**Comment by kapunahelewong** [comment]
Thank you for taking this, @tortuvshin!

**Pull request closed without merging**
