### PR TITLE
fix(http): complete the request on timeout

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Issue Number: #26453

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM. Thanks! This is very straightforward.

**Comment by jessicajaniuk** [comment]
[Presubmit](test/OCL:343918160:BASE:343918193:1606167164283:d5e8953a)

**Review by alxhub — APPROVED** [review]

**Comment by alxhub** [comment]
Merging just to `master` as this conflicts with the patch branches.

**Comment by arturovt** [comment]
> Merging just to `master` as this conflicts with the patch branches. @arturovt, would you be able to open a PR to the `11.2.x` branch for this change?

Sure, I'll try that.

**Pull request closed without merging**
