### PR TITLE
fix(elements): add polyfill to specified project

### LINKED ISSUE #24813: [Elements] ng-add schematic only adds polyfill to first project in angular.json
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using `ng add @angular/elements --project=<project-name>` the document-register-element polyfill script is added to the first project in angular.json regardless of the name passed in the project flag.

## Expected behavior

In a workspace with multiple projects, you should be able to specify the project name and the polyfill should be added to the scripts array of the given project. The schematic already supports the project flag, but it seems to ignore it.

## Minimal reproduction of the problem with instructions

1. Create a new CLI project `ng new foo`
2. Generate a new app `ng generate application bar`
3. Add @angular/elements to the new app `ng add @angular/elements --project=bar`
  - document-register-element.js is added to the architect.build.options.scripts array for the 'foo' project
  - Each subsequent call to `ng add @angular/elements` will add the script to the first project's scripts array again

## What is the motivation / use case for changing the behavior?

- Calling `ng add @angular/elements` with a `--project` flag should honour the given value
- Polyfills script should only be added to the script array once per app

## Environment

<pre><code>
Angular CLI version: 6.0.8
Angular Elements version: 6.0.5 (but the schematic code hasn't changed since)

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.10.0  
- Platform:  Mac 

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by garydex**
The document-register-element polyfill script was added to the first project in angular.json regardless of the name passed in the project flag. options.project is now used instead, if it is specified.

fixes #24813

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #24813 

## What is the new behavior?
The document-register-element polyfill script was added to the first project in angular.json regardless of the name passed in the project flag. options.project is now used instead, if it is specified.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Some tests are failing (and no tests are added for the new behavior). Other than that LGTM.

**Comment by robwormald** [comment]
👍 thanks for sending the PR - will run the presubmit tomorrow!

**Comment by garydex** [comment]
Any update on this @robwormald ?

**Review by gkalpak — CHANGES_REQUESTED** [review]
There is still no test for the new behavior.

**Comment by garydex** [comment]
I think the original test is adequate. The logic was wrong in the original code, and the test was passing incorrectly. After fixing the code, the test failed, and I updated it accordingly. 

Happy to add another test if you disagree, but it’d be pretty much duplicating the current one.

**Comment by garydex** [comment]
No longer an issue in latest version

**Pull request closed without merging**
