### PR TITLE
docs(core): standalone-migration schematics update

### PR DESCRIPTION
**Pull request by bougwal**
Made changes in the description of the standalone-migration schematics guide  introduced yesterday to improve readability and correct typos.

### CODE REVIEW

**Comment by dylhunn** [comment]
Thank you for your PR! However, upon looking it over, I don't think these grammar edits are correct.

**Comment by bougwal** [comment]
Hello, Thanks for your review. 

I do however see that this is a valid change. If that hyphenation is incorrect grammar, then schematics docs should be updated or at least unified and standardized (see attachement). 
Screenshot 2023-01-27 at 19 34 31

Apart from the line-32 reversed commas, I mistakenly introduced, I think these changes are somehow valid. Especially, for the wrong const**rus**tors word out there.

**Comment by dylhunn** [comment]
OK. Let's fix up that comma swap. Also what is the purpose of the `public showGreeting = true;` field being added? And lastly let's leave the re-run directions as-is, since the entry point and name may change

**Comment by dylhunn** [comment]
Hm actually, I cannot reopen this PR, you may need to make a new one to proceed with these changes

**Comment by bougwal** [comment]
Hello, the point of the `public showGreeting = true;` is that we introduced in the template what is not available in the component `.ts`. Thinking of this from a beginner standpoint not someone with extensive experience with Angular. I think Docs should always assume readers-ignorance/-limited-knowledge. And as per your recommendation, let's leave that re-run message as-is even though I think it is also not that clear especially for beginners. I will proceed with a new PR. Thanks !

**Pull request closed without merging**
