### PR TITLE
docs(elements): move clarification about custom elements

### PR DESCRIPTION
**Pull request by BBKolton**
Moved clarification that "custom elements" are a subtype of Web Components to the first use of the term "custom elements"

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
No code changes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
👍
Can you please change the commit message to something like:

> docs(elements): move clarification about custom elements
>
> ...

**Comment by BBKolton** [comment]
Updated the commit message, forgive me if this isn't the format you're looking for. First contribution to open source (even if small) :)

**Comment by BBKolton** [comment]
Proc for cla/google bot

**Comment by BBKolton** [comment]
proc cla/google bot 2: electric boogaloo

**Pull request closed without merging**
