### PR TITLE
docs(aio): add Brian Love to GDE resources

### PR DESCRIPTION
**Pull request by blove**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

- [ ] Refactoring (no functional changes, no api changes)

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

This adds [Brian Love](https://github.com/blove) to the list of Angular GDEs on the Angular Docs page -> cc @StephenFluin 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by blove** [comment]
I signed it!

**Review by gkalpak — APPROVED** [review]

**Review by StephenFluin — APPROVED** [review]

**Comment by gkalpak** [comment]
I hadn't noticed the indentation was incorrect in the whole `contributors.json` file. That explains why so many people were getting the indentation wrong in their PRs :grin:

Thx for fixing it, @blove. Can you please split out the indentation into a separate commit?
Also, make sure the commit messages start with `docs: ...` (not `docs(aio): ...`).

**Comment by blove** [comment]
@gkalpak I've corrected this PR to remove the indentation correction and updated the commit message. I also create #26623 to resolve the indentation issue.

FWIW, I followed the commit message instructions in the CONTRIBUTING.md doc, which seems to indicate that you should specify a scope.

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Thx, @blove. s mentoned in `CONTRIBUTING.md` _"the header is mandatory and the scope of the header is optional"_.
(These generic docs changes is one of the cases, where there should be no scope.)

Anyway, thx for making the changes 👍

**Comment by gkalpak** [comment]
Thx, @blove. s mentoned in `CONTRIBUTING.md` _"the header is mandatory and the scope of the header is optional"_.
(These generic docs changes is one of the cases, where there should be no scope.)

Anyway, thx for making the changes 👍

**Comment by gkalpak** [comment]
Thx, @blove. s mentoned in `CONTRIBUTING.md` _"the header is mandatory and the scope of the header is optional"_.
(These generic docs changes is one of the cases, where there should be no scope.)

Anyway, thx for making the changes 👍

**Comment by gkalpak** [comment]
Thx, @blove. s mentoned in `CONTRIBUTING.md` _"the header is mandatory and the scope of the header is optional"_.
(These generic docs changes is one of the cases, where there should be no scope.)

Anyway, thx for making the changes 👍

**Review by gkalpak — APPROVED** [review]

**Review by gkalpak — APPROVED** [review]

**Pull request closed without merging**
