### PR TITLE
feat(aio): add brand and concept icons, img style class more flexible

### PR DESCRIPTION
**Pull request by sjtrimble**
Changes visible here: https://pr23589-ea0aad6.ngbuilds.io/presskit

Adding brand and concept icons to Press Kit page and made img style more flexible to support differently proportioned (non-square) images

Planning on redesigning this page in the future so it's not a long list of icons but wanted to get the icons up so they are accessible to the community.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by beeman** [comment]
Great work on these icons, I think they look amazing! 

When I tried to upload the svgs to icomoon.io it appeared that there was one icon with a stroke that needed to be converted to a fill.

I don't know enough about svg to know the difference, but I figured I'd let you know as the rest of the icons don't seem to have this. :)

image

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
@sjtrimble The PressKit page looks awesome!

I may be wrong but I am pretty sure that all of the `app.po.ts` files were not supposed to be there?

**Comment by sjtrimble** [comment]
@petebacondarwin I have no idea where or how the `app.po.ts` files got there?? What do you recommend I do?

@beeman I believe both fill and stroke are supported by SVG, so I don't think it will make a big difference, but it would be good to update for consistency purposes 👍

**Comment by petebacondarwin** [comment]
@sjtrimble:

```bash
git checkout presskit-icons
# now delete all of those files
git commit -a --fixup HEAD
git push
```

**Comment by gkalpak** [comment]
> # now delete all of those files

`git rm aio/content/examples/**/e2e/app.po.ts` :wink:

**Comment by petebacondarwin** [comment]
@gkalpak - be careful - not all of them should be deleted!! 😱

**Comment by gkalpak** [comment]
😱

**Comment by gkalpak** [comment]
😱 Really? Which ones do we need?

**Comment by petebacondarwin** [comment]
Actually I take that back. I have some on my local machine. But I think that they are all blocked by `.gitignore` so they shouldn't get committed.

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Both commits are from valid CLA developers.

**Comment by sjtrimble** [comment]
Thanks @petebacondarwin :) you da best

**Pull request closed without merging**
