### PR TITLE
10.1.x

### PR DESCRIPTION
**Pull request by aikithoughts**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by aikidave** [comment]
This is a patch commit from #38353

**Review by atscott — CHANGES_REQUESTED** [review]
@aikidave - did you want this PR to only go to `10.1.x` branch? It looks like this change should probably go there and `master`

**Comment by aikidave** [comment]
Hi @atscott ! It's already in master, so we just need the change reflected here.

**Comment by atscott** [comment]
> Hi @atscott ! It's already in master, so we just need the change reflected here.

Ah, sorry I missed the comment about it being a patch of the other commit!

**Review by atscott — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: global-approvers

**Pull request closed without merging**
