### PR TITLE
docs: fix style guide order and the corresponding examples

### LINKED ISSUE #37030: Angular style guide documentation page is not showing sections in sequence.
# 📚 Docs or angular.io bug report

### Description

In Angular style guide(https://angular.io/guide/styleguide) I found one problem the topics are not in sequence example after section 2-5 it shows section 5-2 and then 2-7 and then 2-6. 

when looking at a broader perspective both 5-2 and 2-7 seem to be talking about component selector name. then this different section makes me confuse especially when I am a new user.

### What's the affected URL?**
https://angular.io/guide/styleguide

### Reproduction Steps**
open the style guide URL mentioned, go to section 2-5 (Bootstrapping) after this it shows section 05-02 instead of 2-6. 

### Expected vs Actual Behavior**
when I open the style guide URL mentioned, go to section 2-5 (Bootstrapping) after this it should show section 2-6 instead of 5-2.  

## 📷Screenshot
Screenshot 2020-05-09 at 11 48 14 PM

## 🔥 Exception or Error

</code></pre>

### Anything else relevant?
If this is done intentionally would like to know the reason.

### PR DESCRIPTION
**Pull request by sonukapoor**
This commit fixes the number ordering of the style guide. It contained
missing sections.

Closes #37030

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 37030

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by sonukapoor** [comment]
@IgorMinar I tried to bring the style guide into the right sequence and order. I assume some of the sections were removed, which caused the sequence to break off at some point. To bring the guide into the correct order, it would make sense to fix the accompanying code examples for each section as well. I did both of these in the same PR, however, it could have also be broken down into multiple PRs/Commits. Let me know what you think and if you want to keep it in the current format or if you want to change it to multiple commits.

**Comment by darpankumar** [comment]
@sonukapoor why this thing requires this much big change. multiple files are deleted

**Review by gkalpak — CHANGES_REQUESTED** [review]
I am afraid this is not a desirable way to address #37030. Although I am not sure what it is, I suspect there is some reasoning behind naming the "rules" a certain way. Having sequential rules should not be a requirement (nor a goal).

More importantly, people (or even tolling such as `codelyzer`) might have links to these rules and renaming them like this will break things and cause great confusion.

##
If you want to fix #37030, you could try looking at the git history (e.g. via `git blame`) and try to figure out how/why `05-02` ended up between `02-05` and `02-07`.
- Was it always there? Was it moved there is a subsequent PR? Why?
- Did there used to be a `02-06` rule? Was it removed? Why?

Note that part of the git history might leave in the old (now archived) repo where angular.io source code lived before being moved into `angular/angular`: https://github.com/angular/angular.io

**Comment by sonukapoor** [comment]
@gkalpak Thanks for the information. 

I have looked into the original changes using `git blame` and found out that it was changed about two years ago. The fix in the [PR](https://github.com/angular/angular/pull/22571) was to group the `Component Selectors` section into the [`Naming`](https://angular.io/guide/styleguide#naming) section. In the same PR, there was a discussion about the ordering and it is unfortunately not clear why that format was used ([here](https://github.com/angular/angular/issues/22081#issuecomment-367758634), and [here](https://github.com/angular/angular/issues/22081#issuecomment-368086474)).  You are also right about the usage in `Codelyzer` - this has been mentioned there as well. To be safe, it was decided to leave the existing ordering as is and add the new section with a new number.

**Comment by gkalpak** [comment]
Thx for looking into it, @sonukapoor (and sorry you had to do all that work 😞).

**Comment by sonukapoor** [comment]
> Thx for looking into it, @sonukapoor (and sorry you had to do all that work 😞).

No worries. Part of the learning process.

**Pull request closed without merging**
