### PR TITLE
feat(forms): add the submitted flag to NgForm & NgFormModel

### PR DESCRIPTION
**Pull request by antonmoiseev**
- **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  Adds the `submitted` flag to the Forms API
- **What is the current behavior?** (You can also link to an open issue here)
  The feature is described in #2960
- **What is the new behavior (if this is a feature change)?**
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
  No breaking changes
- **Other information**:
  Previously closed PR https://github.com/angular/angular/pull/5656

### CODE REVIEW

**Comment by antonmoiseev** [comment]
The failing issue seems unrelated to this PR

**Comment by kara** [comment]
@antonmoiseev Can you rebase this?

**Comment by fxck** [comment]
Thank you!!

**Comment by rmcsharry** [comment]
In Angular 1.x it was possible to set submitted = false. With this code, there is only a getter, so we cannot set the value from code. Why is that useful?

In some situations you want a cancel button to 'dismiss' the form and abandon the input/edit operation. However, if a field has focus that will cause validation to fire.

A good example/use case is a form inside a modal, where the cancel button also closes the modal. However, if the validation fires, the cancel button must be clicked twice. SO question on this [here](https://stackoverflow.com/questions/46411390/angular-form-validation-activated-before-cancel-button-is-triggered?rq=1).

I think if in the onCancel click handler we could

`this.form.submitted = false;
`
wouldn't that then prevent the validation code from firing?

**Pull request closed without merging**
