### PR TITLE
docs(router): fix mdn links in router guide

### PR DESCRIPTION
**Pull request by kaznovac**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

mdn links on https://angular.io/guide/router are wrongly rendered, and first one does not lead to expected page

## What is the new behavior?
correct links and render

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
Note to the Caretaker: the CI failure is unrelated, the PR is ready for the merge.

**Review by AndrewKushnir — APPROVED** [review]
@kaznovac thanks for improving Angular docs!

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit ec5cb0bb5494b0c52e84d13da209765a021993c2.

**Comment by kaznovac** [comment]
it's a pleasure

thanks for review @AndrewKushnir & @dylhunn thanks for the merge

**Pull request closed without merging**
