### PR TITLE
fix(zone.js): setTimeout patch should clean tasksByHandleId cache

### LINKED ISSUE #40387: Memory leak in tests with zone.js >= 0.9.0
# 🐞 bug report

### Affected Package

 The issue is caused by package:
**zone.js: 0.9.0**

### Is this a regression?

Yes. The tests didn't cause Chrome to crash.

### Description
When I've upgraded zone.js from 0.8.26 to 0.9.0 or higher, this problem appeared. I have 3000 unit/integration tests. We use heavily dynamic component creation. Our tests currently cannot be executed at once, because zone.js(the timers patch) keeps a reference to tasks created from **setTimeout()** in **tasksByHandleId** in the patch method.  When I call **clearTimeout()** in ngOnDestroy() I can see that the task is not removed from tasksByHandleId because it's status is **notScheduled**.

## 🔬 Minimal Reproduction
https://github.com/belchevgb/zonejs-memory-leak

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.6
Node: 14.3.0
OS: win32 x64

Angular: 11.0.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.6
@angular-devkit/build-angular   0.1100.6
@angular-devkit/core            11.0.6
@angular-devkit/schematics      11.0.6
@angular/cli                    11.0.6
@schematics/angular             11.0.6
@schematics/update              0.1100.6
rxjs                            6.6.3
typescript                      4.0.5
zone.js                         0.10.2
</code></pre>

**Anything else relevant?**
[SNAPSHOT](https://drive.google.com/file/d/1T7tUuZZPBdiOS1amHcBLWNXWhRNzArKo/view?usp=sharing)
image

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Close #40387

Currently zone.js patches `setTimeout` and keeps a `tasksByHandleId` map to keep `timerId` <-> `ZoneTask` relationship. This is needed so that when `clearTimeout(timerId)` is called, zone.js can find the associated `ZoneTask`. Now zone.js set the `tasksByHandleId` map in the `scheduleTask` function, but if the `setTimeout` is running in the `FakeAsyncZoneSpec` or any other `ZoneSpec` with `onScheduleTask` hooks. The `scheduleTask` in `timer` patch may not be invoked.

For example:

```
fakeAsync(() => {
  setTimeout(() => {});
  tick();
});
```

In this case, the `timerId` kept in the `tasksByHandleId` map is not cleared.
This is because the `FakeAsyncZoneSpec` in the `onScheduleTask` hook looks like this.

```
onScheduleTask(delegate, ..., task) {
  fakeAsyncScheduler.setTimeout(task);
  return task;
}
```

Because `FakeAsyncZoneSpec` handles the task itself and it doesn't call `parentDelegate.onScheduleTask`,
therefore the default `scheduleTask` in the `timer` patch is not invoked.

In this commit, the cleanup logic is moved from `scheduleTask` to `setTimeout` patch entry to
avoid the memory leak.

### CODE REVIEW

**Review by mhevery — CHANGES_REQUESTED** [review]
- [x] I have updated the PR text for grammar. Please update the commit message to match.
- [x] The change seems reasonable, but it needs a test. Could you add one.

**Comment by JiaLiPassion** [comment]
@mhevery , thanks for the review, I have updated the commit message, but since this `tasksByHandleId` is an internal variable, I am not sure how to verify it by the test case, I have tested it with `debugger` in the chrome dev tool.

**Comment by mhevery** [comment]
> @mhevery , thanks for the review, I have updated the commit message, but since this `tasksByHandleId` is an internal variable, I am not sure how to verify it by the test case, I have tested it with `debugger` in the chrome dev tool.

I don't think you need to have `tasksByHandleId` public to test it. I assume that without this change there is a scenario which miss-behaves. Could we describe that scenario in the test?

**Comment by JiaLiPassion** [comment]
@mhevery , yeah, I understand your point, now most cases behave correctly even the `tasksByHandleId` is not cleared, I will try to create a failure case.

**Comment by JiaLiPassion** [comment]
@mhevery , I have added one test case to describe the fix, so this issue will only cause memory leak when using `fakeAsync() ` with `setTimeout()`, the behavior from user's perspective is totally the same, so I use some hack way to test the internal behavior, please review, thanks.

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:355177594:BASE:355177627:1612285259326:23f091f)

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:355177594:BASE:356289095:1612806945170:5a63433c)

**Pull request closed without merging**
