### PR TITLE
feat(adev): rename file in code editor

### PR DESCRIPTION
**Pull request by mikalcallahan**
feat(adev): rename file in code editor

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Address [52652](https://github.com/angular/angular/issues/52652)

## What is the new behavior?
The ability to rename files in the docs code editor

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Demo

https://github.com/angular/angular/assets/14881167/cac89984-e76e-4171-bcc4-a182fbeabe8e

### CODE REVIEW

**Comment by JeanMeche** [comment]
Thank for working on this !  
Don't you think `app.component.ts` shouldn't have an edit button ? Right now editing its filename is a no-op.

**Comment by mikalcallahan** [comment]
@JeanMeche 100% agree. The logic to determine if a file can be delete or renamed is based on this declaration `export const REQUIRED_FILES = new Set(['src/main.ts', 'src/index.html']);`

I'll add `src/app.component.ts` to the set

**Comment by JeanMeche** [comment]
Can you also have a look at the broken tests ?

**Comment by mikalcallahan** [comment]
@JeanMeche just saw you restarted the jobs. Looks like I still need to [fix the commit message](https://github.com/angular/angular/actions/runs/8484612565/job/24023976673), then it should be good to go

**Review by JeanMeche — APPROVED** [review]
Thank for the improvement.

**Comment by mikalcallahan** [comment]
@JeanMeche Just saw you updated the commit message for me, thanks! I was having trouble getting the proper format/description for `docs` but I get it now, `docs(docs-infra): **message**` and _not_ merging `main` into the feature branch

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 49d3062c0eeaf778fb34f10441239b7549f620a3.

**Pull request closed without merging**
