### PR TITLE
feat(common): Add URL support to HttpClient

### PR DESCRIPTION
**Pull request by felipecrp**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Httpclient does not support URL.

Issue Number: #45497

## What is the new behavior?

Httpclient support URL.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I tried to make minor changes in the PR. Hence I updated only the main HttpClient and transformed the URL object to a string to match other internal interfaces.

### CODE REVIEW

**Comment by felipecrp** [comment]
Added support to URL in HttpClient.
Fixes #45497

**Comment by crisbeto** [comment]
There's a PR for this already at https://github.com/angular/angular/pull/46470

**Comment by felipecrp** [comment]
Hi, I know, but #46470 last activity was on Jun 23, 2022, and I thought it was abandoned. Since  #45497 is categorized as a feature for newcomers, I created a small patch to handle the issue, changing the minimal need to HttpClient accept the URL as a parameter.

**Comment by felipecrp** [comment]
However, if the other PR (#46470) is ready, I can abandon this PR.

**Comment by felipecrp** [comment]
I just fixed the tests and I think this PR is ready.

**Comment by JeanMeche** [comment]
We'll Keep the origin PR If we'd like to land this feature ! Thanks for proposing it though !

**Pull request closed without merging**
