### PR TITLE
chore(changelog): fixed link to issue

### PR DESCRIPTION
**Pull request by valorkin**
Just a link fix

### CODE REVIEW

**Comment by PascalPrecht** [comment]
@valorkin could you please update your commit message to match the conventions?

**Comment by valorkin** [comment]
@PascalPrecht like this?

**Comment by PascalPrecht** [comment]
I'd use `chore()` instead of `docs()` tho, otherwise looks good!

**Comment by valorkin** [comment]
@PascalPrecht done

**Comment by vicb** [comment]
dup of #4767

**Pull request closed without merging**
