### PR TITLE
feat(aio): hard code home link image element

### LINKED ISSUE #15017: aio: Hard code the "Home" link in the template
* Make it show the Angular logo
* Remove the item from the dynamic navigation.json

### PR DESCRIPTION
**Pull request by petebacondarwin**
Fixes #15017

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
The code LGTM (the outcome looks ugly, but I assume looking nice it outside the scope of this PR 😛).

**Comment by petebacondarwin** [comment]
@gkalpak is it certainly outside of my CSS skill set :-(
I decided I could spend my time more profitably

**Comment by chuckjaz** [comment]
This change needs to be rebased.

**Comment by petebacondarwin** [comment]
@chuckjaz - rebased

**Pull request merged**
