### PR TITLE
docs(ivy): remove duplicated words in architecture doc

### PR DESCRIPTION
**Pull request by bsdfzzzy**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by trotyl** [comment]
The type should actually be `docs(ivy): ...`

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update git commit message to `docs(ivy): remove duplicated words in architecture doc`

**Comment by bsdfzzzy** [comment]
@brandonroberts Finish.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Caretaker note: This is a docs only change, so should not impact g3. Please run presubmit.

**Pull request closed without merging**
