### PR TITLE
update README.md links to target angular.dev documentation

### LINKED ISSUE #52771: Update README.md links to the new documentation
### Describe the problem that you experienced

The current README.md has several links that redirect on https://angular.io/. 
To ensure the adoption of the new documentation, I believe it can be better that most of the links redirect on https://angular.dev/ instead.

### Enter the URL of the topic with the problem

https://github.com/angular/angular

### Describe what you were looking for in the documentation

In the following screenshots, every links underlined in red redirect to the "old" documentation (https://angular.io/) instead of the new (https://angular.dev/)

### Describe the actions that led you to experience the problem

_No response_

### Describe what you want to experience that would fix the problem

_No response_

### Add a screenshot if that helps illustrate the problem

Screenshot 2023-11-10 at 07 55 01
Screenshot 2023-11-10 at 07 55 11
Screenshot 2023-11-10 at 07 55 22

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by sdedieu**
Change the angular.io links to target the new angular.dev website

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: fixes #52771 & #52627

## What is the new behavior?

Links now target the new documentation website.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by devversion** [comment]
deferring this to dev-rel. @twerske @MarkTechson

**Comment by sdedieu** [comment]
> deferring this to dev-rel. @twerske @MarkTechson

I'm honored 😃

**Review by twerske — APPROVED** [review]

**Comment by twerske** [comment]
> > deferring this to dev-rel. @twerske @MarkTechson
> 
> I'm honored 😃

Looks great to me! Thank you for the contribution!

**Review by MarkTechson — APPROVED** [review]
LGTM.

Thanks so much for doing this!

**Review by devversion — APPROVED** [review]

**Review by jessicajaniuk — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit f51ce68bf5a27da7b18f49f9292722ff1374a9b3.

**Pull request closed without merging**
