### PR TITLE
docs: move tour of heroes tutorial to a subdirectory

### PR DESCRIPTION
**Pull request by bob-watson**
This is to prepare the documentation directories for future tutorials organized by directory. This move changes the URLs of the Tour of Heroes tutorial pages, so the tests and other documents that link to those topics have been updated and redirections were also added to send the old URLs to the correct pages.

This PR also moves the Angular libraries topics from the Tutorials section to the Developer guides section in the ToC. No URLs were changed in that move.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The tutorials directory has only Tour of Heroes content.

## What is the new behavior?
The tutorials directory has a subdirectory with the Tour of Heroes content so that future tutorials can be added to the tutorials directory and organized by sub-directory

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
Other than the one typo, LGTM!

**Review by MarkTechson — APPROVED** [review]
LGTM 🚀

**Review by AndrewKushnir — APPROVED** [review]

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit a6d953e1454c7eef04a66bd77fe10891df0f4a04.

**Pull request closed without merging**
