### PR TITLE
refactor(http): use shared code from public 'angular2/angular2' names…

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
…pace

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
So, I'm not sure if we can do this without creating circular deps / problems for tree-shaking, BUT this would allow us to create the http bundle without pulling in the entire angular core

//cc: @IgorMinar @jeffbcross

**Comment by pkozlowski-opensource** [comment]
If this change is about correct, I'm going to send similar PR(s) for the router

**Comment by vicb** [comment]
LGTM

**Comment by rkirov** [comment]
LGTM. I don't see how would circular deps be a concern, since `angular2` shouldn't ever depend on `http`.

Also tree-shaking is not supported by any tools currently. In fact producing opaque bundles with large set of exposed APIs is an opposing goal to a tight tree-shaking, so I wouldn't worry about that yet.

**Pull request closed without merging**
