### PR TITLE
fix(aio): do not rewrite /styleguide URL in Service Worker

### LINKED ISSUE #22078: aio: redirect https://angular.io/styleguide -> guide/styleguide
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This old v1, once valid styleguide URL, [https://angular.io/styleguide](https://angular.io/styleguide), now is a 404.

Minko Gechev tells me

>This breaks a lot of releases of codelyzer + the printed content of my book.

It used to redirect to its current location, [https://angular.io/guide/styleguide](https://angular.io/guide/styleguide).

Redirects were recently updated. Maybe there is a much bigger regression here?

## Expected behavior

* Should redirect.
* Should confirm that our old v1 to v2 redirects are still working.

## Minimal reproduction of the problem with instructions

Go to [https://angular.io/styleguide](https://angular.io/styleguide)

### PR DESCRIPTION
**Pull request by petebacondarwin**
This URL needs to be redirected via the server, so
we must exclude it from being rewitten.

Closes #22078

### CODE REVIEW

**Comment by petebacondarwin** [comment]
The firebase redirect was setup correctly, which you can confirm by hitting the server directly with a request for `/styleguide` but our Service Worker was trying to rewrite the URL to `index.html` as this rule had got lost during the big vowel shift.

**Review by gkalpak — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]

**Comment by mhevery** [comment]
@petebacondarwin This PR does not cleanly apply to `5.2.x` branch. Can you break it into two separate PRs, once fro `master` and one for `5.2.x`

**Comment by IgorMinar** [comment]
It doesn't not? That's concerning. Did we forget to (mark for) cherry-pick
some PR?

**Comment by petebacondarwin** [comment]
We never landed the original Firebase redirect fixes on stable - we were trying it on master. I am putting together a PR for that and this against stable.

**Pull request closed without merging**
