### PR TITLE
fix(WebWorker): Fix PostMessageBusSink and Source undefined error.

### LINKED ISSUE #7156: PostMessageBusSink and PostMessageBusSource are undefined in Injectable Metadata
The [PostMessageBus](https://github.com/angular/angular/blob/master/modules/angular2/src/web_workers/shared/post_message_bus.ts#L17)'s constructor tries to inject `PostMessageBusSink` and `PostMessageBusSource` but they haven't been defined yet.

### PR DESCRIPTION
**Pull request by jteplitz**
Closes #7156

### CODE REVIEW

**Comment by jteplitz602** [comment]
LGTMd by @rkirov

**Comment by jeffbcross** [comment]
All Travis jobs passed except one, which was because of a flake. I restarted it, but I'm going to go ahead and assign to @matsko for merging.

**Comment by vsavkin** [comment]
Merged via https://github.com/angular/angular/commit/01fe7f5fac7b768668f10aa725e6207379bff059

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166467.
------------------------------------------------------------------------------------------------------------


[[1afb9097628239665e9ef3725dc2d7863bae774d-673073427]]

**Pull request closed without merging**
