### PR TITLE
docs: move ngIndia 2020 to past events on events page

### PR DESCRIPTION
**Pull request by ajitsinghkaler**
ng india was an outdated event removed it from upcoming events on the events page and added to already presented events

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

ngIndia is in upcoming events. Its already completed

Issue Number: N/A

## What is the new behavior?
Added ng India to already presented events

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Thx, @ajitsinghkaler! Good catch :+1:

<sub>(I think it would make sense to have a widget that would show the events as upcoming or past depending on their dates and only have a list of events. I remember we have discussed that in the past, but I couldn't find the discussion.)</sub>

##
Can you update the commit message to be more specific. (This helps when scanning going through git history trying to find a particular commit.) E.g.:

> docs: move ngIndia 2020 to past events on events page

**Comment by ajitsinghkaler** [comment]
@gkalpak made the changes

**Comment by ajitsinghkaler** [comment]
If I get time I'll try to implement that widget

**Comment by gkalpak** [comment]
**merge-assistance:** Global approval for this docs-only change.

**Pull request closed without merging**
