### PR TITLE
docs(core): add advanced use case example

### PR DESCRIPTION
**Pull request by BallisticPain**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by BallisticPain** [comment]
@googlebot I signed it!

**Comment by sonukapoor** [comment]
@BallisticPain Thanks for submitting the PR. The `ci/circleci:lint` job seems to fail, because of the way the file is formatted. Could you please run the below command (in the root folder) to format the file and add a `fixup! docs(core): Added advanced use case example...` commit?

```
yarn ng-dev format files packages/core/src/metadata/ng_module.ts
```

**Comment by BallisticPain** [comment]
@sonukapoor Apologies, I didn't realize I had a response already until I explicitly checked. Will work on your desires immediately.

**Comment by BallisticPain** [comment]
Okay I'm going to pull upstream and rebase my branch... Hopefully that'll fix any remaining issue(s) with the CI.

**Comment by BallisticPain** [comment]
I look forward to any input (and I intend to check back sooner than 23 days lol) and feedback to get this merged. Thanks for your efforts!

**Comment by sonukapoor** [comment]
Thanks @BallisticPain. The formatting error is gone now 👍 , but there is an error with the commit message. 

> The commit message body contains lines greater than 120 characters

Can you please break them up into 120 characters or less?
Once you are done, run `yarn lint` inside the `aio` folder to verify that everything looks good.

**Comment by BallisticPain** [comment]
So I pushed before I ran the `yarn lint` command. Here's my output though ... It appears to be passing?
```
┌─[ballisticpain@BallisticDevelopment] - [~/Development/angular/aio] - [Mon Sep 28, 00:36]
└─[$] <git:(patch-1)> yarn lint
yarn run v1.22.5
$ yarn check-env && yarn docs-lint && ng lint && yarn example-lint && yarn tools-lint
$ yarn ~~check-env
$ node scripts/check-environment
$ yarn aio-check-local
$ node tools/ng-packages-installer check .
$ eslint --ignore-path="tools/transforms/.eslintignore" tools/transforms
Linting "site"...
All files pass linting.
$ tslint --config "content/examples/tslint.json" "content/examples/**/*.ts" --exclude "content/examples/styleguide/**/*.avoid.ts"
Warning: The 'deprecation' rule requires type information.
$ tslint --config "tools/tslint.json" --project "tools/firebase-test-utils"
✨  Done in 30.03s.
```

**Review by AndrewKushnir — CHANGES_REQUESTED** [review]
Hi @BallisticPain, thanks for extending the docs with additional examples.

I think there is an easier way to achieve this, see this [Stackblitz demo page](https://stackblitz.com/edit/angular-ivy-sxa63u?file=src%2Fapp%2Fapp.module.ts). The thing is that the `ApplicationRef.bootstrap` has a second argument that allows passing the node where a given component should be bootstrapped (see [ApplicationRef.bootstrap docs](https://angular.io/api/core/ApplicationRef#bootstrap)):

```
@NgModule({
  imports:      [ BrowserModule ],
  declarations: [ AppComponent ]
})
export class AppModule {
  constructor(private resolver: ComponentFactoryResolver) {}

  ngDoBootstrap(appRef: ApplicationRef) {

    // Declare components that we want to bootstrap on a page.
    const componentsToBootstrap = [ AppComponent ];

    componentsToBootstrap.forEach((component: any) => {
      const factory = this.resolver.resolveComponentFactory(component);

      // Find DOM nodes matching component's selector.
      const nodes = document.querySelectorAll(factory.selector);

      // Bootstrap a component for each DOM node found.
      nodes.forEach(node => appRef.bootstrap(factory, node));
    });
  }
}
```
It also looks like the [ApplicationRef.bootstrap example](https://angular.io/api/core/ApplicationRef#bootstrap) is incorrect, the `bootstrapModule` takes an NgModule as an argument, but a Component was used instead. I think we can improve the docs by doing the following:

- Update the [Bootstrapping guide](https://angular.io/guide/bootstrapping) with the use-case mentioned above and a possible implementation code (see above)
- Update the `ApplicationRef.bootstrap` docs to use a proper example
- Also mention that calling `bootstrap` actually bootstraps a component into a first matching node, so if there are multiple nodes that match component selector, the `ApplicationRef.bootstrap` should be called multiple times (and add a reference to a new section in `Bootstrapping guide` created at step 1)

I think that should improve the docs and make this information more discoverable in the future.

Thank you.

**Comment by BallisticPain** [comment]
@AndrewKushnir 
I'm sure there is some mistake in the StackBlitz as it does not include any of the code in your post and nor does it work (without it). I also attempted to add your code to the [StackBlitz](https://stackblitz.com/edit/angular-ivy-dlpsb6?file=src/app/app.module.ts) and it still does not work.

Also, I would be happy to attempt to provide any updates to any section of documentation or wording you feel would be better or more beneficial. Especially if it's more concise than the code example I provided.

I look forward to your response.

Thanks!

**Comment by BallisticPain** [comment]
Upon further playing, I was able to get your code to work... It's now saved in my StackBlitz linked above.

**Comment by AndrewKushnir** [comment]
@BallisticPain,

Thanks for the reply, it looks like I didn't save the code in my Stackblitz project.

I think we should improve the docs on that topic and it'd be great if you could help with it.

Here is my proposal (it's slightly different from the one I posted yesterday):

- Update the [ApplicationRef.bootstrap](https://angular.io/api/core/ApplicationRef#bootstrap) docs:
  - In the `Bootstrap process` section mention that in case multiple elements match component's selector, the first matched element will be used as a host element.
  - Improve the `Usage Notes` section with more information and better examples, specifically:

     - Remove existing example (I believe it's not correct and also it doesn't actually contain the `bootstrap` usage)
     - Add a simple example on how `ApplicationRef.bootstrap` can be used with one argument, similar to what we have in [DoBoostrap interface docs](https://angular.io/api/core/DoBootstrap#usage-notes), see `Example 1` below.
     - Add an example on how `ApplicationRef.bootstrap` can be used with the second argument (i.e. the `rootSelectorOrNode`), similar to what we have in [DoBoostrap interface docs](https://angular.io/api/core/DoBootstrap#usage-notes), see `Example 2` below.

- Update the [DoBootstrap interface docs](https://angular.io/api/core/DoBootstrap#usage-notes) to include a note into the `Usage notes` section that would contain a link to the ApplicationRef.bootstrap docs, something like this:
```
An example below uses [ApplicationRef.bootstrap](link) to render the `AppComponent` component on a page. More information on the `ApplicationRef.bootstrap` usage and available options can be found on the [ApplicationRef.bootstrap](link) page.
```

- Update the `The bootstrap array` section of the [Bootstrapping guide](https://angular.io/guide/bootstrapping#the-bootstrap-array) to mention that for more advanced bootstrap use-cases the `ApplicationRef.bootstrap` function can be used and provide a link to that function.

I believe in this case we'll avoid content duplication, unnecessary complication of the guides and add links between related part of documentation.

Please let me know if you have any questions.

Example 1:
```typescript
@Component({
  selector: '#app-root',
  template: 'Hello World'
})
class AppComponent {}

@NgModule({
  declarations: [AppComponent]
})
class AppModule implements DoBootstrap {
  ngDoBootstrap(appRef: ApplicationRef) {
    // Bootstraps AppComponent into an element that matches component's selector.
    appRef.bootstrap(AppComponent);
  }
}
```

Example 2:
```typescript
@NgModule({
  declarations: [AppComponent]
})
class AppModule implements DoBootstrap {
  ngDoBootstrap(appRef: ApplicationRef) {
    // Bootstraps AppComponent into an element with the `root-element-id` id,
    // which is different than the one defined in component's selector.
    appRef.bootstrap(AppComponent. '#root-element-id');

     // Second argument might also be a DOM node.
     const rootNode = document.getElementById('root-element');
     appRef.bootstrap(AppComponent, rootNode);
  }
}
```

**Comment by BallisticPain** [comment]
@AndrewKushnir I'll be working on this shortly. Was out of town, but getting back in the saddle. Thanks for the more detailed feedback!

**Comment by AndrewKushnir** [comment]
Closing this PR due to the lack of reply. Please reopen if needed.

**Pull request closed without merging**
