### PR TITLE
feat(zone.js): several enhancement of `flush()` and `tickRAF()` for `fakeAsync`

### PR DESCRIPTION
**Pull request by JiaLiPassion**
- fakeAsyncZone.flush() should flush `requestAnimationFrame`  and scheduled interval.
Current `FakeAsyncZoneSpec.flush()` behavior is not consistent in some use cases.

Close #43875

1. `flush()` is not flusing `requestAnimationFrame`. But `tick(16)`
trigger both `requestAnimationFrame()` and `macrotasks`
2. `flush()` will not trigger `setInterval()` in some cases.

```
it('test timeout and interval', fakeAsync(() => {
  let timeoutCalled = false;
  let intervalCount = 0;
  setTimeout(() => timeoutCalled = true, 50);
  setInterval(() => {
    intervalCount ++;
  }, 50);
  flush();
  expect(timeoutCalled).toBeTrue();
  expect(intervalCounter).toBe(1);
});
```

In this case, both `setTimeout` and `setInterval` callbacks will be triggered.

But consider the following cases.

```
it('test interval', fakeAsync(() => {
  let intervalCount = 0;
  setInterval(() => {
    intervalCount ++;
  }, 50);
  flush();
  expect(intervalCounter).toBe(1);
});
```

this case will fail, since all remaining tasks are `interval`, which
is confusing to the user.

So this PR make the following changes.
1. `flush()` will also trigger `requestAnimationFrame` callbacks.
2. `flush()` will also trigger all `scheduled` tasks.

So consider the following test case

```
it('test interval', fakeAsync(() => {
  let intervalCount = 0;
  setInterval(() => {
    intervalCount ++;
  }, 50);
  flush();
  expect(intervalCounter).toBe(1);
});
```
The case will success, the `flush()` will trigger the scheduled
macrotask(`setInterval` in this case), and will not continue to
`flush` since the remaing tasks are all `interval tasks`.

- feat(zone.js): add tickRAF() to fakeAsyncZone

Now in the `FakeAsyncZoneSpec`, to trigger the `requestAnimationFrame`
callback, we need to call `tick(16)` which is not a good degin since
we need to reply on this `16` magic number, and we may handle the
requestAnimationFrame differently in the future, so in this PR
add a new API `tickRAF()`, internally it is still calling `tick(16)`
to keep the backward compatibility.

NOTE: `aio` document updates need to wait for the new `tickRAF()` API released with the new version of `zone.js`.

### CODE REVIEW

**Review by dylhunn — DISMISSED** [review]
reviewed-for: fw-core, fw-testing

**Comment by dylhunn** [comment]
@JiaLiPassion Looking at the presubmit, this causes a large number of failures. Here's a typical one, snipped of g3 details:

```
TypeError: doTick is not a function
Scheduler</Scheduler.prototype.flushNonPeriodic@zone.js/lib/zone-spec/fake-async-test.ts?l=294
Scheduler</Scheduler.prototype.flush@zone.js/lib/zone-spec/fake-async-test.ts?l=252
FakeAsyncTestZoneSpec</FakeAsyncTestZoneSpec.prototype.flush@zone.js/lib/zone-spec/fake-async-test.ts?l=540
flushInternal@angular2/testing/catalyst/helpers.ts?l=1229
callInFakeAsyncZone@angular2/testing/catalyst/helpers.ts?l=1514
flush@angular2/testing/catalyst/helpers.ts?l=1630
...
Zone</_ZoneDelegate</_ZoneDelegate.prototype.invoke@zone.js/lib/zone.ts?l=1145
FakeAsyncTestZoneSpec</FakeAsyncTestZoneSpec.prototype.onInvoke@zone.js/lib/zone-spec/fake-async-test.ts?l=678
Zone</_ZoneDelegate</_ZoneDelegate.prototype.invoke@zone.js/lib/zone.ts?l=1142
Zone</Zone</Zone.prototype.run@zone.js/lib/zone.ts?l=825
wrapTestInFakeAsyncZone/<@angular2/testing/catalyst/helpers.ts?l=764
<Jasmine>
Zone</_ZoneDelegate</_ZoneDelegate.prototype.invokeTask@zone.js/lib/zone.ts?l=1182
Zone</Zone</Zone.prototype.runTask@zone.js/lib/zone.ts?l=875
drainMicroTaskQueue@zone.js/lib/zone.ts?l=1384
```

**Comment by JiaLiPassion** [comment]
@dylhunn , thank you for the review, I updated the PR to avoid the API breaking, could you re-run the presubmit?

**Comment by dylhunn** [comment]
@JiaLiPassion I have started a [fresh presubmit](http://test/OCL:437532106:BASE:437532140:1648357156145:5a6b867f), and I'll post back with results..

**Pull request closed without merging**
