### PR TITLE
feat(common): Allow passing metadata to HttpClient options

### LINKED ISSUE #18155: Allow passing misc data to http client options
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently when using a http interceptor you cannot pass meta data about the request to the interceptor

## Expected behavior

To be able to pass random data to the http interceptor. Currently the options object is so strongly typed that you cannot pass extra data to it. The proposal would be to add a `meta` (name needs bikeshedding) property with type `any` to the http request options that can be used for this purpose.

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?

```
// tell a caching interceptor to only cache if this is true
this.http.get('/path', {meta: {cache: true}})

// tell an interceptor not to add the `Authorization` for this request only
this.http.get('/path', {meta: {skipAuthorization: true}})
```

## Environment

<pre><code>
Angular version: 4.3.0

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by wKoza**
closes #18155

## PR Type
What kind of change does this PR introduce?

Allow passing metadata to HttpClient options

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by chenkie** [comment]
Really looking forward to this 👍

**Comment by rtrompier** [comment]
We really need this PR guys ;)

**Comment by aksdevac** [comment]
why this is moved to backlog, is this being re-implemented by angular team?

**Comment by alxhub** [comment]
There are a couple of issues that prevent us from merging this PR.

Technically, the PR is incomplete - it only adds `metadata` to the constructor of `HttpRequest`, but does not actually capture or propagate the values. There are no tests which validate the new feature (probably because it's not yet implemented).

On a broader note, metadata is something that we'd really like to do, but don't have the bandwidth currently to implement correctly. This is more challenging than you'd expect - `HttpClient` requests are designed around an immutable, `Observable` based API. This allows them to be cleanly modified and retried in interceptors in an idempotent way. Metadata should fit cleanly into this pattern. I suspect that a correct, code-size-neutral implementation will refactor the implemetations of `HttpParams` and `HttpHeaders` into a separate, shared immutable core that can be used for metadata as well.

**Pull request closed without merging**
