### PR TITLE
refactor(core): rename synthetic host property and listener instructions

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit updates synthetic host property and listener instruction names to better align with the rest of the instructions. The `ɵɵupdateSyntheticHostBinding` instruction was renamed to `ɵɵsyntheticHostProperty` (to match the `ɵɵhostProperty` instruction name) and `ɵɵcomponentHostSyntheticListener` was renamed to `ɵɵsyntheticHostListener` since this instruction is generated for both Components and Directives (so 'component' is removed from the name). This PR is a followup after PR #35568.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@matsko could you please let me know if it looks good to you and if so, we can proceed with further reviews (I will set PR to "Ready for Review" state)? Thank you.

**Review by matsko — APPROVED** [review]
LGTM

**Review by JoostK — APPROVED** [review]

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM, this is good cleanup, thnx @AndrewKushnir

**Review by pkozlowski-opensource — APPROVED** [review]
Reviewed-for: public-api

**Comment by pkozlowski-opensource** [comment]
@AndrewKushnir this LGTM but I think that this one will need a rebase (plus remaining approvals)

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: public-api

I'm curious, though, why symbols prefixed with `ɵ` appear in the API golds in the first place.

**Comment by AndrewKushnir** [comment]
Thanks for the review team!

@jelbourn, Ivy instructions API was in public API golden files for historical reasons. If I understand correctly, the plan is to remove them from the public API. @IgorMinar could you please confirm?

@IgorMinar / @alxhub could you please have a look at this PR when you get a chance (the remaining 3rd approval from `public-api` group members is needed)?

Thank you.

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:322230870:BASE:322230894:1595282025430:55c0d527)

**Review by alxhub — APPROVED** [review]
Reviewed-For: public-api

**Comment by AndrewKushnir** [comment]
FYI, marking this PR as "master-only" due to the conflicts while merging into the patch branch. Created a followup PR #38150 with patch-only version of these changes. Will merge both of them at the same time once patch-only version is ready.

**Pull request closed without merging**
