### PR TITLE
docs: Typo for SSR

### PR DESCRIPTION
**Pull request by nkolosnjaji**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

Typo in SSR -> use product/2 from example above

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]

**Comment by alan-agius4** [comment]
Hi @NicholaAlkhouri, kinda sign the CLA.  See: https://github.com/angular/angular/pull/49781/checks?check_run_id=12658583921 for more info.

**Comment by nkolosnjaji** [comment]
@alan-agius4 hello, thanks. Just signed Google CLA

**Comment by alan-agius4** [comment]
**Caretaker note:** this is a safe PR and my approval should be enough

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 8272b5b3e6f8b3535bda251af3c81062208b6677.

**Pull request closed without merging**
