### PR TITLE
docs: simplify the DevTools readme and add publishing instructions

### PR DESCRIPTION
**Pull request by mgechev**
Remove duplicate information. Add publishing instructions for Firefox
and Chrome.

### CODE REVIEW

**Review by AleksanderBodurri — DISMISSED** [review]
There are some merge conflicts, LGTM otherwise

**Review by AleksanderBodurri — APPROVED** [review]

**Review by AleksanderBodurri — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@mgechev it looks like this PR is ready for merge? Please let me know, I can annotate it as needed and merge. Thank you.

**Comment by mgechev** [comment]
@AndrewKushnir I added a merge label.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 216a96675785535a8394477ac08e0e7c8aa8ea4a.

**Comment by AndrewKushnir** [comment]
@mgechev there was a merge conflict with the 13.3.x branch, so this PR was merged into the 14.0.x and the main branches only. Could you please create a new PR and target the 13.3.x branch if the change should be included there as well? Thank you.

**Pull request closed without merging**
