### PR TITLE
docs: add Luis Aviles to GDE resources

### PR DESCRIPTION
**Pull request by luixaviles**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
This adds Luis Aviles to the list of Angular GDEs on the Angular Docs page.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by luixaviles** [comment]
I signed it!

**Review by StephenFluin — APPROVED** [review]
This PR looks fine, there's a couple unrelated whitespace changes that will likely conflict with other GDEs being added.

**Comment by matsko** [comment]
@luixaviles please rebase

**Comment by luixaviles** [comment]
@matsko my branch is in sync now. Should I open a new PR?

**Comment by matsko** [comment]
@luixaviles no need ... I took care of it https://github.com/angular/angular/commit/c75e16aae8b71412f1e85e76c47d1836b370d641

**Pull request closed without merging**
