### PR TITLE
build(aio): prevent API H1 anchor showing in Table of Contents

### LINKED ISSUE #22387: aio + docs/api: Table of Contents renders a heading link icon
For example (https://next.angular.io/api/forms/AbstractControlDirective):

screen shot 2018-02-22 at 22 33 11

### PR DESCRIPTION
**Pull request by petebacondarwin**
Closes #22387

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Oh, so this also removes the `header-link` on the main page's `<h1>` element. I didn't realize that :)

**Comment by petebacondarwin** [comment]
Yes but I decided that people rarely need to link to the top heading - and the ToC link still works anyway. So for "getting on with things" reasons I just went with the workaround.

**Comment by gkalpak** [comment]
This should fix the ToC `.header-link`: #22446
This might still be a viable partial fix for #22131.

**Comment by petebacondarwin** [comment]
Thanks for the better fix for this. I think that repositioning the heading anchor will be a better fix across the board for #22131

**Pull request closed without merging**
