### PR TITLE
docs: fix footer uses <h3> out of order

### PR DESCRIPTION
**Pull request by noobyogi0010**
## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Angular documentation website's footer uses the `<h3>` tag out of order. According to a11y guidelines, all the heading tags should be in descending order like `<h1>` tag should be followed by `<h2>` tag and so on but in the docs footer `<h3>` tag is being used out of order.

Issue Number: #44338

## What is the new behavior?

Now, the footer instead of using the `<h3>` tag uses the `<div>` tag to display the title of each of the sections in the footer.  This resolves the out-of-order issue as we are no longer using any heading tag.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Fixes Issue: #44338

### CODE REVIEW

**Review by gkalpak — COMMENTED** [review]
LGTM :+1:
Thx, @noobyogi0010!

Can you please update the commit message to more closely follow our [commit message guidelines](https://github.com/angular/angular/blob/655507012b7b59c83e27429349ce3ac10608a82d/CONTRIBUTING.md#commit)? 🙏

**Comment by AlirezaEbrahimkhani** [comment]
@noobyogi0010 
I think your commit message should be something like this 
`docs: fix footer uses <h3> out of order`
and it will be good to add more description to it :pray:

**Comment by noobyogi0010** [comment]
@AlirezaEbrahimkhani  @gkalpak 
Updated the commit message, and added some more detail about the fix.
Please let me know if anything else is needed.
Thank you!

**Comment by gkalpak** [comment]
@noobyogi0010, I don't see the updated commit message. Did you forget to git-push by any chance?

**Comment by AlirezaEbrahimkhani** [comment]
@noobyogi0010 
To update, your last commit message you can use this command `git commit --amend` and then force push your branch

**Comment by noobyogi0010** [comment]
@gkalpak @AlirezaEbrahimkhani 
Sorry for the delay.
I have pushed the updated commit message.
Thank you!

**Comment by noobyogi0010** [comment]
> You can preview [a5ed819](https://github.com/angular/angular/commit/a5ed819f9b3fc9202073e3e829a5fc12405c9446) at https://pr45510-a5ed819.ngbuilds.io/.

Looks good to me!

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx for updating the commit message, @noobyogi0010 :+1:
Can you please add some more info on what the commit is fixing and also add `Fixes #44338` in the commit message footer (per our [guidelines][1]), so that the issue will be auto-closed once the PR is merged? :pray:

For example, you could change the commit message to something like:

> docs: remove out-of-order \`&lt;h3&gt;\` elements from footer
>
> The footer uses \`h3\` elements out of order, which causes a "Heading elements are not in a sequentially-descending order" a11y error.
> Replace the \`h3\` elements with \`div\` to improve a11y.
>
> Fixes #44338

[1]: https://github.com/angular/angular/blob/1c11a5715576632a4fb7170202395cf95dfbce09/CONTRIBUTING.md#commit-message-footer

**Comment by noobyogi0010** [comment]
@gkalpak 
Sorry for dragging this small issue fix for so long.
I have one doubt. In the above comment by commit message do you mean updating this section:
```
PR Type
What kind of change does this PR introduce?

 Bugfix
 Feature
 Code style update (formatting, local variables)
 Refactoring (no functional changes, no api changes)
 Build related changes
 CI related changes
 Documentation content changes
 angular.io application / infrastructure changes
 Other... Please describe:
```

or simply the git commit message which I can do by running the following command:

`git commit --amend -m <updated message>`

**Comment by noobyogi0010** [comment]
@gkalpak 
Updated the commit message. Please let me know if it's correct.
Thanks!

**Comment by AlirezaEbrahimkhani** [comment]
@noobyogi0010 
You add 2 more redundant commit messages please drop them and edit your last commit message and please avoid merging and instead use rebase.

you can use rebase doc I think it will help you do this.
Rebasing docs: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by gkalpak** [comment]
@noobyogi0010, I have updated the commit message for you. (I know `git` can be intimidating when you are not familiar with a particular workflow a project is using :smiley:)
Thx again for fixing the `h3` issue.

@AlirezaEbrahimkhani, thank you for helping out with the PR. This kind of help is very valuable and we really appreciate it 🏅

**Review by gkalpak — APPROVED** [review]

**Comment by noobyogi0010** [comment]
> @noobyogi0010, I have updated the commit message for you. (I know `git` can be intimidating when you are not familiar with a particular workflow a project is using 😃) Thx again for fixing the `h3` issue.
> 
> @AlirezaEbrahimkhani, thank you for helping out with the PR. This kind of help is very valuable and we really appreciate it 🏅

So sorry for this.
Thank you for all the help and guidance!

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 2a81e440f4d38348ee3fa7aca88e7c9a1dafbcf3.

**Pull request closed without merging**
