### PR TITLE
feat(platform-browser) add LinkDefinition and Link service

### PR DESCRIPTION
**Pull request by d-koppenhagen**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #34605 (Provide a LinkService)

## What is the new behavior?

Not implemented yet.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by d-koppenhagen** [comment]
My circle CI tests are failing because of the following error:

```log
//tools/public_api_guard:upgrade_api                                     PASSED in 12.5s
//tools/public_api_guard:upgrade_static_api                              PASSED in 14.6s
//tools/public_api_guard:platform-browser_api                            FAILED in 2 out of 2 in 11.0s
  Stats over 2 runs: max = 11.0s, min = 8.5s, avg = 9.8s, dev = 1.2s
  /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/bazel-out/k8-fastbuild/testlogs/tools/public_api_guard/platform-browser_api/test.log
  /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/bazel-out/k8-fastbuild/testlogs/tools/public_api_guard/platform-browser_api/test_attempts/attempt_1.log
//packages/core/test:test                                                PASSED in 15.4s
  Stats over 4 runs: max = 15.4s, min = 12.0s, avg = 14.2s, dev = 1.3s

Executed 125 out of 200 tests: 199 tests pass and 1 fails remotely.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 3
```

Any clue how to fix this?

**Comment by mhevery** [comment]
> Any clue how to fix this?

run `yarn bazel run //tools/public_api_guard:platform-browser_api.accept`

**Review by mhevery — CHANGES_REQUESTED** [review]
This seems to be a new feature. Please add:
- [ ] Description of a problem this is solving.
- [ ] Developer documentation so that someone can discover it and use it. 

Without the above we don't really know what we are reviewing and it can't be merged since the developers will not know how to use it.

**Comment by d-koppenhagen** [comment]
@mhevery thanks for the reply. As it's my first PR, I may not that experiences in what to add at which place.

>  Description of a problem this is solving.
- Where do I need to add this description? Just here in the PR?

> Developer documentation so that someone can discover it and use it.
- Should this be a new markdown file here `/aio/content/guide`? Or something else?

**Comment by d-koppenhagen** [comment]
The `Link` service with it's interface `LinkDefinition` is a service to add and modify HTML `<link>` elements in the `<head>`of the application.
It will provide an API that makes modifying `link` data easier without touching the `window` / `dom` directly by a developer using Angular (similar to the existing [`Meta` service](https://angular.io/api/platform-browser/Meta)).

One example for using the service is to add _canonical URLs_ dynamically to your app.

Without the service the implementation for doing this would look like this for an angular developer:

```ts
import { Injectable, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/common';

@Injectable({
  providedIn: 'root',
})
export class LinkService {
  constructor(@Inject(DOCUMENT) private dom) {}

  createCanonicalURL(url: string) {
    let link: HTMLLinkElement = document.querySelector('link[rel="canonical"]');
    if (link) {
      link.setAttribute('href', url);
    } else {
      link = this.dom.createElement('link');
      link.setAttribute('rel', 'canonical');
      this.dom.head.appendChild(link);
      link.setAttribute('href', url);
    }
  }
}
```

After the public `Link` service class is available, the implementation is much nicer:

```ts
import { Injectable, Inject } from '@angular/core';
import { Link } from '@angular/platform-browser';

@Injectable({
  providedIn: 'root',
})
export class LinkService {
  constructor(public link: Meta,) {}

  createCanonicalURL(url: string) {
    this.link.updateTag({ rel: 'canonical', href: url });
  }
}
```

**Comment by mhevery** [comment]
Hello, after discussing with the team, we don't think we want to be adding new API surface to the Angular at this time. I will close it for now.

**Pull request closed without merging**
