### PR TITLE
refactor(platform-server): remove `HttpClientModule` import

### LINKED ISSUE #57983: `ServerModule` overrides `HttpClient` customizations
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

Yes

### Description

When using SSR with the module setup generated with `ng new --standalone=false --ssr=true` (or by `ng add @angular/ssr` to an existing module application), any `HttpClient` customizations are overridden by `ServerModule`. This is because `ServerModule` imports `HttpClientModule`. https://github.com/angular/angular/blob/1549afe10eddc92845cd1fde862aaa010c2395af/packages/platform-server/src/server.ts#L83-L88

The repro uses `angular-in-memory-web-api` to demo the customization behavior.

The following things fix this:
- Moving the `ServerModule` import above the `AppModule` in `AppServerModule` (https://github.com/griest024/ng18-ssr-module/tree/module-order)
- Replacing the `ServerModule` import with `provideServerRendering()` (https://github.com/griest024/ng18-ssr-module/tree/server-provider)

### Please provide a link to a minimal reproduction of the bug

https://github.com/griest024/ng18-ssr-module

### Please provide the exception or error you saw

_No response_

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.6
Node: 18.20.4
Package Manager: npm 10.7.0
OS: linux x64

Angular: 18.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.6
@angular-devkit/build-angular   18.2.6
@angular-devkit/core            18.2.6
@angular-devkit/schematics      18.2.6
@schematics/angular             18.2.6
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else?

IMO the *correct* fix is the replace `ServerModule` with `provideServerRendering()` in `@angular/ssr` scaffolding. `HttpClientModule` should probably not be imported by `ServerModule` either.

Related to https://github.com/angular/angular/issues/50454

### PR DESCRIPTION
**Pull request by JeanMeche**
This import is not necessary anymore.

fixes #57983
Note: The standalone counterpart was fixed by #50454

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:680561910:BASE:680561932:1727705475251:54b9a5ed)

**Comment by AndrewKushnir** [comment]
Note: I've changed the target label to merge the change to the main branch only, to avoid any risks for the patch version.

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by AndrewKushnir** [comment]
**Caretaker note**: presubmit is "green", this PR is ready for merge.

**Comment by alxhub** [comment]
This PR was merged into the repository by commit f2bea3b73d6699cf9b99677f3b683304888027b2.

The changes were merged into the following branches: main

**Pull request closed without merging**
