### PR TITLE
Docs(changeLog.md) remove breaking changes section information which was displaying twice.

### PR DESCRIPTION
**Pull request by micronyks**
- **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  I have changed duplication of same information shown in Angular2 2.0.0-beta.9 (2016-03-09) CHANGELOG.md in breaking changes  section.
- **What is the current behavior?** (You can also link to an open issue here)
  breaking changes section was displaying information twice.
- **What is the new behavior (if this is a feature change)?**
  Now, it will show it single time.
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
  **NO**

2.0.0-beta.9 (2016-03-09) breaking changes section was  displaying same information two(2) times. changed it.

### CODE REVIEW

**Comment by micronyks** [comment]
I signed it!

**Comment by woppa684** [comment]
@micronyks Not only was it displayed twice, it's the same "breaking change" as with beta.8!

**Comment by laco0416** [comment]
@micronyks I've already sent a patch for this. #7521 
As @woppa684 says, "breaking changes" of beta.9 is same to beta.8.

**Comment by micronyks** [comment]
@woppa684, yes accepted.  I didn't see it.

**Comment by CaptainCodeman** [comment]
The description for the breaking change commit looks like nothing to do with the code change in the commit itself which looks to me like it's just code formatting. Is this a mistake or intentional?

https://github.com/angular/angular/commit/2548ce8

**Comment by laco0416** [comment]
Beta.9 contains some changes that is also included in Beta.8.
I don't know why it happens.
2016/03/11 1:46 "Simon Green" <notifications@github.com>:

**Comment by mhevery** [comment]
Already merged under different PR

**Pull request closed without merging**
