### PR TITLE
refactor(router): Move more transition logic into the transition handler

### PR DESCRIPTION
**Pull request by atscott**
See individual commits

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api, required-minimum-review

**Comment by atscott** [comment]
caretaker note: probably want to merge and sync this on its own

**Comment by atscott** [comment]
This PR was merged into the repository by commit afc668acd5eef711639dcdb4979acad6c99b8ae3.

**Comment by atscott** [comment]
[TGP](https://fusion2.corp.google.com/presubmit/tap/491486226/OCL:491486226:BASE:491707794:1669753610675:92c2d3bc;groups=PossiblyNewlyFailing/targets). The failing tests are accessing `navigationId`, which is not a valid use-case. A temporary private getter has been added while this is cleaned up internally. Merging can be resumed.

**Comment by atscott** [comment]
**Caretaker Note:** Please ignore the `google-internal-tests` status. Failures are pre-existing. Deflaking does not change this.

**Comment by atscott** [comment]
This PR was merged into the repository by commit 0ff5d972cdd20428d647a94c6c769c0759cfd49c.

**Pull request closed without merging**
