### PR TITLE
fix(core): refine Injector.get declaration to infer correct return type

### PR DESCRIPTION
**Pull request by ts2do**
fix(core): refine Injector.get declaration to infer correct return type

These changes address an overload resolution issue whereby Injector.get
calls would resolve to the deprecated overload, disabling all type
checks with an 'any' return type.

BREAKING CHANGE:
Applications may need to be corrected for revealed type errors.
Applications explicitly specifying the generic argument to the method
should remove the generic argument in favor of type inference.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Given `x` of type `Type<T>|InjectionToken<T>` and `y` of type `U` (excluding `THROW_IF_NOT_NULL` and `undefined`):
- `injector.get(x, undefined)` is `any`
- `injector.get(x, THROW_IF_NOT_NULL)` is `any`
- `injector.get(x, y)` is `any`
- `injector.get(x, someCondition ? y : THROW_IF_NOT_NULL)` is `any`

## What is the new behavior?
- `injector.get(x, undefined)` is `T`
- `injector.get(x, THROW_IF_NOT_NULL)` is `T`
- `injector.get(x, y)` is `T|U`.
- `injector.get(x, someCondition ? y : THROW_IF_NOT_NULL)` is `T|U`

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

Any application injecting Injector may be affected. Applications may need to be corrected for revealed type errors. Applications explicitly specifying the generic argument to the method should remove the generic argument in favor of type inference.

### CODE REVIEW

**Comment by ts2do** [comment]
FYI: I'm trying to contribute from a Windows machine and am unable to build, hence the commit to manually updating the public API guard files.

**Comment by ts2do** [comment]
Can someone restart the automated checks? It looks like an unexpected failure for both.

**Comment by alxhub** [comment]
Hi @ts2do, and thanks for the PR. As far as I can tell, this does actually cause test failures (probably related to the breaking change).

As it is, though, I don't think we can accept this PR until Angular 7, when we can make this kind of breaking change. I definitely think we should make `Injector.get()` more type-safe, though, so I'm adding this to our v7 milestone.

**Comment by trotyl** [comment]
If this will get merged in v7, possibly https://github.com/angular/angular/pull/11813 should be considered as well?

**Pull request closed without merging**
