### PR TITLE
refactor(docs-infra): replace deprecated subscribe usages

### PR DESCRIPTION
**Pull request by markostanimirovic**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Replaced deprecated `observable$.subscribe(next, error, complete)` signature with `observable$.subscribe({ next, error, complete })`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
merge assistance: This change doesn't really require docs-infra domain knowledge so approval from `docs-infra` isn't really necessary.

**Comment by markostanimirovic** [comment]
> merge assistance: This change doesn't really require docs-infra domain knowledge so approval from `docs-infra` isn't really necessary.

@atscott 

I used the `docs-infra` scope, because the changes are made within the `/aio` dir. Let me know if I need to change it 🙂

**Comment by atscott** [comment]
@markostanimirovic You did the right thing. Our pullapprove process would just require someone who owns docs-infra code (based on the files changed) to approve. But I don't think that's necessary here so I've marked it as merge with a note to the caretaker to ignore the pullapprove status.

**Comment by alxhub** [comment]
This PR was merged into the repository by commit b4157449c460908895bc01d0ecfd46c677f53849.

**Pull request closed without merging**
