### PR TITLE
docs: add new UI library resource from the Tailwind CSS ecosystem

### PR DESCRIPTION
**Pull request by zoltanszogyenyi**
## PR Checklist

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Documentation content changes

## What is the current behavior?

The [list of resources](https://angular.io/resources?category=development) page does not include any Angular + Tailwind CSS related library or tool.

## What is the new behavior?

This PR adds a very popular and open-source UI component library called [Flowbite](https://flowbite.com/docs/getting-started/angular/) that is well known within then Tailwind CSS ecosystem and recently published an official integration guide with Angular.

- over 120k downloads per week on NPM: https://www.npmjs.com/package/flowbite
- over 4 million total downloads on NPM
- the most popular UI component library based on Tailwind CSS utility classes
- has an open-source design system in Figma: https://www.figma.com/community/file/1179442320711977498

## Does this PR introduce a breaking change?

- [x] No

### CODE REVIEW

**Comment by MarkTechson** [comment]
Currently reviewing.

**Review by MarkTechson — APPROVED** [review]
LGTM

**Comment by zoltanszogyenyi** [comment]
Thank you! Excited to see it merged.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 75561c96d0dfa4289f05465adbf95fd6b059f3e7.

**Pull request closed without merging**
