### PR TITLE
docs(router): fix error handler deprecation

### PR DESCRIPTION
**Pull request by cexbrayat**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The deprecation mentions `withErrorHandler` whereas the feature is called `withNavigationErrorHandler` since 15eccef4ebf58c889b2a28988ebcc297e3cd2df6.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
👍

**Comment by AndrewKushnir** [comment]
**Caretaker note**: no presubmit required, docs-only change.

**Comment by pkozlowski-opensource** [comment]
Re-targeting at minor since `withNavigationErrorHandler` only exists in 15.2

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit a28cf2438bd69c890e1876edcc765aed243aeb2f.

**Comment by pkozlowski-opensource** [comment]
@cexbrayat @atscott  based on https://github.com/angular/angular/pull/49015#issuecomment-1425323406 - are there any changes that should be done in 15.1.x as well?

**Comment by cexbrayat** [comment]
@pkozlowski-opensource AFAIK this only in v15.2

**Pull request closed without merging**
