### PR TITLE
docs: fix example misprints

### PR DESCRIPTION
**Pull request by stevermeister**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
there were just several misprints in a webworker code example

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — CHANGES_REQUESTED** [review]
Good catch, thx :+1:

Can you, please, change the commit message to `docs: ...` (`webworker` is not a valid commit message scope)? Making this change will also CI happy :wink:

**Comment by stevermeister** [comment]
@gkalpak sure, thx for the hint!

**Comment by kapunahelewong** [comment]
Thanks for this, @stevermeister! Hope it's all right that I adjusted the PR title to reflect your commit message. 🚀

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
**merge-assistance**: Global approval for this docs-only change.

**Pull request closed without merging**
