### PR TITLE
docs: mark hydration and fetch APIs as stable

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This PR contains a few commits that remove `@developerPreview` from several APIs related to hydration and fetch support in HttpClient.

## PR Type
What kind of change does this PR introduce?

- [x] Documentation content changes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM 🎉

**Comment by bigquin99** [comment]
hi thanks again i got into it

________________________________

**Review by JeanMeche — APPROVED** [review]
I'm happy to see this promoted ! 🎉

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Pull request closed without merging**
