### PR TITLE
docs: Fixed filename in First-app

### PR DESCRIPTION
**Pull request by ubermachine**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, thank you for improving the doc !

Can you reword your commit and remove ‘docs-infra’, the “docs” type is enough, no need for a scope for that kind of change !

**Comment by ubermachine** [comment]
Hi Thanks ,I have amended as per your instruction

**Review by alan-agius4 — COMMENTED** [review]
LGTM, thanks for the contribution.

**Review by alan-agius4 — APPROVED** [review]

**Comment by alan-agius4** [comment]
**caretaker note:** this is a safe change and my approval is enough.

**Comment by alxhub** [comment]
This PR was merged into the repository by commit fc1d777c698337f093e6bcb9deedec94856d5d2a.

**Pull request closed without merging**
