### PR TITLE
fix(docs-infra): fix angular.io on IE 11

### PR DESCRIPTION
**Pull request by gkalpak**
- **fix(docs-infra): avoid unnecessarily loading Custom Elements ES5 shim:**
    The custom elements spec is not compatible with ES5 style classes. This means ES2015 code compiled to ES5 will not work with a native implementation of Custom Elements. To support browsers that natively support Custom Elements but not ES2015 modules, we load `@webcomponents/custom-elements/src/native-shim.js`, which minimally augments the native implementation to be compatible with ES5 code.
    (See [here](https://www.npmjs.com/package/@webcomponents/custom-elements#es5-vs-es2015) for more details.)

    Previously, the shim was included in `polyfills.ts`, which meant it was loaded in all browsers (even those supporting ES2015 modules and thus not needing the shim).

    This commit moves the shim from `polyfills.ts` to a `nomodule` script tag in `index.html`. This will ensure that it is only loaded in browsers that do not support ES2015 modules and thus do not needed the shim.

    NOTE:
    This commit also reduces size of the polyfills bundle by ~400B (52609B --> 52215B).

- **fix(docs-infra): fix angular.io on IE 11:**
    Previously, the angular.io app was broken on IE 11. In particular, pages that included Custom Elements would fail to load, because the `Reflect.construct()` method (which the Custom Elements ES5 shim relies on) was not available.

    This commit fixes this by loading the polyfill for `Reflect.construct()` on browsers that do not support ES2015 (including IE 11).

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM

reviewed-for: size-tracking

**Comment by gkalpak** [comment]
@jessicajaniuk, wait what? No 🍪? 😭 😭 😭

**Review by petebacondarwin — APPROVED** [review]
I haven't bothered to test on IE. I trust that you did @gkalpak.
Reviewed-for: size-tracking

**Review by jessicajaniuk — COMMENTED** [review]
🍪  I managed to find one!

**Comment by AndrewKushnir** [comment]
@gkalpak FYI this PR was merged to master only, since it had merge conflicts withe the patch branch (11.2.x). Could you please create a new patch-only version of this PR? Thank you.

**Pull request closed without merging**
