### PR TITLE
docs(common): fix mis-ordered lines

### PR DESCRIPTION
**Pull request by marob**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
:)

**Comment by gkalpak** [comment]
Nice catch, @marob 👍 
Can you please change the commit message to adhere to our [commit message guidelines][1]? E.g. something like `docs(common): fix ...`.

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by gkalpak** [comment]
Needs approval from `common` owners.

**Comment by marob** [comment]
@gkalpak: I've change the MR message. Is that OK or should I change it also on the original commit (how can I do that without having to create a new MR?) ?

**Comment by marob** [comment]
Had to create a new MR: #20221

**Pull request closed without merging**
