### PR TITLE
Explicit label relationship

### PR DESCRIPTION
**Pull request by zersiax**
Implicit programmatic associations between labels and their text fields will break with some accessibility software, in particular Speech-To-Text software like Dragon Dictation and various other Voice Control technologies. More info: https://a11ysupport.io/tech/html/label_element

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by zersiax** [comment]
@googlebot I signed it!

**Comment by zersiax** [comment]
I wasn't sure if it would be preferred to make this change all the way through the docs in one go, which is why I only touched the one file. If people want I can implement all the way through

**Comment by petebacondarwin** [comment]
I think it would be good to eventually update all the examples.

But more importantly, I see that our own a11y page contains an implicit label(!!): See the `app.component.html` snippet under https://angular.io/guide/accessibility#case-study-building-a-custom-progress-bar.

If we are going to make these changes then I think it would be wise to start with this document, and also to add a section here to call out why explicit labelling is better.

(By the way you will also need to update the commit message to follow our required syntax. See the CI lint job failures for more info).

**Comment by zersiax** [comment]
I will close this PR for now, then. I will update the accessibility page, as well as the pages in the tutorial. 
While the accessibility page is really important, the tutorial is the entry point for a lot of people starting out. If we do it right there, it'll send a clear message.

**Comment by aikidave** [comment]
Hi! I know this PR is closed, but I thought I'd share that we are actively working on making sure all of our examples meet accessibility requirements. @kapunahelewong is on it!

**Comment by zersiax** [comment]
ok :) well then I hope this one gets taken along as well :)

**Pull request closed without merging**
