### PR TITLE
feat(forms): add form builder

### PR DESCRIPTION
**Pull request by vsavkin**

### CODE REVIEW

**Comment by mhevery** [comment]
How about:

```
constructor(group:FormBuilder) {
  this.form = group( {
    'login': {"value": "login", "validator": validations.required},
    'optionalField': {"value": "login", "validator": validations.required, optional: true},
    'subGroup': group({...})
    'optionalSubGroup': group.optional({...})
  });
}
```

ThoughtsL

**Comment by mhevery** [comment]
Map Like

```
constructor(group:FormBuilder) {
  this.form = group( {
    'login': ["login", validations.required],
    'optionalField': ["login", validations.required],
    'subGroup': group({...})
    'optionalSubGroup?': group({...})
  });
}
```

**Comment by mhevery** [comment]
Per Discussion with @vsavkin and @mhevery

```
control is optional BAD

group has a hash: optionals. GOOD
group creates

group -> decorator -> control
decorator is optional

group -> decorator -> control

group
  array
    optional controls
    
group
  foo: array
    optional
      group 
        control

group, array, control

{foo:1, bar: {'baz':true}, x: []}

Todo [Task createdByVictor:boolean] 

group
  array
    optional derived from createdByVictor 
      Task 

group.get('tasks').get(0).condition = false

group.controls.items

group.get('items')
group.controls.items


class Example {
  loginForm:ControlGroup;

  constructor(fb:FormBuilder) {
    this.loginForm = fb.group({
      'username': fb.control('', validotor: LDAP),
      'password1': ['', Strong],
      'password2': '',
      'age': 3,
      'children': fb.array((value, i) => fb.group()),
      'foo': fb.group({
      
      }), optional: {
        'age': foo.bar,
        'foo': false
      }), 
    }, validator: SamePassword);
  
    this.loginForm.addControll('foo', ...);
    
    this.loginForm.value == {
      'username': 'misko',
      'password': 'word',
      'age': 3
    };
    this.loginForm.controlls['foo'].cond = true;
    thsi.loginForm.include('foo');
    
    this.loginForm = fb.group([
      fb.field('username'),
      fb.field('password1'),
      fb.field('password2')
    ], validator: SamePassword);

    this.loginForm = new ControllGroup([
      fb.field('username'),
      fb.field('password1'),
      fb.field('password2')
    ], validator: SamePassword);
    
    this.loginForm = fb.build(group({
      username: control(),
      password1: control(),
      password2: control()
    });
    
    
    this.loginForm = new ControlGroup({
        username: new Control('username', ...),
        age: new Control('...', ...)
      })
    ])
  }
}

5
opt = Optional 5
opt.present?
opt.value


<form [controll-group]=form>
  <input name="username">
  <input *if="form.get('age').condition"
         [readonly]="form.get('age').readonly"
         name="age">
  <select controll="mode">
    <option>birth</option>
    <option>age</option>
  </select>
  <input *if="form.has('age')"
         [readonly]="form.get('mode')!=='age'"
         name="age">
  <input *foreach="var child in form.list('children')"
         [controll]="child">
</form>
```

**Comment by vsavkin** [comment]
@mhevery I've updated the PR. Could you take a look at it again?

**Pull request merged**
