### PR TITLE
feat(test): allow tests to specify the platform and application

### PR DESCRIPTION
**Pull request by juliemr**
Note: This is on top of https://github.com/angular/angular/pull/5920

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@juliemr Dart-related failures on TravisCI seem legit

**Comment by juliemr** [comment]
@pkozlowski-opensource agreed, looking into them. Dart is unhappy about const stuff.

**Comment by juliemr** [comment]
Status update: I was hoping to add `PLATFORM_DIRECTIVES` to the test bindings in a way that doesn't introduce any breaking changes to tests, but it looks like that would be very convoluted to get working with the current set of internal tests (including the `test.server.dart` tests which can't include `dart:html` anywhere). I'm working on a minimal, simple breaking change proposal.

**Comment by juliemr** [comment]
New proposal is here: https://github.com/angular/angular/pull/5975

Closing this one for now, since it's insufficient.

**Pull request closed without merging**
