### PR TITLE
docs: fix example for defer on hover on an alternative element

### PR DESCRIPTION
**Pull request by pweyrich**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thanks for this !

**Comment by JeanMeche** [comment]
Could you please drop the scope from your commit message (`adev` isn't a valid one) and make it a `docs: ...`, thank you.

**Comment by pweyrich** [comment]
> Could you please drop the scope from your commit message (`adev` isn't a valid one) and make it a `docs: ...`, thank you.

Done

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 55e3a3a47cddefebc28af03ce58ece136d41a391.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
