### PR TITLE
docs: Update installation.md, changed description from node 18.9.1 to 18.19.1

### PR DESCRIPTION
**Pull request by ulisesmorenomassachusetts**
changed the description of the required version from node 18.9.1 to 18.19.1

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]

**Comment by JeanMeche** [comment]
Could you please sign the CLA and reword your commit to make a `doc: ...` commit message to follow [our guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit), thank you.

**Comment by JeanMeche** [comment]
CLA wasn't sign, we won't be able to merge this PR.

**Comment by ulisesmorenomassachusetts** [comment]
It was confusing to me, I think I signed with a different email, that's why it didn't recognize the signature.

**Comment by ulisesmorenomassachusetts** [comment]
I updated my CLA email contact

**Comment by ulisesmorenomassachusetts** [comment]
updated the commit message

**Comment by JeanMeche** [comment]
Can you drop the scope of the commit message, `installation` is invalid and we don't require one for docs only changes. Thank you.

**Comment by ulisesmorenomassachusetts** [comment]
done, thanks

**Comment by JeanMeche** [comment]
We're all set, thank you for your help !

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit b5efabed53751221a3979c71f2874b21fb9896db.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
