### PR TITLE
fix(common): export the IMAGE_CONFIG token

### PR DESCRIPTION
**Pull request by cexbrayat**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The token introduced in 4fde292bb58f5d5bc3cf6e634f7cff9eb0d13d84 was not exported publicly.

## What is the new behavior?

It is exported publicly

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@cexbrayat thanks for catching this 👍

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:488408271:BASE:488408339:1668451192483:e762071d).

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 804b85554cb98d34038fb59d0b40fa8fc1d9b5b8.

**Pull request closed without merging**
