### PR TITLE
docs: remove code in universal hero detail component

### PR DESCRIPTION
**Pull request by dariobraun**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #22174

## What is the new behavior?
No more obsole annotations and imports:

**@Input** hero: Hero ---> hero: Hero
{ Component, OnInit, **Input** } from '@angular/core ---> { Component, OnInit } from '@angular/core

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by JoostK** [comment]
This PR is so immensely large that it is impossible to review. Furthermore, it looks like a lot of changes are unrelated to the points that were brought up in #22174.

**Comment by dariobraun** [comment]
@JoostK Sorry, I messed up somewhere in the GitHub workflow - fixed it!

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update commit message to `docs: remove code in universal hero detail component`

**Comment by IgorMinar** [comment]
@dariobraun / @brandonroberts is it right that we are updating the universal version of the app to fix #22174? I'd expect to see changes in the chapter 7 of the tutorial.

**Comment by brandonroberts** [comment]
@IgorMinar correct. This should be fixing the tutorial, but that already is covered by https://github.com/angular/angular/pull/22151

The fix does need to be applied to the universal guide also.

**Review by IgorMinar — APPROVED** [review]
I see. thanks for the clarification.

**Review by brandonroberts — APPROVED** [review]

**Pull request closed without merging**
