### PR TITLE
added folder structure details

### PR DESCRIPTION
**Pull request by deepamgupta**
Added folder structure details in README.md for better understanding of the framework and helping the newbies Easy Getting Started.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behaviour?
A folder structure detail of the framework.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

The existing application will have no effect as there is no change in the code. Only the README.md is added with some content. This content will help newbies to get started easily. Changes can be made to the content to make it updated accordingly.

### CODE REVIEW

**Comment by santoshyadav198613** [comment]
This already exist https://angular.io/guide/file-structure if you are referring to an angular app structure.

**Comment by cunla** [comment]
You added the directory structure for a new angular project, not for the angular project.

It would make more sense to add it to the template of a new project.

**Comment by kapunahelewong** [comment]
Thank you for this @deepamgupta. As @santoshyadavdev [shared](https://github.com/angular/angular/pull/36904#issuecomment-623172532), this info exists in the docs already. Instead of adding it to the readme, you could instead improve the existing list @santoshyadavdev links to. What do you think?

**Comment by petebacondarwin** [comment]
Closing due to a lack of response, and this change as it stands is not what we want.

**Pull request closed without merging**
