### PR TITLE
fix(router): Remove deprecated ComponentFactoryResolver from APIs

### PR DESCRIPTION
**Pull request by atscott**
BREAKING CHANGE:
`ComponentFactoryResolver` has been removed from Router APIs. Component factories are not required to create an instance of a component dynamically. Passing a factory resolver via resolver argument is no longer needed and code can instead use `ViewContainerRef.createComponent` without the factory resolver.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
Great cleanup 👍

**Comment by JeanMeche** [comment]
nit: You could also remove the line in the depreciation guide !

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Comment by atscott** [comment]
[TGP](https://fusion2.corp.google.com/presubmit/tap/512956788/OCL:512956788:BASE:515490370:1678412702294:45e2e7f4;groups=PossiblyNewlyFailing/targets)

**Comment by alxhub** [comment]
This PR was merged into the repository by commit ed110a05f05a6875c7dcd489bea57d8fcdfff34a.

**Pull request closed without merging**
