### PR TITLE
docs(aio): mention snippets in WebStorm

### PR DESCRIPTION
**Pull request by prigara**
Added a mention of code snippets in WebStorm and other IDEs

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: docs
```

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by wardbell — CHANGES_REQUESTED** [review]
We love WebStorm. Unfortunately, all of those links take the reader to pages that sell editors. We can't do that. If they were links to free snippet downloads, we could consider it.

**Comment by denofevil** [comment]
Do you think if we add a link to the OS Angular plugin repo it would be better?
//cc @JohnPapa

**Comment by jenniferfell** [comment]
@prigara Hi. Thank you for your interest in contributing information about WebStorm. I'm reviewing older PRs, and I just wanted to check with you. If you are still interested in contributing WebStorm information, please see the request by @wardbell above. Thank you.

**Comment by prigara** [comment]
Hi @jenniferfell,
I've removed a link to the WebStorm website and instead used a link to the sources of our Angular plugin (that contains files with these snippets). 
Even though the plugin is open source and free, there's no free product where you can use it, so I'm not sure that the change I've made fully addresses @wardbell concern.
Let me know what you think!

**Comment by jenniferfell** [comment]
@prigara I apologize for not replying more quickly. Thank you for the update and clarification. I don't think I'm the right person to determine if that sufficiently addresses @wardbell 's concerns. 

@robwormald @StephenFluin : What do you think? @prigara is proposing an addition to https://angular.io/guide/styleguide#file-templates-and-snippets to in a link to the WebStorm website, specifically a link to the sources of their Angular plugin (that contains files with these snippets). The interesting question is this: Even though the plugin is open source and free, there's no free product where you can use it. Is it okay to provide this link in the Angular Style Guide? Thanks for your perspective.

**Comment by StephenFluin** [comment]
The snippet plugin linked seems to point to AngularJS, is that right? Also, it looks like this plugin is bundled with WebStorm, meaning it's automatically available? If that's true, then if a developer chooses webstorm, they get the benefits without any action on their part, so it doesn't seem like it belongs in the guidance. 

Do we have anywhere in the documentation that we talk about IDE choice that might be more appropriate for this? We shouldn't get into the business of picking IDEs for people, but we probably should mention the top 2-3, or that Angular isn't dependent on an IDE.  Based on this it might make sense to link to snippets if they are something users need to manually add to the top 1 or 2 other IDEs. If they are included by default, perhaps just mentioning them and removing the link.

**Comment by prigara** [comment]
Hi @StephenFluin,
Thanks for your reply!

You’re right, the plugin is bundled with WebStorm and people don’t have to configure anything to use the snippets. However, it’s not the most discoverable feature (you need to know what snippets are available to use them) that is why I thought that it would be nice to mention that they are available in WebStorm as well.

The IDEs that support Angular are now listed on the [Resources page](https://angular.io/resources). There’s also a [Getting started guide for Visual Studio](https://angular.io/guide/visual-studio-2015) in the docs section. It might be a great idea to have a dedicated page about the editor and IDE support with links to the getting started guides for each of them.

**Comment by StephenFluin** [comment]
Closing as the summary of the conversation above is that we should highlight WebStorm in other ways on the site.

**Pull request closed without merging**
