### PR TITLE
WIP: feat(router): support regular expression route paths

### PR DESCRIPTION
**Pull request by petebacondarwin**
This is for @btford to look at and comment on...

### CODE REVIEW

**Comment by naomiblack** [comment]
@petebacondarwin can you update with status? we'd like to land this ahead of other router work so you don't end in refactoring hell. My understanding is this is on your to-do list, to resolve some remaining issues with Dart.

**Comment by petebacondarwin** [comment]
Indeed - I have fixes almost ready to upload to GitHub right now.

**Comment by electricBonfire** [comment]
+1
I haven't looked through the commit but I am in favor of this feature!
I am trying to add datatype requirements to the route params as described here: https://github.com/angular/angular/issues/7321

**Comment by naomiblack** [comment]
Closing this PR because it is superceded by #7325 which contains this work + fixes.

**Pull request closed without merging**
