### PR TITLE
ci: add type to done callback

### PR DESCRIPTION
**Pull request by brandonroberts**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by gkalpak** [comment]
FYI, I am working on a proper fix (but this will indeed fix master too).

**Comment by brandonroberts** [comment]
Either way is fine with me

**Comment by gkalpak** [comment]
Here's the PR: #25163.
(It touches more files, so may not be merged as quickly 🤷‍♂️ Maybe this is a good temporary work-around.)

**Comment by brandonroberts** [comment]
Closing in favor of #25163

**Pull request closed without merging**
