### PR TITLE
fix(core): remove support for `Map`/`Set` in `[class]`/`[style]` bind…

### PR DESCRIPTION
**Pull request by mhevery**
…ings

Close FW-1863

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
Lgtm.. let's discuss this in fw meeting and revisit reenabling the support once we are sure this won't be a perf footgun

**Comment by IgorMinar** [comment]
@mhevery can you please presubmit this? Thanks

**Comment by kara** [comment]
[presubmit](http://test/OCL:295026456:BASE:295026483:1581639817893:2b5d9218)

**Comment by arlowhite** [comment]
I was curious about the reasoning/history behind this (for curiosities sake, not impacted), but there's very little information here and the JIRA link doesn't work for me (endless redirect loop on **Choose or add another account** screen).

If JIRA is non-public, linking JIRA isn't verify open source friendly.

**Pull request closed without merging**
