### PR TITLE
docs(forms): add section under Validators.pattern detailing use of global and sticky flags gotcha

### PR DESCRIPTION
**Pull request by AleksanderBodurri**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #39053

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — CHANGES_REQUESTED** [review]
Thanks for creating this PR @AleksanderBodurri 👍  I've just left a couple comments, pleased have a look when you get a chance.

**Comment by AleksanderBodurri** [comment]
@AndrewKushnir Made the requested changes. Not sure why the CI is failing though.

**Review by AndrewKushnir — APPROVED** [review]
@AleksanderBodurri, thanks for addressing the feedback.

The change looks good to me from technical standpoint. I've also added @kapunahelewong as a reviewer to make sure everything is ok from docs perspective.

Thank you.

**Comment by AndrewKushnir** [comment]
> Not sure why the CI is failing though.

The CI failure was a flake. I noticed that you updated the PR, so the CI restarted, let's see if the error goes away.

**Comment by AleksanderBodurri** [comment]
> > Not sure why the CI is failing though.
> 
> The CI failure was a flake. I noticed that you updated the PR, so the CI restarted, let's see if the error goes away.

I see. I noticed I missed removing the reference to `RegExp.prototype.exec` in your first recommendation, hence the force push. Should be good now.

**Review by sonukapoor — APPROVED** [review]
Nice catch 👍

**Review by kapunahelewong — APPROVED** [review]
LGTM! Thank you, @AleksanderBodurri!

Reviewed for global-docs-approvers

**Pull request closed without merging**
