### PR TITLE
docs(common): use table layout for Pre-defined format options

### PR DESCRIPTION
**Pull request by whatthefrog**
easier to read

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by whatthefrog** [comment]
@googlebot I signed it!

**Review by petebacondarwin — APPROVED** [review]
I love it! Thanks
Reviewed-for: global-docs-approvers

**Before:**
Screenshot 2020-12-09 at 10 54 09

**After:**
Screenshot 2020-12-09 at 10 54 14

**Comment by whatthefrog** [comment]
Hi, I see the MR is closed rather than merged ? 

sorry to ask, but is there any reason not to merge at the end ?

**Comment by petebacondarwin** [comment]
We use a script to merge PRs into multiple branches, which it does by cherry-picking the commits from the PR. So Github does not realise that the PR has been merged. Instead it marks it as closed instead.
But you can see that you commits are all now on the `master` branch and the patch branch (`11.0.x`). See 42d478b16aacf6841a93e91db1c2de225ac30f94 and b2090fdf936f59a3cce2bf9dd9f4dcaec2be2faf.

**Pull request closed without merging**
