### PR TITLE
feat(platform-browser, platform-server): async platform TransferState serializing

### PR DESCRIPTION
**Pull request by duykhang53**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by alan-agius4 — COMMENTED** [review]
Can you please elaborate on the use case were you need an async serializer?

**Comment by duykhang53** [comment]
In some scenarios, promise resolve of some services occur after `BEFORE_APP_SERIALIZED`, that cause the current state from `TransferState` is not the latest.

**Comment by duykhang53** [comment]
`@ngrx/store` is an use case

**Comment by alan-agius4** [comment]
The current implementation of `transferState` was actually designed with NGRX in mind. 

Context: https://github.com/ngrx/platform/issues/101#issuecomment-351998548

Can you please provide an example on how you are using the transfer state API were it needs to be async?

**Comment by duykhang53** [comment]
why not make it short by 

```ts
import { firstValueFrom } from 'rxjs';

this.transferState.onSerialize(NGRX_STATE, () => firstValueFrom(this.store));
```

**Comment by alan-agius4** [comment]
Hi @duykhang53,

Thanks for your contribution. 

This change however adds unnecessary complexity to the API.

**Pull request closed without merging**
