### PR TITLE
chore(http): remove RequestMethodsMap

### LINKED ISSUE #2904: chore(http): convert RequestMethods to const list
I made the `RequestMethodsMap` class during the big refactoring to support Dart, so that it could be declared at the top-level of the enums module. The class takes an enum (integer) and returns the corresponding enum's name. Like `requestMethodsMap.get(0)// -> 'GET'`But it should be able to be a constant and provide the same usefulness for converting `RequestMethods` enum values to strings and vice versa, with less overhead

### PR DESCRIPTION
**Pull request by rixrix**
fixes #2904

### CODE REVIEW

**Comment by jeffbcross** [comment]
@rixrix thanks for the PR! Looks good, but could you also remove the `ENUM_INDEX` imports and calls? That also was only added for dart. In TypeScript, ENUM_INDEX just returns its input value.

If you want to, you could also remove ENUM_INDEX from the lang.ts and lang.dart facades, as it's not being used anywhere else. This should be a separate commit from the other changes, but can still be part of this branch/PR.

**Comment by rixrix** [comment]
@jeffbcross thanks for the feedback. I'll work on those stuff you mentioned. cheers

**Comment by rixrix** [comment]
Hi, another batch of changes has been pushed. tnx

**Comment by jeffbcross** [comment]
Looks great! Would you mind formatting the ENUM_INDEX commit message, and add a body to the "remove RequestMethodsMap" with a sentence explaining the change, as well as "Closes #2904 " in the body so Github will automatically close the issue when it merges?

Other than that, looks good to merge. 

If you're not comfortable rebasing/editing messages, I can go ahead and adjust them (your name would still show up on the commit :)

**Comment by rixrix** [comment]
ah my mistake, I'll get those sorted out so I know what to do next time ;) thanks

**Comment by rixrix** [comment]
Hi Jeff, I didn't realize I'd shoot off early today and will be away for 2 days - on mobile at the moment. I'd be happy if you could do the commit logs revision for me. thanks

**Comment by jeffbcross** [comment]
No problem!

**Comment by jeffbcross** [comment]
Pushed to presubmit, so it should be merged soon! https://github.com/angular/angular/tree/presubmit-jeffbcross-pr-3843

**Pull request closed without merging**
