### PR TITLE
Minor Grammatical change

### PR DESCRIPTION
**Pull request by Pedro-D13**
Instead of  'In an SPA ...'

the suggested change is 'in a SPA ...' 👍🏿

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by Pedro-D13** [comment]
@googlebot I signed it!

**Review by petebacondarwin — APPROVED** [review]
This is an interesting one. According to most articles on the web that I found it comes down to whether the letters are spoken individually (as in HTML) or spoken as a word (as in SCUBA). In this case I think it is more common to pronounce SPA as *spah* rather than ess-pee-aye. So I think this is a valid change. 

But perhaps @TeriGlover might have a view?

Reviewed-for: global-docs-approvers

**Comment by petebacondarwin** [comment]
@Pedro-D13 - please can you amend the commit message to follow our commit guidelines. See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Review by atscott — CHANGES_REQUESTED** [review]
> In this case I think it is more common to pronounce SPA as _spah_ rather than ess-pee-aye. So I think this is a valid change.

Really? That’s not how I pronounce it... can we instead change this to “in a Single Page Application (SPA)” or just “in a Single Page Application” to eliminate this question altogether?

**Comment by petebacondarwin** [comment]
> can we instead change this to “in a Single Page Application (SPA)” 

Works for me!

**Review by Pedro-D13 — COMMENTED** [review]
Suggested Change to 'in a Single Page Application (SPA)'  @atscott

**Comment by Pedro-D13** [comment]
Sure that sounds good!

**Comment by petebacondarwin** [comment]
Thanks @Pedro-D13 - now you just need to squash the two commits into one and change the commit message to fit our required syntax.

**Comment by Pedro-D13** [comment]
I wasn't entirely sure how to squash both commits since I don't write access to the repo.

I have ticked "Allow edits by maintainers"

And here is the commit message formatted as suggested :
-  docs(router): minor grammatical change from "in a spa" to "in a single page application"

Thanks!

**Comment by petebacondarwin** [comment]
The changes you made are on your own fork of the repository: https://github.com/Pedro-D13/angular/tree/patch-1. But I suspect that you made the changes through the GitHub UI, which hides this from you. I have rebased and squashed the commits for you.

**Comment by Pedro-D13** [comment]
> The changes you made are on your own fork of the repository: https://github.com/Pedro-D13/angular/tree/patch-1. But I suspect that you made the changes through the GitHub UI, which hides this from you. I have rebased and squashed the commits for you.

Yes, this was the exact issue I was facing.  
Thank you again for your time and all the work you're doing for the Angular project!

**Review by atscott — APPROVED** [review]

**Pull request closed without merging**
