### PR TITLE
docs(core): @View annotations are no longer mandatory

### PR DESCRIPTION
**Pull request by timruffles**
@View is [now optional](https://github.com/angular/angular/commit/bd31b01).

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Thanks for the PR! 

One thing: I'm not sure if it's good to say to have "optionally one **or more**..." since the latter is not implemented yet. We should either say sth. like "an optional @View decorator" or we remove it entirely it and pretend it's not there.

**Comment by IgorMinar** [comment]
Just remove it please

**Comment by IgorMinar** [comment]
let's not talk about `@View` until we have multi view support

**Comment by timruffles** [comment]
Removed the mention of "@View".

**Pull request closed without merging**
