### PR TITLE
docs: updated the preposition in the overview.md docs

### PR DESCRIPTION
**Pull request by alkavats1**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by hexiaokang — APPROVED** [review]

**Comment by alkavats1** [comment]
HI @hexiaokang @twerske please merge this PR
Thanks

**Comment by alkavats1** [comment]
Hi @jessicajaniuk Could you please merge this PR. It is approved.
Thanks

**Comment by alkavats1** [comment]
HI @AndrewKushnir please merge this PR
Thanks

**Comment by alkavats1** [comment]
Hi @JeanMeche Please merge this PR

**Comment by jessicajaniuk** [comment]
@alkavats1 There's no need to ping us on this. It's awaiting review from @twerske, and after that, the caretaker on duty will merge it.

**Comment by twerske** [comment]
Hi @alkavats1!

Thank you for your excitement in contributing to Angular! I see that you have 13+ open PRs currently, and each is small/single line change, most of which are discretionary prose changes to docs. Each of these PRs requires our team to triage (sort and label), PR review and run CI tests in order to merge these changes.

I really appreciate your efforts. In order to merge these changes, and contributions going forward, please combine these types of commits into a single PR for review, and don't worry about needing to ping us, we have lots of email alerts for reviews :) Thank you!

**Pull request closed without merging**
