### PR TITLE
chore(build): update TypeScript version to unreleased beta

### PR DESCRIPTION
**Pull request by alexeagle**
This is needed to get the --emitDecoratorMetadata flag

### CODE REVIEW

**Comment by alexeagle** [comment]
Merged in 59824e40e8354e5b8c70c8c0f81dfce2c0ecb2f4
Realized I missed the change to the SHA of hammerjs, so separately committed a7a9463624f40c17105abe4574794e0fc8302c24

**Comment by alexeagle** [comment]
Broke the build, so I need to try again...

**Comment by rkirov** [comment]
Looks like this morning's push to https://www.npmjs.com/package/typescript should be good enough instead of `mhegazy` branch.

**Comment by alexeagle** [comment]
This was merged in bb50fc131bd74bed2e394df2eaba1bcff75fc6bc

I agree we should now pull the released beta, will do that next...

**Pull request closed without merging**
