### PR TITLE
docs(core): remove experimental tag

### PR DESCRIPTION
**Pull request by mhartington**
Remove experimental note on APP_INITIALIZER.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently docs mark APP_INITIALIZER as experimental, but has been in core for about 2 years.

Issue Number: N/A

## What is the new behavior?
Removes the experimental tag in the docs

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by brandonroberts** [comment]
@mhartington will you rebase this on master?

**Comment by mhartington** [comment]
Should be good now @brandonroberts

**Comment by mhevery** [comment]
What is the reasoning for removing the experimental flag?

**Comment by mhartington** [comment]
Per conversations in GDE chat, I was under the impression that these are no longer an experimental feature. 
If that's not the case, this can be closed then.

**Comment by mhevery** [comment]
Can you make this PR green. Currently it is failing tests.

**Comment by mhevery** [comment]
ping...

**Comment by brandonroberts** [comment]
@mhevery the public API files need to be updated, correct?

**Comment by mhartington** [comment]
Hey sorry about the delay, should good after CI finishes up. @brandonroberts was showing me how the `.d.ts` needed to be update. Is there a command/script that can be run to automate this?

**Comment by brandonroberts** [comment]
It depends on the package update, but in this case to update the "golden" files, you would have run `bazel run //tools/public_api_guard:core_core_api.accept`

**Comment by brandonroberts** [comment]
@IgorMinar will you take a look at this?

**Review by IgorMinar — APPROVED** [review]

**Pull request closed without merging**
