### PR TITLE
build: Update dependencies

### PR DESCRIPTION
**Pull request by GChuf**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by GChuf** [comment]
@AndrewKushnir can you check this PR - dependency updates?
(test_aio worked fine in previous commits - maybe the test just needs to be restarted)

**Comment by AndrewKushnir** [comment]
Hi @GChuf, thanks for creating these PRs!

I've restarted failing CI job, it should go "green" since it was a flake.

We'll have a look at your PRs and provide more feedback.

Thank you.

**Comment by IgorMinar** [comment]
@GChuf thanks for the PR. Can you please help us understand why are you updating these particular dependencies? Your PR/commit description doesn't state the reason for this change. thanks

**Review by IgorMinar — COMMENTED** [review]
@GChuf thanks for the PR. Can you please help us understand why are you updating these particular dependencies? Your PR/commit description doesn't state the reason for this change. thanks

**Comment by GChuf** [comment]
@IgorMinar sure -
I tried to update as many dependencies as possible without breaking anything. Most of these updates fix various bugs and/or security issues.


check side effects: security audit
shelljs: only a fix for circular dependency warning in node v14
node-fetch: security, strongly recommended to update by the developers
minimist: security, bugs
http-server: bugs, updated sub dependencies
chokidar: lots of bug fixes, support for ARM macs added, massively improved linux ram usage and performance, stability improvements
chai - just a change in package.json.  yarn.lock file already had chai 4.2.0 inside. chai 4.3.0 breaks some tests.
bluebird: lots of bugfixes


[The other PR](https://github.com/angular/angular/pull/40727) is focused on security issues only (through resolutions).

**Review by josephperrott — APPROVED** [review]
LGTM

Thanks for updating alot of our deps!

**Comment by GChuf** [comment]
@josephperrott you can check the other PR as well, mentioned above - the one that deals with [resolutions](https://github.com/angular/angular/pull/40727). There's lots of vulnerabilities that can be fixed, if you think this is the right approach ...

**Comment by josephperrott** [comment]
Yep, I am actually doing some updates of other packages to see if we can address vulnerabilities there instead of via resolutions first.

You can see it with: https://github.com/angular/angular/pull/40807 and https://github.com/angular/angular/pull/40810

After I finish a quick audit, I was going to comment on your PR and see what still made sense to do via resolution

**Pull request closed without merging**
