### PR TITLE
fix(compiler): throw an error when styleUrls is not a CSS file

### LINKED ISSUE #9621: Component doesn't load if styleUrls is not a CSS file
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Component doesn't load without any errors

**Expected/desired behavior**
Error in console, component loads without CSS

**Reproduction of the problem**

``` typescript
@Component({
  selector: 'my-hero-detail',
  templateUrl: 'app/hero-detail.component.html',
  styleUrls: ['app/hero-detail.component.html']
})
```

**What is the motivation / use case for changing the behavior?**
People make mistakes, it should at least throw an exception/error in the console.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.3
- **Browser:** Chrome 52.0.2743.49 beta
- **Language:** all

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Closes https://github.com/angular/angular/issues/9621

### CODE REVIEW

**Comment by frederikschubert** [comment]
But what about `.scss` or `.less` files? I think it would be better to throw the error in the CSS parser where we can be sure that it is no CSS file.

**Comment by DzmitryShylovich** [comment]
Angular doesn't know anything about `sass` or `less`. You need to precompile it into `css` anyway.

**Comment by frederikschubert** [comment]
Yes, but some tools like the angular-cli allow using sass files and would break with this change.

**Comment by DzmitryShylovich** [comment]
aot webpack plugin precompiles and inlines styles

**Comment by vicb** [comment]
We do not want to make this too restrictive, closing.

**Comment by DzmitryShylovich** [comment]
@vicb then what is the proper fix for https://github.com/angular/angular/issues/9621 ?

**Comment by vicb** [comment]
We do not really have a way to detect invalid CSS for now.

**Pull request closed without merging**
