### PR TITLE
fix(aio): fix print styles

### LINKED ISSUE #23431: Documentation: Code samples aren't visible when printed
I'm reading the documentation in a printed version as it's more versatile to me than to fuzz with a tablet, particularly in bed or outdoors.

Today I noticed that when printed by Firefox (latest, Windows 10), the code samples aren't visible:

nocodeindocumentation

<hr/>

PS: I'd like to give my kudos to those guys who have set up the documentation for easy printing. Great job!

I'd like to suggest to add a page containing the documentation as a whole, so that it can be printed as one big brochure instead of dozens of small brochures with empty trailing pages.

### PR DESCRIPTION
**Pull request by gkalpak**
Fix/improve the print styles of angular.io.
This supersedes #23500. Fixes #23431.

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
This looks much better.
Is it possible to get headings to move onto the same page as the following table if the table does not fit on the current page. I think this is called "orphan headings"?
See the print preview for https://pr23538-6e80c48.ngbuilds.io/api/common/CurrencyPipe

**Comment by gkalpak** [comment]
> Is it possible to get headings to move onto the same page as the following table if the table does not fit on the current page.

We do use `page-break-after: avoid` for all headings, which is supposed to have that effect (but apparently doesn't). I also tried `break-after: avoid-page` (which is the new way to do it, but supported by fewer browsers) and still doesn't work ¯\\\_(ツ)\_/¯

https://github.com/angular/angular/blob/b0eca85e5187fbfe2f2edd02327ce2fc6f0e196b/aio/src/styles/_print.scss#L17-L19

**Comment by petebacondarwin** [comment]
What about `break-after: avoid`?

**Comment by gkalpak** [comment]
Same. Doesn't work.

**Pull request closed without merging**
