### PR TITLE
docs: add Amadou Sall to GDE resources

### PR DESCRIPTION
**Pull request by ahasall**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]

**Comment by ahasall** [comment]
Just rebased this PR. Is there anything else needed to get it merged?

**Comment by kapunahelewong** [comment]
Bonjour @ahasall! Thank you for this PR. GDE PRs always make me smile! There are a few things we need to do to merge. Could you [rebase](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) to resolve the conflict and [amend](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) your commit message so it has a body of at least 100 characters ?

Feel free to use this one if you like:

```

docs: add Amadou Sall to GDE page

This commit adds Amadou Sall to the Angular GDE page along with a biography, his role at Air France, and a photograph.

```

If you'd like some help with rebasing etc., just let me know. Please tag me when you're ready and I can help move this PR forward. Congrats! 🎉

**Comment by ahasall** [comment]
Hello @kapunahelewong,

Thank you for taking the time to review my PR and for the detailed instructions :).
I've just updated the PR and everything should be good now.

Please let me know if something else is needed.

**Comment by kapunahelewong** [comment]
Thank you, @ahasall! LGTM!

Reviewed-for: global-docs-approvers

**Review by kapunahelewong — APPROVED** [review]

**Pull request closed without merging**
