### PR TITLE
fix(forms): support both value and ng-value

### PR DESCRIPTION
**Pull request by vsavkin**

### CODE REVIEW

**Comment by vsavkin** [comment]
Did a walkthrough Kara.

**Comment by vsavkin** [comment]
Merged via https://github.com/angular/angular/commit/8db97b0b7a20e8b52f377e48f90422ba4ff5a6e7

**Comment by ericmartinezr** [comment]
@vsavkin @kara may I ask why is it `ng-value` instead of `ngValue`? IMO it may be confusing.

**Comment by kara** [comment]
@ericmartinezr  You're right; `ngValue` would be better. I'm going to file a follow-up PR. Thanks for bringing it up!

**Comment by PascalPrecht** [comment]
What was the reasoning behind having ng-value again?

**Comment by kara** [comment]
In order to support objects, we keep track of option values using a unique id, rather than the toString version of the value that is used natively (which for any object would be the dreaded "[object Object]"). This requires replacing the option element's value with a version prefixed with its id. 

Because of this, if you want to set a select's value for any reason, you have to know to prefix the value with the id (read: the original index) of the option. Something like: 

```javascript
// if value is string
mySelect.nativeElement.value = "1: Pepper"

// if value is object
mySelect.nativeElement.value = "2: Object"
```

Setting the select's value is a fairly common pattern, especially in unit testing (to mimic the user's selection of an option).  If you don't know about this special prefixing behavior, it can be confusing because using the raw value just won't work.  And for long lists with many options, counting down the list to find the index can be tedious. 

Because setting the value is such a common use case, we thought it prudent to support it as well.  

If you have a simple select with option values that are primitives, you can still use `[value]` as before and everything should work as expected. 

```html
<select [(ngModel)]="selectedCity">
   <option *ngFor="#city of cities" [value]="city">{{city}}</option>
</select>
```

```javascript
// in unit test
mySelect.nativeElement.value = "Pepper"
```

On the other hand, if your option values are objects, you can opt in to using the `ngValue` directive.

**Pull request closed without merging**
