### PR TITLE
feat: remove deprecated DOCUMENT token from platform-browser

### PR DESCRIPTION
**Pull request by CaerusKaru**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

`DOCUMENT` is a token exported by both `@angular/platform-browser` (deprecated) and `@angular/common`

Issue Number: N/A

## What is the new behavior?

`DOCUMENT` is no longer a token exported from `@angular/platform-browser`. It is now only exported from `@angular/common`

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by CaerusKaru** [comment]
cc @IgorMinar 

The saucelabs failure is a flake and just needs to be restarted.

**Comment by alfaproject** [comment]
A refactor doesn't change behaviour or break compatibility. Behaviour is being changed here and there's nothing being fixed, so I guess this is a `feat` commit.

**Comment by CaerusKaru** [comment]
@alfaproject Yeah I don't know. It's literally the opposite of a `feat` though, since it's removing something from the publicApi. And yet, _technically_, it's removed from the publicApi when it's deprecated. I'll wait until @IgorMinar weighs in, but I have no issue changing the scope to whatever's most appropriate.

**Comment by IgorMinar** [comment]
and yes, "refactor" is misleading. we might need a new category for this type of change, but in the meantime use "feat" as weird as it is because it's best category in terms of user visibility of the change in the changelog.

**Comment by StephenFluin** [comment]
Around 80% of apps I just scanned use the `DOCUMENT` InjectionToken. I can't tell from compiled source where they import it from though, so I have a hard time guessing how many will be affected.

I wouldn't have guessed that it would be many people, as I would guess most developers access `document` directly and assume web-only use cases.

**Comment by CaerusKaru** [comment]
Blocked on #29237

**Comment by CaerusKaru** [comment]
Also blocked on https://github.com/angular/material2/pull/15470

**Comment by CaerusKaru** [comment]
bump @alexeagle @IgorMinar 

This can be merged now that #29950 has been merged

**Review by mhevery — APPROVED** [review]

**Review by vikerman — APPROVED** [review]

**Pull request closed without merging**
