### PR TITLE
test(aio): correct usage of fakeAsync and inject together in an aio test

### PR DESCRIPTION
**Pull request by josephperrott**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently the test wraps `inject` around `fakeAsync`, which results in the test never running.

## What is the new behavior?
`fakeAsync` is wrapped around `inject` so the test runs as expected.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Ooops :smiley:

**Comment by gkalpak** [comment]
Thx for catching this 💯 
Can you please update the commit message to follow our [guidelines][1]?

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

**Comment by josephperrott** [comment]
@gkalpak done.

**Comment by gkalpak** [comment]
Thx, @josephperrott. Looks good, except for the type. It should be `test` instead of `fix` (since it fixes an existing test).

**Comment by josephperrott** [comment]
@gkalpak updated

**Comment by gkalpak** [comment]
The Travis failures are unrelated to the PR.

**Pull request merged**
