### PR TITLE
Add sentence case pipe

### PR DESCRIPTION
**Pull request by apoorvtomar2222**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behaviour?

Currently, we only support Titlecase, Uppercase, Lowercase.

Issue Number: N/A

## What is the new behaviour?

PR contains pipe for sentence case. The first letter of first work will be in uppercase but subsequent words will be in lower case.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by mhevery** [comment]
This looks like a very specific pipe, I don't think it should be part of the framework.

**Comment by apoorvtomar2222** [comment]
> This looks like a very specific pipe, I don't think it should be part of the framework.

@mhevery This PR was for sentence case, so it no specific to any project. Everyone might need content which should have sentence case.

**Comment by ManuelTS** [comment]
@apoorvtomar2222 what is the new status? You only fale on the CI/circlecei test:
https://circleci.com/gh/angular/angular/283819?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
I would appreciate the merge of this PR!

**Comment by petebacondarwin** [comment]
I agree with @mhevery. Angular was designed to be extended, rather than to cover all the possibilities out of the box.

Although we have some similar pipes in common (e.g. `titlecase`) this is much less common and also has more potential for variation in expectation. Also if we start down this path then we would need to provide plenty of others. For example see the option available here: https://titlecase.com/. 

This is the sort of thing that would be great in a 3rd party library. In fact there are already such libraries. For example https://www.npmjs.com/package/angular-pipes has the [`capitalize`](https://github.com/fknop/angular-pipes/blob/HEAD/docs/string.md#capitalize) and [`upperFirst`](https://github.com/fknop/angular-pipes/blob/HEAD/docs/string.md#upperfirst) pipes.

**Pull request closed without merging**
