### PR TITLE
feat(bazel): @angular/bazel compat with bazel 0.27 and rules_nodejs 0.32.2

### PR DESCRIPTION
**Pull request by gregmagolan**
Replaces #31019 which was merged but created a g3 issue so was rolled back. This PR includes a minor change to line https://github.com/angular/angular/blob/master/packages/bazel/src/ng_module.bzl#L272 which should resolve the g3 issue:

```
ERROR: /third_party/javascript/angular2/BUILD:150:1: output 'third_party/javascript/angular2/core_ngc_messages.xmb' was not created
ERROR: /third_party/javascript/angular2/BUILD:150:1: not all outputs were created or valid
Target //javascript/angular2/tools/ngc/e2e:message_extraction_test failed to build
```

* Updates to Bazel 0.27.0 and makes compatibility fixes.
* Updates to rules_nodejs 0.32.2 and makes compatibility fixes for breaking changes since 0.31.x
* Turns on symlinked node_modules finally as 0.32.2 fixes rules_nodejs#802
* Fixes worker mode issue with ts_library (yeay) -- ts_library workers should be turned back on
* Improves how ts_library consumes @types npm packages
***See 0.32.2 release notes for more info: https://github.com/bazelbuild/rules_nodejs/releases/tag/0.32.2***

## rules_nodejs 0.32.0 compat fixes

@npm//node_modules/foobar:foobar.js labels changed to @npm//:node_modules/foobar/foobar.js with fix for bazelbuild/rules_nodejs#802

## Bazel 0.27.0 compat fixes

ctx.new_file is deprecated and ctx.actions.declare_file should be used in Bazel 0.27.0. Error seen here is:
```
        File "ng_module.bzl", line 272, in _expected_outs
                ctx.new_file(ctx.genfiles_dir, (ctx.label.name ..."))
Use ctx.actions.declare_file instead of ctx.new_file.
Use --incompatible_new_actions_api=false to temporarily disable this check.
```
This can be worked around with incompatible_new_actions_api flag but may as well fix it proper so downstream doesn't require this flag due to this code.

Also, depset() is no longer iterable by default without a flag. This required fixing in a few spots in @angular/bazel.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kyliau** [comment]
global presubmit: https://test.corp.google.com/OCL:255546445:BASE:255546541:1561702976988:81435e67

**Comment by kyliau** [comment]
Presubmit after fixup: 	http://test/OCL:255546445:BASE:255643238:1561748517096:10857484

**Comment by kyliau** [comment]
g3 presubmit is green

**Comment by alexeagle** [comment]
merge assist: global approve. this is a rollforward with a google3 fix

**Pull request closed without merging**
