### PR TITLE
docs(aio): add angular-buch to resources

### PR DESCRIPTION
**Pull request by JohannesHoppe**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
Adds a link to the website of our book. Many thanks for reviewing this.

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
- no link

Issue Number: N/A

## What is the new behavior?
- one extra link to the website of the Angular-Buch.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

I'm affiliated with the website. I wrote the book.

### CODE REVIEW

**Review by StephenFluin — CHANGES_REQUESTED** [review]
Can you please update the naming to refer to 'Angular' instead of a specific version in the description? The site looks fine in this regard. 

Also, please remove 'Amazon Bestseller of 2017. Available in printed and electronic format (Kindle, PDF, ePub and Mobi).'

Love that the sources are on GitHub!

**Comment by JohannesHoppe** [comment]
Thanks for reviewing this, I'm going to make the changes soon! 🙂

**Comment by JohannesHoppe** [comment]
new text:

> The first German book about Angular. It gives you a detailed practical overview of the key concepts of the platform. In each chapter a sample application is built upon a new Angular topic. All sources are available on GitHub.

What do you think? @StephenFluin

**Review by StephenFluin — APPROVED** [review]

**Comment by JohannesHoppe** [comment]
Many thanks! :smile:

**Comment by JohannesHoppe** [comment]
Travis has a false-positive:
> The job exceeded the maximum time limit for jobs, and has been terminated.

I'm going to trigger a new build with a force push...

**Pull request closed without merging**
