### PR TITLE
docs: added '>' to ng-template closing tag.

### PR DESCRIPTION
**Pull request by jordan-amman**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Missing the ">" in the closing tag "</ng-template" in docs.
Issue Number: N/A

## What is the new behavior?
Not missing the ">" in the closing tag "</ng-template" in docs.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## Other information
Ticket:
https://github.com/angular/angular/issues/32931

### CODE REVIEW

**Comment by jordan-amman** [comment]
@kapunahelewong 
I was trying to tag https://github.com/julianomacielferreira who opened the ticket but it's not letting me for some reason.

**Comment by kapunahelewong** [comment]
@jordan-amman sometimes that happens to me, too. I donʻt really know why.

This PR looks good - thank you! Could you amend the commit message to be:

> docs: add ʻ>ʻ to ng-template closing tag
>
>Fixes #32931

The body of "Fixes #32931"  should automatically allow GitHub to close the issue when this PR is merged. Here are [my notes](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) on amending commit messaged if youʻd like to refer to them.

**Comment by jordan-amman** [comment]
@kapunahelewong 
Added Fixes #32931, thanks again! Going for the hacktoberfest challenge so any suggestions for pull requests would be appreciated if you have the time. Would like to slowly do harder pull requests if you have any in mind.

**Comment by kapunahelewong** [comment]
For harder PRs, what about advising on some? [I have one](https://github.com/angular/angular/pull/31195) myself that I donʻt know the answer to a question I came upon while working on it. Advising can be a super way of contributing, too. But, I can also be on thee look out for harder PRs, too. :)

As for hacktoberfest PRs, Iʻm not really sure...are you on Twitter? If so, letʻs chat there - might be easier to brainstorm in a chat. Gitter works too.

**Comment by kapunahelewong** [comment]
Caretaker, this is a docs only change. Thank you!

**Review by kapunahelewong — APPROVED** [review]
LGTM!

**Comment by kapunahelewong** [comment]
Caretaker, this is a docs only change. Thank you!

**Comment by kapunahelewong** [comment]
Congrats on getting this in, @jordan-amman 😊

Regarding hacktoberfest, you are welcome to go through any of the [issues assigned to me](https://github.com/angular/angular/issues/assigned/kapunahelewong?page=2&q=is%3Aopen+is%3Aissue+assignee%3Akapunahelewong) to see if they interest you. Some of them are in different stages of discussion (sometimes not obvious by just whatʻs in the issue), so if you see one you want to work on, let me know so I can share any details that are already in play. Just keep in mind that the bigger they are, the longer the review process can take - I think hacktoberfest has the deadline of the end of the month - and the more approvers youʻre likely to need. If you stick to purely docs (files in `angular/aio/content/examples` and `angular/aio/content/guide`) I am able to help more.

**Comment by jordan-amman** [comment]
@kapunahelewong I'll definitely look at the issues assigned to you and I'll stick to the docs issues at least until I get 3 more pull requests in. I'm really wanting the shirt! Thank you.

**Comment by kapunahelewong** [comment]
Best of luck @jordan-amman, let me know if you have any questions!

**Pull request closed without merging**
