### PR TITLE
Fixes double 'as an' in description at line 2069

### PR DESCRIPTION
**Pull request by skrikl**
## PR Type
- [x] Documentation content changes

### CODE REVIEW

**Comment by skrikl** [comment]
@googlebot I signed it!

**Comment by kapunahelewong** [comment]
Hi @skrikl! Thanks for this. The change is great, but it's failing the tests because the commit message has to be formatted like this:
```
docs: Fix double 'as an' in description at line 2069
```
 Can you [amend your commit message](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) and tag me when you're ready? I'd like to help you move this forward.

**Review by IgorMinar — APPROVED** [review]
thanks! but please do update the commit message

**Comment by skrikl** [comment]
Hi @kapunahelewong, thatnk you for your help :) I changed the commit message, however it looks like this time I messed up with my personal/work git usernames and the modified commit fails the tests due to this. Could you please help me out with this one more time?

**Comment by kapunahelewong** [comment]
Certainly, @skrikl! I've rebased and pushed up. Would you check it over and make sure it's what you intend? I think I got it, but can make changes if you spot something I've missed. :)

**Comment by skrikl** [comment]
Hi, @kapunahelewong! I think all is ok ok now, thank you for your help! :) Is there something that I should do from my side to finish this PR?

**Comment by kapunahelewong** [comment]
Nope, @skrikl, I think we're in good shape. Thank you!

**Review by kapunahelewong — APPROVED** [review]

**Pull request closed without merging**
