### PR TITLE
feat(bazel): provide LinkablePackageInfo from ng_module

### PR DESCRIPTION
**Pull request by gregmagolan**
This is required for ng_module to work with rules_nodejs 1.5.0+.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gregmagolan** [comment]
Waiting on https://github.com/angular/components/pull/18960

**Comment by gregmagolan** [comment]
Waiting on https://github.com/angular/components/pull/18982

**Comment by gregmagolan** [comment]
And unblocked again 🏓

**Comment by gregmagolan** [comment]
blocked again on https://github.com/angular/components/pull/18985 🏓🏓

**Comment by gregmagolan** [comment]
Unblocked again. Hopefully for real this time.

**Comment by devversion** [comment]
@googlebot I consent.

**Review by devversion — APPROVED** [review]
LGTM.

**Comment by gregmagolan** [comment]
@googlebot I consent.

**Comment by devversion** [comment]
@googlebot I consent.

**Comment by gregmagolan** [comment]
CLA is messed up. I'll rebase to force a rebuild.

**Comment by devversion** [comment]
@gregmagolan 👍 Feel free to just override the author of the commit I pushed. I just wanted to test whether invalidating the cache works.

**Comment by devversion** [comment]
@gregmagolan @josephperrott Do we have any updates on this one? It would be good if we can create the temporary patch we applied in the components repo.

**Comment by josephperrott** [comment]
@devversion I am still working on the changes to make this able to land in g3.  Its proving to be more challenging that I would expect.

**Comment by gregmagolan** [comment]
Looks like this made it in and is now released in @angular/bazel 10.1.0-next.0

**Pull request closed without merging**
