### PR TITLE
Fix: some typos

### PR DESCRIPTION
**Pull request by qmonmert**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Review by gkalpak — APPROVED** [review]
:+1:

**Comment by qmonmert** [comment]
@googlebot I signed it!

**Review by AndrewKushnir — COMMENTED** [review]
@qmonmert thanks for creating this PR!

Could you please update the commit message (`git commit --amend`) to add the scope and a bit more info on the change. Proposed commit message:
```
docs: fix some typos in angular.io examples

This commit updates example code to make the spacing more consistent.
```
Thank you.

**Comment by qmonmert** [comment]
@AndrewKushnir of course, done ✅

**Comment by AndrewKushnir** [comment]
@qmonmert just want to let you know that this PR is now merged and the changes should be available on angular.io website within the next hour or so.

Thanks for improving Angular docs! 👍

**Pull request closed without merging**
