### PR TITLE
docs: fix typos in the workspace config guide

### PR DESCRIPTION
**Pull request by rozpuszczalny**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The "dafault value" header has a typo in it "d**a**fault". Also, "prefered" has a typo in it.

Issue Number: N/A

## What is the new behavior?

The header has a correct value "d**e**fault" without a typo. Fixed "prefer**r**ed" typo as well.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]
Good catch. Thanks for your contribution.

**Comment by alan-agius4** [comment]
@rozpuszczalny I noticed there are some more instances of the typo in the same page. Can you please address them as well? Thanks.

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Review by alan-agius4 — APPROVED** [review]
LGTM, thanks

**Pull request closed without merging**
