### PR TITLE
fix(core): guarantee ngZone.onStable/onError run outside of ngZone

### PR DESCRIPTION
**Pull request by JiaLiPassion**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/angular/zone.js/issues/900

The issue is `zone.js` provide a `zone-patch-rxjs` (https://github.com/angular/zone.js/pull/843) which will make sure the `rxjs` run in the zone when created. for example.

```javascript
const zoneA = Zone.current.fork({name: 'A'});
const zoneB = Zone.current.fork({name: 'B'});
const zoneC = Zone.current.fork({name: 'C'});
const zoneD = Zone.current.fork({name: 'D'});

let observable: Observable;
let subscribe;
// constructor zone.
zoneA.run(() => {
  observable = new Observable((_subscribe) => {
     subscribe = _subscribe;
    console.log('constructing:', Zone.current.name);
  });
});

// operator zone
zoneB.run(() => {
  observable.map(value => {
       console.log('mapping:', Zone.current.name);
       return value;
  });
});

// subscription zone
zoneC.run(() => {
  observable.subscribe(value => {
       console.log('subscription:', Zone.current.name);
  });
});

// emitter zone
zoneD.run(() => {
  subscribe.next(1);
  subscribe.complete();
 });

```

as the example above, without the new `zone-patch-rxjs`, every one will run in `zoneD`.
the output will be:

```
constructor: D
mapping: D
subscription: D
```
but with `zone-patch-rxjs`, every one will run in the zone when they created.
the output will be

```
constructor: A
mapping: B
subscription: C
```

So with this new behavior change, the zoneD will not affect `observable` running zone at all.
in current `ng_zone.checkStable` call. the logic look like this.

```javascript
          zone.runOutsideAngular(() => zone.onStable.emit(null));
```
the code want to make sure the `onStable` subscription run outside of ngZone, here `zone.runOutsideAngular` use rootZone.

without `zone-patch-rxjs`, this code works, but with `zone-patch-rxjs`, the rootZone here just like the `zoneD` of the above sample. so it will not affect which zone the `subscription` will run into.

so just like the following code (with zone-patch-rxjs loaded)

```javascript
import { Component, NgZone, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnDestroy {

  private readonly zoneSubscription;

  constructor(ngZone: NgZone) {
    this.zoneSubscription = ngZone.onStable.subscribe(() => {
      console.log('testing');
    });
  }

  ngOnDestroy() {
    this.zoneSubscription.unsubscribe();
  }
}
```

`onStable` subscription was added under `ngZone`, so even the `onStable` emit outside of `ngZone`, the subscription logic will still run into ngZone and cause infinite loop, because `ngZone` will trigger `checkStable` again after the function invoked.

## What is the new behavior?

override `ngZone.onStable` and `ngZone.onError` subscribe logic, guarantee they will only subscribe in `root zone`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

@mhevery , I think this issue should be fixed in `angular` repo instead of in `zone.js` repo, please review my understanding is correct or not. Thank you!

### CODE REVIEW

**Comment by webstp** [comment]
Any update on this?

**Comment by stefan-leye** [comment]
Anny news on this? The PR is open for a long time now and the problem is kinda annoying.

**Comment by AndrewKushnir** [comment]
Hi @JiaLiPassion, is this change still relevant?

**Comment by JiaLiPassion** [comment]
I just rethink this issue, since with `zone-patch-rxjs` package is loaded, the behavior here

```
import { Component, NgZone, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnDestroy {

  private readonly zoneSubscription;

  constructor(ngZone: NgZone) {
    this.zoneSubscription = ngZone.onStable.subscribe(() => {
      console.log('testing');
    });
  }

  ngOnDestroy() {
    this.zoneSubscription.unsubscribe();
  }
}
```

the `onStable` subscription running in the `ngZone` is the correct behavior, and to make sure the subscription run outside of ngZone, the user need to do like this.

```
 constructor(ngZone: NgZone) {
    ngZone.runOutsideAngular(() => {
      this.zoneSubscription = ngZone.onStable.subscribe(() => {
        console.log('testing');
      });
    });
  }
```

So this is not an issue, I will close this PR.

**Pull request closed without merging**
