### PR TITLE
Revert "feat(core): allow for injector to be specified when creating …

### PR DESCRIPTION
**Pull request by dylhunn**
…an embedded view (#45156)"

This reverts commit 94c949a60ad0de1f5385ec97f2c1933cb1d55f22.

This PR likely caused a failure in sync cl/431510120.

### CODE REVIEW

**Comment by dylhunn** [comment]
merge-assistance: this is a pure rollback

**Review by jessicajaniuk — APPROVED** [review]

**Comment by dylhunn** [comment]
The automerge must have messed up the formatting. I ran the autoformatter on top of this rollback, and amended the rollback commit.

**Review by atscott — APPROVED** [review]

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 4b936a101406cae037fc911d9b0690b123463044.

**Pull request closed without merging**
