### PR TITLE
feat(test): find testabilities across dart js applications

### PR DESCRIPTION
**Pull request by TedSander**
Find angular testability objects across different dart js contexts by
registering each application in a global array and interrogating each
for testabilities.

### CODE REVIEW

**Comment by TedSander** [comment]
@hankduan can you review this for me?

**Comment by hankduan** [comment]
Instead of creating all these wrapper registries (i.e. _createRegistry), isn't it cleaner to do this (pseudo-code):

addToWindow(registry) {
  window['ngTestabilityRegistries'] = window['ngTestabilityRegistries'] || []
  window['ngTestabilityRegistries'].push(registry);

  window['getAngularTestability'] = function(elem) {
    // iterate through all window['ngTestabilityRegistries'] to find elem, and fail if not found
  }
  window['getAllAngularTestabilities'] = function() {
    // iterate through all window['ngTestabilityRegistries'], and aggregate all testabilities
  }
}

This way you don't have an unnecessary wrapping of the original registries.

@tbosch Can you also review this to see if this solution looks good to you? (essentially with multiple ng2 apps, the globals could override each other, and getAngularTestability/getAllAngularTestabilities would only read from the last registered registry).

**Comment by TedSander** [comment]
Registry is a dart object which needs to live in the js address space since it needs to be available to all apps. To my knowledge the objects need to be converted to jsFunctions, or jsMaps, or jsObjects. I don't think the registry itself can be converted easily. So I convert the wrappers instead.

**Comment by hankduan** [comment]
Does _jsify not work?

**Comment by hankduan** [comment]
Anyway if Registry can't be jsified, then LGTM. It would be good if you wait till Tobias takes a look though as he's much more familiar with Testability and Dart than I am.

**Pull request closed without merging**
