### PR TITLE
docs(tools): enable debug tools with current versions of Angular

### PR DESCRIPTION
**Pull request by jbandi**
Update 

## PR Type
Fix the code snippet in the documentation that shows how to enable debug tools.

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by JoostK** [comment]
I can confirm the documentation is currently incorrect. The weird thing is though, the following works just as well:

```typescript
enableDebugTools(appRef as any);
```

Looking at the constructor of `AngularProfiler` that makes sense:

https://github.com/angular/angular/blob/26a15cc53439e6069a4773ed068ffdbaed9f68e5/packages/platform-browser/src/browser/tools/common_tools.ts#L24

I am not sure why `enableDebugTools` is typed to require a `ComponentRef` and then only uses its `ApplicationRef` anyway.

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Amend the git commit message to `docs: enable debug tools with current versions of Angular`

**Comment by brandonroberts** [comment]
Thanks for the PR @jbandi! I left you some feedback. Once it gets reviewed and passes through CI checks, it should be ready to land.

**Review by IgorMinar — APPROVED** [review]

**Comment by brandonroberts** [comment]
Closing as repo has been removed.

**Pull request closed without merging**
