### PR TITLE
docs(aio): grammatical fix. remove duplicate word 'our'

### PR DESCRIPTION
**Pull request by gkalpak**
I messed up #16345 while rebasing (and now that it is closed, I can't force-push any more).
Re-applying the changes here.

### CODE REVIEW

**Comment by gkalpak** [comment]
We both have CLAs.

**Comment by souvikbasu** [comment]
Is there anything I need to fix in this pull request? Or is it good to go?

**Comment by petebacondarwin** [comment]
@gkalpak can you rebase again now that master if fixed?

**Review by wardbell — APPROVED** [review]
LGTM

**Comment by wardbell** [comment]
The CLAs are here. Just the usual two committer problem. Please merge.

**Pull request merged**
