### PR TITLE
docs(docs-infra): wrong URL for Unicode CLDR fixed

### LINKED ISSUE #53734: Wrong URL for Unicode CLDR
### Describe the problem that you experienced

In the website `https://angular.dev/guide/i18n/locale-id` there are URLs to the Unicode CLDR : `https://cldr.unicode.org/development/core-specification#h.vgyyng33o798/`  and `https://cldr.unicode.org/development/core-specification`. They both result in a 404 due to new setup

### Enter the URL of the topic with the problem

https://angular.dev/guide/i18n/locale-id

### Describe what you were looking for in the documentation

The unicode CLDR for dutch

### Describe the actions that led you to experience the problem

I clicked the URL 

### Describe what you want to experience that would fix the problem

Find the correct link

### Add a screenshot if that helps illustrate the problem

Schermafdruk van 2024-01-01 09-29-53

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by NurRehman**
fixes wrong URLs for Unicodde CLDR

Fixes #53734

## PR Type
Please check the one that applies to this PR using "x".

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Please describe the current behavior that you are modifying, or link to a relevant issue.

Issue Number: #53734

## What is the new behavior?
Now clicking on the links will route to the correct URLs instead of 404

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, we already have #53752 that fixes the issue.

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@NurRehman thanks for improving Angular docs. It looks like the CLA is not signed for one of the accounts that you've used, [see here](https://github.com/angular/angular/pull/53785/checks?check_run_id=20142122711). Could you please update the PR to have a single commit from the account that has CLA signed? Thank you.

**Comment by NurRehman** [comment]
> @NurRehman thanks for improving Angular docs. It looks like the CLA is not signed for one of the accounts that you've used, [see here](https://github.com/angular/angular/pull/53785/checks?check_run_id=20142122711). Could you please update the PR to have a single commit from the account that has CLA signed? Thank you.

I've clicked again to resign the CLA, not sure what else to do, I've 2 emails assigned to my Github account, please assist!

**Comment by JeanMeche** [comment]
This is due to 1 commit being authored by `na***m​@nadeems-mbp.home`.  check your git config !

**Comment by NurRehman** [comment]
@AndrewKushnir I've squashed the commits with proper git configuration, I can see CLA has passed now, please review again. Thanks.

**Comment by JeanMeche** [comment]
One last thing, you'll need to reword your commit to follow our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit) !

**Comment by NurRehman** [comment]
> One last thing, you'll need to reword your commit to follow our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit) !

@JeanMeche  Done!

**Comment by JeanMeche** [comment]
We'll still need this PR to be a single commit, thx for your time !

**Comment by NurRehman** [comment]
> We'll still need this PR to be a single commit, thx for your time !

@JeanMeche Looks like the PR is still under review? can you please check?

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@NurRehman thanks for updating this PR, I've added it to the merge queue. Thank you.

**Comment by AndrewKushnir** [comment]
**Caretaker note**: low-risk change, no additional reviews are required.

**Comment by atscott** [comment]
This PR was merged into the repository by commit 7ff44f94242cc042e11c5f6f132cf8977e1aae18.

**Pull request closed without merging**
