### PR TITLE
fix(animations): check for keyframes before adding previousStyleProps

### PR DESCRIPTION
**Pull request by antidiestro**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Under certain circumstances, repeated playback of an animation might result in an error caused by WebAnimationPlayer attempting to apply previous styles to an unexisting first keyframe. 

**What is the new behavior?**
This small PR fixes the issue by making sure there are keyframes in the animation before executing said code.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by ReneMoraales** [comment]
@googlebot I signed it!

**Comment by Toxicable** [comment]
Looks like some issue with browser stack again, close then reopen the PR to kick of travis again, that usually does it

**Comment by adrienverge** [comment]
Thanks for this PR! What's its status? Should the Travis build be restarted?

For information I also experience this bug, it randomly crashes with:

    TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Array.forEach (native)
    at e.init
    at t.e._queuePlayer
    at t.e.animateTransition
    ...

**Comment by adrienverge** [comment]
Hi, any news on this? It would be great to see this bug fixed!

**Comment by adrienverge** [comment]
Time to merge this!

@ReneMoraales can you close and open the PR so that tests are run again?

**Comment by fdagosti** [comment]
hi, what is the status of this PR? anything blocking its merge ?
I'm having animations errors which are linked to this small change, so would be happy to see it in the main branch :)

**Comment by ReneMoraales** [comment]
Let's hope it runs through now.

**Comment by adrienverge** [comment]
It didn't...

It seems to fail in `scripts/payload.sh` of the `aio` test:

> Error while verifying upload for PR 15858: User 'ReneMoraales' is not an active member of any of the following teams: angular-core, aio-contributors
> HTTP_CODE: 403

@IgorMinar (I think you own `aio`), any idea how to solve it?

**Pull request closed without merging**
