### PR TITLE
type the pipes to reflect string changes

### PR DESCRIPTION
**Pull request by jonnytest1**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ]  Other... Please describe:

## What is the current behavior?
the pipes dont change the type

Issue Number: N/A

## What is the new behavior?
pipes change the type

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jonnytest1** [comment]
so i think ive finished the cla oO - but i cant retry the check

**Comment by jonnytest1** [comment]
alright i completely failed the commit guideline so i tihnk im gonna redo the pull request on demand 😅

**Comment by jessicajaniuk** [comment]
> alright i completely failed the commit guideline so i tihnk im gonna redo the pull request after collecting some feedback 😅

You can do a `git commit --amend` and update the commit message to fix that. You shouldn't need to make a new PR.

**Comment by jessicajaniuk** [comment]
@jonnytest1  Can you address the broken tests? It looks like this affects the public api and would be a breaking change, since the tests are asking to update the golden files.

**Comment by jessicajaniuk** [comment]
Closing this for now, but please re-open if you want to land it.

**Pull request closed without merging**
