### PR TITLE
fix(bazel): do not modify tsconfig.json

### PR DESCRIPTION
**Pull request by kyliau**
Before this change, user's tsconfig.json is cloned and some options
controlled by Bazel are removed otherwise Bazel would complain about:

```
WARNING: your tsconfig.json file specifies options which are overridden by Bazel:
 - compilerOptions.target and compilerOptions.module are controlled by downstream dependencies, such as ts_devserver
 - compilerOptions.typeRoots is always set to the @types subdirectory of the node_modules attribute
 - compilerOptions.rootDir and compilerOptions.baseUrl are always the workspace root directory
```

Since the warning has been removed in rules_typescript/8d8d398, there's no
need to clone and backup tsconfig.json

PR Closes https://github.com/angular/angular/pull/30104

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kyliau** [comment]
@alexeagle This is now good to go, `@bazel/typescript` 0.31.1 has been released.

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
opt: update https://next.angular.io/guide/bazel#removing-bazel too

**Comment by kyliau** [comment]
> opt: update https://next.angular.io/guide/bazel#removing-bazel too

Will do so in a follow up PR.

**Comment by AndrewKushnir** [comment]
@kyliau merging this PR to patch branch failed due to some conflicts. I've changed the label to "master-only" and merged it to master. Could you please create a separate PR and target patch branch? Thank you.

**Pull request closed without merging**
