### PR TITLE
fix(core): remove closing body tag from inert DOM builder

### PR DESCRIPTION
**Pull request by bjarkler**
Fix a bug in the HTML sanitizer where an unclosed iframe tag would
result in an escaped closing body tag as the output:

```
_sanitizeHtml(document, '<iframe>') => '&lt;/body&gt;'
```

This closing body tag comes from the DOMParserHelper where the HTML to be
sanitized is wrapped with surrounding body tags. When an opening iframe
tag is parsed by DOMParser, which DOMParserHelper uses, everything up
until its matching closing tag is consumed as a text node. In the above
example this includes the appended closing body tag.

By removing the explicit closing body tag from the DOMParserHelper and
relying on the body tag being closed implicitly at the end, the above
example is sanitized as expected:

```
_sanitizeHtml(document, '<iframe>') => ''
```

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

```
_sanitizeHtml(document, '<iframe>') => '&lt;/body&gt;'
```

Issue Number: N/A

## What is the new behavior?

```
_sanitizeHtml(document, '<iframe>') => ''
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by jelbourn** [comment]
It looks like this change needs some added unit tests

**Comment by bjarkler** [comment]
Thanks @jelbourn, I added the relevant tests.

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:327279149:BASE:327279184:1597777819099:15da4402)

**Comment by bjarkler** [comment]
The contents of <iframe> are double-escaped on older IE versions. Had to update the tests to reflect that.

**Comment by bjarkler** [comment]
@mhevery Also FYI: [global presubmit](http://test/OCL:326565163:BASE:326622836:1597400106322:6f5aa1b2)

**Comment by mhevery** [comment]
@bjarkler I see that you are a googler. Can you ping me your google id?

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Review by mhevery — APPROVED** [review]

**Review by mhevery — APPROVED** [review]
reviewed-for: fw-security

**Comment by mhevery** [comment]
Reverted. [reason](https://sponge.corp.google.com/target?id=14096760-7e52-4ba4-9d4e-7224b4c19e84&target=//cloud/console/integration/tests/shell/navigation:redirect_hermetic_chrome-linux&searchFor=&show=FAILED&sortBy=STATUS)

**Pull request closed without merging**
