### PR TITLE
docs: add alert usage for single class binding

### PR DESCRIPTION
**Pull request by bampakoa**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
While it is possible to have CSS class names that are camelCase or dash-case, you must match the name exactly when using these kinds of bindings in Angular templates: see https://stackblitz.com/edit/angular-ivy-1ghqzm?file=src%2Fapp%2Fapp.component.html.

So i think that this documentation change could be a bit confusing...

**Comment by bampakoa** [comment]
Thanks very much for your feedback @petebacondarwin. Your point is totally fair. My intention was to highlight that camelCase or dash-case class names are perfectly fine to use in Angular templates. Most people, especially beginners, do not know that and end up using the `ngClass` directive. Do you think that rewording the alert towards that direction would make sense?

**Comment by petebacondarwin** [comment]
> Do you think that rewording the alert towards that direction would make sense?

I think we could land this change if it was reworded to avoid the potential confusion.

Something along the lines of "CSS classes that use dash-case can also be set using this syntax".

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
@bampakoa - thanks for updating the PR.

Reading through the new text, I feel like the "casing" of the class is actually a distraction.
The point is really that what comes after the `.` must match the CSS class exactly. I.e. Angular will do no manipulation of the string before trying to match it.

I wonder if it would be enough just to say:

>Note that class binding text must match the CSS class name exactly.
> Angular does no manipulation of the text.
> 
> For example,
> - the `[class.my-class]="expression` binding will attach the `my-class` CSS class
> - the `[class.myClass]="expression` binding will attach the `myClass` CSS class

**Comment by bampakoa** [comment]
@petebacondarwin thanks so much for your guidance on this PR. After reading your comment and thinking about it, it starts not to make sense to change that after all. If the class name matches then Angular will do its thing and will be done, no matter how the class name has been written. Is that right?

**Comment by petebacondarwin** [comment]
> @petebacondarwin thanks so much for your guidance on this PR. After reading your comment and thinking about it, it starts not to make sense to change that after all. If the class name matches then Angular will do its thing and will be done, no matter how the class name has been written. Is that right?

Yes that is my understanding.

**Comment by bampakoa** [comment]
That's great! Closing it and thank you for your tips, you helped me a lot 🙏

**Pull request closed without merging**
