### PR TITLE
refactor(ivy): remove all old styling code prior to refactor

### PR DESCRIPTION
**Pull request by matsko**
In the previous patch () all the existing styling code was turned
off in favor of using the new refactored ivy styling code. This
patch is a follow up patch to that and removes all old, unused
styling code from the render3 directory.

### CODE REVIEW

**Comment by matsko** [comment]
Presubmit = http://test/OCL:259054798:BASE:259054816:1563576936270:833f108a

Ivy Presubmit = http://test/OCL:259054798:BASE:259054881:1563576961344:6c9c60bb

**Review by kara — APPROVED** [review]
LGTM once CI is green

**Comment by matsko** [comment]
Presubmit = https://test.corp.google.com/ui#id=OCL:259054798:BASE:259467885:1563857135668:5dcd54fd

**Comment by kara** [comment]
[Ivy presubmit](http://test/OCL:259568863:BASE:259569340:1563904604221:6ff22992)

**Comment by kara** [comment]
merge-assistance: global approval

**Pull request closed without merging**
