### PR TITLE
docs: correct grammar error on start page

### PR DESCRIPTION
**Pull request by therealdennis08**
Fixed grammatical error

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]

**Comment by therealdennis08** [comment]
signed CLA and updated commit message

**Comment by JeanMeche** [comment]
The commit message should follow our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit). 

In your case it is missing the `docs:` type.

**Comment by jessicajaniuk** [comment]
@therealdennis08 Looks like you updated the PR header, but you need to also update the commit message. You can do that by running `git commit --amend` and then changing the commit message to match your PR title here. After that, push with a `--force-with-lease` and you should be good to go.

**Review by jessicajaniuk — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 95712872999c54337595acb3014cb2c67d1af683.

**Pull request closed without merging**
