### PR TITLE
chore(benchpress): make benchpress compile

### PR DESCRIPTION
**Pull request by jasonchoimtt**
Also adds compiling benchpress to the build scripts to verify that.

@IgorMinar please review.

**Please check if the PR fulfills these requirements**
- The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
Build related changes
```

**Does this PR introduce a breaking change?** (check one with "x")

```
No
```

### CODE REVIEW

**Comment by vicb** [comment]
Please make sure we format & lint BP. Thanks

**Comment by IgorMinar** [comment]
lgtm

**Comment by IgorMinar** [comment]
@alxhub can you please merge this in? no impact expected for google3.

**Comment by jasonchoimtt** [comment]
@alxhub I fixed the test script and did some clean up; should be good to merge now!

**Comment by alxhub** [comment]
Merged.

**Pull request closed without merging**
