### PR TITLE
ci: provide proper location for artifacts to allow for firebase to find the artifacts for deployment

### PR DESCRIPTION
**Pull request by josephperrott**
Move the artifacts during deployment into adev/ so that its at the same level as the firebase.json file.

### CODE REVIEW

**Review by devversion — COMMENTED** [review]
Isn't there a way to keep it local there?

**Comment by josephperrott** [comment]
Firebase does not allow for the public files to be at a higher directory than the firebase.json file.

**Comment by josephperrott** [comment]
@devversion Firebase does not allow for the public files to be at a higher directory than the firebase.json file.

**Comment by devversion** [comment]
The action does allow you to specify the directory where the output should be extracted into. I think that one should be used and then the config can continue to live local in `/adev`?

**Review by devversion — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit a057b61d1f1acecc4714d4783b490f58f52ada48.

**Pull request closed without merging**
