### PR TITLE
refactor(ng2_transform): use the latest version of pkg/protobuf

### LINKED ISSUE #4644: Upgrade Dart transformers pkg to use protobuf 0.5
It's faster! :smile:

### PR DESCRIPTION
**Pull request by kegluneq**
Closes #4644

### CODE REVIEW

**Comment by kevmoo** [comment]
@kegluneq how is this different than my CL?

**Comment by kevmoo** [comment]
LGTM

**Comment by kegluneq** [comment]
(Added label for kevmoo@)

**Comment by kevmoo** [comment]
@kegluneq this will get auto-magic merged, right?

**Comment by kegluneq** [comment]
No, not without the merge label.

I'm waiting for the next cut before submitting this, as I don't want `protobuf` changes to cause issues there.

**Pull request closed without merging**
