### PR TITLE
fix(ivy): DebugElement.query when there is a node outside Angular context

### PR DESCRIPTION
**Pull request by atscott**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Ivy throws an error when using DebugElement.query on node where a child was added with document.appendChild

Issue Number: N/A

## What is the new behavior?
No error is thrown

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by matsko — CHANGES_REQUESTED** [review]

**Review by matsko — APPROVED** [review]
Excellent :)

**Review by kara — CHANGES_REQUESTED** [review]
Some minor nits

**Review by kara — APPROVED** [review]
LGTM

**Comment by atscott** [comment]
[Presubmit](http://test/OCL:265928767:BASE:266209967:1567109171703:55652323)
[Ivy presubmit](http://test/OCL:265928767:BASE:266210160:1567109222576:42e9ded8)

**Pull request closed without merging**
