### PR TITLE
build(docs-infra): move to circleci v2 api for aio-builds

### PR DESCRIPTION
**Pull request by josephperrott**
Move to the CircleCI v2 api as the authentication now fails on v1.1.

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
LGTM with a couple of minor suggestions.

AFAICT, it is not the v1.1. vs v2 API use that makes the difference (since both result in the same URL for the build artifact), but the fact that the `?circle-token` query param no longer works as an authentication method (and we have to switch to the `Circle-Token` header).

So, could you update the commit message to mention that as well (since that is the main issue causing the failure - moving off of the v1.1 API is a good change, of course, but not directly related to the failures afaict).

Could you also please update [the docs][1] to mention that you need to use a personal API token (not a Project API token) and update the instructions on how to create it :pray:

[1]: https://github.com/angular/angular/blob/c12b3276ec6095fd1cac0e416486130e58373bd3/aio/aio-builds-setup/docs/vm-setup--set-up-secrets.md?plain=1#L27-L29

**Comment by alan-agius4** [comment]
`ci/circleci: aio_preview` seems to be still be failing even with these changes.

**Comment by gkalpak** [comment]
@alan-agius4, for these changes to take effect they need to be deployed to the preview server, which will automatically happen after this PR has been merged. (There is a [cron job][1] that pulls the latest changes from `master` every 30 mins and updates the preview server.)

[1]: https://github.com/angular/angular/blob/59a5b54c235b4988df953815a2f9078565026aad/aio/aio-builds-setup/docs/vm-setup--update-docker-container.md#run-the-script-automatically

**Comment by alxhub** [comment]
This PR was merged into the repository by commit a049840e0db4941e382b6b7046d333e58fccf688.

**Pull request closed without merging**
