### PR TITLE
docs(forms): fixes in forms documentation

### PR DESCRIPTION
**Pull request by bampakoa**
- Apply syntactical fix in forms overview guide.
- Apply fix typos in the template-driven forms tutorial.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
Thanks for the fixes @bampakoa.

FYI I've rebased this PR to re-run CI (for some reasons it didn't run last time). Once CI run is completed, this PR would be ready for the merge.

Thank you.

**Comment by AndrewKushnir** [comment]
@bampakoa the `lint` CI job indicated that the commit message should be updated ([see CI job output here](https://app.circleci.com/pipelines/github/angular/angular/18461/workflows/89f63f29-19e8-4bd9-8875-aee64d535ff3/jobs/762714/steps)), could you please update commit message(s) when you get a chance? Thank you.

**Comment by bampakoa** [comment]
@AndrewKushnir thanks for the feedback! It is ready now 👍

**Comment by AndrewKushnir** [comment]
Thanks for the updates @bampakoa, I'm marking this PR as ready for merge. Thank you.

**Pull request closed without merging**
