### PR TITLE
build(docs-infra): upgrade cli command docs sources to 78db454ce

### PR DESCRIPTION
**Pull request by gkalpak**
Updating [angular#14.0.x](https://github.com/angular/angular/tree/14.0.x) from [cli-builds#14.0.x](https://github.com/angular/cli-builds/tree/14.0.x).

##
Relevant changes in [commit range](https://github.com/angular/cli-builds/compare/b71844f36...78db454ce):

**Modified**
- help/completion.json

### CODE REVIEW

**Comment by alan-agius4** [comment]
FYI @gkalpak, I made a PR in the CLI to make this green https://github.com/angular/angular-cli/pull/23220

But I think that the code in https://github.com/angular/angular/blob/main/aio/tools/transforms/angular-base-package/services/getImageDimensions.js#L5 should be changed to use `join` instead if `resolve` and if rooted images are not meant to be used in AIO a more actionable error message is issued.

**Comment by gkalpak** [comment]
Thx, @alan-agius4 :+1:
Agreed that `.join()` makes more sense for `getImageDimensions()`. .I'll send a PR.

**Comment by gkalpak** [comment]
Blocked on angular/angular-cli#23220.

**Comment by gkalpak** [comment]
FYI: #46138

**Comment by gkalpak** [comment]
Closing so it will be recreated by the script.

**Pull request closed without merging**
