### PR TITLE
docs(changelog): remove duplicate mutate removal entry in 17.0.0

### PR DESCRIPTION
**Pull request by lebedev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently an entry about `mutate` removal in `17.0.0` changelog is duplicated.

Issue Number: N/A

## What is the new behavior?
Duplication is no more.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
This is the changelog not a documentation page. It's not ment to be amended.

**Comment by lebedev** [comment]
@JeanMeche do you mind me asking if this duplication is to stay in changelog forever then?
image

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 7eaa407c22f97122795a477f009eb55c73d76157.

**Pull request closed without merging**
