### PR TITLE
refactor(router): remove standalone true

### PR DESCRIPTION
**Pull request by sheikalthaf**
removed the standalone true from router package.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by kirjs — APPROVED** [review]
Thanks for contributing

**Comment by kirjs** [comment]
Seems like one of the tests fails PTAL

**Comment by sheikalthaf** [comment]
> Seems like one of the tests fails PTAL

@kirjs which command i have to run in local to check the testcase failure?

**Comment by JeanMeche** [comment]
It was probably a flaky test. CI is green !

**Review by AndrewKushnir — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit fe401438134472fc5b663424baad2b1145a9ae22.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
