### PR TITLE
[WIP] docs: deprecations reordered by future removal

### PR DESCRIPTION
**Pull request by jenniferfell**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Deprecated APIs and Features (https://angular.io/guide/deprecations) is organized by API and feature area, with the idea that developers should begin as soon as possible to migrate off all of these APIs and features and with the idea that a given developer might not use some area (such as routing). The doc has an introductory index by the version in which something is a candidate for removal. 

Issue Number: N/A

## What is the new behavior?
Deprecations are announced by version, so some people (so far, specifically Angular team members) who are more familiar with thinking by version have expressed an interest in a new org for this doc. This PR offers a prototype of a variant of this summary by version. 

Note: Most of those who've asked for org by version are thinking of org by the version in which deprecation was announced (past versions). That order, however, forces readers/developers to "do the math" to figure out when they need to move off the API or feature. To help with future-proofing, I've offered the idea of org by future version in which something is a candidate for removal.

Docs > Release Info > Deprecations

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by jenniferfell** [comment]
**Current org:** 
All APIs in one table, each feature its own section. 

Note: It might make sense to take descriptions of API changes, such as the pipes section, and move it to an H4 under the API heading, after the table. I made them H3s so that they are in the nav, even though

**Alternate orgs:** 

_Variant 1:_
Shorter nav, h3 level not super useful, some changes blur the line of feature/API

```
Deprecated APIs and Features
    v9 removal candidates
        APIs
            (no nav but all feature sections go under here are H4)
        Features 
            (no nav but all feature sections go under here are H4)
    v11 removal candidates
        APIs
            (no nav but all feature sections go under here are H4)
        Features 
            (no nav but all feature sections go under here are H4)
etc...
```


_Variant 2:_
Longer nav, makes API tables fit better on narrow screens

```
Deprecated APIs and Features
    v9 removal candidates
        @angular/common  
        @angular/core 
        @angular/forms 
        ...
        ngmodel in reactive forms
        (other features here as H3)
    v11 removal candidates
        @angular/common  
        @angular/core 
        @angular/forms 
        ngmodel in reactive forms
        (other features here as H3)
etc...
```


_Variant 3: title for everything_
Everything in H3 is a name, so API changes are rewritten to have a name not just a package. No xrefs needed for API changes that need more explanation. Tricky for APIs that don't have an explanation.

```
Deprecated APIs and Features
    v9 removal candidates
        i18n pipes
       CollectionChangeRecord 
       DefaultIterableDiffer
       ReflectiveInjector
       ngmodel in reactive forms
        (other APIs and features here as H3)
    v11 removal candidates
etc...
```

**Comment by jenniferfell** [comment]
Merge blocked on purpose. This content was taken from a snapshot of deprecations.md today.  As people continue to merge technical changes into deprecations.md, any such changes would need to be migrated into this doc, but it doesn't make sense to do that merge unless there's a decision to change the org. At that time, it might be safer to merge technical changes into this doc manually, rather than letting github merge which may re-introduce older text that wasn't a direct conflict.

**Comment by trotyl** [comment]
(Off topic) Question: What is the definition of **removal** for **Dependency on a reflect-metadata polyfill in JIT mode** in v11?

For `polyfills.ts` usage, the transform already applied in v8 `ng update`.
For the ability to recognizing types in `Reflect.defineMetadata()`, it can never be removed as required for non-Angular CLI environments, e.g. the StackBlitz.

**Comment by trotyl** [comment]
(Off topic) typo report:

> We expect to remove the polyfill from most if not all CLI projects via an `ng upgrade` migration from version 8 to 9.

I think the command is [`ng update`](https://angular.io/cli/update#ng-update)

**Comment by jenniferfell** [comment]
@trotyl : Thanks for the feedback, but this PR isn't about the technical content. This is a snapshot of deprecation content, for the purpose of testing an alternate organization. I recommend opening issues (or PRs :-) ) for the questions you raise. Thanks!

**Comment by trotyl** [comment]
@jenniferfell Thanks for suggestion

**Comment by trotyl** [comment]
@jenniferfell I guess the question "What is the definition of **removal** for **Dependency on a reflect-metadata polyfill in JIT mode** in v11?" might only matters here, currently it's only listed under **Deprecated features**, which is totally valid, as using `reflect-metadata` is not recommended already.

But within this change, it's going to be listed as a **removal candidate**, so there needs to be a definition of **removal**, otherwise should not be included in the list.

**Comment by jenniferfell** [comment]
@trotyl : Maybe the correct wording is "no longer supported and (if applicable) removed from Angular."

**Comment by trotyl** [comment]
@jenniferfell This isn not about support, but understanding. What being deprecated is actually:

> Dependency on a reflect-metadata polyfill in JIT **because of thinking Angular may need it**.

Any app can depend on what ever library it need, they're not owned by Angular or Google. Angular no longer need it does not ever mean using that library is deprecated.

**Comment by jenniferfell** [comment]
@trotyl : Thanks for the feedback, but I want to return to the purpose of this PR. This PR isn't about the technical content. This is a snapshot of deprecation content, for the purpose of testing an alternate organization. I recommend opening issues (or PRs :-) ) for any issues with the content itself, such as technical clarity with respect to what it means for Angular to deprecate its use of a particular 3rd party package/library. Thanks.

**Comment by petebacondarwin** [comment]
Closing as stale and so if this is something that @aikidave wants to implement it would probably be easier to start fresh.

**Pull request closed without merging**
