### PR TITLE
ci: add golden files for runtime error codes

### PR DESCRIPTION
**Pull request by AndrewKushnir**
Runtime error codes in the Core, Common and Forms packages were not included into the `public-api` group reviews. This commit creates the necessary golden files to keep track of further changes in the runtime codes.

This is a followup from https://github.com/angular/angular/pull/44398#issuecomment-1006910976.

## PR Type
What kind of change does this PR introduce?

- [x] CI related changes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

reviewed-for: public-api

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Review by devversion — APPROVED** [review]

**Comment by atscott** [comment]
This PR was merged into the repository by commit 57d0ca18e70efa37f6d80d8b48d020a807496c2b.

**Pull request closed without merging**
