### PR TITLE
Absolute uris

### PR DESCRIPTION
**Pull request by kegluneq**
@jakemac53 , per our earlier discussion, renaming `parser.dart` > `ng_deps.dart`.

Allowing `package:` uris in templates.

### CODE REVIEW

**Comment by jbdeboer** [comment]
Is there a spec file, so we can follow along with the API changes?

**Comment by jakemac53** [comment]
lgtm

**Comment by kegluneq** [comment]
Thanks for the review.

@jbdeboer , thanks for the reminder, added some entries in test/transform to exercise & demonstrate this.

**Comment by kegluneq** [comment]
Closed by a187c782aa0fa1326154f03be48c780700283eb6

**Pull request closed without merging**
