### PR TITLE
fix(compiler-cli): add warning for unused let declarations

### PR DESCRIPTION
**Pull request by crisbeto**
Adds a new extended diagnostic that will flag `@let` declarations that aren't used within the template. The diagnostic can be turned off through the `extendedDiagnostics` compiler option.

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Review by thePunderWoman — APPROVED** [review]
reviewed-for: public-api

**Review by alxhub — APPROVED** [review]
Reviewed-for: public-api

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Comment by atscott** [comment]
This PR was merged into the repository by commit c76b440ac007128c53699797811bc586220ccbe9.

The changes were merged into the following branches: main, 18.1.x

**Comment by atscott** [comment]
Reopening - this broke at least 1 place in g3 that looks to be an incorrect identification of an unused let variable (it _is_ used)
https://critique.corp.google.com/cl/654849455/analysis

**Comment by crisbeto** [comment]
> Also, should this really target patch? I think we usually consider diagnostics features.

My thinking was that since `@let` is still in developer preview, it would be fine to land this in a patch. I don't feel strongly about it so I'll switch it to `minor`.

The issue that caused the target to break has been fixed and I've run a [TGP just in case](http://test/OCL:653535225:BASE:655069467:1721723141903:eaaa8ba5) (note the one unrelated failing target).

**Comment by atscott** [comment]
This PR was merged into the repository by commit d4ff6bc0b200f0a6bb095ea4a13e52b79e254cca.

The changes were merged into the following branches: main

**Pull request closed without merging**
