### PR TITLE
docs: remove redundant web-worker nav

### PR DESCRIPTION
**Pull request by ajitsinghkaler**
Web- worker was 2 times in the nav pointing towards the same file, just with different names removed one to remove redundancy

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Redundant web worker nav

Issue Number: N/A

## What is the new behavior?
No redundant web worker nav

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ajitsinghkaler** [comment]
@IgorMinar can you please tell me why saucelabs is failing

**Comment by IgorMinar** [comment]
@ajitsinghkaler the failure looks like a flake / dev infrastructure issue.

But more importantly are you sure that this is a duplicate? I don't see this item being in the menu twice. Am I missing something?

**Comment by ajitsinghkaler** [comment]
@IgorMinar "title": "Web Workers in Angular", and  "title": "Web Workers" are the same under techniques

**Comment by ajitsinghkaler** [comment]
@IgorMinar can you please review this again

**Review by IgorMinar — APPROVED** [review]
OMG. I see it now. Thanks for pointing it out @ajitsinghkaler !

**Pull request closed without merging**
