### PR TITLE
chore: update license year

### PR DESCRIPTION
**Pull request by AngelKitty**
Happy New Year

### CODE REVIEW

**Comment by AngelKitty** [comment]
@googlebot I signed it!

**Comment by sonukapoor** [comment]
Thanks for the PR @AngelKitty. There are a few more instances to change the year. Can you change those as well?

- aio/src/app/layout/footer/footer.component.html
- packages/license-banner.txt

**Comment by AngelKitty** [comment]
@sonukapoor OK, Can you review these changes again?

**Review by sonukapoor — APPROVED** [review]
LGTM 👍

**Comment by sonukapoor** [comment]
@AngelKitty The tests/lints seems to be failing. Can you review those?

**Comment by AngelKitty** [comment]
@sonukapoor Maybe the first commit causes, I have tried many times but no way.

**Comment by sonukapoor** [comment]
> @sonukapoor Maybe the first commit causes, I have tried many times but no way.

It's possible that the `licence-banner.txt` might be created dynamically. I would revert that change, and squash all commits into one. 

Maybe someone from the Angular team can help with the `license-banner.txt` file?

**Comment by gkalpak** [comment]
It seems that some 2019 occurrences have not been updated in this PR and CI is currently failing, so I am going to close this in favor of #34651 (which is green and updates more occurrences).

Thank you, @AngelKitty, for working on this (and @sonukapoor for reviewing).
Looking forward to the next PR 😉

**Pull request closed without merging**
