### PR TITLE
build+ci(docs-infra): remove unused contributor images and add CI check

### PR DESCRIPTION
**Pull request by gkalpak**
This PR removes some unused contributor images and adds a check to ensure no unused images exist.
See individual commits for details.

### CODE REVIEW

**Review by twerske — APPROVED** [review]
lgtm - thank you for this! adding preview to check that everyone is still there :)

**Comment by gkalpak** [comment]
> adding preview to check that everyone is still there :)

You don't have to add the `preview` label to my PRs :wink:
I have a deal with @mary-poppins: I regularly send her brown paper packages tied up with strings (which apparently she likes 🤷‍♂️) and she auto-adds previews to my PRs 🦄

**Comment by petebacondarwin** [comment]
Here's a picture of @gkalpak with @mary-poppins:
 
image

**Comment by twerske** [comment]
I'd prefer raindrops on roses and whiskers on kittens!

also ty, good to know re: mary poppins

**Comment by gkalpak** [comment]
> I'd prefer raindrops on roses and whiskers on kittens!

Totally! These work really well if you live nearby and can deliver them in person.
(Pro tip: I've find out that brown paper packages work really well when you have to mail the items to @mary-poppins :wink:)

**Pull request closed without merging**
