### PR TITLE
refactor(elements): remove deps webcomponents/custom-elements.

### PR DESCRIPTION
**Pull request by JeanMeche**
`webcomponents/custom-elements` is unnecessary now that we support only evergreen browsers.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-elements

**Comment by AndrewKushnir** [comment]
@JeanMeche it looks like this PR has a merge conflict with the main branch. Could you please rebase it and resolve conflicts when you get a chance? Thank you.

**Comment by JeanMeche** [comment]
✅ @AndrewKushnir

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 8e821ca41ea08105e1c0082c07cc8578287e3c56.

**Pull request closed without merging**
