### PR TITLE
docs:  add fix bootstrapping application

### PR DESCRIPTION
**Pull request by eolamisan**
docs: add fix bootstrapping application

Successful AngularJs bootstrapping requires document ready

...
import angular from "angular";
...
angular.element(document).ready(() => {
// bootstrapping code here
});

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by eolamisan** [comment]
I signed it!

**Comment by eolamisan** [comment]
I signed it!

**Comment by eolamisan** [comment]
I don't seem to be able to modify the commit message.

**Comment by gkalpak** [comment]
I don't think this is necessary. If you are bootstrapping the Angular app, then you better have your DOM in place already :smiley:
It might be a good idea to move the `System.import(...)` script ([example][1]) to the bottom of the HTML files, though (ensuring that the necessary DOM nodes will be in place by the time the app is bootstrapped).

@eolamisan, would you be interested in making this change, instead?

[1]: https://github.com/angular/angular/blob/8334075c99f834005ec025c626cbd5d2565fed5a/aio/content/examples/upgrade-module/src/index-ajs-to-a-providers.html#L19-L22

**Comment by eolamisan** [comment]
Indeed the Angular part of the application will bootstap fine.
But the AngularJS part of the application doesn't not bootstrap unless the document ready event has fired.

**Comment by eolamisan** [comment]
@gkalpak 
Here's a [SO thread](https://stackoverflow.com/questions/16537783/which-method-should-i-use-to-manually-bootstrap-my-angularjs) regarding this to issue.

**Pull request closed without merging**
