### PR TITLE
refactor(docs-infra): refactors `addImageDimensionsImpl`

### PR DESCRIPTION
**Pull request by sonukapoor**
Change `addImageDimensionsImpl` to reduce nesting.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
LGTM - unfortunately you need to make the body of the commit message longer (>100 chars) to pass the lint check.

**Comment by sonukapoor** [comment]
> LGTM - unfortunately you need to make the body of the commit message longer (>100 chars) to pass the lint check.

I saw this new requirement, but at the same time, I can see PRs that are merged without fulfilling them - Is that normal?

This one for example https://github.com/angular/angular/commit/77d8afb7dac62ca9c4c1eb1fd05112627b2e3245

**Comment by petebacondarwin** [comment]
That looks like a special commit created by the release script. So I don't know if it had to go through the same checks.

**Comment by sonukapoor** [comment]
> That looks like a special commit created by the release script. So I don't know if it had to go through the same checks.

Yes, I will try to add some other info to the `body`

**Pull request closed without merging**
