### PR TITLE
fix(ivy): prevent invalid forward references in setClassMetadata call

### PR DESCRIPTION
**Pull request by JoostK**
In Ivy, a pure call to `setClassMetadata` is inserted to retain the
information that would otherwise be lost while eliding the Angular
decorators. In the past, the Angular constructor decorators were
wrapped inside of an anonymous function which was only evaluated once
`ReflectionCapabilities` was requested for such metadata. This approach
prevents forward references from inside the constructor parameter
decorators from being evaluated before they are available.

In the `setClassMetadata` call, the constructor parameters were not wrapped
within an anonymous function, such that forward references were evaluated
too early, causing runtime errors.

This commit changes the `setClassMetadata` call to pass the constructor
parameter decorators inside of an anonymous function again, such that
forward references are not resolved until requested by
`ReflectionCapabilities`, therefore avoiding the early reads of forward refs.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
Can you get the Travis green?

**Comment by JoostK** [comment]
@mhevery Oh well, after the rebase there's some type-checking issues that didn't show when `ts_library` was broken. I'll fix it once I get home from work tonight.

**Comment by JoostK** [comment]
@mhevery All green now, presubmit time!

**Comment by mhevery** [comment]
http://test/OCL:225239433:BASE:225239459:1544648973743:22fc81a0

**Pull request closed without merging**
