### PR TITLE
docs(PULL_REQUEST_TEMPLATE): fix formatting

### PR DESCRIPTION
**Pull request by robphoenix**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

This change means that contributors will be able to toggle the radio button for the relevant option, after submitting a PR.

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
lgtm. thanks!

**Comment by IgorMinar** [comment]
I fixed the commit message format to comply with our linting and added a better description of why we are making this change.

**Comment by IgorMinar** [comment]
caretaker note: ci is flaky and this change can't affect it.

**Comment by robphoenix** [comment]
Thanks @IgorMinar, I think I got a little confused on the commit message, thanks for fixing it up.

**Pull request closed without merging**
