### PR TITLE
docs: add strictStandalone to angular compiler options

### PR DESCRIPTION
**Pull request by voi99**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thanks for this !

**Comment by thePunderWoman** [comment]
@voi99 Looks like your commit message is causing lint to fail. Can you clean that up for us?

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit 7cb97fb1bf0098d4b235d804e8fab3323cbe8a3d.

The changes were merged into the following branches: main, 19.0.x

**Comment by voi99** [comment]
@thePunderWoman Typo 😓 Guess I was only partially hydrated

**Comment by thePunderWoman** [comment]
Yeah it's a common problem. 🙂

**Pull request closed without merging**
