### PR TITLE
docs: add missing parenthesis

### PR DESCRIPTION
**Pull request by atefBB**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by kapunahelewong — CHANGES_REQUESTED** [review]
Great catch, @atefBB! Only one tiny thing, could you amend your commit message as I've edited the PR title?

> docs: add missing parenthesis

The command if you need it: `git commit --amend`

Please tag me when you're done. Thanks!

**Comment by atefBB** [comment]
@kapunahelewong I think I can't because I havenot `fork` your repo to do this change !
Did you have any ideas how to do so?

**Comment by kapunahelewong** [comment]
Hi @atefBB, you shouldn't have to fork anything else. If you're using the command line for working with git, checkout your branch if needed and do the following:

1. `git commit --amend`
2. An editor (whichever is your default) will open. Change the name of the commit message, save, and close according to the editor. 
3. `git push` (you might have to do `git push -f`)

If you're using a GUI GitHub client, your steps will be different, but the goal is the same. Does this help?

**Comment by atefBB** [comment]
@kapunahelewong You mean `fw-dev-infra` by `my branch`?

**Comment by kapunahelewong** [comment]
@atefBB, it looks like your branch is: `patch-1`

Here it is: https://github.com/atefBB/angular/tree/patch-1

Just be sure you're on that branch locally when you amend your commit message.

**Comment by atefBB** [comment]
@kapunahelewong DONE !
Thank you for help.

**Comment by kapunahelewong** [comment]
Great @atefBB! 😊Now, to get the failing tests to pass, first start by rebasing. Your change shouldn't have caused those failures, so the first step is to make sure you're all updated when failures like that happen. Are you ok rebasing? If the commands would be helpful:

1. On your `patch-1` branch, do `git rebase upstream/master`.
2. Then `git push`. (You might need `git push -f` to force push)

That will update your branch and re-trigger the tests. Hopefully they will all pass with the latest from `master`.  Good luck!

**Comment by atefBB** [comment]
@kapunahelewong I think it's DONE !

**Comment by kapunahelewong** [comment]
Oh, something happened (see all those extra commits?). You might want to do a hard reset, **which will delete your work**, make the change again, and push it up. Luckily, itʻs a small edit.

Here are the steps:
1. On `patch-1`: `git reset --hard upstream/master`
2. Add the parenthesis again. Save, `git add --all`, `git commit -m "docs: add missing parenthesis"`
3. `git push` (might need `git push -f` if that doesnʻt work.

Youʻre doing a great job @atefBB. This can be tricky and Iʻve done this exact thing a few times!

**Comment by atefBB** [comment]
@kapunahelewong Thank you for help !
I think sending a new `proper` PR would be easier?
I'm losing with `git reset --hard upstream/master` !

**Comment by kapunahelewong** [comment]
Yes, you could also just submit a new PR. Itʻs totally your call. If you do, would you request me for review? 🌟

**Comment by petebacondarwin** [comment]
I have rebased this PR on top of master so it is only one commit now. Thanks for your patience @atefBB and @kapunahelewong

**Comment by petebacondarwin** [comment]
Caretaker (merge-assistance): this is a one character documentation change so I don't think it can be merged without tacit approval from @angular/dev-infra-framework .

**Review by filipesilva — APPROVED** [review]

**Comment by atefBB** [comment]
@petebacondarwin Thank you, Sorry for my `dirty` work !

**Pull request closed without merging**
