### PR TITLE
fix(aio): animate hamburger in/out

### LINKED ISSUE #17215: aio: animate hamburger menu on docs page
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Topnav menu changes (hamburger menu displaying) is abrupt compared to the sidenav slide out animation on the initial arrival on the docs page.

**Expected behavior**
Add smoother transition for hamburger icon.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
From home page go to docs page. See how hamburger menu and sidenav transition into the page.

### PR DESCRIPTION
**Pull request by gkalpak**
Fixes #17215.

### CODE REVIEW

**Comment by IgorMinar** [comment]
The initial position of the Angular logo at the beginning of the animations is not the same as the steady state position with menu collapsed. This causes an flicker:

pr-17335-logo-jump


-----

If you break up the animation you'll see that logo is at the steady position (screenshot 1), then is moved to the left, partly off the screen (screenshot 2), and then it's animated out (screenshots 3&4):


screen shot 2017-06-08 at 8 30 26 am
screen shot 2017-06-08 at 8 30 32 am
screen shot 2017-06-08 at 8 30 39 am
screen shot 2017-06-08 at 8 30 44 am

**Review by IgorMinar — CHANGES_REQUESTED** [review]
please fix the initial position of the animation.

**Comment by gkalpak** [comment]
Very observant 😞 This happens because on home page there is a padding on the top-bar, while on other views there isn't.

<sub>(I didn't have time to fix it and hoped nobody would notice 😛)</sub>

**Comment by gkalpak** [comment]
Fixed. PTAL

**Review by IgorMinar — APPROVED** [review]
Much better. There is still something off about that animation, but I think it's unrelated to the hamburger.

**Pull request merged**
