### PR TITLE
docs: fix typo in pipes guide

### PR DESCRIPTION
**Pull request by cchyung**
PR Checklist

Please check if your PR fulfills the following requirements:

    [ X ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
    [ N/A ] Tests for the changes have been added (for bug fixes / features)
    [ N/A ] Docs have been added / updated (for bug fixes / features)

PR Type

What kind of change does this PR introduce?

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ X ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:

What is the current behavior?

There was a typo in the first paragraph it said
"Once data arrive, you could push their raw...'
Issue Number: N/A
What is the new behavior?

Now it says
"Once data arrives, you could ... "
Does this PR introduce a breaking change?

[ ] Yes
[ X ] No

Other information

### CODE REVIEW

**Comment by cchyung** [comment]
What else needs to be done to get these tests to run?

**Comment by brandonroberts** [comment]
Thanks for the PR @cchyung! The change LGTM. 

Will you update the commit message to `docs: fix typo in pipes guide`?

**Comment by cchyung** [comment]
Updated!

**Comment by brandonroberts** [comment]
@cchyung can you update it in the git commit message? Updating the title isn't reflected there.

**Comment by cchyung** [comment]
Sorry about that.  I have updated the commit message

**Review by brandonroberts — APPROVED** [review]

**Pull request closed without merging**
