### PR TITLE
build: remove ngcontainer Docker

### PR DESCRIPTION
**Pull request by josephperrott**
ngcontainer Dockerfile was noted as deprecated ~2 years ago, we no longer
rely on it anymore nor do we publish it.

### CODE REVIEW

**Review by filipesilva — APPROVED** [review]

**Comment by josephperrott** [comment]
@IgorMinar Can you PTAL when you have a chance.

**Comment by josephperrott** [comment]
@IgorMinar any thoughts on this one?

**Review by IgorMinar — APPROVED** [review]
LGTM! Thank you!

Reviewed-for: global-approvers

**Comment by IgorMinar** [comment]
this needs a rebase, otherwise lgtm

**Pull request closed without merging**
