### PR TITLE
chore(test): Public API test failure when broser does not support Sym…

### PR DESCRIPTION
**Pull request by marclaval**
…bol.for

Fixes the first problem found in #5072 .

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Few comments:
* make the commit message shorter and fix typo in "browser"
* add a TODO to indicate that this is a temporary fix
* add more context in the commit message

What would be the long-term fix here?

**Comment by mlaval** [comment]
Done, not sure about a better fix as this API is currently inconsistent among browsers.

**Comment by gkalpak** [comment]
> make the commit message shorter and fix typo in "browser"

Not to mention that [the commit message subject should][1]:

* use the imperative, present tense
* don't capitalize first letter

:stuck_out_tongue: 

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#subject

**Comment by robwormald** [comment]
*grumbles* we'll see about that, Ms Poppins, we'll just see about that....

**Comment by robwormald** [comment]
anyway, lgtm until we figure out a clearer solution - I suspect we'll run into this if we start getting clever with lifecycle events and Symbols

**Pull request closed without merging**
