### PR TITLE
build(aio): remove unused script and GitHub token

### PR DESCRIPTION
**Pull request by gkalpak**
Since 808bd4af4, we are no longer pre-verifying PRs before uploading the build artifacts to the preview server, thus we no longer need the `travis-preverify-pr.sh` script or the `GITHUB_TEAM_MEMBERSHIP_CHECK_KEY` variable.

### CODE REVIEW

**Comment by gkalpak** [comment]
@IgorMinar, afaict the token can be revoked as well.

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
I guess you should also remove this line: https://github.com/angular/angular/blob/master/aio/aio-builds-setup/scripts/travis-preverify-pr.sh#L17

**Comment by gkalpak** [comment]
The script still needs that variable. It's just that we don't use the script any more :smiley: 
Someone/somewhere might want to use `travis-preverify-pr.sh` script, in which case, they would need to define the `GITHUB_TEAM_MEMBERSHIP_CHECK_KEY` variable.

<sub>(Although not very obvious by looking at this specific script, the `aio-builds-setup` project in general is built to be reusable, so that it can be used by other projects - e.g. material, cli etc).</sub>

**Comment by petebacondarwin** [comment]
Needs root approval - @IgorMinar

**Review by IgorMinar — APPROVED** [review]
I think that we should remove the script as well if it's not used. Old copy can always be retrieved from git history if needed.

**Comment by gkalpak** [comment]
Removed the script. PTAL

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Cherry picked as c6aacf5b17dc17453c2565989fbf20297329b24a

**Pull request merged**
