### PR TITLE
docs: add antoniocardenas to GDE resources

### PR DESCRIPTION
**Pull request by AntonioCardenas**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@AntonioCardenas Looks like your image is too large a file size. The limit is 30kb. Can you update it?

**Comment by AntonioCardenas** [comment]
> @AntonioCardenas Looks like your image is too large a file size. The limit is 30kb. Can you update it?

On my way!

**Comment by AntonioCardenas** [comment]
@jessicajaniuk Done

**Comment by jessicajaniuk** [comment]
@AntonioCardenas Thanks for that! Can you do an interactive rebase (`git rebase main -i`) and fixup the second commit into the first (in the interactive rebase, just switch the `pick` on the second commit to an `f`, save and close), then force push (`git push AntonioCardenas addtogdeantonio --force`)? That should get this PR right where it needs to be.

**Comment by jessicajaniuk** [comment]
@AntonioCardenas I rebased for you and took care of the extra commits. We should be all set to review now.

**Review by twerske — APPROVED** [review]
lgtm - thanks Antonio!

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit e4aee2b83d510c91335d1b4314ec9f7b6d4a4e5b.

**Pull request closed without merging**
