### PR TITLE
docs(api): remove extra `the`

### PR DESCRIPTION
**Pull request by manekinekko**

### CODE REVIEW

**Comment by alxhub** [comment]
Hello @manekinekko,

Can you rebase this PR and then apply the `pr_action: merge` label again (and maybe @mention me) and I will get this in ASAP.

**Comment by manekinekko** [comment]
hi @alxhub can I instead close this PR and send another one? I am not sure how I could rebase this PR.

**Comment by pkozlowski-opensource** [comment]
>  can I instead close this PR and send another one?

Sure, whatever works for you

> I am not sure how I could rebase this PR.

https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by manekinekko** [comment]
here is the correct PR https://github.com/angular/angular/pull/5483. 
Closing this one.

**Pull request closed without merging**
