### PR TITLE
fix the naive scrolling benchmark

### LINKED ISSUE #1706: naive_infinite_scroll benchmark occasionally times out with JS
When I try to run the naive_infinite_scroll with JS, it does not work for appSize=1, but works for appSize=2 or 4. Here is the command output:

```
$ xvfb-run node_modules/.bin/protractor protractor-js.conf.js --specs=dist/js/cjs/benchmarks/e2e_test/naive_infinite_scroll_perf.js 
Testing against ChromeDesktop
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://172.18.76.161:34633/wd/hub
Started
BENCHMARK ng2.naive_infinite_scroll
Description:
- appSize: 1
- forceGc: false
- iterationCount: 20
- lang: js
- regressionSlopeMetric: scriptTime
- runId: 279f0450-f419-11e4-b18b-7f8be8bbe531
- sampleSize: 20
- scrollIncrement: 40
- userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
Metrics:
- gcAmount: gc amount in kbytes
- gcTime: gc time in ms
- majorGcTime: time of major gcs in ms
- pureScriptTime: script execution time in ms, without gc nor render
- renderTime: render time in ms
- scriptTime: script execution time in ms, including gc and render

          gcAmount |             gcTime |        majorGcTime |     pureScriptTime |         renderTime |         scriptTime
------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------
FBENCHMARK ng2.naive_infinite_scroll
Description:
- appSize: 2
- forceGc: false
- iterationCount: 20
- lang: js
- regressionSlopeMetric: scriptTime
- runId: 279f0450-f419-11e4-b18b-7f8be8bbe531
- sampleSize: 20
- scrollIncrement: 40
- userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
Metrics:
- gcAmount: gc amount in kbytes
- gcTime: gc time in ms
- majorGcTime: time of major gcs in ms
- pureScriptTime: script execution time in ms, without gc nor render
- renderTime: render time in ms
- scriptTime: script execution time in ms, including gc and render

          gcAmount |             gcTime |        majorGcTime |     pureScriptTime |         renderTime |         scriptTime
------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------
         129271.12 |             124.49 |              71.84 |            1354.75 |             159.58 |            1408.33
           6629.58 |               7.42 |               7.42 |             130.26 |             112.06 |             130.50
              0.00 |               0.00 |               0.00 |             126.73 |             103.92 |             127.42
              0.00 |               0.00 |               0.00 |             130.33 |             120.87 |             130.99
              0.00 |               0.00 |               0.00 |             114.36 |             107.12 |             114.48
          13961.02 |               4.13 |               0.00 |             103.59 |             103.14 |             103.87
              0.00 |               0.00 |               0.00 |              97.30 |              97.50 |              97.83
              0.00 |               0.00 |               0.00 |             111.15 |             127.92 |             111.71
              0.00 |               0.00 |               0.00 |             104.67 |             120.44 |             105.22
          12104.96 |               6.60 |               0.00 |             113.26 |             106.10 |             120.49
              0.00 |               0.00 |               0.00 |             110.75 |             112.69 |             111.21
          16784.38 |               9.21 |               9.21 |             115.31 |             128.78 |             125.02
              0.00 |               0.00 |               0.00 |              98.49 |             106.05 |              98.72
              0.00 |               0.00 |               0.00 |             103.28 |             113.17 |             103.82
          17238.30 |               8.45 |               8.45 |             151.78 |             174.98 |             160.77
              0.00 |               0.00 |               0.00 |             102.35 |              97.08 |             102.83
              0.00 |               0.00 |               0.00 |             101.08 |             111.22 |             101.71
              0.00 |               0.00 |               0.00 |             104.82 |             110.89 |             105.37
          13953.63 |               4.30 |               0.00 |             111.55 |             141.78 |             116.11
              0.00 |               0.00 |               0.00 |             113.37 |             131.34 |             114.10
              0.00 |               0.00 |               0.00 |             108.08 |             124.04 |             108.63
              0.00 |               0.00 |               0.00 |             109.88 |             125.82 |             110.54
          12076.77 |               9.70 |               0.00 |             106.25 |             118.35 |             116.52
              0.00 |               0.00 |               0.00 |             107.78 |             132.07 |             108.25
================== | ================== | ================== | ================== | ================== | ==================
     4305.95+-154% |         2.12+-163% |         0.88+-300% |        109.46+-10% |        119.52+-14% |        111.86+-11%
.BENCHMARK ng2.naive_infinite_scroll
Description:
- appSize: 4
- forceGc: false
- iterationCount: 20
- lang: js
- regressionSlopeMetric: scriptTime
- runId: 279f0450-f419-11e4-b18b-7f8be8bbe531
- sampleSize: 20
- scrollIncrement: 40
- userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
Metrics:
- gcAmount: gc amount in kbytes
- gcTime: gc time in ms
- majorGcTime: time of major gcs in ms
- pureScriptTime: script execution time in ms, without gc nor render
- renderTime: render time in ms
- scriptTime: script execution time in ms, including gc and render

          gcAmount |             gcTime |        majorGcTime |     pureScriptTime |         renderTime |         scriptTime
------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------
          60307.14 |              58.18 |              29.97 |             846.57 |             159.96 |             887.22
              0.00 |               0.00 |               0.00 |             159.89 |             128.55 |             160.48
          15487.47 |              10.07 |              10.07 |             121.48 |              99.59 |             132.24
              0.00 |               0.00 |               0.00 |             143.45 |             131.58 |             143.78
              0.00 |               0.00 |               0.00 |              99.51 |              78.94 |              99.70
              0.00 |               0.00 |               0.00 |             114.89 |             114.05 |             115.23
          14009.92 |               3.85 |               0.00 |             118.74 |             131.70 |             119.00
              0.00 |               0.00 |               0.00 |             111.62 |             100.92 |             112.40
              0.00 |               0.00 |               0.00 |             105.44 |             112.54 |             106.22
          12524.57 |               6.24 |               0.00 |             116.52 |             116.42 |             123.14
              0.00 |               0.00 |               0.00 |             103.36 |             103.10 |             104.09
              0.00 |               0.00 |               0.00 |             129.63 |             115.27 |             130.41
              0.00 |               0.00 |               0.00 |             118.12 |             103.93 |             118.61
          12855.11 |               5.07 |               0.00 |             114.40 |             110.20 |             119.71
          16593.39 |              17.48 |              17.48 |             122.71 |             109.29 |             140.82
              0.00 |               0.00 |               0.00 |             121.52 |             128.19 |             122.17
              0.00 |               0.00 |               0.00 |             132.61 |             126.03 |             133.40
          19063.10 |               9.91 |               9.91 |             110.76 |             105.24 |             120.90
              0.00 |               0.00 |               0.00 |             110.48 |             124.40 |             110.87
              0.00 |               0.00 |               0.00 |             120.80 |             135.39 |             121.01
              0.00 |               0.00 |               0.00 |             104.92 |             100.64 |             105.84
          14098.67 |               3.72 |               0.00 |              95.92 |             105.78 |              96.15
              0.00 |               0.00 |               0.00 |             120.56 |             123.47 |             121.22
              0.00 |               0.00 |               0.00 |             102.71 |             110.13 |             103.33
          12504.82 |               5.99 |               0.00 |             101.59 |              93.12 |             107.83
              0.00 |               0.00 |               0.00 |             118.70 |             117.19 |             119.39
              0.00 |               0.00 |               0.00 |             101.81 |             112.69 |             102.38
              0.00 |               0.00 |               0.00 |             133.20 |             120.31 |             133.83
          12837.22 |               5.24 |               0.00 |             110.64 |             109.52 |             116.49
          16582.83 |              18.17 |              18.17 |             124.72 |             146.29 |             143.56
              0.00 |               0.00 |               0.00 |             111.45 |              97.62 |             111.75
              0.00 |               0.00 |               0.00 |             122.32 |             119.20 |             123.04
              0.00 |               0.00 |               0.00 |             114.65 |             122.20 |             114.90
          21068.11 |              14.54 |               9.25 |             100.92 |              88.85 |             101.45
              0.00 |               0.00 |               0.00 |             115.77 |             124.06 |             116.16
              0.00 |               0.00 |               0.00 |             124.07 |             142.72 |             124.38
================== | ================== | ================== | ================== | ================== | ==================
     4807.74+-157% |         2.88+-182% |         1.87+-252% |         113.93+-9% |        116.24+-12% |        116.39+-10%
.

Failures:
1) ng2 naive infinite scroll benchmark should run scroll benchmark and collect stats for appSize = 1
  Message:
    Failed: Error: Wait timed out after 10031ms
  Stack:
    Error: Failed: Error: Wait timed out after 10031ms
        at /usr/local/google/home/het/git/angular/node_modules/protractor/node_modules/jasminewd2/index.js:102:16
        at [object Object].promise.ControlFlow.runInFrame_ (/usr/local/google/home/het/git/angular/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
        at [object Object].promise.Callback_.goog.defineClass.notify (/usr/local/google/home/het/git/angular/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)
        at [object Object].promise.Promise.notify_ (/usr/local/google/home/het/git/angular/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)

3 specs, 1 failure
Finished in 66.846 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```

### PR DESCRIPTION
**Pull request by vicb**
@tbosch I've fixed this by removing the explicit `browser.wait()`. IIRC you told me this is not required any more and for some reason it seems to be blocking and prevent the scrolling from happening.

Also switch from `id` to `class` for repeated elements (`id`s are supposed to be unique - must be releated to switching to the emulated SDS).

fixes #1706

### CODE REVIEW

**Comment by tbosch** [comment]
@vicb sorry, we really have to wait here, as the benchmark itself is asynchronous :-(

**Comment by tbosch** [comment]
But you could try to change the polling interval of wait, maybe that helps.

**Comment by vicb** [comment]
@juliemr any idea on why this does not work / how to solve this ?

Notes:
- Increasing the timeout (up to 50s) does not work,
- Only the first test fails, subsequent tests are fine (whatever their order),
- The element gets added [here](https://github.com/angular/angular/blob/c8d83dba7da9a23300e7b097f5bfb60a47c6f1d1/modules/benchmarks/src/naive_infinite_scroll/app.js#L74)

**Comment by tbosch** [comment]
Btw, we are reloading the app for every benchmark run...

**Comment by vicb** [comment]
@tbosch @juliemr can we do something like `browser.wait(until.elementTextIs($('#done'), 'Finished'), 10000);` in e2e tests (it triggers `until is not defined`)

**Comment by juliemr** [comment]
@vicb Yes, we'll want to use http://angular.github.io/protractor/#/api?view=ExpectedConditions.

**Comment by vicb** [comment]
@juliemr I haven't actually managed to use `ExpectedConditions` (I was to able to use `protractor.until...`). However the issue here is that the scroll does not start so it is even before we try to locate the `#done` element.

Adding a 1s delay before the test seem to improve the situation. Is it possible that the test start before Angular is actually ready ???

Anyway I'v e re-assigned to you as I don't think I could do more.

Thanks

**Comment by juliemr** [comment]
Ok, I'll give it a shot!

**Comment by jeffbcross** [comment]
@juliemr have you made any progress on this?

**Comment by juliemr** [comment]
No, haven't had a chance to look yet. It's on my todo list after https://github.com/angular/protractor/issues/2245

**Comment by juliemr** [comment]
To be clear - the [errors that I'm seeing](https://travis-ci.org/angular/angular/jobs/67423810) are

```
F>> http://localhost:8001/benchmarks_external/src/naive_infinite_scroll/index.js 0:0 Failed to load resource: the server responded with a status of 404 (Not Found)
>> http://localhost:8001/benchmarks_external/src/naive_infinite_scroll/zone-microtask.js 115:17 Not Found: http://localhost:8001/benchmarks_external/src/naive_infinite_scroll/index.js
```

@vicb @tbosch is this the problem this PR is trying to fix?

**Comment by vicb** [comment]
I don't think so. I have actually never seen this issue.

The error that I see, consistently on my machine and time to time on Travis is a timeout error.

In the browser I can see the list but it never scrolls and result in a timeout.

**Comment by tbosch** [comment]
Hi, just saw the error again: https://travis-ci.org/angular/angular/jobs/67432557
It's in the angular2 version of the benchmark.

**Comment by juliemr** [comment]
Thanks @vicb. Can you share the details of your machine? I'm not able to reproduce locally, but I see a Travis timeout: https://travis-ci.org/angular/angular/jobs/67432557

**Comment by vicb** [comment]
Ubuntu & Google chrome unstable

**Comment by juliemr** [comment]
This should be closed with https://github.com/angular/angular/pull/2678

**Pull request closed without merging**
