### PR TITLE
build: update licence date.

### PR DESCRIPTION
**Pull request by JeanMeche**
Wasn't done last year, let's do it in 2024

### CODE REVIEW

**Review by devversion — APPROVED** [review]

**Review by JiaLiPassion — APPROVED** [review]
LGTM!

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by atscott** [comment]
This PR was merged into the repository by commit 03581b929cd9470bb0c6bf7a705374f7d422bda4.

**Pull request closed without merging**
