### PR TITLE
fix(zone.js): patch global instead of Mocha object

### LINKED ISSUE #42834: zone.js fails to patch mocha v8.3.1 and up
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I've created a fresh Angular 12 project with the CLI, refactored tests to use Mocha instead of Jasmine and the tests failed.

- Clone the repo and run `npm test` - everything will work fine
- Open `package.json` and set the `mocha` dependency to `8.3.1` or higher, then run `npm test` again
- You'll now get the exception below.

### Please provide a link to a minimal reproduction of the bug

https://github.com/Alorel/zone.js-mocha-patch-bug-reproduction

### Please provide the exception or error you saw

```
RangeError: Maximum call stack size exceeded
      at wrapTestInZone (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:1024:1)
      at global.beforeEach.global.setup.Mocha.beforeEach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:1077:1)
      at exports.beforeEach (node_modules/mocha/mocha.js:28402:65)
      at global.beforeEach.global.setup.Mocha.beforeEach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:1077:1)
      at exports.beforeEach (node_modules/mocha/mocha.js:28402:65)
      at global.beforeEach.global.setup.Mocha.beforeEach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:1077:1)
      at exports.beforeEach (node_modules/mocha/mocha.js:28402:65)
      at global.beforeEach.global.setup.Mocha.beforeEach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:1077:1)
      at exports.beforeEach (node_modules/mocha/mocha.js:28402:65)
      at global.beforeEach.global.setup.Mocha.beforeEach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:1077:1)
```

### Please provide the environment you discovered this bug in

```
Angular CLI: 12.1.1
Node: 14.16.1
Package Manager: npm 7.11.2
OS: linux x64

Angular: 12.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.5
```

### Anything else?

The `zone.js` version is `0.11.4`. The same happens on Angular 11 and zone `0.11.3`

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Close #42834

In the new version fo Mocha, all global test functions are from `global`
object instead of `Mocha` object. Adn the current `zone.js` Mocha
patch's logic looks like this.

```
global.describe = Mocha.describe = function() {
  return originalMochaDescribe.apply(this, arguments);
}
```

and `originalMochaDescribe` is the unpathced Mocha implementation
looks like this

```
function describe() {
  return context.describe(...);
}
```

And the `context` will finally delegate to `global.describe()`,
so the current `zone.js` patch causes infinite loop.

This commit will not patch function of `Mocha` object any longer.

### CODE REVIEW

**Review by atscott — APPROVED** [review]
reviewed-for: integration-tests

Verified that tests ran and passed

```
//integration/cli-hello-world-mocha:test                                 PASSED in 79.9s
```

https://app.circleci.com/pipelines/github/angular/angular/42590/workflows/ba543a9b-bf28-4af5-8465-1a46c3242ca2/jobs/1120899

**Comment by atscott** [comment]
@JiaLiPassion Is there a reason this is marked as minor and not patch? Since it's a fix, I would have thought we would want to merge this to patch as well.

**Comment by JiaLiPassion** [comment]
@atscott , thank you for the review, I have updated the target to patch.

**Review by atscott — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit ee381dadc2fa6af13da94b7bbe4995c49c2ec472.

**Comment by dpraul** [comment]
Is there a new release scheduled for zone.js so that we can utilize this patch?

**Pull request closed without merging**
