### PR TITLE
[DO NOT MERGE IN 2.x - 4.x only] refactor(hooks): change abstract classes for interfaces

### LINKED ISSUE #10083: Lifecycle interfaces became abstract classes
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
export declare abstract class OnInit {
    abstract ngOnInit(): any;
}
```

**Expected/desired behavior**

```
export interface OnInit {
    ngOnInit(): void;
}
```

This is valid in TypeScript, but it does not look right:

```
class Some extends OnInit {
      ...
}
```

vs

```
class Some implements OnInit,OnChanges {
     ...
}
```

vs

```
class Some extends OnInit, OnChanges { //compile error
     ...
}
```

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Fixes https://github.com/angular/angular/issues/10083

### CODE REVIEW

**Comment by vicb** [comment]
Thanks for the PR:
- This is a breaking change, can only be merged for 3.0 & need to be documented in the commit comment,
- Also depends on https://github.com/angular/angular/pull/12227 which should fix CI failures

**Comment by DzmitryShylovich** [comment]
@vicb We can probably merge this into 4.0 branch

**Comment by vicb** [comment]
Yes once:
- CI is green,
- Commit headline is refactor(...): change abstract classes for  interfaces,
- Commit message state that this is a breaking change.

**Comment by DzmitryShylovich** [comment]
@vicb done

**Comment by vicb** [comment]
thanks !

**Comment by IgorMinar** [comment]
I was about to merge this in but then realized that the breaking change is not properly documented (in terms of impact on the end users) and upon further digging in I realized that this is actually a bigger breaking change than what it look like. I'd like to have us take one more look at the impact of this change before we merge it in.

I describe my concerns in this typescript snippet: https://goo.gl/sW8qLW

**Comment by DzmitryShylovich** [comment]
> that the breaking change is not properly documented

I think u are underestimate your users :)
Just would need to add a note in the changelog that it can possibly break some code and it would be enough.
All examples on angular.io use `implements`. It doesn't mention abstract classes at all https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#interface-optional
We can call it an impl detail

> in case someone created a popular blog post, tutorial, seed

so we shouldn't change code because of a blog post? I think it's a dead end

Plus in 2.3.1 angular added support for inheritance and using `extends` for lifycycle hooks u will no longer abler to extend anything else.

**Comment by mhevery** [comment]
I think it is unlikely that people today are extending `OnInit` rather than implementing. I think this is fine for v4, but needs better documentation as pointed out.

**Comment by IgorMinar** [comment]
I spoke with @mhevery and @juleskremer and we agreed that Angular DevRel is going to review this, estimate impact and weigh in on this before we merge it in.

The problem is that our promise to the community was that no changes in Angular 4 would break existing components. We don't know if any existing components that people depend on rely on "extends" rather than "implements" and if there are any that do, then people won't be able to use them if they are 3rd party components that they can't change. We promised to make the upgrade to A4 smooth and this change has a potential to make it not smooth, so we need to be cautions.

DevRel will review this, and suggest the path forward for this change.

Just to be clear, I think this is a good change, we just need to be careful about how we roll it out so that we don't break the Angular ecosystem and with that our promises to the community.

**Comment by IgorMinar** [comment]
@robwormald it could. it might be a good idea to roll that out now (specific to our hooks only) so that we start warning people about this now. But we still don't know how many projects are being covered by lint/codelyzer and how many of them will use the updated version before A4.

**Comment by DzmitryShylovich** [comment]
what's so special with lifecycle hooks? For example, this https://github.com/angular/angular/pull/13785 pr will break **all** apps because every decent app uses OpaqueTokens. and this pr will probably break <1% users

**Comment by IgorMinar** [comment]
@DzmitryShylovich I pushed back on that one as well. We need to really understand the impact of these kinds of changes before merging them in.

**Comment by DzmitryShylovich** [comment]
It will also decrease file size.

**Comment by IgorMinar** [comment]
@DzmitryShylovich can you please rebase this one? If things are looking good with the view engine, we'll attempt to land this PR.

**Comment by DzmitryShylovich** [comment]
@IgorMinar done

**Comment by IgorMinar** [comment]
thanks @DzmitryShylovich

**Pull request merged**
