### PR TITLE
docs: add preston lamb to GDE resources

### PR DESCRIPTION
**Pull request by pjlamb12**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Add Preston Lamb to GDE contributors list

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by pjlamb12** [comment]
@googlebot I signed it!

**Comment by AndrewKushnir** [comment]
Hi @pjlamb12, thanks for creating this PR.

I've noticed that the CI jobs are failing due to the following error:

```
Error: The following keys in 'contributors.json' are not in alphabetical order: 'prestonjlamb' and 'pkozlowski-opensource'.
```

Could you please the `contributors.json` file (to keep keys in alphabetical order) and leave a comment on when it's done, so that we can take another look?

Thank you.

**Review by mgechev — APPROVED** [review]
LGTM

**Comment by AndrewKushnir** [comment]
Hi @pjlamb12, thanks for fixing the ordering issue. Could you please also squash commits into a single one? Once it's done, we'll add this PR to the merge queue. Thank you.

**Comment by pjlamb12** [comment]
@AndrewKushnir Sorry, I'm not the best with git. Can you tell me the easiest way to do this? I tried running `git rebase -i`, and it didn't seem to work as I was hoping.

**Comment by pjlamb12** [comment]
@AndrewKushnir I think I may have gotten it...

**Comment by AndrewKushnir** [comment]
@pjlamb12 it looks like the problem with ordering was still there, so I've pushed a fixup commit with the necessary change. Once CI is completed( and there are no errors indicated), we'll add this PR to the merge queue.

**Comment by pjlamb12** [comment]
@AndrewKushnir thanks for the help. I'm sure I just did the remade incorrectly 🤦🏾

**Comment by AndrewKushnir** [comment]
@gkalpak could you plz help look into [the `aio_preview` CircleCI job](https://app.circleci.com/pipelines/github/angular/angular/29739/workflows/ca353b34-c1af-41b5-895b-b50a04f3fdc0/jobs/940505) that is failing with the following error:

```
Error: Request failed (status: 413): CircleCI artifact download failed (content size at <URL> over limit: 26214400)
```

Is that related to the use of an empty image or there is a size limit that we should update?

Thank you.

**Comment by petebacondarwin** [comment]
The image is too big: ~3Mb!!

**Comment by AndrewKushnir** [comment]
@petebacondarwin thanks! I was confused by the GitHub UI that shows `Empty file.` 🤦 

@pjlamb12 could you please update image resolution/size, so that it's around 20Kb?

**Comment by pjlamb12** [comment]
Ah, I should have checked that I will fix the image.

**Comment by pjlamb12** [comment]
@AndrewKushnir okay, the image is smaller, and I noticed that my name was in the json file twice, so I removed the duplicate.

**Comment by AndrewKushnir** [comment]
Thanks for the update @pjlamb12.
FYI I've squashed commits into the first one, this PR should be ready for merge once CI is completed.

**Pull request closed without merging**
