### PR TITLE
Fix: Update Angular index.html DOM text reinterpreted as HTML

### PR DESCRIPTION
**Pull request by Shivam7-1**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:

By using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML.

### CODE REVIEW

**Comment by Shivam7-1** [comment]
Hi @thePunderWoman Could You Please Review This PR 
Thanks

**Comment by JeanMeche** [comment]
Hi, this is a unit test that we are not looking to update. Thank you for you contribution tough. Feel free to drop any usefull PR, thank you for your understanding.

**Comment by Shivam7-1** [comment]
Hii @JeanMeche Thanks For Reviewing
I want to Contribute to Angular Project Could Please Let me Know that How Should I find this is for unit test or not ?

Regards

**Comment by Shivam7-1** [comment]
Hi @thePunderWoman Could You Please Review This PR 
Ad I think this file is not for Unit Test Could 
Thanks

**Pull request closed without merging**
