### PR TITLE
docs: add Maina Wycliffe to GDE resources

### PR DESCRIPTION
**Pull request by mainawycliffe**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mgechev — APPROVED** [review]
Welcome!

**Comment by mgechev** [comment]
@mainawycliffe looks like your photo is too big. Can you resize to under 30KB?

**Comment by mainawycliffe** [comment]
@mgechev let me resize it.

**Review by mgechev — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 17d66d9302387498f9175a08723abca962251bad.

**Pull request closed without merging**
