### PR TITLE
Improper break link in documentation/comments

### PR DESCRIPTION
**Pull request by khyamay**
I saw that there was new line break on some of documentation/comments. I dont know if they are intentional, if they are please ignore the pull request but I think with proper line breaks it's easier to read the documentation/comments thanks.

### CODE REVIEW

**Comment by khyamay** [comment]
I signed It!

**Comment by tbosch** [comment]
Sorry, but we are using `clang-format` to format all of our source files. By changing the docs this file would nee to be reformatted. Could you do so? Closing for now, please open a new one.

**Comment by vicb** [comment]
@khyamay :+1: for the change, the current version is hard to read but as Tobias said, you need to make sure clang-format will not mess with your changes (make sure lines have less than 100 chars).

There are guidelines in the DEVELOPER.md (or CONTRIBUTRING.md) on how to run it.

**Comment by khyamay** [comment]
Hi Victor, thanks for the reply, I will have a look at it :)

**Pull request closed without merging**
