### PR TITLE
fix(aio): copy code button overlap fix on mobile

### LINKED ISSUE #17247: aio: code copy button overlays code
Here's an example:

image

This is annoying but shouldn't block the first release of the Doc Viewer (IMO).

### PR DESCRIPTION
**Pull request by sjtrimble**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Closes https://github.com/angular/angular/issues/17247

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by gkalpak** [comment]
This sure doesn't close #17248 :smiley:

**Review by gkalpak — COMMENTED** [review]
This works better than before, but there can still be overlap:

copy-btn

(Example from the [Hero object][1] section of the tutorial.)

[1]: https://pr17302-4a83e1154e54a42bdeca739d18b2d41cc0c15a8f.ngbuilds.io/tutorial/toh-pt1#hero-object

**Comment by sjtrimble** [comment]
@gkalpak I tried to focus on mobile 480px or smaller but I will see if I can bump that up to cover this as well.

**Comment by wardbell** [comment]
I thought we said our lower bound was 600px wide?

**Comment by sjtrimble** [comment]
@wardbell Take a look .. I checked a few scenarios and it looked better now across all sizes. I think someone changed some styles on the `aio-code-pre` blocks a while back which caused this to happen.

**Review by IgorMinar — APPROVED** [review]

**Pull request merged**
