### PR TITLE
ci: configure Renovate to disable updates for  dependencies versioned `0.0.0-PLACEHOLDER`     

### PR DESCRIPTION
**Pull request by alan-agius4**
ci: configure Renovate to disable updates for  dependencies versioned `0.0.0-PLACEHOLDER`
    
With this change we disable Renovate from updating `@angular/*` peerDependencies which are versioned `0.0.0-PLACEHOLDER`.
    
Example PR: https://github.com/angular/angular/pull/41615

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
NOTE to other reviewers - most of the changes here are just whitespace formatting.

**Comment by alan-agius4** [comment]
Kindly review each commit individually.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by zarend** [comment]
@alan-agius4 I cannot merge this PR because it has merge conflicts with `master` and `12.0.x` 😢 . Please rebase this PR.

**Pull request closed without merging**
