### PR TITLE
docs(forms): warn the user about getting old values and show how to a…

### PR DESCRIPTION
**Pull request by sr5434**
This edit addresses issue #49898

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

There is no warning about trying to access the value of a form control using FormGroup.FormControl.value. Doing this can result in getting old values.
Issue Number: #49898

## What is the new behavior?
Advises the user to use FormGroup.controls.FormCOntrol.value.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sr5434** [comment]
@josephperrott can you please add the aio:preview again? Thanks.

**Review by AndrewKushnir — COMMENTED** [review]
@sr5434 thanks for creating a PR.

I'm a bit confused on what this warning refers to. I think it might be helpful in some context, but the proposed change just adds it at the very top of the reactive forms guide. What is a use-case in which this warning becomes relevant?

**Comment by sr5434** [comment]
In the issue, the author mentions, “on change of field1 or field2 you want to automatically change field 3.” And says, “This doesn't work, since the parent isn't yet updated when the call back is called.” I can add in this example use case if you want.

**Comment by AndrewKushnir** [comment]
@sr5434 thanks for additional info. I think the best place for this information would be API documentation for valueChanges and stateChanges, i.e. https://angular.io/api/forms/AbstractControl#valueChanges. A note that we can add there can mention that the emit happens when a value of a given control changes. Parent controls are updated after that, so if you try to access parent control value from the valueChanges or stateChanges callback - it might have an old value.

**Comment by sr5434** [comment]
Ok, sure

**Comment by yelhouti** [comment]
@AndrewKushnir I agree, the current update of the doc doesn't explain the problem not the solution.
But I think we should do the explanation (also?) in the file modified by this PR since this is the place where people learn about reactive forms.

**Comment by sr5434** [comment]
@AndrewKushnir can I tweak your wording and use it in the note? Also, should I leave a similar warning in the reactive forms guide?

**Comment by sr5434** [comment]
Also, I can't seem to find a place to edit that specific doc. It sends me to a source file but not the markdown file with the content, and I can't find it in the repo.

**Comment by JeanMeche** [comment]
Yes ! Parts of the doc (those under `/api/` in the url) are generated from the source files !

**Comment by AndrewKushnir** [comment]
> can I tweak your wording and use it in the note?

@sr5434 sure, feel free to use any content from my comment and update it as you see fit. 

> should I leave a similar warning in the reactive forms guide?

I don't think this information would be helpful in the reactive guide. The guide talks more about features in general and this use-case is quite specific and can be covered in the API documentation.

> Also, I can't seem to find a place to edit that specific doc. It sends me to a source file but not the markdown file with the content, and I can't find it in the repo.

You can find the docs for the valueChanges and statusChanges here:
https://github.com/angular/angular/blob/main/packages/forms/src/model/abstract_model.ts#L585-L600

**Comment by sr5434** [comment]
@AndrewKushnir is this better?

**Comment by JeanMeche** [comment]
Hi, you still need to squash your commits !

**Comment by sr5434** [comment]
Github codespaces won't let me squash them for some reason.

**Comment by sr5434** [comment]
I have to reopen

**Pull request closed without merging**
