### PR TITLE
fix(platform-browser): ensure that Hammer loader is called only once

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
- [x] Bugfix

## What is the current behavior?
Issue Number: #25995

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by arturovt** [comment]
@AndrewKushnir this is a replacement of this PR (https://github.com/angular/angular/pull/39976).

**Review by jelbourn — APPROVED** [review]
LGTM, this was pretty silly thing for me to miss when I wrote the loader

**Review by AndrewKushnir — APPROVED** [review]
@arturovt thanks for re-creating a PR 👍 The changes looks good to me too.

> BTW, I see that the HammerGesturesPlugin constructor is not marked with @internal,
> so removing Console injectee from it might be a breaking change, right?

I don't see `HammerGesturesPlugin` as a symbol that is included into public API, so the mentioned change should not be breaking. If you create a new PR for that change once this PR lands, we can look at it and run tests to see if anything is affected.

Thank you.

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:358303928:BASE:358303957:1613698978735:44752f6).

**Review by atscott — APPROVED** [review]

**Pull request closed without merging**
