### PR TITLE
docs: fix spelling of case variants in naming.md

### PR DESCRIPTION
**Pull request by Mobiletainment**
unify variant forms of spelling letter cases (upper-case, uppercase, lower case)

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: minor docs update
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by wardbell — APPROVED** [review]
LGTM

**Review by IgorMinar — APPROVED** [review]

**Comment by matsko** [comment]
@Mobiletainment please rebase.

**Comment by matsko** [comment]
@Mobiletainment this needs to be rebased and the conflict resolved so that it can go in. Can you please take care of that?

**Comment by Mobiletainment** [comment]
Thanks for the reminder @matsko. Up to date again.

**Comment by matsko** [comment]
Thank you @Mobiletainment

**Pull request merged**
