### PR TITLE
docs:  remove extra parenthesis from inline animations snippet

### PR DESCRIPTION
**Pull request by pascalfiv**
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

style needs only one closing bracket otherwise we are closing sequence too..

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Hi @Synoon! Thanks for catching this. You have a good eye! Could amend your commit message so that it reads:

```
docs:  remove extra parenthesis from inline animations snippet
```

You don't need the `(animations)` scope.

And don't forget to sign the cla. Once you've done those two things, could you tag me so I can help move this PR forward? Thanks!

**Review by matsko — APPROVED** [review]

**Comment by Synoon** [comment]
@googlebot I signed it!

**Comment by Synoon** [comment]
Hi @kapunahelewong do I need to change the commit message itself or just the pull-request title?

**Comment by kapunahelewong** [comment]
Hi @Synoon, I mean the commit message itself. Are you comfortable doing that? You might like to rebase, too, while you're in there. [Here are my notes](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) on amending a commit message in case you'd like the reference. There are also steps in that same gist on rebasing and squashing, too (just scroll up a little and you'll see them). Will you tag me when you're ready?

**Comment by Synoon** [comment]
Hi @kapunahelewong I forced pushed my new commit.

Maybe you could add to your notes that you have to make sure the right branch is checked out - didn't recognize that i was still on the master i was wondering why i don't see my commit from the feature-branch that was created by github (did make the pull request in github itself) and had to checkout everything locally so i was able to change the commit message... however i failed and had to force push my changes so we got a clean commit history..

but we got it finally... i hope everything is alright.. That was my very first contribution to something on github so... Pls have a look at it if everything is alright :)

**Review by kapunahelewong — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Thanks for the feedback on the notes, I've added your suggestion. 😊

And this PR looks great! Congrats on your first one! 🚀

**Comment by kapunahelewong** [comment]
Caretaker, please let me know if there's anything I can do to help get this green.

**Pull request closed without merging**
