### PR TITLE
refactor(compiler-cli): remove unused integration tests.

### PR DESCRIPTION
**Pull request by JeanMeche**
Theses tests have been disabled when the ViewEngine code has been remove in v13.1 (in [this commit](https://github.com/angular/angular/commit/bb9ff6003c620b3cf00232189d60097395382802))

I believe that if they haven't run since in the last 18 months, it's that they're not needed anymore. 

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

### CODE REVIEW

**Review by JoostK — APPROVED** [review]
LGTM, although I'm also asking @devversion to have a look.

**Review by devversion — APPROVED** [review]
Thank you!!

**Comment by jessicajaniuk** [comment]
@JeanMeche This has conflicts with `15.2.x`. I've updated to `target: rc`. Feel free to create a patch pr targeting `15.2.x` if you'd like this to land in the patch branch.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 3ba5dcc150676da01cbe6dc66ba6d4b3a3667bf1.

**Comment by JoostK** [comment]
@JeanMeche I wasn't expecting this one to conflict and we generally try to keep branches in sync, hence I opted for the `patch` target, but since this is already conflicting I wouldn't bother cherry-picking this to patch.

**Comment by JeanMeche** [comment]
Yeah, I wasn't gonna do it since there were no feature in the PR 😊

**Pull request closed without merging**
