### PR TITLE
docs: fix repeated note in "Add an Input to the component" section

### PR DESCRIPTION
**Pull request by MoIbrahim10**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x]  The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ]  Tests for the changes have been added (for bug fixes / features)
- [x]  Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ]  Bugfix
- [ ]  Feature
- [ ]  Code style update (formatting, local variables)
- [ ]  Refactoring (no functional changes, no api changes)
- [ ]  Build related changes
- [ ]  CI related changes
- [x]  Documentation content changes
- [ ]  [angular.io](http://angular.io/) application / infrastructure changes
- [ ]  Other... Please describe:

## Does this PR introduce a breaking change?

- [ ]  Yes
- [x]  No

## Other information

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]

**Comment by JeanMeche** [comment]
Hi, thank you for the change. Could you please reword the commit and drop the `routing` scope. We're fine here without any scope. Thank you.

**Comment by MoIbrahim10** [comment]
> Hi, thank you for the change. Could you please reword the commit and drop the `routing` scope. We're fine here without any scope. Thank you.

Done 👍

**Review by sonukapoor — APPROVED** [review]
@MoIbrahim10 It's in the commit message. Can you amend that?

**Comment by JeanMeche** [comment]
Thank you for this !

**Review by crisbeto — APPROVED** [review]

**Comment by atscott** [comment]
This PR was merged into the repository by commit f947dd5ba415fe361b0e303a223b6cb0cb0fab27.

**Pull request closed without merging**
