### PR TITLE
feat(common): add `provideLocationMocks()` function to provide Location mocks

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit adds the `provideLocationMocks()` function that returns mocks for the `Location` and `LocationStrategy` classes. This function can be used in tests to configure an environment where it's possible to fire simulated location events (helpful when testing Router configuration).

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by atscott — COMMENTED** [review]
We can remove this now as well: https://github.com/angular/angular/blob/main/packages/router/testing/src/provide_router_for_testing.ts

And then all references to that will have to do `provideRouter(...), provideLocationMocks()`

**Comment by AndrewKushnir** [comment]
@atscott thanks for the feedback, I've updated the PR to remove the `provideRouterForTesting` and use the new function instead.

@alxhub could you please review this PR when you get a chance (the PR is needed before v15 feature freeze).

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Comment by AndrewKushnir** [comment]
Merge-assistance (cc @jessicajaniuk): this PR is ready for merge, but needs one more `public-api` approval. Could you please take a look when you get a chance? Thank you.

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit c0c7efaf7c8a53c1a6f137aac960757cc804f263.

**Pull request closed without merging**
