### PR TITLE
Docs. It's an unclosed <code-example> tag here. Fix

### LINKED ISSUE #21769: Html styles on Angular.io
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

https://angular.io/guide/ajs-quick-reference#style-sheets
Styles are not good decorated

## Expected behavior

Something like [this](https://user-images.githubusercontent.com/4002847/35380385-4b5443e4-01e3-11e8-9172-0d4b1ca04dd0.png) ?

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by Yerkon**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Updating doc .md file 

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #21769 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Fixes #21769.

### CODE REVIEW

**Comment by Yerkon** [comment]
When run test locally: 
./test.sh node
Output is: 
```
Creating packages .metadata.json files...
core/src/animation/animation_metadata_wrapped.ts(8,221): error TS2307: Cannot find module './dsl'.
upgrade/static/public_api.ts(15,84): error TS2307: Cannot find module './src/common/angular1'.
upgrade/static/public_api.ts(16,34): error TS2307: Cannot find module './src/common/downgrade_component'.
upgrade/static/public_api.ts(17,35): error TS2307: Cannot find module './src/common/downgrade_injectable'.
upgrade/static/public_api.ts(18,23): error TS2307: Cannot find module './src/common/version'.
upgrade/static/public_api.ts(19,31): error TS2307: Cannot find module './src/static/downgrade_module'.
upgrade/static/public_api.ts(20,32): error TS2307: Cannot find module './src/static/upgrade_component'.
upgrade/static/public_api.ts(21,29): error TS2307: Cannot find module './src/static/upgrade_module'.
```


Windows 10.
Node: 8.9.4
yarn: 1.3.2
jdk-8u161-windows-x64
git version 2.10.2.windows.1

**Review by gkalpak — APPROVED** [review]
Good catch 👍
(The Travis failures are not related to this PR.)

Can you please update the commit message to follow our [guidelines][1]?

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

**Comment by Yerkon** [comment]
> Can you please update the commit message to follow our guidelines?

@gkalpak,  Of course. Updated. Is it ok?

**Comment by gkalpak** [comment]
@Yerkon, the new commit message still doesn't follow the guidelines. Can you lease change it to something like:

> docs(aio): add missing closing \`<code-example>\` tag

**Comment by gkalpak** [comment]
Thx for the changes, @Yerkon. Can you also rebase on master to fix the Travis failures?

**Comment by Yerkon** [comment]
> Thx for the changes, @Yerkon. Can you also rebase on master to fix the Travis failures?

Done @gkalpak

**Pull request closed without merging**
