### PR TITLE
fix(docs-infra): fix image name in example

### LINKED ISSUE #35618: images not rendering in Property Binding example
# 📚 Docs or angular.io bug report

### Description

In Template Syntax, the Property Binding example images (in the StackBlitz example) aren't rendering.

### What's the affected URL?**
https://stackblitz.com/angular/envrboojygp?file=src%2Fapp%2Fapp.component.ts

### Reproduction Steps**

Only have to visit the link to see them not render.

## 📷Screenshot

image

## 🔥 Exception or Error
<pre><code>

</code></pre>

### PR DESCRIPTION
**Pull request by sonukapoor**
Closes #35618

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #35618

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Good catch! ✨

**Review by gkalpak — CHANGES_REQUESTED** [review]
Oh, you also need to update [this e2e test][1]

[1]: https://github.com/angular/angular/blob/13f7631c25aac562c85bb1125f1ff18af141e992/aio/content/examples/interpolation/e2e/src/app.e2e-spec.ts#L33

**Comment by sonukapoor** [comment]
> Oh, you also need to update [this e2e test](https://github.com/angular/angular/blob/13f7631c25aac562c85bb1125f1ff18af141e992/aio/content/examples/interpolation/e2e/src/app.e2e-spec.ts#L33)

Done. All tests are passing now.

**Review by bt-serdarbuyuktemiz — APPROVED** [review]

**Review by gkalpak — APPROVED** [review]
Awesome, thx!

**Pull request closed without merging**
