### PR TITLE
fix(dev-infra): add vim .swp files to gitignore

### PR DESCRIPTION
**Pull request by zarend**
The vim editor produces temporarily files that can end in both .swo and
.swp. This commits add .swp to the .gitignore so we don't accidentally
commit temporary files.

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by atscott — APPROVED** [review]
LGTM but defer to @josephperrott in case there's something I'm missing here. It's a little surprising that we don't already have this.

**Comment by ayazhafiz** [comment]
fun fact: the variety of potential extensions can be endless, if `swp` is already taken for a file then `swo` is tried, then `swn`, etc. http://vimdoc.sourceforge.net/htmldoc/recover.html#swap-file

**Comment by crisbeto** [comment]
FYI one .swp file already made it into the repo. Maybe we should take the chance to delete it? https://github.com/angular/angular/blob/master/packages/language-service/.build.sh.swp

**Pull request closed without merging**
