### PR TITLE
fix(core): improve docs on afterRender hooks

### PR DESCRIPTION
**Pull request by cexbrayat**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?
This commit improves the documentation of the options parameter of the afterRender hooks.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
This is a rebased version of https://github.com/angular/angular/pull/56522 on the v18 branch as asked by @AndrewKushnir

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@cexbrayat thanks for creating a PR for the 18.0.x branch.

**Comment by AndrewKushnir** [comment]
@cexbrayat do you mind rebasing it on top of the most recent 18.0.x branch? There were some additional commits there that fixed CI issues.

**Comment by cexbrayat** [comment]
@AndrewKushnir Sure, done!

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 2f73281dfd97fd254179770cbdbda5236f5f37fd.

The changes were merged into the following branches: 18.0.x

**Pull request closed without merging**
