### PR TITLE
fix(compiler): properly compile DI factories when coverage reporting is enabled

### LINKED ISSUE #31337: Dependency injection and class inheritance doesn't work in Angular 8 library test
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core@^8

### Is this a regression?
Yes, the previous version in which this bug was not present was: @angular/core@7

### Description

The problem occurs when:

1. The base class has a constructor with an injected service. (`Injector` from the example)

```ts
@Injectable()
export class BaseService {
  // "Injector" is just for the sake of example. Any injectable would have the same problem.
  constructor(public injector: Injector) {
  }
}
```
2. Child class has no constructor (i.e., it relies on base class constructor) AND at least one property with the default value.

```ts
@Injectable()
export class MyLibService extends BaseService {

  public foo = 'bar';

}
```

3. (_dont ask me how I have found this, but:_) In `angular.json` `[lib name].test.options.codeCoverage` should be true. 

### PROBLEM:   

`injector` is undefined in the instance of `MyLibService`. 

--- 

🚩 Removing property from the child class _(2)_ AND/OR opting out `codeCoverage` config in angular.json _(3)_ doesn't brake test.

As a result, I can't have a class inheritance and code coverage at the same time.

---

I could put a constructor in the child class and call `super` by passing all required arguments manually, but it's the last option since the real-life scenario is much more complicated than the example provided here.

## 🔬 Minimal Reproduction
git repo: https://github.com/ddramone/ng-8-library-inheritance-di-test-bug

reproduce steps:

1. Install angular 8 cli
2. Clone `git clone https://github.com/ddramone/ng-8-library-inheritance-di-test-bug.git `
3. `npm i`
4. run Test `ng test my-lib`

 ### Expected behavior

Test should pass = Injector service should be available in the service instance.

### PR DESCRIPTION
**Pull request by JoostK**
When running tests with code coverage using Istanbul, the code is
instrumented with coverage reporting statements. These statements are
also inserted into synthesized constructors, preventing Angular from
properly recognizing them as synthesized constructor.

This commit changes the regex to detect synthesized constructors to allow
for statements within the constructor before the `super(...arguments);`
call. This is limited to code that does not contain a `}`, but this
is sufficient to support Istanbul's coverage instrumentation statements.

The tests have been extended with an input file that is being
instrumented using `babel-plugin-istanbul` for both ES2015 and ES5
targets, in order to verify that the approach works for real-world
usages.

Fixes #31337

### CODE REVIEW

**Comment by JoostK** [comment]
@devversion I've added you as reviewer as I'm interested in your thoughts here. I started with a full integration setup where we actually use Istanbul's Babel's transform, mainly because that was a bit more relevant to have in the original #37811. But this PR opts for a much simpler approach that avoids the problem so I figured a simple unit test is sufficient (so the original integration test setup was reverted in the fixup commit in this PR)

**Comment by JoostK** [comment]
Oh and adding @gkalpak  so he can suggest ten ways to improve the regex 😁

**Review by devversion — APPROVED** [review]
@JoostK that looks great to me!

I also would have been happy with the actual istanbul transformation, but yeah, that looks like a lot of more code to maintain. I'd assume that the naming of these injected expressions etc. does not really matter in the future, neither would it seem likely that at some point the injected code before e.g. `super` will be dropped by istanbul.

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Review by AndrewKushnir — APPROVED** [review]
👍

**Comment by JoostK** [comment]
Presubmit isn't strictly necessary since this touches JIT-only code.

**Comment by AndrewKushnir** [comment]
Starting a new [presubmit](http://test/OCL:423370974:BASE:423370992:1642794068885:cf0671b) just to be safe :)

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 627e807eb8d872e8e2de5067659a3a78eb706ee8.

**Pull request closed without merging**
