### PR TITLE
build: remove source-map-test gulp script

### PR DESCRIPTION
**Pull request by josephperrott**
`source-map-test` is no longer used or referenced in our repository,
additionally it fails to discover source maps as expected anymore
when executed.

### CODE REVIEW

**Review by IgorMinar — COMMENTED** [review]
Hmmm... That's unfortunate. We still need this test and it's not great that we somehow stopped running them. @kara, maybe someone from the FW team could take on fixing the code and moving it to run under Bazel? Sgty?

**Comment by josephperrott** [comment]
@Kara, any thoughts on how we should proceed on this one?

**Comment by devversion** [comment]
A long time ago I created an issue on this and also looked into this. See: https://github.com/angular/angular/issues/27966#issuecomment-452432578

**Comment by IgorMinar** [comment]
Aha!!! @devversion could you please create a JIRA out of #27966 and see if we can get it into the next sprint?

It's concerning that we don't test the source map correctness any more - this could explain some of the issues I've seen in profiles shared with us by our customers.

btw can we please convert this gulp test to a bazel target in the process of fixing it? thanks!

**Review by IgorMinar — CHANGES_REQUESTED** [review]
let's not remove this just yet and instead convert it to a bazel test either in this PR or a separate PR as discussed with @devversion above.

**Comment by IgorMinar** [comment]
hey Joey, I asked @devversion to resurrect this test in https://github.com/angular/angular/pull/37623#issuecomment-646327933. Once this is done, this PR will become obsolete.

**Comment by devversion** [comment]
@IgorMinar Sounds good to me. I've also created a JIRA ticket: DEV-122 for tracking. I imagine that this test should be generic enough so that it can be used in the components repo too.

**Comment by AndrewKushnir** [comment]
FYI, I'm removing the "merge" label for now, since there are conflicts and it looks like there is a feedback that needs to be addressed.

**Pull request closed without merging**
