### PR TITLE
docs: change order of Angular Elements article

### LINKED ISSUE #30268: Angular Guide: 'Dynamic Components' section should come before 'Angular Elements'
In the 'Angular Elements' Popup Service example, the section starts with below:
"Previously, when you wanted to add a component to an app at runtime, you had to define a dynamic component.."

Link ref. : https://angular.io/guide/elements#example-a-popup-service

i.e. The section is referencing & building on the context of 'the Dynamic Components section' which actually gets discussed after the 'Angular Elements' section. 

Hence, I suggest to switch the sequence of these topics in order to maintain the consistency and flow of documentation.

### PR DESCRIPTION
**Pull request by artem-galas**
PR Close #30268

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #30268

## What is the new behavior?
Angular Elements article comes after Dynamic Component article

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Thanks for this @artem-galas! Could you rebase on master?

**Review by StephenFluin — APPROVED** [review]
This is fine.  I believe the intent of the paragraph is to say "in the past, the only way to do this was X", but this change fixes the lack of clarity, so thanks for contributing!

**Comment by kapunahelewong** [comment]
Hey @artem-galas when you've rebased and all the tests pass, could you tag me so I can mark this for merge?

**Comment by artem-galas** [comment]
@kapunahelewong  I've rebased already. And tests, seems, also passed.

**Comment by kapunahelewong** [comment]
great! As soon as the codefresh one passes I'll mark for merge. Thank you  😊

**Pull request closed without merging**
