### PR TITLE
[18.0.x] build: update cross-repo angular dependencies and lock file maintenance of integration tests

### PR DESCRIPTION
**Pull request by devversion**
This commit also performs lock file maintenance on all integration tests, fixing some ambigous ESM/CJS dependency graph issues.

e.g.

```
Unknown error: Error [ERR_REQUIRE_ESM]: require() of ES Module /tmp/ng-integration-test-aTpQOT/test-sandbox/node_modules/string-width/index.js from /tmp/ng-integration-test-aTpQOT/test-sandbox/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /tmp/ng-integration-test-aTpQOT/test-sandbox/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
------------------------------------------
```

Closes #56261.

### CODE REVIEW

**Comment by devversion** [comment]
This is the patch-port of https://github.com/angular/angular/pull/56364.

**Review by crisbeto — DISMISSED** [review]

**Review by AndrewKushnir — DISMISSED** [review]

**Comment by AndrewKushnir** [comment]
FYI, adding the "cleanup" label, since this PR has merge conflicts with the target branch.

**Comment by AndrewKushnir** [comment]
@devversion there is a merge conflict with the target branch, could you please rebase and resolve the conflicts when you get a chance? Thank you.

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 80618b046950e3bb520fd1ad261ef43afd47f472.

The changes were merged into the following branches: 18.0.x

**Pull request closed without merging**
