### PR TITLE
7.2.x

### PR DESCRIPTION
**Pull request by szb512**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes/features)
- [ x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Add support to make it run better.
Issue Number: N/A

## What is the new behavior?
Added support makes it function better.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

### CODE REVIEW

**Comment by szb512** [comment]
I guess....

**Comment by szb512** [comment]
It should fix the update cache error.

**Comment by gkalpak** [comment]
I assume this was opened by accident.

**Comment by szb512** [comment]
This was NOT opened by accident.

**Comment by petebacondarwin** [comment]
@szb512 it is not clear what this PR is for. Please create a new one with a clear title and description of what it does. And also only include the relevant commits that you have authored.

**Pull request closed without merging**
