### PR TITLE
docs: make tutorial instructions consistent

### PR DESCRIPTION
**Pull request by jayoma**
When starting this tutorial, it's not clear to the user whether they should add routing right away, Etc. The other tutorials within the routing section do a better job of this.

Also.. the suggested name of this sample app clashes with that of a previous tutorial, forcing the user to either delete the previous tutorial files, choose a different name for this tutorial's app, or place this app in a different parent directory.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The tutorial at [https://angular.io/guide/router-tutorial-toh](https://angular.io/guide/router-tutorial-toh) doesn't clearly instruct the user how to create a new sample app using the CLI, and re-uses the name of an app that a previous tutorial already used, causing directory/file name collisions.

Issue Number: N/A

## What is the new behavior?
The proposed changes make the app-creation portion of the tutorial consistent with the other tutorials within the Routing and Navigation section of the docs, and suggests an app name that doesn't clash with the previously-created sample app.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@jayoma Thanks for the contribution! Can you rebase and resolve the file conflicts? If we can get CI green, we should be able to land this.

**Review by AndrewKushnir — APPROVED** [review]
@jayoma thanks for improving Angular docs!

**Comment by jayoma** [comment]
> @jayoma Thanks for the contribution! Can you rebase and resolve the file conflicts? If we can get CI green, we should be able to land this.

Thank you @jessicajaniuk. I've rebased and conflicts have been resolved.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 3c1695e3991f284c135aa0f03d3664be2da4303c.

**Pull request closed without merging**
