### PR TITLE
docs: improve doc accessibility

### PR DESCRIPTION
**Pull request by edbzn**
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

No static analysis on accessibility issues.

Issue Number: N/A

## What is the new behavior?

 This PR introduce codelyzer accessibility rules to detect inaccessible elements and fix all the problems reported.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by Edouardbozon** [comment]
@googlebot I signed it!

**Comment by petebacondarwin** [comment]
Thanks for this PR @Edouardbozon - I think the CI failures will be fixed by rebasing this on the current master.

My initial reaction to the second commit is that simply reacting to "any" keypress looks too generic. What happens if you are tabbing focus through the different elements on the page. Doesn't that count as a keypress?

**Comment by Edouardbozon** [comment]
@petebacondarwin You're right event handler hears every keystroke. I can put event filtering like `(keyup.enter)="..."`. What do you think ?

**Comment by petebacondarwin** [comment]
That sounds more reasonable. What is the bottom-line a11y requirement for this?

**Comment by Edouardbozon** [comment]
Accessibility rules aren't compatible with pseudo events. I made [an issue in codelyzer](https://github.com/mgechev/codelyzer/issues/888), I will be back soon here when a fix is pushed.

**Comment by Edouardbozon** [comment]
@petebacondarwin I updated the PR.

**Review by petebacondarwin — APPROVED** [review]
Thanks for getting the codelizer rules fixed. @Edouardbozon 
Can you squash all the commits into one and also add a brief explanation of why the codelyzer version needs to be bumped.

**Comment by Edouardbozon** [comment]
@petebacondarwin Done, added a small explanation to the commit directly. Thanks for the review.

**Comment by petebacondarwin** [comment]
@Edouardbozon - is this rebased on master? I am not sure why the last test is failing.

**Pull request closed without merging**
