### PR TITLE
refactor(compiler): Delete the `@angular/compiler/testing` module.

### PR DESCRIPTION
**Pull request by JeanMeche**
The package was [removed in components](https://github.com/angular/components/pull/26940), it can now be deleted here also.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Actually I'm curious if it has some usage in G3.

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: bazel, dev-infra

**Review by jessicajaniuk — APPROVED** [review]

**Comment by atscott** [comment]
@JeanMeche can you resolve conflicts? There are no uses of this internally

**Comment by JeanMeche** [comment]
@atscott ✅

**Comment by atscott** [comment]
caretaker note: The BUILD file for this package needs to be manually deleted when merging internally.

**Comment by atscott** [comment]
This PR was merged into the repository by commit c2f270cf147e6434957e3b259ddc54a54a2a590e.

**Pull request closed without merging**
