### PR TITLE
fix(ivy): avoid infinite recursion when evaluation source files

### LINKED ISSUE #33734: [Ivy -@9.0.0-rc.1 & -@9.0.0-rc.2] `ngcc` fails to compilate NativeScript-Angular package with error: "Error: Error on worker #3: RangeError: Maximum call stack size exceeded"
# 🐞 bug report

### Affected Package
`@nativescript/angular` . This is the main package that contains the implementation that allows Angular to run in NativeScript.

### Is this a regression?

No, because Ivy is a feature that we want to allow the users of NativeScript to benefit from.

### Description

Currently we want to build the `@nativescript/angular` package with `ngc` (in order to support View engine) and want to make sure that the package is also correctly processed by `ngcc` (in order to support Ivy)

## 🔬 Minimal Reproduction

As this is yet not merged and release because 9.0.0 is still not available officially. You cna observe the issue in a branch of `@nativescript/angular`. Here is a show setup:

- Clone `git clone https://github.com/NativeScript/nativescript-angular.git`
- `cd nativescript-angular`
- `git checkout amiorkov/ivy`
- From the root of the repo execute `cd nativescript-angular && npm i && npm run pack` (this will build the `@nativescript/angular` package, make it into a .tgz and place it in a `dist` directory of the repo)
- From the root of the repo execute `cd nativescript-angular-package && npm i && npm run pack-with-scoped-version /Users/amiorkov/Desktop/Work/nativescript-angular/dist/nativescript-angular-scoped.tgz` (this will create the `nativescript-angular` package that uses the previously build `@nativescript/angular` package as a dependency. Replace the path to the `nativescript-angular-scoped.tgz` that is after the `npm run pack-with-scoped-version <path-to-scoped-tgz>` script)

After this you can proceed with running ngcc in the Test app (e2e/ivy-sample) (`cd e2e/ivy-sample/  && npm i && ./node_modules/.bin/ngcc`)

### Test app
- From root of repo `cd e2e/ivy-sample && npm i && ./node_modules/.bin/ngcc && tns run ios` - We would like to use a symlink in this app for the `nativescript-angular` package. Can we make `ngcc` work with symlinked packages (the code that ngcc needs to compile is nested in an innter `node_modules`)

## 🔥 Exception or Error
<pre><code>

mcsofamiorkov:ivy-sample amiorkov$ ./node_modules/.bin/ngcc
Warning: Entry point '@nativescript/angular' contains deep imports into '/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/tns-core-modules/ui/layouts/layout-base'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Compiling @nativescript/angular : main as commonjs
Error: Error on worker #3: RangeError: Maximum call stack size exceeded
    at visitNode (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/typescript/lib/typescript.js:17006:23)
    at Object.forEachChild (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/typescript/lib/typescript.js:17139:24)
    at NodeObject.forEachChild (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/typescript/lib/typescript.js:124873:23)
    at CommonJsReflectionHost.Esm2015ReflectionHost.findDecoratedVariableValue (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js:605:25)
    at /Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js:605:69
    at visitNodes (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/typescript/lib/typescript.js:17016:30)
    at Object.forEachChild (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/typescript/lib/typescript.js:17140:21)
    at NodeObject.forEachChild (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/typescript/lib/typescript.js:124873:23)
    at CommonJsReflectionHost.Esm2015ReflectionHost.findDecoratedVariableValue (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js:605:25)
    at /Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js:605:69
    at ClusterMaster.onWorkerMessage (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:158:27)
    at /Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:46:95
    at ClusterMaster.<anonymous> (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:238:57)
    at step (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/tslib/tslib.js:117:57)
    at /Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/tslib/tslib.js:106:16)
    at EventEmitter.<anonymous> (/Users/amiorkov/Desktop/Work/nativescript-angular/e2e/ivy-sample/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:232:32)
    at EventEmitter.emit (events.js:189:13)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.1
Node: 10.15.2
OS: darwin x64
Angular: 9.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0-rc.1 (cli-only)
@angular-devkit/core         9.0.0-rc.1
@angular-devkit/schematics   9.0.0-rc.1 (cli-only)
@ngtools/webpack             9.0.0-rc.1
@schematics/angular          9.0.0-rc.1 (cli-only)
@schematics/update           0.900.0-rc.1 (cli-only)
rxjs                         6.5.3
typescript                   3.6.4
webpack                      4.27.1

</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by JoostK**
When ngtsc comes across a source file during partial evaluation, it
would determine all exported symbols from that module and evaluate their
values greedily. This greedy evaluation strategy introduces unnecessary
work and can fall into infinite recursion when the evaluation result of
an exported expression would circularly depend on the source file. This
would primarily occur in CommonJS code, where the `exports` variable can
be used to refer to an exported variable. This variable would be
resolved to the source file itself, thereby greedily evaluating all
exported symbols and thus ending up evaluating the `exports` variable
again. This variable would be resolved to the source file itself,
thereby greedily evaluating all exported symbols and thus ending u
evaluating the `exports` variable again. This variable would be
resolved to the source file itself, thereby greedily evaluating all
exported symbols and thus ending up evaluating the `exports` variable
again. This variable would be resolved to the source file itself,
thereby greedily evaluating all exported symbols and thus ending up
evaluating the `exports` variable again. This went on for some time
until all stack frames were exhausted.

This commit introduces a `ResolvedModule` that delays the evaluation of
its exports until they are actually requested. This avoids the circular
dependency when evaluating `exports`, thereby fixing the issue.

Fix #33734

### CODE REVIEW

**Comment by VladimirAmiorkov** [comment]
What is the simplest way if building an Angular with this PR? I want to test if https://github.com/angular/angular/issues/33734 is resolved by it.

**Comment by JoostK** [comment]
@VladimirAmiorkov You can find instructions here on using artifacts from CircleCI for this PR:

https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#getting-packages-from-build-artifacts

**Comment by VladimirAmiorkov** [comment]
@JoostK 

Thanks for this info. Looking at the builds and the note that the artefacts may not be averrable I feel like they already are not. I checked here https://circleci.com/gh/angular/angular/524826#artifacts but cant seem to find any artefacts, that build was 6 days ago so maybe I am late to get them :) .

**Comment by gkalpak** [comment]
You can find the latest artifacts from this PR here: https://circleci.com/gh/angular/angular/524805#artifacts

**Comment by gkalpak** [comment]
(FWIW, I tried this with #33734 and I got a different error, so I guess the "Maximum call stack size exceeded" error is fixed :tada:)

**Review by alxhub — APPROVED** [review]

**Comment by alxhub** [comment]
[Presubmit](http://test/OCL:281338867:BASE:281338902:1574191655314:d55b6d2e)
[Ivy Presubmit](http://test/OCL:281338867:BASE:281339068:1574191689595:701cd9f4)

**Comment by JoostK** [comment]
merge-assistance: size failure is unrelated.

**Pull request closed without merging**
