### PR TITLE
fix(compiler): Don't strip `/*# ... */` comment when css scoping

### PR DESCRIPTION
**Pull request by asnowwolf**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Currently, the source-mapping comments of component style is stripped by extractStyleUrls, so, css mappings don't work properly for component styles.

**What is the new behavior?**

Don't strip hash comments, so that they will be past to `style` tags properly.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by vicb** [comment]
@asnowwolf what is the difference with #16088 ? could one of them be closed ?

**Comment by asnowwolf** [comment]
@vicb this is #16088 + #16090，so, I think we'd better close this one and merge that two. 

Infact, this PR resolves two issues, split to two separated PRs is more reasonable.

**Comment by asnowwolf** [comment]
O, this one is not exactly same as #16088. In fact, #16088 + #16090 = #14175

**Comment by asnowwolf** [comment]
The #16090 's related issue is:
The component style's scss has no source maps. It's hard to locate the source code. long time ago, I submitted a PR to fix that, but later, another commit broken that PR, this PR this fix that commit.

The #16088 's related issue is:
Even after fixed the #16090, It's not work properly in Chrome(but Firefox is ok), the root cause is that for the embedded `<style>` content with sourceMappingURL, Chrome requires an additional sourceURL comment. Maybe it's an issue of Chrome, but we can also resolve it with a little effort.

**Comment by asnowwolf** [comment]
@vicb What else do i need to do? If possible, I hope to merge it as soon as possible because I have to patch the Angular library mannually for each new project. I think maybe there are other people also suffer from these issues.

**Comment by OzzieOrca** [comment]
Could we get this merged? I'm not sure what it is waiting on. It is really nice to have sourcemaps again. (I patched this file locally to test it.)

**Comment by daddyschmack** [comment]
Hey Guys, Will this be merged in soon?

**Comment by asnowwolf** [comment]
Sorry, when i merge the latest branch, a misuse destroys this PR.

#18641  is the re-pushed version that has merged the latest master.

**Pull request closed without merging**
