### PR TITLE
docs(aio): Fixed typo at AOT compiler documentation

### PR DESCRIPTION
**Pull request by camilogiraldo**
fixed 'infomration' at AOT compiler documentation

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```

[x] Documentation content changes

```
fix(typo): 'infomration' typo at AOT Compiler documentation

docs(aio): fix typo on AOT compiler section

## What is the current behavior?
Typo 'infomration' on AOT Compiler documentation.

Issue Number: N/A

## What is the new behavior?

Typo fixed for 'information'

## Does this PR introduce a breaking change?
```
[x ] No
```

### CODE REVIEW

**Comment by camilogiraldo** [comment]
@googlebot  I signed it!

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Thx for catching this 👍
Can you please rebase on master and also fix the commit message to follow [our guidelines][1]?

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by camilogiraldo** [comment]
Not sure if its right, can you double check 👍  gonna be my first contribution 😆

**Comment by rafaelss95** [comment]
I just searched for the "infomration" word and I found two more occurrences. Could you correct them also?

https://github.com/angular/angular/blob/24bf3e2a251634811096b939e61d63297934579e/packages/language-service/src/types.ts#L42

https://github.com/angular/angular/blob/24bf3e2a251634811096b939e61d63297934579e/packages/language-service/src/types.ts#L327

**Comment by camilogiraldo** [comment]
@rafaelss95  Sure, will do ! :sunglasses:

**Comment by vicb** [comment]
@camilogiraldo could you please rebase (sorry for the delay). Thanks

**Comment by camilogiraldo** [comment]
@vicb Done, can you double check please? :+1:

**Review by IgorMinar — APPROVED** [review]

**Pull request merged**
