### PR TITLE
docs: fixed animations reference links to api

### PR DESCRIPTION
**Pull request by jrumandal**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The automated links for state() and group() are currently going to the 
wrong api pages. Edit directs them to the correct animations api pages.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Hi @jrumandal! Thanks for this. This is a really good catch. It took me a minute to even see what you'd caught.

For anyone else like me, currently, the automated links for `state()` and `group()` go to https://angular.io/api/common/upgrade/$locationShim#state and https://angular.io/api/forms/FormBuilder#group but instead should go to the relevant animations api pages.

@gkalpak and/or @petebacondarwin is this the way we want to handle this situation?

**Review by petebacondarwin — APPROVED** [review]

**Review by kapunahelewong — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Oh hey, @jrumandal could you amend the commit message to get rid of the prose inside? Or you could change it to:

```
The automated links for state() and group() are currently going to the 
wrong api pages. Edit directs them to the correct animations api pages.
```

You can do this with a `git commit --amend`.

Here's the part I mean to change:
image

When you're ready, please tag me and if it's all passing I can mark it for merge. Thanks!

**Comment by jrumandal** [comment]
> Oh hey, @jrumandal could you amend the commit message to get rid of the prose inside? Or you could change it to:
> 
> ```
> The automated links for state() and group() are currently going to the 
> wrong api pages. Edit directs them to the correct animations api pages.
> ```
> 
> You can do this with a `git commit --amend`.
> 
> Here's the part I mean to change:
> image
> 
> When you're ready, please tag me and if it's all passing I can mark it for merge. Thanks!

Grant! @kapunahelewong 
Happy to provide valuable contribution :)

**Comment by kapunahelewong** [comment]
Thank you, @jrumandal. Almost there! Try to format it like this to get the explanation inside the body:

image

That will make it clean here:

image

To make it easier, you can copy and paste the following text if you like. There should be a blank line before and after the body:

```
docs: fix animations reference links to api pages

The automated links for state() and group() are currently going to the
wrong api pages. Edit directs them to the correct animations api pages.

```

Thanks for your diligence, this is such a great fix!

**Comment by jrumandal** [comment]
> Thank you, @jrumandal. Almost there! Try to format it like this to get the explanation inside the body:
> 
> image
> 
> That will make it clean here:
> 
> image
> 
> To make it easier, you can copy and paste the following text if you like. There should be a blank line before and after the body:
> 
> ```
> docs: fix animations reference links to api pages
> 
> The automated links for state() and group() are currently going to the
> wrong api pages. Edit directs them to the correct animations api pages.
> ```
> 
> Thanks for your diligence, this is such a great fix!

@kapunahelewong I see! I was concerned about linter that was accepting only 120chars in the ci/cd pipeline.
Updated as requested :)

**Review by kapunahelewong — APPROVED** [review]

**Pull request closed without merging**
