### PR TITLE
docs: correct the spelling mistake in observables' error handling code

### PR DESCRIPTION
**Pull request by jaskaransr93**
Spell mistake

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
**errror** was spelled wrong

Issue Number: N/A

## What is the new behavior?
Changed it to **error**

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jaskaransr93** [comment]
@googlebot I signed it!

**Comment by kapunahelewong** [comment]
Thank you for this, @jaskaransr93! There are just a couple of things we need to do so we can merge it. Could you [rebase](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) and [amend](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) the commit message so that it is as follows:

```
docs: correct the spelling mistake in observables error handling code

This commit fixes a spelling error in the word error in the observables.md guide. It is currently 
spelled errror  and the mistake is not intentional. 

```

Just make sure to have a blank line before and after the body (or explanation). Feel free to copy this commit message. If you'd like help with the rebase and amend just let me know.

**Comment by jaskaransr93** [comment]
Thank you @kapunahelewong for guiding me through the process. I have rebase and amend the commit message.

Please let me know if I have done it right way or not ?

**Review by kapunahelewong — APPROVED** [review]
Perfect, thank you, @jaskaransr93!!

LGTM!

Reviewed-for: global-docs-approvers

**Review by AndrewKushnir — APPROVED** [review]

**Pull request closed without merging**
