### PR TITLE
fix(http): status code; test(http): normalize responseText/response;

### LINKED ISSUE #2841: Http always return status 200
```
http
			.post("/api/cap/user/ping2")
			.toRx()
			//.map((response:Response) => response.json())
			.subscribe(
			(data:Object) => console.log(data),
			(data:Object) => console.error(data),
			(data:Object) => console.debug(data)
		);
```

In network tab on developer tools in browser status 404.
But in console always object with status 200.

### PR DESCRIPTION
**Pull request by PatrickJS**
fix(http): status code; test(http): normalize responseText/response;
- [x] Tests

closes #2841

### CODE REVIEW

**Comment by tbosch** [comment]
@gdi2290 What is the status of this PR?

**Comment by gdi2290** [comment]
@tbosch I rebased so it should be good when travis is done

**Comment by gdi2290** [comment]
@tbosch all green and ready to be merged

**Comment by jeffbcross** [comment]
@gdi2290 thanks, I'll give a final look.

**Pull request closed without merging**
