### PR TITLE
docs: add reference to ng add in tutorial and quick reference

### PR DESCRIPTION
**Pull request by jenniferfell**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Added reference to new CLI command ng add. Added links to CLI and Materials docs. Changes made in sections of Tutorial and Quick Start where a new project is created. 

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Adding new feature to doc. See above.

Issue Number: N/A

## What is the new behavior?
See above.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X ] No
```

### CODE REVIEW

**Comment by jenniferfell** [comment]
@StephenFluin Updated to include ng add. If tests pass and you approve, I'll mark for merge. Plan is to open new PR and update if appropriate in the future for more specific CLI and Materials URLs. Thanks!

**Review by StephenFluin — APPROVED** [review]
4 new empty lines inside of the DIV looks unnecessary, but Jennifer says this is our standard.

**Comment by jenniferfell** [comment]
Closing to fix CLA issue with new PR

**Comment by jenniferfell** [comment]
moved to https://github.com/angular/angular/pull/23130

**Pull request closed without merging**
