### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by chihab**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Comment by chihab** [comment]
I've signed the CLA, could you please rescan the PR?

**Review by gkalpak — APPROVED** [review]
Thx, @chihab :+1:

Reviewed-for: global-docs-approvers

**Review by dylhunn — APPROVED** [review]

**Review by dylhunn — COMMENTED** [review]
reviewed-for: public-api

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Comment by dylhunn** [comment]
merge-assistance: it's likely OK to skip all three public-api approvers for only a minor typo.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit c6c75c9b7018cfeb4d2bbc8945f3af1ca71943d3.

**Pull request closed without merging**
