### PR TITLE
Update `makeTemplateDiagnostics` and add a wrapper

### PR DESCRIPTION
**Pull request by danieltre23**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The function `makeTemplateDiagnostic` in 12.1.x doesn't accept relatedMessages as a parameter, it accepts a single related message.

## What is the new behavior?
The function `makeTemplateDiagnostic` now accepts an array of relatedMessages that aligns with master.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by atscott** [comment]
Given that we're doing the 12.2.0 release next week, maybe it's easier to leave `12.1.x` as it is and just allow `12.2.x` to diverge. It won't matter come next week anyways

**Review by atscott — APPROVED** [review]

**Review by dgp1130 — APPROVED** [review]
Minor typo in the first commit message (`makeTempalteDiagnostic`), but otherwise LGTM!

**Comment by alxhub** [comment]
I agree with @atscott - this isn't really necessary given that `12.2.x` has the original commit and will be the new patch branch going forward.

**Comment by dgp1130** [comment]
@alxhub, is this worth landing at all since already have everything implemented and working, or is it better to just drop this altogether?

**Comment by dgp1130** [comment]
After some discussion, we've decided to just drop this since the `12.2.0` release tomorrow will make `12.2.x` the new patch branch (which already contains this change) and `12.1.x` will be no longer be maintained anyways.

**Pull request closed without merging**
