### PR TITLE
refactor(router): Remove legacy url creation code

### PR DESCRIPTION
**Pull request by atscott**
This commit removes code for the old way of creating a `UrlTree`.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
👍

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: size-tracking

**Comment by jessicajaniuk** [comment]
Looks like the broken tests in G3 are related.

**Comment by atscott** [comment]
> Looks like the broken tests in G3 are related.

Yes, this is blocked by one team internally that is relying on the old code being patched as a private export. I'll be reaching out again to them today.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit ff9d3b0f02557b159d2a4f178020722d631efb1f.

**Pull request closed without merging**
