### PR TITLE
fix(docs-infra): Fixed top menu logo margin

### PR DESCRIPTION
**Pull request by furevor**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 26468
Here is [issue](https://github.com/angular/angular/issues/26468)

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by furevor** [comment]
I signed it!

**Comment by botanegg** [comment]
in mobile style logo unnecessary moved to 16px

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx for picking this up. The issue is caused by a style change in `@angular/material` that we missed when upgrading to latest version (see https://github.com/angular/angular/issues/26468#issuecomment-430207092).

Previously, the `min-width` for `.mat-button` was 88px and now it is 64px. So, the fix is to change `-88px` to `-64px` here:

https://github.com/angular/angular/blob/1c9b06504b45280a30df937b99bc26256732b55e/aio/src/styles/1-layouts/_top-menu.scss#L3

**Comment by furevor** [comment]
@gkalpak 
I have fixed it as you proposed

**Review by gkalpak — APPROVED** [review]
LGTM 👍
Can you please squash the commit into one and change the commit message to something like:

> fix(docs-infra): fix top menu logo position
>
> Fixes #26468

**Comment by furevor** [comment]
@gkalpak squash done! :)

**Comment by furevor** [comment]
> You can preview [8309fcb](https://github.com/angular/angular/commit/8309fcbcdcd1ca09cb0ab400c749e5357854751f) at https://pr26473-8309fcb.ngbuilds.io/.

seems to be ok

**Comment by gkalpak** [comment]
Thx, @furevor. Can you please update the commit message as described in https://github.com/angular/angular/pull/26473#pullrequestreview-165545727?
(This will ensure that the fixed issue will be automatically closed once the PR is merged.)

**Comment by furevor** [comment]
> Thx, @furevor. Can you please update the commit message as described in [#26473 (review)](https://github.com/angular/angular/pull/26473#pullrequestreview-165545727)?
> (This will ensure that the fixed issue will be automatically closed once the PR is merged.)

I am sorry, this is my first pull request )) I have changed commit message as you advised:)

**Comment by Splaktar** [comment]
@furevor congrats on getting your first PR merged!

**Comment by furevor** [comment]
> @furevor congrats on getting your first PR merged!

thanks :)

**Pull request closed without merging**
