### PR TITLE
build: remove deps on legacy nodejs rules rollup_bundle internals

### PR DESCRIPTION
**Pull request by gregmagolan**
Two problems with original PR #33201:

1) Windows CI failed on master and wasn't caught as it doesn't run by default on PRs. I think I'll turn it on temporarily for all build related PRs from now on as these are more likely to break Windows. For this PR I tested that the fix was green on Windows here: https://circleci.com/workflow-run/9526d9d2-286b-45c6-ba83-7bfbeaa632b6

2) In-flight conflict with material that broke `material-unit-tests`. I landed https://github.com/angular/components/pull/17620 in material to fix this and updated the material commit in this PR.

### CODE REVIEW

**Comment by gregmagolan** [comment]
Windows issues fixed. material-unit-test still red and requires https://github.com/angular/components/pull/17620 to land first.

**Review by josephperrott — APPROVED** [review]
LGTM, global approval

**Comment by gregmagolan** [comment]
@josephperrott There may be some syncing changes required for this. Alex ran the g3sync for the original PR #33201. He left a link here if that helps: https://github.com/angular/angular/pull/33201#issuecomment-547972560

**Comment by josephperrott** [comment]
[g3 presubmit](https://test.corp.google.com/ui#cl=278881292)

**Pull request closed without merging**
