### PR TITLE
docs(aio): add Dart as a language option

### PR DESCRIPTION
**Pull request by juleskremer**

### CODE REVIEW

**Comment by kwalrath** [comment]
Thank you!

@filiph & @matanlurey, you can see this change in the version drop-down in https://pr18080-91861aa.ngbuilds.io/docs (or, I think, any other page under /docs).

**Comment by filiph** [comment]
Awesome, thank you! LGTM.

**Review by gkalpak — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Sadly we need a marketing person (other than Jules) to approve this

**Comment by juleskremer** [comment]
@IgorMinar please approve

**Review by IgorMinar — APPROVED** [review]

**Pull request merged**
