### PR TITLE
docs: fix links to angular documentation

### PR DESCRIPTION
**Pull request by demike**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
A markdown file points to the (now outdated) https://angular.io/docs

Issue Number: N/A

## What is the new behavior?
Replace the link with the new docs link (https://angular.dev/overview)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by devversion** [comment]
Thank you. Can you please sign the CLA so that we can land your change?https://github.com/angular/angular/pull/57391/checks?check_run_id=28755638546

**Comment by devversion** [comment]
@demike Thank you for signing the CLA! The only thing remaining is that there is a `Merge commit` that shouldn't be in this pull request. Ideally, try rebasing via `git` command line to `main` and dropping that commit.

**Comment by demike** [comment]
@devversion sorry for the inconvenience, hope this works now!

**Review by JeanMeche — APPROVED** [review]

**Review by devversion — APPROVED** [review]
No problem. Thank you for the PR

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit a2990757cc6a9b335621063e38b8a49da4ec9878.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
