### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by GrantFleming**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The word 'growns' is used

Issue Number: N/A

## What is the new behavior?
The word 'grows' is used

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by GrantFleming** [comment]
@googlebot I signed it!

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
Hi @GrantFleming - Thanks for the fix. Could you address the lint failure? We enforce a body length on the commit messages. You can use something like 'Correct typo in the router docs, changing "as your app growns" to "as your app grows"'

**Comment by GrantFleming** [comment]
Oops, will do.

**Review by cunla — APPROVED** [review]

**Comment by GrantFleming** [comment]
I have amended the commit message as requested but am unsure how to trigger a re-run of the CI.

**Comment by GrantFleming** [comment]
I have amended the commit message as requested but I am unsure why the CI is now faililng with:

```
TypeError: Cannot read property 'ref' of undefined
    at _main (/home/circleci/ng/tools/rebase-pr.js:89:36)
```

Is this because I force pushed after amending a commit? I didn't think it mattered in this instance because nobody would be using this branch.

**Comment by atscott** [comment]
Hmm, that shouldn't have caused an error, no. Could you try rebasing with master and force pushing again?

**Comment by GrantFleming** [comment]
image

hmmm nup no cigar.

If this pull request is more trouble than it's work I'm happy for it to be closed.

**Comment by GrantFleming** [comment]
@atscott all seems good now. One failing test but it seems to be because of an ssh timeout. Can this test be re-run easily?

**Comment by petebacondarwin** [comment]
I have re-started that test

**Pull request closed without merging**
