### PR TITLE
docs: Add missing markup for the hierarchical dependency injection guide

### LINKED ISSUE #34850: Missing html mark-up
The following markup is missing
```
<p>The following is coming from content. It doesn't get to see the puppy because the puppy is declared inside the view only.</p>
```
# 📚 Docs or angular.io bug report

### Description
The above markup is missing above `<ng-content></ng-content>`
in the quotation of `providers-viewproviders/src/app/child/child.component.html`
It is present in the Stackblitz example, it is quoted as part of the rendered result, but not in the blockquote of code which the doc is asking to insert into that file

### What's the affected URL?**
https://angular.io/guide/hierarchical-dependency-injection

## 🔥 Exception or Error
<pre><code>

</code></pre>

### PR DESCRIPTION
**Pull request by sonukapoor**
Fixes #34850

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #34850

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Thanks for this, @sonukapoor. I need to refresh my mind on how I wrote that in the doc. That bit of html was intentionally left out of the code snippet, but I have to take a look back and see what my reasoning was. At first glance, I think it was because that html was meant for the stackblitz example and not the doc as much. Please give me a few days to review this properly.

**Comment by kapunahelewong** [comment]
Thanks for your patience on this while I looked it through, @sonukapoor. Looks like a good change, but could you make the inline snippet a few lines later where it says:

>Content projection: This is coming from content. Doesn't get to see
puppy because the puppy is declared inside the view only.

the same as what's in the markup?

**Comment by sonukapoor** [comment]
> Thanks for your patience on this while I looked it through, @sonukapoor. Looks like a good change, but could you make the inline snippet a few lines later where it says:
> 
> > Content projection: This is coming from content. Doesn't get to see
> > puppy because the puppy is declared inside the view only.
> 
> the same as what's in the markup?

Good catch @kapunahelewong - I should have seen that. I have updated the section. Please check again.

**Comment by sonukapoor** [comment]
@kapunahelewong Actually, the `ng-content` is supposed to be empty, as the content will be projected into that area. The examples and documentation are fine the way it is in my opinion. I will make a note on the issue.

**Comment by kapunahelewong** [comment]
Great, so will you be taking the `<p>` tag back out of the `<ng-content>`? (I hadn't noticed that you'd moved it inside.) It seems like all you need to do is remove the doc region, no?

**Comment by kapunahelewong** [comment]
Per offline conversation, @sonukapoor and I determined to close this as the snippet is correct.

**Pull request closed without merging**
