### PR TITLE
refactor(bazel): use runfiles helper in ts-api-guardian

### PR DESCRIPTION
**Pull request by gregmagolan**
Pre-fractor for future rules_nodejs release when require.resolve patches are removed.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM! 

<sup>As noted on Slack; This PR currently just fails due to an invalid cache on your fork due to work in #36333</sup>

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by atscott** [comment]
@gregmagolan - It looks like this might be ready to merge. Please remove Grep from the reviewers list if his review is not needed.

**Comment by gregmagolan** [comment]
> @gregmagolan - It looks like this might be ready to merge. Please remove Grep from the reviewers list if his review is not needed.

Thanks. Didn't notice that.

**Pull request closed without merging**
