### PR TITLE
fix(ngUpgrade): return $injector from AoT bootstrap method

### PR DESCRIPTION
**Pull request by petebacondarwin**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

The ngUpgrade AoT `boostrap()` function does not return the `$injector`

**What is the new behavior?**

The ngUpgrade AoT `boostrap()` function does return the `$injector`

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

cc: @mhevery

### CODE REVIEW

**Comment by vsavkin** [comment]
Could you fix Travis?

**Comment by vicb** [comment]
@petebacondarwin you need to run `gulp public-api:update` when the public API is changed to re-generate the reference files.

However changing the ref files is an API break and could not happen before 3.0

**Comment by petebacondarwin** [comment]
@vicb - sorry about forgetting to update the API files. This would not be a breaking change and so would be fine to go into a 2.x minor release.

**Comment by vicb** [comment]
np.

Why is this not a breaking change ? 
If someone extends the class, this PR will break is code, right ?

**Comment by petebacondarwin** [comment]
@vicb you're right! I didn't realise that TypeScript would bail if a child class method override does not match the parent class.

In this case we are OK though. Apart from the fact that subclassing this class is not the recommended approach and so unlikely to affect any real code, it is also marked as `@experimental`, which I believe gives us freedom to make breaking changes such as this.

**Comment by vicb** [comment]
`@experimental` means that we can break in major version (3.0) without having a deprecation story first.

**Comment by petebacondarwin** [comment]
@vicb I just re-read the blog post and you are right again! 

So this is a problem. Perhaps @mhevery can make a call here. We have a brand new API that was pushed into the master branch only so that internal Google projects could try it out. We now appear to be trapped by the no-BC rules so that we cannot evolve this API any more.

**Comment by vicb** [comment]
My understanding was that we would create a `ngUpgradeAgain` package to "work around" the API break rule. 
@mhevery will know more.

**Comment by mhevery** [comment]
I don't think this is a breaking change as this has not been released yet. (Only releases have been beta/rc)

**Comment by petebacondarwin** [comment]
Sadly with the release of 2.2.0 the `void` API is now in a public release. So I unless @mhevery overrules, this might have to wait for 3.0

**Comment by mhevery** [comment]
No one should be subclassing the class, so I don't see a reason why we can't change that? I vote for merging it in. @IgorMinar ?

**Comment by petebacondarwin** [comment]
I'm afraid that after the fix (for protractor) that allows for a delayed bootstrap via `window.resumeBootstrap` we can no longer return the `$injector` in a synchronous manner from the `bootstrap` method. The dynamic style `UpgradeAdapter` gets around this by returning the `UpgradeAdapterRef` object which will have its `$injector` property set later. In this case the `UpgradeModule` is the relevant object, which of course the caller already has access to in order to call the `bootstrap` method in the first place.

What I think we really need here is to put some kind of pseudo promise into the Angular 1 compilation so that the caller can tell when compilation has settled.

Closing this PR as not valid.

**Pull request closed without merging**
