### PR TITLE
fix(zone.js): only call jasmine test done function once

### PR DESCRIPTION
**Pull request by crisbeto**
Currently zone.js may end up attempting to call the `done` function of async tests more than once. This used to be a noop, but Jasmine now logs the following warning:

```
DEPRECATION: An asynchronous function called its 'done' callback more than once. This is a bug in the spec, beforeAll, beforeEach, afterAll, or afterEach function in question. This will be treated as an error in a future version. See<https://jasmine.github.io/tutorials/upgrading_to_Jasmine_4.0#deprecations-due-to-calling-done-multiple-times> for more information
```

These changes add a wrapper around the `done` function so it only gets called once, otherwise we risk triggering errors in future versions of Jasmine.

**Note:** I couldn't figure out a good way to add a test for this since it would be checking something that's part of the testing infrastructure.

### CODE REVIEW

**Comment by crisbeto** [comment]
The build error is unrelated and will be fixed by https://github.com/angular/angular/pull/44924.

**Comment by JiaLiPassion** [comment]
@crisbeto , the changes LGTM, I just wonder is there a reproduce scenario or repo to describe the error case?

**Comment by crisbeto** [comment]
I noticed it both in the tests of this repo and the ones in angular/components. Usually you won't see it, because Bazel doesn't log anything if the test run passes. You can get it to show up by adding a test that always fails. I was testing like this:

1. Add a failing test to `packages/core/test/util_spec.ts`. Something like `it('should fail', () => expect(1).toBe(2));`. The file doesn't really matter, as long as it's in the test target mentioned below.
2. Run `yarn bazel test packages/core/test:test`.

**Comment by JiaLiPassion** [comment]
@crisbeto , thank you for the reproduce, I did some debug and find out this maybe a bug of `asyncTest` in zone.js, I will try to fix it in another PR, I will let you know when it is ready for review.

**Comment by crisbeto** [comment]
So I had this fixed in `aysnc-test.ts` as well by only calling the `finishCallback` once here https://github.com/angular/angular/blob/master/packages/zone.js/lib/zone-spec/async-test.ts#L226. I ended up doing it in `jasmine.ts` instead, because it seemed like a more appropriate place for a fix that is specific to a warning generated by Jasmine.

**Comment by JiaLiPassion** [comment]
@crisbeto , I just figured it out that the issue is a bug of `AsyncTestZone`, and I created a PR to fix it, https://github.com/angular/angular/pull/45025, I believe this fix will resolve the jasmine warning about the multiple done issue, and also resolve a lot of other flaky test issues . Please review. Thank you

**Comment by crisbeto** [comment]
Closing in favor of #45025.

**Pull request closed without merging**
