### PR TITLE
docs: remove unnecessary/confusing route from examples

### PR DESCRIPTION
**Pull request by swisscoder**
Warning about double wildcards in example

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by swisscoder** [comment]
@googlebot I signed it!

**Review by kapunahelewong — COMMENTED** [review]
Thanks for finding this, @swisscoder! (I'm the one who made this mistake! 🙃) To fix it, we need to take that first wildcard out of that example, which means editing the docregions. In editing the docregions, we have to make sure that it doesn't mess up another example in the router doc. Are you comfortable editing those? If not, I can take it. Just let me know. 🙂

Here's the file that has to be edited: https://github.com/angular/angular/blob/master/aio/content/examples/router/src/app/app-routing.module.8.ts#L11

**Comment by swisscoder** [comment]
Thanks for getting back to me @kapunahelewong. 
The docs seem to not need that line at all.
I've edited the example ts file, as you suggested and undid the other change.

**Comment by kapunahelewong** [comment]
@swisscoder, this is great. Could you rebase? The preview is rendering your first commit (and the error that you're getting is one that I got earlier today and fixed with a rebase). Squashing would be good too since you'll have to do that anyway. If you need a hand with either step, I can help out. I also keep my own notes on [rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) and [squashing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) if you would like to refer to them. 

Please tag me when you're ready or if you have any questions. I'll be on the lookout for any notifications from you so I can catch it right away. Thank you!

**Comment by atscott** [comment]
Closing, as progress on this seems to have stopped. Please open a new PR if you would still like to contribute a fix. Thank you!

**Pull request closed without merging**
