### PR TITLE
feat(common): implement appendAll for HttpParams

### LINKED ISSUE #20798: HttpParams doesn't have appendAll method...
Angular version: 5.0.3

### PR DESCRIPTION
**Pull request by harunurhan**
Close #20798

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #20798 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by alxhub — APPROVED** [review]

**Comment by alxhub** [comment]
@harunurhan please update the commit to include a detailed description of the new feature and the motivation behind it, thanks!

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Comment by harunurhan** [comment]
@alxhub I rebased and updated the commit message.

**Comment by petebacondarwin** [comment]
@harunurhan - a couple of typos in the commit message:

`contruct` -> `construct`
`avoid` -> `avoids`

**Comment by harunurhan** [comment]
ping @petebacondarwin

**Comment by petebacondarwin** [comment]
@harunurhan - we are awaiting reviews for `public-api` from a minimum of two of the requested reviewers, plus the code needs testing against the internal Google repository (`google3` presubmit). Since it is now the holiday period, it is unlikely these things will happen before New Year.

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

Nit on the commit message:
It currently reads "Adds `appendAll` functionality to for HttpParams..." but should be "Adds `appendAll` functionality to HttpParams..."

**Comment by atscott** [comment]
[presubmit](http://test/OCL:348487204:BASE:348487227:1608574836053:b820bbf8)

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:352898916:BASE:352898935:1611188275131:8ac2cdb8).

**Comment by AndrewKushnir** [comment]
@petebacondarwin FYI, presubmit is successful for the changes in this PR. Thank you.

**Pull request closed without merging**
