### PR TITLE
build against both stable and dev channels of Dart

### PR DESCRIPTION
**Pull request by kevmoo**
@chirayuk - I also removed your work-around for 20896

This seems to be fixed

### CODE REVIEW

**Comment by kevmoo** [comment]
@yjbanov would you merge this in? Or give me a commit bit? :smile:

**Comment by vicb** [comment]
won't this test JS twice ?

**Comment by kevmoo** [comment]
@vicb Yes, it will.

I bet we can get a bit clever with the travis script to only re-run Dart – but I'd need help doing it.

**Comment by yjbanov** [comment]
I could give it a try, if you don't mind. I have our build master Tobias sitting 6 feet away from me.

**Comment by kevmoo** [comment]
Awesome.

This is good for Angular and Dart – let's make sure the transition to Dart v+1 is super smooth

**Comment by yjbanov** [comment]
Superseded by #651. Closing.

**Pull request closed without merging**
