### PR TITLE
Docs lifecycle

### PR DESCRIPTION
**Pull request by tbosch**

### CODE REVIEW

**Comment by tbosch** [comment]
@petebacondarwin @IgorMinar When I want to link to the lifecycle event dev guide, I am getting the error below.

This is strange as other parts in our sources already refer to this guide successfully (see e.g. https://github.com/angular/angular/blob/master/modules/@angular/core/src/metadata.ts#L294).

Note: My links contain a `#` at the end, but the error is also present when I remove the `#`.

To reproduce: Clone this PR and replace `\@ with `@` in the file `lifecycle_hooks.ts`

```
TypeError: Cannot read property 'baseName' of undefined
    at Object._self.handler (/Users/tbosch/projects/angular.io/tools/api-builder/links-package/inline-tag-defs/linkDocs.js:49:76)
    at /Users/tbosch/projects/angular.io/node_modules/dgeni-packages/jsdoc/processors/inline-tags.js:229:41
```

**Comment by zoechi** [comment]
Some hint which lifecycle hooks will or will not throw "expression has changed after it was checked" when they modify the model would be great.

**Comment by tbosch** [comment]
@zoechi This is already documented in the lifecycle guide (http://localhost:3000/docs/ts/latest/guide/lifecycle-hooks.html#!#afterview). I shortened the docs on lifecycle to a simple example and point to the dev guide.

**Comment by zoechi** [comment]
@tbosch thanks for the link. I read 3 times through the docs until I saw it.
I'll create an issue for angular.io to make this more obvious.

**Comment by tbosch** [comment]
Closing in favor of #11609

**Pull request closed without merging**
