### PR TITLE
docs: add webucator to resources

### PR DESCRIPTION
**Pull request by isunkes**
Added Webucator's Angular Training to Workshops & Onsite Training section.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Added Webucator's Angular Training to Workshops & Onsite Training section of resources.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks for the PR @isunkes! You'll also need to set the branch to `master`.

Once that change is made, its reviewed and approved, and is green on CI it will be ready to merge.

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update the git commit message to `docs: add webucator to resources`

**Comment by isunkes** [comment]
How do I switch this to master?

**Comment by brandonroberts** [comment]
You probably need to close this PR and open a new one against master.

**Comment by isunkes** [comment]
Thanks

**Comment by gkalpak** [comment]
FYI, you can change the target branch of a PR by clicking the `Edit` button on the top right.

**Comment by isunkes** [comment]
I have another pull request already started on master so will delete this branch and let that one go through the process.

**Pull request closed without merging**
