### PR TITLE
docs: Use ngOnInit to fetch data from services in the Getting Started guide

### PR DESCRIPTION
**Pull request by bampakoa**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #32048

## What is the new behavior?
Data services are queried inside `ngOnInit` interface implementation of components

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
@kapunahelewong

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Thank you, @bampakoa. I thought you meant to call methods _from within_ `ngOnInit()`. Could you put that logic in a separate method and then call that method in the `ngOnInit()`? Like:

```ts
  ngOnInit() {
    setItems();
  }	  

  setItems() {
    this.items = this.cartService.getItems();
  }
```
This is a point I've been corrected on before (so it has stayed in my mind!). What do you think?

**Comment by bampakoa** [comment]
@kapunahelewong you are right. This is also the way that I follow in my projects. But isn't it too complicated for a Getting Started guide? I mean the purpose is to show them the proper way of calling services in a component. This looks to be more of a coding style as in Angular Style Guide.

**Comment by kapunahelewong** [comment]
You're right, @bampakoa. I looked more closely and the Getting Started has logic in the `ngOnInit()` in [routing](https://angular.io/start/routing). Never mind what I said! :)

**Review by kapunahelewong — APPROVED** [review]
LGTM, thank you @bampakoa!!

**Review by gkalpak — APPROVED** [review]
Thx, @bampakoa :tada:
Can you, please, change the commit message to `docs: ...` (we have deprecated the `aio` scope) 🙏

**Comment by bampakoa** [comment]
@gkalpak sure. Bear in mind that it still appears in the list of suggested scopes during commit 😉

**Comment by gkalpak** [comment]
> Bear in mind that it still appears in the list of suggested scopes during commit

That doesn't sound right. Where exactly does it appear?

**Comment by gkalpak** [comment]
**merge-assistance:** Global approval for this docs-only change.

**Comment by bampakoa** [comment]
@gkalpak When I tried to commit my change initially through Visual Studio Code, I got a notification (correctly) that my commit message does not follow the guidelines of the repository. It specifically suggested me a list of scopes where **aio** was included. 

After a search I think that it is due to [this](https://github.com/angular/angular/blob/3df54be9e4580986cf4714b22f6b2800ee593939/tools/validate-commit-message/commit-message.json#L16)

**Comment by gkalpak** [comment]
This is a custom config file that VSCode should have no idea about :grin:
Can you look into where that notification came from? Was it a VSCode extension?

**Comment by bampakoa** [comment]
It came from the **Git** output window of the VSCode when I tried to commit. I thought that `commit-message.json` file is parsed every time you are trying to commit. Isn't it?

**Comment by gkalpak** [comment]
Oh, it is the commitmsg git hook. Yes, you are right. That's where the error message comes from :grin:
We have kept it there, because there were in-flights PRs that used the `aio` scope at the time. I think it is safe to remove it from the list of valid scopes now (it's been a while).

**Pull request closed without merging**
