### PR TITLE
docs(docs-infra): update examples to the latest release

### PR DESCRIPTION
**Pull request by marcin-wosinek**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently, if I download an example from https://angular.io/tutorial/toh-pt6, the `npm i` fails with:
```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular.io-example@0.0.0
npm ERR! Found: @angular/common@14.0.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0" from angular-in-memory-web-api@0.13.0
npm ERR! node_modules/angular-in-memory-web-api
npm ERR!   angular-in-memory-web-api@"~0.13.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/marcinwosinek/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marcinwosinek/.npm/_logs/2022-06-29T16_17_45_073Z-debug.log
```

Issue Number: N/A

## What is the new behavior?

It still fails, but with a different error:
```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular.io-example@0.0.0
npm ERR! Found: rxjs@7.5.5
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~7.5.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.5.3" from jasmine-marbles@0.8.4
npm ERR! node_modules/jasmine-marbles
npm ERR!   dev jasmine-marbles@"~0.8.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/marcinwosinek/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marcinwosinek/.npm/_logs/2022-06-29T16_18_49_077Z-debug.log
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by marcin-wosinek** [comment]
The other install issue can be fixed by switching to `"jasmine-marbles": "~0.9.2",`. Should I make a separate MR/commit for it, or just add it here?

**Comment by gkalpak** [comment]
Thx for working on this, @marcin-wosinek :+1:
We are discussing to decide what is the best way to address the issue with `angular-in-memory-web-api`'s peer dependency range not accepting pre-release versions of Angular (for example, the currently used `14.1.0-next.3`).

I'll let you know as soon as we have a resolution.

##
Regarding your last question: Feel free to update `jasmine-marbles` in the same commit (or on a separate commit on this PR).

BTW, you also need to update the lockfile at `aio/tools/examples/shared/yarn.lock` by running `yarn` inside the `aio/tools/examples/shared/` directory.

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx for making the changes, @marcin-wosinek :heart:

One last thing:
Can you please change the commit message to contain a little more detail. Something like:

> build(docs-infra): update versions of some docs examples dependencies
>
> Update `angular-in-memory-web-api` and `jasmine-marbles` (used in docs examples) to latest versions.

Other than that, this lgtm :+1:

##
BTW, I have created #46715 to track the issue with `angular-in-memory-web-api`'s incompatibility with prerelease versions of Angular.

This issue will still cause an error when trying to `npm install` in a downloaded docs example, but it should not block this PR.

**Comment by marcin-wosinek** [comment]
@gkalpak thanks for your feedback! I applied it & rebased the branch.

**Review by gkalpak — APPROVED** [review]
Thank you, @marcin-wosinek 🚀

**Pull request closed without merging**
