### PR TITLE
docs: remove unnecessary newline

### PR DESCRIPTION
**Pull request by nikselite**
## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by juleskremer — APPROVED** [review]

**Comment by gkalpak** [comment]
What typo is this PR fixing? 😕

**Comment by nikselite** [comment]
This PR removes a unnecessary newline.

| Before         | After          |
| :------------: | :------------: |
| before | image |

**Comment by gkalpak** [comment]
I see. Well, that's not a typo; the rendered output is the same. It is common to limit lines in markdown files to a certain number or chars (although it is equally common not to :smiley:).

The PR is fine - just asked out of curiosity.

**Comment by matsko** [comment]
@nikselite please fix up the commit message to match the requirements of what circleci is requesting.

**Comment by nikselite** [comment]
Done.

@matsko

**Pull request merged**
