### PR TITLE
fix hammer_gestures infinite loop

### PR DESCRIPTION
**Pull request by asukaleido**
ref #6993

### CODE REVIEW

**Comment by asukaleido** [comment]
I signed it!

**Comment by vikerman** [comment]
TAP green

**Comment by vikerman** [comment]
Travis is failing on merge conflicts. Please rebase - https://travis-ci.org/angular/angular/builds/114401308

**Comment by vikerman** [comment]
Will rebase and push this

**Comment by vikerman** [comment]
Manually merged

**Pull request closed without merging**
