### PR TITLE
docs: fix code-example header path in dependency-injection-in-action-md

### PR DESCRIPTION
**Pull request by shavidze**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@shavidze thanks for improving Angular docs, the change looks good 👍 

Could you please also merge all 3 commits into one when you get a chance? Please let us know (by leaving a comment here) once it's done, so that we can proceed with the final review and the merge.

Thank you.

**Comment by shavidze** [comment]
> @shavidze thanks for improving Angular docs, the change looks good 👍
> 
> Could you please also merge all 3 commits into one when you get a chance? Please let us know (by leaving a comment here) once it's done, so that we can proceed with the final review and the merge.
> 
> Thank you.

Done!

**Review by AndrewKushnir — APPROVED** [review]
@shavidze thanks for merging commits into one! This PR is now added to the merge queue.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit f79a5bc71c621910b8ec87840c6043d65eed1587.

**Pull request closed without merging**
