### PR TITLE
add cygwin support to build.sh and scripts/windows/create-symlinks.sh, so cygwin users can build angular on 32-bit machines

### PR DESCRIPTION
**Pull request by ribbon-otter**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

I wrote no tests as I did not see a testing framework for the build system scripts.

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The build fails to work on windows/cygwin when following the [DEVELOPER.md](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md). Note that this set up involves the windows version of node because cygwin does not package node.

## What is the new behavior?

The build with build.sh now finishes on windows/cygwin without errors. Note that to make the build succeed on a clean build, I had to run `bower install`. This step is undocumented as far as I can tell. This pull request does not modify documentation as I was unsure if this was my fault, or if the documentation actually needs updating. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
In my tests, I only get a log report saying that ` build.sh build package: core ` and not for any of the other packages. I don't know if this is normal behavior or not because I never built angular successfully before

### CODE REVIEW

**Comment by ribbon-otter** [comment]
I signed it
(I am hoping this worked. I might need to do it again, to get email synced correctly)

**Comment by alexeagle** [comment]
@filipesilva @DevVersion @gkalpak you are the windows experts, do we want a fix like this? I think we just want to remove build.sh

**Comment by filipesilva** [comment]
I think it is only a matter of time until these changes would either 
- rot (because we don't test on Windows)
- are made obsolete (because we remove build.sh in favor of Bazel)
- need follow up changes (because something else isn't quite working in cygwin)

So I don't think it's worth changing the current build script much at this time.

**Comment by gkalpak** [comment]
I think we've given up updating `build.sh` some time ago (e.g. I don't think it even compiles all packages/subpackages atm).
Since it is going away soon, I agree there is no point in modifying it.

**Comment by AndrewKushnir** [comment]
Closing this PR based on the comments in this thread and the fact that the `build.sh` as well as `scripts/windows/*` files were removed. Thank you.

**Pull request closed without merging**
