### PR TITLE
fix(common): do not override locale provided on bootstrap

### LINKED ISSUE #13607: LOCALE_ID is overwritten with platformBrowserDynamic
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you provide `LOCALE_ID` as an extra provider like so:
`platformBrowserDynamic([{'provide': LOCALE_ID, 'useValue': 'sv'}]).bootstrapModule(AppModule) `
it gets overwritten with `en-US` .

**Expected behavior**
Keeping the `LOCALE_ID` provided.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/1Ev5fIVVwpPMgln6lMVJ?p=preview

* **Angular version:** 2.0.X
ng 2.3.0

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Closes #13607

### CODE REVIEW

**Review by vicb — CHANGES_REQUESTED** [review]
Please add a test

**Comment by DzmitryShylovich** [comment]
@vicb There's a problem with writing a test case for it :)
I need to create a new platform with providers, but there's already a default platform configured for test thus I cannot create a new one (only 1 platform can be active at a time). I also cannot destry a default one because, for some reason, it's already marked as destroyed. I faced the same issue here https://github.com/angular/angular/pull/13105
I tried to use  compiler providers
```
defaultPlatform.bootstrapModule(createModule(), {providers: [{provide: LOCALE_ID, useValue: 'fr-FR'}]})
```
but they are not available for the app. 
So do u know where I can found a test example with a custom platform or do u have an idea how I can test it without creating a new platform?

**Comment by vicb** [comment]
Create an e2e test?

**Comment by DzmitryShylovich** [comment]
@vicb added a test

**Review by vicb — APPROVED** [review]

**Comment by vicb** [comment]
great, thanks !

**Pull request merged**
