### PR TITLE
docs(forms): fix grammar and add clarification to setValue

### PR DESCRIPTION
**Pull request by Coly010**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

`setValue` method on `FormGroup` documentation for when it would throw contained a grammar
mistake and also may have caused ambiguity around when exactly the
method would throw.

## What is the new behavior?

Changed `setValue` documentation for throwing an error to fix grammar mistake and reduce potential ambiguity.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Coly010** [comment]
@googlebot I signed it!

**Comment by Coly010** [comment]
@googlebot I signed it!

**Comment by kapunahelewong** [comment]
@Coly010 This is great, thank you!! 😊 

Caretaker, this is a docs only change. Please let me know if I can be of any help. Thank you!

**Review by kapunahelewong — APPROVED** [review]
LGTM. This is a docs only change.

**Comment by kapunahelewong** [comment]
Oh wait, @Coly010, can you squash so there's only one commit? Here are [my notes on my own workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) if you'd find them helpful. Thank you!

**Comment by Coly010** [comment]
Sure thing!

**Comment by Coly010** [comment]
Should be back to one commit now!

**Comment by kapunahelewong** [comment]
Thank you, @Coly010!

Caretaker, this is a docs only change. Please let me know if I can be of any help. Thank you!

**Pull request closed without merging**
