### PR TITLE
[WIP] feat(common): add new NgLoopTo directive

### PR DESCRIPTION
**Pull request by ghetolay**
NgLoopTo directive instanciates templates following a common loop pattern.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added
- [ ] Docs have been added / updated

**What kind of change does this PR introduce?** (check one with "x")
- [x] Feature

## Description
This directive complete `ngFor` by allowing iteration over a range of number without having to build a fake array. This uses 4 Inputs: `from`, `to`, `by` and `precision`. Both `from` and `to` are inclusive. `precision` define the precision to use when handling decimal number.
The directive is named `ngLoopTo` because `to` is the only mandatory input.
### usage 

```ts
*ngLoop="let i from 0 to 6 by 2"
```
will generate `0, 2, 4, 6`.

```ts
*ngLoop="let i to 3"
```
will generate `0, 1, 2, 3`.

```ts
*ngLoop="let i from 1.2 to 1.4 by 0.1"`
```
will generate `1.2, 1.3, 1.4`

## Concerns
This is still a work in progress because I still have some concerns : 

1) Decimals: I had a bit of trouble handling decimals. I'm not sure current implementation will handle correctly all corner cases. Passing `to` to exclusive instead of inclusive could make things easier for decimals.
2) Reusable DOM Elements: Currently we reuse DOM elements based on the number of elements but not on their value. For example if we go from `1, 2, 3` to `1, 2, 3, 4` we'll just push a DOM element at the end and keep the three first unchanged. But if we go from `1, 2, 3` to `0, 1, 2, 3` we will reuse existing elements but change their values :
```
1 2 3
| | |
0 1 2 3
```
The perfect solution here would have been to prepend a new element and keep the last 3 unchanged. But doing so requires complexity I'm not sure it's worth having. 
Take for example going from `0, 2, 4` to `2, 3, 4`.

This is my first PR so I'm all ears for any feedback.
P.S.: I wasn't able to run `gulp format` so circleci may fail but no worry I'll correct it.

### CODE REVIEW

**Comment by tytskyi** [comment]
Hi @ghetolay i respect your work done. Please do not treat my comment as personal attack :) 
I have 2 questions:
1. Why do you want to inline in into angular? You could build npm modules with such directive and then anyone can install and use it.
2. It is event easy without directive, because to generate fake array we just need an utility. Something like `_.range(0, 6, 2)`

**Comment by ghetolay** [comment]
Hi, @tytskyi this pr is a following of [that plunker](https://plnkr.co/edit/DGp3BY3FeROFS3oCI1kS?p=info) I did a while ago to help someone on gitter. Then after sharing it multiples times I thought we could make a common directive from it. It's very basic utility that's why I think it should fit on the core framework.
I wouldn't create a lib for just 1 directive, if this is rejected I'll probably just create a gist and share it.

About using `ngFor` I consider it being a workaround as it's a bit an overkill to generate an array, run a differ on it on each CD etc... when you just want to display 3 `<li>`. I also did a pipe to use with `ngFor` that generated an array, but I prefer that lightweight directive better.

**Comment by vicb** [comment]
This could live outside of Angular, right ?

_I don't see any good reason for this to include it_

**Comment by ghetolay** [comment]
This could totally live outside Angular like any directive part of the common module, it's up to you to decide if this is worth to also be part of the common module.

This was a long time ago but I think I was reacting to people asking how to loop through numbers. Like we can loop through models with `ngFor` but we can't easily create 5 `li` without using some static array as a fake model.

**Comment by sandangel** [comment]
IMO this should be a part of NgForOf instead.

**Comment by vicb** [comment]
Closing as we don't see this being a big use case.

**Pull request closed without merging**
