### PR TITLE
style: fix typos boostrap to bootstrap

### PR DESCRIPTION
**Pull request by adrienboulle**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by adrienboulle** [comment]
I signed it

**Comment by wardbell** [comment]
Thanks!  I've tee'd this up for approval by someone authorized to do that.

**Review by wardbell — APPROVED** [review]
LGTM _after_ you resolve the conflict with the `upgrade.md` file.

I could approve that one if you moved it into a separate PR, away from the API doc changes.

I have tee'd this PR up for approval by someone authorized for API doc changes (which I am not).

**Comment by adrienboulle** [comment]
@wardbell thx for the update, i've cleaned it up! :)

**Comment by jenniferfell** [comment]
The "boostrap" to "bootstrap" issue has been resolved. Current doc is correct: https://angular.io/guide/ngmodule-faq
I also don't find the typo in the ngModule API ref. Closing. If I've overlooked an instance of the problem, please open an issue. Thank you.

**Pull request closed without merging**
