### PR TITLE
docs: fix minor grammatical error in glossary

### PR DESCRIPTION
**Pull request by Brianmanden**
A instance => An instance

Read more forms => Read more about forms

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@Brianmanden - thanks for this. Can you fix up the commit message to follow our require format?
The expected format for a commit is: 

```
<type>(<scope>): <subject>

<body>
```

See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by Brianmanden** [comment]
I thought they were up to standard.

What should I change ?

**Comment by petebacondarwin** [comment]
Currently the commit message is:

```
Fix minor grammatical errors 

A instance => An instance

Read more forms => Read more about forms
```

Instead it should be something more like:

```
docs: fix minor grammatical errors in the glossary

A instance => An instance

Read more forms => Read more about forms
```

**Comment by Brianmanden** [comment]
Done :)

**Review by IgorMinar — APPROVED** [review]
LGTM! Thank you!

Reviewed-for: global-approvers

**Comment by petebacondarwin** [comment]
Sorry @Brianmanden - it is not enough to change the title of the PR. You have to actually amend the commit itself and force-push to your remote branch. Let me know if you need help with this.

**Comment by Brianmanden** [comment]
Too much hazzle - why bother.

**Comment by petebacondarwin** [comment]
No problem. I appreciate that for such a small change it does seem like a hassle. Unfortunately it is necessary, because we generate our change-log directly from the commit messages, so it is important that they conform to a well defined syntax.

**Pull request closed without merging**
