### PR TITLE
chore(animation): remove double var declaration.

### PR DESCRIPTION
**Pull request by rkirov**
**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by alexeagle** [comment]
Can we add something (eg. tslint check) to prevent regressions?

**Comment by vicb** [comment]
+1 for a lint rule

**Comment by alexeagle** [comment]
added `"no-duplicate-variable":true,` to `tslint.json` and I get:
```
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[252, 13]: duplicate variable: 'span'
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[260, 13]: duplicate variable: 'span'
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[265, 13]: duplicate variable: 'tokens'
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[271, 13]: duplicate variable: 'span'
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[282, 13]: duplicate variable: 'tokens'
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[283, 13]: duplicate variable: 'endToken'
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[286, 13]: duplicate variable: 'end'
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[287, 13]: duplicate variable: 'strValue'
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[288, 13]: duplicate variable: 'span'
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[289, 13]: duplicate variable: 'query'
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[315, 13]: duplicate variable: 'endToken'
[16:48:57] [gulp-tslint] error compiler/src/css_parser.ts[316, 13]: duplicate variable: 'span'
[16:48:58] [gulp-tslint] error upgrade/src/metadata.ts[40, 7]: duplicate variable: 'selector'
[16:48:58] [gulp-tslint] error compiler/src/animation/animation_parser.ts[320, 7]: duplicate variable: 'limit'
[16:48:58] [gulp-tslint] error compiler/src/expression_parser/parser.ts[465, 15]: duplicate variable: 'result'
[16:49:00] [gulp-tslint] error examples/core/di/ts/forward_ref/forward_ref.ts[32, 5]: duplicate variable: 'ref'
```

**Comment by vicb** [comment]
@alexeagle do you have a PR for that ?

**Comment by alexeagle** [comment]
Sure I'll send one

**Comment by vicb** [comment]
fixed in #10048

**Pull request closed without merging**
