### PR TITLE
docs: fix minor typo in tutorial

### PR DESCRIPTION
**Pull request by nczempin**
"uses", the verb, not "users", the noun

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM! Thanks for the fix!

**Comment by jessicajaniuk** [comment]
@nczempin Can you fix the commit message? It looks like the PR header looks good, but the commit message needs a tweak yet. You should be able to `git commit --amend` to change the commit message and then force push.

**Comment by nczempin** [comment]
Yes, I will (fix the commit message) ;I was in the middle of fixing it and
got sidetracked.

**Comment by nczempin** [comment]
cleaned up the commit message, not sure if I need to do anything else

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit b36ec7a4333e47555cc0f9b06e9853f4c2f08401.

**Pull request closed without merging**
