### PR TITLE
WIP: feat(router): add router module

### PR DESCRIPTION
**Pull request by btford**
I am suspending work on porting the router directives to ng 2 for now to make sure that the new router is stable when ng 1.4 is released, but I wanted to open this PR as a placeholder. This PR will need more work (especially on getting it running in Dart) before it lands in this repo.

The current state of this code is that it compiles, but much of RouteRecognizer needs to be rewritten.

See [angular/router](github.com/angular/router) for the current router code that targets Angular 1.x.

### CODE REVIEW

**Comment by yjbanov** [comment]
Is this still suspended? When will this be ready for review?

**Comment by btford** [comment]
@yjbanov – yes. I'll have time to resume moving this code into this repo the week after next (the week of Fed 2nd). I'm ambitiously aiming for it to only take a week to get the ng2/dart bits working with the existing code, and then I'll update this PR.

**Comment by mhevery** [comment]
I am going to close this PR. Please reopen once ready.

**Comment by yjbanov** [comment]
Is there a corresponding issue for this?

**Comment by mhevery** [comment]
Tracking issue #618

**Pull request closed without merging**
