### PR TITLE
docs: html entity change &emdash; --> &mdash;

### PR DESCRIPTION
**Pull request by amar9312**
HTML entity &emdash; correct to &mdash; under Doc - title "Communicating with backend services using HTTP"

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by tphobe9312** [comment]
Dear all, any response on this PR?

**Comment by kapunahelewong** [comment]
Hi @tphobe9312! Good catch! Pardon the delay, as I was out for a bit. Would you mind removing the spaces from around either side of the em dashes? We are supposed to use them without spaces. Once you've done that just be sure that you [squash any additional commits that you make](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash). If you need any help with the process just tag me. Thank you!

**Comment by tphobe9312** [comment]
@kapunahelewong I have removed the spaces from around the em dashes. I need guidance in squashing the commit.

**Comment by kapunahelewong** [comment]
Great! To squash your commits, you can give this a try:

1. Make sure you're on your branch, `patch-2`.
2. Enter the command `git rebase -i HEAD~2` 
3. Your default editor will open with a list of your commits at the top. `pick` the one at the top and `fixup` (f) the rest in the list. This will squash the work of your second commit into the first one so that all of the work is just in that one commit.
4. Save and exit your editor. 
5. To double check you've done it right, do a `git log` or `git log --oneline` at the command line to see the commit log. Your fixed up commit should be no longer in the list and the one you picked should be the only one left of your commits on `patch-2`.
7. Do a `git push --force-with-lease`. To confirm it worked, check that there is only one commit listed on this page https://github.com/angular/angular/pull/38397/commits

If you have any issues with it, just let me know. I'm happy to do it from this end too. Thank you!!

**Comment by kapunahelewong** [comment]
I just noticed that you also need to rebase to pass CircleCI, which you could do before pushing up (step 6 above). CircleCI gives the following instructions on how to do it starting on `master` (so checkout master to do these steps):

```
         git fetch upstream master;
         git checkout patch-2;
         git rebase upstream/master; 
```

Alternatively, I also have notes on this: https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase

Again, if you would like me to do it from my end I can. Feel free to tag me. Thanks!

**Comment by gkalpak** [comment]
Here is an alternative (in case we don't hear back from @tphobe9312): #38665
@kapunahelewong, please also close #38662 and #38665 if this is merged (which would be totally fine by me).

**Comment by tphobe9312** [comment]
@kapunahelewong sorry for : 1. late reply, 2. I am not able to squash the commits. (I am not good at command line editing)

could you do it for me.

**Comment by aikidave** [comment]
Hey @tphobe9312! @kapunahelewong and I would be glad to try to help you with this PR; however, we have a number of other items that we're working on, so it may take a while before we can get to it. It may be faster for you to follow the steps that Kapunahele outlined. (I also find the [Beginner's guide to rebasing and squashing](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) helpful!) Thanks for your patience and understanding!

**Comment by sonukapoor** [comment]
> Hey @tphobe9312! @kapunahelewong and I would be glad to try to help you with this PR; however, we have a number of other items that we're working on, so it may take a while before we can get to it. It may be faster for you to follow the steps that Kapunahele outlined. (I also find the [Beginner's guide to rebasing and squashing](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) helpful!) Thanks for your patience and understanding!

The below squash video might be helpful as well:

https://twitter.com/stephenfluin/status/1009904095073718275?lang=en

**Comment by gkalpak** [comment]
The issue has been fixed by #38665.

**Pull request closed without merging**
