### PR TITLE
docs(docs-infra): refactor use of media queries

### PR DESCRIPTION
**Pull request by carlosasj**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Screen widths close to breakpoints sometimes presented the layout with a mixture of styles from 2 different "screen sizes" (small and medium, or tiny and small...).
This occur because there is many media queries with inline values.

Also, for screen widths smaller than 900px there was a horizontal scroll on the home page.

## What is the new behavior?
This pull request aims to provide a consistent and semantic way to use media queries to avoid strange behaviors close to breakpoints.

Also, changes some values to remove the horizontal scroll on the home page for small screens.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
There is 2 commits in this PR. The first one do the "obvious" work: it creates the mixins and apply them to media queries with values close to a breakpoint. The second one apply the mixins to media queries that are not so close to a breakpoint value, so I had to look for which screen size would be a better fit to the value inline.

### CODE REVIEW

**Comment by ajitsinghkaler** [comment]
@petebacondarwin @gkalpak  is this still required or is this still relevant

**Comment by petebacondarwin** [comment]
@carlosasj - did you want to continue to work on this? If not then @ajitsinghkaler should take it on

**Comment by ajitsinghkaler** [comment]
@petebacondarwin I'm taking over this one

**Comment by ajitsinghkaler** [comment]
@carlosasj if o are not taking this I'm taking over this one

**Comment by ajitsinghkaler** [comment]
@carlosasj if o are not taking this I'm taking over this one

@petebacondarwin I'm taking over this one if it is okay

**Comment by ajitsinghkaler** [comment]
@petebacondarwin should I start on this

**Comment by petebacondarwin** [comment]
Go for it @ajitsinghkaler !

**Comment by gkalpak** [comment]
Superceded by #36869.

**Pull request closed without merging**
