### PR TITLE
fix(forms): make setDisabledState optional for custom comps

### LINKED ISSUE #11719: ControlValueAccessor.setDisabledState is not reliably checked for presence before calling
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior** 

The `ControlValueAccessor` interface recently received a new optional method, `setDisabledState`. There are places in the form handling code that do not check if the `setDisabledState` method is present before invoking it.

https://github.com/angular/angular/blob/57cb82052bbe7bad452e8a3f28a63561254540eb/modules/%40angular/forms/src/directives/reactive_directives/form_control_directive.ts#L93

https://github.com/angular/angular/blob/dd8204a655161ad9c37a4e9c696240834a89fafe/modules/%40angular/forms/src/directives/reactive_directives/form_control_name.ts#L150

image

**Expected behavior**

Setting disables state should either always be checked, implemented in some base class or abstract way or have some function that things can call to encapsulate the optional call.

**Reproduction of the problem**

Set disabled on a form with components that do not implement `setDisabledState`

* **Angular version:** 2.0.0
* **Browser:** all
* **Language:** all

### PR DESCRIPTION
**Pull request by kara**
Closes #11719

r: @vsavkin

### CODE REVIEW

**Comment by zigzag95** [comment]
@kara 
When setting a formControl disabled, it don't appear in form.value

 setTimeout(() => {
      this.formTask = new FormGroup({
        id: new FormControl({ value: task.id, disabled: disabled }),
        guid: new FormControl({ value: task.guid, disabled: disabled }),
        activityId: new FormControl(task.activityId, Validators.required),
        **taskTypeId: new FormControl({
          value: task.taskTypeId,
          disabled: true
        }, Validators.required),**
        name: new FormControl({ value: task.name, disabled: disabled }),
        startDate: new FormControl({
          value: task.startDate,
          disabled: disabled
        }, Validators.required),
        endDate: new FormControl({ value: task.endDate, disabled: disabled }),
        resources: new FormControl({ value: task.taskResources, disabled: disabled })
      });
      this.formTask.valueChanges.subscribe(() => this.isModified = true);
    });,

**{{formTask.value | json}}**

{ "id": 3, "activityId": 5, "name": "IHM", "startDate": "2016-09-26T00:00:00.000Z", "endDate": "2017-09-26T00:00:00.000Z", "resources": [ { "id": 1, "resourceId": 1676, "startDate": "2016-09-26T14:52:18.780Z", "endDate": "2016-10-26T14:52:18.780Z", "load": 20.5 } ] }

**Comment by zigzag95** [comment]
Solved when using

form.getRawValue()

**Comment by kara** [comment]
@zigzag95 This is by design. Like in native HTML5 forms, disabled form controls are not included in aggregate form value. See more detail [here](https://docs.google.com/document/d/1k_iYcgTS1cDJkyXvBWQZGPlkWZhEqAVphC0xyKSAqPs/preview).

**Comment by zigzag95** [comment]
Very helpful
Thanks

**Pull request merged**
