### PR TITLE
refactor: remove extra line break in gulpfile

### PR DESCRIPTION
**Pull request by sarkiroka**
this is not an ascii art

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by filipesilva — APPROVED** [review]
@sarkiroka the changes LGTM but will need the CLA before merging.

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update git commit message to `refactor: remove extra line break in gulpfile`

**Comment by sarkiroka** [comment]
CLA ok, what is the next?

**Comment by sarkiroka** [comment]
I create new one: https://github.com/angular/angular/pull/29489
Can you check it?

**Comment by filipesilva** [comment]
Heya @sarkiroka, lets continue the conversation in #29489.

**Pull request closed without merging**
