### PR TITLE
build: update cross-repo angular dependencies

### PR DESCRIPTION
**Pull request by alan-agius4**
See associated pull request for more information.

Closes #57880 as a pr takeover

### CODE REVIEW

**Comment by alan-agius4** [comment]
**Caretaker Note:** Please disregard the lint failure. The issue stems from the license checker, which incorrectly parses multiple licenses.

**Review by thePunderWoman — APPROVED** [review]

**Review by alxhub — APPROVED** [review]
Reviewed-for: global-approvers

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: global-approvers

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 01fcbafa2ba5a3ea7dfd1567032be4699862e001.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
