### PR TITLE
build(aio): implement prerendering

### LINKED ISSUE #15104: aio: add prerendering support

### PR DESCRIPTION
**Pull request by gkalpak**
The current implementation is based on @igorminar's [angular-io-v42][1]. It is using Protractor to request all docs URLs, let them fallback to `/index.html` and save the rendered page.

Fixes #15104

[1]: https://github.com/IgorMinar/angular-io-v42/tree/05508ab3/tools/prerenderer

### CODE REVIEW

**Comment by gkalpak** [comment]
For the record, I also investigated using `@angular/platform-server` for prerendering but didn't manage to get far 😞 I am sure it is possible to make it work, but not in the given timeframe.

There are too many tools and interdependencies involved (angular, cli, tsc, ngc, tsickle, webpack). I tried different setups and combinations, but I was constantly running into some issue:

- cli  does not emit `.ngfactory.ts` files.
- ngc didn't like the cli-generated `tsconfig.json`'s sourcemap config.
- tsickle threw some "Unknown modifier" errors (probably due to some version mismatch).
- ...

##
For future reference, here are some relevant repos:
- https://github.com/robwormald/ng-universal-demo
- https://github.com/steveschmitt/toh-universal/blob/master/webpack.config.uni.js
- https://github.com/jeffbcross/prerender-example

---
We should definitely investigate this more in the future, when we have more time (probably post-4.0).

**Comment by gkalpak** [comment]
FYI: Added `/.sass-cache` to `aio/.gitignore` (as discussed in the meeting).

**Comment by IgorMinar** [comment]
I ran a few tests on this and there is a good news and a bad news:
- the good news is that the prerendering shaves off 3.3sec for mid-tear mobile devices
- the bad news are:
  - time to interactive with prerendering is prolonged by 3.6sec
  - there is a lot of flicker during the transition that we still need to deal with

I think that we should keep on heading in this direction, but keep on comparing the metrics with and without prerendering to get more insights of the real pros and cons of prerendering.

I have yet to do the code review, but wanted to measure this impact first. My results are based on the following test: https://www.webpagetest.org/video/compare.php?tests=170315_JH_14C%2C170315_MB_14D&thumbSize=200&ival=500&end=visual

**Comment by IgorMinar** [comment]
I think this is a good start, but it needs a lot of polish to remove the flicker that occurs during the transition from static html to the client-side constructed dom.

**Comment by IgorMinar** [comment]
I'm fine merging this in as is but please do the following as a follow up tasks:
- open up an issue(s) to track the flicker issues
- open up an issue to track the TTI hit
- open up an issue to add a loading indicator of some sort that disappears once the transition has completed
- send a PR with a readme file describing the architecture and how to locally develop features specific to the pre-rendering / transition (which tasks to run, how what's the development workflow, caveats)

**Review by IgorMinar — APPROVED** [review]

**Pull request merged**
