### PR TITLE
build(dev-infra): fix deprecated extension recommendation

### PR DESCRIPTION
**Pull request by DavidWeiss2**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Thare a link to a deprecated extention

## What is the new behavior?
There a link to the version of the extention

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
None

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by DavidWeiss2** [comment]
@josephperrott What is the next step for this one?

**Comment by DavidWeiss2** [comment]
Hi, @josephperrott I saw that this PR is still open. You know if this done on purpose?

**Comment by JeanMeche** [comment]
The PR is in conflict and also there is a CI failure on the linting job.

**Comment by DavidWeiss2** [comment]
No need for this PR. some other PR already fix the issue.

**Pull request closed without merging**
