### PR TITLE
feat(router): Allow `UrlTree` as an input to `routerLink`

### LINKED ISSUE #34468: feat(router-link): Accept UrlTree as input
# 🚀 feat(router-link): Accept UrlTree as input

### Relevant Package
This feature request is for @angular/router

### Description
Currently [`[routerLink]`](https://github.com/angular/angular/blob/master/packages/router/src/directives/router_link.ts#L142) directive accepts either an array of commands or a string. Since angular uses `UrlTree` as a model to store urls, it'd be great to extend this directive so that in addition it accepts a `UrlTree`.

### Describe the solution you'd like
Let `[routerLink]` input accept `commands: any[]|string|UrlTree`.

### Describe alternatives you've considered

* A different directive for this purpose. But having already a directive for that it'd be great to just extend the API.
* A pipe that converts a `UrlTree` into a string. The problem is that the params that a `UrlTree` might include should be extracted and put in their respective inputs. So that doesn't play nicely with all the features `UrlTree` have.

### PR DESCRIPTION
**Pull request by atscott**
This commit adds `UrlTree` as a valid input to `routerLink`. It disallows using this together with any inputs that come from `UrlCreationOptions`, such as `queryParams` or `fragment`.

We could, in the future, decide on a different approach for these, like merging or replacing those in `urlTree` input. We cannot, however, go the other way (decide to prevent those inputs if we've already decided to allow it and using a merging/replacing strategy). For this reason, an error seems the most reasonable approach to start and we can re-evaluate if there's a compelling reason to.

fixes #34468

### CODE REVIEW

**Comment by samuelfernandez** [comment]
This is great, thanks so much @atscott

**Review by thePunderWoman — APPROVED** [review]
reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by alxhub** [comment]
This PR was merged into the repository by commit a13f5da77303f4ab2f1543df1de1f416216b5a9c.

**Pull request closed without merging**
