### PR TITLE
docs(forms): fix typo in `toInteger()` function

### PR DESCRIPTION
**Pull request by rofrol**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@rofrol - thanks for this PR. Can you please update the commit message to follow our required format? See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

I would recommend simply:

```
docs(forms): fix typo in `toInteger()` function.
```

**Comment by AndrewKushnir** [comment]
@rofrol thanks for improving the docs!

I noticed that you've updated the PR description with a new title, but [the original commit](https://github.com/angular/angular/pull/44075/commits) still has the old message. Could you please update the commit message as well?

Thank you.

**Review by AndrewKushnir — APPROVED** [review]

**Comment by rofrol** [comment]
Updated commit message

**Comment by petebacondarwin** [comment]
I took the liberty of rebasing this on the current master in order to get the CI to run.

**Comment by petebacondarwin** [comment]
@AndrewKushnir - please can you disable the presubmit check.

**Pull request closed without merging**
