### PR TITLE
Documentation Change: Moved alert is-helpful to correct place

### PR DESCRIPTION
**Pull request by kperath**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

In wrong location: start-data.md
Issue Number: N/A

## What is the new behavior?
In correct location: start-routing.md

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by kpeara** [comment]
@googlebot I signed it!

**Review by IgorMinar — APPROVED** [review]
this looks good to me!! thanks for catching that we were providing the definition in the second and not the first occurance of the pipe in the tutorial.

can you please update this PR to follow our commit message guidelines (you'll have to squash the two commits into one and update the commit message, and then force push into this branch on github). Thanks! https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-a-pull-request-pr

**Comment by kpeara** [comment]
Happy to help! Cleaned up my commits and force pushed.

**Review by aikithoughts — APPROVED** [review]
LGTM!

Reviewed-for: global-docs-approvers

**Comment by kapunahelewong** [comment]
Hey, @kpeara could you rebase to help make CircleCI happy? Here are [my notes](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) on the process. Please tag me if you have any questions or would like a hand with it. Thank you!

**Comment by petebacondarwin** [comment]
This has already been addressed in a reworking of this guide by @kapunahelewong - see https://github.com/angular/angular/pull/39628

**Pull request closed without merging**
