### PR TITLE
refactor(core) Sharing components between modules.

### PR DESCRIPTION
**Pull request by eusen**
When I want to create components in different modules, Angular always throws exceptions. I think this method has great limitations. Since components can only be included in unique modules, there is no need for modules to be isolated from each other. Static variables enable components to be shared and can create components of other modules. I hope it can be passed. This is very important.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [v] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[v] Feature
```

## What is the current behavior?

Component of B module cannot be created in A module.
Issue Number: 1

## What is the new behavior?
Components can be shared in all modules.

## Does this PR introduce a breaking change?
```
[v] Yes
[ ] No
```

This small change allows us to implement previously impossible functions, such as when we want to create components of module A without importing module A. 

Specific scenarios: I want to use guards to control whether a new page should replace the current page, or pop up as a modal box using MatDialog. It is impossible to implement this function until it changes, and it will always report that it is not added to entryComponents. 

This change will solve a big problem. It is very important to cancel unnecessary isolation before the module.

## Other information
Please try and think about the benefits it brings!

### CODE REVIEW

**Comment by Eusen** [comment]
Please do not pass this pr. I got some error after this change. I'm sorry, but this idea is very useful, i will try again.

**Comment by Eusen** [comment]
image
image

this test error is wrong,
```
expect(() => nestedChildComp.cfr.resolveComponentFactory(NestedChildComp))
          .toThrow(noComponentFactoryError(NestedChildComp)); // It's should not throw anything.
```

**Comment by Eusen** [comment]
If not, please explain why. 
In the course of my testing, there were no errors due to this modification, so please clarify which part it would affect if not.

**Comment by Eusen** [comment]
Has anyone ever discussed this problem with me?

**Comment by Eusen** [comment]
@alxhub @vicb @petebacondarwin @mhevery hi there?

**Comment by thesayyn** [comment]
As I know ComponentFactoryResolver contains all the components that the application have so I do not agree that _factories variable should be static however we can make it public to be able to pass type checking when accessing _factories variable

I think making _factories accessible from anywhere on the application will break the injection tree, for instance;
let's say I have a Component like so

```
@Component({...})
export class MyComponent {
   constructor(@Self() @Inject(MY_COMP_CONF) myconf: any) {
       // This component only works with the config which is provided in its own module injector
   }
}
```
If you gonna create(inject) this component on a different module which has its own injector, the component couldn't be injected on a different module. (somebody should correct me if I'm wrong)

My workaround is: if you need a custom ComponentFactoryResolver you can provide it on main.ts

**Comment by Eusen** [comment]
@thesayyn I think Angular's system is too closed and loses a lot of flexibility and possibilities. Proper openness can bring more vitality to Angular.

**Comment by thesayyn** [comment]
@Eusen I agree with your point and also I'm taking advantage of your idea in my main project however it smells bad since it can cause to some problems like I pointed above so I'm just saying that dependency injection system of angular isn't ready for this feature (afaik).

**Comment by thesayyn** [comment]
i think core team will allow this feature in future when they complete ivy and tree-shakeable providers

**Comment by Eusen** [comment]
@thesayyn I'm also worried about some unforeseen problems, but my program has been working properly since it was modified. You can try to change the code in this part of @angular/core/fesm5/core.js into the following way:
1. seek out: `var CodegenComponentFactoryResolver `
2. modify:
`
function CodegenComponentFactoryResolver(factories, _parent, _ngModule) {
        this._parent = _parent;
        this._ngModule = _ngModule;
        this._self = CodegenComponentFactoryResolver;
        if (!this._self._factories) this._self._factories = new Map();
        for (var i = 0; i < factories.length; i++) {
            var factory = factories[i];
          this._self._factories.set(factory.componentType, factory);
        }
    }
    CodegenComponentFactoryResolver.prototype.resolveComponentFactory = function (component) {
        var factory = this._self._factories.get(component);
        if (!factory && this._parent) {
            factory = this._parent.resolveComponentFactory(component);
        }
        if (!factory) {
            throw noComponentFactoryError(component);
        }
        return new ComponentFactoryBoundToModule(factory, this._ngModule);
    };
`

**Pull request closed without merging**
