### PR TITLE
docs(docs-infra): move API members cards to the center of the page

### PR DESCRIPTION
**Pull request by hawkgs**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The API members cards are rendered on the right-hand side of the main page content.
Screenshot 2024-11-12 at 12 53 49

## What is the new behavior?

The members cards are moved below the header, i.e. they are now part of the main page content in the center. This should improve the UX by effectively using the available free space on the page and emphasizing the importance of the members descriptions.
Screenshot 2024-11-12 at 12 53 27

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by hawkgs** [comment]
I'll revert the PR to a draft since I noticed that I've broken the CLI reference details until I issue a fix.

**Comment by thesmiler** [comment]
Every page seems now to add a "Jump to details" at the bottom, which is not a link. Not sure where this is coming from 
Screenshot 2024-11-18 13 59 42

**Comment by hawkgs** [comment]
Got rid of it.

**Review by JeanMeche — CHANGES_REQUESTED** [review]
We probably should remove the click listener on the cards.
It us useless with the new layout

**Comment by hawkgs** [comment]
Removed. The cards are still focusable but they no longer have listeners. Clicking on a code line and auto-scrolling to its card is still there.

**Comment by Ahmed-Hakeem** [comment]
> Every page seems now to add a "Jump to details" at the bottom, which is not a link. Not sure where this is coming from Screenshot 2024-11-18 13 59 42

The problem is that this item and other items with class="cdk-visually-hidden" should be hidden.... we shouldn't remove these tags.

This was fixed by #58812

**Comment by hawkgs** [comment]
I guess we need it for screen readers? I overlooked that. Will revert the change. Strangely, I was not able to reproduce the issue on `main` last week.

**Comment by Ahmed-Hakeem** [comment]
> I guess we need it for screen readers? I overlooked that. Will revert the change. Strangely, I was not able to reproduce the issue on `main` last week.

Exactly, Elements with these classes are intended for screen readers

**Comment by hawkgs** [comment]
This PR is ready for review.

**Comment by JeanMeche** [comment]
The scrolling looks broken. 

ex: https://ng-dev-previews-fw--pr-angular-angular-58610-adev-prev-undk8pcw.web.app/api/router/Router#events

If you click on `events`, it scrolls down to the bottom of the page.

**Comment by Ahmed-Hakeem** [comment]
If it's final that you will change the cards to be in the bottom permanently ... I believe we will have the opportunity to remove all the resize observer stuff and start using the straight forward scrollIntoView way

It will add extra effort to change though but will save too much operations and we will get better performance

What do you think?

**Comment by hawkgs** [comment]
> The scrolling looks broken.

I am unable to reproduce it. Tried that on Chrome, Safari and Firefox. However, it seems that on my local setup I've closed the small "The state of JS survey" banner which is indeed covering the header section of the card when I tested the app from the demo link where the banner hasn't been closed yet:

Screenshot 2024-12-02 at 10 36 25

Maybe this is what you are experiencing? I can add some margin so the scroll stops above the target element.



> If it's final that you will change the cards to be in the bottom permanently ... I believe we will have the opportunity to remove all the resize observer stuff and start using the straight forward scrollIntoView way
>
> It will add extra effort to change though but will save too much operations and we will get better performance

I initially planned this as "as small as possible change". I agree that upon further look there is some redundant code which is no longer used and can be removed. And this is actually done in [the upcoming PR](https://github.com/hawkgs/angular/compare/docs/api-reference-details-move-params..docs/api-reference-details-drop-mat-tabs) which is an evolution of this one where the tabs are removed, the template of the API details page is pretty much reduced to a single `docs-viewer` instance and the respective scrolling services are cleaned from all of the redundant code. It is ready but it's blocked by this one.

**Comment by JeanMeche** [comment]
You're right the demo doesn't exihibit the issue anymore. Maybe I was hitting the cache.

**Comment by hawkgs** [comment]
@JeanMeche, I updated the scroll margin top functionality to include `100px` constant margin. Hopefully, this should take into account any banners that we have at the top of the page.

@Ahmed-Hakeem, given the margin top was related in some way to the `ResizeObserver` I dropped the redundant code from the service.

The change can be inspected in the last commit. I intentionally didn't squash it. Let me know, if there is anything else. If the PR is good to go, I will proceed with the squashing.

**Review by mgechev — APPROVED** [review]

**Review by JeanMeche — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 922ffdb40e5d3e19ae451a21e9ac9bea86fbef20.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
