### PR TITLE
docs: remove confusing word in di providers doc

### PR DESCRIPTION
**Pull request by kabrunko-dev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM, thanks

**Comment by kabrunko-dev** [comment]
> LGTM, thanks

Thank you!

**Comment by pkozlowski-opensource** [comment]
@kabrunko-dev you've got 2 merge commits in your PR, can you remove those?

**Comment by kabrunko-dev** [comment]
> @kabrunko-dev you've got 2 merge commits in your PR, can you remove those?

Oh! Sure hahaha

**Pull request closed without merging**
