### PR TITLE
docs: unified console.log single string style

### PR DESCRIPTION
**Pull request by danielsogl**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

```ts
console.log(`Im a string without a variable`);
```

## What is the new behavior?
```ts
console.log('Im a string without a variable');
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by brandonroberts** [comment]
@danielsogl will you rebase on master and remove `(aio)` from the git commit message?

**Comment by danielsogl** [comment]
@brandonroberts Done

**Comment by brandonroberts** [comment]
@danielsogl You must remove the entire scope, so its just `docs: ...`

**Comment by danielsogl** [comment]
@brandonroberts fixed

**Review by brandonroberts — APPROVED** [review]

**Pull request closed without merging**
