### PR TITLE
docs: making footer copyright year dynamic

### PR DESCRIPTION
**Pull request by red1code**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Angular documentation website's footer copyright year is hard coded, so it shows the following `Super-powered by Google ©2010-2022`, but we are in 2023, so the years need to be `2010-2023`

Issue Number: #48811

## What is the new behavior?
Now the footer will display the current copyright year dynamically, it will change every new year dynamically.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by red1code** [comment]
Hi @jessicajaniuk 
I just wanna tell you that this PR won't take 5 min of your time, and I think it is important because the year in footer docs website is 2022, and should be updated.
regards.

**Comment by jessicajaniuk** [comment]
@red1code Thanks. Our tooling had someone else pinged for review on this, but I can take a look.

**Comment by jessicajaniuk** [comment]
@red1code Can you clean up the commit message? CI is failing on lint right now. I think if you update it to what you used for the PR header, that should address it.

**Review by jessicajaniuk — APPROVED** [review]
LGTM . Once the lint is fixed, It can be merged.

**Comment by red1code** [comment]
> @red1code Can you clean up the commit message? CI is failing on lint right now. I think if you update it to what you used for the PR header, that should address it.

I think it's done :heavy_check_mark:

**Review by jessicajaniuk — APPROVED** [review]

**Review by jessicajaniuk — APPROVED** [review]

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 3a9bbada5d4ffb0d5b4d75c86a40cdf74b54af06.

**Pull request closed without merging**
