### PR TITLE
docs(router): paramMap.get could be null

### PR DESCRIPTION
**Pull request by antonellopasella**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
Thanks for improving Angular docs!

**Comment by AndrewKushnir** [comment]
Caretaker note: no presubmit required, docs-only change.

**Comment by pkozlowski-opensource** [comment]
Actually, I think that this change is misleading. While it is true that `route.paramMap.get('id')` can be null, adding `!` doesn't "fix" the problem. One should either:
* check for `null` (or other invalid values) in a resolver, or
* make sure that `service.getHero` can handle "invalid" values

Obviously API docs can't have complete examples so I think that what we've got right now is fit for the purpose.

@antonellopasella  thnx for the PR, but I would rather leave this one as-is.

**Comment by antonellopasella** [comment]
> Obviously API docs can't have complete examples so I think that what we've got right now is fit for the purpose.

My point is that the code is wrong and the reader will got an error in his IDE.
IMHO tutorial would be "error free" when copy/pasting the code.

Clearly is a "typescript issue" non "angular issue" because the get() can return string | null (correctly).
But in the tutorial I'm expected to learn without distractions or non working code.

Thanks for the great work, in any case :-)

**Pull request closed without merging**
