### PR TITLE
docs: template files should have .html extension Fixes a typo in the …

### PR DESCRIPTION
**Pull request by Krishnabisht07**
…component guide

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Oh! So close! Unfortunately the commit message all went on to a single line.

I am wondering whether you have been using the Github web UI to create these PRs. Is that correct?
If so then you will not be able to fix these commits in that UI, and I can do it for you.

Let me know.

**Comment by Krishnabisht07** [comment]
> Oh! So close! Unfortunately the commit message all went on to a single line.
> 
> I am wondering whether you have been using the Github web UI to create these PRs. Is that correct?
> If so then you will not be able to fix these commits in that UI, and I can do it for you.
> 
> Let me know.

Yes I used Github web UI to create this PR. Now what should I do?

**Comment by petebacondarwin** [comment]
I will pull down your branch and fix it up for you.

For future reference, do you understand how the commit messages should be formatted?
Here is a detailed description: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Pull request closed without merging**
