### PR TITLE
fix(compiler-cli): Emit type annotations for synthesized decorator fi…

### PR DESCRIPTION
**Pull request by nreid260**
…elds

Previously, the decorator transformer was annotating the synthesized properties with TS type annotations. However, because it ran after the JSDoc transformer, the TS types were just dropped from the emitted JS. Attempting to move the decorator transformer before the JSDoc transformer causes tsickle crashes because synthetic AST fragments are not attached to a SourceFile node.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by blickly — COMMENTED** [review]
@mprobst, hey Martin, do you know who would be an appropriate person to review this CL?  This is currently on the critical path to improving checking of TypeScript libraries as a whole

**Comment by mprobst** [comment]
@blickly I believe this has landed internally and we need to figure out why the sync is stuck.

**Comment by mprobst** [comment]
@mprobst nope, I mixed this up with the tsickle change. Nevermind.

**Comment by alxhub** [comment]
Also adding @clydin as I think this transform is used by the CLI as well.

**Review by alxhub — APPROVED** [review]

**Review by clydin — APPROVED** [review]

**Comment by nreid260** [comment]
These failures look like TAP noise.

**Pull request closed without merging**
