### PR TITLE
docs(aio): change wording on rollup plugins

### PR DESCRIPTION
**Pull request by janpio**
Change wording so the description is explicit that the changes are already in the configuration and no additional work by the reader is required.

### CODE REVIEW

**Review by IgorMinar — CHANGES_REQUESTED** [review]
The changes you made use passive voice, which is something we are trying to avoid. Can you please reword the changes using active voice? For example "The following had to be added..." would become "We added the following to"

**Comment by piotrowski** [comment]
Sure.

I actually wasn't sure if you want the "we" - but didn't think that maybe passive voice would be the bigger problem ;)

**Comment by wardbell** [comment]
Sorry to jerk you around on this, but I'd rather that you remove both statements and the example code!

There is no need to tell the reader what is in the configuration. We didn't do that for any of the other configuration items; we shouldn't do so now.

As for "We" and passive voice, you should avoid **both** of them. 

We appreciate your help in clarifying this section. Happy to move it along after you've cleaned this up.

**Comment by janpio** [comment]
Oh, I am all good with removing these completely - they felt out of place but what made it worse for me, trying to learn things, was that it just wasn't correct the way it was worded. 

But I think removing these paragraphs should be done in another PR then from someone who has more insight into how the docs should be.

(On the other side: It has been >10 days now where the docs could have been better than they are right now)

**Comment by janpio** [comment]
(Updated my CLI for changed Github name: I signed it!)

**Comment by wardbell** [comment]
I'm asking someone to confirm your claim. Once confirmed, we'll delete the sentences. Thanks.

**Comment by wardbell** [comment]
OK .. I checked with the page author. **You, the developer, must add those plugins!** There are not part of rollup configuration by default.  Your statement is incorrect (he says):

>the changes are already in the configuration and no additional work by the reader is required.

Perhaps you are confused by fact that he _shows_ you what the config looks like after adding those plugins? This guide is written in tutorial style.

**Comment by thelgevold** [comment]
Yes, here is a bit more information about why you need to add these plugins:

In order to benefit from "Tree shaking", we are  transpiling the application code code to ESM (ES5 JavaScript + ES2015 modules). 

However there is one issue. RxJs is published as commonJS, which isn't directly compatible with ES2015. To get around this we add the commonJS plugin to make a conversion from commonJS to ES2015 via Rollup.

The Uglify plugin is technically optional, but if you don't add it, your bundle will not be minfied. This is obviously bad for performance.

Point is, you don't get these plugins for "free", or by default. 

You as the developer has to specify the config, and add the plugins.

**Comment by janpio** [comment]
I, the developer already added these lines in the previous paragraph: In https://angular.io/guide/aot-compiler#rollup I, the developer following the tutorial, create a `rollup-config.js` that already includes these plugin. If you tell me to add these lines in the next paragraph I am confused and will be wondering if I did something wrong.

**Pull request closed without merging**
