### PR TITLE
Refactor ReflectionCapabilities to rely on metadata for identifying 'pass-through' constructors

### PR DESCRIPTION
**Pull request by deadalusai**
Refactor `ReflectionCapabilities` to rely on metadata for identifying 'pass-through' constructors

- avoid the regex check whenever possible
- generate default metadata only after we've checked all parent constructors

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

This is an effort to improve the way `ReflectionCapabilities` determines if a constructor function is a "pass-through" or implicit constructor and decide when we should take constructor parameters from the parent type.

For example:

```typescript
class Foo extends Base {
}
```

...will generate a `Foo` constructor like:

```javascript
function Foo () {
    __super.apply(this, arguments);
}
```

The current implementation works by running a regular expression against the generated javascript code to guess whether the function calls the super constructor in the manner above. The current regex *does not work* if the generated code is a little more complicated, like:

```javascript
function FooComponent () {
    __super.apply(this, __tslib.__spread(arguments));
}
```

## What is the new behavior?

Rather than try to make this regex cover all possible permutations of this pattern, can we instead determine if a constructor is implicit by inspecting metadata alone?

This change relies on the following:

- `tsc` does not emit `design:paramtypes` metadata for types with implicit constructors
- this change to `tsickle` ensures the same for tsickle code: https://github.com/angular/tsickle/pull/760

If a constructor function does not provide constructor parameter metadata and reports no explicit arguments, then we attempt to inherit constructor parameters from the parent type.

## Does this PR introduce a breaking change?
```
[X] Yes
[ ] No
```

## Other information

**Edit:** I have a work around for this issue described here in the form of the `_isInjectable` check, which tries to determine if a type has been prepared for injection in *some* way before trying to determine the parameter list.

This change works for all code currently in the `./test.sh node` test suite, though it may be working "accidentally" for some types. This is because it **does not** work correctly with the following pattern:

```typescript
@Injectable()
class BaseClass {
    constructor (public data: string) {
    }
}

// NOTE: no attribute to trigger metadata generation
class Foo extends BaseClass {
    constructor () {
        super('hello');
    }
}
```

Specifically, attempting to inject a non-attributed class which inherits from an attributed class.

Because the class `Foo` does not have any attributes, it does not get any constructor metadata and so looks like it could be a "pass-through" constructor. The super class *does* have constructor metadata,
so the routine incorrectly uses that parameter list.

`Foo` is technically incorrectly declared - it should have the `@Injectable()` attribute, however because it does not we determine that the parameter set for `Foo` is `[string]` and the code eventually fails with the following unhelpful error:

```
NullInjectorError: No provider for String!
```

### CODE REVIEW

**Comment by deadalusai** [comment]
I've made some changes to try and work around the edge case described above - specifically I've added the `_isInjectable` check, which tries to determine if a type has been prepared for injection in some way before trying to determine the parameter list.

It does this by checking that the type constructor...

- has es5 `attributes`/`parameters` properties, or
- has `tsickle` properties, or
- has been marked up with an Angular attribute (`@Injectable`, `@Component` etc)

Only one change to the tests had to be made to mark up a test subclass with an `@ClassDecorator` attribute (simulating `@Injectable`).

**Comment by deadalusai** [comment]
Because fixing the problem here is non-trivial I've also opened an issue on ng-packagr around its codegen: https://github.com/dherges/ng-packagr/issues/679

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
@deadalusai Thanks for the fix. Can you force the ci/circleci to re-run, I think it may be flake. 

I think this can be merged after v6.0.0 is out.

**Comment by trotyl** [comment]
Also closes https://github.com/angular/angular/issues/13211

**Comment by deadalusai** [comment]
@trotyl @mhevery do you consider this PR still relevant and viable? I no longer have an environment available to easily re-test this code with the latest master, but I'm willing to build out an environment if need be.

**Comment by deadalusai** [comment]
Closing as abandoned

**Pull request closed without merging**
