### PR TITLE
feat(dart/transform): Generate all code into <file>.template.dart

### PR DESCRIPTION
**Pull request by kegluneq**
/cc @yjbanov

Previously, we generated the code to initialize the reflector into the
<file>.ng_deps.dart and the compiled template and change detector code
into <file>.template.dart.

Update the transformer to generate all code into <file>.template.dart to
avoid the additional HTTP requests necessary when debugging
applications in Dartium.

### CODE REVIEW

**Comment by yjbanov** [comment]
This is a great change. I'm wondering if `template` is a good infix for the file name given that:

- it may actually _not_ contains any template code (e.g. injectables and directives)
- it is angular-specific and yet does not reflect that

How about `.ng.dart` or `.ng2.dart`?

**Comment by kegluneq** [comment]
/cc @tbosch 
Totally agreed on the naming, however because the .template.dart files reference each other, this will require updating the Template Compiler, which Tobias was hesitant to do right now.

Can we take renaming the output as a separate TODO? At the same time we do it, perhaps we can unify the naming code that is currently duplicated in the transformer & the template compiler.

**Comment by yjbanov** [comment]
SGTM. Let's file an issue to follow-up.

**Comment by kegluneq** [comment]
Spun of https://github.com/angular/angular/issues/6712

**Pull request closed without merging**
