### PR TITLE
API doc and examples: Route interface, Router NgModule

### PR DESCRIPTION
**Pull request by jbogarthyde**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by jenniferfell** [comment]
@brandonroberts @jbogarthyde : Hi. Would you two connect and recommend how to get this closed? Either Brandon submitting updates or comments against this PR, or Brandon opening a new PR? Thanks!

**Comment by jenniferfell** [comment]
Internal link: https://angular-team.atlassian.net/browse/DOCS-186

**Comment by jenniferfell** [comment]
According to API status spreadsheet, this includes: 
* RouterModule |   | class
* UrlSegment |   | class
* UrlSegmentGroup |   | class
* ROUTES |   | const
* Route |   | interface
* Routes |   | type alias
* LoadChildren |   | type alias
* LoadChildrenCallback |   | type alias
* ResolveData |   | type alias
* RunGuardsAndResolvers |   | type alias
* UrlMatcher |   | type alias
* UrlMatchResult |   | type alias

**Comment by jenniferfell** [comment]
Internal links:
https://angular-team.atlassian.net/browse/DOCS-124
https://angular-team.atlassian.net/browse/DOCS-125
https://angular-team.atlassian.net/browse/DOCS-126

**Comment by brandonroberts** [comment]
I've made a new branch to include these changes, and will open a new PR.

**Comment by jenniferfell** [comment]
Work moving to new PR. Closing

**Pull request closed without merging**
