### PR TITLE
Make path lowerable

### PR DESCRIPTION
**Pull request by vsavkin**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 19336

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Review by jasonaden — APPROVED** [review]

**Review by jasonaden — CHANGES_REQUESTED** [review]
Talked to @chuckjaz about this. It looks like the `ngc_spec.ts` modification will likely work even without this change in place. Let's remove the change in `lower_expressions.ts` to validate the tests still pass.

The route config is expressed as `useValue`, which is already going to be lowered, therefore we don't need to lower anything inside it.

If that doesn't work, a conversation should be had with @chuckjaz as there are more changes that would be needed.

**Comment by vsavkin** [comment]
The test fails for the following reason:

In that test lowering happens twice. The first time `data` is lowered, and the second time `useValue` is lowered. Since it happens twice, `calculateString` (in the test) doesn't have to be exported. If I add `path: calculateString()`, I'll have to export this function.

If we look at LOWERABLE_FIELD_NAMES, we see this:

```
const LOWERABLE_FIELD_NAMES = new Set(['useValue', 'useFactory', 'data']);
```

Having `data` in that set causes this behavior.

I think to make it consistent we either need to have both `path` and `data` there, or neither. And I actually would prefer neither.  What do you think?

**Comment by chuckjaz** [comment]
I am confused about what you are trying to fix. Can you explain the motivation for this change?

BTW, you might be running into issues that I am fixing for #18170.

**Comment by vsavkin** [comment]
Talked to Chuck. It's a minor thing, not worth fixing.

**Pull request closed without merging**
