### PR TITLE
refactor: remove unused imports

### PR DESCRIPTION
**Pull request by aanchal88**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
**Caretaker note**: low risk change, the CI and presubmit are "green", so we can proceed with merging this change.

**Comment by aanchal88** [comment]
Hii @pkozlowski-opensource , updated the commit message, please review.

**Comment by aanchal88** [comment]
Hii @pkozlowski-opensource , please merge the PR.

**Comment by JeanMeche** [comment]
Your commit message still doesn't follow the guidelines. Please see https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit

**Comment by aanchal88** [comment]
Hii @JeanMeche , I make the commit message as suggested by @pkozlowski-opensource to start with "refactor".
Can you please suggest what else needs to update for the commit message, it would be helpful for me.

**Comment by alxhub** [comment]
@aanchal88 thank you for the cleanup PR, it's appreciated! Please do fix up the commit message to pass the lint check and we can get this merged.

I would also suggest not using the term "code smell" in the commit message. A code smell is an easily noticed property of the code which hints at a deeper problem. Unused imports are not symptoms of a deeper problem, just cleanup from prior refactorings that was missed.

**Review by alxhub — CHANGES_REQUESTED** [review]
^ see above

**Comment by aanchal88** [comment]
Hii @pkozlowski-opensource , CI is succeded now. Please have a look.

**Comment by aanchal88** [comment]
Hii @alxhub , please review the PR.
Thanks

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Pull request closed without merging**
