### PR TITLE
Add spec argument to the config

### PR DESCRIPTION
**Pull request by Zizzamia**
Allows to run a list of module test/perf.
Hi @tbosch, to run separate test/perf I found very useful have a command line argument to choose only the list of files I want run the test/perf.

Also can I ask if Benchpress will be an independent tool (so possible to installing by npm) before the ng-conf?

ThankYou

### CODE REVIEW

**Comment by tbosch** [comment]
Will look into it today. And yes, we will release benchpress before
Ng-conf. We are also doing a talk about it. Do you have time to sync up so
out two talks are a good combination?

**Comment by Zizzamia** [comment]
Yes I would love that. Can you set a google hangout? 
So I can show you an highlight of my talk.
#ThankYou

**Comment by tbosch** [comment]
Hi,
I changes some stuff around and will land the change with #757.

**Comment by Zizzamia** [comment]
#Awesome thank you!

**Pull request closed without merging**
