### PR TITLE
feat(router): Add UrlTree constructor to public API

### PR DESCRIPTION
**Pull request by atscott**
The `UrlTree` is a fundamental concept in the router's API design.
Generally speaking, a `UrlTree` would be constructed via things like
`Router.createUrlTree` or `UrlSerializer#parse`. The second example here
is the core reason to make the constructor public, regardless of how
develpers generally create a `UrlTree` in an application.

Applications can provide their own `UrlSerializer` and may want to implement their
own `parse` method. This means they would also need to create a
`UrlTree` but would not be able to do so effectively because the
constructor is marked `@internal`.

In addition, the `UrlTree` constructor only has 3 parameters, all of
which are already public. There's nothing "special" about it other than
the potential desire to push developers to use other methods for
constructing a `UrlTree` (i.e. `Router.createUrlTree`).

Also see http://b/234604699#comment9 for additional context.

### CODE REVIEW

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by atscott** [comment]
[TGP](https://fusion2.corp.google.com/presubmit/tap/468488945/OCL:468488945:BASE:468541077:1660856338887:b7e579cc/targets)

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 5163e3d876cdfd6d309d7e35aefa6f07ef62715e.

**Pull request closed without merging**
