### PR TITLE
chore(changelog): Fixed broken changelog

### PR DESCRIPTION
**Pull request by 0x-r4bbit**

### CODE REVIEW

**Comment by PascalPrecht** [comment]
@googlebot it's alright.

/cc @ericmartinezr

**Comment by ericmartinezr** [comment]
It's all ok ;)

**Comment by tzi** [comment]
+1
Would be great to merge it to help people migrating from alpha 35 to alpha 36 ;)

**Comment by ericmartinezr** [comment]
@PascalPrecht You can close this PR, the duplicate removal was merged already from another user and the changelog changed again because of .37. 

Thanks for your help :+1:

**Pull request closed without merging**
