### PR TITLE
docs: Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by andriy101**
Fixing typo: reactoring -> refactoring

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by andriy101** [comment]
could anybody please help me with FAILED CLA, I made all required steps:

image

**Comment by JeanMeche** [comment]
You're fine, the CLA is green, it can take a bit of time to be up-to-date in the checks. !

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by thePunderWoman** [comment]
@andriy101 Can you fix your commit message to match our lint rules? Once you do that, we should be able to merge. Thanks!

**Comment by andriy101** [comment]
Do I need to to something regarding this:
image
?

**Comment by andriy101** [comment]
What should I do about **_Pending - Forbidden labels detected: action : cleanup_** workflow? What is blocking this merge?

**Comment by JeanMeche** [comment]
That was an action on our side to add the PR to the merge queue.

**Comment by andriy101** [comment]
Is there anything else blocking this PR from being merged? Do I need to take any action?

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 75266874957c9a24ab391cb3463ef29e530dd081.

The changes were merged into the following branches: main

**Pull request closed without merging**
