### PR TITLE
docs(docs-infra): extract captured group from heading custom id regexp

### PR DESCRIPTION
**Pull request by JeanMeche**
Backport of angular/dev-infra#2202

cc @lacolaco

### CODE REVIEW

**Comment by lacolaco** [comment]
@JeanMeche Thank you! I think `heading.spec.ts` should also be updated to ensure that custom heading extraction works as expected.
https://github.com/angular/angular/blob/main/adev/shared-docs/pipeline/guides/testing/heading/heading.spec.ts#L75-L84

**Comment by JeanMeche** [comment]
Good catch, thank you.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit a49f7c951f9bb6900f598c5ec69ccca798de067d.

The changes were merged into the following branches: main, 18.1.x

**Pull request closed without merging**
