### PR TITLE
Remove es6 promise

### PR DESCRIPTION
**Pull request by IgorMinar**
- **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  drop obsolete es6-promise dependency
## \* **What is the new behavior (if this is a feature change)?**
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
  not really. projects that already require es6-promise polyfill will now contain unnecessary dependency which should be removed if only everygreen browsers are targeted by the app.
- **Other information**:

### CODE REVIEW

**Comment by IgorMinar** [comment]
// @wardbell - fyi

**Comment by wardbell** [comment]
To be clear, is the shim still required for older supported browsers e.g.  IE10 and IE11? I'm not sure which browsers you're including in "evergreen browsers"

**Comment by IgorMinar** [comment]
My understanding is that edge is the only evergreen browser from MS.

MDN concurs
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by e-oz** [comment]
@wardbell I share your opinion that majority of apps will have to support IE1, but it will be easy and more fair (and explicit) for them to add es6-shim to app dependencies, without having it as default dependency.  And small subset of apps, which don't have to support IE11 (mobile apps, for example), will have benefit of it. "Pay for what you use" :)

**Comment by IgorMinar** [comment]
CI is green.

**Comment by filipesilva** [comment]
It comes down to what is said [here](https://angular.io/features.html):

> LEGACY BROWSER SUPPORT
> 
> In addition to fully supporting latest versions of Chrome, Edge, Firefox, IE, and Safari, Angular 2 is also tested for older browsers including IE9+ and Android 4.1+.

If we put a warning about it somewhere, that this shim is only needed on those platforms, I think it's reasonable enough to remove it from the angular peer deps.

But it would be expected that in any best practices document the shim is listed, for without it apps would not work on one browser and one mobile platform.

It's also worth noting that component libraries should care nothing for this shim. Maybe not even for other shims.

**Comment by mhevery** [comment]
New zones will polyfill Promises regardless if they are in the browser, so removing the polyfill here is the right thing, and it will have no impact on any legacy browsers.

**Pull request closed without merging**
