### PR TITLE
docs: add TypeScript team members to aio

### PR DESCRIPTION
**Pull request by alexeagle**
/cc @evmar @LucasSloan @bowenni 
Igor says you should be listed here as part of Angular team. Will appear on angular.io/about
Evan and Bowen, do you want photos included?

### CODE REVIEW

**Comment by StephenFluin** [comment]
I don't think we have any other team members without photos. Is it a problem to include photos for everyone?

**Comment by alexeagle** [comment]
Evan is on leave, and I don't have a photo for him.

**Comment by evmar** [comment]
I'm fine without a photo.

**Comment by IgorMinar** [comment]
Obsolete. Closing.

**Pull request closed without merging**
