### PR TITLE
Router lazy loading sample

### PR DESCRIPTION
**Pull request by vsavkin**
Look at the last commit.

### CODE REVIEW

**Comment by mhevery** [comment]
thanks this looks good

**Comment by mprobst** [comment]
@vsavkin could you rebase?

**Comment by mhevery** [comment]
Obsolete

**Comment by trongthanh** [comment]
Although this ticket is closed but since it's commonly referred to, can I ask about loading of un-compiled components?

In the sample, the string at `component` property is a compiled JS file. I'd like to know if it's possible to declare a normal SystemJS module path which is a TypeScript file and leverage runtime compilation? Currently I'm getting errors when trying to lazy load a TypeScript module. (I'm still need to isolate the case and investigate more but would like to quick check on the possibility first).

Thanks.

**Comment by trongthanh** [comment]
Never mind. I can confirm that lazy loading of TypeScript files works.

My issue was that my component doesn't have default export, so I have to explicitly append the Component name after a hash `#` in the component path, i.e. `app/components/AboutUs#AboutUs`. This is not obvious until I trace through the source code.

**Pull request closed without merging**
