### PR TITLE
docs(aio): fix jade leftover from toh5

### LINKED ISSUE #16032: docs(aio): toh-pt5 does not show file content
In [part 5 of the tour of heroes tutorial](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html) there is code listing that is not shown correctly.
This listing is found at the subtitle 'Update AppModule' as you can see here:

screenshot from 2017-04-16 12-58-39

I think it should show some code listings similar to this:

screenshot from 2017-04-16 12-59-08

### PR DESCRIPTION
**Pull request by Foxandxss**
Fixes #16032

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]

**Comment by marcelocra** [comment]
Hey there!

I've been going through the documentation and this is the second issue that I find that has been fixed but is still showing up in angular.io. The other one is #16398.

I couldn't find **instructions on how to generate a release version of the docs** in the angular/aio package. Could you folks help me?

Thanks!

**Comment by Foxandxss** [comment]
@marcelocra we need to release the site, so all the issues that have been fixed are not up yet.

Don't worry, we are going to release it very soon.

**Comment by marcelocra** [comment]
Thanks! One question: is there a release process with a defined cycle that you folks go through or it depends on how many people are available?

**Comment by Foxandxss** [comment]
We have a written release schedule somewhere, I don't remember where now :/

**Comment by marcelocra** [comment]
Ok then, no problem! I'll search around :)

**Comment by gkalpak** [comment]
The release schedule is [here][1].

[1]: https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md

**Pull request merged**
