### PR TITLE
fix(router): routerLink remove tabindex attribute

### LINKED ISSUE #28345: routerLink directive always makes element focusable
# 🐞 bug report

### Affected Package
@angular/router

### Description

Issue https://github.com/angular/angular/issues/10895 requests that the `routerLink`-directive should automatically add `tabindex` on the target element if not already present (implemented via https://github.com/angular/angular/pull/13094).

I understand that this behavior might be convinient in some cases, but it should still be configurable.

For example, in order to implement a custom menu widget it's a good practice that the focus always stays on the surrounding element (e.g. `<nav>`) while the user selects the target menu item with the arrow keys (see demo for Kendo Angular Menu at https://www.telerik.com/kendo-angular-ui/components/menus/menu/keyboard-navigation/ for example).

Right now, implementing this in a clean and straight-forward way is not possible due to the feature implemented in the issue above. If `<a>` is used for the menu entries, the `href` injected by `routeLink` makes it focusable and even if `<span>` is used instead, `routeLink` still injects a `tabindex=0` to always make it focusable.
When the user then clicks on a link the surrounding `<nav>` element looses its focus as focus moves to the link that has been clicked instead. Even setting `tabindex=-1` only prevents tabbing to the link but still allows focus via mouse click.

There should either be a configuration parameter to prevent setting of `tabindex` or the feature should be reverted as `tabindex` can always be configured manually if necessary.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-qudebd

```html
<nav tabindex="0">
  <ol>
    <li>
      <!-- becomes focusable because of href attribute -->
      <a routerLink="bikes" routerLinkActive="active">Bikes</a>
    </li>
    <li>
      <!-- becomes focusable because of tabindex attribute -->
      <span routerLink="cars" routerLinkActive="active">Cars</span>
    </li>
  </ol>
</nav>
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 6.2.9
Node: 8.11.3
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.16.4
</code></pre>

**Anything else relevant?**

This can be reproduced as described in Chrome v71.0.3578.98.
In Safari the focus is only lost on the second link (i.e. where `<span>` is used).

### PR DESCRIPTION
**Pull request by alan-mroczek**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently, `routerLink` directive adds `tabindex` attribute if not set.
That behavior blocks users from creating their own widgets with custom
focus managing via ARIA attributes, because there is no way to unset
that attribute. It has also been stated that it's not `routerLink`
resposibility to make app more accesible and it also caused some problems
because it wasn't obvious to everyone why elements are focusable (#10895).

Issue Number: #28345

## What is the new behavior?

With an approach proposed by this PR `tabindex` can (and in many cases should) be still set manually.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

BREAKING CHANGE: Previously `tabindex` has been set for any element
that had `routerLink` directive applied. Change in this PR can introduce
situation when previously reachable elements with a keyboard won't be
focusable anymore unless explicitly set with `tabindex="0"`.

## Other information

PR Close #28345

### CODE REVIEW

**Review by jasonaden — CHANGES_REQUESTED** [review]
Thank you for the PR. I like the idea of adding a way to change the `tabIndex` behavior. However, I wouldn't want to introduce this as a breaking change.

I think there are a few options here. One would be to add this as a configuration option to `RouterModule.forRoot` config. Another option would be to change the constructor logic such that `undefined` and `null` are treated differently.

If `null` were passed, we could remove any `tabindex` attribute, and if `undefined` were passed we could treat it the same as the current logic.

**Comment by jasonaden** [comment]
@alan-mroczek One thing to note is that the MDN link you provided above is to `getAttribute`, whereas we would be accessing properties. So the actual doc we would be looking for is https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/tabIndex.

Thinking about this a bit, is there a scenario where we *don't* want a `routerLink` to be focusable? I get it on changing the tabbing behavior, but what about using `-1` to just make it focusable but not allow tabbing to it? See [this doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) on tabindex.

**Comment by alan-mroczek** [comment]
@jasonaden this is exactly first question that I've asked in linked isssue as it seemed to me really confusing (#28345)!

Me:
> Why would you put `routerLink` directive on something that needs to be non-focusable?

Link to [answer](https://github.com/angular/angular/issues/28345#issuecomment-458443259), so you don't have to read everything.

The general reasoning behind that kind of feature was to create custom widgets, for example select field where whole select should be focusable, but not individual elements (https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_build_custom_form_widgets and especially "Make it accessible" section) - therefore individual elements shouldn't be focusable, so we won't lose focus on our widget. After applying tabindex by angular it can't be adjusted again to make element non-focusable without some fancy workarounds.

I posted MDN link to `getAttribute` because right now `tabindex` is being retrieved using `@Attribute` decorator, but I haven't thought that in order to allow user code to bind to this, it should be a property - so you're right, and passing `null` should be perfectly fine.

If you have still some other thoughts feel free to share them. I'm not telling that we **must** implement that, and if you decide that we won't benefit enough, we can close this PR, but we also would need to tell people that this it's something that we won't fix (even though it's a simple change). In a meanwhile I'll take a look at passing `null` via property binding instead of reading an attribute.

**Comment by trotyl** [comment]
> In a meanwhile I'll take a look at passing `null` via property binding instead of reading an attribute and post an update to my PR.

I think this is a more reasonable approach, to make this change non-breaking, it can first be made a `@Input()` property and keep the default behavior, but allows passing `null` to prevent the behavior. Then the default value of that `@Input()` can be reconsidered in some later version.

**Comment by nuts-n-bits** [comment]
> Thank you for the PR. I like the idea of adding a way to change the `tabIndex` behavior. However, I wouldn't want to introduce this as a breaking change.
> 
> I think there are a few options here. One would be to add this as a configuration option to `RouterModule.forRoot` config. Another option would be to change the constructor logic such that `undefined` and `null` are treated differently.
> 
> If `null` were passed, we could remove any `tabindex` attribute, and if `undefined` were passed we could treat it the same as the current logic.

#28345 suggests only add tabindex for &lt;a> elements. Reasons are also elaborated there.

**Pull request closed without merging**
