### PR TITLE
docs: clarify scale statement for template-driven forms in overview

### PR DESCRIPTION
**Pull request by pyzen5**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks for the PR @pyzen5. I think the current wording is correct. What is confusing about it to you?

**Comment by pyzen5** [comment]
"They're easy to add to an app, but they don't scale as well as reactive forms." this sentence will convey that template driven forms as well as reactive forms are not scalable. Instead it has to be like "They're easy to add to an app, but they don't scale as reactive forms."

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update git commit message to `docs: clarify scale statement for template-driven forms in overview`

**Comment by brandonroberts** [comment]
@pyzen5 You must [Sign the CLA](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#cla) before this PR can move forward.

**Pull request closed without merging**
