### PR TITLE
docs: fix minor typos

### PR DESCRIPTION
**Pull request by frederikprijck**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?
Fix typos in docs

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

Breaking change:
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by frederikprijck** [comment]
CircleCI failed due to the commit message. I'm a bit unsure what scope to take for this change 🙈

**Comment by sarunint** [comment]
Just `docs` without scope. Also `Fix` should be all lowercase.

`docs: fix minor typos`

**Comment by frederikprijck** [comment]
Closed/reopened to retry Travis (apparently, Travis dislikes me. It pretty much fails on me for both the AngularJS and Angular repository every single time :( )

**Comment by sarunint** [comment]
Well, Travis has been flakey for the past 2-3 months.

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
The Travis failures are indeed unrelated.
Needs `root` approval.

**Comment by frederikprijck** [comment]
@gkalpak FYI I've edited the PR after ur approval as I've found another typo.

**Comment by gkalpak** [comment]
Sneaky! Still LGTM :smiley:

**Comment by frederikprijck** [comment]
Typos are resolved by https://github.com/angular/angular/pull/21739 .

**Pull request closed without merging**
