### PR TITLE
docs: add missing picture of Jason Bedard

### PR DESCRIPTION
**Pull request by gkalpak**
Related to #29141.

### CODE REVIEW

**Comment by jbedard** [comment]
😲

**Review by StephenFluin — CHANGES_REQUESTED** [review]
Can we get the file size down to about 20kb?

**Comment by gkalpak** [comment]
@StephenFluin: This PR is just aligning 7.2.x with the master branch.
The size is being brought down (in both branches) in #29601.

**Review by StephenFluin — APPROVED** [review]

**Comment by gkalpak** [comment]
Merged as a52123f53.

**Pull request closed without merging**
