### PR TITLE
docs: adapt the NgModule to the new default : standalone

### PR DESCRIPTION
**Pull request by JeanMeche**

### CODE REVIEW

**Comment by marcosebsilva** [comment]
Marcos from discord here.

I saw the same problem on different pages other than the ones that where changed on the PR. Is there a problem if a make some commits in your fork? Not sure how to reference those pages here since they were not changed

**Review by bencodezen — APPROVED** [review]
Thanks for the PR. Looks good to me!

**Comment by JeanMeche** [comment]
@bencodezen I've added a new set of changes, feel free to have a look !

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 029163c494a925f29e01aeaffbbf153cb184b254.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
