### PR TITLE
feat(common): HttpParams fromObject accepts ReadonlyArray<str…

### LINKED ISSUE #28452: HttpParams fromObject should accept ReadonlyArray<string>
# 🚀 feature request

### Relevant Package
@angular/common/http

### Description
The type definition for HttpParamsOptions fromObject property only accepts string and string[].  If using immutable types, such as ReadonlyArray, you must create a new array unnecessarily to satisfy the type.

### Describe the solution you'd like
Please change the type to the following (which is backwards compatible):

```
    fromObject?: {
        [param: string]: string | string[] | ReadonlyArray<string>;
    };
```

### PR DESCRIPTION
**Pull request by MansourFall**
…ing>

Fixes #28452

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #28452

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by MansourFall** [comment]
I signed it!

**Comment by cexbrayat** [comment]
@MansourFall Can you update the commit message with `feat(common): HttpParams fromObject accepts ReadonlyArray<string>` please?

**Comment by MansourFall** [comment]
@cexbrayat  update done! thanks!

**Review by alxhub — APPROVED** [review]

**Comment by cexbrayat** [comment]
@MansourFall Would you mind rebasing the PR to resolve the conflict? Basically keeping the new signature, but with the updated comment:
```typescript
/** Object map of the HTTP parameters. Mutually exclusive with `fromString`. */
fromObject?: {[param: string]: string | ReadonlyArray<string>};
```

To do so:
```
git fetch upstream
git rebase upstream/master
# resolve the conflict
git add packages/common/http/src/params.ts
git rebase --continue
# check if everything is OK
git show
# all good? ready to push!
git push --force
```

When that's done we should be able to merge it!

**Comment by MansourFall** [comment]
@cexbrayat thank you for the instructions, just made the changes!

**Comment by petebacondarwin** [comment]
Caretaker: this is a docs-only change so should not require a presubmit.

**Comment by matsko** [comment]
Presubmit = http://test/OCL:266428477:BASE:266428502:1567191852249:433a52b0

Ivy Presubmit = http://test/OCL:266428477:BASE:266428670:1567191897180:bf41ddb3

**Pull request closed without merging**
