### PR TITLE
fix(localize): include meaning in generated ARB files

### LINKED ISSUE #40506: ARB Serializer -> missing "meaning" on extracted translation files
# 🐞 bug report

### Is this a regression?
No, ARB file format is new on Angular 11.1

### Description

We would like to support ARB format for our component translations files (to avoid the use of XML parser library to handle xliff files: xml2js or cheerio). After update our solution to Angular 11.1 we are now testing ARB extraction format but what we have noted is that there is no more _meaning_ information extracted:

```
"71788121164220023": "no tags found",
  "@71788121164220023": {
    "description": "No tags found placeholder",
    "x-locations": [
      {
        "file": "projects\\xxxxx\\hardware-editors\\src\\lib\\elements\\channelEditor.component.html",
        "start": { "line": "70", "column": "25" },
        "end": { "line": "70", "column": "38" }
      }
    ]
  },
```

Why not to use [Customized Attribute]( https://github.com/google/app-resource-bundle/wiki/ApplicationResourceBundleSpecification#customized-attributes) on ARB format (as ready did with x-location) and add an `x-meaning` property?

For example:

```
"71788121164220023": "no tags found",
  "@71788121164220023": {
    "description": "No tags found placeholder",
    "x-meaning": "My meaning",
    "x-locations": [
      {
        "file": "projects\\xxxxx\\hardware-editors\\src\\lib\\elements\\channelEditor.component.html",
        "start": { "line": "70", "column": "25" },
        "end": { "line": "70", "column": "38" }
      }
    ]
  },
```

### PR DESCRIPTION
**Pull request by crisbeto**
The ARB format doesn't have a dedicated field for message meaning so these changes include it as a customize attribute called `x-meaning`.

Fixes #40506.

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
LGTM - thanks @crisbeto

**Comment by petebacondarwin** [comment]
I wonder whether this shoud be `target: minor` as it arguably is a feature?

**Comment by crisbeto** [comment]
I don't feel strongly about it. I tagged it as a `fix`, because most of the other formats were exposing the `meaning` already.

**Comment by petebacondarwin** [comment]
Fair enough. Let's land it.

**Pull request closed without merging**
