### PR TITLE
build(docs-infra): update docs examples to Angular v13.0.0-rc.0

### PR DESCRIPTION
**Pull request by gkalpak**
This PR updates the docs examples to Angular v13.0.0-rc.0. In addition to updating the dependency versions, it also updates the projects' structure and configs to more closely match what a new v13 CLI app would look like. See, also, the [diff][1] between a basic v12.1.3 CLI app and a v13.0.0-rc.0 one.
(NOTE: v12.1.3 was the last version for which we aligned the projects with how a new CLI app would look like.)

Additionlly:
- Since we now use RxJS v7 in docs examples, this commit removes the extra CI steps to explicitly test the docs examples against RxJS v7.
- Since Angular v13 no longer supports IE, this commit removes an IE-specific section from `upgrade-setup.md`.

[1]: https://github.com/cexbrayat/angular-cli-diff/compare/12.1.3..13.0.0-rc.0

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
Thanks for updating AIO to use v13. This would also unblock further updates of https://angular.io/guide/dynamic-component-loader guide (and other examples) to use new `ViewContainerRef.createComponent` API.

**Review by petebacondarwin — APPROVED** [review]

**Review by atscott — APPROVED** [review]

**Review by alxhub — APPROVED** [review]
Approved-for: global-approvers

**Review by alxhub — APPROVED** [review]
Approved-for: global-approvers

**Review by alxhub — APPROVED** [review]
Reviewed-for: global-approvers

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 7b35a3426f8210db10464c1084d5720472c27f87.

**Comment by IgorMinar** [comment]
Thanks @gkalpak for doing this work!

**Pull request closed without merging**
