### PR TITLE
docs(aio): Added resource link to Amexio Canvas Web Based Drag and Drop IDE

### PR DESCRIPTION
**Pull request by ketan-gote**
docs(aio): Added resource link to Amexio Canvas Web Based Drag and Drop IDE

Amexio Canvas link added.

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Added new resource link

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by ketan-gote** [comment]
Can anyone suggest as to why travis build is failing?? As the changes(Addition of resource) are just in a single file aio/content/marketing/resources.json ??

**Comment by gkalpak** [comment]
Don't worry about the Travis failures. They are not related to this PR.
(They seem to be caused by some temporary network/yarn server issue.)

**Review by StephenFluin — CHANGES_REQUESTED** [review]
We reviewed the request and it looks like it does not meet our requirements. In particular requirements 1, 4, and 5.

See: https://github.com/angular/angular/blob/master/aio/content/marketing/resources-contributing.md

**Comment by ketan-gote** [comment]
@StephenFluin 
Have changed the resource [link](https://amexio.tech/home) to our main page where it talks about Angular.  Amexio is open source library based on angular, where we have seen lot of traction by angular developer. Amexio Canvas is UI Automation platform for Angular and Amexio UI Component Library.

Let me know if any more info is required.

**Review by StephenFluin — CHANGES_REQUESTED** [review]
This link looks much better and seems to meet our requirements, thanks for that! Can you squash the commits so there's a single commit?

**Comment by ketan-gote** [comment]
Have squashed commit in [one](https://github.com/angular/angular/pull/24286/commits/e8dda9f585ad35bf33ae3e39350cc91c5751d7b4)

**Comment by StephenFluin** [comment]
@ketan-gote If you look at https://github.com/angular/angular/pull/24286/commits You will see that we now have 4 commits. You'll need to squash them down, and you'll want to rebase on the latest master (it looks like your PR contains changes from other commits to master that have happened), then you'll need to git push -f to your branch to update this PR.

Let us know if that makes sense or if you have any questions.

**Comment by ketan-gote** [comment]
Closing this PR will open new PR

**Pull request closed without merging**
