### PR TITLE
docs: update input/output guide links

### LINKED ISSUE #54134: https://angular.dev/tutorials/first-app/inputs   BAD LINK
### Describe the problem that you experienced
https://angular.dev/tutorials/first-app/inputs   the main tutorial

Bad link  

This one at the bottom dont works

[Sharing data between child and parent directives and components](https://angular.dev/guide/components/inputs-outputs)

### PR DESCRIPTION
**Pull request by swami-sanapathi**
Closes: #54134

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, thanks for helping us improve the docs, what do you think of having 2 links here for input and outputs ?

**Comment by swami-sanapathi** [comment]
Sure, can we set the title of the `docs-pill-row` as 'Sharing data between parent and child directives and components'?

**Comment by JeanMeche** [comment]
What about using the title of the dedicates pages : 

* [Accepting data with input properties](https://angular.dev/guide/components/inputs)
* [Custom events with outputs](https://angular.dev/guide/components/outputs)

**Comment by swami-sanapathi** [comment]
That's great, I've updated with changes.

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 45288f78150bc49086288c00704a6535d71bcb37.

**Pull request closed without merging**
