### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by ranma42**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
There are some typos in the code and in the docs.

Issue Number: N/A

## What is the new behavior?
There are less typos in the code and in the docs.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

This PR renames some exported identifiers that are marked as internal; if they are considered as breaking change, I will drop those changes.

## Other information

I am unsure if this is the best approach for fixing the typos (a single branch multiple commits each one consisting of "coherent" changes).

I am also unsure if you accept fixes for the different typos (I guess fixes in docs are fine, but maybe fixing typos in local variable names is considered unwanted noise in the commit history).

I tried my best in classifying these changes according to the guidance provided in the `CONTRIBUTING.md` document, but the headers might need some polishing (for example, is a typo fix a "bug fix" when it affects code?).

If splitting or reorganizing the PR (or deferring part of it after v17) is desired, I will gladly do it.
If these changes are welcome, I will try to go over more parts of the codebase.

### CODE REVIEW

**Review by alxhub — CHANGES_REQUESTED** [review]
Hi @ranma42,

This looks great, so many fixes! I promise the Angular team _does_ know how to spell...

I would recommend squashing all of these commits into a single `refactor` commit, a la:

```
refactor: fix a number of typos throughout the codebase

Etc etc.
```

There's no need to spell out all the typos in the commit message or anything.

Otherwise, this LGTM and I don't see a problem with landing it.

**Comment by ranma42** [comment]
I rebased to fix a conflict (the typo already fixed in #52258) and to take your recommendation about the commit message into account... and this time the tests passed cleanly 🥳 

Thank you for your suggestions! I will come up with more typo fixes soonish :)

**Comment by ranma42** [comment]
another PR was merged causing conflicts, so I rebased this one. unfortunately this PR is quite likely to have conflicts since it affects many files... so I'll try with a ping @alxhub 😇

**Comment by ranma42** [comment]
rebased to resolve conflicts 😎 @alxhub

**Review by dylhunn — APPROVED** [review]
Based on Alex's conditional LGTM, let's just merge this.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit fc9ba3978cc098b59c107371bbd5413044fbecda.

**Pull request closed without merging**
