### PR TITLE
refactor: replace deprecated `HTMLDocument` with `Document`

### PR DESCRIPTION
**Pull request by alan-agius4**
`HTMLDocument` is deprecated in favor of `Document`. This change replaces the usages of `HTMLDocument`.

See: https://github.com/microsoft/TypeScript/blob/20c93d3b1da44d8ee740b466a5cde7894e8b3260/lib/lib.dom.d.ts#L6370-L6376

### CODE REVIEW

**Review by devversion — APPROVED** [review]

**Review by alxhub — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@alan-agius4 do you have a presubmit link? If not, could you please run a presubmit for the changes in this PR?

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:433273461:BASE:433273495:1646769669372:c9fa9c30).

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit ba0efd1f801a27b6a59c5fd3fcb7f21f9e8169e1.

**Comment by AndrewKushnir** [comment]
@alan-agius4 FYI there was a conflict with the patch branch (13.2.x), so this change was only merged into master. Please create a followup patch-only PR if needed. Thank you.

**Pull request closed without merging**
