### PR TITLE
docs: add missing comma to environment config in build guide

### PR DESCRIPTION
**Pull request by RGelman**
Line 57 missing comma after 'true'.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by RGelman** [comment]
I signed it!

**Review by gkalpak — APPROVED** [review]
Good catch 👍

**Comment by gkalpak** [comment]
Can you please update the commit message to adhere to [our guidelines][1]?

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by RGelman** [comment]
Updated commit message to adhere to guidelines

**Review by brandonroberts — APPROVED** [review]

**Pull request closed without merging**
