### PR TITLE
build: update @microsoft/api-extractor to 7.18.1

### PR DESCRIPTION
**Pull request by alan-agius4**
microsoft/rushstack#2797 is fixed.

### CODE REVIEW

**Review by devversion — APPROVED** [review]
🎉

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by AndrewKushnir** [comment]
@alan-agius4 FYI there is a merge conflict with the master branch atm (due to other updates to the `package.json` file merged earlier). Could you please rebase and resolve conflict when you get a chance? Thank you.

**Comment by alan-agius4** [comment]
@AndrewKushnir, done!

**Pull request closed without merging**
