### PR TITLE
docs(frequent-ngmodules): fix RouterModule description

### PR DESCRIPTION
**Pull request by SangKa**
The `Import it from` of RouterModule is `@angular/router`

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Great eye @SangKa! Thank you! LGTM

**Review by kapunahelewong — APPROVED** [review]

**Comment by SangKa** [comment]
@kapunahelewong my pleasure 🤗

**Comment by kapunahelewong** [comment]
@SangKa would you rebase when you get a chance? Please ping me when you're ready and I'll change the label from clean up to review. Thanks again! :)

**Comment by SangKa** [comment]
@kapunahelewong rebased

**Comment by kapunahelewong** [comment]
Ah, I see what happened @SangKa. It's just the commit message:

> INVALID COMMIT MSG: "docs(frequent-ngmodules): fix RouterModule description"

Try this: "docs: fix RouterModule description"

I think that will satisfy the test. Please tag me when you're ready. Thank you! :)

**Comment by kapunahelewong** [comment]
Just found this: duplicate of [https://github.com/angular/angular/pull/21523](https://github.com/angular/angular/pull/21523)

**Comment by SangKa** [comment]
@kapunahelewong Thank you for your guide. It works.

**Pull request closed without merging**
