### PR TITLE
docs(aio): add missing dependencies and files to testing zip download

### LINKED ISSUE #23060: docs(testing): not works download example.
## I'm submitting a...

<pre><code>[ x ] Bug report 
</code></pre>

## Current behavior
After downloads [Tests](https://angular.io/generated/zips/testing/specs.testing.zip) from [docs](https://angular.io/guide/testing), `npm i` and `npm test`, angular CLI report about error:

> ERROR in Entry module not found: Error: Can't resolve '/var/repos/angular-sample-tests/src/test.ts' in '/var/repos/angular-sample-tests/node_modules/@angular/cli/models/webpack-configs'
>
> ERROR in error TS6053: File '/var/repos/angular-sample-tests/src/test.ts' not found.
src/app/twain/twain.component.marbles.spec.ts(3,40): error TS2307: Cannot find module 'jasmine-marbles'.

And even after `npm i jasmine-marbles rxjs` throw error:

> ERROR in Entry module not found: Error: Can't resolve '/var/repos/angular-sample-tests/src/test.ts' in '/var/repos/angular-sample-tests/node_modules/@angular/cli/models/webpack-configs'
>
> ERROR in error TS6053: File '/var/repos/angular-sample-tests/src/test.ts' not found.
node_modules/jasmine-marbles/src/scheduler.d.ts(1,31): error TS2307: Cannot find module 'rxjs/testing'.
node_modules/jasmine-marbles/src/test-observables.d.ts(2,33): error TS2307: Cannot find module 'rxjs/internal/testing/SubscriptionLog'.

## Expected behavior
Test example should works.

## Environment

<pre><code>
Angular CLI: 1.6.5
Node: 8.10.0
OS: linux x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, upgrade

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0
</code></pre>

### PR DESCRIPTION
**Pull request by brandonroberts**
Closes #23060

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
LGTM for the zips.
(The stackblitz projects seem to be broken, but that could be fixed in another PR.)

**Comment by gkalpak** [comment]
BTW, the live examples seem to be broken because StackBlitz doesn't know where to look for `app/**` stuff required in [test.sb.ts][1]. Maybe changing `from 'app/...'` to `from './app/...'` would fix it.

[1]: https://github.com/angular/angular/blob/88ab1d0e553238f45e16fabd208134f836564a63/aio/content/examples/testing/src/tests.sb.ts

**Comment by brandonroberts** [comment]
@gkalpak yea, that fixes it but it works on the V5 examples using `app/...` 

V5 - https://stackblitz.com/angular/ovyxpbjxapo
V6 - https://stackblitz.com/angular/lnajarexvlk

cc: @EricSimons

**Comment by brandonroberts** [comment]
Yes, we had this same issue with the live example for the router also not recognizing `app/...` and the StackBlitz team fixed the issue on their end.

**Comment by brandonroberts** [comment]
I opened a separate issue about the StackBlitz zip files as they are broken for V5 and V6. https://github.com/angular/angular/issues/23962

**Comment by EricSimons** [comment]
Yeah, what @gkalpak pointed out is the cause of this issue. Unf this one will be a bit harder for us to immediately fix on our end, although we do have some new upgrades we're working on for our bundler/loader that are coming in 2-4wks that will make it possible. In the meantime, swapping the imports to be relative does fix this problem- here's a fork I made: https://stackblitz.com/edit/angular-nfcbbm?file=src/tests.sb.ts

**Comment by brandonroberts** [comment]
Ok. I'll change the paths to be relative.

**Review by gkalpak — APPROVED** [review]

**Pull request closed without merging**
