### PR TITLE
fix(upgrade): fix infinite $rootScope.$digest()

### LINKED ISSUE #6385: bug(upgrade): infinite digests with setTimeout (repro inside)
angular2/upgrade has a bug that occurs when an angular1 watcher calls `setTimeout`, as is the case with many angular1 components.

Repro: http://plnkr.co/edit/5iCEQOSOer5c630FStXv?p=preview

This results in infinite angular1 digests because of this line:

https://github.com/angular/angular/blob/master/modules/angular2/src/upgrade/upgrade_adapter.ts#L341

Changing `ngZone.run` to `ngZone.runOutsideAngular` there seems to fix it or make it more manageable.

### PR DESCRIPTION
**Pull request by andreialecu**
Fixes #6385

### CODE REVIEW

**Comment by andreialecu** [comment]
@googlebot I signed it.

**Comment by andreialecu** [comment]
Not sure why the `clang-format` test is failing, I ran it and that's the output I got.

**Comment by andreialecu** [comment]
Repro at http://plnkr.co/edit/5iCEQOSOer5c630FStXv?p=preview

**Comment by andreialecu** [comment]
Bump. 

There were 3 beta releases since posting this.

This bug makes it impossible to upgrade anything but the most trivial app since a lot of angular1 components use timers... I need to maintain my own fork to be able to use angular2 at all.

Paging @vsavkin @pkozlowski-opensource @tbosch @mhevery

**Comment by mhevery** [comment]
Scheduled for merging.

**Comment by andreialecu** [comment]
@mhevery: Awesome, maybe have a look at my other PR as well which is also blocking: https://github.com/angular/angular/pull/6460

**Pull request closed without merging**
