### PR TITLE
docs: deprecate ViewEngine-based `renderModuleFactory`

### PR DESCRIPTION
**Pull request by alan-agius4**
DEPRECATED:

The `renderModuleFactory` symbol in `@angular/platform-server` is no longer necessary as of Angular v13.

The `renderModuleFactory` calls can be replaced with `renderModule`.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

**Review by alxhub — APPROVED** [review]
Reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
Thanks for deprecating this function 👍 
I must have missed that as I was doing other similar deprecations.

Reviewed-for: public-api

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Comment by josephperrott** [comment]
This PR was merged into the repository by commit 4eedf77fd0147a9dafccdfb2638f11771b26c253.

**Pull request closed without merging**
