### PR TITLE
docs(aio): fix styling

### PR DESCRIPTION
**Pull request by sibiraj-s**
## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
improper border for h1. check here at https://angular.io/guide/displaying-data

Homepage having different image width

Issue Number: N/A

## What is the new behavior?

Fixed h1 styling - typography.scss

Fixed images in homepage

This will look good

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by gkalpak** [comment]
I am not sure if these were intentional dicisions or oversights. Assigning to @sjtrimble.

**Comment by sjtrimble** [comment]
The current h1 styling is intended as such. I will take a look at the images item in more detail.

**Comment by Sibiraj-S** [comment]
@sjtrimble . I proposed those changes. because when I enter the pages. I felt that odd. the line below `h1` could be removed or can be of full width. and what about the home page edit?

**Comment by Sibiraj-S** [comment]
@sjtrimble . also for `h1`. I thought it was a mistake. If it is intentional. then not a problem.
but having a full width looks better than that because when I first saw that short line I didn't understand what exactly is that for.

**Comment by Sibiraj-S** [comment]
@sjtrimble . any updates?

**Comment by petebacondarwin** [comment]
@Sibiraj-S thanks for this PR and I am sorry it has taken so long to deal with it.
As noted above, the width of the underline below the heading is by design, and @sjtrimble has provided an alternative PR for the image sizes.
Closing in favour of #17927.

**Pull request closed without merging**
