### PR TITLE
fix(EventEmitter): resolve synchronously by default and remove boolean parameter

### PR DESCRIPTION
**Pull request by tamascsaba**
https://github.com/angular/angular/issues/6699

### CODE REVIEW

**Comment by tamascsaba** [comment]
I think when use typescript or dart, then autocomplete is a good for boolean parameter, but when use ES5  or ES6 then not so logical.

My other proposal is separate sync and async eventemitter, what do you think?
```
new EventEmmiter(); //sync
and
new AsynEventEmmiter(); //async
```

**Comment by tamascsaba** [comment]
@pkozlowski-opensource what do you think about:
```EventEmitter``` and ```AsynEventEmitter```??

**Comment by vsavkin** [comment]
Can you fix travis-ci?

**Comment by tamascsaba** [comment]
I rebased the newest angular/master, but it's also failed with TypeScript errors

**Comment by vsavkin** [comment]
Could you fix the typescript errors?

**Comment by tamascsaba** [comment]
typescript errors are in other files, I rebased my master, still fail :(

**Comment by tamascsaba** [comment]
I fixed typescript errors, but integration test fails too :(, I think it is a really big change and discuss it before implement.

**Comment by thinkh** [comment]
I agree to differentiate the type of EventEmitter by name. This would have saved me a lot of time debugging the EventEmitter and discovering the flag in the constructor.

**Comment by mhevery** [comment]
Duplicate of https://github.com/angular/angular/pull/7421

**Pull request closed without merging**
