### PR TITLE
fix(router): Added route data to normalized async route

### LINKED ISSUE #6272: Async routes cause route data to be lost
Hello guys,

I'm using angular 2 beta.0 and I'm trying to change the routeconfigs so some of my components are loaded asynchronously.
Unfortunately, when I do so, the data I pass to the data parameter of the route gets lost. This is only happening for ```AsyncRoute```s, I figured it might be the case that this is not supposed to be possible but the docs say otherwise.
I've set-up a plunkr where you can see this happen. There are 2 components to which you can navigate by clicking one of the 2 buttons.
The first one is for a synchronous route and it prints out the data I pass in.
The second one is for an asynchronous route and it does not print out anything because as you can see from the console output, the routeData object does not hold the data that I passed in the route configuration.
Example here: https://plnkr.co/edit/LYaQvPzpBmmI9ADn3poQ

Best regards,
André

### PR DESCRIPTION
**Pull request by brandonroberts**
Closes #6272 #6636 

cc: @petebacondarwin

### CODE REVIEW

**Comment by brandonroberts** [comment]
I'm getting a Dart build error. Any ideas on how to fix?

**Comment by zoechi** [comment]
In Dart AFAIK a class is passed instead of an object (Map/_LinkedHashMap).

I assume it's this line

    {path: '/route-data', loader: asyncRouteDataCmp, data: {isAdmin: true}}

it should be something like this instead

    new AsyncRoute(path: '/route-data', loader: asyncRouteDataCmp, data: {isAdmin: true});

**Comment by brandonroberts** [comment]
@zoechi right, but the test is for making sure if you don't provide a type that it still works. Maybe I need to move this test to the ng1 router tests.

Thanks!

**Comment by brandonroberts** [comment]
@petebacondarwin @btford this PR is ready. Both of my test failures were from the builds flaking out.

**Comment by petebacondarwin** [comment]
LGTM

**Comment by brandonroberts** [comment]
Rebased this one again

**Comment by btford** [comment]
Thanks @brandonroberts!

Looks like this last failure is a flake. I'm re-running it to double check and will merge if it passes.

**Comment by brandonroberts** [comment]
:+1:

**Pull request closed without merging**
