### PR TITLE
doc(core): fix typo for getting component definition function

### PR DESCRIPTION
**Pull request by Zuckjet**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-docs-approvers

**Comment by petebacondarwin** [comment]
@Zuckjet - please can you fix the commit message. It should be `docs` not `doc`.

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by Zuckjet** [comment]
> @Zuckjet - please can you fix the commit message. It should be `docs` not `doc`.

My bad and now fixed. Thanks for so quick response

**Comment by petebacondarwin** [comment]
Nice! Thanks

**Pull request closed without merging**
