### PR TITLE
docs(compiler-cli): ng new does not generate app.module.ts

### LINKED ISSUE #52751: ng new does not generate  app.module.ts in the src root folder Angular CLI 17.0.0
### Command

new

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v16.0.5

### Description

I ran the command "ng new my-blog --routing --style=scss" to create a new angular project using Angular CLI version 17.0.0 and could not find the app.module.ts file automatically generated by the CLI. 

In the documentation "https://angular.io/guide/file-structure" it says 

app/app.module.ts | Defines the root module, named AppModule, that tells Angular how to assemble the application. Initially declares only the AppComponent. As you add more components to the app, they must be declared here. This file is not generated when using --no-standalone option.

I did not use the --no-standalone option so I was expecting this file to be generated by Angular CLI v17.0.0. Is this something new to be added by developer going forward.

### Minimal Reproduction

```
ng new my-blog --routing --style=scss
? Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? No
CREATE my-blog/README.md (1060 bytes)
CREATE my-blog/.editorconfig (274 bytes)
CREATE my-blog/.gitignore (548 bytes)
CREATE my-blog/angular.json (2771 bytes)
CREATE my-blog/package.json (1038 bytes)
CREATE my-blog/tsconfig.json (909 bytes)
CREATE my-blog/tsconfig.app.json (263 bytes)
CREATE my-blog/tsconfig.spec.json (273 bytes)
CREATE my-blog/.vscode/extensions.json (130 bytes)
CREATE my-blog/.vscode/launch.json (470 bytes)
CREATE my-blog/.vscode/tasks.json (938 bytes)
CREATE my-blog/src/main.ts (250 bytes)
CREATE my-blog/src/favicon.ico (15086 bytes)
CREATE my-blog/src/index.html (292 bytes)
CREATE my-blog/src/styles.scss (80 bytes)
CREATE my-blog/src/app/app.component.scss (0 bytes)
CREATE my-blog/src/app/app.component.html (20887 bytes)
CREATE my-blog/src/app/app.component.spec.ts (919 bytes)
CREATE my-blog/src/app/app.component.ts (369 bytes)
CREATE my-blog/src/app/app.config.ts (227 bytes)
CREATE my-blog/src/app/app.routes.ts (77 bytes)
CREATE my-blog/src/assets/.gitkeep (0 bytes)
✔ Packages installed successfully.
```

### Exception or Error

_No response_

### Your Environment

```text
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.0 (cli-only)
@angular-devkit/core         17.0.0 (cli-only)
@angular-devkit/schematics   17.0.0 (cli-only)
@schematics/angular          17.0.0 (cli-only)
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by asyncLucas**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

fixes #52751

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by twerske** [comment]
Can you please also add this to `adev/` content folder?

**Review by twerske — APPROVED** [review]

**Review by KlausEverWalkingDev — APPROVED** [review]

**Comment by josephperrott** [comment]
@jelbourn, can you take a look at the wording here?

**Review by twerske — APPROVED** [review]

**Review by jelbourn — COMMENTED** [review]
Missed the original notification on this one-

I think this update is obsolete now; the current reference table includes the line:

```
Only generated when using the --standalone false option.
```

For the local setup guide, I don't think the absence of the module file needs an explicit callout

**Comment by JeanMeche** [comment]
Per Jeremy, we'll go with the current changes.

**Pull request closed without merging**
