### PR TITLE
docs: use SimpleChanges in component interaction guide

### PR DESCRIPTION
**Pull request by bampakoa**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The [example ](https://angular.io/guide/component-interaction#intercept-input-property-changes-with-ngonchanges)of the component interaction guide currently uses the `SimpleChange` interface.

Issue Number: N/A

## What is the new behavior?
The example uses the [SimpleChanges](https://angular.io/api/core/SimpleChanges) interface for explaining the `ngOnChanges` method.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
LGTM, thanks for improving Angular docs!

**Comment by bampakoa** [comment]
@AndrewKushnir it looks that the CI test fails after you force-pushed it. Is there anything I can do to help with that?

**Comment by AndrewKushnir** [comment]
@bampakoa, there was a temporary CI problem with the master branch (thus affecting your PR after I rebased it). The problem is now fixed and I've rebased your PR again to rerun CI. Once CI is "green", this PR will be added to the merge queue. Thank you.

**Comment by AndrewKushnir** [comment]
Quick update: it looks like there is some instability on CI at this moment, so the `test_ivy_aot` CI job is failing. We are looking at this issue, but there is no ETA at this moment. Once CI is more stable we will restart the failing CI job. Thank you.

**Comment by bampakoa** [comment]
🙏  for your feedback @AndrewKushnir

**Pull request closed without merging**
