### PR TITLE
build: update cross-repo angular dependencies

### PR DESCRIPTION
**Pull request by alan-agius4**
See associated pull request for more information.

(cherry picked from commit ba630a3c65da2ee522f4d139174621a05af1d461)

The size increase is due to some additional wrapping done to improve tree-shaking of unused classes and in some cases, single characters have been replaces with 2. 

Example: 
Screenshot 2023-03-09 at 14 06 58

Screenshot 2023-03-09 at 14 10 44

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: size-tracking

**Review by AndrewKushnir — APPROVED** [review]

**Review by devversion — APPROVED** [review]
lgtm. do we know what causes the different class wrapping? is this from a CLI optimizer babel plugin?

**Comment by alan-agius4** [comment]
> lgtm. do we know what causes the different class wrapping? is this from a CLI optimizer babel plugin?

Yes it is. It’s caused by https://github.com/angular/angular-cli/pull/24815

**Comment by alxhub** [comment]
This PR was merged into the repository by commit a50ff60bff64859e4cd279a9ce0c8b47e6dfa691.

**Pull request closed without merging**
