### PR TITLE
docs(core): fix broken link <BLANK LINE> Dead link is updated with new, working, and updated link. 

### PR DESCRIPTION
**Pull request by vivekkoya**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Redirects users to dead (invalid) link: https://amexio.tech

Issue Number: N/A

## What is the new behavior?
Goes to proper documentation page: https://api.amexio.org

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@vivekkoya Thanks for the fix. Looks like your commit message needs to be fixed. Once you do that, we can review / land this.

**Review by twerske — APPROVED** [review]
LGTM

**Comment by vivekkoya** [comment]
docs(core): fix broken link
<BLANK LINE>
Dead link is updated with new, working, and updated link.

**Comment by vivekkoya** [comment]
I've formatted the commit message to the format requested.

**Comment by jessicajaniuk** [comment]
@vivekkoya It looks like you've updated the PR title, but not the commit message header. If you do `git commit --amend` in your command line and update the commit with the same info you put in the title here, you should be able to force push the change to your PR. That'll resolve it.

**Pull request closed without merging**
