### PR TITLE
Fix typo in Forms API doc

### PR DESCRIPTION
**Pull request by JoelBalmer**
'withngModelOptions' to 'with ngModelOptions'

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JoelBalmer** [comment]
@googlebot I signed it

**Comment by kapunahelewong** [comment]
Good catch, @JoelBalmer! Could you rebase and amend your commit message? You could use the following as your commit message:

```
docs: fix typo in form_control_name API doc
```
Here are [my notes for rebasing and amending](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) (scroll down for the amend section).

Requesting @jbogarthyde's review as she is familiar with the API docs.

**Review by jbogarthyde — APPROVED** [review]
LGTM

**Comment by kapunahelewong** [comment]
@JoelBalmer, will you tag me when you're ready? I should have mentioned it in my previous comment. I'd like to help you land this. Thanks!

**Comment by jbogarthyde** [comment]
@JoelBalmer, I took the liberty of changing the **title of the PR** to be more descriptive, but I think you still need to change the **commit message**, as Kapunahele recommended. The commit message stays in the git logs forever, so it's even more important for that to be descriptive.

**Comment by JoelBalmer** [comment]
@kapunahelewong, thanks for offering your help and assistance, it is definitely appreciated I've just been busy at work and life (I spotted this at work once and sent a note to myself to fix). I'm taking a look now!

@jbogarthyde, to be honest I followed the instructions and assumed it would just sign itself and work but apparently not! No idea why. I'm just looking into it now.

In the meantime, any other issues you need fixing? A 1 letter change for this PR doesn't seem enough now everyone's gone to all this effort 🤣

**Comment by JoelBalmer** [comment]
@googlebot I signed it!

**Comment by JoelBalmer** [comment]
@kapunahelewong see if that works for you - looks like it made a new commit with the right message

**Comment by JoelBalmer** [comment]
@jbogarthyde thanks for the tip - I actually changed nothing, just resaved my info on google CLA, resaved my emails in github, deleted an old unused one, and voila

**Comment by jbogarthyde** [comment]
@JoelBalmer Try running the tests again -- Click **Details** for one that failed, click **default_workflow**, then choose "Rerun from failed" from the drop-down.

**Comment by JoelBalmer** [comment]
@kapunahelewong, @jbogarthyde clicking default_workflow link results in a page with a never-ending spinner:
Screenshot 2019-11-03 at 10 13 02

Perhaps it's something to do with the previous failed test details page:
Screenshot 2019-11-03 at 10 13 53

Looking at why the test failed I can only see typescript version mismatching. Not sure why that would be a problem for my PR.

Thanks!

**Comment by JoelBalmer** [comment]
@kapunahelewong, @jbogarthyde, I've created a circle ci account (connected to my github account and repositories) and i'm now seeing the default_workflow details page so that spinner has gone.

However, there's just a big red failed button in the top left with no dropdown:
Screenshot 2019-11-03 at 10 31 26

**Comment by jbogarthyde** [comment]
@JoelBalmer I reran the test for you, hoping it was just a flake, but it seems to be a real error. 
`Error: The Angular Compiler requires TypeScript >=3.6.4 and <3.7.0 but 3.5.3 was found instead.`
Can you update your TypeScript version?

**Comment by AndrewKushnir** [comment]
Hi @JoelBalmer, thanks for creating this PR! It looks like the problem was caused by the fact that this PR was created before TypeScript version check was introduced. Could you please perform the following steps to resolve the issue:
- squash all commits into a single one (to avoid linter errors)
- rebase this PR on top of the latest master

Thank you.

**Comment by JoelBalmer** [comment]
@AndrewKushnir, so I've gone and squashed the commits correctly. Then on a test branch, I pull master onto master from upstream and rebased as per the [instructions linked above](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase). However, this kept overwriting or deleting the changes I wanted to make (the commits appera to have been removed locally when i look at git log). On another test branch I tried pulling master onto my feature branch, which retained my local changes, plus the merge I'd just made. Again, rebasing at this point removed my local change. However, the CLI did output a line something along the lines of "change has already been applied".

That led me to some more investigating, where it looks like the 1 letter typo this PR was initially about has already been fixed in #33352. So, I'm not sure what will happen with this PR anymore? This PR actually contains 0 changes now?

I feel like it's best I abandon the PR. What do you think? Apologies, I was only trying to help 😥

**Comment by jbogarthyde** [comment]
@JoelBalmer Certainly no need to apologize - this has been a great learning experience, and you are now in a position to make more substantive contributions. The whole PR workflow does require a bit of a learning curve, especially with API docs. 
The typo you identified does seem to have been fixed in Next (although is still appears in the current release). That doc will become current shortly, so it's fine if you want to close this. 
I hope we see more contributions from you soon -- I'm sure the process will continue to get easier. 😃

**Comment by kapunahelewong** [comment]
@JoelBalmer if you want to do another PR, I'd be happy to help you walk through the squash/rebase steps.  You could even submit a PR without even intending that it be merged - just to experiment if you like. Tag me if you want. We can chat as you do it or even hop on a call. Let me know.

**Comment by JoelBalmer** [comment]
@jbogarthyde, thanks for the encouragement although I'm not sure i have enough info to successfully submit a PR - I guess i could indeed write the code for a more substantive PR, but the commits might get deleted again, so maybe not!

@kapunahelewong, I thought I'd try following your document again on how to rebase and yeah same issue, but this time i tried to force push and now it's closed the PR automatically because no commits. So something in the process has removed my commits.

Anyways, i guess that's closed the PR for me! if I notice another issue with the docs down the line I'll ping you before submitting a PR in the first place, and maybe we'll get to the bottom of why that happened.

appreciate the effort and consideration though

**Comment by JoelBalmer** [comment]
FYI, looks like #33352 is the reason my commits were removed: 

> [rebase] will also skip any commits if it finds that the commits being added to the base identically match, in their content - commits that are already in the history - even if the hashes are different

[Source here](https://stackoverflow.com/questions/27117952/missing-commits-after-git-rebase).

I guess I did learn something after all!

**Comment by kapunahelewong** [comment]
ohhh, I didn't even know one could push 0 commits! We're looking into the depths of the git Mystery. 🧘🏻‍♂️
This is definitely new to me. So yes, please do hit me up if you decide to do another PR. And truly, a PR just to experiment is fine too. Thanks for all your hard work. 🌸

**Pull request closed without merging**
