### PR TITLE
fix(router): setTimeout to greater then 0 ...

### PR DESCRIPTION
**Pull request by dorje42**
to trigger in Firefox in a hybrid app (AngularJs and Angular) routing immediately, not every second route. 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #29113

## What is the new behavior?
Firefox is routing fine again, no more gaps between two routing.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jasonaden** [comment]
Interesting PR. But can you please provide more information on why this is needed? Also, most of the tests have broken with this change and would need to be adjusted.

**Review by jasonaden — CHANGES_REQUESTED** [review]
We need a test for this change.

Also, many tests have broken with this change being added.

Take a look at the [DEVELOPER](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md) docs to see how to set up your environment for running tests locally.

**Comment by dorje42** [comment]
@jasonaden You can find more information for this PR in #29113. Do you need more?

**Comment by atscott** [comment]
Closing as this change cannot be merged in its present state. There are too many unknowns here and changes need to be backed up by evidence. While the change may fix the immediate problem, it may break in other scenarios (worth noting that this change broke quite a few internal tests). Without knowing exactly why the change is needed, what the root cause of the issue is, and why navigation doesn't work in the current state, we can't justify or prove that this is the right thing to do.

**Pull request closed without merging**
