### PR TITLE
docs(aio): grammatical fix. remove duplicate word 'our'

### PR DESCRIPTION
**Pull request by souvikbasu**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: Documentation grammatical error
```

**What is the current behavior?** (You can also link to an open issue here)
Documentation mentions the word 'our' twice

**What is the new behavior?**
Replaced second occurrence of word 'our' with 'code'

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Review by wardbell — APPROVED** [review]
Thanks

**Comment by wardbell** [comment]
We both have CLAs.

**Comment by mhevery** [comment]
Fails circle CI, needs rabese

**Comment by wardbell** [comment]
Thanks. Sorry screwed up resolving merge conflicts.  See #16402

**Comment by gkalpak** [comment]
Sorry, I messed up trying to rebase this (and now that this was accidentally closed, I don't have the rights to force-push and fix it any more).
I re-applied the changes in #16405.

**Pull request closed without merging**
