### PR TITLE
docs(aio/content/marketing/resources.json): add We Are One Sàrl as onsite training

### PR DESCRIPTION
**Pull request by fduperier**
Adding We Are One Sàrl as an onsite training company in Switzerland.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[X] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]

**Comment by gkalpak** [comment]
@fduperier, can you please rebase this on latest master?

**Comment by gkalpak** [comment]
@fduperier, seems like you did a `merge` not a `rebase`, which create a merge commit (and causes linting to fail). This is not what we want. You need to do a `rebase`.
(E.g. reset to your commit (before the merge) and run `git pull --rebase upstream master` (assuming tht `upstream` points to `github.com/angular/angular`).)

**Comment by fduperier** [comment]
Actually I just click on resolve conflicts on github interface and then it created a merge... I'll try to fix that.

**Comment by gkalpak** [comment]
Oh, I didn't know GitHub can do that :smiley: Interesting...

**Comment by fduperier** [comment]
Sorry my mistake

**Pull request closed without merging**
