### PR TITLE
docs: add Hostman as a deployment option

### PR DESCRIPTION
**Pull request by alena-ko**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
Hi @alena-ko, it looks like you don't have CLA signed, so we can not proceed with this PR. Could you please have a look at the comment posted above (https://github.com/angular/angular/pull/41769#issuecomment-825008793) for instructions on how to sign CLA? Thank you.

**Comment by alena-ko** [comment]
Hey, I've already signed the CLA, please check
[image: image.png]

чт, 29 апр. 2021 г. в 01:53, Andrew Kushnir ***@***.***>:

**Comment by petebacondarwin** [comment]
@alena-ko - can you ensure that the email address you used to sign the CLA is the same as the one used in the commit?

**Comment by AndrewKushnir** [comment]
@alena-ko  the email used for your account ends with `@users.noreply.github.com` (looks like auto-generated by GitHub). As Pete mentioned above, please make sure that there is a correct email used in your GitHub account and try to rebase the commit (or re-create a PR), so that the committer email gets updated.

**Comment by alena-ko** [comment]
Thanks for your help. Made my email public in Git, made a new PR. Hope
everything is fine now.

чт, 29 апр. 2021 г. в 22:52, Andrew Kushnir ***@***.***>:

**Pull request closed without merging**
