### PR TITLE
fix(di): handle es2015 class instantiation

### LINKED ISSUE #7740: [ES6 support] Cannot reflectively construct classes in ES6 mode
Because we reflectively create instances of things defined as ES6 class and constructor, we get a Chrome error:
`constructor cannot be invoked without 'new'`

### PR DESCRIPTION
**Pull request by calebboyd**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
When using es2015 classes DI will fail to instantiate the resource
fixes #7740 

**What is the new behavior?**
Class is correctly instantiated using `Reflect.construct`

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by vicb — CHANGES_REQUESTED** [review]
Please add a test

**Comment by calebboyd** [comment]
@vicb, afaik there is no way to test this language level behaviour in es5 (I'm a way that would cause the previous version to fail). The code defers to to the documented `Reflect.construct` method and the factory creator (`.factory`) already has the test to verify its behaviour. -- to make a test we'd need to change to compile target.

**Comment by calebboyd** [comment]
Closed via #12099

**Comment by calebboyd** [comment]
@vicb Thanks for getting that in!

```

```

**Pull request closed without merging**
