### PR TITLE
build(npm): update rxjs to 2.0.0-beta.6

### PR DESCRIPTION
**Pull request by jeffbcross**
Note: this contains two commits from #8003 to make sure Travis will be green.

### CODE REVIEW

**Comment by jeffbcross** [comment]
I think I need to fix a couple of typings in `http`

**Comment by jeffbcross** [comment]
There are obscure Travis failures in environments I don't have time to troubleshoot right now, so please don't merge this unless someone can make it green.

**Comment by jeffbcross** [comment]
I'm going to try reproducing and fixing the Windows and Safari issues now

**Comment by jeffbcross** [comment]
@blesh had the idea that our `Symbol` problems are probably the result of RxJS no longer polyfilling `Symbol` as it did in beta.2, and our code in facade/lang.ts was assuming that `Symbol` had been polyfilled when calling `isPresent(Symbol)` in lang.ts: https://github.com/angular/angular/blob/cc86fee1d1e597a196c443c6bbcd9b10e539a9ba/modules/angular2/src/facade/lang.ts#L454

I changed that line to `if ('Symbol' in globalScope && isPresent(Symbol.iterator)) {`

**Comment by jeffbcross** [comment]
Got verbal LGTM from @alxhub 

@robertmesserle this will require updating internal version of Rx, which I can help with. It'd be great to get this landed before our next beta release.

**Comment by blesh** [comment]
@jeffbcross going forward, if you need to access `Symbol.observable` you'll want to use this module: https://www.npmjs.com/package/symbol-observable

**Comment by rkirov** [comment]
This is blocked on google internal ts1.9 upgrade. Will revisit after ng-conf.

**Comment by blesh** [comment]
Just noticed this: 

>  update rxjs to 2.0.0-beta.6

That would be a 3 major version downgrade.

**Comment by jeffbcross** [comment]
I'm going to rebase and get this thing ready for merge. We're not going to wait on G3. This is blocking some offline compiler work now.

**Comment by jeffbcross** [comment]
Thx @blesh fixed commit message :)

**Comment by jeffbcross** [comment]
READY TO MERGE!

**Comment by gdi2290** [comment]
:

**Pull request closed without merging**
