### PR TITLE
refactor(Router): rename RouteConfig to Routes

### LINKED ISSUE #7723: [Router] Rename `@RouteConfig` to `@Routes`
* **I'm submitting a ... **
[x] feature request

- Angular version: 2.0.0-beta.11
- Language: [all]

* **Other information**

`@RouteConfig()` should be renamed to `@Routes`. The former `@RouteConfig()` should be deprecated and will be removed in the future.

### PR DESCRIPTION
**Pull request by vicb**
- **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

The `@RouteConfig` annotation has been renamed to `@Routes` (`@RouteConfig` is still available for now but deprecated)
- **Other information**:

fixes #7723

RouteConfig is still supported but deprecated and will be removed in a future release.

### CODE REVIEW

**Comment by johnpapa** [comment]
Have you considered leaving `@RouteConfig`  in as well, as an alias?

**Comment by PascalPrecht** [comment]
@johnpapa 

> The @RouteConfig annotation has been renamed to @Routes (@RouteConfig is still available for now but deprecated)

**Comment by johnpapa** [comment]
yes, i read that :) I'm asking why not keep the alias

**Comment by zoechi** [comment]
Two different names for the same thing cause only confusion.

**Comment by ericmartinezr** [comment]
Finally! :tada: :tada:

**Comment by wardbell** [comment]
I vote for sweeping away all deprecated stuff before RC. Of course all laggard apps will go BOOM!

But, with enough warning, we can survive that and it would be great to enter release v.1 with a clean slate.

I agree with others who would rather not have aliases that cover for deprecations.

OFF TOPIC:
I like aliases that are permanent!  For example, I wish `*ngFor #item in list` were legal.  I get why `of` is preferred to `in` but that seems pedantic to me.

**Comment by brandonroberts** [comment]
:smile:

**Comment by petebacondarwin** [comment]
@vicb - this PR should update the Angular1 router bits too.

**Comment by vicb** [comment]
@petebacondarwin I have updated the Angular1 router, could you please check the changes. Thanks.

**Comment by petebacondarwin** [comment]
There are a couple more references to `RouteConfig` that need to be fixed:

* https://github.com/vicb/angular/blob/0322-routes/modules/angular2/test/router/route_config/route_config_spec.ts#L41
* https://github.com/vicb/angular/blob/0322-routes/typing_spec/router_spec.ts#L19

**Comment by mhevery** [comment]
@vicb please take care of https://github.com/angular/angular/pull/7726#issuecomment-200738244 and then it should be good to go.

**Comment by mhevery** [comment]
Waiting on other refactorings as part of the Router overhaul.

**Pull request closed without merging**
