### PR TITLE
refactor(core): remove disabled injectable-pipe migration

### PR DESCRIPTION
**Pull request by devversion**
Initially the plan was to have a migration that adds `@Injectable()` to
all pipes in a CLI project so that the pipes can be injected in Ivy
similarly to how it worked in view engine.

Due to the planned refactorings which ensure that `@Directive`, `@Component`
and `@Pipe` also have a factory definition that is picked up by the injector, this
migration is no longer needed for Ivy (FW-1468). Additionally since it is already disabled
(due to 572b54967c969c88c61970650fb857afc1d74f8a) and we have a more generic migration (known as `missing-injectable)`
that could do the same as `injectable-pipe`, we remove the migration from the code-base.

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM

**Review by kara — APPROVED** [review]
LGTM

**Comment by kara** [comment]
[presubmit](https://test.corp.google.com/ui#id=OCL:264184587:BASE:264184627:1566235516366:41c29bed)

**Comment by AndrewKushnir** [comment]
@devversion this PR had merge conflicts with patch branch, so I merged it to master only. Could you please create a new PR with the necessary changes against patch branch? Thank you.

**Pull request closed without merging**
