### PR TITLE
docs: replace from class hero to interface with accordance with #344022

### LINKED ISSUE #21186: docs(ToH): use interface instead of class to define the Hero model
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The ToH defines the Hero model using a **class**, but in the tutorial "instances" of this class arent created using the ctor of the class, promoting a bad practice. 

Furthermore the use of a class for this model is IMO inappropriate, as the class defines no behavior (methods). An interface would be better suited for this use case.

An example extracted from the tutorial:

```
class Hero {
  id: number,
  name: string,
}

const aHero: Hero = {
  id: 1,
  name: 'Superman'
}
````
Type checking will result in the following:

````
console.log(aHero instanceof Hero); //false
````

## Expected behavior
The Hero model should be defined using an **interface**.

## Minimal reproduction of the problem with instructions

Check the [ToH](https://angular.io/tutorial/toh-pt1#create-a-hero-class)

### PR DESCRIPTION
**Pull request by ajitsinghkaler**
Fixes #21186

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Small changes left in #344022

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 21186

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ajitsinghkaler** [comment]
@petebacondarwin can you please have a look at this

**Review by petebacondarwin — APPROVED** [review]

**Comment by ajitsinghkaler** [comment]
@kapunahelewong @petebacondarwin is there a error remaining in my pr.

**Comment by kapunahelewong** [comment]
@ajitsinghkaler, no, no errors in your PR. I had added the merge label without realizing that there were still people who need to review the change first, so I had to remove it. Everything's on track though. It just needs review by additional team members.

**Comment by ajitsinghkaler** [comment]
@kapunahelewong thanks for clearing it out.

**Comment by ajitsinghkaler** [comment]
@kapunahelewong it's been a week can you please help me get this reviewed

**Comment by kapunahelewong** [comment]
Hi @ajitsinghkaler, thanks for your patience. I've reached out to find the best way to make sure your PR gets in front of the right reviewers. In the meantime, I've added the `PR action: review` label so everyone knows it's ready.

**Comment by ajitsinghkaler** [comment]
Thanks @kapunahelewong

**Review by kapunahelewong — APPROVED** [review]

**Comment by kapunahelewong** [comment]
merge-assistance: Global approval for this docs-only change.

**Pull request closed without merging**
