### PR TITLE
build: update yarn 1.21.1

### PR DESCRIPTION
**Pull request by IgorMinar**

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by kara** [comment]
@IgorMinar Okay to merge this? It's still in draft mode

**Comment by IgorMinar** [comment]
merge-assistance: global approval

**Review by gkalpak — APPROVED** [review]

**Review by devversion — APPROVED** [review]

**Comment by kara** [comment]
Change reverted due to circle CI failures once it was merged into master, e.g. https://github.com/angular/angular/commit/b405942b0c44c999ea4006129ac38d387637da27

**Comment by gkalpak** [comment]
@googlebot I consent.

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
This should be good to go now (pending review).

##
I have added some more commits to make this change work on Windows jobs (and make these updates easier in the future).

You can see the Windows CI jobs running successfully with the changes in this PR [here][1].
<sub>I temporarily enabled the Windows jobs on PRs and then disabled again.</sub>

[1]: https://circleci.com/workflow-run/54f6f14c-b1ee-4b53-98c1-dad4fe545495

**Review by IgorMinar — COMMENTED** [review]
Lgtm. Thanks for the windows fixes @gkalpak

**Pull request closed without merging**
