### PR TITLE
ci(docs-infra): show custom 404 page on preview server (for consistency)

### PR DESCRIPTION
**Pull request by gkalpak**
☝️ 

<sub>(Hardly a fix, but wasn't sure what a better type would be.)</sub>

### CODE REVIEW

**Comment by alfaproject** [comment]
You are introducing new behavior, so a feature? d:

**Comment by gkalpak** [comment]
It is new behavior for the preview server (which is only used for PRs). There is no new behavior for the actual app.
Also, in a sense this is fixing the behavior of the preview server to be more consistent with the production hosting, so that we get a more accurate preview 🤷‍♂️

**Comment by petebacondarwin** [comment]
So perhaps it should be `ci` or `build`?

**Comment by petebacondarwin** [comment]
I'm not sure what difference this makes?

See https://pr26202-1dd3f31.ngbuilds.io//ggg/xxx (from a different PR) this appears to display our 404.

**Comment by gkalpak** [comment]
That URL is redirected to `index.html` (and does show the correct page). It's for URLs that don't get redirected (e.g. files): https://pr26202-1dd3f31.ngbuilds.io//ggg/xxx.yyy

**Comment by petebacondarwin** [comment]
Oh! OK. So at the moment we get a basic nginx 404 page.

screen shot 2018-10-05 at 11 58 33

But after this is merged we will get the custom one:

screen shot 2018-10-05 at 11 59 57

**Review by petebacondarwin — APPROVED** [review]

**Pull request closed without merging**
