### PR TITLE
docs: udpate the details

### PR DESCRIPTION
**Pull request by santoshyadavdev**
updating my twitter handle and bio as it is changed from
Angular and Web Tech to Angular also the
twitter handle is changed to SantoshYadavDev

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by santoshyadavdev** [comment]
Looks like size issue is a not related to this PR, as this should not impact it anyways,

**Comment by gkalpak** [comment]
Yes, this is a known flake (tracked in #37699). I restarted the CI job.

**Review by aikithoughts — APPROVED** [review]
LGTM!

Reviewed-for: global-docs-approvers

**Comment by santoshyadavdev** [comment]
Hi Team,
Can we get it merged.

**Review by kitti66 — CHANGES_REQUESTED** [review]
Okay

**Pull request closed without merging**
