### PR TITLE
docs: fix linter errors for property-binding-best-practices.md

### PR DESCRIPTION
**Pull request by dsnoeijer**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #47179

## What is the new behavior?
No more linter errors in the file.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by bob-watson — CHANGES_REQUESTED** [review]
Thanks for the edit!
Just one formatting suggestion to improve readability.

**Comment by dsnoeijer** [comment]
@bob-watson 
Done.

**Comment by bob-watson** [comment]
LGTM

reviewed-for: global-docs-approvers

**Review by bob-watson — APPROVED** [review]

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-core

**Comment by dylhunn** [comment]
Please @ me or Bob when this needs a merge label

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 5fbe40c2f438ad07b276ec46d8f95537388c8d72.

**Pull request closed without merging**
