### PR TITLE
docs(aio): fix -mm- to -MM- for month in DatePipe example

### PR DESCRIPTION
**Pull request by iwhp**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by vicb** [comment]
@ocombe please review

**Review by ocombe — APPROVED** [review]
Oh you're right thanks for catching this!

**Comment by ocombe** [comment]
Can you change your commit message please to `docs(common): fix date pipe examples format`

**Comment by jasonaden** [comment]
@iwhp Please fix your commit message to fix the lint error. Should be something like:

`docs(aio): fix -mm- to -MM- for month in DatePipe example`

**Comment by iwhp** [comment]
Since I cannot figure out how to change the commit message, I will close this PR and open a new one.

**Pull request closed without merging**
