### PR TITLE
fix(router): stricter typing for Route.pathMatch

### LINKED ISSUE #37469: router: stricter typing for Route.pathMatch
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description

`Route.pathMatch` field is now typed as `string | undefined` but actually it can accept `prefix` or `full` as a valid value.
I want to restrict invalid values statically at compilation step with a string literal types.

### Describe the solution you'd like

Typing `pathMatch` as `pathMatch?: 'prefix' | 'full'`

### Describe alternatives you've considered

This is a breaking change because it may cause build error by narrowing the acceptable value (even if those already have caused runtime error).

### PR DESCRIPTION
**Pull request by lacolaco**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #37469

## What is the new behavior?

```
interface Route {
  pathMatch?: 'prefix' | 'full';
}
```

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by atscott** [comment]
Hi @lacolaco, thanks for the PR to fix this. I've added this to our v11 candidates tracking. This is the right change, but would be breaking so we'll have to wait until the master branch is accepting changes for v11 to merge it.

**Review by IgorMinar — APPROVED** [review]
LGTM for v10.0 unless google3 reveals that this change breaks the world. If we don't manage to land this in time for v10, this will have to wait for v11 because if we use the strictest interpretation this is a breaking change. However it should be so rare and if it does break apps, it should only reveal pre-existing fatal bugs - for this reason I'm ok with this landing in v10.0.

Reviewed-for: public-api

**Comment by IgorMinar** [comment]
I'm labeling this as master&patch becase we don't yet have `target: rc` label.

**Review by atscott — APPROVED** [review]
Adding my LGTM as this is the right change, but it's still blocked since it's a breaking change and needs to target v11. We would also need to determine if we can get a migration for this or if g3 needs a patch to still accept `string`.

**Comment by Airblader** [comment]
Duplicate of #35950?

**Comment by atscott** [comment]
Duplicate of #35950

**Pull request closed without merging**
