### PR TITLE
refactor(platform-browser):remove unused code in dom sanitization ser…

### PR DESCRIPTION
**Pull request by ChellappanRajan**
Removed unused code in DomSanitizer service

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit d24d54bf693684ea842307540086b1b32bc3db6f.

**Pull request closed without merging**
