### PR TITLE
Add Discord Link Icon

### PR DESCRIPTION
**Pull request by Krapanshu-Tyagi**
[adev] Add Discord link icon in navigation menu

The angular.dev navigation menu includes the list of social media except the Discord one:

334120835-b8ce5fbb-46a7-4763-8ce6-f3fd76359721

I add a link icon for the discord server.

image

### CODE REVIEW

**Comment by JeanMeche** [comment]
@Krapanshu-Tyagi You need to reword the commit message itself, the PR title has no influence on the linter.

**Review by JeanMeche — CHANGES_REQUESTED** [review]
The icon isn't visible. 
Have you tried running the app with `yarn docs` ?

**Comment by Krapanshu-Tyagi** [comment]
I am sorry, it was my first time  contributing so, I am sure confused. But I will run it now and fix the problem. Thanks for your help.

**Comment by JeanMeche** [comment]
Thank you for your contribution, however another pull request already landed that change. 
Feel free to have a look at the https://github.com/angular/angular/labels/help%20wanted label for any other contributions.

**Pull request closed without merging**
