### PR TITLE
Empty the circular dependencies golden

### PR DESCRIPTION
**Pull request by alxhub**
Collection of commits which use `import type` to remove every existing circular dependency exception.

### CODE REVIEW

**Comment by thePunderWoman** [comment]
As soon as this lands, I'll add the new goldens for rhombular dependencies.

**Review by AndrewKushnir — APPROVED** [review]
Thanks for the cleanup 👍

**Comment by alxhub** [comment]
> As soon as this lands, I'll add the new goldens for rhombular dependencies.

Diamond dependencies are known to cause lots of problems, though...

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 4a0c6cd435be33437c4307caf61074cbaa7434a8.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
