### PR TITLE
test(upgrade): run tests against AngularJS v1.8.x as well

### PR DESCRIPTION
**Pull request by gkalpak**
☝️

### CODE REVIEW

**Comment by petebacondarwin** [comment]
> The commit message body does not meet the minimum length of 20 characters
🤣

**Review by petebacondarwin — APPROVED** [review]
LGTM - should we drop testing older versions now?

**Comment by gkalpak** [comment]
> should we drop testing older versions now?

Theoretically, ngUpgrade should remain compatible with AngularJS v1.5+. So, I would keep all versions (esp. since the extra cost seems low). Or maybe we could just keep v1.5 and the latest.

**Comment by petebacondarwin** [comment]
Happy to carry on testing if the cost is low

**Pull request closed without merging**
