### PR TITLE
docs: fix typo in sample

### LINKED ISSUE #33979: Typo in Reactive Form section
# 📚 Docs or angular.io bug report

### Description

The demo code was misspelled which makes readers confused in Step 4, Dynamic controls using form arrays, Reactive Form, Forms, Fundamentals. 

## 🔬 Minimal Reproduction

https://angular.io/guide/reactive-forms#step-4-displaying-the-form-array-in-the-template

### Expected vs Actual Behavior**

"address" => "alias"

## 📷Screenshot

Screen Shot 2019-11-22 at 12 19 16 pm

## 🔥 Exception or Error
<pre><code>

</code></pre>

### PR DESCRIPTION
**Pull request by Potapy4**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #33979

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Fixes #33979

### CODE REVIEW

**Review by antontemchenko — APPROVED** [review]

**Review by ajitsinghkaler — COMMENTED** [review]
@Potapy4  Can you please change add the details in the body and the issue no that is closed in the commit message

**Review by kapunahelewong — CHANGES_REQUESTED** [review]
Good catch, @Potapy4! Could you [amend the commit ](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit)so that it is like this:

```
docs: fix typo in sample

Fixes #33979
```

If you have any questions, let me know. Please tag me when you're ready.

**Comment by ajitsinghkaler** [comment]
thanks @kapunahelewong

**Comment by Potapy4** [comment]
> Good catch, @Potapy4! Could you [amend the commit ](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit)so that it is like this:
> 
> ```
> docs: fix typo in sample
> 
> Fixes #33979
> ```
> 
> If you have any questions, let me know. Please tag me when you're ready.

@kapunahelewong ready 🙂

**Review by kapunahelewong — APPROVED** [review]
Excellent, thank you, @Potapy4!

**Comment by kapunahelewong** [comment]
merge-assistance: Global approval for this docs-only change.

**Pull request closed without merging**
