### PR TITLE
fix(animations): make sure easing values work with web-animations

### LINKED ISSUE #15115: [4.0.0-rc.3]: Animations easing not working at all
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Easing doesn't work. I'm using cubic-bezier in my angular app, but i get a linear ease.

**Expected behavior**
That easing works just like ng2.

**Minimal reproduction of the problem with instructions**
http://embed.plnkr.co/G8JdPc8f9hQcA9OGCO6k/
```
@Component({
	animations: [
		trigger("drawerOpened", [
			state("yes", style({ display: "block", transform: "translate3d(0, 0, 0)" })),
			state("no-left", style({ display: "none", transform: "translate3d(-100%, 0, 0)" })),
			state("no-right", style({ display: "none", transform: "translate3d(100%, 0, 0)" })),
			transition("* => yes", animate("240ms cubic-bezier(0.0,0.0,0.2,1.0)")),
			transition("yes => *", animate("240ms cubic-bezier(0.4,0.0,1.0,1.0)"))
		])
	],
	selector: "id-navigation-drawer",
	templateUrl: "./navigation-drawer.component.html",
	styleUrls: ["./navigation-drawer.component.scss"]
})
```

**What is the motivation / use case for changing the behavior?**
It worked in ng2.

**Please tell us about your environment:**
Windows, PHPStorm Public Preview and @angular/cli for serving to Google Chrome.

* **Angular version:** 4.0.0-rc.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

### PR DESCRIPTION
**Pull request by matsko**
Closes #15115

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by nicky-lenaers** [comment]
i need this one so bad 👍  will it be in `rc.5`?

**Comment by naveedahmed1** [comment]
Was it fixed in Angular 4 Rc5? I am still having this issue with Angular 4.0.0-rc.5

**Comment by d3viant0ne** [comment]
@naveedahmed1 - https://github.com/angular/angular/blob/master/CHANGELOG.md#400-rc5-2017-03-17

**Comment by naveedahmed1** [comment]
Nothing mentioned about it, I hope it will be the part of next release RC/Final

**Pull request closed without merging**
