### PR TITLE
build: remove unused deps

### PR DESCRIPTION
**Pull request by JeanMeche**
* All `@types` package removed have typings in their package.
* brotli is unused
* tmp is unused
* vlq is unused

## PR Type
What kind of change does this PR introduce?

- [x] Build related changes

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by alan-agius4** [comment]
@JeanMeche can you please rebase?

**Review by tokidev-ai — APPROVED** [review]
Looks good! Thank you

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by alxhub** [comment]
This PR was merged into the repository by commit e60b3d45b9d5089e58b671dfdfe5bc29637860cd.

**Pull request closed without merging**
