### PR TITLE
build: sync all lock file and `package.json` updates from next with patch

### PR DESCRIPTION
**Pull request by devversion**
With the goal of avoiding more conflicts with build changes that should
go into both patch + next in general, this commit brings the lock files + `package.json` files from patch branch to the equivalent contents of the next branch, except for the actual `version` field.

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: global-approvers

**Comment by josephperrott** [comment]
@googlebot I consent

**Comment by atscott** [comment]
This PR was merged into the repository by commit 1ace7d4f38bafc43831387b2e026369e2a90d5dd.

**Pull request closed without merging**
