### PR TITLE
fix(core): use presence of .subscribe to detect observables rather than Symbol.observable

### LINKED ISSUE #14298: 4.0.0 beta6 @angular/core.umd global.rxjs_symbol_observable error
```
[ x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
script error:  `Cannot read property '$$observable' of undefined , `

error in 
```javascript
function isObservable(obj) {
  return !!(obj && obj[rxjs_symbol_observable.$$observable]);
}
```

because:

```javascript
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('rxjs/symbol/observable'), require('rxjs/Subject'), require('rxjs/Observable')) :
    typeof define === 'function' && define.amd ? define(['exports', 'rxjs/symbol/observable', 'rxjs/Subject', 'rxjs/Observable'], factory) :
    (factory((global.ng = global.ng || {}, global.ng.core = global.ng.core || {}),global.rxjs_symbol_observable,global.Rx,global.Rx));
}(this, function (exports,rxjs_symbol_observable,rxjs_Subject,rxjs_Observable) { 'use strict';
```

that `global.rxjs_symbol_observable` is undefined.

**Expected behavior**
right run.

**How to fix?**

Adjust the rollup.config, add `symbol_observable` alias.

Need to : `global.Rx.Symbol`

### LINKED ISSUE #14473: core.umd.js isObservable always return false
```
[ x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
`isObservable ` always return false

**Expected behavior**
Correct execution

```javascript
function isObservable(obj) {
        return !!(obj && obj[rxjs_symbol_observable.$$observable]);
    }
```

that `rxjs_symbol_observable.$$observable` is undefined, should update to `rxjs_symbol_observable.observable`

* **Angular version:** v4.0.0-beta.7
* **Language:** [ TypeScript 2.1.6 ]

### LINKED ISSUE #14926: 4.0.0-rc.2 - es5 - CanDeactivate with EventEmitter
**I'm submitting a ...**  (check one with "x")

[ * ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 

**Current behavior**
CanDeactivate does not work with EventEmitter !

**Expected behavior**
CanDeactivate should work with true/false and with EventEmitter

**Minimal reproduction of the problem with instructions**
https://embed.plnkr.co/tPtY1a31CnFqhNbzVViU/
--> Unable to return to Home when List Displayed

**What is the motivation / use case for changing the behavior?**
CanDeactivate should work with true/false and with EventEmitter

**Please tell us about your environment:**
Windows 7 / VisualCode / NPM / Express

* **Angular version:** 2.0.X
4.0.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

* **Node (for AoT issues):** `node --version` =   
Not concerned

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Fixes #14298
Fixes #14473
Fixes #14926

cc @jasonaden

### CODE REVIEW

**Comment by jasonaden** [comment]
LGTM

**Comment by jasonaden** [comment]
@DzmitryShylovich can you fix the build?

**Comment by DzmitryShylovich** [comment]
> Error at /home/travis/build/angular/angular/e2e_test.1489600382/src/module.ts:23:17: 'Named' is declared but never used.

it's not related to my pr. I also have the same error here https://github.com/angular/angular/pull/14679

**Comment by DzmitryShylovich** [comment]
looks like it was introduced here https://github.com/angular/angular/pull/14894
cc @chuckjaz

**Comment by chuckjaz** [comment]
@DzmitryShylovich This is now fixed in master.

**Comment by jasonaden** [comment]
@DzmitryShylovich Please rebase and push.

**Review by vicb — APPROVED** [review]

**Comment by DzmitryShylovich** [comment]
@jasonaden rebased, but it failed again because of the unrelated issue with docs 😄

**Comment by jasonaden** [comment]
@DzmitryShylovich Saw that. Caretaker will get this in. Thanks for the fix!

**Review by IgorMinar — APPROVED** [review]
I think this is fine as a temporary workaround

**Comment by DzmitryShylovich** [comment]
@jasonaden @IgorMinar looks like it will be fixed soon https://github.com/ReactiveX/rxjs/pull/2435#issuecomment-286903366

**Comment by trotyl** [comment]
@vicb @IgorMinar Should this workaround be reverted in favor of rxjs v6? There're no more path-mapping for sub paths.

**Comment by jasonaden** [comment]
Good question. I'll check on that.

**Comment by benlesh** [comment]
FYI: I have a PR in RxJS to do just this: https://github.com/ReactiveX/rxjs/pull/3628

It's a new feature, so it'll be 6.1

**Pull request merged**
