### PR TITLE
docs: tutorial url on tutorials/first-app/http page fixed

### LINKED ISSUE #53122: tutorials url
### Describe the problem that you experienced

on page, https://angular.dev/tutorials/first-app/http

https://angular.dev/tutorial is missing an 's'
should be: https://angular.dev/tutorials

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/http

### Describe what you were looking for in the documentation

_No response_

### Describe the actions that led you to experience the problem

_No response_

### Describe what you want to experience that would fix the problem

_No response_

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by baranyit**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The url is misspelled on the bottom of the page:
```[tutorials](tutorial)```

Issue Number: fixes #53122

## What is the new behavior?
Fixed url:
```[tutorials](tutorials)```

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, can you reword the commit to follow our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit). It should be `doc: ...` (without scope).

**Comment by baranyit** [comment]
> Hi, can you reword the commit to follow our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit). It should be `doc: ...` (without scope).

Sorry about mistake, fixed.

**Comment by JeanMeche** [comment]
Sorry, this one is on my own, it should be `docs: ...` instead of `doc: ... `

**Comment by baranyit** [comment]
> Sorry, this one is on my own, it should be `docs: ...` instead of `doc: ... `

No problem, fixed...

**Review by JeanMeche — APPROVED** [review]
LGTM

**Review by twerske — APPROVED** [review]

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit cf507d5cc895f48b357d0f7db67967de3bbeb71e.

**Pull request closed without merging**
