### PR TITLE
fix(aio): alert, subsection and callout width fix

### PR DESCRIPTION
**Pull request by sjtrimble**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the new behavior?**
Callout sections set to 100% width include `l-sub-section`s and `alert`s

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by wardbell** [comment]
@sjtrimble Can you point to a place in a doc where we can see this? Would make it easier to review.

**Comment by sjtrimble** [comment]
@wardbell One example: https://aio-staging.firebaseapp.com/tutorial/toh-pt2#style-the-selected-hero

screen shot 2017-06-07 at 10 58 09 am

> Note the `l-sub-section` that is shorter than the rest of the content.

**Comment by IgorMinar** [comment]
The new version however sticks pass the code snippet elements. Can we make the callouts the same width as code snippets?

screen shot 2017-06-08 at 12 52 51 am

**Review by IgorMinar — CHANGES_REQUESTED** [review]
please align the with with code snippet boxes

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
thanks @sjtrimble

**Comment by sjtrimble** [comment]
@IgorMinar already did it.. hope that's ok

**Pull request merged**
