### PR TITLE
fix: changed behavior of markAsTouched and markAsDirty

### PR DESCRIPTION
**Pull request by RCnowak**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

When you call `form.markAsTouched()` nested controls are still untouched. It's the same for markAsDirty. 

Issue Number: N/A

## What is the new behavior?
When you mark form as dirty or touched children controls react on this

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

I think it can break smth for people who rely on current behavior, but it seems non-logical in my opinion.

## Other information
P.S. sorry for my English. I just wanted to resolve such issues https://github.com/angular/angular/issues/11774 . Current behavior makes me crazy. I dont want to write recursive function every time.

### CODE REVIEW

**Comment by RCnowak** [comment]
I signed it!

**Comment by RCnowak** [comment]
I signed it!

**Comment by RCnowak** [comment]
I've done too much commits for it :( Should I recreate pull request? 

And what's wrong with travis-ci? Smth fails but I cant understand what exactly

**Comment by kara** [comment]
@RCnowak Thanks for taking the time to submit a PR. Unfortunately, the change you're proposing would be breaking, and it is already working as intended. See [this comment](https://github.com/angular/angular/issues/11774#issuecomment-253396201) for context. 

That said, there is an open feature request for adding a new `markAllTouched` method [here](https://github.com/angular/angular/issues/19400) if you'd like to tackle that instead in a new PR.

**Pull request closed without merging**
