### PR TITLE
docs(aio): fix typo in filename (packages.json --> package.json)

### PR DESCRIPTION
**Pull request by marcelosdm**
docs(aio): fix typo in filename (packages.json --> package.json)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by marcelosdm** [comment]
I signed it

**Review by gkalpak — APPROVED** [review]
👍

**Comment by gkalpak** [comment]
Good catch! Can you please update the commit message to follow our [guidelines][1]. E.g. something like:

> docs(aio): fix typo in filename (packages.json --> package.json)

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by marcelosdm** [comment]
@gkalpak, thanks for the feedback!
I tried to change the commit message, but I don't know if I did it right. Could you please check it up?

**Comment by gkalpak** [comment]
You have updated the PR title, but not the commit message :smiley:

I assume you have created the PR via the GitHub web-interface. In order to update the commit message, you would need to clone your fork of the repository on your machine, make the change and push again to GitHub (via the command-line or an app for managing git repositories).
It is a lot of work just for updating a commit message. (Things are much better if you already have cloned the repo and created the PR from your local machine.)

Let me do it for you. In case you are wondering, here is how you could do it via the command line:

```
# Clone your fork of the angular repository.
git clone https://github.com/marcelosdm/angular.git
cd angular

# Checkout the branch associated to this PR.
git fetch origin patch-2
git checkout -b patch-2 FETCH_HEAD

# Change the commit message.
git commit --amend
# ...an editor will open with the old commit message for you to edit and save...

# Push the changes back to GitHub.
git push --force-with-lease --set-upstream origin patch-2
```

**Comment by marcelosdm** [comment]
@gkalpak thank you so much friend! Next time I'll be smart and clone the fork to my machine!

**Pull request closed without merging**
