### PR TITLE
docs: fix typos in first app tutorial

### PR DESCRIPTION
**Pull request by bampakoa**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by bampakoa** [comment]
@AndrewKushnir upon reviewing this PR, could you please check out the following line? 

https://github.com/angular/angular/blob/d6d0956f4d3e194468c6d8c66a62e706ba58db7d/aio/content/tutorial/first-app/index.md?plain=1#L85

I am not sure that this is valid. Maybe it meant to refer to the `ng --version` command instead?

**Comment by AndrewKushnir** [comment]
> upon reviewing this PR, could you please check out the following line?

@bampakoa thanks for noticing this 👍 I think we should remove that line (as you pointed out, it's only displayed when `ng --version` is invoked). Could you please remove that line as a part of this PR?

Thank you.

**Comment by bampakoa** [comment]
@AndrewKushnir this is ready.

**Review by AndrewKushnir — APPROVED** [review]

**Comment by dylhunn** [comment]
(needs rebase)

**Comment by bampakoa** [comment]
@dylhunn this is ready.

**Review by AndrewKushnir — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 319aa76a8f6913f8c6f9ed3205bc9ab34fd084b6.

**Pull request closed without merging**
