### PR TITLE
docs: fixed typo in toh-pt5.md

### PR DESCRIPTION
**Pull request by tk3369**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by tk3369** [comment]
commit message amended, thanks @kapunahelewong

**Comment by kapunahelewong** [comment]
Thank you, @tk3369! The commit message looks good. Could you rebase to make sure it's up-to-date? Here's [my workflow for rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase). It might also help it pass those checks it failed. If you have any questions on rebasing, I'm happy to help you out. Please tag me when you're ready. Thanks for all of this!

**Comment by tk3369** [comment]
Rebased as requested.

**Comment by tk3369** [comment]
@kapunahelewong

**Review by kapunahelewong — APPROVED** [review]
LGTM. Thank you, @tk3369!!

**Comment by kapunahelewong** [comment]
Care taker, this is a docs only change. Thank you!

**Pull request closed without merging**
