### PR TITLE
chore(gulp): print dart & pub versions

### PR DESCRIPTION
**Pull request by vicb**
yep, `stderr`.

Might help troubleshooting build issues, ref #2585 

/cc @PascalPrecht

[Review on Reviewable](https://reviewable.io/reviews/angular/angular/2587)

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Why not, but we've got this info on TravisCI:

> Dart SDK detected:
- dart: Dart VM version: 1.11.0-dev.5.2 (Thu Jun 11 07:28:36 2015) on "linux_x64"
- pub: Pub 1.11.0-dev.5.2

and people can check their local config.

I think this is a good idea if time-impact is negligible (is it?), since our build is getting slow already....

**Comment by vicb** [comment]
```
$ time dart --version
Dart VM version: 1.10.0-dev.1.10 (Thu Apr 23 01:11:08 2015) on "linux_x64"

real	0m0.002s
user	0m0.000s
sys	0m0.000s

$ time pub --version
Pub 1.10.0-dev.1.10

real	0m0.181s
user	0m0.196s
sys	0m0.004s
```

**Comment by vicb** [comment]
Not sure if this deserves to be merged ?

**Comment by vicb** [comment]
@pkozlowski-opensource had the idea to create a separate task for that. I think it's a great idea, I'll update accordingly.

**Comment by PascalPrecht** [comment]
@pkozlowski-opensource we might have it on travis. Unfortunately, I wasn't even able to build the project locally because of a broken pub version. 

So I think having something like this locally would be helpful in any case. :)

**Comment by vicb** [comment]
Oh sorry, we had offline discussions with Pawel about this. The idea was to create a separate gulp task (that could be executed locally) instead of having it part of the Dart SDK detection.

So yeah it would be available locally but only on-demand.

**Comment by PascalPrecht** [comment]
SG!

**Comment by vicb** [comment]
@IgorMinar could you please review ?

**Comment by jeffbcross** [comment]
@vicb LGTM

**Comment by vicb** [comment]
@jeffbcross thanks for the review. Landed as f020a5cdea707bd1c286cc8d37385c97acebe2c5

**Comment by IgorMinar** [comment]
Sorry, missed this earlier.

Would it make sense do something similar to how we check and warn about incompatible node/npm versions?

**Comment by vicb** [comment]
This is probably good enough for now to debug env issues plus we can set a minimum SDK version in the pubspec file.

**Pull request closed without merging**
