### PR TITLE
docs(forms): clarify note in reactive forms doc

### PR DESCRIPTION
**Pull request by kapunahelewong**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #20058 

## What is the new behavior?
Change `formGroupName` to `[formGroup]`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by kapunahelewong** [comment]
@kara Would you review when you get a chance? Thank you!

**Review by kara — APPROVED** [review]
LGTM

**Comment by IgorMinar** [comment]
please update the commit message. see https://github.com/angular/angular/pull/21110#issuecomment-353691608

**Comment by IgorMinar** [comment]
@kara I shouldn't need to approve this particular PR. Can you please send a PR that adds forms tutorial and guide md files to the existing forms group? thanks!

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
@kara I shouldn't need to approve this particular PR. Can you please send a PR that adds forms tutorial and guide md files to the existing forms group? thanks!

**Comment by alexeagle** [comment]
Haven't been able to get a green build here. Same reason as the other recent PR?

**Comment by kapunahelewong** [comment]
@alexeagle I can rebase, but I see the tests are running. I can hold on pushing until we see if it fails.

**Pull request closed without merging**
