### PR TITLE
chore(core): mute mode printing in console in prod mode

### PR DESCRIPTION
**Pull request by samjulien**
Issue #6540. Talked with @robwormald briefly and he suggested simply muting that logging if not in dev mode.

### CODE REVIEW

**Comment by vsavkin** [comment]
@samjulien  Could you fix TravisCi?

**Comment by samjulien** [comment]
Ugh, I apologize @vsavkin, I accidentally made the merge commit with my work email which caused the CLA check to fail. Trying to figure out how to reset and redo. Not sure why the CI and tests failed though.

**Comment by samjulien** [comment]
I think I need to rebase from master. Stand by.

**Comment by samjulien** [comment]
CircleCI is failing on npm install, Travis is failing on some dart issues. Any ideas @valorkin?

**Comment by samjulien** [comment]
Closing this PR due to the hilariously botched rebase. Will resubmit.

**Pull request closed without merging**
