### PR TITLE
fix(dev-tools): use a shared angular detection code

### LINKED ISSUE #51565: Chrome toolbar icon reports wrong app mode in Firebase Console
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

1. Navigate to Firebase Console
2. Click on the Extensions button and pin Angular DevTools
3. Click the Angular DevTools button in the Chrome toolbar

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

The message displayed should indicate that the application is running in production mode:

>Angular application running in production mode. We recommend using DevTools with apps in dev mode, running ng serve.

Instead it says:

>Angular application running development mode. Open developer tools, and select the Angular tab.

### Please provide a screenshot if possible [Bug Report only]

image

### Please provide the exception or error you saw [Bug Report only]

_No response_

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

_No response_

### Description [Feature Request only]

_No response_

### Proposed solution [Feature Request only]

_No response_

### Alternatives considered [Feature Request only]

_No response_

### LINKED ISSUE #51566: Angular language Service not supporting Visual Studio Code for the Web
### Which @angular/* package(s) are relevant/related to the feature request?

language-service

### Description

if I open any Angular projects in GitHub with VS Code Web. And try to install the extension it is showing warning "The 'Angular Language Service' extension is not available in Visual Studio Code for the Web".

image

### Proposed solution

It is better to support Language Service for Web for better usability.

### Alternatives considered

Currently don't have

### PR DESCRIPTION
**Pull request by JeanMeche**
This fixes an issue where an angular app exposes a global `ng` object that is not our `ng`.

fixes #51565

### CODE REVIEW

**Comment by atscott** [comment]
@JeanMeche I think you may have tagged the wrong issue. There would be quite a bit of investigation and work needed in order to resolve that: https://code.visualstudio.com/api/extension-guides/web-extensions

**Comment by JeanMeche** [comment]
@atscott You're right, it's a fix for #51565 !

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by AleksanderBodurri — APPROVED** [review]
Looks great, thanks @JeanMeche 🙏

**Comment by ducin** [comment]
all criteria within this one seems to be met, but the PR is stuck. What a pity!
_Waiting to check until the pull request is ready_ - @JeanMeche can you mark it as ready?
@josephperrott @AleksanderBodurri can you remove the `action: review` tag to unlock this one?

**Pull request closed without merging**
