### PR TITLE
fix(RouterLink): do not prevent default behavior if target set on anc…

### LINKED ISSUE #4233: bug(router): target attribute not respected when used with router-link
```html
<a [router-link]="['/account']" target="_blank">Account</a>
```

The expectation is that this link should open in a separate tab/window.

Tracks internal b/24125739.

### PR DESCRIPTION
**Pull request by jeffbcross**
…hor element

If the anchor element on which the "router-link" directive is present has a target
attribute other than "_self," the handler will not prevent default behavior of
the browser.

Closes #4233

### CODE REVIEW

**Comment by jeffbcross** [comment]
I forgot that we don't have the reverse-lookup enum support enabled in ts2dart :/. https://github.com/angular/ts2dart/issues/221

**Comment by jeffbcross** [comment]
I'll update this not to use enums.

**Comment by btford** [comment]
Other than the enum thing, LGTM. Merge once that fix is in :+1:

**Comment by jeffbcross** [comment]
(I got verbal LGTM of recent changes from @btford)

**Comment by btford** [comment]
(confirming said verbal LGTM, also thanks for your work on this, @jeffbcross )

**Pull request closed without merging**
