### PR TITLE
docs: add html template for sizer component in template syntax guide

### LINKED ISSUE #33771: Sizer component does not have template in Basics of two-way binding
# 📚 Docs or angular.io bug report

### Description

There is a code snippet for the `size.component.ts` in "Fundamentals > Components & Templates > Template Syntax > Basics of two-way binding": https://angular.io/guide/template-syntax#basics-of-two-way-binding

This component references an html template but no equivalent code snippet is provided. However a template can be found in previous version of the docs: https://v7.angular.io/guide/template-syntax#two-way-binding---

A code snippet named `sizer.component.html` should display the html template.

### What's the affected URL?**

https://angular.io/guide/template-syntax#basics-of-two-way-binding

## 📷Screenshot

image

image

### Anything else relevant?

I can create a PR to reference the html template once this issue has gone through triage.

### PR DESCRIPTION
**Pull request by DiscoPYF**
fixes #33771

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #33771

The code example for the sizer component (`src/app/sizer.component.ts`) is missing the html template in the "Template Syntax" guide.

## What is the new behavior?

A code example has been added to display the html template (`src/app/sizer.component.html`) of the sizer component in the "Template Syntax" guide.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This is my first contribution. Let me know if I missed something.

I followed the instructions mentioned in the [aio/README.md](https://github.com/angular/angular/blob/master/aio/README.md) and in the [Angular Documentation Style Guide](https://angular.io/guide/docs-style-guide).
I ran `yarn setup` and `yarn serve-and-sync` to make sure that the changes work as expected.

### CODE REVIEW

**Review by kapunahelewong — APPROVED** [review]
Nice addition. Thank you, @DiscoPYF!

**Comment by AndrewKushnir** [comment]
FYI, I rebased this PR, since CI got stuck for some reasons (rebasing triggered a new CI run). Thank you.

**Comment by kapunahelewong** [comment]
merge-assistance: Global approval for this docs-only change.

**Comment by DiscoPYF** [comment]
Thank you. I'm glad I was able to contribute, even if only a little.

**Comment by kapunahelewong** [comment]
Every bit counts, @DiscoPYF. 😊If you submit any more docs PRs, please tag me. I'm happy to help you. Thanks again 🌸

**Pull request closed without merging**
