### PR TITLE
docs(examples): add empty examples directory for api docs examples

### PR DESCRIPTION
**Pull request by IgorMinar**
This is a place for api docs examples hand written in an idiomatic way.

### CODE REVIEW

**Comment by IgorMinar** [comment]
cc: @btford @naomiblack

**Comment by btford** [comment]
LGTM

**Comment by rkirov** [comment]
Why not rename `modules/examples` in the same PR to avoid confusion in the meantime.

Why `modules/angular2/examples` instead of `modules/examples`? Being inside `angular2` means we would publish examples to `npm` as part of publishing angular2 (which might be desirable).

Also a reminder for the example writers to use the bundles unlike our current `examples`.

**Comment by btford** [comment]
>  Being inside angular2 means we would publish examples to npm as part of publishing angular2 

I assumed that was the intent

**Pull request closed without merging**
