### PR TITLE
docs: typo fix

### PR DESCRIPTION
**Pull request by maksymiliansielicki**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
It just fixes a typo.

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ x] Other... Please describe: fixing a typo

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by maxmeister** [comment]
@googlebot I signed it!

**Comment by kapunahelewong** [comment]
Thank you very much for this PR, @maxmeister, but this typo was fixed in https://github.com/angular/angular/pull/35907. Would you be interested in submitting another fix of similar scope? If so I could help you find one. Just let me know. 🙂

**Comment by maxmeister** [comment]
@kapunahelewong Sure, I'd love to contribute to Angular!

**Comment by kapunahelewong** [comment]
Yay @maxmeister! How about this? In https://github.com/angular/angular/blob/master/aio/content/guide/dependency-injection-providers.md there is an instance of "let's say" (line 200) and "we" (line 204), but we're supposed to keep the docs in second or third person. "Let's say" could change to "Imagine that" (or something along those lines) and "we" could just be deleted.  What do you think?

**Pull request closed without merging**
