### PR TITLE
docs(aio): add Mashhood Rastgar to GDE resources

### PR DESCRIPTION
**Pull request by mashhoodr**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Updates GDE information in the documentation

### CODE REVIEW

**Comment by mashhoodr** [comment]
@StephenFluin build keeps failing on this (recreated the PR) - any suggestions on what I can do?

**Comment by gkalpak** [comment]
Don't worry about the Travis failure. It is unrelated to this PR.

**Review by StephenFluin — APPROVED** [review]

**Comment by trotyl** [comment]
Should use rebase...

**Comment by mashhoodr** [comment]
@trotyl can you please guide me on how do this here? Can this be fixed in the current PR?

**Comment by trotyl** [comment]
I think it could be fixed by:

```
# drop the merge commit
git reset --hard HEAD~1

# update master to latest
git checkout master
git pull upstream master

# rebase on master
git checkout upstream  # real bad branch naming
git rebase master

# update this PR
git push origin upstream --force
```

**Comment by mashhoodr** [comment]
Thanks @trotyl - updated

**Comment by mashhoodr** [comment]
Anything else needed from my side here?

**Pull request closed without merging**
