### PR TITLE
refactor(compiler): remove unused files in css_parser/ and corresponding spec tests

### PR DESCRIPTION
**Pull request by ngwattcos**
remove unused files in css_parser/ and corresponding spec tests

Reasons for change:
- css_parser, css_ast, and css_lexer are not used anywhere and there are
no entry points from compiler.ts
- besides several refactors, files in css_parser/ have been been changed since 2017 (when they were copied over), which means this is very likely dead code

Testing
- tested by building Angular and building/running aio with build-local

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by ngwattcos** [comment]
@googlebot I signed it!

**Comment by kseamon** [comment]
LGTM

**Review by gkalpak — APPROVED** [review]

**Comment by jelbourn** [comment]
@ngwattcos could you rebase this PR so that CI can run?

**Review by petebacondarwin — APPROVED** [review]
LGTM.

**Review by jelbourn — APPROVED** [review]
LGTM, using global approvers since this is a straightforward cleanup

Reviewed-for: global-approvers

**Pull request closed without merging**
