### PR TITLE
docs: use language-agnostic links for external docs

### PR DESCRIPTION
**Pull request by bampakoa**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
This PR touches a lot of files in `adev` so please let me know if this is not the correct way to approach changes 🙂

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Thanks for the changes, could you make a those changes in a single PR with #56375 (you could close the other one). I'll ease the caretaker work. Thank you.

**Comment by bampakoa** [comment]
@JeanMeche thanks for the help 🙂 I have noticed similar links to comments in the actual source code as well but did not know if I should update them also. Let me know if I could help on that also!

**Review by JeanMeche — APPROVED** [review]

**Comment by JeanMeche** [comment]
I don't think that necessary for the code itself, thank for the changes.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 54170cd60d56767a6b678fe10851f5573fa79702.

The changes were merged into the following branches: main, 18.0.x

**Pull request closed without merging**
