### PR TITLE
docs: add Brooke Avery to GDE resources 

### PR DESCRIPTION
**Pull request by bravery08**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by twerske — APPROVED** [review]
welcome!

**Comment by pkozlowski-opensource** [comment]
@bravery08 this PR will require some cleanup before it can get merged:
* you need to sign the CLA 
* the commit message will need update to follow our guidelines, see https://app.circleci.com/pipelines/github/angular/angular/52619/workflows/5ec0aceb-5146-46c9-a460-bc679567403b/jobs/1248402

**Comment by bravery08** [comment]
Hi Pawel!

Thanks for letting me know about my commit message. I believe I was able to
fix it. I copied what I saw from Tomas Trajan's example. Here was the
example I referred to and what my commit message looks like now:

[image: image.png]

[image: image.png]

Did I do it correctly this time?

Also, I did sign the CLA a few days ago. Is it still showing on your end
that I haven't signed it?

[image: image.png]

Hopefully I have everything correct and taken care of but please let me
know if not.

Thank you so much for your help!

**Comment by bravery08** [comment]
Hi Pawel -

Just following up on my previous email.

Were we able to get my commit message resolved?

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 2009b578883ac4def497e6f5638382f555c0e472.

**Pull request closed without merging**
