### PR TITLE
refactor: move platform-browser/animations to animations/browser

### PR DESCRIPTION
**Pull request by jasonaden**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by DzmitryShylovich** [comment]
@jasonaden are there any plans to remove [dsl.ts](https://github.com/angular/angular/blob/master/packages/core/src/animation/dsl.ts) file?

**Comment by matsko** [comment]
LGTM

**Comment by jasonaden** [comment]
@DzmitryShylovich Yes, that will be removed.

cc: @matsko

**Comment by chuckjaz** [comment]
https://github.com/angular/angular/commit/21a18d6cebd1214b12f435fd18d9607c10cd3ba3

**Pull request closed without merging**
