### PR TITLE
fix(zone.js): Closes #31686, patch shadydom

### LINKED ISSUE #31686: webapis-shadydom.js breaks IE11
When integrating the ShadyDOM polyfill in an Angular 7, the routing in Edge breaks but IE11 just works. To fix this one can include `webapis-shadydom.js`. In that case Edge works fine but IE11 breaks.

Without `webapis-shadydom.js` in Edge:
  - Navigating works one time. 
  - Every attempt at navigating triggers the warning `Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?`
  - Subsequent navigation attempts are failing. The current path remains unchanged.

With `webapis-shadydom.js` in IE11:
  - Navigation does not work at all.

The navigation is done via `routerLink`.

Firefox, Chrome and Safari work regardless.

Here are projects that recreate the discribed behavior:

  - with `webapis-shadydom.js`: https://stackblitz.com/edit/czee42-bug-ie11
  - without `webapis-shadydom.js`:https://stackblitz.com/edit/czee42-bug-edge

### PR DESCRIPTION
**Pull request by JiaLiPassion**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31686 
`@webcomponents/shadydom` polyfills will not work well with `webapis-shadydom` of zone.

## What is the new behavior?
shadydom will work fine with polyfill in IE and Edge.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
Why no test?

**Comment by mhevery** [comment]
http://test/OCL:259422510:BASE:259422529:1563835592907:c48ba53a

**Comment by JiaLiPassion** [comment]
@mhevery, I tested with a sample application locally, I will add unit tests with this one. thanks!

**Comment by JiaLiPassion** [comment]
@mhevery, I added test and make some refactor of the `bazel karma rule` to support `normal browser test` and `shadydom test`. please review, thanks.

**Pull request closed without merging**
