### PR TITLE
[WIP] feat(NgZone): add support for a user provided NgZone

### LINKED ISSUE #2683: Angular should throw when zone.js is not present
Currently, the application will bootstrap, and the first digest will run successfully. But after that the application will stop reacting to changes, which is extremely confusing.

### PR DESCRIPTION
**Pull request by vicb**
fixes #2683 

TODO:
- [ ] add unit tests,
- [ ] create a fake zone for CJS tests (now that the `_disabled` flag has been removed)

### CODE REVIEW

**Comment by vicb** [comment]
PR blocked: I could not find a way to have a cjs specific version of `NgZoneImp` (as using a .cjs extension is not working any more)

**Comment by tbosch** [comment]
@vicb What is the status here?

**Comment by vicb** [comment]
@tbosch I'll resume working on this when I'm done with the doc. However I still do not know how to have a cjs specific override, see my comment above.

**Comment by mhevery** [comment]
any update?

**Comment by vicb** [comment]
I can check the cjs thing. 

Is the bootstrap being refactored ? when ?

**Comment by mhevery** [comment]
we already have `platform().application().component()`, we need to create `platform` imports. Should be happening next week.

**Comment by vicb** [comment]
will re-open when working on it actively

**Pull request closed without merging**
