### PR TITLE
docs: improve examples, description of PipeTransform (#37321)

### LINKED ISSUE #37321: PipeTransform docs unclear when dealing with multiple parameters
# 📚 Docs or angular.io bug report

### Description

The PipeTransform's `transform` parameters are unclear as it can now support multiple individual parameters or a rest param. It should be clarified how you can pass multiple parameters to the transform method. I suggest adding an additional example with multiple parameters as both of these ways of invoking the method are valid:

```ts
export class MyPipe implements PipeTransform { 
    // specify every argument individually   
    transform(value: any, arg1: any, arg2: any, arg3: any): any { }
    // or use a rest parameter
    transform(value: any, ...args: any[]): any { }
}
```
Example addition suggestion:

```ts
@Pipe({
    name: 'truncate'
})
export class TruncatePipe implements PipeTransform {

    transform(value: string, limit: number, trail: string): string {
        return value.substring(0, limit) + trail;
    }

}
```

Invoking {{ 'Truncate me' | truncate:8:'!' }} in a template produces Truncate!.

Additionally, it would be nice to document how to write a unit test for a pipe with multiple parameters. Similar to this:

```ts
it('should support multiple pipe parameters in the template', () => {
        @Component({
          template: `{{ text | truncate:8:'...' }}`,
        })
        class App {
          text = 'Truncate me';
        }

        TestBed.configureTestingModule({declarations: [App, TruncatePipe]});
        const fixture = TestBed.createComponent(App);
        fixture.detectChanges();

        expect(fixture.nativeElement.textContent).toEqual('Truncate...');
    });
```

### What's the affected URL?**
https://angular.io/api/core/PipeTransform

## 📷Screenshot
Screen Shot 2020-05-28 at 11 57 35

Screen Shot 2020-05-28 at 12 09 19

</code></pre>

Can I open up a PR to make this change?

### PR DESCRIPTION
**Pull request by cesperian**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: Fixes #37321

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Thanks for this PR @cesperian.

Ideally we should be putting examples into external files that can be syntax checked and maybe even tested. I would propose that you create a new folder:

```
packages/examples/core/ts/pipes
```

And place in it two files:

**simple_truncate.ts**
```
import {Pipe, PipeTransform} from '@angular/core';

@Pipe({name: 'repeat'})	 * @Pipe({name: 'truncate'})
export class RepeatPipe implements PipeTransform {	 * export class TruncatePipe implements PipeTransform {
  transform(value: any, times: number) {	 *   transform(value: any) {
   return value.repeat(times);	 *     return value.split(" ").slice(0, 2).join(" ") + "...";
  }
}
```

**truncate.ts**
```
import {Pipe, PipeTransform} from '@angular/core';

@Pipe({name: 'truncate'})
export class TruncatePipe implements PipeTransform {
  transform(value: any, length: number, symbol: string) {
    return value.split(" ").slice(0, length).join(" ") + symbol;
  }
}
```

Then in the docs for this you can reference these files using something like:

```
<code-example path="core/ts/pipes/simple_truncate.ts" header="simple_truncate.ts"></code-example>
```

and so on.

If you were feeling really keen you could even create a `truncate.spec.ts` file that unit tests these classes. Such a file would be automatically run as part of our CI jobs. I don't think you would want to reference the test file in the docs.

**Comment by cesperian** [comment]
@petebacondarwin thanks for the suggestions, all done except for the unit test. I'm still trying to get a handle on testing within this workspace, although Dave just gave me a couple more pointers. Right now I think I would cause more issue than solve. I'll make a note to add this at a later time, if that is ok.
Quick question; i amended my previous commit using the direction in the contributing md guide, but is this the correct result you needed?...
image

**Comment by petebacondarwin** [comment]
Looking good. See https://pr40863-16a222e.ngbuilds.io/api/core/PipeTransform#usage-notes

We need to fix up the linting and building errors for the example.

- Add comment header to each file
- Add a file containing an NgModule that declares these two pipes

Regarding the commits. Good effort. I think that the last commit has too many "fixup!" prefixes 😄 .
Once you have added one fixup commit using `git commit --fixup` fixes up the fixup!
Usually in that case I would use `git commit --reuse=HEAD` to just copy the fixup commit message to the new commit.

I don't know whether our merge script will cope with the double fixup commit so it would be best to amend that last commit message to remove one of the prefixes.

**Comment by cesperian** [comment]
> We need to fix up the linting and building errors for the example.
> 
> * Add comment header to each file
> * Add a file containing an NgModule that declares these two pipes
> 
> Regarding the commits. Good effort. I think that the last commit has too many "fixup!" prefixes  .

Yeah, I didn't think that looked correct. I corrected that and these other issues, thanks for the direction before I ended up with a commit called "fixup!fixup!fixup!fixup!fixup! add line break" : ) 

Regarding the comment header to add, you're referring to the @license comment block that I see in all these files?

And where should the module be imported? I found a few clues from previous module commits, but probably better to ask...

**Comment by petebacondarwin** [comment]
- **Header**: yes just copy in the copyright header comment from one of the other source files to the top of any new file you create.
- **NgModule**: I would suggest simply creating a new file:

**packages/examples/core/ts/pipes/module.ts**

```ts
/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
import {NgModule} from '@angular/core';
import {TruncatePipe as SimpleTruncatePipe} from './simple_truncate';
import {TruncatePipe} from './truncate';

@NgModule({
  declarations: [SimpleTruncatePipe, TruncatePipe]
})
export class TruncateModule {}
```

**Comment by cesperian** [comment]
Gotcha. That's about where I was earlier, but the module does not then need to be explicitly imported elsewhere?...

**Comment by petebacondarwin** [comment]
> Gotcha. That's about where I was earlier, but the module does not then need to be explicitly imported elsewhere?...

I don't believe so. The test program will include all three files - and the compiler will then be able to see that both pipes are declare in a module.

**Comment by cesperian** [comment]
> > Gotcha. That's about where I was earlier, but the module does not then need to be explicitly imported elsewhere?...
> 
> I don't believe so. The test program will include all three files - and the compiler will then be able to see that both pipes are declare in a module.

That's pretty cool. Ok thanks, just pushed update...

**Review by petebacondarwin — COMMENTED** [review]
So close!

```
The following files are out of format:
    - packages/examples/core/ts/pipes/pipeTransFormEx_module.ts


To format the failing file run the following command:
  yarn ng-dev format files packages/examples/core/ts/pipes/pipeTransFormEx_module.ts
```

**Review by petebacondarwin — APPROVED** [review]

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Pull request closed without merging**
