### PR TITLE
Minor spelling change - Typescript to TypeScript

### PR DESCRIPTION
**Pull request by kapilepatel**
Updated from Typescript to TypeScript (see small/capital 's')

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Spelling of TypeScript had small case 's' character

Issue Number: N/A

## What is the new behavior?
Updated spelling of TypeScript

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
thanks!

**Review by patilharshal16 — COMMENTED** [review]
Looks good. Corrected typo

**Review by patilharshal16 — APPROVED** [review]

**Comment by kara** [comment]
@kapilepatel Can you fix the commit message to match our guidelines? That's why the CI is red.

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by kapilepatel** [comment]
@kara thanks, I have updated commit message

**Comment by AndrewKushnir** [comment]
Merge assistance: it looks like CircleCI didn't pick up the change in commit message. Commit message looks good now (verified using lint tool manually).

**Comment by AndrewKushnir** [comment]
Closing this PR, the changes are incorporated into a different PR, see comment from @kapunahelewong [here](https://github.com/angular/angular/pull/32153#issuecomment-521754468).

@kapilepatel thanks a lot for your contribution!

**Pull request closed without merging**
