### PR TITLE
Remove extra semicolons found in the http guide

### PR DESCRIPTION
**Pull request by davidauza-engineer**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

There are some extra semicolons found in some of the code examples in the HTTP [guide](https://angular.io/guide/http), which doesn't match Typescript style guidelines.

## What is the new behavior?

Extra semicolons were removed both for:

- aio/content/guide/http.md 

and for: 

- aio/content/examples/http/src/app/config/config.service.ts

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

In the second commit:

- Replace a comma for a dot in the comment at line 79 to ensure consistency
with the rest of the document.

- Capitalized and added a dot at the end of the comment at line 84 to
ensure consistency with the other comments.

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Thanks for this, @davidauza-engineer! That commit message is great! Could you squash the two commits into one? I have [some notes on the workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) if you'd find them helpful.

**Review by jbogarthyde — APPROVED** [review]
LGTM

**Comment by davidauza-engineer** [comment]
Hi @kapunahelewong 

I did just squashed the commits as suggested.

Thank you very much!

**Comment by kapunahelewong** [comment]
Thank you, @davidauza-engineer! After you did that I noticed that it needed to be replaced! So instead of asking you to do another step I have done it for you. I hope that's all right. Once it turns green, we can move it forward. 🎉

**Review by kapunahelewong — APPROVED** [review]
LGTM! Thanks, @davidauza-engineer!

Reviewed-for: global-docs-approvers

**Comment by davidauza-engineer** [comment]
Thanks a lot @kapunahelewong! I really appreciate your support, you are very kind 😃

**Pull request closed without merging**
