### PR TITLE
docs(aio): add JiaLiPassion to Angular collaborators

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by JiaLiPassion** [comment]
@alexeagle, thanks, that looks great!

**Comment by alexeagle** [comment]
We'll need to get a signed NDA from you so we can invite you to meetings. @manughub will send one.

**Comment by JiaLiPassion** [comment]
> We'll need to get a signed NDA from you so we can invite you to meetings. @manughub will send one.
> (It's so we can invite you to our subteam meetings)
@alexeagle, got it, looking forward to it, thanks!

**Comment by alexeagle** [comment]
@manughub says the NDA is signed, thanks!

**Review by JiaLiPassion — APPROVED** [review]
Thanks!

**Comment by alexeagle** [comment]
caretaker: assistance, Igor has disappeared :)

**Review by kara — APPROVED** [review]
LGTM (global)

**Pull request closed without merging**
