### PR TITLE
docs: fix result of sanitization example

### PR DESCRIPTION
**Pull request by rch850**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

The result of sanitization example is wrong in https://angular.io/guide/template-syntax#content-security.

```
"Template  Syntax" is the interpolated evil title.
"Template alert("evil never sleeps")Syntax" is the property bound evil title.
```

## What is the new behavior?

* Escape < and > of interpolation result.
* Fix result of property binding result.

```
"Template <script>alert("evil never sleeps")</script> Syntax" is the interpolated evil title.
"Template Syntax" is the property bound evil title.
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by kapunahelewong — APPROVED** [review]
Nice catch, @rch850! Could you rebase so everything is up-to-date? Here are [my notes on the process](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) if you'd like them. Please tag me if you have any questions or when you're ready. Thank you!

**Comment by rch850** [comment]
Hey @kapunahelewong, I've rebased the branch.

**Comment by kapunahelewong** [comment]
Thank you so much for looking out and submitting this fix and for your patience, @rch850. 

Reviewed-for: global-docs-approvers

**Comment by rch850** [comment]
@kapunahelewong I have extended the commit message but test_aio_local failed. Please ask me if there is something I can do.

**Review by gkalpak — APPROVED** [review]
Reviewed-for: global-docs-approvers

(For testing purposes.)

**Comment by kapunahelewong** [comment]
Thank you, @rch850! We had some issues getting it so I could add the merge label. All good now!

**Pull request closed without merging**
