### PR TITLE
docs(aio): added a link to Angular-RU

### LINKED ISSUE #21686: Can you add a link to a new resource?
In Russia, now the popularization of the framework is the Angular-RU and AngularMoscow community:
https://github.com/Angular-RU

image

https://angular-ru.github.io/

I translate and our team spends different examples with Angular in Russian.

It would be great if you added a link (https://angular.io/resources) to our community. 

Thank you.

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
Angular-RU Community on GitHub is a single point for all resources, chats, podcasts and meetups for Angular in Russia

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

Fixes #21686.

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]

**Comment by splincode** [comment]
What is the reason for the refusal?

**Comment by StephenFluin** [comment]
What refusal @splincode? It looks to me like it was merged into master and should be live soon.

**Comment by gkalpak** [comment]
Yes, it has been released on https://next.angular.io/resources#community-curations. It will be released to the stable version on the next patch release.
(@splincode, the PR shows on GitHub as "closed" instead of "merged", because we follow a rebase-based workflow, but the commit is in: 2015ccd1f)

**Comment by splincode** [comment]
Excuse me for worrying, now I will be more attentive in matters. Thank you ))

**Pull request closed without merging**
