### PR TITLE
docs: fix sentence in attribute directives guide

### PR DESCRIPTION
**Pull request by ashishpatelcs**
minor change for better readability.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by ashishpatelcs** [comment]
I signed It!

**Comment by sarunint** [comment]
@ashishpatelcs please update PR title to be something more specific.

**Comment by ashishpatelcs** [comment]
> Thanks for the PR @ashishpatelcs! Will you update the git commit message to `docs: fix sentence in attribute directives guide`?
> 
> Once that change is made, its reviewed and approved, and is green on CI it will be ready to merge.

Done. Thank you for help!

**Comment by ashishpatelcs** [comment]
> @ashishpatelcs please update PR title to be something more specific.

Did it. Thank You!

**Comment by brandonroberts** [comment]
@ashishpatelcs you also need to update the commit message here https://github.com/angular/angular/pull/26266/commits. You will need to do this through the git command line client and amend the commit message.

**Comment by brandonroberts** [comment]
@ashishpatelcs no worries. You have a couple of options.

- Close this PR and open a new one with the same change and update the commit message before you submit it.

- Use the git command line client to clone your repo and amend the commit message. If you don't have the git client installed, you need to do that first.

Instructions on how to clone/amend your git commit message:

1. Clone the repo to your machine using git - `git clone git@github.com:ashishpatelcs/angular.git`
2. Change to your cloned repo - `cd angular`
3. Check out your branch - `git checkout patch-1`
4. Amend your commit message - `git commit --amend -m "docs: fix sentence in attribute directives guide"`
5. Push your changes back up to origin - `git push origin --force-with-lease patch-1`

**Comment by ashishpatelcs** [comment]
@brandonroberts Thank you so much. I took the hard way and finally did it! :)

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
CARETAKER: Unrelated build flake

**Pull request closed without merging**
