### PR TITLE
docs: add tslib change to v10 CHANGELOG

### PR DESCRIPTION
**Pull request by lacolaco**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/angular/angular/pull/37198

## What is the new behavior?

Add a line about `tslib` dependency change in v10.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Discussion: https://github.com/angular/angular/pull/37198#issuecomment-634401051

cc/ @IgorMinar

### CODE REVIEW

**Comment by ajitsinghkaler** [comment]
@lacolaco you have to add a 100 character commit message body for this to pass ci/cd

**Review by IgorMinar — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]
LGTM. thanks!

**Review by IgorMinar — APPROVED** [review]
I rebased this and expanded the comment to comply with our lint checks (and force pushed into this branch).

Reviewed-for: public-api

**Review by IgorMinar — APPROVED** [review]
Reviewed-for: global-approvers

**Pull request closed without merging**
