### PR TITLE
Unused import.

### PR DESCRIPTION
**Pull request by tcoz**
refactor(core): remove an unused import in application_ref

### CODE REVIEW

**Comment by tcoz** [comment]
I signed it!

**Review by vicb — CHANGES_REQUESTED** [review]
The change LGTM however the commit message does not follow angular guidelines, should be 
`refactor(core): remove an unused import in application_ref`

**Comment by vicb** [comment]
Also you need to sign the CLA with the address used by the commit `...@tcoz.com`

**Comment by tcoz** [comment]
How do I make that CLA change? I spent about 20 mins this morning trying to figure it out, there doesn't appear to be any way to edit that email, and I can't just delete he CLA and create a new one (and even if I did, will it just use my signed-in gmail address and not let me add the one I want, which is a non-gmail address?)

**Pull request merged**
