### PR TITLE
docs: change "patchMatch" to "pathMatch"

### PR DESCRIPTION
**Pull request by sahansera**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
In the current live version of docs of the Angular router page, `pathMatch` has been misspelt as `patchMatch`.

Link: https://angular.io/api/router/Route#matching-strategy

Issue Number: N/A

## What is the new behavior?
This PR fixes the typo for the Router's Matching Behaviour section

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sahan91** [comment]
@googlebot I signed it!

**Comment by kapunahelewong** [comment]
This is a good catch, @sahan91! Could you do a couple of things so we can move this forward?

1. rebase: I have[ some notes on my own workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) you may find helpful.
1. Amend your commit message. I have [notes on this](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) too. Try this: `docs: change "patchMatch" to "pathMatch"`. You don't need the scope of `router`.

Please tag me when you're ready or if you have any questions. Thank you!

**Comment by sahan91** [comment]
@kapunahelewong Thanks a lot for reviewing it :) I have made the changes you suggested and it's ready for another round of reviewing. Please feel free to let me know if there's anything else. Cheers!

**Review by kapunahelewong — APPROVED** [review]
LGTM. Thank you very much, @sahan91!! 🌺

**Comment by kapunahelewong** [comment]
Caretaker, this is a docs only change. Please let me know if there's anything I can do to help with this. Thank you!

**Pull request closed without merging**
