### PR TITLE
docs: move lazy loading section to the best practices section

### PR DESCRIPTION
**Pull request by eduardbme**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 39161

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by eduardbme** [comment]
moved to the Best Practices section, though will reread in order to adjust to BP writing style

**Comment by aikidave** [comment]
This move makes sense to me. Let me know when it's out of Draft stage and if there's anything I can do to help!

**Comment by eduardbme** [comment]
have gone through the BP section and didn't find any reason to update the current version of the lazy loading documentation

**Review by aikithoughts — APPROVED** [review]
This change makes sense to me.

Reviewed-for: global-docs-approvers

**Comment by aikidave** [comment]
@kapunahelewong Do you have a few moments to try to rebase this PR?

**Comment by eduardbme** [comment]
let's close this one in the favor of #41378
rebased PR against the master branch

**Pull request closed without merging**
