### PR TITLE
docs(elements): fix typo (you custom element --> your custom element)

### PR DESCRIPTION
**Pull request by amar9312**
changed "you" to "your" in sentence - "This is a good way to quickly get TypeScript features, such as type checking and autocomplete support, for you custom element."

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by tphobe9312** [comment]
@googlebot I signed it!

**Review by santoshyadavdev — APPROVED** [review]

**Review by gkalpak — APPROVED** [review]
Thx for fixing this, @tphobe9312 :+1:

FYI, I updated the commit message to be a little more descriptive and more closely follow our commit message guidelines. For future reference, you can find our guidelines [here][1]

[1]: https://github.com/angular/angular/blob/289a96b078a135459992f6996c922d36651f3bbc/CONTRIBUTING.md#commit

**Comment by gkalpak** [comment]
Also, thank you @santoshyadavdev for helping @tphobe9312 through the PR process 💯

**Comment by ajitsinghkaler** [comment]
Failures are flake

**Comment by ajitsinghkaler** [comment]
Test failure is a flake

**Pull request closed without merging**
