### PR TITLE
Rename modules/examples to modules/playground

### LINKED ISSUE #4342: rename modules/examples directory to modules/dev-playground or modules/playground
the contents of that directory are really just end2end tests and mini apps for testing/developing/playing with the core in ts2dart pseudolanguage. we should not make it look like this is the canonical place for examples.

related to: #4341

### PR DESCRIPTION
**Pull request by kutyel**
Closes #4342

Is there any other reference to this folder or something else that I'm missing?

### CODE REVIEW

**Comment by IgorMinar** [comment]
there are references in the gulp file, and also in dart_tree.ts, browser_tree.ts and node_tree.ts

**Comment by IgorMinar** [comment]
can you fix that please and rebase?

**Comment by kutyel** [comment]
Sure I will do it this evening ASAP. By rebasing you mean squashing all the changes I made in a single commit right? GitHub says *this branch has conflicts that must be resolved*, can I fix this or is something you will do before merging? Thanks in advance.

**Comment by kutyel** [comment]
@IgorMinar Done, I just rebased and left one single commit. I couldn't find the references you mention in the **node_tree.ts** file, the rest are just fine. Give some feedback when you have time ;)

**Comment by IgorMinar** [comment]
@kutyel looks better, but there are still conflicts. can you rebase one more time please?

**Comment by kutyel** [comment]
@IgorMinar Done, thanks for the assistance :smile:

**Comment by IgorMinar** [comment]
Sorry, there are still some test failures. looks like you missed a rename somewhere that is affecting e2e tests. Can you please look into it (and rebase against master again + squash everything into one commit).

Lastly, please change the commit message to:

```
chore: rename modules/examples to modules/playground

The directory contains code authored in a style that makes it transpilable to dart. As such, these are not idiomatic examples of Angular 2 usage.

The main purpose of this directory is to enable experimentation with Angular within the angular/angular repository.

Closes #4342
```


Thanks

**Comment by kutyel** [comment]
@IgorMinar I give up, I really don't know what else to do, the CI tests fail and I cannot even run them on locale to check whats wrong before pushing it, it's being a real pain, I'm sorry :disappointed:

**Comment by kutyel** [comment]
@IgorMinar Done, but I really do not know what else is missing :scream:

**Comment by IgorMinar** [comment]
I think this is the last instance of "example" that needs to be updated: https://github.com/kutyel/angular/blob/ffaa1a2164aa21c9b7499c36222ea1b260ca6a8a/tools/broccoli/html-replace/SCRIPTS_benchmarks.html#L10

**Comment by IgorMinar** [comment]
sorry, I know that this is back and forth frustrating..

**Comment by kutyel** [comment]
@IgorMinar I finally made it! Don't worry, putting aside the initial frustration, I'm very happy to contribute to such an awesome project! :smile:

**Comment by IgorMinar** [comment]
Merged! Thanks!

**Pull request closed without merging**
