### PR TITLE
docs: ngvikings 2020 event added

### PR DESCRIPTION
**Pull request by jornare**
Added ngVikings 2020 event on angular.io events list and announcements

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:
Added ngVikings event to angular.io

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
ngVikings event is visible in the events list and front page announcements.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by StephenFluin — CHANGES_REQUESTED** [review]
We haven't yet finalized our 2020 speaker lineup, but there aren't any current plans to speak at ngVikings to my knowledge, so we would need to reject this.

**Comment by jornare** [comment]
> We haven't yet finalized our 2020 speaker lineup, but there aren't any current plans to speak at ngVikings to my knowledge, so we would need to reject this.

Let me check with the rest of the organizers. I was given the clear impression that we had several core members coming.

**Comment by StephenFluin** [comment]
Alright, it looks like we DO have a speaker attending, hurray! We can definitely add this to the events page, but you'll need to remove this from the announcements. We only use announcements for events where we send a huge portion of our team. Thanks!

**Comment by jornare** [comment]
> Alright, it looks like we DO have a speaker attending, hurray! We can definitely add this to the events page, but you'll need to remove this from the announcements. We only use announcements for events where we send a huge portion of our team. Thanks!

Alright, done! But I happily re-revert when you all figure out how lovely it is to visit Oslo end of May ;)

**Review by StephenFluin — APPROVED** [review]

**Comment by jornare** [comment]
I see circleci fails because the branch is behind master. Is this something you will deal with or something I will have to do?

**Comment by StephenFluin** [comment]
If you can rebase and make sure you have a single commit, that would be
great.

**Comment by jornare** [comment]
while rebasing, it seems ci automatically approved and closed the branch while empty. There is another update in the branch that is not in. How do we fix this? New PR?

**Comment by jornare** [comment]
Hi, Is there any chance of having this in anytime soon?

**Review by gkalpak — APPROVED** [review]

**Pull request closed without merging**
