### PR TITLE
fix(class): allow class names with mixed case

### LINKED ISSUE #3001: Ability to turn off dash case for CSSClass directive
I'm finding problems with css that uses camel case when using CSSClass because [this line](https://github.com/angular/angular/blob/44891996b592cbbeafb3a6f45a27d8d943895bab/modules/angular2/src/render/dom/view/view.ts#L58) automatically converts each class to dashed case.

Can we have a choice between camel case and raw input when using the CSSClass directive?
Would be nice if we could provide a means to configure CSSClass directive per component.

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Fixes #3001

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@tbosch I've moved the normalization of class names to the ProtoViewBuilder so we are not messing with the casing for class names that come from JS (class directive or host properties). IMO we could / should do this with attribute and style names as well, but wanted to check with you first.

Could you PTAL?

**Comment by tbosch** [comment]
This looks good, the only question is which interface we want to provide for people that use the `Renderer` directly: Before this PR they would always send over camelCase class/attribute/style names and let the renderer decide whether it supports camelCase or not. I.e. directives would be more independent of the renderer than with the PR.

Having said this, we also have issues with the auto camel casing (https://github.com/angular/angular/issues/3001). So yes, let's do it, but please mark this as a `BREAKING CHANGE`.

**Comment by pkozlowski-opensource** [comment]
@tbosch I would say that the renderer shouldn't touch CSS class casing (hence this change, that was done to fix #3001). We do those case-converting massaging only to handle `[class.my-class]=exp` properly.

Agree that it is a breaking change, will mark as one (although I don't think it is going to break peoples code, hopefully)

**Comment by tbosch** [comment]
Should we merge this as is or wait for more changes to come?

**Comment by pkozlowski-opensource** [comment]
@tbosch I've updated the commit message to add info about the breaking change. Let's land this one so it doesn't become bit-rotten - I will take care of attributes and styles in a separate PR.

**Pull request closed without merging**
