### PR TITLE
feat(core): allow resetting compilation for HMR

### LINKED ISSUE #35265: HMR fails with IVY: Type AppComponent is part of the declarations of 2 modules: AppModule and AppModule!
# 🐞 bug report

### Affected Package
HMR + IVY

### Is this a regression?

pre-IVY, it works

### Description

Seems IVY and HMR don't play well together? However I've seen tickets of them that are closed so I suppose it should be possible.
I have on re-load after code change:

nhandled Promise rejection: Type AppComponent is part of the declarations of 2 modules: AppModule and AppModule! Please consider moving AppComponent to a higher module that imports AppModule and AppModule. You can also create a new NgModule that exports and includes AppComponent then import that NgModule in AppModule and AppModule.
Type Background is part of the declarations of 2 modules: AppModule and AppModule! Please consider moving Background to a higher module that imports AppModule and AppModule. You can also create a new NgModule that exports and includes Background then import that NgModule in AppModule and AppModule.
...

and so on (for 5 components as far as I can see)

Seems somebody already did some more in-depth research on it than me:
https://www.gitmemory.com/issue/storybookjs/storybook/8494/551763214

## 🌍  Your Environment

**Angular Version:**
ng 9.0.0
cli 9.0.1

### PR DESCRIPTION
**Pull request by JoostK**
This is a work in progress effort to allow Ivy to be used together with
Hot Module Replacement in JIT mode. Not ready for review yet.

### CODE REVIEW

**Comment by sp90** [comment]
@JoostK I think everyone who cares about HMR and the speed it brings to development is awaiting this, do you think we can see this change anytime soon.

**Comment by gemron** [comment]
now , we use hmr reload time is so long,  we hope this work is finish quickly. thanks

**Comment by sp90** [comment]
@JoostK Amazing with the draft, here 3 months later is there work elsewhere getting done on this issue or is this the only place? 🚀

**Comment by jessicajaniuk** [comment]
@JoostK Closing this as we have already landed support for this feature in the interim. However, if we're incorrect, please re-open.

**Pull request closed without merging**
