### PR TITLE
feat(http): throw error if headers are passed

### LINKED ISSUE #9141: JsonP from
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**

**Expected/desired behavior**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-beta.X 
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

### PR DESCRIPTION
**Pull request by nhodges**
CLOSES #9141

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #9141

## What is the new behavior?
JSONPConnection will throw an error if headers are passed.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by nhodges** [comment]
Repushed my branch with appropriate scope name. Build is running now.

**Comment by nhodges** [comment]
Looks like the only build failure is the Saucelabs one, should be good to go.

**Comment by splincode** [comment]
@nhodges http module is deprecated, please closed

**Comment by petebacondarwin** [comment]
Indeed the `@angular/http` module has now been removed so this PR is obsolete.

**Pull request closed without merging**
