### PR TITLE
chore: Fix Dart analysis

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
There are still warnings/errors in web directories. I print these out, but I don't consider them errors – yet.

The output will be good help for anyone trying to fix https://github.com/angular/angular/issues/1392

**Comment by kevmoo** [comment]
CC @yjbanov @mhevery

**Comment by yjbanov** [comment]
Thanks! I was going to start fixing our analyzer situation two tasks from now, but you did most of the work already! :)

**Comment by kevmoo** [comment]
Closed by 6600ac7031944703ff7bb1f1aeee9650e8572460

**Pull request closed without merging**
