### PR TITLE
fix(service-worker): remove `controllerchange` listener when app is destroyed

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by arturovt** [comment]
@dylhunn this is the same as https://github.com/angular/angular/pull/55365, but targets `17.3.x` branch.

**Comment by JeanMeche** [comment]
17.3.x is now a LTS branch, are we sure we want to ship it there ?

**Comment by dylhunn** [comment]
Yeah, 17.3.x is now LTS. We can do it if you like, but I recommend against it unless you have a real reason to backport it.

**Comment by dylhunn** [comment]
Oh actually, it looks like I put the original PR on `main`, which is `18.1.x`, not `18.0.x`. Sorry about that! We can port to `18.0.1` if you like.

Our branch configuration is really weird during the RC, and I got a bit confused.

**Comment by AndrewKushnir** [comment]
> Regardless, I'd still advise against LTS ports.

+1, let's avoid merging the fix into an LTS branch and land it into the `18.0.x` branch (and release it in a patch version). @arturovt could you please update the PR to target `18.0.x` branch instead?

**Comment by JeanMeche** [comment]
@AndrewKushnir It already landed in the RC.

**Comment by AndrewKushnir** [comment]
> It already landed in the RC.

@JeanMeche thanks for additional info, I'll close the PR since it has landed in RC already.

**Pull request closed without merging**
