### PR TITLE
Preserve metadata during AOT compilation via setClassMetadata

### PR DESCRIPTION
**Pull request by alxhub**

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
approval for the BUILD.bazel change

**Review by benlesh — APPROVED** [review]

**Comment by benlesh** [comment]
When looking at `core:test`, the PR improves the situation quite a bit:

*master*
1264 specs, 776 failures, 2 pending specs

*this PR*
1264 specs, 539 failures, 2 pending specs

237 fixed tests

**Comment by alxhub** [comment]
Caretaker: Pull Approve is not cooperating. Please hit it over the head.

**Review by jasonaden — APPROVED** [review]
Try to get pull approve to pass this on.

**Review by mhevery — APPROVED** [review]

**Pull request closed without merging**
