### PR TITLE
docs: add fatima amzil to contributors

### PR DESCRIPTION
**Pull request by famzila**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@famzila Thanks for the PR! Looks like your image is above the limit of 30k. Can you fix that? When you do, either make it a fixup commit of squash it into your current commit. Thanks!

**Review by twerske — APPROVED** [review]
LGTM - welcome!

**Comment by bob-watson** [comment]
@jessicajaniuk I've since updated the max image size test so how can we rerun the CI tests?

**Comment by jessicajaniuk** [comment]
@famzila @bob-watson I rebased this for you. We should be good to merge after CI finishes up.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 150dd3092bcc63dad96935930774f3fb4316ecf1.

**Comment by famzila** [comment]
Thank you, @jessicajaniuk. I've just checked the email about the rebase notification!

**Pull request closed without merging**
