### PR TITLE
refactor: remove unused and duplicate CSS properties

### PR DESCRIPTION
**Pull request by DanielRuf**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

There are some CSS properties which are overwritten by rules below them and so they are not needed and just duplicate properties.

Issue Number: N/A

## What is the new behavior?

Unused, duplicate and overwritten CSS properties are removed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by DanielRuf** [comment]
Will do so later.

**Comment by DanielRuf** [comment]
> Could you, please, change the commit message

Done.

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
@DanielRuf - great! Please squash the commits and rebase on master.

**Comment by DanielRuf** [comment]
Ok, will do so in ~1 hour.

**Comment by DanielRuf** [comment]
> Please squash the commits and rebase on master.

Done.

**Comment by DanielRuf** [comment]
It seems CI is not very stable.
https://circleci.com/gh/angular/angular/171914

I guess we have to increase the Yarn timeouts.

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
Thank you!

**Pull request closed without merging**
