### PR TITLE
docs: fixed typo of ChangeDetectionStrategy in the zoneless guide

### PR DESCRIPTION
**Pull request by AmlaPeter**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thanks for this

**Comment by JeanMeche** [comment]
Hi, can you please reword your commit to follow our guide lines. It should be a `doc: ...` commit. 
Thank you.

**Comment by AmlaPeter** [comment]
> Hi, can you please reword your commit to follow our guide lines. It should be a `doc: ...` commit. Thank you.

Oops - have reworded, thanks.

**Review by AndrewKushnir — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 2a07a7f6fc1e8ef6df9f9394120b194cc51e23e0.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
