### PR TITLE
docs: corrected link for defer related blocks

### PR DESCRIPTION
**Pull request by mattezell**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
'blocks' links are broken.

Issue Number: N/A

## What is the new behavior?
'blocks' links work

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@mattezell Thanks for this, but unfortunately it is incorrect. Our docs pages strip out the `@` symbol in links to these pages. So the path in this PR would actually create a broken link. The actual path is https://angular.io/api/core/defer. https://angular.io/api/core/@defer does not work. I'm going to close this, but if you see anything else, please feel free to create a PR to address it. And again, thanks for the effort.

**Comment by mattezell** [comment]
Apologies @jessicajaniuk - I now see this was submitted for /aio/, which I am now assuming is angular.io.

The error that I was attempting to resolve is for the NEW angular.dev site - https://angular.dev/api/core/@defer

As you can see, this link is broken there - and the URL does include the @ symbol.

To arrive at this source asset, I simply did an ORG search against the angular github organization, and this file was the only matching asset. 

Is this asset not also used to generate angular.dev?

BTW: Great job on the Angular Special Event video!

Thanks and keep up the awesome work!

**Comment by jessicajaniuk** [comment]
@mattezell The a.dev stuff lives in a separate folder. That website was originally built in a separate repository and has been moved over now under the adev/ path in the root of the repository. Feel free to go make the necessary updates there. :)

And thank you! Glad you enjoyed it. But really, thanks for being a part of the community. We're glad you're here.

**Comment by mattezell** [comment]
Sweet. Thanks @jessicajaniuk .

I believe that I actually found it under the tools/manual_api_docs/blocks/ folder: https://github.com/angular/angular/pull/52704

I somehow missed that asset in my initial search...

Admittedly, this new PR is a bit of a shot in the dark - I can't find any docs on what the purpose of tools/manual_api_docs/ is, so I am somewhat rolling with an assumption here (the assumption being that some docs are being manually handled currently due to differences, such as the usage of @ symbols).

Thanks again!

**Pull request closed without merging**
