### PR TITLE
docs: fix typo in structural directive example

### LINKED ISSUE #32458: fix typo in structural directive example
# 📚 Docs or angular.io bug report

### Description

In the example of a structural directive (unless.directive.ts) at the bottom of the linked documentation page there is a problem within the description of the class. The structural directive `*appUnless` should be used in the commented section instead of the `*ngUnless` because the selector of the structural directive is also `[appUnless]`.

### What's the affected URL?**
https://angular.io/guide/structural-directives#write-a-structural-directive

### Expected vs Actual Behavior**
Expected:
```
<div *appUnless="errorCount" class="success">
  Congrats! Everything is great!
</div>
```

Actual:
```
<div *ngUnless="errorCount" class="success">
  Congrats! Everything is great!
</div>
```

### PR DESCRIPTION
**Pull request by mircowidmer**
Fixes #32458

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The issue this PR fixes is described in the linked issue: https://github.com/angular/angular/issues/32458

## What is the new behavior?
The documentation bug is fixed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Thanks for this, @mircowidmer! Could you prepend `docs: ` to your commit message so that it reads like this?

```
docs: fix typo in structural directive example 
Fixes #32458
```

Please tag me when you're ready. Thanks!

**Comment by mircowidmer** [comment]
@kapunahelewong jepp, done that!

**Review by kapunahelewong — APPROVED** [review]
This is great, thanks @mircowidmer!!

**Comment by kapunahelewong** [comment]
Caretaker, this is a docs only change fixing a typo. Thank you!

**Pull request closed without merging**
