### PR TITLE
 fix(router): remove configuration when module is destroyed

### PR DESCRIPTION
**Pull request by kewde**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Destroyed modules are still being loaded for some reason.

Issue Number: #24962

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jasonaden — CHANGES_REQUESTED** [review]
This seems like a good change, but we need to have tests added for it. Can you please add tests?

**Comment by kewde** [comment]
@jasonaden is there a good way to restart the CI tests? There seems to be an unrelated error.

**Comment by petebacondarwin** [comment]
@kewde - I am sorry this is taking a long time to get through the review process. The simplest way to triggere a new CI run from your point of view is to amend one of the commits and force-push back to GitHub.

Given that this hasn't been changed since February, I expect it would benefit from being rebased on master anyway. Please can you do this and then I will chase the people in Google to review.

**Comment by felipeplets** [comment]
@kewde are you able to look into this again? 

If not @petebacondarwin what are your thoughts about we opening a new PR based on current master with @kewde changes? I can do that and then we can close the topic.

**Comment by petebacondarwin** [comment]
@felipeplets - let's open a new PR. I think after a year @kewde is not likely to restart work on this.

**Comment by kewde** [comment]
I have spent enough effort on trying to get this upstreamed.
I simply decided to apply a patch to solve my own needs and that solved my problem.
Good luck though.

**Pull request closed without merging**
