### PR TITLE
feat(core/compiler): AppViewPool use OpaqueToken

### PR DESCRIPTION
**Pull request by PatrickJS**
`APP_VIEW_POOL_CAPACITY = 'AppViewPool.viewPoolCapacity';` => `const APP_VIEW_POOL_CAPACITY = new OpaqueToken('AppViewPool.viewPoolCapacity');`

### CODE REVIEW

**Comment by tbosch** [comment]
Travis fails because:

1. JS needs to be formatted with the command that `gulp check-format` outputs
2. Dart fails as the change should be `const APP_VIEW_POOL_CAPACITY = CONST_EXPR(...)`

`CONST_EXPR` is contained in `angular2/src/facade/lang` and is a special token for ts2dart to add a `const` also on the right hand side of the `=`

**Comment by vicb** [comment]
still "JS needs to be formatted with the command that gulp check-format outputs" you might need to update the node modules, a new version is used since the last few days

**Comment by gdi2290** [comment]
I switched to `var` and removed `CONST_EXPR`

**Comment by vicb** [comment]
Why not const ?

**Comment by tbosch** [comment]
Also, please add a `@CONST` to the class definition of `OpaqueToken`. Then you should be able to use `const` together with `CONST_EXPR` to make Travis happy...

**Comment by gdi2290** [comment]
alright the tests for js passed locally (waiting for dart to finish building). I pushed up the changes with `@CONST` and the format is also correct so it should pass now.

**Comment by tbosch** [comment]
Could you try to replace `Token${desc}` with 'Token(' + desc + ')' in `OpaqueToken` constructor?

**Comment by gdi2290** [comment]
updated dart source to
```dart
library angular2.src.di.opaque_token;

/**
 *
 *
 * @exportedAs angular2/di
 */
class OpaqueToken {
  final String _desc;
  const OpaqueToken(String desc) : _desc = 'Token(' + desc + ')';
  String toString() {
    return this._desc;
  }
}
```
works. I'll submit an issue on ts2dart to transform it to this workaround

**Comment by tbosch** [comment]
Landed in master.

**Pull request closed without merging**
