### PR TITLE
chore(refactor): easier to make sense of attr-to-prop map

### PR DESCRIPTION
**Pull request by yjbanov**
Even if we have to repeat a couple of properties, it's better to have all of them in one place.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@yjbanov yeh, this was my initial proposal but I've changed this as [requested](https://github.com/angular/angular/pull/783#discussion_r25452700) by @mhevery 

Personally I'm on the fence - on one hand it make sense to have them duplicated but it is duplication so it might happen that people add things for dart and not JS or vice-versa (although tests should catch this).

In short: I don't mind either way, maybe @mhevery should do the final call here.

**Comment by yjbanov** [comment]
As for @mhevery's request to dedupe the values, the way I see it, JS has its mappings, Dart has its own mappings. Some of these mappings are the same, but that's purely a coincidence. I'm not worried that one would forget to add a mapping. It should be caught by tests, but even if its not caught, its trivial to fix once discovered.

**Comment by pkozlowski-opensource** [comment]
@yjbanov as I've said, I don't feel strongly about dedupe so it is LGTM from my side.

**Comment by yjbanov** [comment]
That's good enough for me. I'll fight it out with Misko later, if he objects. Not that hard to change back.

**Comment by mhevery** [comment]
Find with me for now.

**Pull request merged**
