### PR TITLE
refactor(bazel): extract the helper patchNgHostWithFileNameToModuleName to its own file for 1P use

### PR DESCRIPTION
**Pull request by pmvald**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by dgp1130 — APPROVED** [review]
@pmvald I think we can merge this as is right? It shouldn't break google3? We can update the internal `BUILD` targets once this syncs. If so, I can add the label telling the caretaker to merge it in.

**Review by devversion — APPROVED** [review]

**Comment by pmvald** [comment]
@dgp1130 No it is backward compatible and will not break google3 (the helper `patchNgHostWithFileNameToModuleName ` is still exported from index.ts as a temporary solution to keep g3 dependencies).

**Comment by dgp1130** [comment]
Sounds good, should be ready to merge then.

**Comment by AndrewKushnir** [comment]
@pmvald @dgp1130 if I understand correctly, this change doesn't affect g3 (we don't sync `packages/bazel` folder) and similar changes are needed to the internal implementation of ngc-wrapped. Just wanted to confirm that this is an expected situation and we want to proceed with the merge.

**Comment by dgp1130** [comment]
Ah damn, thanks @AndrewKushnir for pointing that out. I didn't realize we stopped syncing this package entirely. I knew the Bazel rules were forked, but I thought we still synced `ngc_wrapped` as well. It does seem like [we skip this package](http://google3/third_party/javascript/angular2/copy.bara.sky;l=84-85;rcl=501609176).

I guess in that case, I think we probably just don't care about this change in GitHub and can make it internally?

**Comment by devversion** [comment]
I knew about it no longer being synced, but still we generally tried to keep it in sync if possible, if it's easy. The change seems good regardless to make the code more readable IMO

**Comment by dgp1130** [comment]
Works for me. @AndrewKushnir you can go ahead and merge this.

**Comment by AndrewKushnir** [comment]
Thanks for the replies @dgp1130 and @devversion, we can proceed with the merge.

@pmvald if this change is needed in g3, please create a separate CL to update g3 version of those files (there will be no changes in g3 after merging this PR).

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 08b72b77e3fc29f996b0b918abf079f5185ed890.

**Pull request closed without merging**
