### PR TITLE
test(router): add canDeactivate test for forChild route

### PR DESCRIPTION
**Pull request by atscott**
This PR adds test case to cover a failure that was detected after
merging #36302. That commit will be reverted and will need a new PR that
does not cause this test to fail.

### CODE REVIEW

**Comment by atscott** [comment]
Blocked by https://github.com/angular/angular/pull/36697

**Review by matsko — APPROVED** [review]
LGTM

**Comment by atscott** [comment]
merge assistance: I'm the only owner of router so pullapprove can't be green.

**Review by IgorMinar — APPROVED** [review]
LGTM - @atscott please file an issue against dev-infra to enable code owners to get code changes to their own code approved with just a simple LGTM from anyone on a bigger team (either the fw team, or anyone listed as an approver in the .pullapprove config file). Essentially we want pullapprove to have the same behavior as what we see in google3.

Reviewed-for: global-approvers

**Comment by matsko** [comment]
@atscott please rebase

**Pull request closed without merging**
