### PR TITLE
refactor(migrations): remove old migrations

### PR DESCRIPTION
**Pull request by alan-agius4**
When using `ng update` users cannot update multiple major versions at the same time. Therefore migrations that are not targeting version 14 cannot be run and therefore we are removing them.

### CODE REVIEW

**Comment by alan-agius4** [comment]
@dylhunn, I am not sure what we want to do with the experimental `migration-v14-typed-forms`.

**Comment by dylhunn** [comment]
> @dylhunn, I am not sure what we want to do with the experimental `migration-v14-typed-forms`. Do we want to leave it as experimental/optional?

Thanks Alan, yes, please leave it as experimental. I'm currently working with it, and will either remove it or enable it in time for v14.

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-migrations

**Comment by jessicajaniuk** [comment]
@alan-agius4 This looks green, but you added `action: presubmit`. Are you looking for a regular presubmit or a global one?

**Comment by jessicajaniuk** [comment]
TGP ran green. Good to go!

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit bc61cc24499415c6edc1c2f0bf2886a3f84b06f4.

**Pull request closed without merging**
