### PR TITLE
Update interceptors.md

### PR DESCRIPTION
**Pull request by ErikWegner**
Fix example code

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [/] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thanks for this !

**Comment by JeanMeche** [comment]
Could you please [sign the CLA](https://github.com/angular/angular/pull/57406/checks?check_run_id=28785599422) and reword your commit to follow our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit), thank you.

**Review by JeanMeche — APPROVED** [review]
Thanks for the swift improvements, we're good for the merge queue !

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 751880a16ab489726c1e8bc7f96cd427843798dd.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
