### PR TITLE
docs: fix cli builder doc

### PR DESCRIPTION
**Pull request by ukyo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

There were some typos and incorrect examples.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Thank you for this, @ukyo. Could you squash your commits into one?

**Comment by ukyo** [comment]
@kapunahelewong,  I squashed commits into one.

**Comment by jbogarthyde** [comment]
Requesting review from `@alan-agius4`

**Review by alan-agius4 — APPROVED** [review]
Thanks for this

**Comment by kapunahelewong** [comment]
Since this is just a typo, I've marked for merge. Caretaker, this is a docs only edit.

**Review by kara — APPROVED** [review]

**Pull request closed without merging**
