### PR TITLE
refactor(core): remove old AJD workaround for G3

### PR DESCRIPTION
**Pull request by alan-agius4**
This workaround does not seem to be needed any longer.

### CODE REVIEW

**Review by dgp1130 — APPROVED** [review]
LGTM assuming TGP passes.

**Comment by alan-agius4** [comment]
TGP https://test.corp.google.com/OCL:493045661:BASE:493032632:1670264565365:ae699b39

**Review by AndrewKushnir — APPROVED** [review]
Thanks for creating a separate PR for these changes 👍

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 8189b64d7df418f91829c74f96dafcb0e3dd80c0.

**Pull request closed without merging**
