### PR TITLE
docs: fix issue link in v13 release notes

### PR DESCRIPTION
**Pull request by artu-ole**
See:  #44181

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Documentation content changes

## What is the current behavior?

Link is broken
image

## What is the new behavior?

Link works
image

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by alan-agius4** [comment]
@artu-ole, looks like you didn’t sign the CLA

**Comment by artu-ole** [comment]
@alan-agius4 right, my bad. Should be sorted out now.

**Review by gkalpak — APPROVED** [review]
Good catch! Thx, @artu-ole :+1:

Reviewed-for: global-docs-approvers

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 4527931977d00fcfab1e1cad45b6a5e0c4638f39.

**Comment by dgp1130** [comment]
Thanks for catching this @artu-ole!

**Pull request closed without merging**
