### PR TITLE
perf(ivy): improve Uglify configuration in hello world integration test

### PR DESCRIPTION
**Pull request by marclaval**
This PRs implements suggestions from https://github.com/angular/angular/issues/21880 
The bundle size is now 9.8k (vs ~8k with Closure)

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by trotyl** [comment]
Since build-optimizer has provided [its own rollup plugin](https://github.com/angular/devkit/pull/416), would it be better to use that official one instead of some 3rd-party not-well-maintained naive implementation?

<sub>Would require next build-optimizer, so could be done in separate PR.</sub>

**Comment by alexeagle** [comment]
@trotyl has a good point - @marclaval do we even need this integration test anymore, since we're measuring bundles using "unit tests" in `packages/core/test/bundling` ?

**Comment by marclaval** [comment]
@trotyl I've opened a PR to use the official plugin: #22121 
@alexeagle From Igor's comment (https://github.com/angular/angular/pull/21940#issuecomment-364017310), I understand we should keep it to see the trend

**Comment by alexeagle** [comment]
I think we should get the trend from https://github.com/Daniel15/BuildSize/issues/7 instead - need to evaluate that and we can tear down ours once we're satisfied with results and stability.

**Pull request closed without merging**
