### PR TITLE
fix(docs-infra): improve rendering of method overloads

### LINKED ISSUE #24349: API template design for method overloads
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Overload descriptions are hard to identify and navigate through if there are more than two or three.

## Expected behavior
Suggested solution is to increase the weight of the line between overloads, and move the short-description of each method before the code signature. 
I would also  like some kind of marker or icon to distinguish the description of each new overload from the Params/Returns headers of the previous one.

## Minimal reproduction of the problem with instructions
See HttpClient doc, where many methods have 15+ overloads.
Some test doc for the file is in PR 
https://github.com/angular/angular/pull/23839

## What is the motivation / use case for changing the behavior?
It should be easier to find the overload that does what you want. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by petebacondarwin**
See https://github.com/angular/angular/pull/24000#issuecomment-395117096

Closes https://github.com/angular/angular/issues/24349

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Here is an example: https://pr24331-a87f431.ngbuilds.io/api/common/http/HttpClient

screen shot 2018-06-07 at 12 09 41

**Comment by splincode** [comment]
@petebacondarwin I think this kind of mapping is very confusing. Because, now I do not understand what version is the last among those 17 remade.

I would just like to see the difference in yellow, but somehow show the latest version at once, and the old one is collapsed.

**Comment by petebacondarwin** [comment]
@splincode - thanks for providing feedback on this. Can you explain it again? I don't really understand the comment.

**Comment by jbogarthyde** [comment]
It is still hard to distinguish one overload from another. I think you need more separation. I would like to some kind of header between the previous Returns and the new overload, followed by the description that calls out how this next one is different, followed by the  signature/params/returns. That would make each overload look like a normal method section in the class. The header could just be something like "Overload n", in a color and/or font size that distinguishes it clearly from the previous "Returns" header.

As a bonus, in this HTTP case, it would be helpful to be able to put some key to how each one differs: perhaps something like "Overload: Blob", "Overload: JSON"...

**Comment by petebacondarwin** [comment]
Something @sjtrimble could help with?

**Comment by petebacondarwin** [comment]
We need more thought on the design than this PR provides.

**Pull request closed without merging**
