### PR TITLE
feat: remove MapWrapper.create(), get(), set(), contains()

### PR DESCRIPTION
**Pull request by mprobst**

### CODE REVIEW

**Comment by vicb** [comment]
@mprobst I've seen that you added support for `{}`, great !

Should ts2dart be updated to support initialization 
- from a literal array `new Map([[k,v], [k1, v]]);` ? const + non-const
- from an exp `new Map(arrayOfArray)` ? non-const only

However this not block this PR

**Comment by vicb** [comment]
LGTM.

One more sexy PR, thanks !

**Comment by vicb** [comment]
You should also be safe to remove `MapWrapper.clear()` as `Map.clear()` is valid in both JS & Dart.

**Comment by pkozlowski-opensource** [comment]
@mprobst I feel like it is never ending Xmas :-) A new gift every day :-) Keep them coming!

**Comment by mprobst** [comment]
@vicb done.

**Comment by IgorMinar** [comment]
lgtm!

**Comment by IgorMinar** [comment]
I'll reassign this to myself so that @mprobst can merge it before it gets stale

**Pull request merged**
