### PR TITLE
test: remove Ivy/ViewEngine switch helpers and corresponding tests

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit removes special functions that were used to run tests in ViewEngine or Ivy only.
Since ViewEngine is deprecated and we no longer run ViewEngine tests on CI, we can cleanup
those special helpers and ViewEngine-only tests.

## PR Type
What kind of change does this PR introduce?

- [x] Other... Please describe: updates to tests to get rid of no longer needed helpers and corresponding tests.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
This PR is blocked by #43884, which would result in the `legacy-unit-test-saucelabs` CI job to use Ivy JIT compiler correctly.

**Review by crisbeto — APPROVED** [review]
LGTM

**Review by petebacondarwin — COMMENTED** [review]
I think you can actually delete the `packages/private/testing/src/angular_ivy_enabled.ts` file too.

**Review by petebacondarwin — APPROVED** [review]
Nice work @AndrewKushnir. You're killin' it! (ViewEngine that is!)

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

Just a couple of places where the name `Ivy` is still mentioned. We should probably audit the code base looking for View Engine and Ivy and remove references at some point.

**Comment by AndrewKushnir** [comment]
Note to the Caretaker: this is refactoring PR with low risk (does not affect g3 as well). The PR was reviewed and approved by multiple team members, so it should be ok to proceed with the merge.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit b31973c176f67fda563e77c8c5d59ae45881de4c.

**Comment by AndrewKushnir** [comment]
FYI, patch-only version of this PR is available here (original change conflicted with 13.0.x branch): https://github.com/angular/angular/pull/44262.

**Pull request closed without merging**
