### PR TITLE
refactor(directives): use of the property decorators

### PR DESCRIPTION
**Pull request by vicb**

### CODE REVIEW

**Comment by vicb** [comment]
The Travis failure is explained by the fact that transformers do not seem to have been updated to handle `@Property, @Event, @HostListener and @HostBinding`.

@vsavkin @kegluneq Is the update already planned ?

**Comment by vicb** [comment]
@kegluneq your fix (https://github.com/angular/angular/pull/4325) seems to fix Travis, thanks !

@vsavkin could you please review now ?

**Comment by vicb** [comment]
Actually the build errors are gone but e2e tests do not work, I'll investigate.

**Comment by vicb** [comment]
I do suspect that we do not generate the getters & setters for the property decorators which would explain why the examples do not work.

**Comment by kegluneq** [comment]
@vsavkin, thoughts? I don't believe we are generating getters or setters for these, and I haven't seen or heard about the design for these changes, so I'm not sure in what situations they should or should not be generated.

**Comment by vicb** [comment]
The annotations that we need to handle:
- `@Property` -> defines a property in the same way as the `properties:` config of a directive,
- `@Event` -> defines an event in the same way as the `events:` config of a directive,
- `@HostListener` and `@HostBindings` map to `host:` config of a directive

I could take a stab at this, doing the same kind of thing as what is done in https://github.com/angular/angular/commit/589ce31dfc4fc2840b675ed0266d4e2c60b26f07

But IMO it would be cleaner if the `directive_metadata_reader` handle it all (both annotation & property decorators). As of today `queries` are not handled in the same way as `proprties`, `events` and `host`.

**Comment by vicb** [comment]
Blocked on https://github.com/angular/angular/issues/4407

**Pull request closed without merging**
