### PR TITLE
fix(docs-infra): allow only Node.js v14

### LINKED ISSUE #42086: bug(docs-infra): AIO cannot build with Node.js v12
# Docs or angular.io Bug Report

### Description

https://github.com/angular/angular/blob/2e7eb270dfe26d157b8bf819fcb669d9f0d0a066/aio/tools/transforms/angular-api-package/processors/processNgModuleDocs.js#L100

Because optional chaining is supported since Node.js v14, the current AIO build process fails on Node.js v12.
But AIO allows both v12 and v14. This is inconsistent.

https://github.com/angular/angular/blob/2e7eb270dfe26d157b8bf819fcb669d9f0d0a066/aio/package.json#L82

Option 1. fix code for Node.js v12 compatibility
Option 2. allow v14 only

I can submit a patch for whichever, but I'd like to know which AIO team prefers.

### PR DESCRIPTION
**Pull request by lacolaco**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #42086 

## What is the new behavior?

Node.js v14 is the only allowed version.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Fix #42086

### CODE REVIEW

**Comment by lacolaco** [comment]
@petebacondarwin Should the root `package.json` keep v12 in `engine`?

**Review by petebacondarwin — APPROVED** [review]
Let's leave the top level package.json alone, as long as the builds and other tooling outside AIO work with node v12.

**Comment by petebacondarwin** [comment]
Please can you fix the commit message. I think it should really be:

```
build(docs-infra): allow only Node.js v14 and above

The AIO doc-gen uses JavaScript syntax that requires node.js 14.0.0 or above.

Closes #42086
```

**Comment by lacolaco** [comment]
@petebacondarwin (reminder) I changed the commit message and re-pushed.

**Pull request closed without merging**
