### PR TITLE
docs(README): Angular 2 RC

### PR DESCRIPTION
**Pull request by vitorf7**
- **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- **What is the current behavior?** (You can also link to an open issue here)
- **What is the new behavior (if this is a feature change)?**
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
- **Other information**:

Update the line that says that Angular 2 is in Beta to Release Candidate

### CODE REVIEW

**Comment by vitor-faiante** [comment]
I signed it!

**Comment by fxck** [comment]
https://github.com/angular/angular/pull/8405

**Comment by vitor-faiante** [comment]
@fxck Yep I missed that. I will make a comment on that Pull request. Just checked it and believe it should be "Release Candidate" instead of "Release Candidates". Thanks for pointing it out

**Comment by mprobst** [comment]
@naomiblack PTAL for docs?

**Comment by cebor** [comment]
The npm badge should also be updated, preferably to `@angular/core`.

**Comment by mhevery** [comment]
Closing as duplicate of https://github.com/angular/angular/pull/8405

**Pull request closed without merging**
