### PR TITLE
fix(platform-browser): add unique input event plugin

### LINKED ISSUE #14440: Textarea element in form when binding model has initial state as dirty in IE
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Textarea element in form when binding model has initial state as dirty in IE

**Expected behavior**
Textarea element in form when binding model has initial state as pristine in IE

**Minimal reproduction of the problem with instructions**
Using ng-form with textarea element and bind model on that textarea

Plunker example: http://plnkr.co/edit/JEgKqSEXGpUDSRDuMXcD?p=preview
Inspect textarea in browser development tool. `textarea` and `form` element have `ng-pristine` CSS class in Chrome/Firefox/Edge while they have `ng-dirty` CSS class in IE.

**Please tell us about your environment:**
* **Angular version:** 2.4.7

* **Browser:** IE 11

### PR DESCRIPTION
**Pull request by DerSizeS**
This plugin checks if value of element is changed before firing input event  

Internet Explorer 10+ implements 'input' event but it erroneously fires under various situations, e.g. when placeholder changes, when non english placeholder is used or a control is focused

Fixed only from Edge 15.15002
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101220/
This bug will not be fixed in Internet Explorer 
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11405058/

Closes #14440, #17951, #15299, #16151

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Internet Explorer 10+ implements 'input' event but it erroneously fires under various situations, e.g. when placeholder changes, when non english placeholder is used or a control is focused

Issue Number: #14440, #17951, #15299, #16151

## What is the new behavior?
If plugin config is provided – input event is fired when value of element is changed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Here is the problem reproduction (to fix IE behavior- uncomment the provider): https://stackblitz.com/edit/angular-feu5wd?embed=1&file=src/app.module.ts

### CODE REVIEW

**Comment by DerSizeS** [comment]
@mhevery, what can i do to make things going?

**Comment by DerSizeS** [comment]
Here is the problem reproduction (to fix IE behavior- uncomment the provider): https://stackblitz.com/edit/angular-feu5wd?embed=1&file=src/app.module.ts

**Comment by DerSizeS** [comment]
I had to recreate this PR due to the accidental deletion of the associated fork.
New PR: https://github.com/angular/angular/pull/33688

**Comment by pkozlowski-opensource** [comment]
My understanding is that this PR is replaced by #33688 so closing this one here.

**Pull request closed without merging**
