### PR TITLE
refactor(common): decouple preconnect checks from image loaders

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Previously the built-in image loaders for the optimized image directive were tightly coupled to the preconnect checks infrastructure. This was creating a problem when developers were trying to provide a loader on a component level (or, more generally, deeper in the DI hierarchy):
- PreconnectLinkChecker is the application-level service, provided in root;
- it makes sense to provide loaders in different parts of the DI hierarchy;

This refactoring removes the PreconnectLinkChecker configuration from the loaders infrastructure and makes it application-wide config. The PRECONNECT_CHECK_BLOCKLIST is also a simple provider (it was a multi-provider previously) which should make the overall configuration easier.

This PR addresses the root cause of the problem that #47498 was attempting to address.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@pkozlowski-opensource thanks for the PR, this looks great 👍

Quick comment: there are some references to the `ensurePreconnect` (and loader config argument) in each loader, for example: `packages/common/src/directives/ng_optimized_image/image_loaders/imgix_loader.ts`. Could you please also drop outdated parts of the docs (from JSDoc above the loader fns)?

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by pkozlowski-opensource** [comment]
> Quick comment: there are some references to the ensurePreconnect (and loader config argument) in each loader, for example: packages/common/src/directives/ng_optimized_image/image_loaders/imgix_loader.ts. Could you please also drop outdated parts of the docs (from JSDoc above the loader fns)?

Good catch, thank you @AndrewKushnir! Just pushed a fixup commit.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit d3c25f20a331dce0fc3fddc976f0f0544b051e68.

**Pull request closed without merging**
