### PR TITLE
feat(forms): introduce url validator

### LINKED ISSUE #14222: Add url validator
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There's no `url` validator

**Expected behavior**
Angular should provide validators for basic types such as `url`

Part of https://github.com/angular/angular/issues/2962

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Closes #14222

Regexp from ng1 [link](https://github.com/angular/angular.js/blob/a24777a2c4ad2ac087d9e3aa278fa2e61e8cc740/src/ng/directive/input.js#L25)

### CODE REVIEW

**Comment by splincode** [comment]
@DzmitryShylovich what is the status of your pull request? is it still relevant?

**Comment by trotyl** [comment]
@wojtek1150 

```
 httphttphttphttphttphttphttphttphttphttphttphttp  :   //   google.com
|------------------ scheme ----------------------|":"|"//"|-- host ---|
                                                          | authority |

  http   :   //   /           /          ...  /  google.com
|scheme|":"|"//"|"/"|segment|"/"|segment|...|"/"| segment  |
                |-------------- path-abempty --------------|
```

Both of them are valid URLs.

**Comment by kara** [comment]
This PR is pretty stale, closing.

**Comment by tiagomsmagalhaes** [comment]
I was keen to trying to do a PR about an URL built in Validator and found this PR. Why it was closed by being considered stale?

**Pull request closed without merging**
