### PR TITLE
docs(web_workers/worker/renderer.ts): correct typo

### PR DESCRIPTION
**Pull request by TimurM**

### CODE REVIEW

**Comment by TimurM** [comment]
I signed it!

**Comment by gdi2290** [comment]
dup of https://github.com/angular/angular/pull/4078 I can give you another typo Pull-Request

**Comment by TimurM** [comment]
Yea I'd love one too

**Comment by gdi2290** [comment]
@TimurM can you close this one and make one for 
"underyling" => "underlying"
https://github.com/angular/angular/blob/master/modules/angular2/src/web_workers/ui/application.ts#L36

**Pull request closed without merging**
