### PR TITLE
docs: add Michael Hladky to the GDE list

### PR DESCRIPTION
**Pull request by BioPhoton**
## PR Type
What kind of change does this PR introduce?
- [X] Other... Please describe:

## What is the current behavior?
Michael Hladky is missing in the list of GDE's

## What is the new behavior?
Michael Hladky now in the list of GDE's

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Link to activity stream can be found here: https://www.gdeapp.com/home/experts/cdc00ecce69d66255025

### CODE REVIEW

**Comment by StephenFluin** [comment]
Thanks for getting this started!

@BioPhoton A few changes before we can merge this. 
1. You'll need to sign the CLA, let me know if the instructions above aren't clear
2. Can we shrink the image to about 20kb to match the rest of the photos? You'll need to amend your commit and force push so we have a single commit with the new proposal
3. You'll need to update the commit message, check out other commits regarding GDE additions or our contributing guidelines.

**Review by StephenFluin — CHANGES_REQUESTED** [review]
Thanks for getting this started!

@BioPhoton A few changes before we can merge this. 
1. You'll need to sign the CLA, let me know if the instructions above aren't clear
2. Can we shrink the image to about 20kb to match the rest of the photos? You'll need to amend your commit and force push so we have a single commit with the new proposal
3. You'll need to update the commit message, check out other commits regarding GDE additions or our contributing guidelines.

**Comment by brandonroberts** [comment]
@BioPhoton will you resolve the outstanding issues with the PR?

**Comment by BioPhoton** [comment]
Not sure if this was right. I guess I forgot the -f.

**Review by StephenFluin — APPROVED** [review]

**Comment by BioPhoton** [comment]
As this PR is "not in best shape" haha, i created a new one that might fit better.
So i close this one in favour of https://github.com/angular/angular/pull/30596.

**Pull request closed without merging**
