### PR TITLE
Convert gulpfile to typescript

### PR DESCRIPTION
**Pull request by jeffbcross**
I did this for fun last night because I was sick of all the function boilerplate in gulpfile.js. The typescript-require dependency allows requiring any typescript file and compiling it in-place. I would need to update shrinkwrap if we were actually going to merge this, but I don't want to needlessly subject myself to that torture.

### CODE REVIEW

**Comment by jeffbcross** [comment]
This could potentially be used to compile our tools at runtime as well, but I don't have a deep enough knowledge of that process to say for certain.

**Comment by jeffbcross** [comment]
Travis is erroring because postinstall script is calling `gulp pubget.dart` before tsd, which is causing the reference d.ts not to be found. I should be able to just shift the order of the postinstall script to do tsd before gulp is ever evaluated. But I will only do that if we want to merge this change.

**Comment by alexeagle** [comment]
+cc @IgorMinar

**Comment by alexeagle** [comment]
This seems generally good to me.
We are thinking to pull our build system out of angular to a shared repo. We should think about whether we want angular-cli users to have a TS gulpfile, and whether we want to have the typescript compiler compile more of the build tool on the fly like this. Right now it's strange that we have a build.tools task to bootstrap the rest of the typescript build tooling, but this task is now called from a separate TS file. Also strange that the gulpfile doesn't have typing info for the broccoli builder.

**Comment by IgorMinar** [comment]
This is worrisome for me because we are complicating the build bootstrap process which is already tricky. we are already having hard time profiling and debugging the build code and this will make the situation even worse.

If fat arrows are the primary reason for this conversion then we might as well just use es6 directly by enabling the appropriate flags in node or wait for the next version fat arrows will be supported out of the box.

-1 from me.

**Comment by gdi2290** [comment]
the `gulpfile.js` shouldn't be necessary anymore with this update https://github.com/tkellen/js-interpret/pull/32 so gulp will pickup `gulpfile.ts` correctly

**Comment by alexeagle** [comment]
I suggest we try this setup out in a smaller and lower-risk environment
first so we understand the tradeoffs.
I plan to reboot the build process for angular-cli (angular-toolkit) so
maybe we could start there with a gulpfile.ts?

**Comment by jeffbcross** [comment]
Sounds good @alexeagle. I'm also going to submit a PR to ReactiveX/RxJS with gulpfile.ts, which is easy because that project has no build process yet.

**Comment by gdi2290** [comment]
you're now able to correctly use `gulpfile.ts` just by installing `npm install typescript-node --save` just make sure you reinstall gulp

**Pull request closed without merging**
