### PR TITLE
refactor(ngcc): change async locker timeout to 250 secs

### PR DESCRIPTION
**Pull request by vokeit-gschuster**
As it is the default with 10.x anyways

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Parallel builds fail due to too low timeout.

Issue Number: https://github.com/angular/angular/issues/36796

## What is the new behavior?

Raised retries and thus a longer timeout at all, as it is the default with 10.x branch

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by vokeit-gschuster** [comment]
@googlebot I signed it!

**Comment by petebacondarwin** [comment]
Thanks @vokeit-gschuster - Can you fix up the commit message. See https://app.circleci.com/pipelines/github/angular/angular/14767/workflows/c0c3ab37-aeac-4627-80bb-9932da9df616/jobs/703517/steps

It also needs a minimum character requirement. I would suggest reusing similar wording to the commit on master:

```
refactor(ngcc): change async locker timeout to 250 secs

Previously the `AsyncLocker` was configured to only wait
50x500ms before timing out. This is 25secs, which is often
less than a normal run of ngcc, so the chance of a timeout
flake was quite high.

The timeout is now 500x500ms, which is 250secs.
```

**Comment by vokeit-gschuster** [comment]
@petebacondarwin Message fixed, everything else OK now?

**Comment by petebacondarwin** [comment]
Great thanks. We don't need the second commit. If this sort of information is important it should be in the commit message, which can be found using `git blame` if needed. Please can you remove it from the PR. Once that is done, I am happy to approve and mark this for merge.

(Also, for future reference, these two commits would only be squashed together if the second has a `fixup!` message. I assume that this was the intention.)

**Review by petebacondarwin — APPROVED** [review]

**Comment by mhevery** [comment]
merged as f0ce3c2ce5..ad3fbe1ea0

**Pull request closed without merging**
