### PR TITLE
ci(docs-infra): improve deployment process (reduce manual config steps)

### PR DESCRIPTION
**Pull request by gkalpak**
This PR contains several changes that reduce the manual steps involved in the process of deploying the various versions of angular.io. It also refactors the `deploy-to-firebase` script to make it easier to maintain and adds more tests.

See the individual commits for details.

<sub>(Supersedes #40882.)</sub>

---
**TODO**

_**Before merging this PR:**_
- [x] Decide whether we want to keep the redirect from `v<X>.angular.io` to `angular.io` (and whether we want to automate it via Firebase config - currently it happens via Firebase console and/or DNS):
  - Getting rid of the redirect simplifies the setup, but changes the current behavior.
  - Keeping the redirect preserves the current behavior, but requires either manual steps (to set/unset the redirect in Firebase console/DNS) or special Firebase config (to redirect all requests to `angular.io` while stable).
  - Also, all options have slightly different behavior/timing when releasing a new major.

  _Discussed in the `docs-infra` meeting on 2021-03-03 and decided to (a) keep the `v<X>.angular.io` to `angular.io` redirect and (b) look into managing the redirects from `v<X>.angular.io` to other sub-domains via the Firebase config._

_**After merging this PR:**_
- [x] Wait for the changes to be deployed (on `master`, RC and the patch branch).
- [x] Connect `angular.io` and `www.angular.io` to the `stable-angular-io-site` Firebase site.
    (Ensure the domains are disconnected from the `v12-angular-io-site` Firebase site.)
- [x] Remove the redirect from `v13.angular.io` to `rc.angular.io` (in Firebase console).
- [x] Remove the redirect from `v12.angular.io` to `angular.io` (in DNS).
- [x] Verify that the redirects still work:
    - [x] [v13.angular.io](https://v13.angular.io/) --> [rc.angular.io](https://rc.angular.io/)
    - [x] [v12.angular.io](https://v12.angular.io/) --> [angular.io](https://angular.io/)
    - [x] [www.angular.io](https://www.angular.io/) --> [angular.io](https://angular.io/)

### CODE REVIEW

**Review by petebacondarwin — COMMENTED** [review]
Looking good so far. I ran out of time to complete the review. I got to 

```
ci: improve angular.io deployment process for the RC branch
```

will continue tomorrow.

**Review by IgorMinar — APPROVED** [review]
This is an awesome PR! Thank you, @gkalpak for making it so easy to read thanks to clean and logical commit separation, great commit messages, descriptive docs, and awesome test coverage. You rock!

**Review by petebacondarwin — APPROVED** [review]
The commit message typo still needs fixing. But otherwise LGTM.
As always there is some bike-shedding possibilities.

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 8d8cdc1991e26358ded644c51a8449f3869016ca.

**Pull request closed without merging**
