### PR TITLE
feat(dart/transform): Create standalone transformers for phases

### PR DESCRIPTION
**Pull request by kegluneq**
Create transformers that allow specifying transformer actions on
specific libraries.
- angular2/transform/codegen: Generates all necessary code.
- angular2/transform/reflection_rewriter: Replaces `bootstrap` calls in
  application entry points to remove transitive dart:mirrors import,
  resulting in smaller code size & faster execution.
- angular2/transform/deferred_rewriter: Rewrites deferred imports and
  `loadLibrary` calls to initialize Angular2 and preserve deferred
  operation.

Proper configuration of these three transformers can replace the single
angular2 transformer, resulting in significant performance gains for
builds of large angular2 apps.

Also remove the undocumented & unused quick_transformer.

### CODE REVIEW

**Comment by kegluneq** [comment]
Passing modulo (unrelated) flaky saucelabs & js.dev tasks.

**Comment by kegluneq** [comment]
Discovered a minor update I need to make

**Comment by kegluneq** [comment]
@jakemac53 , would to PTAL at the additional commit. Thanks!

**Comment by kegluneq** [comment]
Okay, this is once again ready for merge - passing modulo the flaky js.dev task

**Comment by vikerman** [comment]
TAP Green

**Comment by vikerman** [comment]
Merged manually

**Pull request closed without merging**
