### PR TITLE
build(docs-infra): upgrade cli command docs sources to 2eb97bf5b

### PR DESCRIPTION
**Pull request by gkalpak**
Updating [angular#master](https://github.com/angular/angular/tree/master) from [cli-builds#master](https://github.com/angular/cli-builds/tree/master).

##
Relevant changes in [commit range](https://github.com/angular/cli-builds/compare/548c6ed3e...2eb97bf5b):

**Modified**
- help/analytics.json
- help/build.json
- help/config.json
- help/e2e.json
- help/extract-i18n.json
- help/generate.json
- help/lint.json
- help/new.json
- help/serve.json
- help/test.json
- help/update.json

### CODE REVIEW

**Comment by petebacondarwin** [comment]
This is good! Our systems have found that there is a link in the glossary to `cli/generate#appshell` whereas this change to the CLI docs renames it `app-shell`. I think the best way to process is to update this PR (and https://github.com/angular/angular/pull/39944) with a change to the glossary docs, yes?

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
See https://github.com/angular/angular/pull/39943#issuecomment-738040058

**Review by petebacondarwin — APPROVED** [review]

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Comment by gkalpak** [comment]
Superceded by #39970.

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by gkalpak** [comment]
Superceded by #39985.

**Review by atscott — APPROVED** [review]
Reviewed-for: public-api

**Comment by gkalpak** [comment]
Superceded by #39991.

**Comment by gkalpak** [comment]
Superceded by #40000.

**Pull request closed without merging**
