### PR TITLE
WIP: switch to named UMD rxjs bundle

### PR DESCRIPTION
**Pull request by gregmagolan**
Testing new rxjs named UMD bundle that will be in next rxjs release

### CODE REVIEW

**Comment by gregmagolan** [comment]
Verifying that the angular build and the integration/bazel build will work with rxjs not being build from source with Bazel. Using a custom dist commit for rxjs that is based on https://github.com/ReactiveX/rxjs/pull/4309.

//cc @alexeagle @alan-agius4

**Comment by gregmagolan** [comment]
Note: integration/bazel prodserver is failing in the browser with an issue with `extendStatics` not being a function in the rxjs code that is bundled in. Not sure what this is about but may be some incompatibility with the latest rxjs typescript output and angular:
```
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    }
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
```

**Comment by gregmagolan** [comment]
Other issues are that the rxjs UMD bundle will now be named `rxjs` with https://github.com/ReactiveX/rxjs/pull/4309 but there are no bundles for the secondary entry points such as `rxjs/operators`, `rxjs/testing`, etc... I added rxjs shims files to work-around these issues for running tests. Not sure what the best approach is. Perhaps add these secondary entry point shims to the `rxjs.umd.js` bundle itself in the rxjs build?

^ @benlesh @mgechev @alexeagle @alan-agius4

**Comment by gregmagolan** [comment]
A number of golden files have additional symbols with this change as well

**Comment by alan-agius4** [comment]
@gregmagolan, I think that each entry point should have its umd bundle with its own naming (ie. having using rollup on each entrypoint).

That said, this will be a breaking change since to use the  `rxjs/operators` you would need to include `rxjs.operators.bundle.js`

As an intern solution, what i’d suggest, is all the above but the. Merge everything into the main rxjs umd bundle.

I can take it, if needs be 😊

**Comment by gregmagolan** [comment]
A little more data on the extendStatics issue with prodserver in integration/bazel:

`rollup.umd.js` has `__extends` defined like this:

```
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };

    function __extends(d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    }
```

but individual `.js` files which are the bundled up for the production bundle in integration/bazel have it defined like this:

```
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    }
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
```

the browser runtime error happens in the latter case

**Comment by gregmagolan** [comment]
The error being:

```
Uncaught TypeError: extendStatics is not a function
    at __extends (bundle.js:2748)
    at bundle.js:1966
    at bundle.js:1993
    at bundle.js:31184
```

**Comment by gregmagolan** [comment]
Ahhhh. Looks like `integration/bazel` `bundle.es6.js` works fine so its not a rollup issue. Something breaks when downleveling to `bundle.js`.

**Comment by gregmagolan** [comment]
Ok. Finally tracked it down.

In the es6 bundle,

```
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b)
                if (b.hasOwnProperty(p))
                    d[p] = b[p]; };
        return extendStatics(d, b);
    };
    function __extends(d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    }
```

ends up before any uses of `__extends`.

After downleveling to es5, the line `class ComponentFactoryBoundToModule extends ComponentFactory {` is downleved to

```
    var ComponentFactoryBoundToModule = /** @class */ (function (_super) {
        __extends(ComponentFactoryBoundToModule, _super);
```

and you now have one use of `__extends` before its definition which causes the runtime error.

**Comment by gregmagolan** [comment]
Done testing.  Not meant for merging.

rxjs named-UMD-bundle (https://github.com/ReactiveX/rxjs/pull/4309) will allow us to not build rxjs from source with Bazel.

angular/angular build will be updated after the next release of rxjs and the changes will depend on https://github.com/bazelbuild/rules_nodejs/pull/429 which in turn depends on https://github.com/rollup/rollup-plugin-node-resolve/pull/186 / https://github.com/rollup/rollup-plugin-node-resolve/pull/182 and a rollup-plugin-node-resolve release.

**Pull request closed without merging**
