### PR TITLE
test: create integration tests for Trusted Types support in Ivy

### PR DESCRIPTION
**Pull request by bjarkler**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?
Support for Trusted Types in a basic Angular application is now tested with a dedicated integration test.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]
Overall this looks great.

One nit, as discussed in person - could you please rename `ivy-trusted-types` to just `trusted-types`. don't worry about updating the intermediate commits, just add one more commit to do the rename at the end. Thank you.

Reviewed-for: global-approvers

**Comment by bjarkler** [comment]
Thanks for the feedback @IgorMinar, should be fixed. :)

**Review by IgorMinar — APPROVED** [review]
LGTM. thank you

**Comment by IgorMinar** [comment]
merge-assistance: inclusive language check failed to a reference to a master branch.

**Comment by AndrewKushnir** [comment]
Hi @bjarkler, it looks like this PR causes failures in the patch branch, see:
https://app.circleci.com/pipelines/github/angular/angular/24899/workflows/89b4bb46-1eb6-4571-837a-ba7e13433653/jobs/862282
Could you please have a look?
Thank you.

**Comment by bjarkler** [comment]
@AndrewKushnir, I think target should have been "minor", just like the rest of the Trusted Types-relevant fixes.

(On the bright side the fact that the tests are failing in that environment, which doesn't include the Trusted Types-relevant fixes, means that both the integration test, and our Trusted Types fixes are working as expected.)

**Comment by AndrewKushnir** [comment]
@bjarkler got it, thanks, here is a revert PR (for patch branch only, the changes will be retained in master): https://github.com/angular/angular/pull/39767

**Pull request closed without merging**
