### PR TITLE
docs: changelog typo fix

### PR DESCRIPTION
**Pull request by oktav777**
## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by oktav777** [comment]
I signed it!

**Comment by Sibiraj-S** [comment]
I don't think that was a typo. iff is a short word for 'if and only if'

**Comment by gkalpak** [comment]
There sure is a typo in there, because it says `only iff` (which would be sort for `only if and only if` :smiley:).
So, it should be either `iff` or `only if` (either is equally accurate in this context).

**Comment by smart--petea** [comment]
Hm. Scratching my head about that "iff" :confused:

**Review by IgorMinar — APPROVED** [review]

**Pull request merged**
