### PR TITLE
fix(http): ensure new cache state is returned on each request

### PR DESCRIPTION
**Pull request by brandonroberts**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The cache state is only used only the first server request. Restarting the server uses the cache on the first request.

Subsequent requests skip the cache because the `CACHE_STATE` object is mutated.

## What is the new behavior?

A new cache state is returned on every server request.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Angular v16.0.0-next.7 release with Universal installed and client hydration enabled
Reproduction: https://github.com/brandonroberts/angular-v16-universal-standalone

1. Clone the repo, install the dependencies
2. Run npm run dev:ssr
3. Visit the `/todos` route
4. Notice the API request is not made
5. Reload the page
6. Notice the API request is made on the client

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@brandonroberts thanks for reporting the issue and submitting a fix! We'll review it asap.

I'm wondering if you could help to put together a test that reproduces the problem, which would also help to ensure that there are no regressions in the future? This might be a good place for a test and it should contain the necessary helpers: https://github.com/angular/angular/blob/main/packages/platform-server/test/integration_spec.ts#L1097.

Thank you.

**Comment by brandonroberts** [comment]
Thanks @AndrewKushnir! Thanks for pointing me to the integration tests also. I wasn't sure where to start on that with it being an internal token.

**Review by alan-agius4 — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@brandonroberts thanks again for the fix! We will proceed with the merge and we plan to expand the test coverage as a followup (in conjunction with other changes).

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 0b3677e1498bcc86120b72afb229fcebf85b42c1.

**Comment by brandonroberts** [comment]
Thanks @AndrewKushnir and @alan-agius4!

**Pull request closed without merging**
