### PR TITLE
feat(router): Cascading route support (4.3.x)

### PR DESCRIPTION
**Pull request by matthewerwin**
See #16416

This is rebased for merging into 4.3.x

@jasonaden FYI includes your code review request for changes on the original 4.0.x pull request.

### CODE REVIEW

**Comment by Toxicable** [comment]
@matthewerwin Why are there 3 copies of this PR?
Changes cannot be made to prior version of Angular, only newer versions

**Comment by matthewerwin** [comment]
@Toxicable there were differences due to a number of things that happened to Angular codebase since the 4.0.x version -- this PR has been around for a long time. Since I'm unsure where it makes most sense for the Angular team to merge (4.3.x would be closest to 5.x, or we can issue a PR against master).

The software change is backwards compatible so I don't know if that'll be a factor related to where it should be merged. I'm happy to delete whatever PR's don't make sense and issue against whatever branch it does...just trying to make sure that it can be managed as desired by Angular team and I'll make sure any future PR's are in alignment with the decision on how this is merged.

**Comment by Toxicable** [comment]
I don't mean sound pedantic here, but like I said before, it cannot be merged into those older versions. Even though it's a old PR, what version it goes into is based on when it's merged not when the PR was made.
Even though it's backwards compatible that's only because of semantic versioning which you would be breaking by merging this into 4.0, 4.1, 4.2 or 4.3 therefore the only option is v5, unless there is a 4.4 which there shouldn't be.

**Comment by jasonaden** [comment]
Let's just move forward with this version since it's the one that's synced to the more recent version of Angular.

@matthewerwin You can go ahead and do the compare against `master` branch. We only merge to that branch, and the 4.x.x branches are just for creating/tagging the releases.

**Comment by jasonaden** [comment]
@matthewerwin Ignore above comment.

Let's go back to #16416 as the main PR since that has the most history.

Please rebase that one against master and submit the compare against master.

Closing this PR.

**Pull request closed without merging**
