### PR TITLE
docs: add demo video for Angular CLI autocompletion doc

### PR DESCRIPTION
**Pull request by dgp1130**
This explains how to set up autocompletion with the Angular CLI via:

1. The automated prompt on first execution.
2. Via `ng completion`.
3. Manually via `source <(ng completion script)`.

It also specifically calls out supported and unsupported platforms.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Documentation content changes

## Does this PR introduce a breaking change?

- [X] No

/cc @twerske, @alan-agius4

### CODE REVIEW

**Comment by dgp1130** [comment]
@mgechev, added you as a reviewer in case someone from docs should take a look at this?

**Comment by alan-agius4** [comment]
@dgp1130, we already have an auto completion page. Maybe we’d like to add to that? The source code of this page is in the CLI repo.

https://next.angular.io/cli/completion
https://github.com/angular/angular-cli/blob/main/packages/angular/cli/src/commands/completion/long-description.md

**Comment by alan-agius4** [comment]
@dgp1130, also to generate the gif, can you please use the latest RC as there are some user visible changes.

**Comment by dgp1130** [comment]
After discussion, we decided to merge this into the existing page for CLI autocompletion to keep things a little easier to navigate in AIO. I'll make a new PR in the CLI repo with the content. We do need the gif to go in angular/angular, so I'll rescope this PR just for the gif.

**Comment by dgp1130** [comment]
Moved the new documentation to https://github.com/angular/angular-cli/pull/23146 and reduced this PR down to just the demo image. @twerske offered to re-record the video to incorporate recent changes (thanks so much!), so I'll update the demo once that's ready and re-request review.

**Review by alan-agius4 — APPROVED** [review]

**Review by gkalpak — COMMENTED** [review]
Drive-by comment: It would be great if we could reduce the GIF size (without visibly hurting quality).

**Comment by dgp1130** [comment]
> Drive-by comment: It would be great if we could reduce the GIF size (without visibly hurting quality).

Does AIO support multiple image sources? I was hoping to use an avif / webp video and fall back to gif, but I'm not sure how hard that is to do?

**Comment by gkalpak** [comment]
No, currently we don't use multiple sources for images.

**Comment by dgp1130** [comment]
Updated the image to use a GIF from a more recent CLI build (thanks so much @twerske!).

> Drive-by comment: It would be great if we could reduce the GIF size (without visibly hurting quality).

I compressed the GIF as best I could and even tried converting to Webp, but that wasn't any better (I couldn't find good optimizers for Webp videos, only images). If anyone can do better I'll be happy to update it.

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 23a99909359d5b684f82ab000eac0092811281c1.

**Pull request closed without merging**
