### PR TITLE
docs: use HttpClient in the style guide

### PR DESCRIPTION
**Pull request by danielsogl**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The style guide actually uses the deprecated HttpModule.

## What is the new behavior?
I refactored the examples to use the new HttpClient

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by brandonroberts** [comment]
Hi @danielsogl, apologies for this one becoming stale. Are you still interested in landing this PR?

**Comment by danielsogl** [comment]
Sure but I'm not sure where are the conflicts are in me PR.

**Comment by brandonroberts** [comment]
@danielsogl I don't think the conflicts exist anymore. Will you rebase the branch on top of master and change the chained operators in pipeable operators?

**Comment by brandonroberts** [comment]
@danielsogl nevermind on the operators. They have already been updated, so your changes shouldn't be needed there.

**Comment by danielsogl** [comment]
Should I update the style guides to rxjs v6 because of Angular 6?

**Comment by danielsogl** [comment]
@brandonroberts fixed

**Comment by brandonroberts** [comment]
Yes, the style guide should be using RxJS V6 pipeable operators if it isn't already.

**Pull request closed without merging**
