### PR TITLE
docs(localize): fix angular.json syntax

### PR DESCRIPTION
**Pull request by windmichael**
In the chapter internationalization (i18n) at section "Deploy multiple locales" the syntax for the angular.json is wrong.
This commit fixes the angular.json, when specifying the translation file and the baseHref for a locale.

## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
In the chapter internationalization (i18n) at section "Deploy multiple locales" the syntax for the angular.json is wrong.

## What is the new behavior?
This commit fixes the angular.json in the docs at section "Deploy multiple locales", when specifying the translation file and the baseHref for a locale.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
So there are two options here:

```jsonc
"locales": {
  "fr": "src/locale/messages.fr.xlf"
  // no baseHref
}
```

```jsonc
"locales": {
  "fr": {
    "translation": "src/locale/messages.fr.xlf",
    "baseHref": "..."
  }
}
```

But in the example text it is seen that the second one (as in this PR) is the desired one.


Reviewed-for: global-docs-approvers

**Comment by petebacondarwin** [comment]
@windmichael - thanks. Unfortunately we still have some problems. Do you see that there are 3 commits in the PR now, rather than 1? This is also perhaps why the `ci/circleci: lint` check is still failing.

What you need to do is rebase your branch on top of the `master` branch, and squash the 3 commits into one.

**Comment by windmichael** [comment]
@petebacondarwin thanks for your hint. I squashed the 3 commits as suggested by you into one commit. Please check, if it is ok now.

**Comment by petebacondarwin** [comment]
Excellent! Thanks

**Pull request closed without merging**
