### PR TITLE
docs: correct gramatical missing word in guide in angular.dev website

### LINKED ISSUE #52777: Gramatical missing word in guide in angular.dev website
### Describe the problem that you experienced

The website under this link displays the text as 
https://angular.dev/guide/ssr

CommonEngine is used render an Angular application.

But the actual should be 
CommonEngine is used to render an Angular application.
or 
CommonEngine  renders an Angular application.

### Enter the URL of the topic with the problem

https://angular.dev/guide/ssr#example-1

### Describe what you were looking for in the documentation

i was trying to understand SSR and implement it

### Describe the actions that led you to experience the problem

I was going over the documentation

### Describe what you want to experience that would fix the problem

Nothing major. Just updating text. 

### Add a screenshot if that helps illustrate the problem

image

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by Dhoni77**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Grammatical mistake in [docs](https://angular.dev/guide/ssr#example-1)

Issue Number: fixes #52777

## What is the new behavior?

Correct the grammar mistake.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by sasidharansd — COMMENTED** [review]
Can you please also update this to adev/ content folder too?

**Review by twerske — APPROVED** [review]

**Review by jessicajaniuk — APPROVED** [review]
LGTM! Thank you!

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 7252ee41621c2149fd284a683b94dc8f1beb6b19.

**Comment by jessicajaniuk** [comment]
@Dhoni77 Looks like this fix already landed in an earlier PR. Thanks for your contribution!

**Pull request closed without merging**
