### PR TITLE
feat(core) strong typing for QueryList#changes

### PR DESCRIPTION
**Pull request by JeanMeche**
## PR Checklist
A PR for #30296, it brings strong typings for QueryList#changes.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

The breaking change is fairly simple as we move from `any` to a more specific type. 

## Other information
As a pretty new to contributing to Angular, did a miss some tests or to run some script ? 
Should the PR target `main` or `15.0.x` ? 

Thx

### CODE REVIEW

**Review by hexiaokang — DISMISSED** [review]

**Comment by JeanMeche** [comment]
The unit tests on `angular/components` are failing. 

What's the process in this case ?

**Comment by JoostK** [comment]
> Should the PR target main or 15.0.x ?

By default a PR should target `main`; the PR will then merge into the appropriate branches as indicated by a `target: _` label. Other base branches are only needed when a PR can only be applied to some older version, e.g. a backport PR (if a clean cherry-pick was not possible for example).

> The unit tests on `angular/components` are failing.
> 
> What's the process in this case ?

This change is breaking, as the tightened type may now surface issues that weren't a problem before. A quick glance at the component tests make me believe that the cast in those tests is slightly incorrect, where it casts to an array instead of a `QueryList` type.

Breaking changes can only land in majors (so v16 at the earliest, as v15 is already in RC) and depending on the impact on projects it may be necessary to include a migration to insert explicit casts to the `Observable<any>` type that it used to be. The tests in Google may be a good indication on how breaking this change might be, I'm afraid it will be quite breaky.

**Comment by JoostK** [comment]
Requesting a preliminary TGP to see what the impact within Google is.

**Comment by JeanMeche** [comment]
@JoostK Thanks for your feedback. What does TGP stands for ? 

FYI, [here is the commit](https://github.com/angular/components/compare/main...JeanMeche:components:fix-breaking-changes-querylist) to fix components repo. 

Is there any doc about integrating a particular commit to the tests ?

**Comment by JeanMeche** [comment]
I see that #43604 which is closely related, was pushed back to v16. 

I will look into it, to provide a similar schematic for the migration.

**Comment by jessicajaniuk** [comment]
[TGP](https://fusion2.corp.google.com/presubmit/tap/507645770/OCL:507645770:BASE:507644630:1675739862654:52d04a16/targets)

**Comment by jessicajaniuk** [comment]
The preliminary TGP had a large amount of broken targets. A sampling of targets has breakages that would be pretty challenging to migrate.

**Comment by JeanMeche** [comment]
From what a gathered from the components repo, 

https://github.com/angular/components/blob/1186c8036182bdbb850738a57118d5bc623e9aca/src/cdk/listbox/listbox.ts#L400-L407

Is it mostly casted to `Array<T>` ? 

The migration will indeed be tricky. 

As Joost suggested, `Observable<any>` is a possibility but it might trigger implicit `any` errors.

**Comment by jessicajaniuk** [comment]
The typing errors are all over the place and not just `Array<T>`. The failures are in the thousands. So it's hard to look at all of them. In `any` case, `Observable<any>` is what is present for QueryList typing now. I don't think we'd see any difference in implicit `any` errors, but we'd have to see the migration implementation to be sure.

**Comment by JeanMeche** [comment]
Let me know what you think of the migration I just push !

**Comment by JeanMeche** [comment]
Closing to spare us the effort of landing a migration as we now have the signal queries.

**Pull request closed without merging**
