### PR TITLE
docs(language-service): fix link URLs

### PR DESCRIPTION
**Pull request by dzhavat**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, could you reformat the file with `yarn ng-dev format files packages/language-service/src/quick_info_built_ins.ts` to satisfy the linting job. Thank you.

**Comment by dzhavat** [comment]
@JeanMeche thanks for your help. Should be fixed now :)

**Comment by JeanMeche** [comment]
Could you please squash both commits, we'd like the change to be a single commit.

**Comment by dzhavat** [comment]
Should be ok now 🙂

**Review by clydin — APPROVED** [review]

**Review by devversion — APPROVED** [review]
Caretaker note: Docs only change; skipping google internal tests to save time

**Comment by devversion** [comment]
This PR was merged into the repository by commit 9097b734e5b4a942d821345fa1879f239957284b.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
