### PR TITLE
docs: replace  --create-application by --createApplication

### PR DESCRIPTION
**Pull request by thierryc**
ref: https://angular.io/cli/new

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by netfreak9** [comment]
unsubscribe all mails

**Comment by alan-agius4** [comment]
Thanks for this. Although as far as I am concerned kebab case should be preferred.

**Comment by thierryc** [comment]
image

ref: https://angular.io/cli/new v11.0.x

**Comment by alan-agius4** [comment]
The arguments format are interchangeable at least for the time being. Ie both kebab and camel cases can be used. 

In general kebab causes should be preferred in the documentation.

**Comment by alan-agius4** [comment]
Hi @thierryc,

Thanks for your contribution however, I am closing this as part of the camel cased arguments deprecation. Will be creating a PR to address CLI MAN page today.

**Pull request closed without merging**
