### PR TITLE
fix(animations): handle platform-server elements (no style prop)

### PR DESCRIPTION
**Pull request by adrienboulle**
## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

In some cases, flush animations are called in ssr, but `style` prop does not exists on ssr node elements.

Issue Number: N/A

## What is the new behavior?
`cloakElement` implementation add a `style` empty object if element has no property style

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by adebree** [comment]
Same issue as https://github.com/angular/angular/pull/17792, but different approach

**Comment by coryrylan** [comment]
We are running into the same issue on our ssr angular app

**Comment by janvandenberg** [comment]
We have the same issue

**Comment by matiger** [comment]
Is this going to be merged anytime soon? We have the same problem with server side rendering, and would highly appreciate it.

**Comment by adrienboulle** [comment]
@IgorMinar any news on this ?

**Comment by josephliccini** [comment]
Same issue here.  Looking forward to this or any fix.

**Pull request closed without merging**
