### PR TITLE
feat(security): document <iframe src> to be TRUSTED_URL.

### PR DESCRIPTION
**Pull request by mprobst**
Docs on the DomSanitizationService didn't match actual usage before.

Also fixes some minor docs and implementation issues.

Part of #8511.

### CODE REVIEW

**Comment by mprobst** [comment]
@rjamet would you mind taking a look?

I'm quoting this here from an internal discussion:

>  - for <iframe src=URL>, we require the TrustedResourceUrl contract.  That's type is primarily intended for contexts where the resource referred to by the URL will be evaluated and could result in script execution in the current origin (i.e., <script src=URL>, <link rel=stylesheet href=URL>).  However, for <iframe src> that's not the case; the risk of an untrustworthy resource in <iframe src> is that the script in the frame might navigate top.location and then mount a phishing attack, or some such.   Also, if <iframe sandbox> is used that concern goes away, and the plain SafeUrl contract would be sufficient (which says that the URL is safe (with respect to XSS) to dereference as a hyperlink, and in particular is not javascript:evil()).
> 
> I.e., requiring TrustedResourceUrl is possibly unnecessarily conservative.  OTOH, the distinction is subtle enough that introducing a separate type seemed undesirable.

**Comment by mprobst** [comment]
CC @vikerman

**Comment by rjamet** [comment]
Several things here:

- I agree with the attack scenarios for "naked" iframes: phishing, downloads and more generally other-origin javascript. You can have an alert box asking for a password, forms that grab their input without the user sending them, navigation, maybe timing measurements on some things, carpet-bombing downloads, ... That's significant attack surface, and the trustAsResourceUrl / bypassSecurity... requirement is there to show that. It's clearly not as bad as a script src, but it's also clearly not as safe to iframe arbitrary content as it is to embed an image or a link.

- Iframe sandbox: Yup, SafeUrl, if your browser supports sandboxes (older ones will ignore that attribute), and keeping in mind the ability to re-enable features. You can still trigger downloads though, but I think it's safe to ignore.

FYI, we've got https://github.com/google/closure-library/blob/master/closure/goog/html/safehtml.js#L450 in Closure for sandboxed iframes, which does some checks on the browser. Also, we chose to not track the re-enabled attributes, but that's something to consider: allowing popups is probably fine, allowing scripts + same-origin accesses is certainly not.

**Comment by mprobst** [comment]
@rjamet makes sense. I changed the PR to just fix the documentation then, how does that look?

**Comment by mprobst** [comment]
@rjamet Friendly Ping?

**Comment by rjamet** [comment]
Sorry, missed the first mail. Looks good!

**Pull request merged**
