### PR TITLE
refactor: standardize doctype declaration to <!DOCTYPE html>

### PR DESCRIPTION
**Pull request by ptu14**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

Currently, the Angular codebase contains different variations of the DOCTYPE declaration including `<!doctype html>`, `<!DOCTYPE html>` and `<!DOCTYPE HTML>`. Though these are all technically correct as the DOCTYPE is case-insensitive, they lead to inconsistency in the codebase.

## What is the new behavior?

This PR proposes to standardize the DOCTYPE declaration across the codebase to <!DOCTYPE html>, as recommended by the official HTML Living Standard documentation by WHATWG (https://html.spec.whatwg.org/multipage/syntax.html#the-doctype). It helps to present the codebase in a more standardized and aligned way with the industry best practices.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Although this may seem like a minor detail, the standardization of these declarations adds to the overall quality and consistency of the project. This change was implemented using a find-and-replace command (cmd + R), so feel free to make any further changes, or alter the target merge branch if necessary.

I kindly request you to consider this PR for merging.

Thank you for your time and consideration.

Best Regards,
Mateusz

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@ptu14 Looks like this needs a rebase.

**Comment by ptu14** [comment]
> @ptu14 Looks like this needs a rebase.

done

**Comment by JeanMeche** [comment]
Hi, could you rebase it again ? thx !

**Comment by ptu14** [comment]
> Hi, could you rebase it again ? thx !

sure, a lot of DOCTYPE have been added since then 😅

**Review by alxhub — APPROVED** [review]
Reviewed-for: global-approvers

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit de777afbc55307fafb4614755565e9dd09b6f3ab.

**Comment by JeanMeche** [comment]
Adding a note, as we're moving to prettier we're going to encounter some issues with it. 
Per #prettier/prettier#6502 & prettier/prettier#7391 prettier does format `DOCTYPE` as `doctype`.

**Pull request closed without merging**
