### PR TITLE
docs(readme): update readme - OLD

### PR DESCRIPTION
**Pull request by sjtrimble**
Add more content and organize

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Updated README file to improve usability

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sjtrimble** [comment]
Need to add a few images still.

**Comment by sjtrimble** [comment]
@gkalpak I wasn't sure about the commit message?

**Comment by gkalpak** [comment]
For the commit message, just use `docs: ...` (without a scope).
I see you created thir PR from a branch on the `angular/angular` instead of your own fork? Was it on purpose? If not, I suggest you close this a open a new PR from a branch on your fork, because certain CI checks will always fail if not run from a fork branch.

**Comment by gkalpak** [comment]
The new design looks amazing, btw 💯

**Comment by sjtrimble** [comment]
Closing and opening new PR pre @gkalpak recommendation.

**Comment by sjtrimble** [comment]
@kapilepatel you're right - I moved things over to https://github.com/angular/angular/pull/32084

**Pull request closed without merging**
