### PR TITLE
chore: build the stable branch of Dart

### PR DESCRIPTION
**Pull request by kevmoo**
Now that Dart 1.9 is stable

### CODE REVIEW

**Comment by vicb** [comment]
@kevmoo then it might be good to update all refs to the dev release in the docs, pubpec, ... as part of this PR

**Comment by kevmoo** [comment]
@vicb The only other reference to 1.9 (that I could see) was in the pubspec. The use of `1.9-dev` works great with release build. Once the `dev` build becomes `1.10-dev` we can fix that – so we don't have to worry about turning off the dev build now and turning back on later.

**Comment by vicb** [comment]
> The use of 1.9-dev works great with release build

There should be a ref in DEVELOPER.md but you're right having the "-dev" doe not hurt

> so we don't have to worry about turning off the dev build now and turning back on later.

Why would we want to turn it on later ? I think it's preferable to develop against a stable release. IIRC we've switched to -dev only because of some bugs or unimplemented features in 1.8.

**Comment by kevmoo** [comment]
> There should be a ref in DEVELOPER.md but you're right having the "-dev" doe not hurt

Good point! Will add...

> Why would we want to turn it on later ? I think it's preferable to develop against a stable release. IIRC we've switched to -dev only because of some bugs or unimplemented features in 1.8.

We had both before. It allows a sanity check of Angular on Dart bleeding-edge. Changes to future Dart that break Angular should be caught as early as possible.

**Comment by vicb** [comment]
> We had both before. It allows a sanity check of Angular on Dart bleeding-edge. Changes to future Dart that break Angular should be caught as early as possible.

I agree that testing with a -dev version could be a good thing. However we don't need to have a "-dev" in the pubspec, ie ">=1.9" is compatible with "1.10-dev"

**Comment by kevmoo** [comment]
@vicb so this is where Dart weirdness leaks in.

Currently, our `dev` branch still has `1.9-dev.10.13`. If we change to `>=1.9` then tests would fail on our dev bot.

We could change the pubspec and disable the dev branch build. But then we need to remember to re-enable it when dev branch is `1.10-dev`.

Since the -dev doesn't affect anything, we can hold off – without missing a test coverage window.

**Comment by vicb** [comment]
@kevmoo I would have thought that dev bot just pick the latest dev release available.

If not the PR is probably good to go.

**Comment by kevmoo** [comment]
@vicb The dev bot does pick up the latest dev release, but:

T-1: dev bot has 1.9-dev
T+0: stable bot has 1.9 gold (dev bot still has 1.9-dev)
T+1: dev bot gets 1.10-dev when we do our first merge from bleeding edge into dev – this happens about weekly

**Pull request closed without merging**
