### PR TITLE
docs: Add Ady Ngom to the contributors list

### PR DESCRIPTION
**Pull request by adyngom**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@adyngom Sorry for the delay. Can you squash the commits down to one and then rebase to latest? That should resolve the size check issue. Use `docs: add Ady Ngom to GDE resources` as your commit message, and that should make the lint check happy.

**Review by MarkTechson — APPROVED** [review]
LGTM - welcome, Ady!

**Comment by adyngom** [comment]
Thank you 🙏🏿🙏🏿

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 5abe0c513b63fdd86b704dc953f6dbf643303178.

**Pull request closed without merging**
