### PR TITLE
docs: update resources.json with additional book on Angular

### PR DESCRIPTION
**Pull request by DenysVuika**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Add the `Developing with Angular` book to the list of education resources (Books)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by DenysVuika** [comment]
@googlebot I signed it!

**Review by StephenFluin — CHANGES_REQUESTED** [review]
The brand name is "webpack" (all lowercase).

**Comment by DenysVuika** [comment]
@StephenFluin updated, thanks for pointing out

**Review by StephenFluin — APPROVED** [review]
Content looks OK, you'll need to squash your commits. https://twitter.com/stephenfluin/status/1009904095073718275?lang=en

**Comment by DenysVuika** [comment]
this squash thing drives me crazy :( I will create another PR as I can't make this one work

**Comment by kapunahelewong** [comment]
Hey @DenysVuika, maybe you'll find my [notes on my own workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) helpful for future reference. It also has other workflow things like squashing, etc.

**Comment by DenysVuika** [comment]
@kapunahelewong thanks a lot for the notes!

**Pull request closed without merging**
