### PR TITLE
Improve explaination of @Self decorator

### PR DESCRIPTION
**Pull request by zachary-svoboda-accesso**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The explanation currently reads:
"Parameter decorator to be used on constructor parameters, which tells the DI framework to start dependency resolution from the local injector."

This isn't incorrect exactly but I don't think it properly explains the use. As noted in the [Dependency Injection in Action](https://angular.io/guide/dependency-injection-in-action) article: "Using the @[Self](https://angular.io/api/core/Self) decorator, the injector _only_ looks at the component's injector for its providers." (Emphasis mine.) The DI search normally starts at the local injector and searches upward but `@Self` stops that upward search which is the real point of the decorator.

Issue Number: N/A

## What is the new behavior?
I edited the language to emphasize the "scoping" behavior of the `@Self` decorator rather than the starting point which does not change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Thank you for your time

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, thank you for improving the docs !

For your PR to move forward, you'll need to : 
* sign the CLA. 
* run `run yarn lint` to reformat the file
* reword your commit, not need for a scope here `docs: ....` should be sufficient !

**Comment by zachary-svoboda-accesso** [comment]
I haven't forgotten this, just bringing my org through the cla process.

**Comment by zachary-svoboda-accesso** [comment]
(still working on that cla)

**Comment by JeanMeche** [comment]
As you didn't sign the CLA I'll close the PR. 

Also please note that we're looking at deprecating angular.io in favor of https://angular.dev. Feel free to drop any PR for improvements of the new doc site !

**Comment by zachary-svoboda-accesso** [comment]
Thank you for your time @JeanMeche, sorry I couldn't get that CLA done (still trying). I see the new docs could also use this update -  https://angular.dev/api/core/Self
Where can I find that content? I don't see an update button on the page.

**Comment by JeanMeche** [comment]
It's actually the same file for both docs sites. So I'm reopening and rescoping !

**Comment by zachary-svoboda-accesso** [comment]
Thank you, it's out of my hands at the moment - waiting on sign-off from above as this is my corporate account.

**Comment by JeanMeche** [comment]
One possibility for you, could be to amend the commit and change the author email with your own.

**Comment by zachary-svoboda-accesso** [comment]
I hope it won't prove painful for it to continue dangling, I've been using this PR to push for open source at my work
(regardless, I am also unsure of the legality)

**Comment by bencodezen** [comment]
@zachary-svoboda-accesso Sorry for the number of hoops you've had to jump through for the PR. There's just a lot of CI that gets run that we need to pass through. 

It looks like there's one more change in terms of the invalid commit message. `di` is not considered a valid scope, so I think you can just amend your commit message to just be "docs: {rest_of_your_message}" to fix it.

**Comment by thePunderWoman** [comment]
I'm going to close this for now. Without resolving the CLA issue, we can't land this change. Feel free to open a new PR if you'd like to get this to land.

**Pull request closed without merging**
