### PR TITLE
fix(router): Routed components never inherit `RouterOutlet` `Environm…

### LINKED ISSUE #53369: Standalone injectors do not seem to be completely isolated
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Actually, this is more like a Stackoverflow question. But I'd appreciate if someone could help me and shed some light on this topic 😅

Just getting familiar with the concept of standalone components and now I'm a little curious about standalone injectors.

[The official documentation](https://angular.io/guide/standalone-components#standalone-injectors) says that such injectors are created in order to isolate the providers imported by a standalone component from the rest of an application. Indeed, that sounds right to me - especially in terms of "self-contained components". 

However, It seems that different standalone injectors are not fully isolated from each other in some cases ([stackblitz](https://stackblitz.com/edit/stackblitz-starters-zgv74k)). 

In the provided example the optional presense of providers at the routing configuration level deeply affects the entire tree of environment injectors.

1. When you define the "`providers`" property in the routing config (even if you leave it empty), Angular creates the corresponding `EnvironmentInjector` for a router scope and the outcome hierarchy has the following shape. As we can see, `Standalone[_AppComponent]` and `Standalone[_ChildComponent]` injectors are completely isolated and cannot affect each other.

image
(isolated injectors)

2. However, if you don't define providers in the routing configuration, the hierarchy looks completely different. Now `Standalone[_AppComponent]` and `Standalone[_ChildComponent]` injectors are chained one by one and dependencies from `Standalone[_AppComponent]` are suddenly available inside the scope of `ChildComponent`. This looks like quite the opposite thing to what the official documentation initially states.

image
(not isolated injectors)

Is this correct behaviour? And if it was added intentionally - what was supposed to be achieved? 

I admit that I may be misunderstanding the concept of standalone injectors. But for me it looks like that some dependencies provided in parent standalone components might unexpectedly leak to its child component injector's scope. Please explain me if I'm wrong 😅 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-zgv74k

### Please provide the exception or error you saw

_No response_

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.5
Node: 20.10.0
Package Manager: yarn 1.22.21
OS: darwin arm64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@schematics/angular             17.0.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by atscott**
…entInjector`

This commit ensures components in the route config predictably always get their providers from the hierarchy available to routes rather than sometimes being dependent on where they are inserted.

fixes #53369

BREAKING CHANGE: Providers available to the routed components always come from the injector heirarchy of the routes and never inherit from the `RouterOutlet`. This means that providers available only to the component that defines the `RouterOutlet` will no longer be available to route components in any circumstances. This was already the case whenever routes defined providers, either through lazy loading an `NgModule` or through explicit `providers` on the route config.

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Comment by atscott** [comment]
TGP=https://fusion2.corp.google.com/presubmit/608676576/OCL:608676576:BASE:611170876:1709182987304:d164f545/targets

**Comment by atscott** [comment]
caretaker note: Will need to patch this change to tracking_router_outlet when sycning cl/608676576

**Comment by atscott** [comment]
This PR was merged into the repository by commit da906fdafcbb302fa280a162d1c1f04369be2efa.

**Comment by atscott** [comment]
caretaker note: Please merge and sync on its own

**Comment by atscott** [comment]
This PR was merged into the repository by commit 3839cfbb18fcc70cae5a6ba4ba7676b1c4acf7a0.

**Pull request closed without merging**
