### PR TITLE
docs: add Material Design for Bootstrap to UI Component resources

### PR DESCRIPTION
**Pull request by bwsky-a**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe: add Material Design for Bootstrap to UI Component resources

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by bwsky-a** [comment]
@googlebot I fixed it.

**Comment by AndrewKushnir** [comment]
Hi @bwsky-a, thanks for re-creating this PR. It looks like there is still the same issue: your GitHub account is linked to an email that is not recognized by the CLA subsystem. The email that was used to sign the CLA is the GMail one, but the email which is used for committing the change belongs to `@mdbootstrap.com` domain. May be try using GMail email in your GitHub account and rebase the commit once again? Thank you.

**Comment by bwsky-a** [comment]
@googlebot I fixed it.

**Comment by bwsky-a** [comment]
@AndrewKushnir Thanks a lot for your help, I was able to add the CLA

**Review by gkalpak — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by gkalpak** [comment]
FYI, I rebased this on latest master to make CI green.

**Pull request closed without merging**
