### PR TITLE
Refactor some router internals

### PR DESCRIPTION
**Pull request by atscott**
Refactors some router internals to prep for upcoming features / changes to support standalone in Router.

### CODE REVIEW

**Comment by atscott** [comment]
[presubmit](https://fusion2.corp.google.com/presubmit/tap/441032984/OCL:441032984:BASE:441554715:1649879462390:a684d544/targets)

**Review by AndrewKushnir — APPROVED** [review]
👍

**Comment by dylhunn** [comment]
Could not merge into 13.3.x due to conflicts; let me know if you want to do a patch port.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit eb7661c07279212df77d554fc80890d7288fde85.

**Pull request closed without merging**
