### PR TITLE
docs: add Pato Vargas to GDE resources

### PR DESCRIPTION
**Pull request by devpato**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by devpato** [comment]
@googlebot I signed it!

**Review by IgorMinar — CHANGES_REQUESTED** [review]
can you please resolve the linting errors and compress the image to <30kb (see https://github.com/angular/angular/pull/35925#issuecomment-610081966)

also, can you please rebase the PR?

**Review by mgechev — APPROVED** [review]

**Comment by petebacondarwin** [comment]
@devpato - do you still want to land this PR? If so, can you rebase to resolve the conflicts and also address the comments about your github username?

**Comment by devpato** [comment]
Unfortunelty, I deleted the repository I had the branch on which I couldn't retrieve the branch. As suggested by @mgechev I created a new PR

https://github.com/angular/angular/pull/40030

**Pull request closed without merging**
