### PR TITLE
fix(platform-server): handle id attribute as host

### PR DESCRIPTION
**Pull request by adrienboulle**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
id is not set in the rendered document when specifying the id as an host as following:
```
@Component({
    ...
    host: {
        '[id]': 'id',
    },
})
...
```

**What is the new behavior?**
the id is properly set in the rendered document

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
Even if this fixes the issue I think it would require a little refacto as we check for the property name in an if else statment (same for `class` for instance)
I would be happy to know what do you think about that :)

### CODE REVIEW

**Comment by adrienboulle** [comment]
@alxhub Do you think this is the right way to handle the issue? I guess it fixes for `id` but not all the attributes ?

**Comment by adrienboulle** [comment]
@alxhub any news ?

**Comment by alxhub** [comment]
@adrienboulle is `id` special in parse5?

This looks okay to me. Normally property-to-attribute reflection is already handled, but this PR seems to imply that more work is necessary to make IDs work correctly.

**Comment by adrienboulle** [comment]
@alxhub imo, other attributs like for instance accesskey wont work if sets as in host property of the component.

**Comment by adrienboulle** [comment]
@alxhub any news on this ?

**Comment by vikerman** [comment]
Changed the backing from Parse5 to Domino in 5.0. Please retry

**Pull request closed without merging**
