### PR TITLE
Fix for i18n locale data undefined values (+update CLDR data)

### PR DESCRIPTION
**Pull request by ocombe**
## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
```

## What is the current behavior?
We remove `undefined` values in CLDR data

Issue Number: #22988

## What is the new behavior?
We replace `undefined` values by a constant instead

## Does this PR introduce a breaking change?
```
[x] No
```

## Other information
I've also updated the CLDR data to v33 that was just released last week.

### CODE REVIEW

**Review by vicb — DISMISSED** [review]
The second commit is not a "fix", right ?

Otherwise LGTM.

**Comment by ocombe** [comment]
Yeah I wasn't sure about the fix, "build" then?

**Comment by vicb** [comment]
`refactor` seems to be the best (A code change that neither fixes a bug nor adds a feature)

**Comment by vicb** [comment]
LGTM.
Please add the merge label once the CI is green

**Comment by vicb** [comment]
http://test/OCL:192509062:BASE:192509996:1523482369737:eade1c00

**Review by vicb — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]

**Pull request closed without merging**
