### PR TITLE
LTS BACKPORT 12.2.x - fix(compiler): ensure that partially compiled queries can handle forward references

### PR DESCRIPTION
**Pull request by petebacondarwin**
LTS backport to 12.2.x of #44113

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Caretaker: this is a backport. I "think" the failing CI tests are not related to this change.

**Comment by AndrewKushnir** [comment]
@petebacondarwin this PR is in the "draft" mode. Could you please confirm if it's ok to change it and proceed with the merge?

**Comment by petebacondarwin** [comment]
> @petebacondarwin this PR is in the "draft" mode. Could you please confirm if it's ok to change it and proceed with the merge?

@AndrewKushnir - oops sorry. I forgot to mark it ready.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit e3db0385b6ae18f35b16d5a7fcbfac49ef729330.

**Pull request closed without merging**
