### PR TITLE
ci: find latest tag when deeper than the git clone depth

### PR DESCRIPTION
**Pull request by gkalpak**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] ~~Tests for the changes have been added (for bug fixes / features)~~
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Since we have a shallow clone of the repository, it might be the case that the latest tag (which we need for publishing the build artifacts) might not be in the current history.

**What is the new behavior?**
The clone in incrementally deepened until a tag is found (or a max depth is reached).

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

**Other information**:
An alternative is to create a deeper clone from the beginning and hope that the latest tag in present (as done in #14193).

### CODE REVIEW

**Comment by IgorMinar** [comment]
@alexeagle can you please review?

**Comment by gkalpak** [comment]
BTW, if this gets approved, then it makes sense to decrease the initial clone depth in [.travis.yml][1].

[1]: https://github.com/angular/angular/blob/bc20e8ac9d99cdbbcadec331f3bf3c96ac1446a0/.travis.yml#L7

**Review by alexeagle — APPROVED** [review]
I guess we can't just fetch all the tags? Because we don't know which one was applied most recently?

thanks for making the real fix here :) I'm curious how this only just started happening..

**Review by mhevery — APPROVED** [review]

**Comment by gkalpak** [comment]
Should I amend this commit to also decrease the initial clone depth or should I not change it now that it has been approved?

**Comment by alexeagle** [comment]
We should remove the whole `git` setting again, which was just a short-term workaround.

**Comment by gkalpak** [comment]
Removed the `git` setting.

**Review by mhevery — APPROVED** [review]

**Pull request closed without merging**
