### PR TITLE
feat(renderer): use a comment instead of an element when stamping out…

### LINKED ISSUE #4805: css :first-child selector will not work when using *ng-for
It seems like when using `*ng-for="item of items"` to render a list of items, if I want to use the `:first-child` selector it will not work as expected. It looks like right before the first item, there is a `<script></script>` tag inserted, so the rendering ends up as:
```html
<ul>
    <script></script>
    <li></li>
    <li></li>
    <li></li>
</ul>
```
Probably that is intentional, but it should be taken into consideration that this would break the expected behaviour of `:first-child` and a fix for it might be a good idea.

### PR DESCRIPTION
**Pull request by tbosch**
… `<template>` elements

Closes #4805

### CODE REVIEW

**Comment by tbosch** [comment]
Reviewed in person with @vsavkin

**Comment by vsavkin** [comment]
Use comments does not work with AppView.logBindingUpdate.

**Comment by jeffbcross** [comment]
FYI I am planning to work on this after landing #5036, which hopefully will be done today (work is done, just updating docs now and then need to submit PR). The time risk of that issue depends mostly on how difficult it is to merge into google3.

**Comment by jeffbcross** [comment]
Back to work on this issue now...

**Comment by ericmartinezr** [comment]
Sorry for bumping. The changelog for alpha 47 shows that this was closed in this commit https://github.com/angular/angular/commit/bb9cfe6, but I still can see script tags in the DOM
Repro with a47
http://plnkr.co/edit/M37R7sk1tI3mwwrGgLo4?p=preview

Is that an error in the changelog?

**Comment by jeffbcross** [comment]
Oops that is a problem with our change log script not knowing when a commit
has been reverted. The change had been merged and reverted so is currently
still pending.

**Pull request closed without merging**
