### PR TITLE
PathMatch only allows full or prefix

### PR DESCRIPTION
**Pull request by deinok**

### CODE REVIEW

**Comment by deinok** [comment]
I signed it!

**Comment by jasonaden** [comment]
Looks good. Let's get this green by:

1. Update the commit message to something like `fix(router): pathMatch only allows full or prefix`
2. This is updating the public API so you need to run `gulp public-api:update` which will run a build and will update some files. You should add those updates to your commit.

There is a possibility this will break existing applications if they are using other string values. We will need to run this against Google codebase to make sure it can be merged cleanly. If it can't, it'll be a breaking change and wouldn't be in a release until `v6`. But hopefully it doesn't cause breakages and can be merged soon.

Thanks!

**Comment by deinok** [comment]
@jasonaden I changed commit message to the suggested.
I'm having problems while running that gulp command, (node versions and dont detecting that command).
Could you run it for me? I checked the "Allow edits from maintainers" so you can do changes.

**Comment by jasonaden** [comment]
Looked into this a little bit more. Unfortunately, it's a breaking change of some significance. For this reason, the build fails. For some context:

```
let pathMatch = 'full';
RouterModule.forRoot([{path: '', component: MyComp, pathMatch: pathMatch}]);
```

This will fail because the type of `pathMatch` is `string`.

If it were defined with a `const`, it would work. Or you can do: 

`RouterModule.forRoot([{path: '', component: MyComp, pathMatch: pathMatch as 'full'}]);`

But neither of those is workable as it will break too much existing code. So I'll go ahead and close this PR since we won't be able to land it. Thank you for submitting though!

**Comment by deinok** [comment]
Okey, no problem, but for next i would be nice to have it.
I think that its better to have defined the available options than accept any string

**Pull request closed without merging**
