### PR TITLE
fix(docs-infra): fix alert child margin issue

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
replace the generic `*` selector used in the alert styling with
`p` (which is what gets generated from the markdown) as the styling adds
margins which are not always wanted

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

Extra margins are added to direct children of `.alert`s this is ok for auto generated alerts which have a `p` as their only child, but not in other cases:

(see the alter here: https://angular.io/guide/view-encapsulation)
Screenshot at 2022-04-25 21-22-42

\
\
(https://angular.io/guide/lifecycle-hooks)
Screenshot at 2022-04-25 22-37-42

## What is the new behavior?

Make the selector more specific so that it targets only direct child `p` elements (which I would imagine are generally the only ones which should actually get that margin)

Screenshot at 2022-04-25 22-11-31
(PS: the alter still looks a bit off with the link wrapping onto a second line, but I it does look better :sweat_smile:)

\
\
Screenshot at 2022-04-25 22-43-39

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by dario-piotrowicz** [comment]
@gkalpak if you could have a look it would be awesome, I think the change is correct, but it can effect a bunch of places obviously, so yeah I would love to know what you think :slightly_smiling_face:

**Review by gkalpak — APPROVED** [review]
Good catch!

Theoretically, there shouldn't be alerts without a `<p>` child. (I see that some of them were accidentally introduced in 42289f25c69ec7a36d2e3ef424d32f77bc7cd19a 🤷‍♂️)

I think this is a good solution/work-around :+1:

**Comment by dario-piotrowicz** [comment]
> Good catch!
> 
> Theoretically, there shouldn't be alerts without a `<p>` child. (I see that some of them were accidentally introduced in [42289f2](https://github.com/angular/angular/commit/42289f25c69ec7a36d2e3ef424d32f77bc7cd19a) man_shrugging)
> 
> I think this is a good solution/work-around +1

Thanks :smile: 

Yes, I did check with @josmar-crwdstffng before opening the PR, not messing with the md but trying to fix the thing via css seemed the cleanest option :slightly_smiling_face: 

Alternatively I guess we could update the template generation logic so that alerts inside tables do get the child `p` :thinking: (but that sounds riskier/more complex than tweaking the css)

**Comment by gkalpak** [comment]
I doesn't have to do with tables specifically. It's more that our tooling requires (but has no way to enforce) that there is always an empty line when switching from HTML to Markdown in the templates.

Anyway, this is a good enough solution for now, so let's roll with it :+1:

**Comment by atscott** [comment]
This PR was merged into the repository by commit f282ca4f62abbb6529580228196b7a40a865f6f4.

**Pull request closed without merging**
