### PR TITLE
docs: fix typo in control-flow.md

### PR DESCRIPTION
**Pull request by DanWahlin**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Typo in sentence

Issue Number: N/A

## What is the new behavior?
Fix typo

## Does this PR introduce a breaking change?

- [ ] Yes
- [X ] No

### CODE REVIEW

**Comment by danieljancar** [comment]
The change in the docs look good, you forgot to use the semantic commit message for your commit tho. [Here](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format) is the guide. Also make sure to squash your commits incase there are multiple.

**Review by sonukapoor — APPROVED** [review]

**Review by JeanMeche — APPROVED** [review]
Thank you for fixing that ~~type~~ typo  !

**Comment by sonukapoor** [comment]
> Thank you for fixing that type !

You mean typo @JeanMeche 🤣

**Comment by atscott** [comment]
@DanWahlin could you fix the commit message? 

```
  The commit message header does not match the expected format.
  
  The expected format for a commit is: 
  <type>(<scope>): <summary>
  
  <body>
  
  ``

**Comment by DanWahlin** [comment]
I'm assuming you mean the text before the template? Removed that but if you need something else let me now.

**Comment by JeanMeche** [comment]
The commit message should in the form:
```
docs: fix typo in control-flow.md

```

`docs` commit don't require a body.

**Comment by atscott** [comment]
> The commit message should in the form:
> 
> ```
> docs: fix typo in control-flow.md
> ```
> 
> `docs` commit don't require a body.

The lint check is still failing so it needs to be fixed or this cannot be merged.

**Comment by DanWahlin** [comment]
This was submitted through the website, using the supplied template. If there's more that needs done please let me know specifics. PR title was updated, PR used the supplied template, etc. For a 1 typo fix the process is reaching the "not worth the time" stage. 😀

**Comment by sonukapoor** [comment]
@DanWahlin You need to update the commit title instead by downloading the branch to your local and run a `git commit --amend`. Unfortunately, this is not possible through the template. 

Happy to do this for you if you like.

**Comment by DanWahlin** [comment]
I'd appreciate that @sonukapoor! Not something I'll have time to do right away. Thank you.

Given that this was initiated directly from the website is there something that needs updated in that process so that others don't hit this as well? That may not be your area I realize, but to get public contributions for simple things like this (typo fix) it feels like the process is missing something since I followed what I was given. At least I think I did. 😀

**Comment by atscott** [comment]
This PR was merged into the repository by commit 1b8bf1d4b8470eb0c0f7d85bebb84b0103e38c95.

**Pull request closed without merging**
