### PR TITLE
fix(WebWorker): Make MessageBus EventEmitter synchronous

### PR DESCRIPTION
**Pull request by jteplitz**

### CODE REVIEW

**Comment by robwormald** [comment]
LGTM :+1: -

**Comment by jeffbcross** [comment]
Assigning to @btford for the merge

**Comment by jteplitz602** [comment]
Assigned to @matsko for merge

**Comment by vsavkin** [comment]
Merged via https://github.com/angular/angular/commit/69c16949001e0b0b3fd9998c09d8c2a891c7bc92

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166475.
------------------------------------------------------------------------------------------------------------


[[40402a40b0a567086e7677bf29002fa0fca344ff-673073737]]

**Pull request closed without merging**
