### PR TITLE
fix(elements): do not throw in SSR due to `HTMLElement` not being defined

### LINKED ISSUE #39950: Angular Universal: HTMLElement is not defined
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/elements

### Description

Using Angular Elements (specifically `createCustomElement`) breaks SSR.

## 🔬 Minimal Reproduction

Here's a repository that reproduces the issue: https://github.com/juristr/repro-angular-elements-with-ssr-issue

It's a newly generated Angular CLI app + with SSR using `@nguniversal/hapi-engine`.

This commit works [96f5ed9fc5f40ab61be09854200ff404090698e1](https://github.com/juristr/repro-angular-elements-with-ssr-issue/tree/96f5ed9fc5f40ab61be09854200ff404090698e1), but once I add `@angular/elements` it breaks.

## 🔥 Exception or Error
<pre><code>
/Users/.../ngssr/dist/ngssr/server/main.js:55010
class NgElement extends HTMLElement {
                        ^

ReferenceError: HTMLElement is not defined
    at Module.Dti6 (/Users/.../ngssr/dist/ngssr/server/main.js:55010:25)
    at __webpack_require__ (/Users/.../ngssr/dist/ngssr/server/main.js:20:30)
    at Module.ZAI4 (/Users/.../ngssr/dist/ngssr/server/main.js:78554:75)
    at __webpack_require__ (/Users/.../ngssr/dist/ngssr/server/main.js:20:30)
    at Module.24aS (/Users/.../ngssr/dist/ngssr/server/main.js:38572:69)
    at __webpack_require__ (/Users/.../ngssr/dist/ngssr/server/main.js:20:30)
    at Module.K011 (/Users/.../ngssr/dist/ngssr/server/main.js:61050:80)
    at __webpack_require__ (/Users/.../ngssr/dist/ngssr/server/main.js:20:30)
    at Module.uj+Y (/Users/.../ngssr/dist/ngssr/server/main.js:155539:74)
    at __webpack_require__ (/Users/.../ngssr/dist/ngssr/server/main.js:20:30)

A server error has occurred.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.2
Node: 12.14.0
OS: darwin x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@nguniversal/builders           11.0.0
@nguniversal/hapi-engine        11.0.0
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

Related:

- https://github.com/angularathens/2nd-workshop-angular-contrib/issues/10#issuecomment-735907510
- https://github.com/angular/angular/issues/24551
- https://github.com/angular/angular/pull/37799

### PR DESCRIPTION
**Pull request by gkalpak**
Previously, `NgElement` was defined as a top-level abstract class which extended `HTMLElement` in `create-custom-element.ts`. When rendering on the server, `HTMLElement` (which is provided by `domino`) is not yet available when the `create-custom-element.ts` file is imported, leading to an error.

This commit avoids referencing `HTMLElement` at the top level and converts `NgElement` to an interface. The `HTMLElement` class is used at runtime, when the `createCustomElement()` function is called (by which time `domino`'s implementation of `HTMLElement` has been made available on the global object).

Fixes #39950.

### CODE REVIEW

**Comment by gkalpak** [comment]
We need to decide whether the changing `NgElement` from an [abstract class][1] to an [interface][2] is a breaking change.
To add some context:
- `NgElement` is the return value of `createCustomElement()` and people should only care about the shape of the returned class.
- I don't think exposing the `NgElement` abstract class as public API was intentional. I assume the intention was to expose the `NgElement` type.
- People could theoretically:
  - ...be using the `NgElement` abstract class independent of other `@angular/elements` APIs.  
    _That would be of little use to them, since the class really only has one non-abstract property (a protected property initialized to `null`)._
  - ...be adding their own stuff on `NgElement.prototype` to ensure all Angular Elements have these extra properties/methods.  
    _This sounds unlikely, risky and unsupported and TS would complain about it (although that is easy to work around, of course)._

[1]: https://v10.angular.io/api/elements/NgElement
[2]: https://pr39994-93bb461.ngbuilds.io/api/elements/NgElement

**Comment by JoostK** [comment]
@gkalpak Another usage of `NgElement` as a value could be with an `instanceof NgElement` check.

**Comment by gkalpak** [comment]
Argh! Good point 😅

**Review by IgorMinar — COMMENTED** [review]
At first glance, I like [the alternative solutions](https://github.com/angular/angular/issues/39950#issuecomment-747598403) better than the proposed PR primarily because the app code should be able to assume that HTMLElement is defined upfront both in browser and server environments. But I wonder if we could somehow execute this code from a file that is known to have top-level side-effects - like the bootstrap file or polyfill file.

**Comment by gkalpak** [comment]
> But I wonder if we could somehow execute this code from a file that is known to have top-level side-effects - like the bootstrap file or polyfill file.

I am not sure what "this code" refers to. The code in this PR or the code that imports `domino` as suggested in https://github.com/angular/angular/issues/39950#issuecomment-747598403.

##
BWT, in a [related discussion][1] (private link - sorry), the conclusion was that `main.server.ts` is the most appropriate place to import that file that loads `domino.impl` onto `global`.

[1]: https://angular-team.slack.com/archives/C0DH5UDN1/p1608217041116800

**Comment by IgorMinar** [comment]
Apologies for the ambiguity, I was referring to: 
```
Object.assign(global, require('domino').impl);
```

from https://github.com/angular/angular/issues/39950#issuecomment-747598403

I agree that `main.server.ts` is the right place to load this code from and trigger the global variable assignment. Could we do that instead of this PR?

**Comment by gkalpak** [comment]
Closing this in favor of implementing the more generic (and less breaking) fix described in https://github.com/angular/angular/issues/39950#issuecomment-747598403.

Follow #39950 for updates.

**Pull request closed without merging**
