### PR TITLE
feat(router): add 1.x router code

### PR DESCRIPTION
**Pull request by btford**
This adds the Angular 1.x router to `modules/angular1_router`.

A couple questions:
- Is this the right place for this code to live?
- How should I configure CI tests to be run?

/cc @rkirov

### CODE REVIEW

**Comment by tbosch** [comment]
@rkirov could you review?

**Comment by vsavkin** [comment]
@matsko could you review it?

**Comment by btford** [comment]
I'm reassigning this to @shahata who's going to help me get this in.

**Comment by btesser** [comment]
@btford @shahata Any news on this...?

**Comment by btford** [comment]
We're still working on it. Will have more details later this week. :)

**Comment by mhevery** [comment]
Cleaning up PRs. This one has not been touched for a while. Please create new PR once ready.

**Comment by beataa** [comment]
Any news on releasing this module? We are interested in a fix for issue related with sibling named viewports, is there a chance that you have worked on it ?

**Pull request closed without merging**
