### PR TITLE
docs(docs-infra): updates to doc codeowners

### PR DESCRIPTION
**Pull request by jenniferfell**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Change to codeowners for docs

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [X] Other... Please describe: codeowners

## What is the current behavior?

Docs lead cannot approve changes to docs intro materials, such as TOH, setup, and getting started.

No doc codeowners for schematics docs. 

Issue Number: N/A

## What is the new behavior?
Docs lead can approve changes to docs intro materials. 

Tooling team can approve changes to schematics docs. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by jenniferfell** [comment]
@IgorMinar The PR we discussed a couple of weeks ago, to align my approvals with brandon's, with the exception of docs-infra. Thanks.

**Comment by jenniferfell** [comment]
Expanded PR to include adding codeowners for schematics doc. Created separate group, but it also could be merged with doc-libraries group depending on level of granularity desired.

**Review by IgorMinar — APPROVED** [review]
lgtm - I created the team and assigned the members.

**Comment by IgorMinar** [comment]
merge-assistance: ci is flaky

**Pull request closed without merging**
