### PR TITLE
Final ESM changes

### PR DESCRIPTION
**Pull request by devversion**
**Overall goal**:

* Currently our Bazel setup still produces CommonJS output. This output is mostly used by tests. Even though we ship ESM to our users through NPM, we test CommonJS here in the repository.
* Given that we test CommonJS, but ship ESM- our code needs to be able to work with both module systems. e.g. using `require` in a safe way, but also not being able to use `import.meta.url` (since it's unknown syntax for CJS).
   * Removing CommonJS here- allows us to simplify our code significantly
   * An easier mental model of "ESM only"
   * We test more closely what we actually ship more 
* No longer relying on the `ts_library`/ng_module` devmode/prodmode constructs allows us to migrate to e.g. `rules_js` in the future (a better & maintained variant of `rules_nodejs`).
   * Rules NodeJS originated out of g3 and shows its ESM incompatibilities.
   * That's the reason we need to patch/trick the current rules into actually supporting ESM at all..

See individual commits

### CODE REVIEW

**Comment by devversion** [comment]
Caretaker note: When merging, patch https://critique.corp.google.com/cl/496086044 before Copybara

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by josephperrott** [comment]
Looks like there is an error in some of the commit messages syntax

**Comment by devversion** [comment]
Yeah, now that I have your approval, I will re-target this PR to `main` (from `esm-stage-1`) and will now fix up the commit messages when all commits are part of it.

**Review by alxhub — APPROVED** [review]

**Comment by devversion** [comment]
This PR was merged into the repository by commit 22871e952d79f5a25d757e777684b524abf967e4.

**Pull request closed without merging**
