### PR TITLE
fix(compiler-cli): do not report multiple diagnostics for undecorated classes w/ Angular features

### PR DESCRIPTION
**Pull request by devversion**
* See individual commits.

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: fw-ngcc

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: public-api

I tried to look at the other code too, but I'm supremely out of my wheelhouse here

**Comment by jessicajaniuk** [comment]
@devversion Did you still want to land this PR? It looks like it would still be helpful and relevant.

**Comment by devversion** [comment]
@jessicajaniuk his change is tricky. I felt confident about it back in the days but we have decided to hold off with it because @alxhub mentioned that he wanted to restructure some compiler-parts to make this easier/and more reasonable to implement.

I'm not sure if that refactoring has happened yet. @alxhub can you please weight in on that?

**Comment by devversion** [comment]
Closing as I have not seen any urgency on this issue/I do not even know if this is still an issue, and if it was without anybody complaining, then it's not worth investing time regardless! can always re-open

**Pull request closed without merging**
