### PR TITLE
docs(aio): fix typo for broken link

### PR DESCRIPTION
**Pull request by maasencioh**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```
## Extra information
The line 108 is not rendering correctly, maybe should be changed to the clas `l-sub-section`?

### CODE REVIEW

**Comment by maasencioh** [comment]
I signed it!

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Good catch! Thx 👍

**Comment by gkalpak** [comment]
Actually, I am going to close this as duplicate of #20288 (which was submitted first - sorry, maybe next time :smiley:)

**Comment by maasencioh** [comment]
@gkalpak thanks!, but the other comment is not fixed, but I don't know if my proposition is accepted for you?
> The line 108 is not rendering correctly, maybe should be changed to the clas l-sub-section?

**Comment by gkalpak** [comment]
Sorry, I missed that comment. This happens because our markdown-to-html processor requires an empty line between the HTML tags and the markdown content. Can you please submit a new PR for that.
 Essentially, you we need to add empty lines around the markdown:

```diff
 <div class="alert is-helpful">
+                                                                                   
    Learn more about _providers_ in the [NgModules](guide/ngmodule#providers) guide.
+                                                                                   
  </div>
```

**Pull request closed without merging**
