### PR TITLE
fix(di): add support for reflection on parameterized types in Dart

### LINKED ISSUE #5704: Dart dependency injection ignores type arguments on component constructors parameters
https://github.com/angular/angular/issues/1691 and https://github.com/angular/angular/pull/1779 provide for injection of generics via `TypeLiteral`s.  However, this does not appear to have been extended to injection of parameters into component constructors.  E.g., if I have a `FooComponent` that takes a `List<String>` as a parameter to its constructor, adding a provider for `TypeLiteral<List<String>>` will not result in a value being injected into the `FooComponent` constructor; I have to add a provider for `List`.

This is because `ParameterWriterMixin` only writes out the type name into the parameter model, ignoring the type arguments.  I believe that this can be resolved by writing out a `TypeLiteral` for parameters with type arguments and adding a case in `_extractToken()` in [provider.ts](https://github.com/angular/angular/blob/master/modules/angular2/src/core/di/provider.ts) to set the token to the `.type` of the `TypeLiteral`.

### PR DESCRIPTION
**Pull request by nealgroothuis-zz**
fixes #5704

### CODE REVIEW

**Comment by nealgroothuis** [comment]
Do I need to sign an individual CLA, since I'm already covered by the Google corporate one?

**Comment by IgorMinar** [comment]
@nealgroothuis  yes, see http://go/googler-cla

**Comment by nealgroothuis** [comment]
I signed it!

**Comment by btford** [comment]
@IgorMinar @nealgroothuis: What's the status of this?

**Comment by nealgroothuis** [comment]
Is there anything further I can do at this point?

**Comment by alxhub** [comment]
Hello @nealgroothuis,

If you could rebase this change and ensure it passes the tests, that would be awesome.

Thanks!

**Comment by nealgroothuis** [comment]
Hi @alxhub ,

I've rebased a couple of times, but the CI builds are failing.  The test failures don't appear to be due to my changes, but it's hard to be sure, since it looks like master itself is broken and has been for a while.

**Comment by tbosch** [comment]
We need to double check that we don't get merge problems for in flight
changes with this...

**Comment by tbosch** [comment]
Unless this is urgent, this has to wait until #6270 is done. Sorry!

When that is done we should revisit this PR again. Also this use integration tests instead of unit tests, and also not copy the existing unit tests from `element_spec.ts` (which won't exist after #6270 is done).

**Comment by nealgroothuis** [comment]
Looking at #6270, I suspect this may end up being a complete rewrite. :-)   Any guess on timeframe?

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166499.
------------------------------------------------------------------------------------------------------------


[[18b703baefb95d083a27c4b5c9379b822c8ac9fb-673073826]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166554.
------------------------------------------------------------------------------------------------------------


[[6457cb887ebdedd10387c324645f0c7ae5dadb48-673074181]]

**Comment by mhevery** [comment]
This PR is stale (does not rebase; pass CI; had no activity for a while). It is probably our fault, and we are sorry. In an effort to keep our PR queue under control, and prevent us from taking too long to get back to you we are cleaning up the queue. Unfortunately this means that this PR is getting closed.

If you would like to resurrect this change, please rebase on master, make the tests pass and create a new PR.

**Pull request closed without merging**
