### PR TITLE
fix(router): make sure deactivation does not fail when router outlet cannot be found

### PR DESCRIPTION
**Pull request by jlowcs**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
If no router-outlet is present (usually because of the router-outlet being inserted conditionally, ie with a ngIf for instance) and deactivation checks are set on the route, the routing will fail with an error:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'component' of null
TypeError: Cannot read property 'component' of null
[..]
```

Issue Number: 18253

## What is the new behavior?

It checks whether there is an outlet. If not: Simply skip the deactivation checks (which are related to a component) instead of hard fail.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

This is heavily inspired from https://github.com/angular/angular/pull/19374, whose maintainer (@blaubaer) is currently inactive.

### CODE REVIEW

**Comment by jlowcs** [comment]
The Travis build failure seems to have nothing to do with the changes...

**Comment by alfaproject** [comment]
Still no test tho

**Comment by vincentjames501** [comment]
@jlowcs , I sent you a PR with a test that would fail w/o your change into this branch. Cheers!

**Comment by vincentjames501** [comment]
I'm OK with my commit going in this PR @googlebot .

**Comment by vincentjames501** [comment]
@mhevery , since you are adding tags, can you change the CLA one as we've both agreed by chance?

**Comment by ChBernat** [comment]
Can we have this merged, please?

**Comment by professphysics** [comment]
+1

**Comment by jordandh** [comment]
Is there something keeping this PR from being merged that we can help with?

**Review by jasonaden — APPROVED** [review]
This looks good. Thanks for getting this cleaned up.

[Presubmit](http://test/OCL:212052652:BASE:212052798:1536361874568:97099532)

**Comment by IgorMinar** [comment]
@jasonaden can you please rebase this? thanks

**Comment by dcantu476** [comment]
This totally fixed my problem. I hope it gets merged in soon

**Comment by jlowcs** [comment]
I just rebased the branch. Regarding the CLA, @vincentjames501's commit hasn't changed and he already said he's ok with this.

**Comment by vincentjames501** [comment]
And I'm still OK with the commit 👍

**Comment by jmleoni** [comment]
I can't wait to have this fixed ! 👍

**Comment by Abadii** [comment]
Pleaaase get this fixed..

**Comment by jpduckwo** [comment]
Hanging out for this...

**Pull request closed without merging**
