### PR TITLE
docs: tohpt3 typo fix

### LINKED ISSUE #21384: Attention, maybe there is a typo here?
Attention, maybe there is a typo here?
https://angular.io/tutorial/toh-pt3#update-the-heroescomponent-template  
**HeroComponent** - not true, **HeroesComponent** - right

_Not true_
> It's a one way data binding from the selectedHero property of the **HeroComponent** to the hero property of the target element, which maps to the hero property of the HeroDetailComponent.

_Right_
> It's a one way data binding from the selectedHero property of the **HeroesComponent** to the hero property of the target element, which maps to the hero property of the HeroDetailComponent.

### PR DESCRIPTION
**Pull request by kapunahelewong**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A
Closes #21384.

## What is the new behavior?
Fixes a typo.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Moves #21594.

### CODE REVIEW

**Review by jenniferfell — APPROVED** [review]
LGTM

**Comment by jenniferfell** [comment]
@StephenFluin: I reviewed the original issue, the original doc, and this fix. LGTM. Now HeroComponent is HeroesComponent, as it should be in this doc. When you're done with your review, go ahead and set the "PR action: Merge" label or tag me, and I'll do it.

**Comment by jenniferfell** [comment]
@kapunahelewong @gkalpak Any idea why marypoppins didn't run until I set the aio: preview label? Just curious.

**Comment by gkalpak** [comment]
For previews to be shown automatically, the PR author has to be a member of the `angular-ocre` or [aio-contributors][1] GitHub teams. @kapunahelewong is not a member of either (I would expect her to be a member of [aio-contributors][1]).

@jbogarthyde, @chembu and @dennispbrown are.
@jenniferfell and @kapunahelewong aren't :grin:

(cc @IgorMinar)

[1]: https://github.com/orgs/angular/teams/aio-contributors/members

**Review by StephenFluin — APPROVED** [review]

**Comment by vicb** [comment]
already fixed in master, closing

**Pull request closed without merging**
