### PR TITLE
docs: fix typo in ng_control.ts

### PR DESCRIPTION
**Pull request by gkarapeev**
## PR Type:
Documentation content changes

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
Hi @gkarapeev, thanks for creating this PR. Could you please sign the CLA by following instructions in https://github.com/angular/angular/pull/38157#issuecomment-661790839, so we can proceed with the review? Thank you.

**Comment by gkarapeev** [comment]
> Hi @gkarapeev, thanks for creating this PR. Could you please sign the CLA by following instructions in [#38157 (comment)](https://github.com/angular/angular/pull/38157#issuecomment-661790839), so we can proceed with the review? Thank you.

Hi @AndrewKushnir, yes I did it.

**Comment by AndrewKushnir** [comment]
Hi @gkarapeev, based on the https://github.com/angular/angular/pull/38157#issuecomment-661790839, you should reply here with `@googlebot I signed it!` to complete the process. Thank you.

**Comment by gkarapeev** [comment]
@googlebot I signed it!

**Comment by AndrewKushnir** [comment]
Update: it looks like verification was completed, so we can proceed with this PR.

**Review by AndrewKushnir — APPROVED** [review]
The change looks good, thanks for improving Angular docs!

**Pull request closed without merging**
