### PR TITLE
docs: add NG Poland 2022 and JS Poland 2022 to events

### PR DESCRIPTION
**Pull request by kalbarczyk**
add NG Poland 2022 and JS Poland 2022 to events

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@kalbarczyk the are a couple of things that are needed before we can merge this PR:
* you will need to sign the CLA
* CI is [currently failing](https://app.circleci.com/pipelines/github/angular/angular/49763/workflows/892df8af-fb28-487d-bf60-8b4c31bde8cf/jobs/1211806) due to the commit message that is not following our conventions. Could you update the commit message to be something like `docs: add NG Poland and JS Poland to events`

Thnx!

**Comment by kalbarczyk** [comment]
I have already signed the CLA, but it is still not updated. 
Commit message is changed to proposed. 
Thank you!

**Comment by pkozlowski-opensource** [comment]
@kalbarczyk 
* CLA: please make sure that you've signed it with the same e-mail as used to author the PR - this is the most common of problems. Currently your commit shows `kalbarczyk@users.noreply.github.com` as the author.
* commit message: thnx for updating the PR _title_ but you need to actually update the _commit message_ - those are 2 separate things...

**Comment by kalbarczyk** [comment]
I have created a new PR (#47128) with a corresponding email address. I hope it is ok now. Sorry for the confusion.

**Pull request closed without merging**
