### PR TITLE
Detecting lifecycle

### LINKED ISSUE #2120: Interface-based lifecycle methods
We currently declare lifecycle callback methods in annotations:

```dart
@Component(
  lifecycle: const [onChange]
)
class MyComponent {
  void onChnage() { ... }
}
```

This is not idiomatic in Dart and error-prone in both Dart and TypeScript. Note that in the example above I misspelled the method. Also note that the signature of the method is wrong. There's no warning from the analyzer about these mistakes.

## Proposal

This is more idiomatic Dart:

```dart
@Component()
class MyComponent implements OnChange {
  @override
  void onChange(_) { ... }
}
```

With this you get much better feedback from tools.

Because `@Component` is shared between Dart and JS we will extract "lifecycle" property into its own annotation `@Lifecycle` for use with JS:

```typescript
@Component({...})
@Lifecycle({[onChange]})
class MyComponent {
  onChange():void { ... }
}
```

The reason we need to keep `@Lifecycle` is because TypeScript does not reify interfaces, so there is no way to reflectively tell if a class implements an interface.

Components intended to transpile to both languages (such as our own material components) would simply use both:

```typescript
@Component({...})
@Lifecycle({[onChange]})
class MyComponent implements OnChange {
  onChange(_):void { ... }
}
```

Dart would ignore `@Lifecycle` and JS would ignore `implements OnChange`.

Related issue: #1943

### PR DESCRIPTION
**Pull request by vsavkin**
Closes #2120

/cc @yjbanov 

This PR contains only the reflective version of the feature. @kegluneq will have to update the transformer to update the registered type info after this PR is merged. I use the same reflector object, so I hope it won't be very difficult.

### CODE REVIEW

**Comment by vicb** [comment]
I don't think this "Closes #2120", more discussion needs to happen there ?

**Comment by vsavkin** [comment]
@vicb The OnChange interface is already in master. This PR does not change the name. What else apart from names require the discussion?

**Comment by vicb** [comment]
The structural type check for JS ?

**Comment by vsavkin** [comment]
Misko and I talked about it yesterday and decided on that. This is the only way to do checks in JS, and you can always override the behavior using the lifecycle property in the annotation.

**Comment by vicb** [comment]
Why don't we drop the lifecycle property then ? (keeping both is confusing IMO).

**Comment by vsavkin** [comment]
We need to be able to detect this info statically. If you add onChange reflectively, then you need a way to tell Angular that onChange will be there.

**Comment by vicb** [comment]
LGTM when Travis is green. 
As discussed we'll open an issue to discuss the structural type check/renaming

**Pull request merged**
