### PR TITLE
docs: add docs about build cache

### PR DESCRIPTION
**Pull request by alan-agius4**
With this change we add docs about persistent disk cache with was enabled by default in the CLI via https://github.com/angular/angular-cli/pull/21827

---
**NB:** I am uncertain if https://angular.io/guide/build is the right page for this, I can see that the contents of this page can also be in either https://angular.io/cli or new page under https://angular.io/cli similar to https://angular.io/cli/usage-analytics-gathering.

**_Following a convo with @dgp1130 and @clydin, it is preferred that to do a new page similar to https://angular.io/cli/usage-analytics-gathering_**

### CODE REVIEW

**Review by aikithoughts — COMMENTED** [review]
Nice work! A few comments to help improve clarity.

**Comment by alan-agius4** [comment]
> @alan-agius4 I noticed several resolved comments, but no changes were made. Did I miss something?

I did miss a push for a single change.

They should be resolved, I’ll double check again later.

**Review by aikithoughts — COMMENTED** [review]
Getting there! Just a couple of other small changes based on your feedback.

**Comment by alan-agius4** [comment]
Thanks for the suggestions @aikidave.

**Comment by alan-agius4** [comment]
@aikidave, I rechecked and I cannot find any unaddressed comments from the resolved once. 

I also pushed the changes related to `Clearing the cache` section.

**Review by aikithoughts — APPROVED** [review]
LGTM! Thanks, Alan!

Reviewed-for: global-docs-approvers

**Review by clydin — APPROVED** [review]

**Pull request closed without merging**
