### PR TITLE
[11.2.x] build: preparation for primary branch rename in the Angular repos

### PR DESCRIPTION
**Pull request by devversion**
Preparation for the framework repo as outlined our planning
document.

### CODE REVIEW

**Comment by devversion** [comment]
I added merge assistance because the test failures are unrelated here and its unlikely we will need a v11 LTS (which is ending in 1month anyway)

**Comment by dylhunn** [comment]
>  the test failures are unrelated here

It looks like `ng_update_migrations_test` is failing only on this PR, and even after a rerun. Are you sure this is unrelated?

**Comment by devversion** [comment]
@dylhunn Yes. The integration test is not locked to a specific Angular major update, and since we cut new majors, it fails (it tests the update to v13 in the v11 branch -- not going to work 😛). The test should likely be improved in the future, but that is unrelated to here.

**Comment by dylhunn** [comment]
> @dylhunn Yes. The integration test is not locked to a specific Angular major update, and since we cut new majors, it fails (it tests the update to v13 in the v11 branch -- not going to work 😛). The test should likely be improved in the future, but that is unrelated to here.

OK thanks, I'll go ahead and merge this!

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 7fbe7b73222d38b18088c676e2767f1e61ddbcc2.

**Pull request closed without merging**
