### PR TITLE
Clean up: Using toPromise() for obs to promise

### PR DESCRIPTION
**Pull request by ansh-ag**
Using toPromise() instead of custom implementation for observable to promise

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ansh-ag** [comment]
> @googlebot I signed it!

**Review by ansh-ag — COMMENTED** [review]
new to open source, would be great if somebody can help me with their review on this. :-)

**Review by petebacondarwin — COMMENTED** [review]
Thanks for this PR.
Given that `toPromise()` is deprecated and will be removed in RxJS 8, I don't think it is wise for us to use it here.

**Comment by JoostK** [comment]
Heya, thanks for your contribution!

The `toPromise` function is intentionally not used here, as it has been deprecated in RxJS 7. The replacement `lastValueFrom` has different behavior than is desired in this case, as an initializer observable only has to be completed, whereas `lastValueFrom` would throw if no values had been emitted. That's why this custom implementation is used.

**Comment by ansh-ag** [comment]
@JoostK and @petebacondarwin 

Thank you for your review. :) 
I agree with you both, so I'm closing this pull request.

**Comment by destus90** [comment]
@JoostK 
> The replacement lastValueFrom has different behavior than is desired in this case, as an initializer observable only has to be completed, whereas lastValueFrom would throw if no values had been emitted

We could provide `defautlValue` in the config object in order to avoid throwing an error with no values emitted.

https://stackblitz.com/edit/rxjs-5nbnxe?devtoolsheight=60

**Comment by JoostK** [comment]
@destus90 Neat! I did not know that. It was added very close to the RxJS final (in ReactiveX/rxjs#6204), a couple weeks later than when #33222 landed :-) We can't switch to that as long as we support RxJS 6 though.

**Pull request closed without merging**
