### PR TITLE
Typo and grammar fixes in docs

### PR DESCRIPTION
**Pull request by ashishpatelcs**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe: typo and grammar fixes

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Squash the commits down to a single commit and update the git commit message according to the guidelines https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by ashishpatelcs** [comment]
Hi @brandonroberts I'm unable to squash these commits. can you please show me some light?

Thank You!

**Comment by brandonroberts** [comment]
@ashishpatelcs Sure.

Instructions on how to rebase/squash your branch:

1. Change to your cloned repo - `cd angular`.
2. Checkout master - `git checkout master`.
3. Rebase from upstream - `git rebase upstream/master -i` .
4. Next to each commit besides the first one, change the hash to an `s`. This will mark the commit to be squashed into the previous commit.
5. Exit out of your editor to save the changes and start the rebase.
6. Fix any rebase conflicts if needed, following the prompts.
7. Push your changes back up to origin - `git push origin --force-with-lease master`

If you need additional help, let me know.

**Comment by ashishpatelcs** [comment]
I've created a new PR #26919 with a single commit.

**Pull request closed without merging**
