### PR TITLE
docs: update support policy of angular releases to account for 7.0.0

### PR DESCRIPTION
**Pull request by preethamvishy**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Support policy only lists support upto ^6.0.0

Issue Number: #26616

## What is the new behavior?
Support policy updated to include ^7.0.0

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by alfaproject** [comment]
Version 4 is no longer LTS

**Comment by preethamvishy** [comment]
Good spot! I think creating a separate issue for this would be a good idea.

**Comment by jenniferfell** [comment]
Duplicate of https://github.com/angular/angular/pull/26660

**Comment by jenniferfell** [comment]
Thanks. I've incorporated your suggestion and the one in the comments re v4 into a larger PR with updates to this doc. The other PR:

* Changes table to markdown format 
* Adds v9 to the future release schedule table
* Makes a few other editorial changes for ease of reading

Thanks again!

**Comment by jenniferfell** [comment]
I appreciate your help on this. I'm going to close your PR, now that the changes have been incorporated into the other PR. Sorry I didn't see yours first, but as you can tell from the other PR we had a few other cleanup items to handle at the same time. Thanks again!

**Comment by preethamvishy** [comment]
No problem! 👍

**Pull request closed without merging**
