### PR TITLE
fix(aio): fix presskit typos

### PR DESCRIPTION
**Pull request by wardbell**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@wardbell - what have you done here? I think in rebasing you have somehow merged your commit into @gkalpak's!

**Comment by lazaridis-com** [comment]
@petebacondarwin , maybe github is just not the right place for a project like angular. I mean, look a this chaos:

* a googlebot
* a ci thing
* a code-review thing
* a cla thing

and I just realize that this "mary-poppins" is a thing, too:

Shouldn't  a decent development-infrastructure integrate all this, naturally, without the UI / flow getting messed up by bots&tools-user-bots? I try to follow some issues on this repo, and got really kind of an headache!

Essence: angular should migrate to a decent project-infrastructure.

**Comment by gkalpak** [comment]
And to make things worse, there is a @petebacondarwin thing popping up in between 😛 
<sub>(BTW, I am pretty sure @mary-poppins doesn't enjoy being called "a thing" 😛)</sub>

**Comment by wardbell** [comment]
@petebacondarwin @gkalpak Apologies. I fixed it. Now it is only my change.

**Review by petebacondarwin — APPROVED** [review]

**Pull request merged**
