### PR TITLE
docs: fix grammar issues in various markdown files

### PR DESCRIPTION
**Pull request by vyom1611**
docs: fixing grammar in main docs

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Changed grammar in docs

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM, but can you please amend your commit and fix the lint check?

1. Running locally `git amend`
2. Changing the commit message to something like:

```
docs: fix grammar issues in various markdown files

Fixes grammar issues in various markdown files, like the `CHANGELOG.md`
```

3. Force-pushing to your remote.

**Comment by vyom1611** [comment]
Changed the commit message and fixed the pull-request format

**Review by devversion — APPROVED** [review]
Thank you!

**Comment by devversion** [comment]
Caretaker note: Feel free to only merge into `main` if this conflicts.

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 2095a08781167e91a60a4cec65c694688b319cd0.

**Pull request closed without merging**
