### PR TITLE
docs(docs-infra): first-app-lesson typo fixes

### PR DESCRIPTION
**Pull request by architect254**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, there are conflicts on your PR can you rebase your changes on `main` ? 

Also can you reword your commit and drop the `doc-infra` scope. `docs` commits are fine without it. `docs-infra` are meant for updates on the angular.io app for example.

**Comment by architect254** [comment]
@JeanMeche what is the base

**Comment by JeanMeche** [comment]
@architect254 I'm not sure I understand your question.

**Comment by architect254** [comment]
@JeanMeche , Im a noob. I believe git rebase required the base as a parameter. Ive run git rebase in my local copy and the response is its already upto date

**Pull request closed without merging**
