### PR TITLE
[4.x only] 	feat(compiler): should only inject services annotated with @Injectable

### LINKED ISSUE #12467: Improve error message for when Injectable() is missing
**I'm submitting a ...** 

```
[x] bug report
```

**Current behavior**
If component A has a dependency on service B, but service B does not have the `Injectable()` decorator defined, a vague error message is thrown:

```
Can't resolve all parameters for SomeService: (?, ?)
```

This is the exact same error message for [when dependencies can't be loaded](http://stackoverflow.com/questions/37902476/automatic-ordering-of-exports-in-index-ts-makes-app-crash/37907696). Up until now that error message was given because I use barrel files and the order of import/exports should be adjusted. Thus, I was thrown off when trying to fix this problem.

**Expected behavior**
A specific error message like:

```
SomeService was provided, but an `Injectable()` decorator was not found
```

**Minimal reproduction of the problem with instructions**
- Create a service, but omit the `Injectable()` decorator. This service should have a dependency to at least one other service (defined correctly).
  
  ```
  import { Injectable } from '@angular/core';
  
  // oops, forgot the decorator
  export class SomeService {
    constructor(private otherService: OtherService) { }
  }
  
  @Injectable()
  export class OtherService { }
  ```
- Provide the services with the module.
- Create a component that gets the `SomeService` injected.

I used the Plnkr of the Angular quickstart to [reproduce this problem](http://plnkr.co/edit/VfNug0dJFNPcmeeboKzi?p=preview). On the `Car` service in `app/car/car.ts`, I simply removed the decorator. The console immediately shows the error:

```
Can't resolve all parameters for Car: (?, ?)
```

// Edit:
In the documentation, [it is mentioned that the injector will throw a `NoAnnotationError`](https://angular.io/docs/ts/latest/api/core/index/Injectable-decorator.html), but the link to [`NoAnnotationError`](https://angular.io/docs/ts/latest/api/core/index/NoAnnotationError) results in a 404.

**What is the motivation / use case for changing the behavior?**
A more precise error message would direct me to the problem instantly and the problem could have been fixed in a matter of seconds. Because this message is the exact same as when dependencies can't be resolved due to import/export order with barrel files, it now took me 30 minutes of stripping dependencies and order checking before I noticed this simple and tiny mistake.

**Please tell us about your environment:**
Windows 10, Chrome 53 and SystemJS as the module loader.
- **Angular version:** 2.0.0 and upwards. It is still a problem in 2.1.0.
- **Browser:** The web application crashes in all browsers. Chrome 53 and Edge 38 clearly show the error in the console. Firefox however, shows a `CompileMetadataResolver` and I'm not able to find a more specific error message.
- **Language:** TypeScript 2.0.3.
- **Node (for AoT issues):** 6.0.0.

### LINKED ISSUE #13820: [4.x] Don't allow injecting classes without @Injectable
- `Injectable` or any sub classes,
- Should be deprecated in 4.x, remove in the next major release,
- As of now it is possible when the ctor has no arguments or if any other decorator is applied.

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Closes #12467
Closes #13820

### CODE REVIEW

**Comment by Toxicable** [comment]
hi

**Comment by DzmitryShylovich** [comment]
@vicb @chuckjaz it's a breaking change. can you take a look please? thanks

**Comment by laco0416** [comment]
it can make a huge impact on existing apps. I think it needs deprecation phase and warning message.

**Comment by Toxicable** [comment]
@laco0416 I agree it will have a huge impact but what exactly is it deprecating? and it does have a warning message: ` syntaxError(`${stringifyType(identifier)} must be annotated with @Injectable`));`

**Comment by laco0416** [comment]
I expect it emits only warning messages without any effects on application behavior.

**Comment by DzmitryShylovich** [comment]
@laco0416 
> it can make a huge impact on existing apps

don't think so. it's already recommended in the style guide to always use `Injectable`.

**Comment by laco0416** [comment]
First, the style guide says only "Use `@Injectable()` instead of `@Inject()`. 

https://angular.io/docs/ts/latest/guide/style-guide.html#!#07-04

> Do use the `@Injectable` class decorator instead of the `@Inject` parameter decorator when using types as tokens for the dependencies of a service.

And as you say, the _recommendation_ is existing at https://angular.io/docs/ts/latest/guide/dependency-injection.html#!#injectable . but this is just **suggestion**. not a caution.

Angular hasn't warned Injectable-less services anywhere yet. It's not ready to be broken.

**Comment by vicb** [comment]
Only security fixes go to 4.x

**Pull request closed without merging**
