### PR TITLE
docs(docs-infra): change format diagrams&colors

### LINKED ISSUE #56314: docs: diagrams have wrong colors on angular.dev
### Describe the problem that you experienced

Compare the diagram on angular.dev page with GH Markdown version:
[angular.dev](https://angular.dev/best-practices/skipping-subtrees#an-event-is-handled-by-a-component-with-default-change-detection):
image

[GH Markdown](https://github.com/angular/angular/blob/main/adev/src/content/best-practices/runtime-performance/skipping-subtrees.md#an-event-is-handled-by-a-component-with-default-change-detection):
image

All diagrams are supposed to be displayed in color as specified in the Markdown file.

### Enter the URL of the topic with the problem

https://angular.dev/best-practices/skipping-subtrees#using-onpush

### Describe what you were looking for in the documentation

_No response_

### Describe the actions that led you to experience the problem

_No response_

### Describe what you want to experience that would fix the problem

_No response_

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by vladboisa**
Change the format of diagram to the hexagone node & make color of event node more brighter for dark theme

Fixes #56314

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #56314 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
The styling needs some improvement on the dark theme. 
Could you please have a look at it ? Thank you. 

Screenshot 2024-07-13 at 00 39 34

**Comment by vladboisa** [comment]
> The styling needs some improvement on the dark theme. Could you please have a look at it ? Thank you.
> 
> Screenshot 2024-07-13 at 00 39 34

Do you mean change the black rectangles? Or more in the direction of colour contrast

**Comment by vladboisa** [comment]
> The styling needs some improvement on the dark theme. Could you please have a look at it ? Thank you.
> 
> Screenshot 2024-07-13 at 00 39 34

cc @JeanMeche

**Comment by JeanMeche** [comment]
Yes, we'd need better contrast on the dark theme

**Comment by vladboisa** [comment]
> Yes, we'd need better contrast on the dark theme


I already fix the contrast by 251ae8e , can u adev: preview, and approve my vision? ;)
Thank for your time, and opportunity to contribute to the Angular Community!

**Comment by JeanMeche** [comment]
Fixes by #58223

**Pull request closed without merging**
