### PR TITLE
fix(compiler): report better error on interpolation in an expression

### LINKED ISSUE #27740: Using {{}} interpolation in an expression causes toUpperCase error
Accidental use of interpolation expressions inside an existing expression context results in a strange error.

Example:

```html
<div *ngIf="name && {{name}}"></div>
```

results in:

```text
Template parse errors:
TypeError: Cannot read property 'toUpperCase' of undefined ("<div [ERROR ->]*ngIf="name && {{name}}">
```

Live example here: https://stackblitz.com/edit/touppercase-of-undefined?file=src/app/app.component.html

Instead of throwing a more useful syntax error, we crash (probably in the attempt to throw the useful error).

### PR DESCRIPTION
**Pull request by krzysztof-grzybek**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Fixes #27740

## What is the new behavior?

Compiler report proper "unexpected token" error.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by atscott** [comment]
Hi @krzysztof-grzybek, thanks for the fix. Are you still interested in working on this? You'll need to rebase this and update the test a bit, but other than that this looks like a reasonable fix to me.

**Comment by krzysztof-grzybek** [comment]
Yes, I will fix it in the next few days, probably tommorow.

**Comment by krzysztof-grzybek** [comment]
@atscott I updated my PR, I think it's ready for code review.

**Review by petebacondarwin — APPROVED** [review]
LGTM!

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
[presubmit](https://test.corp.google.com/ui#id=OCL:344260331:BASE:344260345:1606322887516:c21c204b)

**Review by JoostK — APPROVED** [review]
The change LGTM. In the future we may want to look into calling `_checkNoInterpolation` in `Parser.parseTemplateBindings`, similar to what is done for regular bindings, but that might have unforeseen consequences on existing code so let's get this change in.

**Pull request closed without merging**
