### PR TITLE
chore(benchpress): add ff extension test to ci

### PR DESCRIPTION
**Pull request by hankduan**

### CODE REVIEW

**Comment by tbosch** [comment]
Please remove custom selenium url
Please use a local url (e.g. `index.html` form `hello_world` example) instead of an external site.

**Comment by hankduan** [comment]
hold off on this for a bit. Still trying to figure out why it's failing on CI (and not on my local machine)

**Comment by hankduan** [comment]
dependent on: https://github.com/angular/angular/pull/2295

**Comment by hankduan** [comment]
Should be good to go now.

**Pull request closed without merging**
