### PR TITLE
Cherry pick aio fixes

### PR DESCRIPTION
**Pull request by kormide**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Broken after merge of aio bazel migration.

## What is the new behavior?

Cherry-pick all the fixes from main.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by josephperrott — DISMISSED** [review]
LGTM


Could you `reword` the commit messages to not include the pr numbers from the other pr merges that were cherry picked.

**Comment by kormide** [comment]
Reworded the commits.

**Comment by kormide** [comment]
Fixed.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by josephperrott** [comment]
This PR was merged into the repository by commit cfd8702747d46f95c1eb924dae97cbdd8eed7743.

**Pull request closed without merging**
