### PR TITLE
docs: do not add auto-code-links to observables example

### LINKED ISSUE #34793: More hyperlinks in code comments
# 📚 Docs or angular.io bug report

### Description

On this page
https://angular.io/guide/observables
the following code comment contains the whole bunch of hyperrefs (create, a, sequence)
// Create a new Observable that will deliver the above sequence

### What's the affected URL?**
https://angular.io/guide/observables

## 🔥 Exception or Error
<pre><code>

</code></pre>

### PR DESCRIPTION
**Pull request by petebacondarwin**
Fixes #34793

See https://pr34797-e671b3b.ngbuilds.io/guide/observables

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
lgtm, but shouldn't this be the default for all examples?

my guess is that most examples will contain bogus links because the auto-linking is primarily meant to work for API docs. no?

**Comment by IgorMinar** [comment]
merge-assistance: global approval

**Comment by petebacondarwin** [comment]
@IgorMinar - there may well be a number of false-positives, but they are not that noticeable (and so do not negatively impact on the docs) since you only realise the link is there if you hover over it. This is evidenced by how few issues we receive like this one.

I think that there is enough value in generally having code linked to API docs, that it is worth having a few false positives.

One mitigation could be to create a stop-list of terms that should not be linked.

**Comment by gkalpak** [comment]
The stop list might be worth for things that are likely to generate false positives. E.g. things such as `a`, `group`, `sequence`.

**Pull request closed without merging**
