### PR TITLE
docs: fix typo in getting started guide

### PR DESCRIPTION
**Pull request by bargemb**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [x] Other... Please describe:

## What is the current behavior?
A sentence in the getting started guide is incorrect.

Issue Number: 33181

## What is the new behavior?
Fixed the sentence in the getting started guide

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
N/A

### CODE REVIEW

**Review by santoshyadavdev — CHANGES_REQUESTED** [review]
change commit messge to docs: Getting started guide fix in output section.

**Comment by bargemb** [comment]
Is it fine if I amend the commit message and force commit ?

This will delete my earlier commit and adds new.

**Comment by santoshyadav198613** [comment]
> Is it fine if I amend the commit message and force commit ?
> 
> This will delete my earlier commit and adds new.

Yes this is what we generally do.

**Comment by bargemb** [comment]
> change commit messge to docs: Getting started guide fix in output section.

Done!

**Review by santoshyadavdev — APPROVED** [review]
LGTM

**Review by kapunahelewong — CHANGES_REQUESTED** [review]
Thanks for this, @bargemb! Could you amend your commit message so that it is as follows?

> docs: fix typo in getting started guide
>
> Fixes #33181 

That should automatically close the issue when this PR is merged and also puts the emphasis on the action you're taking in the PR. And you can continue to force push. When we merge PRs, just having one commit is ideal. Will you tag me when you're ready? Thanks!

EDIT - fix my typo 😄

**Comment by bargemb** [comment]
@kapunahelewong Done!

**Review by kapunahelewong — APPROVED** [review]
Perfect! Thank you, @bargemb!

Caretaker, this is a docs only change. Please ping me if you need me to help with this. Thank you!

**Pull request closed without merging**
