### PR TITLE
fix(common): cleanup location change listeners when the root view is removed

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
- [x] Bugfix

## What is the current behavior?
Issue Number: #31546

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by arturovt** [comment]
This is a copy of this PR (https://github.com/angular/angular/pull/39570) since I accidentally deleted the fork.

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api, size-tracking

**Comment by petebacondarwin** [comment]
Someone just merged a change to the size tracking golden files. Can you rebase again please @arturovt ?

**Comment by arturovt** [comment]
> Someone just merged a change to the size tracking golden files. Can you rebase again please @arturovt ?

Sure.

**Review by atscott — APPROVED** [review]
reviewed-for: size-tracking
reviewed-for: public-api

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
caretaker note: This patch cl/357791794 needs to needs to be patched to the sync CL.

**Review by jessicajaniuk — APPROVED** [review]

**Comment by atscott** [comment]
[global presubmit (with patch)](https://test.corp.google.com/ui#id=OCL:357793561:BASE:359270564:1614186182491:8be14f57)

**Comment by atscott** [comment]
[another global presubmit](https://test.corp.google.com/ui#id=OCL:357793561:BASE:360170553:1614635338461:227489ed). All green but waiting on 3 CLS ([360194213](https://critique-ng.corp.google.com/cl/360194213), [360194075](https://critique-ng.corp.google.com/cl/360194075), [360194845](https://critique-ng.corp.google.com/cl/360194845)) before this can merge.

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: fw-testing

**Review by kyliau — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by atscott** [comment]
caretaker note: I've already submitted the necessary CLs in g3 to account for this change, but I'm still tacking on the "risky" label in case there are new changes between then and when this is merged & synced.

**Pull request closed without merging**
