### PR TITLE
fix(forms): improve error message for invalid value accessors

### PR DESCRIPTION
**Pull request by dirkluijk**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

When you forget to provide a NG_VALUE_ACCESSOR with `multi: true`, you get an fuzzy error message.

## What is the new behavior?

A clear error message is thrown: `Value accessor should be provided as an array`

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

This is my first Angular PR. Do we need docs/tests for such small enhancements?

### CODE REVIEW

**Comment by Toxicable** [comment]
You'll need some tests for this.

**Comment by dirkluijk** [comment]
@Toxicable No problem. Tests added.

**Review by kara — APPROVED** [review]
LGTM. Thanks for improving error messages!

**Comment by kara** [comment]
[presubmit](http://test/OCL:191528725:BASE:191528730:1522803647788:ccb177b)

**Pull request closed without merging**
