### PR TITLE
docs: change typo Stacblitz into Stackblitz

### PR DESCRIPTION
**Pull request by nobobo1234**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
There is a typo on the Tour of Heroes app page in the docs, namely Stacblitz instead of Stackblitz

Issue Number: N/A

## What is the new behavior?
I changed it into Stackblitz, the actual name of the service

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by nobobo1234** [comment]
@googlebot I signed it!

**Review by aikithoughts — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by nobobo1234** [comment]
@aikidave Is there a way to undo a commit message because the `ci/circleci: lint` still fails because my first commit message was less than 100 characters.

**Comment by petebacondarwin** [comment]
There are a few approaches:

```
git commit --amend
```

This should open up a text editor for you to change the commit message.

Or

```
git reset HEAD^
```

This should move the current branch back to the previous commit but leave the changes in the working directory, so you can create a new commit with a longer message.

In any case, once you have updated (or replaced) the commit you then push it back to Github via:

```
git push --force-with-lease
```

**Review by aikithoughts — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by nobobo1234** [comment]
I honestly don't know what I did wrong :confused:, sorry for the pending reviews...

**Comment by AndrewKushnir** [comment]
Hi @nobobo1234, it looks like you also updated the `goldens/size-tracking/integration-payloads.json` file (which triggered additional reviewers to be added). I believe this additional change is not needed as the value is the same in the master branch. Could you please rebase this PR on top of the master branch? Thank you.

**Comment by aikidave** [comment]
I wonder if the rebase didn't go as planned? Let me know if you need some help? @kapunahelewong is great at figuring these things out. :)

**Comment by nobobo1234** [comment]
I have dropped the ci commit from the list in the interactive rebase but it seems like it didn't remove the extra reviewers :thinking:

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Thanks for rebasing this PR @nobobo1234. I've updated the list of reviewers and dropped the ones that were added as a result of the `goldens/size-tracking/integration-payloads.json` file modification.

**Pull request closed without merging**
