### PR TITLE
refactor(forms): update minlength/maxlength to inherit abstractValidator

### LINKED ISSUE #42267: Regression introduced by new min max validators
# Bug Report

### Affected Package

@angular/forms 12+

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11

### Description
@angular/forms 12 introduced min and max validators based on the min and max attributes presence in #39063.

Before that, the browser would react to min/max attributes by doing validation and also by preventing to introduce invalid value. Both of those **native features are now impossible to leverage**.

Also, before that, it was possible to deactivate the browser native features with a null value, such as `[min]="null"` or `[min]="undefined"`. This is now impossible to do in strict mode compilation, because the new directive only accept `string | number` and would **result in a compilation error**. Possible temporary workaround for that is to use `$any` casting similar to `[min]="configuration.min ?? $any(undefined)"`

image

### Suggested fixes

I would suggest that both directives create, and maintain, the equivalent attribute on the HTMLInputElement, so that browsers are able to react accordingly and adapt their UX.

And I would suggest to loosen the input type like so:

```diff
- @Input() min!: string|number;
+ @Input() min: string|number|null|undefined;
```

If those suggestions sound mergeable I could create PRs for it.

## Minimal Reproduction

- https://stackblitz.com/edit/min-max-regression-angular-11
- https://stackblitz.com/edit/min-max-regression-angular-12, same as above, but with strict mode disabled, and Angular 12

## Exception or Error

```
Type 'number | null' is not assignable to type 'string | number'.
```

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: yarn 1.22.5
OS: linux x64

Angular: 12.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.0.1
ng-packagr                      12.0.0
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

### PR DESCRIPTION
**Pull request by iRealNirmal**
Modified minlength and maxlength validator to inherit abstractValidator

For every validator type different PR will be raised as discussed in #42378.

Closes #42267

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
validators are not uniform 

Issue Number: related to  #42378.

## What is the new behavior?
modified minlength and maxlength validator to use abstractValidator

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — COMMENTED** [review]
@iRealNirmal thanks for working on this! A couple comments:

- Could you please change the commit message to `refactor(forms): ...` - I think it'd better reflect the nature of this change
- It looks like there are few legit failures in tests
- I've also left a couple more comments related to code

Thank you.

**Review by AndrewKushnir — APPROVED** [review]
Thanks for this refactoring @iRealNirmal, the changes look good 👍 

I'd like to propose that we change the scope of the commit from `feat(forms)` -> `refactor(forms)`: that would better reflect the goal of this PR and we can merge this change into the next patch version.

I've also started tests in [Google's codebase](http://test/OCL:405505245:BASE:405505278:1635200885191:71e9dabb) (internal-only link) and will let you know once I get the results.

Thank you.

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Review by atscott — APPROVED** [review]
Reviewed-for: public-api

**Comment by iRealNirmal** [comment]
@AndrewKushnir @petebacondarwin when I was trying to raise PR against 12.2, I found that [https://github.com/angular/angular/pull/42978](https://github.com/angular/angular/pull/42978) is also missing, which is also needed, let me know if you want me to push both changes in one PR.

**Comment by AndrewKushnir** [comment]
@iRealNirmal thanks for checking. Since we are very close to v13, I think we can skip adding this (and #42978) refactoring into 12.2.x branch.

**Pull request closed without merging**
