### PR TITLE
feat(core/di): DI support custom error messages

### LINKED ISSUE #4008: DI should support custom error messages
I should be able to do the following:

```
var INCLUDE_MODULE_ERROR = "Did you include my module? See here...."
class MyDirective {
  constructor(@NoBindingErrorMessage(INCLUDE_MODULE_ERROR) s:MyDependency)
}
```

When DI cannot find MyDependency, it will throw a meaningful message, asking, for instance, to include some module.

I don't expect this to be used by app developers, but this can be very useful for libraries and frameworks.

cc @IgorMinar @mhevery

### PR DESCRIPTION
**Pull request by erictsangx**
Support @NoProviderErrorMessage('cannot find....')

Closes #4008 

```
@Injectable()
class Car {
  engine;
  constructor(@NoProviderErrorMessage('cannot find Engine') engine:Engine) {
    this.engine = engine;
  }
}

var injector = Injector.resolveAndCreate([Car]);
expect(()=>int.get(Car).engine).toThrowError('cannot find Engine');
```

PS: default error message is still using ``No provider for ${first}!${constructResolvingPath(keys)}``

### CODE REVIEW

**Comment by PascalPrecht** [comment]
LGTM except that most of the changes are done to double vs single quotes in the tests. Could we pull those apart?

**Comment by erictsangx** [comment]
removed the changes of single/double qoutes

**Comment by mhevery** [comment]
@tbosch what do you think about this PR? I am not convinced that there is a use case for this? Should we close?

**Comment by tbosch** [comment]
Also, this will not work in codegen'ed DI. Sorry, closing for now.

**Pull request closed without merging**
