### PR TITLE
fix(core): align TestBed interfaces and implementation

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This PR contains 3 commits with the TestBed implementation cleanup.

The change affected the public API surface, but in practice those types were already exposed via [the TestBedStatic interface](https://angular.io/api/core/testing/TestBedStatic), so those APIs were already public.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:458108166:BASE:458108185:1656552242826:3ccd7d08) (this change will also require a TGP).

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
LGTM

reviewed-for: fw-core, fw-testing, circular-dependencies, public-api

**Comment by AndrewKushnir** [comment]
[Presubmit #2](http://test/OCL:458337806:BASE:458337835:1656631598053:3d6fd23a).

**Comment by AndrewKushnir** [comment]
[Global Presubmit](https://test.corp.google.com/OCL:458395431:BASE:458395665:1656657753422:4a963808).

**Comment by AndrewKushnir** [comment]
[Global Presubmit #2](https://test.corp.google.com/OCL:459652945:BASE:459653007:1657246120585:5b0a1780).

**Comment by AndrewKushnir** [comment]
[Global Presubmit #3](https://test.corp.google.com/OCL:459652945:BASE:460085936:1657488768218:3004c775) (to make sure there are no new regressions).

**Review by alxhub — APPROVED** [review]
Reviewed-for: public-api

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 7e03fc90d61602d4383d68af66724827172b321e.

**Pull request closed without merging**
