### PR TITLE
[WIP] feat(router): introduce a service for document head management

### LINKED ISSUE #13361: Proposal: Service for document head management (with support for title, meta, link, style etc) on all route changes
**I'm submitting a ...**  (check one with "x")
```
- [ ] bug report => search github for a similar issue or PR before submitting
- [x] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Expected behavior**

Proposed syntax:
```
const routes: Routes = [
  {
    path: 'home',
    component: HomeComponent,
    data: {
      head: {
        title: 'Home page',
        description: 'Description of the home page',
        meta: [
               {'name': 'description', 'content': 'My application'},
               {'property': 'og:type', 'content': 'article'}
        ]
      }
    }
  }
];
```
**What is the motivation / use case for changing the behavior?**

Make the document head management more declarative and simple.

Related to https://github.com/angular/angular/issues/7630

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Closes https://github.com/angular/angular/issues/13361

Todo:
- [ ] Add docs
- [ ] Add tests
- [ ] Consider a better name

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@DzmitryShylovich AFAIK there is a plan to introduce such service for the server-side rendering purposes - @vikerman might know more. In any case I don't think it should be router specific.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource 
> I don't think it should be router specific.

the original idea was to simplify (make it more declarative) document head manipulation (title, meta tags) on every route change. I don't see how such service can be router independent.

**Comment by pkozlowski-opensource** [comment]
> I don't see how such service can be router independent.

We should first have a service that can actually do manipulation of head, title etc. Then router could build on it / use it.

**Comment by DzmitryShylovich** [comment]
We already have such services: Title and Meta.

**Comment by DzmitryShylovich** [comment]
Actually this pr already conintains the impl. I just need to add tests and docs

**Pull request closed without merging**
