### PR TITLE
docs: corrected gramatical mistake in ssr.md

### PR DESCRIPTION
**Pull request by Tweniee**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

gramatical mistake in ssr.md(doc) file
changes in `adev/ and aio/` directories

Issue Number: #52777 

## What is the new behavior?
Added the appropriate missing words in the doc and its gramatical correct

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]
LGTM, thanks

**Comment by alan-agius4** [comment]
@Tweniee, can you please update the commit message to `docs: corrected gramatical mistake in ssr.md`?

**Comment by Tweniee** [comment]
> @Tweniee, can you please update the commit message to `docs: corrected gramatical mistake in ssr.md`?

sure its done

**Comment by JeanMeche** [comment]
You only edited the PR title, not the commit message.

**Comment by Tweniee** [comment]
My Mistake, @JeanMeche
Hope this looks good now ?

**Review by twerske — APPROVED** [review]

**Comment by twerske** [comment]
can you remove the Merge commit?

**Pull request closed without merging**
