### PR TITLE
fix(aio): polyfill for custom elements

### PR DESCRIPTION
**Pull request by lsfgrd**
The intention of this commit is to fix the Safari/Chrome issue on iOS 9.3.5 by adding a polyfill for custom elements

This commit fixes issue #24392

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ X ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ X ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #24392

Trying to load Angular.io on an iDevice with iOS 9.3.5 results in a blank page. Console errors indicate custom-elements-related issues with **TypeError: Attempted to assign to readonly property**.

## What is the new behavior?

With the polyfill, he website now loads on Safari and Chrome on iDevices with iOS 9.3.5.

## Does this PR introduce a breaking change?
```
[ ] Yes
[ X ] No
```

## Other information
My newbie self doesn't know if this is the best way to import a polyfill. Please, enlighten me.

### CODE REVIEW

**Comment by robwormald** [comment]
AIO already includes the CE polyfill, so I don't think this PR is necessary?

**Comment by gkalpak** [comment]
Yes, we are loading the polyfills [here][1].
I assume the browsers on iOS 9.3.5 have `window.customElements` (which leads in loading the `native-shim.js` polyfill), but they actually need the `custom-elements.min.js` polyfill. Maybe we need a better check than `!!window.customElements`.

@lsfgrd, can you find out exactly "readonly property" is trigerring the error. We could use that to feature detect proper support.

[1]: https://github.com/angular/angular/blob/0b4d85e9f19246af68a75140afc4db3d97f9ddfd/aio/src/index.html#L87-L107

**Comment by lsfgrd** [comment]
@gkalpak okay, I'm understanding it better now, sorry for the confusion. I have more info.

My Safari doesn't have **window.CustomElement**. I know that because I sent an alert in the if statement that loads CE Polyfill and it appeared in my browser. So, since it's in the condition, I guess it's something else.

Tried loading the CDN link in the **loadCustomElementsPolyfill** function: blank screen. **The script is loaded though.**

I really think it has to do with the order. [According to the polyfill repository](https://github.com/webcomponents/custom-elements), the script must come before any code that manipulates the DOM. The script tag that loads the CE polyfill writes the script src tag after it.

**Comment by IgorMinar** [comment]
I was able to reproduce this issue on ios9 via browserstack.

But rather than pulling in a polyfill from a CDN we should update aio to load the polyfill in the same way as `ng add @angular/elements` does via `script nomodule` and load the document-register-element polyfill.

The schematics for this are in https://github.com/angular/angular/blob/01ec5fd6b034ce105f90b7462e5358ba5492425d/packages/elements/schematics/ng-add/index.ts#L33-L66 but it might be easier to read what we do there if we just look at the diff after calling `ng add @angular/elements` on the project and cleaning that up.

**Comment by gkalpak** [comment]
@IgorMinar, that would mean that `nomodule` support implies `window.customElements` support. Is there evidence of that? 😈

**Comment by AndrewKushnir** [comment]
Closing this issue since it refers to ios9 (current version is ios14) and there were no recent reports related/similar to this issue. Please reopen if the problem still exists. Thank you.

**Pull request closed without merging**
