### PR TITLE
feat(router): add componentClasses input property for router outlet

### PR DESCRIPTION
**Pull request by KingMario**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

PS: docs have been added by ts comment

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

No component classes binding for router-outlet

Issue Number: #49483

## What is the new behavior?

component classes binding is added to router-outlet

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by KingMario** [comment]
Hi @AndrewKushnir.

I have problem in resolving the building and testing issues reported by ci. Perhaps it's the problem of my dev environment?

I tried to set --jobs=1 for bazel in the building script and it finally built.

But for the cli-hello-world-lazy:test, I just can't run test locally.

image

The error message for cli-hello-world-lazy:test local running is `BrowserslistError: [BABEL] /Users/cgeng/WebstormProjects/angular/integration/cli-hello-world-lazy/src/main.ts: Unknown version 109 of edge (While processing: "base$0$0")`. I searched stackoverflow, but one of the solution `npx browserslist --update-db` doesn't work for me.

I'd like to know if all the tooling and package/config settings are working properly. Should the dev environment meet any requirements to run building and testing?

Thanks.

**Comment by AndrewKushnir** [comment]
@KingMario the root cause is the payload size increase in one of the integration/test apps:
```
FAIL: Commit 0337e97f0fb98541b2019b2f0a141b28025d9911 uncompressed main exceeded expected size by 500 bytes or >1% (expected: 232018, actual: 232545).
```
Just find the `232018` value and replace with the `232545` one for now, this should make the CI "green".

Thank you.

**Comment by KingMario** [comment]
@AndrewKushnir Thanks for the hint. The PR is ready for review now.

**Comment by KingMario** [comment]
@atscott Thanks for your time and your explanation.

I should have considered the size cost before I started to write the feature. I'm guessing, though, that perhaps most of the addition is documentation comments.

After your review, I updated the code by accepting only an array of strings, so it doesn't increase much size like it did before.

I hope it'll get enough upvotes and be part of the framework. If not, I think I can make another directive and publish it to npm for others who really need it.

Thanks again.

**Comment by KingMario** [comment]
PS: in main branch, I built cli-hello-world-lazy locally, and the size for main is already 232600, 500 bytes larger than in the payload json file.

**Pull request closed without merging**
