### PR TITLE
build(docs-infra): remove unnecessary zipper.json file

### PR DESCRIPTION
**Pull request by petebacondarwin**
The `zipper.json` file is only needed if the example does not
have a `stackblitz.json` file, which this (i18n) example does.

Moreover, it appears that having both can cause the generated
zip file to be corrupted and not unzippable.

Fixes #37849

### CODE REVIEW

**Review by gkalpak — CHANGES_REQUESTED** [review]
We can still have both `stackblitz.json` and `zipper.json` if we want to include different files in each. I am not sure whether that is the case here.

I understand little of the i18n example, but I noticed the following (which I am not sure whether intentional):

- [doc-files/][1] are included in both the StackBlitz and the zip. Is that intentional? Are these files useful to the user?
- [src/locale/][2] is not included in neither the StackBlitz nor the zip. Is that intentional?

[1]: https://github.com/angular/angular/tree/79850983e6fcedb82377f2784e6d59c62727b71e/aio/content/examples/i18n/doc-files
[2]: https://github.com/angular/angular/tree/79850983e6fcedb82377f2784e6d59c62727b71e/aio/content/examples/i18n/src/locale

**Comment by petebacondarwin** [comment]
> We can still have both stackblitz.json and zipper.json if we want to include different files in each. I am not sure whether that is the case here.

I am not sure that this is correct. From my reading of https://github.com/angular/angular/blob/1c385a1c2200ffc90b2848b6a07c19c0293cae82/aio/tools/example-zipper/exampleZipper.js#L24 having both files will result in the zipper attempting to produce two zip files, right?

**Comment by petebacondarwin** [comment]
I agree that the StackBlitz and zip file should have not include docs-files and include locale files. So we should probably add these lines to the `stackblitz.json`. 

```
    "!doc-files/**/*",	
    "**/*.xlf"
```

**Comment by petebacondarwin** [comment]
Updated the stackblitz.json...

**Review by gkalpak — APPROVED** [review]
:100:

**Comment by petebacondarwin** [comment]
Merge-assistance: Github seems to think there are two outstanding code-reviews, but this is not correct. The PR has been reviewed and approved as required.

**Review by Splaktar — APPROVED** [review]
LGTM

**Pull request closed without merging**
