### PR TITLE
docs: delete duplicated word

### PR DESCRIPTION
**Pull request by lharries**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Duplicate word in aio/content/tutorial/toh-pt4.md

Issue Number: #21063

## What is the new behavior?

Deleted duplicate word

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by lharries** [comment]
completed cla

**Comment by IgorMinar** [comment]
can you please remove the unrelated changelog changes and squash the commits in the PR? thanks!

**Comment by lharries** [comment]
Done @IgorMinar!

**Review by IgorMinar — APPROVED** [review]
in the future use just `docs:` instead of `docs(aio)`. thanks!

**Comment by lharries** [comment]
@IgorMinar will do, thanks Igor!

**Pull request closed without merging**
