### PR TITLE
fix(common): embed `tslib`in `http` UMD bundle

### PR DESCRIPTION
**Pull request by alan-agius4**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
At the moment `tslib` is not embedded inside the UMD bundle https://github.com/angular/common-builds/blob/master/bundles/common-http.umd.js#L6

Issue Number: #23041

## What is the new behavior?
Embed tslib in UMD bundle

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by alan-agius4** [comment]
//cc: @mgechev

**Comment by gkalpak** [comment]
Is supposed to fix #22949.

**Comment by alan-agius4** [comment]
Maybe someone can help reviewing this small fix? @kara

**Comment by alan-agius4** [comment]
@alexeagle this is a small fix for another tslib issue.

**Review by alexeagle — COMMENTED** [review]
You caught us just during a transition - as of Friday we no longer use this file in the build. It will be deleted this week. Instead we publish the result of `bazel build //packages/common:npm_package`

**Comment by alan-agius4** [comment]
Thanks for the update Alex. i’ll close the PR in that case.

**Comment by alexeagle** [comment]
Do we need to make a fix in the bazel rules? Is the original issue still
evident in angular 6.0.0-rc.1 ?

**Comment by alan-agius4** [comment]
Yeah the issue is still present.

tslib is still being required.

See here:
https://github.com/angular/common-builds/blob/master/bundles/common-http.umd.js

**Comment by alexeagle** [comment]
Sorry, the snapshot builds currently don't represent what we are
publishing.
https://unpkg.com/@angular/common@6.0.0-rc.1/bundles/common.umd.js is the
source of truth.

Igor says this is intentional - we don't want to embed tslib because you
can end up with multiple copies in an application.

Is there an issue describing what the problem is?

**Comment by alan-agius4** [comment]
Oh good to know that, so I update ng-packagr as I am migrate it to APF v6.

In theory I dont have a problem though someone tagged an issue with my PR
but I am sure if it is directly related cause I didn’t look at the issue
myself:
https://github.com/angular/angular/issues/22949

**Comment by alan-agius4** [comment]
Makes total sense that is not embedded. I totally in favor of that. Since if you use UMDs, you would mpst likely end up with loads of duplicates methods. Since its embeded in all umd bundles.

**Pull request closed without merging**
