### PR TITLE
docs: fix typo in ng-content.md

### PR DESCRIPTION
**Pull request by Tariqu**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thanks for this !

**Comment by JeanMeche** [comment]
Could you please [sign the CLA](https://github.com/angular/angular/pull/57836/checks?check_run_id=30217260340) and reword your commit to follow our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit), thank you.

**Comment by JeanMeche** [comment]
You edited the PR's title but not the commit message itself. Can you make sure to reword the commit message, thank you.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit f5349cbfa90119e2d7e3d8759a5391823145a648.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
