### PR TITLE
fix(docs-infra): don't call locationService.setSearch when clicking outside of the search box and searchResults are empty

### LINKED ISSUE #26544: docs: Fetching favicons on every click in Chrome
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I click anywhere on angular.io, the website always fetches all favicons (total of 19.3 KB).

## Expected behavior

The site gets them only once.

## Minimal reproduction of the problem with instructions

Go to https://angular.io, open the Network tab in the DevTools and click on the page. Only happens on Google Chrome.
## What is the motivation / use case for changing the behavior?

The website downloads way more content than it needs to.

## Environment

<pre><code>
Angular version: -

Browser:
- [x] Chrome (desktop) version 70.0.3538.67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by mahalde**
Partially fixes #26544 by not calling locationService.setSearch on every click outside of the search box.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

On every click on the `aio-shell` `locationService.setSearch` gets called, which fetches all favicons because of [this Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=895175).

Issue Number: #26544 

## What is the new behavior?
`locationService.setSearch` is not getting called when the search is empty.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Favicons still get fetched on a click on an \<a\>-tag, which is a [known Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=895175), because Chromium doesn't support the `size` attribute on \<link\>-tags.

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Can you, please, add `Fixes #26544` in the commit message?

**Comment by gkalpak** [comment]
Hm...the tests are failing, though 😕

**Comment by onlyflix** [comment]
@gkalpak Finally had the time to do it correctly. 😄 
I suppose it's ready to be merged.

**Review by gkalpak — APPROVED** [review]

**Comment by onlyflix** [comment]
@gkalpak Changed the commit message 😄 Hope that it is according to the guidelines!

**Comment by gkalpak** [comment]
👌

**Pull request closed without merging**
