### PR TITLE
test: protractor test for closure bundle

### PR DESCRIPTION
**Pull request by alexeagle**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by alexeagle** [comment]
Totally lifted from @filipesilva 's work

**Comment by alexeagle** [comment]
Hmm, sadness, with latest protractor as well as 4.0, Angular is not found on the page. Probably because closure has renamed something it looks for. @sjelin do you remember how we fixed this for google3?

**Comment by filipesilva** [comment]
@alexeagle the error I see on CI is the same as on my PR:

```
[1] [05:04:49] I/direct - Using ChromeDriver directly...
[1] [05:04:49] I/launcher - Running 1 instances of WebDriver
[1] [05:05:50] E/launcher - unknown error: Chrome failed to start: crashed
[1]   (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.8.12-040812-generic x86_64)
[1] [05:05:50] E/launcher - WebDriverError: unknown error: Chrome failed to start: crashed
```

I'll try to fix it there.

**Comment by gkalpak** [comment]
@alexeagle, @filipesilva: I think the failure maybe be due to [running the tests][1] before [starting Xvfb][2].

[1]: https://github.com/alexeagle/angular/blob/3f538259f3f5ee2b7341c8d36f494f5055f2f014/scripts/ci-lite/test_e2e.sh#L25
[2]: https://github.com/alexeagle/angular/commit/4d5a4d89cd518b934aeada42098dda6f1de30899#diff-468ef16928053a6ff945e06346d41b46R40

**Comment by filipesilva** [comment]
@gkalpak good catch. I'll try that as well.

I think it also has to do with the version of chromium in the used Travis instanced (Ubuntu 12.04). On other repos I could only get it to work with Ubuntu 14.04 due to it's updated chromium.

**Comment by filipesilva** [comment]
@alexeagle I modified https://github.com/angular/angular/pull/14196 (with a lot of help from @gkalpak !) and now it passes Protractor tests. 

You'll want to have a look at the changes there. The main problem in this PR is what @gkalpak highlighted in https://github.com/angular/angular/pull/14240#issuecomment-276923881.

**Comment by alexeagle** [comment]
Almost working, just need to resolve the issue with waitForAngular

**Comment by alexeagle** [comment]
Requires @IgorMinar or @mhevery for pullapprove

**Review by mhevery — APPROVED** [review]

**Review by vikerman — APPROVED** [review]

**Comment by alexeagle** [comment]
@sjelin this integration test installs its own protractor dependency, which means it has to run `webdriver-manager update`. That's slow and downloads and installs more stuff. When we have 10 integration tests like this, it will be too slow. What do you think we could do to avoid that?

**Comment by filipesilva** [comment]
@alexeagle we can use a protractor one level up, or even the root one. We do something similar in docs.

**Comment by alexeagle** [comment]
I tried installing the protractor from the root node_modules but running
into typings issues - I'll let this one merge and keep working on it in the
background.

**Comment by alexeagle** [comment]
@filipesilva I resolved it and removed the `webdriver-manager update` (needed `--skipLibCheck` due to older Protractor in shrinkwrap not type-checking).
You could do this in your PR too, we don't want anyone copy-pasting the slow way.

**Comment by filipesilva** [comment]
@alexeagle done, #14196 is updated with those protractor changes.

**Pull request closed without merging**
