### PR TITLE
feat(license) include license files in dev and dev.sfx bundles

### PR DESCRIPTION
**Pull request by zzo**
@rado @alexeagle what do you guys think about something like this.  too cheesy? :)

### CODE REVIEW

**Comment by zzo** [comment]
cannot make sense of the one travis failure - is there a way to kick off just the failing build again?  I can update the PR and that will build them all again I suppose.

**Comment by alexeagle** [comment]
There is also a somewhat hard-to-spot refresh button on the far right of
the header for each run, that kicks it to run again. Sadly you lose any
access to the failing log.

**Comment by alexeagle** [comment]
looks like an elegant approach, and it produces a bundle which looks the same as the current one, right?

**Comment by zzo** [comment]
Yes the bundles are exactly the same as the current ones except for the comment blocks with the licenses inserted (In theory at least unless travis did manage to find some hard to spot bug!). 
I'll factor out the common code in the gulpfile which will trigger a travis rebuild I think. Not that the original travis error message was all that useful.

**Comment by zzo** [comment]
crap the previously failed build now errored out updating chromedriver - have one more mini fix to give it another shot.

**Comment by zzo** [comment]
3rd time's a charm woo!

**Comment by alexeagle** [comment]
Cool, I'll merge. Did you try building and executing the bundle? @rkirov points out that there are no tests for the bundle so theoretically we could break it un-knowingly, but my understanding is your code can only insert comments so unless a license file contains `*/` it should be good.

**Comment by zzo** [comment]
Thanks I have built the bundles but have not tested with them so you are right if a license file contains a '*/' it will break stuff.  Currently no license file contains those characters let's hope that continues

**Comment by alexeagle** [comment]
merged as 1eab4f5

**Pull request closed without merging**
