### PR TITLE
refactor: remove requestAnimationFrame from polyfills and platforms

### PR DESCRIPTION
**Pull request by marclaval**
rAF isn't used anymore, that's one less polyfill needed for the browsers which don't support rAF (IE9, Android 4.1, 4.2, 4.3)

### CODE REVIEW

**Comment by vicb** [comment]
LGTM.

Just curious: do you think there is a chance @matsko will need it in the future ?

**Comment by alxhub** [comment]
@matsko has asked that we hold this until he's back on Monday and can evaluate it, so I've assigned it to him and removed the merge label.

**Comment by naomiblack** [comment]
Team decided to remove this now. We can add it back easily in future if it is needed. @vicb

**Comment by mlaval** [comment]
Rebased, all green

**Comment by naomiblack** [comment]
Matias confirms this is ok to remove.

**Pull request merged**
