### PR TITLE
build(packaging): upgrade yargs package to 13.1.0

### PR DESCRIPTION
**Pull request by MaksPob**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
There is a vulnerability in yargs package, because its version is old.  
https://app.snyk.io/vuln/npm:mem:20180117  

## What is the new behavior?
I updated the version of the yargs package. Vulnerability should not be.  

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

I'm not sure.  

## Other information
You are using the old version of the yargs package, which at that time used the old version of the os-local package, which used the vulnerable version of the package mem.  
https://app.snyk.io/vuln/npm:mem:20180117

### CODE REVIEW

**Review by filipesilva — CHANGES_REQUESTED** [review]
Hi there, thanks for updating this dependency!

Can make it a single commit named `build: upgrade yargs package to 13.1.0` please? The commit name and count is important for us because we generate changelogs from the commits.

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx!

That dependency is only used for local development, so it is less of an issue. However, [compiler-cli][1] also has it as a dependency, so I think it makes sense to update it there.

(BTW, `yargs` is also used as a devDependency in other places throughout the codebase. Feel free to update it everywhere if you feel like it :grin:)

[1]: https://github.com/angular/angular/blob/699ecac2c28006df807e240e226e7dbaf9012d3d/packages/compiler-cli/package.json#L23

**Comment by MaksPob** [comment]
> Hi there, thanks for updating this dependency!
> 
> Can make it a single commit named `build: upgrade yargs package to 13.1.0` please? The commit name and count is important for us because we generate changelogs from the commits.

Ok, I did as you wrote:)

**Comment by MaksPob** [comment]
> Thx!
> 
> That dependency is only used for local development, so it is less of an issue. However, [compiler-cli](https://github.com/angular/angular/blob/699ecac2c28006df807e240e226e7dbaf9012d3d/packages/compiler-cli/package.json#L23) also has it as a dependency, so I think it makes sense to update it there.
> 
> (BTW, `yargs` is also used as a devDependency in other places throughout the codebase. Feel free to update it everywhere if you feel like it 😁)

OK, I updated yargs package in compiler-cli:))

**Comment by MaksPob** [comment]
> Thx!
> 
> That dependency is only used for local development, so it is less of an issue. However, [compiler-cli](https://github.com/angular/angular/blob/699ecac2c28006df807e240e226e7dbaf9012d3d/packages/compiler-cli/package.json#L23) also has it as a dependency, so I think it makes sense to update it there.
> 
> (BTW, `yargs` is also used as a devDependency in other places throughout the codebase. Feel free to update it everywhere if you feel like it 😁)

Im reopen new PR)

**Comment by MaksPob** [comment]
> Hi there, thanks for updating this dependency!
> 
> Can make it a single commit named `build: upgrade yargs package to 13.1.0` please? The commit name and count is important for us because we generate changelogs from the commits.

Im reopen new PR)

**Pull request closed without merging**
