### PR TITLE
Diagnostic to flag cases where control flow can break content projection

### PR DESCRIPTION
**Pull request by crisbeto**
**Note:** this is a resubmit of #52726.

These changes are a follow-up to the fix from #52414. They add a new diagnostic to the compiler that will flag cases where an element would've been projected into a specific slot of a component, but it isn't because it exists inside of a control flow node that has multiple root nodes. Aside from the diagnostic, I have to move some code around so it can be reused. Includes the following commits:

### refactor(compiler): expose utility for creating CSS selectors from AST nodes
When doing directive matching in the compiler, we need to be able to create a selector from an AST node. We already have the utility, but these changes simplify the public API and expose it so it can be used in `compiler-cli`.

### refactor(compiler-cli): expose ng-content selectors and preserveWhitespaces during template type checking
These changes expose the `ngContentSelectors` and `preserveWhitespaces` metadata to the TCB so they can be used in the next commit to implement a new diagnostic.

### test(core): add tests for control flow content projection with ng-container
The control flow projection diagnostic will mention `ng-container` as a workaround for projection multiple nodes. These changes add a couple of tests to ensure that the approach works.

### fix(compiler-cli): add diagnostic for control flow that prevents content projection
This is a follow-up to the fix from https://github.com/angular/angular/pull/52414. It adds a diagnostic that will tell users when a control flow is preventing its direct descendants from being projected into a specific component slot.

### CODE REVIEW

**Comment by crisbeto** [comment]
[Passing TGP](http://test/OCL:585567264:BASE:585598927:1701084858577:1e18b2c0)

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 4c1d69e2880f22745c820eee630d10071e4fa86b.

**Pull request closed without merging**
