### PR TITLE
refactor(ivy): back to frog eyes `ɵɵ`

### PR DESCRIPTION
**Pull request by benlesh**
Patch version of #30546

### CODE REVIEW

**Review by kara — APPROVED** [review]
LGTM

**Comment by benlesh** [comment]
This is blocked on https://github.com/angular/angular/pull/30593

Which is required to get the examples tests passing CI.

**Comment by kara** [comment]
@benlesh I think that PR fixes a different CI issue

**Comment by benlesh** [comment]
@kara Sorry, I should have added more context. I was working with @brandonroberts to figure out why I was having CI failures in aio examples on this PR, and he uncovered that it was linked to the other PR.

**Comment by jasonaden** [comment]
[Presubmit](http://test/OCL:249353381:BASE:249353425:1558482903990:5f933be3)

**Comment by jasonaden** [comment]
Merged

**Pull request closed without merging**
