### PR TITLE
test: updated the commonHttpTesting

### PR DESCRIPTION
**Pull request by alkavats1**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, 
you might want to change your commit message, this is not a doc update but a refactor on the integration tests.

**Comment by alkavats1** [comment]
> Hi, you might want to change your commit message, this is not a doc update but a refactor on the integration tests.

updated, thanks

**Review by AndrewKushnir — APPROVED** [review]
@alkavats1 thanks for the fix! 👍

**Comment by alkavats1** [comment]
> @alkavats1 thanks for the fix! +1

Thank u :), @AndrewKushnir can you merge this PR?

**Comment by AndrewKushnir** [comment]
> can you merge this PR?

@alkavats1 this PR is marked for merge and will be merged by the caretaker (likely within the next couple of days or so).

**Comment by alkavats1** [comment]
> > can you merge this PR?
> 
> @alkavats1 this PR is marked for merge and will be merged by the caretaker (likely within the next couple of days or so).

Ok thanks for your guidance @AndrewKushnir

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 178ece4dfb3d0f08b0da543479626e8eafaff7a3.

**Pull request closed without merging**
