### PR TITLE
Style(Compiler): improve code readability and make guidelines happy

### PR DESCRIPTION
**Pull request by alimd**
I'm just try to read and understand the codes
And while reading try to improve code readability and make guidelines happy
Could you please tel me: can i continue ?is it useful ?
And i have some suggestion for folders tree structure, where can we discussion about these stuff ?
Thank you in advance

### CODE REVIEW

**Comment by AliMD** [comment]
cla fixed

**Comment by ilijamilcinoski** [comment]
I have signed your contract 






Sent from Windows Mail





From: googlebot
Sent: ‎Friday‎, ‎February‎ ‎20‎, ‎2015 ‎12‎:‎52‎ ‎PM
To: angular/angular





Thanks for your pull request.

It looks like this may be your first contribution to a Google open source project, in which case you'll need to sign a Contributor License Agreement (CLA) at https://cla.developers.google.com/.

If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check the information on your CLA or see this help article on setting the email on your git commits.

Once you've done that, please reply here to let us know. If you signed the CLA as a corporation, please let us know the company's name.

**Comment by mhevery** [comment]
We are planning on having a bot do this work in bulk. See #714. As of right now, I think we value a good history over having consistent code, given that #714 will happen.

I like your enthusiasm. Could we direct it for something we need? Perhaps help us in writing the comments explaining how it works?

PS: I will close this PR per reasons above. Let me know if you feel strongly about it.

**Comment by AliMD** [comment]
@mhevery Nice idea :ok_hand: about the bot
Thank you

**Pull request closed without merging**
