### PR TITLE
fix(router): change 'ROUTES' InjectionToken type

### PR DESCRIPTION
**Pull request by yairtawil**
## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
```

## What is the current behavior?

Type for InjectionToken is not correct (`Route[][]`)

## What is the new behavior?
Type for InjectionToken is correct  (`Routes[]`)

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
No error is given for this bug as `useValue` is of type `any`.

### CODE REVIEW

**Comment by yairtawil** [comment]
I signed it!

**Comment by Toxicable** [comment]
Sorry but you might misunderstand how `multi` providers work, this is indeed the correct type

**Comment by yairtawil** [comment]
@Toxicable You're right!
To avoid confusion like I had, lets change it from `Route[][]` to `Routes[]`, making it easier to understand.

**Comment by trotyl** [comment]
Please run `gulp format` to fix the lint and merge all your commits into one.

<sub>Just for experience, do not try to change any space.</sub>

**Comment by wbhob** [comment]
@yairtawil what's the status of this PR? Looks like it hasn't been touched for a while.

**Comment by jasonaden** [comment]
Thanks for this PR. Interestingly, due to how the documentation is processed, it's better for us to inline the type as it was previously. This might be something we could look at some time in the future, but at this time with the current way we process documentation, we need to inline the type.

**Pull request closed without merging**
