### PR TITLE
docs: add rx-angular to resources.json

### PR DESCRIPTION
**Pull request by BioPhoton**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Add a resource to the Angular docs page

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

RxAngular is missing in the resources

Issue Number: N/A

## What is the new behavior?
RxAngular is included in the resources

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mgechev — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Hi, @BioPhoton! Thanks for this. Could you rebase? When it passes all the tests, we can mark it for merge.

**Comment by kapunahelewong** [comment]
Hi @BioPhoton! You're so close! You should be able to get it to pass by [squashing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) and [amending](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) your commit message to be:

```
docs: add rx-angular to resources.json
```

It looks like it's failing on the scope `(docs)` and I think it will fail on the second commit message as well, so squashing will clear that second issue up.

**Comment by petebacondarwin** [comment]
@BioPhoton - can you do the last squash and amend of the commit (and rebase on master for good measure)? Thanks.

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Pull request closed without merging**
