### PR TITLE
build: npm dependencies update + dedupe

### PR DESCRIPTION
**Pull request by IgorMinar**
**This PR absorbed #6067**

The goal of this PR is to update our dependencies and dedupe them to take advantage npm3's features and decrease the installation time.

Current state:

```
$ npm outdated

Package  Current   Wanted   Latest
```
- [x] `broccoli-funnel                0.2.3      git      git`
- [x] `angular                        1.4.7    1.4.8    1.4.8`
- [x] `angular-animate                1.4.7    1.4.8    1.4.8`
- [x] `angular-mocks                  1.4.7    1.4.8    1.4.8`
- [x] `bower                          1.6.5    1.7.2    1.7.2`
- [x] `broccoli                      0.15.4   0.15.4   0.16.9` - 
- [x] `broccoli-funnel                0.2.3      git      git`
- [x] `broccoli-slow-trees            1.1.0    1.1.0    2.0.0`
- [x] `broccoli-stew                  0.2.1    0.2.1    1.2.0`
- [ ] `browserify                    10.2.6   10.2.6   12.0.1`
- [x] `chokidar                       1.2.0    1.4.2    1.4.2`
- [ ] `clang-format                  1.0.32   1.0.33   1.0.33`
- [ ] `conventional-changelog         0.2.1    0.2.1    0.5.3`
- [x] `del                            1.2.1    1.2.1    2.2.0`
- [ ] `es6-shim                     0.33.10  0.33.13   0.34.0`
- [x] `fs-extra                      0.18.4   0.18.4   0.26.3`
- [ ] `glob                           4.5.3    4.5.3    6.0.3`
- [x] `googleapis                    1.0.23   1.0.23    2.1.7`
- [x] `gulp-connect                   1.1.1    1.1.1    2.3.1`
- [x] `gulp-load-plugins              1.0.0    1.1.0    1.1.0`
- [x] `gulp-sass                      2.1.0    2.1.1    2.1.1`
- [ ] `gulp-tslint                    3.5.0    3.6.0    4.2.2`
- [x] `gulp-uglify                    1.4.2    1.5.1    1.5.1`
- [x] `jasmine                        2.3.1    2.3.1    2.4.1`
- [ ] `jpm                            1.0.0    1.0.0    1.0.4`
- [x] `js-yaml                        3.4.3    3.4.6    3.4.6`
- [x] `karma                        0.13.15  0.13.16  0.13.16` - blocked on https://github.com/karma-runner/karma/issues/1768
- [x] `karma-browserstack-launcher    0.1.7    0.1.8    0.1.8`
- [x] `karma-chrome-launcher          0.2.1    0.2.2    0.2.2`
- [x] `karma-sauce-launcher          0.2.14   0.2.14    0.3.0`
- [x] `lodash                         2.4.2    2.4.2   3.10.1`
- [ ] `madge                          0.5.0    0.5.0    0.5.3` - blocked on #5022
- [x] `minimatch                     2.0.10   2.0.10    3.0.0`
- [x] `minimist                       1.1.3    1.1.3    1.2.0`
- [x] `mock-fs                        2.7.1    2.7.1    3.6.0`
- [x] `node-uuid                      1.4.3    1.4.7    1.4.7`
- [ ] `parse5                         1.3.2    1.3.2    2.0.2`
- [x] `protractor                     2.5.1    2.5.1    3.0.0`
- [x] `proxy-middleware              0.13.1   0.13.1   0.15.0`
- [x] `react                         0.14.2   0.14.5   0.14.5`
- [x] `rewire                         2.3.4    2.5.1    2.5.1`
- [x] `run-sequence                   1.1.4    1.1.5    1.1.5`
- [x] `semver                         4.3.6    4.3.6    5.1.0`
- [ ] `source-map                     0.3.0    0.3.0    0.5.3`
- [ ] `strip-ansi                     2.0.1    2.0.1    3.0.0`
- [ ] `systemjs                     0.18.10  0.18.10   0.19.9`
- [ ] `systemjs-builder              0.10.6   0.10.6  0.14.15`
- [ ] `through2                       0.6.5    0.6.5    2.0.0`
- [x] `ts2dart                       0.7.18   0.7.19   0.7.19`
- [x] `universal-analytics            0.3.9   0.3.10   0.3.10`
- [x] `webpack                       1.12.6   1.12.9   1.12.9`
- [x] `which                          1.2.0    1.2.1    1.2.1`
- [x] `yargs                          2.3.0    2.3.0   3.31.0`

```
```

### CODE REVIEW

**Comment by btford** [comment]
LGTM

**Comment by IgorMinar** [comment]
CI is flaking out, rerunning the job now. Circle CI failure is a flake as well. We should be ignored for now - I'll fix that in a separate PR.

**Comment by rkirov** [comment]
How about squashing it, before merging? This many commits (31) will dilute our history.

**Comment by IgorMinar** [comment]
Lots not squash in case we need to bisect an issue. I've done as much
testing as I could but there are quite a few changes here and squashing
them will make any follow up debugging hard.

**Pull request closed without merging**
