### PR TITLE
Doc language improvements

### PR DESCRIPTION
**Pull request by Michael-Ziluck**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Some of the language used in the NgModel documentation is unclear or worded awkward. There are also some minor grammatical errors.

## What is the new behavior?
All the docs in the file that I had the time to look at have been reworded or expanded.

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

## Other information
I tried to break it up into several commits so it'd be easy to revert any that are seen as unnecessary or incorrect. They are all accurate and significantly more clear to my knowledge and in my opinion.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
Thanks for improving Angular docs! The change looks good to me.

I'd propose to merge all commits into one and list all updates there, for example:

```
docs(forms): update `ngModel` documentation

This commit improves `ngModel` docs, specifically:
- fixes a number of typos
- rewords docs regarding NgModel directive's control property
- ...
```

Thank you.

**Comment by Michael-Ziluck** [comment]
@AndrewKushnir I can merge them together, sure thing. Quick question though, the CircleCI linter gets upset if the commit body is longer than 120 characters. Would it be fine if I went over that limit to include all the necessary details? If not I can just summarize it more broadly like you had in your example.

**Comment by AndrewKushnir** [comment]
@Michael-Ziluck there is a limit on the length of a single line in commit message body, but you can have multiple lines, so feel free to include all the necessary details. Thank you.

**Comment by Michael-Ziluck** [comment]
@AndrewKushnir Squashed and pushed. Thanks for getting back to me on that!

**Review by gkalpak — APPROVED** [review]
LGTM

Reviewed-for: dev-infra

**Comment by AndrewKushnir** [comment]
@Michael-Ziluck thanks for updating the PR. This PR is now approved, the CI is "green", so I'm adding it to the merge queue.

Thanks for improving Angular docs!

**Pull request closed without merging**
