### PR TITLE
docs: Fixes HttpClient.get() link from HttpGuide

### PR DESCRIPTION
**Pull request by karthick-manoharan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
All links for HttpClient.get() from HttpClient guide points to www.angular.io

Issue Number: #27820 

## What is the new behavior?
Now the links point to the correct one.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by IgorMinar — CHANGES_REQUESTED** [review]
@karthick-manoharan unfortunately your fix is not the right one. We need these links to be autoge erated because otherwise they will break once we archive the content on our archival subdomains. e.g. v7.angular.io

Let's wait for Pete to chime in to see if we can get this fixed in dgeni, unless you want to look into that.

**Comment by karthick-manoharan** [comment]
@IgorMinar @petebacondarwin I have spent some time trying to understand the how's of the dgeni and how it works for angular doc generation. Can you help me with some inputs?

**Comment by petebacondarwin** [comment]
@karthick-manoharan I can help you get up to speed with dgeni if you are interested. I'll send you an email...

**Comment by petebacondarwin** [comment]
The correct fix is here https://github.com/angular/angular/pull/27864

**Pull request closed without merging**
