### PR TITLE
fix(aio): make the search-pane larger (and improve the search-box)

### LINKED ISSUE #17094: Scroll results pane too short on mobile
the results view would be much more useful if we increased the width. Right now we are wasting the screen space with portion of the previously displayed document:

screenshot_20170530-023350

### PR DESCRIPTION
**Pull request by gkalpak**
Fixes #17094.

### CODE REVIEW

**Comment by Foxandxss** [comment]
I still get a weird behavior

I click it, it gets bigger. I click somewhere else and it gets super long and then goes back to normal.

**Comment by gkalpak** [comment]
This PR does not fix that issue. It just makes the search-pane (where the results are shown) larger and makes the search input field `type="search"`.

**Comment by Foxandxss** [comment]
Right right, my bad, I had that issue in mind only. My bad.

**Review by petebacondarwin — APPROVED** [review]
LGTM

**Comment by petebacondarwin** [comment]
Mergeable once the Travis flakes sort themselves out.

**Comment by gkalpak** [comment]
The e2e2 Travis failures are "inherited" from master. The rest is green (now).

**Pull request merged**
