### PR TITLE
docs: add explanation of cd command to integration/README

### PR DESCRIPTION
**Pull request by steviebeenz**
Add explanations for the CD batch command.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Hi @steviebeenz! Thank you for this. Could you amend your commit message to read:

docs: add explanation of cd command to integration/README

**Review by steviebeenz — COMMENTED** [review]
docs: add explanation of cd command to integration/README

—

**Comment by kapunahelewong** [comment]
Hey @steviebeenz! CircleCI is failing on the commit message. Make sure you do it with the same spaces etc. like this:

docs: add explanation of cd command to integration README

^^ That should pass. Also make sure you squash (`git rebase -i HEAD~2`).

**Comment by steviebeenz** [comment]
Hello, People. 

Please stop suggesting commit names longer than 50 characters.

Thanks

Steviebeenz

**Comment by brandonroberts** [comment]
@steviebeenz let's keep things on-topic here. Thanks for the PR

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Remove added spaces

**Comment by trotyl** [comment]
This doc is for Angular maintainers, not users, would explanation for what `cd` is really be necessary?

**Comment by brandonroberts** [comment]
Good point @trotyl.

**Pull request closed without merging**
