### PR TITLE
Make compilerHost.readResource injectable, so scss preprocess is possible via the API

### PR DESCRIPTION
**Pull request by alippai**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Feature
```

## What is the current behavior?
It's not possible to preprocess the loaded resources during compilation.

## What is the new behavior?
This PR adds an option to process scss files and inject the desired css (using the the API), so there is no need for extra watch step and temporary files.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Example usage:
```
main(['-p', './src/tsconfig.json'], undefined, path => {
  if (path.endsWith('.scss')) {
    const result = node_sass.renderSync({
      file: path,
      outputStyle: 'compressed',
      sourceMap: false,
    });
    return postcss([autoprefixer]).process(result.css.toString('utf8'), { from: undefined }).css;
  }
  return fs.readFileSync(path).toString('utf8');
});
```

### CODE REVIEW

**Comment by alippai** [comment]
Thanks @kara!

**Comment by alexeagle** [comment]
It's part of the old compiler, which we are rewriting for Ivy right now, so it's a hard time to accept changes here.
Can you explain what's your use case for writing a custom Angular compiler? We don't want to fragment the ecosystem by having some compiler with additional semantics that aren't in the `ngc` program

**Comment by alippai** [comment]
Maybe there is no need today. Back then it was really easy to call ngc watch + rollup watch from a single script, also made this 10 line patch to support scss. It was really fast, incremental "natively" (both ngc and rollup was nice, had only a few bugs). The build chain is custom anyways (web workers, custom loaders, multiple targets like ES5/6/8 in parallel)

**Comment by alippai** [comment]
Also the integrated ngc+scss compile ensured the only one watch is triggered. There was no timing weirdness which we had with separate scss watch + ngc watch.

**Review by cunla — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Closing this PR since it affects ViewEngine, which is now deprecated. Thank you.

**Pull request closed without merging**
