### PR TITLE
build: check for latest Chromium version

### LINKED ISSUE #22231: Restore `install-chromium.sh` version checking once `https://omahaproxy.appspot.com/all` is back
When travis runs this error pops up:

```
   creating: /home/travis/.chrome/chromium/chrome-linux/resources/inspector/security_test_runner/
  inflating: /home/travis/.chrome/chromium/chrome-linux/resources/inspector/security_test_runner/security_test_runner_module.js  
/home/travis/build/angular/angular/scripts/ci/install-chromium.sh: line 82: LATEST_CHROMIUM_VERSION: unbound variable
```

And it's due to [https://omahaproxy.appspot.com/all](https://omahaproxy.appspot.com/all) being unresponsive.

Once that page is working again. We can uncomment and close this issue.

### PR DESCRIPTION
**Pull request by gkalpak**
Now that https://omahaproxy.appspot.com/all is back up, we can restore the check for newer available version of Chromium.

Fixes #22231

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
lgtm if the CI is happy.

**Comment by gkalpak** [comment]
CI was green. I'll restart the `aio_e2e` jobs a few times to make sure they are not flakey and mark for merge.

(Background: The `aio_e2e` jobs were super flakey with some older Chromium/ChromeDriver versions and we had to pin them to even older versions. I want to make sure whatever was causing the flakes has been fixed in the latest versions.)

**Comment by gkalpak** [comment]
Note to caretaker: No g3 impact.

**Comment by matsko** [comment]
@gkalpak running g3 presubmit...

**Comment by matsko** [comment]
https://test/ui#id=OCL:209985435:BASE:209985520:1535054859216:d9c900d6

**Comment by matsko** [comment]
@gkalpak this doesn't patch cleanly into `6.x`. Please fix.

**Comment by gkalpak** [comment]
@matsko, let's merge this into master only. I will create a separate PR for patch.

**Comment by gkalpak** [comment]
See #25668.

**Comment by gkalpak** [comment]
See #25669.

**Pull request closed without merging**
