### PR TITLE
docs: remove AIO guides

### PR DESCRIPTION
**Pull request by JeanMeche**

### CODE REVIEW

**Comment by sonukapoor** [comment]
@JeanMeche Anything linking to these docs will be broken right? Is there any plan to link to the new content instead?

**Comment by JeanMeche** [comment]
AIO will not be updated anymore from the main branch. If changes should happens they will land in the `17.3.x` branch. 
Removing those files will have no effects.

**Comment by sonukapoor** [comment]
That makes sense. I am just worried about all of the links in the world pointing to aio.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by dylhunn** [comment]
Looks like this needs a rebase

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit f17134a7a44c00be2fdc4b9e18db6546afbdf6db.

**Pull request closed without merging**
