### PR TITLE
feat(angular_1_router): route to directives instead of controllers

### PR DESCRIPTION
**Pull request by btford**
Previously, route configuration took a controller constructor function as the value of
`component` in a route definition:

```
$route.config([
  { route: '/', component: MyController }
])
```

Based on the name of the controller, we used to use a componentMapper service to
determine what template to pair with each controller, how to bind the instance to
the $scope.

To make the 1.x router more semantically alligned with Angular 2, we now route to a directive.
Thus a route configuration takes a normalized directive name:

```
$route.config([
  { route: '/', component: 'myDirective' }
])
```

This is a pretty significant refactor, so I'd like to land it ASAP.

Also addresses #4184, #3993.

### CODE REVIEW

**Comment by IgorMinar** [comment]
I did a quick review. The biggest concern is https://github.com/angular/angular/pull/4266#commitcomment-13322062, otherwise the rest needs some cleanup but looks generally ok. Sorry, but I can't do an in-depth review now. It would be good for @matsko or @shahata to also take a look.

**Comment by btford** [comment]
Great. Thanks so much, @IgorMinar!

**Comment by shahata** [comment]
Also did a quick review and added some comments. Generally looks good, I really like the idea of ngRouteShim.

**Comment by shahata** [comment]
Comments are here: https://github.com/btford/angular/commit/011205e60b513bd29e1ad4408cf2c93c7d6ac5f2

**Comment by btford** [comment]
I've addressed comments and made a bunch of the suggested fixes.

I'm going to merge this now.

**Pull request closed without merging**
