### PR TITLE
feat(common): introduce ngForRange directive

### PR DESCRIPTION
**Pull request by DzmitryShylovich**

### CODE REVIEW

**Comment by otodockal** [comment]
- tests are missing
- I don't like this kind of effort of expanding common Angular directives. I'm not sure if Angular should even offer some common pipes. I think we didn't need this in AngularJS, do we really need it for Angular(maybe I'm wrong)?

Sorry for this, only my opinion. Maybe I'm missing something...

Besides that, thanks @DzmitryShylovich for your awesome work for Angular community!

**Comment by DzmitryShylovich** [comment]
> tests are missing

I don't want to waste my time until I get a confirmation that it will be merged this is why I didn't add any tests/docs.

> I don't like this kind of effort of expanding common Angular directives. I'm not sure if Angular should even offer some common pipes. I think we didn't need this in AngularJS, do we really need it for Angular(maybe I'm wrong)?

why not? it's a pretty common use case. All unused staff will be removed during treeshaking so I don't see a problem here.

**Comment by vicb** [comment]
@DzmitryShylovich we don't want to add this to common because we do not see a useful use case. And if we start we this one then users will want a 1-based index, a n-based index, steps, ...
IMO It should be provided as a 3rd party directive.

**Comment by otodockal** [comment]
@DzmitryShylovich only my reply...

People tend to complain about a lot of stuff to learn. I would rather have a smaller surface to prevent these kinds of discussions and let people create e.g. structural directives by themselves (I'm not talking about common *ngFor, *ngIf). Personally, I don't mind as well. It's something like marketing point of view rather than practical :). And I'm glad for your hard work!

**Pull request closed without merging**
