### PR TITLE
feat(core): Synchronize changes from internal JSAction codebase.

### PR DESCRIPTION
**Pull request by iteriani**
1: Remove USE_EVENT_PATH, which has no users.

2: Create a new `EventActionInfo` object to represent actions, update all `EventInfoWrapper` users.

3: Fix `stopPropagation` behavior in JSAction Dispatcher - it should only `stopPropagation` if an action is found, which is only known during normal dispatch rather than global.

4: Update the internal `EventInfo` representation of an `ActionInfo` to match the external representation in `EventInfoWrapper`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [X ] Tests for the changes have been added (for bug fixes / features)
- [X ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [X ] No

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]

**Review by crisbeto — APPROVED** [review]

**Review by tbondwilkinson — APPROVED** [review]

**Comment by alan-agius4** [comment]
//cc @rahatarmanahmed

**Review by tbondwilkinson — APPROVED** [review]

**Review by tbondwilkinson — APPROVED** [review]
How many licks does it take to get to the center of a tootsie pop.

#3

**Review by mturco — APPROVED** [review]

**Review by tbondwilkinson — APPROVED** [review]
reviewed-for: primitives-event-dispatch

**Review by mturco — APPROVED** [review]
reviewed-for: primitives-event-dispatch

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: primitives

**Comment by AndrewKushnir** [comment]
@mturco could you please leave a review with the "Reviewed-for: primitives-shared" comment? That should complete the set of required LGTMs for this PR.

**Review by mturco — APPROVED** [review]
Reviewed-for: primitives-shared

**Comment by thePunderWoman** [comment]
Caretaker note: This isn't in use yet in G3. So we can merge this without a TGP.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 1ee9f32621f6d72e8038a08f5ad4a0cfe8bd6a13.

**Pull request closed without merging**
