### PR TITLE
build(aio): do not fail on first `yarn setup`

### PR DESCRIPTION
**Pull request by gkalpak**

### CODE REVIEW

**Review by petebacondarwin — COMMENTED** [review]
I thought the idea was that check-env was run before `yarn install` because it was supposed to check things like the node version, which might prevent the yarn install and related scripts from running correctly.

**Comment by gkalpak** [comment]
The `check-environment` script assumes that you have installed the dependencies:

https://github.com/angular/angular/blob/b1ca5d4ddfab9422b9d9278593ccb2c55b76ed8c/aio/scripts/check-environment.js#L30-L39

So, when you try to run `yarn setup` for the first time (before having installed any dependencies), you get this error.

**Comment by petebacondarwin** [comment]
Ahah! Silly me. LGTM then

**Review by petebacondarwin — APPROVED** [review]
Not sure if we should include the change to `yarn.lock` in this commit. Perhaps leave that for #19616?

**Comment by gkalpak** [comment]
Removed the `yarn.lock` change.

**Pull request closed without merging**
