### PR TITLE
fix(router): handle URL that does not match a route

### LINKED ISSUE #7349: bug(Router): Stack trace on unrecognized routes
@petebacondarwin @btford @IgorMinar 

Code sample: http://plnkr.co/edit/Ly2gfBsyd1J4iJlTjA4C
To reproduce:
- http://run.plnkr.co/plunks/Ly2gfBsyd1J4iJlTjA4C/#/x1 (loads the child component correctly)
- **in the same tab**, change URL to http://run.plnkr.co/plunks/Ly2gfBsyd1J4iJlTjA4C/#/x2 (stack trace)

Note that navigating directly to the incorrect URL does not seem to trigger the issue; only navigating from a valid to an invalid route in the context of the same tab does.

Attempted fix: #7203

### PR DESCRIPTION
**Pull request by petebacondarwin**
Only the last commit is relevant here. Once #7319 lands I'll rebase

Closes #7349
Closes #7203

### CODE REVIEW

**Comment by btford** [comment]
LGTM, let's merge this!

**Comment by vikerman** [comment]
@petebacondarwin - Can you rebase this? Thanks

**Comment by petebacondarwin** [comment]
@vikerman Rebased!

**Comment by martine** [comment]
#7319 is in, can you rebase?

**Comment by alexeagle** [comment]
merged as 8e3e450

**Pull request closed without merging**
