### PR TITLE
test: make e2e tests for element and upgrade docs examples less flaky

### PR DESCRIPTION
**Pull request by gkalpak**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

## PR Type
- [x] Other... Please describe: Test changes.

## What is the current behavior?
A little flaky e2e tests for `elements` and `upgrade` docs examples.

Issue Number: N/A

## What is the new behavior?
Less flaky e2e tests for `elements` and `upgrade` docs examples.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Assuming the tests are happy, this looks good to me.

**Comment by gkalpak** [comment]
I run the `test_docs_examples_*` jobs 7 times each and they didn't flake :tada:

**Comment by IgorMinar** [comment]
@gkalpak / @petebacondarwin please update the label to merge on your own once all the review feedback is resolved and CI is green.

**Comment by IgorMinar** [comment]
oh.. you did... I guess I had a stale version of this PR opened in the browser. sorry about the noise :)

**Pull request closed without merging**
