### PR TITLE
docs: add Accelebrate to resources

### PR DESCRIPTION
**Pull request by annefernandez3**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Accelebrate is not listed as an option on angular.io/resources in the section Workshops & Onsite Training 
Issue Number: N/A

## What is the new behavior?
Accelebrate is listed as an option on angular.io/resources in the section Workshops & Onsite Training 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Comment by annefernandez3** [comment]
I signed it!

Anne

**Review by StephenFluin — APPROVED** [review]

**Comment by vicb** [comment]
> The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

Nope. Please update it.

**Comment by brandonroberts** [comment]
Hi @annefernandez3. Will you rebase your branch on master and update the git commit message to `docs: add Accelebrate to resources`

Thanks!

**Review by StephenFluin — CHANGES_REQUESTED** [review]
It looks like you are trying to add back the Intertech classes? Can you remove this addition?

**Comment by brandonroberts** [comment]
@StephenFluin this one should be ready now.

**Review by StephenFluin — APPROVED** [review]

**Pull request closed without merging**
