### PR TITLE
docs: add CSRF to XSRF section of http guide

### PR DESCRIPTION
**Pull request by rdmueller**
When I searcched for CSRF/XSRF protection for an Angular app, I had some trouble to find the right information. 
So I now created this PR in hope that it will help others to find the infos more easily

#hacktoberfest

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Hi @rdmueller, thanks for this. It'll definitely help with searching. Could you do a few things so we can move this forward?

1. rebase: I have[ some notes on my own workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) you may find helpful.
1. Remember to sign the CLA.
1. Squash and amend your commit message. I have [notes on these](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) too. Try this: `docs: add CSRF to XSRF section of http guide`

When you're ready, would you tag me so I can help you through the process? And of course, feel free to tag me with any questions along the way. 🙂

**Comment by rdmueller** [comment]
Hi @kapunahelewong ,
thanx for your tips.
rebased, squashed, commit comment updated, cla signed.
some failing tests, but these can't be connected with my change, can they?

**Comment by kapunahelewong** [comment]
Oops! Sorry for the delay in my response, @rdmueller! No, I don't think it was anything in your changes that made them fail. Sometimes the tests flake. I've gone ahead and rebased again and pushed up to re-trigger the tests to try to get this through soon. Fingers crossed!

Thanks for your patience. 😊

**Review by kapunahelewong — APPROVED** [review]
LGTM. Thank you, @rdmueller!

**Comment by kapunahelewong** [comment]
merge-assistance: Global approval for this docs-only change.

**Pull request closed without merging**
