### PR TITLE
build: adding locales path to exports in package.json

### PR DESCRIPTION
**Pull request by Rambou**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Allow locales to be dynamically imported.

Issue Number: [N/A](https://github.com/angular/angular/issues/44153)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@Rambou - hi, thanks for this PR. Can you give us some more information about the motivation for this change? Why does the current exports of:

```
    "./locales/global/*": {
      "default": "./locales/global/*.js"
    },
    "./locales/*": {
      "default": "./locales/*.mjs"
    }
```

not provide you with the access that you need?

The `"./locales/*"` should provide access to the extra folder too via sub-path mapping. See https://nodejs.org/api/packages.html#subpath-patterns

**Comment by petebacondarwin** [comment]
Ah! I see that this is to resolve https://github.com/angular/angular/issues/44153.

**Comment by petebacondarwin** [comment]
I would say that, at best, this is a workaround for a bug in webpack.

**Comment by alan-agius4** [comment]
Thanks for your contribution. However, there are other workarounds for this Webpack bug that don't require any changes in the package exports.

See https://github.com/angular/angular/issues/44153#issuecomment-967061797

**Comment by Rambou** [comment]
Thanks guys @petebacondarwin @alan-agius4 indeed it's a webpack issue and solution is here 
```
import(
  /* webpackExclude: /\.d\.ts$/ */
  /* webpackMode: "lazy-once" */
  /* webpackChunkName: "i18n-extra" */
  `@/../node_modules/@angular/common/locales/extra/${id}`)
```

**Pull request closed without merging**
