### PR TITLE
build(aio): remove unnecessary `--` from yarn commands

### PR DESCRIPTION
**Pull request by gkalpak**
Essentially backports ffceae0a0 and f7199aa8c to 4.4.x.

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Can you look into why Travis is failing? Looks like there might be some issues with building against the local dists??

**Comment by gkalpak** [comment]
The Travis failures are unrelated to this PR. 4.4.x has been failing since https://travis-ci.org/angular/angular/jobs/283293450.
Investigating...

**Comment by gkalpak** [comment]
The reason for the 4.4.x failures is using yarn@1.1.0 (vs yarn@1.0.2 on master).
[This change][1] in particular (introduced in v1.1.0) seems to be the culprit.

##
It seems that something (possibly `@ngtools/webpack`, which is a dependency of `@angular/cli`) peer-depends on TypeScript (TS@^2.0.2) and gets linked to a higher version (TS@2.4.1) with yarn@1.1.0, which is stricter than the 2.3.2 version we use on `aio/` (and which that something gets linked to with yarn@1.0.2).

Ideally, we should upgrade TypeScript and other dependencies (e.g. RxJS) on `aio/` and fix our code to be compatible. But t might not be worth it for 4.4.x. In any case,"downgrading" yarn to 1.0.2 on 4.4.x (same as master), until we figure out the next steps.

[1]: https://github.com/yarnpkg/yarn/pull/4478

**Comment by petebacondarwin** [comment]
Good sleuthing. Let's just downgrade for the time being, yes?

**Comment by gkalpak** [comment]
@ocombe is working on an alternative fix, so we can keep yarn@1.1.0: #19585

**Comment by gkalpak** [comment]
`yarn` has been downgraded for 4.4.x with d45e3aa43.

**Pull request closed without merging**
