### PR TITLE
typo in example caused tutorial to break; void return type was missing

### PR DESCRIPTION
**Pull request by JeanPierreDeTiege**
…g from method which caused the website to push out error messages via console log.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The Tutorial includes the generation of a message service which, when created by copying the tutorial text, doesn't run correctly because the add method doesn't have a void return type specified in the provided code. As a result, the tutorial breaks because the injection code does not generate the service and the add call in the HeroService cannot execute to add an actual message. 

Issue Number: N/A

## What is the new behavior?

The added void return type allows the tutorial to run successfully.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ X] No

### CODE REVIEW

**Comment by JeanPierreDeTiege** [comment]
I Signed it!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Review by mhevery — APPROVED** [review]

**Comment by brandonroberts** [comment]
@JeanPierreDeTiege I don't think this change is explicitly needed, as the void type is inferred. Where in the tutorial did you run into this issue?

**Comment by JeanPierreDeTiege** [comment]
> @JeanPierreDeTiege I don't think this change is explicitly needed, as the void type is inferred. Where in the tutorial did you run into this issue?

Hello @brandonroberts, I ran into this issue on part 4 of the tutorial (services) when I finished copying all the statements, saved the files and refreshed the browser window in which the page was loaded. I fully understand your reasoning and actually assumed the same expectation (void type being inferred) I discovered that the tutorial only worked when I added the statement explicitly.

I cannot however reproduce the actual issue right now; that is to say, I went into the tutorial locally, started up Angular, removed the explicit void return type and saved and saw the page refresh and still load and provide messages. I should add that I did implement the rest of the tutorial so the state of the code has moved on since the initial issue but I can't confirm right now that this is an issue still without doing the tutorial from scratch again. Let me know if you'd prefer me to go through the tutorial from scratch again to see if I hit the same problem or if you feel comfortable with parking this issue based on the expectation that the void type is to be inferred by default.

**Comment by brandonroberts** [comment]
I feel comfortable with parking this issue and the type being inferred not being the root cause.

**Comment by JeanPierreDeTiege** [comment]
Apologies for a late response and thanks for taking the time to look into this. I can confirm that I've recently tried to replicate the error condition I encountered and could not manage to do so; it must've been a phantom error when I ran into it the first time and I'll try to reproduce reliably next time before I file another. The one thing that I did notice is that I had an issue where the solution didn't immediately load all files which caused another reference in the tutorial not to resolve correctly; only when I made another edit in the same file and saved did it update that reference; it could very well have been something similar to that having caused the original issue I encountered.

**Pull request closed without merging**
