### PR TITLE
docs: adds Chris Perko to the GDE resources

### PR DESCRIPTION
**Pull request by BaronVonPerko**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Adds Chris Perko to the GDE resources

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by sonukapoor — APPROVED** [review]
Welcome @BaronVonPerko

**Comment by BaronVonPerko** [comment]
> Welcome @BaronVonPerko

Thank you!  Happy to be part of the Angular GDEs!

**Review by bencodezen — APPROVED** [review]

**Comment by sonukapoor** [comment]
@JeanMeche Can you point me to the link on adev?

**Comment by JeanMeche** [comment]
@sonukapoor It's in the footer of every page.

**Comment by sonukapoor** [comment]
I see it. I feel there should be a section for the trusted contributors as well. Its missing at this moment.

**Comment by BaronVonPerko** [comment]
> Hi Chris, with the release of v18 coming soon, angular.io entered maintenance mode and won't accept updates. On the new angular.dev site, we directly pointing to global GDE directory, so this change isn't needed anymore.
> 
> Thank you for your understanding.

Makes perfect sense, thank you!

**Pull request closed without merging**
