### PR TITLE
feat(migrations): add schematic to migrate to signal queries

### PR DESCRIPTION
**Pull request by devversion**
This commit adds an automated `ng generate` schematic/migration for converting decorator
queries to signal queries, as good as possible.

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]

**Comment by devversion** [comment]
This PR was merged into the repository by commit b6bc93803c246d47aac0d2d8619271d42b249a4a.

The changes were merged into the following branches: main

**Comment by lamisChebbi** [comment]
Very good news !

**Comment by abdelillahbel** [comment]
That's really cool ! @devversion

**Comment by abdelillahbel** [comment]
**That's really cool !**

**Comment by muhammadawaisshaikh** [comment]
good contribution. thanks @devversion

**Pull request closed without merging**
