### PR TITLE
docs(router): document segment consumption during route evaluation

### PR DESCRIPTION
**Pull request by nesjett**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This PR was previously closed because of inactivity. Let me know if this is not the right way of resending it, but otherwise, which commit message should I have set on the correction?

Original PR: https://github.com/angular/angular/pull/57437

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@nesjett thanks for improving Angular docs!

**Comment by AndrewKushnir** [comment]
**Caretaker note**: no presubmit is required, docs-only change.

**Comment by devversion** [comment]
Note: adding cleanup label. Lint seems to be failing.

**Comment by nesjett** [comment]
Do I need to do anything? The command that failed seem to modify the file but not changing anything at all. (maybe some EOF or something?)
```
yarn ng-dev format files packages/router/src/models.ts
```

I can update the PR with that change, but what commit message should I use, chore? It does not seem to fit any of the listed in the "contributing" docs: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit

**Comment by devversion** [comment]
Hmm. Maybe you are not rebased? CI runs with a rebased version

**Comment by JeanMeche** [comment]
I ran on the branch of the PR, the script updates and fixes the file without a rebase. 
Can you double check that you don't get any changes ?

**Comment by nesjett** [comment]
Indeed I had to enable "view whitespace differences" in my IDE to see the change.

Should I commit that change with a "chore:" commit message type?

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
**Caretaker note**: no presubmit is required, docs-only change.

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 18ddf0de76796596507838c64c57baf0eaa26137.

The changes were merged into the following branches: main, 18.2.x, 19.0.x

**Pull request closed without merging**
