### PR TITLE
docs: fix CLI command usage

### PR DESCRIPTION
**Pull request by trotyl**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

The command is `ng update`: https://angular.io/cli/update#ng-update

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jenniferfell** [comment]
Thank you :-)

**Comment by trotyl** [comment]
I guess `aio/content/guide/deprecations.md` is missing from [CODEOWNERS](https://github.com/angular/angular/blob/master/.github/CODEOWNERS), resulting in reviewer fallback.

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
**merge-assistance:** Global approval (this is a docs-only change).

(@trotyl, feel free to submit a PR adding the file to CODEOWNER 🙏)

**Comment by gkalpak** [comment]
No idea 😅
Someone from the tooling team should know (cc @filipesilva, @alan-agius4).

**Comment by filipesilva** [comment]
@clydin can you chime in about this deprecation please?

**Comment by clydin** [comment]
The entire paragraph can be removed.  The polyfill is now internally managed for CLI users and can be removed in 9.0 without changes to the Angular project itself.

**Comment by trotyl** [comment]
Removed this line as per @clydin 's suggestion.

**Comment by trotyl** [comment]
I think I may misunderstood what **entire paragraph** is, but technically each text separated by empty line is rendered to a standalone paragraph (`<p>`) in markdown... 😃

**Pull request closed without merging**
