### PR TITLE
fix(core): More precise return type for `InjectableDecorator`

### LINKED ISSUE #26942: InjectableDecorator should have a more specific return type than `any`
## I'm submitting a...
<pre><code>
[x] Bug report
</code></pre>

## Current behavior

`InjectableDecorator`, when called as a function, has the return type `any`. 
Using `Injectable()` as a decorator therefore causes a violation of TSLint's `no-unsafe-any` rule. See https://github.com/palantir/tslint/issues/3784.

## Expected behavior
 The `any` type is generally something to avoid in TypeScript because it removes type safety from operations it's involved in.

## Minimal reproduction of the problem with instructions

`MyComponent.ts`:

```typescript
import { Injectable } from "@angular/core";

@Injectable()
export class MyComponent {
    // ...
}
```

`tslint.json`:

```json
{
  "rules": {
     "no-unsafe-any": true
  }
}
```

## What is the motivation / use case for changing the behavior?

Until the return type is more specific, TSLint users will need to disable the otherwise-useful `no-unsafe-any`.

For Tooling issues:
<pre><code>
- TSLint version: 5.11.0
- TypeScript version: 3.1.3
</code></pre>

### PR DESCRIPTION
**Pull request by mhevery**
closes #26942

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]

**Comment by mhevery** [comment]
http://test/OCL:224059565:BASE:224059640:1543966927646:f9e5b746

**Review by IgorMinar — APPROVED** [review]
lgtm, but shouldn't more decorators be fixed in this way?

**Comment by mhevery** [comment]
CARETAKER: Not sure why this is not going green since it was approved

**Comment by IgorMinar** [comment]
@mhevery you didn't add the right labels: screen shot 2018-12-04 at 11 15 43 pm

**Pull request closed without merging**
