### PR TITLE
Updated vi.ts

### PR DESCRIPTION
**Pull request by hql287**
Updated words casing & order.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:

Update words casing & order.

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by hql287** [comment]
@googlebot I signed it!

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
I'm sorry @hql287 - these files are generated from CLDR so you cannot change them here.
See https://github.com/angular/angular/blob/ac9c508998a37229dbe6cb7d8fa981915fef88af/packages/common/locales/vi.ts#L9

**Comment by santoshyadav198613** [comment]
Hey thanks for PR, can you read line no 9 of file.

Actually this file is autogenerated.

**Comment by petebacondarwin** [comment]
Closing as this PR cannot be merged.
@hql287 - if there is a problem with the source CLDR then please raise an issue there.
Or if there is a problem with our extraction tool then raise a new PR here.

**Pull request closed without merging**
