### PR TITLE
build(docs-infra): use stable packages in examples

### PR DESCRIPTION
**Pull request by alan-agius4**
With this change we replace AIO examples to use stable Angular packages.

The main reasons for this is that prereleases might contain bugs that are not in the stable version especially in the Angular CLI were it's not validated in G3.

### CODE REVIEW

**Review by devversion — COMMENTED** [review]
Can we clarify why we are changing this back? (it's not clear to me, and the commit doesn't mention it -- just an issue)

**Comment by alan-agius4** [comment]
@devversion PTAL

**Comment by devversion** [comment]
I think it makes sense for CLI packages, but I want to bring up one small point for discussion (@gkalpak would know best I think)

1. Angular AIO is deployed from `HEAD`. i.e. next.angular.io.
   * Docs content reflects the API from `main`
   * The examples are tested with the local builds as well (so also `main`)
   * I believe the site itself uses the NPM packages from `aio/package.json`

This means that the AIO sites may always be ahead of what is on `@latest`, especially for `next.angular.io`. The example code may also be ahead of what is released on NPM `@latest` as it seems? So I believe it would make sense considering the examples to also use the most recent pre-releases `@next` (as that is closer to what we test in the actual repo here)

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Yes, it is true that the content on AIO can be ahead of the latest released versions. Unfortunately, I don't think there is an ideal solution.

I think a good compromise would be to use prereleases on next.angular.io (and rc.angular.io) and use stable packages in angular.io (which corresponds to the stable version). But I don't know of a good way to achieve this automatically.

**Comment by alan-agius4** [comment]
We could add an additional Renovate rule to only use next in `main` and latest in the patch version. That said, this is complex for our case since the patch branch name changes with every minor. 

Context: https://docs.renovatebot.com/configuration-options/#matchbasebranches

**Comment by gkalpak** [comment]
But we would have to manually update the versions whenever we create a new patch branch for `main`, right?

**Comment by alan-agius4** [comment]
Yes

**Comment by devversion** [comment]
I'm good with doing the change as is, but just wanted to mention that it's not ideal (which we have all acknowledged now)

**Comment by devversion** [comment]
I guess a question would be, what would be the downside of always using pre-releases for framework packages, and keep using stable CLI/devkit packages? That wouldn't be any different to the current setup, except that CLI is not updated (addressing the problem outlined as the reason for this PR)

**Review by devversion — APPROVED** [review]
LGTM, but @alan-agius4 feel free to consider my latest comment above.

**Comment by devversion** [comment]
(discussed offline -- we will just go with this for now and see how it ends up working)

**Comment by alxhub** [comment]
@alan-agius4 looks like this could use a rebase

**Comment by alxhub** [comment]
Hi @alan-agius4, looks like this needs a quick rebase!

**Comment by alxhub** [comment]
This PR was merged into the repository by commit a44b4bfebc98cdaaa19a3cb1dbf77e987b5770c5.

**Pull request closed without merging**
