### PR TITLE
Added animation-delay and animation-duration support.

### PR DESCRIPTION
**Pull request by troyanskiy**
Added animation-delay and animation-duration support.

### CODE REVIEW

**Comment by troyanskiy** [comment]
I signed it!

**Comment by breath103** [comment]
:+1:

**Comment by mhevery** [comment]
@matsko can you have a look, i believe this is obsolete and it can be closed.

@troyanskiy I am sorry that it has taken so long for us to merge your changes. We pledge to do a better job in a future. I believe that the new animation (https://github.com/angular/angular/pull/8734) which are about to land will make this PR obsolete.

**Comment by troyanskiy** [comment]
@mhevery it's ok.
I do understand you. You are doing a great job.
Thank you!

**Comment by matsko** [comment]
We do support delays in the new API: https://github.com/angular/angular/pull/8734/files#diff-edceb42aab61f991b98f4804c788f382R340

**Comment by matsko** [comment]
Thank you for the contribution. This existing API will be scrapped tomorrow. Sorry it didn't get picked up earlier.

**Pull request closed without merging**
