### PR TITLE
fix(forms): Add UntypedFormBuilder

### PR DESCRIPTION
**Pull request by dylhunn**
This was intended to be part of #45205, but was left out. Adds a new class for use in migration.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by atscott — APPROVED** [review]
Reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by dylhunn** [comment]
merge-assistance: the CI failures are unrelated to this PR. See the Slack for more info.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 4332897baa2226ef246ee054fdd5254e3c129109.

**Pull request closed without merging**
