### PR TITLE
docs(animations): fix wrong code links present in the animations guide

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
fix the links present in the animations guide under td elements written as
`<code>[text](link)()</code>` which are not rendered properly

Note:
  - the bug was introduced in PR #42885
  - the bug seems to be only present for code blocks inside a td element,
    the aforementioned format can be used in the normal sections without issues

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Some links in the aio animation guides are rendered incorrectly:
Screenshot at 2021-10-09 13-54-51

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

@gkalpak sorry I missed this [here](https://github.com/angular/angular/pull/42885#discussion_r716716518) :sob:  :sob:  :sob:

Strangely as I mentioned in the commit this only applies for such `code`s in `td` elements, the other instances seem to be fine

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by petebacondarwin** [comment]
The difference is what it means to "enter an HTML block" :-) What you just linked to is called "inline HTML". In that case the markdown parser continues to process the text within the element as markdown.

But if you have an HTML tag at the beginning of a line with a preceding blank line, then this switches the parser to HTML mode and only after another blank line will it switch back.

**Comment by dario-piotrowicz** [comment]
> The difference is what it means to "enter an HTML block" :-) What you just linked to is called "inline HTML". In that case the markdown parser continues to process the text within the element as markdown.
> 
> But if you have an HTML tag at the beginning of a line with a preceding blank line, then this switches the parser to HTML mode and only after another blank line will it switch back.

Ah wow! I had no idea!!!! :open_mouth: 

I thought that once you are inside html tags it's always handled the same way! wow this is super interesting (and honestly, slightly confusing :sweat_smile:)

Thanks a lot!!!! :smiley: :smile:

**Comment by petebacondarwin** [comment]
> @petebacondarwin given what you just explained, would you mind if I updated the commit message to be more precise? 🙂

Sure

**Pull request closed without merging**
