### PR TITLE
Fix styling dynamically created components in ViewEncapsulation.Emulated mode

### PR DESCRIPTION
**Pull request by daneget**
## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number:  #12215

## What is the new behavior?
Dynamically created components with ViewContainerRef.createComponent() has the _ngcontent-* attribute in ViewEncapsulation.Emulated mode so can be styled easily

### CODE REVIEW

**Comment by splincode** [comment]
@daneget what is the status of your pull request? is it still relevant?

**Comment by devoto13** [comment]
@splincode Yes, this PR is still relevant. It is not useful to bot-post this question without looking at the PR. Old != not relevant. Please refrain from doing this unless you have tested that underlying issue is fixed and PR is actually no longer relevant.

**Comment by splincode** [comment]
@devoto13 Many PRs have already been forgotten, so I just ask the authors of the request that in the end they plan to do, continue or close the task.

**Comment by devoto13** [comment]
@splincode Most of these PR are stuck because they didn't get attention from the team, not from the author. IMO a better way to reduce amount of open PRs would be to figure out what it takes to move these PRs forward instead of closing them, because author gave up waiting for their PR to get reviewed.

**Comment by AndrewKushnir** [comment]
Hi, sorry that we didn't have a chance to review this PR sooner. It looks like the fix is in the ViewEngine part of the codebase and since it's now deprecated (so only security and other critical fixes are merged for ViewEngine), I'm closing this PR. As Pawel mentioned in https://github.com/angular/angular/issues/12215#issuecomment-633898959, the same problem exists in Ivy and we would try to review a PR that would target Ivy part of the codebase sooner. Thank you.

**Pull request closed without merging**
