### PR TITLE
Small fixes while updating to TS 1.6

### PR DESCRIPTION
**Pull request by mhegazy**
Trying TS1.6 on latest from master and ran into a few compiler errors. here are the fixes. This should work just fine for 1.5, but would make migrating to 1.6 error-free.

### CODE REVIEW

**Comment by mhevery** [comment]
Looks like your changes broke dart. https://travis-ci.org/angular/angular/jobs/77609361#L718 Could you have a look?

**Comment by mhegazy** [comment]
yes. my bad. did not think i needed to run the dart checks.. sorry about that.

**Comment by mhegazy** [comment]
@mhevery what is the easiest way to get Dart SDK installed on a Windows machine, i got the package downloaded, but it is a .zip file. and the failing tasks only run if dart sdk is installed.

**Comment by mhevery** [comment]
@mlaval can you help @mhegazy with the windows dart installation question. Can we better document this here: https://github.com/angular/angular/blob/master/DEVELOPER.md

**Comment by mlaval** [comment]
@mhegazy what works for me is to first download Dart SDK and Dartium from https://www.dartlang.org/downloads/archive/ and unzip them somewhere.
Then, I edit the environment variable as follows:
1) Add Dart to the Path, e.g. `D:\Dev\Dart\dart-sdk\bin`
2) Create a new env variable named DARTIUM_BIN which points to the Dartium exe, e.g. `D:\Dev\Dart\dartium-win-full-stable-1.12.0.0\chrome.exe`

@mhevery I'll do an update

**Comment by mhegazy** [comment]
thanks @mlaval and @mhevery. looks like the dart issue has been resolved with my latest changes.

**Comment by tbosch** [comment]
Could you rebase ontop of master?

**Comment by tbosch** [comment]
Thanks, we are already on 1.6.

**Pull request closed without merging**
