### PR TITLE
Compiler lex interpolations 2

### PR DESCRIPTION
**Pull request by petebacondarwin**
~~Blocked behind https://github.com/angular/angular/pull/43129~~

This PR is a replacement for the reverted #42062

The significant commit that should fix the i18n message ID problem is https://github.com/angular/angular/pull/43132/commits/359e043af89237059a609f3be55d4caab66e7c97. I have checked that the compliance test passes before this PR.

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:391447581:BASE:391447613:1629261686360:9c31ee74) + [Global Presubmit](https://test.corp.google.com/OCL:391447581:BASE:391447779:1629261801685:b80814fe).

**Comment by AndrewKushnir** [comment]
@petebacondarwin FYI there are legit failures (related to i18n) in the presubmit. I will investigate further and try to come up with a repro within the next day or two. Will keep you updated.

**Comment by petebacondarwin** [comment]
😭 - I am sorry @AndrewKushnir - this is becoming an epic. I just realised that I don't think I fixed the i18n problem for attributes, only for text nodes. Let me add tests and fix that.

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:391447581:BASE:391658989:1629337776012:dd1c343b).

**Comment by AndrewKushnir** [comment]
[One more global presubmit](https://test.corp.google.com/OCL:391447581:BASE:392594344:1629785606533:c0535844).

**Comment by AndrewKushnir** [comment]
[New global presubmit](https://test.corp.google.com/OCL:391447581:BASE:395167548:1630987132384:cfe683b9).

**Comment by AndrewKushnir** [comment]
[One more global presubmit](https://test.corp.google.com/OCL:391447581:BASE:396276945:1631507877614:a5d3fcdf) (after g3 cleanup).

**Comment by AndrewKushnir** [comment]
Quick update: [most recent TGP is "green"](https://test.corp.google.com/ui#id=OCL:391447581:BASE:396989973:1631764408741:b9cf3fd1) and extra checks in g3 confirmed that extracted message IDs are the same before/after the fix, so we should be ready for merge.

**Review by AndrewKushnir — APPROVED** [review]

**Pull request closed without merging**
