### PR TITLE
fix(compiler-cli): do not require platform-server peerDependency

### PR DESCRIPTION
**Pull request by IgorMinar**

### CODE REVIEW

**Comment by vicb** [comment]
need rebasing on master after https://github.com/angular/angular/pull/11593 is merged

**Comment by vicb** [comment]
@IgorMinar please rebase

**Comment by IgorMinar** [comment]
this is now obsolete

**Comment by pdavin** [comment]
What made this obsolete? It's not clear to me whether I need to install platform-server. Should the Angular cookbook instructions that say to install it be updated? 

https://angular.io/docs/ts/latest/cookbook/aot-compiler.html
npm install @angular/compiler-cli @angular/platform-server --save

**Pull request closed without merging**
