### PR TITLE
docs(guide): beware of pipe operator's precedence trap

### PR DESCRIPTION
**Pull request by thorn0**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #27415

### CODE REVIEW

**Comment by brandonroberts** [comment]
@kapunahelewong is this something you can incorporate into your rewrite?

**Comment by kapunahelewong** [comment]
@brandonroberts Sure thing. Hey, @thorn0, would you mind waiting on this one until I'm on that section? I'm working on the part just prior to that right now and should be there in the next couple of weeks. I can tag you here if you're up for it as soon as I'm ready. I'd like you to get credit (hence the PR).

**Comment by thorn0** [comment]
@kapunahelewong Okay. BTW, this also needs to be mentioned here https://angular.io/guide/ajs-quick-reference because the precedence of operators is not like this in AngularJS. For those who are used to the old syntax, the new one is especially unobvious. Does your rewriting include that page too?

**Comment by kapunahelewong** [comment]
@thorn0 No, my current rewrite is just Template Syntax. The ajs quick reference would have to be its own PR.

Do you know if anyone is working on [that doc](https://angular.io/guide/ajs-quick-reference), @brandonroberts?

**Comment by brandonroberts** [comment]
@kapunahelewong not currently, but I think its in the plans.

**Comment by kapunahelewong** [comment]
Thanks, @brandonroberts. @thorn0, if you'd like to submit a PR for the ajs quick ref, that'd be great, since it will probably take a while to get to that one organically.

**Comment by kapunahelewong** [comment]
Hey @thorn0, I have my PR ready if you'd like to add to the Pipes section of Template Syntax:

[https://github.com/angular/angular/pull/28087](https://github.com/angular/angular/pull/28087)

If writing/explaining isn't your thing, I'm happy to do a pass for things like clarity, grammar, and docs conventions we use.

**Comment by thorn0** [comment]
So, what's the workflow, @kapunahelewong ? Can I add commits to your PR? Or do I need to submit a PR to your fork where your PR branch resides? As my change simply adds a self-sufficient warning, can you probably simply copy it from this PR?

**Comment by kapunahelewong** [comment]
I can certainly copy from this PR. But am happy to accept a PR on my fork so you get credit. We can do it however you like.

**Comment by thorn0** [comment]
@kapunahelewong Please feel free to copy it. I don't care about credit.

**Comment by kapunahelewong** [comment]
@thorn0 All right. Thank you very much for bringing this up and submitting the PR. 🌻

**Comment by kapunahelewong** [comment]
Closing this as @thorn0's changes are now incorporated in #28087.

**Pull request closed without merging**
