### PR TITLE
refactor(core): specify the type of changes for QueryList

### PR DESCRIPTION
**Pull request by yzhe554**
Specify the type of changes
Remove unnecessary type castings

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by yzhe554** [comment]
@googlebot I fixed it.

**Comment by yzhe554** [comment]
@googlebot I fixed it.

**Comment by yzhe554** [comment]
@googlebot I fixed it.

**Comment by yzhe554** [comment]
@googlebot I fixed it.

**Comment by yzhe554** [comment]
Can anyone help me to solve the CLA issue. I have signed it with my primary github email.

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/pull/30375

**Pull request closed without merging**
