### PR TITLE
docs: fix a typo in creating libraries guide

### PR DESCRIPTION
**Pull request by eduard9x**
Minor typo

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks for the PR @eduard9x. You must [Sign the CLA](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#cla) before this PR can move forward.

**Comment by eduard9x** [comment]
Is it okay now, @brandonroberts ?

**Comment by brandonroberts** [comment]
@eduard9x close. The description should begin with a lowercase letter. `docs: fix a typo in creating libraries guide`

**Comment by eduard9x** [comment]
Okay. I have changed it as you suggested. Please have another look.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Caretaker note: I am using a global approval as this is a docs-only change.

**Pull request closed without merging**
