### PR TITLE
refactor(common): Remove ngOnChanges from NgForOf

### PR DESCRIPTION
**Pull request by mhevery**
`NgForOf` used to implement `OnChanges` and than use
`ngOnChanges` callback to detect when `ngForOf` binding
changed to update the differ. We now do the checking 
manually which puts less pressure on the runtime to do 
the bookkeeping and should result in minor perf improvement.

### CODE REVIEW

**Comment by mhevery** [comment]
https://test.corp.google.com/ui#id=OCL:192847783:BASE:192847873:1523665473946:8e01002f

**Comment by IgorMinar** [comment]
the build is failing

**Comment by vicb** [comment]
What kind of improvement to expect ?
What about adding a benchmark ?

**Review by kara — APPROVED** [review]
LGTM

**Comment by mhevery** [comment]
http://test/OCL:198944606:BASE:198944613:1527896149630:7844b149

**Comment by vicb** [comment]
Strictly speaking this is a breaking change.
Do we really want this in the patch branch ?

**Comment by trotyl** [comment]
Agree with this being a breaking change, for example in [class inheritance](https://github.com/trotyl/angular-contrib/commit/6f377e6c1e20c04ce265d29b417ade899f6ecc4e).

**Pull request closed without merging**
