### PR TITLE
Add 'declarations' to the getting-started routing example

### PR DESCRIPTION
**Pull request by eedrah**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Getting started routing example doesn't work - missing declaration of the component

## What is the new behavior?

Add declarations key to example and explain

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandonroberts** [comment]
This isn't required to do manually, as the StackBlitz generator, or the Angular CLI does this for you.

**Review by jbogarthyde — APPROVED** [review]
LGTM

**Comment by kapunahelewong** [comment]
@eedrah, thanks for this PR, but as @brandonroberts commented above, the CLI and StackBlitz both do this automatically for us, so if the reader manually added `declarations`, it could duplicate a `declarations` that would already be in the app. If you're still inspired to submit a PR, I'd be happy to find something of similar scope for you and help you get it through the process. What do you think?

**Comment by eedrah** [comment]
All good, I wasn't aware of the generator at the time - was just copy-pasting to a texteditor. 

Thanks for the warm welcome @kapunahelewong  :) alas though, I've moved on to other projects in other frameworks and already pressed for open-source time

**Pull request closed without merging**
