### PR TITLE
refactor(devtools): use dark scrollbars in dark mode

### PR DESCRIPTION
**Pull request by Den-dp**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

image

Issue Number: N/A

## What is the new behavior?

https://github.com/angular/angular/assets/1770529/ad139725-5ca6-40cb-875c-6fce3799801f

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]

**Comment by Den-dp** [comment]
Didn't know the commit message body was required.

I'll fix the commit message shortly

**Comment by JeanMeche** [comment]
Can you also make a `refactor(dev-tools): ...` commit. 
Fix commit make it to the change log and this isn't really a bugfix. Thank you.

**Comment by Den-dp** [comment]
> this isn't really a bugfix

depending on how you look at it 😅

done!

**Review by devversion — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 080e971db3c3959af98b83e265e9d6572526fcbd.

**Pull request closed without merging**
