### PR TITLE
fix(service-worker): handle quota exceeded

### LINKED ISSUE #36086: Service Worker "Quota exceeded" can break all JS
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/service-worker

### Is this a regression?

 Not sure

### Description

 A clear and concise description of the problem...

The service worker fails to load core JS files with `DOMException: Quota exceeded.`

This results in just a white page being shown, with a broken app.

Angular 9.0.4
Chromium 80

image

image

I've migrated from a custom workbox based serviceworker to the angular native service worker and now running into this.

Force reloading (`ctrl+f5`) makes everything load, but the error returns on the next normal load.

After using DevTools to debug it, I found that the error is `DOMException: Quota exceeded.`  and occurs in this block: 

image

## 🔬 Minimal Reproduction

Hard to reproduce unfortunately, needs low disk space or a big app being cached.

## 🔥 Exception or Error
<pre><code>
The FetchEvent for ".../runtime-es2015.91c3f469886b8efa1fca.js" resulted in a network error response: the promise was rejected.
Promise.then (async)
onFetch @ ngsw-worker.js:1993
(anonymous) @ ngsw-worker.js:1928
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

9.0.4
</code></pre>

**Anything else relevant?**

Might be related to #21412 and #33793 which both appear fixed.

I'm not sure what the right fix here would be, I think fallback to network might be appropriate rather than completely failing the request.

### PR DESCRIPTION
**Pull request by andreialecu**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Failing to write to the cache because of Quota Exceeded results in catastrophic failure.

Issue Number: Fixes #36086

## What is the new behavior?

Don't blow up when writing to the cache.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx for taking this on, @andreialecu (and sorry for my slow turn-around 😅).
I have left some commnents, but all in all I think the current approach is a little too aggressive.

I have looked through all calls of [CacheTable#write()][1] throughout the `service-worker` code and tried to trace them up to were they are handled and/or can affect the observed behavior of the SW.

Details below (mostly for personal reference - not in a particularly useful format :grin:), but the main finding is that the only failure that needs to be handled is:

https://github.com/angular/angular/blob/c8bef1259c185fab24ef483ed626bc27ba61d775/packages/service-worker/worker/src/driver.ts#L419-L421

For example:

```diff
     // Decide which version of the app to use to serve this request. This is asynchronous as in
     // some cases, a record will need to be written to disk about the assignment that is made.
-    const appVersion = await this.assignVersion(event);
+    let appVersion = null;
+    try {
+      appVersion = await this.assignVersion(event);
+    } catch (err) {
+      this.debugger.log(err, `Failed to assign an app version: Driver.fetch(${event.request.url})`);
+    }
```

WDYT?
Also, can you try that the above change does indeed solve the problem for you?

##
<details>
<summary><code>CacheTable#write()</code> calls</summary>

- In the list below, its indentation level lists the call-sites of the method in the previous indentation level.
- An error thrown in a method is propagated to the caller/rethrown, unless otherwise mentioned after the method (separated with ` - `). E.g. `SomeClass#someMethod() - Log it` means that the error thrown inside `SomeClass`' `someMethod()` is logged (i.e. suppressed).
- A method surrounded by `[...]` is one that no further analysis is needed for. This can be either because it appears elsewhere in the list (so it is already analyzed) or because it is handled in an adequate way. 

```
CacheTable#write()
  AssetGroup#fetchAndCacheOnce() - throw SwCriticalError
    IdleScheduler#schedule() callback
      IdleScheduler#execute() - DebugHandler#log()
        IdleScheduler#trigger()
          [Driver#... - never awaited]
    AssetGroup#handleFetch()
      AppVersion#handleFetch()
        [Driver#handleFetch() (with SwCriticalError) - Driver#versionFailed() (NORMAL => EXISTING_CLIENTS_ONLY) + Driver#safeFetch()]
    [PrefetchAssetGroup#initializeFully()]
    LazyAssetGroup#initializeFully()
      [AppVersion#initializeFully() - AppVersion#_okay = false + rethrow]
  AssetGroup#maybeUpdate()
    [PrefetchAssetGroup#initializeFully()]
    [LazyAssetGroup#initializeFully()]
  PrefetchAssetGroup#initializeFully()
    AppVersion#initializeFully() - AppVersion#_okay = false + rethrow
      [IdleScheduler#schedule callback - DebugHandler#log() + Driver#versionFailed()]
      [Driver#setupUpdate()]
  [DataGroup#syncLru() - DebugHandler#log()]
  DataGroup#cacheResponse()
    [DataGroup#safeCacheResponse() - DebugHandler#log()]
  Driver#initialize()
    Driver#ensureInitialized() - SAFE_MODE + rethrow
      [Driver#handleFetch() - Driver#safeFetch()]
  Driver#sync()
    Driver#assignVersion()
      Driver#handleFetch()
        Driver#onFetch() - FetchEvent#respondWith(...)  <-- Unhandled failure
    Driver#cleanupCaches()
      Driver#initialize()
        [IdleScheduler#schedule callback - DebugHandler#log()]
    Driver#setupUpdate()
      Driver#checkForUpdate() - DebugHandler#log() + EXISTING_CLIENTS_ONLY
        Driver#handleFetch()
          [IdleScheduler#schedule() callback - never awaited]
        [Driver#handleMessage()]
        Driver#initialize()
          [IdleScheduler#schedule() callback - never awaited]
    Driver#updateClient()
      [Driver#assignVersion()]
      Driver#handleMessage()
        [Driver#repostStatus()]
    [Driver#versionFailed() - DebugHandler#log()]
```

</details>

[1]: https://github.com/angular/angular/blob/c8bef1259c185fab24ef483ed626bc27ba61d775/packages/service-worker/worker/src/db-cache.ts#L67

**Comment by andreialecu** [comment]
Even with the changes in this PR I think something is still missing.

I've made a build of the app that was initially affected by #36086 using this service-worker PR. 

On a 2019 generation LG OLED TV the service worker still completely breaks the app on the second load. First load is fine, but on reload nothing loads any more. It shows a "This page is not available" generic browser error. The LG TV runs Chromium 53.

I haven't been able to debug the TV to see what the actual error is, but it seems similar to `ERR_FAILED` that I've seen before even on desktop chrome.

**Comment by andreialecu** [comment]
@gkalpak since I'm already here, would it make sense to add the polyfills from #20756 as part of this PR? Reminder of your own comment here: https://github.com/angular/angular/issues/20756#issuecomment-386315924

The problem is that some devices are stuck on older Chromium versions and there's no way to update them. This is valid for Smart TVs and also other Smart TV Box type devices and kiosks.

Ref: https://github.com/jakearchibald/async-waituntil-polyfill

**Comment by gkalpak** [comment]
I wish we could implement option (b) (from https://github.com/angular/angular/issues/20756#issuecomment-386315924), but it didn't get traction :grin:

I am a little concerned about monkey-patching such basic APIs (i.e. `waitUntil()` and `respondWith()`) for everyone (versus just for those needing it). IS there a way to feature-detect this?

In any case, feel free to create a separate PR for that fix and we can discuss there.
(I'd rather keep this on a separate PR, since it is an unrelated issue and potentially controversial too :grin:)

**Comment by gkalpak** [comment]
Hey, @andreialecu, would you have time/interest to move this forward? (Or should someone else take over?)

**Comment by andreialecu** [comment]
I could, but maybe it's easier for you to take it over yourself if you have time yourself?

Allow edits is on. The polyfill turns out is more important for our use case. As mentioned previously, all LG TV's before 2020 need it. They cannot be updated so nothing can be done about getting angular+service-worker not completely blow up on them. I'd be interested in a solution for that as well, because kiosk/informational apps are broken otherwise (other TVs/boxes have the same issue)

**Comment by andreialecu** [comment]
Chromium version for webOS releases, for reference:
http://webostv.developer.lge.com/discover/specifications/web-engine/

**Comment by andreialecu** [comment]
For Samsung TVs, 2018 and older won't work either: 
https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html

**Pull request closed without merging**
