### PR TITLE
DEVELOPER.md had some grammatical mistakes

### PR DESCRIPTION
**Pull request by sumit-khanduri**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```
Update developer.md file.

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by sumitknoldus** [comment]
I signed it!

**Comment by IgorMinar** [comment]
@sumitknoldus it seems that your CLA submission didn't go through or you provided us with incorrect github name / email address and we can't associate your CLA signature with this PR. Can you please try again?

**Comment by sumitknoldus** [comment]
Hi I have signed it again., Please find the attached screeenshot and please do let me know if you find something.
screenshot from 2017-03-02 12-11-35


my username is now sumitknoldus and emailId is sumit@knoldus.com

**Comment by DzmitryShylovich** [comment]
did you configure your emial in git https://help.github.com/articles/setting-your-email-in-git/ ?

**Comment by jenniferfell** [comment]
@sumitknoldus I'm going through some older open doc PRs. Are you still interested in assistance resolving any remaining failed checks/conflicts and having this PR move forward? If so, I'm happy to do what I can to help. Your proposed change looks good, so resolution seems to be related to permissions and standards. It looks like ci/circleci is reporting an issue with the commit messages.

**Comment by jenniferfell** [comment]
I verified that this PR would still be applicable. The current stable DEVELOPER.md still has the old text that is being improved by this PR.

**Comment by IgorMinar** [comment]
@sumitknoldus this PR needs to be rebased. Could you please do it? thanks a bunch!

**Comment by sumitknoldus** [comment]
hi @igor Minar yes i would love to do it.

**Comment by sumitknoldus** [comment]
I signed it!

**Comment by sumitknoldus** [comment]
I signed it!

**Comment by sumitknoldus** [comment]
I signed it!

**Comment by jenniferfell** [comment]
@sumitknoldus I'm not sure why the cla/google check is still not associating your CLA signature with the activity in this PR. We sometimes see problems when a person's git account doesn't match the email used for the CLA. We added some new information here: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#cla

Perhaps that will help? If not, I'll see if we can find out what else might be causing the disconnect. Thanks.

**Comment by brandonroberts** [comment]
@sumitknoldus if you are still interesting in landing this PR, you'll need to sign the CLA and rebase the branch off laster master.

**Pull request closed without merging**
