### PR TITLE
refactor(dart): use Map instead of HashMap

### PR DESCRIPTION
**Pull request by harryterkelsen**
this makes the ng2.di.instantiate benchmark a little faster for Dart

### CODE REVIEW

**Comment by spacebark** [comment]
CLA done

**Comment by kegluneq** [comment]
This LGTM though I'll let someone else flip the bit.

**Comment by vicb** [comment]
IIRC we've switched from `Map` to `HashMap` in Angular.Dart because the later were faster. What kind of perf impact can you see ?

**Comment by spacebark** [comment]
Switching to Map brought the ng2.di.instantiate benchmark pureScriptTime from 194ms to 140ms on my machine. The rest of the benchmarks remained the same. Doing forEach on Map is a lot faster than on HashMap. We also have plans to forward to a native ES6 map for Map in dart2js.

**Pull request closed without merging**
