### PR TITLE
build(docs-infra): upgrade cli command docs sources to 7653f8616

### PR DESCRIPTION
**Pull request by gkalpak**
Updating [angular#9.1.x](https://github.com/angular/angular/tree/9.1.x) from [cli-builds#9.1.x](https://github.com/angular/cli-builds/tree/9.1.x).

##
Relevant changes in [commit range](https://github.com/angular/cli-builds/compare/98de22823...7653f8616):

**Modified**
- help/e2e.json

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Strangely the CI failures do not seem to be flakes, after a restart...

**Comment by gkalpak** [comment]
The errors are unrelated to this PR and will be fixed by #37151.

**Comment by gkalpak** [comment]
Rebased on 9.1.x now that #37151 has been merged. That should make CI green.

**Comment by kara** [comment]
Closed in https://github.com/angular/angular/commit/4830d664da8d55051afeb2cf1bef002e981459d6

**Pull request closed without merging**
