### PR TITLE
Improvements for safe access in template pipeline

### PR DESCRIPTION
**Pull request by mmalerba**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

- temporary variables are not reused within an expression
- safe calls are not handled correctly

Issue Number: N/A

## What is the new behavior?
- temporary variables are reused within an expression when it is safe to do so
- safe calls are handled correctly

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-compiler

Thanks in addition for adding the infrastructure to support alternate golden files.

**Comment by mmalerba** [comment]
Caretaker note: internal failures were already failing / flakes, reran and got a green

**Comment by alxhub** [comment]
This PR was merged into the repository by commit c1dee4cfe304dd5110d63e7dbb1b2dccbb25514d.

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 2d52d5e62c4364808c4e3c62d1fb98e3203c5d61.

**Pull request closed without merging**
