### PR TITLE
docs: simple grammatical corrections

### PR DESCRIPTION
**Pull request by Highbury14**
Simple typo-error grammatical corrections.

Correction: "....its  associated files...."

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Wrong grammatical usage in sentence.

Issue Number: N/A

## What is the new behavior?
Correct grammatical usage in sentence.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by 3imed-jaberi — APPROVED** [review]

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

thanks for fixing this!

**Comment by dario-piotrowicz** [comment]
Could the commit message be improved and not have an emoticon in it? :sweat:

**Comment by AndrewKushnir** [comment]
Thanks for creating this PR. It looks like the CLA has not been signed yet, so we can not proceed with this PR. Could you please [follow the instructions here](https://github.com/angular/angular/pull/44347/checks?check_run_id=4389494461) to sign the CLA? Please let us know (by leaving a comment in this thread) when you sign the CLA, so we can proceed with the review. Thank you.

**Comment by atscott** [comment]
Closing due to lack of CLA for some time. Please feel free to open a new PR once you've done that.

**Pull request closed without merging**
