### PR TITLE
Docs: add info regarding custom pipes

### PR DESCRIPTION
**Pull request by elena-sam**
Indicate that a pipe also needs to be included in the providers array

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by elena-sam** [comment]
CLA signed!

**Comment by brandonroberts** [comment]
Thanks for the PR @elena-sam! Pipes are only _required_ to be added to `declarations`. What's your use case?

**Comment by elena-sam** [comment]
Thanks for your reply @brandonroberts!
My suggestion was pertaining to [this kind of issue](https://github.com/angular/angular/issues/15107). I felt it would be relevant to indicate that adding pipes in the providers set can be necessary when you want to inject a custom pipe in your components. I feel info is missing in the documentation regarding this issue.

**Comment by brandonroberts** [comment]
Adding a custom pipe to the `providers` array isn't required unless you want to inject the pipe into a component/service, which you should try not to do. Will you instead add an extra bullet instead?

```
If you choose to inject your pipe into a component, you must provide it in the `providers` array.
```

**Comment by brandonroberts** [comment]
@elena-sam are you still interested in landing this change?

**Review by brandonroberts — APPROVED** [review]

**Pull request closed without merging**
