### PR TITLE
Fix a couple of i18n typos

### PR DESCRIPTION
**Pull request by alan-agius4**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
👍

**Review by dgp1130 — APPROVED** [review]
Thanks Alan! I was hoping to fix myself but just couldn't get around to it. I remember `extract-18n` happens a couple times in this file, can you fix those as well?

**Comment by alan-agius4** [comment]
> Thanks Alan! I was hoping to fix myself but just couldn't get around to it. I remember `extract-18n` happens a couple times in this file, can you fix those as well?

Update. Note sure how I missed those.

**Comment by atscott** [comment]
This PR was merged into the repository by commit 5fd3bb6a15b88be8a13ba76a78e0dc6afb7a48d3.

**Pull request closed without merging**
