### PR TITLE
fix(router): terminal route in custom matcher

### PR DESCRIPTION
**Pull request by SamVerschueren**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/angular/angular/issues/14833

**What is the new behavior?**
That you can use a custom matcher to match terminal routes.

```js
const routes = [
  {
    matcher: (url: UrlSegment[]) => {
      return url.length === 0 ? ({consumed: url}) : null;
    },
    component: FooComponent
  }
];
```

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Sorry, had some trouble rebasing. Fixed the merge conflicts.

**Comment by SamVerschueren** [comment]
ping :)

**Comment by kevinphelps** [comment]
+1

This change also allows routes that consist only of an optional, given that you have a matcher that supports it. Currently, Angular encounters an error if your matcher returns and empty `consumed` array.

```
const routes: Routes = [
  {
    path: 'v2?', matcher: optionaMatcher, component: DefaultLayoutComponent, children: [
      {
        path: 'items/:itemId', component: ItemViewComponent
      }
    ]
  }
];

**Review by jasonaden — APPROVED** [review]
@SamVerschueren Thanks for the PR and sorry for the delay.

This looks good. Can you rebase again and then we can get this merged?

**Comment by SamVerschueren** [comment]
Thanks for taking this up @jasonaden ! I rebased and fixed the merge conflicts so I think it's good to go.

**Review by jasonaden — APPROVED** [review]
lgtm & thanks!

**Comment by jasonaden** [comment]
Caretaker: Please close #14833 when this is merged.

**Comment by SamVerschueren** [comment]
Thanks guys! 🍻

**Pull request merged**
