### PR TITLE
style: change style css syntax

### PR DESCRIPTION
**Pull request by seunggabi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
I changed css files to sass files. but I found build errors. It is css syntax error.
So, I change css styles. and I suggest this PR.
Thanks.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Woohoo, thx! :tada:
Can you, please, change the commit message to `style: ...` (without the `(aio)` part). Otherwise LGTM 👍

**Comment by seunggabi** [comment]
@gkalpak 
Thanks! I will do it your comment.

**Comment by seunggabi** [comment]
@gkalpak
Thx, I merged latest master branch.
but still occurs build failed.. 

I checked lint, Should I recover commit message's `style(aio)`?
```error
INVALID COMMIT MSG: "Merge branch 'master' of https://github.com/angular/angular into change-css-syntax"
 => ERROR: The commit message does not match the format of '<type>(<scope>): <subject>' OR 'Revert: "type(<scope>): <subject>"'
```

(Thanks for your concern.)

**Comment by seunggabi** [comment]
@gkalpak 
Thanks to your comment.
I understood. Next time it will be easier. :)

**Comment by gkalpak** [comment]
Thx for following through, @seunggabi. It looks good now 👍

**Review by petebacondarwin — APPROVED** [review]

**Review by jenniferfell — APPROVED** [review]
LGTM. Thanks for fixing these formatting/syntax errors to be more consistent and precise.

**Comment by seunggabi** [comment]
@IgorMinar 
Thanks!

**Pull request closed without merging**
