### PR TITLE
docs(docs-infra): add blog in the social toolbar

### PR DESCRIPTION
**Pull request by bampakoa**
Add the logo of Medium in the toolbar along with other social links

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
This PR adds the link of the Angular blog along with the Medium icon in the toolbar along with the other related external links.

image

Please notice that I have not removed it from the links at the bottom of the app. It sounds like a good plan to me to remove it as soon as you approve this change. Thanks a lot!

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Also if @mgechev agrees to this change, then we will need to update the payload sizes, since that is what is currently failing.

**Comment by dario-piotrowicz** [comment]
Hi @bampakoa :slightly_smiling_face: 

Just wanted to ask you, I think we already have a link to the blog in the header:
Screenshot at 2021-10-16 21-37-37

I think two would be too much, wouldn't you agree? :thinking: 
Are you perhaps suggesting to remove the existing one and add yours? :slightly_smiling_face:

**Comment by dario-piotrowicz** [comment]
Another thing, in the past with the help of @gkalpak I tried to make the header a bit more responsive and make it adapt better to smaller screen sizes, with your new icon we get less room in the header which could lead to ugly results:

Screenshot at 2021-10-16 21-41-39

Screenshot at 2021-10-16 21-42-07
(this second one unfortunately already happens for the youtube icon already, so not a big deal I'd say)

These don't seem deal breakers to me but I just wanted to point them out as something we could want to keep in mind :slightly_smiling_face:

**Comment by bampakoa** [comment]
> Hi @bampakoa 🙂
> 
> Just wanted to ask you, I think we already have a link to the blog in the header: Screenshot at 2021-10-16 21-37-37
> 
> I think two would be too much, wouldn't you agree? 🤔 Are you perhaps suggesting to remove the existing one and add yours? 🙂

@dario-piotrowicz thanks very much for your feedback 🙏  I feel that both links for the blog, the one in the header and another at the bottom of the page do not have the attention that they deserve because they blend in with the rest of links and are not easily distinguishable. Additionally, a link about the blog seems to be a better fit with the rest of the resources and social links.
Thus, my proposal is to replace both existing links, with an icon in the toolbar along with the other social icons.

**Comment by twerske** [comment]
@bampakoa thank you so much for this suggestion! 

DevRel reviewed and we're closing this for now as the Blog is already in the main header, which is more highlighted than the social icons. I'm definitely going to bring this suggestion into future planning for the future of the website's design.

**Pull request closed without merging**
