### PR TITLE
fix(bazel): ng_package(data) should support non-text files

### PR DESCRIPTION
**Pull request by jbedard**
Today non-text `ng_package(data)` files might (always?) get corrupted because they get read+written as utf8, for example font or image files.

I think the `utf8` will be used by default for non-binary files, so the param is not needed at all?

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

The bazel `ng_package(data)` now supports non-utf8 files.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
awesome, nice job finding a way to test it

**Comment by AndrewKushnir** [comment]
@jbedard thanks for the PR! Could you please have a look at the lint error here:

https://circleci.com/gh/angular/angular/459499

Thank you.

**Comment by AndrewKushnir** [comment]
@alexeagle should this PR go into master only or master and patch?

**Comment by jbedard** [comment]
Fixed 🤞

Would be great if this was in a patch release...

**Comment by AndrewKushnir** [comment]
Thanks @jbedard and @alexeagle, this PR is now merged into master and patch branches.

**Pull request closed without merging**
