### PR TITLE
Correcting a spelling mistake in the Angular glossary

### PR DESCRIPTION
**Pull request by dmytro-shapovalov**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by santoshyadavdev — APPROVED** [review]

**Comment by Shapovalov-Dmitry** [comment]
@googlebot I signed it!

вт, 24 мар. 2020 г. в 13:59, Santosh Yadav <notifications@github.com>:

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Comment by kapunahelewong** [comment]
Thank you for this, @Shapovalov-Dmitry! Could you do a couple of things so we can move this PR forward? I'd love to mark it for merge

1. [Amend your commit message](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) to be in this format:

```
docs: fix typo in glossary.md

Then in the body of the commit message, explain the changes that you're making and while you're making them. This section needs to be at least 100 characters and have a blank line before and after it.

```

2. [Rebase](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) so you're all up-to-date.

These two links are my own personal notes on working with the Angular repo. If you have any questions or you need help doing it just tag me and I can help you.

**Review by IgorMinar — APPROVED** [review]
I fixed up this PR to pass the lint checks and force-pushed.

LGTM now! Thank you!

Reviewed-for: global-approvers

**Comment by AndrewKushnir** [comment]
FYI, it looks like "lint" is still failing, adding the "cleanup" label. Thank you.

**Comment by jelbourn** [comment]
@Shapovalov-Dmitry the lint failure here is that it requires commit messages to be at least 100 characters, so feel free to just add something like 
```
Fixes a spelling mistake in the Angular glossary, correcting "valdation" to "validation" in the reactive forms section. 
```

**Comment by AndrewKushnir** [comment]
Hi @Shapovalov-Dmitry, FYI I've updated the commit message to remove duplicated lines and also rebased this PR to trigger new CI run. Once CI run is completed, this PR should be ready for merge. Thanks for your contribution.

**Pull request closed without merging**
