### PR TITLE
refactor(core): Throw a runtime error if both zone and zoneless are p…

### PR DESCRIPTION
**Pull request by atscott**
…rovided

This commit adds a dev-mode error if both the zone and zoneless providers are used together.

### CODE REVIEW

**Review by pkozlowski-opensource — COMMENTED** [review]
LGTM

Reviewed-for: public-api 
Reviewed-for: fw-core

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api
Reviewed-for: fw-core

**Comment by pkozlowski-opensource** [comment]
LGTM but needs a bit of cleanup (error verifications failing)

**Review by thePunderWoman — APPROVED** [review]
reviewed-for: public-api

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit abbaf8f6397a642f0d6ae39750b269c64b66bf2e.

**Pull request closed without merging**
