### PR TITLE
docs: remove extraneous word from sentence in styleguide

### PR DESCRIPTION
**Pull request by simonua**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
You have a good eye, @simonua! Could you amend the commit message to something more descriptive such as:

```
docs: remove extraneous word from sentence in styleguide
```

As in the other two PRs, please tag me when you're ready and I'll help this through. Thanks for your work!

**Comment by simonua** [comment]
@kapunahelewong, I read the styleguide cover-to-cover. =P It's very well-written.

After I pushed this commit, I noticed several other instances of a missing hyphen. Could you take a look at the _Style 04-11_ section, please, and let me know whether you want all those instances to be updated?

**Comment by kapunahelewong** [comment]
I like the style guide too! 😊

As for the other missing hyphens, do you mean between "lazy" and "loaded" in section [04-11](https://angular.io/guide/styleguide#lazy-loaded-folders)? We try to keep those unhyphenated, but maybe I'm missing what you're referring to.

**Comment by simonua** [comment]
Hi @kapunahelewong, yes, that's what I meant. To me, _lazy-loaded_ is a compound adjective and should be hyphenated. Either way, I would stay consistent, too, so if you suggest to leave as is, then I would close this PR as well.

**Comment by kapunahelewong** [comment]
I see what you mean, and agree that technically in keeping with grammar rules, it should be _lazy-loaded_, but we've used _lazy loaded_ throughout the site, and it appears to be the general use in tech writing. I looked up what the Google Developer Documentation Style Guide [says on hyphens](https://developers.google.com/style/hyphens)  and it looks like the original direction within the Angular docs might have been based on whether or not using a hyphen would cause confusion. It looks as though the original precedent might have been set assuming that the term wouldn't be confusing without it.

All that said though, please don't close this PR! 😊🙏🏼 The change you've made is good and it'd be great for it merge.

**Comment by simonua** [comment]
Thank you very much for clarifying. I'll fix up the commit history like we talked about in the other PR and send it back your way. Very much appreciate the good collaboration and education, @kapunahelewong.

**Comment by simonua** [comment]
Hi @kapunahelewong, I amended the commit. 

I see where the hyphen conversation snuck into this PR. I then erroneously believed this was the hyphen PR, which led me to comment that I could close this PR. Silly me. =P

**Comment by kapunahelewong** [comment]
Caretaker, this is a docs only change and the failures appear unrelated. If there's anything I can do to help get this green, please let me know. Thank you!

**Pull request closed without merging**
