### PR TITLE
docs(query_list): update highlight language

### PR DESCRIPTION
**Pull request by mgechev**

### CODE REVIEW

**Comment by PascalPrecht** [comment]
LGTM

**Comment by tbosch** [comment]
Hi, can you rebase?

**Comment by mgechev** [comment]
After rebase the example was changed so my change was no longer valid.

However, I found another minor issue which I fixed.

**Comment by pkozlowski-opensource** [comment]
@mgechev it doesn't merge cleanly anymore. Could you please rebase once again?

**Comment by mgechev** [comment]
Ups, I broke something in my fork.

I opened another PR https://github.com/angular/angular/pull/5029

**Pull request closed without merging**
