### PR TITLE
Dynamic component loading

### PR DESCRIPTION
**Pull request by SetTrend**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
The current documentation on [Dynamic Component Loading](https://angular.io/guide/dynamic-component-loader) is partially quite ambiguous and, thus, hard to get.

1. At the beginning it doesn't clearly differentiate between custom and library directives.
1. The "ad" example description doesn't match the actual example.
1. It doesn't get clear on whether "dynamic component loading" means
   1. "loading components dynamically from a fixed, precompiled set of components" or
   1. "loading components dynamically from a web service, which are unknown at compile time".

Issue Number: #23498 

## What is the new behavior?

I tried to amend the documentation in regard to (1) and (2).

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by alan-agius4** [comment]
Your commit message should be structured in this way
```
docs(aio): amend dynamic component loading section
```

**Comment by SetTrend** [comment]
Ah, thanks for the information 👍 😊 

Do you know how I can change that line without being required to add remove empty lines in the code just to create new commitments?

**Comment by alan-agius4** [comment]
If you add new commit the lint will still fail.

You’d need to fixup or reseT.

‘git reset —soft upstream/master’

Do you commit 

and ‘git push -f’

**Comment by SetTrend** [comment]
Strange ... The commit still fails ...

**Comment by vicb** [comment]
Please rebase the changes

**Comment by brandonroberts** [comment]
Hi @SetTrend! Are you still interested in landing this PR?

**Comment by SetTrend** [comment]
This process it too complicated for me, I'm afraid. So I'm out of it.

Yet, the changed files are still in my repository. So anyone who's more acquainted with the PR process is very much invited to take over.

**Comment by brandonroberts** [comment]
Maybe next time there won't be so much friction to getting a PR landed.

**Pull request closed without merging**
