### PR TITLE
docs: add note about the month being zero-based in the Date constructor

### PR DESCRIPTION
**Pull request by NickHodges**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ NA ] Tests for the changes have been added (for bug fixes / features)
- [ NA ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ X ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
NA

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ X ] No

## Other information

Simple change to a comment

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by petebacondarwin** [comment]
@NickHodges - thanks for this submission. Can you please try rebasing on the most recent master commit. I think the CI failures would be fixed by this.

**Comment by NickHodges** [comment]
Argh!  I'm fairly new to git.  Can you give me a pointer on doing so?

**Comment by petebacondarwin** [comment]
No problem! Let's assume that your local git repo has the `origin` remote pointing to your own fork (`https://github.com/NickHodges/angular`).

Add the angular/angular repo as the `upstream` remote:

```
git remote add upstream https://github.com/angular/angular
```

Then fetch the latest master from that remote:

```
git fetch upstream/master
```

Now rebase your branch against this:

```
git checkout datecomment
git rebase upstream/master
```

and finally force-push the changes back to github:

```
git push --force-with-lease
```

Let me know if that doesn't work.

**Comment by NickHodges** [comment]
@petebacondarwin 

Thanks for the assistance.

It appeared to work -- this is my first submission, so I appreciate the help.  I hope this is correct.

**Comment by petebacondarwin** [comment]
Much better! Just one more fix:

```
ERROR: 
  The commit message body does not meet the minimum length of 100 characters
```

Can you add a block of description to the commit message, which needs to be more than 100 chars long?

You can do this by running the following if you are not using a git UI tool.

```
git commit --amend
```

Then force-pushing again as before.

**Comment by NickHodges** [comment]
It appears that my commit message is too short?

Didn't realize there was a minimum, sorry.

**Comment by NickHodges** [comment]
As far as I can tell, my commit message is now 137 characters......yet it still failed for that....?

**Comment by petebacondarwin** [comment]
Sorry it is not clear. The first line of a commit message is its "title". The subsequent lines are the "body". In this case your body is only 88 chars 😢

**Comment by NickHodges** [comment]
LOL -- okay. Comedy of errors.  I lengthened it.  ;-)

**Comment by AndrewKushnir** [comment]
Hi @NickHodges, thanks for your PR, it was merged to main branches a couple mins ago. I just wanted to mention that we plan to remove the commit body length requirement for the docs-related commits (that start with `docs:`) in PR #37764. Thank you.

**Pull request closed without merging**
