### PR TITLE
docs(cheatsheet): add missing bootstrapping section

### PR DESCRIPTION
**Pull request by petebacondarwin**
@naomiblack and @IgorMinar this fixes the incorrect cheatsheet sections

### CODE REVIEW

**Comment by IgorMinar** [comment]
kinda hard to review. if the output looks good, I'd label it for merging..

**Comment by petebacondarwin** [comment]
It looks good to me but then I so did the previous version :-)

**Comment by IgorMinar** [comment]
Now you know what to watch out for!

**Comment by petebacondarwin** [comment]
Rebased for good measure. I have no idea how to merge stuff these days. Over to you @naomiblack

**Pull request closed without merging**
