### PR TITLE
docs(guide): corrected import path for router

### PR DESCRIPTION
**Pull request by muhammadfaizan**
fix in "frequent-ngmodules"

BREAKING CHANGE: none

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by alexeagle** [comment]
Would you please update the commit message as "fix(aio): ..." to satisfy the lint check?

**Comment by muhammadfaizan** [comment]
Sure i will add and contribute back

**Comment by petebacondarwin** [comment]
Sorry @muhammadfaizan the commit message should be `docs(aio):...`
@alexeagle - `fix|feat(aio)` are only for changes to the AIO application itself, while `build(aio):` are generally for changes to the doc-gen infrastructure.

**Comment by muhammadfaizan** [comment]
@petebacondarwin  i just changed commit message.
i am just getting my feet wet so that i can continue contributing

**Comment by petebacondarwin** [comment]
We love contributors! Keep them coming. Thanks.

**Review by petebacondarwin — APPROVED** [review]

**Comment by brandonroberts** [comment]
@muhammadfaizan This change has already been made in master. If you see something else in the future, we'll get it through the process quicker!

**Pull request closed without merging**
