### PR TITLE
docs: simplify deleteHero method in tutorial

### LINKED ISSUE #41233: [Docs][Tutorial] unused complexity on hero deletion
# 📚 Docs or angular.io bug report

### Description

On the last section of the Tour of Heroes tutorial, a [feature is added](https://angular.io/tutorial/toh-pt6#delete-a-hero) to delete an existing hero.
Considering the provided function into the `HeroService` : 

```ts
/** DELETE: delete the hero from the server */
deleteHero(hero: Hero | number): Observable<Hero> {
  const id = typeof hero === 'number' ? hero : hero.id;
  const url = `${this.heroesUrl}/${id}`;

  return this.http.delete<Hero>(url, this.httpOptions).pipe(
    tap(_ => this.log(`deleted hero id=${id}`)),
    catchError(this.handleError<Hero>('deleteHero'))
  );
}
```

It only used once into the app, into the HeroComponent : 

```ts
delete(hero: Hero): void {
    this.heroes = this.heroes.filter(h => h !== hero);
    this.heroService.deleteHero(hero).subscribe();
  }
```

As the provided argument is always an `Hero`, there is no explicit reason the parameter is of type `Hero | number` into the `HeroService`. It might lead to confusion.

As the `deleteHero()` from the `HeroService` just need the hero id, i would suggest refactoring the current code to : 

```ts
// HeroComponent
delete(hero: Hero): void {
    this.heroes = this.heroes.filter(h => h !== hero);
    this.heroService.deleteHero(hero.id).subscribe();
  }
```

```ts
// HeroService
deleteHero(id: number): Observable<Hero> {
  const url = `${this.heroesUrl}/${id}`;

  return this.http.delete<Hero>(url, this.httpOptions).pipe(
    tap(_ => this.log(`deleted hero id=${id}`)),
    catchError(this.handleError<Hero>('deleteHero'))
  );
}
```

### What's the affected URL?**
https://angular.io/tutorial/toh-pt6#delete-a-hero

### Reproduction Steps**
Add the deletion feature to the Tour of Heroes tutorial app

### Expected vs Actual Behavior**
the `deleteHero()` function from the `HeroService expects an argument of type `Hero | number` while it never pass a number in the existing code.

### Anything else relevant?
I can open a PR if the suggestion is accepted

### PR DESCRIPTION
**Pull request by MariosRadis**
Fixes #41233

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #41233 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by MariosRadis** [comment]
@googlebot I signed it!

**Review by gkalpak — APPROVED** [review]
Thx, @MariosRadis 🚀

**Review by gkalpak — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by gkalpak** [comment]
**merge-assistance:** The `ci/angular` check does not get updated with the latest PR status 🤷‍♂️

**Pull request closed without merging**
