### PR TITLE
build: upgrade yargs package to 13.1.0

### PR DESCRIPTION
**Pull request by MaksPob**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
There is a vulnerability in yargs package, because its version is old.  
https://app.snyk.io/vuln/npm:mem:20180117  

## What is the new behavior?
I updated the version of the yargs package. Vulnerability should not be.  

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

I'm not sure.  

## Other information
You are using the old version of the yargs package, which at that time used the old version of the os-local package, which used the vulnerable version of the package mem.  
https://app.snyk.io/vuln/npm:mem:20180117

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Thx, @MaksPob! 
LGTM, but please change the commit message to include info about the vulnerability.

**Comment by gkalpak** [comment]
I've marked this as `master & patch`, but I am not sure if that is appropriate for patch.

**Comment by MaksPob** [comment]
> Thx, @MaksPob!
> LGTM, but please change the commit message to include info about the vulnerability.

Hi @gkalpak! Ok i did it;))

**Comment by gkalpak** [comment]
The CI failures are flakes. Don't worry about that.
Thx for adding the link to the vulnerability in the commit message. Can you also explain why updating `yargs` fixes a `mem` vulnerability (because right now it is not easy to make the connection). E.g. something like:

> build: ...
>
> Update \`yargs\`, because the old version was transitively (via \`os-local\`)
> depending on a vulnerable version of the `mem` package:
> https://app.snyk.io/vuln/npm:mem:20180117

**Comment by MaksPob** [comment]
> The CI failures are flakes. Don't worry about that.
> Thx for adding the link to the vulnerability in the commit message. Can you also explain why updating `yargs` fixes a `mem` vulnerability (because right now it is not easy to make the connection). E.g. something like:
> 
> > build: ...
> > Update `yargs`, because the old version was transitively (via `os-local`)
> > depending on a vulnerable version of the `mem` package:
> > https://app.snyk.io/vuln/npm:mem:20180117

Hi @gkalpak) Ok, i did it;))

**Comment by MaksPob** [comment]
> The CI failures are flakes. Don't worry about that.
> Thx for adding the link to the vulnerability in the commit message. Can you also explain why updating `yargs` fixes a `mem` vulnerability (because right now it is not easy to make the connection). E.g. something like:
> 
> > build: ...
> > Update `yargs`, because the old version was transitively (via `os-local`)
> > depending on a vulnerable version of the `mem` package:
> > https://app.snyk.io/vuln/npm:mem:20180117

Hi @gkalpak! When you merge it commit?)

**Comment by gkalpak** [comment]
@MaksPob, this needs to be reviewed by @angular/fw-compiler owners.

**Review by kara — APPROVED** [review]
LGTM

**Comment by gkalpak** [comment]
Thx, @kara!
@MaksPob, can you rebase on latest master to resolve conflicts?

**Comment by MaksPob** [comment]
> Thx, @kara!
> @MaksPob, can you, please, rebase on latest master to resolve conflicts?

**Comment by MaksPob** [comment]
> Thx, @kara!
> @MaksPob, can you, please, rebase on latest master to resolve conflicts?

Hi @gkalpak!Ok, i already did it))

**Comment by gkalpak** [comment]
**merge-assistance:** @kara's global approval covers the `fw-compiler` review requirement.

**Comment by szellcsaba-ge** [comment]
Bump, can this be applied to Angular 7 as well?

**Pull request closed without merging**
