### PR TITLE
New doc: HTTP: Request data from a server

### PR DESCRIPTION
**Pull request by trekladyone**
New document extracted from the original Communicating with backend services using HTTP document, which is to be retired.

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
@trekladyone 
```
Dangling links: 3 unmatched links. The following docs have links to URLs that do not exist
       - doc "guide/http-request-data-from-server" (content)  - from file "guide/http-request-data-from-server.md"
         - guide/http-request-data-from-server#adding-headers
         - guide/http-request-data-from-server#url-params
         - guide/http-request-data-from-server#report-progress
```

**Comment by jessicajaniuk** [comment]
@trekladyone Can you squash these two commits into one?

**Comment by trekladyone** [comment]
Deleted broken links because the correct links are to docs that are not yet merged. After merging all HTTP docs, the links can be updated.

**Review by jessicajaniuk — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit a51b5cf73c6cbc216c5a4613658a700eca44adf1.

**Pull request closed without merging**
