### PR TITLE
build: move metadata up one level and remove metadata alias workaround

### LINKED ISSUE #15219: Re-enable test/test_summaries.js to make sure we don't break it moving forward
We disabled test_summaries run in offline_compiler_test.sh temporarily. Need to move metadata for secondary entry points up one level and get rid of `alias: ...` stuff.

### PR DESCRIPTION
**Pull request by jasonaden**
Fixes #15219

### CODE REVIEW

**Review by chuckjaz — APPROVED** [review]
Please note in the commit that this reverts 0ab49d4cec23e2957fd7e8dad55d15fc539c69ed

**Review by chuckjaz — CHANGES_REQUESTED** [review]
The file referencesin `browser.metadata.json` are not correct.

**Comment by IgorMinar** [comment]
is this PR dead?

**Comment by chuckjaz** [comment]
Yes. This should be closed as the alias feature was removed differently.

**Pull request closed without merging**
