### PR TITLE
docs: refactor getting started guide

### LINKED ISSUE #43691: [Docs][Tutorial] Refactor Getting Started Guide
### Description
References a set of related tasks in the TaskList #43634 created by @geromegrignon 

- [x] [Docs][Tutorial] Typo on 'description'
section: https://angular.io/start#create-the-product-list
Change from Add the product descriptions. to Add the product description.

- [x] [Docs][Tutorial] Product import not explained
section: https://angular.io/start#pass-data-to-a-child-component
The Product import is included in the snippet but the related task only refers to the Input.

```
import { Component, OnInit } from '@angular/core';
import { Input } from '@angular/core';
import { Product } from '../products';
```

- [x] [Docs][Tutorial] typing consistency
section: https://angular.io/start#pass-data-to-a-parent-component
The product @Input was previously defined using the non-null assertion operator: @Input product!: Product;. The tutorial should be consistent about its usage.

```
export class ProductAlertsComponent {
  @Input() product: Product | undefined;
  @Output() notify = new EventEmitter();
}
```

- [x] [Docs][Tutorial] Pass data to a parent component title misleading
section: https://angular.io/start#pass-data-to-a-parent-component
As no data is passed with the example with the event, I would expect a title more close to the one used in the documentation core: Parent listens for child event (https://angular.io/guide/component-interaction#parent-listens-for-child-event)

### What is the affected URL?

https://angular.io/start

### Please provide the steps to reproduce the issue

_No response_

### Please provide the expected behavior vs the actual behavior you encountered

_No response_

### Please provide a screenshot if possible

_No response_

### Please provide the exception or error you saw

_No response_

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
No
```

### PR DESCRIPTION
**Pull request by helloankit**
Affected URL: https://angular.io/start

Fixes #43691

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #43691

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by aikithoughts — APPROVED** [review]
Looks good to me. Thank you!

Reviewed-for: global-docs-approvers

**Comment by dylhunn** [comment]
This PR appears to have some lint issues as reported in the `test_aio` target. Let me know if any specific help is needed.

**Comment by helloankit** [comment]
> This PR appears to have some lint issues as reported in the `test_aio` target. Let me know if any specific help is needed.

@dylhunn  Can you please provide the issue details? I can't see any linting errors on my side.

**Comment by petebacondarwin** [comment]
Hi @helloankit - the errors are shown in the CI here: https://app.circleci.com/pipelines/github/angular/angular/38068/workflows/c4928992-1fc1-4bee-8cd3-a27f5db4583f/jobs/1063981

```
$ tslint --config "content/examples/tslint.json" "content/examples/**/*.ts" --exclude "content/examples/styleguide/**/*.avoid.ts"
Warning: The 'deprecation' rule requires type information.
content/examples/getting-started/src/app/product-list/product-list.component.ts:19:24
ERROR: 19:24  typedef-whitespace  expected onespace after colon in parameter
ERROR: 19:24  whitespace          missing whitespace
```

**Comment by atscott** [comment]
Closing since the CI issues haven't been addressed. Please feel free to open a new PR once this is cleaned up.

**Pull request closed without merging**
