### PR TITLE
docs:updated angular tech docs

### PR DESCRIPTION
**Pull request by zero-bugger**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Angular is an application design framework and development platform for creating efficient and sophisticated single-page apps.

Issue Number: N/A

## What is the new behavior?
Angular is an open-source application design framework and development platform for creating efficient and sophisticated single-page apps.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ajitsinghkaler** [comment]
Hey can you change our commit-msg to docs: updated angular tech docs right now you have not put a space after `:` listing is failing because of it.

**Comment by zero-bugger** [comment]
Hi,

I have changed commit message and pushed the code.

Thank you very much.

**Comment by ajitsinghkaler** [comment]
actually instead of closing your pull request each time you can also do: git commit --amend; It amends git commit message
After that you can force push with: git push --force-with-lease

**Comment by zero-bugger** [comment]
Ok from next time I will take care of this thanks...!!!!

**Pull request closed without merging**
