### PR TITLE
refactor(compiler-cli): deprecate `allowEmptyCodegenFiles`

### PR DESCRIPTION
**Pull request by JeanMeche**
The `allowEmptyCodegenFiles` option is not used anymore.

Usage was removed in #48268 

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

### CODE REVIEW

**Review by alxhub — APPROVED** [review]

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Comment by dylhunn** [comment]
caretaker: windows target is flaky

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Review by alxhub — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit c31fe761cf6db127ff6bd61aa76487d6a348c723.

**Pull request closed without merging**
