### PR TITLE
chore(ShadowDomStrategies): adds Injectable annotations

### PR DESCRIPTION
**Pull request by 0x-r4bbit**

### CODE REVIEW

**Comment by vicb** [comment]
It should not be required as those are not bound as classes (but as factories as you need to pass an el)

**Comment by PascalPrecht** [comment]
@vicb ah interesting! Didn't know that `@Injectable` annotations are only meant to be used for classes that are required to be bound as classes.

Any insights on why that is? E.g. what if there's no `@Injectable` annotation on a class?

**Comment by vicb** [comment]
`@Injectable` basically tells Dart to generate metadata info for the ctor (ie arg types).

If you do not add `@Injectable` it would not be possible to retrieve the args types. 

As you give explicit type when doing a `=> new xxxStrategy(...)` we don't need this.

**Comment by PascalPrecht** [comment]
@vicb thanks for the explanation. Closing this PR.

**Pull request closed without merging**
