### PR TITLE
feat(aio): code block colors to match palette

### PR DESCRIPTION
**Pull request by sjtrimble**
Proposed alternate code block colors that match the material design palette.

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by sjtrimble** [comment]
The biggest color family changes I made were these:
.lit used to be light blue (now light green)
.pun, .opn, .clo used to be olive green (now blue-gray)

I still think we can improve on the .str color because typically that is the bulk of the code block content, and I'm not sure all that orange is visually pleasing (seems like we're screaming at the user).

Also, would it make sense to consolidate some pre types in order to not have so many colors?

This can all be discussed later if needed, as this PR only addresses the color palette used (blue was kept as blue, for example - but just using the material blue which has a different color tone).

**Comment by IgorMinar** [comment]
just for current aio vs this pr vs webstorm w/ a custom theme:

screen shot 2017-06-20 at 2 32 30 pm

screen shot 2017-06-20 at 2 37 03 pm


screen shot 2017-06-20 at 2 33 15 pm

----

snippet with comments before vs after:

screen shot 2017-06-20 at 2 40 55 pm

screen shot 2017-06-20 at 2 40 49 pm

**Comment by wardbell** [comment]
@sjtrimble This is closer but I am still uncomfortable with the artifacts shown here:

image

Meant to say
>class names color insufficiently different from **string** coloring.

Class, attribute (code/html), and property names are the most important items in a code snippet because they are 90% of the references to code in the prose.

Keeping the comments green is good because that's the universal color of comments in all light-themed editor displays. Nothing else should be green or greenish ... and definitely not items of importance such as attributes.

As I said, you're close. Just need to adjust for these thoughts. I'd suggest those adjustments but I you understand better than I how these syntax colors should relate to the overall them.

**Comment by petebacondarwin** [comment]
I don't see any movement on this PR. I think it is not so important to make this change and I don't like PR sitting around for ages as they go stale and get forgotten.
So unless @IgorMinar or @juleskremer chime in and request to merge this before the end of the week I am going to close it.

**Comment by sjtrimble** [comment]
@petebacondarwin I was planning on updating based on Ward's comments later this week. Overall, I still think this PR is an improvement from what is currently live.

**Comment by petebacondarwin** [comment]
@sjtrimble are you still going to work on this? I haven't heard any recent complaints about the current colour scheme for code. Perhaps we should leave it as-is?

**Comment by sjtrimble** [comment]
@petebacondarwin I was hoping to update :) I still think it would make a big difference in polish.

**Comment by petebacondarwin** [comment]
I think we should close this PR. We have no complaints from anyone about the current colour scheme for the code snippets.

**Pull request closed without merging**
