### PR TITLE
fix(core): Remove `debugger` statement

### LINKED ISSUE #35470: debugger;  // Left intentionally for better debugger experience.
Please, remove this debugger.

https://github.com/angular/angular/blob/9bd959076730c4e22ceadda73694198b4f01b9e0/packages/core/src/render3/errors.ts#L59

### PR DESCRIPTION
**Pull request by mhevery**
Fix #35470

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by AndrewKushnir — COMMENTED** [review]
@mhevery should we also remove `debugger`s from the following locations?
https://github.com/angular/angular/blob/01ab168774aefebdbc59dfde92fa836bb6d42974/packages/core/src/di/injector_compatibility.ts#L225-L228
and
https://github.com/angular/angular/blob/01ab168774aefebdbc59dfde92fa836bb6d42974/packages/core/src/util/assert.ts#L96-L97

**Review by kara — CHANGES_REQUESTED** [review]
Thanks! Marking as needing changes because we still need to remove the `debugger` in the assert file (see @AndrewKushnir's comment)

**Comment by mhevery** [comment]
> Thanks! Marking as needing changes because we still need to remove the `debugger` in the assert file (see @AndrewKushnir's comment)

I intentionally broke this up into two PRs as I wanted to provide options
- https://github.com/angular/angular/pull/35730 (for the second half)

**Comment by kara** [comment]
@mhevery The debugger statements should be removed from the asserts in this PR as well. If we decide later to implement a flag, we can re-add the debugger statement at that point.

**Comment by mhevery** [comment]
Closing in favor of https://github.com/angular/angular/pull/35763

**Pull request closed without merging**
