### PR TITLE
docs: add jaybell to gde list

### PR DESCRIPTION
**Pull request by yharaskrik**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@yharaskrik welcome to the GDE group!

I've added @twerske as a reviewer, but I have a couple minor comments as well:
- Could you please combine 2 commits into one?
- You could drop the `docs-infra` part of the commit message and just have `docs: ...`.

Thank you.

**Comment by yharaskrik** [comment]
Hey @AndrewKushnir thanks a lot!

Ah, I didn't see `docs` in the commit guidelines but I can definitely change that. How do I go about combining these commits into one in this PR, don't think I have ever done that before! 

Thanks!

**Comment by AndrewKushnir** [comment]
@yharaskrik you could use `git rebase` to combine commits (squash the second one into the first commit), try running `git rebase --interactive HEAD~2`.

**Comment by yharaskrik** [comment]
Ok there we go, there is now a single commit with both of them in it but the other two exist there should those be gone if I did it right?

**Comment by AndrewKushnir** [comment]
@yharaskrik I see just 1 commit now in the "Commits" tab of this PR, so it looks like everything worked correctly 👍

**Comment by yharaskrik** [comment]
Great! Thank you for explaining that!

**Review by twerske — APPROVED** [review]
LGTM - welcome!!

**Comment by alxhub** [comment]
This PR was merged into the repository by commit c68385a967fae022831a192e2dd94945980654ad.

**Pull request closed without merging**
