### PR TITLE
fix(forms): for option elements without parent select control value accessor do not set value of native element

### PR DESCRIPTION
**Pull request by MrWolfZ**
fix(forms): for option elements without parent select control value accessor do not set value of
native element

The NgSelectOption directive should only perform any actions if the corresponding option is used
in the context of an @angular/forms form as to not interfere with other libraries that interact with
option elements.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
The `NgSelectOption` directive of the `forms` package is always applied to `option` elements regardless of whether they are used in a corresponding form. In its `value` binding it unconditionally sets the `value` attribute of the underlying native element, i.e. even if the `option` is not used as part of a form the `value` will be set. Every other code in that directive that performs any action is protected by a guard that checks for the presence of parent select control value accessor.

This behaviour leads to issues when any of the forms modules are imported in a module that uses another library or custom directive which interacts with the `value` attribute of the native element (see [this issue](https://github.com/MrWolfZ/ngrx-forms/issues/32) as an example for how this behavior interferes with my `ngrx-forms` library).

Issue Number: N/A

## What is the new behavior?
The new behavior is to extend the guard that checks for the presence of parent select control value accessor to also prevent the directive from modifying the native element's value if no accessor is present.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by MrWolfZ** [comment]
Is there anything else I need to do for this to be considered to be merged?

**Comment by MrWolfZ** [comment]
Any chance of this getting merged?

**Review by cburduja — APPROVED** [review]

**Comment by cburduja** [comment]
Any chance this wil be merged?

**Review by AndrewKushnir — COMMENTED** [review]
Hi @MrWolfZ, thanks for creating this PR and sorry that we didn't have a chance to review it sooner.

The change looks reasonable to me. Could you please rebase it on top of the latest master branch, so we can run additional tests in Google's codebase (to assess whether this change might potentially break any use-cases)?

Thank you.

**Pull request closed without merging**
