### PR TITLE
build(docs-infra): update fsevents to 1.2.4 to support node 10

### PR DESCRIPTION
**Pull request by clydin**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

fsevents 1.1.x does not fully support Node 10.

## What is the new behavior?

fsevents 1.2.4 provides prebuilt binaries for Node 10

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by gkalpak** [comment]
Can you please change the commit message to `build(docs-infra): ...`?
OOC, what command did you run to update the lockfile for `fs-events`?

**Comment by clydin** [comment]
message updated.

There's no nice yarn command (that I could find anyway).  My standard method to update transitive dependencies is to add a temporary `resolutions` field to package.json with the version of the package I would like to update, run `yarn`, then remove the `resolutions` field.

**Review by gkalpak — APPROVED** [review]
Not sure how I feel about the update approach, but `fsevents` only affects macOS, so I don't care that much 😛

**Comment by clydin** [comment]
You'll get a warning if the resolution version is incompatible with any package.  The only other alternative that worked reliably is to remove all the direct packages that have a transitive dependency on the package in question and then re-add them.

**Comment by clydin** [comment]
Reference yarn issue if curious: https://github.com/yarnpkg/yarn/issues/4986

**Review by IgorMinar — APPROVED** [review]

**Pull request closed without merging**
