### PR TITLE
docs: more precise docs for template statement syntax

### PR DESCRIPTION
**Pull request by thorn0**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JoostK** [comment]
I think there's a bit more to it than you currently suggest, although the proposed change is already getting us in the right direction.

Pipes are simple and are indeed not allowed.

The non-null assertion operator, _can_ be used in template statements (both in a _left-hand side_ (LHS) expression and in a _right-hand side_ (RHS) expression) with the exception that LHS expressions cannot end with it, whereas RHS expressions can. As an example, `selectedName = person.name!` is fine, but `selectedName! = person.name;` is not. The latter however would also not be valid TypeScript, so that is mainly a matter of grammar, not so much restrictions.

For the safe-navigation operator, it depends on where it is used. It is perfectly fine to use it in a RHS expression, which is basically something that evaluates to a value. It cannot be used, however, in LHS expressions, which are the ones that you can assign something into. For example, the statement `toggle.enabled = !toggle.enabled` has a LHS = `toggle.enabled` and a RHS of `!toggle.enabled`. The `?.` operator can be used in the RHS as that would just result in an `undefined` value, whereas it's illegal on the left as you can't assign into something that is not available.

So if anything, we should be mentioning the safe-navigation operator here, not the non-null assertion operation. @thorn0 If you think I'm misinterpreting something here please let me know.

**Comment by thorn0** [comment]
@JoostK Yeah, I included the non-null assertion operator there by mistake. Fixed.

As for `?.` in assignments, it's the same rules as in TS, so I don't think this needs additional explaining.

**Comment by JoostK** [comment]
@thorn0 Agreed, looks good now! Could you squash the two commits into one?

**Comment by thorn0** [comment]
@JoostK done

**Review by mhevery — APPROVED** [review]

**Pull request closed without merging**
