### PR TITLE
refactor(core): cross-realm signal symbol

### PR DESCRIPTION
**Pull request by ducin**
## PR Checklist

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Signals include a standard symbol. As a consequence, we're unable to identify a signal by a symbol e.g. in devtools. Hence, we need to do dirty workarounds like the following:

https://github.com/angular/angular/pull/53143/files#diff-6897e8af2831c16f93ae282279052dde82c55a9ab8f01484fa4107ab803cbcf0R31-R34

## What is the new behavior?

A cross-realm signal is used. Thanks to this, there'd be interoperability across realms, e.g. in angular devtools. See [crossing realms with symbols](https://2ality.com/2014/12/es6-symbols.html#crossing-realms-with-symbols).

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by AleksanderBodurri — COMMENTED** [review]
Thanks for the PR 🙏 Some thoughts on this solution,

Currently we have a public API `isSignal` https://angular.dev/api/core/isSignal. This API depends on the `SIGNAL` symbol in question.

Using `Symbol.for(...)` has an end result similar to adding the symbol to the public API, but it'd be in a bit of a grey area in terms of whether or not Angular developers could assume it's stable. Since it'd be exposed by Angular, there is an argument that it is a public API (similar to how no one explicitly imports the `ng` global, but it's still considered public). 

If this symbol is considered public, it would be very difficult to change our implementation of the `isSignal` framework API in the future (for example if we want to stop relying on this symbol).

External tools would have to implement their own `isSignal` logic based on this symbol. This again could cause breakages if how the framework identifies signals changes.

My first instinct for the problem described here would be a ng global debug API `ng.isSignal` that wraps the framework `isSignal`. This would allow the implementation details of the framework `isSignal` to continue to be flexible. It would also allow any changes to the implementation of how the framework identifies signals to propagate to debug API consumers (like Angular DevTools). All of this is under the assumption that this symbol is an implementation detail that we want to protect. @alxhub can speak more to that 🙏

**Comment by ducin** [comment]
@AleksanderBodurri correct me if I'm wrong, but in current shape the https://angular.dev/api/core/isSignal cannot be used within devtools, since it's another realm and unique symbols would be different.

**Comment by AleksanderBodurri** [comment]
@ducin the ng global debug APIs are brought in by the inspected Angular application (the same realm that the SIGNAL symbol exists in). These APIs are published to the window object, which allows Angular DevTools to access and use them to implement its features

**Comment by ducin** [comment]
Thanks for explanations 🙏 So if @alxhub is fine with extending the global, I could provide that :)

**Comment by alxhub** [comment]
@ducin that sounds good to me - we might even consider providing APIs that walk the signal graph to enumerate dependencies, etc.

**Comment by AleksanderBodurri** [comment]
Closing for https://github.com/angular/angular/pull/53269. Thanks @ducin for the work you did pushing this forward 🙏

**Pull request closed without merging**
