### PR TITLE
fix(platform-browser): reexport Ruler service

### PR DESCRIPTION
**Pull request by IgorMinar**

### CODE REVIEW

**Comment by mhevery** [comment]
We have decided to remove `Ruler` service, and so it is not part of the public API.

**Comment by brijeshamin** [comment]
@mhevery is there any alternative already available for Ruler service?

**Comment by mhevery** [comment]
For now just use the DOM directly. This will only be an issue if you run your app in  WebWorker

**Comment by zoechi** [comment]
See also https://github.com/angular/angular/issues/8509#issuecomment-223139233 I haven't found any info yet how to create and provide a custom renderer for different platforms (server, webworker, browser DOM thread)

**Pull request closed without merging**
