### PR TITLE
feat(testability): option to disable tree walking

### PR DESCRIPTION
**Pull request by goderbauer**

### CODE REVIEW

**Comment by hankduan** [comment]
I think the option makes more sense if it's called exactMatch or findInAncestor something.

**Comment by goderbauer** [comment]
renamed to findInAncestors as suggested.

**Comment by hankduan** [comment]
Can you rebase?

**Comment by goderbauer** [comment]
rebased done.

**Comment by hankduan** [comment]
merged via https://github.com/angular/angular/commit/8f5360c38700aa2f2245cc246c29dceccbbed4a4

**Pull request closed without merging**
