### PR TITLE
refactor(forms): remove deprecated symbols

### PR DESCRIPTION
**Pull request by JeanMeche**
Follow-up of #55698 to help remove the symbols from G3.

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
FYI, justification for symbols removal can be found in https://github.com/angular/angular/pull/55698#issuecomment-2099570051.

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
FYI, this PR is blocked by an internal cleanup in Google's codebase ([CL](http://cl/634466179)).

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by thePunderWoman — APPROVED** [review]
reviewed-for: fw-core, public-api

**Comment by AndrewKushnir** [comment]
[Global Presubmit](https://test.corp.google.com/OCL:634623025:BASE:634618324:1715919534545:e75fde87).

**Comment by AndrewKushnir** [comment]
**Caretaker note**: cleanup in g3 is completed, the TGP is "green", this PR is ready for merge.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit eddb4051b831a91141cc41ab260180036bfaf342.

**Pull request closed without merging**
