### PR TITLE
build: import in-memory-web-api project

### PR DESCRIPTION
**Pull request by crisbeto**
Moves the `angular-in-memory-web-api` project into the main repository in order to make it easier to maintain and release.

### CODE REVIEW

**Review by IgorMinar — CHANGES_REQUESTED** [review]
lgtm, except for two change requests

**Review by IgorMinar — APPROVED** [review]
LGTM! Thank you!

Reviewed-for: global-approvers, code-ownership, dev-infra

**Comment by IgorMinar** [comment]
please rebase the PR one (last) time. thanks!

**Comment by crisbeto** [comment]
Rebased and resolved the CI issues.

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:316481207:BASE:316481237:1592238647901:76ac97ea)

**Pull request closed without merging**
