### PR TITLE
docs: add clarity to parent calls an ViewChild

### PR DESCRIPTION
**Pull request by MrJithil**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #38302 

## What is the new behavior?
Added clarification to the statement

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Since this changes are not part of any packages, I didn't add the package name in the commit or PR title. Please guide me in case of any changes needed.

### CODE REVIEW

**Review by aikithoughts — APPROVED** [review]
LGTM from a docs perspective!

Reviewed-for: global-docs-approvers

**Comment by jelbourn** [comment]
@aikidave I don't think that the "globally" here is really accurate, or conveys the idea of the difference between the two patterns under discussion. Here's my best attempt at clarifying what the existing docs are trying to convey:

**You would use template variables when you want to reference something from another element in your template**. For example, the Angular Material menu API:
```html
<button [matMenuTriggerFor]="toppingsMenu">Select a topping</button>

<mat-menu #toppingsMenu>
  <button mat-menu-item>Cheese</button>
  <button mat-menu-item>Pepper</button>
  <button mat-menu-item>Onion</button>
</mat-menu>
```

Here I can create a template variable as a convenient/declarative way to grab a reference or value from one element (the menu panel) and use it somewhere else in the template (the button trigger). You can even use template variables to call a method on component/directive:
```html
<expand-collapse-panel #zippy>
  Some content in here
</expand-collapse-panel>

<button (click)="zippy.toggle()">Toggle</button>
```

By contrast, using `@ViewChild` can accomplish the same thing, just less directly. For example, you could do
```ts
export class SomeComponent {
  @ViewChild(ExpandCollapsePanel) zippy: ExpandCollapsePanel;
}
```
```html
<expand-collapse-panel>
  Some content in here
</expand-collapse-panel>

<button (click)="zippy.toggle()">Toggle</button>
```
So why would you want to use the latter approach? You would do this any time you want to **do something more complex than just referencing the value in the template**. For example, maybe you want to throw an error if your template doesn't have an `ExpandCollapsePanel`. Then you'd have to use `@ViewChild` and do something like this
```ts
export class SomeComponent {
  @ViewChild(ExpandCollapsePanel) zippy: ExpandCollapsePanel;
}

ngOnInit() {
  if (!this.zippy) {
    throw Error('SomeComponent must contain a ExpandCollapsePanel!');
  }
}
```

**Comment by aikidave** [comment]
@jelbourn And that's why I included you in the review! :) I only approved it because, from a documentation perspective, the sentence is correct, but I don't know know enough to say one way or the other if the term "globally" is applicable here. 

Perhaps I should have said: "Reads correct to me, but needs engineering approval." Sorry for the confusion!

**Comment by MrJithil** [comment]
> @aikidave I don't think that the "globally" here is really accurate, or conveys the idea of the difference between the two patterns under discussion. Here's my best attempt at clarifying what the existing docs are trying to convey:
> 
> **You would use template variables when you want to reference something from another element in your template**. For example, the Angular Material menu API:
> 
> ```
> <button [matMenuTriggerFor]="toppingsMenu">Select a topping</button>
> 
> <mat-menu #toppingsMenu>
>   <button mat-menu-item>Cheese</button>
>   <button mat-menu-item>Pepper</button>
>   <button mat-menu-item>Onion</button>
> </mat-menu>
> ```
> 
> Here I can create a template variable as a convenient/declarative way to grab a reference or value from one element (the menu panel) and use it somewhere else in the template (the button trigger). You can even use template variables to call a method on component/directive:
> 
> ```
> <expand-collapse-panel #zippy>
>   Some content in here
> </expand-collapse-panel>
> 
> <button (click)="zippy.toggle()">Toggle</button>
> ```
> 
> By contrast, using `@ViewChild` can accomplish the same thing, just less directly. For example, you could do
> 
> ```ts
> export class SomeComponent {
>   @ViewChild(ExpandCollapsePanel) zippy: ExpandCollapsePanel;
> }
> ```
> 
> ```
> <expand-collapse-panel>
>   Some content in here
> </expand-collapse-panel>
> 
> <button (click)="zippy.toggle()">Toggle</button>
> ```
> 
> So why would you want to use the latter approach? You would do this any time you want to **do something more complex than just referencing the value in the template**. For example, maybe you want to throw an error if your template doesn't have an `ExpandCollapsePanel`. Then you'd have to use `@ViewChild` and do something like this
> 
> ```ts
> export class SomeComponent {
>   @ViewChild(ExpandCollapsePanel) zippy: ExpandCollapsePanel;
> }
> 
> ngOnInit() {
>   if (!this.zippy) {
>     throw Error('SomeComponent must contain a ExpandCollapsePanel!');
>   }
> }
> ```

I don't think any potential difference in the reasoning above @jelbourn.

The first statement
> **You would use template variables when you want to reference something from another element in your template**.
this stands for, we can only use the local variable reference (as the name stands) could be only used in the view (or template).

and now another statement, 
> By contrast, using `@ViewChild` can accomplish the same thing, just less directly.
Here, why we able to directly use across the component? Because it's not a local variable to the view. It's a global variable to the class.

In my opinion, there is no wrong to use the term `globally`. If you really, think, the term needs to be changed, I would like you to come back with a proper statement which could be updated here.

**Comment by jelbourn** [comment]
@MrJithil  "Global variable" generally means "global to the program", not "global to the template"; it's not a term we would use to describe this pattern. I'd typically refer to to something like this as a "component property". 

@aikidave I know! I agree with the premise of the PR that the doc here could be a bit more clear, but I also don't have a great sense of how to actually describe the difference, so I'm hoping to we come up with an alternate edit.

**Comment by AndrewKushnir** [comment]
@aikidave could you please have a look at this PR again (when you get a chance) to see what the next step is? Should be put it on hold (close for now) and think of a way to rephrase the docs?

**Comment by aikidave** [comment]
@AndrewKushnir Let's go ahead and close for now.

**Pull request closed without merging**
