### PR TITLE
docs: missing item variable in structural directives example

### LINKED ISSUE #34762: Missing item variable / item is not defined
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
https://angular.io/guide/structural-directives

### Reproduction Steps**

**Go To:**
Writing your own structural directives
These microsyntax mechanisms are also available to you when you write your own structural directives. For example, microsyntax in Angular allows you to write <div *ngFor="let item of items">{{item}}</div> instead of <ng-template ngFor [ngForOf]="items"><div>{{**item**}}</div></ng-template>. The following sections provide detailed information on constraints, grammar, and translation of microsyntax.

**item is not defined**

missing item variable

## 🔥 Exception or Error
<pre><code>

</code></pre>

### PR DESCRIPTION
**Pull request by sacgrover**
PR Close #34762

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #34762

## What is the new behavior?

Expected content has been added

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by pkozlowski-opensource — APPROVED** [review]
Yep, this is good change: https://stackblitz.com/edit/angular-fsjcwt

**Review by kapunahelewong — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Thank you very much for this, @sacgrover!!

merge-assistance: Global approval for this docs-only change.

**Comment by sacgrover** [comment]
@Kara Why it's closed instead of merged?

**Comment by pkozlowski-opensource** [comment]
@sacgrover it _was_ merged as 843b3a2

**Comment by sacgrover** [comment]
Got it.. Thanks. I thought, It was closed by mistake.  Sorry!!

**Pull request closed without merging**
