### PR TITLE
fix(compiler): throw an error if variable with the same name is already defined.

### PR DESCRIPTION
**Pull request by Ne4istb**

### CODE REVIEW

**Comment by zoechi** [comment]
Does this also throw when the variable is added multiple times like

    <div *ngFor="#item of items" #somevar></div>

This is sometimes handy and didn't cause issues for me so far.

**Comment by Ne4istb** [comment]
@zoechi This change will not influence your case because it checks duplicates on template level, and ngFor creates separate templates. I've checked it locally :)

**Comment by zoechi** [comment]
@Ne4istb great, thanks for the feedback :)

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166566.
------------------------------------------------------------------------------------------------------------


[[880966d1139256982d1e435645abc678f22d9001-673074345]]

**Comment by mhevery** [comment]
I am sorry for the delay in getting back to you. 

Please add one more tests, which says that the same variables across different templates are OK.

```
<div #a>
  <span *ngIf="..." #a>OK</span>
</div>
```
The above is allowed.

**Comment by Ne4istb** [comment]
Will do soon

**Comment by Ne4istb** [comment]
@tbosch What kind of cleanup should be done?
P.S. presubmit.sh does not work now, i guess, because of changes in gulpfile.js. How can I run any code style validation?

**Comment by tbosch** [comment]
The test that @mhevery mentioned...

**Comment by tbosch** [comment]
Try to rebase, master should be good again.

**Comment by Ne4istb** [comment]
@tbosch 
test is already there with template
```html
<div #a><template #a><span>OK</span></template></div>
```

**Pull request merged**
