### PR TITLE
docs(common): add new date format example to documentation

### PR DESCRIPTION
**Pull request by luishcastroc**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

There's a missing example in the docs that solves an issue

Issue Number: #51348 

## What is the new behavior?
Example added to the docs

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi Luis, thank you for improving the docs. 

Can you fix the formating by running `yarn lint` ?

**Comment by luishcastroc** [comment]
> Hi Luis, thank you for improving the docs.
> 
> Can you fix the formating by running `yarn lint` ?
> 
> Edit: And also sign [the CLA](https://github.com/angular/angular/pull/51359/checks?check_run_id=15888289366).

ran the lint and nothing seems to be changing locally not sure if i'm missing anything

**Comment by luishcastroc** [comment]
> My bad, I was expecting it to fail but it's green ! Nonetheless, can you revert the formating changes as we're only modifying the docs here ?

done

**Review by AndrewKushnir — APPROVED** [review]
@luishcastroc thanks for improving Angular docs! 👍

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 328b3613b8f86ef911858f2c978ad53349d813da.

**Pull request closed without merging**
