### PR TITLE
docs: add message property to compose-message component

### PR DESCRIPTION
**Pull request by vovchik-manko**
docs: add message property to compose-message component

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
error occurs while running "ng serve --aot" (ERROR in src/app/compose-message.component.html(10,15): : Property 'message' does not exist on type 'ComposeMessageComponent'.)

Issue Number: N/A

## What is the new behavior?
result: Compiled successfully

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by vovchik-manko** [comment]
I signed a Contributor License Agreement (CLA)!

**Comment by brandonroberts** [comment]
Hi @vovchik-manko, will you update the commit message to follow the guidelines? `docs: add message property to compose-message component`

**Comment by brandonroberts** [comment]
@vovchik-manko Will you amend the git commit message to follow the message guidelines?

**Comment by vovchik-manko** [comment]
Hi @brandonroberts, I think it's done if I correctly understand you. I amended commit message and pushed changes here.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
@vovchik-manko That did it. I'll rerun the job again to see if it goes green. If not, I'll get some merge assistance for it.

Thanks!

**Pull request closed without merging**
