### PR TITLE
test(ivy): enable unit tests for @angular/animations

### PR DESCRIPTION
**Pull request by IgorMinar**
it turns out that we didn't even have test targets setup for @angular/animations....

### CODE REVIEW

**Comment by IgorMinar** [comment]
@alxhub is it really expected that we add tags to all of these targets? I think we should do the reverse - tag targets as "ivy-jit-todo" and "ivy-aot-todo".

**Comment by IgorMinar** [comment]
> @alxhub is it really expected that we add tags to all of these targets? I think we should do the reverse - tag targets as "ivy-jit-todo" and "ivy-aot-todo".

see #26471

**Review by matsko — CHANGES_REQUESTED** [review]
Why are there three commits to change one file?

**Review by matsko — APPROVED** [review]

**Comment by IgorMinar** [comment]
the other two are fixups

**Pull request closed without merging**
