### PR TITLE
docs(aio): update `live-example` docs in authors style guide

### PR DESCRIPTION
**Pull request by gkalpak**

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Is there much point in holding on to these unused images?

**Comment by gkalpak** [comment]
Probably not. There is a bunch of `**/_unused/**` images we could delete, but I never delete "marketing" stuff :grin:

**Comment by petebacondarwin** [comment]
Let's get @StephenFluin to check the `unused` folder and then delete it all.

**Comment by StephenFluin** [comment]
Looks like we made a couple new _unused folders for this? I see no reason to keep these files around. I dug a tiny bit for other unused folders but didn't find any. In general I'm in favor of deletion rather than moving to _unused.

**Comment by gkalpak** [comment]
💥Paf💥 - Gone!

**Pull request closed without merging**
