### PR TITLE
Provide support for SVG foreignObject by adding xhtml namespace

### PR DESCRIPTION
**Pull request by gionkunz**
This PR enables the use of elements with HTML namespace within SVG foreignObjects.

### CODE REVIEW

**Comment by tbosch** [comment]
Looks good, although not really standards compliant. The svg docs give this example for using html in svg:
```
<foreignObject width="100" height="50">
      <!-- XHTML content goes here -->
      <body xmlns="http://www.w3.org/1999/xhtml">
        <p>Here is a paragraph that requires word wrap</p>
      </body>
</foreignObject>
```

But let's keep this as is for now so that we have at least a working path on which we can improve later if needed...

**Comment by gionkunz** [comment]
Well the specification is not quite clear about the contents. Using a body as a root element within the foreignObject is just an example. They are talking about document fragments so I'd assume that we can refer to https://www.w3.org/2003/01/dom2-javadoc/org/w3c/dom/DocumentFragment.html as what is a valid document fragment. I'm using foreignObjects within my library https://github.com/gionkunz/chartist-js and so far all browsers are totally fine with foreignObjects containing no body element. Somehow we'd need to exclude this test for IE however, as they don't support foreignObject at all.

**Comment by btford** [comment]
This change needed to be reverted. We can probably merge this again independently, or once #6363 is resolved

**Comment by gionkunz** [comment]
@btford is there any action required from my side if #6363 is merged?

**Comment by vikerman** [comment]
Breaks google3. @tbosch - Here is the link for the failure  - https://test.corp.google.com/ui#cl=114446968

Please re-add the merge label once this is resolved.

**Comment by tbosch** [comment]
Sorry, don't have time to work on this right now...

**Comment by mhevery** [comment]
Hi @gionkunz, sorry for the long delay in getting this in, totally our fault. Can you try to rebase to the laste master?

If we don't get an update in a week, we will close this PR as obsolete.

**Comment by gionkunz** [comment]
Sure, will do. Cheers

**Comment by mhevery** [comment]
@gionkunz Any update on the rebase or should we just abandon this PR?

**Comment by gionkunz** [comment]
@mhevery Sorry I got a bit sidetracked from this issue. Please leave it open. I'll schedule some time for this next week. Cheers

**Comment by vicb** [comment]
@gionkunz any update ?

**Comment by gionkunz** [comment]
@vicb @mhevery I'm closing this PR in favor of #9458

**Pull request closed without merging**
