### PR TITLE
docs: add missing underline

### PR DESCRIPTION
**Pull request by musicq**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Missing underline of character 'secondary' on line 104

Issue Number: N/A

## What is the new behavior?
Character 'secondary' has been rendered the right way.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by musicq** [comment]
I signed it!

**Review by gkalpak — APPROVED** [review]
Good catch! Thx 👍

**Comment by gkalpak** [comment]
The Travis failures are not related to this PR 😕

**Comment by musicq** [comment]
@gkalpak Yep~ Not sure why cannot pass the tests.

**Comment by gkalpak** [comment]
The tests are probably related to something in master; not your PR.

**Pull request closed without merging**
