### PR TITLE
build: Fix version of image recommended Dockerfile

### LINKED ISSUE #48802: Dockerfile recommended in .devcontainer folder isn't correct. cim/node:14-browsers isn't available anymore on Dockerhub
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

It is impossible with recommended Dockerfile to use devcontainers as development environnement.

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

_No response_

### Please provide the environment you discovered this bug in (run `ng version`)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yatho**
Change tags used for recommended Dockerfile to permit to use devcontainers as new developper.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [X] Other... Please describe: Devcontainers doesn't work with recommended file currently

## What is the current behavior?

Issue Number: [48802](https://github.com/angular/angular/issues/48802)

## What is the new behavior?
From recommended Dockerfile, is it working correctly

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Since Node 14 is not active anymore, maybe bump directly to 16  ?

**Comment by yatho** [comment]
> Since Node 14 is not active anymore, maybe bump directly to 16 ?

16.13-browsers is enough ?

**Comment by JeanMeche** [comment]
Yes it's perfect !

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Can you please update the commit message to `build:` instead of `fix(devcontainers): ` as the latter is not valid. Also please squash the commit into a single one and add a closes note in the footer. Example `Closes #48803`. 

Kindly see: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit

**Review by alan-agius4 — APPROVED** [review]
LGTM, thanks

**Review by JeanMeche — APPROVED** [review]

**Review by devversion — APPROVED** [review]

**Comment by devversion** [comment]
Can you please address the CircleCI issue (see https://app.circleci.com/pipelines/github/angular/angular/55565) and rebase. looks great otherwise. Thanks!

**Comment by yatho** [comment]
> Can you please address the CircleCI issue (see https://app.circleci.com/pipelines/github/angular/angular/55565) and rebase. looks great otherwise. Thanks!

I tried to passed circle ci but without success.
Someone could be help me on this point ?

**Comment by devversion** [comment]
@yatho This may help: https://support.circleci.com/hc/en-us/articles/360008097173-Troubleshooting-why-pull-requests-are-not-triggering-jobs-on-my-organization-. We are good with this PR going forward anyway because it's a simple change which is not tested in CI anyway. Thanks for the PR

**Review by devversion — APPROVED** [review]
LGTM

Caretaker note: Please ignore that CI did not run here. This is a change not being tested by CircleCI  anyway

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit a63983d1bac4f78d4941b4f505754d449f9be2d2.

**Pull request closed without merging**
