### PR TITLE
 missing information about binding the occupation property to the UserComponent template

### PR DESCRIPTION
**Pull request by ashish-sharma4u**
added the binding of occupation property which was missing in UserComponent

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The documentation does not specify to bind the property occupation to UserComponent as a result even on providing input value in AppComponent nothing changes thus creating confusion for user

Issue Number: N/A

## What is the new behavior?
Added the missing information about binding the occupation property to the UserComponent template

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by sonukapoor** [comment]
@ashish-sharma4u Thanks for contributing. Can you please sign the CLA? You can find it here:

https://github.com/angular/angular/blob/main/CONTRIBUTING.md#cla

**Comment by ashish-sharma4u** [comment]
> @ashish-sharma4u Thanks for contributing. Can you please sign the CLA? You can find it here:
> 
> https://github.com/angular/angular/blob/main/CONTRIBUTING.md#cla

Hello, I have already signed the CLA. Although I did that after creating this request, for some reason it's showing here as not signed.

**Comment by MarkTechson** [comment]
LGTM

**Review by MarkTechson — APPROVED** [review]
LGTM

**Comment by dylhunn** [comment]
caretaker: Mark's approval is enough

**Comment by dylhunn** [comment]
Actually, looks like the CLA is not signed.

**Comment by ashish-sharma4u** [comment]
CLA was signed but for some reason, it still shows here as not signed. 
image

**Review by sonukapoor — APPROVED** [review]
CLA came through 👍

**Review by jessicajaniuk — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
@ashish-sharma4u Looks like you have a lint failure regarding your commit message. Can you fix it to match the requirements in CONTRIBUTING.md? You can do `git commit --amend` and change the message to add the docs prefix `docs: missing information...`. Once you do that, then force push to get the PR updated. Then you should be green.

**Comment by ashish-sharma4u** [comment]
> @ashish-sharma4u Looks like you have a lint failure regarding your commit message. Can you fix it to match the requirements in CONTRIBUTING.md? You can do `git commit --amend` and change the message to add the docs prefix `docs: missing information...`. Once you do that, then force push to get the PR updated. Then you should be green.

Done!

**Review by thePunderWoman — APPROVED** [review]
LGTM

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit 493c1922bfb2b8f3dc3c8edc513d693c4b9a3487.

**Pull request closed without merging**
