### PR TITLE
docs: update /deep/ to ::ng-deep

### PR DESCRIPTION
**Pull request by andyg3**
Since, for the time being, ::ng-deep is the preferred syntax, the example should be updated.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Example uses :host /deep/

Issue Number: N/A

## What is the new behavior?
Example uses :host ::ng-deep

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Hi @andyg3 could you do a `git commit --amend` and change the commit message to:

```
docs: update /deep/ to ::ng-deep in component styles example

Update example because ::ng-deep is the preferred syntax.

```

For reference, you're deleting the scope (`(docs-infra)`) and editing the body. Here are the parts to edit, highlighted:

image

Please tag me when you're ready. Thanks!

**Comment by andyg3** [comment]
@kapunahelewong I think I did it right.

**Comment by kapunahelewong** [comment]
Thank you, @andyg3, just one new thing - there are now three commit messages, but to merge, we need just one. Could you squash? Here's how I squash: [my gist on my own workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash).

**Comment by andyg3** [comment]
@kapunahelewong As you can see, this went off the rails FAST!
What am I doing wrong??

**Comment by andyg3** [comment]
@kapunahelewong It took me far too long to figure out the right way to squash, but I believe it's ready now.

**Comment by kapunahelewong** [comment]
Squashing isn't intuitive. It took me a while to get it, too. And look, you did it right! 🚀

Ok, so since there have been some commits to master in the meantime, could you rebase? (I think that will fix that saucelabs failure). Here's [my workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase). Just follow those steps exactly (replacing the feature branch name with your `patch-1` branch name) and if you have any questions, feel free to tag me and I'll help you. Thanks so much for your help in fixing this, @andyg3 🌟

**Review by mhevery — APPROVED** [review]

**Pull request closed without merging**
