### PR TITLE
fix(docs-infra): switch over to img[loading=lazy] for front page images

### PR DESCRIPTION
**Pull request by IgorMinar**
This should speed up the perceived loading latency as the image loading won't block rendering.

https://addyosmani.com/blog/lazy-loading/

Screen Shot 2020-01-22 at 7 01 30 AM

### CODE REVIEW

**Comment by IgorMinar** [comment]
hmm.. this doesn't seem to work in https://pr34900-985c0b4.ngbuilds.io/ in a recent browser that does support loading=lazy. no idea why.

**Comment by IgorMinar** [comment]
it seems to work correctly here: https://mathiasbynens.be/demo/img-loading-lazy I'm not sure what's the difference.

**Comment by petebacondarwin** [comment]
What do you expect to see? If the images are on the screen at start up they are not lazy loaded.
I also note that a certain number of the cat images get loaded any way.

Screenshot 2020-01-22 at 16 51 24

So perhaps we have so few images on the home page it does not bother waiting?

**Comment by IgorMinar** [comment]
maybe, but then why does lighthouse complain. Seems like there is a disconnect somewhere...

**Comment by IgorMinar** [comment]
to be clear, lighthouse complains about the images even with loading=lazy - can be seen when auditing https://pr34900-985c0b4.ngbuilds.io/

**Comment by gkalpak** [comment]
Based on [this][1] (and the corresponding [Chromium source code][2]), my understanding is that images "below the fold" will be loaded as soon as they reach 3000 to 8000 pixels from the viewport (depending on network type). Given that our home page is less than 2300px long, it is no surprise that all images are loaded asap.

I agree that Lighthouse should not be complaining though :grin:

[1]: https://web.dev/native-lazy-loading/#load-in-distance-threshold
[2]: https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/frame/settings.json5?l=971-1003&rcl=e8f3cf0bbe085fee0d1b468e84395aad3ebb2cad

**Comment by IgorMinar** [comment]
@gkalpak thank you! I ❤️ that you checked the chromium source code.

@addyosmani @housseindjirdeh is this something that should be fixed in Lighthouse audits? The issue is that lighthouse complains about us not deferring loading of offscreen images (see screenshot above), and the audit warning doesn't go away when we add `loading=lazy` to the problematic images.

**Comment by housseindjirdeh** [comment]
@IgorMinar I can see how that audit suggestion can be a little confusing if the loading attribute is being used correctly (`loading="lazy"`).

Opened an issue to discuss on the Lighthouse repo to discuss some possible ways to approach this: https://github.com/GoogleChrome/lighthouse/issues/10259

**Comment by housseindjirdeh** [comment]
[Fix](https://github.com/GoogleChrome/lighthouse/pull/10117) merged in Lighthouse repo. I tested locally on latest master and all the front page images are not flagged as expected 👍🏾.

Changes should be available in the next LH release (v5.7.0)!

**Comment by IgorMinar** [comment]
thank you @housseindjirdeh !

**Comment by IgorMinar** [comment]
@gkalpak I think this PR is still useful because it is explicit about our intent regardless of browser heuristics. Can you please review?

**Review by gkalpak — APPROVED** [review]
👌

**Comment by jessicajaniuk** [comment]
@IgorMinar What's the status of this PR?

**Comment by gkalpak** [comment]
This is still relevant and should be good to go. I've rebased it on latest master and resolved conflicts.

**Pull request closed without merging**
