### PR TITLE
docs(aio): remove http from tutorial pending rewrite

### PR DESCRIPTION
**Pull request by juleskremer**

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
didn't you also want to delete the actual md file? if we keep it around, dgeni will still find it and include it in the search index

**Comment by juleskremer** [comment]
@IgorMinar yes, here it is.

**Comment by Foxandxss** [comment]
Shouldn't be there a warning instead of a comment? "Sorry, next part is being rewritten, come back soon"

**Comment by brandonroberts** [comment]
Closing as no longer applicable.

**Pull request closed without merging**
