### PR TITLE
refactor(core): add `ENABLE_ROOT_COMPONENT_BOOTSTRAP` token

### PR DESCRIPTION
**Pull request by alan-agius4**
Introduced the `ENABLE_ROOT_COMPONENT_BOOTSTRAP` token to control the bootstrapping of components during application initialization. This token is utilized by the Angular CLI in the `@angular/ssr` package, particularly during server-side rendering (SSR) when extracting routes.

When set to `false`, this token prevents the root component from being bootstrapped during SSR's route extraction phase, which is crucial for efficiently extracting routes without triggering component initialization. This mechanism separates the concerns of route extraction and component bootstrapping during SSR rendering, optimizing performance.

If not provided or set to `true`, the default behavior of bootstrapping the root component(s) during initialization is maintained.

Context: https://github.com/angular/angular-cli/issues/29085

### CODE REVIEW

**Comment by alan-agius4** [comment]
@AndrewKushnir PTAL.

**Comment by alan-agius4** [comment]
Following a convo with @pkozlowski-opensource we are going with a workaround in the CLI for now https://github.com/angular/angular-cli/pull/29101

**Comment by alan-agius4** [comment]
Turns out we need this approach due to https://github.com/angular/angular-cli/issues/29131

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 9e0b50b4654ec35b702db6af077e68fb45ac4d24.

The changes were merged into the following branches: main

**Pull request closed without merging**
