### PR TITLE
docs: update toh-pt5.md

### PR DESCRIPTION
**Pull request by saikartheekb**
Fixed a typo in the file name 'app-routing.module.ts' in toh-pt5.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@saikartheekb thanks for creating the PR.

Could you please sign the CLA (as described in https://github.com/angular/angular/pull/49307#issuecomment-1453465166)? Also could you please update the commit message to start with `docs: ` (i.e. `docs: update toh-pt5.md`), so that the lint CI job becomes "green"?

**Comment by saikartheekb** [comment]
> @saikartheekb thanks for creating the PR.
> 
> Could you please sign the CLA (as described in [#49307 (comment)](https://github.com/angular/angular/pull/49307#issuecomment-1453465166))? Also could you please update the commit message to start with `docs: ` (i.e. `docs: update toh-pt5.md`), so that the lint CI job becomes "green"?

I have signed the CLA and updated the commit message.

**Comment by AndrewKushnir** [comment]
@saikartheekb thanks for signing the CLA. Could you please also update the commit message (I still see the old message)?

**Comment by saikartheekb** [comment]
> @saikartheekb thanks for signing the CLA. Could you please also update the commit message when you get a chance (I still see the old message)?

@AndrewKushnir  Updated the commit header and commit message.

**Comment by AndrewKushnir** [comment]
@saikartheekb it looks like you've updated the PR description, but the commit message remains the same (see Commits tab). Could you please apply the same changes to the commit message as well (`git commit --amend`)?

**Comment by saikartheekb** [comment]
> @saikartheekb it looks like you've updated the PR description, but the commit message remains the same (see Commits tab). Could you please apply the same changes to the commit message as well (`git commit --amend`)?

@AndrewKushnir It is done

**Review by AndrewKushnir — APPROVED** [review]
@saikartheekb thanks for improving Angular docs!

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 7749b19e90f6b36ece36b431531f05e2207ca2b4.

**Pull request closed without merging**
