### PR TITLE
fix(animations): cleanup DOM elements when the root view is removed

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
- [x] Bugfix

### CODE REVIEW

**Comment by arturovt** [comment]
This is a replacement of this PR (https://github.com/angular/angular/pull/39982).

@atscott cc. There were some presubmit failures, but you mentioned in that comment that you manually fixed some issues (https://github.com/angular/angular/pull/39982#issuecomment-752202977). Could you try to re-run the presubmit?

**Comment by atscott** [comment]
triggered [global tests](https://test.corp.google.com/ui#id=OCL:359614875:BASE:359535995:1614292717370:e1401d2a) to see what still needs to be fixed (if any).

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
Global tests are all green. This should be good to go now 👍

**Comment by arturovt** [comment]
@atscott oh great :+1: 

Well, I see the _Presubmit Failed_ :smile:

**Comment by atscott** [comment]
> @atscott oh great 👍
> 
> Well, I see the _Presubmit Failed_ 😄

There were some unrelated failures. I just need to force it green :)

**Review by crisbeto — APPROVED** [review]
LGTM

**Review by mhevery — APPROVED** [review]

**Comment by atscott** [comment]
After a bit more investigation, the failure was legitimate - the SSR code was configured to destroy the platform before returning the generated HTML which resulted in the Angular elements being cleaned up as well. I missed this in the global tests because I hadn't configured them to run with Ivy enabled.
We'll have to re-open this PR, rerun the tests, and evaluate what this change means for SSR clients -- it could be quite a bit more breaking than anticipated if others have their server rendering set up in a similar way.

**Pull request closed without merging**
