### PR TITLE
docs: fix duplicate in CHANGELOG

### PR DESCRIPTION
**Pull request by wellWINeo**
Fix duplicate in CHANGELOG.md under "Compiler" section.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Brandinga** [comment]
reverts are not considered in the changelog :(

this fix never landed / got 2 times reverted
so it should deleted completly: see https://github.com/angular/angular/pull/42608

**Review by josephperrott — CHANGES_REQUESTED** [review]
LGTM

**Review by josephperrott — APPROVED** [review]
LGTM

Accidentally checked the wrong box last time.

**Comment by alxhub** [comment]
This PR was merged into the repository by commit cac4d0527eb304845699bfa6fddc254161c4a8e5.

**Pull request closed without merging**
