### PR TITLE
docs: migrate security guide and example to standalone

### PR DESCRIPTION
**Pull request by bencodezen**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by MarkTechson — APPROVED** [review]
LGTM

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Review by twerske — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit dad47bb7206982fd5658050f4d14d86a40f3486e.

**Pull request closed without merging**
