### PR TITLE
feat(upgrade): use offline compiled components with ng-upgrade

### PR DESCRIPTION
**Pull request by thelgevold**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
I am proposing this as a solution to https://github.com/angular/angular/issues/10139
The problem I am trying to solve is that ng-upgrade does not benefit from offline compiled components. Instead, any template or css file is requested during bootstrap. I think it would be beneficial if we could leverage the pre-compiled templates even during ng-upgrade 

**What is the new behavior?**
I have proposed a solution where I make use of the ngComponentFactory to benefit from the pre-compiled code

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
@mhevery @tbosch @robwormald  Please let me know if this seems like a reasonable suggestion.

P.S in order to unit test this I checked in a pre-compiled version and the original component under a mock folder. This might not be ideal and it would probably be better to generate the ngFactory file on the fly.  

Thanks,
-Tor

### CODE REVIEW

**Comment by thelgevold** [comment]
Seeing the build error `'public-api:enforce' errored after 4.99 s`
Is this from changing the signature of a public method?

**Comment by IgorMinar** [comment]
This approach doesn't look right to me because ComponentFactories should not be something that app developers have to work with.

Also once AppModules/NgModules land the unit of compilation will be component that is part of a module, so we need to provide the module context to the ngUpgrade as well.

// @mhevery

**Comment by thelgevold** [comment]
@IgorMinar My understanding of this might be outdated. This is show I've been importing components before downgrading though. How should we feed the offline compiled components to ngUpgrade?

**Comment by IgorMinar** [comment]
Likely via ComponentFactoryResolver - but I haven't thought about this enough.

Is your goal to offline compile the whole Angular 2 part of the app, bundle it up and then use it within Angular 1? Or what strategy are you thinking about?

**Comment by thelgevold** [comment]
@IgorMinar Yes, my approach so far has been to first offline compile the entire A2 part.

This is kind of following the original offline compiler sample, so it might be outdated. 

I end up with code like this
```
import { DemoNgFactory } from './demo.ngfactory';
import { FriendNgFactory } from './friend.ngfactory';

const upgradeAdapter = new UpgradeAdapter();

angular.module('a1').directive('tgh', upgradeAdapter.downgradeNg2Component(DemoNgFactory));
angular.module('a1').directive('friend', upgradeAdapter.downgradeNg2Component(FriendNgFactory));

upgradeAdapter.bootstrap(document.body, ['a1'])
```

The next step I do is bundle the whole thing up into a single file using systemjs builder.

Are you saying this API is too low level?

**Comment by thelgevold** [comment]
My tweak is to allow factories to be passed into `downgradeNg2Component `, so that the pre-compiled code can be used directly - without requesting external templates etc from within the bootstrap.

**Comment by thelgevold** [comment]
Based on feedback from @IgorMinar and @robwormald I am closing this PR.
I like your direction of not exposing ngFactories much better than my proposal :-)

Thanks!

**Pull request closed without merging**
