### PR TITLE
refactor(router): clean up internal hooks

### PR DESCRIPTION
**Pull request by atscott**
* beforePreactivation hook is unused
* The only place that uses afterPreactivation does not use the arguments

Not to say we won't want to provide hooks similar to this in the future,
but the current state is over-engineered for what it's being used for.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
Looks great! Awesome to see the size decrease as well 👍

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: size-tracking

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: size-tracking

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

reviewed-for: size-tracking

**Comment by AndrewKushnir** [comment]
@atscott FYI there was a problem merging this PR to 12.2.x, so I merged it to 13.0.x and master. If this change needs to go into 12.2.x, could you please create a new PR that would target that branch?

**Pull request closed without merging**
