### PR TITLE
fix(upgrade): make ng1 typings compatible with older versions

### LINKED ISSUE #26420: Angular 6 (6.0.7+) @angular/upgrade: Interface 'IAnnotatedFunction' incorrectly extends interface 'Function'.
## I'm submitting a...

<pre><code>
[X ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The following error is thrown during TS compile from 6.0.7 through 6.1.10:

> node_modules/@angular/upgrade/static/src/common/angular1.d.ts(10,18): error TS2430: Interface 'IAnnotatedFunction' incorrectly extends interface 'Function'.
  Types of property '$inject' are incompatible.
    Type 'ReadonlyArray<string>' is not assignable to type 'string[]'.
      Property 'push' is missing in type 'ReadonlyArray<string>'.

This error does not occur when using version up to, and including 6.0.6.

## Expected behavior

No TS compile errors occur for any @angular packages in versions after 6.0.7.

## Minimal reproduction of the problem with instructions

Compile a hybrid angular application using Typescript 2.9.2 and the following values in package.json:
"@angular/animations": "^6.1.10",
    "@angular/common": "^6.1.10",
    "@angular/compiler": "^6.1.10",
    "@angular/core": "^6.1.10",
    "@angular/forms": "^6.1.10",
    "@angular/http": "^6.1.10",
    "@angular/platform-browser": "^6.1.10",
    "@angular/platform-browser-dynamic": "^6.1.10",
    "@angular/platform-server": "^6.1.10",
    "@angular/router": "^6.1.10",
    "@angular/upgrade": "6.0.7"

## What is the motivation / use case for changing the behavior?
Upgrading to Angular 6.

## Environment

<pre><code>
Angular version: X.Y.Z

This also appears to occur when using @angular/upgrade 6.1.10.

Browser:
N/A
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Windows

Others:
IDE: VS Code
Package Manager: Gulp 3.9.1, Gulp CLI 2.0.1

</code></pre>

### PR DESCRIPTION
**Pull request by Andy-Blatecky**
Make angular1 typings compatible with older versions

closes #26420

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Allows angular1.d.ts to compile without error when using angular 1.5.x.

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 26420

## What is the new behavior?
Allows angular1.d.ts compile without error when using angular 1.5.x.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx! Can you also make sure CI is happy (e.g. you need to run `gulp format:changed` to make the linter happy)?

**Comment by gkalpak** [comment]
Thx for making the changes, @Andy-Blatecky. ❤️

I've squashed the commits (and tweaked the message slightly) and also moved the comment closer to `$inject` (since that is what it refers to).
As soon as CI is happy, I will mark it for merging.

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Note to caretaker: Requires g3sync (I guess).

**Comment by kara** [comment]
[presubmit](http://test/OCL:219824247:BASE:219824348:1541180816024:57e19d63)

**Comment by kara** [comment]
@Andy-Blatecky Is there a reason there aren't any tests for this change? Could we add a test in a follow-up?

**Comment by gkalpak** [comment]
@kara: What kind of test? This is a types-only change.

For context:
The previous types were not compatible with an older version of `@types/angular` (which we don't use).
The new types use conditional types to remain compatible with the latest `@types/angular` version (we use), but also be compatible with older `@types/angular` versions that people might be using in their apps.

The fact that TS can still build our code is the "test" that proves the change doesn't break compatibility with latest `@types/angular`. Maybe we could have an integration test that verifies the new types are also compatible with older `@types/angular` versions, but that is not worth the trouble imo.
(Happy to create such an integration test, though, if you feel otherwise.)

**Comment by kara** [comment]
Okay, that makes sense. For context, this PR came up in our weekly release review, where we check that each change has tests and docs. Since this didn't have tests or any explanation, we wanted to double-check.

**Comment by rhillefeld** [comment]
Thank you for addressing this issue. We hit this as we upgraded from Angular 5 -> 6 -> 7. We still have some remnants of AngularJS and need this fix. We will work around it for now, but I'm wondering if you have a sense for which release this patch will make it into?
Thanks again!

**Pull request closed without merging**
