### PR TITLE
fix(docs-infra): removed duplicated style in aio examples

### PR DESCRIPTION
**Pull request by ilmalte**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

Issue Number: N/A

## What is the new behavior?
I have found duplicated style definitions in few examples scss files (duplicateProperties).

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@ilmalte Looks like the commit message needs some tweaking. I think it's just missing a body. Could you update that?

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

Thanks for the fix!

**Comment by ilmalte** [comment]
@jessicajaniuk thank you the review! 
It looks like that ci/circle: lint is failing because of the merge _commit message header does not match the expected format_.
Does I need to rebase or revert my merge commit?😊

**Comment by jessicajaniuk** [comment]
@ilmalte You can just do a `git commit --amend` and update the commit message before re-pushing. You shouldn't have to revert anything. The linter requires the commit to have the header, which you currently have just fine, and then at least 20 characters of a body. So do something like: 
```
fix(docs-infra): removed duplicated style in aio examples

[put your body here]
```

That should resolve it.

**Comment by ilmalte** [comment]
I pulled another PR #45157 because I have not been able to change old commit messages.

**Pull request closed without merging**
