### PR TITLE
docs: Angular + NgRx book by the asian BPB Publications

### PR DESCRIPTION
**Pull request by codef0rmer**
Beginners, as well as Experienced Angular developers who want to write sustainable Angular applications over time, will benefit from this book. This book is for anyone interested in State Management with NgRx in Angular.

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by codef0rmer** [comment]
Thanks for approving @petebacondarwin 👍

**Comment by AndrewKushnir** [comment]
Hi @codef0rmer,

I've rebased your PR and it looks like there is a couple things to cleanup:

- there is a comma at the end of the object that you've added, I believe this is causing some CI jobs to fail
- the `lint` CI job is failing since commit message doesn't contain a scope (i.e. "docs: " in front of the message). Could you please update commit message (`git commit --amend`) to start commit message with `docs: ` and also please make the lines in commit message less than 120 chars

Once the above mentioned items are resolved, the CI should pass and we'll be able to add your PR to the merge queue.

Thank you.

**Comment by codef0rmer** [comment]
@AndrewKushnir Done. Thanks for the shout out.

**Pull request closed without merging**
