### PR TITLE
docs: fix cli link

### PR DESCRIPTION
**Pull request by jerone**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Link for Angular CLI doesn't work.
image

Issue Number: N/A

## What is the new behavior?
Link for Angular CLI works.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
* https://angular.io/guide/glossary#workspace

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Good catch! Thx, @jerone :+1:

Reviewed-for: global-docs-approvers

**Comment by gkalpak** [comment]
For reference, you can see the [current (broken) behavior][1] versus the [fixed version][2].

[1]: https://angular.io/guide/glossary#workspace
[2]: https://pr43085-8e58ffa.ngbuilds.io/guide/glossary#workspace

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Pull request closed without merging**
