### PR TITLE
build(core/labs):  Set up `@angular/core/labs` package for experimentation

### PR DESCRIPTION
**Pull request by mhevery**
This change creates a new sub-package `@angular/core/labs` the purpose of which is to allow us to have experimental API in a way where the community can try them out without us being committed to supporting them long term.

Before the developer can use any of the APIs in the `@angular/core/labs` package they have to agree to the conditions which are clearly spelled out in both the way of agreeing as well as a warning in the console.

```
import {iWantToUseExperimentalAPIs} from `@angular/core/labs`

iWantToUseExperimentalAPIs({
  iUnderstand: ['not ready for production', 'unstable API']
})
```

The purpose of the above code is to make it very clear that the developer is about to use experimental APIs which should not be used in production.

Additionally this change sets up testing harness for `@angular/core/labs` where the specs are next to the actual code to simplify the directory structure.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by IgorMinar — CHANGES_REQUESTED** [review]
We should merge this with https://github.com/angular/angular/pull/26003

The two PRs use different designs to create the labs. The original PR follows a design that ahs gone through several iterations so it would be great if you could capture why that design is inferior to the one used in this PR.

**Comment by IgorMinar** [comment]
Also, is it intentional that this PR is in a draft state but has reviewers assigned? What kind of feedback are you looking for from the reviewers on a PR that is not ready yet? Reviewing PRs take a lot of time so it would be great if you set the expectations upfront so that the reviewers know how deep they should go.

Thanks for the PR description that one is very helpful, it just doesn't answer what state this PR is in.

**Comment by mhevery** [comment]
> Also, is it intentional that this PR is in a draft state but has reviewers assigned? What kind of feedback are you looking for from the reviewers on a PR that is not ready yet? Reviewing PRs take a lot of time so it would be great if you set the expectations upfront so that the reviewers know how deep they should go.

I think the short answer is that I don't know how to use Draft button. My thinking was that this is more of a discussion rather than ready to be merged hence I wanted to  signal with the Draft.

**Comment by mhevery** [comment]
> The two PRs use different designs to create the labs. The original PR follows a design that ahs gone through several iterations so it would be great if you could capture why that design is inferior to the one used in this PR.

The biggest difference I see is:
1. is it `@angular/core/labs` or `@angular/labs/core`. I know the design doc says `@angular/labs/core`, but I think `@angular/core/core` makes more sense from the build file organization.
2. I also suggest rules for test files unification in same directory
3. propose a way to agree to a disclaimer.

**Comment by robwormald** [comment]
my PR used `@angular/labs/package-name` for a few reasons:
- it required an explicit opt-in package install of `@angular/labs` vs experimental APIs being added to existing packages.
- `@angular/labs` package easier to exclude from builds / CI
- easy promotion / merging to top-level packages, eg `@angular/labs/http-client` => `@angular/http-client`
- potential for automated releasing outside of normal release cycle

This was mostly set up for feature package development, like a unified `@angular/forms` rewrite or a standalone animations engine. For experimental core / Ivy APIs, IMHO we should decide where we want to be in a couple of years in terms of package structure, especially the dependencies between the `@angular/core`, `@angular/platform-*`, and `@angular/common` packages and stuff like `BrowserModule`

**Pull request closed without merging**
