### PR TITLE
Fix docs in example for @Output

### PR DESCRIPTION
**Pull request by adammartin1981**
Minor issue found when implementing the example given

### CODE REVIEW

**Comment by adammartin1981** [comment]
I've signed it.

**Comment by btford** [comment]
@adammartin1981 can you please follow the commit message guidelines? https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

Otherwise looks good.

**Comment by alxhub** [comment]
Hello @adammartin1981, please reword your commit to follow the guidelines that @btford mentioned.

Thanks!

**Comment by mhevery** [comment]
Obsolete

**Pull request closed without merging**
