### PR TITLE
Ngtsc much speed such fast

### PR DESCRIPTION
**Pull request by JoostK**
It is advised to review per commit.

### CODE REVIEW

**Review by alxhub — APPROVED** [review]
Very approve, so excite!

**Comment by alxhub** [comment]
[Presubmit](http://test/OCL:285239720:BASE:285239782:1576180702868:159680ea)
[Ivy Presubmit](http://test/OCL:285239720:BASE:285239782:1576180702795:75785577)

**Comment by alxhub** [comment]
merge-assistance: i am the approver for all code within!

**Review by petebacondarwin — COMMENTED** [review]
LGTM! Good sleuthing @JoostK

**Pull request closed without merging**
