### PR TITLE
refactor: replace deprecated String.prototype.substr()

### PR DESCRIPTION
**Pull request by CommanderRoot**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) or [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) which work similarily but aren't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

## What is the new behavior?

Everything should behave the same way

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by dgp1130 — APPROVED** [review]
Reviewed-for: fw-i18n

**Review by atscott — APPROVED** [review]
reviewed-for: fw-router

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

reviewed-for: fw-core, fw-common, fw-animations, fw-testing, fw-upgrade, docs-getting-started-and-tutorial, fw-platform-server

**Comment by dylhunn** [comment]
@alxhub @jelbourn Since this PR touches so many areas, a global approval would likely be appropriate?

Also, I have started a presubmit.

**Review by dylhunn — APPROVED** [review]

**Comment by dylhunn** [comment]
g3 presubmit is green.

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: global-approvers

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 4ddcf81e610a518618c3b914335be7bd79974bf2.

**Pull request closed without merging**
