### PR TITLE
chore(*): call super() in subclasses before using `this`

### LINKED ISSUE #844: Use super() only in subclasses, and before any use of `this`
Blocks #733 as Traceur is now enforcing these rules correctly

### PR DESCRIPTION
**Pull request by caitp**
It is necessary to do this because of the changes to class semantics (mostly detailed in https://github.com/tc39/ecma262/blob/master/workingdocs/ES6-super-construct%3Dproposal.md) --- particularly step 5. These changes are now enforced by traceur (since https://github.com/google/traceur-compiler/commit/6d63b73c9ec3011fbe1790c4ef25d2e00928b469)

Closes #844

### CODE REVIEW

**Comment by caitp** [comment]
PTAL, it should be a pretty trivial fix --- I've tested against upstream traceur (including unit tests), but I don't want to pull in the updated version until it's released

**Comment by caitp** [comment]
blocked on updating traceur in es6-module-loader and other dependencies ._.

**Comment by caitp** [comment]
Blocked on https://github.com/google/traceur-compiler/pull/1791 + another release

**Comment by mhevery** [comment]
Looks like dart does not like this. What is the next step?

**Comment by caitp** [comment]
waiting on the publishing of 0.0.87, and getting that into the projects which require traceur with strict version requirements. The reason it fails is a package was using a different version than the one explicitly installed, which does not implement the fix

**Comment by caitp** [comment]
PTAL --- these are passing js and dart tests locally, but it likely won't fix webkit just yet (haven't tested yet)

**Comment by caitp** [comment]
fails the one e2e test for sourcemapping, might need a little fix

**Comment by caitp** [comment]
bahh whatever

**Comment by mhevery** [comment]
Wait I am confused. Looks like you closed this without merging. What happened?

**Comment by caitp** [comment]
merge conflicts at the last minute, and no idea how to fix the failing e2e test, so I give up on it

**Pull request closed without merging**
