### PR TITLE
docs(router): use pipe in activatedRoute example

### PR DESCRIPTION
**Pull request by frederikprijck**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Copying the example, mentioned at Activated Route (https://angular.io/api/router/ActivatedRoute), to Stackblitz doesn't compile: https://stackblitz.com/edit/angular-x7pbeb?file=src%2Fapp%2Fhello.component.ts

That's because the example does not use `.pipe`.

Issue Number: N/A

## What is the new behavior?

I've updated the example to include `pipe`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by frederikprijck** [comment]
It looks like the CI errors are not related to this PR.

**Review by gkalpak — APPROVED** [review]
Good catch! Thx :+1:

<sub>It would be great if someone wanted to convert these hard-coded code examples to snippet extracts from actual mini-apps (as most code examples).</sub>

**Comment by gkalpak** [comment]
merge-assistance: This is a docs only change and I am using my global approval super-power.

**Comment by frederikprijck** [comment]
@gkalpak as mentioned offline, ill take a stab at reworking this to use a miniapp in a follow up pr so they example is compiled!

**Pull request closed without merging**
