### PR TITLE
docs(animations): API doc misspelled word

### PR DESCRIPTION
**Pull request by jasonhodges**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: documentation correction
```

**What is the current behavior?** (You can also link to an open issue here)
currently [here](https://angular.io/docs/ts/latest/api/animations/index/group-function.html) it says _at different statrting/ending times_

**What is the new behavior?**
should say _at different starting/ending times_

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
LGTM except for the commit messages (which also break CI). Can you please merge the commits and use `animations` for subject?

**Comment by wardbell** [comment]
Also overlaps with #16508 which is approved for merge. I'd close this one as a duplicate but you caught a second error.

For full credit, please correct the PR title, the commit message, and squash.

**There is good reason for you confusion**

The _guide_ is called "animations" (plural). The _Angular module_ is called "animation".  By beginning your commit with "docs(animations)", you're telling us that you're making a change to the _Angular module_.  But you are not. 

You're making a change to the documentation. _Those_ kinds of changes must begin "docs(aio): ".In your case it might be something like "docs(aio): animations typos fixed".

How the world is going to understand these distinctions is beyond me.

**Comment by jasonhodges** [comment]
@wardbell sorry I've gotten these two changes into a git mess. Working on it

**Comment by wardbell** [comment]
Thanks. Now moving to the right person.

**Review by matsko — APPROVED** [review]

**Pull request merged**
