### PR TITLE
docs: clarify sentence in lifecycle hooks doc

### PR DESCRIPTION
**Pull request by jordan-amman**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Hard to understand sentence in the documentation.
Issue Number: N/A

## What is the new behavior?
Easier to understand sentence.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by jordan-amman** [comment]
@kapunahelewong This is my new pull request, thanks again! [:

**Review by kapunahelewong — APPROVED** [review]
LGTM. Thank you so much, @jordan-amman!!

**Comment by kapunahelewong** [comment]
Hi Caretaker, I think the failure isn't related to the changes in this PR. Can you help us get it green? Please ping me if I can help. Thank you!

**Comment by kapunahelewong** [comment]
Oh, I see what's happening here, @jordan-amman - the reason it's failing is because the original branch is behind. If you can get it up to date by rebasing, so that it will pass, we can get it merged. Here's where I see that it's behind: 
image

So to get that up to date, where your branch should just be one commit ahead (and zero behind) master, try [my rebasing steps](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase). Let me know when you're ready, ok? :)

**Comment by jordan-amman** [comment]
@kapunahelewong So when I tried git pull upstream master from my master local branch, it's giving me this error: 
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by kapunahelewong** [comment]
Ah, I see. So there are two things here:

1. You did it! It looks good. Your branch is only one commit ahead of angular master, which is exactly what it should be. 🎉Let's merge this!

2. The other question you had about upstream master means that your system is calling this  angular repo something other than upstream. You can see this with `git remote -v` or `git remote --v` (both work on Mac, which is what I have). You're looking for the one that is:
```
https://github.com/angular/angular.git
```

So, for example, this is the output of `git remote --v` on my machine:

```
origin	https://github.com/kapunahelewong/angular.git (fetch)
origin	https://github.com/kapunahelewong/angular.git (push)
upstream	https://github.com/angular/angular.git (fetch)
upstream	https://github.com/angular/angular.git (push)
```

`origin` for me is my fork on GitHub. `upstream` is angular/angular (here). You can name these anything you like and you can have a number of them pointing to different remotes (repos out on github). I hope this helps. 😊

**Comment by kapunahelewong** [comment]
Caretaker, this is a docs only change. Please let me know if you need me. Well done, @jordan-amman!!!🌟

**Comment by jordan-amman** [comment]
@kapunahelewong That makes complete sense to me, and I added the upstream remote link now. Thank you for all of your help you have been so helpful with my first pull request and I can't wait to contribute more to open source projects. You helped clear up a lot of confusion with git as well! [:

**Comment by kapunahelewong** [comment]
This makes me so happy, @jordan-amman!! 🌺

**Pull request closed without merging**
