### PR TITLE
refactor(http): deprecated symbol used

### PR DESCRIPTION
**Pull request by SrdjanMilic**
Support for passing an error value to "throwError" method will be removed in v8 of rxjs. More info at https://rxjs.dev/api/index/function/throwError#throwerror

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@SrdjanMilic It looks like there's one very relevant failing tests in this PR. Please take a look when you have a chance.

**Comment by SrdjanMilic** [comment]
I've just notice that there are two unused methods in that same file `getConfig_2` and `getConfig_3`, last edited at 2018 and marked by IntelliJ:

Screenshot from 2022-01-16 13-46-34

**Comment by alxhub** [comment]
@SrdjanMilic instead of adding a second commit to fix the styling issues, please squash all such changes into the single original commit.

**Comment by SrdjanMilic** [comment]
@alxhub After squashing, I've ended up with git tree like in the picture bellow:
image

I'm not sure if this is OK to be pushed?
image

**Comment by SrdjanMilic** [comment]
OK. So here is the new PR: https://github.com/angular/angular/pull/44985  

Please, take a look at discussion about the same error with another PR here: https://github.com/angular/angular/pull/44985

**Comment by AndrewKushnir** [comment]
Closing this PR in favor of https://github.com/angular/angular/pull/44985.

**Pull request closed without merging**
