### PR TITLE
docs: add Jeff Cross to GDE page

### PR DESCRIPTION
**Pull request by jeffbcross**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Jeff does not exist on GDE page.

Issue Number: N/A

## What is the new behavior?

Jeff does exist on GDE page.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This drastically increases the quality beard content of the GDE page.

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]

**Comment by brandonroberts** [comment]
@jeffbcross will you remove the `(aio)` scope from the commit message?

**Comment by jeffbcross** [comment]
@brandonroberts will do

**Comment by jeffbcross** [comment]
@brandonroberts done!

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Caretaker note: This is a docs only change and I am using a global approval. The `ci/angular: size` job didn't trigger even after the `test_ivy_aot` job completed.

**Pull request closed without merging**
