### PR TITLE
docs: add learning resource

### PR DESCRIPTION
**Pull request by dymafr**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ x ] Other... Please describe: learning resource

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by dymafr** [comment]
@googlebot I signed it!

**Review by StephenFluin — APPROVED** [review]
The change looks great. You'll need to make sure the commit message matches our guidelines.

**Comment by kapunahelewong** [comment]
Hi @dymafr, here are my [notes on amending a commit](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) if you'd like to refer to them. Let me know if you have any questions. Will you ping me when you're ready?

**Comment by dymafr** [comment]
Hi @kapunahelewong! Hope it's now ok. Thanks

**Comment by kapunahelewong** [comment]
You changed the title of the PR, but the tests are looking at the commit message ([here](https://github.com/angular/angular/pull/33730/commits)). Once the commit message is `docs: add learning resource`, I think the tests will pass. Take a look at my notes and see if they make sense. If you have any questions, I can help you. 🙂

**Comment by dymafr** [comment]
@kapunahelewong This time, is the one! ;) Sorry!
My mistake was that I did the change on GiHub and I did not create a branch locally. I could not amend the commit on GiHub, but I followed your guide and figured it out. Thanks!

**Comment by kapunahelewong** [comment]
It's ok, @dymafr. It happens all the time! 😊The failures are unrelated to your change, so I've rebased and am pushing up to trigger the tests to run again. If everything passes, then we can move forward.

**Review by kapunahelewong — APPROVED** [review]
Perfect, thank you @dymafr!

**Pull request closed without merging**
