### PR TITLE
docs: add a comma

### PR DESCRIPTION
**Pull request by solkaz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Hi @solkaz, thanks for this PR! Please remember to sign the CLA. When you've done that, will you tag me so I can help this move forward? 🌸

**Comment by solkaz** [comment]
@googlebot I signed it!

**Comment by solkaz** [comment]
@kapunahelewong CLA has been signed.

**Review by kapunahelewong — APPROVED** [review]
Thank you, @solkaz!! 

merge-assistance: Global approval for this docs-only change.

**Pull request closed without merging**
