### PR TITLE
refactor(core): Add a bit to `EventInfo` to mark resolution.

### PR DESCRIPTION
**Pull request by tbondwilkinson**
This will prevent running `ActionResolver` logic multiple times while migrating to use `Dispatcher` to resolve actions rather than `EventContract`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Comment by tbondwilkinson** [comment]
TESTED=[TGP](https://fusion2.corp.google.com/presubmit/634894425/OCL:634894425:BASE:634816936:1716005434087:edc399d/targets)

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Review by iteriani — APPROVED** [review]

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit bb13174bd1fe4f1175eab44c9daef80f7a328ce3.

**Pull request closed without merging**
