### PR TITLE
build(aio): use http push for navigation.json

### PR DESCRIPTION
**Pull request by petebacondarwin**
Tries to solve : #17733

### CODE REVIEW

**Comment by petebacondarwin** [comment]
An interesting resource:
https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/

**Comment by IgorMinar** [comment]
I tried to test this on our preview server and couldn't get it to work only to realize that this changes the firebase config file which is not used by the preview server. sigh.

let's get this in and test it on firebase.

**Review by IgorMinar — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Yeah, I had to create a temporary Firebase project to test it.

**Comment by IgorMinar** [comment]
screen shot 2017-10-21 at 4 08 06 am

it seems to work just fine (it hasn't been cherry-picked to stable branch yet, so you can test it only on next.angular.io).

This is cool - could we do the same for polyfill and the main bundle? otherwise the json files get a higher priority and delay loading of these two critical paths JS files.

**Comment by IgorMinar** [comment]
this was the test run: https://www.webpagetest.org/video/compare.php?tests=171021_Z4_b8966f2b966ac463916ab38dc46d1926-r:1-c:0

**Pull request merged**
