### PR TITLE
fix(docs-infra): update tooltip of events link

### LINKED ISSUE #30480: The tooltip of 'Events' link in the footer of angular.io is wrong
# 📚 Docs or angular.io bug report

### Description

 Events tooltip in the footer of angular.io is wrong.

### What's the affected URL?**
 All subpages of https://angular.io/

### Reproduction Steps**

 Just hover your mouse over the 'Events' link.

## Expected:
A message about Angular events.

## Actual:
"Post issues and suggestions on GitHub"

### PR DESCRIPTION
**Pull request by Hugoer**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #30480

## What is the new behavior?
A message about Angular events

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Fixes #30480.

### CODE REVIEW

**Comment by Hugoer** [comment]
> I signed it!

I signed it!

**Comment by trotyl** [comment]
Hi @Hugoer, thanks for the contribution, please consider:

+ Squash the two commits into one;
+ Remove the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) added in the top;
+ Preserve the empty line in the end.

**Review by StephenFluin — APPROVED** [review]
Change looks good.

Still need fixes to commits mentioned by @trotyl

**Comment by gkalpak** [comment]
@Hugoer, could you please add `Fixes #30480` at the end of the commit message (per our [commit message guidelines][1])?

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by mhevery** [comment]
@gkalpak I have added `Fixes #30480` to the commit msg.

**Pull request closed without merging**
