### PR TITLE
chore(package.json) upgrade typescript to ^1.5.3 stable

### PR DESCRIPTION
**Pull request by PatrickJS**

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@gdi2290 you would have to update https://github.com/angular/angular/blob/master/npm-shrinkwrap.json as well (see https://github.com/angular/angular/blob/master/npm-shrinkwrap.readme.md).

But from the brief chat with @IgorMinar about this one, we might still need a custom patch. Having said this, I would love to to get rid of dependencies on git repositories as it makes npm install time painfully long.

**Comment by tbosch** [comment]
@alexeagle can we do this, i.e. remove your custom branch now?

**Comment by alexeagle** [comment]
We still need a fork where the ES6 types are declared in a subtype-able
way. But I should rebase the branch to 1.5.3.

**Comment by gdi2290** [comment]
I'll close this since the repo still needs to work on a branch

**Comment by pkozlowski-opensource** [comment]
@alexeagle is there any chance of pushing the required changes to TypeScript master? The problem with referencing a git endpoint is that it makes the npm update much, much slower. And we need to do the npm update (install) quite often since any change in npm dependencies triggers purging of all the npm-installed deps.

**Comment by alexeagle** [comment]
We were waiting on https://github.com/Microsoft/TypeScript/issues/3332
which Mohammed told me was scheduled for 1.6
but now that's marked closed.
However Error is still defined as a var which cannot be subclassed:
https://github.com/Microsoft/TypeScript/blob/master/bin/lib.es6.d.ts#L890
+Mohamed Hegazy <mhegazy@microsoft.com> is there an issue we can follow for
the whole feature?

**Pull request closed without merging**
