### PR TITLE
fix(zone.js): do not silence uncaught promise rejections when the `finally` is called

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
- [x] Bugfix

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@arturovt thanks for re-creating the PR 👍 I will need to do some cleanup work in Google's codebase and let you know if I find any patterns that might need extra attention. Thank you.

**Comment by AndrewKushnir** [comment]
[Global Presubmit](https://test.corp.google.com/OCL:456663548:BASE:456663642:1655951369836:7407bb7b).

**Comment by AndrewKushnir** [comment]
@arturovt unfortunately, this change caused a number of failures in Google's codebase. We'd need to discuss the next steps with the team, but the current state looks similar to #45447, see   https://github.com/angular/angular/pull/45447#issuecomment-1166164811.

**Comment by arturovt** [comment]
Closing since this breaks some tests internally, which would require some effort to investigate and land in g3.

**Pull request closed without merging**
