### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by flyyang**
See the changes

### CODE REVIEW

**Comment by flyyang** [comment]
I signed it!

**Comment by robwormald** [comment]
@flyyang thanks for the PR. could you update your commit message to conform to the guidelines mentioned here? thanks!

**Comment by flyyang** [comment]
All these changes should go docs or style or fix?

**Comment by PascalPrecht** [comment]
I'd go with `docs: ....` here. Fixes are really for bug fixes. Just don't specify a scope, since you touched docs comments but also test specs.

**Comment by flyyang** [comment]
Hi @PascalPrecht . Does the update suits our conventions. Anything else?

**Pull request closed without merging**
