### PR TITLE
docs: indenting internal code for easier understanding

### PR DESCRIPTION
**Pull request by alvaro-junqueira-axa**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thanks for this !

**Comment by JeanMeche** [comment]
Can you please make sure to [sign the CLA](url), thank you.

**Comment by JeanMeche** [comment]
The CLA wasn't signed, we'll have to decline this PR.

**Comment by alvaro-junqueira-axa** [comment]
> The CLA wasn't signed, we'll have to decline this PR.

Sorry, I can sign with this user
I'll need to open an PR with my personal user then
Sorry for the confusion and late reply =/

**Pull request closed without merging**
