### PR TITLE
chore(build): Karma watches broccoli output.

### PR DESCRIPTION
**Pull request by alexeagle**
This is a prerequisite for switching to TypeScript. We need to remove the Traceur preprocessor
from Karma, so we have the build specified in a single place (broccoli tree def'n).

### CODE REVIEW

**Comment by alexeagle** [comment]
I could use some help testing this, since breakages to dev workflow aren't caught by travis

**Comment by jeffbcross** [comment]
Works for me

**Comment by zzo** [comment]
looks good for a start thanks

**Comment by alexeagle** [comment]
merged in 511e832ee25a3d8734b0835c7e8c8d8aa14bfb88

**Pull request closed without merging**
