### PR TITLE
docs: add Kotlin on deployment session

### PR DESCRIPTION
**Pull request by wendreof**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by wendreof** [comment]
@googlebot I signed it!

**Review by kapilepatel — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]
lgtm, but can you please follow our commit message format?

**Comment by wendreof** [comment]
Ok, I have been changed my commit message!

**Comment by kapunahelewong** [comment]
Hi @wendreof, could amend your commit message (as opposed to the title of the PR on this page)? Here's what I'm referring to:

image

You can follow the steps I use in [my own workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) if you like. Try changing it to something like:

> docs: add Kotlin on deployment session

Will you tag me when you're done? Thanks!

**Comment by AndrewKushnir** [comment]
@wendreof, I'm closing this PR since the `aio/content/start/deployment.md` file has changed (that sentence was moved below in the doc) and there is now a merge conflict. I'm closing this PR for now, feel free to reopen or create a new one when you get a chance. Thank you.

**Pull request closed without merging**
