### PR TITLE
refactor(common): remove usage of deprecated Renderer

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Limiting usage of deprecated APIs so it is easier to drop those in the future.

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]

**Comment by vicb** [comment]
@pkozlowski-opensource Have you discussed this with the team ? (We were blocked on some internal code for this)

**Comment by jasonaden** [comment]
@IgorMinar Moved this out of "merge" to address TAP failures. See [cr/160711332](http://cr/160711332)

**Comment by IgorMinar** [comment]
@pkozlowski-opensource can you please rebase this and we'll try to get it in?

**Comment by pkozlowski-opensource** [comment]
@IgorMinar done. Should I stick the `merge` label on it?

**Comment by IgorMinar** [comment]
yes. let's see if we can get this into google3. the last time we tried there was an issue with flex-layout depending on this private api but that should have been fixed already.

**Comment by hansl** [comment]
https://test.corp.google.com/ui#id=OCL:165337105:BASE:165337155:1502822756102:28790f52

It's failing.

**Comment by matsko** [comment]
@hansl The internal g3 code for @angular/flex-layout needs to be first applied for this to pass.

**Comment by hansl** [comment]
@matsko still red: https://test/ui#id=OCL:165337105:BASE:165387481:1502845815479:248c5fa5

Seems like flex-layout typing is still the issue, but we synced the latest master of flex-layout to g3 so I don't know what's going on.

**Comment by ThomasBurleson** [comment]
@matsko - can I help ?

**Comment by mhevery** [comment]
@ThomasBurleson We need to get this in: https://github.com/angular/flex-layout/pull/386
/cc @jelbourn

**Comment by ThomasBurleson** [comment]
@mhevery  - once this is merged into master, it will be super easy to update `@angular/flex-layout`. Most the required changes are already in that repos (see SHA https://github.com/angular/flex-layout/commit/695bf371f96363a41b4bf14bbb8653f0b624dca2).

> The only exception is the use of Renderer injected into the current ngStyle and ngClass directives.

So this PR will allow us to upgrade... the question becomes one on timing the versions.

**Pull request closed without merging**
