### PR TITLE
ci(docs-infra): fix and improve `aio_monitoring` job

### PR DESCRIPTION
**Pull request by gkalpak**
Sits on top of #26596.

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Once the SECRETS are in place

**Comment by gkalpak** [comment]
Secrets are in place. (Too bad the `aio_monitoring` will consistently pass now and we won't get to see the failure notifications 😛 - famous last words)
Rebased on top of #26596 (which should go in first).

**Comment by petebacondarwin** [comment]
Still LGTM

**Review by IgorMinar — APPROVED** [review]
I do like what you did with `xvfb`. The env variables are also a bit more readable IMO at the cost of discoverability, but I think it's worth it.

**Comment by gkalpak** [comment]
Closed and reopened to trigger CircleCI (which hadn't run for some reason 😕).

**Comment by gkalpak** [comment]
Notes to caretaker:
- `test_docs_examples_0` failure inherited from master. (Will be fixed by #26777.)
- This has been approved by @petebacondarwin and @IgorMinar, but PullApprove can't pick this up after closing and reopening.

**Comment by gkalpak** [comment]
Rebased on master (after #26596 was merged).

**Review by IgorMinar — APPROVED** [review]

**Comment by gkalpak** [comment]
Rebased on master and added one more commit to fix another flake:
- [test(docs-infra): make redirection tests more robust][1]

[1]: https://github.com/angular/angular/pull/26649/commits/77b2b7a880fc5da4009043faeaef6815c569b96c

**Pull request closed without merging**
