### PR TITLE
docs(docs-infra): fix table overriding main content block

### PR DESCRIPTION
**Pull request by MeAkib**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI-related changes
- [ ] Documentation content changes
- [ ] angular.io application/infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

https://youtu.be/v87CWLiTtcY

Issue Number: #45121

## What is the new behavior?
Just the table would be scrollable not its parent.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by akib1997** [comment]
The issue is:  #51469

**Comment by akib1997** [comment]
Here is the issue and solution description:
https://youtu.be/xOW35W0KDXU

**Comment by akib1997** [comment]
This issue is here also. https://angular.io/guide/deprecations
It will be fixed after merge.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by JeanMeche** [comment]
We're not looking to update the AIO infra anymore.

**Pull request closed without merging**
