### PR TITLE
docs: remove solution style tsconfig

### PR DESCRIPTION
**Pull request by alan-agius4**
Following the issues highlighted in
https://docs.google.com/document/d/1eB6cGCG_2ircfS5GzpDC9dBgikeYYcMxghVH5sDESHw/edit?usp=sharing
and discussions held with the TypeScript team.
Together with the TypeScript team it was decided that the best course of action is to rollback this feature.

In future, it is not excluded that solution style tsconfigs are re-introduced.

See: https://github.com/angular/angular-cli/pull/18478

### CODE REVIEW

**Comment by alan-agius4** [comment]
Blocked until https://github.com/angular/angular-cli/pull/18478 is merged.

**Comment by alan-agius4** [comment]
@kyle116 & @clydin FYI

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: docs-packaging-and-releasing

**Review by aikithoughts — APPROVED** [review]
This looks like it reverts the changes back to where they were in v9, which seems correct. LGTM.

Reviewed-for: global-docs-approvers

**Review by mgechev — APPROVED** [review]

**Review by kyliau — APPROVED** [review]

**Pull request closed without merging**
