### PR TITLE
refactor(core): Move preventDefault to Dispatcher

### PR DESCRIPTION
**Pull request by tbondwilkinson**
This is a simple move.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Comment by tbondwilkinson** [comment]
TESTED=[TGP](https://fusion2.corp.google.com/presubmit/632669334/OCL:632669334:BASE:632813518:1715453441362:e99540b;groups=PossiblyNewlyFailing/targets)

**Comment by tbondwilkinson** [comment]
DIFFBASE=https://github.com/angular/angular/pull/55721

**Review by AndrewKushnir — APPROVED** [review]

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Review by thePunderWoman — APPROVED** [review]
reviewed-for: fw-core, primitives, public-api

**Review by rahatarmanahmed — APPROVED** [review]

**Comment by atscott** [comment]
This PR was merged into the repository by commit caedd10597a6becfc1f1f0d98b06dc76d6b25a86.

**Pull request closed without merging**
