### PR TITLE
fix(tests): remove fit in component_fixture_spec

### PR DESCRIPTION
**Pull request by kara**
This fixes a `fit` that made it into master.

### CODE REVIEW

**Comment by jelbourn** [comment]
LGTM

**Comment by jesperronn** [comment]
Seems like CircleCI complains about the commit with the message 

> [00:15:19] WARNING: Files are not properly formatted. Please run
> [00:15:19]   node_modules/clang-format/index.js -i -style="file" > `/home/ubuntu/angular/modules/@angular/core/test/component_fixture_spec.ts`
> [00:15:19]   (using clang-format version 1.0.41)

How come that this is only an error in CircleCI? Could it be that Travis is not running the same tasks as Circle?

**Comment by kara** [comment]
@jesperronn Good catch; I can fix the formatting.  Travis and Circle do run different checks :)

**Comment by jesperronn** [comment]
Thanks for clarification @kara. If I get a chance, I can try to fix the formatting.

**Pull request merged**
