### PR TITLE
refactor(ivy): tighten up path types in ngstc and ngcc

### PR DESCRIPTION
**Pull request by petebacondarwin**
Previously, we introduced the "branded" path types, `AbsoluteFsPath` and
`PathSegment` to distinguish between different kinds of path strings used
in the system. It was not possible to implicitly cast from `string` to
these types or from one type to another. This helps to prevent mistakenly
using the wrong type of path string in the wrong place.

This commit goes one step further. It locks down these types so it is not
possible to cast to a `string` either. Now one must use the `.toString()`
method on the branded path to get an actual string type. The branded paths
are still `string` values at runtime and they extend the `String` interface
so that all the string methods, (e.g. `.startsWith()`) can be used directly.

Further it was found that there were places were a string was being used
as a kind of path to represent the import specifier of a module. Such paths
can be absolute or relative but it is still helpful to reason about these
types separately to `string`, `AbsoluteFsPath` and `PathSegment`.

A new type `ModuleSpecifier` has been defined that represents this new
branded path. It has a create helper (`ModuleSpecifier.from()`) but can
be cast implicitly to `AbsoluteFsPath` and `PathSegment` as needed.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by alan-agius4** [comment]
@petebacondarwin codefresh failure looks legit!

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Windows CI is failing and it looks like a legit failure caused by these changes.

**Comment by petebacondarwin** [comment]
@alan-agius4 - yep! I'm working my way through them :-)

**Comment by petebacondarwin** [comment]
Bit tricky without my own Windows box to test it on :-)

**Comment by petebacondarwin** [comment]
Combined into #30591

**Pull request closed without merging**
