### PR TITLE
chore(docgen): Use updated dartdoc tool

### PR DESCRIPTION
**Pull request by kegluneq**
I don't have the hardware to test this on Windows -- does Travis handle that for us?

Use the new `dartdoc` tool, which
[shipped with 1.12](https://groups.google.com/a/dartlang.org/forum/#!topic/announce/Q1JSlVaFFnY)

Update the sdk constraint to 1.12

### CODE REVIEW

**Comment by yjbanov** [comment]
Will add `merge

**Comment by kegluneq** [comment]
Missed an argument format change in my first PR -- this one is fixed.

Thanks!

**Comment by vicb** [comment]
:+1:

**Comment by kegluneq** [comment]
Closed by 0f54ed03067704f65a1130c8ebccb7db0d40ff96

**Pull request closed without merging**
