### PR TITLE
build(docs-infra): upgrade cli command docs sources to 6b6b8f828

### PR DESCRIPTION
**Pull request by gkalpak**
Updating [angular#8.2.x](https://github.com/angular/angular/tree/8.2.x) from [cli-builds#8.1.x](https://github.com/angular/cli-builds/tree/8.1.x).

##
Relevant changes in [commit range](https://github.com/angular/cli-builds/compare/a8fe15cb6...6b6b8f828):

**Modified**
- help/build.json

##

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@gkalpak changes in `CHNAGELOG.md` and `package.json` look suspicious. Could you please check (and `CHANGELOG.md` seems to have conflicts)? I'll mark this PR as "cleanup" for now. Feel free to put the "merge" label back once it's resolved. Thank you.

**Comment by petebacondarwin** [comment]
@AndrewKushnir for some reason the PR has picked up two commits from Misko. The primary commit is correct. Not sure how that happened.

We can fix it with a rebase, dropping those two commits, but I think @gkalpak should take a look before we do that to check if there is something weird going on with his script.

**Comment by gkalpak** [comment]
According to GitHub, it seems that @mhevery accidentally force-pushed to my branch 🤷‍♂
I'll fix it.

force-pushing-to-31856

**Comment by petebacondarwin** [comment]
😱 😱 😱 😱 😱 😱 😱 😱 😱

**Comment by AndrewKushnir** [comment]
Thanks @petebacondarwin and @gkalpak. This PR is now merged into patch branch.

**Pull request closed without merging**
