### PR TITLE
URLSearchParams: added getKeys() support so that it more closely fo…

### PR DESCRIPTION
**Pull request by avhetman**
…llows map-like operations

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)  Note: I added code comments, not sure what other documentation is needed

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently, there is no way to get the keys from URLSearchParams
Issue Number: N/A

## What is the new behavior?
getKeys() can now be called to retrieve an array of keys

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by avhetman** [comment]
I submitted a CLA, I think it is waiting for approval?

**Comment by trotyl** [comment]
I don't think `URLSearchParams` should introduce too much difference from [standard](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), why not just `keys()`?

**Comment by avhetman** [comment]
Yes, good point trotyl, if necessary we can change it from getKeys() to keys()

**Comment by trotyl** [comment]
I'm just providing a suggestion, please align with official reply from Angular team. (>_<)

**Comment by Toxicable** [comment]
As @trotyl mentioned, Angular's URLSearchParam should not be different from the native implimentation. 
Also, Http will eventually be depricated in favour of HttpClient so I'd suggest using that instead.

**Comment by avhetman** [comment]
Is there anything I can do to fix these build failures?

**Comment by chivne** [comment]
123

**Pull request closed without merging**
