### PR TITLE
docs: remove references to Trusted Types due to incompatibility to Webpack 5

### PR DESCRIPTION
**Pull request by aikithoughts**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Removing references to Trusted Types until we know that Webpack supports them.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

We have learned that Trusted Types does not work with Webpack 5. While that issue sorts out, we are removing references to Trusted Types from the Angular documentation.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Review by gkalpak — CHANGES_REQUESTED** [review]
Could you please add some info in the commit message on why we are removing these references? 🙏 🙏 🙏

**Comment by aikidave** [comment]
> Could you please add some info in the commit message on why we are removing these references? 🙏 🙏 🙏

I added a comment to the PR checklist.

**Comment by gkalpak** [comment]
> I added a comment to the PR checklist.

Why not the commit message? (It is much easier to find that info if it is in the commit message as well.)

**Review by gkalpak — APPROVED** [review]

**Review by mhevery — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: global-approvers


Using global approvers as @mhevery already approved for `fw-security`.

**Pull request closed without merging**
