### PR TITLE
docs: describe how to run tests in GitLab CI

### PR DESCRIPTION
**Pull request by profanis**
The documentation has a very useful configuration for Travis and CircleCI but not for GitLab CI. So, I thought that might be useful to have that as well.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by MattiJarvinen** [comment]
Additional extra 👍 🥳  if you add this to GitLab examples too, I have meant to do it for years but you know how it is.

https://docs.gitlab.com/ee/ci/examples/README.html

https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/ci/templates

**Comment by profanis** [comment]
> Additional extra   if you add this to GitLab examples too, I have meant to do it for years but you know how it is.
> 
> https://docs.gitlab.com/ee/ci/examples/README.html
> 
> https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/ci/templates

That's a good idea @MattiJarvinen 🙂
I will plan to. Thanks for this

**Review by aikithoughts — APPROVED** [review]
Looks good from a docs perspective!

Reviewed-for: global-docs-approvers

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed as eng-review

**Pull request closed without merging**
