### PR TITLE
docs(forms): fix ControlValueAccessor code example

### PR DESCRIPTION
**Pull request by VinitTomar**
registerOnChange usage note correction,
previous => (change): '_onChange($event.target.value)'
updated => '(change)': '_onChange($event.target.value)'

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by EmmanuelDemey — APPROVED** [review]

**Comment by trotyl** [comment]
Please fix the commit message per [Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit). Like:

```text
docs(forms): fix ControlValueAccessor code example
```

**Comment by trotyl** [comment]
@VinitTomar Commit message is unrelated to PR title, it's part of the git commit.

**Comment by VinitTomar** [comment]
@trotyl I have tried all option given on this page, https://help.github.com/en/articles/changing-a-commit-message, still I am unable to change commit message. Can you help me how to change commit message?

**Comment by trotyl** [comment]
You can only do that in Git command line, and force push it to the remote, it cannot be changed in GitHub.

**Comment by brandonroberts** [comment]
Thanks for the PR @VinitTomar! I squashed the extra commits down to one, so you should be good to go.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Caretaker note: This is a docs only change and should not impact g3. Please run presubmit.

**Review by kara — APPROVED** [review]
LGTM

**Pull request closed without merging**
