### PR TITLE
docs(core): fix `ViewChildren` code examples to avoid TS error

### PR DESCRIPTION
**Pull request by behroozbc**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
found ts2564 error when use your code in description
this
```Any provider defined through a string token (e.g. @ViewChild('someToken') someTokenVal: any)```

Issue Number: https://github.com/angular/angular/issues/42811

## What is the new behavior?
add ! to fix ts2564 error

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by behroozbc** [comment]
hi @gkalpak for fix commit message I change the pull request 
please check it
Thanks

**Comment by gkalpak** [comment]
@googlebot I consent.

**Comment by gkalpak** [comment]
Thx, @behroozbc!

FYI, I pushed some changes to update the commit message (to make the description a little more clear and add a reference to the issue as described in https://github.com/angular/angular/pull/42812#pullrequestreview-703492959) and format the file to pass linting.

**Review by gkalpak — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by gkalpak** [comment]
**merge-assistance:** This is a docs-only change and should not require a presubmit.

**Pull request closed without merging**
