### PR TITLE
docs(aio) updating package.json for webpack section

### LINKED ISSUE #20198: docs(aio) Configuring Webpack section has older angular version in package.json
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Navigate to **[Webpack Configuration Section](https://angular.io/guide/webpack#configuring-webpack)**
image

## Expected behavior

package.json should have the updated versions of dependencies

## What is the motivation / use case for changing the behavior?

Doc support

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by aravindfz**
closes #20198

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by gkalpak** [comment]
This guide is currenty hidden (i.e. there is not link to it from the sidenav). We should either remove it (in which case it doesn't make sense to keep updating it) or make it public (and update it).
cc @juleskremer

**Comment by juleskremer** [comment]
@gkalpak the document should be removed; we removed it from the navigation but had left it hidden for a reference reason; however, it is not going to be continued due to evolution of the CLI.

**Comment by mogusbi** [comment]
Does this mean going forwards we have no choice but to use the CLI? Seems a bit of a backwards step to me

**Comment by SebastianStehle** [comment]
The beauty of the web and JavaScript is that it is an open environment and I should have the option to use my preferred setup and environment and the tools I want. Having some kind of closed frameworks with their own tooling would be a backwards step for me also.

**Comment by juleskremer** [comment]
Apologies, I did not mean to infer that we are not supportive of Webpack or that you must use the CLI.  The document in question, Introduction to WebPack, is a general introduction to using Webpack. Webpack's own documentation, however, is a better place to learn about Webpack and all of its various options as it covers more and is continually updated with Webpack's release cadence.  

https://webpack.js.org/concepts/

**Pull request closed without merging**
