### PR TITLE
docs(aio): Fix decorator JS feature explanation

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Review by wardbell — APPROVED** [review]
This is fine. It introduces a bit more doubt about the prospects for decorators than I'd like. But I can live with that.

**Comment by mhevery** [comment]
fix ci breakage

**Comment by cmckni3** [comment]
@mhevery sure thing. I goofed on the commit message.

**Comment by gkalpak** [comment]
@cmckni3, Travis was already green, so no need to close/reopen to trigger it again. The ci failure is from `ci/circle`, which is probably due to the fact that your commit message is invalid. It should be `docs(aio): ...`.

**Comment by cmckni3** [comment]
Good to go. Sorry about triggering a full build again.

**Review by mhevery — APPROVED** [review]

**Pull request merged**
