### PR TITLE
docs: fix spelling error in angular component class description

### PR DESCRIPTION
**Pull request by ODAVING**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Docs have been added / updated (for bug fixes / features)

- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ODAVING** [comment]
@googlebot I signed it!

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
To be honest, I think this whole sentence doesn't really make sense and that we should just remove the whole thing. What do you think @jbogarthyde ?

**Comment by petebacondarwin** [comment]
@ODAVING thanks for submitting this. Please note that the commit message must follow our required syntax: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Review by jbogarthyde — COMMENTED** [review]
How about: 

 In Angular, you create a *component* class to contain the data model and control methods. Use the TypeScript `export` keyword to export the class so that the functionality can be imported into NgModules.

**Comment by ODAVING** [comment]
@petebacondarwin and @jbogarthyde thank you for reviewing this. I'll make the changes asap.

**Review by petebacondarwin — APPROVED** [review]
Great! Can you please squash together the two commits?

**Comment by kapunahelewong** [comment]
Thanks for this, @ODAVING. Could you rebase and then tag me when you're ready? I'd like to help you move this forward. By the way, I have [notes on rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) if you'd find them helpful. Thank you!

**Comment by ODAVING** [comment]
@kapunahelewong I’ve rebased it, it seems to pass everything except the yarn local build the testers here do, any idea how I can get it passed that final one? 

Thanks,

**Comment by kapunahelewong** [comment]
Hm, I think this might be a flake. Or, wait. Did you remember to push up after rebasing? I'm still seeing your branch as being well behind. https://github.com/ODAVING/angular/tree/angular%2332948

**Comment by ODAVING** [comment]
@kapunahelewong I forced pushed after rebasing it 11 days ago. The ci/circleci: test_aio_local_ivy test keeps failing though.

**Comment by ODAVING** [comment]
@kapunahelewong The only reason according to circleci_ivy that it's failing is the following message: 
"Command 'build-local-with-ivy-ci' not found." Which I don't even know why it would be running it, since it's a simple documentation. Any insight into this would be helpful

**Comment by kapunahelewong** [comment]
Oh, I thought you meant you'd just rebased today. Could you try it? 🙏🏼

Sometimes there are flakes and a new rebase can help clear them up. I don't think it's anything you've done (since it's referring to Ivy). And if you bring it as up-to-date as possible, that should help. Then if it still fails, either that one or another, it's easier for us to get it green for merge since a whole bunch of other updates are in there. Does that help give context?

**Comment by ODAVING** [comment]
@kapunahelewong Done, hoping it works this time 🤞

**Comment by kapunahelewong** [comment]
Yay! It worked! But, I only just noticed that there are two commits. Could you squash? Here are my [own notes on the workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash). You're so close! :)

**Comment by ODAVING** [comment]
When I try to squash, do I have to go through all 260 commits that my branch was behind of, and 'f' them all? @kapunahelewong

**Comment by kapunahelewong** [comment]
No, you don't need to go through all those. Just `f`/`fixup` the second one. So, here's the way you want to go through it:

```git rebase -i HEAD~2```

^^That will only give you the option to squash 2 commits. Here's where that command get me on just some branch I have locally (unrelated to this PR, so disregard the commit messages):

image

Next, I change the second (my more recent commit) to be `f`:

image

Then I save and exit. Now if I do a `git log --oneline`, I have only the one commit:
```
57e6e7c75f (HEAD -> my-test-branch) docs: fix animations reference links to api pages
``` 

Now, if I were to push up, that single commit would be the one to show up in my PR. My second looks like it's gone, but its work is still in there. 

After you've [squashed](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase), the rebase will take care of the 260-ish commits. Those should be handled automatically. Does that help?

**Comment by ODAVING** [comment]
I’ll try this again, but Last time I did that, I saw all the 260 commit
messages!
Will update asap!

**Comment by kapunahelewong** [comment]
Look, @ODAVING! I fixed the extra merge commit! (I've never done that before on someone else's PR). Yay!!!!! Rebased and amended!

**Review by kapunahelewong — APPROVED** [review]
Thank you, @ODAVING!!

Merge assistance: global approval for docs changes. Thank you!

**Pull request closed without merging**
