### PR TITLE
refactor(http): inline HttpObserve

### PR DESCRIPTION
**Pull request by Toxicable**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: 
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Refactoring (no functional changes, no api changes)
```

## What is the current behavior?
HttpObserve is a seprate Type

Issue Number: #18146

## What is the new behavior?
the type from HttpObserve is inlined

## Does this PR introduce a breaking change?
```
[x] No
```

### CODE REVIEW

**Comment by mydata** [comment]
when will this merged version be available?

**Review by alxhub — APPROVED** [review]

**Comment by Toxicable** [comment]
@IgorMinar Could you review this for public api?

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:344882446:BASE:344882472:1606773282196:cd5e2e7)

**Review by mhevery — APPROVED** [review]
reviewed-for: global-approvers

**Pull request closed without merging**
