### PR TITLE
docs: Smart quote that breaks code block

### PR DESCRIPTION
**Pull request by AdityaK60**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

In the angular.dev docs, a smart quote character is present in the "How to use a service" code block on the "Sharing Logic" page. This breaks syntax highlighting in the code block as well as allowing a reader to copy broken code that will generate a syntax error if used.

Issue Number: #53486

## What is the new behavior?
Fixed the smart quote so that there is no syntax error

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@AdityaK60 thanks for improving Angular docs!

**Comment by AndrewKushnir** [comment]
@AdityaK60 could you please update the commit message to start with `docs: ` (instead of `fix(docs): `)? That should make the commit message compatible with the guidelines and the `lint` CI check should be "green". Thank you.

**Comment by AdityaK60** [comment]
@AndrewKushnir Made the changes to the commit message as per your suggestion. Thank you!

**Comment by AndrewKushnir** [comment]
@AdityaK60 thanks for the updates, I've added this PR to the merge queue.

**Comment by AndrewKushnir** [comment]
**Caretaker note**: low risk PR, no additional reviews are required.

**Comment by alxhub** [comment]
This PR was merged into the repository by commit e1d01c7be89596a9d0cf445c3e8bb4e38b3c8c2d.

**Pull request closed without merging**
