### PR TITLE
add http and router to angular2/angular2, update typings, too.

### PR DESCRIPTION
**Pull request by jeffbcross**

### CODE REVIEW

**Comment by jeffbcross** [comment]
Travis needs to be restarted once #4097 is merged

**Comment by jeffbcross** [comment]
FYI @jteplitz602 this PR removes web_worker from the angular2 typings and doesn't create a separate typings file. If you want me to change that I can (I'm not sure if we had already published angular2 with worker typings or not, which would make this a breaking change).

**Comment by jteplitz602** [comment]
@jeffbcross Looking at DefinitelyTyped I don't think the typings ever made it into a release so that's fine. Once I finish #4064 WebWorkers will have their own typings files anyways.

**Comment by jeffbcross** [comment]
To recap an IRL conversation with @alexeagle a few days ago when we reviewed this...

 * We determined it was best to not introduce a new typings file, `generated_typings.d.ts`, that would have to be included in our distributions. 
 * For the `InjectableReference` typing, we should just define and export it from `core.ts`, since it has no significant side effects to do so.
 * I think we decided to just remap `StringMap` to `Object`, even though `StringMap` is more constrained than `Object`, and also requires square-bracket accessors instead of dot notation.
 * I think for now, we are going to leave the `Map` declaration hard-coded in the global namespace inside the `core.d.ts` template, rather than solve issues relating to ES5/ES6 targets in this PR.

@alexeagle is this accurate?

**Comment by alexeagle** [comment]
Yes, that matches what I remember.
Note that Rado is removing last bits of traceur so we could revisit the
traceur-runtime.d.ts.

**Comment by jeffbcross** [comment]
I actually decided to keep `InjectableReference` in the typings template so that it won't show up in our docs. 

I also didn't alias `StringMap` to `Object` since `Object` is not generic. I just left it in the core.d.ts file under the `ng` namespace.

**Comment by alexeagle** [comment]
LGTM

Good rationale for leaving those things where they are. We can clean it up a bit more later, maybe after TS 1.6.

**Comment by jeffbcross** [comment]
@mhevery @tbosch or @vsavkin can one of you review this commit that changes where the public API imports from? https://github.com/jeffbcross/angular/commit/aa838e4568868a35a8a80474139eab934e65922a

The other way to solve this would be to add all router and http public exports to the test.

**Comment by jeffbcross** [comment]
Got the verbal LGTM from @mhevery  on the updated commit to `public_api_spec` 42d29e44954a9e25b570745d127280ed3eb3765f

Going to verify that the only Travis flakes are related to our current build issues so I can send to presubmit (since the build issue is only present in the PR travis jobs).

**Comment by jeffbcross** [comment]
I haven't touched this in a couple of weeks, but realize I forgot to comment on the status. I ran into issues with a handful of router exports not being correctly re-exported from angular2/angular2 when checking in the public API spec. Also, our typings process is simplifying, leaving much of this PR blissfully obsolete.

After chatting with @IgorMinar this morning, neither of us are super keen on distributing http and router as part of the angular2 bundle.

**Pull request closed without merging**
