### PR TITLE
refactor(router): replace `last` helper with native `Array.at(-1)`

### PR DESCRIPTION
**Pull request by JeanMeche**
We now have a native method to return the last item of an array

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
This PR was merged into the repository by commit 5e84d9c8c3fa673161566f9d4e6499b2357b7634.

**Comment by Talb2005** [comment]
This change to using Array.at caused many errors to our users who are using older browsers.
This method isn't being transpiled to older syntax, so we had to include a pollyfill for it.

**Comment by Talb2005** [comment]
@alfaproject Thanks for the reply. 
I understand, but up until now it seems that defining older browsers in .browserslistrc was good enough and everything was working fine.
I just didn't expect updating Angular from 17.0.8 to 17.0.9 to introduce any breaking changes..
Also, why can't I find this commit in the [CHANGELOG](https://github.com/angular/angular/blob/main/CHANGELOG.md) ?

**Comment by alfaproject** [comment]
Refactor commits don't show in the change log because in theory they don't change functionality. Browserlist has nothing to do with polyfills btw and if that's the only thing you rely on, you are in for a bunch of surprises in the long run

**Comment by atscott** [comment]
What @alfaproject is true but this change feels a bit needlessly breaking. We don’t benefit much from it so I’ll revert this on Monday and have the caretaker do an LTS release of the 17.0.x branch next week as well.

**Pull request closed without merging**
