### PR TITLE
docs: better documentation for multiple projects within one workspace

### PR DESCRIPTION
**Pull request by eduardbme**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 39368

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by aikidave** [comment]
Thanks, @eduardbme! I've asked our editor, @TeriGlover, to review the content you've written. We'll need someone to verify the code examples as well.

Really appreciate you taking the time to put this together!

**Comment by eduardbme** [comment]
@aikidave this PR is still kind of in progress
I'll update the status to the ready for review, for now, example and content is too rough

**Comment by aikidave** [comment]
Oh! Good to know! I'll hold off on reviewing until you're ready!

**Comment by dylhunn** [comment]
Hello! This PR has not been updated recently, and looks possibly abandoned. If you'd still like to land it, please feel free to reopen the PR.

**Pull request closed without merging**
