### PR TITLE
docs: Add Transparency to Ecosystem Image

### PR DESCRIPTION
**Pull request by MariusTilvanDev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The image for the ecosystem picture on the readme is not transparent.

Issue Number: #45929

## What is the new behavior?
Now, we have transparency in the image for the ecosystem picture on the readme.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Thx, @MariusTilvanDev :+1:

**Comment by MariusTilvanDev** [comment]
> Thx, @MariusTilvanDev 👍

Thanks too, George!
Who will do the merge since I am not authorized to merge this PR?

**Comment by gkalpak** [comment]
@MariusTilvanDev, someone from the team will take care of it.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 3242f75efe0670b9b88a010ecc0f6ead8c9ca88f.

**Comment by gkalpak** [comment]
@MariusTilvanDev, since you have commented on the issue, GitHub has automatically subscribed you to notifications for that issue. You can change that in the "Notifications" section in the right sidebar on the issue page.

**Pull request closed without merging**
