### PR TITLE
docs: fix typo in bootstrapping guide

### PR DESCRIPTION
**Pull request by GavinSong123**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #25938

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by GavinSong123** [comment]
I signed it!

**Comment by GavinSong123** [comment]
I signed it!

**Comment by GavinSong123** [comment]
I signed it!

**Comment by GavinSong123** [comment]
solved it

**Comment by GavinSong123** [comment]
solved it

**Comment by GavinSong123** [comment]
solved it

**Comment by GavinSong123** [comment]
solved it

**Comment by GavinSong123** [comment]
I signed it!

**Review by gkalpak — APPROVED** [review]
Can you please change the commit message to follow our [guidelines][1]? E.g.:

> docs: fix typo in bootstrapping guide
>
> Fixes #25938

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by gkalpak** [comment]
Oh, btw, did you sign the CLA? 😛

**Comment by GavinSong123** [comment]
I signed it!

**Comment by GavinSong123** [comment]
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and have the pull request author add another comment and the bot will run again. If the bot doesn't comment, it means it doesn't think anything has changed.

resolved it!

**Comment by GavinSong123** [comment]
I signed it!

**Comment by GavinSong123** [comment]
ok?

**Comment by GavinSong123** [comment]
ok?

**Review by jenniferfell — APPROVED** [review]

**Pull request closed without merging**
