### PR TITLE
docs(aio): Add info about how to create translation source files via Angular CLI

### PR DESCRIPTION
**Pull request by mischah**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: Docs
```

**What is the current behavior?** (You can also link to an open issue here)

The [Internationalization (I18N) recipe](https://angular.io/docs/ts/latest/cookbook/i18n.html) is missing info about how to create translation source files via Angular CLI.

**What is the new behavior?**

Added the information

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

This is extermely important. Because using the way which is described right now doesn’t work when using Sass imports.

I found upon a few closed Github issues which offered dirty workarounds and nearly tried to used on of them:

- https://github.com/angular/angular/issues/11747
- https://github.com/mgechev/angular-seed/issues/1488
- https://github.com/mgechev/angular-seed/issues/1772

But it’s all good when using the Angular CLI ❤️ 

**Question**: Should I replace the old way with the angular CLI way instead?

### CODE REVIEW

**Comment by mischah** [comment]
> Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

I signed it!

**Comment by ocombe** [comment]
There's a story in the angular-cli repo about i18n: https://github.com/angular/angular-cli/wiki/stories-internationalization
If anything, the angular.io i18n guide should just link to this story.

**Comment by wardbell** [comment]
... and the link to CLI wiki will be included in the guide as of PR #16469. Closing _this_ issue for _that_ reason.

When the process settles down, we'll revisit this decision and, potentially, pull the CLI discussion more prominently into the Angular docs.

Thank you for helping, though. Your suggestion was a good one. We're just meeting the need in a different way.

**Comment by mischah** [comment]
@wardbell 👌

**Pull request closed without merging**
