### PR TITLE
docs: use new link for update guide

### PR DESCRIPTION
**Pull request by bampakoa**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
LGTM

**Review by JeanMeche — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by JeanMeche** [comment]
Hi @bampakoa, can you please drop that merge commit and do a rebase instead ? Thank you.

**Comment by bampakoa** [comment]
@JeanMeche I just converted it into fixup commit. Is that ok?

**Comment by thePunderWoman** [comment]
@bampakoa Can you rebase and squash? It appears this can't merge cleanly, and when I checked it locally, it's because there's file conflicts. Once you do that, I think this is good to go.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by alxhub** [comment]
This PR was merged into the repository by commit a7e4a578d833d0a70a913c818e7391c1679a8725.

**Pull request closed without merging**
