### PR TITLE
feat(Binding): improve errors

### LINKED ISSUE #4358: Misleading error when incorrectly binding toClass
Doing something like `bind(Number).toClass(4)` instead of `bind(Number).toValue(4)` throws `Cannot create a factory for '4' because its constructor has more than 20 arguments`, when really it's because we're being silly and trying to bind a value as a class.

Simple plunkr: http://plnkr.co/edit/WY7JA4Z66IDgzRs3n5Qf?p=preview

### PR DESCRIPTION
**Pull request by vicb**
fix #4358

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@vicb what do you think about adding "positive" cases as well? It probably doesn't belong here but currently https://github.com/angular/angular/blob/master/modules/angular2/src/core/facade/lang.ts doesn't have proper tests for `isFunction` / `isClass`. 

Unless we assume that those utils are sufficiently tested by all the other tests in the ng2 codebase.

**Comment by pkozlowski-opensource** [comment]
LGTM otherwise, feel free to merge if you think that more tests wouldn't add much here.

**Comment by pkozlowski-opensource** [comment]
Oh, and BTW, I guess this check makes sense only for people using ES5/ES6, right? Since both Dart and TS should catch this, no? So I guess we should have some policy on those checks?

**Comment by vicb** [comment]
@pkozlowski-opensource yep the check only makes sense for ES5 & ES6

**Pull request closed without merging**
