### PR TITLE
refactor(compiler): /a/.exec() returns RegExpExecArray

### PR DESCRIPTION
**Pull request by frigus02**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

(No tests, yet. Is there a way to build Angular with TypeScript nightly in tests?)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix

## What is the current behavior?

TypeScript added a field `0` to `RegExpMatchArray` in https://github.com/microsoft/TypeScript/commit/3b80ddca212959ae5dcf2f48704be627283c6468. Before that, `RegExpMatchArray` and `RegExpExecArray` were identical.

In one place Angular incorrectly expects `RegExpMatchArray` as the result of a RegExp#exec() call. This assignment fails on TypeScript nightly with the error:

    Property '0' is missing in type 'RegExpExecArray' but required in type 'RegExpMatchArray'.

## What is the new behavior?

Compilation succeeds in TypeScript nightly as well as older TypeScript versions.

## Does this PR introduce a breaking change?

- [x] No

### CODE REVIEW

**Review by JoostK — CHANGES_REQUESTED** [review]
The change LGTM, but could you please update the commit message to `refactor(compiler)` as this is not a user-facing bug fix (it only affects compiling Angular from source against an as-of-yet unsupported TS version, so is irrelevant for the changelog)

**Comment by frigus02** [comment]
Thanks for the quick review. I updated the commit message and PR title. I'll try to remember that for next time: fix == fix a user-facing issue. Makes sense.

**Review by JoostK — APPROVED** [review]
Thanks for the fix!

**Comment by alxhub** [comment]
This PR was merged into the repository by commit ce76103e8fc22240870c31e1f1972bba0257202f.

**Pull request closed without merging**
