### PR TITLE
docs: inserted language attributes

### PR DESCRIPTION
**Pull request by aanchal88**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by aanchal88** [comment]
Hii @AndrewKushnir , please review the PR.

**Review by dylhunn — APPROVED** [review]

**Comment by dylhunn** [comment]
Hi @aanchal88. Thanks for the contribution. In the future, we'd like to encourage you to batch small commits like this into larger PRs -- that minimizes the wait time for each commit, and also reduces the overhead of having lots of small PRs.

caretaker note: can merge with current approvals

**Comment by aanchal88** [comment]
Hii @dylhunn , please merge the PR.

**Comment by pkozlowski-opensource** [comment]
@aanchal88 this PR would need to be rebased.

**Comment by aanchal88** [comment]
Hii @pkozlowski-opensource , I have resolved the conflicts. Please have a look.
Thanks

**Comment by JeanMeche** [comment]
Again, you will need to drop that merge commit.

**Comment by aanchal88** [comment]
Hii @JeanMeche , Due to two commits need to drop the last one?

**Comment by JeanMeche** [comment]
Yes, we don't want merge commits.

**Pull request closed without merging**
