### PR TITLE
refactor(compiler): drop obsolete NgFactory and NgSummary config options

### PR DESCRIPTION
**Pull request by AndrewKushnir**
The options to generate NgFactory and NgSummary files were added to Ivy for backwards compatibility with ViewEngine. Since ViewEngine was deprecated and removed, the NgFactory and NgSummary files are no longer used as well.

This commit drops obsolete options to generate NgFactory and NgSummary files. Also, the logic that generates those files is removed.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:492079872:BASE:492079896:1669864249542:402ecf8b).

**Review by dgp1130 — APPROVED** [review]
Bazel changes LGTM.

/cc @devversion as he might be interested.

**Review by devversion — APPROVED** [review]
LGTM for Bazel. Do you plan on doing the same internally, or are the shims still needed there? (I know ngc-wrapped is no longer synced but I still prefer to keep it somewhat in sync at this point)

**Comment by AndrewKushnir** [comment]
@devversion thanks for the review! I've [submitted a change](http://cl/492511365) today with a similar cleanup to the internal `ng_module` rule.

**Comment by AndrewKushnir** [comment]
@devversion sorry, I've misunderstood a part of the question. For `ng_module` rule - similar changes have landed today. I will also do a cleanup in the ngc-wrapped internal code as well (there will be no need in extra code there after full removal of the code as a part of this PR).

**Comment by devversion** [comment]
Makes sense! thx for clarifying

**Review by jessicajaniuk — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
[TGP](https://test.corp.google.com/OCL:493505672:BASE:510852581:1676847215193:469660a6).

**Comment by AndrewKushnir** [comment]
**Caretaker note**: @alxhub FYI this PR is reviewed, but waiting for the `fw-compiler` approval. Could you please take a quick look before merging?

**Review by alxhub — APPROVED** [review]

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: fw-core, fw-common, fw-upgrade, fw-benchmarks, integration-tests, public-api

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 83a6e203e3fc8a1414fc134d111415ef60ade717.

**Pull request closed without merging**
