### PR TITLE
feat(core): Add `TAG_NAME` DI token

### PR DESCRIPTION
**Pull request by devknoll**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
The name of the function feels wrong to me, there is no injection here. Do you have other suggestions ?

**Comment by JoostK** [comment]
What is the use-case for a builtin function like this compared to using `ElementRef`? For example this can be accomplished in user-land code:

```ts
export function injectTagName() {
  return inject(ElementRef).nativeElement.tagName;
}
````

which to me seems like a niche that doesn't have to be in the framework.

**Comment by devknoll** [comment]
`ElementRef.nativeElement` is meant as [a last resort](https://angular.io/api/core/ElementRef#properties) for when Angular itself does not offer a way to get what you need.

The `tagName` is a fundamental part of the API of an Angular directive: you specify it as part of the selector. In some cases, you could have a selector like `input[foo], textarea[foo]` and want to do something slightly different depending on whether your template matched an `input` or a `textarea` (e.g. apply a different 3rd party CSS class, whose selector you cannot change).

Therefore, it makes sense to be able to read it without needing to resort to an escape hatch.

**Comment by jessicajaniuk** [comment]
@JoostK The goal here is to move closer to end the need for DOM emulation, and one of the big offenders is grabbing the elementRef on the server side. The components use case is mostly just getting the tag name. This PR is essentially targeted at being able to avoid needing to get the element ref for that purpose.

**Pull request closed without merging**
