### PR TITLE
docs: Fixed Typo

### PR DESCRIPTION
**Pull request by ChrTall**
Fixed Typo

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Just a single typo fix.

## What is the new behavior?
Typo is fixed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, thanks for improving the docs !

For the PR to move forward, you will need to [sign the CLA](https://github.com/angular/angular/pull/49753/checks?check_run_id=12611023832).

**Comment by ChrTall** [comment]
@JeanMeche I signed the CLA.

**Review by AndrewKushnir — APPROVED** [review]
@ChrTall thanks for improving Angular docs! 👍

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit fd0c26e43055cd9b024c14c4fde4d65fccb735d6.

**Pull request closed without merging**
