### PR TITLE
fix(devtools): remove existing highlight before highlighting another …

### PR DESCRIPTION
**Pull request by sheikalthaf**
…element

In this PR we will remove the exiting highlight before highlighting the another element so that the highlight always be one

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #57557

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sheikalthaf** [comment]
@AleksanderBodurri created a separate PR, also the issue attached shows how to reproduce the issue.

**Review by dgp1130 — APPROVED** [review]
Looks reasonable to me. @AleksanderBodurri any concerns here? I'm not very familiar with this highlighter code or the full implications of adding/removing highlights. Looks safe to me though.

**Review by dgp1130 — COMMENTED** [review]
Actually, should we add a test to make sure we remove highlights when selecting a new element? That way we make sure we don't introduce the same mistake in the future.

**Comment by sheikalthaf** [comment]
@dgp1130 added testcase to verify the changes.

**Review by dgp1130 — APPROVED** [review]
Thanks for the test, looks good to me!

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 860272980128104e8e89f06b33807bfef576e797.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
