### PR TITLE
Update Domino to latest SHA

### LINKED ISSUE #44685: Inline styles with quotes are incorrectly stripped
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [x] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
Given:
```html
<div [ngStyle]="stylesOne"></div>
<div [ngStyle]="stylesTwo"></div>
```

```ts
stylesOne = {
  gridTemplate: '"a b c"',
};
stylesTwo = {
  gridTemplate: "'a b c'",
};
```

This is produced:
```html
<div style="grid-template: a b c">
<div style="grid-template: a b c">
```

When either of these would be expected ("a b c" need to be wrapped in quotes). This is handled correctly by browser-side Angular, but not Universal:

```html
<div style='grid-template: "a b c"'>
<div style="grid-template: 'a b c'">
```

## 🌍 Your Environment

<pre><code>

ngular CLI: 13.1.2
Node: 14.18.1
Package Manager: yarn 1.22.4
OS: darwin x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@angular/flex-layout            12.0.0-beta.35
@nguniversal/builders           13.0.1
@nguniversal/express-engine     13.0.1
@schematics/angular             13.1.2
rxjs                            7.5.1
typescript                      4.5.4
webpack                         5.65.0
</code></pre>

I guess this problem could be from Domino, but not sure how to write it there, in case it's actually Angular related

### PR DESCRIPTION
**Pull request by alan-agius4**
Closes #44685

### CODE REVIEW

**Review by JiaLiPassion — APPROVED** [review]
LGTM!

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@alan-agius4 since this is a low risk change, I think we can proceed with the current set of approvals.

**Comment by alan-agius4** [comment]
@AndrewKushnir agreed

**Review by gabrielduete — APPROVED** [review]

**Comment by atscott** [comment]
This PR was merged into the repository by commit 50c58ce56e92ea00077bb6772f3f73b63790aae3.

**Pull request closed without merging**
