### PR TITLE
Unparser

### LINKED ISSUE #1949: AST.toString() === 'AST'?
Is there any particular reason why subclasses of `AST` do not override the 'abstract' `AST` implementation of `toString`?

For this reason, change detection errors that use `ProtoRecord#expressionAsString`, which is derived from `bindingRecord.ast.toString()` throw unhelpful, garbage errors like this:

`Expression 'AST' has changed after it was checked. Previous value: ''. Current value: ''`

### PR DESCRIPTION
**Pull request by vicb**
fixes #1949

/cc @gdi2290

### CODE REVIEW

**Comment by tbosch** [comment]
Could we rename his into `serializer`, instead of `unparser`?

**Comment by tbosch** [comment]
Or maybe `formatter`?

**Comment by tbosch** [comment]
Or `stringifier`?

**Comment by vicb** [comment]
I have also wondered about the naming and done a bit of searching. This is an unparser.

**Comment by vsavkin** [comment]
As far as I understand the only reason for this is to provide better error messages when change detection throws. If so, should not we just show the source we parsed the AST from?

**Comment by vicb** [comment]
The main reason why I've created this is to help with parser tests (see #2348).

This can also probably be used in place of ASTWithSource, but not the intent of this PR

**Comment by vsavkin** [comment]
I can see how it is useful for tests. Should it be in the tests directory then?

**Comment by vicb** [comment]
@vsavkin I've moved the UnParser to the test folder in the last commit, PTAL.

**Pull request closed without merging**
