### PR TITLE
refactor(localize): remove redundant import

### PR DESCRIPTION
**Pull request by alan-agius4**
Remove redundant import from ARB serializer

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Thanks @alan-agius4 - while you are at it could you fix up the JSDOC comment for the serializer, which I realise I copy-pasted from the simple JSON serializer:

Instead of

```
/**
 * This is a semi-public bespoke serialization format that is used for testing and sometimes as a
 * format for storing translations that will be inlined at runtime.
 *
 * @see ArbTranslationParser
 */
```

it should be something more along the lines of:

```
/**
 * A translation serializer that can render JSON formatted as an Application Resource Bundle (ARB).
 *
 * See https://github.com/google/app-resource-bundle/wiki/ApplicationResourceBundleSpecification
 *
 * ```
 * {
 *   "@@locale": "en-US",
 *   "message-id": "Target message string",
 *   "@message-id": {
 *     "type": "text",
 *     "description": "Some description text",
 *     "x-locations": [
 *       {
 *         "start": {"line": 23, "column": 145},
 *         "end": {"line": 24, "column": 53},
 *         "file": "some/file.ts"
 *       },
 *       ...
 *     ]
 *   },
 *   ...
 * }
 * ```
 */
```

**Comment by alan-agius4** [comment]
@petebacondarwin update the JSON comment.

**Review by petebacondarwin — APPROVED** [review]
Great. Thanks!

**Comment by axferch89** [comment]
Thx

**Pull request closed without merging**
