### PR TITLE
docs: fix html tags in changelog

### PR DESCRIPTION
**Pull request by macjohnny**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
the tags are interpreted as html instead of being shown when viewing the changelog

Issue Number: N/A

## What is the new behavior?
the tags are shown as code

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx!
Could you please change the commit message to `docs: ...`?

**Comment by macjohnny** [comment]
@gkalpak I updated the commit message

**Review by gkalpak — APPROVED** [review]

**Comment by macjohnny** [comment]
@gkalpak the build error seems to be unrelated to this change

**Comment by gkalpak** [comment]
merge-assistance: The Material tests failure is unrelated to this PR.

**Comment by macjohnny** [comment]
@gkalpak all CI tests pass

**Comment by matsko** [comment]
@macjohnny please rebase.

**Comment by matsko** [comment]
Also get rid of the 2nd commit (the merge one).

**Comment by macjohnny** [comment]
@gkalpak @matsko I rebased the PR. now it has only one commit with the correct commit message, and the tests pass, so it should be good to go. sorry for the inconveniences

**Pull request closed without merging**
