### PR TITLE
refactor(core): Remove `ReflectiveInjector` symbol

### PR DESCRIPTION
**Pull request by JeanMeche**
ReflectiveInjector has been replaced since v5 and deprecated in v8, let's remove this. 

- [x] Refactoring (no functional changes, no api changes)
- [x] Removing deprecated code 

## Does this PR introduce a breaking change?

- [x] Yes

What are the impacts at google ? Is this API still used ?

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

This is a breaking change and can't land until v16

Reviewed-for: benchpress

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-core, fw-benchmarks

**Comment by AndrewKushnir** [comment]
@JeanMeche could you please rebase this PR (and resolve conflicts) when you get a chance? We'll try to perform the necessary cleanup in Google's codebase by v16 to unblock this.

**Comment by AndrewKushnir** [comment]
[Global Presubmit](https://test.corp.google.com/OCL:514280651:BASE:514280680:1678074955364:5af9624a).

**Comment by AndrewKushnir** [comment]
[Global Presubmit #2](https://test.corp.google.com/OCL:519586532:BASE:519586468:1679881023893:788143b1).

**Comment by AndrewKushnir** [comment]
**Caretaker note**: this PR would also require [this change](http://cl/519586565) in g3.

**Comment by AndrewKushnir** [comment]
[Global Presubmit #3](https://test.corp.google.com/OCL:520515724:BASE:520515661:1680146334511:7e9b864f).

**Comment by dylhunn** [comment]
@AndrewKushnir Just wondering if this is landable? It seems like you've been running a lot of TGPs, but I'm unsure of the status

**Comment by AndrewKushnir** [comment]
> Just wondering if this is landable?

@dylhunn not yet, still waiting for a couple CLs to land....

**Comment by AndrewKushnir** [comment]
[Presubmit #4](https://test.corp.google.com/OCL:520515724:BASE:521642204:1680581082921:1aa63885).

**Review by AndrewKushnir — APPROVED** [review]

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api, circular-dependencies

**Comment by AndrewKushnir** [comment]
**Caretaker note**: g3 cleanup is completed 🎉 This PR is now ready for merge (once CI run is completed). Please sync this PR into g3 as a **separate change**.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 3b863ddc1e67a2fa7627ad78e172c839781e81b6.

**Pull request closed without merging**
