### PR TITLE
refactor(router): use native functions instead of custom utils

### PR DESCRIPTION
**Pull request by JeanMeche**
Quick refactor on Router's collection utils : 

* `flatten()` => `flat()` (Something similar was done on Core with #48358) 
* `last()` => `at(-1)`
* `forEach()` => `Object.entries/values/keys().forEach()`
* `and()` => `every()`

### CODE REVIEW

**Comment by atscott** [comment]
I think we're going to need to revert the `at(-1)` change. `at` is only available when targeting ES2022 output. This is causing a lot of build failures in presubmits.

**Comment by JeanMeche** [comment]
> I think we're going to need to revert the `at(-1)` change. `at` is only available when targeting ES2022 output. This is causing a lot of build failures in presubmits.

Yep, I went too far with that one. I restored `last()`.

**Review by atscott — APPROVED** [review]

**Comment by dylhunn** [comment]
Oy vey. `rif_platform` is importing `ɵflatten as flatten`, causing presubmit failures. Should be a fairly mechanical cleanup, I'll go fix it.

**Comment by dylhunn** [comment]
caretaker: merge only after [this cleanup CL](https://critique.corp.google.com/cl/513059801) is submitted.

**Review by dylhunn — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 6d9e979be1f5e731464b35c85769488725a7245c.

**Comment by jessicajaniuk** [comment]
That cleanup CL seems to have not been enough to capture all use cases.

**Comment by jessicajaniuk** [comment]
You can see the failures here: https://fusion2.corp.google.com/presubmit/tap/513345426/OCL:513345426:BASE:513345728:1677710416765:262c73cb/targets

**Comment by atscott** [comment]
[Additional cleanup CL](https://critique.corp.google.com/cl/513360384)

**Comment by dylhunn** [comment]
caretaker: next cleanup cl has merged

**Comment by jessicajaniuk** [comment]
This has safely landed.

**Pull request closed without merging**
