### PR TITLE
fix(core): Allow modification of lifecycle hooks any time before bootstrap

### PR DESCRIPTION
**Pull request by mhevery**
[Rebase of #45464 onto `10.0.x`](https://github.com/angular/angular/pull/35464#issuecomment-659065231)

--------

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
FYI, this is patch-only version of the PR #35464 that was reviewed and approved, so no additional reviews are required.

**Comment by ramtob** [comment]
@mhevery 
Thanks very much for this fix.
Will it be added to version 9.x also?

**Comment by mikaelboff** [comment]
We need this o 9.x too, it'll be done too? @AndrewKushnir  @mhevery

**Comment by mlc-mlapis** [comment]
I think that it§s necessary to count on the fact that it won't be added to any previous versions. As usual, new features flow only forward. Where is the problem with such logic? The difference between 9 and 10 is not so significant so it's easy to migrate.

**Comment by mikaelboff** [comment]
makes sense @mlc-mlapis

**Comment by ramtob** [comment]
> I think that it's necessary to count on the fact that it won't be added to any previous versions. As usual, new features flow only forward. Where is the problem with such logic? The difference between 9 and 10 is not so significant so it's easy to migrate.

It happens that I am partly dependent on applications that do not make upgrades often. So waiting for them to upgrade to version 10 might take months. Not that I am asking for personal favors :) I thought it was due naturally to enter version 9, since the issue was opened when Angular was at version 9. Angular switched to version 10 when the PR was still in process.

**Comment by ramtob** [comment]
P.S. and what is this "patch" for anyway? Why is there a PR for a "patch" beside the original PR? I thought it was related too to fixing previous versions.

**Comment by petebacondarwin** [comment]
"Patch" is the version branch that is currently receiving bug fixes.  Currently  this is 10.0.x.
"Master" is the version currently receiving active development,  which will result in 10.1.0.

**Comment by ramtob** [comment]
> "Patch" is the version branch that is currently receiving bug fixes. Currently this is 10.0.x.
> "Master" is the version currently receiving active development, which will result in 10.1.0.

Thanks. Which reminds me: this PR is a fix, not a feature. Which also seems to provide a reason for applying it to version 9 too..

**Comment by petebacondarwin** [comment]
Yes, patch (10.0.x) receives only bug fixes, not features; master receives features, which will end up in 10.1.0.

**Comment by mlc-mlapis** [comment]
[**@ramtob**](https://github.com/ramtob) It certainly would fine to have it also in 9.x, but it would also mean significant circumstances and additional costs. Just imagine how standard development flow is going on. It starts at some point. All surrounding things are changing from day to day, even new versions and so. You, as a developer, you are keeping your work up-to-date with all the latest changes, continuously merging, so in the end, you finish your work in a different situation than you have been started.

**Comment by BryanYin** [comment]
This bug is critical, all reasons listed in the original issue. So it should be ported to v9, as per stated below:

All of our major releases are supported for 18 months.

6 months of active support, during which regularly-scheduled updates and patches are released.
12 months of long-term support (LTS), during which only critical fixes and security patches are released.

VERSION | STATUS | RELEASED | ACTIVE ENDS | LTS ENDS
-- | -- | -- | -- | --
^10.0.0 | Active | Jun 24, 2020 | Dec 24, 2020 | Dec 24, 2021
^9.0.0 | Active | Feb 06, 2020 | Aug 06, 2020 | Aug 06, 2021
^8.0.0 | LTS | May 28, 2019 | Nov 28, 2019 | Nov 28, 2020

**Comment by bryanrideshark** [comment]
If you started using 9.x and then realized this bug, you obviously have learned how to live with it, or you've downgraded to Angular 8.

Upgrading to Angular 10 may be an issue to people because of policies, but you've already made compromises if you're using Angular 9 with this bug. I don't think we should demand the team backport this rather extensive PR just to satisfy our policies.

**Comment by mikaelboff** [comment]
any updates?

**Comment by mlc-mlapis** [comment]
@[**mikaelboff**](https://github.com/mikaelboff) Update for what?

**Comment by mikaelboff** [comment]
didn't saw it was released, thanks @mlc-mlapis

**Comment by mhevery** [comment]
> We need this o 9.x too, it'll be done too? @AndrewKushnir @mhevery

Sorry, this will not be added to v9. If you need this functionality please upgrade to latest code.

**Pull request closed without merging**
