### PR TITLE
[7.2.x] ivy+docs-infra: compile angular.io with Ivy

### PR DESCRIPTION
**Pull request by gkalpak**
Backports most commits from #26947 to 7.2.x. 

Most ivy-related changes are merged into master only, so building aio with ivy does not work on 7.2.x, but as many of the changes as possible have been backported in order to avoid unnecessary deviation of the master branch and reduce the likelihood of merge conflicts for future backports to 7.2.x.

### CODE REVIEW

**Comment by gkalpak** [comment]
merge-assistance: The `test_ivy_aot` failure is "inherited" from upstream.

**Review by petebacondarwin — COMMENTED** [review]
The message in 

> refactor(docs-infra): get rid of `on` component input

is no longer accurate.

Ivy does allow this, but we are choosing to refactor it for other reasons.

**Comment by petebacondarwin** [comment]
I'm not convinced that 

>  ci(docs-infra): compile with Ivy

should be backported, since we should not be trying to compile with ivy in 7.2.x, right?

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Just the one change to the commit message - otherwise LGTM

**Comment by gkalpak** [comment]
Updated the commit message.

**Review by petebacondarwin — APPROVED** [review]

**Comment by gkalpak** [comment]
Merged as [a9a095d44 - c64e66675][1].

[1]: https://github.com/angular/angular/compare/a9a095d44~1...c64e66675

**Pull request closed without merging**
