### PR TITLE
refactor(docs-infra): add new Input for better description of close button in notification component

### PR DESCRIPTION
**Pull request by ferrorenan**
Problem: 
The close icon on the announcement should read "Close {description of banner}", this is a reusable component.

Solution proposal:
Add a new input for banner description with default value, allowing the insertion of other descriptions and if nothing is passed, it assumes a default value.

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@ferrorenan Thanks for the PR! Can you update this to not use `feat`? This is definitely a refactor, and features get restricted to specific targeted branches. Also `(close button)` is not a valid scope for commits. So you'll have failing lint errors. Since this is AIO, you can probably just update this PR to `refactor(docs-infra): [your commit message here]` since that's what this PR affects. You can see all the scopes and types on [the CONTRIBUTING.md file](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format) in the repo.

**Comment by ferrorenan** [comment]
@jessicajaniuk Sure, sorry! Adjusted and thanks a lot for the help!

**Comment by jessicajaniuk** [comment]
@ferrorenan Ah it looks like you updated the PR header but not the actual commit message itself. Can you update that with a a git commit --amend and then force push that change?

**Comment by ferrorenan** [comment]
@jessicajaniuk  I'm sorry, It's ok now!?

**Comment by jessicajaniuk** [comment]
@ferrorenan Sorry for all the back and forth here. Now you have all the scope and typing correct, but lint is complaining about a lack of a body message. Here's what that looks like:

```
refactor(docs-infra): add new Input for better description of close button in notification component
  Error:
    The commit message body does not meet the minimum length of 20 characters
  
  The expected format for a commit is: 
  <type>(<scope>): <summary>
  
  <body>
```

So essentially do the same thing you did before, but just add a body to the commit and you should be good. You'll also need to sign the CLA that's mentioned in an earlier comment. Once you do those things, I think we can merge.

Again, sorry for all the back and forth.

**Comment by ferrorenan** [comment]
@jessicajaniuk Adjusted, Thank you so much for all your help, it's my first time here! Now it's ok!?

**Comment by jessicajaniuk** [comment]
@ferrorenan Awesome! Looks like all those issues are in order. We're seeing a failing test due to size changes, which is not really your fault. You just tipped the size over the edge. I'll add a fixup commit for you to save you the pain of dealing with that. Thanks for working through all the lint / CLA issues!

**Comment by ferrorenan** [comment]
@jessicajaniuk Perfect, thank you! Do I need to do anything else!?

**Review by jessicajaniuk — APPROVED** [review]

**Review by dylhunn — APPROVED** [review]
reviewed-for: size-tracking

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 84478f5a1c8be239641ad0b100f640903508e09c.

**Comment by jessicajaniuk** [comment]
@ferrorenan Thanks for your work on this! We really appreciate your taking the time and energy to contribute.

**Pull request closed without merging**
