### PR TITLE
fix(core): use addCustomEqualityTester instead of overriding toEqual

### LINKED ISSUE #22939: Custom toEqual matcher doesn't propagate custom equality testers
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The custom toEqual matcher in packages/platform-browser/testing/src/matchers.ts doesn't propagate custom equality testers that have been registered via jasmine.addCustomEqualityTester. 

## Expected behavior
The toEqual function should take a second argument (after "util") which is the list of registered customEqualityTesters, and include it in the array passed to util.equals. See the original jasmine implementation for an example: https://github.com/jasmine/jasmine/blob/master/src/core/matchers/toEqual.js

## Minimal reproduction of the problem with instructions
Register a custom equality tester with jasmine.addCustomEqualityTester that would return a different result than the regular toEqual logic, call toEqual with values that should trigger it, watch it fail.

## What is the motivation / use case for changing the behavior?
I would like my custom equality testers to work.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by KevinVillela**
This propagates other custom equality testers added by users. Additionally, if
an Angular project is using jasmine 2.6+, it will allow Jasmine's custom object
differ to print out pretty test error messages.

fixes #22939

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
[x] Kind of?
```

It may break (well, fix) tests that add matchers which were not being invoked. Now that those matchers will be invoked, some tests that weren't testing things correctly will start to do so, and that could cause test failures.

### CODE REVIEW

**Comment by KevinVillela** [comment]
Friendly ping, I know y'all are busy but this PR seems pretty innocuous, and I think a lot of people would want to have their nice jasmine differs and custom equality checkers back.

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
http://test/OCL:202952812:BASE:202952835:1530544443627:d8926531

**Comment by KevinVillela** [comment]
Ah dang, so all these tests pass but the google3 ones don't? Is there action required by me to make that work, or is that something the project maintainers handle?

**Comment by mhevery** [comment]
I think https://github.com/angular/angular/pull/22983/commits/5671dccc4d37e83be2d8a9b4babf97ccfe7b9aa9 will fix it...

**Comment by mhevery** [comment]
http://test/OCL:202952812:BASE:203013823:1530567229011:65b7b5f3

**Comment by mhevery** [comment]
http://test/OCL:202952812:BASE:203018390:1530568887320:ef26e311

**Pull request closed without merging**
