### PR TITLE
docs(compiler): fix typos in architecture.md

### PR DESCRIPTION
**Pull request by pmartijena**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Fix a typo

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by pmartijena** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Review by sonukapoor — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
@pmartijena thanks for improving Angular docs!

Could you please squash all commits into one and update commit message to include the "docs" scope into it like this:

```
docs: fix typo in architecture.md guide
```

Thank you.

**Comment by pmartijena** [comment]
@AndrewKushnir Sure! Sorry about that, was updating it as I read it.

**Comment by pmartijena** [comment]
@AndrewKushnir Just checking that I squashed it correctly? Commit d0a374e has everything in it that was changed.

**Comment by sonukapoor** [comment]
> @AndrewKushnir Just checking that I squashed it correctly? Commit [d0a374e](https://github.com/angular/angular/commit/d0a374e631b73e6fd6810e8f7186eaf7e2cafc49) has everything in it that was changed.

Hi @pmartijena. They are not fully squashed yet. You need to rebase to squash the commits together. Here is a quick video on how to do this:

https://twitter.com/stephenfluin/status/1009904095073718275?lang=en

**Comment by pmartijena** [comment]
@sonukapoor awesome...thanks. First time squasher :)

**Comment by AndrewKushnir** [comment]
Thanks for updating this PR @pmartijena, everything looks good now and I'm adding this PR to the merge queue.

**Pull request closed without merging**
