### PR TITLE
docs: adding Doguhan Uluca as GDE resource

### PR DESCRIPTION
**Pull request by duluca**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?
Added new bio to Angular.io

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by duluca** [comment]
@kapunahelewong I had to create a new PR. I found myself in a situation having other people's commits in my branch. Followed your awesome guide, but as I was rolling back commits... let's just say things got complicated :)

**Comment by kapunahelewong** [comment]
Aw @duluca, I call those "git tangles". Is there anything that could be clarified in my notes? If it happens again, please let me know and I can look on my end to see if I can help. 🌺

**Review by kapunahelewong — APPROVED** [review]

**Comment by duluca** [comment]
@kapunahelewong Can I get an assist in getting this resolved?

**Comment by kapunahelewong** [comment]
Hey, @duluca, we still need marketing review. I've added the `PR action: review` to help clarify that you're ready for them to take a look. Thanks for your patience. :)

**Comment by duluca** [comment]
@fw-docs-marketing are you able to review?

**Comment by duluca** [comment]
@kapunahelewong should I close and re-create a PR? Perhaps it fell off the review radar?

**Comment by kapunahelewong** [comment]
Hi @duluca, no need to close this one - if we need to rebase, I can do it for you. Let me reach out and see if I can get us some help. With everything in flux, it may have just been overlooked. Thanks for the tag. I'll be back. :)

**Review by StephenFluin — APPROVED** [review]

**Comment by kara** [comment]
@kapunahelewong @duluca Can one of you rebase this? It's a bit too old to work with the merge script.

**Comment by duluca** [comment]
@Kapunahelewong you’re the rebase master. I made a mess of it last time. I’d appreciate the assist very much so 🙏

**Comment by kapunahelewong** [comment]
Hey @duluca! Sure thing, but I tried to force push and get:

```
Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 8 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 28.17 KiB | 14.09 MiB/s, done.
Total 9 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
To https://github.com/duluca/angular.git
 ! [remote rejected]       docs/contributors-gde-doguhan-uluca -> docs/contributors-gde-doguhan-uluca (permission denied)
error: failed to push some refs to 'https://github.com/duluca/angular.git'
```

Looks like it works and then says permission denied.

Could you maybe invite me as a collaborator (in your fork's settings --> manage access)? I've never had to do this before, but since it says permission denied, maybe that will let me do it. Feel free to ping me on gitter or twitter if chatting through it's easier. Thanks!

**Comment by duluca** [comment]
@kapunahelewong I checked the `allow edit from maintainers` box. Is that it?

**Pull request closed without merging**
