### PR TITLE
fix(docs-infra): remove entry components from aio codebase

### PR DESCRIPTION
**Pull request by ajitsinghkaler**
Angular version 9 no longer need entry components in the code so clean up remaining entry components in the aio codebase

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Extra code of entry components
Issue Number: N/A

## What is the new behavior?
Removed extra code of entry components

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ajitsinghkaler** [comment]
@petebacondarwin can you please have a look

**Comment by ajitsinghkaler** [comment]
@petebacondarwin can you please explain why these tests are failing

**Comment by petebacondarwin** [comment]
Sorry I have been overloaded with ngcc stuff today. Let me take a look

**Comment by petebacondarwin** [comment]
I believe the problem is that we test both ivy and ViewEngine builds of AIO. While the entry components are no longer needed for ivy, they are needed for ViewEngine, so we cannot actually remove these from the code base until we decide to stop testing AIO under ViewEngine.

**Pull request closed without merging**
