### PR TITLE
docs: add Sonu Kapoor to the collaborator list

### PR DESCRIPTION
**Pull request by sonukapoor**
After 6 months of continuous contributions, Sonu Kapoor did finally make
it into the collaborator list.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sonukapoor** [comment]
@gkalpak is this a new flake?

**Comment by CaerusKaru** [comment]
@sonukapoor Do you have a mentor you can add to the config?

**Comment by sonukapoor** [comment]
> @sonukapoor Do you have a mentor you can add to the config?

Not yet. Cindy will confirm soon. I can submit a new PR once I know.

**Review by aikithoughts — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by aikidave** [comment]
Yay, @sonukapoor!

**Pull request closed without merging**
