### PR TITLE
Copy animations API doc back to stable

### PR DESCRIPTION
**Pull request by jbogarthyde**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A
PR https://github.com/angular/angular/pull/23682 was merged into next, which is correct but only partially complete. The same content needs to be merged into stable. This PR is to address that oversight on our PR target for previous PR. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by jbogarthyde** [comment]
This is just moving the target from next to stable - original target was v6, it just took a long time to get merged. 
I don't know why it's not passing the travis build now, but the entire PR was already approved and merged into master, so it should be fine for master&patch.

**Comment by mhevery** [comment]
http://test/OCL:200637460:BASE:200638884:1529018965642:39ed99d6

**Review by jenniferfell — APPROVED** [review]
LGTM. Same files as previous PR. I didn't go deep into the content because those files were already reviewed and approved in previous PR.

**Comment by jenniferfell** [comment]
@mhevery @matsko : Hi. Sorry to bother you. When you get a moment, we need your approval...and then this is ready to mark for merge. Thanks!

The story: The Animations API updates (PR #23682) was merged into next, which is correct but only partially complete. The same content needs to be merged into stable. We forgot to update the PR target on 23682 after v6 was released, so it was only marked for next. This PR is to merge the same content into stable, so next and stable are in sync again and both have the new Animations API work.

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
merged as aa66e84e44

**Pull request closed without merging**
