### PR TITLE
Steal and adapt changelog script from angularjs

### PR DESCRIPTION
**Pull request by yjbanov**

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@yjbanov wouldn't a separate module (https://github.com/ajoslin/conventional-changelog) that we've got now work here instead of copy & paste of the code?

**Comment by yjbanov** [comment]
@pkozlowski-opensource I've never heard of that module. Does it conform to Angular's message formatting? Not that I'm attached to our commit message style, but the script parses out message types and components and organizes the changelog accordingly. Personally, I'd be fine if we just produced a flat printout of commit messages in chronological order.

@IgorMinar, what do you think?

**Comment by pkozlowski-opensource** [comment]
@yjbanov yes, this module was created based on Angular commit conventions. I would say - let's give it a try and change it if it doesn't work. @ajoslin is behind this module, so I'm pretty positive we could change it if needed.

**Comment by yjbanov** [comment]
Switched to `conventional-changelog`. @pkozlowski-opensource PTAL.

**Pull request closed without merging**
