### PR TITLE
Port CanActivate bug fix to 2.4.x

### PR DESCRIPTION
**Pull request by nertzy**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
See #13530

**What is the new behavior?**
See #13929

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by DzmitryShylovich** [comment]
it will be available in the next 2.x release

**Comment by nertzy** [comment]
I signed it!

**Comment by nertzy** [comment]
My goal is to get fd9667a8be13cdc763b0c6fe4d8157f07f848273 cherry-picked onto the 2.4.x branch. I've attempted to get my cherry-pick to show me as the commiter. Feel free to do it yourselves if we can't get the CLA thing worked out.

**Comment by DzmitryShylovich** [comment]
the question is why? fixes go into 2.x and 4.x branches.
features or breaking changes in 4.x

**Comment by nertzy** [comment]
Ok I guess I don't understand the versioning policy. So I should expect this fix in 2.5 but not in some potential 2.4.X version? Feel free to close this if so.

**Comment by devoto13** [comment]
@nertzy fix commits from master branch will be cherry-picked and included into next 2.4.x release. No need to open extra PRs. You can close this PR yourself 😉

**Pull request closed without merging**
