### PR TITLE
feat(http): add toString method for request class

### PR DESCRIPTION
**Pull request by CSchulz**
**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
There is no toString method for Request, which results into `[object Object]`.

**What is the new behavior?**
It returns `Request for URL: http://localhost:8080/api using method: Get`.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by Toxicable** [comment]
What is the reason for this PR? What use cases does this API solve?

**Comment by CSchulz** [comment]
It allows directly logging of the Request similar to the Response.

**Comment by Toxicable** [comment]
@CSchulz why does that need to be in the Core framework though? it sounds like a very Domain and specific issue that you're trying to solve

**Comment by CSchulz** [comment]
Why does Response has this method? In general it makes it easier for debugging purposals if anyone tries to print out the Request.

**Comment by splincode** [comment]
@CSchulz module http is deprecated, please close PR

**Comment by CSchulz** [comment]
Closed in favor of #22822 .

**Pull request closed without merging**
