### PR TITLE
docs(router): use Resolve interface for custom title resolver

### PR DESCRIPTION
**Pull request by markostanimirovic**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Custom title resolver doesn't implement `Resolve` interface.

Issue Number: N/A

## What is the new behavior?

Custom title resolver implements `Resolve` interface.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@markostanimirovic the change looks good, thanks for improving Angular docs!

**Comment by AndrewKushnir** [comment]
@markostanimirovic it looks like one of the CI jobs failed with a lint error. Could you please try to run the `eslint content/examples` [as mentioned in the CI job log](https://app.circleci.com/pipelines/github/angular/angular/42193/workflows/75a8f819-ffb5-46a3-8a03-6b22587f68a3/jobs/1115348) and update the change? Thank you.

**Comment by markostanimirovic** [comment]
@AndrewKushnir

Lint is fixed now. However, tests failed for some reason 🤔

**Comment by jessicajaniuk** [comment]
This PR has conflicts with `13.2.x`. I've updated the target to minor and will merge. Please create a patch PR targeting `13.2.x` to get this change to land there.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit fc1c143594b0970d7aa6422047cf2b11ce082e40.

**Comment by markostanimirovic** [comment]
> This PR has conflicts with `13.2.x`. I've updated the target to minor and will merge. Please create a patch PR targeting `13.2.x` to get this change to land there.

@jessicajaniuk

File `router/src/app/app-routing.module.10.ts` doesn't exist on the `13.2.x` branch. It seems that [this commit](https://github.com/angular/angular/commit/910de8bc3379b1452c0bc23a866b5108d6d94e55) is missing.

**Comment by AndrewKushnir** [comment]
Sorry, that was my bad: I put "target: patch", which instructs the tooling to merge the change to 13.2.x branch, when in fact the Router title code was merged to master only (since it's a new feature, so we can not merge it to the patch branch), so we don't need extra PR against 13.2.x branch.

**Pull request closed without merging**
