### PR TITLE
Remove unused methods and consts

### PR DESCRIPTION
**Pull request by alan-agius4**

### CODE REVIEW

**Review by dgp1130 — APPROVED** [review]
Have we run this through TGP? Removing AJD imports seem like it could have very nuanced effects which are hard to anticipate. AJD doesn't exist anymore, but it's been replaced by JSTrimmer which fills a similar role, so I'm not sure how load-bearing these imports are.

**Comment by alan-agius4** [comment]
@AndrewKushnir @dgp1130 remove the AJD-related code from this PR and opened https://github.com/angular/angular/pull/48363

**Comment by alan-agius4** [comment]
TAP https://test.corp.google.com/OCL:493045661:BASE:493032632:1670264565365:ae699b39

**Review by AndrewKushnir — APPROVED** [review]
@alan-agius4 thanks for the cleanup! 👍

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit cf51690341a3d1b4fecfa950814db4ea426794cb.

**Pull request closed without merging**
