### PR TITLE
chore(doc-gen): generate router typings file

### LINKED ISSUE #2659: router needs type definitions to accompany router bundle
https://github.com/borisyankov/DefinitelyTyped/blob/master/angular2/angular2.d.ts doesn't contain any info about router or http services, which makes them hard to use from a bundle.

### PR DESCRIPTION
**Pull request by petebacondarwin**
Closes #2659

### CODE REVIEW

**Comment by alexeagle** [comment]
Sorry for the delay, got caught up with celebratory Independency Day barbecue lunch distraction.

I'm still novice in this codebase, looks very reasonable. I guess we don't have any automated tests covering this?

**Comment by petebacondarwin** [comment]
There are no unit tests for this processor (shame face) but I could knock
some up.
The real issue is whether the actual output is any use.
Currently there is some stuff hardcoded in the template that is probably
not for the router dts file.

**Comment by tbosch** [comment]
@petebacondarwin Please find someone that can verify this is correct

**Comment by alexeagle** [comment]
I fetched the PR and built the file. I think the hardcoded section at the top needs to move so it only appears in angular2.d.ts.

**Comment by petebacondarwin** [comment]
I have moved out the hard coded bits from the router file. Is there a tool I can run on the generated files to check they are valid?

**Comment by petebacondarwin** [comment]
and rebased.

**Pull request merged**
