### PR TITLE
feat: upgrade clang-format.

### PR DESCRIPTION
**Pull request by mprobst**

### CODE REVIEW

**Comment by mprobst** [comment]
Note that the indentation sucks:

```ts
class X {
  constructor({selector, properties, events, hostListeners, hostProperties,
               hostAttributes}: {
    selector?: string,
    properties?: any,
    events?: List<string>,
    hostListeners?: StringMap<string, string>,
    hostProperties?: StringMap<string, string>,
    hostAttributes?: StringMap<string, string>,
  } = {}) {
    super();
    this.selector = selector;
    this.properties = properties;
    this.events = events;
    this.hostListeners = hostListeners;
    this.hostProperties = hostProperties;
    this.hostAttributes = hostAttributes;
  }
}
```

I wonder how this should get indented, ideally? This doesn't seem like a huge improvement:

```ts
class X {
  constructor({
    selector,
    properties,
    events,
    hostListeners,
    hostProperties,
    hostAttributes
  }: {
    selector?: string,
    properties?: any,
    events?: List<string>,
    hostListeners?: StringMap<string, string>,
    hostProperties?: StringMap<string, string>,
    hostAttributes?: StringMap<string, string>,
  } = {}) {
    super();
    this.selector = selector;
    this.properties = properties;
    this.events = events;
    this.hostListeners = hostListeners;
    this.hostProperties = hostProperties;
    this.hostAttributes = hostAttributes;
  }
}
```

Essentially I guess the syntax just isn't very nice.

@vicb FYI.

**Comment by vicb** [comment]
@mprobst not perfect yet but a little closer :)

**Comment by mprobst** [comment]
@vicb you mean the current state is an improvement already, or do you mean we should try to implement the second case?

**Comment by vicb** [comment]
The current state seems closer to the current formatted code, seems like an improvement to me

**Pull request closed without merging**
