### PR TITLE
Updates the README changelog link text to capture more of the surrounding text

### PR DESCRIPTION
**Pull request by CodeMaster7000**
docs: update `README.md` to improve changelog link

Updates the README changelog link text to capture more of the
surrounding text.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by devversion** [comment]
Hi, thank you for this PR. I'm happy to accept this PR but you would need to sign CLA and fix the commit message (see `lint` job). Happy to re-open then. Thx!

**Comment by CodeMaster7000** [comment]
I have signed the CLA now.

**Comment by devversion** [comment]
@CodeMaster7000 Thanks for signing the CLA. Basically you would perform the following steps:

* `git commit --amend`
* Change the description from `Update README.md to improve formatting` to something like: 

```
docs: update `README.md` to improve changelog link`

Updates the README changelog link text to capture more of the
surrounding text.
```
* Then push the change with something like: `git push origin HEAD:patch-2 --force-with-lease`

**Comment by CodeMaster7000** [comment]
That is complete now

**Comment by devversion** [comment]
@CodeMaster7000 Thank you. You actually just changed the PR title here, but the commit is still incorrect. Please see for help: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by CodeMaster7000** [comment]
@devversion Thanks for the feedback. I am just getting to the grips with committing to open-source projects and using Git, so I am not too familiar with it. However, I will try to have the changes done within the next day.

**Comment by CodeMaster7000** [comment]
Is there a way that this PR can be merged without running Git commands? I am new to using Git and it is time-taking and confusing.

**Comment by devversion** [comment]
Unfortunately not. We enforce a strict format in commit messages, and fixing them up for every contribution would slow down the process. Sorry!

I would recommend just re-creating the changes and then specifying the right commit message in GitHub. That way you wouldn't need to use Git.

**Pull request closed without merging**
