### PR TITLE
docs: fix typo in housing.service.ts lesson 12

### PR DESCRIPTION
**Pull request by alpha-mouse**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, thank you for improving the docs ! 

Could you also do the same change in `first-app-lesson-13/src/app/housing.service.ts`, there is the same issue !

**Comment by alpha-mouse** [comment]
Hi! I actually did, but in a separate PR: https://github.com/angular/angular/pull/50388. Can close that one and update this if that'd be more convenient for everyone. Should I?

**Comment by JeanMeche** [comment]
Yeah that would be less work for the team thanks !

**Comment by alpha-mouse** [comment]
done

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Pull request closed without merging**
