### PR TITLE
docs(docs-infa): fix typo in Architecture overview page

### PR DESCRIPTION
**Pull request by calendee**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Architecture overview docs has a typo

Issue Number: N/A

## What is the new behavior?
Corrected the typo

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks for the PR @calendee! I left you some feedback. Then once its goes through CI it should be ready to land.

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update the commit message to `docs: fix typo in Architecture overview page`

**Comment by calendee** [comment]
@brandonroberts Why not use `docs-infra` for the scope?  The CONTRIBUTING.md indicates I should?'

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#scope

> docs-infra: used for docs-app (angular.io) related changes within the /aio directory of the repo

FYI: I just realized I spelled it `docs(docs-infa)` instead of `docs(docs-infRa)`.  If you'd like, I can change it to that.

**Comment by brandonroberts** [comment]
@calendee that scope is for changes to the aio application (infra)structure. There is an additional note below it.

`docs changes that are not related to a specific package (e.g. docs: fix typo in tutorial)`

**Comment by calendee** [comment]
I messed up the commit history when trying to edit it.  I'm closing this as I've replaced it with #25438 .  Sorry for the mess up and extra work.

**Comment by brandonroberts** [comment]
:+1:

**Pull request closed without merging**
