### PR TITLE
build: Update dependencies

### PR DESCRIPTION
**Pull request by GChuf**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by GChuf** [comment]
@devversion can you check this?
Should I include `rollup-plugin-node-polyfills` to dependencies?

`ci/circleci: build-npm-packages — Your tests failed on CircleCI `
```

INFO: From Bundling JavaScript packages/language-service/bundles/ivy.js [rollup]:
(!) Missing shims for Node.js built-ins
Creating a browser bundle that depends on 'os', 'constants', 'stream', 'util', 'assert' and 'path'. You might need to include https://github.com/ionic-team/rollup-plugin-node-polyfills
INFO: From Bundling JavaScript packages/language-service/bundles/language-service.js [rollup]:
(!) Missing shims for Node.js built-ins
Creating a browser bundle that depends on 'path'. You might need to include https://github.com/ionic-team/rollup-plugin-node-polyfills
INFO: From ng_package: Rollup umd //packages/platform-server:npm_package:
(!) Missing shims for Node.js built-ins
Creating a browser bundle that depends on 'url'. You might need to include https://github.com/ionic-team/rollup-plugin-node-polyfills

Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by AndrewKushnir** [comment]
It looks like PR conflicts with the master branch. Also since it was created a few months ago, I believe package versions are likely changed since that time, so I'm closing this PR. Please create a new one (with most recent versions) if package updates are needed. Thank you.

**Comment by GChuf** [comment]
@AndrewKushnir I can open another PR, if you - or someone else - will check it. Else, if it takes 3 months before someone merges it, it will be outdated again. So should I open another PR and tag you when it's ready?

**Comment by AndrewKushnir** [comment]
Hi @GChuf, thanks for the reply. Sorry that we didn't have a chance to review your PR sooner.
Let me check with the team on what's the best way to proceed with dependency updates like this and I'll get back with an answer.

**Comment by GChuf** [comment]
@AndrewKushnir any news?

**Comment by AndrewKushnir** [comment]
@GChuf sorry for the delay. We've discussed that with the team and we plan to evaluate solutions to create PRs with updated dependencies automatically (like https://dependabot.com/). Meanwhile we'll be able to review (and merge) PRs with updated deps created manually, so if you have a chance to create one, please mentioned my account name there and we'll have a look. Thank you.

**Pull request closed without merging**
