### PR TITLE
feat(aio): class api page html template design

### PR DESCRIPTION
**Pull request by sjtrimble**
- Added `.md` file for HTML template on class API page layout.
- Updated CSS classes and styles to accommodate changes
- Is not fully mobile responsive, especially tables
- Will need to move the page-legend tags (view source for only API and suggest edits for all other documentation pages) so it applied to all pages accordingly

@petebacondarwin Is this enough for you to get started on the dgeni template?

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

Issue Number: #21715 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by petebacondarwin** [comment]
I'll give it a go...

**Comment by petebacondarwin** [comment]
@sjtrimble - by the way the changes to the CSS break the API page: https://pr21786-03e371c.ngbuilds.io/api

**Comment by IgorMinar** [comment]
fyi: the preview is here: https://pr21786-03e371c.ngbuilds.io/guide/api-page-class

I took a screenshot and annotated it: https://photos.app.goo.gl/ctbE8u4PXFgQ4Qop2

Below are descriptions / explanations for the annotations in the screenshot:

@sjtrimble a few notes:
- [ ] 1. breadcrumbs should say "API / @angular/core" not just "API / @core" - I know it's a mock but I just making sure we pull the right data for this
- [ ] 2. the overview has lots of left padding / offset on my screen. is that intentional?
- [ ] 3. @jbogarthyde have you considered moving the subclasses and seealso as a sidenote to the class overview? this would use up the space that would otherwise be blank and would shorten the page
- [ ] 4. (general problem): could you think of constraining the content width so that the page looks reasonable even on big screens? similar to how github uses only the center of the screen if you open it even on huge monitors? it is generally agreed that reading very wide paragraphs is difficult so having a reasonable max-width constraint for text is a best practice.
- [ ] 5. the constructor is missing param description - I thought we agreed that it would look similar to method
- [ ] 6. all methods should have some kind of indication of a return type, even if the type is `void`.
- [ ] in general and this applies to the class overview, constructor, properties and methods - our type syntax/notation should resemble the one used by typescript's d.ts files. take a look at this [core.d.ts](https://github.com/angular/angular/blob/master/tools/public_api_guard/core/core.d.ts) which captures the entire type surface of the public api of the @angular/core entry-point.
- [ ] 7. I'm not sure if a special "declarations" header is needed here. I think we should create a design that doesn't require this kind of header within a method section
- [ ] 8. (I'm not sure if this content is just a placeholder) the method type info should not contain the class wrapper, it should be just the method type signature
- [ ] 9. have we considered merging the method header and type signature => making the type signature the header? @jbogarthyde what do you think? I think that this would reduce the duplication, but there is a risk that the header would be too long if the signature is too long...
- [ ] 10. weird space / padding
- [ ] 11. is this going to be a zippy that is hidden by default? I'm afraid that this section is going to be adding too much noise. both the mock and today's httpclient overloads are quite hard to decipher and contrast with the main method signature.
- [ ] 12. is the placement of the description right? I think it should be above or below the signature
- [ ] 13. I'm hoping that many of these examples will actually be [embedded live examples](https://angular.io/guide/docs-style-guide#embedded-live-example) rather than embedded snippets, or snippets / [code tabs](https://angular.io/guide/docs-style-guide#code-tabs) that have a link to an external stackblitz. we should actually adjust the code tab component to have this link built in. All of these combined examples should always have an external link to open the example stackblitz.

that's it for now.... I'm sorry about the barrage of comments :-) Igor out...

**Comment by jbogarthyde** [comment]
3. @jbogarthyde have you considered moving the subclasses and seealso as a sidenote to the class overview? this would use up the space that would otherwise be blank and would shorten the page
     _Yes -- I would definitely prefer this, if it's possible. I was trying to make those less prominent._ 

 5. the constructor is missing param description - I thought we agreed that it would look similar to method
     _We did agree on that._

7. I'm not sure if a special "declarations" header is needed here. I think we should create a design that doesn't require this kind of header within a method section
     _Right, this is not supposed to be here - it got copied from the Function page, where it replaces "Overview"._
 
8. (I'm not sure if this content is just a placeholder) the method type info should not contain the class wrapper, it should be just the method type signature
    _I agree -- and it should be formatted with every param on a separate line --certainly not centered, either _

9. have we considered merging the method header and type signature => making the type signature the header? @jbogarthyde what do you think? I think that this would reduce the duplication, but there is a risk that the header would be too long if the signature is too long...
     _I would prefer NOT to put the whole signature in the header. It would certainly be too long in many cases, and could not me in code font. I think it's important to clarity for the signature to be formatted with every param on its own line, and the last line for the return type (unless there are no params)._

12. is the placement of the description right? I think it should be above or below the signature

I would prefer all description to be above the signature, and limited to 2 or 3 paragraphs. This is a matter of style - the complete description of each parameter should be with that parameter, not in the general description, and special cases can be called out in syntax examples. 

The same applies to the class as a whole -- I would like the one-liner short description and the 2-3 paragraph long description to go _before_ the code Overview.

Ideally, API doc should be a reference for syntax, with Xrefs to usage information in the related user guide. If there is no such guide yet, additional info can go into the Usage Notes at the bottom (not "Example", although it could include examples) - we should try to distinguish usage information from syntax information, and move it into the guide when possible.

**Comment by jbogarthyde** [comment]
3. @jbogarthyde have you considered moving the subclasses and seealso as a sidenote to the class overview? this would use up the space that would otherwise be blank and would shorten the page
     _Yes -- I would definitely prefer this, if it's possible. I was trying to make those less prominent._ 

 5. the constructor is missing param description - I thought we agreed that it would look similar to method
     _We did agree on that._

7. I'm not sure if a special "declarations" header is needed here. I think we should create a design that doesn't require this kind of header within a method section
     _Right, this is not supposed to be here - it got copied from the Function page, where it replaces "Overview"._
 
8. (I'm not sure if this content is just a placeholder) the method type info should not contain the class wrapper, it should be just the method type signature
    _I agree -- and it should be formatted with every param on a separate line --certainly not centered, either _

9. have we considered merging the method header and type signature => making the type signature the header? @jbogarthyde what do you think? I think that this would reduce the duplication, but there is a risk that the header would be too long if the signature is too long...
     _I would prefer NOT to put the whole signature in the header. It would certainly be too long in many cases, and could not me in code font. I think it's important to clarity for the signature to be formatted with every param on its own line, and the last line for the return type (unless there are no params)._

12. is the placement of the description right? I think it should be above or below the signature

I would prefer all description to be above the signature, and limited to 2 or 3 paragraphs. This is a matter of style - the complete description of each parameter should be with that parameter, not in the general description, and special cases can be called out in syntax examples. 

The same applies to the class as a whole -- I would like the one-liner short description and the 2-3 paragraph long description to go _before_ the code Overview.

Ideally, API doc should be a reference for syntax, with Xrefs to usage information in the related user guide. If there is no such guide yet, additional info can go into the Usage Notes at the bottom (not "Example", although it could include examples) - we should try to distinguish usage information from syntax information, and move it into the guide when possible.

**Comment by sjtrimble** [comment]
Responding to the concerns. Pete's template for reference: #21874 

From a design perspective items 4 & 9 are important, the rest are to dos to be implemented, app-wide items or further or still under discussion (overloads).

<hr>

> 1. breadcrumbs should say "API / @angular/core" not just "API / @core" - I know it's a mock but I just making sure we pull the right data for this

Yes, understood. I believe Pete has implemented this in #21874.

> 2. the overview has lots of left padding / offset on my screen. is that intentional?

That is not intended to be as such. There are some issues with the code blocks and color as well. Not sure when this changed. Can be easily addressed. I did not tackle in this PR as I wanted to give Pete something to work off of to get started.

> 3. @jbogarthyde have you considered moving the subclasses and seealso as a sidenote to the class overview? this would use up the space that would otherwise be blank and would shorten the page

> > Yes -- I would definitely prefer this, if it's possible. I was trying to make those less prominent.

The content might be of different lengths (vertically) and would look asymmetrical and not so visually appealing. I also recommend having the data placed in a hierarchical order that makes sense - not to add content simply to fill up the space. Also, this space will be a bit more visually condensed once the TOC is added back in.

> 4. (general problem): could you think of constraining the content width so that the page looks reasonable even on big screens? similar to how github uses only the center of the screen if you open it even on huge monitors? it is generally agreed that reading very wide paragraphs is difficult so having a reasonable max-width constraint for text is a best practice.

We do this on the marketing pages already - I think this would be ok to implement. Most designs group the TOC/sidenav with the content, and we do not do this. Just something to note. I think this should be tackled in a separate PR.

> 5. the constructor is missing param description - I thought we agreed that it would look similar to method

Yes, missing param description in this particular template. Will be included as discussed.

> 6. all methods should have some kind of indication of a return type, even if the type is void.
 in general and this applies to the class overview, constructor, properties and methods - our type syntax/notation should resemble the one used by typescript's d.ts files. take a look at this core.d.ts which captures the entire type surface of the public api of the @angular/core entry-point.

Yes, this would go in returns section where it says '_Returns information and results goes here._'

> 7. I'm not sure if a special "declarations" header is needed here. I think we should create a design that doesn't require this kind of header within a method section

Ok.

> 8. (I'm not sure if this content is just a placeholder) the method type info should not contain the class wrapper, it should be just the method type signature

Might need further explanation to make sure I understand the concern.

> 9. have we considered merging the method header and type signature => making the type signature the header? @jbogarthyde what do you think? I think that this would reduce the duplication, but there is a risk that the header would be too long if the signature is too long...

I recommend we keep the header simple - the intent is to allow users to quickly get to the content they are looking for and to avoid them getting lost inside code.

> 10. weird space / padding

Not supposed to be there. See item 2 comment above.

> 11. is this going to be a zippy that is hidden by default? I'm afraid that this section is going to be adding too much noise. both the mock and today's httpclient overloads are quite hard to decipher and contrast with the main method signature.

Still discussing options for this. Was not initially planning a collapsable table for this might imply it's not of the same value as the rest of the content.

> 12. is the placement of the description right? I think it should be above or below the signature

The intent was to have it on the right side of the code so you can easily cross check the differences between the overloads. Table format would be easier for readers to process and compare (description to description). This is being further discussed.

> 13. I'm hoping that many of these examples will actually be embedded live examples rather than embedded snippets, or snippets / code tabs that have a link to an external stackblitz. we should actually adjust the code tab component to have this link built in. All of these combined examples should always have an external link to open the example stackblitz.

I think this would be nice to have across all code blocks on the docs site. Perhaps we can make this a separate PR/issue as well as it affects all code blocks. Or would it?

**Comment by IgorMinar** [comment]
I think this PR is now obsolete. I believe @jenniferfell already created issues for all the unresolved things. If that's the case then can we close this PR? @jenniferfell ?

**Comment by sjtrimble** [comment]
@IgorMinar Yes, this was just an HTML mockup template for Pete to use for the real PR.

Should I delete? The content / convo might be useful to keep somehow. Now sure how you want to proceed.

Yes, @petebacondarwin added several issues today based on these comments, but @jenniferfell might want to review to make sure everything accounted for.

**Comment by petebacondarwin** [comment]
I didn't go through the comments here. I would only close when we're happy we captured anything important from the comments

**Comment by petebacondarwin** [comment]
We have now landed these changes.

**Pull request closed without merging**
