### PR TITLE
refactor(core): remove unused r2 debug code

### PR DESCRIPTION
**Pull request by JeanMeche**
`_createNgProbeR2` isn't called anymore, `ɵgetDebugNodeR2` isn't needed anymore. We can now remove it from the export in Core.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

### CODE REVIEW

**Review by dylhunn — APPROVED** [review]

**Comment by dylhunn** [comment]
Thanks for finding a potential bundle size improvement :)

**Comment by dylhunn** [comment]
Running presubmit: http://cl/513565319

**Comment by dylhunn** [comment]
caretaker: CI failures are from a stale branch and preexisting (the `flatten` failures from the other day)

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit e57d5db0458ad9ff3ac96534aeb3d1a31ca11280.

**Pull request closed without merging**
