### PR TITLE
build(aio): bump angular to 5.0.0-beta.4

### PR DESCRIPTION
**Pull request by IgorMinar**

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@IgorMinar - Shouldn't this file change too: https://github.com/angular/angular/blob/master/aio/tools/examples/shared/package.json

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
@IgorMinar - Shouldn't this file change too: https://github.com/angular/angular/blob/master/aio/tools/examples/shared/package.json

**Comment by petebacondarwin** [comment]
Also @IgorMinar I don't think you should bump the example versions of Angular if this is going to be merged into the patch branch.

**Comment by petebacondarwin** [comment]
We are now able to run and test the AIO application against the current build, which provides us good feedback about breaking changes. How about we close this PR and then upgrade to 5.0.0 final when it is released?

**Comment by IgorMinar** [comment]
yeah. I'm closing this. hopefully #19702 will stick - it's currently blocked on a size regression in cli.

**Pull request closed without merging**
