### PR TITLE
docs: fix link from zoneless to OnPush

### PR DESCRIPTION
**Pull request by hybrist**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

Link leads to a 404 page.

## What is the new behavior?

Link goes to https://angular.dev/best-practices/skipping-subtrees#using-onpush.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Good catch !

**Comment by JeanMeche** [comment]
Can we make it ready for review ? :)

**Comment by jkrems** [comment]
Shouldn't prep PRs while mentally being out for lunch already. De-drafted!

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit 45575b5ce433c6106ae076d548c3836d3f1f4cc4.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
