### PR TITLE
build(docs-infra): show a dist-tag when installing the CLI on non-stable versions (BACKPORT: 9.1.x)

### LINKED ISSUE #39821: Installation tutorial on older documents is installing the latest version of @angular/cli
# 📚 Docs or angular.io bug report

### Description

I was taking a look at the old documentation and I noticed that the installation command was the same used to install the latest version of @angular/cli

<code>
npm i @angular/cli@ -g
</code>

I supposed that the correct command would be something like:

<code>
npm i @angular/cli@^8 -g
</code>

### What's the affected URL?**
https://v8.angular.io/guide/setup-local

### Reproduction Steps**
- Open https://v8.angular.io/guide/setup-local
- See the "Install the Angular CLI" step
- Execute "npm i -g @angular/cli" on terminal
- "Run the command "ng version"

### Expected vs Actual Behavior**

Expected:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.29
@angular-devkit/core         8.3.29
@angular-devkit/schematics   8.3.29
@schematics/angular          8.3.29
@schematics/update           0.803.29
rxjs                         6.4.0

Actual behavior:

@angular-devkit/architect    0.1100.2 (cli-only)
@angular-devkit/core         11.0.2 (cli-only)
@angular-devkit/schematics   11.0.2 (cli-only)
@schematics/angular          11.0.2 (cli-only)
@schematics/update           0.1100.2 (cli-only)

[](url)
## 📷Screenshot
image

### PR DESCRIPTION
**Pull request by petebacondarwin**
It is important to use the correct major version of the Angular CLI when
following the examples in the tutorials. This commit provides a custom
element that renders an appropriate dist-tag in the setup step of
the tutorial when the docs are not in "stable" mode.

Fixes #39821

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
LGTM 

Reviewed-for: size-tracking, docs-infra

**Review by IgorMinar — APPROVED** [review]
LGTM 

Reviewed-for: docs-getting-started-and-tutorial

**Comment by josephperrott** [comment]
Caretaker Note: PullApprove on this branch is outdated.

**Comment by zarend** [comment]
Closed by commit fc25f94f2fc7f0aab83da3247ed7b3ceaf3053e6

**Pull request closed without merging**
