### PR TITLE
docs: fix typo for Browserslist in file structure guide

### PR DESCRIPTION
**Pull request by MattiJarvinen**
Filename browserlist is actually browserslist

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #28311

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Documentation typo fix.

### CODE REVIEW

**Comment by MattiJarvinen-BA** [comment]
I signed it!

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update git commit message to `docs: fix typo for Browserslist in file structure guide`

**Comment by MattiJarvinen-BA** [comment]
@brandonroberts actually noticed another Browserlist mention in the file and fixed it too, also updated commit message.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Caretaker note: This is a docs-only change and I'm using a global approval.

**Comment by MattiJarvinen-BA** [comment]
@IgorMinar just occurred to me my CLA is with my real email address and my commit is on Github no-reply, do I have to amend it to the real address or not?

**Comment by brandonroberts** [comment]
@MattiJarvinen-BA Igor can correct me, but I believe the CLA bot uses your provided GitHub email to confirm that you've signed the CLA. So even if you just create a pull request using the pencil on any page, its still tied to the email on your GitHub account.

**Pull request closed without merging**
