### PR TITLE
docs: use the updated http guides and remove the monolithic docs page

### PR DESCRIPTION
**Pull request by mgechev**
This PR finalizes the HTTP restructuring.

@trekladyone broke down the HTTP guide into multiple sections which we got in as part of previous pull requests. Here I just update the navigation to include links to the individual guides and change links that are pointing to `guide/http`.

Additionally, the PR adds a redirect from `guide/http` to `/guide/understanding-communicating-with-http`.

### CODE REVIEW

**Comment by trekladyone** [comment]
Error in:  
{
    path: 'SideNav.3.children.5.children.7',
    url: 'guide/configure-http-url-parameters'
  }
  
  Should be        url: 'guide/http-configure-http-url-parameters'

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-core, fw-http, fw-testing, in-memory-web-api

**Review by jessicajaniuk — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Review by AndrewKushnir — APPROVED** [review]

**Review by alxhub — APPROVED** [review]
Reviewed-for: fw-security

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 9f2fb7c6dcebc0437b0e3ce97565a86502f0266c.

**Pull request closed without merging**
