### PR TITLE
 Correct escaping in various locations

### PR DESCRIPTION
**Pull request by josephperrott**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]

**Comment by alfaproject** [comment]
Some of these look obviously broken or not expected and should be double-checked by the original author perhaps

If you see something like this: `\s*` then the author wanted it to be 0 or more whitespace characters, but now you changed it to `s*` which means 0 or more `s` characters.

So, if no tests fail and no one ever reported any issue, you can just remove the `\s*` altogether because it never did anything, or check with the author

**Comment by josephperrott** [comment]
@alfaproject I agree that this does not match what the author was intending to do in many of the cases, but these `\` uses were superfluous.  So the resulting regexs are actually the same.



These two strings create the same RegExp when actually interpretted:
```ts
new RegExp(`^test\s`) ==> /^tests/

new RegExp(`^tests`) ==> /^tests/

**Review by AndrewKushnir — APPROVED** [review]

**Comment by alfaproject** [comment]
@josephperrott I know they do but that was not my point. Instead of fixing what the author intended or removing `\s*` altogether since it wasn't doing anything you left those regexes in a very weird format now....

**Comment by gultyayev** [comment]
Agree with @alfaproject. Looks like it would be better to do the `\\` so that it would become the original intent of targeting a space instead of some literal "s"

**Pull request closed without merging**
