### PR TITLE
docs(aio): Update form validation guide

### PR DESCRIPTION
**Pull request by kapunahelewong**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

This PR is based on #18467 by @kara.

### CODE REVIEW

**Review by kara — APPROVED** [review]
LGTM

**Comment by juleskremer** [comment]
@kapunahelewong there are 3+ places in this doc where we link out to the download sample; can we include it just at the bottom of the document?

**Comment by kapunahelewong** [comment]
@juleskremer I've removed the extra live example links, leaving the one at the bottom. I've also squashed and re-pushed.

**Comment by juleskremer** [comment]
LGTM

**Review by juleskremer — APPROVED** [review]

**Pull request closed without merging**
