### PR TITLE
Edge one more time

### PR DESCRIPTION
**Pull request by IgorMinar**
Inspired by #8628 and @mehmetg

### CODE REVIEW

**Comment by mehmetg** [comment]
@IgorMinar Just created https://github.com/IgorMinar/angular/pull/2
It adds disconnect tolerance option to Karma. It should help. If it works you can bundle it into your PR or whatever it works.

**Comment by IgorMinar** [comment]
@mehmetg disconnectTolerance only works around the instability of the browser/tunnel and prolongs the build. there surely must be a better solution than that. We can't be ok with the browser disconnecting 4 our of 5 tries.

**Comment by IgorMinar** [comment]
@mehmetg is there something else that we can do?

**Comment by mhevery** [comment]
@mehmetg This PR has had over a week of inactivity. Could we move it forward?

**Comment by vicb** [comment]
ping @mehmetg ?

**Comment by IgorMinar** [comment]
obsolete. we now run edge in our ci thanks to @mlaval

**Pull request closed without merging**
