### PR TITLE
docs: typo fix

### PR DESCRIPTION
**Pull request by samhrncir**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by josephperrott** [comment]
@samhrncir Thanks for creating this fix, can you sign the CLA?

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-For: global-approvers

**Comment by samhrncir** [comment]
I signed the CLA, does it update as a batch ever so often? @josephperrott

**Comment by petebacondarwin** [comment]
You have to say "@googlebot I signed it!"

**Pull request closed without merging**
