### PR TITLE
refactor(core): format values for `ExpressionChangedAfterItHasBeenCheckedError` error

### PR DESCRIPTION
**Pull request by alexnoz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

`ExpressionChangedAfterItHasBeenCheckedError` error message doesn't show helpful values if they are of type `object` (they look like this `[object Object]`)

## What is the new behavior?

If either previous or current value is of type `object` it's properly formatted with `JSON.stringify()`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JoostK** [comment]
I'm afraid this may throw, such as when the data contains circular references.

**Comment by alexnoz** [comment]
The solution is to use a custom replacer as a second argument for `JSON.stringify()` (see [this MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value) for details). It looks good to me, what do you guys think?

**Comment by trotyl** [comment]
Reminder: compiler has used `JSON.stringify` once at https://github.com/angular/angular/pull/22689 but reverted due to performance issue.

**Comment by AndrewKushnir** [comment]
Hi, it looks like this PR targets ViewEngine code. Since ViewEngine is deprecated, we do not plan to merge any non-critical fixes/improvements, so I'm closing this PR. There is a ticket #34454 which also mentions this improvement. Thank you.

**Pull request closed without merging**
