### PR TITLE
refactor(core): Use intersections on branded types.

### PR DESCRIPTION
**Pull request by JeanMeche**
An Intersection on a branded type allows us to remove some unecessary type assertions.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Are we interessted in this change ?

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
caretaker: The presubmit has only unrelated failures. This is safe to merge.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 05e4dbb859789d66b150583c9a5a0ccb13ca0bfe.

**Pull request closed without merging**
