### PR TITLE
docs: update the copyright notice date

### PR DESCRIPTION
**Pull request by ghost**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by IgorMinar — DISMISSED** [review]
thanks for the pr, can you please sign CLA? thanks

**Comment by storm-sergey** [comment]
> thanks for the pr, can you please sign CLA? thanks

Done! 

Date Signed
Feb 04, 2021 10:27 PST

**Comment by storm-sergey** [comment]
@googlebot I signed it!

**Review by gkalpak — APPROVED** [review]
Thx, @storm-sergey :+1:

(BTW, there are a bunch more `2020`s to update throughout the repo, if you're interested - just search for `2010-2020`  :wink:)

**Pull request closed without merging**
