### PR TITLE
docs: updating the contribution guidline docs with the secure tag

### PR DESCRIPTION
**Pull request by alkavats1**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by devversion — APPROVED** [review]

**Comment by alkavats1** [comment]
Hi @devversion please merge this PR
Thanks :)

**Review by clydin — APPROVED** [review]

**Comment by alkavats1** [comment]
Hi, @devversion  and @clydin could you please review and merge this PR? It is pending since last week
Thanks :)

**Review by devversion — APPROVED** [review]
LGTM

Reviewed-for: global-dev-infra-approvers

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 1391a7e7e0ed85a37f7e01839c86d6aa0cadb5d8.

**Pull request closed without merging**
