### PR TITLE
docs: remove unused Input decorator

### PR DESCRIPTION
**Pull request by falinsky**
In the part "5. Add In-app Navigation" of the tutorial it was already removed

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by falinsky** [comment]
Hi @StephenFluin, I would like to kindly ask if something is missed or done in an inappropriate way regarding current pull-request? Thank you in advance.

**Comment by StephenFluin** [comment]
Hey there! I'm not sure why this was routed to me. Usually changes like this are routed to our docs teams. I'm pulling in @aikidave to help take a look.

**Comment by falinsky** [comment]
Thank you, @StephenFluin

**Review by aikithoughts — APPROVED** [review]
Thanks for this! LGTM!

Reviewed-for: global-docs-approvers

**Review by aikithoughts — APPROVED** [review]

**Comment by falinsky** [comment]
Thank you, @aikidave

**Pull request closed without merging**
