### PR TITLE
Transform refactor

### PR DESCRIPTION
**Pull request by kegluneq**
/cc @tbosch 

@yjbanov, this is not urgent, let's discuss before you start reviewing.

Thanks!

### CODE REVIEW

**Comment by kegluneq** [comment]
Responded to all comments (except `unlinked` -- I'll leave that for another PR).

PTAL

**Comment by kegluneq** [comment]
Okay... addressed `unlinked` also :)

**Comment by yjbanov** [comment]
LGTM, but let's wait until the big internal sync is complete before merging.

**Comment by kegluneq** [comment]
Looks like at runtime we use [ViewResolver](https://github.com/angular/angular/blob/7c6130c2c5d8ac2d5ba8df5f70b7f1264c283a2c/modules/angular2/src/core/linker/view_resolver.ts) which `throw`s if any view-related parameters are specified on `@Component` and `@View` is present.

I'll match this behavior.

**Pull request closed without merging**
