### PR TITLE
fix(zone.js): Fix ConsoleTask interface typo

### PR DESCRIPTION
**Pull request by victorporof**
Signed-off-by: Victor Porof <victorporof@chromium.org>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:

This PR updates a TypeScript interface.

## What is the current behavior?

`ConsoleTask::run` is typed as returning `void`.

## What is the new behavior?

`ConsoleTask::run` is typed returning the same value from invoking the function that was passed in as an argument.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

According to the [V8 implementation](https://chromium-review.googlesource.com/c/v8/v8/+/3776678), the Async Stack Tagging API's task `run` function is transparent and equivalent to changing `f()` to `task.run(f)`. The return value of `f` won't be lost. This PR updates the interface to reflect that.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Merge-assistance: low risk change, no additional reviews are required, we can proceed with the merge.

**Comment by dylhunn** [comment]
@victorprof this has merge conflicts with the patch branch. If you'd like this in patch, please create a patch port rebase, thanks!

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 91954cf20e17a386d71cc8ea25d1d17b9ae1e31c.

**Comment by victorporof** [comment]
> @victorprof this has merge conflicts with the patch branch. If you'd like this in patch, please create a patch port rebase, thanks!

Is this still needed?

**Pull request closed without merging**
