### PR TITLE
docs: use proper case in styleguide sentence

### PR DESCRIPTION
**Pull request by simonua**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Another good catch, @simonua! Could you amend your commit message to something like:

```
docs: use proper case in styleguide sentence
```

Please tag me when you're ready and I'll help this PR through too. Thanks for this!

**Comment by simonua** [comment]
Hi @kapunahelewong, I updated the commit message. Does this work now?

**Comment by kapunahelewong** [comment]
Yep, @simonua that commit message works. Could you squash, too? 🙏🏼

**Comment by simonua** [comment]
Hi @kapunahelewong, I think it's all done. Ready for your review, please. Thank you!

**Comment by kapunahelewong** [comment]
Caretaker, this is a docs only change and the failures appear unrelated. If there's anything I can do to help get this green, please let me know. Thank you!

**Review by alxhub — APPROVED** [review]

**Pull request closed without merging**
