### PR TITLE
refactor(ivy): remove unused code in the TestBed implementation

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Minor cleanup (removal of dead code) spotted while working on another issue.

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
merge-assistance as needs g3 presubmit

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:228908588:BASE:228908620:1547232964246:6452fb10)

**Comment by AndrewKushnir** [comment]
@pkozlowski-opensource after merging other TestBed-related changes into master, this PR now has conflicts. Could you please rebase it from the latest master, resolve conflicts and put "merge" label back? Thank you.

**Comment by pkozlowski-opensource** [comment]
merge-assistance since it:
- needs another g3 pre-submit
- sauclabs flakes

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:228908588:BASE:229386261:1547573999191:3c905972)

**Comment by AndrewKushnir** [comment]
@pkozlowski-opensource I've just run g3 presubmit and received some errors which are most likely appeared because PR was created on top of some old revision in master. Could you please try to rebase it again, so I can run another presubmit to verify that things work correctly in g3? Thank you.

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:228908588:BASE:229466835:1547599893873:9d24a6bc)

**Pull request closed without merging**
