### PR TITLE
fix(render3):fix spelling mistakes

### PR DESCRIPTION
**Pull request by Zuckjet**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by pgn666 — APPROVED** [review]

**Review by jbogarthyde — APPROVED** [review]
Thanks - always good to catch the typos!

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Hi @Zuckjet, it looks like this PR got stuck in the review queue for some reasons, sorry about that. The change still looks good, but I'd like to ask if you could update the commit message to say something like this:

```
doc(core): fix typo for get definition functions
```

and also rebase this PR in top of the latest master to re-run the CI.

Thank you.

**Comment by Zuckjet** [comment]
> Hi @Zuckjet, it looks like this PR got stuck in the review queue for some reasons, sorry about that. The change still looks good, but I'd like to ask if you could update the commit message to say something like this:
> 
> ```
> doc(core): fix typo for get definition functions
> ```
> 
> and also rebase this PR in top of the latest master to re-run the CI.
> 
> Thank you.

Since this PR has stayed more than one year, I cannot find the original branch. So I send a new [PR](https://github.com/angular/angular/pull/39823) for this.

**Comment by AndrewKushnir** [comment]
Thanks @Zuckjet, I'm closing this PR in favor of the newly created one (#39823).

**Pull request closed without merging**
