### PR TITLE
fix(core): static-query migration should not prompt if no queries are used

### PR DESCRIPTION
**Pull request by devversion**
Currently we always prompt when the static-query migration runs. This is not
always needed because some applications do not even use `ViewChild` or
`ContentChild` queries and it just causes confusion if developers need to
decide on a migration strategy while there is nothing to migrate.

In order to avoid this confusion, we no longer prompt for a strategy
if there are no queries declared within the project.

References #30224

### CODE REVIEW

**Review by CaerusKaru — APPROVED** [review]
LGTM

**Review by filipesilva — APPROVED** [review]

**Review by kara — APPROVED** [review]
LGTM

**Comment by kara** [comment]
[presubmit](http://test/OCL:247129433:BASE:247129454:1557278163970:2b20483)

**Comment by kara** [comment]
Caretaker note: This will need a G3 patch

https://sponge.corp.google.com/target?id=047288ec-04d9-445d-accb-8e6f61dc0a6a&target=//third_party/javascript/angular2:angular2_rc_build_test

**Comment by kara** [comment]
@devversion Can you rename the commit to `fix(core)`?

**Pull request closed without merging**
