### PR TITLE
fix(build): Reduce rx typings to what we actually require.

### PR DESCRIPTION
**Pull request by alexeagle**
This should help a lot with github rate limiting by removing about
2/3 of the dependencies.

[Review on Reviewable](https://reviewable.io/reviews/angular/angular/2780)

### CODE REVIEW

**Comment by alexeagle** [comment]
Note, upgrading to tsd 0.6.3 picks up a fix for --reinstall not removing stale typings.
By doing that in the same commit, it should cause the unused rx typings to be removed from everyone's local copy.

**Comment by caitp** [comment]
Aren't we pulling in 0.6.3 anyways because of the hat operator? I don't see the version in the shrinkwrap diff either. Otherwise looks alright

**Comment by alexeagle** [comment]
Something must be wrong with my shrinkwrapping - v0.6.1 is in the `npm-shrinkwrap.json`.

Will fix and then merge.

**Comment by alexeagle** [comment]
merged as 8bab6dd

**Pull request closed without merging**
