### PR TITLE
Corrected the spelling of access

### PR DESCRIPTION
**Pull request by 2007certain**
Removed extra "s" from access which I noticed while reading docs

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by 2007certain** [comment]
@googlebot I signed it!

**Review by ghost — APPROVED** [review]

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by matsko** [comment]
@2007certain please rebase.

**Comment by 2007certain** [comment]
@matsko I'm not familiar with rebase.

can you please help me with steps for this, as I pushed changes on the master itself it is showing all updated when I rebase on my repository. Thanks

**Pull request closed without merging**
