### PR TITLE
refactor(upgrade): modules/upgrade/src/aot is a package root

### PR DESCRIPTION
**Pull request by alexeagle**
In g3 we can point `@angular/upgrade` at a subdirectory. Currently we need to make both `src/aot.ts` and `src/aot` directories be roots which is not allowed. By moving to an `index.ts` we can make `src/aot` be the root.

### CODE REVIEW

**Comment by alexeagle** [comment]
This is a workaround for the fact that the `@angular/upgrade` package depends on `@angular/compiler` in a way that tree-shakers like rollup and closure compiler don't remove the compiler from AoT-compiled upgraded apps

**Comment by petebacondarwin** [comment]
Inside `/angular/modules/@angular/upgrade/index.ts` we have the following lines:

```
export * from './src/upgrade';
export * from './src/aot';
```

Does that still work with this PR or do we need to change the second line to import `./src/aot/index`?

**Comment by petebacondarwin** [comment]
In fact looking at the Travis failures, the import does need fixing

**Comment by alexeagle** [comment]
Fixed.

**Comment by mhevery** [comment]
Build still broken???

**Comment by alexeagle** [comment]
Update as discussed in person: the 4 new APIs are now in `@angular/upgrade/static`

**Comment by IgorMinar** [comment]
please update to follow #12452 12452

**Comment by alexeagle** [comment]
Yes I had already done that. Are you asking for the new bundle in this PR as well?

**Comment by IgorMinar** [comment]
@alexeagle I pushed two commits to your branch that fix compilation errors and add umd bundle config. I expect CI to still fail, we'll see.... I need to go offline, so please resolve the remaining issues and apply the merge label.

**Comment by vsavkin** [comment]
Merged https://github.com/angular/angular/commit/a26dd28bdb6ad3e5ac07080a629cdf9ea7980aee

**Pull request closed without merging**
