### PR TITLE
fix(core): remove duplicated EMPTY_OBJ constant

### PR DESCRIPTION
**Pull request by cexbrayat**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The codebase currently contains several EMPTY_OBJ constants,
and they can end up in the bundle of an application.
A recent commit 6fbe219 tipped us off
as it introduced several noop occurrences in the golden symbol files.

## What is the new behavior?

After investigating, we decided to remove the duplicated symbols.

This probably shaves only a few bytes,
but this commit removes the duplicated constants,
by always using the one in core/src/utils/empty.

This is a follow-up to #40991 that recently landed, allowing to delete `core/src/render3/empty`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
[presubmit](https://test.corp.google.com/ui#id=OCL:360712032:BASE:360712085:1614798235440:3a62e953)

**Comment by AndrewKushnir** [comment]
Hey @cexbrayat, there was a merge conflict with the patch branch (11.2.x), so I've merged the change to the master branch only. Could you please create a patch-only version of this PR if needed? Thank you.

**Comment by cexbrayat** [comment]
@AndrewKushnir I think the previous PR https://github.com/angular/angular/pull/40991 removing EMPTY_ARRAY was only merged on master and not on 11.2.x (it was but was later reverted).

So I can do another one targeting 11.2.x, but we would need both commits (removing EMPTY_ARRAY, then the one removing EMPTY_OBJ). Is that what you want me to do, or are we fine with the commits in master only?

**Comment by AndrewKushnir** [comment]
@cexbrayat we've landed #40991 in master only (the change would go into next major, i.e. v12) since there was a risk of breaking some apps in a similar way that we've observed in Google's codebase. Since there were not issues with the `EMPTY_OBJ` changes, they are safer and we can land them in the patch branch as well. Could you please create a new patch-only PR that would only include the changes from this PR? Thank you.

**Comment by cexbrayat** [comment]
@AndrewKushnir Thanks for the explanation 👍 I opened #41153 with this commit targeting 11.2.x.

**Pull request closed without merging**
