### PR TITLE
Glossary copy edit

### PR DESCRIPTION
**Pull request by jbogarthyde**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by jbogarthyde** [comment]
@jenniferfell All green now except approvals

**Comment by jbogarthyde** [comment]
@jenniferfell All green now except approvals

**Review by jenniferfell — APPROVED** [review]
Some things to fix before releasing:
- Line breaks in some unexpected places (not paragraph breaks)
- Inconsistent vert spacing in lists
- A few caps or other copy edit things

Optional:
- Some places where a comma was included out of habit but is not correct or where a comma is standing in for missing words. 
- Some places where a "which" or "that" clause could be more clear.
Optional because I'm not sure if we can be more clear in this copy edit pass. Might need to put on backlog to rewrite some definitions.

**Comment by jenniferfell** [comment]
P.S. Please squash commits. Thanks!

**Pull request closed without merging**
