### PR TITLE
fix(common): remove deprecated support for intl API

### PR DESCRIPTION
**Pull request by ocombe**
BREAKING CHANGE:
In v5, we deprecated support for the intl API in order to improve the browser support. We are now removing these deprecated APIs for v9. See the original change here for more info on why: #18284.

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
lgtm, but I'd like @StephenFluin to also approve just in case he knows of some use-cases that would make the removal problematic.

**Review by StephenFluin — APPROVED** [review]
I reviewed these changes with Olivier. Based on the long deprecation timeframe and the clear expectation management (deprecated in the symbol name), this looks good.

**Comment by kara** [comment]
[presubmit](https://test.corp.google.com/ui#id=OCL:240594677:BASE:240595268:1553708821063:e6e34fc3)

**Review by petebacondarwin — APPROVED** [review]

**Review by petebacondarwin — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Blueprint presubmit is successful, [starting a global one](https://test.corp.google.com/ui#id=OCL:274282012:BASE:274291695:1570845819591:fcf14a85).

**Comment by AndrewKushnir** [comment]
FYI, the [global presubmit](https://test.corp.google.com/ui#id=OCL:274282012:BASE:274305085:1570855964766:937c24db) is also successful 🎉 

@kara could you please have a final look/approval, so we can proceed with merging?

Thank you.

**Comment by kara** [comment]
merge-assistance: Igor has global approval

**Pull request closed without merging**
