### PR TITLE
adev: fix broken link

### PR DESCRIPTION
**Pull request by abcox**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by abcox** [comment]
Hi @twerske. Are there any actions I need to take to resolve this PR?

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
@abcox Looks like we have your CLA signed from one of your two contributor emails. We'll need it on both. Can you take care of that? Otherwise this looks just about ready to go.

**Comment by jessicajaniuk** [comment]
@abcox Seeing no updates for now, I'm going to close this. Feel free to put up a new PR with this change. Landing it will be much faster now that the adev infra is in place. Thanks for taking the time to put the contribution up!

**Pull request closed without merging**
