### PR TITLE
docs(changelog): fix typo on the commit link

### PR DESCRIPTION
**Pull request by edysegura**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by kapunahelewong** [comment]
Thanks so much for this, @edysegura. Could you amend your commit message to something like:

```
docs: fix commit link typo in changelog
```

I think that will get it passing. Then, please tag me so I can come back and help the PR through the process. 😊

**Comment by edysegura** [comment]
> docs: fix commit link typo in changelog

Hi @kapunahelewong!!

Thank you very much for giving me the directions!

Cheers,

**Comment by kapunahelewong** [comment]
Glad to help, @edysegura 😊

There are a few tests that are failing, but I don't think it's anything you've done. To try to get them to pass, though, you might want to rebase and push up. That'll get everything up-to-date and re-trigger the tests. (I re-ran the tests this morning to see if they'd maybe just flaked but they failed again). If you need help let me know. Thanks for all your efforts. :)

**Pull request closed without merging**
