### PR TITLE
docs(forms): fix example 'Reset the form group values and disabled status'

### PR DESCRIPTION
**Pull request by monsGT-R**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by monsGT-R** [comment]
@googlebot I signed it! and we'll verify it.

**Comment by monsGT-R** [comment]
@googlebot I fixed it.

**Comment by santoshyadav198613** [comment]
Hi @monsGT-R ,
Can you change the commit message, changes looks correct. 
follow docs: commit message

**Comment by monsGT-R** [comment]
Hi @santoshyadav198613,
I changed it.

**Comment by santoshyadav198613** [comment]
> Hi @santoshyadav198613,
> I changed it.

please change the commit message as well.

**Comment by kapunahelewong** [comment]
Thanks for this, @monsGT-R. Could you squash and rebase? (You want there to be only 1 commit). You might find the [notes on my own workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) helpful. 

Requesting @jbogarthyde for review as she is familiar with the API docs.

**Review by jbogarthyde — APPROVED** [review]
LGTM

**Comment by monsGT-R** [comment]
Hi @kapunahelewong,
I changed it.)

**Comment by kapunahelewong** [comment]
Great, thanks, @monsGT-R. Don't forget [the rebase](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase).

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]

**Pull request closed without merging**
