### PR TITLE
test(core): correct typo in signal_spec.ts

### PR DESCRIPTION
**Pull request by ghost**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
@BrianDGLS Looks like your commit message needs a body added to it in order to pass lint.

**Review by AndrewKushnir — APPROVED** [review]

**Comment by BrianDGLS** [comment]
Thanks @jessicajaniuk , I have added a message body.

This PR is a great learning exercise on how to contribute.

**Comment by AndrewKushnir** [comment]
@BrianDGLS thanks for adding the commit message body! This PR is now added to the merge queue.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit ea560a7098d0e849b95bd342d62a89bbbf06675e.

**Pull request closed without merging**
