### PR TITLE
build: Fix size tracking test

### PR DESCRIPTION
**Pull request by jessicajaniuk**
One of our goldens needed to be bumped.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

- [x] CI related changes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM, but quite a significant increase? will we investigate separately?

**Review by crisbeto — APPROVED** [review]
LGTM

**Review by crisbeto — APPROVED** [review]
Approved for size-tracking

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 069498ca897f89f31c6784600ae7fe6eecd174ad.

**Pull request closed without merging**
