### PR TITLE
build(aio): render doc-gen issues in overview dump

### PR DESCRIPTION
**Pull request by petebacondarwin**
Related to #22138

### CODE REVIEW

**Comment by petebacondarwin** [comment]
You can view the report here: https://pr22675-6bd333b.ngbuilds.io/generated/docs/overview-dump.html

screen shot 2018-03-09 at 10 33 19

**Comment by gkalpak** [comment]
Why does it think that [getAngularJSGlobal()][1] is undocumented?

[1]: https://pr22675-6bd333b.ngbuilds.io/api/upgrade/static/getAngularJSGlobal

**Review by gkalpak — APPROVED** [review]

**Comment by petebacondarwin** [comment]
> Why does it think that getAngularJSGlobal() is undocumented?

I have no idea! This seems like a bug! I am surprised that you approved it given that issue.

**Comment by gkalpak** [comment]
> I am surprised that you approved it given that issue.

The error didn't seem related to this PR :wink:

**Comment by petebacondarwin** [comment]
True. I'll fix in a follow up PR

**Comment by kara** [comment]
@petebacondarwin Would you mind rebasing this?

**Comment by petebacondarwin** [comment]
@kara - of course. Done. Thank you.

**Pull request closed without merging**
