### PR TITLE
docs: use 17.3.x branch for aio quick start

### PR DESCRIPTION
**Pull request by JeanMeche**

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
@JeanMeche should it target `patch` instead?

**Comment by JeanMeche** [comment]
That's what I said to @atscott, I'm not sure why he changed it back !

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit c67cbe98a664cca20c5ec879b1f02fcd52d9e47e.

**Pull request closed without merging**
