### PR TITLE
Updated docs about HTTP testing

### PR DESCRIPTION
**Pull request by CodeF0x**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The order of the http testing related providers is pretty important and doing it wrong made my tests fail.

## What is the new behavior?

Added a small heads up to always keep the order in mind

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, can you please sign the CLA for the PR to go foward, thank you.

**Comment by CodeF0x** [comment]
Hi, sorry for keeping you waiting. I signed the CLA.

**Comment by CodeF0x** [comment]
Hi @JeanMeche, sorry for keeping you waiting. I signed the CLA.

**Comment by JeanMeche** [comment]
Can you check that you signed it with ` <co****t​@codef0x.dev>`, the check still returns an error.

**Comment by CodeF0x** [comment]
I triggered the CLA check again, now it seems to work.

**Review by JeanMeche — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 3ac0a785324f00b34b7445aab7d7edaf395b1c72.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
