### PR TITLE
docs: fix anatomy-of-components removing duplicate paragraphs

### PR DESCRIPTION
**Pull request by nektobit**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Removed a typo that duplicated paragraphs in the documentation on the anatomy-of-components page

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Review by twerske — APPROVED** [review]

**Review by asyncLucas — APPROVED** [review]

**Comment by Ansh101112** [comment]
Will submit a PR asap.

**Comment by devversion** [comment]
This PR was merged into the repository by commit 3cf18bb6f2798020cbe8633fae79f920cf98816b.

**Comment by devversion** [comment]
This PR was merged into the repository by commit 3cf18bb6f2798020cbe8633fae79f920cf98816b.

**Comment by devversion** [comment]
Thanks for this PR, it looks like this change already landed in a different PR so this one is no longer applicable.

**Pull request closed without merging**
