### PR TITLE
G3_MASTER: feat(benchpress): add custom user metric to benchpress

### PR DESCRIPTION
**Pull request by ochafik**
(continuation of @jeffbcross 's https://github.com/angular/angular/pull/7440)

### CODE REVIEW

**Comment by jeffbcross** [comment]
Well, at least it's a _different_ error now?

**Comment by jeffbcross** [comment]
LGTM, when Travis goes green I'll apply the merge label.

**Comment by ochafik** [comment]
Hey @jeffbcross, now looks green (Dart tests are gone, do I need to remove anything from the PR?).

**Comment by tbosch** [comment]
Talked offline to sync against the g3_master branch...

**Comment by tbosch** [comment]
Ping, could you rebase ontop of `g3_master`?

**Comment by jeffbcross** [comment]
I rebased on `g3_master` and opened a new PR: #8752

**Comment by mhevery** [comment]
Closing in favor of #8752

**Pull request closed without merging**
