### PR TITLE
build: fix strictNullChecks related issues.

### PR DESCRIPTION
**Pull request by gunan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
When I enable strictNullCheks on TS compiler internally at google, angular wont build. This patch fixes that.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by devversion** [comment]
I just saw this PR. Is this being discussed somewhere else or what's the state? I wonder why these are for strict null checks, but we have strict null checks enabled to my knowledge. See: https://github.com/angular/angular/blob/main/packages/tsconfig-build.json

**Comment by gunan** [comment]
Hi, the issue is when the build happens inside google. If you like, I can start an internal thread to discuss before we continue the review of this change.

**Comment by jessicajaniuk** [comment]
@gunan Yes, let's start the internal thread. I think that would be helpful.

**Comment by devversion** [comment]
This PR is no longer relevant.

**Pull request closed without merging**
