### PR TITLE
build(docs-infra): upgrade cli command docs sources to bff1908b4

### PR DESCRIPTION
**Pull request by gkalpak**
Updating [angular#master](https://github.com/angular/angular/tree/master) from [cli-builds#master](https://github.com/angular/cli-builds/tree/master).

##
Relevant changes in [commit range](https://github.com/angular/cli-builds/compare/a517160a2...bff1908b4):

**Added**
- help/cache.json

**Modified**
- help/add.json
- help/analytics.json
- help/build.json
- help/config.json
- help/deploy.json
- help/doc.json
- help/e2e.json
- help/extract-i18n.json
- help/generate.json
- help/lint.json
- help/new.json
- help/run.json
- help/serve.json
- help/test.json
- help/update.json
- help/version.json

##
Relevant changes in [commit range](https://github.com/angular/cli-builds/compare/207de70b7...bff1908b4) since PR #45385:

**Added**
- help/cache.json

**Modified**
- help/config.json

##
Closes #45330
Closes #45346
Closes #45361
Closes #45385

### CODE REVIEW

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Now that ng-cache has been added as a CLI command.

The following needs to be removed as the the new page will use the same URL and includes the same content.

https://github.com/angular/angular/blob/master/aio/content/cli/cache.md

https://github.com/angular/angular/blob/a049840e0db4941e382b6b7046d333e58fccf688/aio/content/navigation.json#L1031

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Comment by alan-agius4** [comment]
For context here is the replaced page: https://pr45395-7984bab.ngbuilds.io/cli/cache

**Review by AndrewKushnir — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 650715062d309b51b6c6c0217089728b755b43a1.

**Pull request closed without merging**
