### PR TITLE
docs: fix typo in directive decorator description

### PR DESCRIPTION
**Pull request by rileyL6122428**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Fixing typo in docs DirectiveDecorator.

Issue Number: N/A

## What is the new behavior?
Typo fixed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by rileyL6122428** [comment]
I have just signed the CLA.

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Git commit message should be updated to `docs: fix typo in directive decorator description`

**Comment by rileyL6122428** [comment]
@brandonroberts commit message updated.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Caretaker note: This is a docs only change and should not impact g3. Please run presubmit.

**Review by kara — APPROVED** [review]
LGTM

**Pull request closed without merging**
