### PR TITLE
Location docs

### PR DESCRIPTION
**Pull request by mhevery**

### CODE REVIEW

**Comment by Foxandxss** [comment]
@mhevery Shouldn't we follow [this](https://docs.google.com/document/d/1_AvWE7CFgPDn6FLGci51G15eOMwfbgJQlQRhoBuqvhI/edit#heading=h.r4d3xhyi5aga) document? To move the e2e tests to a concrete folder and unit tested snippets to another folder.

On the other hand, we are not going to add a Unit tested snippet for HashLocationStrategy?

**Comment by mhevery** [comment]
@Foxandxss 
1) I replaced the unit test with e2e test.
2) I was the impression that the extra folders were not necessary as everything is driven by the location of `module.ts` (At least that is how @matsko  and I designed it.) What do you think the benefit of the extra folder would give you?

**Comment by Foxandxss** [comment]
The document says otherwise. To put the test in their own folder.

**Comment by Foxandxss** [comment]
There is no extra benefit other than being consistent.

**Comment by mhevery** [comment]
Let's see if you will run into any issues trying to publish to plunker. If not, I like the freedom over strictness, but we should talk to @IgorMinar as well.

**Comment by vicb** [comment]
@mhevery @Foxandxss what is the status here ?

**Comment by vicb** [comment]
lgtm/merge by @mhevery

**Pull request closed without merging**
