### PR TITLE
docs: Change word "standaone" to "standalone"

### LINKED ISSUE #52595: angular.dev: Change word "standaone" to "standalone"
### Describe the problem that you experienced

Inside the first step Create the ReversePipe, in the block of code: 

@Pipe({
    standaone: true,
    name: 'reverse'
})

The word "standalone" is misspelled.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/create-a-pipe#create-the-reversepipe

### Describe what you were looking for in the documentation

The word "standalone" is misspelled.

### Describe the actions that led you to experience the problem

_No response_

### Describe what you want to experience that would fix the problem

Change word "standaone" to "standalone"

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by AFreeNeat**
Fixes #52595

### CODE REVIEW

**Review by ddelavega — APPROVED** [review]

**Review by twerske — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 0ffa228165f2d34ed92b01765961998444c3d54b.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit b1cc0923a03cec64500743aabff3091c519f6117.

**Comment by jessicajaniuk** [comment]
@AnthonyFr75 Can you update your commit message to match lint requirements? It needs to be `docs: Change word "standaone" to "standalone"`.

**Comment by AnthonyFr75** [comment]
Hello @jessicajaniuk, it is done

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 8c8ff633760eada2acfbe69c3269e76ac98809d0.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 8c8ff633760eada2acfbe69c3269e76ac98809d0.

**Comment by josephperrott** [comment]
This PR was merged into the repository by commit 029edea32af811d86b9bf05832ddf8851bdf4369.

**Pull request closed without merging**
