### PR TITLE
docs: fix broken guide link (tutorial/index --> tutorial)

### PR DESCRIPTION
**Pull request by priyashpatil**
docs: fix broken guide link (tutorial/index --> tutorial)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

clicking link shows 404 error
Issue Number: N/A

## What is the new behavior?
the link redirects as expected

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Good catch! Thx :+1:

**Comment by gkalpak** [comment]
@priyashpatil, we need a couple of things before this can be merged:
1. We need a signed CLA (see https://github.com/angular/angular/pull/36453#issuecomment-609789763).
2. The commit message needs to follow [our guidelines][1]. E.g.:
    > docs: fix broken guide link (tutorial/index --> tutorial)

[1]: https://github.com/angular/angular/blob/c8bef1259c185fab24ef483ed626bc27ba61d775/CONTRIBUTING.md#commit

**Comment by priyashpatil** [comment]
@googlebot I signed it!

**Review by gkalpak — APPROVED** [review]
Thx, @priyashpatil!

I noticed you had updated the PR title instead of the commit message. I fixed it for you, since I realized you had probably created the PR through the GitHub UI. (Fixing the commit message of an existing commit requires checking it out on your machine and amending the commit using the git cli or an equivalent UI tool.)

I also rebased on master to make CI happy.

Reviewed-for: global-docs-approvers

**Pull request closed without merging**
