### PR TITLE
docs(aio): add Alyle UI to resources

### PR DESCRIPTION
**Pull request by Enlcxx**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Add the component library to the list of resources.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by gkalpak** [comment]
One thing I noticed by quickly browsing through the site:

> Disclaimer: This is a beta version. The API can change, I recommend that you use it in new projects.

The disclaimer on the [installation page][1] is a little vague. Does it mean that you should not use it in old projects? (What difference does it make?)

[1]: https://alyle-ui.firebaseapp.com/getting-started/installation

**Comment by StephenFluin** [comment]
It sounds from the disclaimer that this component library might not be ready for lots of users, or that users that adopt it may experience significant breaking changes.

Would it make sense to revisit when it's more stable?

**Comment by Enlcxx** [comment]
Now it can be used in any project.

But some components are in beta version and can have changes, the disclaimer will be removed and I will add a warning to the components that are in beta version.

**Comment by jenniferfell** [comment]
@Enlcxx Hi. I was just rechecking some PRs that have been open for a bit. A couple of questions, to make sure our understanding is current: 

- As a visitor to your page, it looks like your project is still in beta (v1.7.0-beta.76gq3), is that correct? 
- You mentioned that only some components are in beta. I didn't notice any beta-specific notes on the component docs. Can you highlight one that has a beta message?

Thanks!

**Comment by Enlcxx** [comment]
New version [1.7.2](https://alyle-ui.firebaseapp.com/), most of the components are stable, the components that are in beta now have a note.

**Review by StephenFluin — APPROVED** [review]

**Pull request closed without merging**
