### PR TITLE
fix(deps): update clang-format dependency, re-shrinkwrap.

### PR DESCRIPTION
**Pull request by mprobst**

### CODE REVIEW

**Comment by vicb** [comment]
LGTM, I would not merge all the file change, it will cause conflicts with other pending PRs, could we postpone the re-formatting of everything ?

**Comment by mprobst** [comment]
Then it'd break the build. And of course the in-flight PRs will add more changes that would need re-formatting; unless we expect to have zero PRs and nobody with a large CL locally at some point in time, we would never get this in, I think...

**Comment by vicb** [comment]
> Then it'd break the build. 

Ah yes... 

I think we have too many in-flight PRs ATM. -1 to merge this now.

We should merge most in-flight PRs before converting the tests to TS. May be we can propose that everybody focus on merging in-flight PR Friday morning and then you can update/merge this & test can be TSified ?

**Comment by mprobst** [comment]
I guess you're the better judge of that than I am, but overall I expect that waiting might just increase the effort in total.

**Comment by vicb** [comment]
> I guess you're the better judge of that than I am

I don't know but what I can is that I lost half my day yesterday trying to rebase a PR after TSification (& the other half with the build system, hopefully I was able to work for the 3rd half) and I can say it's not really nice.

As we should merge all possible PRs before upgrading the tests, I think it's worth the wait. It can be quite fast if we can get 3/4 people to merge pending PRs.

**Comment by tbosch** [comment]
I am rebasing it right now and will merge as soon as Travis says it is green.

**Comment by tbosch** [comment]
See https://github.com/angular/angular/pull/2107

**Comment by tbosch** [comment]
Just landed in master.

**Pull request closed without merging**
