### PR TITLE
docs: fix dynamic template tutorial

### LINKED ISSUE #59228: Visual bug in framework tutuorial
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I am learning this framework with the help of the basic tutorial you have and I found the text overflowing.

Image
https://github.com/user-attachments/assets/b7bb203a-1085-437f-b847-b1be6d39858e

### Please provide a link to a minimal reproduction of the bug

https://github.com/user-attachments/assets/b7bb203a-1085-437f-b847-b1be6d39858e

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JeanMeche**
fixes #59228

### CODE REVIEW

**Review by josephperrott — CHANGES_REQUESTED** [review]
Looks like it still has the overflow issue shown in the reported issue.

image

**Comment by JeanMeche** [comment]
@josephperrott Redeploy was still in progress, it's fine now !

**Review by josephperrott — APPROVED** [review]
LGTM

Perfect! Sorry about that!

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 3d86c586dc73a426f7bda45472a6e2c1609a141b.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
