### PR TITLE
docs: remove redudant word in goldens/README.md

### PR DESCRIPTION
**Pull request by mgred**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type
What kind of change does this PR introduce?

- [x] Other... Please describe:

This PR fixes a small typo in `goldens/README.md`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@mgred thanks for improving the docs. Could you please change commit message (`git commit --amend`) and replace `fix:` with `docs:`? Thank you.

**Comment by mgred** [comment]
@AndrewKushnir done :heavy_check_mark:

**Comment by AndrewKushnir** [comment]
Note to Caretaker: this is a safe change, it doesn't require extra approvals (it was approved).

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 6a2d8e20e9e1333325ed440e2e4186cb57c2a830.

**Pull request closed without merging**
