### PR TITLE
refactor(router): Added token for router primary component

### LINKED ISSUE #9870: Component Router does not work with Upgrade Adapter
When trying to use the Angular 2 Component Router (Angular 2 RC 4) with the upgrade adapter I got the following error:

> Bootstrap at least one component before injecting Router. at setupRouter

This is my main.ts file:

```
angular.module(moduleName).directive('App', upgradeAdapter.downgradeNg2Component(AppComponent));

upgradeAdapter.addProvider(APP_ROUTER_PROVIDERS);

upgradeAdapter.bootstrap(document.body, [moduleName]);
```

I google the problem and found the following links, but they all correspond to the router deprecated module as the Angular team changed how the router works since RC4:

https://github.com/angular/angular/issues/7147?_pjax=%23js-repo-pjax-container

Any ideas?

### PR DESCRIPTION
**Pull request by brandonroberts**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

Allows the router primary component to be overridden when using ngUpgrade.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Closes #9870, #8463, #9973

### CODE REVIEW

**Comment by Guardiannw** [comment]
@brandonroberts Are there any updates on this?  Will this be in RC5?

**Comment by brandonroberts** [comment]
@Guardiannw no updates yet. It will get reviewed at some point unless there is another solution coming for using ngUpgrade.

**Comment by brandonroberts** [comment]
Ready for review @vsavkin

**Comment by brandonroberts** [comment]
Will open a new PR when https://github.com/angular/angular/pull/10489 lands

**Pull request closed without merging**
