### PR TITLE
refactor(common): remove ng_switch ability to use == equality check

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
In Angular v17 we've alligned NgSwitch equality check with the build in control flow to be ===. At the same time we've left the ability to use ==. This ability was controlled by the NG_SWITCH_USE_STRICT_EQUALS const targetted by the G3 patch.

This commits removes the infrastructure to swap equality operator in preparation for the G3 patch removal.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Note about G3 end the existing patch:
* I've done the cleanup off all the usages of NgSwitch that were relying on the `==` equality check
* running a TGP to confirm that we didn't back-slide
* the actual patch will be removed in a separate CL followed by the removal of the `ng_switch_equality` file.

**Comment by pkozlowski-opensource** [comment]
"green" [TGP](https://fusion2.corp.google.com/presubmit/646825370/OCL:646825370:BASE:646823817:1719479687545:e27ff0ff;groups=PossiblyNewlyFailing/targets) (only unrelated failures after de-flake).

**Review by crisbeto — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
caretaker note: this PR has a "green" [TGP](https://fusion2.corp.google.com/presubmit/646825370/OCL:646825370:BASE:646823817:1719479687545:e27ff0ff;groups=PossiblyNewlyFailing/targets) (only unrelated failures after de-flake) but I would still suggest syncing it separately in case that there are NgSwitch usages not covered by tests (those things could be subtle).

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit 08f56d980bfce4591b4fbac7f44d223cdd591ebe.

The changes were merged into the following branches: main, 18.0.x

**Pull request closed without merging**
