### PR TITLE
docs: include angular-eslint in update guide

### PR DESCRIPTION
**Pull request by michaelbe812**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ]  Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This PR will include update informations for running the `@angular-eslint/schematics` `ng update` command.

### CODE REVIEW

**Comment by JeanMeche** [comment]
You can run the doc site with `yarn docs`.

**Comment by mikelgo** [comment]
> You can run the doc site with `yarn docs`.

Thank you. I already tried this, however on my machine the build fails with this error

```
RROR: /Users/michaelberger/Documents/dev/open-source/angular-fork/adev/shared-docs/pipeline/guides/BUILD.bazel:3:11: Compiling TypeScript (prodmode) //adev/shared-docs/pipeline/guides:guides failed: (Exit 1): tsc_wrapped.sh failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/npm/@bazel/concatjs/bin/tsc_wrapped.sh @@bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/adev/shared-docs/pipeline/guides/guides_tsconfig.json
adev/shared-docs/pipeline/guides/tranformations/heading.ts:37:6 - error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.

37     .replaceAll(/`(.*?)`/g, '<code>$1</code>')
        ~~~~~~~~~~

Target //adev:serve failed to build
Use --verbose_failures to see the command lines of failed build steps.

```
So I believe something is not configured correctly. I'll need to check it. However with a little workaround I was able to run the docs-site and verify my changes.

**Comment by JeanMeche** [comment]
You might want to rebase on `main`, we fixed this issue yesterday. 

Also I'm not sure this a change we'd like to land. There is no direct integration for `angular-eslint` by the CLI and it is an external dependency (as in not developed and supported by the angular team.)

**Comment by mikelgo** [comment]
Don't know, u decide :)

**Comment by JeanMeche** [comment]
We discussed this we the team, we don't have any direct integration with `angular-eslint` (we don't generate it with `ng new`) nor do we provide any migration guide for community packages. So this is not something we'd like to land. 

Anyway, thanks for the suggestion, we appreciate community suggestions toward our docs.

**Comment by mikelgo** [comment]
@JeanMeche Thank you, appreciate your efforts.

**Pull request closed without merging**
