### PR TITLE
docs(aio) fix typo

### LINKED ISSUE #19078: Spelling error in Angular docs
## I'm submitting a...
[x ] Documentation issue or request

## Current behavior
wrong sentence: "// This component make a request but it can't actually delete a hero."

## Expected behavior
correct sentence: "// This component makes a request but it can't actually delete a hero."

## Minimal reproduction of the problem with instructions
see: https://angular.io/guide/template-syntax#custom-events-with-eventemitter

### PR DESCRIPTION
**Pull request by aravindfz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Typo fix

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 19078

## Does this PR introduce a breaking change?
```
[ ] Yes
[ x] No
```

## Other information
Fixes #19078

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
LGTM, thx!

@aravindfz, could you change the commit message to `docs(aio): fix typo` (to adhere to the [commit message guidelines][1])?

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

**Comment by aravindfz** [comment]
@gkalpak I modified the commit message still the build is failing. Please help

**Comment by gkalpak** [comment]
I just realized this PR is against the `angular:4.0.x` branch. It should be against the `master` branch.

**Comment by aravindfz** [comment]
@gkalpak I have changed the base branch as master.

**Comment by gkalpak** [comment]
I changed the trget branch. Can you please rebase your `aravindfz:pr-issue-fix` branch on latest master?

**Comment by aravindfz** [comment]
@gkalpak I guess its fine now?

**Comment by gkalpak** [comment]
The change should be in file `aio/content/examples/template-syntax/src/app/hero-detail.component.ts`, but you have added a new file (`aio/content/examples/template-syntax/ts/src/app/hero-detail.component.ts`).

Also, if you add `Fixes #19078` in your commit message, it will automatically close that issue once this is merged.

**Comment by aravindfz** [comment]
@gkalpak I have updated the PR with the exact file as you mentioned in the previous comment.

**Comment by gkalpak** [comment]
CircleCI is trying to validate irrelevant commits from the 4.1.x branch. This is PR is OK for merging.

**Comment by matsko** [comment]
Landed as 867ab11def3abb3b9af599f6d501bf15912632f6 and 5baa069b16b2d2f1f57894f112662b8096575385

**Pull request closed without merging**
