### PR TITLE
fix(compiler): narrow the type of the aliased if block expression

### PR DESCRIPTION
**Pull request by crisbeto**
Currently the TCB for aliased `if` blocks looks something like this:

```
// Markup: `@if (expr; as alias) { {{alias}} }

if (block.condition) {
  var alias = block.condition;
  "" + alias;
}
```

The problem with this approach is that the type of `alias` won't be narrowed. This is something that `NgIf` currently supports.

These changes resolve the issue by emitting the variable outside the `if` block and using the variable reference instead:

```
// Markup: `@if (expr; as alias) { {{alias}} }

var alias = block.condition;
if (alias) {
  "" + alias;
}
```

### CODE REVIEW

**Comment by eneajaho** [comment]
What about this case? Where we alias the expr, but still use the expr and not the alias?

```html
@if (expr; as alias) { 
  {{expr}} 
}
```

Asking because of this comment
CleanShot 2023-09-29 at 12 15 04@2x

**Comment by crisbeto** [comment]
That case isn't a problem since the generated code will always read the value off of the context:

image

**Comment by eneajaho** [comment]
My question was more for the TCB? 

CleanShot 2023-09-29 at 14 02 33@2x


It looks like the TCP will always create the alias and use that one inside if. 
```html
@if (expr; as alias) {
   {{expr}}
}
```
would it generate this one? 
```ts
 var _t1 = ((this).expr); 
 if (_t1) { 
   "" + ((this).expr);  // this.expr will be catched ? 
 }
```

**Comment by crisbeto** [comment]
Yes it would, but it's not worth the additional effort to deduplicate it since this is only used during type checking so we don't care about the size of the code.

**Review by dylhunn — APPROVED** [review]
Looks straightforward. Thanks for fixing this!

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 02edb4306736e6f12e87a4164c17eca6cbdfe151.

**Pull request closed without merging**
