### PR TITLE
fix(zone.js): patch node for nested fs functions

### LINKED ISSUE #45546: zone.js/node breaks for fs.realpath.native and fs.realpathSync.native
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

1. Using the ready-made https://angular.io/generated/zips/universal/universal.zip from https://angular.io/guide/universal.  

2. Edited `server.ts` or the TypeScript would whine ([TS4111](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature)) and refuse to run.
   ```diff 
   -  const port = process.env.PORT || 4000;
   +  const port = process.env['PORT'] || 4000;
   ```

3. I added the following at the very beginning of the `server.ts`:
   ```diff
   +  console.log("NODEJS VERSION:", process.version);

   +  console.log("=====1=====");
   +  import * as fs from 'fs';
   +  console.log("2nd-level API fs.appendFile:", fs.appendFile); // a second-level API (fs.xxx)
   +  console.log("2nd-level API fs.realpath:", fs.realpath);
   +  console.log("3rd-level API fs.realpath.native:", fs.realpath.native); // a third-level API (fs.xxx.yyy)

   =  import 'zone.js/node';

   +  console.log("=====2=====");
   +  console.log("2nd-level API fs.appendFile:", fs.appendFile); // a second-level API (fs.xxx)
   +  console.log("2nd-level API fs.realpath:", fs.realpath);
   +  console.log("3rd-level API fs.realpath.native:", fs.realpath.native); // a third-level API (fs.xxx.yyy)

   =  import { ngExpressEngine } from '@nguniversal/express-engine';
   ```
   
4. `npm install` followed by `npm run dev:ssr` command.

5. It seems like the `import 'zone.js/node';` did something to the `fs`.
    `fs.realpath.native` become `undefined` from the logs.
    
    image

6. It does seem like [zone.js/node](https://www.npmjs.com/package/zone.js) did not factor in `fs` third-level functions. From the [fs API documentation](https://nodejs.org/docs/latest-v14.x/api/fs.html), most are second-level functions (i.e. `fs.xxx`). But there are 2 exceptions since NodeJS 9.2.0 that are in third-level (i.e. `fs.xxx.yyy`), which are `fs.realpath.native` and `fs.realpathSync.native`. So when the package did some wrapping around, the third-level functions broke.

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true
`fs.realpath.native` is `undefined`
`fs.realpathSync.native` is `undefined`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.1
Node: 14.19.1
Package Manager: npm 6.14.16
OS: win32 x64

Angular: 13.3.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.1 (cli-only)
@angular-devkit/build-angular   13.3.1
@angular-devkit/core            13.3.1 (cli-only)
@angular-devkit/schematics      13.3.1 (cli-only)
@nguniversal/builders           13.1.0
@nguniversal/express-engine     13.1.0
@schematics/angular             13.3.1 (cli-only)
rxjs                            7.4.0
typescript                      4.5.5
```

### Anything else?

Fixed by PR https://github.com/angular/angular/pull/45552

### PR DESCRIPTION
**Pull request by lamweili**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Only direct `fs` functions are patched by `zone.js/node`.
After `zone.js/node` patches `fs` functions, nested `fs` functions become `undefined`. 
* `fs.realpath.native` is `undefined`
* `fs.realpathSync.native` is `undefined`

Issue Number: angular#45546

## What is the new behavior?
It patches the nested functions `fs.realpath.native` and `fs.realpathSync.native` first, storing them in a temporary space, before patching the usual `fs` functions (which will cause the nested functions to be `undefined`). Lastly, it populates back the patched nested functions from the temporary space back to `fs`.

* `fs.realpath.native` is patched by `zone.js/node` and is no longer `undefined`
* `fs.realpathSync.native` is patched by `zone.js/node` and is no longer `undefined`

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information
Fixes: angular#45546

### CODE REVIEW

**Comment by JiaLiPassion** [comment]
@peteriman , thank you for the PR, could you add test case to make sure the method is patched correctly?

**Comment by peteriman** [comment]
Hi @JiaLiPassion, I would need some help on that and would need your advice.
I have contacted you privately.

**Comment by dylhunn** [comment]
Converting this to draft since it doesn't seem to be ready for review, until the unit test issue is resolved

**Comment by JiaLiPassion** [comment]
@lamweili , sorry I didn't have time to review this one, I will check it this week.

**Comment by lamweili** [comment]
@JiaLiPassion, thanks. I have emailed you my questions previously.

**Comment by lamweili** [comment]
@JiaLiPassion, thanks. I have emailed you my questions on 8 April thereabouts previously. Have you gotten the time?

**Comment by JiaLiPassion** [comment]
@lamweili , sorry for the late response, I updated the source and also added test cases, please check the test cases and make it complete and run 
```
yarn bazel test //packages/zone.js/...
```

to make sure the test passed.

Then `rebase` the PR to the latest `main` branch content.

Thank you.

**Comment by JeanMeche** [comment]
I'm closing old draft PRs coming from outside contributors. Feel free to ping if you'd like to keep it open.

**Pull request closed without merging**
