### PR TITLE
fix(testing): remove deprecated testing APIs

### PR DESCRIPTION
**Pull request by juliemr**
See https://github.com/angular/angular/blob/master/CHANGELOG.md for
prior deprecation and how to update.

### CODE REVIEW

**Comment by juliemr** [comment]
See https://github.com/angular/angular/issues/9591

**Comment by juliemr** [comment]
Pending - I'd like to also include finishing the `TestComponentBuilder` move to core in this PR.

**Comment by juliemr** [comment]
Ok, ready for review now!

**Comment by vikerman** [comment]
LGTM.

Does this need a BREAKING CHANGE commit message with a Before and After?

**Comment by juliemr** [comment]
I don't think so, the breaking change was already reported in https://github.com/angular/angular/blob/master/CHANGELOG.md for RC4.

Working on making Travis happy...

**Comment by juliemr** [comment]
Travis is green! Merging.

**Comment by eastlondoner** [comment]
How am I supposed to use Modules in tests?

All the public docs say is:

"We are still preparing the testing guide with all the new testing features introduced in RC5 and will update it very soon."

however RC5 breaks all of our tests and there is nothing documenting what the "new" testing looks like.

I've attempted to reproduce some of the stuff that is in testing_internal but I am now getting:

Cannot read property 'injector' of null
	    at TestBed._createCompilerAndModule

**Comment by qdouble** [comment]
@eastlondoner - check the test examples in the ng2-bootstrap repo: https://github.com/ng-bootstrap/ng-bootstrap/tree/1266e0451bb8de5623fa7f7dbc0386a2a5dc77e7/src

**Pull request merged**
