### PR TITLE
build: update to nodejs rules 0.38.3

### PR DESCRIPTION
**Pull request by gregmagolan**
Some changes in rules_nodejs providers folded into @angular/bazel package:
* `NodeModuleSources` renamed to `NpmPackageInfo` and now loaded from `//internal/common:npm_package_info.bzl`
* `collect_node_modules_aspect` renamed to `node_modules_aspect`
* new JS provider `JSNamedModuleInfo` now available and ng_module provides it using the `js_named_module_info` factory function
* sources_aspect has also been removed so the use of the `node_sources` legacy provider has been replaced with `JSNamedModuleInfo`.

### CODE REVIEW

**Comment by gregmagolan** [comment]
@alexeagle Changes to external.bzl will need g3 equivalents

**Comment by gregmagolan** [comment]
@alexeagle @devversion Looks like we may need an update to material to get this in like we did with the 0.38.1 update

**Comment by gregmagolan** [comment]
@alexeagle @devversion Looks like we'll need to update material to 0.38.2 first to green this PR up. I'll make a PR in the morning if you don't get to it overnight @devversion .

**Review by mhevery — APPROVED** [review]

**Comment by alexeagle** [comment]
Note to caretaker: cl/271704225 has to land before this can get a green g3sync

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
caretaker: [g3sync presubmit](http://test/OCL:274242159:BASE:274242181:1570827248633:f0b5eb4c)

**Pull request closed without merging**
