### PR TITLE
refactor(forms): replace errors with hasError()

### LINKED ISSUE #55378: Use hadError instead of errors
### Describe the problem that you experienced

Angular material made the choice to use `hasError()` in their documentation. For homogeneity reason, I believe it's better that both documentation use the same way to display form errors.

### Enter the URL of the topic with the problem

https://angular.dev/guide/forms/form-validation#validating-input-in-template-driven-forms

### Describe what you were looking for in the documentation

_No response_

### Describe the actions that led you to experience the problem

_No response_

### Describe what you want to experience that would fix the problem

_No response_

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by ice-blaze**
Material documentation use hasError. For homogeneity reason, this commit will adopt material style.

Fixes #55378

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #55378

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ice-blaze** [comment]
The material discussion about use `hasError` instead of `errors` https://github.com/angular/components/pull/28884#issuecomment-2059568167
The issue related to it https://github.com/angular/components/issues/28883

**Review by JeanMeche — APPROVED** [review]
Thanks for this improvement !

**Review by sonukapoor — APPROVED** [review]
I agree `hasError` is a better approach. 👍

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit e54c950e92a149ebda0ba5240637749fec552368.

**Pull request closed without merging**
