### PR TITLE
docs: add Nikita Poltoratsky to GDE resources

### PR DESCRIPTION
**Pull request by Tibing**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Thanks for this, @Tibing, and congrats! 🌟 Could you get your picture smaller than 30k, [squash, and rebase](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase)? You'll also want to add a body to your commit message that is at least 100 characters. You could use this one if you like:

```
docs: add Nikita Poltoratsky to GDE resources

This commit adds Nikita Poltoratsky to the GDE resources page, gives a brief bio, and adds his photo.

```

If you'd like any help with the workflow, just tag me.

**Review by mgechev — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Hi @Tibing,

This PR was approved, but as Kapunahele mentioned above, there is a couple action items before we can proceed with the merge:

- update the picture to use a version of it that'd be smaller than 30k
- squash commits and update the commit message (see https://github.com/angular/angular/pull/37082#issuecomment-655637965)
- rebase this PR on top of the latest master and resolve the merge conflict

Please let us know if you have any questions, we'll be glad to help.

Thank you.

**Comment by petebacondarwin** [comment]
Hi @Tibing - this PR still needs some work. See https://github.com/angular/angular/pull/37082#issuecomment-733296331
Can you take a look, please?

**Comment by AndrewKushnir** [comment]
FYI, I'm closing this PR for now due to the lack of response. Feel free to reopen when you get a chance to look at it in the future. Thank you.

**Pull request closed without merging**
