### PR TITLE
build(bazel): Turning on strictPropertyInitialization for Angular.

### PR DESCRIPTION
**Pull request by rkirov**
All errors for existing fields have been detected and suppressed with a
`!` assertion.

Issue #24571 is tracking proper clean up of those instances.

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by rkirov** [comment]
Waiting to hear from Martin on why does clang-format decided to do 'foo !: string', instead of 'foo!: string', which is way better IMHO.

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
http://test/OCL:201432174:BASE:201432279:1529535233454:ab292332

**Comment by mhevery** [comment]
@alxhub There seems to be some weird interaction between this PR and `ngtsc` could you have a look?

**Comment by rkirov** [comment]
@alxhub The extra '!' have no runtime implications, but it is possible that the syntax throws off the new transformers.

**Comment by rkirov** [comment]
AlexR and I sorted out the ivy failures, PTAL

**Pull request closed without merging**
