### PR TITLE
build: migrate to enabling ivy via --config=ivy bazel flag 

### PR DESCRIPTION
**Pull request by josephperrott**
Remove all usage of `--define=compile=*` within the angular/angular repo, using `--config=ivy` instead.

See individual commits for more information about specific changes.

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
I think you got them all! Thanks for a great cleanup throughout the whole repo.

**Comment by IgorMinar** [comment]
And I also appreciate that you are putting more context into the commit messages. It makes reviews much easier.

**Comment by IgorMinar** [comment]
merge-assistance: global approval

@josephperrott if you don't want to wait for @gregmagolan then remove him from reviewer list and add merge-assistance (due to global approval override).

**Review by gregmagolan — APPROVED** [review]
LGTM

**Pull request closed without merging**
