### PR TITLE
build: add script to publish v10-lts releases

### PR DESCRIPTION
**Pull request by zarend**
Adds a script to publish v10-lts versions to npm. This will make it easier to do further v10-lts releases.

I copied the `scripts/release/publish-latest` script, then changed the `--tag latest` to `--tag v10-lts`

I also added suggested changes to the release docs with instructions on doing a 10.2.x release: https://docs.google.com/document/d/1mUlhZejeOoQXVFKfI9-9CPPWtFRCZOpB76oLHS-v5C4/edit#

### CODE REVIEW

**Review by josephperrott — CHANGES_REQUESTED** [review]
If we are going to have a specific LTS release script for this branch, we should also delete the `publish-latest` and `publish-next` scripts

**Comment by zarend** [comment]
that's a good point, I removed the scripts for `latest` and `next`, since this branch is only for `v10-lts`.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by AndrewKushnir** [comment]
Closed by commit 318e7b8ce4a7c3d64bc37cb832e3d588b0ebd4a7

**Pull request closed without merging**
