### PR TITLE
fix minor typo on issue template

### PR DESCRIPTION
**Pull request by dlo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:

Issue template update.

## What is the current behavior?

There was a missing 's'.

## What is the new behavior?

Now the 's' is no longer missing.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

❤️

### CODE REVIEW

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update the git commit message to `docs: fix minor typo on issue template`

**Comment by brandonroberts** [comment]
Thanks for the PR @dlo! I left you some feedback.

Once that change is made, its reviewed and approved, and is green on CI it will be ready to merge.

**Comment by dlo** [comment]
@brandonroberts just updated. :)

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks for the PR @dlo! The issue templates are being completely redone here https://github.com/angular/angular/pull/26918, so this one is no longer needed. If you see something else, feel free to open a new PR.

**Pull request closed without merging**
