### PR TITLE
docs: remove Ivy-specific guides

### PR DESCRIPTION
**Pull request by dgp1130**
Ivy is the only supported rendering engine in v13, so there is no need to document the concept. Everything in Angular is Ivy. This starts the removal process by deleting Ivy-specific guides and references to them. It also updates the glossary to be more clear that Ivy is the current rendering engine while View Engine is simply a historical note.

This does not attempt to fully remove all references to "Ivy" or "View Engine", that will likely be a more involved clean up process.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Documentation content changes

## What is the current behavior?

AIO has Ivy specific guides and pages which are no longer needed in v13 where Ivy is the only supported rendering engine.

## What is the new behavior?

These guides and references to them are removed. This PR does *not* attempt to remove all references to Ivy and View Engine (though we should definitely do that). This is just a starting point for the removal and to help us be more clear that View Engine is not supported in v13.

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
Awesome! Thank you

Reviewed-for: global-docs-approvers

**Review by jelbourn — APPROVED** [review]
lgtm 💠

**Review by IgorMinar — APPROVED** [review]
hmm.. how come my previous approval didn't work? let's try again..


Reviewed-for: global-docs-approvers

**Review by IgorMinar — APPROVED** [review]
ah.. one more try..

Reviewed-for: global-approvers

**Review by AndrewKushnir — APPROVED** [review]
Thanks for the cleanup Doug!

**Review by aikithoughts — APPROVED** [review]
LGTM!

Reviewed-for: global-docs-approvers

**Pull request closed without merging**
