### PR TITLE
refactor(service-worker): Remove deprecated `activated` & `available` observables.

### PR DESCRIPTION
**Pull request by JeanMeche**
`activated`and `available` were deprecated by #43535 in v13.

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: docs-infra

**Review by alxhub — APPROVED** [review]
Reviewed-for: public-api

**Review by alxhub — APPROVED** [review]
Reviewed-for: global-approvers

**Comment by alxhub** [comment]
Caretaker: saucelabs flake

**Pull request closed without merging**
