### PR TITLE
Styling more perf scenarios

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
(review commit by commit)

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
can you please also add "static style" scenario? otherwise lgtm. thanks!

**Comment by pkozlowski-opensource** [comment]
@IgorMinar added the static style (`style="color: red"`) use-case.

**Comment by IgorMinar** [comment]
there was a typo in the commit message so I fixed it and forcepushed

**Comment by atscott** [comment]
[presubmit](https://test.corp.google.com/ui#id=OCL:289674440:BASE:289674505:1579024998795:e85c24c2)

**Pull request closed without merging**
