### PR TITLE
fix(platform-webworker): remove platform-webworker and platform-webworker-dynamic

### PR DESCRIPTION
**Pull request by josephperrott**
Remove @angular/platform-webworker and @angular/platform-webworker-dynamic
as they were deprecated in v8

BREAKING CHANGE: @angular/platform-webworker and @angular/platform-webworker-dynamic
have been removed as they were deprecated in v8

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: docs-infra

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: fw-core

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: fw-playground, docs-packaging-and-releasing

[image](https://www.youtube.com/watch?v=q3svW8PM_jc)

**Review by IgorMinar — APPROVED** [review]
LGTM! Thank you!

Reviewed-for: global-approvers

**Comment by IgorMinar** [comment]
I removed Alex as there are no significant framework specific bits to review here.

**Pull request closed without merging**
