### PR TITLE
Apply standard header case convention in docs

### PR DESCRIPTION
**Pull request by jbogarthyde**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The Google doc guideline to use sentence-style capitalization for page titles is not in the Angular doc guidelines, and is not applied consistently.

Issue Number: https://github.com/angular/angular/issues/21605#

## What is the new behavior?
- Adds the recommendation to the guidelines
- Applies the correct case to all pages
- Fixes some incidental terminology and organizational inconsistencies encountered while touching every page.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jbogarthyde** [comment]
This is a docs-only change and does not actually require technical review from every code-owner. 
@kara should look at it, since it includes some terminology/doc org corrections for ivy/ngcc.

**Review by kapunahelewong — APPROVED** [review]
Wow, thanks for this Judy. Did you mean to delete `ngcc.md`? Otherwise LGTM!

**Comment by jbogarthyde** [comment]
> Did you mean to delete `ngcc.md`? Otherwise LGTM!

Yes -- it was a whole new page that just had a 2-sentence definition of the term, and sat uneasily in the CLI section. I added the definition to the glossary (along with "Ivy") and replaced the references to the page with references to the glossary definition.

**Review by petebacondarwin — APPROVED** [review]
LGTM!

**Review by IgorMinar — APPROVED** [review]
lgtm, global approval

**Comment by IgorMinar** [comment]
merge-assistance: global approval

**Pull request closed without merging**
