### PR TITLE
LTS-only - fix(core): use appropriate inert document strategy for Firefox & Safari 

### PR DESCRIPTION
**Pull request by petebacondarwin**
Both Firefox and Safari are vulnerable to XSS if we use an inert document
created via `document.implementation.createHTMLDocument()`.

Now we check for those vulnerabilities and then use a DOMParser or XHR
strategy if needed.

Further the platform-server has its own library for parsing HTML, so we
sniff for that (by checking whether DOMParser exists) and fall back to
the standard strategy.

Thanks to @cure53 for the heads up on this issue.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## Other information

This is the LTS version of #17019

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
uh. oh. I'm afraid that if we want to merge this we'll need several of @gkalpak's CI stability changes as well - at minimum the chrome/chrome-driver changes that prevent chrome flakes and crashes.

**Comment by gkalpak** [comment]
CI is green now :tada:

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
the instructions at https://g3doc.corp.google.com/javascript/angular/g3doc/sync.md#syncing-tap-status-to-github don't work for me, so I can't force push the g3 status for this pr.

@mhevery can you please try to force push the status? since this PR targets the lts branch, the g3 check is pointless.

**Comment by IgorMinar** [comment]
wrt the error, I'm getting `  error: unknown option `--raw-output'` (that is after I had to install `npm install -g jq` and some other packages.

**Comment by mhevery** [comment]
merged as 2c5cf19c6d

**Pull request closed without merging**
