### PR TITLE
docs: Fix typo in application_common

### PR DESCRIPTION
**Pull request by mgechev**

### CODE REVIEW

**Comment by PascalPrecht** [comment]
LGTM. @mgechev could you change your commit message to `docs: ...` ?

**Comment by PascalPrecht** [comment]
@mgechev I actually didn't mean the PR title, but your commit message :)

Simply run `git commit --amend` and change it there.

**Comment by mgechev** [comment]
@PascalPrecht uups, fixed it :-)
Thanks!

**Comment by PascalPrecht** [comment]
LG! :+1:

**Pull request closed without merging**
