### PR TITLE
fix(core/testing): show full error

### PR DESCRIPTION
**Pull request by PatrickJS**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
not showing full stacktrace

**What is the new behavior?**
show full stacktrace tracked by zone.js

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

**Other information**:
before

screen shot 2016-06-20 at 5 53 59 pm

after

screen shot 2016-06-20 at 5 51 20 pm

### CODE REVIEW

**Comment by vicb** [comment]
:+1:

**Comment by gdi2290** [comment]
oh nice, the tests have tests

**Comment by vicb** [comment]
we even test CS :) (run gulp format)

**Comment by gdi2290** [comment]
@vicb tests are green. I ran format and pushed that so it should be good

**Comment by vicb** [comment]
could you please squash your commit ? (tests should pass on every single sha)

**Comment by gdi2290** [comment]
@vicb kk good to go

**Comment by vicb** [comment]
thanks !

**Comment by vicb** [comment]
merged via 297f0fd

**Pull request closed without merging**
