### PR TITLE
docs: display the beginning label in interpolation guide example

### PR DESCRIPTION
**Pull request by jamierytlewski**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The docs looked strange with a hanging </label> tag. I included the full context. 
Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by trotyl** [comment]
@jamierytlewski Could you please squash the commits into one and change the message to something like `docs: add the beginning label`?

For reviewers:

Link: https://angular.io/guide/template-syntax#expression-context
Position: Code block of `src/app/app.component.html (template reference variable)`.
Screenshot:

image

**Comment by jamierytlewski** [comment]
Sorry about the delay. The merge has been squashed. Thanks.

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update the git commit message to `docs: display the beginning label in interpolation guide example`

**Comment by jamierytlewski** [comment]
I have made the changes.

**Review by brandonroberts — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]

**Pull request closed without merging**
