### PR TITLE
UpperCase and LowerCase pipes

### PR DESCRIPTION
**Pull request by PatrickJS**
because the world needs more uppercase madness 

update:

update: 
there was a refactor with facade

### CODE REVIEW

**Comment by gdi2290** [comment]
the api for pipes changed between master and tagged release so I need to repo this

**Comment by mhevery** [comment]
Needs Dart cleanup:

```
dist/dart/angular2:[warning] Undefined name 'NO_CHANGE' (/home/travis/build/angular/angular/dist/dart/angular2/lib/src/change_detection/pipes/lowercase_pipe.dart, line 22, col 14)
dist/dart/angular2:[warning] Undefined name 'NO_CHANGE' (/home/travis/build/angular/angular/dist/dart/angular2/lib/src/change_detection/pipes/uppercase_pipe.dart, line 22, col 14)
dist/dart/angular2:[warning] Undefined name 'NO_CHANGE' (/home/travis/build/angular/angular/dist/dart/angular2/test/change_detection/pipes/lowercase_pipe_spec.dart, line 40, col 27)
dist/dart/angular2:[warning] Undefined name 'NO_CHANGE' (/home/travis/build/angular/angular/dist/dart/angular2/test/change_detection/pipes/uppercase_pipe_spec.dart, line 40, col 27)
dist/dart/angular2:[hint] Unused import (/home/travis/build/angular/angular/dist/dart/angular2/test/change_detection/pipes/lowercase_pipe_spec.dart, line 7, col 8)
```

**Comment by mhevery** [comment]
@gdi2290 please rebase on master and fix the import issues which are breaking Dart.

**Comment by gdi2290** [comment]
@mhevery the PR is ready for merge. The problem I had was building for the API that was on NPM which had `NO_CHANGE` which is now using `WrappedValue` I can get `JsonPipe` this weekend

**Comment by vicb** [comment]
merged via 7a4a6353998fe66e59f6630f1a722c6000ef4bba + previous commit

**Pull request closed without merging**
