### PR TITLE
feat(forms): add ontouched on focusout event

### PR DESCRIPTION
**Pull request by StefanNieuwenhuis**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

While using a custom form input element (i.e. a Custom Element), the validation engine won't fire while focussing out. This is because the onBlur event doesn't bubble. 

Issue Number: N/A

## What is the new behavior?
On focussing out, the onTouched() event handler will be triggered.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by StefanNieuwenhuis** [comment]
CLA?

**Comment by StefanNieuwenhuis** [comment]
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and have the pull request author add another comment and the bot will run again. If the bot doesn't comment, it means it doesn't think anything has changed.
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fangular%2Fangular%2Fpull%2F31046) for more info**.

Does it work now?

**Comment by kapunahelewong** [comment]
@StefanNieuwenhuis are you by chance using a different email address than what you used to sign the CLA originally? When it's working, it should automatically change the label to the green `cla: yes`.

**Comment by StefanNieuwenhuis** [comment]
Hi Kapunahele, 

I just checked it and, as far as I can see it's all synced.
I checked the following:
- Gmail mail-address (my main account is the only active one)
- Github mail-address (this was indeed a different one, but changed it 4 hours ago)
- CLA Subscription (name, mail-address & GitHub account)

Do I miss anything?

**Comment by alfaproject** [comment]
The email you used for the commit is either empty or not associated with your GitHub account

**Comment by StefanNieuwenhuis** [comment]
> The email you used for the commit is either empty or not associated with your GitHub account

My e-mail was indeed different, so I've updated it. Thanks for pointing it out :)

**Comment by AndrewKushnir** [comment]
Hi @StefanNieuwenhuis, thanks for creating this PR and sorry that we didn't have a chance to review/respond sooner. 

The proposed change will be a breaking change for a large portion of applications (since new behavior would be invoked for a lot of input elements), so we would not be able to land it without a strong signal from the community that this change is mandatory to resolve a critical issue or there are major benefits that can justify the breaking change.

I believe that in the mentioned use-case you should be able to achieve the necessary functionality by creating your custom value accessor (which can be based on default one with extra added functionality).

Thank you.

**Pull request closed without merging**
