### PR TITLE
build(bazel): fix yarn path and workaround issues with AIO deploy script

### PR DESCRIPTION
**Pull request by kormide**
The YARN_BIN env var path was relative to the runfiles root, so cwd in shelljs caused it to not be found.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The AIO deploy script performed a shelljs `cwd`, which made it unable to find the vendored yarn because the path was relative to the runfiles root. There was also a missing dependency on AIO's package.json file.

## What is the new behavior?

Resolved absolute yarn path and added missing dep.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by kormide** [comment]
Still working through a couple of missing deps.

**Comment by kormide** [comment]
Updated with workaround as discussed.

**Comment by kormide** [comment]
Do not merge.

**Pull request closed without merging**
