### PR TITLE
feat(platform-server): rename `provideServerSupport` to `provideServerRendering`

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit renames `provideServerSupport` to `provideServerRendering`.

### CODE REVIEW

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: fw-platform-server, public-api

**Review by AndrewKushnir — APPROVED** [review]
👍

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 7870fb07fe6b25f5ebb22497bff3a03b7b5fc646.

**Pull request closed without merging**
