### PR TITLE
Complex animation sequences update

### PR DESCRIPTION
**Pull request by trekladyone**
Linting corrections. Restructuring or rewording sentences to be shorter and clearer. Inserted an introductory paragraph under level 1 heading.

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@trekladyone There's a merge commit in the history. Can you rebase and drop the merge commit?

**Review by jessicajaniuk — APPROVED** [review]
LGTM

Once you get the rebase done, we can merge this.

**Comment by jessicajaniuk** [comment]
@trekladyone I've rebased this for you. We can proceed with merge.

**Review by jessicajaniuk — APPROVED** [review]

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 177c55686d37deedde56008fc03b0c70a3282b94.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit af8afee5bde7a3078c35202db75d1b2b6a8e7bee.

**Pull request closed without merging**
