### PR TITLE
docs(docs-infra): fix a11y of external links

### LINKED ISSUE #43512: a11y (accessibility) of "open in new window" link icons
### Description

The "opens in new window" icon seems to not get announced correctly by a screen reader, or maybe not behave as you might expect: 
1. In Firefox, I hear "open_in_new", which gets announced as "open underscore in underscore new", instead of simply "opens in new window or tab". 
2. In Chrome, I don't hear that announced at all. 
3. When you on links with that icon, it does not seem to open in a new window or tab for me. 

I don't believe I have opening new windows/tabs automatically disabled, but hopefully someone can repro this bug to confirm. 

### What is the affected URL?

https://angular.io/docs

### Please provide the steps to reproduce the issue

1. Mac > Firefox > https://angular.io/docs > turn on VoiceOver > tab to the first link with that "opens in new window" icon. 
2. Mac > Chrome > https://angular.io/docs > turn on VoiceOver > tab to the first link with that "opens in new window" icon. 

Should get similar results for other screen readers. 

### Please provide the expected behavior vs the actual behavior you encountered

If the link is intended to behave as opening in a new tab/window, then ideally the announcement should match in Firefox with something like "open in new window or tab". 

If the link is intended to simply change the URL to a new page, then maybe the icon could simply be removed, since that icon usually indicates opening in a new tab/window. 

## Firefox:
firefox

## Chrome:
chrome

## VoiceOver says "open underscore in underscore new" in Firefox:
voiceover open_in_new

### Please provide the exception or error you saw

_No response_

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

_No response_

### PR DESCRIPTION
**Pull request by hchiam**
prevent screen readers from falsely announcing "open_in_new" since they may not actually open new tabs/windows but simply send the current page to a domain outside angular.io

Fixes #43512

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features) - (EDIT: Can we easily simulate screen readers with an e2e?)
- [ ] Docs have been added / updated (for bug fixes / features) - (EDIT: not sure if applicable?)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [x] Other... Please describe: Screen reader a11y (accessibility).

## What is the current behavior?

Screen readers literally say "open_in_new" as "open underscore in underscore new", but shouldn't even say that because the links don't open a new tab/window.

Issue Number: #43512

## What is the new behavior?
Screen readers won't announce the material icon `content: "open_in_new";`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

First time contributing to this project! :)

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Thanks for this @hchiam.
Can I check if you meant to update the yarn.lock file? If so, why? If not, can you remove it from the PR?
Otherwise LGTM.

**Comment by petebacondarwin** [comment]
Oh and please can you rebase on top of the current `master` branch since that is blocking the CI from running. See the `setup` job.

**Comment by hchiam** [comment]
> Thanks for this @hchiam. Can I check if you meant to update the yarn.lock file? If so, why? If not, can you remove it from the PR? Otherwise LGTM.

I'm not sure why I had to, but I needed the updated deps to be able to run the site locally. Feel free to commit changes to this PR to help us get the CI to pass.

**Review by petebacondarwin — APPROVED** [review]

**Comment by atscott** [comment]
This PR was merged into the repository by commit 8920fa093b95f2658ef52a1be68c0d0b496be49c.

**Pull request closed without merging**
