### PR TITLE
Location of text was incorrect & a duplicate snippet

### PR DESCRIPTION
**Pull request by edjm1971**
The code example exists in this location which is not correct. It is further down the page and with it in this location it confused the heck out of me as to what I was to do with it.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Thanks for this @edjm1971 :D The order reads ok to me, though. @chembu what do you think?

**Comment by edjm1971** [comment]
@kapunahelewong from the perspective of one that knows Angular I can understand that it would make sense. However to someone new to this, such as myself, they may be baffled about the reference for the code <app-hero-detail [hero]="selectedHero"></app-hero-detail> because I had no idea where it is to be placed. It is not until further down the page where it shows what file this code should be placed. This is why I suggested that the page be updated. 
I felt like I was missing something for several frustrating moments when I reached that code section and thus backtracked what I had read and done thinking that I missed a step somewhere.

**Comment by edjm1971** [comment]
Also, this approach of presenting the code prior to informing the reader where it goes does not exist anywhere else in the tutorial. All other code references I believe in this tutorial has it where the code presented is to go into the file referenced by the prior code snippet with a blue banner. 

Changing the notion to present the code and a user is to know it goes to another file that has not been presented yet can at least in my case cause confusion.

**Comment by chembu** [comment]
I think that example text is in the right place. We are just showing the user how the property binds to the Heroes component. _Update the HeroesComponent template_ section clearly shows where the user needs to update the code.

**Comment by chembu** [comment]
The _Add the @Input() hero property_ section is showing the user how the property binds to the component. The _Update the HeroesComponent template_ clearly show where the code goes. So I think the text is in the right place.

**Comment by kapunahelewong** [comment]
Though I am in agreement with @chembu, @edjm1971, I do see your point. That bit that you're thinking to move isn't accompanied with instructions to copy it into the project yet. It's just there to show you why you're going to use `@Input()` in the component class since this is possibly the first time a reader encounters it in the learning process. But since you did find it a stumbling block, how about clarifying where it is (rather than moving it since the next section has instructions where to put it)? We do still want readers to understand the purpose of using `@Input()`. You could do something to clarify something like this (but smoother!):

image

Or even consider removing it altogether (I like this one a lot less but welcome conversation on it anyway 🙂):
image

The second way leads succinctly through the steps, but lacks the reasoning behind it. With the reason for doing it, the concepts stick better.

Hope these ideas help. We are happy to consider other ideas too. These are just the first two I've come up with. :)

**Review by IgorMinar — APPROVED** [review]
LGTM. Thank you!

**Comment by IgorMinar** [comment]
Thank you for your contribution @edjm1971, but I see that a different change was already made to resolve the same issue. I'm going to go ahead and close this PR since the proposed change is no longer compatible and the original issue has been resolved.

**Pull request closed without merging**
