### PR TITLE
fix(common): `locales` are not being shipped 

### PR DESCRIPTION
**Pull request by alan-agius4**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number:  #23140, #23103

## What is the new behavior?
locales are shipped

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by alan-agius4** [comment]
@alexeagle can you have a quick look please? Thanks :)

**Comment by alan-agius4** [comment]
`yarn buildifier` is throwing an error on windows even in admin mode

```sh
λ yarn buildifier
yarn run v1.3.2
$ bazel build --noshow_progress @com_github_bazelbuild_buildtools//buildifier
DEBUG: C:/users/alag/appdata/local/temp/_bazel_alag/btbwur4a/external/io_bazel_rules_go/go/private/toolchain.bzl:104:5: mkdir C:\WINDOWS\go-build100047967: Access is denied.
ERROR: C:/users/alag/appdata/local/temp/_bazel_alag/btbwur4a/external/io_bazel_rules_go/go/toolchain/BUILD.bazel:6:1: every rule of type _go_toolchain implicitly depends upon the target '@go_sdk//:packages.txt', but this target could not be found because of: no such package '@go_sdk//': Traceback (most recent call last):
        File "C:/users/alag/appdata/local/temp/_bazel_alag/btbwur4a/external/io_bazel_rules_go/go/private/toolchain.bzl", line 45
                _prepare(ctx)
        File "C:/users/alag/appdata/local/temp/_bazel_alag/btbwur4a/external/io_bazel_rules_go/go/private/toolchain.bzl", line 105, in _prepare
                fail("failed to list standard package...")
failed to list standard packages
ERROR: Analysis of target '@com_github_bazelbuild_buildtools//buildifier:buildifier' failed; build aborted: no such package '@go_sdk//': Traceback (most recent call last):
        File "C:/users/alag/appdata/local/temp/_bazel_alag/btbwur4a/external/io_bazel_rules_go/go/private/toolchain.bzl", line 45
                _prepare(ctx)
        File "C:/users/alag/appdata/local/temp/_bazel_alag/btbwur4a/external/io_bazel_rules_go/go/private/toolchain.bzl", line 105, in _prepare
                fail("failed to list standard package...")
failed to list standard packages
INFO: Elapsed time: 29.225s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alan-agius4** [comment]
fixed the lint on a mac

**Comment by alexeagle** [comment]
Let's file the issue with rules_go - I don't want to leave Windows broken...

Could you try upgrading the Go rules first - change /WORKSPACE to this version
https://github.com/alexeagle/angular-bazel-example/blob/master/WORKSPACE#L65

So that our issue report is against their current release (or maybe it will be solved by updating)

**Comment by alan-agius4** [comment]
Ill try that tomorrow morning, as at the moment I have only my Mac
available.

Ill give it a shot tomorrow and keep you posted.

**Review by alexeagle — APPROVED** [review]
Thanks!
It's simpler than I expected - I thought these nested locales directories needed to appear as entry points. But checking the output from the old build.sh (still published as https://github.com/angular/common-builds) this seems right to me.

**Review by IgorMinar — APPROVED** [review]

**Comment by alan-agius4** [comment]
Hi @alexeagle & @IgorMinar I relized I did a small mistake I did a nested `it` in the tests which was causing the tests to give false positives. I did a PR to change this. However, it s failing because in the data arg only `.d.ts` files are being passed. I check some other implementations of the data attr, ex: https://github.com/angular/angular/blob/master/packages/compiler/test/BUILD.bazel#L66 and cannot really quite get why only `.d.ts` files are passed. I can see that the `js` and `map` files are being generated if I do cd ../locales from `bin/packages/common/npm_package`. 

Any pointers where should I look?

PR: https://github.com/angular/angular/pull/23153

I am really sorry for this guys. But I didn't notice earlier about this mistake and problem, and the tests where not giving an error.

**Comment by alan-agius4** [comment]
Hey @alexeagle.

As promised I have tried to update the `Go Rules` on `Windows`. Now the error message have changed to something else. It seems the error is more related to `Bazel`. it seems that this issue is already tracked: https://github.com/bazelbuild/bazel/issues/4496

**Pull request closed without merging**
