### PR TITLE
build(rxjs): update RxJS to 5.1.1

### PR DESCRIPTION
**Pull request by benlesh**
This update includes an important memory leak fix.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: dependency update
```

```
[ ] Yes
[x] No
```

**Other information**:

Updates to RxJS to the latest version which has an important fix for a slow memory leak.

### CODE REVIEW

**Comment by gkalpak** [comment]
The shrinkerap also needs to be updated ([more info][1]).

[1]: https://github.com/angular/angular/blob/master/npm-shrinkwrap.readme.md

**Comment by blesh** [comment]
Looks like I also missed several other package.json files.

**Comment by gkalpak** [comment]
Now you have to also update [aio/yarn.lock][1] :smiley:
(The more you dig into it, the worse it'll get :stuck_out_tongue:)

[1]: https://github.com/blesh/angular/blob/2228295302cbf312235f16cc04bafd5dff1d5f7a/aio/yarn.lock

**Comment by ocombe** [comment]
Should we update to 5.2?

**Comment by benlesh** [comment]
Closed as out of date.

**Pull request closed without merging**
