### PR TITLE
refactor: remove unused benchmarks

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
The benchmarks in the 'old' directory are not used / maintained.

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]

**Review by devversion — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
This PR will need cleanup as the test invocation code exists in G3

**Comment by AndrewKushnir** [comment]
> This PR will need cleanup as the test invocation code exists in G3

@pkozlowski-opensource quick question (just to double check): any special instructions on g3 sync? Or g3 was already cleaned up and we can proceed with the merge and sync as normal?

**Comment by pkozlowski-opensource** [comment]
@AndrewKushnir I've dropped deletions that had corresponding invocations in G3, so should be safe to merge IMO as none of the code from this PR is synced to G3 (as far as I can tell).

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 143b85184d32393769c32bcade568890837641e6.

**Pull request closed without merging**
