### PR TITLE
docs(02_directives.md): foreach -> for

### PR DESCRIPTION
**Pull request by PatrickJS**

### CODE REVIEW

**Comment by sdwebster** [comment]
looks good to me!

**Comment by samccone** [comment]
ha this invalidated so many tutorials on the internet :crying_cat_face: :+1:

**Comment by matthewjh** [comment]
Such is the nature of pre-release OSS. I believe this is going to be changed again from For to NgFor. ;)

**Comment by vicb** [comment]
@matthewjh right, see #1900

**Comment by samccone** [comment]
:+1: no worries

**Pull request closed without merging**
