### PR TITLE
docs: change ”it's" to "its" as needed in several docs.

### PR DESCRIPTION
**Pull request by snood1205**
**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**What kind of change does this PR introduce?** (check one with "x")
```
[X] Other... Please describe: Fix documentation to be grammatically correct w.r.t. to it's vs. its. 
```

**What is the current behavior?** (You can also link to an open issue here)
It currently uses it's a fair amount for the possessive of it.

**What is the new behavior?**
It uses its where it should.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Could you update the commit message to follow the [commit message guidelines][1].

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by snood1205** [comment]
@gkalpak I have corrected the commit message. Sorry about that.

**Comment by gkalpak** [comment]
Strinctly speaking, the scope of the PR is not `aio`, since it touches files in `packages`.
And it needs approval from someone from the `common` pullaprove group.

**Comment by wardbell** [comment]
I fixed the commit message for you but, because of the one API doc change, it needs special approval.

**Comment by snood1205** [comment]
Something got messed up here I think. @rkirov

**Review by vicb — APPROVED** [review]

**Comment by vicb** [comment]
@snood1205 could you please rebase your PR ? (Sorry for the delay)

**Pull request closed without merging**
