### PR TITLE
docs(docs-infra): change MySixthClass to MyFifthClass

### PR DESCRIPTION
**Pull request by noorsyyed**
change MySixthClass to MyFifthClass in After migration section as it intend MyFifthClass

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

Please sign the CLA before we can merge this.

**Comment by petebacondarwin** [comment]
Also I'm afraid the commit message needs to be longer to pass our CI checks

**Comment by kapunahelewong** [comment]
Thanks for this, @noorsyyad! Could you sign the CLA? After you've done that, I can help you with amending the commit message and getting it to pass CircleCI. Will you tag me when you're ready?

**Comment by petebacondarwin** [comment]
Closing due to lack of response.

**Pull request closed without merging**
