### PR TITLE
refactor(Type): merge Type and ConcreType<?> into Type<?>

### PR DESCRIPTION
**Pull request by mhevery**

### CODE REVIEW

**Comment by mhevery** [comment]
LGTM per @IgorMinar

**Comment by vikerman** [comment]
Running TAP Presubmit...

**Comment by vikerman** [comment]
Breaking Google3 - Pinged Misko

**Comment by SharadPurohit** [comment]
What should i do in this case, when i want to use interface Type . For Example i have an array of Interface Type. After your change that does not apply. How can i use something like that.
As of now you are only allowing Concrete Class types.

**Pull request merged**
