### PR TITLE
fix(router): HashLocationStrategy should strip leading hash

### PR DESCRIPTION
**Pull request by pavelgj**

### CODE REVIEW

**Comment by pavelgj** [comment]
Not sure what to do here with the CLA...

**Comment by vicb** [comment]
Have you signed it with the gmail address used for this commit ?

**Comment by pavelgj** [comment]
@vicb I work @Google.

**Comment by tbosch** [comment]
@pavelgj Sorry, but you still need to sign the CLA :-(

**Comment by pavelgj** [comment]
I signed it!

**Comment by btford** [comment]
Ah! Wish I would've seen this a bit ago. We landed almost the same patch in https://github.com/angular/angular/commit/c177d889a2e17f846c181f3431478e83a3817a5e.

Closing this as a dup. Thanks though, @pavelgj!

**Pull request closed without merging**
