### PR TITLE
fix(router): shouldn't break history when CanDeactivate cancel back

### LINKED ISSUE #13586: Deactivation Guard breaks the routing history
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently, I have a deactivation guard on a route which will return false or true depending on a condition.  To get to this guarded route, the user must pass though 3 navigation step.  Now, once on the guarded route, when using `location.back()`, the guard is called. If it returns `true`, the previous route is loaded. If the guard returns false, the navigation is cancelled.  But if we redo a Location.back() after a failed navigation, the previous route that will be loaded will be 2 steps in the history instead of 1 (user perception).

Workflow
```
Main    -- navigate to     --> Route 1
Route 1 -- navigate to     --> Route 2
Route 2 -- navigate to     --> Route 3
Route 3 -- location.back() --> guard returns true  --> Route 2
Route 2 -- navigate to     --> Route 3
Route 3 -- location.back() --> guard returns false --> Route 3
Route 3 -- location.back() --> guard returns true  --> Route 1  (should be Route 2)
```

**Expected behavior**
An expected behavior for a user would be that navigating back brings back to the previous routed page.
Workflow
```
Main    -- navigate to     --> Route 1
Route 1 -- navigate to     --> Route 2
Route 2 -- navigate to     --> Route 3
Route 3 -- location.back() --> guard returns true  --> Route 2
Route 2 -- navigate to     --> Route 3
Route 3 -- location.back() --> guard returns false --> Route 3
Route 3 -- location.back() --> guard returns true  --> Route 2  (expected)
```

**Minimal reproduction of the problem with instructions**
[Plnkr](https://embed.plnkr.co/k1iX7PzmOre7P6ACtcur/)
1. Click button Nav to route1
2. Click button Nav to route2
3. Click button Nav to route3
4. Click button Block Nav Back
5. Click button Nav back
   - BOGUE: The location.back() routed on Route1 instead of Route2

**Personnal investigation**
After some investigation, I saw that in `routerState$.then` ([router.ts line 752](https://sourcegraph.com/github.com/angular/angular@b5c4bf1c59c56d48b8a536aa61c7bd72d94c99fc/-/blob/modules/@angular/router/src/router.ts#L756))  this logic used when `navigationIsSuccessful == false` is pretty simply but it is the actual cause of this bug.  Basically, when a deactivation guard is hit, the location of the browser is already changed to the previous route.  Which means that when the guard returns false, the `routerState$` runs his logic and calls `resetUrlToCurrentUrlTree()`.  At this point we can see that we replace the state of the current location.  But by doing this, we loose that route in the history which means that in my plunker, if we click the block nav back 3 times and then click the nav back we will actually kill the application.

**What is the motivation / use case for changing the behavior?**
This is for me a pretty big bug since a guard that returns false breaks alters the current routing history.  In the case of our application this breaks the workflow and brings wrong business scopes to a user.

**Please tell us about your environment:**

Windows 10, NPM, Nodejs, Visual Studio 2015  (using nodejs for typescript compilation)

* **Angular version:** 2.3.3

* **Browser:** [ all ]
 
* **Language:** [TypeScript 2.0.10 | ES5]

### PR DESCRIPTION
**Pull request by jasonaden**
navigation

Rebased from #13922.

Closes #13586

### CODE REVIEW

**Review by vicb — CHANGES_REQUESTED** [review]
As discussed in https://github.com/angular/angular/pull/13922#issuecomment-290574181 this does not account for the forward button.

Might be better to fix all in a single PR.

**Comment by jibbers42** [comment]
@vicb :thinking: Is waiting for forward to be fixed really required? Back is used so much more and it looks this was first fixed 6 months ago. Nobody seems too interested in addressing forward.

**Comment by MacKinley** [comment]
Anyone working this? Is this being postponed until the forward button issue [#15664](https://github.com/angular/angular/issues/15664) is solved as well and put into a single pull request?

**Comment by jasonaden** [comment]
Closing this PR as it's not getting approved as-is. We need to create a new PR to fix both issues.

**Comment by alfredorevilla** [comment]
@jasonaden so issues is still present?

**Comment by thanhnhan2tn** [comment]
+1

**Comment by apostnov** [comment]
> @jasonaden so are issues still present?

yes, still reproducable in 7.2

**Pull request closed without merging**
