### PR TITLE
feat(platform-server): added getComputedStyle implementation

### PR DESCRIPTION
**Pull request by ardatan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Now getComputedStyle method can be used in platform-server with flex-layout etc.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by ardatan** [comment]
any review?

**Comment by CaerusKaru** [comment]
@ardatan Can you refactor this for the new `domino` implementation?

@vikerman This needs to be prioritized for a current issue in `flex-layout`, see [here](https://github.com/angular/flex-layout/blob/12679727aa588e8646115839f90ab28901b23e0b/src/lib/utils/style-utils.ts#L86-L97)

**Comment by ardatan** [comment]
@CaerusKaru I sent new PR for domino adapter.

**Comment by CaerusKaru** [comment]
Thanks @ardatan, can you close this PR now that the other one is open?

**Pull request closed without merging**
