### PR TITLE
ci: update components repo unit tests job commit

### PR DESCRIPTION
**Pull request by devversion**
* See individual commits

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by kara** [comment]
Note: doesn't apply cleanly to patch. @devversion Can you create another PR for that?

**Comment by devversion** [comment]
@kara Yeah, created #37183 that captures the same change for the `9.1.x` branch.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by devversion** [comment]
I wanted to send another PR for updating to the components-repo commit for the TS 3.9 update, but changes were so similar, I incorporated that into this PR. Also this now re-enables the job.

**Pull request closed without merging**
