### PR TITLE
ci: add missing codeowners for `aio/` files

### PR DESCRIPTION
**Pull request by gkalpak**
☝️

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@gkalpak it looks like we need to add these rules to PullApprove config now (so I added "blocked" label for now).

**Comment by gkalpak** [comment]
Thx, @AndrewKushnir. Updated.

**Review by IgorMinar — APPROVED** [review]
thanks!

**Comment by IgorMinar** [comment]
@gkalpak this needs a rebase

**Comment by gkalpak** [comment]
Thx! Rebased.

**Pull request closed without merging**
