### PR TITLE
fix(forms): expose ControlConfig in public API

### PR DESCRIPTION
**Pull request by udaysonyy**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #46570

## What is the new behavior?

We can use ControlConfig type in application
- import { ControlConfig } from '@angular/forms';

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x ] No

### CODE REVIEW

**Comment by udaysonyy** [comment]
I have signed Contributor License Agreement (CLA).

**Comment by udaysonyy** [comment]
When I tried to run yarn bazel run //packages/forms:forms_api.accept, i am getting this error i tried my best but it's the same.

 
image
image

**Comment by udaysonyy** [comment]
I've tried so much but yarn is not working properly...

**Comment by AndrewKushnir** [comment]
@udaysonyy FYI I've updated this PR to reflect the change in the golden file.

@dylhunn could you please take a look at this change once again when you get a chance?

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-forms, public-api

Looks good, ~but it's odd that pullapprove isn't asking for public-api approval~ (this resolved itself). Also, I think the error in the components integration test CI result is a configuration problem or flake.

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
[Presubmit](https://fusion2.corp.google.com/presubmit/tap/460487627/OCL:460487627:BASE:460487655:1657644799779:89c48206/targets)

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit c0ca3fc71aabc8902c7ed68f8f6a0efd9d1a6d81.

**Pull request closed without merging**
