### PR TITLE
docs: remove unused imports and decreased the codesmells

### PR DESCRIPTION
**Pull request by alkavats1**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by alkavats1** [comment]
The “width” attribute on the table (or td) element is obsolete. Use CSS instead. Refer : https://developer.mozilla.org/en-US/docs/web/html/element/th#attr-width

**Comment by alkavats1** [comment]
Hi @crisbeto @jessicajaniuk please review the PR
Thanks

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 5576b9a5ea442cc98804bbeaeed0e0f11792c6f7.

**Pull request closed without merging**
