### PR TITLE
fix(forms): FormControl should emit status event on construction

### LINKED ISSUE #14542: FormGroup & FormControl statusChanges are not emitted on creation
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
FormGroup and FormControl don't emit statusChange after first creation (while untouched / pristine?) with asyncValidator.

1. Initial status of FormGroup and FormControl is "PENDING"
2. Both status changes to "VALID" or "INVALID"
3. statusChange is not emitted

**Expected behavior**
statusChange should always be emitted.

**Minimal reproduction of the problem with instructions**

1. Create a FormGroup with the FormBuilder and add a FormControl with asyncValidator(e.g. with a TimeOut Promise of 2sec).
2. Subscribe to FormGroup.statusChange or FormGroup.controls.key.statusChange

**Angular version**
2.4.1

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Closes #14542

### CODE REVIEW

**Comment by MickL** [comment]
Not sure if this is needed within constructor. Changes after construction will still not be emitted until FormControl is dirty.

**Comment by MickL** [comment]
Looks good! :)

**Comment by MickL** [comment]
Looks good in theory. Tried the fix but i get errors: `Cannot read property 'emit' of undefined`

**Comment by DzmitryShylovich** [comment]
`this._initObservables();` should be called before update

**Comment by MickL** [comment]
You are right! Still i see now changes in the behavior. I don't get any event when status changes unless the FormControl is dirty.

**Comment by DzmitryShylovich** [comment]
yeah, on construction event is emitted before you actually can subscribe to it :)

**Comment by MickL** [comment]
On line 393 emitEvent is still false for me

**Comment by MickL** [comment]
Not sure if this helps but for me `updateValueAndValidity()` is called three times for a single FormControl. Once before the form is even built:

bildschirmfoto 2017-02-17 um 00 13 36

**Comment by DzmitryShylovich** [comment]
> updateValueAndValidity() is called three times for a single FormControl. 

yeah, it's puzzling me too :)
Looks like the issue is that `emitEvent` is defaulted to false.

BehaviorSubject + `this._runAsyncValidator(true);` will emit right events. I'll update the pr later

**Comment by MickL** [comment]
BehaviorSubject would be lovely, too since we have an initial state on subscribe() without calling `Control.updateValueAndValidity()` manually.

**Comment by MickL** [comment]
Im not sure why my async validator is called 4 times on build. This would cause 4 server requests.

https://plnkr.co/edit/fI4LiLY4QIRRSm72zMZg?p=preview

I updated my plunker, just check the console. Is this another issue maybe?

**Comment by DzmitryShylovich** [comment]
I also noticed that. Maybe @kara can shed some light on ☝️

**Comment by MickL** [comment]
Did you find any solution yet? :)

**Comment by finalxcode** [comment]
+1

**Pull request closed without merging**
