### PR TITLE
docs: update 18.1.0 release date

### PR DESCRIPTION
**Pull request by AndrewKushnir**
Pushing the release by a week to have more time to test RC.

## PR Type
What kind of change does this PR introduce?

- [x] Documentation content changes

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
**Caretaker note**: marking as merge-ready - should be ok to merge once @thesmiler LGTMs the PR.

**Comment by thesmiler** [comment]
LGTM

**Review by thesmiler — COMMENTED** [review]
LGTM

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit a0fbd0e5e1f8691ec0d95c63f4d2f04c8f3b7b57.

The changes were merged into the following branches: main, 18.0.x

**Pull request closed without merging**
