### PR TITLE
docs: The `InputDecorator` (`@Input`) api description is incorrect #2…

### PR DESCRIPTION
**Pull request by Suresh918**
…8043

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

Issue Number: #28043

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandonroberts** [comment]
@petebacondarwin this doesn't seem to be rendering correctly for the Pipe decorator even after the change.

**Comment by petebacondarwin** [comment]
@brandonroberts - it turns out that these missing docs are because the `PipeDecorator` interface (along with a bunch of other `...Decorator` interfaces) are not publicly exported from the `@angular/core` package. This means that the doc-gen does not even "see" them, and so they are not included in the processing.

I have exported these in a commit added to this PR.

**Comment by brandonroberts** [comment]
Thanks @petebacondarwin. @Suresh918 will you rebase and squash the commits down to a single commit so the CLA bot is happy?

**Comment by brandonroberts** [comment]
@Suresh918 are you still interested in landing this change? If not, I can take it over as others are in need of the change.

**Comment by Suresh918** [comment]
Yes @brandonroberts. I squashed the code as you suggested earlier. Actually I was waiting for your review and approval. Do you want me to do anything else ? Unfortunately my branch was deleted in which i have made changes. If you want to me to do in new branch, I can do it. I think you can merge the code still.

**Comment by brandonroberts** [comment]
@Suresh918 your changes were incorporated into these PRs https://github.com/angular/angular/pull/28836 https://github.com/angular/angular/pull/28986

If you see something else, open a new PR.

**Pull request closed without merging**
