### PR TITLE
docs: Fix minor grammar mistake

### PR DESCRIPTION
**Pull request by eliasvagan**
Remove a misplaced apostrophe symbol from docs in `web-worker.md`

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM! Thank you!

**Comment by jessicajaniuk** [comment]
@eliasvagan Looks like you'll need to update your commit message and re-push. You can remove the `(docs-infra)` from the commit and have it just be `docs: Fix minor grammar mistake`.

**Comment by eliasvagan** [comment]
Thanks for the heads up, @jessicajaniuk. I've updated the title :)

**Comment by JeanMeche** [comment]
@eliasvagan It's the commit message itselft that needs to be amended.

**Comment by eliasvagan** [comment]
My bad, @JeanMeche. The PR description will become the commit message, yes? My understanding was that this could be left empty for docs-related changes.

**Comment by JeanMeche** [comment]
Currently your commit message is `Update web-worker.md: spelling`. It independent of the PR title.

**Comment by eliasvagan** [comment]
Should be resolved now

**Comment by jessicajaniuk** [comment]
Caretaker: This is docs only and low risk. It's safe to merge with the current reviewers.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit b9aa25ed2301f82964a619ac142038e0301ba6ff.

**Pull request closed without merging**
