### PR TITLE
docs(core): update <content> to <ng-content>

### PR DESCRIPTION
**Pull request by shuhei**

### CODE REVIEW

**Comment by zoechi** [comment]
There was also a recent issue (or PR) to change `ng-content` to `ngContent`.

**Comment by shuhei** [comment]
This one? https://github.com/angular/angular/issues/6199

I'm not sure if it's going to be renamed but the current doc is confusing.

**Comment by alexeagle** [comment]
I think it should be ngContent

**Comment by alexeagle** [comment]
merged as c25b9fc

**Pull request closed without merging**
