### PR TITLE
APF guide improvements 

### PR DESCRIPTION
**Pull request by alan-agius4**
**docs: update Definition of Terms in APF guide**
Several improvements to the Definition of Terms of terms section in the APF guide.

**docs: unlink `async` keyword in APF guide**
 Currently, `async` keywords in the APF guide incorrectly links to https://angular.io/api/common/AsyncPipe

**docs: update apf guide files layouts table**
With this change we improve the file layout structure table and align it with other similar tables example: https://angular.io/guide/file-structure

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

Nice tidy up. Thanks.

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by atscott** [comment]
This PR was merged into the repository by commit 523e8fd8a347fd5e56833f8bd27b3d7d57ca5d5b.

**Pull request closed without merging**
