### PR TITLE
docs: remove TypeScript to JavaScript guide & sample

### PR DESCRIPTION
**Pull request by wardbell**
Remove "TypeScript to JavaScript" guide & sample

Deletes the guide (ts-to-js.md) and its entry from navigation.json
Replaces reference to this guide that happened to be in a comment of `code.component.ts`
Remaining files belong to the sample.

Requested by @juleskremer

### CODE REVIEW

**Comment by chivne** [comment]
Can I?

**Review by juleskremer — APPROVED** [review]

**Review by Foxandxss — APPROVED** [review]

**Comment by denaje** [comment]
Took me a long time to track this down. Why was this page removed? Our company is going to start upgrading our app from AngularJS to Angular soon, and I bookmarked this page as the singularly most helpful page in all the docs. Without it, we won't know how to implement Angular concepts in JS, and a conversion to TS is not possible for us. Is there a replacement page that we can look at to guide us through the conversions?

**Comment by StephenFluin** [comment]
@denaje Happy to answer any more questions about this, or jump on a call to understand your needs better.

This page still exists here: https://v2.angular.io/docs/ts/latest/cookbook/ts-to-js.html if you need to reference it.

We removed this page because based on conversations with our community, trying to do high performing Angular apps in ES5 was more difficult than switching to TypeScript as part of using the CLI.

Angular only really asks you to write "TypeScript" for the decorators (@Component, @NgModule) for metadata, and for dependency injection. Your files will still be called .ts, but everything else you can written in ES2015 so you don't really need to learn anything new or change how you write code.

**Comment by denaje** [comment]
@StephenFluin thanks for the link and explanation! We tried (and failed) to migrate our app to Angular v2 via a complete frontend rewrite. We couldn't figure out how to do everything in JS, and I think at the time that the cookbook you linked to may have been incomplete. Our decision for upcoming try #2 is to use the upgrade module to do the upgrade piecemeal. Hopefully that combined with your link will allow us to succeed this time.

Our problem with renaming file extensions and selectively using TypeScript for decorations and DI is because our code is all actually written in CoffeeScript, not raw JS. It may be possible to get this to work. We would _love_ to switch to TS, but it doesn't seem feasible at the moment given we previously used CoffeeScript.

**Pull request merged**
