### PR TITLE
[2.x] fix(router): instantiate lazy loaded module only once

### LINKED ISSUE #12889: Dependency injection creates new instance each time if used in router submodule
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
My application is divided into modules. Router navigates between modules, each child modules has some providers and some components. I expect application to reuse services injected to components within one module. However, when I navigate, service constructor is called each time component is loaded.

RootModule:
```
		RouterModule.forRoot([
			{ path: '', component: EmptyComponent },
			{ path: 'module', loadChildren: () => SubModule },
		]) 
```
SubModule:
```
		RouterModule.forChild([
			{ path: 'test1', component: TestComponent1 },
			{ path: 'test2', component: TestComponent2 },
		])

...
	providers:
	[
		TestService
	],
```

Each time I navigate between /module/test1 and /module/test2 - TestService constructor is called

**Expected behavior**
If test1 and test2 are defined as routes in RootModule, only one instance of TestService is created. I expect SubModule to inject the same instance of TestService if I navigate between its components.

If I move TestService provider to RootModule - works as expected

**Minimal reproduction of the problem with instructions**
https://github.com/peku33/angular2-dependency-injection-failure

**What is the motivation / use case for changing the behavior?**
Most of components of one of modules uses a service that opens and maintains WebSocket connection. Each time a service is spawned, new connection is opened. I definitely want to reuse the component and keep single connection open than close and reopen it every time user navigates between pages.

**Please tell us about your environment:**
Everything is up to date, browser - Chrome

* **Angular version:** 2.0.X
Have 'latest' for almost everything in package.json
@angular/core@2.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
@mhevery
Re-opened https://github.com/angular/angular/pull/14178 against `2.4.x` branch

Closes #12889

### CODE REVIEW

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/pull/14178#issuecomment-276244782
> Also could you take a stab at the proper solution in 4.0?

I'm working on it, but I still don't have a clear picture how it works now vs how it suppose to work. Plus as far as I can tell it will require to change code generation and I'm not very familiar with it.

**Comment by mhevery** [comment]
@DzmitryShylovich let me know how I can help. Send question to misko at google dot com or we can set up a VC.

**Comment by DzmitryShylovich** [comment]
@mhevery 
> let me know how I can help. Send question to misko at google dot com or we can set up a VC.

sure, will do.
@tbosch is working on a new view engine so I think it's blocked until the view engine will be completed.

**Comment by bevrard** [comment]
Any idea when this one will be integrated?  we really need it.
Thanks

**Comment by mhevery** [comment]
Very sorry, but it is not look like we are going to get to this in 4.0.0.

We understand this is a priority for many of you. Can yo create a work around by crating a factory for your injectable which makes sure to always return only one instance per application?

**Comment by ciesielskico** [comment]
How does one do that?

**Comment by mhevery** [comment]
A possible work around
```
class Cache {
  createIfnotExists(key, fn) { ... }
}

@NgModule({
  providers: [
    Cache
  ]
})
class MyApp {}

class SomeService

@NgModule({
  providers: [
    { provide: SomeService, 
      toFactory: (cache, aDep, bDep) => 
          cache.createIfnotExists(SomeService, () => new SomeService(aDep, bDep)), 
      deps: [Cache, A, B, ...]}
  ]
})
class LazyLoadedModule {}



```

**Comment by karptonite** [comment]
@mhevery As I understand it, this isn't just about injectables being created twice, it is about ngrx effects being loaded multiple times, as described here: https://github.com/angular/angular/issues/12869
I'm not sure how a factory could solve this problem.

**Comment by mhevery** [comment]
> @kryptonite @mhevery As I understand it, this isn't just about injectables being created twice, it is about ngrx effects being loaded multiple times, as described here: #12869
> I'm not sure how a factory could solve this problem.

Can you give me an example? My understanding is that effects hang from instantiation. If instantiation is not duplicated, then side effects will not be duplicated either.

**Comment by DzmitryShylovich** [comment]
@mhevery why don't you want to merge this into 2.x branch as a temporary workaround until the proper fix will be implemented?

**Comment by karptonite** [comment]
@mhevery I'm not sure what sort of an example you are looking for. You can see here how ngrx/effects works: https://github.com/ngrx/effects/blob/master/docs/intro.md with the effects imported in the imports section of the module with `effectsModule.run( EffectsClass)`. Here is an issue that claims to replicate the problem: https://github.com/ngrx/effects/issues/81.

This is a significant problem for us, but I had proceeded under the assumption that this would be fixed by the time we were going to deploy our new app. 

What is wrong with this pull request for the 2.x branch? Does it break other things? It seems to pass the tests.

**Comment by mhevery** [comment]
My concern is that:
1. it is a bit of a hack, as it creates slightly wrong semantics
2. it will be broken again in 4.x

So we think we should just fix the underlying cause.

**Comment by DzmitryShylovich** [comment]
> It seems to pass the tests.

😄 it doesn't mean it won't break something else

**Comment by karptonite** [comment]
The fact that the bug exists in 4.0 is a poor argument for not fixing it in 2.x. This seems to be a significant bug, not a feature request--one could argue that the proper course of action would be to fix it in 2.x, and delay 4.0 until it is fixed there as well. 

As for it being a hack, don't they say, "First make it work, then make it fast, then make it right"? One step at a time.

**Comment by karptonite** [comment]
@mhevery I reread that, and it sounded harsher and more entitled than I'd intended--sorry about that! But I stand by the argument that, if this pull request fixes the issue and doesn't break anything, it should be pulled. And if 4.0 is changing enough that this code doesn't make sense there, that is all the more reason to pull the hack in 2.x, and fix it properly in 4.x.

**Comment by alvipeo** [comment]
this bug actually hits my app too. And it just makes my http request twice instead of just one. So I'm hitting the server twice every time!

**Comment by thaoula** [comment]
@mhevery To be quite frank and with utmost respect, the reason to not merge this fix is now sounding more like a religious decision than a technical one.

If as a consumer of the Angular library, I cannot tell the difference from the hack and the proper fix, you should be pragmatic and merge the fix. I am not looking at the source code to say omg how ugly is that. You should also delay 4 to fix this issue.

If you don't want to merge this fix, then essentially you guys should update the documentation and  state that Lazy Loaded modules are broken and cannot be used as people starting new projects will encounter this issue also. 

@DzmitryShylovich suggested in another post we should try and move to known modules rather than lazy loaded modules and this will fix the issue. 

- Are you guys not using Lazy Loaded modules at Google, is that why this issue is not high priority?
- You are using lazy loaded modules but implemented some work around. If so, what is it?

Would removing the private injector paradigm for lazy loaded modules (make them work the same as known modules) eliminate the need for fixing this issue?

On paper the idea of sandboxed injectors for lazy loaded modules sound like a good feature. However, in the real world, i still don't fully understand the usefulness of the injector strategy for lazy loaded modules. 

In all projects i have worked on, where working in a co-located team or distributed team. The same team build all of the modules used in the App, we never load random modules from anywhere. Simple exceptions can be used to detect naming collisions. 

The silence (up until recently), the lack of formal escalation procedures, lack of guidance and waiting more than 3 months a fix for such a massive issue is scary. 

Honestly @mhevery we desperately need a fix for this today.

**Comment by bevrard** [comment]
@mhevery All our production builds are waiting for this fix.  To provide the best Angular experience to our clients, we've put in place AOT, Lazy loading and Tree-Shaking.
We definitely don't understand why this bug is not considered as major.

As you said that it will be fix in version 4.x (mid-April?), the lazy loading is down for 5 months...  Can we deduce that Lazy loading is not the way to go?

**Comment by mhevery** [comment]
I hear that this is a priority for you. We have other things which need to
make it before we work on this. It is not an easy fix.

**Comment by DzmitryShylovich** [comment]
@mhevery so should I close this one so people won't have wrong expectations that it will be fixed in 2.x?

**Comment by Spawnrad** [comment]
Can you please merge this one?

**Comment by santialbo** [comment]
Is there a way we could reference this branch somehow on our package.json file? In the old days we could just pin a package to use any github repo's commit.

**Comment by karolmie1** [comment]
@santiablo - you are free to fork angular, merge this branch to master and use it in your package.json, referencing your repository url. You still can use selected commit in package.json if thats what you want to do - it still works.

**Comment by vicb** [comment]
I'm starting to work on a fix for this issue.

**Comment by kel-sakal-biyik** [comment]
Hey everyone,

Until it gets fixed, in our team we tried this workaround and it worked for us. I know it is really sloppy but does the trick.

https://gist.github.com/kel-sakal-biyik/32540198fd0363ea6422992e84c700dc

**Comment by mbellezi** [comment]
Closed? Was this solved?

**Comment by DzmitryShylovich** [comment]
@mbellezi it won't be fixed in 2.x
the fix for 4.x is here https://github.com/angular/angular/pull/15044

**Comment by royling** [comment]
Any plan to fix this in 2.x later? If not, then lazy loading module is a feature since `v4.x` only...

**Comment by vicb** [comment]
Probably not but depends on needs.
If you are interested, please create an issue explaining why you can not upgrade to 4 and if it got enough stars/+1 we might consider.

**Comment by royling** [comment]
Because my project depends on [clarity-angular](https://github.com/vmware/clarity) which is now on v2.x, and also lazy loading modules is a very important feature for us, I cannot control if the dep will upgrade to v4. How can I work around this issue then?

**Comment by Spawnrad** [comment]
Have upgrade to angular4 rc.4 and now rc.6 and its working very well .

Thanks a lot!

**Comment by vicb** [comment]
@royling do you know if clarity has any plan to upgrade to 4.x ? As said please create an issue so that we can collect what is blocking migration to v4. Thanks !

**Comment by DzmitryShylovich** [comment]
there's already an issue https://github.com/angular/angular/issues/15394

**Comment by vicb** [comment]
@DzmitryShylovich Thanks !

**Comment by royling** [comment]
@vicb I opened an issue on clarity to ask their plan, waiting for the response.

**Pull request closed without merging**
