### PR TITLE
fix(http): remove dots from jsonp callback name

### LINKED ISSUE #13175: Jsonp callbackName can be modified wanted
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The jsonp callbackName is set as `__ng_jsonp__.__req0.finished`

**Expected behavior**

It will be nice if I can modify the jsonp callbackName

**Reason**
Some servers don't response right data if jsonp callbackName with `.`, And most of servers which need a jsonp method to get cannot easy to modify.
Please

* **Angular version:** <= 2.2.4

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =  all

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Fixes https://github.com/angular/angular/issues/13175

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by doxiaodong** [comment]
@DzmitryShylovich , hello, after upgrade to 2.4.6, I get `Uncaught ReferenceError: __ng_jsonp____req0_finished is not defined` as https://github.com/angular/angular/pull/13219#discussion_r90797936

**Comment by doxiaodong** [comment]
the code is as follow
```
search(key: string) {
    const params = new URLSearchParams()
    params.set('jsonpCallback', 'JSONP_CALLBACK')
    return this.jsonp.get('https://c.y.qq.com/splcloud/fcgi-bin/smartbox_new.fcg?' + params)
    .toPromise()
    .then(res => {
      console.log(res)
      return []
    })
  }
```

**Comment by ipeshev** [comment]
Тhe feature request and the issue are intertwined in very interesting way. The consequences are that in angular version 2.4.6 JSONP with usual setup is not working. Do we have the feature though @DzmitryShylovich  ?

**Comment by DzmitryShylovich** [comment]
@ipeshev use http  2.4.5 until it will be fixed
there's nothing new in 2.4.6 except jsonp bug :)

**Pull request closed without merging**
