### PR TITLE
fix(service-worker): add badge to NOTIFICATION_OPTION_NAMES (#23196)

### PR DESCRIPTION
**Pull request by HiveSolution**
packages/service-worker/worker/src/driver.ts
- add badge to NOTIFICATION_OPTION_NAMES to support custom notification badge/icon.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Notifications wouldn't display custom notification badge due to missing badge prop in options

Issue Number: #23196 

## What is the new behavior?
Badge has been added and will now be displayed if set by caller.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by gkalpak** [comment]
Thx, @HiveSolution! This looks good 👍
Except...our formatter is peaky :grin: Can you please format the array as shown in the [lint output][1].
(The Travis failure looks like a flake, so ignore that for now.)

<sub>(While you are at it, feel free to add the `image` property (or make a new PR for that).)</sub>

[1]: https://circleci.com/gh/angular/angular/38542

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Oh, and you also need to format the commit message as described in our [commit message guidelines][1], e.g.:

> fix(service-worker): add badge to NOTIFICATION_OPTION_NAMES
> 
> Add badge to `NOTIFICATION_OPTION_NAMES` to support custom notification badge/icon.
> Fixes #23196

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by HiveSolution** [comment]
Thanks for the feedback @gkalpak should i push a new commit to this branch that fixes the linting and commit message issues or create a new one just to keep things clean?

**Comment by gkalpak** [comment]
Updating this one is preferrable. The only way to update the commit message is to amend the last commit, so you can make the changes to fix linting and the `git commit -a --amend` and fix the commit message (then force-push to your branch).

**Comment by HiveSolution** [comment]
Thanks for the help with everything @gkalpak 

Reason for the linting error was totally on me for not checking that TSLint was running. It somehow stopped working on my vsCode. But after updating it started working again. So sorry for that.

Issue format should also be guideline conform. Thanks for pointing that out. I've read the guidelines but somehow missed that point. Probably should not be doing stuff like this so late 😆

**Pull request closed without merging**
