### PR TITLE
docs: add Mosaic library to resources

### PR DESCRIPTION
**Pull request by pimenovoleg**
Added the Mosaic library to the list of resources.
Mosaic build on Angular and inspired by NgMaterial.

In the next release, we will fully switch to angular/cdk, remaining only necessary in our own CDK.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Fost** [comment]
I signed it!

**Review by kapunahelewong — APPROVED** [review]
Thank you, @Fost! LGTM.

**Comment by brandonroberts** [comment]
@Fost you need to remove the scope `(aio)` from the commit message

**Review by StephenFluin — APPROVED** [review]

**Comment by Fost** [comment]
* synchronized with the master
* CI was successful

**Pull request closed without merging**
