### PR TITLE
docs: add change detection docs to angular.io

### LINKED ISSUE #33731: Missing official change detection documentation
# 📚 Docs or angular.io bug report

### Description

An official change detection documentation is missing

There exist a lot of unofficial blog posts but it would be nice to have an official guide on angular.io.

Are there any special reasons why there is no offical documentation available?

I am currently working on a change detection blog post so I could create a first draft.

### PR DESCRIPTION
**Pull request by ajitsinghkaler**
Added change detection guide to the angular.io website and also added a new tab to the navigation menu

#Fixes #33731

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Added new change detection documentation

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #33731 

## What is the new behavior?
Added new change detection documentation

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ajitsinghkaler** [comment]
I've added an initial draft please feel free to comment and review.

**Comment by ajitsinghkaler** [comment]
@kapunahelewong can you please have a review of my first draft

**Comment by kapunahelewong** [comment]
Thank you so much for this, @ajitsinghkaler. @jbogarthyde and I are already working on this particular doc, and because it requires a working example, e2e tests, meeting certain content criteria, etc., the scope and time commitment for you would continue to increase substantially beyond what's here thus far. As an alternative, would you be all right with @jbogarthyde and I using your work here as a resource for what we already have underway? You've shared a lot of knowledge that we'd still love to incorporate into the docs, but we may have to do it by using your expertise as part of informing the doc draft, rather than as the doc itself. What are you thoughts? Again, thank you very much for putting so much thought into this!

**Comment by ajitsinghkaler** [comment]
Yeah please use it as the base of the documentation

**Comment by kapunahelewong** [comment]
Thank you, @ajitsinghkaler! Yes, you can close this PR. We will still be able to reference it. 

There are so many ways to get involved. One way that's very helpful for the docs team is when community members comment on [Docs Issues](https://github.com/angular/angular/labels/comp%3A%20docs) or [PRs](https://github.com/angular/angular/pulls?q=is%3Apr+is%3Aopen+label%3A%22comp%3A+docs%22)  because those comments help us understand what's important to developers. This doesn't require PRs and is still extraordinarily helpful.

Another very specific way to contribute would be to create a StackBlitz example for Change Detection to demonstrate the concepts because I am still learning. You wouldn't have to add CSS or anything like that because we already use a base set. Then I could build on it, write the e2e tests and help @jbogarthyde incorporate it into her doc. If you wanted to do this, we could create an issue and track our work in there. 

Do either of these interest you?

**Comment by ajitsinghkaler** [comment]
@kapunahelewong yeah, I would really like to create stackblitz examples you just guide me towards an example of how you create them in this repo are there any rules regarding stackblitz examples that we put in here.

#34295 it's also related to zone.js and change detection you could incorporate both of these and I think we could really have a good base for change detection documentation.

**Comment by kapunahelewong** [comment]
Thank you, @ajitsinghkaler. Yes, @jbogarthyde and I are definitely learning from @JiaLiPassion. He's a great source of knowledge. 

For a StackBlitz example, you could just create a minimal app and share the link with me here or in a new issue. You don't have to do anything for angular.io at this stage. Since we're still coordinating everything, we're not at the point of creating a PR yet. Once we do a PR, that's when we'll have the example and the written doc together so that the written doc can use the code snippets form the example. So for now, we can just create the example in stackblitz and iterate on it. Sometimes when creating example apps, I make 40-80 versions before creating the PR because iterating is easier that way.

Getting all the pieces of a new doc working just right can take months, so often we work first in other things like StackBlitz or locally and then move into a PR when we're closer. Does that help?

**Comment by ajitsinghkaler** [comment]
yeah, I'll keep posting the links here.

Today I'll post what all examples I'll be working on. You can tell me if something needs to be added or removed.

**Pull request closed without merging**
