### PR TITLE
refactor(common): remove deprecated ReplacePipe

### PR DESCRIPTION
**Pull request by IgorMinar**

### CODE REVIEW

**Comment by RobiFerentz** [comment]
My only contribution to ng2 was removed? Bummer.

**Comment by choeller** [comment]
Is there any background on why `ReplacePipe` was removed? It was quite useful and now people will start to implement their own...

**Comment by RobiFerentz** [comment]
I implemented it several times in angular 1 projects, that's why I thought I'd add it to ng2, but if the core team decided it needed deprecating, then they must have a good reason.

**Comment by vicb** [comment]
I guess because you can use `.replace()` ?

**Comment by RobiFerentz** [comment]
You can also use '.slice()' yet that pipe exists.
You can also write a single page app without a framework at all, so why create one at all?
So I hope the reasoning behind removing it was more than just 'because you can use something else' .

**Comment by kodeine** [comment]
@RobiFerentz @vicb @choeller 
why this was removed :/ can anyone share the code if they created one?

**Pull request merged**
