### PR TITLE
fix(upgrade): fix memory leaks when the component is destroyed

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Issue Number: #39911

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gkalpak** [comment]
@arturovt, is this PR ready for review (I've noticed you have been pushing new commits recently)?

**Comment by arturovt** [comment]
> @arturovt, is this PR ready for review (I've noticed you have been pushing new commits recently)?

Yep, you can start reviewing.

**Review by petebacondarwin — APPROVED** [review]
LGTM but it has been a while since I look at ngUpgrade code.
@gkalpak will probably have more to say :-)

**Comment by arturovt** [comment]
@petebacondarwin @gkalpak gentlemen just for your information:
**this is BEFORE applying these changed**

before

---
---
---

**this is AFTER**

after

Basically, the `DowngradeComponentAdapter` (and all its resources) are released.

**Comment by gkalpak** [comment]
Thx for working on this, @arturovt :+1:

While reviewing your PR, it thought it was "suspicious" that we had to clean up stuff that would normally be cleaned up automatically. So I dug deeper to understand why it wasn't being clean up.

In a nutshell, it happens because (under some circumstances) Angular will remove the component host element from the DOM before AngularJS has a chance to clean it up. See [here][1] for more details.

##
Based on the above, I have created #39965 with an alternative fix, which I think is simpler and more consistent with how things would work in a pure AngularJS app. I would appreciate it if you could take a look and let me know what you think?

BTW, you can also grab the build artifacts [from my PR][2] (see [here][3] for more info) and use them in a sample app in order to verify the fix.

[1]: https://github.com/angular/angular/blob/61baba2b0a5e228fe1a9b5fe33fc3aa47c5b3799/packages/upgrade/src/common/src/downgrade_component_adapter.ts#L230-L247
[2]: https://app.circleci.com/pipelines/github/angular/angular/25557/workflows/070d4a68-6c1a-405c-8708-d36d4e4dc3d0/jobs/872823/artifacts
[3]: https://github.com/angular/angular/blob/65651b094d3259960542374e9ddc170289491110/docs/DEVELOPER.md#getting-packages-from-build-artifacts

**Comment by arturovt** [comment]
@gkalpak 

I've played with your changes and it seems to work (the adapter is released successfully). Nice job!

**Comment by gkalpak** [comment]
Awesome! Thx for checking, @arturovt ❤️

**Pull request closed without merging**
