### PR TITLE
refactor(platform-server): avoid using `platformDynamicServer` when `ngJitMode` is disabled

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit refactors the logic of the `platform-server` to avoid using `platformDynamicServer` when `ngJitMode` is disabled. This is needed to avoid including JIT compiler into the source code of the server bundle, when this compiler is not needed.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
[Presubmit](https://test.corp.google.com/OCL:527146162:BASE:527121265:1682481460228:7c159b85).

**Review by alan-agius4 — APPROVED** [review]
LGTM, thanks

**Comment by alan-agius4** [comment]
[Presubmit](http://fusion2/presubmit/527146162/OCL:527146162:BASE:527265106:1682520785109:19a5427a/targets).

**Comment by AndrewKushnir** [comment]
**Caretaker note**: presubmit is "green" (only unrelated failures).

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 744f7ffb618a993a7217e510c221f493f2ad9f9a.

**Pull request closed without merging**
