### PR TITLE
docs(): update directives.ts to correct semantic for host keys description

### PR DESCRIPTION
**Pull request by Teebo**
correct semantic for host keys description

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]

**Comment by Teebo** [comment]
Hi, CLA signed

**Comment by JeanMeche** [comment]
Can you reword your commit message to follow [our guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit) ? thx

**Comment by Teebo** [comment]
Commit message updated

**Comment by atscott** [comment]
This PR was merged into the repository by commit add0bd364cbe9b31641de83e9db680cbbf22892f.

**Pull request closed without merging**
