### PR TITLE
refactor(di/tests): removes unecessary for-loop

### PR DESCRIPTION
**Pull request by 0x-r4bbit**

### CODE REVIEW

**Comment by tbosch** [comment]
Travis failed because of clang-format. Could you reformat and update the PR?

**Comment by PascalPrecht** [comment]
Yupp, on it.

**Comment by PascalPrecht** [comment]
@tbosch I ran `gulp check-format` it didn't complain. Also, the output at travis doesn't really look like there's a problem with formatting. In addition, I just removed code. Not sure how to format that part differently (since I just removed stuff).

**Comment by tbosch** [comment]
The error is weird: `Invalid link (does not match any doc)`, but you are not changing docs...

Could you try to rebase and try again?

**Comment by PascalPrecht** [comment]
@tbosch rebased :)

**Pull request closed without merging**
