### PR TITLE
fix(router): support null response in UrlMatcher

### PR DESCRIPTION
**Pull request by trshafer**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features) (updated router golden)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
This allows UrlMatcher responses to be null.

## What is the new behavior?
The example (in the documentation) UrlMatcher supports returning null.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by bitjson** [comment]
I think this PR solves #21624 – is this waiting on any further development work? @jasonaden have you had a chance to take a look? (Are you the right reviewer?)

**Review by mattleff — APPROVED** [review]
We need this

**Review by sod — APPROVED** [review]

**Comment by waterplea** [comment]
This is an important fix to matcher functionality, and it sits here for almost a year :(

**Comment by sod** [comment]
This is stil super annoying. And before the stale-bot closes this, I add a comment.

**Comment by odiak** [comment]
I want this PR to be merged.
@trshafer Please fix conflicts.

**Comment by sod** [comment]
fixed by https://github.com/angular/angular/pull/36402 via angular > 9.1.0

**Comment by JoostK** [comment]
Thanks @sod, this has indeed landed per #36402 for Angular v10. Sorry that this PR never made it in! 😞

**Pull request closed without merging**
