### PR TITLE
add Keilla Fernandes to GDE resources

### PR DESCRIPTION
**Pull request by keilla**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
This adds Keilla Menezes Fernandes to the list of Angular GDEs on the Angular Docs page -> cc @StephenFluin

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by keilla** [comment]
I signed it!

**Comment by keilla** [comment]
I signed it!

**Review by StephenFluin — CHANGES_REQUESTED** [review]
It looks like there's a merge commit that shouldn't be there.  Can you squash them to get rid of it?

https://twitter.com/stephenfluin/status/1009904095073718275

**Comment by StephenFluin** [comment]
@IgorMinar I just noticed that the profile image is 1.5mb, should we have guidelines for image sizes? I don't think we are doing any size optimizations, right?

**Comment by gkalpak** [comment]
We are using this innovative, OIAW (Once In A While) optimization technique, known as @jelbourn: #28479 😛

**Comment by StephenFluin** [comment]
Yes but PRs like that don't stop us from making angular/angular bigger. 😀

**Comment by gkalpak** [comment]
We can add guidelines and CI checks for size then :wink:

**Comment by keilla** [comment]
@StephenFluin Do I have to made some action in this PR yet?

**Comment by StephenFluin** [comment]
Sorry, I was trying to figure out if we had a standard about getting the filesize down before we merge it. Can you get it to  under 20kb to match most of the other images in the bios folder?

Thanks!

**Comment by keilla** [comment]
@StephenFluin I replaced the image and squash the commits :)

**Review by StephenFluin — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Caretaker: I added a global approval

**Review by IgorMinar — APPROVED** [review]

**Pull request closed without merging**
