### PR TITLE
refactor(router): fix several typos in router spec

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Found several typos when I do some research on router related tests.

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@JiaLiPassion why `minor`?

**Comment by JiaLiPassion** [comment]
@petebacondarwin , I am not sure which target is the correct one, should I use `major` or `patch`?

**Comment by petebacondarwin** [comment]
@jelbourn is working on docs to clarify this (https://github.com/angular/angular/pull/39924), but the basic idea is that if these changes are non-breaking bug-fixes you should go with `target: patch`, in which case the PR will be merged into `master` and also the patch branch (plus any RC branch if available). I think that would be the case here, unless these changes do not merge into the patch branch because the original tests do not appear there.

**Comment by JiaLiPassion** [comment]
@petebacondarwin , got it, thanks.

**Review by atscott — APPROVED** [review]
Note: Updated the commit message header to read "refactor(router)" rather than "fix(router)" so this doesn't appear in the changelog as a fix.

**Pull request closed without merging**
