### PR TITLE
fix(DirectiveResolver): throw error on invalid query selector

### PR DESCRIPTION
**Pull request by mgechev**

### CODE REVIEW

**Comment by IgorMinar** [comment]
sorry about the delay. is this still an issue? if so, can you please rebase the PR?

**Comment by ericmartinezr** [comment]
@IgorMinar @mgechev since I opened the issue time ago, I updated the repro to a47 (still reproducible) in case is needed

http://plnkr.co/edit/kDlz0z?p=preview

**Comment by IgorMinar** [comment]
can you rebase please?

**Comment by mgechev** [comment]
@IgorMinar sure, during the weekend I'll take care of this.

**Comment by mgechev** [comment]
@IgorMinar done.

**Comment by pkozlowski-opensource** [comment]
@mgechev there are a couple of formatting errors to be resolved, see: https://travis-ci.org/angular/angular/jobs/95176808

Run `gulp check-format` locally to see what needs automatic re-formatting.

**Comment by mgechev** [comment]
@pkozlowski-opensource sorry for that..Fixed.

**Comment by mgechev** [comment]
@IgorMinar does it look fine now?

**Comment by mgechev** [comment]
There are too many merge conflicts. I will close this PR.

**Pull request closed without merging**
