### PR TITLE
fix(TemplateParser): match element and attributes regardless the name…

### PR DESCRIPTION
**Pull request by vicb**
…space

relates to #5547

### CODE REVIEW

**Comment by alexeagle** [comment]
Any concern about how this will merge into g3? Does it affect downstream Dart users?

**Comment by vicb** [comment]
There should be no pb

**Comment by vsavkin** [comment]
Can you rebase it on top of master?

**Comment by vicb** [comment]
@vsavkin rebased & merge #5751 into here

**Pull request closed without merging**
