### PR TITLE
docs: update link to static queries in changelog

### PR DESCRIPTION
**Pull request by alan-agius4**
At the moment this link is broken.

### CODE REVIEW

**Comment by alan-agius4** [comment]
Caretaker: CI failure is unrelated.

**Review by devversion — APPROVED** [review]
Can you also update the link in the `static-query` migration? We've added it there as well (see [here](https://github.com/angular/angular/commit/8479cb4233ba00cc6a7156467b46f51ed9a753f7))

**Review by petebacondarwin — APPROVED** [review]
I think it is good practice to always use these kind of version specific links in the change log; especially when we are talking about migrating from one version to another.

**Comment by devversion** [comment]
Updated the links in the migration schematic as @alan-agius4 is not available right now and asked me to push the update to that branch.

**Review by IgorMinar — APPROVED** [review]

**Pull request closed without merging**
