### PR TITLE
build: refactor ambient node & jasmine types so they are only included where needed (6.1.x branch)

### PR DESCRIPTION
**Pull request by gregmagolan**
6.1.x version of https://github.com/angular/angular/pull/25491

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]

**Review by alexeagle — APPROVED** [review]

**Comment by IgorMinar** [comment]
@gregmagolan CI seems to be quite unhappy about this change :-|

**Comment by gregmagolan** [comment]
@IgorMinar All good. Just the merge conflict ended up with an extra file that shouldn't have been there.

**Comment by gregmagolan** [comment]
@IgorMinar @alexeagle Well... the aio on travis is not flaky after all here but the error is very criptic:

```
$ scripts/deploy-preview.sh --skip-build
HTTP/1.1 413 Request Entity Too Large
Server: nginx/1.10.3
Date: Fri, 17 Aug 2018 07:29:20 GMT
Content-Type: text/html
Content-Length: 199
Connection: close
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
HTTP_CODE: 413
error Command failed with exit code 1.
```

Any idea as to why this is happening on 6.1.x and not on master?

**Comment by gregmagolan** [comment]
The travis aio failure here is from a change on master that didn't get merged onto patch which changes the preview server

From @petebacondarwin: "No that error is because we changed the preview server. I forgot to merge the change to the patch branch."

**Pull request closed without merging**
