### PR TITLE
build(docs-infra): upgrade RxJS to 6.5.1

### PR DESCRIPTION
**Pull request by gkalpak**
☝️
Upgrade RxJS to 6.5.1 on angular.io and docs examples.
Related to #30043.

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Uh oh! Something is wrong with the updates on StackBlitz examples.
For a reproduction, go to https://pr30048-897006b.ngbuilds.io/getting-started#click-here-to-create-a-new-project-in-stackblitz
And then click on the `Click here to create a new project in StackBlitz.` link.
Results in an error of `{"error":"UNSATISFIED_RANGE","data":{"name":"rxjs","range":"^6.5.1"}}` at https://run.stackblitz.com/api/angular/v1

**Comment by gkalpak** [comment]
It seems that the registry used by StackBlitz is not updated with RxJS@6.5.1 yet. Maybe wait a few hours?
(cc @EricSimons)

**Comment by gkalpak** [comment]
StackBlitz seems to have updated. 6.5.1 is now available (and the example seems to work fine).
@petebacondarwin, ptal.

**Review by petebacondarwin — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@gkalpak, there are some conflicts while trying to merge this PR to patch branch. I've merged this PR to master only, could you plz create a new PR to target patch branch? Thank you.

**Pull request closed without merging**
