### PR TITLE
Added find to QueryList api.

### PR DESCRIPTION
**Pull request by trshafer**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

There is no ability to find a specific QueryList item.

**What is the new behavior?**

Developers can now find a specific QueryList item.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

**Other information**:

Here is a gift of a baby Koala in hopes you'll accept this change:
baby koala

### CODE REVIEW

**Comment by trshafer** [comment]
Sooo Array#find is [unsupported in Internet Explorer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility). :(. All the tests pass, but I'm not sure what Angular's browser compatibility requirement is.

**Comment by vicb** [comment]
Please
- squash your commits,
- the comment should be `feat(core): add the find method to QueryList`,
- remove the extraneous interface from the tets.

Thanks

**Comment by trshafer** [comment]
Thanks for the review @vicb. I have squashed my commits and modified the commit message.

Would you like me to remove the whole _JsQueryList object from the tests? I'd be touching more code than my specific feature addition. That seems out of scope for this PR. I'd be happy to submit a new PR that removes the _JsQueryList from the tests. Let me know how to proceed. Thanks.

**Comment by vicb** [comment]
You can add a second `refactor(core): ...` commit to this PR.

Thanks !

_I have reviewed the PR only to get the gift_

**Comment by trshafer** [comment]
@vicb, I'm happy to hear the gift was to your liking. I have added a commit, which precedes the feature change commit, to remove the extraneous interface from the tests.

**Comment by vicb** [comment]
> which precedes the feature change commit

Perfect, forgot to mention that in my previous comment but it will help us merging only the first commit in the patch release and both in the minor release.

:+1:

**Comment by vsavkin** [comment]
Merged https://github.com/angular/angular/commit/7c16ef942e135ea64a69ce8025c75c140c113d83

**Pull request closed without merging**
