### PR TITLE
fix(animations): avoid infinite loop in `containsElement`

### LINKED ISSUE #57243: Infinite loop in shared.ts
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

~No~
Yes

### Description

Due to an extremely unlikely  (but not too unlikely!) coincidence, the Angular animation module stucked in an infinite loop.

This occured inside `containsElement(elm1, elm2)`: https://github.com/angular/angular/blob/18.1.3/packages/animations/browser/src/render/shared.ts#L204
because of how `getParentElement(element)` is implemented: https://github.com/angular/angular/blob/18.1.3/packages/animations/browser/src/render/shared.ts#L159.

There are just [3 relevant files](https://github.com/perceptron8/quirk/tree/master/src/app) in the linked repository. The rest was generated with `ng new` using default settings (with the exception of routing, which I disabled). The most important part seems to be `AppComponent`'s template:

```html
@if (true) {
	<form>
		<input id="host" />
		<p-overlay></p-overlay>
	</form>
}
```

1. `p-overlay` is some meaningless component using `animations: []` (see [overlay.ts](https://github.com/perceptron8/quirk/blob/master/src/app/overlay.ts)),
2. It's sibling, `input` identified as `"host"`, is enclosed inside a `form`,
3. Initially `form` seems to have no `parentElement` because of `@if` (same would be true if `*ngIf` was used).

All of the above had to appear for this bug to occur: element using animations, `input` with id (or name) equal to 'host' and a `form` inside control flow block. Then, `getParentElement` gets no `element.parentNode` because of (3.) and falls back to `element.host`. Next, because of (2.), `element.host` refers to `input` instead of nothing (as form is not so much of a custom element). Finally, there is (1.), which makes `containsElement` being called in the first place.

---

It seems to me, that it may be sufficient to change `getParentElement` so it uses `.host` access more carefully (i.e. conditionally).

---

Please note, that the current implementation will also fail for `<a href='...'>` inside a control block as `a` also has `host` property (see https://developer.mozilla.org/en-US/docs/Web/API/Location/host).

```html
@if (true) {
	<a href="https://angular.dev/">
		<p-overlay></p-overlay>
	</a>
}
```

In this case however, there will be no infinite loop, as `a`'s `host`, being a `String` equal to`"angular.dev"`, has neither `parentNode` nor `host`. Still, parent element doesn't really seem to be determined correctly.

---

Some hopefully useful spec links:
- https://dom.spec.whatwg.org/#dom-shadowroot-host
- https://html.spec.whatwg.org/multipage/forms.html#dom-form-nameditem

### Please provide a link to a minimal reproduction of the bug

https://github.com/perceptron8/quirk

### Please provide the exception or error you saw

```true
Browser's tab freezes with 100% CPU usage.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.3
Node: 22.3.0
Package Manager: npm 10.8.1
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1801.3 (cli-only)
@angular-devkit/core         18.1.3 (cli-only)
@angular-devkit/schematics   18.1.3 (cli-only)
@schematics/angular          18.1.3 (cli-only)
```

### Anything else?

If you disable animations (globally in `ApplicationConfig` or locally in `Overlay`) _or_ change `input`'s id to something else than `"host"` _or_ remove `@if` wrapper, this crazy bug dissapears.

### PR DESCRIPTION
**Pull request by perceptron8**
`getParentElement`, which was previously used within `containsElement`, can behave incorrectly when used with `HTMLFormElement`s as explained below.

> `form[name]` returns the form control (or, if there are several, a RadioNodeList of the form controls) in the form with the given ID or name (excluding image buttons for historical reasons); or, if there are none, returns the img element with the given ID.

(source: https://html.spec.whatwg.org/multipage/forms.html#dom-form-nameditem)

If `<form>` contains `<input name="parentNode">` (or `<input name="host">`), then `form.parentNode` (or `form.host`) refers to that `input` instead of actual parent (or host) of `form`.

BREAKING CHANGE: None

Fixes #57243

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

I believe that there's no need to update the docs.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #57243

## What is the new behavior?

Infinite loop in `containsElement()` is avoided by not using flawed `getParentElement()`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
To satisfy the linting rules, could you make this a `fix(animations): ...` commit and drop the `DEPRECATE` mention as there is none. Thank you.

**Comment by perceptron8** [comment]
> To satisfy the linting rules, could you make this a `fix(animations): ...` commit

Sure, done.

> and drop the `DEPRECATE` mention as there is none. Thank you.

If you meant removing `BREAKING CHANGE: None`, then I did it too.

**Comment by thePunderWoman** [comment]
@perceptron8 Looks like you have some legitimate failing tests. Once this is fully green, I'll take a look.

**Comment by perceptron8** [comment]
Looks like arguments passed to `MockAnimationDriver.containsElement` can be `TNode`s instead of `DOM Node`s, which means they do not provide `getRootNode()` method. I've spent about 5 hours trying to find some workaround, but found none. I suspect that `AnimationDriver` is meant to be used with those nodes - and such calls happen all the time - in which case this PR is simply a misfire. I'll try to find another way to "escape" named form items, but it looks less and less promising. Please let me know if something comes to your mind.

**Pull request closed without merging**
