### PR TITLE
refactor(compiler-cli): move downlevel decorators transform into ngtsc

### PR DESCRIPTION
**Pull request by JoostK**
This commit moves the `downlevel_decorators_transform` into a dedicated
compilation unit within `ngtsc`.

The tests were refactored to move to ngtsc's testing abstractions, allowing
VE's `MockAotContext` and `MockCompilerHost` to be removed.

### CODE REVIEW

**Comment by JoostK** [comment]
Note to reviewer: unfortunately the whitespace changes are causing too much differences for the spec file rename to be considered as rename; use

```sh
git diff -M30% -w 6237234b9cf02558b12e5521633e18b62daf433c~ 6237234b9cf02558b12e5521633e18b62daf433c
```

to see a readable diff.

**Review by alan-agius4 — APPROVED** [review]

**Review by dgp1130 — APPROVED** [review]

**Review by dgp1130 — DISMISSED** [review]
Reviewed-for: tooling-cli-shared-api

**Review by alan-agius4 — DISMISSED** [review]
Reviewed-for: tooling-cli-shared-api

**Comment by JoostK** [comment]
Yes, I shall rebase! Some more approvals are needed though.

**Review by josephperrott — APPROVED** [review]
LGTM

**Pull request closed without merging**
