### PR TITLE
feat(forms): FormArray.at can return undefined

### LINKED ISSUE #16933: ReactiveForms: FormArray.at could return undefined
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The `FormArray.at` method signature declares the return value to be `AbstractControl`.

**Expected behavior**

The `FormArray.at` method signature declares the return value to be `AbstractControl | undefined`.

Since:
`FormArray.at` returns the result of accessing the contained `controls` array.
`undefined` is returned when the supplied index is out-of-range, with respect to the target `FormArray`.

Note: `Typescript` does not point out an issue, even with `strictNullChecks: true`.

**Minimal reproduction of the problem with instructions**

```typescript
    const formBuilder: FormBuilder = new FormBuilder();
    const formArray: FormArray = formBuilder.array([]);

    const outOfRangeItemPositiveAt: AbstractControl = formArray.at(5);
    const outOfRangeItemNegativeAt: AbstractControl = formArray.at(-1);

    console.log(`outOfRangeItemPositiveAt is defined = [${!!outOfRangeItemPositiveAt}]`);
    console.log(`outOfRangeItemNegativeAt is defined = [${!!outOfRangeItemNegativeAt}]`);

    console.log(`outOfRangeItemPositiveAt = [${outOfRangeItemPositiveAt}]`);
    console.log(`outOfRangeItemNegativeAt = [${outOfRangeItemNegativeAt}]`);
```
**What is the motivation / use case for changing the behavior?**

To indicate the possibility of an `undefined` result.

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **Browser:** [ Chrome ]

 
* **Language:** [ TypeScript 2.3.2 | ES5 ]

* **Node (for AoT issues):** `node --version` = v6.9.2

### PR DESCRIPTION
**Pull request by JeanMeche**
FormArray.at may return undefined as arrays do return undefined with an out-of-bound index.

fixes #16933

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [x] Yes, migration schematics provided. 
- [ ] No

This is my 1st PR for a feature with a migration schematic, I'm open for every constructive comments about it. 

Per @dylhunn, on #16933, I helped myself with [aeec223](https://github.com/angular/angular/commit/aeec223db1236db236ab56a4a283cf2ca410cae3) to create the schematic.

### CODE REVIEW

**Comment by JeanMeche** [comment]
Any info on what is failing on the internal tests ?

**Comment by dylhunn** [comment]
This is failing because it breaks google's internal code base. Which makes sense -- this is a breaking change. Every call site where `at` is used would need either a null check or a `!`. Most likely, this change would need an accompanying migration schematic to insert the `!` everywhere, and then could be landed in a major version.

**Comment by dylhunn** [comment]
@JeanMeche Thanks again for this exhaustive PR! In order to merge this, I will need to migrate all of google's internal code.

Unfortunately, because Google does not the the Angular CLI to build, we cannot run the migration using the normal tooling. So every migration has a _secondary entrypoint_, which allows the migration to run as a TSLint rule instead. You can find them in `packages/core/schematics/migrations/google3/`, and there are accompanying tests for each one, just to make sure that the entrypoint works. In addition to the ones you see there, there are a number that have been deleted (since they are obsolete), but you can find them in the repo history for reference.

Let me know if you'd be able to implement that as well -- we'd need it to migrate google, in order to merge this PR.

Thanks.

**Comment by JeanMeche** [comment]
@dylhunn Thanks for the feedback, I plugged the google3 entry point and added a basic test. 

Tell me if you need something more 👍

**Comment by dylhunn** [comment]
@JeanMeche This tentatively looks good. I'm going to try to run the migration inside Google during our fixit coming up week of November 28th, and I'll do a full review closer to then.

We won't be able to actually land this until the v16 merge window opens in ~4 months, but I've added it to the tracking milestone for v16.

**Comment by JeanMeche** [comment]
It believe this will shift to at least v17 ?

**Comment by AndrewKushnir** [comment]
> It believe this will shift to at least v17 ?

Yes, I've added it to the `v17-candidates` milestone.

**Comment by JeanMeche** [comment]
I'll close it as it is too big a hasle to land for a small return.

**Pull request closed without merging**
