### PR TITLE
[13.2.x]: patch port of angular update/dev-infra update

### PR DESCRIPTION
**Pull request by devversion**
Patch port of https://github.com/angular/angular/pull/45206

### CODE REVIEW

**Comment by devversion** [comment]
Note: Please pay attention to the golden update. Had to update as the job failed otherwise. Seems like a small increase, but it's always hard to tell if we slowly move to threshold boundaries over time.. 🤷

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: size-tracking

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: size-tracking

**Comment by devversion** [comment]
The changes were already approved, except for the size-tracking, so I'll move ahead and mark this as ready

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 913bbba42b71955d91e0b018a9768d07366e305d.

**Pull request closed without merging**
