### PR TITLE
refactor(docs-infra): use CDK clipboard service

### PR DESCRIPTION
**Pull request by crisbeto**
The CDK has had a service for copying strings to the clipboard for a while now. These changes switch AIO to it, rather than having to maintain a custom solution.

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
LGTM

**Comment by theBolck** [comment]
crisbeto:cdk-clipboard

**Comment by theBolck** [comment]
Genial

**Comment by gkalpak** [comment]
For reference, (based on comparing CI jobs from [master][1] and [this PR][2]) this increases the bundle size of one of the lazy bundles (`default~code-code-example-module~code-code-tabs-module`) by just 0.11KB (from 53.77KB to 53.88KB).

[1]: https://circleci.com/gh/angular/angular/918530
[2]: https://circleci.com/gh/angular/angular/919006

**Review by gkalpak — APPROVED** [review]
:tada:

**Pull request closed without merging**
