### PR TITLE
chore: remove unused docs/dgeni tasks and packages

### PR DESCRIPTION
**Pull request by IgorMinar**
This stuff now lives in angular.io repo.

Related to #4477

### CODE REVIEW

**Comment by alexeagle** [comment]
cc @petebacondarwin 
I can't tell from the PR: does this delete the entire docs directory?

**Comment by alexeagle** [comment]
and you missed `Error: Task docs/test is not configured as a task on gulp`

**Comment by IgorMinar** [comment]
@alexeagle not the whole directory, I left stuff needed for d.ts generation. I guess we'll remove those in your pr

**Comment by IgorMinar** [comment]
@alexeagle I removed the leftover task dependency on 'docs/test'. thanks!

**Pull request closed without merging**
