### PR TITLE
Perf: Remove decorator DSL which depends on Reflect, and can't be used sucesfuly with  Angular

### PR DESCRIPTION
**Pull request by mhevery**

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
please update the commit message as discussed

**Comment by mhevery** [comment]
@IgorMinar done

**Comment by mhevery** [comment]
@vicb http://test/OCL:164659837:BASE:164659910:1502234120239:45410e68 pre-flight

**Comment by vicb** [comment]
Blocked on failing the internal CI

**Comment by mhevery** [comment]
@vicb http://test/OCL:164923183:BASE:164923204:1502409581236:90e29af

**Pull request merged**
