### PR TITLE
fix(platform-browser): ensure that Hammer loader is called only once

### PR DESCRIPTION
**Pull request by arturovt**
Currently, the function that is provided through `HAMMER_LOADER` is called the
same number of times as the `HammerGesturesPlugin.addEventListener` method is called
(until the Hammer is loaded).

This commit adds a class property in which the loader call is saved, thereby
preventing multiple calls to the loader function.

## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
- [x] Bugfix

## What is the current behavior?
Issue Number: #25995

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
Thanks for creating this PR @arturovt 👍 

Just wanted to mention that there is a couple other PRs that we should take into account (to see it they are related/duplicates) while reviewing these changes: #26925, #26077.

**Comment by arturovt** [comment]
@AndrewKushnir thanks for pointing. Haven't seen the first one since it's not linked to the issue. Does it seem like those PRs are abandoned?

**Comment by AndrewKushnir** [comment]
> Does it seem like those PRs are abandoned?

@arturovt not sure if that's the case, but we'd need to revisit the changes from those PRs as well while reviewing this one to make sure all cases are covered. Also there may be some useful pieces in the mentioned PR (like test cases, etc) that may be reused.

**Comment by arturovt** [comment]
Sure.

**Review by AndrewKushnir — APPROVED** [review]
@arturovt thanks for the fix 👍

The change looks good, but I'd like to ask @jelbourn to review it as well (as an original author of the Hammer loader).

**Comment by arturovt** [comment]
@AndrewKushnir I accidentally deleted the fork but I see there are no conflicts. Would it be possible to merge if the fork doesn't exist (just curious, since I don't know)? I also forgot to update bundle size after `console.warn` was dropped.

**Comment by AndrewKushnir** [comment]
Hi @arturovt, I don't think we can merge without having a fork, so if you could re-create it and open a new PR that'd be great (closing this PR for now). Thank you.

**Comment by arturovt** [comment]
NP, I'll re-open it.

**Pull request closed without merging**
