### PR TITLE
typo correction

### PR DESCRIPTION
**Pull request by metasong**
then -> than

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Marked as approved - but we will not be able to merge this until you have signed the CLA @metasong.

Reviewed-for: global-docs-approvers

**Comment by metasong** [comment]
@googlebot I signed it!

**Comment by petebacondarwin** [comment]
Caretaker: this is just a simple docs change so should not need a presubmit.

**Comment by petebacondarwin** [comment]
Oops, I forgot to mention that the commit message needs fixing. Can you change it to:

```
docs: fix typo in NgForOf directive
```

**Comment by atscott** [comment]
Closing since https://github.com/angular/angular/pull/43641#issuecomment-931396617 has been undressed for a while. If you'd still like to contribute this fix, please open a new PR. Thanks!

**Pull request closed without merging**
