### PR TITLE
test(animations): Add size regression test for animations package

### PR DESCRIPTION
**Pull request by jessicajaniuk**
This adds a size regression test for the animations package to the test suite.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
This adds a new test target to check bundle size for the animations package.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe: tests

## What is the current behavior?

There are no size regression tests for the animations package alone.

Issue Number: N/A

## What is the new behavior?
There is now a test that checks specifically for size regression in the animations package.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
Looks great 👍 Thanks @jessicajaniuk!

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: size-tracking

**Review by atscott — APPROVED** [review]
Reviewed-for: size-tracking

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 112a6cdec37e1a3418c063ab7421aacc69027fd7.

**Pull request closed without merging**
