### PR TITLE
docs(aio): add FancyGrid to resources

### PR DESCRIPTION
**Pull request by MikeTatsky**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #27969

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
 Adding robust JavaScript grid library in resources section.

### CODE REVIEW

**Review by StephenFluin — CHANGES_REQUESTED** [review]
Can you make sure the commit message matches our contribution guidelines? You'll also need to sign the CLA.

**Comment by MikhailTatsky** [comment]
I signed CLA!

**Comment by MikhailTatsky** [comment]
@StephenFluin 
Could you rerun `checks`, please?
I think I did all.

**Comment by StephenFluin** [comment]
You'll need to amend the commit and update your commit message to follow our standard. The PR title looks like what your commit message should be.

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by MikhailTatsky** [comment]
@StephenFluin 
May I close this pull request and do new one with right title?

**Comment by brandonroberts** [comment]
@MikhailTatsky yes, you can open a new PR with the message `docs: add FancyGrid to resources page`

**Pull request closed without merging**
