### PR TITLE
fix(HttpClient): add missing signatures for HttpClient methods

### PR DESCRIPTION
**Pull request by princemaple**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #18424 

## What is the new behavior?
HttpClient methods now have the correct signatures defined

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
N/A

### CODE REVIEW

**Comment by splincode** [comment]
@princemaple what is the status of your pull request? is it still relevant?

**Comment by princemaple** [comment]
If the missing signatures are still not there then it's still relevant. I'm traveling and on my phone, kinda hard to check..

**Comment by splincode** [comment]
@princemaple I'm sorry, but http module is deprecated, you need closed current PR

**Comment by princemaple** [comment]
This PR is about HttpClient.

**Comment by splincode** [comment]
I'm sorry, I did not understand at first

**Pull request closed without merging**
