### PR TITLE
test(ivy): temp disable payload limit tests

### PR DESCRIPTION
**Pull request by kara**
Update payload size for ivy

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
@kara we discussed this with @IgorMinar and decided to disable the size tracking for render3 for now. Tha plan is to do it on symbol level. This is creating too much noise. Could you disable it? 

//cc @chuckjaz

**Review by jasonaden — APPROVED** [review]

**Comment by IgorMinar** [comment]
wait - this is not what we agreed on though. because you disabled it here, we no longer see the trend (see how the graph ends abruptly https://size.angular.io/hello_world__render3__rollup/master)

What we agreed on is that we will no longer break the build when the size changes. This was supposed to be done by removing these lines of code: https://github.com/angular/angular/blob/b58c3527e993c1f87dd435c9296d88eb6a2cc366/integration/_payload-limits.json#L18-L40 

Can we please roll back this change and update the _payload-limits.json as I suggested?

**Comment by kara** [comment]
Apologies! Clearly misunderstood your meaning.

**Comment by IgorMinar** [comment]
No worries. I asked Misko to fix this unless you want to do it. Please sync
up with Misko.

**Comment by mhevery** [comment]
Given that we have a new way of tracking the payload, is this still needed?

**Comment by IgorMinar** [comment]
The new way doesn't show trend. Alex has requested that feature but it's
going to take a while. In this meantime all we have are comments on various
PRs that don't show us the trend.

**Comment by mhevery** [comment]
@IgorMinar now that we buildsize bot is your comment still relevant?

**Comment by IgorMinar** [comment]
yes. please read https://github.com/angular/angular/pull/21940#issuecomment-364017310

**Pull request closed without merging**
