### PR TITLE
feat(docs-infra): suggest localized version based on browser language

### PR DESCRIPTION
**Pull request by lacolaco**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

When the browser language (`navigator.language`) matches defined localizations, the app suggests localized version documentation.

Inspired by Material-UI documentation site. https://material-ui.com/

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I'm a maintainer of angular.jp. 
I'd love to hear the opinions from angular.cn and angular.kr maintainers.

### CODE REVIEW

**Comment by IgorMinar** [comment]
Hi @lacolaco we are sorting this out and coming up with generic guidelines for how to better support community supported localized docs. Please be patient with us in the meantime. I'm hoping to have an update for you within a week or so.

**Comment by petebacondarwin** [comment]
@IgorMinar (or maybe @StephenFluin) do we have an update on this?

**Comment by StephenFluin** [comment]
It sounds like Igor has other plans, but this seems like it might be a solid step forward to consider at least for the short term.

The assumption here is that the docs on these sites are always up to date, but in reality they might lag a little.

**Comment by IgorMinar** [comment]
@StephenFluin content freshness is one potential problem.

The others are:

- ensuring that visitors understand that the localized sites are community driven and not Angular/Google owned/monitored
- dealing with versioning and branching
- missing analytics which means we'll have less data for making decisions
- lastly, the snackbar is going to show up every time you visit angular.io with no way to stop it, that will be annoying.

**Comment by petebacondarwin** [comment]
Hi @lacolaco - thank you for your work on this.

We discussed this further today and decided that we do not want to implement this feature.
We don't control the quality of the sites that we would be redirecting users to, and also this would add more snackbar pop ups which is not a great UX either.

**Pull request closed without merging**
