### PR TITLE
feat(ngFor): add the ability to repeat the given number of cycles

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
**Before**

```
 @Component({
  selector: 'my-app',
  template: `
    <div>
      <h2 *ngFor="let item of dummyArr">{{item}}</h2>
    </div>
  `,
})
export class App {
  dummyArr: any[] = [0, 1, 2, 3, 4];
}
```

**After**

```
@Component({
  selector: 'my-app',
  template: `
    <div>
      <h2 *ngFor="let cycle of cycles">{{cycle}}</h2>
    </div>
  `,
})
export class App {
 cycles: number = 5;
}
```

### CODE REVIEW

**Comment by vicb** [comment]
Is this a frequent use case ?
You can do this quite easily with a generator.

**Comment by DzmitryShylovich** [comment]
> Is this a frequent use case ?

yeah, a lot of people in gitter have use cases where they need to create a given number of items, for example 5 `<li>` elements etc.

**Comment by vicb** [comment]
- I don't see any "real" argument there,
- this would deviate from JS syntax

I'm :-1: on merging this. I'll discuss with the team - please attach strong use cases if you have some in the meantime.

**Comment by vicb** [comment]
Sorry @DzmitryShylovich but we don't see value added in this PR. closing it.

**Comment by laco0416** [comment]
I think it should be implemented as ngForRange.

**Comment by maoguiyou** [comment]
In angular1 can achieve this function?  
example：
   given number=10;
   create 10 <option>  elements
thanks~~~

**Pull request closed without merging**
