### PR TITLE
refactor(ivy): combine query load instructions

### PR DESCRIPTION
**Pull request by crisbeto**
Combines the `loadViewQuery` and `loadContentQuery` instructions since they have the exact same internal logic. Based on a discussion here: https://github.com/angular/angular/pull/32067#pullrequestreview-273001730

### CODE REVIEW

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM, thnx!

**Review by kara — APPROVED** [review]
LGTM

**Comment by kara** [comment]
[VE presubmit](https://test.corp.google.com/ui#id=OCL:262926247:BASE:262926268:1565622957892:e9e7357c)

[Ivy presubmit](https://test.corp.google.com/ui#id=OCL:262926247:BASE:262926429:1565623028120:2efa7e82)

**Comment by kara** [comment]
merge-assistance: global approval

**Pull request closed without merging**
