### PR TITLE
docs(core): Document TestBed.get deprecation

### PR DESCRIPTION
**Pull request by Goodwine**
It was replaced by TestBed.inject, documenting such change.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [N/A] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by vikerman — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Hi @Goodwine, thank you for this! Would you rebase? I'd love to get this in. If you'd like them, I also have [notes on rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase). Please tag me when you're ready so I can help you get this in. Thanks!

**Review by kapunahelewong — APPROVED** [review]
LGTM!

**Comment by Goodwine** [comment]
Done, PTAL

**Review by kapunahelewong — APPROVED** [review]
Thank you, @Goodwine! 

Caretaker, this is a docs only change. Thank you!

**Pull request closed without merging**
