### PR TITLE
docs: Update deployment docs for Vercel

### PR DESCRIPTION
**Pull request by leerob**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The current documentation references and out of date package for deploying to Vercel.

## What is the new behavior?

Updated with the latest recommendation.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@leerob thanks for updating the docs 👍

Could you please also [sign the CLA](https://github.com/angular/angular/pull/44904/checks?check_run_id=5001361267) when you get a chance, so that we can proceed with merging this PR?

**Comment by leerob** [comment]
Done!

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Merge assistance: this is an update to an existing item in the deployment section, no extra reviews are required.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 5e099b5e6c65b00bd8071ee62ac560eb158f12c1.

**Pull request closed without merging**
