### PR TITLE
docs: fix links in ngModule API guide

### LINKED ISSUE #54506: Angular Dev: UI duplicated on navigation
### Describe the problem that you experienced

image
image

Getting duplicated root of the app when navigating to the above URL

### Enter the URL of the topic with the problem

https://angular.dev/guides/providers

### Describe what you were looking for in the documentation

Trying to get some info in the providers implementation for standalone modules and on navigation it created a duplicate UI which closed on navigation

### Describe the actions that led you to experience the problem

_No response_

### Describe what you want to experience that would fix the problem

_No response_

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Running on latest chrome
```

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by JeanMeche**
fixes #54506

### CODE REVIEW

**Comment by sonukapoor** [comment]
@JeanMeche Doesn't seem like this fixed it:

image

**Comment by JeanMeche** [comment]
There is no link to this URL, I'd consider it a separate issue.

**Comment by sonukapoor** [comment]
> There is no link to this URL, I'd consider it a separate issue.

Would it make sense to remove the linked issue then?

**Review by josephperrott — APPROVED** [review]
LGTM

**Pull request closed without merging**
