### PR TITLE
G3_MASTER DUPE of #8161 (rebased on correct branch): Benchpress User metric

### PR DESCRIPTION
**Pull request by jeffbcross**

### CODE REVIEW

**Comment by tbosch** [comment]
Travis failed because
```
benchpress/test/metric/user_metric_spec.ts:53:12: Untyped property access to "get" which could be a special ts2dart builtin. Please add type declarations to disambiguate.
```

**Comment by tbosch** [comment]
Probably cast to `Injector` before calling `get`.

**Comment by mhevery** [comment]
@jeffbcross Can you have a look and push this PR forward?

**Comment by tbosch** [comment]
Cherry picked into #9073 for g3/dart and into master.

**Comment by tbosch** [comment]
Had trouble making this work on g3_master...

**Pull request closed without merging**
