### PR TITLE
docs(aio): fix not found schema

### PR DESCRIPTION
**Pull request by aravindfz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: [20338](https://github.com/angular/angular/issues/20338)

## What is the new behavior?
Documentation refrence will work fine.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by trotyl** [comment]
Could you please change the commit message to `docs(aio): fix not found schema`? The current one is invalid.

<sub>The title itself sounds weird, could it be something like: `fix schema.ts file url in link`?</sub>

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Thx! Please fix the commit message (to follow our [commit message guidelines][1]) as mentioned above and include `Fixes #20338` (so that the issue is automatically closed when the PR is merged.

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by aravindfz** [comment]
Ok @gkalpak I have updated as you suggested. :)

**Comment by aravindfz** [comment]
I'm still in the learning process. I tried to give a commit message but it fails many times. Can you help me how to run the master branch in my local machine

**Comment by gkalpak** [comment]
I am not sure what you mean by "give a commit message" and "run the master branch" (but I would very much like to help :grin:).
If you are trying to change the commit message (and assuming you have cloned https://github.com/aravindfz/angular to your local machine and checked out the `pr-schema` branch), you can do the following:

```
# Amend the commit.
git commit --amend
# ...an editor should open with the current commit message, where you can edit it and save...

# Update the PR.
git push --force-with-lease origin pr-schema
```

**Comment by aravindfz** [comment]
Ok commit message I got it.
If I want to run the core Angular in my local how to do that? :(

**Comment by gkalpak** [comment]
If you want to build angular and/or run the tests locally, you can follow the instructions in [DEVELOPER.md][1] (but be warned that building on Windows is probably not possible atm).

If you want to build/test/serve the angular.io app locally, you can follow the instructions in [aio/README.md][2] (it works on Windows too :smiley:).

##
BTW, can you make sure that the `fixes #...` part is separated by the commit message subject by a new line:

> docs(aio): fix not found schema
>
> Fixes #20338

[1]: https://github.com/angular/angular/blob/master/docs/DEVELOPER.md
[2]: https://github.com/angular/angular/blob/master/aio/README.md

**Comment by aravindfz** [comment]
@gkalpak Done (y) sorry for late though was packed at workplace. Just reached home! :)

**Comment by gkalpak** [comment]
No worries :smiley: Thx for following up so quickly 👍 
<sub>(Marked for merge.)</sub>

**Pull request closed without merging**
