### PR TITLE
Fix docs 24571

### PR DESCRIPTION
**Pull request by anupwritescode**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Behavior as defined in issue #24571

Issue Number: N/A

## What is the new behavior?
Fix for issue #24571 

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

## Other information
angular

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
LGTM - please can you squash the two commits together into one?

Reviewed-for: global-docs-approvers

**Comment by anupwritescode** [comment]
@petebacondarwin umm, the first commit was pushed from my local machine and then rebase with remote master was done from github web. Now I'm not able to see the second commit on my local machine. I tried a few things, but was not successful. Any suggestions?

**Comment by petebacondarwin** [comment]
I have rebased on master and force-pushed to your branch. That seems to have solved it. For reference I did:

```
git rebase master
git push --force
```

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Pull request closed without merging**
