### PR TITLE
HtmlParser: self-closing and void elements handling ** BREAKING **

### PR DESCRIPTION
**Pull request by vicb**
see individual commit messages for more details

/cc @IgorMinar @jelbourn @pkozlowski-opensource @tbosch

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
I just went through the tests and the behavior looks good to me.

**Comment by e-oz** [comment]
Can you please add couple examples of what is not allowed now, what was allowed before (and why)?

**Comment by IgorMinar** [comment]
Only valid Html5 is allowed

**Comment by jelbourn** [comment]
@e-oz Basically anything that is invalid HTML is now disallowed:

```html
NOT ALLOWED
<div />
<custom-thing />
<input></input>
<img ...></img>
```

**Pull request closed without merging**
