### PR TITLE
docs: fix two grammatical/typographical errors present in first-app-lesson-06.md

### PR DESCRIPTION
**Pull request by lmartins18**
fix two grammatical/typographical errors present in the document.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Lesson has typographical errors.
https://angular.io/tutorial/first-app/first-app-lesson-06

Issue Number: N/A

## What is the new behavior?
Lesson's grammar has been fixed and reviewed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM, but we have conflicting changes with #50418. It looks like you'll also need to fix your commit message. You've fixed the PR header, but the commit message still needs to be addressed.

**Comment by lmartins18** [comment]
> LGTM, but we have conflicting changes with #50418. It looks like you'll also need to fix your commit message. You've fixed the PR header, but the commit message still needs to be addressed.

Oops! Should be correct now. 
In regards to the conflicting changes, what should I do?
Thanks you.

**Comment by jessicajaniuk** [comment]
If you could you add to your commit message body the following, you'll both get credit for the change:

Co-authored-by: Usama Nadeem <usamanadeem1991@gmail.com>

**Comment by lmartins18** [comment]
> If you could you add to your commit message body the following, you'll both get credit for the change:
> 
> Co-authored-by: Usama Nadeem [usamanadeem1991@gmail.com](mailto:usamanadeem1991@gmail.com)

Done!

**Comment by jessicajaniuk** [comment]
@lmartins18 It looks like you've updated the PR header and body, but not the commit message. Can you update the commit message / body with this info? You can use `git commit --amend` to amend the commit message. After that, you'd need to force push. That'll make lint go green.

**Comment by lmartins18** [comment]
> @lmartins18 It looks like you've updated the PR header and body, but not the commit message. Can you update the commit message / body with this info? You can use `git commit --amend` to amend the commit message. After that, you'd need to force push. That'll make lint go green.

Should be done now Jessica, thank you.
I apologise, I'm still getting used to git, by mistake I pushed to main! 
I reverted the change and changed the right branch.
Thank you for your patience.

**Comment by jessicajaniuk** [comment]
@lmartins18 No worries at all. There's definitely a learning curve, and those are common mistakes. Looks like you got it.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 4c01107c0de875837527b42e2b548b83806235f5.

**Pull request closed without merging**
