### PR TITLE
feat(datePipe): date pipe week support

### PR DESCRIPTION
**Pull request by laskoviymishka**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

see _http://plnkr.co/edit/l9wU6DlGRsZkGKEjcHA1?p=preview_

### CODE REVIEW

**Comment by laco0416** [comment]
Internationalization API doesn't support `week` property.
http://www.ecma-international.org/ecma-402/1.0/#sec-12.1

Does Angular stop using the standard API?

**Comment by laskoviymishka** [comment]
@laco0416 no, datepipe still related in `Intl` API, but for `week` use vanilla JS to get week number. This is PR made to fill gap between a1 dateFilter and a2 datePipe.

**Comment by laco0416** [comment]
@laskoviymishka Thank you. I understand your motivation. 

In this context, I'd like to know the stance of core team about _compatibility_ vs _standard spec_

**Comment by laskoviymishka** [comment]
@laco0416 me too

In a fact `Intl` API is almost worst API ever been made by human being (I not sure about last statement, it looks like it was maded by robots who not follow first law of Robotics and try to demolish every human, and they start with this scary API).

**Comment by pkozlowski-opensource** [comment]
@laskoviymishka thnx for the PR - I see where you are going with it but we've decided to hold off PRs that would change API surface till we've got better idea of where to take i18n-related pipes in the future. I've added more info in https://github.com/angular/angular/issues/10809#issuecomment-266532053

I'm going to close this PR for now but we can come back to the topic when `Intl` API concerns are sorted out. Once again, thnx for all the hard work on the topic so far!

**Pull request closed without merging**
