### PR TITLE
feat(common): support null / undefined in ngTemplateOutlet (#24926)

### LINKED ISSUE #24926: Convenient way to define context of a sub-template
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?
Assume that you want to define a context for a part of the template, like on the following artificial example:

```
<ng-container [some-way-to-specify-context]="{success: noError && resultAvailable; issueCount: warningCount + errorCount">

<h1 [class.success]="success">
<i class="fas" [class.fa-check]="success">
{{title}}
</h1>

<div>Issue count: {{issueCount}}</div>

<div *ngIf="issueCount > 0">
...
</div>

</ng-container>
```

Currently, we have multiple choices:

- use nested ngIf directives (not convenient for more variables, not usable for variables which can have "false" values like issueCount above)
- use *ngTemplateOutlet (probably the best choice now, but a bit cumbersome)
- use [ngTemplateOutlet] - quite comparable to the previous choice
- write a custom structural directive similar to ngTemplateOutlet
- refactor the code so that the sub-template is moved into a sub-component (often a good idea, but not always)

There might be other options which I do not know about. Here I describe the choices in more detail.

Nested ngIfs:

```
<ng-container *ngIf="noError && resultAvailable as success">
<ng-container *ngIf=warningCount + errorCount as issueCount">
...
</ng-container>
</ng-container>
```

The above code fails if issueCount si 0.

Using *ngTemplateOutlet:

```
<ng-template #xxx let-success="success" let-issueCount="issueCount">
...
</ng-template>
<ng-container *ngTemplateOutlet="xxx; context: {success: noError && resultAvailable, issueCount: warningCount + errorCount}">
</ng-container>
```

The above code works, but it is a bit cumbersome. In my opinion, the biggest problem is unnecessary bloat of global namespace with template reference variable.

Another way to write the same:

```
<ng-template #xxx let-success="success" let-issueCount="issueCount" [ngTemplateOutlet]="xxx" [ngTemplateOutletContext]="{success: noError && resultAvailable, issueCount: warningCount + errorCount}">
...
</ng-template>
```

Another option is to write a custom structural directive. Then, the code might look like (skipping obvious directive implementation):

```
<ng-container *customContext="{success: noError && resultAvailable, issueCount: warningCount + errorCount}">
</ng-container>
```

Nice and clean, but I feel that for something like this, we should have support in angular itself, without the need to write a custom directive. I have two suggestions how this can be achieved.

The first possibility is to allow code like this:

```
<ng-container *ngTemplateOutlet="undefined; context: {success: noError && resultAvailable, issueCount: warningCount + errorCount}">
</ng-container>
```

That would require an extension to ngTemplateOutlet to obtain TemplateRef in its constructor and use that value if undefined is provided as the input.

Other possibility is to extend template syntax to support the following:

```
<ng-container *ngTemplateOutlet="$this; context: {success: noError && resultAvailable, issueCount: warningCount + errorCount}">
</ng-container>
```

where $this may be any string providing a reference to underlying ng-template (for example, ngTemplate string might be used).

I'd like to know angular developers opinion about this. If the first choice is preferred, I'm able to implement that change and send a pull request.

## Environment

<pre><code>
Angular version: 6.0.9

### PR DESCRIPTION
**Pull request by sebek64**
PR Close #24926

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 24926

Introduce a convenient way to define context in a sub-template.

## What is the new behavior?

ngTemplateOutlet supports null / undefined values, with the fallback to internal template.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No (in my opinion)
```

although it changes behavior in some rare cases (using *ngTemplateOutlet="null" to comment-out template part).

### CODE REVIEW

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/pull/14621

**Comment by sebek64** [comment]
@trotyl Thanks for pointing me to a duplicate PR. It seems that the duplicate is no longer maintained and has conflicts. I've just updated my branch to resolve conflicts with current master. If you has any suggestions what should be improved, I'm ready to update the patch again. If you disagree with this change, please tell me that soon, so that I don't update the patch many times and then get it rejected.

**Comment by sebek64** [comment]
@pkozlowski-opensource Well, I agree that code like

```
<ng-container *ngTemplateOutlet="null; context: {...}">
something here
</ng-container>
```

is quite confusing. But, in my opinion, the following code is much less confusing:

```
<ng-container *ngTemplateOutletContext="{...}">
something here
</ng-container>
```

The only confusing part of the above code is the name of the directive. Even better solution would be

```
<ng-container *ngContext="{...}">
something here
</ng-container>
```

To obtain version 2, one has to change selector of ngTemplateOutlet to be [ngTemplateOutlet],[ngTemplateOutletContext]. For now, I've modified the patch this way, because I think it is a good idea.

To obtain version 3, one has to add an alias to input ngTemplateOutletContext to ngContext, and change the selector similarly. Alternatively, it is possible to create a completely new directive ngContext.

I tried to prepare a somewhat real-world example in the original issue. I'll try again, with another example. It is not purely real-world, as pasting here a real-world code wouldn't clarify much.

```
<ng-container *ngIf="(dataObservable | async) as data">
  <ng-container *ngTemplateOutlet="null; context: {success: data.errorCount === 0 && data.warningCount === 0, successCount: data.totalCount - data.errorCount - data.warningCount, failedCount: data.errorCount + data.warningCount}">
    <dl>
      <dt>Name</dt>
      <dd [class.text-success]="success">{{data.name}}
      <dt>Description</dt>
      <dd [class.text-success]="success">{{item.description}}</dd>
      <dt>Number of successful items</dt>
      <dd [class.text-success]="true">{{successCount}}</dd>
      <dt>Number of unsuccessful items</dt>
      <dd>{{failedCount}}</dd>
    </dl>
    <h1>Detailed report of successful items</h1>
    <custom-items-component [items]="data.successfulItems"></custom-items-component>
    <custom-paginator-component [total]="data.successCount"></custom-paginator-component>
  </ng-container>
</ng-container>
```

In the above example, I've tried to demonstrate how useful is to create new constants with assigned expressions. It might seem a bit artificial, one can argue that the same can be achieved via other means, but that is not always true. For example, one can change backend server to provide data in a more convenient form, so that the need for complicated expressions is reduced. That is not always possible. The other objection might be that using multiple [class.text-success] can be avoided by clever usage of stylesheets. Yes,  that's true here, but not always.

I probably cannot find some universally accepted example that demonstrates why it is useful to assign names to expressions in templates. At least, I tried.

The fact that my pull request is a duplicate of another doing the same indicates that other people would find this feature useful.

**Comment by sebek64** [comment]
@pkozlowski-opensource Thanks for the long explanation and sketch of the future plans. I'm looking forward to proper solution of this issue and I understand that I'll take many months to be finally resolved.

**Pull request closed without merging**
