### PR TITLE
Diagrams wrong colors

### PR DESCRIPTION
**Pull request by vincent-agi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
There is only one shape on best pratices diagrams kipping-subtrees

Issue Number: #56314

## What is the new behavior?
I have mixed rectangles and circles to improve readable

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
The round nodes introduces a disbalance in the chart. What do you think of using a [hexagone node] (https://mermaid.js.org/syntax/flowchart.html#a-hexagon-node) instead and my keep the colors ?

**Comment by vincent-inviseo** [comment]
@JeanMeche Yes i agree. i will make changes this afternoon. What do know about `Event` Element on mermaid diagram ?

**Comment by vincent-agi** [comment]
@JeanMeche i have a little problem with my angular version. I will push soon

**Comment by vincent-agi** [comment]
@JeanMeche I pushed a new version with corrections. I wait your returns or your agree.
Thank you so much for this experience

**Comment by JeanMeche** [comment]
We still have some styling issues on the dark theme. 

Screenshot 2024-07-07 at 23 42 00

**Comment by vincent-agi** [comment]
Hi @JeanMeche, thanks a lot. Do you want work togerther to solve this issue. That interest me.

**Comment by vincent-agi** [comment]
@JeanMeche i didn't found issue about dark mode. Have you got a way of follow to solve it ?

**Comment by JeanMeche** [comment]
Fixed by #58223

**Pull request closed without merging**
