### PR TITLE
docs: fix typo in app.component.ts

### PR DESCRIPTION
**Pull request by eltociear**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:
Fixed typo.
```
identifer -> identifier
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM for the code change.

It looks like you'll need to fix your commit header (Not the PR header). I suggest switching if from `refactor(aio): ...` to just `docs: ...`. You should be able to quickly fix this with `git commit --amend` and then force pushing your change.

**Comment by eltociear** [comment]
@jessicajaniuk Thanks!
Changed commit header and PR header.

**Review by jessicajaniuk — APPROVED** [review]
LGTM

Thank you!

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 7e0de5b8be3d46c07f80e7161093b71440ea9111.

**Pull request closed without merging**
