### PR TITLE
docs: changed component name to home.component.ts in point…

### PR DESCRIPTION
**Pull request by OssamaRafique**
… 2 of step 3

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #50166 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi Ossama, thank you for improving the docs ! 

Please [sign the CLA](https://github.com/angular/angular/pull/50170/checks?check_run_id=13271908754), for your PR to move forward !

**Comment by OssamaRafique** [comment]
@JeanMeche Signed.

**Comment by JeanMeche** [comment]
One this, can you amend your commit to remove `doc-infra`. You're only changing the content of the doc, not parts of the angular.io app.

**Comment by OssamaRafique** [comment]
> One thing, can you amend your commit to remove `doc-infra`. You're only changing the content of the doc, not parts of the angular.io app.

@JeanMeche Thanks for letting me know. I did the proposed changes.

**Review by vamsi-kodimela — APPROVED** [review]

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 46a3692a02c3819c846ba837dcbc7141b6033c85.

**Pull request closed without merging**
