### PR TITLE
fix(router): run microtask outside of Angular when removing pending task

### PR DESCRIPTION
**Pull request by arturovt**
This commit updates the Router logic to schedule microtasks outside of Angular when removing pending tasks. This prevents redundant change detections since scheduling a microtask in the next tick would otherwise trigger another change detection.

cc @AndrewKushnir

### CODE REVIEW

**Comment by emiryumak** [comment]
@CodiumAI-Agent

**Review by AndrewKushnir — APPROVED** [review]
@arturovt thanks for the fix 👍

**Comment by AndrewKushnir** [comment]
[Global Presubmit](https://test.corp.google.com/OCL:551091695:BASE:551091291:1690348067436:75d7368e).

**Comment by AndrewKushnir** [comment]
FYI, after running global presubmit in Google's codebase, it looks like this change is causing failures that require investigation. It's unlikely that we'd be able to prioritize the investigation in the nearest future, so I'm closing this PR for now.

**Pull request closed without merging**
