### PR TITLE
docs: fix typo in `browser-support.md` (ES1015 --> ES2015)

### PR DESCRIPTION
**Pull request by Zovube**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The first bundle contains modern `ES1015` syntax, takes advantage of built-in support in modern browsers, ships less polyfills, and results in a smaller bundle size. 

## What is the new behavior?

The first bundle contains modern `ES2015` syntax, takes advantage of built-in support in modern browsers, ships less polyfills, and results in a smaller bundle size.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Zovube** [comment]
I signed it!

**Review by gkalpak — APPROVED** [review]
Good catch, thx! 😄

**Comment by gkalpak** [comment]
@Zovube, could you please change the commit message to follow our [guidelines][1]. E.g. change to something like:

> docs: fix typo on \`browser-support.md\` (ES1015 --> ES2015)

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Review by IgorMinar — APPROVED** [review]
Woops! Thank you

**Comment by Zovube** [comment]
@gkalpak changed commit message to follow  guidelines, awesome framework  btw :thumbsup:

**Pull request closed without merging**
