### PR TITLE
docs: Edited to remove jargon in Reference Errors

### PR DESCRIPTION
**Pull request by TeriGlover**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by alxhub — APPROVED** [review]

**Review by aikithoughts — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by alxhub — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Note to Caretaker: this is a straightforward change in the docs that trigger `public-api` group approvals. We've got 2 out of 3, but it should be safe to proceed with the current set of approvals.

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Pull request closed without merging**
