### PR TITLE
fix(dart/transform): Use updated package:analyzer

### LINKED ISSUE #950: Issue in Dart transformer
On master (afda43dc0281e3671d6df3218749d5050d47f188),

```
gulp clean
gulp build.dart
gulp serve/examples.dart
```
+ open http://localhost:8080/src/hello_world/index.html

gives the following error:

```
$ gulp serve/examples.dart
Dart SDK detected
[19:27:12] Using gulpfile ~/dart/angular/gulpfile.js
[19:27:12] Starting 'serve/examples.dart'...
Loading source assets... 
Loading angular2 transformers... 
Serving examples web  on http://localhost:8080
Serving examples test on http://localhost:8081
[Warning from DirectiveProcessor]:
Processing ng directives failed.
Exception: Error in test/benchpress/webdriver_async.server.spec.dart: Expected an identifier
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ')'
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ';'
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ';'
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ';'
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ';'
Error in test/benchpress/webdriver_async.server.spec.dart: Expected an identifier
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ';'
[...]
```

/cc @tbosch should we add e2e for this ?

### PR DESCRIPTION
**Pull request by kegluneq**
Updates Angular 2 to use package:analyzer v0.24.0, which contains fixes
for the parsing of `async` and `await`.

Closes #950

### CODE REVIEW

**Comment by yjbanov** [comment]
LGTM if LGT travis.

**Comment by mhevery** [comment]
@kegluneq can you get travis happy?

**Comment by kegluneq** [comment]
the issue is pubspec.yaml constraints. all of our dependencies that need analyzer need to be updated as well.

- [x] [observe](https://github.com/dart-lang/observe)
- [ ] [di.dart](https://github.com/angular/di.dart/pull/210)
    - [x] Change merged
    - [ ] Tag & publish 3.3.4 to pub
- [ ] [angular.dart](https://github.com/angular/angular.dart/pull/1694)
    - [ ] Change merged
    - [ ] Tag & publish to pub

I'll keep working on this today

**Comment by kegluneq** [comment]
@rkirov is working rolling up some updates & releasing Angular.dart `1.1.1`, which should make travis happy.

**Comment by kegluneq** [comment]
Angular `1.1.1` is now out. The pubspec was updated to pull in the new `analyzer` in 99045b2f6adfac16da1628f40751fb07f10a52a3

**Pull request closed without merging**
