### PR TITLE
docs: fix code style

### PR DESCRIPTION
**Pull request by Piyush132000**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM! Thanks, @Piyush132000!

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 4a68b0f6abbc7601db2311cfe3e97bef911cfed6.

**Comment by PiyushAgrawal1243** [comment]
Thanks @jessicajaniuk

**Comment by Piyush132000** [comment]
Thank @jessicajaniuk

**Pull request closed without merging**
