### PR TITLE
fix(forms): ensure OnPush ancestors are marked dirty when the promise resolves

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
- [x] Bugfix

## What is the current behavior?
Issue Number: #10816

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by arturovt** [comment]
@atscott this is a copy of this PR (https://github.com/angular/angular/pull/39879).

**Comment by AndrewKushnir** [comment]
[Global Presubmit](https://test.corp.google.com/ui#id=OCL:425220694:BASE:425220782:1643571423567:63101ae7).

**Review by atscott — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 889de8276d77eed3b65f8c2032f2f5c3c4ac9139.

**Pull request closed without merging**
