### PR TITLE
feat(core): Add incremental hydration public api

### PR DESCRIPTION
**Pull request by thePunderWoman**
This exposes the public api to utilize incremental hydration.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api 
Reviewed-for: fw-core

**Comment by thePunderWoman** [comment]
Caretaker note: the adev failures are expected. This is ready for merge.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 69fc5ae9229b872a9ad70eb920087af2a378fead.

The changes were merged into the following branches: main

**Pull request closed without merging**
