### PR TITLE
docs: update router reference to use standalone

### PR DESCRIPTION
**Pull request by atscott**
this commit updates the router reference to use standalone features.

### CODE REVIEW

**Review by MarkTechson — CHANGES_REQUESTED** [review]
Can you please update the `@reviewed` tag with the current date since you made recent updates?

**Comment by atscott** [comment]
@MarkTechson Done

**Review by twerske — APPROVED** [review]

**Review by MarkTechson — APPROVED** [review]
LGTM.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 92f478ea7d5616099b818167d4881ba98d11fd5b.

**Pull request closed without merging**
