### PR TITLE
refactor(core): improve type for EventEmitter

### PR DESCRIPTION
**Pull request by Teamop**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The return type of `EventEmitter.subscribe()` is `any`
Issue Number: N/A

## What is the new behavior?
The return type of `EventEmitter.subscribe()` is `Subscription`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Teamop** [comment]
@Toxicable maybe, but just as per the code, the return type should be just `Subscription`

**Comment by trotyl** [comment]
@Teamop There's a [goal to not have dependency on RxJS](https://github.com/angular/angular/issues/21578):

> ~~[ ] remove dependency on RxJS from the core package~~ - pushed out to v7

This change will make it harder to happen.

**Comment by thorn0** [comment]
> The goal of EventEmitter is only for @Output and should not be used in other scenarios, thus all of the operations are done in the framework itself without leaking type information to user, then Angular could change the underlying mechanism transparently.

The return type should be `void` then, not `any`.

**Comment by mhevery** [comment]
http://test/OCL:225446406:BASE:225449682:1544744711835:df5ea220

**Review by benlesh — APPROVED** [review]

**Pull request closed without merging**
