### PR TITLE
docs: improve documentation

### PR DESCRIPTION
**Pull request by A-5ingh**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by A-5ingh** [comment]
@googlebot I signed it!

**Comment by bampakoa** [comment]
Hey @A-5ingh 👋, not sure why _file_ an issue is different than _report_ 😕 I think that the former is a valid word for filing/reporting issues, bugs, and other things.

**Comment by A-5ingh** [comment]
> Hey @A-5ingh 👋, not sure why _file_ an issue is different than _report_ 😕 I think that the former is a valid word for filing/reporting issues, bugs, and other things.

Hi there @bampakoa for some reason _file_ a bug/defect/issue didn't sound right while reading the doc. Mostly have seen more usage of either _report_ or _log_ bug/defect, Ha 😃 I could be wrong too. But in my opinion, I felt _report_ sound much better than _file_. even though it is a tiny change.

**Review by beligh-hamdi — APPROVED** [review]

**Review by gkalpak — APPROVED** [review]
Thx for submitting the PR, @A-5ingh!

As @bampakoa said, both `file` and `report` work fine here. As a non-native English speaker, I also prefer `report`, so let's go with that :smiley:

**Comment by atscott** [comment]
This PR was merged into the repository by commit 35072796c2ad6db2ff99dd7ad68118f76b6b0539.

**Pull request closed without merging**
