### PR TITLE
docs: fix typo in component architecture guide

### PR DESCRIPTION
**Pull request by palerdot**
Change the sentence from 'this tells Angular how provide ...' to 'this tells Angular how to provide ...'. The current sentence does not make grammatical sense.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by palerdot** [comment]
I signed it

**Comment by brandonroberts** [comment]
Thanks for the PR @palerdot! Will you update the git commit message to `docs: fix typo in component architecture guide`? Once everything passes with CI, it will be ready to merge.

**Comment by palerdot** [comment]
@brandonroberts I have amended the [commit](https://github.com/angular/angular/pull/24832/commits/25b7d685499ac8064c3f4ab2ff8f4809dc0313a5) and changed the title to `docs: fix typo in component architecture guide`. Let me know if it looks ok.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
@palerdot LGTM. Once it passes CI it will be ready for merge.

**Pull request closed without merging**
