### PR TITLE
Added --no-standalone  to the project creation command

### PR DESCRIPTION
**Pull request by gdeardorff**
The beginning of this tutorial expects an app.module.ts file to be used, in the next steps this is removed. To start the tutorial and not get any error requires that to be added.  It is noted at the top of the page but not called out on the command that a user would copy

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by gdeardorff** [comment]
The project switches from Module based project to Standalone in the 'Display a section list' page.  Which also causes error for angular beginner.

**Comment by gdeardorff** [comment]
After working through the tutorial again, this may not be the correct change.  Other changes to the first few pages may be needed sot that the rest of the steps work

**Comment by jessicajaniuk** [comment]
@gdeardorff It looks like you're on angular.io. However our new documentation and tutorials are on angular.dev. The tour of heroes tutorial is actually no longer part of our new set of tutorials. So I'd recommend heading to the new site and using those to learn. We're likely not going to make much changes to the tour of heroes or angular.io content at this point.

**Comment by gdeardorff** [comment]
Thank you for the information.  I will switch my team to the new site.
Since the site said Beta we did not try to use it, but we will pivot.

**Comment by jessicajaniuk** [comment]
@gdeardorff Fantastic. With that, I'll close this PR for now. Thanks for the effort to improve the docs though! We appreciate it!

**Pull request closed without merging**
