### PR TITLE
build: update ngcontainer to node 10.12

### PR DESCRIPTION
**Pull request by devversion**
## PR Type
What kind of change does this PR introduce?

```
[X] Build related changes
```

## What is the current behavior?

NodeJS version is outdated and the previous NodeJS base image includes an outdated version of Firefox. 

Issue Number: N/A

## What is the new behavior?

Upgraded to NodeJS 10.12 +  This base image includes a more recent Firefox version that supports running tests in headless mode (v47 to v62.0.3)

## Does this PR introduce a breaking change?
```
[X] No
```

cc. @alexeagle

### CODE REVIEW

**Comment by alexeagle** [comment]
We want to run the same version of node that angular developers use. Do we need to force everyone on the team to switch to node 10.12?

**Comment by alexeagle** [comment]
another way to say that is: we should force developers to 10.12 if we change CI to use it

**Comment by jelbourn** [comment]
As long as there's nothing in the toolchain that breaks with 10.12 I don't see why not

**Comment by IgorMinar** [comment]
I also don't see a reason why not to upgrade. I pinged @gregmagolan and asked him to incorporate this update in his ngcontainer update that he's working on.

@gregmagolan could you also update yarn? see #26383

**Comment by jasonaden** [comment]
Note from @alexeagle: Bazel 0.18 is the only one published now, so a new ngcontainer will pick that up too. When the bazel -> master merge PR goes in, then we can do this.

I can remove the `yarn` update commit, or we can just wait on the bazel update to land, rebase, and this should pass.

**Comment by DevVersion** [comment]
@jasonaden I think the CI failures can be only fixed with a new published version of the `ngcontainer` that will be used by Circle, right?

Otherwise it will still use the old version of `ngcontainer` that doesn't match the _new_ minimum Yarn version. Also for later reference: the `10.12-browsers` image provides Yarn v1.10.1.

**Comment by DevVersion** [comment]
@alexeagle Should we still consider updating the NodeJS version of the `ngcontainer`, even though we now run Bazel through `yarn`. I suppose there are still projects using Bazel from the `ngcontainer` and would like to have the latest Firefox version w/ headless support.

**Comment by alexeagle** [comment]
I just sent a separate PR to update the version of yarn angular depends on - sorry I had forgotten about this one.
We can still update just the ngcontainer, want to change this PR to only update files under tools/ngcontainer? I'm not sure if anyone will ever use it though, so you could just close instead.

**Comment by DevVersion** [comment]
@alexeagle No worries 😄 We still use the `ngcontainer` at the moment, and I'm not sure if we are going to switch to `yarn bazel` soon. Considering that we do in the future, and it's not very urgent, I'm fine closing this.

**Pull request closed without merging**
