### PR TITLE
fix(core): improve error message for duplicate components

### LINKED ISSUE #7067: chore: improve error message when multiple components use same selector
I accidently ran into this due to copy and pasting. Forgot to change the selector of the copied component, here's the error I got:

```
EXCEPTION: Template parse errors:
More than one component: ComponentEight,ComponentNine ("

    <ul>
      <li>[ERROR ->]<cmp-eight></cmp-eight></li>
      <li><cmp-nine></cmp-nine></li>
    </ul>
"): ComponentFour@4:10
```

While this actually already gives enough information, I think we can do better with the `"More than one component"` message. Maybe we can make it sth. like `"The following components have the same selector: Cmp1, Cmp2"` ?

/cc @vsavkin

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Fixes #7067

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
Wow, clang went really crazy on https://github.com/pkozlowski-opensource/angular/blob/f5f24212dbf65943f524038a673f7e68a287f9c1/modules/%40angular/compiler/test/template_parser/template_parser_spec.ts

@mprobst is it "normal" that there are so many format changes while there was just _one_ line touched (1364 in the file before change)?

**Comment by mprobst** [comment]
I don't see any change to that file here?

**Comment by vicb** [comment]
@pkozlowski-opensource have you tried to lint before format ?

**Comment by pkozlowski-opensource** [comment]
@vicb I did

@mprobst if you look at my PR you will see that GH doesn't even display diff for `template_parser_spec.ts` as there are too many changes :-)

On my side I've changed one line, run clang and the whole file was changed.  I will give you a SHA with my original change (before running clang) so you can see on your side.

**Comment by pkozlowski-opensource** [comment]
@mprobst here is the SHA with reproduce. You can see what I mean by "excessive reformatting" by:
* cherry-picking https://github.com/pkozlowski-opensource/angular/commit/e53bcfdeb575835ac9e9480db593c536340554c5 on the current master
* running clang (`gulp lint`) 

Notice that after the above the `template_parser_spec.ts` has huge diff (almost file re-write) as in this PR while I wouldn't expect such consequences of 1-line change (longer string really).

**Pull request closed without merging**
