### PR TITLE
docs: misc fixes

### PR DESCRIPTION
**Pull request by trotyl**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by vicb** [comment]
@trotyl Thanks for your PRs. I am going to close all others, please add all the commits in this PR.

**Comment by trotyl** [comment]
@vicb Thanks for reply, I'll move them soon.

**Comment by trotyl** [comment]
@vicb Added now.

**Comment by vicb** [comment]
Thanks !
Please squash all you commits into a single one

**Comment by vicb** [comment]
@mprobst please squash and merge

**Comment by mprobst** [comment]
Merged as dd03bf12e1c035597d2fab252e393846efca5ea1.

**Pull request closed without merging**
