### PR TITLE
docs: Fix typo in Anatomy of a component

### PR DESCRIPTION
**Pull request by melroy89**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

A typo on the documentation Anatomy of a component page.

## What is the new behavior?

No typo 🥳 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thanks for this :)

**Comment by melroy89** [comment]
> Thanks for this :)

You're welcome!

**Comment by melroy89** [comment]
Actually I found another type in the components guide.. I guess it will also add it to this PR?

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit 21ac592310713fb743a7868d4e6aa6ff4db7c38c.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
