### PR TITLE
docs(aio): Reactive form validation: Fix docregions in form reactive example

### PR DESCRIPTION
**Pull request by andys8**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```
Doc region changes in example code.

**What is the current behavior?** (You can also link to an open issue here)
The displayed code in the documentation is not correct. See #16063

**What is the new behavior?**
Fixed the doc regions. 

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by andys8** [comment]
I found out, that the root cause for this issue was that there is a which shouldn't be shown in the docs. This workaround isn't even necessary for this example (it is in the others).

#### Original plnkr with workaround
https://plnkr.co/edit/n1SpISNuVedIqzsjY5Wv?p=preview

#### Modfied plnkr without workaround
https://plnkr.co/edit/uZjixP?p=preview

I will remove the workaround to simplify the code.

**Comment by andys8** [comment]
Any opinions or feedback?

**Comment by wardbell** [comment]
Sorry we took so long to look at this.

Would you please rebase it and then confirm that your request is still valid? I'll get someone to look at it after that.

**Comment by wardbell** [comment]
Ok ... Looked.  Clearing the pristine flag is critically important to a design goal on this page: a new hero should not show error messages. 

Angular added `Forms.reset()` a while back. An update was overdue. See PR #17734.

Closing yours. Thanks for the effort though.

**Pull request closed without merging**
