### PR TITLE
build(aio): less verbose boilerplate generator

### PR DESCRIPTION
**Pull request by Foxandxss**
There is a log that says "Copying example files". I opted to leave it.

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
❤️

**Comment by gkalpak** [comment]
Now we just have to get rid of these warnings :smiley::

```
** WARNING: no "/home/travis/build/angular/angular/aio/content/examples/testing/src/systemjs.config.extras.web.js" replacement for "/home/travis/build/angular/angular/aio/content/examples/testing/src/systemjs.config.extras.js".
```

**Comment by Foxandxss** [comment]
Tried, Pete asked me to leave it.

**Comment by gkalpak** [comment]
Pete asked you to not fix the warning? Why are we getting those warnings?

**Comment by Foxandxss** [comment]
https://github.com/angular/angular/pull/16687

**Comment by petebacondarwin** [comment]
Warnings are important no? If there is a warning it must mean something that we are supposed to pay attention to.

**Comment by gkalpak** [comment]
True in general. Not sure if it is true in this case.

**Comment by petebacondarwin** [comment]
If they are not really warnings that need to be actioned then they should go too

**Pull request merged**
