### PR TITLE
docs: update awade jigsaw's web site url of the resources

### PR DESCRIPTION
**Pull request by rdkmaster**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]

**Comment by rdkmaster** [comment]
Hi @kapunahelewong 

I've updated the commit message, should I need to change the title of this PR?

**Comment by kapunahelewong** [comment]
Thank you, @rdkmaster. I changed it for you. The reason it's failing now is because it just needs to be rebased. I had this same thing happen to me today. Could you [rebase](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase)? I can help you with the rebase if you need.

**Comment by rdkmaster** [comment]
Hi @kapunahelewong, @StephenFluin 

Sorry for my mistake on operationg git commands, I have to close this PR and reopen a new one.

**Comment by rdkmaster** [comment]
Hi @kapunahelewong, @StephenFluin 

Sorry for my mistake on operationg git commands, I have to close this PR and reopen a new one.

**Pull request closed without merging**
