### PR TITLE
refactor(forms): remove unnecessary Array.from

### PR DESCRIPTION
**Pull request by garrettld**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

`Map.prototype.keys` returns an iterator, so the `Array.from` is unnecessary overhead since all we're doing with it is iterating.

## What is the new behavior?
No more unnecessary array copy.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by garrettld** [comment]
I noticed this when looking at #50233, though I don't think this does anything to help with that issue.

**Review by AndrewKushnir — APPROVED** [review]
@garrettld thanks for the refactoring 👍

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:532257961:BASE:532257987:1684192277750:a379e01d).

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit efa92ab6caf61444456b38a122f8c87458be4923.

**Pull request closed without merging**
