### PR TITLE
fix(aio): fix PWA testing in cases where `atob`/`btoa` is necessary

### PR DESCRIPTION
**Pull request by gkalpak**
In some cases (unclear when), traceviewer-js, used by Lighthouse under the hood, assumes `atob`/`btoa` are defined in the global scope. This is true for browser environments, but not on node.

As a result, some aggregations that required access to model-tracing failed to produce results, dropping the overall PWA score.

This affected #16665 (e.g. commit 0de6eec).

##
This PR also includes a commit to enable logging the full PWA testing results. This will (hopefully) help diagnose errors or regressions in PWA scores.

### CODE REVIEW

**Comment by petebacondarwin** [comment]
The code looks good. We still seem to be failing the PWA tests with too low a score though...

**Comment by gkalpak** [comment]
Only the local test fails. The test against the deployed versions scores 99%. Investigating...

**Comment by gkalpak** [comment]
It's the upgrade to lighthouse@1.6.5 😞 
v1.6.3 gives 93%. v1.6.5 gives 87%

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Still needs approval from @IgorMinar

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
I'm going to cherry-pick this into #16665

**Comment by IgorMinar** [comment]
cherry-picked! thanks @gkalpak

**Pull request closed without merging**
