### PR TITLE
feat(common): introduce token for url origin

### LINKED ISSUE #19224: Support relative URLs for HTTPClient on platform server
Currently the server HTTPClient only accepts absolute URLs. It should accept relative URLs similar to the client and the server should use the current URL to figure out the absolute path.

This becomes more important as we use the URL as key to the HTTP cache that is transferred from the server to the client.

### PR DESCRIPTION
**Pull request by Toxicable**
## PR Checklist
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Feature
```

## What is the current behavior?
closes #19224
When using Universal you must provide the HttpClient with absolute urls 

## What is the new behavior?
Able to use relative urls after providing this token with your hostname
If the token is not provided nothing will change

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by trotyl** [comment]
Why not make it an interceptor like JSONP? And shouldn’t it check whether the url is already absolute?

**Comment by Toxicable** [comment]
@trotyl That's a good point about checking for existing absolute url, however it wouldn't technically be a breaking change since this is a opt-in feature, either way ill add a check.

As for Interceptor vs embedded into HttpClient - I don't really have any opinions there, either way works.

@alxhub What do you think?

**Comment by trotyl** [comment]
@Toxicable Imagine that:

+ Lib A (old) used absolute URL without using `HOSTNAME` token;
+ Lib B (new) used relative URL with the `HOSTNAME` token;

Then once lib B imported to app, the lib A functionality would be broken.

**Comment by Toxicable** [comment]
@trotyl Fixed now, nothing to worry about

**Comment by trotyl** [comment]
@Toxicable There can be absolute URL other than the user API, `indexOf` is not enough, say I just want send a request to GitHub regardless of what user sets... 😢

**Comment by trotyl** [comment]
Also, user can write `/path`, `./path`, `path`, `../parh`, etc., shouldn’t there be a normalization?

**Comment by Toxicable** [comment]
@trotyl In that case we have 2 options.
Enforce that absolute urls must include the protocol
With this we can test that the url contains `://` (more complex but that's the idea)
-or- 
Enforce that a relative url must start with `./` or `/`.
I don't see the point in normalisation here since `../` means nothing to a url, we don't use file system semantics here.
`path` would be counted as absolute since there's no way to test the diff between `www.t.com/somepath.json` and `somepath.json`

**Comment by trotyl** [comment]
> I don't see the point in normalisation here since ../ means nothing to a url, we don't use file system semantics here.

`..` is also valid URL segment, try https://github.com/angular/angular/pull/not-exist/../22280

> With this we can test that the url contains ://

Scheme-independent URL is also common, like: `//github.com/angular/angular/pull/22280`, in that case should require `APP_HOSTNAME_HREF` and reuse the scheme there, just like what in browser.

> path would be counted as absolute since there's no way to test the diff between
> www.t.com/somepath.json and somepath.json

`www.t.com/somepath.json` is also recognized as a path, rather than host + path:

image

**Comment by Toxicable** [comment]
This is the regex im thinking of using at the moment: https://regex101.com/r/nR2yL6/12/
feel free to improve on it
So it might look something like this. We'd need to handled `//` specifically
```
if(this.hostPathName && url) {
  if(!regex.test(url)) {
    url = url + this.hostPathName;
  } else if (url.startsWIth('//') {
     //fix up scheme
  }
}
```


>.. is also valid URL segment, try https://github.com/angular/angular/pull/not-exist/../22280

Ah yes, well that appears to be handled by XHR anyway, we don't need to interfere with anything past the start of the path
```
fetch('https://github.com/angular/angular/pull/not-exist/../22280')
e {_fetchPromise: Promise, _cancelRequest: ƒ}
sw.js:1 Handling fetch event for https://github.com/angular/angular/pull/22280
```

>www.t.com/somepath.json is also recognized as a path, rather than host + path

yup, that's why I think the first option is better

**Comment by Toxicable** [comment]
Well I made something that works but im not happy about it.
definitely needa use a normalisation fn but I couldn't find one thats easily accessible to HttpClient, ie without dipping into router

**Comment by CaerusKaru** [comment]
@Toxicable @trotyl check out #22282

**Comment by Toxicable** [comment]
So since Interceptors can be tree shakin for the browser, but modifying HttpClient cannot be shaken then the Interceptor approach is the best. Will update.

**Comment by thorn0** [comment]
Is this thing really called hostname?
The `hostname` property usually doesn't include port (e.g. `location.hostname`).
Isn't the schema/host/port combination called `origin`?

**Comment by Toxicable** [comment]
@thorn0 Yup, sounds right to me

**Comment by Toxicable** [comment]
I've restarted CI about 8 times now, each time it's a different flake

**Comment by Toxicable** [comment]
we're not proceeding with this method at this time

**Pull request closed without merging**
