### PR TITLE
refactor(docs-infra):  move gif to display

### LINKED ISSUE #54778: ADEV is missing illustration on `ng completion`
### Describe the problem that you experienced

ADEV: https://angular.dev/cli/completion
AIO https://angular.io/cli/completion

### PR DESCRIPTION
**Pull request by vladboisa**
To display the image correctly, swap the image from the folders

Fixes  #54778

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:  #54778

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by JeanMeche — CHANGES_REQUESTED** [review]
It doesn't fix the issue : https://ng-dev-previews-fw--pr-angular-angular-54795-adev-prev-91dyz5k0.web.app/cli/completion

The generated path for the CLI command: `/generated/images/guide/cli/completion.gif`. 

FYI I believe that the fix isn't straight foward as CLI commands docs are generated in from the AIO directory.

**Comment by JeanMeche** [comment]
It's an acceptable alternative I believe since we're planning to deprecate/remove the angular.io code base now that we have branched for v18.

**Comment by vladboisa** [comment]
> It's an acceptable alternative I believe since we're planning to deprecate/remove the angular.io code base now that we have branched for v18.

So, i can commit second solution?

**Comment by JeanMeche** [comment]
fwiw I'd keep the change you already maid but we'd would still need to disable tha AIO jobs first. It's a pending change at #54765

**Comment by JeanMeche** [comment]
We've unplugged the CI tests related to AIO and fixed the failing CI test. It should solve the CI failing on the next push. 

Could you squash your commits into a single one ?

**Comment by vladboisa** [comment]
> We've unplugged the CI tests related to AIO and fixed the failing CI test. It should solve the CI failing on the next push.
> 
> Could you squash your commits into a single one ?

Done, thank you in advance

**Review by JeanMeche — APPROVED** [review]

**Comment by JeanMeche** [comment]
caretaker: This is a doc only change, no need for more reviews.

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
This PR was merged into the repository by commit e0a31b68f5214c805d59d6ca445869a8f3250efd.

**Pull request closed without merging**
