### PR TITLE
Aio new about

### PR DESCRIPTION
**Pull request by Foxandxss**
Coming from #17442 

The images have been resized down and some of them manually tweaked so they don't look weird in the about page.

From 11mb of photos to 1mb.

Closes #17442

### CODE REVIEW

**Comment by gkalpak** [comment]
There are some [dagling links warnings][1] that seem related to this PR (not sure though).

[1]: https://travis-ci.org/angular/angular/jobs/242365524#L997

**Comment by Foxandxss** [comment]
Yes, Apparently in staging I get some non photos.

**Comment by petebacondarwin** [comment]
The CircleCI problem is because the previous version of the PR ran on CircleCI v1

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Jesus and Jules are both good for CLA.

**Pull request merged**
