### PR TITLE
[WIP] docs(aio):rewrite architecture page

### PR DESCRIPTION
**Pull request by jbogarthyde**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
First attempt to change content. Rewrote Intro and part of Modules section of Architecture page.
Please review to see if this is the direction we want to go in.
@kapunahelewong 
@dennispbrown
@hazmatdance
@jenniferfell

### CODE REVIEW

**Comment by jbogarthyde** [comment]
Trying to resolve CLA problem

**Comment by jbogarthyde** [comment]
Trying again

**Comment by jbogarthyde** [comment]
Trying again after accepting invitation to Angular for the account tied to my gmail address.

**Comment by jbogarthyde** [comment]
Trying again after accepting invitation to Angular from my other git account that is tied to my gmail address.

**Comment by jenniferfell** [comment]
Related info, in case we see this again: https://help.github.com/articles/setting-your-commit-email-address-in-git/

If you use github for more than one identity (different projects), then you need to set the email address to use for each repo separately. You can't just use one email address for all repos. That article explains how.

**Pull request closed without merging**
