### PR TITLE
docs(animations): fix grammar

### PR DESCRIPTION
**Pull request by yuwu9145**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe: Code description grammar fix

## What is the current behavior?

Issue Number: #44403

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx, @yuwu9145 :+1:

Can you please update the commit message to more closely follow our [commit message guidelines](https://github.com/angular/angular/blob/655507012b7b59c83e27429349ce3ac10608a82d/CONTRIBUTING.md#commit). For example:

> docs(animations): fix grammar 
>
> Fix grammar issues based on suggestions in issue #44403.
>
> Fixes #44403

**Comment by yuwu9145** [comment]
Hi @gkalpak , thanks for your suggestion.

Commit message has been updated and I have also signed CLA.

**Review by gkalpak — APPROVED** [review]
Thx, @yuwu9145 :+1:

Reviewed-for: global-docs-approvers

**Comment by gkalpak** [comment]
**merge-assistance:** This is a docs-only change and should not need a presubmit.

**Comment by atscott** [comment]
This PR was merged into the repository by commit 7b9169e5e10c247c7ce4b5782450fa4936ed9f1e.

**Pull request closed without merging**
