### PR TITLE
refactor(testing): limit imports of barrel-private APIs

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
While trying to produce testing UMD bundles (see #5581) I've started to look into imports of the testing barrel. Unfortunately it looks like the testing barrel has many imports from all over the code base (there are imports for core "private" APIs, animation and router barrels, DOM-related imports etc.). 

This PR cleans up some of the imports pointing to core, but this is just a tip of an iceberg....

**Comment by IgorMinar** [comment]
thanks for doing the cleanup. I agree that there is still a ton to do.

**Comment by alexeagle** [comment]
any concerns about this merging into g3? Does it affect downstream Dart users?

**Comment by IgorMinar** [comment]
@alexeagle no, it should be an internal-only change

**Comment by IgorMinar** [comment]
no public api should be affected by this

**Comment by vsavkin** [comment]
Could you fix travis and reapply the merge label?

**Comment by pkozlowski-opensource** [comment]
@vsavkin TravisCI is green again. Not sure what was going on, looked like some pb with cache on Travis.

Anyway, all green and ready to go now.

**Pull request closed without merging**
