### PR TITLE
fix: update exports to result in correct public api

### PR DESCRIPTION
**Pull request by josephperrott**

### CODE REVIEW

**Review by IgorMinar — COMMENTED** [review]
My attempt at setting the expectations: I started reviewing this but realized that now that we expose so many new symbols, we will need to rename some of them for external API naming consistency and that will take more time than just a casual review (and might require consultations with various people on the team).  I will need to review this PR again with a fresh brain, which it is not right now.

**Comment by petebacondarwin** [comment]
Needs a rebase and conflict resolution.

**Review by atscott — APPROVED** [review]
reviewed-for: fw-router

While we could make the documentation on better `Tree` and `TreeNode`, the links to them at the moment are completely broken so this is still an improvement.

**Comment by petebacondarwin** [comment]
@josephperrott is this PR still relevant?

**Comment by josephperrott** [comment]
I will go ahead and close this and I can make issues for each of the symbols that are errantly in our goldens.  I think that will end up being the best way to get traction on fixing them individually

**Pull request closed without merging**
