### PR TITLE
build: bump in-memory-web-api dependency versions

### PR DESCRIPTION
**Pull request by Tyler-V**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

Bump angular-in-memory-web-api package.json which requires a peer dependency of 15.x.x not supported by v16

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

image

```
    "dependencies": {
        "@angular/animations": "^16.0.1",
        "@angular/cdk": "^16.0.0",
        "@angular/common": "^16.0.1",
        "@angular/compiler": "^16.0.1",
        "@angular/core": "^16.0.1",
        "@angular/forms": "^16.0.1",
        "@angular/localize": "^16.0.1",
        "@angular/material": "^16.0.0",
        "@angular/platform-browser": "^16.0.1",
        "@angular/platform-browser-dynamic": "^16.0.1",
        "@angular/router": "^16.0.1",
        "angular-in-memory-web-api": "^0.15.0"
    }
```

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@Tyler-V thanks for the PR 👍 Could you please update the commit message (`git commit --amend`) to start with `refactor(core):` (this should resolve the `lint` CI issue)? Thank you.

**Comment by AndrewKushnir** [comment]
@Tyler-V FYI I've pushed a change to update the commit message, so no extra actions are required at this time. Thank you.

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit b0eff10b5345439a9b4fae0ce4078a1d4b5fee85.

**Comment by AndrewKushnir** [comment]
> Thanks, @AndrewKushnir sorry I didn't realize misc wasn't acceptable, I see that now in the contributing guidelines

No problem, thanks for your contribution! 👍

**Comment by devversion** [comment]
FYI released `0.16.0`. Thanks for the PR!

**Pull request closed without merging**
