### PR TITLE
docs: move Minko to Angular

### PR DESCRIPTION
**Pull request by mgechev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

I was part of the GDE group

## What is the new behavior?

Moved myself to the Angular team :)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
:tada:

**Comment by gkalpak** [comment]
Hm...the tests were passing (except for `integration`) one moment ago. Now they are all red :thi

**Comment by gkalpak** [comment]
Also, please, change the commit message to `docs: ...`.

**Comment by mgechev** [comment]
Done
Looks like CI is about to welcome me to the team as well 😄

**Comment by gkalpak** [comment]
:joy:
I restarted [aio_preview][1]; let's see if CircleCI will ping the preview server this time.

[1]: https://circleci.com/gh/angular/angular/115337

**Comment by gkalpak** [comment]
Nothing 🤷‍♂️

**Pull request closed without merging**
