### PR TITLE
docs(docs-infra): add new component imports documentation structure

### PR DESCRIPTION
**Pull request by ferrorenan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently the documentation does not mention that you need to declare the new component in a module, such as app.module.ts.

Issue Number: [52201](https://github.com/angular/angular/issues/52201)

## What is the new behavior?
Add new structure to document the need and how to declare the component in a module and also how to declare the component as standalone.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by MarkTechson — COMMENTED** [review]
I appreciate the intention behind this PR and what we need to consider here is that the documentation is has to be "standalone first". What that means here is that the change that we should include here are two fold:

1. A step should be added to include `standalone: true` to the component decorator in the application (before reaching the section about styles).

2. The second thing is adding some context to around what to do if you are using an `NgModule` based application and need to add a component (hence, declaring it in the module)

I totally understand that these changes are beyond the scope of the intention here so if you would rather not take on those changes, would you be willing to open an issue so we can at least track that these changes need to be made?

**Comment by ferrorenan** [comment]
@MarkTechson Hey, nice to meet you! I'll definitely work on these two steps shared by you and create the new commit soon!

Thank you very much for the feedback and see you soon!

**Comment by jessicajaniuk** [comment]
@ferrorenan I just pushed a fix to this to squash your commits and fix the broken lint.

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 098543f1d82b98f26e5acac9c19780efc0681a76.

**Pull request closed without merging**
