### PR TITLE
fix(zone.js): swallow the error when the element callback is not patchable

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
- [x] Bugfix

## What is the current behavior?
Issue Number: #42546

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JiaLiPassion — COMMENTED** [review]
@arturovt , thank you for the PR, is that possible to check the propertyDescriptor is non-configurable instead of try/catch?

**Comment by arturovt** [comment]
> @arturovt , thank you for the PR, is that possible to check the propertyDescriptor is non-configurable instead of try/catch?

Hey, unfortunately, the code that throws is this one:
```ts
else if (prototype[callback]) {
  prototype[callback] = api.wrapWithCurrentZone(prototype[callback], source);
}
```
The descriptor is `undefined` there.

**Comment by JiaLiPassion** [comment]
Got it, and is that possible to load `zone.js` before `lwc` to avoid this error?

**Comment by arturovt** [comment]
> Got it, and is that possible to load `zone.js` before `lwc` to avoid this error?

Sure. The thing is the `zone.js` is always loaded before the `lwc` (since polyfills are loaded before the main bundle). The error is thrown when the `customElements.define` is called for the first time, which is usually called within the `AppModule` constructors since developers follow the official guide (e.g. we use Lit (not directly, but some packages that expose web components) except of LWC in conjunction with `@angular/elements` in of the apps).

**Review by JiaLiPassion — APPROVED** [review]
LGTM!

**Comment by dylhunn** [comment]
It looks like this might be ready for merge @arturovt @JiaLiPassion?

**Comment by JiaLiPassion** [comment]
@dylhunn , yes, this one is ready for merge, thank you.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 4ea70e36b998208302183f78088637f3de86323d.

**Pull request closed without merging**
