### PR TITLE
build: upgrade yargs package to 13.1.0

### LINKED ISSUE #33933: Snyk Vulnerability: compiler-cli ^7.2.8 package vulnerability because of package mem
# 🐞 bug report

### Affected Package
The issue is caused by package mem which is a dependency for @angular/compiler-cli ^7.2.4

### Severity
Low - Denial of Service 

### Description
mem package is vulnerable to 

More info: https://npmjs.com/advisories/1084

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.8
Node: 10.16.3
OS: win32 x64
Angular: 7.1.0
... animations, common, compiler, core, forms, http
... language-service, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.8
@angular-devkit/build-angular      0.13.9
@angular-devkit/build-ng-packagr   0.13.8
@angular-devkit/build-optimizer    0.13.9
@angular-devkit/build-webpack      0.13.9
@angular-devkit/core               7.3.1
@angular-devkit/schematics         7.3.1
@angular/cdk                       7.3.7
@angular/cli                       7.3.8
@angular/compiler-cli              8.2.14
@angular/material                  7.3.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.9
@schematics/angular                7.3.8
@schematics/update                 0.13.8
ng-packagr                         5.0.1
rxjs                               6.3.3
typescript                         3.1.3
webpack                            4.29.0

</code></pre>

### PR DESCRIPTION
**Pull request by JoostK**
Update yargs, because the old version was transitively (via os-local)
depending on a vulnerable version of the mem package:
https://app.snyk.io/vuln/npm:mem:20180117

Fixes #33933

### CODE REVIEW

**Comment by JoostK** [comment]
This seems to suffer from https://github.com/bazelbuild/rules_nodejs/issues/818, although I'm not familiair with any of this. @josephperrott could you please have a look?

**Comment by josephperrott** [comment]
@JoostK I am not sure how the dependency was being included previously, but I feel like we had an unpinned dep that was bringing in the package.

I added in the dep manually and repinned the `karma-sauce-launcher` dep

**Comment by IgorMinar** [comment]
@JoostK this is still failing on integration/bazel-schematics/demo issues due to unpinned dependencies. I suggest you delete `integration/bazel-schematics/` since that integration test is for bazel which is in labs and we won't need to modify the bazel code ever in this branch, so it's safe to remove it.

**Comment by JoostK** [comment]
@IgorMinar thanks for the hint, that totally worked!

**Review by IgorMinar — APPROVED** [review]
lgtm. thanks for jumping over the hoops of working on an old branch.

**Comment by IgorMinar** [comment]
merge-assistance: this PR needs to be manually merged into the 7.2.x branch

**Comment by alxhub** [comment]
Merged as 9c8dda5e (and friends).

**Pull request closed without merging**
