### PR TITLE
Idiomatic TS

### PR DESCRIPTION
**Pull request by vicb**

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
LGTM if Travis is happy

**Comment by pkozlowski-opensource** [comment]
Seems like Travis in not happy :-/

**Comment by vicb** [comment]
He will end up being happy...

I like how stupid PRs like this can help spot issues sometimes.

**Comment by vicb** [comment]
Travis seems to be happier now, I'll merge when he's green.

FYI: https://github.com/angular/ts2dart/issues/204

**Comment by vicb** [comment]
& thanks for the review

**Pull request merged**
