### PR TITLE
docs: add UI Bakery to IDEs section in resources

### PR DESCRIPTION
**Pull request by Tibing**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by StephenFluin — CHANGES_REQUESTED** [review]
I think the "tooling" category better describes UI Bakery than "IDE", as to my knowledge it's not a fully development environment?

**Comment by Tibing** [comment]
@StephenFluin Thanks! I agree with you, for now, **Tooling** section suites better for UI Bakery

**Comment by AndrewKushnir** [comment]
Hi @Tibing, could you please rebase this PR on top of the latest master and squash commits into a single one? Thank you.

**Comment by Tibing** [comment]
This PR was created from the browser and now it's an orphan so I can't push in it and can't squash commits. That's why I've created a new PR and closing this one.

**Pull request closed without merging**
