### PR TITLE
build(docs-infra): upgrade cli command docs sources to 1f4b7e372

### PR DESCRIPTION
**Pull request by gkalpak**
Updating [angular#master](https://github.com/angular/angular/tree/master) from [cli-builds#master](https://github.com/angular/cli-builds/tree/master).

##
Relevant changes in [commit range](https://github.com/angular/cli-builds/compare/a517160a2...1f4b7e372):

**Modified**
- help/add.json
- help/analytics.json
- help/build.json
- help/config.json
- help/deploy.json
- help/doc.json
- help/e2e.json
- help/extract-i18n.json
- help/generate.json
- help/lint.json
- help/new.json
- help/run.json
- help/serve.json
- help/test.json
- help/update.json
- help/version.json

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

But I would like to someone who knows what to look for to review the preview version to confirm everything looks as expected.  Perhaps @alan-agius4 as he did the updates to the infra underneath.

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Comment by gkalpak** [comment]
Superceded by #45361.

**Comment by gkalpak** [comment]
Superceded by #45385.

**Comment by gkalpak** [comment]
Superceded by #45395.

**Pull request closed without merging**
