### PR TITLE
test(elements): run tests with Ivy

### PR DESCRIPTION
**Pull request by gkalpak**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] ~~Tests for the changes have been added (for bug fixes / features)~~
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

## PR Type
- [x] Build related changes
- [x] CI related changes

## What is the current behavior?
`elements` tests are not run with Ivy.

## What is the new behavior?
`elements` tests are run with Ivy.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Related to [FW-654], [FW-690], [FW-690].

[FW-654]: https://angular-team.atlassian.net/browse/FW-654
[FW-690]: https://angular-team.atlassian.net/browse/FW-690
[FW-691]: https://angular-team.atlassian.net/browse/FW-691

### CODE REVIEW

**Comment by gkalpak** [comment]
The test failures should be fixed by #27341 without requiring any code changes.

**Review by kara — APPROVED** [review]
LGTM once tests pass

**Review by mhevery — APPROVED** [review]

**Comment by gkalpak** [comment]
Added a fixup commit to fix some tests on Travis.

**Comment by gkalpak** [comment]
Note to caretaker: Requires g3sync presubmit.

**Pull request closed without merging**
