### PR TITLE
docs(docs-infra): Fix typo in documentation for standalone components

### PR DESCRIPTION
**Pull request by yommu**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
One code example looks like:
```typescript
export const ROUTES: Route[] = [
  {
    path: 'admin',
    providers: [
      AdminService,
      {provide: ADMIN_API_KEY, useValue: '12345'},
    ],
    children: [
      path: 'users', component: AdminUsersComponent,
      path: 'teams', component: AdminTeamsComponent,
    ],
  },
  // ... other application routes that don't
  //     have access to ADMIN_API_KEY or AdminService.
];
```

Issue Number: N/A

## What is the new behavior?
Above code example looks like:
```typescript
export const ROUTES: Route[] = [
  {
    path: 'admin',
    providers: [
      AdminService,
      {provide: ADMIN_API_KEY, useValue: '12345'},
    ],
    children: [
      {path: 'users', component: AdminUsersComponent},
      {path: 'teams', component: AdminTeamsComponent},
    ],
  },
  // ... other application routes that don't
  //     have access to ADMIN_API_KEY or AdminService.
];
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
@yommu thnx for the contribution! Before we can merge it, though, we would like to ask you to sign the [CLA](https://github.com/angular/angular/pull/48026#issuecomment-1311076023)

**Comment by yommu** [comment]
@pkozlowski-opensource no problem. I have signed CLA.

**Comment by pkozlowski-opensource** [comment]
caretaker note: not sure what is going on with the CI pipeline but this is just docs change

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 85d9b61f9a403b6e09dca543f4fdff9e7ea1850c.

**Pull request closed without merging**
