### PR TITLE
chore(build): fail experimental Dart build but allow Travis failures

### PR DESCRIPTION
**Pull request by yjbanov**

### CODE REVIEW

**Comment by mhevery** [comment]
I think this may break the presubmit queue. As it stands now the https://github.com/angular/angular/blob/master/scripts/ci/after-script.sh#L13 script waits for all travis build to go green. If any of them fails, the presubmit will not go through. 

Will this be a problem?

**Comment by mlaval** [comment]
It will be a problem. In fact, it is already one with the saucelabs job which can break the presubmit queue. It happened twice yesterday:
https://travis-ci.org/angular/angular/builds/76560799
https://travis-ci.org/angular/angular/builds/76550902

https://raw.githubusercontent.com/jbdeboer/travis_after_all/master/travis_after_all.py should be updated to ignore jobs where the flag "allow_failure" is true. 

Something like this: https://gist.github.com/mlaval/4db1056f316ab1e37da0 (changes are lines 45 and 84)
/cc @jbdeboer

**Comment by mhevery** [comment]
@yjbanov I have changed the presubmit to ignore builds which are merged as `allowed_to_fail`. so this should be fine.

**Comment by yjbanov** [comment]
@mhevery, awesome! Thanks. I'll go ahead and merge then,

**Comment by yjbanov** [comment]
Note: had to push manually as mary poppins didn't merge even though the build succeeded.

**Comment by mhevery** [comment]
Please manually delete the branch: https://github.com/angular/angular/tree/presubmit-yjbanov-pr-3734

It did not auto merge because of 500 https://travis-ci.org/angular/angular/jobs/77010406#L3189 from travis. Seems like travis service which returns build status is flaky.

**Pull request merged**
