### PR TITLE
docs: minor typo fix

### PR DESCRIPTION
**Pull request by YooInKeun**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

It's a very simple issue.
There is a typo in "angular/docs/PR_REVIEW.md", line 44.
The typo is "reseting".
I suggest to modify `reseting` with `resetting` .

Thank you!

Issue Number: #35419

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by YooInKeun** [comment]
@googlebot I signed it!

**Comment by santoshyadav198613** [comment]
Hi @YooInKeun,
Can you change the commit message to **docs: minor typo fix**

**Comment by YooInKeun** [comment]
@santoshyadav198613 I'm done!

**Comment by santoshyadav198613** [comment]
> @santoshyadav198613 I'm done!

Unfortunately you change the title commit message it 
image

**Comment by santoshyadav198613** [comment]
You missed entering docs: minor typo fix entering this message on the Propose File changes textbox

**Comment by YooInKeun** [comment]
I don't know what is the Propose File changes textbox...
Could you tell me which part?

**Comment by santoshyadav198613** [comment]
> I don't know what is the Propose File changes textbox...
> Could you tell me which part?

You can refer the original discussion on issue raised. I have mentioned all steps.

**Comment by ajitsinghkaler** [comment]
This is a duplicate of #35423

**Comment by gkalpak** [comment]
Indeed this issues seems to have been fixed. Thx, @YooInKeun :+1:

**Pull request closed without merging**
