### PR TITLE
docs(adev): and docs(aio) Fix typo in the word "intrinsic"

### PR DESCRIPTION
**Pull request by Cammeritz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Fix typo in the word "intrinsic"
https://angular.dev/guide/image-optimization#include-width-and-height
https://angular.io/guide/image-directive#step-5-include-height-and-width

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, do you mind rewording your commit to follow our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit) ?

**Comment by Cammeritz** [comment]
@JeanMeche should be in the correct form now

**Comment by JeanMeche** [comment]
I'm afraid you changed only changed the PR title but not the commit message.

**Comment by Cammeritz** [comment]
> I'm afraid you changed only changed the PR title but not the commit message.

Idk, maybe refresh the page?

image

This is how it looks for me now

**Comment by JeanMeche** [comment]
The commit message is visible here: https://github.com/angular/angular/pull/53249/commits

**Pull request closed without merging**
