### PR TITLE
docs: add balram chavan to GDE resources

### PR DESCRIPTION
**Pull request by ultrasonicsoft**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mgechev — APPROVED** [review]

**Review by twerske — APPROVED** [review]
LGTM and WELCOME!

**Comment by AndrewKushnir** [comment]
Hi @ultrasonicsoft, I've restarted the CI (it didn't run initially for some reasons) and there is a failing check related to the size of the avatar image:

```
Error: The following pictures exceed maximum size limit of 30kb:
  - /home/circleci/ng/aio/content/images/bios/balram_chavan.jpg
```

Could you please resize it, so that it's less than 30kb?

Thank you.

**Comment by ultrasonicsoft** [comment]
Hi @AndrewKushnir, I have reduced the image size. Can you please re-run the build? Thanks!

**Comment by AndrewKushnir** [comment]
@ultrasonicsoft thanks for the update. The CI was restarted automatically and all checks are now "green", so this PR is ready for merge.

**Comment by AndrewKushnir** [comment]
@ultrasonicsoft I've restarted the CI (not sure why that didn't happen automatically). When you get a chance, could you please merge 2 commits into one (so that there is just the first one)?

**Comment by ultrasonicsoft** [comment]
@AndrewKushnir I have squashed the commits. Let's see if it solves.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 16f504b2cfb4ad69d49a1028f115e7695b93492b.

**Pull request closed without merging**
