### PR TITLE
refactor(localize): use ngtsc's `Filesystem`

### PR DESCRIPTION
**Pull request by petebacondarwin**
A fairly straightforward, if extensive, refactoring of `@angular/localize`.

This does introduce a dependency on `@angular/compiler-cli` but since we already have a dependency on `@angular/compiler` I think we have already made our bed with that one. In the long run we might consider moving code out from `@angular/compiler` and `@angular/compiler-cli` into a shared common utility package...

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@petebacondarwin, quick question: did you create this PR and after that marked it as Draft? I see that reviewers were assigned by PullApprove (which should not happen for Draft PRs), so I was wondering if this is expected.

**Comment by petebacondarwin** [comment]
@AndrewKushnir - yes that is exactly what happened. I meant to create a draft but hit the create button too quickly!

**Review by devversion — APPROVED** [review]
LGTM for dev-infra. 

<sup>Looks like the PR needs a rebase</sup>

**Review by AndrewKushnir — APPROVED** [review]
LGTM 👍 

Reviewed for: fw-i18n, fw-testing

It looks like `ci/circleci: test` CircleCI job failure is legit (added `cleanup` label).

**Comment by petebacondarwin** [comment]
All green now. I am not sure whether this actually requires a presubmit, but since it adds to the `FileSystem` interface I guess it is touching code that is used by Google3.

**Comment by AndrewKushnir** [comment]
@petebacondarwin I've started a [presubmit](http://test/OCL:310029255:BASE:310029325:1588716385877:c993af80).

**Comment by AndrewKushnir** [comment]
FYI, g3 presubmit is successful for the changes in this PR 👍

**Review by alxhub — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:310029255:BASE:311179688:1589311855461:8edfdf11)

**Pull request closed without merging**
