### PR TITLE
first cut of the polymer js 0.8-preview binary tree benchmark

### PR DESCRIPTION
**Pull request by jakemac53**
A few notes:
- There is not yet a template if equivalent, so I hand coded that logic.
- I just copied in polymer js 0.8 since there is no package available right now that provides it, let me know if that is not acceptable.
- This isn't using any benchmark libraries right now, it just console logs the result. Let me know if there is something else you want me to use for that.
- I did not include the polyfills yet, so this will only run under chrome. Let me know if you want me to include those.

### CODE REVIEW

**Comment by tbosch** [comment]
@jakemac53 Thanks!

- Yes, please look into a way so that we don't need to add Polymer to our repo...
- Chrome only is fine.
- For benchmarking, we are using our tool benchpress. Esentially it reads out the browser performance logs, i.e. it has access to everything the DevTools have. I can do the integration, no problem.

**Comment by tbosch** [comment]
@jakemac53 Don't bother with getting the right numbers via `console.time()/console.timeEnd()` and `this.async` calls. Benchpress will take care of this automatically...

**Comment by tbosch** [comment]
Just need a version that does not require us to check in the Polymer...

**Comment by jakemac53** [comment]
Are you ok with a git dependency as opposed to an actual published package? (for polymer)

**Comment by jakemac53** [comment]
Ok, added a git dependency on polymer so its no longer in the repo

**Comment by tbosch** [comment]
Closing this in favor of a modified PR that includes your changes plus adjustments to the build: https://github.com/angular/angular/pull/943

**Pull request closed without merging**
