### PR TITLE
docs: add guide-angular.wishtack.io to education resources

### PR DESCRIPTION
**Pull request by yjaaidi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[X ] No
```

### CODE REVIEW

**Comment by yjaaidi** [comment]
I signed it!

**Comment by gkalpak** [comment]
Could you please squash the commits together and change the commit message to follow our [commit message guidelines][1]?

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by gkalpak** [comment]
Almost perfect :smiley: Actually `docs-infra` is for changes in the application itself or the tooling, not content. Can you please change it to just `docs: ...` (sorry I wasn't more clear before).

(Then @StephenFluin has to approve for content :smiley:)

**Comment by yjaaidi** [comment]
D'OH! 😱Sorry! And thank you for your quick replies.

**Review by StephenFluin — DISMISSED** [review]
The content looks great!

We're trying to standardize on English titles for foreign language content. can you tweak the title to be something like:

`The Angular Guide by Wishtack (Français)`

**Comment by yjaaidi** [comment]
Hi @StephenFluin! Thank you for your feedback 👍.
I just made the change.
Have a nice day!

**Review by gkalpak — APPROVED** [review]

**Pull request closed without merging**
