### PR TITLE
docs(aio) fix-glossary-date-pipe

### PR DESCRIPTION
**Pull request by aravindfz**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ x] Other... Please describe: Docs URL
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by aravindfz** [comment]
can some one help me out to fix The Travis CI build failed.

**Comment by gkalpak** [comment]
The failure is a flake. I restarted the job.

**Comment by aravindfz** [comment]
@gkalpak  how did you restart the task,.. Can you guide me. pls

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
@aravindfz, you need special powers (aka permissions) to restart a specific job. You can restart the whole build on your PRs by pushing a new or amended commit or by closing and re-opening the PR.
(But you usually don't need to - and you should do it sparingly as it takes up resources.)

**Comment by aravindfz** [comment]
@gkalpak  Thanks for the help.. Who should be merging this!

**Comment by gkalpak** [comment]
@aravindfz, the caretaker will take care of it 😛

**Pull request merged**
