### PR TITLE
refactor(ivy): pass host into createLView explicitly

### PR DESCRIPTION
**Pull request by mhevery**
`LView` `HOST` was set in most cases right after creating `LView`.
This makes the API cleaner by explicitly passing it ont `createLView`.

### CODE REVIEW

**Review by kara — APPROVED** [review]
LGTM

**Comment by kara** [comment]
@mhevery Linter/symbol test are complaining

**Comment by mhevery** [comment]
This seems to be unrelated flake.

**Comment by matsko** [comment]
http://test/OCL:232528737:BASE:232528942:1549396231652:2411719f

**Comment by matsko** [comment]
Up to date G3: http://test/OCL:232528737:BASE:232609318:1549427840867:89af30ce

**Pull request closed without merging**
