### PR TITLE
docs: removed outdated migration documentation

### LINKED ISSUE #46236: Migration guide unclear on steps
### Description

While googling for how to use ES2020 with Angular, I stumbled upon the below link https://angular.io/guide/migration-update-module-and-target-compiler-options

It starts by saying "This migration adjusts the target and module settings ...". Upon reading the whole document, I did not find what "this migration" meant. Is it referring to some command which needs to be run?

I searched angular repository on github for pages that refer "migration-update-module-and-target-compiler-options" to understand context, but I did not find any other docs referring to it.

### What is the affected URL?

https://angular.io/guide/migration-update-module-and-target-compiler-options

### Please provide the steps to reproduce the issue

None

### Please provide the expected behavior vs the actual behavior you encountered

_No response_

### Please provide a screenshot if possible

None

### Please provide the exception or error you saw

```true
None
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
No
```

### PR DESCRIPTION
**Pull request by phalgunv**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

closes #46236

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]
LGTM.

**Comment by alan-agius4** [comment]
@dgp1130 we can definitely drop this.

**Review by dgp1130 — APPROVED** [review]
Thanks for the confirmation @alan-agius4, and for taking the time to clean up the obsolete doc @phalgunv!

**Comment by dgp1130** [comment]
@phalgunv, we have a "caretaker" rotation that merges PRs which area ready. The `action: merge` marks this as ready to merge, so the caretaker should merge it today or tomorrow. Nothing you need to do. :D

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 385b5ec92c68e7e499d1fb883bbb41aec8a82816.

**Pull request closed without merging**
