### PR TITLE
fix(http): use `serializeBody` to support JSON payload in FetchBackend

### PR DESCRIPTION
**Pull request by leo6104**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/angular/angular/issues/50775 

## What is the new behavior?
it correctly serialize request body (same behavior with HttpXhrBackend)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
I would expect to see a test verifying code in this PR.

**Comment by leo6104** [comment]
@pkozlowski-opensource  Thanks for comment. 😊

I adds test codes in XHR / Fetch both side.

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:542018423:BASE:542018445:1687290147127:49e055a5).

**Review by AndrewKushnir — APPROVED** [review]
@leo6104 thanks for the fix 👍

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit a126cbcf22d0341377e67bcabe01ad97d44bc8b7.

**Pull request closed without merging**
