### PR TITLE
fix(upgrade): account for baseHref when calling navigateByUrl

### LINKED ISSUE #20061: Changing baseHref in Angular along with the Upgrade Module to work with AngularJS router causes infinite redirect
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If using the Angular router and the AngularJS router together with the Upgrade Module you can define routes that each router will handle and the other router will, since the route is not defined, go to its sink state and not populate the router-outlet or ng-view respectively. This works great except for if you want to host your app anywhere but root. As soon as you define a baseHref things will go haywire and you get in a (seemingly) infinite redirect between the two frameworks. _(For more information on the project set-up you can visit Victor Savkin's [tutorial](https://blog.nrwl.io/using-ngupgrade-like-a-pro-lazy-loading-angularjs-applications-469819f5c86))_.

## Expected behavior
You should be able to define a baseHref and have the two routers still play nice with each other just like they do when hosted at root.

## Minimal reproduction of the problem with instructions

Detailed steps along with some things I've tried to fix the problem are on [StackOverflow](https://stackoverflow.com/questions/46899392/changing-basehref-in-angular-along-with-the-upgrade-module-to-work-with-angularj) but to summarize:

* Clone the [repo](https://github.com/zbuhler/ngUpgradeBaseHref) _(bare bones Angular-CLI project demonstrating the issue. I would have used plunker but SystemJS appears to rely on the ```<base>``` tag which makes it so I can't demonstrate the problem)_
 * ```npm install```
 * ```ng serve```
 * Navigate to [http://localhost:4200](http://localhost:4200)
 * View it working normally by clicking back and forth on any of the links.
 * Change the .angular-cli.json file like so adding a baseHref-
```
"defaults": {
"styleExt": "css",
"component": {
},
"build": {
  "baseHref": "/"
}
```
to
```
"defaults": {
"styleExt": "css",
"component": {
},
"build": {
  "baseHref": "/sub/"
}
```
 * See it break when clicking on any of the two AngularJS links (navigate from Angular to an AngularJS page)

## What is the motivation / use case for changing the behavior?

Not everyone's app is hosted at root and you should be able to use routing along with the Upgrade Module whether it is or not.

## Environment

<pre><code>
Angular version: 4.4.6 (using CLI Project)

Browser:
- [X] Chrome (desktop) version 61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 55.0
- [X] Safari (desktop) version 11.0
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

To aid in debugging I have enableTracing: true in the app module and some console.log statements in AngularJS for the $locationChangeStart and $locationChangeSuccess events so you can see the order of events regarding navigation.

### PR DESCRIPTION
**Pull request by zbuhler**
url.pathname needs to remove baseHref otherwise it repeatedly gets added causing numerous redirects

Fixes angular/angular#20061

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently the baseHref is not being removed when syncing the URL from AngularJS to Angular.

Issue Number: [20061](https://github.com/angular/angular/issues/20061)

## What is the new behavior?
The baseHref is now removed before calling navigateByUrl which fixes navigation problems / seemingly infinite redirects.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
I know there is a commit against this issue already but I feel this is a more robust way to address the issue. This change, rather than parsing and splicing url fragments and inferring the baseHref, uses ```LocationStrategy```'s ```getBaseHref()``` and simply removes it before navigating. Seems less fragile **AND** more importantly will also work in the case where somebody manually sets ```APP_BASE_HREF```.

Another item of note is there was no spec file covering this method. I attempted to add one but get odd results when trying to call ```setupLocationSync``` from within my test. When calling ```setupLocationSync``` from within a test my assertion would not be reached whereas without the call to ```setupLocationSync``` it does.  Perhaps this is why there is no test? In any case, I am willing to add one but might need some guidance.

### CODE REVIEW

**Comment by zbuhler** [comment]
I signed it!

**Comment by zbuhler** [comment]
Added my alternate email (crossing fingers hoping it works)

**Comment by rossgardt** [comment]
Equivalent to #20244

**Comment by gkalpak** [comment]
See also https://github.com/angular/angular/pull/20244/files#r151214896.
Since #20244 was submitted first, I think it is better to go with that (as long as @jahumes is willing to move it forward).

**Comment by zbuhler** [comment]
Sounds good to me. Having reported the bug, and trying things locally in a production level app, I was concerned about it being somewhat fragile and not taking into account if somebody set ```APP_BASE_HREF``` programmatically. I also attempted to write a unit test to feel better about it in general. In retrospect, I should have just commented on the commit / pull request with the code I had written and tested. I also wasn't aware of Location#normalize() which I think probably takes it a step further than what I had tried. I will close the issue.

**Pull request closed without merging**
