### PR TITLE
refactor(core): remove useless hack

### PR DESCRIPTION
**Pull request by JeanMeche**
This hack is remnant of the Ivy migration.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Is the failing presubmit related to this change ?

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
> Is the failing presubmit related to this change ?

Nope.

**Comment by pkozlowski-opensource** [comment]
caretaker note: G3 failure is unrelated

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 4602545fe6d6a5cd13929a966ca14c4bdca526a7.

**Pull request closed without merging**
