### PR TITLE
Fix directive prefix

### PR DESCRIPTION
**Pull request by vicb**
- They should not have been applied to ng1,
- Some inline doc fix

/cc @gkalpak

### CODE REVIEW

**Comment by vicb** [comment]
Travis seem to be related to ng2, #1856 ?

**Comment by gkalpak** [comment]
Since you are at it, this also needs fixing: https://github.com/angular/angular/pull/1827/files#diff-3037c1b9244afa234b625b5475a8a16bR34 
(`ng-for-of`  -->  `of`)

**Comment by vicb** [comment]
Thanks, I'll update the PR.
And I forgot to give you credits for the updates, they originate from your comments, thanks.

**Comment by vicb** [comment]
Hum I'm actually not sure, I think it should be `ng-for-of` looking at the code

**Comment by vicb** [comment]
That's because I did update 2 lines while your comment was on l34 only, will update

**Comment by vicb** [comment]
merged into #1864

**Comment by gkalpak** [comment]
> And I forgot to give you credits for the updates, they originate from your comments, thanks.

Woohoo, more credits in my credits-bag :stuck_out_tongue: I am glad I could help.
(I wish I could help more, but ng2 is like a black box to me right now. OK, maybe not black, but _dimgray_ at best :smile:)

**Comment by vicb** [comment]
@gkalpak ng2 is moving really fast and I have the same black box feeling for some parts of the code that have evolved recently. But we will catch up with the help of this great team and a little bit of work :)

**Pull request closed without merging**
