### PR TITLE
Fix example in lazy-loading routing modules

### PR DESCRIPTION
**Pull request by iversonLv**
docs: change existing `ng generate module orders --route orders --module app.module`  
  
could not generate the below folder structure
/orders
  /orders-list
  orders-routing.module.ts
  orders.module.ts

only could generate
/orders
  orders.modules.ts

this is my project
ng g module threads --route thread-list --module app.module
CREATE src/app/threads/threads.module.ts (191 bytes)
UPDATE src/app/app.module.ts (1469 bytes)
----------------------------

ng generate module orders --routing --module app.module
/orders
 orders-routing.module.ts
 order.modules.ts 

this is my project
ng g module threads --routing --route thread-list --module app.module
CREATE src/app/threads/threads-routing.module.ts (250 bytes)
CREATE src/app/threads/threads.module.ts (283 bytes)
UPDATE src/app/app.module.ts (1469 bytes)

ng generate component ./orders/order-list --module ./orders/orders.module
/orders
  /orders-list
 orders-routing.module.ts
 order.modules.ts 

this is my project
ng g c ./threads/test --module ./threads/threads.module
CREATE src/app/threads/test/test.component.html (23 bytes)
CREATE src/app/threads/test/test.component.spec.ts (614 bytes)
CREATE src/app/threads/test/test.component.ts (262 bytes)
CREATE src/app/threads/test/test.component.scss (0 bytes)
UPDATE src/app/threads/threads.module.ts (447 bytes)

Please correct me if I am wrong.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by iversonLv** [comment]
@googlebot I signed it!

**Comment by jbogarthyde** [comment]
I don't think this is quite right -- we need to connect the `foo-list` component to the `foo-list` route name. @AndrewKushnir, can you clarify this issue?

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Hi @iversonLv, thanks for your contribution but the change made is not quite right,

You don't need to use `ng generate component` to generate a lazy loaded route. 

I am thinking that you might be using an older version of the Angular CLI. Kindly note that this version of the docs is for Angular 8+. For previous versions to need to use the version number sub domain example: 
https://v7.angular.io/guide/lazy-loading-ngmodules

Can you kindly provide which version of the Angular CLI are you using?

**Comment by iversonLv** [comment]
@alan-agius4 
Ah, thanks for responsing.
Yes, my bad, my side is Angular CLI: 7.3.1 rather than 8

**Pull request closed without merging**
