### PR TITLE
fix(router): restore 'history.state' (#28108)

### LINKED ISSUE #28108: 'history.state' object is getting lost when navigate using back/forward buttons
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router....

### Is this a regression?

 No

### Description

I think there is a small bug - the `history.state` object is getting lost when navigate using back/forward buttons.
The fix should be pretty simple- set the restored state into the `NavigationExtras`  parameter in the call of `scheduleNavigation` in `Router.setUpLocationChangeListener()` method :

```javascript
        // Navigations coming from Angular router have a navigationId state property. When this
        // exists, restore the state.
        const state = change.state && change.state.navigationId ? change.state : null;
     setTimeout(
            () => { this.scheduleNavigation(rawUrlTree, source, state, {replaceUrl: true, state }); }, 0);
```

## 🔬 Minimal Reproduction

[https://stackblitz.com/edit/angular-bupuzn](https://stackblitz.com/edit/angular-bupuzn) created by @fjauer - just use back/forward after pressing Test button

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.1
Node: 10.15.0
OS: win32 x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.1
@angular-devkit/build-angular     0.12.1
@angular-devkit/build-optimizer   0.12.1
@angular-devkit/build-webpack     0.12.1
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.1
@angular/cdk                      7.2.1
@angular/cli                      7.2.1
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.2.1
@ngtools/webpack                  7.2.1
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.0.0
typescript                        3.2.2
webpack                           4.23.1

</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by alecvolo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:  #28108

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by Airblader** [comment]
Just want to point out that I would like to discuss this change first, see https://github.com/angular/angular/issues/28108#issuecomment-460005717

**Comment by atscott** [comment]
This seems like the correct fix. I've rebased the PR and started kicked off the internal tests.

**Comment by atscott** [comment]
@googlebot I consent.

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
caretaker note: as this is a router change, please merge and sync to g3 on its own for easy rollback if it breaks things.

**Review by atscott — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@atscott it looks like a couple CircleCI jobs are failing. Could you please have a look when you get a chance? Thank you.

**Comment by atscott** [comment]
Hey @josephperrott, I'm not familiar with the `integration:side-effects_test`. Can you advise how to proceed here? I'm guessing it has something to do with the object destructuring done in the change.

**Comment by josephperrott** [comment]
@atscott Yes, the destructuring causes tslib to have to be loaded to use router, making it a "side effect" of the usage.

If we are okay with adding this side effect to @angular/router, then `//integration/side-effects/snapshots/router/esm2015.js` needs to be updated to reflect `tslib` needs to load.  If we would not like for `tslib` to be a side effect, then the code needs to be refactored to no longer rely on the destructuring.

**Comment by atscott** [comment]
[global presubmit](https://test.corp.google.com/ui#id=OCL:325298328:BASE:325836076:1597086613516:a56701b7)

**Pull request closed without merging**
