### PR TITLE
fix(security): html5 filesystem url

### PR DESCRIPTION
**Pull request by Prepd-Root**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
```

**What is the current behavior?** (You can also link to an open issue here)
Sanitize fails for urls like : "filesystem://" 

**What is the new behavior?**
Sanitize will allow urls that start like "filesystem://"

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Allow "filesystem://" as a safe url pattern for html5 filesystem feature

### CODE REVIEW

**Comment by Prepd-Root** [comment]
I signed it!

**Comment by mprobst** [comment]
@rjamet can you take a look?

**Comment by rjamet** [comment]
Some colleagues discussed that before internally (2014, some of it might be out of date), and there's an issue with attack persistence. `filesystem://` created on an origin A are run in origin A. That's an issue when there's XSS on a page: if I attack A.com, I can use an XSS to put a backdoor on `filesystem://A.com/backdoor.html`, keeping a new XSS open even if the first one is closed, assuming I can trick the users to go visit that page.

The important part: the `filesystem://` also can't be navigated to from a different origin. So if the attacker can't inject links to that `filesystem://` on your origin, he has no way to push users to this backdoor URL other than phishing, and this whole persistence issue is completely mitigated. That's something Closure chose to keep, and Angular might want this too, even though it goes a bit beyond the URL type contract.

Finally, that's from 3-year-old informations: if something doesn't sound right, I can verify whether things are still the same.

**Comment by mprobst** [comment]
@rjamet so what's the recommendation, rather leave it out and have users whitelist explicitly?

**Comment by rjamet** [comment]
yup, some sort of per-call explicit whitelisting sounds like the best option, either filter or a filesystem URL service to build these. It's not a big risk, but since it has no value for most users, the best tradeoff seems to be leaving it off by default, and letting users of the API actively enable it.

**Comment by splincode** [comment]
What is the status of the task?

**Comment by alexeagle** [comment]
Closing pull requests from 2016, sorry this got stale and was never merged. Please open a new one if you still care about this change.

**Pull request closed without merging**
