### PR TITLE
refactor(migrations): support parallel tsurge metadata merging

### PR DESCRIPTION
**Pull request by devversion**
This is helpful and important for large scale migrations where a single
call for merging _all_ unit data's can be subject to memory / disk
resource constraints. Consider a compilation unit data for every target
in Google3, and those being merged in a single program.

### CODE REVIEW

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
LGTM but will require cleanup (G3 presubmit is failing)

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by devversion** [comment]
Caretaker note: Please include https://critique.corp.google.com/cl/688512995 into your sync.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit cb34e406baf2c8ede5d49054e7cea8ddb4d601f9.

The changes were merged into the following branches: main

**Comment by AndrewKushnir** [comment]
FYI, reopening this PR, since it was reverter via https://github.com/angular/angular/pull/58313.

**Comment by devversion** [comment]
Caretaker note: Please include https://critique.corp.google.com/cl/688512995 into your sync.

**Pull request closed without merging**
