### PR TITLE
refactor(compiler): some small compiler refactorings

### PR DESCRIPTION
**Pull request by petebacondarwin**
These commits were extracted from the reverted #42062 PR since they do not change any behaviour.
This PR let's us land those commits now, and will make the reworking of #42062 simpler.

### CODE REVIEW

**Review by JoostK — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:390500787:BASE:390500807:1628815463427:2ed2e885).

**Comment by AndrewKushnir** [comment]
[Global Presubmit](https://test.corp.google.com/OCL:390500787:BASE:390973635:1629093720780:ad9a14f).

**Comment by AndrewKushnir** [comment]
@petebacondarwin FYI presubmits went well + I also verified that there are no changes in the extracted message IDs for the app that was affected previously by #42062.

**Comment by AndrewKushnir** [comment]
Note to Caretaker: since this is a part of the PR that was reverted earlier (due to g3 issues), please sync this PR into g3 as a separate change to minimize the risks and simplify the rollback if needed.

**Pull request closed without merging**
