### PR TITLE
docs: fixed unexpected closing tags for Receipt

### PR DESCRIPTION
**Pull request by aramirezj**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The closing tag is not the correct one so it throws an error.

Issue Number: [52911](https://github.com/angular/angular/issues/52911)

## What is the new behavior?

Now the closing tags its what was expected and does not break.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ X] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM!

**Comment by jessicajaniuk** [comment]
@aramirezj Thanks for the contribution! Can you fix your commit message to match lint requirements? You should be able to just change `fix(adev): ...` to `docs: ...`.

**Comment by aramirezj** [comment]
> @aramirezj Thanks for the contribution! Can you fix your commit message to match lint requirements? You should be able to just change `fix(adev): ...` to `docs: ...`.

There you go! My first PR, sorry about that hehe

**Comment by jessicajaniuk** [comment]
@aramirezj Thank you!

**Comment by jessicajaniuk** [comment]
Caretaker note: this is safe to merge and does not need any more reviews.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit f8d5b8464ba021d49d54a1cb49b8914336d9fb8e.

**Pull request closed without merging**
