### PR TITLE
docs: fix dynamic component loader example

### PR DESCRIPTION
**Pull request by kapunahelewong**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #21903 #22371 #22020

## What is the new behavior?

Example works and copy in the doc is updated.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by alxhub — APPROVED** [review]

**Comment by ssilvert** [comment]
I tried this change and it still appears broken with AdBlock on Firefox.  I no longer get an error in the console, but the app now just shows a blank screen.  Works fine if I pause AdBlock.

**Comment by kapunahelewong** [comment]
@ssilvert thanks for checking. I'll add a note about needing to disable AdBlock and similar extensions.

**Comment by ssilvert** [comment]
BTW, this is REALLY important to us as I'm considering dynamic component loading as a major part of our architecture.  We can't just tell everyone to turn off Ad Blockers.

**Comment by kapunahelewong** [comment]
Ah, thanks for the context, @ssilvert. Would you be so kind as to file an issue with the concern about telling people to turn off AdBlockers? We should have a thread of conversation specifically for that and having it in its own issue will help us single that point out. Please tag me in it so I can help look out for your concern. 

We still want to get this PR's change in since the example needs refactoring due to the `ExpressionChangedAfterItHasBeenCheckedError`.

**Comment by ssilvert** [comment]
OK.  There is already on open issue that led to this.  I can just add to that.  The thing is, this PR seems to avoid the ExpressionChangedAfterItHasBeenCheckedError, but it doesn't actually fix the problem.

I suspect that this is a general problem with dynamic component loading rather than just a problem with the example.  But I hope I'm wrong.

**Comment by mlc-mlapis** [comment]
@ssilvert ... there is important to answer also what `AdBlock` is doing ... how it works because it is principal for understanding what affects the behavior in fact.

**Comment by ssilvert** [comment]
I agree.  That's outside my area of expertise.  Wish I could help with that.

**Comment by kapunahelewong** [comment]
Thanks @mlc-mlapis. @ssilvert I think AdBlock is specifically looking for the word "ad" and any thinkable combination with it. They use [EasyList](https://easylist.to/easylist/easylist.txt). It's not my area of expertise either, but I think that's what's happening. At some point, maybe we could try the example with the wording changed as an experiment, though that might be time consuming - probably something for a rewrite of that guide, which is a bigger undertaking.

**Comment by kapunahelewong** [comment]
@jenniferfell fyi ^^ 

@ssilvert has legitimate concerns about AdBlock and the Dynamic Component Loader example. We should put our heads together on it and see what we can do. (@ssilvert she and I were _just_ discussing this the other day).

**Comment by ssilvert** [comment]
@kapunahelewong You were right!!!  I did a global change of everything from "ad" to "foo" and from "Ad" to "Foo".  Now it works.  Made my day.

**Comment by kapunahelewong** [comment]
@ssilvert Yay!!!! I'm so happy! Ok great, this confirms what we need to do then. Thank you very much!

**Comment by kapunahelewong** [comment]
fyi @jenniferfell The above conversation shows what needs to be done in Dynamic Component Loader regarding AdBlock.

**Pull request closed without merging**
