### PR TITLE
test(ivy): update TNode counts to reflect changes in #24113

### PR DESCRIPTION
**Pull request by vicb**
This PR is a fix for master being red (due to a conflicting merge of the pending IVY PRs)

### CODE REVIEW

**Review by kara — APPROVED** [review]
LGTM

**Comment by JoostK** [comment]
Ah I was confused already :)

**Comment by vicb** [comment]
Sorry @JoostK but a lot of PR have been merged today causing some (minor) breakages on master. We need a couple of hours to get back to normal.

**Comment by JoostK** [comment]
@vicb No problem! I'm actually very pleased with what is going on today 👍

**Pull request closed without merging**
