### PR TITLE
docs(aio): fix card inconsistency

### PR DESCRIPTION
**Pull request by joejordanbrown**
The cards had inconsistent container elements.

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Good catch, @joejordanbrown 👍 
Can you please change the commit message to `docs(aio): ...` (so that it follows our [commit message guidelines][1])?

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by joejordanbrown** [comment]
@gkalpak  

Thanks, sorry about that, I missed the scope section on the guidelines. I've changed the commit message to the correct format.

**Comment by gkalpak** [comment]
@joejordanbrown, I still see the old commit message. Have you force-pushed to your branch? (That would update the PR.)

**Comment by joejordanbrown** [comment]
@gkalpak corrected the mistake, thanks.

**Pull request closed without merging**
