### PR TITLE
docs(Http): add docs about breaking changes with EventEmitter/Observable

### PR DESCRIPTION
**Pull request by jeffbcross**

### CODE REVIEW

**Comment by jeffbcross** [comment]
@IgorMinar mind taking a look? I will publicize the change once it lands.

**Comment by IgorMinar** [comment]
lgtm. if this change was released already it should be in the changelog.md as well.

**Comment by jeffbcross** [comment]
Hasn't been released yet, I will add a breaking change message to this commit.

**Comment by jeffbcross** [comment]
Merged 34eaf65a79b2f43eccff8e88fb3b799d5e0906a0

**Pull request closed without merging**
