### PR TITLE
feat(core): make static query flag optional

### PR DESCRIPTION
**Pull request by crisbeto**
Switches back to having the `static` flag be optional on `ViewChild` and `ContentChild` queries, in preparation for changing its default value.

### CODE REVIEW

**Comment by kara** [comment]
Note: blocked on switching the default (must do in this order for Google3)

**Review by kara — APPROVED** [review]
LGTM

**Review by IgorMinar — APPROVED** [review]
lgtm

**Comment by atscott** [comment]
[Presubmit](https://test.corp.google.com/ui#id=OCL:272293309:BASE:272293468:1569964936457:685fc249)
[Ivy Presubmit](https://test.corp.google.com/ui#id=OCL:272293309:BASE:272293685:1569964995875:892bd941)

**Comment by atscott** [comment]
Note: This didn't get merged but was closed because I needed to rebase to get CI to run correctly. The rebase clobbered the changes. Probably something to do with this PR being committed and then reverted.

**Pull request closed without merging**
