### PR TITLE
feat(diffing-broccoli-plugin): use optional fast-path for initial builds

### PR DESCRIPTION
**Pull request by caitp**
Enable plugins to use a fast path for the initial build, which does not
require calculating a diff. Useful for plugins like Funnel or MergeTrees.

Blocked on #1961

### CODE REVIEW

**Comment by caitp** [comment]
Adding tests for the diffing plugin wrapper is problematic without support for class expressions and non-global class declarations (https://github.com/Microsoft/TypeScript/issues/497)

**Comment by IgorMinar** [comment]
I don't think that we can do it like this because of several reasons:
- in your change you didn't prime the tree-differ's figerprint cache, so the next time we run partial build, we'll actually report that everything changed which means that the second build will be slow
- since all plugins I can think of need to do the first traversal anyway (or shouldn't be diffing plugins at all), it's pretty useful to get the filtered list of paths even for the first build

Given this, it doesn't seem very useful to have plugins implement this special api. What might be useful, is to pass "firstBuild" info into the rebuild function. 

Take a look at #1906. I'm trying to implement the same thing there, but rather than changing what diffing plugins look like, I'm keeping track of whether a rebuild is first or not within the typescript plugin.

**Comment by caitp** [comment]
yeah, I was thinking that earlier --- but I'm a bit worried about typescript flipping out if implementors of the diffing plugin interface don't take both the firstBuild flag and the treeDiff --- seems inconvenient for classes that don't need it. Not that big of a deal, but sort of a pain.

Lets figure out how we want to do that, because in my tests, it makes the initial build significantly longer (like 17 seconds), and that's kind of a pain

**Comment by IgorMinar** [comment]
it seems that the tree-diffing commit from the PR was already merged, but now that all input trees are stable (#2051) we don't actually need this because broken symlinks indicate a bug in a plugin or build system.

the second commit is not needed, so I'm going to close this PR.

**Pull request closed without merging**
