### PR TITLE
docs: update the webWorker command

### PR DESCRIPTION
**Pull request by santoshyadavdev**
Fixes 30554

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #30554

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by filipesilva — CHANGES_REQUESTED** [review]
Heya @santoshyadav198613, thanks for looking into this! The command should work with both `webWorker` and `web-worker`. Are you seeing behaving differently?

**Comment by santoshyadav198613** [comment]
Ohh actually CLI doc only mentions webWorker, may be we should update the CLI doc. 

Also found another issue which raised in CLI.

**Comment by filipesilva** [comment]
Can you point me to that CLI doc please?

**Comment by santoshyadav198613** [comment]
https://next.angular.io/cli/generate#webWorker-command

**Comment by santoshyadav198613** [comment]
https://github.com/angular/angular-cli/issues/14467 the issue is raised in CLI, also raised a PR let me know if it is correct.

**Comment by filipesilva** [comment]
Perhaps I am mistaken and the preferred syntax is camelCase. @jenniferfell can you chime in?

**Comment by alan-agius4** [comment]
Hi, so indeed the CLI accepts multiple casings for arguments and options, as it’s explained here: https://next.angular.io/cli#cli-command-language-syntax

Though I agree there is a bit of inconsistency in the docs, as in the CLI guide camel-cases are used, but in other parts of the docs kebab-cases are typically used.

Ideally we should stick to one. Let’s wait for @jenniferfell to confirm.

**Comment by santoshyadav198613** [comment]
Yes you guys are correct it is alias name, but it is confusing.
https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/collection.json#L105

**Comment by santoshyadav198613** [comment]
Hi Everyone,
Should we keep alias names to "w" and "worker", as we follow same pattern for component and service.

@filipesilva , any thoughts. @jenniferfell can you confirm.

**Comment by filipesilva** [comment]
@santoshyadav198613 I don't think `worker` would be a good alias because there are both `service-worker` and `web-worker` generators. 

I haven't a big opinion about `w` as an alias. I'd prefer `ww` instead as it leaves room for `sw` for `service-worker`. But neither are super common so it is fine that they don't have aliases.

**Comment by santoshyadav198613** [comment]
> mmon so it is fine that they don't have aliases.

so should we remove the existing alias
 "aliases": ["web-worker", "worker"],

**Comment by filipesilva** [comment]
Oh is `worker` there already with an alias? I think it should stay then, if it's there someone already thought about it outside this PR.

**Comment by filipesilva** [comment]
@mgechev was also looking at this and thinks the `worker` alias should be removed, it should be done before version 8 final in https://github.com/angular/angular-cli/pull/14526.

**Comment by santoshyadav198613** [comment]
Thanks, guys closing this PR and issue.

**Pull request closed without merging**
