### PR TITLE
style(lint): new tslint rule to enforce privates to start with _

### PR DESCRIPTION
**Pull request by gilamran**
As a convention from AtScript, private functions and members must start with _ (underscore). A new tslint rule was created to enforce that. All the places that broke this new rule were also fixed (Added underscore).

### CODE REVIEW

**Comment by alexeagle** [comment]
The code change LGTM, just checking with Victor that he agrees this is a correct thing to do.

**Comment by vsavkin** [comment]
@gilamran could you rebase this PR?

**Comment by Foxandxss** [comment]
This is nice. I might shamefully steal it for ng-bootstrap. We are using lots of ng2 conventions and this is one of them.

**Comment by naomiblack** [comment]
looks like this just needs a rebase.

**Comment by vikerman** [comment]
@gilamran - Hi can you rebase this PR?

**Comment by mhevery** [comment]
This PR is stale (does not rebase; pass CI; had no activity for a while). It is probably our fault, and we are sorry. In an effort to keep our PR queue under control, and prevent us from taking too long to get back to you we are cleaning up the queue. Unfortunately this means that this PR is getting closed.

If you would like to resurrect this change, please rebase on master, make the tests pass and create a new PR.

**Pull request closed without merging**
