### PR TITLE
build(docs-infra): upgrade cli command docs sources to 71e72ecdb

### PR DESCRIPTION
**Pull request by gkalpak**
Updating [angular#master](https://github.com/angular/angular/tree/master) from [cli-builds#master](https://github.com/angular/cli-builds/tree/master).
Relevant changes in [commit range](https://github.com/angular/cli-builds/compare/02d2ec250...71e72ecdb):

**Modified**
- help/generate.json
- help/new.json

### CODE REVIEW

**Review by jenbuzz — COMMENTED** [review]
It seems a little strange to always have to update this hash. Would it not make sense to change extract-cli-commands.js so that it can get the latest hash itself? Call extract-cli-commands.js with "latest" argument and then it would lookup the latest hash in cli-builds use that.

**Comment by IgorMinar** [comment]
We want to know what version we are updating to. And we want to run ci at
that version. Otherwise it's an unpinned dep, similar to npm without the
lock file.

**Comment by IgorMinar** [comment]
George/Pete ci failed with "no space left on the device" have we've seen
this before?

**Comment by petebacondarwin** [comment]
@IgorMinar see https://github.com/angular/angular/issues/28105

**Review by petebacondarwin — APPROVED** [review]

**Pull request closed without merging**
