### PR TITLE
[6.1.x] update angular.io to the new ServiceWorker

### PR DESCRIPTION
**Pull request by gkalpak**
This essentially backports #19795 to 6.1.x.
(Related: Jira FW-289)

### CODE REVIEW

**Comment by gkalpak** [comment]
Rebased on master and backported #25999.

**Comment by gkalpak** [comment]
This should be updated to incorporate #26042 once that is released.

**Comment by gkalpak** [comment]
Backported #26145 into this PR.
This is now failing, because #26136 hasn't be backported to patch 😕

**Review by IgorMinar — APPROVED** [review]

**Comment by gkalpak** [comment]
This seems to [have been merged][1]. Closing...

[1]: https://github.com/angular/angular/commits/d815e4137f8c7d504ebadda315fddc7ffb895b1a

**Pull request closed without merging**
