### PR TITLE
docs: fix non-relative links.

### PR DESCRIPTION
**Pull request by JeanMeche**
Relative links have 2 advantages :
* They're not marked as external links
* When on a specific doc version, the link point to the same version.

## PR Type
What kind of change does this PR introduce?

- [x] Documentation content changes

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
Caretaker: This is docs only and safe to merge without additional reviews.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit a6b99254e1c7179a03ecaf94f331b6bf8f713dcc.

**Comment by pkozlowski-opensource** [comment]
@JeanMeche @jessicajaniuk re-targeted this one at RC since it didn't merge cleanly into 15.2.x. Not sure if it makes sense to also patch 15.2.x at this point.

**Pull request closed without merging**
