### PR TITLE
Refactor router recognition and redirects

### LINKED ISSUE #4170: Router RFC: `redirectTo` should use the link DSL rather than a URL fragment
Currently, `redirectTo` in a Redirect route takes a string representing the remaining (unmatched) URL that should be recognized.

```
@RouteConfig([
  { path: '/', redirectTo: '/bar' }, // is "/bar" relative, or absolute?
  // ...
])
class MyClass {}
```

This makes it hard to tell whether the redirection is local, or absolute.

Instead, I propose that we use the route link DSL (same as what the RouterLink directive uses):

```
@RouteConfig([
  { path: '/', redirectTo: ['/bar'] }, // aha! bar is absolute
  // or... { path: '/', redirectTo: ['./bar'] }, // aha! bar is relative
  // ...
])
class MyClass {}
```

Related to #4133, #4166, and https://github.com/angular/angular/issues/3751#issuecomment-136520533

### LINKED ISSUE #4490: Router's navigate() throws exception for component has no route config (in Alpha 38)
Just tried alpha 38 … found a few minor things, but this one is confusing on the router. We can now use `navigate` or `navigateByUrl`/ The latter accepts a string (the old style) and works. The former accepts a tuple, and tosses an error at me.

```
  // this works
  this._router.navigateByUrl(`detail/${this.selectedHero.id}`);

  // this does not work
  this._router.navigate([`./${Routes.detail.as}`, {id: this.selectedHero.id}]);
```

The error is `ORIGINAL EXCEPTION: Component "HeroesComponent" has no route config.`

See example here

https://github.com/johnpapa/angular2-tour-of-heroes/blob/master/src/app/heroes.component.ts#L38-L39

cc/ @btford:

### LINKED ISSUE #4694: Auxiliary routes can be targeted via the url, not via a router-link
The auxiliary routing example (in the test code) navigates to the view with an auxiliary routing via the url. As far I can see, there does not seem to be a way to navigate to such a view using a router-link  (from looking at the source code). Maybe this is on purpose, but we are left guessing how to use this feature, see also #4693.

### LINKED ISSUE #5200: Router: link to child component should go to default child route if no child route name
In many cases, the `Parent` component will display links to the child components. The parent doesn't know about the child's own routes and shouldn't have to know *in this scenario*.

For example, suppose that we have a "Hero Employment Agency" that matches hero employees to crises.

The `AppComponent` is the parent and it is a shell with links across the top to go to child "feature" components, `CrisisCenterComponent` and `HeroesComponent`, each dealing with its own concern (managing crises, managing heroes), each with its own rats-nest of sub-components and routes.

Assume
```
@Component({
  selector:'my-app',
  template:  `
    <h1 class="title">Hero Employment Agency</h1>
    <a [router-link]="[...]" >Crisis Center</a>
    <a [router-link]="[...]" >Heroes</a>
    <router-outlet></router-outlet>
  `,
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
  {path: '/crisis-center/...', as: 'CrisisCenter', component: CrisisCenterComponent},
  {path: '/heroes/...',  as: 'Heroes', component: HeroesComponent}
]))
export class AppComponent { ... }
```

And 
```
@Component({ ... })
@RouteConfig([
  {path:'/',    as: 'CrisisCenter', component: CrisisListComponent},
  {path:'/:id', as: 'CrisisDetail', component: CrisisDetailComponent}
])
export class CrisisCenterComponent { }
```

And
```
@Component({ ... })
@RouteConfig([
  {path:'/',    as: 'Heroes', component: HeroListComponent},
  {path:'/:id', as: 'HeroDetail', component: HeroDetailComponent}
])
export class HeroesComponent { }
```

Right now, the `AppComponent` template's link bar has to look something like this:
```
<a [router-link]="['CrisisCenter', 'CrisisCenter']" >Crisis Center</a>
<a [router-link]="['Heroes', 'Heroes']" >Heroes</a>
```

That's silly. Worse, it obliges the `AppComponent` to know about at least one of the route names for each child feature.

I'd rather it be:
```
<a [router-link]="['CrisisCenter']" >Crisis Center</a>
<a [router-link]="['Heroes']" >Heroes</a>
```

At present, this raises a complaint about a non-terminal route. But what if the child component had a default route? Then the router would know how to keep working it's way toward a terminal route.

I can think of ways to identify a default route:

1. A "default" property (only one allowed per configuration)
1. A child route with the path `\`

The other constraint would be that a default route cannot have a parameters object ... because there would be no way to specify it. We could live with that.

# Corollary

The `{path: '/crisis-center/...', ` syntax seems unnecessary if the target component has configured routes, one of which is the default.

I don't think this is a big deal. But if we could omit it, then `AppComponent` would never have to know that `CrisisCenterComponent` has its own routes.

That seems like a win to me.

### PR DESCRIPTION
**Pull request by btford**
This has a little bit more cleanup work, but I'd like @matsko to start reviewing the code ASAP so we can finally land this. :cat2: 

---

This is a big change. @matsko also deserves much of the credit for the implementation.

Previously, `ComponentInstruction`s held all the state for async components.
Now, we introduce several subclasses for `Instruction` to describe each type of navigation.

BREAKING CHANGE:

Redirects now use the Link DSL syntax. Before:

```
@RouteConfig([
  { path: '/foo', redirectTo: '/bar' },
  { path: '/bar', component: BarCmp }
])
```

After:

```
@RouteConfig([
  { path: '/foo', redirectTo: ['Bar'] },
  { path: '/bar', component: BarCmp, name: 'Bar' }
])
```

BREAKING CHANGE:

This also introduces `useAsDefault` in the RouteConfig, which makes cases like lazy-loading
and encapsulating large routes with sub-routes easier.

Previously, you could use `redirectTo` like this to expand a URL like `/tab` to `/tab/posts`:

@RouteConfig([
  { path: '/tab', redirectTo: '/tab/users' }
  { path: '/tab', component: TabsCmp, name: 'Tab' }
])
AppCmp { ... }

Now the recommended way to handle this is case is to use `useAsDefault` like so:

```
@RouteConfig([
  { path: '/tab', component: TabsCmp, name: 'Tab' }
])
AppCmp { ... }

@RouteConfig([
  { path: '/posts', component: PostsCmp, useAsDefault: true, name: 'Posts' },
  { path: '/users', component: UsersCmp, name: 'Users' }
])
TabsCmp { ... }
```

In the above example, you can write just `['/Tab']` and the route `Posts` is automatically selected as a child route.

Closes #4170
Closes #4490
Closes #4694
Closes #5200

### CODE REVIEW

**Comment by ericmartinezr** [comment]
With the new `useAsDefault` can we default to a child route?
```typescript
// Parent...
{ path : '/index/...', component: Child}
// Child
{ path : 'default', useAsDefault : true}
```
And then when I enter to `myproject/#/index` it uses `/index/default`

**Comment by btford** [comment]
I think "routes with an empty component" is a separate (but reasonable) concern. Right now you can easily construct a component with blank template and reference it where you need. @tandu could you file an issue describing this?

**Comment by tandu** [comment]
Here are other issues related to router
https://github.com/angular/angular/issues/5359
https://github.com/angular/angular/issues/5345

**Comment by btford** [comment]
Great! Thanks for the write-up, @tandu.

**Comment by LMFinney** [comment]
@btford Would it be possible to have a version in which I could programmatically decide what to do when the child route is left off?

In our app, we have a tabbed interface that I want to correspond to child routes. However, the contents of the tabs depend on the data I've loaded with these possibilities:
```
ID
AST 1
AST 1, ID
AST Summary, AST 1, AST 2
AST Summary, AST 1, AST 2, ID
```

I would like to have a child route for the selected tab to be able to specify via URL which tab is selected, but I also want the first tab to be selected by default if none is specified in the URL. In all the examples I've seen, I need to declare in code which one is to be used as default, but in my case any of three different tabs could be the one to use depending on the data.

Is this problem solvable through AsyncRoutes combined with Child Routes somehow?

**Comment by btford** [comment]
@matsko LGTM'd this

**Pull request closed without merging**
