### PR TITLE
docs(changelog): update marketing resources with Angular UI Toolkit

### PR DESCRIPTION
**Pull request by jnsencha**
https://www.angular-ui-tools.com

Thanks in advance,

Jordan

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]
The content looks fine, but you'll need to fix the commit message

**Comment by jnsencha** [comment]
Thanks @StephenFluin I will amend the commit message per the guidelines and sign the CLA

**Comment by jnsencha** [comment]
@googlebot I signed it!

**Review by kapilepatel — APPROVED** [review]

**Comment by jnsencha** [comment]
@StephenFluin and @kapilepatel thank you for approval. My apologies for not resolving the commit message amendment earlier. I do see the failing test checks - but I don't believe they are related. Please confirm if there is anything else I need to do for the PR.

**Comment by jnsencha** [comment]
@StephenFluin and @kapilepatel please let me know if there is anything else I can do. I don't believe the failing tests are related but I could be wrong. I do not know if such a PR needs to have tests added or docs added per the requirements. Thanks in advance

**Comment by kapunahelewong** [comment]
Hi @jnsencha, thanks for this PR. Yes, those failures look like flakes. Could you rebase and push back up? Once the tests have run again (whether passing or failing), will you tag me? I'm happy to help you get this through. Thanks!

**Comment by jnsencha** [comment]
@kapunahelewong Hello! I've done the rebased and pushed back up. I see the same 3 failures are still plaguing the PR. Thank you so much for your help!

**Comment by kapunahelewong** [comment]
Thanks so much @jnsencha! 😊

Caretaker, the failures look unrelated to this docs only change. Can you help us get it green? Please let me know if you need me. Thanks!!

**Comment by kapunahelewong** [comment]
Oh, @jnsencha could you squash to one commit? (I missed that there are three commits!). Could you make it:
```
docs: update marketing resources with Angular UI Toolkit
```

You don't need the scope. Thank you!

**Comment by jnsencha** [comment]
@kapunahelewong  I'm sorry I missed the squash on that. I have squashed and now see one commit with the appropriate commit message format. Can you please confirm? Thank you!

**Comment by kapunahelewong** [comment]
Thanks, @jnsencha. Almost there. Can you remove the highlighted parts (and replace "by adding" with "with")? Like this:

image


You don't need the scope ( `(changelog)`) and "with" just shortens it a bit. You don't need the extra (old msg) because the change is straightforward and doesn't need more detail. Does this help? In case you need it, you should be able to do this with just `git commit --amend`. Thank you!! 😊

**Comment by jnsencha** [comment]
@kapunahelewong Thanks, yes I just did an amend for the requested changes and have removed the scope.

**Comment by kapunahelewong** [comment]
Thanks, @jnsencha! Don't forget the second part in there:

image

**Comment by jnsencha** [comment]
@kapunahelewong Hi! Ok, I have removed the old message, now there is just the one line. Thanks!

**Comment by kapunahelewong** [comment]
Caretaker, the failures look unrelated to this docs only change. Can you help us get it green? Please let me know if you need me. Thanks!!

**Pull request closed without merging**
