### PR TITLE
fix(router): resolve isRouteActive for parent routes

### PR DESCRIPTION
**Pull request by ciriarte**
Router.isRouteActive is not resolving routes like ['../RouteDefinedInParentComponent']

I just used the resolved router reference in the loop to evaluate the predicate instead of 'this'

### CODE REVIEW

**Comment by PascalPrecht** [comment]
@ciriarte could you add a test for this as well?

**Comment by ciriarte** [comment]
@PascalPrecht of course! I'm just a bit nervous as it is my first contrib. Should I take one of the tests under router as an example?

**Comment by PascalPrecht** [comment]
@ciriarte No worries! Let's just first double check with @btford if this is intentional or not. Maybe there's already a different way to solve your problem which we are not aware of.

**Comment by btford** [comment]
@ciriarte Looks good, but this will need to be rebased and it'll need an automated test like this: https://github.com/angular/angular/blob/master/modules/angular2/test/router/integration/router_link_spec.ts#L238

**Comment by ciriarte** [comment]
@btford Thank you for your feedback. I've added an automated test per your suggestion. Sorry it took so long, it took me a while to understand the tooling.

Please let me know if you need anything else.

**Comment by ciriarte** [comment]
@PascalPrecht, @btford should I close this PR? Is there another approach I should take? Perhaps further cleanup / rebase again?

**Comment by hansl** [comment]
@ciriarte could you please rebase your branch?
@btford Is this ready to submit? If so, could you LGTM?

:)

**Comment by petebacondarwin** [comment]
@ciriarte - thanks for this. I think that the test should perhaps be against the router rather than the `ngLink`. Something near here: https://github.com/angular/angular/blob/master/modules/angular2/test/router/router_spec.ts#L196

**Comment by mhevery** [comment]
This PR is stale (does not rebase; pass CI; had no activity for a while). It is probably our fault, and we are sorry. In an effort to keep our PR queue under control, and prevent us from taking too long to get back to you we are cleaning up the queue. Unfortunately this means that this PR is getting closed.

If you would like to resurrect this change, please rebase on master, make the tests pass and create a new PR.

**Pull request closed without merging**
