### PR TITLE
build: update remark packages

### PR DESCRIPTION
**Pull request by gkalpak**
This PR updates the `remark` packages to v12 instead of the latest (v13), because v13 is a major breaking change that requires more investigation and work.

More specifically, v13 replaces the internals of `remark` with a new CommonMark-compliant parser.
(See their [release notes][1] for more info.)

This change causes our old `remark` plugins (in [renderMarkdown.js][2]) to stop working.

[1]: https://github.com/remarkjs/remark/releases/tag/13.0.0
[2]: https://github.com/angular/angular/blob/d42019d4128ca0d9f233a085bfe838f93f8d0412/aio/tools/transforms/remark-package/services/renderMarkdown.js#L17-L24

### CODE REVIEW

**Comment by gkalpak** [comment]
I have also created #41797 to track updating to the latest versions.

**Review by petebacondarwin — APPROVED** [review]
LGTM once you have fixed the conflicts.

**Comment by jessicajaniuk** [comment]
This has been merged into `master` and `12.0.x`, but has conflicts with `11.2.x`. Please create a patch PR to land it there.

**Comment by gkalpak** [comment]
For reference, here is the PR for patch: #41862

**Pull request closed without merging**
