### PR TITLE
docs: add Jordan Powell to GDE resources

### PR DESCRIPTION
**Pull request by jordanpowell88**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information
Based on info provided [here](https://github.com/WebGDEProgram/main/tree/master/Angular)

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@jordanpowell88 Looks like the jpg image is too large in file size. It needs to be smaller than 30kb. Can you update this PR with a resized image? That should get all tests green.

**Review by MarkTechson — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
@jordanpowell88 Looks like that second commit message is causing lint issues. Can you squash it into the first commit instead? That should get you all green.

**Review by mgechev — APPROVED** [review]

**Comment by jordanpowell88** [comment]
@jessicajaniuk looks like the `action: cleanup` label needs removed before It can be merged

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 7ab10a503132772e3b57acd440e29073b2f2731d.

**Pull request closed without merging**
