### PR TITLE
chore(package.json): version lock zone.js to patches

### PR DESCRIPTION
**Pull request by PatrickJS**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
downloads 0.7.0 which breaks angular

**What is the new behavior?**
limits zone.js to only download patches

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by chuckjaz** [comment]
Please change commit title to: "chore(build): version lock zone.js to patches"

**Comment by gdi2290** [comment]
@chuckjaz done

**Comment by mattlewis92** [comment]
As zone.js isn't 1.0.0 yet, `^0.6.0` and `~0.6.0` are actually equivalent:
screen shot 2016-11-23 at 08 35 22

Source: https://semver.npmjs.com/

**Comment by gdi2290** [comment]
@mattlewis92 while true, developers are still reporting errors of zone.js 0.7.0 being installed when given the version `^0.6.25` maybe it's a problem with npm or maybe something else

**Comment by vicb** [comment]
agree with @mattlewis92 here. We should figure out the issue before coming with a fix.

**Pull request closed without merging**
