### PR TITLE
Fix .d.ts generation errors caused by invisible types of exported declarations

### PR DESCRIPTION
**Pull request by mhegazy**
Ran into a few declaration emit errors while looking into broccoli extension. here are the errors for future references:

> [16:41:52] Error: [DiffingTSCompiler]: Typescript found the following errors:
> 
>  angular2/src/di/injector.ts (28, 5): Type 'string' is not assignable to type 'number'.
> 
>  angular2/src/change_detection/parser/lexer.ts (35, 50): Parameter 'type' of constructor from exported class has or is using private name 'TokenType'.
> 
>  angular2/src/directives/ng_for.ts (94, 34): Parameter 'tuples' of public static method from exported class has or is using private name 'RecordViewTuple'.
> 
>  angular2/src/directives/ng_for.ts (95, 60): Return type of public static method from exported class has or is using private name 'RecordViewTuple'.
> 
>  angular2/src/directives/ng_for.ts (111, 34): Parameter 'tuples' of public static method from exported class has or is using private name 'RecordViewTuple'.
> 
>  angular2/src/directives/ng_for.ts (112, 55): Return type of public static method from exported class has or is using private name 'RecordViewTuple'.
> 
>  angular2/src/render/dom/compiler/selector.ts (301, 40): Parameter 'map' of public method from exported class has or is using private name 'SelectorContext'.
> 
>  angular2/src/render/dom/dom_renderer.ts (354, 3): Return type of public method from exported class has or is using name 'LightDom' from external module "angular2/src/render/dom/shadow_dom/light_dom" but cannot be named.
> 
>  angular2/test/render/dom/dom_testbed.ts (32, 17): Return type of exported function has or is using private name 'TestRenderElementRef'.
> 
>  benchpress/src/common_options.ts (5, 14): Return type of public static property getter from exported class has or is using name 'Binding' from external module "angular2/src/di/binding" but cannot be named.
> 
>  benchpress/src/metric.ts (11, 10): Return type of public static method from exported class has or is using name 'Binding' from external module "angular2/src/di/binding" but cannot be named.
> 
>  benchpress/src/reporter.ts (12, 10): Return type of public static method from exported class has or is using name 'Binding' from external module "angular2/src/di/binding" but cannot be named.
> 
>  benchpress/src/validator.ts (14, 10): Return type of public static method from exported class has or is using name 'Binding' from external module "angular2/src/di/binding" but cannot be named.
> 
>  benchpress/src/web_driver_adapter.ts (13, 10): Return type of public static method from exported class has or is using name 'Binding' from externalmodule "angular2/src/di/binding" but cannot be named.

### CODE REVIEW

**Comment by mhegazy** [comment]
I signed it!

**Comment by tbosch** [comment]
Hi,
thanks. Why do these errors not show up in our build? @alexeagle could you dig into this?

**Comment by mhegazy** [comment]
The problem is declaration errors are only generated when the declarations are emitted. if you do not attempt to emit the declaration you will not see the errors. I have another [branch](https://github.com/angular/angular/compare/master...mhegazy:broccoli-build-update?expand=1) that shows the errors. I need to clean it up and send a PR.

**Comment by tbosch** [comment]
Maybe related: https://github.com/angular/angular/issues/3098

**Comment by alexeagle** [comment]
Thanks Mohamed, I'm re-running this through travis after rebase and merge. I'd like to get the other change in soon so we enforce that we don't have regressions of this problem.

**Comment by alexeagle** [comment]
Merged in 573c047

**Pull request closed without merging**
