### PR TITLE
fix(TemplateCompiler): allow minification

### LINKED ISSUE #6366: [beta.1] Error bundling using SystemJS Builder in Beta.1
Hi, I just updated my starter project to **angular2.0.0@beta.1** and when running in development, it was okay, but when I run production build and serve it, it showed error as follows:
screen shot 2016-01-09 at 6 46 17 am
**It's not happening in angular2.0.0@beta.0**

you can reproduce it by cloning my [repo](https://github.com/antonybudianto/angular2-starter) using `repro-mangle-error` branch, then run `gulp serve-build`

I'm using [SystemJS builder](https://github.com/systemjs/builder) for bundling, thanks!

### LINKED ISSUE #6380: [beta.2] ngDoCheck is not a function when using minified bundles
When using minified bundles with SystemJS, and a simple snippet like this 

```
        <template ngFor #item [ngForOf]="items" #i="index">
          <li>{{i}}</li>
          <li *ngIf="i % 2 == 0">number is even</li>
        </template>
```

Will throw 

```
TypeError: this.directive_0_0.ngDoCheck is not a function
```

This is only reproducible with minified bundles, non-minified work correctly. 

As an example check this [plnkr](http://plnkr.co/edit/ZWiQqw3nR8xS1MRrpTry?p=preview) (took it from https://github.com/angular/angular/issues/6304#issuecomment-170200989). To reproduce switch between minified and unminified bundles.

This is also reproducible with Webpack using this line in the config

```
    plugins : [
    	new webpack.optimize.UglifyJsPlugin()
    ],
```

Am I missing something?

### PR DESCRIPTION
**Pull request by PatrickJS**
fixes #6380 
fixes #6366

### CODE REVIEW

**Comment by gdi2290** [comment]
I'm guessing the other bug (https://github.com/angular/angular/issues/6366#issuecomment-170324997) is due to name conflicts from minification. Definitely maybe

**Comment by ocombe** [comment]
Ahh thanks a lot, we need to get this merged for the next release :)

**Comment by gdi2290** [comment]
fixed via https://github.com/angular/angular/commit/eda4c3eb4c823029b885fdfcd602a8c3c93f0d31

**Comment by stefanocke** [comment]
@gdi2290   I use 2.0.0-beta.7 and still experience issues similar to #6366:  I have a very simple Example with 2 Components.  Without minification, everything works. After minification (especially: mangling),  the first component seems to use the same template as the  2nd component.
This sounds much like the name conflicts you mentioned above...

So has #6366 really been fixed via eda4c3e ?

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166550.
------------------------------------------------------------------------------------------------------------


[[d3f86e31269ab39d4bfbc712d15ba9b96da5cc2c-673074172]]

**Comment by gdi2290** [comment]
?

**Pull request closed without merging**
