### PR TITLE
styles(topMenu):space between .home and .hamburger

### PR DESCRIPTION
**Pull request by aghArdeshir**
when hamburger menu is clicked, it's ripple background is drawn until the very edge of home's image, leaving no space. this adds a tiny space there

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

On the top header, when hamburger menu button is present, when clicked on it, a ripple background is drawn and is extended just to very edge of the main `Angular` image in home link.

Issue Number: N/A

## What is the new behavior?
I added a tiny space, and in my opinion it just looks nicer

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

## Other information
this is just self-opinionated. I just saw it on website and felt like there needs to be a small space there

### CODE REVIEW

**Comment by gkalpak** [comment]
Thx for working on this. It has been bothering me for a while :grin:
Adding some margin would also be more consistent with the [Material Design guidelines][1].

##
I believe it would be more consistent to fix it by adjusting the hamburger's margin (since that is what we use for spacing the hamburger button and the logo.

So, can you please change the following lines (instead of adding a margin to the logo):

https://github.com/angular/angular/blob/c5cfc3a1b652dd748a774d7f1dbc4ca4e8524b15/aio/src/styles/1-layouts/_top-menu.scss#L2-L3

```css
$hamburgerShownMargin: 0 8px 0 0;
$hamburgerHiddenMargin: 0 16px 0 -88px;
```

Changing the "hidden" margin to `16px`, makes it more consistent with the margin on the right side of the toolbar. And making the "shown" margin `8px` looked better to me (because the hamburger button itself has plenty of padding). Open to different suggestions.

[1]: https://material.io/guidelines/layout/structure.html#structure-app-bar

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx for working on this. It has been bothering me for a while :grin:
Adding some margin would also be more consistent with the [Material Design guidelines][1].

##
I believe it would be more consistent to fix it by adjusting the hamburger's margin (since that is what we use for spacing the hamburger button and the logo.

So, can you please change the following lines (instead of adding a margin to the logo):

https://github.com/angular/angular/blob/c5cfc3a1b652dd748a774d7f1dbc4ca4e8524b15/aio/src/styles/1-layouts/_top-menu.scss#L2-L3

```css
$hamburgerShownMargin: 0 8px 0 0;
$hamburgerHiddenMargin: 0 16px 0 -88px;
```

Changing the "hidden" margin to `16px`, makes it more consistent with the margin on the right side of the toolbar. And making the "shown" margin `8px` looked better to me (because the hamburger button itself has plenty of padding). Open to different suggestions.

[1]: https://material.io/guidelines/layout/structure.html#structure-app-bar

**Comment by Ardeshir81** [comment]
Thank you @gkalpak :smiley: 
I changed exactly as you told me and also tried it out! Yep! That's the true solution! Thanks.

But there is still one tiny thing (very trivial) that bothers me :laughing: 
and that is the outline when I click & hold on or drag logo.

screenshot-2018-5-2 screenshot from 2018-05-02 11-42-40 png png image 1366 x 768 pixels

as you see the the outline is started from the very beginning of image, but at the end there is 20px margin : ))))
But of course, that's so trivial.

Thank You! :+1:

**Comment by gkalpak** [comment]
Awesome! Thx 👍 

WRT the asymmetric outline:
I can't reproduce it, but let's fix it anyway :smiley:
We should move the right margin from the image (`.nav-link.home img`) to the anchor wrapper (`.nav-link.home`).

You can remove the `margin-right` style from here:

https://github.com/angular/angular/blob/c5cfc3a1b652dd748a774d7f1dbc4ca4e8524b15/aio/src/styles/1-layouts/_top-menu.scss#L96-L99

...and apply it to `a.nav-link.home` by changing:

https://github.com/angular/angular/blob/c5cfc3a1b652dd748a774d7f1dbc4ca4e8524b15/aio/src/styles/1-layouts/_top-menu.scss#L142-L153

...to:

```diff
 a.nav-link {
   margin: 0;
   padding: 24px 16px;
   cursor: pointer;
+
+  $.home {
+    margin-right: 20px;
+  }
  
   &:focus {
     background: rgba($white, 0.15);
     border-radius: 4px;
     outline: none;
     padding: 8px 16px;
   }
 }
```

##
BTW, it would be great if you could follow our commit message guidelines :heart:
(Read more about it [here][1].)

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by Ardeshir81** [comment]
oops! sorry for those commit messages :grin: 
I hope you like this one :)

I did as you said! and its great right now! :smiley: thanks!

Thank you so much for walking me through this. I'm learning so much. 

+1

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Thank _you_ for working on this :heart: This should be ready to get merged now :tada:
(BTW, I have changed the first two commit messages (and squashed the commits together) for you.)

**Pull request closed without merging**
