### PR TITLE
refactor(compiler): remove dependency on fs-extra

### PR DESCRIPTION
**Pull request by alan-agius4**
Currently, fs-extra is used to delete a directory recursively, but this is already available in native Node.JS. Hence, making this dependency redundant.

See: https://nodejs.org/docs/latest-v12.x/api/fs.html

### CODE REVIEW

**Comment by JoostK** [comment]
Can the `fs-extra` dependency in `package.json` also be removed? Only `@types/fs-extra` was removed from there.

**Comment by alan-agius4** [comment]
@JoostK, at first I though it was used else where, but now that I double checked I see that it's used in AIO tooling which has it's own package.json.

**Review by petebacondarwin — APPROVED** [review]

**Review by JoostK — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by josephperrott** [comment]
Caretaker Note: This PR will need to be landed alongside [cl/366864255](https://critique-ng.corp.google.com/cl/366864255).

Please land this PR and [cl/366864255](https://critique-ng.corp.google.com/cl/366864255) simultaneously to ensure that `g3sync`s and presubmits continue as expected.

**Pull request closed without merging**
