### PR TITLE
docs(docs-infra): add tab titles to home, playground and tutorial

### LINKED ISSUE #53020: Page titles are not distinguishable
### Describe the problem that you experienced

The home page, should let the user know where they are at via the title tag. 

### Enter the URL of the topic with the problem

angular.dev

### Describe what you were looking for in the documentation

Angular | Home

### Describe the actions that led you to experience the problem

Inspecting the Page title. 

### Describe what you want to experience that would fix the problem

You should Append the location to the end of the title. 

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by aramirezj**
## PR Checklist

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently, in [Angular dev](https://angular.dev/), the home, the playground and the tutorials does not have a specific title, only has "Angular". On the other hand, the option of the sidenav **Reference** and **Docs** have specific title being for each one:

- API Reference * Overview * Angular
- What is Angular? * Angular

Without
image
image
image

With
image
image

Issue Number: Fixes [53020](https://github.com/angular/angular/issues/53020)

## What is the new behavior?

With the new behaviour, the routes that had only Angular, now should have their own label plus * Angular

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

Since adev cannot be compiled and tested locally, these changes havent been tried, but I think they should work, if this PR should be block till adev can be tested locally I would totally understand.

Thanks!

### CODE REVIEW

**Comment by JeanMeche** [comment]
I'm marking this as blocked until the infra is setup to test the result.

**Comment by aramirezj** [comment]
> I'm marking this as blocked until the infra is setup to test the result. Btw can you reword your commit and make this a `docs(docs-infra): ... `

Seems good! I have read a few times the contributing.md but still didnt get it right XD, I will reword the commit, thanks!

**Comment by twerske** [comment]
As @JeanMeche mentioned - this is blocked but I'll review once we can have a build preview!

**Comment by aramirezj** [comment]
> As @JeanMeche mentioned - this is blocked but I'll review once we can have a build preview!

Perfect, thank you so much Emma!

**Review by JeanMeche — APPROVED** [review]
This works fine thx ! 

Just one thing @twerske, do we want the "Home" for the home page ?

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by aramirezj** [comment]
Thanks for the reviews guys! ^^

**Pull request closed without merging**
