### PR TITLE
docs: fixed typos

### PR DESCRIPTION
**Pull request by thapasusheel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [X] Other... Please describe: Typos fixed in multiple files

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

```pseudo
foward > forward
dependening > depending
executue > execute
sampel > sample
fils > file
```

### CODE REVIEW

**Review by AndrewKushnir — COMMENTED** [review]
@thapasusheel thanks for improving Angular docs!

Could you please update the commit message (using `git commit --amend`) to start with `docs: `?

**Comment by thapasusheel** [comment]
@AndrewKushnir  I have updated commit message as you have mention. Could you please review it?

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
**Caretaker note**: docs-only (low risk) change, no extra reviews are required. This PR is ready for merge.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 31c7bc1cf4fa7e9bad130ddcfbae54f10fef81ae.

**Pull request closed without merging**
