### PR TITLE
docs: change `item` to `items` to match the code

### LINKED ISSUE #35368: Typo in template-syntax example
# 📚 Docs or angular.io bug report

### Description
In the "Passing in an object" section, the text describes the ListItemComponent as having a property item of type Item.

However, the code example src/app/list-item.component.ts shows ListItemComponent having a property items of type Item[].

&lt;code-example path="property-binding/src/app/list-item/list-item.component.ts" region="item-input" header="src/app/list-item.component.ts"&gt;

### What's the affected URL?
https://angular.io/guide/template-syntax#return-the-proper-type

### PR DESCRIPTION
**Pull request by sonukapoor**
Closes #35368

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #35368

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
This change LGTM, but it'd be great if @kapunahelewong can have a look as well. Thank you.

**Review by gkalpak — APPROVED** [review]
Thx, @sonukapoor :+1:

##
This change looks good on its own (it's an improvement over the current state), but I believe a bigger change is needed to make the example more intuitive. Things I noticed that are confusing:

- A component named `ListItemComponent` that lists items. AFAICT, such components usually have `List` as a suffix, not a prefix; i.e. `ItemListComponent`.
- `AppComponent` has a property called `currentItem` (implying a single item) that holds a list of items (even if it happens to have only one item, it is still a list).

@kapunahelewong, wdyt? Did I miss something?

**Comment by sonukapoor** [comment]
@gkalpak. Makes sense. Can I address those in a follow up PR and we can merge this one first as is?

**Comment by gkalpak** [comment]
**merge-assistance:** Global approval for this docs-only change.

**Comment by kapunahelewong** [comment]
> @kapunahelewong, wdyt? Did I miss something?
I think you covered it, @gkalpak. It'll be clearer with those updates, for sure. Thank you both!

**Pull request closed without merging**
