### PR TITLE
docs: Rename FAQ to Useful Tips

### LINKED ISSUE #35056: Confusing statement in testing documentation
# 📚 Docs or angular.io bug report

### Description

In the **Frequently Asked Questions** section of the testing guide, there is a statement that tries to explain why not rely on E2E tests of DOM integration. I have read it many times but I find it really confusing to understand its meaning. At first glance, it seems that it tries to explain the same thing as the following section **Why not defer DOM integration tests to end-to-end (E2E) testing?**.

### What's the affected URL?**
https://angular.io/guide/testing#why-not-rely-on-e2e-tests-of-dom-integration

## 📷Screenshot

image

## 🔥 Exception or Error
<pre><code>

</code></pre>

### PR DESCRIPTION
**Pull request by sonukapoor**
Previously, a section in the FAQ was not clear when discussing a simple unit test.
We also want to move away from question-based sections. This commit clarified 
the confusing section and changed all question-based sections.

Closes #35056

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #35056

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by kapunahelewong — CHANGES_REQUESTED** [review]
I like "Useful tips" as a title! Thank you so much for this. Requesting @aikidave as this section just came up in conversation.

**Review by aikithoughts — APPROVED** [review]
I like moving away from FAQs. +1 to @kapunahelewong 's comments.

**Comment by sonukapoor** [comment]
> I like moving away from FAQs. +1 to @kapunahelewong 's comments.

Glad to hear that @aikidave.

@kapunahelewong I have made the suggested changes.

**Review by kapunahelewong — APPROVED** [review]
This is great. Thank you so much, @sonukapoor!!

**Pull request closed without merging**
