### PR TITLE
docs: fix invalid file replacement configuration

### LINKED ISSUE #52801: docs: invalid environment fileReplacements configuration
### Describe the problem that you experienced

Section: Using environment-specific variables in your app

It should only show fileReplacements for the staging environment since it's a staging configuration.

image

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/environments#using-environment-specific-variables-in-your-app

### Describe what you were looking for in the documentation

_No response_

### Describe the actions that led you to experience the problem

_No response_

### Describe what you want to experience that would fix the problem

_No response_

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by sasidharansd**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Closes #52801

## What is the new behavior?
The invalid file replacement config is removed to avoid confusion

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by twerske** [comment]
@alan-agius4 Can you confirm this is correct?

**Review by alan-agius4 — APPROVED** [review]

**Comment by twerske** [comment]
Adding blocked until we can build a preview of the Angular.dev app in this PR!

**Review by jessicajaniuk — APPROVED** [review]
LGTM! Looks good and verified in the preview.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit c8d1b11cec0e779d3191e077482d61f664991ba9.

**Pull request closed without merging**
