### PR TITLE
doc: add enddocregion

### PR DESCRIPTION
**Pull request by Popovkov57**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, is this change supposed to fix an issue ? The rendering on [this doc page](https://angular.io/start/start-data#use-the-cart-service) seems to be fine !

**Comment by Popovkov57** [comment]
> Hi, is this change supposed to fix an issue ? The rendering on [this doc page](https://angular.io/start/start-data#use-the-cart-service) seems to be fine !

Hi @JeanMeche 

Comment `/* . . . */` doesn't appear to explain there are some code above and below. 

I watch in similar file and there are endtag at the end of the file.

I think that the endtag can explain it.

Best regards

**Comment by JeanMeche** [comment]
Check the generated docs, this won't add `/* ... */` to the doc example. This whould need to appear within the code region.

**Comment by Popovkov57** [comment]
Hi @JeanMeche

I'm pushing a new commit and I now it's working. 
But remove I remove `#docplaster` tag. 
Do you what this tag do please ?

Best regards

**Comment by Popovkov57** [comment]
I find explaination in [old doc Angular](https://v2.angular.io/docs/ts/latest/styleguide.html) what `#docplaster` do.

**Comment by JeanMeche** [comment]
The `docplaster` overrides the default plaster (separator). When followed by nothing it just removes the plaster. 

When I look at your current change, that doesn't look like something we'd want : 

image

The plaster doesn't bring much readability, quite the opposite i'd say.

**Review by jessicajaniuk — COMMENTED** [review]
Like @JeanMeche, I'm a bit unclear on what this is doing and why it's needed. There's also some lint issues that need addressing. Also please squash this into a single commit.

**Comment by JeanMeche** [comment]
The change doesn't seem to be necessary, so i'll close it.

**Pull request closed without merging**
