### PR TITLE
refactor(core): tree-shake defer block registry code

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit updates the code of the incremental hydration feature to make the `DeferBlockRegistry` class tree-shakable. The class is only needed for hydration cases and it should not be included into client bundles for client-only apps.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by thePunderWoman — APPROVED** [review]
LGTM! Thanks for taking care of this, @AndrewKushnir!

reviewed-for: fw-core, public-api

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:691543836:BASE:691543892:1730321945357:99b3cf97).

**Comment by AndrewKushnir** [comment]
**Caretaker note**: the `public-api` check was triggered since I've added a new error code, which is a low risk and the current review should be sufficient.

**Comment by pkozlowski-opensource** [comment]
@AndrewKushnir this PR will have to be rebased after the latest merges.

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 89db5f734d2fdb3a2e96e903b572b7de9702e818.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
