### PR TITLE
docs: ordered words

### PR DESCRIPTION
**Pull request by Luis-Scapin**
Fixed some words order in the Learn Angular tutorial's step 16 - Getting form control value (step 1).

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ N/A ] Tests for the changes have been added (for bug fixes / features)
- [ N/A ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
In "...you can the use interpolation syntax...", the words the and use are switched.

Issue Number: N/A

## What is the new behavior?
Now they are in the correct order. "...you can use the interpolation syntax..."

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x ] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thank you for the fix.

**Comment by JeanMeche** [comment]
Could you please amend the commit message and remoce the `tutorial` scope. There is not required scope for docs commits. Thank you.

**Comment by JeanMeche** [comment]
Currently you're only changing the title of the PR. 
We would need you to reword the commit.

**Comment by Luis-Scapin** [comment]
> Currently you're only changing the title of the PR. We would need you to reword the commit.

Created another PR > https://github.com/angular/angular/pull/56534

**Pull request closed without merging**
