### PR TITLE
chore(test): move to using dart:test for dart unit tests

### PR DESCRIPTION
**Pull request by juliemr**
This is a work in progress PR showing how Angular2 tests could be migrated to using the new `dart:test` unit test runner and library.

### CODE REVIEW

**Comment by kevmoo** [comment]
Darn – broken by `benchpress` – I'll help you debug

**Comment by kevmoo** [comment]
You need to upgrade `modules/benpress` to use `guinness2` as well – then you're golden

**Comment by juliemr** [comment]
Yup, haven't touched the auxiliary parts yet. There's also some tests in
transformers that need updating.

**Comment by juliemr** [comment]
Updated with a little script that generates one big file to run all tests. This lets us use `iit` and `ddescribe` as expected.

**Comment by juliemr** [comment]
Open issues
- shadow dom css tests are broken. I debugged a bit and I'm not sure they're actually running at all - they fail when I run manually
- Debugging is still a concern. See https://github.com/dart-lang/test/issues/45
- The 'dart server' tests have not yet been upgraded.
- Need to make sure that this is acceptably fast. In a quick test on my machine, running the whole suite takes 37 seconds on guinness2, as opposed to ~2 minutes on karma-dart. However, the actual time spent running test with karma-dart is much faster, only 9 seconds.

**Comment by tbosch** [comment]
@juliemr I am in the progress of changing the shadow dom tests. Don't worry...

**Comment by naomiblack** [comment]
@yjbanov can you complete this one since julie is OOO?

**Comment by tbosch** [comment]
@juliemr are you still working on this?

**Comment by juliemr** [comment]
@tbosch it's still on my todos but I'm not actively able to work on in probably for the next week or so.

**Comment by juliemr** [comment]
I don't think this should be beta-0, since there are still blockers on debugging and tests taking too long. I'm moving to beta.1, please yell at me if you feel otherwise.

**Comment by kevmoo** [comment]
@juliemr I'd love to get this out ASAP. It's not changing anything that exists – just providing a new option.

`pkg/test` is **THE** way to easily run browser tests. If this works, we should get it out.

**Comment by juliemr** [comment]
@kevmoo just making sure we're on the same page - this is a separate issue from providing a library on top of dart:test (https://github.com/angular/angular/pull/3289) - this issue is about migrating Angular2's own internal tests. So it does involve quite a bit of changing things that already exist.

**Comment by juliemr** [comment]
Note to all: I am actively picking this up again (moving angular tests to the new dart tests runner).

**Comment by kevmoo** [comment]
Woo hoo! :metal:

**Comment by juliemr** [comment]
This is so out of date I just made a new one - see instead https://github.com/angular/angular/pull/7111

**Pull request closed without merging**
