### PR TITLE
Update resources.json

### PR DESCRIPTION
**Pull request by mrholek**
Add CoreUI UI Components Library for React 13

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe: add project to resources list

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@mrholek thanks for creating this PR. It looks like there is a couple failing checks:

- the CLA has not been signed yet, could you please [follow the instructions here](https://github.com/angular/angular/pull/44613/checks?check_run_id=4703887190) to sign it?
- the `lint` CI check is failing due to the missing scope in the commit message, could you please update it to start with `docs:`, for example: `docs: add CoreUI UI Components Library to the Resource list` (please also check the commit message itself if it's accurate)?

Please let us know once it's done (by leaving a comment in this thread) and we'll take another look. Thank you.

**Comment by mrholek** [comment]
@AndrewKushnir CLA is signed, and commit message changed.

**Review by twerske — APPROVED** [review]
lgtm

**Comment by atscott** [comment]
This PR was merged into the repository by commit 3517e51ab5b6b1dcd5c2b637da3073c9bd3173ba.

**Pull request closed without merging**
