### PR TITLE
refactor(router): Simplify the prioritizeGuardValue logic

### PR DESCRIPTION
**Pull request by atscott**
The existing logic does something similar but in a more roundabout way.
It reads _the whole array_. If it encounters a pending value, it ignores
the remaining ones. If it hasn't encountered a pending value by the time
it hits false/UrlTree, it returns that result.

The new logic is the same, but reverses what we're looking for. Instead
of processing the whole array, we stop when we encounter an initial
value. When we encounter one that isn't `true`, that gets returned. If
we get to the end and everything was `true`, return `true`.

### CODE REVIEW

**Comment by atscott** [comment]
[presubmit](https://fusion2.corp.google.com/presubmit/tap/459777036/OCL:459777036:BASE:459777048:1657298972455:66ba99f6/targets)

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit cee207ea1124eb7f6dfda62210e324496ec29981.

**Comment by jessicajaniuk** [comment]
This ended up causing a breakage in google3.

**Comment by atscott** [comment]
note: retargeting to minor to avoid the symbol test failure in patch. This doesn't really need to be merged to patch.

**Comment by atscott** [comment]
caretaker note: This was already rolled back once. Please merge and sync on its own.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 647afb02b32381b33c3c3829e29f5a33bd59df07.

**Pull request closed without merging**
