### PR TITLE
feat(http): add `has()` method to `HttpContext` class

### PR DESCRIPTION
**Pull request by HyperLife1119**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Unable to determine whether a certain token exists in `HttpContext`.

## What is the new behavior?
Use the `has()` method provided by `HttpContext` to detect whether a certain token exists

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@HyperLife1119 - thanks for this PR.
Please can you rebase on the current `angular/angular` master to get the CI to run.
Also, please just squash all three commits together into a single one.
Finally, we might need to update the size tracking files if this new feature pushes the size of applications that use `HttpContext` over the current limit.

**Comment by petebacondarwin** [comment]
Great! As expected we now have a couple more steps due to the new public API.

Please run `yarn bazel run //packages/common:common_api.accept`.

And then save it as a fixup commit (e.g. `git commit -a --fixup=HEAD`).

**Comment by HyperLife1119** [comment]
Encountered the following error when executing `yarn bazel run //packages/common:common_api.accept`:

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository npm instantiated at:
  C:/users/18384/desktop/github/angular/angular/WORKSPACE:41:13: in <toplevel>
  C:/users/18384/_bazel_18384/6th6ai7i/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  C:/users/18384/_bazel_18384/6th6ai7i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:917:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "C:/users/18384/_bazel_18384/6th6ai7i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 915, column 24, in _yarn_install_impl
                _create_build_files(repository_ctx, "yarn_install", node, repository_ctx.attr.yarn_lock, repository_ctx.attr.generate_local_modules_build_files)
        File "C:/users/18384/_bazel_18384/6th6ai7i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 492, column 13, in _create_build_files
                fail("generate_build_file.ts failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (result.stdout, result.stderr))
Error in fail: generate_build_file.ts failed: 
STDOUT:

STDERR:
could not find dependency '@types/tmp' of '@angular/dev-infra-private'
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/18384/_bazel_18384/6th6ai7i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 915, column 24, in _yarn_install_impl
                _create_build_files(repository_ctx, "yarn_install", node, repository_ctx.attr.yarn_lock, repository_ctx.attr.generate_local_modules_build_files)
        File "C:/users/18384/_bazel_18384/6th6ai7i/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 492, column 13, in _create_build_files
                fail("generate_build_file.ts failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (result.stdout, result.stderr))
Error in fail: generate_build_file.ts failed: 
STDOUT:

STDERR:
could not find dependency '@types/tmp' of '@angular/dev-infra-private'
ERROR: no such package '@npm//@bazel/protractor': generate_build_file.ts failed:
STDOUT:

STDERR:
could not find dependency '@types/tmp' of '@angular/dev-infra-private'
INFO: Elapsed time: 138.340s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Please help me.

> Great! As expected we now have a couple more steps due to the new public API.
> 
> Please run `yarn bazel run //packages/common:common_api.accept`.
> 
> And then save it as a fixup commit (e.g. `git commit -a --fixup=HEAD`).

I finished.

**Comment by HyperLife1119** [comment]
> Great! As expected we now have a couple more steps due to the new public API.
> 
> Please run `yarn bazel run //packages/common:common_api.accept`.
> 
> And then save it as a fixup commit (e.g. `git commit -a --fixup=HEAD`).

I finished

**Comment by petebacondarwin** [comment]
I think this is the commit you need https://github.com/angular/angular/commit/8ba2a367191478167b8f0815aa68166ca0f37b38

**Review by petebacondarwin — APPROVED** [review]
Looks good to me. Thanks.

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
@HyperLife1119 thanks for contributing to Angular! 👍 

I just wanted to mention that this change adds some non-tree-shakable code to app bundles in case HTTP package is used. However the added code would be small and the new API looks reasonable (and somewhat missing in the current implementation), so we can probably justify that minimal size increase.

Reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:
Thanks for your contribution!

reviewed-for: public-api

**Comment by atscott** [comment]
This PR was merged into the repository by commit d452b388bdc0d661f41ab382f5e7ac998b0f9915.

**Pull request closed without merging**
