### PR TITLE
html_sanitizer: add id and style html attrs as allowed to avoid dropping of them by sanitizer

### PR DESCRIPTION
**Pull request by amaestr0**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 45270

https://github.com/angular/angular/issues/45270
## What is the new behavior?
style and id attrs should be kept in html security context but sanitized inside.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by amaestr0** [comment]
@AndrewKushnir , does smb plan to pick it up for review?

**Comment by amaestr0** [comment]
@AndrewKushnir , does smb plan to pick it up for the review?

**Comment by pkozlowski-opensource** [comment]
@amaestr0 it is not clear to me what is the motivation for this change. What is the problem that you are trying to address?

**Comment by pkozlowski-opensource** [comment]
@amaestr0 it is not clear to me what is the motivation for this change. What is the problem that you are trying to address?

**Comment by amaestr0** [comment]
> @amaestr0 it is not clear to me what is the motivation for this change. What is the problem that you are trying to address?

@pkozlowski-opensource have you read the related issue an it's description?

**Comment by pkozlowski-opensource** [comment]
> have you read the related issue an it's description?

@amaestr0 sure, I'm assuming that you are referring to https://github.com/angular/angular/issues/45270. But this is where the confusion starts. The #45270 mentions the `id` and `style` attributes, so does your PR title. But it doesn't match what is going on in the code:
* it doesn't deal with the `id` (good, but the PR title and the communication should be updated);
* it introduces `export const UNSAFE_SPEC_ATTRS_VALUES: string[] = ['expression', 'javascript', 'script'];` (and the processing of it) which I find unrelated to what it discussed in the issue / PR communication.

I'm fine if we focus on the `style` attribute - in fact we might no longer need to sanitize it at all, given changes done in https://github.com/angular/angular/pull/35621.

I'm going to close this PR for now as there is lots of noise going on here already. If we are to do changes to the `style` attribute sanitization we should do so in a dedicated, focused PR. But before opening a PR we should discuss if the `style` attribute sanitization is needed at all. 

Moving the discussion back to  #45270

**Pull request closed without merging**
