### PR TITLE
fix(platform-browser): fix #22155, destroy hammer manager when off

### LINKED ISSUE #22155: Hammerjs events are causing memory leaks (detached nodes)
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When angular removes the event listener for a hammer event, it only calls the `.off()` function of the hammer manager instance. 

 addEventListener(element: HTMLElement, eventName: string, handler: Function): Function {
    const zone = this.manager.getZone();
    eventName = eventName.toLowerCase();

    return zone.runOutsideAngular(() => {
      // Creating the manager bind events, must be done outside of angular
      const mc = this._config.buildHammer(element);
      const callback = function(eventObj: HammerInput) {
        zone.runGuarded(function() { handler(eventObj); });
      };
      mc.on(eventName, callback);
      return () => mc.off(eventName, callback); <----- right here
    });
  }

However, this is not destroying the manager instance, which is holding a reference to the element. This is causing detached nodes for every element that has a `@HostListener` listening for a hammer touch event.

## Expected behavior

When removing an event listener for a hammer touch event, no detached nodes should be left over.
Therefore, in addition to `.off()` Angular should also call `destroy()`. 

## Minimal reproduction of the problem with instructions

Here is a simple demo reproducing the problem.
[https://stackblitz.com/edit/angular-j95qco](https://stackblitz.com/edit/angular-j95qco)

- Repeatedly clicking the 'toggle button' button will add and remove a `my-button` component with an `HostListener` on a tab event.
- After that, go to the Memory tab in Chrome Dev Tools and create a heap snapshot.
- Filter the list for detached.
- You will see a bunch of detached nodes. Expand the nodes to see that `my-button` is causing it.

I also added a quick fix. Go to gesture.service.ts and un-comment the code between line 31 and 39. The fix simply calls `.destroy()` ind addition to `.off()`

## What is the motivation / use case for changing the behavior?

The current behavior drastically decreases performance of apps with lot of touch events.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [X] Chrome (desktop) version 63

### PR DESCRIPTION
**Pull request by JiaLiPassion**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #22155 

## What is the new behavior?
`destroy` the `HammerManager` when `off`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by vicb** [comment]
http://test/OCL:186165298:BASE:186165300:1518993201087:9b1ad8ec

**Comment by vicb** [comment]
@JiaLiPassion Seems like the CI is broken for a valid reason. Please take a look. Thanks.

**Comment by JiaLiPassion** [comment]
@vicb, thank you for review, I modified the code to make the new API `optional`, now CI is green, please review.

**Comment by kykint** [comment]
When will it be merged? It is very critical for adaptive SPA.

**Comment by kykint** [comment]
WA: 
```
import { AppComponent }   from './app.component';
import {Inject, Injectable} from "@angular/core";
import {HAMMER_GESTURE_CONFIG, EVENT_MANAGER_PLUGINS, HammerGestureConfig, ɵHammerGesturesPlugin} from "@angular/platform-browser";
import {DOCUMENT} from "@angular/common";

@Injectable()
export class HammerGesturesPluginPatch extends ɵHammerGesturesPlugin {
    constructor(@Inject(DOCUMENT) doc: any,
                @Inject(HAMMER_GESTURE_CONFIG) private config: HammerGestureConfig) {
        super(doc, config);
    }

    addEventListener(element: HTMLElement, eventName: string, handler: Function): Function {
        const zone = this.manager.getZone();
        eventName = eventName.toLowerCase();

        return zone.runOutsideAngular(() => {
            // Creating the manager bind events, must be done outside of angular
            const mc = this.config.buildHammer(element);
            const callback = function (eventObj: HammerInput) {
                zone.runGuarded(function () {
                    handler(eventObj);
                });
            };
            mc.on(eventName, callback);
            return () => {
                mc.off(eventName, callback);
                // destroy mc to prevent memory leak
                if (typeof mc["destroy"] === 'function') {
                    mc["destroy"]();
                }
            };
        });
    }
}

@NgModule({
....
providers: {
            provide: EVENT_MANAGER_PLUGINS,
            useClass: HammerGesturesPluginPatch,
            multi: true
}
})
AppModule{

}
```

**Comment by JiaLiPassion** [comment]
@kykint , I think this PR is still under review.
@vicb, could you please help to check this one, thank you.

**Comment by HannesT117** [comment]
@kykint, thanks for the workaround! Just a remark: In the example, the providers are missing ``[]`` (``providers: -->[{provide: ...}]<--``) which could lead to some confusion.

**Comment by adarowiec** [comment]
pls fix?

**Comment by JiaLiPassion** [comment]
@vicb, could we merge this one? thanks!

**Comment by mhevery** [comment]
http://test/OCL:215849887:BASE:215849896:1538710922497:330cf404

**Pull request closed without merging**
