### PR TITLE
refactor: remove View Engine runtime (v13 edition)

### PR DESCRIPTION
**Pull request by alxhub**

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Review by jelbourn — APPROVED** [review]

**Review by dgp1130 — APPROVED** [review]
L! G! T! M!

**Review by JoostK — APPROVED** [review]
🤩

**Review by jessicajaniuk — APPROVED** [review]
LGTM 🍪  🍪  🍪

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by gkalpak — APPROVED** [review]
LGTM 🚀  <sub>(as soon as CI is happy 😛)</sub>

**Review by crisbeto — APPROVED** [review]

**Review by devversion — APPROVED** [review]

**Review by dylhunn — APPROVED** [review]
LGTM

**Review by pkozlowski-opensource — APPROVED** [review]
Yeh!

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 84ef01d9d2b7dcb266ccf534b964443315e2618d.

**Pull request closed without merging**
