### PR TITLE
docs: Adding step to include child component to fix compile error

### PR DESCRIPTION
**Pull request by subson**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
This PR updates the getting started doc to add child component to app.module.ts to fix the compile error.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently is throws a compile error on `Pass data to a child component` Step.

Issue Number: 43211

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@subson - thanks for submitting this change. I note that there are couple of issue that need addressing:

```
warn:    Missing example region... relativePath: "getting-started/src/app/app.module.1.ts", region: "as-generated". - doc "start/index" (content)  - from file "start/index.md"
Regions available are: "" - doc "start/index" (content)  - from file "start/index.md"
error:   Error running processor "renderExamples":
Missing example region... relativePath: "getting-started/src/app/app.module.1.ts", region: "as-generated". - doc "start/index" (content)  - from file "start/index.md"
Regions available are: ""
```

**Comment by subson** [comment]
@petebacondarwin Can you help me with relativepath issue? I saw similar path is added for product-alerts.component.1.ts. 
Do I have to use relativePath from the root folder?

**Comment by petebacondarwin** [comment]
Looks like you might have worked it out... you use the path from the `examples` folder.
I think, though, that dumping the whole of that file into the guide will be too much. We probably want to be a bit more careful with selecting a section of the code to display.

**Review by gkalpak — COMMENTED** [review]
Thx for stepping up and submitting a pull request, @subson 💯

I think it is an overkill to create a whole new file for showing just a couple of lines in a code-snippet, esp. given these lines were already present in `app.module.ts`. I created an alternative approach in #43229 (which uses the existing `app.module.ts` and also moves the step just before using the `ProductAlertsComponent` in another component, so that the step is closer to where it is conceptually needed).

Please take a look and let me know what you think :pray:

**Pull request closed without merging**
