### PR TITLE
feat: add an env for testing closure builds

### PR DESCRIPTION
**Pull request by vicb**
/cc @alexeagle @mhevery 

Based on @alexeagle PR #13471

### CODE REVIEW

**Comment by mhevery** [comment]
- [ ] Please add travis support. We should have a build the projects and assert that we get no errors so that we don't bit-rot
- [ ] Please add compilation of `@angular/core` which should result in 0 byte file (currently due to closure bugs it does not work), this way we have easy way to reproduce it and work on getting it to zero bytes
- [ ] Dido for all other packages as well.

**Review by alexeagle — CHANGES_REQUESTED** [review]
I was expecting multiple integration tests. Some may not use closure compiler, eg. we should have an integration test that we work with webpack.
Can the build_folder.sh just run `npm test` in each subdirectory? Then the closure-specific script would move inside a subdir.

**Comment by mhevery** [comment]
+1 for @alexeagle  comment.

**Comment by alexeagle** [comment]
I'm refactoring this, will replace with a new PR.

**Pull request closed without merging**
