### PR TITLE
Remove unused JSNAMESPACE_SUPPORT from event-dispatch

### PR DESCRIPTION
**Pull request by rahatarmanahmed**
This was an old feature that let you add `jsnamespace="ns` to an element to implicitly add the `ns.` namespace to all unnamespaced JSAction handlers on or under that element. This required an expensive DOM walk to find the jsnamespace, and almost all JSAction users turned this feature off. The last usage in google 3was removed, so we can delete this now.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been ~~added~~ deleted (for bug fixes / features)
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Comment by rahatarmanahmed** [comment]
Caretaker note: cl/630174160 is needed either in sync CL or prior to sync CL due to copybara changes.

**Comment by rahatarmanahmed** [comment]
TESTED=[TGP](https://fusion2.corp.google.com/presubmit/630173751/OCL:630173751:BASE:631094773:1715014119997:c4c1f2a9;groups=PossiblyAlreadyFailing,PossiblyNewlyFailing/targets) (failures are extremely flaky and fail at HEAD)

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by tbondwilkinson — APPROVED** [review]
:tada:

**Comment by AndrewKushnir** [comment]
**Caretaker note**: this PR is ready for merge, the only missing piece was an additional `public-api` approval, but since this is a removal of a no longer used feature, existing approvals should be sufficient.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 879537466ea1d8485599176f4a7cb2d0d81ac870.

**Pull request closed without merging**
