### PR TITLE
feat(NgZone): context/arguments pass to zone cb

### PR DESCRIPTION
**Pull request by PatrickJS**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
you don't

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

allow using `runOutsideAngular`/`run`/`runGuarded` without having to recreate the function during each call

[Tipe CMS](https://tipe.io?ref=github-comment)

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
Rebase and fix tests?

**Comment by vicb** [comment]
@gdi2290 please fix the CI. Thanks.

**Comment by tbosch** [comment]
This is a change we are willing to take. Could you please rebase against master if you are still interested in landing this PR?

**Comment by gdi2290** [comment]
@splincode feel free to take this PR over

**Comment by mhevery** [comment]
This work has already landed in master. https://github.com/angular/angular/blob/9623e7c639bd30bb03869b9e62a64cf86969ce3e/packages/core/src/zone/ng_zone.ts#L170 closing this PR

**Pull request closed without merging**
