### PR TITLE
release: cut the zone.js-0.13.2 release

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Cut a new release to include https://github.com/angular/angular/pull/51652

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]

**Comment by alan-agius4** [comment]
**Caretaker note:** please release zone.js

**Comment by AndrewKushnir** [comment]
FYI, will release early next week (likely Monday, Sep 11).

**Comment by alan-agius4** [comment]
> FYI, will release early next week (likely Monday, Sep 11).

SGTM, thanks

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit ac56efa41063c8251868c1f1362ebe6af58c8955.

**Comment by ocombe** [comment]
@JiaLiPassion this PR broke jest preset angular somehow https://github.com/thymikee/jest-preset-angular/issues/2162 and probably all projects using jest :-/

**Comment by alan-agius4** [comment]
Replied to the above issue.

**Pull request closed without merging**
