### PR TITLE
ci: minor CircleCI config refactoring/improvements

### PR DESCRIPTION
**Pull request by gkalpak**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] ~~Tests for the changes have been added (for bug fixes / features)~~
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

## PR Type
- [x] CI related changes

## What is the current behavior?
`aio` CI jobs run.

## What is the new behavior?
`aio` CI jobs run faster.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
It builds on top of #26377.

TODOs:

❌ Investigate caching `aio/node_modules/`.
&emsp;&emsp;_Doesn't seem to reduce total time and unnecessarilly complicates jobs._
❌ Investigate caching `aio/examples/node_modules/`.
&emsp;&emsp;_Doesn't seem to reduce total time and unnecessarilly complicates jobs._
❌ Investigate sharing `aio` build artifacts across jobs.
&emsp;&emsp;_Pro: When something flakes, we only need to re-run that part, without having to setup/build `aio` again._
&emsp;&emsp;_Con: Complicates the jobs and makes them more fragile. (For example, the best strategy for sharing `aio/node_modules/` would be via [caching][1], but it makes more sense to share `aio/dist/` via [attaching to workspace][2]. ([Relevant read][3]))_
&emsp;&emsp;_Since the total time for the slowest job is less than ~8 mins, I feel that the cons outweight the pros._
❌ [Re-use jobs][4] for `test_docs_examples` sharding. (Requires CircleCI version 2.1.)
&emsp;&emsp;_It turns out reusable commands are still in preview (not stable) and impose certain limitations (e.g. see [here][5] and [there][6])._
&emsp;&emsp;_Not worth it for just one job. We should revisit once the API is stable._
✔️ Other minor improvements.

[1]: https://circleci.com/docs/2.0/caching/
[2]: https://circleci.com/blog/deep-diving-into-circleci-workspaces/
[3]: https://circleci.com/blog/persisting-data-in-workflows-when-to-use-caching-artifacts-and-workspaces/
[4]: https://circleci.com/docs/2.0/reusing-config/#section=configuration
[5]: https://circleci.com/docs/2.0/build-processing/#limitations
[6]: https://github.com/CircleCI-Public/config-preview-sdk/blob/73f11fe7c41ab4bd6118dd525557bf174f3b8b77/README.md#important-21-configuration-caveats

### CODE REVIEW

**Comment by petebacondarwin** [comment]
I am not too bothered either way about the environment setting. Happy to leave it in the CircleCI config file if that is your preference.

**Comment by gkalpak** [comment]
This PR will also fix an issue with deploying aio to production:
The `deploy-production` script [here][1] needs xvfb (because it runs the PWA tests on the deployed app).
We either need to prefix the commad with `xvfb-run --auto-servernum` or land this PR :grin:

[1]: https://github.com/angular/angular/blob/d744dd70e0378a783352e5db007f4d5231c1edf9/.circleci/config.yml#L185

**Comment by gkalpak** [comment]
Rebased on master.

**Review by IgorMinar — APPROVED** [review]
to be honest, I find this version of the config file more readable, and I also like the cleanup you did with xvfb. I think we should merge this in.

**Comment by gkalpak** [comment]
:+1:
<sub>(Rebased on master.)</sub>

**Comment by gkalpak** [comment]
Note to caretaker: The CI failure is inherited from master 😞

**Comment by gkalpak** [comment]
Closed and reopened for CircleCI to pick it up 😞

**Comment by gkalpak** [comment]
`test_docs_examples_0` failure inherited from master. (Will be fixed by #26777.)

**Comment by gkalpak** [comment]
Rebased on master and re-targeted to master-only.
Opened #26786 for patch.

**Pull request closed without merging**
