### PR TITLE
chore: update the browser matrix image

### PR DESCRIPTION
**Pull request by asnowwolf**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

the browser-matrix image was cached incorrectly.

**What is the new behavior?**

the browser-matrix image would be updated to latest ... I guess.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
#11523 the browser matrix image was cached incorrectly. I think to change it's url should invalidate the cache from githubusercontent.com.

### CODE REVIEW

**Comment by IgorMinar** [comment]
this should not be necessary since the http server already sends no-cache headers:

screen shot 2016-09-13 at 10 41 57 am

**Comment by asnowwolf** [comment]
But currently, the browser-matrix is the old one yet. 

It seems that that image was cached by github, not by browser.

I checked it not only in my mac, please double check it.

This would make developers say: Angular 2 is not compatible with IE9 and Android 4.3. So I think it becomes very important now.

**Comment by vicb** [comment]
I have updated the image by [purging the cache](https://help.github.com/articles/why-do-my-images-have-strange-urls/#removing-an-image-from-camos-cache)

**Comment by asnowwolf** [comment]
Great, It's green all! very nice!

**Pull request closed without merging**
