### PR TITLE
docs(docs-infra): suggesting a typo error in the document

### PR DESCRIPTION
**Pull request by HarieswaranD**
I did observe a typo error in the document. I have raised a PR for the fix  https://angular.dev/guide/di/hierarchical-dependency-injection#self

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]

**Review by bencodezen — APPROVED** [review]
Thanks for the PR!

**Comment by bencodezen** [comment]
Hey @HarieswaranD. It looks like the commit message needs to be updated to match the conventions we have in the repo. You can learn more about it here: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit-message-header.

Let me know if you have any questions!

**Comment by HarieswaranD** [comment]
@bencodezen Thanks for pointing it out. I have update the commit message.

**Comment by JeanMeche** [comment]
You updated the PR title, we need you to reword your commit message: https://github.com/angular/angular/pull/57627/commits

**Comment by JeanMeche** [comment]
Could you please rebase your PR and squash the 3 commits into one, thank you.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 87a724ec1d66b75e2dc9fbc5f932f41dc30cce94.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
