### PR TITLE
fix(common): parse error response body for responseType "json"

### PR DESCRIPTION
**Pull request by dherges**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

For `req.responseType = "json"`, a non-2xx response body is always "text"

Issue Number: #18682

## What is the new behavior?

For `req.responseType = "json"`, response body is `JSON.parse()`'d

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by dherges** [comment]
🍎  Test Failure for commit d34eeed is 🍎 

```
Chromium 60.0.3112 (Ubuntu 0.0.0) XhrBackend handles a json error response for 4xx status FAILED
	HttpErrorResponse: Http failure response for /test: 400 Bad Request
Chromium 60.0.3112 (Ubuntu 0.0.0) XhrBackend handles a json error response for 5xx status FAILED
	HttpErrorResponse: Http failure response for /test: 500 Internal Server Error
```

With commit f473960f9, these two tests should turn green! 🍏

**Comment by dherges** [comment]
I accidentally duplicated #19378

Related issues are #19377 and #19103 

Related code change introducing the issues seems to be 452a7ae88b3b1144369f884c10de044502dc3c65

**Comment by ashgibson** [comment]
Is this going to be merged or the issue that it fixes updated soon? My app is full of forms which have server side validation that returns a 422 with json errors object. I then use this object to display field errors and this is now broken. I can fix by adding some logic to my interceptor to manually parse the json but not going to bother if the breaking change that was brought in 4.4.4 will be reversed in 4.4.5.

**Comment by Linskeyd** [comment]
@dherges you may want to update this comment as it seems to still assume that only 'ok' results are being processed: https://github.com/angular/angular/pull/19477/files#diff-26683cfb34fa97883213282055aef1e7R189

Additionally, you may want to add a test which explicitly checks for XSSI prefix support in the error response: https://gist.github.com/Linskeyd/df32564d539862350e927721ffad86df

**Comment by dherges** [comment]
Is it fixed by #19773 ?

**Pull request closed without merging**
