### PR TITLE
docs: changed weird plus syntax in route doc to be more readable and …

### PR DESCRIPTION
**Pull request by jordan-amman**
…easier to understand.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Using plus syntax to convert to number: products[+params.get('productId')];

Issue Number: #33001

## What is the new behavior?
Using Number interface since it is more readable and easier to understand. products[Number(params.get('productId'))];

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jordan-amman** [comment]
@hematy61 @kapunahelewong @trotyl 
Added pull request for this issue: https://github.com/angular/angular/issues/33001

**Comment by dannyskoog** [comment]
Also to add is that coercing using `Number` rather than `+` is in line with the style guide https://google.github.io/styleguide/jsguide.html#disallowed-features-wrapper-objects

**Review by StephenFluin — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Hey @jordan-amman could you [rebase](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase)?

**Comment by AndrewKushnir** [comment]
Closing this PR due to the lack of reply. Please reopen if needed. Thank you.

**Comment by jordan-amman** [comment]
I didn't realize this pull request was being held up by me, it sounds like I need to rebase in order for the code to be committed? Just let me know, thank you. @kapunahelewong @AndrewKushnir

**Comment by AndrewKushnir** [comment]
Hi @jordan-amman, thanks for the reply, I've reopened this PR.
Could you please try to rebase and resolve merge conflicts? This change was approved, so once the PR is in a mergeable state, we can add it to the merge queue.
Thank you.

**Comment by jelbourn** [comment]
Also the commit message should be something like

```
docs: use Number for coercion instead of plus operator

Update the product-details example to use the `Number` constructor instead of the plus operator
to coerce a value to a number.
```

**Comment by AndrewKushnir** [comment]
Closing this PR since the mentioned part of the code has changed (hence the merge conflict) and the current code uses `Number` instead of `+`.

**Pull request closed without merging**
