### PR TITLE
style: change to American English

### PR DESCRIPTION
**Pull request by mahalde**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The word `behaviour` is used in some of the documentation.

## What is the new behavior?

`Behaviour` is changed to `behavior`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jbogarthyde — APPROVED** [review]
LGTM

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Caretaker note: This is a docs only change and does not impact g3. Please run presubmit

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:229290879:BASE:229290911:1547517174925:2040339e)

**Comment by AndrewKushnir** [comment]
@brandonroberts I've rebased this PR on top of the latest master and run g3 presubmit to verify everything looks good. Could you please have a quick look at the changes to make sure there are no unexpected changes after rebase and return "merge" label back if everything is ok? Thank you.

**Comment by petebacondarwin** [comment]
😭

**Pull request closed without merging**
