### PR TITLE
fix(router): fix a problem with router not responding to back button

### PR DESCRIPTION
**Pull request by jasonaden**
There was a problem with a combination of the `eager` URL update, browser `back` button, and hybrid applications. Details provided in internal ticket http://b/123667227.

This fix handles the problem by setting `router.browserUrlTree` when all conditions have failed, meaning the browser doesn't do anything with the navigation other than update internal data structures. Without this change, the problem was an old value was stored in `router.broserUrlTree` causing some new navigations to be compared to an old value and breaking future navigations.

### CODE REVIEW

**Comment by jasonaden** [comment]
[Presubmit](http://test/OCL:245498606:BASE:245498646:1556317959910:c8fa196a)

**Review by mhevery — APPROVED** [review]

**Comment by kara** [comment]
@jasonaden Linter is failing, so I added "cleanup" to this.

**Comment by kara** [comment]
@jasonaden Still failing :-(

**Comment by jasonaden** [comment]
Thanks... passed now.

**Pull request closed without merging**
