### PR TITLE
Removes es5 and es6 from the build path.

### PR DESCRIPTION
**Pull request by ttowncompiled**
Removes traceur from the build path so that only the typescript compiler is being used to actually compile our modules tree.

### CODE REVIEW

**Comment by ttowncompiled** [comment]
@tbosch @mprobst

**Comment by tbosch** [comment]
Let's define exactly how the output of our build should look like. @rkirov

**Comment by ttowncompiled** [comment]
After talking with @rkirov , it is my understanding that our publication structure would best benefit from having es6/dev, es6/prod, cjs/dev, cjs/prod, and ts/

**Comment by rkirov** [comment]
heads up - I merged https://github.com/angular/angular/commit/796fc6677113ac8489e386ffda22b3e60d981ed7 that removed `.es6` extensions.

**Comment by vsavkin** [comment]
@ttowncompiled ping

**Comment by ttowncompiled** [comment]
Look at PR - #2573

**Pull request closed without merging**
