### PR TITLE
docs: add Angular Master website to resources list

### PR DESCRIPTION
**Pull request by kalbarczyk**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by kalbarczyk — COMMENTED** [review]
The course has the word "master" in its name.

**Comment by bob-watson** [comment]
It's a little awkward that he's built a brand around a term we're trying to avoid to be inclusive.

**Comment by kalbarczyk** [comment]
> It's a little awkward that he's built a brand around a term we're trying to avoid to be inclusive.

I don't quite understand? 

We also have 2 podcasts:

Angular Master Podcast and JavaScript Master Podcast.

https://anchor.fm/angular-master
https://anchor.fm/javascript-master

Is there any chance to add them to the site?

**Review by mgechev — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit b34320128dace397d64fbd6ff18fe1947239bc19.

**Pull request closed without merging**
