### PR TITLE
build(docs-infra): upgrade cli command docs sources to 4faa81e25

### PR DESCRIPTION
**Pull request by gkalpak**
[help/generate.json][1] has been updated.

[1]: https://github.com/angular/cli-builds/compare/a2129510d...4faa81e25#diff-61df84c0a3f1ea7ed21328ff328b5a23

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Before:

screen shot 2018-10-25 at 11 14 09


After:

screen shot 2018-10-25 at 11 14 22

etc...

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
CI error is inherited from master

**Comment by matsko** [comment]
@gkalpak please rebase

**Comment by gkalpak** [comment]
Rebased.

**Pull request closed without merging**
