### PR TITLE
chore(bundles): align content of System.register and UMD bundles

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Similar to https://github.com/angular/angular/pull/5830 but for System.register bundles

### CODE REVIEW

**Comment by jeffbcross** [comment]
@pkozlowski-opensource is the commit message supposed to be "adding"?

**Comment by pkozlowski-opensource** [comment]
Oh, actually I've meant `align` :-) Will update the commit message

**Comment by IgorMinar** [comment]
lgtm. please rebase.

**Comment by pkozlowski-opensource** [comment]
@vsavkin this is rebased and all green. Please merge. Thnx!

**Pull request closed without merging**
