### PR TITLE
docs: remove NG6999 error page.

### PR DESCRIPTION
**Pull request by JeanMeche**
`NGMODULE_VE_DEPENDENCY_ON_IVY_LIB` was a ViewEngine related error. This commit removes the doc page but keeps a redirection for older versions still throwing this error.

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]

**Review by atscott — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Comment by jessicajaniuk** [comment]
caretaker: the pre-rebase presubmit was green. This is safe to merge.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 525acbb165396a7463e877d4e2af9399674e4be0.

**Pull request closed without merging**
