### PR TITLE
docs: add browsers switch to CI test example

### PR DESCRIPTION
**Pull request by thomasturrell**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I presume there is currently an error in the documentation because the example does not work on a continuous integration server.

### CODE REVIEW

**Review by dgp1130 — APPROVED** [review]

**Comment by dgp1130** [comment]
Thanks @thomasturrell I think you'll need to update the commit message description to match [our conventions](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit). I think this should work:

```
docs: add browsers switch to CI test example
```

**Review by MarkTechson — APPROVED** [review]
Thanks for this contribution!

LGTM!

**Review by alan-agius4 — APPROVED** [review]
LGTM, thanks

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit a610eb160a133f4f647206aab726a3899cac47b8.

**Pull request closed without merging**
