### PR TITLE
chore(build): remove workaround now that we are on rxjs-beta.2

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by alexeagle** [comment]
Ping!

**Comment by alexeagle** [comment]
@jeffbcross :hibiscus:

**Comment by alexeagle** [comment]
This is now breaking me in google3.
@vikerman please LG, since Jeff seems busy.

**Comment by robwormald** [comment]
LGTM

**Comment by vikerman** [comment]
TAP Green

**Comment by vikerman** [comment]
@alexeagle - The Travis build keeps failing for this PR - can you check?

**Comment by vikerman** [comment]
Merge conflict when running mary-poppins - https://travis-ci.org/angular/angular/builds/113801191. Please rebase

**Comment by mhevery** [comment]
@alexeagle Can your rebase and get this green.

**Comment by jeffbcross** [comment]
Closing in favor of #7985

**Pull request closed without merging**
