### PR TITLE
Add default value for statusText. Fix #23334

### LINKED ISSUE #23334: HttpErrorResponse statusText always default to 'OK' regardless of statusCode
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When server response does not contain any statusText, [HttpErrorResponse.statusText](https://angular.io/api/common/http/HttpResponseBase#statusText) is [automatically set to `OK`](https://github.com/angular/angular/blob/5.2.9/packages/common/http/src/xhr.ts#L140) regardless of the status code.
Thus you can end up with `403 OK` error response for instance, which I believe is weird. In the [previous documentation](https://angular.io/api/http/Response#statusText) it was clearly stated that `OK` was the default value, but I'm not sure to understand the reason behind it -- an empty string would be less confusing I think.

## Expected behavior

Either the statusString should be left empty, or even better check for status code and either use the proper http status for it, or show `ok` only for success status code only (and.. something has to be done for others)?

## What is the motivation / use case for changing the behavior?

While debugging some 403 errors on a website, I looked at HttpErrorResponse object with a 403 OK status which made me think there was something going wrong with the server and/or the error handling, but actually that was not the error at all. I know that documentation states `Do not depend on this.`, but this is still misleading when you see that in logs IMO.

## Environment

<pre><code>
Angular version: 5.2.9, still applicable on latest version

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 59.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by bagage**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by bagage** [comment]
I signed it!

**Comment by AndrewKushnir** [comment]
Hi @bagage, sorry we didn't have a chance to review this PR sooner. The change looks good to me and if you're still interested in working on it, it'd be great if you could rebase it on top of the latest master. Thank you.

**Comment by bagage** [comment]
Glad to hear it @AndrewKushnir! Should be good to go now.

**Review by AndrewKushnir — APPROVED** [review]
@bagage thanks for updating the PR! The change looks good to me.

**Comment by AndrewKushnir** [comment]
@bagage, sorry, I just noticed that the commit message refers to ticket #23334 and mentions that it's resolved by this PR. It looks like there is more discussion happened in #23334, so while this change improves docs (which is great!) the #23334 would not be resolved. Could you please update the commit message (`git commit --amend`) to exclude the "Fix #23334" part? Thank you.

**Comment by bagage** [comment]
@AndrewKushnir done :)

**Comment by AndrewKushnir** [comment]
@bagage FYI this PR is now merged. Thank you for contributing to Angular!

**Pull request closed without merging**
