### PR TITLE
test(core): fix test with false-negative risk

### PR DESCRIPTION
**Pull request by yjaaidi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [X] Other... Please describe: fix test

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by atscott — CHANGES_REQUESTED** [review]
Could you change this instead to expect…toThrow?

**Comment by yjaaidi** [comment]
BTW, do you know why toThrow was not used there? Is just because the initial tests were written with an old version of Jasmine?

**Comment by yjaaidi** [comment]
Oh! I got it! Jasmine doesn't have Jest|Vitest's `await expect(promise).rejects....` async matchers.

**Comment by atscott** [comment]
> Oh! I got it! Jasmine doesn't have Jest|Vitest's await expect(promise).rejects.... async matchers.

It does have `expectAsync`. Knowing all these different APIs is always a struggle...

**Review by atscott — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 454d5e9c867e1898f996c9a2621154bf12d2aa7c.

**Pull request closed without merging**
