### PR TITLE
fix(NgZone): Pass the Chain to the error handler instead of a List

### PR DESCRIPTION
**Pull request by jbdeboer**

### CODE REVIEW

**Comment by vicb** [comment]
@jbdeboer there should be some description of the breaking change in the commit message.

We should also probably discuss how to handle that on the JS side ?

**Comment by jbdeboer** [comment]
I need to update the unit tests as well.

For Dart, the old API is confusing as every other error handler takes an error and a StackTrace.  For Chains specifically, this code was counterproductive as it is preventing users from, say, providing their own "terse" functions.

**Comment by IgorMinar** [comment]
@jbdeboer can you please make the requested changes?

**Comment by vsavkin** [comment]
Closing this. Please, reopen the PR once the commends are addressed.

**Comment by jbdeboer** [comment]
Sorry, committing to this project is more work than I expected.

Instead of this PR, I have opened the issues for you address: #6828

**Comment by jbdeboer** [comment]
And  #6829 for the actual breaking change.

**Pull request closed without merging**
