### PR TITLE
Update payload size on 10.1.x branch

### PR DESCRIPTION
**Pull request by atscott**
Update payload size changes from https://github.com/angular/angular/pull/38920 for patch branch.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
LGTM 👍

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: size-tracking

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: size-tracking

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: size-tracking

**Comment by mhevery** [comment]
merged as 38923

**Pull request closed without merging**
