### PR TITLE
docs: added missing 'next steps' section

### PR DESCRIPTION
**Pull request by 1heykal**
added missing 'next steps' section.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@1heykal I see you have multiple PRs adding this similar code. If you can group these into one PR, that'd be helpful.

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Review by jessicajaniuk — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
@1heykal You'll need to squash your commits down to 1 and reword your commit message to match lint rules. You've done that for the PR header already, but the commit message is what matters to lint.

**Comment by 1heykal** [comment]
@jessicajaniuk Done. Anything else?

**Review by jessicajaniuk — APPROVED** [review]

**Comment by dylhunn** [comment]
This doesn't merge cleanly into patch, so if you want it on the 16.2.x branch, you'll need a different rebase and a new PR. Merging into main though.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 4726203e0d0918532bd76bfacfd4720c1d2f54c0.

**Pull request closed without merging**
