### PR TITLE
docs: removed duplicate "compilerOptions" property

### PR DESCRIPTION
**Pull request by serpent5**
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Comment by serpent5** [comment]
@googlebot I signed it!

**Review by kapunahelewong — APPROVED** [review]
Perfect. Thank you, @serpent5!

**Comment by kapunahelewong** [comment]
Caretaker, this is a docs only change. Can you help us get it green? Please ping me if I can help. Thank you!

**Comment by gkalpak** [comment]
FWIW, this shouldn't have been merged into the patch branch too.

**Pull request closed without merging**
