### PR TITLE
feat(core): expose queries as signals

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
This commit exposes authoring functions for queries as signals thus making those generally available.

### CODE REVIEW

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by alxhub — APPROVED** [review]
Reviewed-for: public-api

**Review by devversion — APPROVED** [review]

**Review by JoostK — APPROVED** [review]
🥇

**Comment by pkozlowski-opensource** [comment]
caretaker note: I believe that G3 presubmit is "green"

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 43de097704fa621714e5d2c719540c34b130ee9f.

**Pull request closed without merging**
