### PR TITLE
fix(aio): group topbar into a single sidenav node when narrow

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Comment by gkalpak** [comment]
I like it (except for the fact that other than `Features` all other subitems are not highlighted and expanded when selected 😕)

**Comment by petebacondarwin** [comment]
> I like it (except for the fact that other than Features all other subitems are not highlighted and expanded when selected 😕)

The reason for this is that those nodes also appear in the Footer nav view, and that seems to get precedence. So they don't get highlighted in the TopBarNarrow nav view.

I'll create an issue and fix in a subsequent PR.

**Comment by petebacondarwin** [comment]
@IgorMinar - I have removed the "Docs" item from the "TopBarNarrow" view as requested. PTAL.

**Review by IgorMinar — APPROVED** [review]
Much better! thanks

**Pull request merged**
