### PR TITLE
docs-infra: aio CLI boolean options

### PR DESCRIPTION
**Pull request by petebacondarwin**
These are the changes based on offline discussions from 4 Oct 18.

Notably, we only show the "canonical" syntax for each option:

* the primary name of the option
* the list of values (including true/false for boolean)
* no visual indication of the default value

Then the default value and any aliases are listed at the end of the description.

Additionally, if the value (or list of values) is over 15 character long, then we move that to a new (indented) line, to prevent the description column from being squashed.

Here are some examples:

screen shot 2018-10-05 at 14 06 10

screen shot 2018-10-05 at 14 07 57

screen shot 2018-10-05 at 14 07 52

### CODE REVIEW

**Comment by Splaktar** [comment]
Looks much less confusing!

Should we consider 13 or 14 chars being the cutoff? 15 is a bit too long for a phone with width of 425px.

screen shot 2018-10-05 at 2 49 13 pm

Worse on an iPhone:
screen shot 2018-10-05 at 2 51 15 pm

**Review by Splaktar — COMMENTED** [review]
Looks much less confusing!

**Comment by petebacondarwin** [comment]
We are going to fix tables generally to be more responsive for mobile layouts in the not-too-distant future. So that should make that better, generally for this situation.

**Comment by jenniferfell** [comment]
I really like this. My only comment is that the blue italic looks like a hyperlink. And italic is used to mean something variable in other parts of the doc. Maybe just regular font?

**Review by jenniferfell — COMMENTED** [review]
See comment above.

**Review by Splaktar — APPROVED** [review]
LGTM

**Review by jenniferfell — APPROVED** [review]
LGTM

**Pull request closed without merging**
