### PR TITLE
docs: fix grammar in guide/defer

### PR DESCRIPTION
**Pull request by SahulKola**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #52897 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — COMMENTED** [review]
@SahulKola thanks for improving Angular docs! Could you please apply the same change to the `aio/content/guide/defer.md` file? Thank you.

**Comment by SahulKola** [comment]
Hey @AndrewKushnir, updated the changes in aio/content/guide/defer.md too. and squashed the commits.

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
**Caretaker note**: this PR is ready for merge, no additional reviews are required.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 7d00175daeb1fd73ac8e7c9539e87b1583d4e315.

**Pull request closed without merging**
