### PR TITLE
docs: New doc HTTP - Intercept requests and responses

### PR DESCRIPTION
**Pull request by trekladyone**
New doc extract from the original HTTP doc which is to be retired.

Note: this doc is a part of the Gummybears project.

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
@trekladyone This doc is looking for an internal link pointing to `#caching` that doesn't exist, which is causing CI to fail. Please take a look.

**Comment by jessicajaniuk** [comment]
@trekladyone Can you squash these commits into one commit?

**Comment by trekladyone** [comment]
Deleted broken links because the correct links are to docs that are not yet merged. After merging all HTTP docs, the links can be updated.

**Review by jessicajaniuk — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 9553a9a2a1a6ebb8f8103c35407c484ca7a50084.

**Pull request closed without merging**
