### PR TITLE
Expand scope of formatting to enforce formatting on more files

### PR DESCRIPTION
**Pull request by josephperrott**
See individual commits.

All `js`/`ts` changes in this change are the result of `clang-format` enforcing format on the code.

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: fw-i18n

The commit message scope should be `common` not `localize`.

**Review by devversion — APPROVED** [review]
LGTM. @josephperrott I'm assuming we can rely on the extract-cldr script outputting properly formatted files? I see it runs clang-format, so whenever we should re-generate the data, there should be no formatting changes?

**Review by atscott — APPROVED** [review]
We should give a heads-up ping to everyone before merging this.

Review-for: fw-core

**Comment by josephperrott** [comment]
@atscott Happy to announce, though it looks like this will not effect much outstanding work:

```
$ yarn -s ng-dev pr discover-new-conflicts 36940
Requesting pending PRs from Github
Retrieved 615 total pending PRs
Checking 147 PRs for conflicts after a merge of #36940
[========================================] ETA: 0s | 147/147

Result:
1 PR(s) which conflict(s) after #36940 merges:
    - 37263: Added the method addValidators and addAsyncValidators
```

**Comment by atscott** [comment]
> @atscott Happy to announce, though it looks like this will not effect much outstanding work:
> 
> ```
> $ yarn -s ng-dev pr discover-new-conflicts 36940

Oh, that's cool. Didn't know we had that! One thing I just thought of: could you update the required base sha so that we ensure PRs are formatted correctly?

**Comment by josephperrott** [comment]
@atscott will do in a follow up PR once we have the SHAs available from this PR merging.

**Pull request closed without merging**
