### PR TITLE
feat(upgrade): support NgModule class as an argument of the `downgradeModule` function

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit extends the logic of the `downgradeModule` function to support NgModule class as an argument. This is needed to simplify the API surface to avoid the need to resolve NgModule factory before invoking the `downgradeModule` method.

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — COMMENTED** [review]
:tada:

**Comment by AndrewKushnir** [comment]
@petebacondarwin FYI I've tested the code in g3 both as is as well as by modifying apps code to use the new codepaths (by using the factory-less NgModule reference). Everything looks good, so this PR is ready for the final review.  Could you please take a look when you get a chance? Thank you.

**Review by petebacondarwin — APPROVED** [review]
Great sleuthing about that test, which only should run in Ivy.

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Comment by AndrewKushnir** [comment]
[Global Presubmit #2](https://test.corp.google.com/OCL:406754360:BASE:406754469:1635746803109:821ead8d).

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

reviewed-for: public-api

**Review by IgorMinar — APPROVED** [review]
LGTM! Thanks!

Reviewed-for: public-api

**Comment by atscott** [comment]
This PR was merged into the repository by commit 34f990986cade3ce6b355354d1e2f6e5ec2f18ec.

**Pull request closed without merging**
