### PR TITLE
docs: update broken link in Bazel docs

### PR DESCRIPTION
**Pull request by Splaktar**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
- The link to the Bazel docs for NodeJS is broken (404).

Issue Number: N/A

## What is the new behavior?
- fix broken link to Bazel docs for NodeJS
- add link to debugging docs
  - source of the instructions above the link

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
N/A

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by kapunahelewong — APPROVED** [review]
LGTM. Thank you @Splaktar 🌟

**Comment by kapunahelewong** [comment]
merge assistance: global approval for docs changes

**Comment by AndrewKushnir** [comment]
Hi @Splaktar, there was a "PR target" label missing, so I merged this change to master only for now. If these changes are also required in patch branch, please create a separate PR and target patch branch. Thank you.

**Comment by Splaktar** [comment]
Just `master` is fine AFAIK.

**Pull request closed without merging**
