### PR TITLE
feat(core): type QueryList#changes strongly

### LINKED ISSUE #30296: QueryList#changes is not typed strongly
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core.

### Is this a regression?

No.

### Description

The type of `QueryList#changes` is `Observable<any>` ([link](https://github.com/angular/angular/blob/7.2.14/packages/core/src/linker/query_list.ts#L44)). Given that `QueryList` does have a type argument, the type should be `Observable<T[]>` as – at least AFAIK – this is the only thing that is ever emitted here.

Additionally, it is initialized as `EventEmitter` for no good reason and should probably be a `Subject` instead.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
7.3.6
</code></pre>

### PR DESCRIPTION
**Pull request by Airblader**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

`QueryList#changes` is typed as `Observable<any>`.

Issue Number: #30296

## What is the new behavior?

`QueryList#changes` is typed as `Observable<this>`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Airblader** [comment]
Regarding the failing Material unit test, what would you like me to do? It's an easy fix in Material (affecting only test code). The alternative is to use `Observable<QueryList<T>>` instead of `Observable<this>` (suggested by @trotyl), but the latter is in theory more accurate.

**Review by nutza249949 — APPROVED** [review]

**Comment by dannymcgee** [comment]
@Airblader Is this PR solely being held up by the `Observable<this>` vs `Observable<QueryList<T>>` issue?

**Comment by Airblader** [comment]
From my side, yes, but the lack of response for 1.5 years doesn't make me too hopeful that just going with the less accurate version would speed this up.

**Comment by Airblader** [comment]
I'm closing this now since I won't be interested in rebasing this anymore. Perhaps some day a Googler will stumble across this, it seems that their PRs get resolved in a matter of days rather than years, although it's a bit of a shame that a small, straight-forward improvement for type-safety could go ignored for so long.

**Comment by mgechev** [comment]
Hey @Airblader, we're sorry we didn't respond better and quicker to the PR. We're continually brainstorming how we could be more efficient in reviewing contributions, but it looks like we still have a long way to go.

We'll continue iterating on the process, and I hope we'll improve over time. Even though we might not be able to merge any improvement because of potential breaking changes, we'll work on improving our communication.

**Pull request closed without merging**
