### PR TITLE
Update counting.html DOM text reinterpreted as HTML

### PR DESCRIPTION
**Pull request by Shivam7-1**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
By using textContent, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML.

textContent is More Useful Instead of Using InnerText  By Using `textContent` over `innerText` enhances security by preventing potential vulnerabilities such as Cross-Site Scripting (XSS) attacks. `textContent` retrieves only the raw text content of an element, avoiding interpretation of HTML tags, thereby reducing the risk of malicious script injection and unintended content disclosure.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Shivam7-1** [comment]
Hi @JiaLiPassion Could You Please Review This PR 
Thanks

**Comment by Shivam7-1** [comment]
Hi @JiaLiPassion Could You Please Review This PR
Thanks

**Comment by Shivam7-1** [comment]
Hi @JiaLiPassion Could You Please Review This PR
Thanks

**Comment by Shivam7-1** [comment]
Hi @dylhunn Could You Please Review This PR 
Thanks

**Comment by JoostK** [comment]
There is no such risk associated with `innerText`, that's only the case with `innerHtml`. [Here's more details](https://www.freecodecamp.org/news/innerhtml-vs-innertext-vs-textcontent/#how-to-update-content-with-innerhtml-innertext-and-textcontent). Closing as these are essentially the same in this context.

**Pull request closed without merging**
