### PR TITLE
refactor(core): Remove deprecated DynamicComponentLoader

### PR DESCRIPTION
**Pull request by chuckjaz**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

The core contains an deprecated class, `DynamicComponentLoader` which needs to be removed.

**What is the new behavior?**

The deprecated class `DynamicComponentLoader` is removed.

**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

The deprecated class `DynamicComonentLoader` was removed.

**Other information**:

BREAKING CHANGE: previously deprecated DynamicComponentLoader was removed; see deprecation notice for migration instructions.

### CODE REVIEW

**Comment by vikerman** [comment]
Lots of breakages in Google.

**Comment by chuckjaz** [comment]
What is the CL for the breakage?

Chuck.

**Comment by EricTetz** [comment]
Where does one find the referenced "migration instructions" for this change?

**Comment by vasuneet** [comment]
i have used dynamiccomponent loader . it is deprecated now. what need to be used in place of this.

**Comment by IgorMinar** [comment]
Please take a look at the ComponentFactoryResolver that allows you to get
hold of a ComponentFactory that you can then use to append to any
ViewContainer of your choosing.

**Comment by peter-bozovic** [comment]
I spent some time searching how to use new ComponentFactoryResolver so I will share my findings.

Most websites show how to use it to load component into ViewContainer:
```
import {Component, ViewChild, ViewContainerRef, ComponentFactoryResolver} from '@angular/core';
import {ChildComponent} from "./child/child.component";

@Component({
  selector: 'app-root',
  template: '<div #parent></div>'
})
export class AppComponent {
  @ViewChild('parent', {read: ViewContainerRef})
  parent: ViewContainerRef;
  constructor (private componentFactoryResolver: ComponentFactoryResolver) {
  }
  createChildComponent() {
    const childComponent = this.componentFactoryResolver.resolveComponentFactory(ChildComponent); 
    this.parent.createComponent(childComponent);
}
}
```
But I needed the way to load components into DOM element that is generated by JavaScript (ex: div with specific id)
```
import {Component, ComponentFactoryResolver, Injector, ApplicationRef} from '@angular/core';
import {ChildComponent} from "./child/child.component";

@Component({
  selector: 'app-root',
  template: '<div id="parent"></div>'
})
export class AppComponent {
  constructor (private componentFactoryResolver: ComponentFactoryResolver, private injector: Injector, private appRef: ApplicationRef) {
  }
  createChildComponent() {
    const childComponent = this.componentFactoryResolver.resolveComponentFactory(ChildComponent);
    var childComponentRef = childComponent.create(this.injector, null, '#parent');
    (<any>this.appRef)._loadComponent(childComponentRef);
  }
```
This kinda uses hacky way to initialize the component with appRef._loadComponent, but works.

Hope this helps others that have similar problem, and if anybody have better solution, please share ...

**Pull request merged**
