### PR TITLE
docs: uwu

### PR DESCRIPTION
**Pull request by JeanMeche**
🙃

### CODE REVIEW

**Comment by mgechev** [comment]
There's a bit of a rough initial flicker when you open the page. We'd like to show the right logo as part of the prerendered page. I guess this gets a little tricky without redirects.

**Review by bencodezen — APPROVED** [review]
This is great! I was actually thinking of doing this too. Thanks for the PR!

**Comment by AndrewKushnir** [comment]
Waiting for an LGTM from @mgechev or @twerske (added the "blocked" label for now).

**Review by mgechev — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 7287fefe7a750a1ae584d9bb9e0378aa047b5d95.

**Pull request closed without merging**
