### PR TITLE
docs: added `missingControlFlowDirective` extended diagnostics details page

### PR DESCRIPTION
**Pull request by AndrewKushnir**
## PR Type
What kind of change does this PR introduce?

- [x] Documentation content changes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by pkozlowski-opensource — APPROVED** [review]
reviewed-for: public-api

**Review by bob-watson — APPROVED** [review]
LGTM

reviewed-for: global-docs-approvers

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 4bff346240079c3671a508a9a18e1a0e1517461b.

**Pull request closed without merging**
