### PR TITLE
feat(core): introduce @BaseView and @View - WIP, do NOT merge

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Here is WIP for @BaseView / @View annotations to kick off discussion on where those annotations should be processed in Dart. 

The "problem" is that annotations are const classes so I can't simply concatenate directive arrays in the directive itself :-( So I'm not sure what is the best place to add all the `coreDirectives`. More specifically, I'm not sure what is the role of Dart transformers in the entire process....

@tbosch @kegluneq  any help here would be much appreciated

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
So, after pondering different solutions, I'm not sure how to add different processing for BaseView and View in Dart :-/ I will need some help from one of the Dart gurus, I'm afraid....

**Comment by pkozlowski-opensource** [comment]
The basic problem is that I can add core directives in the `@View` annotation itself as it is a constant class which means that I can't (?) concatenate coreDirectives with user-supplied directives in the annoation constructor....

**Comment by mhevery** [comment]
So I thought you could do this:

```
class NgIf{}
class MyClass{}

class BaseView {
  final List directives;
	const BaseView(this.directives);
}

const ngCore = const [NgIf];
class View extends BaseView {
	const View(directives): super(const [ngCore, directives]);
}

main() {
  return const View(const [MyClass]);
}
```

But it turns out that does not work. :-( Will check with dart team.

**Comment by pkozlowski-opensource** [comment]
Yeh, I was counting on a 15-minutes fix as well :-) What is causing problems in:

```javascript
class View extends BaseView {
    const View(directives): super(const [ngCore, directives]);
}
```
is the `directives` argument as it is known only during runtime and I could find any way of marking Dart's function argument as 'const' (don't even know if this makes sense...).

Now, I'm looking into other places for plugging this logic, but if I do this during compilation time (ex. in https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/template_resolver.ts) I think that I might be killing tree-shaking...

**Comment by mhevery** [comment]
But this hack works:

```
class NgIf{}
class MyClass{}

class BaseView {
  final List directives;
	const BaseView(this.directives);
}

const ngCore = const [NgIf];
class View extends BaseView {
	const View(directives): super(directives);
  get directives {
    return [ngCore, super.directives];
  }
}

main() {
  print(const View(const [MyClass]).directives);
}
```

**Comment by kegluneq** [comment]
Note that right now this will probably fail in transformed mode -- running the compiler requires metadata for the directives referenced by the `View` and aliasing confuses the transformer (especially since the alias could exist anywhere in the program and a requirement of the transformer was locality).

This feature request is being tracked in https://github.com/angular/angular/issues/1747

For reflective code, Misko's hack is the best solution I'm aware of. Here is a slight modification that also works:
```
class NgIf{}
class MyClass{}

class BaseView {
    final List directives;
        const BaseView(this.directives);
}

const ngCore = const [NgIf];
class View extends BaseView {
  final List _directives;
  const View(this._directives): super(ngCore);

  List get directives => [super.directives, this._directives];

  @override
  String toString() => 'View with $directives';
}

main() {
    print(const View(const [MyClass]));
}
```

**Comment by pkozlowski-opensource** [comment]
OK, so the hack proposed by @mhevery seems to be "working" - that is, allows me to move one srep further. I've got still several JS / Dart test failures - digging into it

**Comment by pkozlowski-opensource** [comment]
Hmm, so, after a hack proposed by @mhevery I'm bumping into circular dependencies for JS modules. Indeed, we now've got: View->Directives->View. There is a lot more going on in this chain (we've got annotations and decorators generation, intermediate files etc.), but the crux is here.

I'm pulling my hairs out as I'm not sure how to break this cycle - we can't use usual tricks. 

Question: are we planning to remove annotations and traceur in the near future? The current setup is quite complex and it would be much easier to investigate / fix pbs with a simpler system....

**Pull request closed without merging**
