### PR TITLE
feat(router): enforce usage of ... syntax for parent to child component routes

### PR DESCRIPTION
**Pull request by matsko**

### CODE REVIEW

**Comment by btford** [comment]
I'll take a look after lunch :cat2:

**Comment by btford** [comment]
@matsko – can you fix the formatting issues?

**Comment by btford** [comment]
Other than the one comment, LGTM. Fix that and get CI passing, then merge!

**Comment by btford** [comment]
I'm rebasing and merging

**Comment by btford** [comment]
@matsko – rebasing this ended up being a bit more involved – can you rebase and merge this?

**Comment by btford** [comment]
LGTM, merge when green :+1:

**Comment by matsko** [comment]
Merged as https://github.com/angular/angular/commit/2d2ae9b8d88f99381852a5e678afb5f292234e7d

**Pull request closed without merging**
