### PR TITLE
fix(router): Update `createUrlTreeFromSnapshot` to tolerate some ambiguity with empty paths

### PR DESCRIPTION
**Pull request by atscott**
See individual commits

### CODE REVIEW

**Comment by atscott** [comment]
[TGP](https://fusion2.corp.google.com/presubmit/tap/501845023/OCL:501845023:BASE:501839543:1673635659931:1b69e8be/targets)

**Review by AndrewKushnir — APPROVED** [review]

**Comment by atscott** [comment]
caretaker note: Please merge and sync on its own.

**Comment by AndrewKushnir** [comment]
FYI, adding the "blocked" label for now to avoid merging the PR until we get a confirmation from one of the teams.

**Comment by AndrewKushnir** [comment]
FYI, got LGTMs from internal teams, moving forward with the merge.

**Pull request closed without merging**
