### PR TITLE
docs: add Smart UI to UI Components section in resources

### PR DESCRIPTION
**Pull request by bmarkov**
docs(aio): Added resources to UI Components. Added Smart Angular Components

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by brandonroberts — DISMISSED** [review]
Update git commit message to `docs: Add Smart UI to UI Components section in resources`

**Comment by bmarkov** [comment]
Updated the Git commit message. Thank you.

**Comment by brandonroberts** [comment]
@bmarkov The lint check is still failing because you're original commit with the invalid commit message is still present. Will you squash your commits down to one commit with the correct message `docs: add Smart UI to UI Components section in resources`

Thanks

**Comment by bmarkov** [comment]
removed last 2 commits and left just the first one. Hope it is ok now. 

Thank you.

**Comment by bmarkov** [comment]
> @bmarkov The lint check is still failing because you're original commit with the invalid commit message is still present. Will you squash your commits down to one commit with the correct message `docs: add Smart UI to UI Components section in resources`
> 
> Thanks

updated the commit message to the requested one.

**Comment by StephenFluin** [comment]
I reviewed the Angular references in the docs and ran into a couple of things.

1. Can you verify that the Edit in Codepen links work for Angular code?  I get an error when I click on them. `Uncaught TypeError: Cannot read property '1' of null
    at submitToCodepen (demos.js:654)
    at HTMLAnchorElement.onclick ((index):2386)`

2. Can you verify that your forms implement controlvalueaccessors so that they can be used with Angular Forms?

In general we aren't adding generic web components, but because you have Angular dedicated documentation, if you have added integrations with Angular (such as Contol Value Accessors), then we'd be happy to list you.

**Comment by StephenFluin** [comment]
From the link you shared, it looks like you don't provide Angular Components and developers are responsible for creating integrations. Is that something that you could do? It is our intention that we don't list any bare web components in our resources page, as there are many great listings of web components across the web.

**Comment by bmarkov** [comment]
Hi Stephen,

The topic I referred shows how to use our components with ControlValueAccessor. That is what you asked for.

In general, all components can be used with Angular and bound to Component properties without any special code.

Example:

```javascript
    <smart-check-box
          [checked]="value" 
          (change)="onChange($event)" 
          (keyup)="onChange($event)">
        
        </smart-check-box>
```

Of course, with the time we will put more such topics, more components, etc.

**Comment by StephenFluin** [comment]
Sorry if I created any confusion. I originally thought these were Angular components, not simply web components. We appreciate you creating documentation that will help Angular developers take advantage of web components and build their own ControlValueAccessors, but these components would probably make more sense on https://www.webcomponents.org/.

In our resources page, we only list UI libraries with out of the box Angular integration.

**Comment by bmarkov** [comment]
Ok, We implemented 3 Angular Components - Smart.RadioButton, Smart.CheckBox and Smart.ProgressBar. The link to them is https://www.htmlelements.com/docs/angular-components/.

**Comment by StephenFluin** [comment]
Can you update the link to this new URL?

**Comment by bmarkov** [comment]
The url is updated.

**Comment by StephenFluin** [comment]
Content looks okay, can you squash your commits?

https://twitter.com/stephenfluin/status/1009904095073718275?lang=en

**Comment by bmarkov** [comment]
> Content looks okay, can you squash your commits?
> 
> https://twitter.com/stephenfluin/status/1009904095073718275?lang=en

done

**Review by StephenFluin — APPROVED** [review]

**Comment by bmarkov** [comment]
Anything more from me?

**Review by StephenFluin — APPROVED** [review]

**Review by gkalpak — APPROVED** [review]

**Pull request closed without merging**
