### PR TITLE
refactor(core): add batching for defer blocks with `on idle` conditions

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit updates runtime logic of defer blocks to schedule a single `requestIdleCallback` for a group of defer blocks created within a single change detection cycle (for example, as a result of a defer block being defined in a for loop).

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by AndrewKushnir** [comment]
**Caretaker note**: there was a merge conflict in a spec file. No changes were made to the main code, so we can reuse a [previous presubmit status](https://fusion2.corp.google.com/presubmit/568116661/OCL:568116661:BASE:568116708:1695621327353:b0e9dd98/targets). This PR is ready for merge.

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:568328675:BASE:568328702:1695678120788:ba99cb8f).

**Comment by AndrewKushnir** [comment]
[Presubmit #2](http://test/OCL:568328675:BASE:568583133:1695749738944:d33df3c6).

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 4b38e9a1abd28f601aa598563ed6fe055eb5c353.

**Pull request closed without merging**
