### PR TITLE
PR target: Fixed doc for getLocaleCurrencyName from USD to US Dollar

### PR DESCRIPTION
**Pull request by rodrioce**
#23321 Fixed doc for getLocaleCurrencyName from USD to US Dollar

### CODE REVIEW

**Comment by vicb** [comment]
@rodrioce what you need to do if you want this PR merged:
- sign the CLA with the email you have used for this PR (your `git config`),
- format the code (run `gulp format`),
- make sure the commit message follow our conventions (see `CONTRIBUTING.md`).

Sounds like a lot but let us know if you have any questions.

Thanks

**Comment by rodrioce** [comment]
I signed it!

**Comment by rodrioce** [comment]
@vicb Thanks, can't do it now, will finish it latter

**Comment by vicb** [comment]
Please open a new PR when you get a chance.

**Pull request closed without merging**
