### PR TITLE
docs(docs-infra): mixin generated same multiple css

### PR DESCRIPTION
**Pull request by MeAkib**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
SCSS Mixin Generating same multiple CSS and second one overrides first one

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

SCSS Mixin Generating same multiple CSS and second one overrides first one
Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@crisbeto do you see any particular reason to have a font-size defined like this (before changes proposed in this PR)?

**Review by crisbeto — APPROVED** [review]
This pattern can be used for the cases where a browser doesn't support a specific CSS declaration. I don't think that's the case here so my best guess is that it was a messed up merge conflict. LGTM.

**Comment by AndrewKushnir** [comment]
@crisbeto thanks for looking into this!

@akib1997 thanks for creating this PR, I'm adding it to the merge queue 👍

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit fe1a50c63f536a9802c1310f64c4cc6612bf51ca.

**Pull request closed without merging**
