### PR TITLE
docs: use node 10 on travisci

### PR DESCRIPTION
**Pull request by ersimont**
Fixes the error `error @angular-devkit/build-angular@0.800.0-rc.3: The engine "node" is incompatible with this module. Expected version ">= 10.9.0".`

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

There is an error using `8.0.0-rc.3` when following these instructions on travis:
```
error @angular-devkit/build-angular@0.800.0-rc.3: The engine "node" is incompatible with this module. Expected version ">= 10.9.0".
```

Issue Number: N/A

## What is the new behavior?

No error.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by ersimont** [comment]
I signed it

**Comment by brandonroberts** [comment]
Thanks for the PR @ersimont  You must [Sign the CLA](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#cla) before this PR can move forward.

**Comment by ersimont** [comment]
I did sign it. When I go back to [the link](https://cla.developers.google.com/clas), it shows me I already signed it. Something broken with the integration, perhaps? Maybe a race condition, and now that I comment much later after I sign it will pick it up ...

**Comment by brandonroberts** [comment]
@ersimont the email address in the git commit needs to match the email you used to sign the CLA. Check there first. If you edited straight from GitHub, check that your registered GitHub email matches the one you signed for the CLA.

**Comment by brandonroberts** [comment]
@ersimont any progress on resolving the CLA signature?

**Pull request closed without merging**
