### PR TITLE
refactor(core): export additional methods from primitives/signals

### PR DESCRIPTION
**Pull request by alxhub**
Export `producerIncrementEpoch` which was missing before, as well as a new `runPostSignalSetFn` helper. These changes make it easier to write `signal`- like utilities which don't use the `createSignal` abstraction.

### CODE REVIEW

**Review by atscott — APPROVED** [review]
reviewed-for: public-api, fw-core, fw-primitives

**Comment by alxhub** [comment]
Caretaker: pullapprove is 😢 but this PR is 😄

**Review by thePunderWoman — APPROVED** [review]
reviewed-for: public-api, primitives

**Comment by alxhub** [comment]
Caretaker: no further approvals needed

**Comment by thePunderWoman** [comment]
@alxhub A quick reminder that any PR that has the `requires: TGP` label needs a comment that begins with `TESTED=` and either the TGP link or the reason why a TGP isn't needed in that comment.

**Comment by thePunderWoman** [comment]
TESTED=see @alxhub's comment above.

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit 46b029226193930fc81e481f85573d67d4ddf4ad.

The changes were merged into the following branches: main, 18.0.x

**Pull request closed without merging**
