### PR TITLE
feat(angular2.version): Added a version attribute to public api

### LINKED ISSUE #1357: Output a version number
Hi.

In AngularJS 1.x, `console.log(angular.version);` to output the following.

```
{
  full: "1.3.x",
  major: 1,
  minor: 3,
  dot: x,
  codeName: "codeName"
}
```

I want you to adopt also in Angular 2 this feature for utility development. For example,

``` js
import * as angular2 from 'angular2/angular2';
console.log(angular2.version);
```

```
{
  full: "2.0.0-alpha.n",
  major: 2,
  minor: 0,
  dot: 0,
  codeName: "codeName"
}
```

Thanks.

### PR DESCRIPTION
**Pull request by danrasmuson**
You can now reference the current version of angular2, "import {version} from 'angular2/angular2'"

Closes #1357

### CODE REVIEW

**Comment by danielrasmuson** [comment]
I based this commit on how angular1 supported the version attribute. In the build system it replaces "NG_VERSION_.." with the current version. The new gulp task that accomplishes this is called, "build.version". However, could someone comment on the best time/place to run the "build.version" task?

**Comment by IgorMinar** [comment]
I think that this should happen as part of our broccoli pipeline. In this
the replacement is happening too late which makes it expensive and I don't
think it even applies to the dart build.

**Comment by danielrasmuson** [comment]
Thanks for the feedback @IgorMinar. I moved the build process to the broccoli pipeline and added the task to the browser tree and the dart tree.

Additionally, I would like to note this pull request adds `version` to the public api, [which needs clearance](https://github.com/angular/angular/blob/master/modules/angular2/test/public_api_spec.ts#L22).

Happy to hear any feedback.

**Comment by danielrasmuson** [comment]
@IgorMinar, I just refreshed this pull request and made sure the tests are passing.

**Comment by IgorMinar** [comment]
we want this feature, but it's not critical for beta.0, punting until beta.1

**Comment by mhevery** [comment]
@IgorMinar what is your plan with this. Can this go in, or does it need more work?

**Comment by IgorMinar** [comment]
there is a lot of obsolete stuff in this PR copied from Angular 1 that doesn't apply to Angular 2.

currently this is a nice to have feature - it is not required. we can add it later if there is a good reason for it.

**Pull request closed without merging**
