### PR TITLE
feat(platform-server): bump Domino to v2.0

### PR DESCRIPTION
**Pull request by CaerusKaru**
BREAKING CHANGE:

* Bump the dependency on Domino to 2.0 to resolve issues with
  namespacing

### CODE REVIEW

**Comment by vikerman** [comment]
Please follow instructions at https://github.com/angular/angular/blob/master/yarn.lock.readme.md to actually update the dependency. And then the tests would run against the newer version

**Review by vikerman — CHANGES_REQUESTED** [review]
Please follow instruction at https://github.com/angular/angular/blob/master/yarn.lock.readme.md to update dependencies

**Comment by CaerusKaru** [comment]
@vikerman Fixed

**Review by vikerman — APPROVED** [review]

**Comment by vikerman** [comment]
Just to clarify - There is no API breakages from Domino - but they upped their major version.

**Review by mhevery — APPROVED** [review]

**Pull request closed without merging**
