### PR TITLE
docs: typo in testing component with dependencies

### LINKED ISSUE #36210: Docs: typo in the testing section, components with async service
# 📚 Docs or angular.io bug report

### Description

There is a typo in the next sentence:

And in some case, we don't want to trigger the new **maco** task

We mean, _macro_, don't we?

### What's the affected URL?**
https://angular.io/guide/testing#component-with-a-dependency

## 🔥 Exception or Error
<pre><code>

</code></pre>

### PR DESCRIPTION
**Pull request by Fouzyyyy**
Fixes #36210

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The current sentence looks like: And in some case, we don't want to trigger the new **maco** task

Issue Number: #36210

## What is the new behavior?

maco will be replaced by macro.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Thx, @Fouzyyyy :+1:

**Review by gkalpak — CHANGES_REQUESTED** [review]
@Fouzyyyy, please add `Fixes #36210` at the bottom of the commit message as described in our [commit message guidelines][1].

[1]: https://github.com/angular/angular/blob/4419907b08948b9f7b3b835658d319a4573ea374/CONTRIBUTING.md#commit

**Comment by Fouzyyyy** [comment]
@gkalpak very happy to help, someone needs to trigger again the failing builds/scripts in `circleci`

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
**merge-assistance:** Global approval for this docs-only change.

**Pull request closed without merging**
