### PR TITLE
build: allow "zone.js" as scope for commit messages

### PR DESCRIPTION
**Pull request by devversion**
Adds `zone.js` as valid scope for commit messages. This
is necessary because the `zone.js` repository has been
moved into the mono-repo and future changes should be
categorized properly through commit messages.

Currently the pre-commit git hook or CircleCI will fail when
`zone.js` is used as commit scope.

### CODE REVIEW

**Review by filipesilva — APPROVED** [review]

**Comment by gkalpak** [comment]
Should `zone.js` changes show up in the main changelog?

**Review by josephperrott — APPROVED** [review]

**Comment by josephperrott** [comment]
@IgorMinar Do you want `zone.js` to be in the main changelog?

**Comment by josephperrott** [comment]
@gkalpak @devversion 

I spoke with Igor,  zone.js is going to continue have its own `CHANGELOG.md` in its directory (`packages/zone.js/CHANGELOG.md`).  It will also be on its own release cadence so we don't want to link the changes to the rest of the repo too tightly.

The commit/PR lint/styling rules are the same, so this change should be commited.  We should also ensure that `zone.js` changes do not appear in the main `angular/angular` repo changelog.

**Review by gkalpak — APPROVED** [review]
Could you also add it to [CONTRIBUTING.md#scope][1]?

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#scope

**Comment by devversion** [comment]
@gkalpak Fair point. Looks like `ivy` isn't there either. Even though it might be temporary, it's still helpful for contributing.. so I'll add that one too.

**Pull request closed without merging**
