### PR TITLE
fix(animations): implement getPosition in browser animation builder

### LINKED ISSUE #18891: AnimationPlayer.getPosition always returns zero
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

AnimationPlayer.getPosition() always returns 0

## Expected behavior

getPosition() should return the current 0% of the animation inferred in the [API docs](https://angular.io/api/animations/AnimationPlayer) 

## Minimal reproduction of the problem with instructions
Create an Animation programatically such as:
<pre><code>
createAnimation(){
  let a = this._builder.build([
    animate('1000ms', keyframes([
      style({ transform: 'translate3d(0px, 0px, 0px)', offset: 0.0 }),
      style({ transform: 'translate3d(100px, 0px, 0px)', offset: 1.0 }),
    ]))
  ]);
  this.animationPlayer = a.create(this.domNode);
  this.animationPlayer.play();
  setTimeout(this.pauseAnimation.bind(this), 500);//half animation time
}

pauseAnimation(){
  this.animationPlayer.pause();
  console.log(this.animationPlayer.getPosition());//excepting ~50 to be printed
}
</code></pre>

[Live example](https://plnkr.co/edit/naPUCFOJNAa4SS9SeEgN?p=preview)
## Environment

<pre><code>
Angular version: 4.3.6
@angular/cli: 1.3.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.4
- Platform:  Mac
</code></pre>

### LINKED ISSUE #23785: AnimationGroupPlayer getPosition() always zero
https://github.com/angular/angular/blob/d0ccf5f1697c1c0d4e3c8ea7a25f3c87a239df7e/packages/animations/src/players/animation_group_player.ts#L127

```
    function () {
        var /** @type {?} */ min = 0;
        this.players.forEach(function (player) {
            var /** @type {?} */ p = player.getPosition();
            min = Math.min(p, min);
        });
        return min;
    };
```

IS THIS A BUG ???

when min = 0, it always 0 unless player.getPosition() < 0

maybe like this :  `var min = 1`

### PR DESCRIPTION
**Pull request by mhevery**
Accidently closed #28264 re-opening it here.

Forward `getPosition` to `animation_group_player`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by cgatian** [comment]
We have been waiting for this! This is the first contribution from the Hyland team. We are going celebrate when this is merged.

Good job @literalpie

**Comment by literalpie** [comment]
@googlebot I consent.

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:346138975:BASE:346139022:1607369344066:7c6c0ee6)

**Comment by literalpie** [comment]
I see that the presubmit check is failing. Is there anything I can do to help?

**Comment by mhevery** [comment]
MERGE_ASSISTANCE: This PR has already been approved in https://github.com/angular/angular/pull/28264 (and accidently closed) This will be merged without further approval.

**Comment by literalpie** [comment]
@mhevery was this unintentionally closed again?

**Comment by petebacondarwin** [comment]
@literalpie - no it was merged by our tooling which github doesn't understand, so we close the PR directly.

**Comment by literalpie** [comment]
Cool, thank you!

**Comment by JoostK** [comment]
As a matter of fact this [has already been released in 11.0.4](https://github.com/angular/angular/blob/master/CHANGELOG.md#1104-2020-12-09) :)

**Pull request closed without merging**
