### PR TITLE
release: bump Angular DevTools version to 1.0.13

### PR DESCRIPTION
**Pull request by dgp1130**

### CODE REVIEW

**Comment by JeanMeche** [comment]
Can we also ship/merge #54912 with this releases ?

**Review by AleksanderBodurri — APPROVED** [review]

**Comment by dgp1130** [comment]
> Can we also ship/merge #54912 with this releases ?

This is focused just on getting a usable Firefox build at all which seems to require a version bump at this stage. It doesn't really include any meaningful changes from 1.0.12.

I know that PR has been sitting around for a bit, I'm still catching up on things after `ng-conf` and multiple weeks of summits. I'll try to take a look at that this week.

**Review by JeanMeche — APPROVED** [review]
Ok, fine for me, lets go !

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 5f859727e242331de93775c7ee5e054eb08654e9.

**Pull request closed without merging**
