### PR TITLE
fix(common): invalid ImageKit transformation

### PR DESCRIPTION
**Pull request by tanoabeleyra**
`q-auto` is an invalid/unsupported transformation and should not be used

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The `ImageLoader` for ImageKit is using an invalid/unsupported transformation (`q-auto`).
Being that I could not find any mention of this transformation in [the official documentation](https://docs.imagekit.io/features/image-transformations/resize-crop-and-other-transformations#quality-q), I contacted ImageKit's support and they said:
> q-auto while would result in different sizes because of some internal implementations, being an unsupported, undocumented feature, it should not be used in any application.

Issue Number: N/A

## What is the new behavior?
The `q-auto` invalid transformation is not used. Instead, we rely on the default quality value from ImageKit's dashboard, which unless modified is 80 (`q-80`).

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Unless modified (and if not overwritten via URL), ImageKit applies the following transformations:

Captura de pantalla 2023-02-25 a las 1 07 30

- Automatic format (`f-auto`)
- Quality = 80 (`q-80`)

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
Hi @khempenius, could you please take a look at this change when you get a chance? Thank you.

**Comment by AndrewKushnir** [comment]
@tanoabeleyra thanks for creating a PR! It looks like you need to sign a CLA ([see an auto-generated comment above](https://github.com/angular/angular/pull/49201#issuecomment-1444811275)) before we can proceed with the review. Could you please sign the CLA when you get a chance? Thank you.

**Comment by tanoabeleyra** [comment]
Hi @AndrewKushnir. I already signed the CLA but it failed on the first try because the email was not my primary one.
It seems to be good after pushing the commit once again with the right email. Please tell me otherwise.

> imagen

https://github.com/angular/angular/pull/49201/checks?check_run_id=11590617764

**Comment by AndrewKushnir** [comment]
// cc @atcastle

**Review by atcastle — APPROVED** [review]
LGTM

**Review by AndrewKushnir — APPROVED** [review]
@tanoabeleyra thanks for improving NgOptimizedImage directive!

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:513125990:BASE:513126003:1677647565823:741ed67e).

**Review by AndrewKushnir — APPROVED** [review]

**Pull request closed without merging**
