### PR TITLE
fix(forms): Fix dynamic change of reactive form

### LINKED ISSUE #26998: Dynamically changing reactive forms throws a registerOnChange error
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[   ] feature request
[   ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Changing a reactive form template fails. When replacing the form, it throws an error: `ERROR TypeError: control.registerOnChange is not a function`

**Expected behavior**

It should not throw any error... and should change the template

**Minimal reproduction of the problem with instructions**

http://next.plnkr.co/edit/vh1HCo2WrwNgr95G?open=lib%2Fapp.ts&deferRun=1

Click on "new template" and check the console

**Please tell us about your environment:**

NodeJS 8 running on Windows 10

* **Angular version:** 6.0.9

* **Browser:** Chrome 70 64bit

* **Language:** Typescript

### PR DESCRIPTION
**Pull request by natcohen**
Closes #26998

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #26998

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by natcohen** [comment]
I signed it!

**Comment by natcohen** [comment]
@kara @IgorMinar @mhevery @jenniferfell Could you please merge this? It passes all the tests and fixes a 2 years old bug (https://github.com/angular/angular/issues/14376). Thanks for your help!

**Comment by alfaproject** [comment]
This won't be merged until you add tests and sign the CLA (;

**Comment by natcohen** [comment]
@alfaproject I have signed the cla and would be happy to add a test but I don’t know how it works and what to test!

**Comment by natcohen** [comment]
@kara @IgorMinar @mhevery @jenniferfell Can someone have a look why I'm not getting the CLA? I have signed it and would really like to move forward with this issue since it's been already 2 years!

**Comment by sarunint** [comment]
According to [raw commit](https://github.com/angular/angular/commit/81fe32246fbd3c6117b7eec4945c9564d9b975c8.patch), it seams that the email address used to commit is not the email address that you used to sign the CLA, it should be that email instead of `natcohen@users.noreply.github.com`. That's why the CLA is failed.

**Comment by natcohen** [comment]
@sarunint Got it! Seems like it was because I ticked the "keep my email private" box Github used this address. Can you please check again? Thanks!

**Comment by sarunint** [comment]
No, I think you need to do `git commit --amend --reset-author` and then `git push -f`.

**Comment by natcohen** [comment]
@sarunint Since I modify the files in Github, I have created a new PR: https://github.com/angular/angular/pull/27246

Thank you very much for your help!

**Pull request closed without merging**
