### PR TITLE
docs(docs-infra): first-app-lesson typo fixes

### PR DESCRIPTION
**Pull request by architect254**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, can you drop the merge commit, rebase on main and squash your commits ?

**Comment by architect254** [comment]
> Hi, can you drop the merge commit, rebase on main and squash your commits ?

@jessicajaniuk, Im not sure I know how to do that. Im a noob in git. Could you guide me through. or atleast give me the git command

**Comment by JeanMeche** [comment]
Take a look at "interactive rebase" (`git rebase -i`) there is extensive documentation on the web.

**Comment by jessicajaniuk** [comment]
I'm going to close this PR for now since there's been no activity and now has multiple file conflicts. Feel free to open a new PR if you'd like to see these changes land.

**Pull request closed without merging**
