### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by alwye**
Just fixed a tiny typo :)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by alwye** [comment]
@googlebot I signed it!

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by AndrewKushnir** [comment]
Hi @alwye, thanks for creating this PR and improving Angular docs 👍 

Could you please update the commit message to include a bit more info on the change (currently it says `docs: describe your change...`)? For example:

```
docs: fix typo in the Router guide
```

Thank you.

**Comment by alwye** [comment]
Opened a new PR with the fixed commit message: #42455

**Pull request closed without merging**
