### PR TITLE
refactor(ivy): migrate content spec from render3

### PR DESCRIPTION
**Pull request by cexbrayat**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?

Migrate the remaining `render3/content_spec.ts` to acceptance (some JS block ones were already migrated with `ngIf`).

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by cexbrayat** [comment]
Note that the failures in `test_ivy_aot` are potentially real issues. It needs to be sorted out before merging.

**Comment by AndrewKushnir** [comment]
@cexbrayat thanks for the update. I've add the "cleanup" label to this PR to make sure it's not merged. Please update this thread once the problem is resolved, so we can change labels back to put this PR into the merge queue. Thank you.

**Comment by cexbrayat** [comment]
The issues surfaced by this PR (resulting in failures in `test_ivy_aot`) were fixed by #32548 . This PR has been rebased on the fix, is now green and can be merged.

**Comment by AndrewKushnir** [comment]
Thanks for the update @cexbrayat, I've added "merge" label to put this PR into the merge queue.

**Pull request closed without merging**
