### PR TITLE
docs(localize): change dependencies to devDependencies in document

### PR DESCRIPTION
**Pull request by minahmoghadam**
after installing @angular/localize package, it will be placed in devDependencies object

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]
LGTM, thanks for your contribution.

**Review by jelbourn — APPROVED** [review]
LGTM

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: global-docs-approvers

**Comment by alxhub** [comment]
This PR was merged into the repository by commit db59f5b051c13dcacaa59c189a9f2bebda32e77e.

**Pull request closed without merging**
