### PR TITLE
fix(language-service): infer the type of array-like element.

### PR DESCRIPTION
**Pull request by ivanwonder**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

```js
const test: { {[key: string]: number};
```
current behavior of `test.test` will report a error;

## What is the new behavior?
new behaviour will infer the type `number`;

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by kyliau — APPROVED** [review]
LGTM for language service. Thank you for fixing this!

**Comment by ayazhafiz** [comment]
fixed by https://github.com/angular/angular/commit/53fc2ed8bf345222e0c3d53ce7f13a4f27f3052e

**Comment by andrius-pra** [comment]
@ayazhafiz,  [53fc2ed ](https://github.com/angular/angular/commit/53fc2ed8bf345222e0c3d53ce7f13a4f27f3052e) doesn't cover all functionality from this pull request. I still get `Identifier 'firstName' is not defined. '__type' does not contain such a member` error message in this example:
```
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';

@Component({
  selector: 'app-simple-form',
  template: `{{ profileForm.controls.firstName.valid }}`
})
export class SimpleFormComponent {
  profileForm = new FormGroup({
    firstName: new FormControl(''),
    lastName: new FormControl(''),
  });
}
```

**Comment by ayazhafiz** [comment]
Yes, you're totally right.. but the functionality of indexing a string index via dot notation is a little bit different from the index signature functionality. We will need to change how `SymbolTableWrapper#get` works, as @ivanwonder did in this PR. This can be done pretty easily; I will make a PR unless someone else is interested.

**Comment by ivanwonder** [comment]
@ayazhafiz have a plan to support this feature?
https://github.com/angular/angular/blob/054e3593a7ad3c98c41555f7342c2f9418d32b27/packages/language-service/test/hover_spec.ts#L39
I add a comment here.
https://github.com/angular/angular/blob/054e3593a7ad3c98c41555f7342c2f9418d32b27/packages/compiler-cli/src/diagnostics/symbols.ts#L119

**Comment by ayazhafiz** [comment]
No, it really appears that we closed this PR too soon; sorry about that - we thought it was just concerned with objects having index signatures. Would you like to create a new PR to implement the tuple functionality @ivanwonder?

**Comment by ivanwonder** [comment]
> @andrius-pra Yes, you're totally right.. but the functionality of indexing a string index via dot notation is a little bit different from the index signature functionality. We will need to change how `SymbolTableWrapper#get` works, as @ivanwonder did in this PR. This can be done pretty easily; I will make a PR unless someone else is interested.

I extend the `SymbolTableWrapper` because I don't want to add a new function parameter.
https://github.com/ayazhafiz/angular/blob/0fd03938fd006fe1e7e24eb38d4eb756513948ef/packages/language-service/src/typescript_symbols.ts#L459
and the `symbols` can be got from the `type`. and It’s a bit strange to me. This is why i add a new class`SymbolTableAndStringIndexTypeWrapper`

**Comment by ivanwonder** [comment]
> No, it really appears that we closed this PR too soon; sorry about that - we thought it was just concerned with objects having index signatures. Would you like to create a new PR to implement the tuple functionality @ivanwonder?

If I have time, I will try.

**Pull request closed without merging**
