### PR TITLE
docs: adding space in eventhandlers in attribute-directives.md

### PR DESCRIPTION
**Pull request by Showtim3**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A
#32924 

## What is the new behavior?
changed eventhandlers to event handlers(added a space in between as there are two different words)

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by Showtim3** [comment]
@kapunahelewong Please take a look.
Thanks!

**Comment by kapunahelewong** [comment]
This is great. Thank you, @Showtim3! Would you mind amending the commit message so that the body says that it fixes https://github.com/angular/angular/issues/32924? So it would be like this:
```
docs: add space in eventhandlers in attribute-directives.md
Fixes #32924
```
You could also say:

```
docs: fix typo in attribute-directives.md
Fixes #32924
```

I have some [notes on the amend workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) if youʻd like them. 

Will you tag me when youʻre ready so I can help this one get through? Thanks!

**Comment by risrawat90** [comment]
@kapunahelewong I amended the commit message. Let me know if i need to change something else.
Thanks!

**Comment by Showtim3** [comment]
@kapunahelewong Hey i have amended the commit message. Let me know if something else also needs to be done. 
Thanks ! :)

**Comment by kapunahelewong** [comment]
Can you try it like this (in the body instead of in the subject)? Sorry, I forgot to put a blank line in my example.

image

**Comment by Showtim3** [comment]
@kapunahelewong Ok I have done that. Please Take Another Look
Thanks!

**Review by kapunahelewong — APPROVED** [review]
LGTM! Caretaker, this is a docs only change. Please ping me if I can do anything to help get this green. Thank you!

**Pull request closed without merging**
