### PR TITLE
docs: remove p tags in Template binding example

### PR DESCRIPTION
**Pull request by dalejodc**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

In the Templates example it says that the user sees a string with `<p>` tags which is not true.

image

Issue Number: N/A

## What is the new behavior?
When binding the variable, this is what an end-user would see, a plain string without any `<p>` tags

image

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
I don't think we'd want to remove the paragraph tags here. A template like this would always have an html element instead of just a loose text node. WDYT?

**Comment by dalejodc** [comment]
@jessicajaniuk - Agreed, we don't want to have a lost empty node. But that is why the tags are added at the beginning in the template `<p>{{message}}</p>`

That way when the template loads what a user sees in the UI it is only the message "_Hello world_". Maybe I am missing something but I don't get why a user should see `<p>` tags rendered on the actual browser UI based on that example.

wdyt?

image

**Comment by jessicajaniuk** [comment]
@dalejodc I think the consistency here is what matters. In the first block we show the <p> tags, and the last block is showing that the text inside the p tags is changed, which indicates what happens in the template. I think that's clearer because it communicates what actually gets rendered in the template. If we remove the <p> tags in the last block, someone could be confused wondering if the tags get removed, when they don't.

**Comment by dalejodc** [comment]
@jessicajaniuk Got it. I see your point now. 

I am closing this PR. Thanks for your feedback.

**Pull request closed without merging**
