### PR TITLE
docs: add colon before introducing the list of items

### PR DESCRIPTION
**Pull request by dalejodc**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

A colon is missing before introducing a list of items
Issue Number: N/A

## What is the new behavior?
A colon before introducing the list of items was added

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by Hossein13M — APPROVED** [review]
This pull request has fixed some grammatical issues with the documentation.

**Review by AndrewKushnir — APPROVED** [review]
@dalejodc thanks for improving Angular docs!

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 6829fc4a4c072c631f8b49622298b4fc8b0ce04a.

**Comment by AndrewKushnir** [comment]
Merge assistance: this is a straightforward fix, no extra reviews are required, the PR is ready for merge.

**Pull request closed without merging**
