### PR TITLE
fix(bundle): add angular2/platform/testing/browser to SystemJS testin…

### PR DESCRIPTION
**Pull request by marclaval**
It is missing in beta.2

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
A similar change was done for UMD bundles already in 4a414420e940bf4a5eea2c870ddff6e33f0343b9, this PR fixes things for SystemJS bundles.

**Comment by pkozlowski-opensource** [comment]
LGTM

**Comment by alexeagle** [comment]
What's the severity? Do we need a beta.3?

**Comment by alexeagle** [comment]
Where is the missing testing for this? Don't we test the example tests using the bundle?

**Comment by pkozlowski-opensource** [comment]
> What's the severity? Do we need a beta.3?

This pretty much breaks unit tests for all the people using SystemJS bundles.
IMO definitively needed for beta.3

**Comment by pkozlowski-opensource** [comment]
> Where is the missing testing for this? Don't we test the example tests using the bundle?

I was also surprised that we don't have tests for this. From what I understand now we use other bundles for e2e tests but we don't use the testing bundles anywhere.

We should add proper testing as a follow up of this PR.

**Comment by Foxandxss** [comment]
Thanks for the PR, I was hitting the wall for ng-bootstrap tests until @pkozlowski-opensource told me that it was missing :P

**Comment by juliemr** [comment]
Thanks for finding this - sorry I didn't realize the bundles would need fixing when I made the test setup changes.

**Comment by pkozlowski-opensource** [comment]
> Thanks for finding this - sorry I didn't realize the bundles would need fixing when I made the test setup changes.

@juliemr no worries - there should be safety net for this. In the future we should:
* add automated tests
* think of a way of sharing this config for all bundles

**Comment by alexeagle** [comment]
Please bring up the beta.3 question on slack so we get a definitive answer. Would be nice if we could just publish an updated beta.2 bundle and not change any code? caretaker takes a lot of time without extra releases to perform

**Comment by alexeagle** [comment]
I decided to just cherry-pick this change onto the 2.0.0-beta.2 branch and re-publish the bundles.
Please verify: https://code.angularjs.org/2.0.0-beta.2/

**Comment by Foxandxss** [comment]
I can see it. Thank you.

For npm users, should we wait for beta.3?

**Comment by alexeagle** [comment]
I am not sure the severity for the use case of getting bundles out of the npm distribution. The workaround of replacing files from the CDN seems possible. @mhevery ?

**Comment by Foxandxss** [comment]
For the ones that relies on npm that won't work. A workaround can be done tho.

Personally for ng-bootstrap is not a big deal, we can wait for beta.3 while we code it up :)

**Comment by gdi2290** [comment]
The beta releases could benefit by having patch releases. Then everyone can simply run `npm upgrade` to take advantage of [semver](http://semver.npmjs.com/). Doing so everyone can simply specify that patches are fine to install with the tilde symbol (`~2.0.0-beta.3.0`) then the ngTeam can release patches any time for that version (`~2.0.0-beta.3.1`)

**Pull request merged**
