### PR TITLE
refactor(router): Remove use of OutletInjector

### PR DESCRIPTION
**Pull request by atscott**
OutletInjector doesn't do anything special. Injector.create can be used instead

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
👍

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 9acec3f0f72c9f286ab06f20357f58a74d198750.

**Comment by AndrewKushnir** [comment]
Reverting via #46775 as it's breaking g3.

**Comment by AndrewKushnir** [comment]
Adding the "blocked" label for now, since we'd need to perform further investigation in g3 (and possibly a TGP) before merging it again.

**Comment by atscott** [comment]
Closing as this actually changes behavior, specifically for `providedIn: 'any'`. Because `OutletInjector` doesn't act as a real `Injector` instance, but only provides new things for two specific tokens and delegates everything else to the parent, it does not affect `providedIn: 'any'`. Converting to `Injector.create` has the effect of creating a real injector which will instantiate `providedIn: 'any'` Injectables. 

We should have discussions about the `providedIn: 'any'` option and at the very least update the documentation to be more accurate. Currently, the documentation mentions that a new instance is only created at lazy loading boundaries. But this isn't true at all. A new instance is created at any new `Injector` boundary.

**Pull request closed without merging**
