### PR TITLE
feat(pipes): add filter pipe

### PR DESCRIPTION
**Pull request by piloopin**

### CODE REVIEW

**Comment by tbosch** [comment]
This needs more design as we can't use reflection in an ad hoc way.

**Comment by tbosch** [comment]
@mhevery what should we do here? Only support this in JS?

**Comment by mhevery** [comment]
Let's only support this pipe in JS and ignore it in Dart.

**Comment by tbosch** [comment]
Let's not do this as part of angular core, as it won't work with the precompiled templates that we are about to do. Please feel free to publish this as a standalone directive.

**Pull request closed without merging**
