### PR TITLE
fix(compiler): do not allow unterminated interpolation to leak into later tokens

### PR DESCRIPTION
**Pull request by petebacondarwin**
The lexer tracks whether it is reading characters from inside an interpolation
when consuming a text token, so that it can identify invalid ICU expressions.
Inside an interpolation there will be no ICU expression so it is safe to
have unmatched `{` characters, but outside this is an error.

Previously, if an interpolation was started, by an opening marker (e.g. `{{`)
in the text, but the text came to an end before the closing marker (e.g. `}}`)
then the lexer was not clearing its internal state that tracked that it was
inside an interpolation. So if when a new text token was being consumed,
the lexer, incorrectly thought it was already within an interpolation.
This resulted in invalid ICU expression errors not being reported.

There are instances of this error being hidden inside G3, and so these will
need to be fixed in order to land this change.

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
[Ivy Presubmit](https://test.corp.google.com/ui#id=OCL:380503757:BASE:380503855:1624253025654:6c28a828) + [Global Presubmit](https://test.corp.google.com/ui#id=OCL:380503757:BASE:380503824:1624253008563:3a37c73e).

**Comment by petebacondarwin** [comment]
@AndrewKushnir can you check this new code against the failing targets in G3? Thanks!

**Comment by AndrewKushnir** [comment]
[Presubmit #2](https://test.corp.google.com/ui#id=OCL:380503757:BASE:380657713:1624308959601:c950cc6c).

**Review by AndrewKushnir — APPROVED** [review]
LGTM 👍

**Comment by AndrewKushnir** [comment]
[Global Presubmit #2](https://test.corp.google.com/OCL:380503757:BASE:380714247:1624328443959:cc42ccb2).

**Comment by AndrewKushnir** [comment]
@petebacondarwin FYI, presubmits (including TGP) are now "green" 🎉

**Comment by petebacondarwin** [comment]
Caretaker: since the last presubmit, I have only changed the wording of the commit messages, so there should be no need to re-run the presubmit, unless you want to check for backsliding.

**Comment by dylhunn** [comment]
@petebacondarwin Sounds good, is that the only reason you have `merge-assistance` on the PR?

**Comment by AndrewKushnir** [comment]
@dylhunn I've forced g3 status and removed the `action: merge-assistance` label.

**Pull request closed without merging**
