### PR TITLE
Ngtsc revert filesystem stuff

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Review by JoostK — APPROVED** [review]

**Review by IgorMinar — COMMENTED** [review]
Do we have a reproduction that confirms that this is the culprit?

Also, can you please update the commit messages with the rollback reason? Thanks!

**Comment by petebacondarwin** [comment]
Commit messages updated.

**Comment by JoostK** [comment]
I can reproduce the issue on Windows and both this PR as well as #37008 solve it for me.

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@petebacondarwin I just noticed that the "PR target" label is missing: I believe it should be "master&patch"?

**Comment by petebacondarwin** [comment]
Thanks for spotting that @AndrewKushnir - no this is patch only.

**Comment by AndrewKushnir** [comment]
@petebacondarwin ok, got it. For the "10.0.0-next.X" release the plan is to fix forward with #37008?

**Comment by petebacondarwin** [comment]
Yes.

**Comment by AndrewKushnir** [comment]
FYI, g3 presubmit should not be needed for this PR, since it's a patch-only (i.e. we keep these changes in master) and g3 sync happens from the master branch.

**Comment by petebacondarwin** [comment]
Landed on 9.1.x

**Pull request closed without merging**
