### PR TITLE
chore(test): upgrade form tests to testcomponentbuilder

### PR DESCRIPTION
**Pull request by juliemr**
Part of #2354

[Review on Reviewable](https://reviewable.io/reviews/angular/angular/2744)

### CODE REVIEW

**Comment by juliemr** [comment]
Note that some tests need to use `fakeAsync` because `dispatchEvent` will not synchronously dispatch all of form's ng- events, such as `ng-submit`. We also can't then do work inside the `createAsync().then()` callback, because fake async in dart does not allow nested `tick` statements. @vicb @tbosch does this seem like a reasonable workaround?

**Comment by vicb** [comment]
<sup>**[modules/angular2/test/forms/integration_spec.ts, line 85 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2744#-Jt-ezHiAY3gbcRBQzK4)** ([raw file](https://github.com/angular/angular/blob/a42483cb812db2cc950d5a4b4879065650cadae0/modules/angular2/test/forms/integration_spec.ts#L85)):</sup>
don't `detectChanges()` and `tick()` do the same thing here ?
calling one only should do

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/angular/angular/2744)

**Comment by vicb** [comment]
LGTM however I think either `tick()` or `tc.detectChanges()` should be used consistently

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/angular/angular/2744)

**Comment by juliemr** [comment]
No, both `detectChanges` and `tick` are necessary in many places. I went through and made sure they're both needed where they are used.

**Comment by juliemr** [comment]
Merged as 82e8e8c638b50f5b310a10b1e57b26a147c5e25a

**Pull request closed without merging**
