### PR TITLE
refactor(compiler): add support for animation properties and listeners

### PR DESCRIPTION
**Pull request by mmalerba**
Depends on #50818, #50805, #50899

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Template pipeline does not handle animation property or listener bindings correctly

## What is the new behavior?

Template pipeline handles animation property and listener bindings correctly

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by mmalerba** [comment]
Note to reviewers: first commit is cherrypicked from one of Dylan's PRs to unblock this. I'll rebase once that PR goes in, so only need to review the other commits for this PR

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-core, fw-compiler

**Comment by mmalerba** [comment]
Does not affect internal tests

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 09bf32724f3977a6e8eb536a9ae53513ef2c9166.

**Pull request closed without merging**
