### PR TITLE
docs(aio/content/marketing/resources.json): add We Are One Sàrl as onsite training

### PR DESCRIPTION
**Pull request by fduperier**
Adding We Are One Sàrl as an onsite training company in Switzerland.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[X] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information
Copy of PR #19876 following a bad manipulation of the previous PR...

### CODE REVIEW

**Comment by fduperier** [comment]
@gkalpak I have created a new PR since I make a mistake in the previous one (#19876)

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
The original PR (#19876) had been approved by @StephenFluin.
Any Travis failures are not related to this PR.

**Comment by fduperier** [comment]
@gkalpak Thank you !

**Comment by fduperier** [comment]
Hi @gkalpak !
Any chance to get this PR merge before being in the same case as the previous one ?
Thanks you :)

**Comment by gkalpak** [comment]
It is marked for merge, so all we have to now is wait :smiley:

**Pull request closed without merging**
