### PR TITLE
docs: correct @ngtools/webpack url

### PR DESCRIPTION
**Pull request by tieppt**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Fix Broken link for "Angular Ahead-of-Time Webpack Plugin documentation"
Issue Number: #32385

## What is the new behavior?
correct @ngtools/webpack url

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
@kapunahelewong please review this PR.

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]

**Comment by alan-agius4** [comment]
Thanks for this.

**Review by kapunahelewong — APPROVED** [review]
LGTM.

Thanks, @tieppt!

**Review by alan-agius4 — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Thanks for this, @tieppt. Could you rebase? It would be super helpful in moving it through the rest of the process. Here are the steps I use in my own workflow: https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase

Please tag me with any questions/when you're ready. 🙏🏼

**Comment by kapunahelewong** [comment]
Caretaker, this is a docs only change. Thanks!

**Pull request closed without merging**
