### PR TITLE
Fix a tiny spelling of tutorial document

### PR DESCRIPTION
**Pull request by nyaapass**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

> the components CSS element selector

## What is the new behavior?

> the component's CSS element selector

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

nope

### CODE REVIEW

**Comment by nyaapass** [comment]
`I signed it!`

**Comment by sarunint** [comment]
Please format your commit message to match the [Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).

**Comment by kapunahelewong** [comment]
Hey @nyaapass how about this as a commit message? 

"docs: fix typo in toh-pt1"

Will you tag me when you update so I can approve? Thank you!

**Comment by jenniferfell** [comment]
Thanks for working on this issue. It looks like it has already been fixed by someone else in a recent update.

**Pull request closed without merging**
