### PR TITLE
Update contributors.json

### PR DESCRIPTION
**Pull request by An0nymous0**
#old commit message
vue incident angular team is considered to remove the negative impact of this person

#declare
请收起来你们的假慈悲，认真思考一下这个事情。

不要觉得你们跟随vue团队对这件事的态度就是站在了胜利的一方，让人觉得你们一样很大度，站在vue团队的立场上这件事情处理的是正确的，而且也不得不这么做，难道去攻击？angular团队做的也没问题，双方的团队都很good，但是作为开源的受益者角度来讲这件事我觉得应该做出看得见的惩罚。并且这个pull只是建议性。错误的是可能不应该由我来做这个公关。

我不是贵圈的人，谈不上给前端大神们丢脸。下面来说一说我为什么要这么做。

1.目前的前端风气真是让我这个主后端辅前端的小白无从下手，很少有理性分析对比前端框架的文章过多过少都带一点政治气息，而且我也发现国内好多人是不喜欢这种风气的，所以你们都去理性分析然后去推翻xxx的对比与评价是不对的，或者说是恶意的，然后指出反驳，如果道歉就表明我们接受道歉大家宽容你的态度，不道歉也就不了了之，这种做法是官方应该做的而不是受益者该做的，如果所有人都这样无脑跟风胜利的一方的态度，这么做我们就怎么做能改变这种风气？角度不同做的事情也不同。

2.人人都大度都表示我们前端圈的风气很好，你做错了没事，我们都原谅你，心里都希望你可以像我们一样的人。 但是实际呢？带有恶意的人真的能被你们感化？如果一个人做了有违你们向往的前端的环境下的事，你们只是说一说表示自己很宽容道歉我们就接受了，如果道歉之后还有人指责，你们就来群体攻击职责的人表示一下，你道过歉就好了我们不许有人说你了？这种做法对于别有用心的人应该是最好的环境吧？只会让这种人更加肆无忌惮，因为他做错了事道道歉就有人来保护他了，但是如果他做的事情没反驳成功，真的毁灭的了一个好的项目呢？

3.在开源界如果做出了恶意的可能毁灭或者破坏优秀项目的事情，就应该受到应有的惩罚，有好的风气就要有好的规矩，要让这种人做这样的事情之前会想自己会不会后悔，而不是做了再说，不行再道歉。  只有在良好的风气之下保留一些宽容和大度才有意义。 相反只能更糟。

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by Kingwl** [comment]
It's so bad man  
We cannot deny his contribution to the angular even if he made some inappropriate things

**Comment by AngryPowman** [comment]
Could the action of this PR appear proper to him in the case? 
This is can't change the fact that he's the contributor of Angular. 

**Please close this PR.**

**Comment by An0nymous0** [comment]
OK，close is pull.

**Comment by lightningtgc** [comment]
丢人现眼！Shame on you!

**Comment by wangxf91** [comment]
用中文喷：楼主真是个low B，闲的蛋疼？别他妈在这给Vue社区丢人好吗？

**Comment by yodfz** [comment]
这么做真的很丢份！这让其他人怎么看我们国内的前端？

**Comment by JustClear** [comment]
It's a real eye-opener...

**Comment by myst729** [comment]
This is so wrong! I'm a Vue community contributor and I disagree with it. It's a shame.

**Comment by iminto** [comment]
It's a shame

**Comment by yqfang** [comment]
I disagree with it

**Comment by zhangzhaoaaa** [comment]
I don't know why you do this, emotional behaviour?

We can't ignore someone's contribution to it,even though someone did some negative effects to it.
This is not fair.

Calm down,man

But,what a shame!

**Comment by castielluo** [comment]
It ain't right,man.Sorry for what you've done.

**Comment by dasunsy** [comment]
what a shame.

**Comment by icepoint0** [comment]
what a shame for vue fans.

**Comment by wujun4code** [comment]
: Are you a fan of vue
: NO! you are a fan of vue, your father and your mother are fans of vue,your family are tatally fans of vue.
: ...

**Comment by leizongmin** [comment]
林子大了，什么鸟都有。

**Comment by An0nymous0** [comment]
Sorry everyone, not intentionally, just ask.

**Comment by leuvi** [comment]
Idiot

**Comment by wulong381** [comment]
super 1 3

**Comment by akira-cn** [comment]
It's so ridiculous.

**Comment by giscafer** [comment]
I want to speak dirty words

**Comment by helloli** [comment]
I have a Mamaipi and do not know if I can speak it out

**Comment by QAQMiao** [comment]
Boring.

**Comment by sunyongjian** [comment]
what a fucking funny day!

**Comment by bluewayne** [comment]
@An0nymous0 你是刚毕业 还是哗众取宠？WTF

**Comment by icepoint0** [comment]
@helloli six six six

**Comment by kmvan** [comment]
h3 25 qeru lga lf9q v3

**Comment by lvanboy** [comment]
break brain.

**Comment by sulihuang** [comment]
sb

**Comment by Justineo** [comment]
Plz lock this issue to close this irrational discussion.

**Comment by myst729** [comment]
Please lock this thread.

**Comment by yuantongkang** [comment]
why  Aaron Zhang  became out of control，because some of vue`s crazy fun  give the Intimidation to him on China Dev community，cause he be scared and became angry 。on this PR ,I saw the the behavior that @An0nymous0 do , I feel very disappointed

**Comment by yuantongkang** [comment]
why  Aaron Zhang  became out of control，because some of vue`s crazy fun  give the Intimidation to him on China Dev community，cause he be scared and became angry 。on this PR ,I saw the the behavior that @An0nymous0 do , I feel very disappointed

**Comment by Fleurer** [comment]
What a shame.

**Comment by WD-iGaves** [comment]
in tree‘s ting ...

**Comment by xiaolongyuan** [comment]
兄弟 你要搞文化大革命啊

**Comment by Passluo** [comment]
根正苗红啊

**Comment by Yixi** [comment]
MDZZ

**Comment by trotyl** [comment]
Some technical review:

+ When removing the entry, you'd better remove the image file as well, or you would cause ~~memory~~ disk leak in the repo;
+ Your commit message didn't follow the requirement in CONTRIBUTING guideline.

**Comment by IgorMinar** [comment]
We are investigating what was posted on Chinese social media and taking steps to correct the situation.

**Pull request closed without merging**
