### PR TITLE
refactor(zone.js): remove #9100 todos.

### PR DESCRIPTION
**Pull request by JeanMeche**
This commit assigns the correct type instead of `any`.

----
This PR is part of a series of 4 to remove the last remaining todos from #9100

- #49406
- #49407
- #49408
- #49409

### CODE REVIEW

**Review by JiaLiPassion — APPROVED** [review]
LGTM, thanks.

**Comment by dylhunn** [comment]
@JeanMeche Is this ready for merge?

**Comment by JeanMeche** [comment]
@dylhunn Yes !

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 1f3f5642f55d37466f5cfa2185235a43f387a830.

**Pull request closed without merging**
