### PR TITLE
feat(dart/transform): Add a parser for `.ng_deps.dart` files and use.

### PR DESCRIPTION
**Pull request by kegluneq**
Use the parser in `BindGenerator`
This checkin also removes types from `registerSetters` calls since they
can cause runtime failures (see #886). We will resolve this in the future by
generating change detector classes.

### CODE REVIEW

**Comment by kegluneq** [comment]
Thanks, @yjbanov . I've tried to split things up into a few pieces this time -- please give any feedback on how you find the PR organization this time around.

**Comment by yjbanov** [comment]
There's something strange about having to parse Dart code to extract data. I feel like we should be using a file format more suitable for carrying data, such as JSON or YAML. I guess it will do for now.

LGTM

**Comment by kegluneq** [comment]
Using Dart as our data format *does* feel a little strange, I'm not opposed to using something else but I haven't found a clear reason to switch to another format yet.

Just to make sure I understand the procedure, now that this is LGTM'd I squash the 5 commits into a single one (probably using the message from the PR as the commit message) and commit to master. Correct?

**Comment by mhevery** [comment]
When you think you have taken care of all of the issues you should remove `!cleanup` label. Since you have `!merge` you are free to merge it in if you have the right permissions.

**Pull request closed without merging**
