### PR TITLE
docs(common): describe behavior when reference changes

### PR DESCRIPTION
**Pull request by bit-jkraushaar**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Added description how the async pipe behaves when the referenced object changes.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by bit-jkraushaar** [comment]
@googlebot I signed it!

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

This looks fine to me, but we should have the docs folks look at it, too.

**Review by dario-piotrowicz — APPROVED** [review]
Nice one :slightly_smiling_face: 

However (and this a thing already there) we say that we unsubscribe to promises which doesn't make much sense to me

as you can see here I think we aren't doing anything in particular: 
Screenshot at 2021-07-18 16-33-00

(but we do reset the `_subscription` and `_obj` so it is sort of like unsubscribing to it...)

I'm just thinking if here and in the rest of the comment we could find a better wording for what is happening to promises :thinking:

**Review by aikithoughts — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Pull request closed without merging**
