### PR TITLE
docs(zone.js): fix typos in NgZone guide

### PR DESCRIPTION
**Pull request by MansourFall**
fix typos in NgZone guide example

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #36594

## What is the new behavior?
Typos are fixed
## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Good catch! Thx, @MansourFall :+1:

Can you, please, update the commit message to more closely follow our [commit message guidelines][1]. E.g. something like:

> docs(zone.js): fix typos in NgZone guide code example
>
> Fixes #36594

Reviewed-for: global-docs-approvers

[1]: https://github.com/angular/angular/blob/ca677481a2ac3675b84698e2d16fd379e1799e2c/CONTRIBUTING.md#commit

**Review by gkalpak — DISMISSED** [review]
Reviewed-for: global-docs-approvers

**Review by gkalpak — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by MansourFall** [comment]
Thanks @gkalpak 😄 ! just updated the commit message as requested!

**Pull request closed without merging**
