### PR TITLE
feat(aio): show top-nav with same styling as side-nav when window is narrow

### LINKED ISSUE #15490: aio: fix mini-toolbar layout for narrow view

### PR DESCRIPTION
**Pull request by petebacondarwin**
Fixes #15490

### CODE REVIEW

**Review by sjtrimble — APPROVED** [review]

**Review by gkalpak — COMMENTED** [review]
The home link gets lost on smaller screens. I think it is nice to have a way to navigate home (even if it is not used often). Could be done in a follow-up PR (if others agree it is useful).

LGTM otherwise.

**Review by Foxandxss — APPROVED** [review]
LGTM but I think I agree with George. It is common to have the home link.

**Comment by petebacondarwin** [comment]
Added the Home link. PTAL

**Comment by sjtrimble** [comment]
I was hoping to get the Angular icon on the toolbar as the "home button" - see image I originally shared. We can add that to another PR if needed.

screen shot 2017-03-22 at 11 50 02 pm

**Comment by petebacondarwin** [comment]
I can change that...

**Comment by petebacondarwin** [comment]
@sjtrimble - done. PTAL (when the preview is ready).

**Comment by gkalpak** [comment]
The search-box gets pushed "out of the screen" on very small screens: aio-tiny-screen

Maybe we could just have the `A` (without `ngular`) when the top-nav is not visible.

**Comment by sjtrimble** [comment]
@petebacondarwin Yes, just the icon ("A" alone) would be lovely!

This one: aio/src/assets/images/logos/angular2/angular.svg

**Comment by petebacondarwin** [comment]
I fixed it to show the shield only in narrow view.

**Review by gkalpak — APPROVED** [review]
Magic!

**Comment by wardbell** [comment]
The idea is incorporated in #15570. @petebacondarwin Do you agree that we should close?

**Pull request merged**
