### PR TITLE
docs: remove DI_token link

### LINKED ISSUE #52621: docs: remove DI_token link
### Describe the problem that you experienced

In this page (https://angular.dev/api/core/ANIMATION_MODULE_TYPE), when I click on **DI_token** link, it redirects me to (https://angular.dev/overview) and the attribute [href] equals to (https://angular.dev/docs).

### Enter the URL of the topic with the problem

https://angular.dev/api/core/ANIMATION_MODULE_TYPE

### Describe what you were looking for in the documentation

_No response_

### Describe the actions that led you to experience the problem

_No response_

### Describe what you want to experience that would fix the problem

_No response_

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by Dhoni77**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Text with link is present which on clicking redirects to [docs](https://angular.dev/docs)

Issue Number: fixes #52621

## What is the new behavior?
Remove the link

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by twerske — APPROVED** [review]

**Comment by twerske** [comment]
You'll need to lint before merge!

**Comment by AndrewKushnir** [comment]
@Dhoni77 as Emma mentioned above, please update the commit message (`git commit --amend`) to start with `docs: `, so that the `lint` CI checks pass.

**Comment by JeanMeche** [comment]
Hi, do you mind squashing your commits and reword the remaining one to follow our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit) ?

**Comment by JeanMeche** [comment]
In absence of cleanup, I'll close this PR. Feel free to reopen one if necessary !

**Pull request closed without merging**
