### PR TITLE
docs(docs-infra): remove Featured/Most Common section from the API reference list page

### PR DESCRIPTION
**Pull request by hawkgs**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The section can be found at the top of the API reference list page.

## What is the new behavior?

The section has been removed along with all of the code that's related to the Featured functionality. The filter is now moved to the top of the page instead.

Screenshot 2024-11-14 at 16 56 41

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Last time I brought the topic @MarkTechson wanted to take a step back to think, we'd need his approval for this  !

**Comment by JeanMeche** [comment]
Could you please squash all those changes in a single `docs(docs-infra): ...` commit, we keep fix/test/feat for the framework. Thank you.

**Comment by MarkTechson** [comment]
> Last time I brought the topic @MarkTechson wanted to take a step back to think, we'd need his approval for this !

Yes this is true, we've had some time to chat on the team and prioritize this work and made the decision to remove this section. Thank you for remembering this 😀

**Review by JeanMeche — APPROVED** [review]
Happy that we land this !!

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 0deb6f9ffb24bd1b1ea541a62b0cf34710828c3e.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
