### PR TITLE
ci: Upgrade tsec to 0.2.0.

### PR DESCRIPTION
**Pull request by uraj**
tools/tsec.bzl is now part of tsec. Remove from Angular repo and update
BUILD.bazel files.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by uraj** [comment]
@devversion I've released a new tsec version and moved tools/tsec.bzl into the tsec package.

**Review by devversion — APPROVED** [review]
Thanks @uraj.

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: global-approvers


Thank you so much for finishing up this transition, its definitely great to have this functionality in the tsec library so we can use it in other repos as well.

**Comment by AndrewKushnir** [comment]
@josephperrott just wanted to check if this PR is ready for merge (looks like all approvals are there and CI is "green")?

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit adaff4109b88105a58a5e772717472ac17673ee7.

**Pull request closed without merging**
