### PR TITLE
update redirect links and fix typo

### PR DESCRIPTION
**Pull request by sreevani-ship-it**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
update redirect links with new deprecation summary filename

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]

**Review by gkalpak — COMMENTED** [review]
AFAICT, the name of the guide is still `deprecation`, not `deprecations` 😕

**Comment by gkalpak** [comment]
I see the guide name will be changed in #26733. Marking this as blocked, so that it is merged after #26733.

**Comment by jenniferfell** [comment]
> I see the guide name will be changed in #26733. Marking this as blocked, so that it is merged after #26733.

Thank you! Yes, that is the intent.

**Review by jenniferfell — APPROVED** [review]

**Comment by IgorMinar** [comment]
this is unblocked now. marking for merge

**Pull request closed without merging**
