### PR TITLE
docs: fix typo in BUILD.bazel comments

### PR DESCRIPTION
**Pull request by alexDtorres**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Thanks for this, @alexDtorres! It looks like a rebase may help clean this up. Here are [my notes](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#what-to-do-if-you-end-up-with-a-bunch-of-commits-that-arent-yours-in-your-pr) that I use when a bunch of extra commits end up in a PR. If you have any questions just let me know and I can help out from this end. Once we get those extra commits out of there, I can help by reviewing your contribution.

**Review by mhevery — APPROVED** [review]

**Review by mhevery — COMMENTED** [review]
reviewed-for: global-approvers

**Comment by kapunahelewong** [comment]
Hi @alexDtorres, I think the reason the test is not passing is because of the commit message. If you make it:

```
docs: fix typo in BUILD.bazel comments
```

Without the `(bazel)` scope, it should pass. To change the commit message use `git commit --amend`, save (and exit your editor), and push. Here are my notes on amending if you'd like them. Feel free to tag me when you're ready or if you have any questions. 🙂

**Comment by alexDtorres** [comment]
@kapunahelewong Thank you for notifying. I was waiting for the reviewer. hah.

Seems all the tests are passing. Let me know if there's anything else blocking this PR from being accepted. I appreciate all your help thus far!

**Review by josephperrott — APPROVED** [review]
LGTM

**Pull request closed without merging**
