### PR TITLE
ci(aio): move e2e tests to optional job

### PR DESCRIPTION
**Pull request by petebacondarwin**
The AIO e2e tests are failing randomly.
This PR moves those tests to an optional Travis job while we investigate.
See https://github.com/angular/angular/issues/20159#issuecomment-341832801

### CODE REVIEW

**Review by gkalpak — CHANGES_REQUESTED** [review]
Some more preparation work in needed:

- Add `aio_optional` [here][1].
- Add `aio_optional` [there][2].
- Run `yarn setup` before `yarn e2e`.

[1]: https://github.com/petebacondarwin/angular/blob/cc6ff75f67eb181dd900172e7d1f88c57e6dbca0/scripts/ci/install.sh#L50
[2]: https://github.com/petebacondarwin/angular/blob/cc6ff75f67eb181dd900172e7d1f88c57e6dbca0/scripts/ci/install.sh#L77

**Comment by petebacondarwin** [comment]
Yep, I realised as soon as I went to bed but had no energy to get up and fix it

**Comment by petebacondarwin** [comment]
Plus it needed the new shell script to be given `chmod +x` of course

**Comment by petebacondarwin** [comment]
@IgorMinar - can you review this?

**Review by IgorMinar — APPROVED** [review]

**Review by gkalpak — APPROVED** [review]

**Pull request merged**
