### PR TITLE
docs: add Angular university website to resources list

### PR DESCRIPTION
**Pull request by AlirezaEbrahimkhani**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Angular University website has very useful content and the website is created by @jhades

### CODE REVIEW

**Comment by danqulogy** [comment]
The website provide great content and technical details for architecting angular applications. It is thumb 👍 for me,

**Review by dylhunn — APPROVED** [review]
This looks like a nice resource. @twerske Are you OK with me merging this?

**Review by twerske — APPROVED** [review]
lgtm

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit e1e440d65af928e569533bb1725eefcdf0794ebf.

**Pull request closed without merging**
