### PR TITLE
refactor(core): Introduce `ngServerMode` as global

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit adds the `ngServerMode` as global, which allows for the tree-shaking of server-only code from the bundles. When this flag is unset at runtime, server-specific code will be excluded by Closure, optimizing bundle size.

**Internal Angular Flag**: This is an *internal* Angular flag (not a public API), avoid relying on it in application code.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Comment by alan-agius4** [comment]
**Caretaker note:** this requires a G3 patch to be updated http://cl/690926004

**Review by alxhub — APPROVED** [review]

**Review by alxhub — APPROVED** [review]
Reviewed-for: public-api

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 378284fa08b5af1c71d5534116d84cae127ac084.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
