### PR TITLE
Docs/contributors gde kevin kreuzer

### PR DESCRIPTION
**Pull request by nivekcode**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by gabrielbussolo — COMMENTED** [review]
I verified and you are really you! :laughing: 
I saw @StephenFluin recommend images with <30kb in another [pull request
](https://github.com/angular/angular/pull/35925#issuecomment-610081966), so I wold like to give the same suggestion :grin:

**Comment by kreuzerk** [comment]
@gabrielferreirapro thanks a lot for reviewing the PR and verifying that its really me 😉. I updated the PR, the image file is now under 30kb.

**Review by StephenFluin — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Thanks for this PR, @kreuzerk! I love new GDE PRs! Could you [rebase](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-rebase) to resolve the conflict and [squash ](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash)your commits into one?

Also, to pass, you'll want to add a body of at least 100 characters to your commit message. You could use this one if you like:

```

docs: add Kevin Kreuzer to GDE page

This commit adds Kevin Kreuzer to the Angular GDE page along with a biography, his contributions, and a photograph.

```

Just make sure that whatever you put in the body of the commit is at least 100 characters. If you'd like some help with rebasing etc., just let me know. Please tag me when you're ready and I can help move this PR forward. Congrats!

**Comment by kreuzerk** [comment]
Hi @kapunahelewong 

Thanks a lot for the response. I had some troubles with rebasing all the commits - so I created a new PR (https://github.com/angular/angular/pull/37927) and will close this one.

**Pull request closed without merging**
