### PR TITLE
docs: delete aborted documentation files

### PR DESCRIPTION
**Pull request by JeanMeche**
Those files were created as part of #47391 but the content was never merged.

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
I'm adding @mgechev here since he has the context about these docs.

**Comment by JeanMeche** [comment]
@jelbourn you probably have some inputs, since you closed all @josmar-crwdstffng PRs in december.

**Review by jelbourn — APPROVED** [review]
LGTM on deleting these for now, unsure of we will restore them later, but they're always in history if we need them. 

Reviewed-for: global-approvers

**Review by jessicajaniuk — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 478c70c80653c19c9e5f5a8a71b568a7c38fa249.

**Pull request closed without merging**
