### PR TITLE
build(docs-infra): update http-server to 0.11.1

### LINKED ISSUE #30363: Upgrade http-server in example to 0.11.1
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

Currently, we are using http-server package for running doc portal locally and we are using http-server version 0.9 which is dependent on ecstatic 1.4, which is removed from artifactory.

Even http-server is not updated from last 1 year, so for best let's move away to 
https://www.npmjs.com/package/local-web-server or update to latest version which is 0.11.1

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

### PR DESCRIPTION
**Pull request by santoshyadavdev**
Fixes #30363

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #30363

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Please, change the commit message to `build(docs-infra): update http-server to 0.11.1`.
Otherwise lgtm 👍

**Comment by santoshyadav198613** [comment]
Hi @gkalpak ,

Done.

**Comment by santoshyadav198613** [comment]
The build got failed for a different reason.

**Comment by gkalpak** [comment]
**merge-assistance:** The codefresh failure is a flake.

**Pull request closed without merging**
