### PR TITLE
docs: update homepage headline

### PR DESCRIPTION
**Pull request by StephenFluin**
The headline we use has become somewhat out of date. We have a larger
refactoring going on for the home page, but this update clarifies things a little bit in the
mean time.

CC: @jelbourn 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Documentation content changes

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

**Review by IgorMinar — APPROVED** [review]
This LGTM but I'd like @mgechev and @juleskremer to LGTM this change as well.

If we change this, then we should also change the github [repo description](https://github.com/angular/angular):

Screen Shot 2020-06-09 at 10 33 41 PM

**Comment by mgechev** [comment]
@StephenFluin we can move it forward with the headline we discussed offline.

**Comment by petebacondarwin** [comment]
> @StephenFluin we can move it forward with the headline we discussed offline.

Does this mean this is ready to merge @mgechev ?

**Comment by jelbourn** [comment]
Changes to the homepage got stuck in discussions and seems to have fallen through the cracks. Stephen is on parental leave now, so I'm closing this PR; if we want to revisit someone else will need to pick up the changes.

**Pull request closed without merging**
