### PR TITLE
fix(common): fallback to last defined value for named date and time formats

### LINKED ISSUE #21282: date pipe - longDate not working in zh locales
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

date = Wed Jan 03 2018 20:21:42 GMT+0800 (CST)
``` {{date | date: "longDate"}}```
outputs `longD下午te`
## Expected behavior

output `2018年1月3日` or 2018年01月03日` or `2018年一月3日` or `2018年一月03日` 

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-datepipe-zh

## Environment

<pre><code>
Angular version: >5.0.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by trotyl**
closes #21282

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #21282

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

Didn't find a locale which has identical time formats, should we add mock data to test it ?

### CODE REVIEW

**Review by ocombe — APPROVED** [review]

**Comment by ocombe** [comment]
Good fix. I just checked the CLDR extraction scripts and that's the only data that we deduplicate and that didn't have a "get last defined" check.

**Review by vicb — APPROVED** [review]

**Comment by vicb** [comment]
@trotyl could you please rebase on the latest master ? (changes LGTM but there is a conflict preventing the merge). Thanks !

**Comment by trotyl** [comment]
Rebased, the saucelabs failure seems unrelated.

**Comment by ocombe** [comment]
I've restarted the failing test

**Review by vicb — APPROVED** [review]

**Comment by chuckjaz** [comment]
Failing presubmit checks https://sponge.corp.google.com/8d84db57-af4c-4948-8942-e0279d54c3af

**Comment by chuckjaz** [comment]
Failures not unique to this PR

**Pull request closed without merging**
