### PR TITLE
docs: remove labs location and update LTS info

### PR DESCRIPTION
**Pull request by jenniferfell**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Affected doc: https://angular.io/guide/releases

Replaces PR https://github.com/angular/angular/pull/23920
for removing paragraph: "Angular Labs projects typically are in separate branches in the Angular repo, clearly separated from the main Angular codebase."

Updates LTS information to be calendar-based, not release-based. 

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

https://angular.io/guide/releases#angular-labs
* Describes Angular Labs as typically being in branches (not completely accurate)
* Has mixed verbage about LTS

Issue Number: N/A

## What is the new behavior?

Replaces PR https://github.com/angular/angular/pull/23920
for removing paragraph: "Angular Labs projects typically are in separate branches in the Angular repo, clearly separated from the main Angular codebase."

Updates LTS information to be calendar-based, not release-based. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
Please update the commit message to just "docs: ...." rather than "docs(update): ...". otherwise lgtm

**Comment by jenniferfell** [comment]
@IgorMinar : Fixed commit message. Also:
- Changed section title from "Long-term support" to "Support policy" (because it's all support not just LTS)
- Turned markdown table into correct HTML
- Added column for current status as LTS or Active (I liked this from the node.js example you sent)

Still LGTY?

**Comment by IgorMinar** [comment]
hmm.. why html table? it looks inconsistent with the rest of the design on the site and the html is also harder to read in the source form.

original markdown:

screen shot 2018-05-16 at 9 59 16 am



html table:

screen shot 2018-05-16 at 9 59 23 am


I would prefer the original unless you see something wrong with it that I'm missing...

**Comment by jenniferfell** [comment]
@IgorMinar The Angular Author Guide specifies that HTML tables be used, and this table is the same style as other tables in the guides: 

https://angular.io/guide/docs-style-guide#tables
https://angular.io/guide/module-types
https://angular.io/guide/ngmodule-api#ngmodule-metadata
https://angular.io/guide/ajs-quick-reference
https://angular.io/guide/router#router-events
https://angular.io/guide/template-syntax#binding-targets

Yes, I think we could improve on the css for tables, and I'll open a separate issue for the aio team on that. Fwiw...ALL CAPS is harder for the eye to scan than Title Caps or Sentence caps, so the markdown titles aren't as easy for readers to parse quickly.)

**Comment by jenniferfell** [comment]
Issue to change markdown to HTML for some tables: 
https://github.com/angular/angular/issues/23978

Issue to improve css for tables in guides:
https://github.com/angular/angular/issues/23980

**Comment by matsko** [comment]
This fails to merge into master. Please rebase and fix.

**Pull request closed without merging**
