### PR TITLE
refactor: use `queueMicrotask` to schedule micro tasks instead of various helpers

### PR DESCRIPTION
**Pull request by alan-agius4**
`queueMicrotask` is an API which is supported by all browser and Node.js versions.

### CODE REVIEW

**Comment by alfaproject** [comment]
I guess this also raises the minimum version of Zone.js required

**Comment by alan-agius4** [comment]
> I guess this also raises the minimum version of Zone.js required.

If you use SSR, you might need to update to the latest patch version. For browsers only-apps it does not make a difference.

**Review by AndrewKushnir — APPROVED** [review]
Awesome refactoring, thanks @alan-agius4 👍

**Review by jessicajaniuk — APPROVED** [review]
LGTM!

**Comment by pkozlowski-opensource** [comment]
@alan-agius4 looks to me like TGP came back with a [real issue](https://fusion2.corp.google.com/presubmit/538732872/OCL:538732872:BASE:538732575:1686224407300:cc0f5dd1/targets/invocations/15dbb634-6614-41dd-8c9c-ef0f41522937/targets/%2F%2Fjava%2Fcom%2Fgoogle%2Fpersonalization%2Fchrome%2Fsync%2Fbackstreet%2Fasset%2Fv2:unit_tests_chrome-linux/tests)

**Comment by alan-agius4** [comment]
@pkozlowski-opensource, that has been addressed see. https://github.com/angular/angular/pull/50485#issuecomment-1582491411

**Comment by alan-agius4** [comment]
New TGP after deflaking http://fusion2/presubmit/540242848/OCL:540242848:BASE:540547048:1686837335541:f5eb70e4/targets

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 4550fe42f704b18f48bd0c490b0c6a283ea912c5.

**Pull request closed without merging**
