### PR TITLE
Require return types on public methods

### PR DESCRIPTION
**Pull request by alexeagle**
[Review on Reviewable](https://reviewable.io/reviews/angular/angular/2746)

### CODE REVIEW

**Comment by mhevery** [comment]
+(pr_state: LGTM) +(pr_action: cleanup) 

---

Reviewed 68 of 68 files at r1.
Review status: all files reviewed at latest revision, 30 unresolved discussions, some commit checks failed.

---

<sup>**[modules/angular2/src/core/application.ts, line 329 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jslyl6h_vTKc4fYWhL7)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/core/application.ts#L329)):</sup>
I think this should be void.

---

<sup>**[modules/angular2/src/core/application.ts, line 331 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-JslyvQZJsj2wrVfG9H7)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/core/application.ts#L331)):</sup>
remove `return`

---

<sup>**[modules/angular2/src/core/compiler/proto_view_factory.ts, line 289 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-JslzRgqTaxZKVDbHEKf)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/core/compiler/proto_view_factory.ts#L289)):</sup>
I think original was correct. This is a lost of strings `string[]`

---

<sup>**[modules/angular2/src/core/compiler/proto_view_factory.ts, line 294 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-JslzYZsZB1Z678M38fm)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/core/compiler/proto_view_factory.ts#L294)):</sup>
`(mappedName: string, varName:string) => ...`

---

<sup>**[modules/angular2/src/core/compiler/query_list.ts, line 81 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-JslzhxjIkFWAn7PDQbG)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/core/compiler/query_list.ts#L81)):</sup>
`: void`

---

<sup>**[modules/angular2/src/core/compiler/query_list.ts, line 85 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-JslzkRvdNU7w0ZAfw-z)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/core/compiler/query_list.ts#L85)):</sup>
`: void`

---

<sup>**[modules/angular2/src/directives/ng_for.ts, line 94 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm-r8pQ0dYN4An8QOW)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/directives/ng_for.ts#L94)):</sup>
`viewContainer: ViewContainerRef`

---

<sup>**[modules/angular2/src/dom/dom_adapter.ts, line 48 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm0E6PAMBlqlZP-MpY)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/dom/dom_adapter.ts#L48)):</sup>
I think there is some issue where our DOM.Adapter can not have any type, since these do not exist in node.js. Not sure if it is actually an issue.

---

<sup>**[modules/angular2/src/dom/generic_browser_adapter.ts, line 9 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm0_kG0emZl40ZV9kJ)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/dom/generic_browser_adapter.ts#L9)):</sup>
Do we not know the exact type here? (instead of any)

---

<sup>**[modules/angular2/src/dom/generic_browser_adapter.ts, line 22 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm0Y8ovY-qqj56LzKe)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/dom/generic_browser_adapter.ts#L22)):</sup>
Do we not know the exact type here?

---

<sup>**[modules/angular2/src/facade/async.ts, line 12 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm0hPVeHm_m6RR8jUf)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/async.ts#L12)):</sup>
can we add full signature to `resolve`/`reject`?

---

<sup>**[modules/angular2/src/facade/collection.ts, line 71 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm0sEeJDSvHp6Tk23F)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/collection.ts#L71)):</sup>
`iterable<T>(m: T):T` (not sure exact syntax)

---

<sup>**[modules/angular2/src/facade/lang.ts, line 42 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm1AuiVI5H4m1sS_VN)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/lang.ts#L42)):</sup>
`<T>(target: T>) => T`

---

<sup>**[modules/angular2/src/facade/lang.ts, line 46 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm1LNpDeclTFd7Md83)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/lang.ts#L46)):</sup>
same here, (generics)

---

<sup>**[modules/angular2/src/facade/lang.ts, line 53 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm1P5iMZ_lUmTyiGsH)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/lang.ts#L53)):</sup>
same here (generics)

---

<sup>**[modules/angular2/src/facade/lang.ts, line 216 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm1XgzCAiNAj471ND-)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/lang.ts#L216)):</sup>
`: {re: RegExp, input: string}`

---

<sup>**[modules/angular2/src/forms/model.ts, line 125 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm1rYYHYgB0dw820Cf)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/forms/model.ts#L125)):</sup>
`Map<string, string>`

---

<sup>**[modules/angular2/src/http/http.ts, line 177 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm24r64D3loEpXfiqK)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/http/http.ts#L177)):</sup>
Can we typedef this. (since dart does not support inline function declarations)

---

<sup>**[modules/angular2/src/render/dom/compiler/compile_control.ts, line 14 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm2YhZY7tjU0hBKYKw)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/compiler/compile_control.ts#L14)):</sup>
`CompileElement[]`

---

<sup>**[modules/angular2/src/render/dom/compiler/compile_control.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm2aDNGxP18r_izx1n)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/compiler/compile_control.ts#L21)):</sup>
`: CompileElement[]`

---

<sup>**[modules/angular2/src/render/dom/events/event_manager.ts, line 93 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm2mw5Ds9NNc6XV9yO)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/events/event_manager.ts#L93)):</sup>
typedef fns?

---

<sup>**[modules/angular2/src/render/dom/events/event_manager.ts, line 101 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm2oKPU2LsI2jywHwq)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/events/event_manager.ts#L101)):</sup>
typedef fns?

---

<sup>**[modules/angular2/src/render/dom/events/key_events.ts, line 95 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm3KCS1XmgL00S15Ct)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/events/key_events.ts#L95)):</sup>
typedef fns?

---

<sup>**[modules/angular2/src/render/dom/shadow_dom/emulated_unscoped_shadow_dom_strategy.ts, line 23 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm3RqCdEdiv9gpqfpP)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/shadow_dom/emulated_unscoped_shadow_dom_strategy.ts#L23)):</sup>
`Node`? (I think)

---

<sup>**[modules/angular2/src/render/dom/shadow_dom/native_shadow_dom_strategy.ts, line 13 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm3WiZa1q7S5eiFJB-)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/shadow_dom/native_shadow_dom_strategy.ts#L13)):</sup>
`Node` I think

---

<sup>**[modules/angular2/src/render/dom/view/view_container.ts, line 9 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm3jDlNtBYwAYzpJuv)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/view/view_container.ts#L9)):</sup>
`List<viewModule.DomView>`

---

<sup>**[modules/angular2/test/core/compiler/dynamic_component_loader_spec.ts, line 85 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm3xhKMwF6H2ST6qHQ)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/test/core/compiler/dynamic_component_loader_spec.ts#L85)):</sup>
`Element`?

---

<sup>**[modules/angular2/test/core/compiler/dynamic_component_loader_spec.ts, line 179 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm4-HxrgSfP4Bna7XB)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/test/core/compiler/dynamic_component_loader_spec.ts#L179)):</sup>
`Element`?

---

<sup>**[modules/angular2/test/render/dom/dom_renderer_integration_spec.ts, line 110 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm41Rq7jiMZCBPwkX9)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/test/render/dom/dom_renderer_integration_spec.ts#L110)):</sup>
`Element`?

---

<sup>**[modules/angular2/test/render/dom/dom_renderer_integration_spec.ts, line 113 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm4255mxx2vrf8jocE)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/test/render/dom/dom_renderer_integration_spec.ts#L113)):</sup>
`Element`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/angular/angular/2746)

**Comment by mhevery** [comment]
VERY NICE!

**Comment by alexeagle** [comment]
Review status: all files reviewed at latest revision, 29 unresolved discussions, some commit checks failed.

---

<sup>**[modules/angular2/src/core/application.ts, line 329 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jslyl6h_vTKc4fYWhL7)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/core/application.ts#L329)):</sup>
Done.

---

<sup>**[modules/angular2/src/core/application.ts, line 331 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-JslyvQZJsj2wrVfG9H7)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/core/application.ts#L331)):</sup>
Done.

---

<sup>**[modules/angular2/src/core/compiler/proto_view_factory.ts, line 289 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-JslzRgqTaxZKVDbHEKf)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/core/compiler/proto_view_factory.ts#L289)):</sup>
good catch. better fix is to type the [] below, then type inference works

---

<sup>**[modules/angular2/src/core/compiler/proto_view_factory.ts, line 294 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-JslzYZsZB1Z678M38fm)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/core/compiler/proto_view_factory.ts#L294)):</sup>
Done.

---

<sup>**[modules/angular2/src/core/compiler/query_list.ts, line 81 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-JslzhxjIkFWAn7PDQbG)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/core/compiler/query_list.ts#L81)):</sup>
void is implied by no return type now. (the .d.ts generator will insert the ":void")
Or do you think this is a spot where we should be extra explicit?
If we want to generally enforce ":void" on methods, it should be a follow up change since there are many spots to fix

---

<sup>**[modules/angular2/src/directives/ng_for.ts, line 94 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm-r8pQ0dYN4An8QOW)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/directives/ng_for.ts#L94)):</sup>
Done.

---

<sup>**[modules/angular2/src/dom/dom_adapter.ts, line 48 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm0E6PAMBlqlZP-MpY)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/dom/dom_adapter.ts#L48)):</sup>
the child classes declared Node type for some of these methods. and no tests fail. I'm not sure if there is some other issue?

---

<sup>**[modules/angular2/src/dom/generic_browser_adapter.ts, line 9 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm0_kG0emZl40ZV9kJ)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/dom/generic_browser_adapter.ts#L9)):</sup>
only comes from native API - looks like List<Node> should be correct.
http://www.w3.org/TR/shadow-dom/#widl-HTMLContentElement-getDistributedNodes-NodeList

---

<sup>**[modules/angular2/src/dom/generic_browser_adapter.ts, line 22 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm0Y8ovY-qqj56LzKe)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/dom/generic_browser_adapter.ts#L22)):</sup>
I spent a while on this one - I don't see any API that provides cssRules on the StyleSheet type.

---

<sup>**[modules/angular2/src/facade/async.ts, line 12 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm0hPVeHm_m6RR8jUf)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/async.ts#L12)):</sup>
Done.

---

<sup>**[modules/angular2/src/facade/collection.ts, line 71 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm0sEeJDSvHp6Tk23F)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/collection.ts#L71)):</sup>
Done.

---

<sup>**[modules/angular2/src/facade/lang.ts, line 42 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm1AuiVI5H4m1sS_VN)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/lang.ts#L42)):</sup>
Done.

---

<sup>**[modules/angular2/src/facade/lang.ts, line 46 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm1LNpDeclTFd7Md83)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/lang.ts#L46)):</sup>
Done.

---

<sup>**[modules/angular2/src/facade/lang.ts, line 53 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm1P5iMZ_lUmTyiGsH)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/lang.ts#L53)):</sup>
Done.

---

<sup>**[modules/angular2/src/facade/lang.ts, line 216 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm1XgzCAiNAj471ND-)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/facade/lang.ts#L216)):</sup>
Done.

---

<sup>**[modules/angular2/src/forms/model.ts, line 125 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm1rYYHYgB0dw820Cf)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/forms/model.ts#L125)):</sup>
Done.

---

<sup>**[modules/angular2/src/http/http.ts, line 177 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm24r64D3loEpXfiqK)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/http/http.ts#L177)):</sup>
actually there is already a type for it in ./interfaces

---

<sup>**[modules/angular2/src/render/dom/compiler/compile_control.ts, line 14 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm2YhZY7tjU0hBKYKw)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/compiler/compile_control.ts#L14)):</sup>
Done.

---

<sup>**[modules/angular2/src/render/dom/compiler/compile_control.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm2aDNGxP18r_izx1n)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/compiler/compile_control.ts#L21)):</sup>
Done.

---

<sup>**[modules/angular2/src/render/dom/events/event_manager.ts, line 93 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm2mw5Ds9NNc6XV9yO)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/events/event_manager.ts#L93)):</sup>
Done.

---

<sup>**[modules/angular2/src/render/dom/events/event_manager.ts, line 101 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm2oKPU2LsI2jywHwq)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/events/event_manager.ts#L101)):</sup>
Done.

---

<sup>**[modules/angular2/src/render/dom/events/key_events.ts, line 95 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm3KCS1XmgL00S15Ct)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/events/key_events.ts#L95)):</sup>
Done.

---

<sup>**[modules/angular2/src/render/dom/shadow_dom/emulated_unscoped_shadow_dom_strategy.ts, line 23 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm3RqCdEdiv9gpqfpP)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/shadow_dom/emulated_unscoped_shadow_dom_strategy.ts#L23)):</sup>
Done.

---

<sup>**[modules/angular2/src/render/dom/shadow_dom/native_shadow_dom_strategy.ts, line 13 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm3WiZa1q7S5eiFJB-)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/shadow_dom/native_shadow_dom_strategy.ts#L13)):</sup>
Done.

---

<sup>**[modules/angular2/src/render/dom/view/view_container.ts, line 9 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm3jDlNtBYwAYzpJuv)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/src/render/dom/view/view_container.ts#L9)):</sup>
Done.

---

<sup>**[modules/angular2/test/core/compiler/dynamic_component_loader_spec.ts, line 85 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm3xhKMwF6H2ST6qHQ)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/test/core/compiler/dynamic_component_loader_spec.ts#L85)):</sup>
HTMLElement works

---

<sup>**[modules/angular2/test/core/compiler/dynamic_component_loader_spec.ts, line 179 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm4-HxrgSfP4Bna7XB)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/test/core/compiler/dynamic_component_loader_spec.ts#L179)):</sup>
Done.

---

<sup>**[modules/angular2/test/render/dom/dom_renderer_integration_spec.ts, line 110 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm41Rq7jiMZCBPwkX9)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/test/render/dom/dom_renderer_integration_spec.ts#L110)):</sup>
HTMLInputElement works

---

<sup>**[modules/angular2/test/render/dom/dom_renderer_integration_spec.ts, line 113 \[r1\]](https://reviewable.io:443/reviews/angular/angular/2746#-Jsm4255mxx2vrf8jocE)** ([raw file](https://github.com/angular/angular/blob/2f762e726fe0aff63623ca7c9324e74e53c2aac8/modules/angular2/test/render/dom/dom_renderer_integration_spec.ts#L113)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/angular/angular/2746)

**Comment by alexeagle** [comment]
Merged in 44891996b592cbbeafb3a6f45a27d8d943895bab

**Pull request closed without merging**
