### PR TITLE
refactor(core): signal epoch limit numeric value range

### PR DESCRIPTION
**Pull request by leonelvsc**
Remove all limitations of numeric values and make epoch versions safe for comparing in all cases.

For long running apps with alot of value changes like an always on display showing realtime trading data, industrial apps, flight radars and alike.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER.

I've created a new type just for the `epoch`, as `signal versions` are safe. The problem `epoch++` is called everytime a signal value change occurs so as more producers you have in the graph less time you need to reach MAX_SAFE_INTEGER.

Theorical limit for 1 live consumer up to `2**32-1` producers that's 4294967295 producers as `2**32-1` is the max array index in javascript, so: 4294967295 updates their values every 1 second we are moving epoch 4294967295 times in each "loop"  it takes about 24 hours to reach `2**53-1`

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
This has been discussed already. Max integer is `2**53-1`. 

If we had 1 update every ms. It would take almost 300 000 years to reach the limit. 

We can reasonable say that it will never be reached.

**Comment by leonelvsc** [comment]
> This has been discussed already. Max integer is `2**53-1`.
> 
> If we had 1 update every ms. It would take almost 300 000 years to reach the limit. (`Number.MAX_SAFE_INTEGER / (1000*60*60*24*365)`)
> 
> We can reasonable say that it will never be reached.

I agree but that is for 1 producer, if you have `n` producer in the graph its `/n` because the value is incremented everytime it changes.
Like the algorithm just campares versions it's also safe to say that a number between 0 and 2**32-1 ( going back to 0 again ) is safe.

**Comment by JeanMeche** [comment]
My point is also that Max integer is not `2^32` but `2^54` which makes a huge difference.

**Comment by leonelvsc** [comment]
> My point is also that Max integer is not `2^32` but `2^54` which makes a huge difference.



> My point is also that Max integer is not `2^32` but `2^54` which makes a huge difference.

Yes, i would agree with you if you need huge numbers, but in `graph.ts` you only compare nodes versions against edges seen versions. I thought of this modification as a safe way of comparing versions.

But i can be wrong, just wanted the give you the heads up about this, if you already discussed this just don't merge this commit

**Comment by leonelvsc** [comment]
@JeanMeche @atscott
Last proposal, how about using `Symbol()` instead of `version++` it could run forever without limitations as each `symbol` is unique it should also have equal performance as it's a primitive.

I'll change the state from draft to ready for review so you can discard or approve this pull request, but i think at least it's worth the discussion

**Comment by leonelvsc** [comment]
Note: I've changed the type of `Version` but it could be also be applied just for the `epoch` with a new type and leave `node.version` as a branded type number

**Comment by leonelvsc** [comment]
Changed back to the original implementation as it's more performant and changed the main description with use cases that could broke `epoch++`

**Comment by atscott** [comment]
Closing - there's no indication that this is a change that needs to be made at this time. If this becomes an actual problem that applications run into, we can reconsider.

**Pull request closed without merging**
