### PR TITLE
fix(BaseException): Change to interface implements instead of class extends

### PR DESCRIPTION
**Pull request by Bogatinov**
`Error` from `lib.d.ts` is interface and does not need `super()`

Interface requires for these to be implemented 

``` javascript
name:string
message:string
```

### CODE REVIEW

**Comment by Bogatinov** [comment]
### CLA
I signed it!

**Comment by Bogatinov** [comment]
### CLA
I signed it!

**Comment by Bogatinov** [comment]
### CLA
I signed it!

**Comment by jeffbcross** [comment]
The typescript version being used in this project does treat Error as a class, it's installed from @alexeagle's fork with a branch specifically for that purpose: "alexeagle/TypeScript#error_is_class" in package.json.

**Pull request closed without merging**
