### PR TITLE
docs(changelog): remove docs-infra changes

### PR DESCRIPTION
**Pull request by trotyl**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

`docs-infra` changes removed from CHANGELOG.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by jenniferfell** [comment]
@gkalpak @IgorMinar Question: Why would we remove docs-infra changes from the changelog? 

If we don't describe docs-infra and docs changes as part of the master changelog, then is there another place these are documented and shared? Do we need to keep and publish additional change logs for docs-infra and docs themselves?(related to https://github.com/angular/angular/issues/23615 and https://github.com/angular/angular/issues/22489, in which there is consideration of removing a docs-specific change log in favor of having everything in the one changelog).

**Comment by gkalpak** [comment]
The main point is that `CHANGELOG.md` is for framework changes (which most people looking at that file are looking for). The fact that the docs viewer app is part of the repo and thus the git history includes changes to the app is irrelevant for most people. (More or less the same holds for docs-only changes.)

Having a docs-only changelog is an interesting idea. We could run a similar process to the one we use to populate `CHANGELOG.md` for populating another changelog with docs-only changes.

(`I don't see much value in `docs-infra` changes, since this is only relevant to few of us and it is easy (even if rarely useful) to find the history through `git`.)

**Comment by brandonroberts** [comment]
@gkalpak can this be closed?

**Comment by gkalpak** [comment]
I have approved it, but was waiting for feedback from @IgorMinar and @jenniferfell.
FWIW, I think it is a good change (but minor, so I am fine if you feel like closing it).

**Comment by brandonroberts** [comment]
I'm fine with the change also, just wasn't sure if it was still needed. I'll wait on further review

**Comment by brandonroberts** [comment]
@trotyl will you rebase this on master?

**Comment by trotyl** [comment]
@brandonroberts Rebased.

**Pull request closed without merging**
