### PR TITLE
aio/docs - inherit line-height to list item anchors

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
in order to have a consistent line-height between list items containing text and list items containing links the anchors should inherit the list item's line-height

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

List items comprised of a single link get an inconsistent line-height

As you can for example see here: https://angular.io/guide/template-syntax
Screenshot at 2021-06-14 18-09-44
and here: https://angular.io/guide/template-syntax#prerequisites
Screenshot at 2021-06-14 18-09-18

(note that the list items with the links are slightly more distanciated)

## What is the new behavior?

The anchors inherit the list item's line-height and all list items are then spaced consistently

as for example:
Screenshot at 2021-06-14 18-13-55

Screenshot at 2021-06-14 18-14-16

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Good eye 👁️ :100:
Thx, @dario-piotrowicz :+1:

**Comment by gkalpak** [comment]
Can you please rebase this on latest master to make CI green, @dario-piotrowicz? 🙏

**Comment by dario-piotrowicz** [comment]
Thanks @gkalpak

Rebase done! :) 

(sorry I had no idea that was making the CI red)

**Comment by dario-piotrowicz** [comment]
@gkalpak sorry just out of curiosity... do you know why this one didn't get a mary-poppins deployment? :slightly_smiling_face:


(I thought all PRs to aio got one :confused: )

**Comment by petebacondarwin** [comment]
Some special people get previews for all the PRs (e.g. @gkalpak) but for the rest the PR needs to have the `aio: preview` label added.

**Comment by dario-piotrowicz** [comment]
ahhhh yeah, my other PRs do have that tag!

Yeah it does make sense I guess (otherwise some clever trickery should implemented in the CI to understand whether a PR is an aio one or not)

Sorry for the silly question and thanks for the explanation @petebacondarwin :slightly_smiling_face:

**Comment by petebacondarwin** [comment]
Not silly at all - and not necessarily intuitive. The main reason for this constraint is to prevent abuse of our preview server by people posting PRs that contain malicious code.

**Comment by dario-piotrowicz** [comment]
@petebacondarwin wow yeah that really makes a lot of sense! I didn't think of malicious intent! that's very interesting, thanks again! :slightly_smiling_face: 

Also @gkalpak thanks for the tag ( I appreciated it but I honestly was just simply asking out curiosity :stuck_out_tongue_winking_eye: )

**Comment by gkalpak** [comment]
There you go, @dario-piotrowicz 😛

As @petebacondarwin said, this is mostly a security precaution. Basically, all PRs that touch files that may affect angular.io get their previews generated on the preview server, but only those that have the `aio: preview` label or come from "special people" (😛) have their previews publicly available.
If you are interested, you can read more about the previews [here][1].

[1]: https://github.com/angular/angular/blob/b52e93543f617b7242d01152e4c8f6c1452485ea/aio/aio-builds-setup/docs/_TOC.md

**Comment by dario-piotrowicz** [comment]
Ah wow, thanks a bunch @gkalpak I'll give the doc a read :slightly_smiling_face: 
( but CI and docker are really not my thing :stuck_out_tongue_winking_eye:  )

**Pull request closed without merging**
