### PR TITLE
refactor(router):remove unused parameter pathIndex

### PR DESCRIPTION
**Pull request by dejour**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
pathIndex is passed around but never used

### CODE REVIEW

**Comment by DzmitryShylovich** [comment]
> fix(router):remove unused parameter pathIndex|

u don't fix anything. it's a refactor

**Comment by dejour** [comment]
how can i change the commit message to refactor without add a new commit

**Comment by DzmitryShylovich** [comment]
u can add a second commit and then squash them using interactive rebase `git rebase -i HEAD~2`

**Comment by dejour** [comment]
@DzmitryShylovich should i create a new branch? seems like i was doing it wrong, it contains three commit now

**Comment by DzmitryShylovich** [comment]
yeah, create a new branch :)

**Pull request closed without merging**
