### PR TITLE
test: update side-effects test to be more descriptive

### LINKED ISSUE #30570: Side effects test needs more details
We recently ran into this test failure on CI:

https://circleci.com/gh/angular/angular/328483#tests/containers/3

It's not clear from this message what actual side effects were added (nothing is printed) and it's also not clear what actions need to be taken.

There is this sentence on the bottom, but it doesn't contain a command:

> To update the expectations, run this command again with the --update flag.

I assume it's this from above?
> check-side-effects --test side-effects.json --pure-getters

We should print the full command to run like we do for the symbol tests.

### PR DESCRIPTION
**Pull request by filipesilva**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Fix #30570

## What is the new behavior?
This test will now list diffs for failed expectations and the full command to update them.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Why is this marked as `master-only`?

**Comment by filipesilva** [comment]
Here is an example of how the output when testing the 8.0.0 packages against the current snapshots:

Before:
```
Loading tests from D:\work\angular\integration\side-effects\side-effects.json

Testing ./node_modules/@angular/animations/esm5/animations.js
Testing ./node_modules/@angular/animations/fesm5/animations.js
Testing ./node_modules/@angular/animations/esm2015/animations.js
Testing ./node_modules/@angular/animations/fesm2015/animations.js
Testing ./node_modules/@angular/animations/esm5/browser/browser.js
Testing ./node_modules/@angular/animations/fesm5/browser.js
Testing ./node_modules/@angular/animations/esm2015/browser/browser.js
Testing ./node_modules/@angular/animations/fesm2015/browser.js
Testing ./node_modules/@angular/common/esm5/common.js
Testing ./node_modules/@angular/common/fesm5/common.js
Testing ./node_modules/@angular/common/esm2015/common.js
Testing ./node_modules/@angular/common/fesm2015/common.js
Testing ./node_modules/@angular/core/esm5/core.js
Testing ./node_modules/@angular/core/fesm5/core.js
Testing ./node_modules/@angular/core/esm2015/core.js
Testing ./node_modules/@angular/core/fesm2015/core.js
Testing ./node_modules/@angular/elements/esm5/elements.js
Testing ./node_modules/@angular/elements/fesm5/elements.js
Testing ./node_modules/@angular/elements/esm2015/elements.js
Testing ./node_modules/@angular/elements/fesm2015/elements.js
Testing ./node_modules/@angular/forms/esm5/forms.js
Testing ./node_modules/@angular/forms/fesm5/forms.js
Testing ./node_modules/@angular/forms/esm2015/forms.js
Testing ./node_modules/@angular/forms/fesm2015/forms.js
Testing ./node_modules/@angular/platform-browser/esm5/platform-browser.js
Testing ./node_modules/@angular/platform-browser/fesm5/platform-browser.js
Testing ./node_modules/@angular/platform-browser/esm2015/platform-browser.js
Testing ./node_modules/@angular/platform-browser/fesm2015/platform-browser.js
Testing ./node_modules/@angular/router/esm5/router.js
Testing ./node_modules/@angular/router/fesm5/router.js
Testing ./node_modules/@angular/router/esm2015/router.js
Testing ./node_modules/@angular/router/fesm2015/router.js

Tests failed for modules:
  ./node_modules/@angular/core/esm5/core.js
  ./node_modules/@angular/core/fesm5/core.js
  ./node_modules/@angular/core/esm2015/core.js
  ./node_modules/@angular/core/fesm2015/core.js

To update the expectations, run this command again with the --update flag.
```

After:
```
Loading tests from D:\work\angular\integration\side-effects\side-effects.json

Testing ./node_modules/@angular/animations/esm5/animations.js
Testing ./node_modules/@angular/animations/fesm5/animations.js
Testing ./node_modules/@angular/animations/esm2015/animations.js
Testing ./node_modules/@angular/animations/fesm2015/animations.js
Testing ./node_modules/@angular/animations/esm5/browser/browser.js
Testing ./node_modules/@angular/animations/fesm5/browser.js
Testing ./node_modules/@angular/animations/esm2015/browser/browser.js
Testing ./node_modules/@angular/animations/fesm2015/browser.js
Testing ./node_modules/@angular/common/esm5/common.js
Testing ./node_modules/@angular/common/fesm5/common.js
Testing ./node_modules/@angular/common/esm2015/common.js
Testing ./node_modules/@angular/common/fesm2015/common.js
Testing ./node_modules/@angular/core/esm5/core.js
Testing ./node_modules/@angular/core/fesm5/core.js
Testing ./node_modules/@angular/core/esm2015/core.js
Testing ./node_modules/@angular/core/fesm2015/core.js
Testing ./node_modules/@angular/elements/esm5/elements.js
Testing ./node_modules/@angular/elements/fesm5/elements.js
Testing ./node_modules/@angular/elements/esm2015/elements.js
Testing ./node_modules/@angular/elements/fesm2015/elements.js
Testing ./node_modules/@angular/forms/esm5/forms.js
Testing ./node_modules/@angular/forms/fesm5/forms.js
Testing ./node_modules/@angular/forms/esm2015/forms.js
Testing ./node_modules/@angular/forms/fesm2015/forms.js
Testing ./node_modules/@angular/platform-browser/esm5/platform-browser.js
Testing ./node_modules/@angular/platform-browser/fesm5/platform-browser.js
Testing ./node_modules/@angular/platform-browser/esm2015/platform-browser.js
Testing ./node_modules/@angular/platform-browser/fesm2015/platform-browser.js
Testing ./node_modules/@angular/router/esm5/router.js
Testing ./node_modules/@angular/router/fesm5/router.js
Testing ./node_modules/@angular/router/esm2015/router.js
Testing ./node_modules/@angular/router/fesm2015/router.js

The following snapshots have changed:


Snapshot for ./node_modules/@angular/core/esm5/core.js changed:

Index: D:\work\angular\integration\side-effects\snapshots\core\esm5.js
===================================================================
--- D:\work\angular\integration\side-effects\snapshots\core\esm5.js
+++ D:\work\angular\integration\side-effects\snapshots\core\esm5.js
@@ -2,4 +2,16 @@

 import "rxjs";

 import "rxjs/operators";
+
+function getGlobal() {
+    var __globalThis = "undefined" !== typeof globalThis && globalThis;
+    var __window = "undefined" !== typeof window && window;
+    var __self = "undefined" !== typeof self && "undefined" !== typeof WorkerGlobalScope && self instanceof WorkerGlobalScope && self;
+    var __global = "undefined" !== typeof global && global;
+    return __globalThis || __global || __window || __self;
+}
+
+var _global = getGlobal();
+
+if ("undefined" === typeof ngI18nClosureMode) _global["ngI18nClosureMode"] = "undefined" !== typeof goog && "function" === typeof goog.getMsg;


Snapshot for ./node_modules/@angular/core/fesm5/core.js changed:

Index: D:\work\angular\integration\side-effects\snapshots\core\esm5.js
===================================================================
--- D:\work\angular\integration\side-effects\snapshots\core\esm5.js
+++ D:\work\angular\integration\side-effects\snapshots\core\esm5.js
@@ -2,4 +2,16 @@

 import "rxjs";

 import "rxjs/operators";
+
+function getGlobal() {
+    var __globalThis = "undefined" !== typeof globalThis && globalThis;
+    var __window = "undefined" !== typeof window && window;
+    var __self = "undefined" !== typeof self && "undefined" !== typeof WorkerGlobalScope && self instanceof WorkerGlobalScope && self;
+    var __global = "undefined" !== typeof global && global;
+    return __globalThis || __global || __window || __self;
+}
+
+var _global = getGlobal();
+
+if ("undefined" === typeof ngI18nClosureMode) _global["ngI18nClosureMode"] = "undefined" !== typeof goog && "function" === typeof goog.getMsg;


Snapshot for ./node_modules/@angular/core/esm2015/core.js changed:

Index: D:\work\angular\integration\side-effects\snapshots\core\esm2015.js
===================================================================
--- D:\work\angular\integration\side-effects\snapshots\core\esm2015.js
+++ D:\work\angular\integration\side-effects\snapshots\core\esm2015.js
@@ -1,3 +1,147 @@
-import "rxjs";
+import { Subject, Subscription } from "rxjs";

 import "rxjs/operators";
+
+function getGlobal() {
+    const __globalThis = "undefined" !== typeof globalThis && globalThis;
+    const __window = "undefined" !== typeof window && window;
+    const __self = "undefined" !== typeof self && "undefined" !== typeof WorkerGlobalScope && self instanceof WorkerGlobalScope && self;
+    const __global = "undefined" !== typeof global && global;
+    return __globalThis || __global || __window || __self;
+}
+
+const _global = getGlobal();
+
+let _symbolIterator = null;
+
+function getSymbolIterator() {
+    if (!_symbolIterator) {
+        const Symbol = _global["Symbol"];
+        if (Symbol && Symbol.iterator) _symbolIterator = Symbol.iterator; else {
+            const keys = Object.getOwnPropertyNames(Map.prototype);
+            for (let i = 0; i < keys.length; ++i) {
+                const key = keys[i];
+                if ("entries" !== key && "size" !== key && Map.prototype[key] === Map.prototype["entries"]) _symbolIterator = key;
+            }
+        }
+    }
+    return _symbolIterator;
+}
+
+if ("undefined" === typeof ngI18nClosureMode) _global["ngI18nClosureMode"] = "undefined" !== typeof goog && "function" === typeof goog.getMsg;
+
+function flatten(list, dst) {
+    if (void 0 === dst) dst = list;
+    for (let i = 0; i < list.length; i++) {
+        let item = list[i];
+        if (Array.isArray(item)) {
+            if (dst === list) dst = list.slice(0, i);
+            flatten(item, dst);
+        } else if (dst !== list) dst.push(item);
+    }
+    return dst;
+}
+
+class EventEmitter extends Subject {
+    constructor(isAsync = false) {
+        super();
+        this.__isAsync = isAsync;
+    }
+    emit(value) {
+        super.next(value);
+    }
+    subscribe(generatorOrNext, error, complete) {
+        let schedulerFn;
+        let errorFn = err => null;
+        let completeFn = () => null;
+        if (generatorOrNext && "object" === typeof generatorOrNext) {
+            schedulerFn = this.__isAsync ? value => {
+                setTimeout(() => generatorOrNext.next(value));
+            } : value => {
+                generatorOrNext.next(value);
+            };
+            if (generatorOrNext.error) errorFn = this.__isAsync ? err => {
+                setTimeout(() => generatorOrNext.error(err));
+            } : err => {
+                generatorOrNext.error(err);
+            };
+            if (generatorOrNext.complete) completeFn = this.__isAsync ? () => {
+                setTimeout(() => generatorOrNext.complete());
+            } : () => {
+                generatorOrNext.complete();
+            };
+        } else {
+            schedulerFn = this.__isAsync ? value => {
+                setTimeout(() => generatorOrNext(value));
+            } : value => {
+                generatorOrNext(value);
+            };
+            if (error) errorFn = this.__isAsync ? err => {
+                setTimeout(() => error(err));
+            } : err => {
+                error(err);
+            };
+            if (complete) completeFn = this.__isAsync ? () => {
+                setTimeout(() => complete());
+            } : () => {
+                complete();
+            };
+        }
+        const sink = super.subscribe(schedulerFn, errorFn, completeFn);
+        if (generatorOrNext instanceof Subscription) generatorOrNext.add(sink);
+        return sink;
+    }
+}
+
+class QueryList {
+    constructor() {
+        this.dirty = true;
+        this._results = [];
+        this.changes = new EventEmitter();
+        this.length = 0;
+    }
+    map(fn) {
+        return this._results.map(fn);
+    }
+    filter(fn) {
+        return this._results.filter(fn);
+    }
+    find(fn) {
+        return this._results.find(fn);
+    }
+    reduce(fn, init) {
+        return this._results.reduce(fn, init);
+    }
+    forEach(fn) {
+        this._results.forEach(fn);
+    }
+    some(fn) {
+        return this._results.some(fn);
+    }
+    toArray() {
+        return this._results.slice();
+    }
+    [getSymbolIterator()]() {
+        return this._results[getSymbolIterator()]();
+    }
+    toString() {
+        return this._results.toString();
+    }
+    reset(resultsTree) {
+        this._results = flatten(resultsTree);
+        this.dirty = false;
+        this.length = this._results.length;
+        this.last = this._results[this.length - 1];
+        this.first = this._results[0];
+    }
+    notifyOnChanges() {
+        this.changes.emit(this);
+    }
+    setDirty() {
+        this.dirty = true;
+    }
+    destroy() {
+        this.changes.complete();
+        this.changes.unsubscribe();
+    }
+}


Snapshot for ./node_modules/@angular/core/fesm2015/core.js changed:

Index: D:\work\angular\integration\side-effects\snapshots\core\esm2015.js
===================================================================
--- D:\work\angular\integration\side-effects\snapshots\core\esm2015.js
+++ D:\work\angular\integration\side-effects\snapshots\core\esm2015.js
@@ -1,3 +1,147 @@
-import "rxjs";
+import { Subject, Subscription } from "rxjs";

 import "rxjs/operators";
+
+function getGlobal() {
+    const __globalThis = "undefined" !== typeof globalThis && globalThis;
+    const __window = "undefined" !== typeof window && window;
+    const __self = "undefined" !== typeof self && "undefined" !== typeof WorkerGlobalScope && self instanceof WorkerGlobalScope && self;
+    const __global = "undefined" !== typeof global && global;
+    return __globalThis || __global || __window || __self;
+}
+
+const _global = getGlobal();
+
+let _symbolIterator = null;
+
+function getSymbolIterator() {
+    if (!_symbolIterator) {
+        const Symbol = _global["Symbol"];
+        if (Symbol && Symbol.iterator) _symbolIterator = Symbol.iterator; else {
+            const keys = Object.getOwnPropertyNames(Map.prototype);
+            for (let i = 0; i < keys.length; ++i) {
+                const key = keys[i];
+                if ("entries" !== key && "size" !== key && Map.prototype[key] === Map.prototype["entries"]) _symbolIterator = key;
+            }
+        }
+    }
+    return _symbolIterator;
+}
+
+if ("undefined" === typeof ngI18nClosureMode) _global["ngI18nClosureMode"] = "undefined" !== typeof goog && "function" === typeof goog.getMsg;
+
+function flatten(list, dst) {
+    if (void 0 === dst) dst = list;
+    for (let i = 0; i < list.length; i++) {
+        let item = list[i];
+        if (Array.isArray(item)) {
+            if (dst === list) dst = list.slice(0, i);
+            flatten(item, dst);
+        } else if (dst !== list) dst.push(item);
+    }
+    return dst;
+}
+
+class EventEmitter extends Subject {
+    constructor(isAsync = false) {
+        super();
+        this.__isAsync = isAsync;
+    }
+    emit(value) {
+        super.next(value);
+    }
+    subscribe(generatorOrNext, error, complete) {
+        let schedulerFn;
+        let errorFn = err => null;
+        let completeFn = () => null;
+        if (generatorOrNext && "object" === typeof generatorOrNext) {
+            schedulerFn = this.__isAsync ? value => {
+                setTimeout(() => generatorOrNext.next(value));
+            } : value => {
+                generatorOrNext.next(value);
+            };
+            if (generatorOrNext.error) errorFn = this.__isAsync ? err => {
+                setTimeout(() => generatorOrNext.error(err));
+            } : err => {
+                generatorOrNext.error(err);
+            };
+            if (generatorOrNext.complete) completeFn = this.__isAsync ? () => {
+                setTimeout(() => generatorOrNext.complete());
+            } : () => {
+                generatorOrNext.complete();
+            };
+        } else {
+            schedulerFn = this.__isAsync ? value => {
+                setTimeout(() => generatorOrNext(value));
+            } : value => {
+                generatorOrNext(value);
+            };
+            if (error) errorFn = this.__isAsync ? err => {
+                setTimeout(() => error(err));
+            } : err => {
+                error(err);
+            };
+            if (complete) completeFn = this.__isAsync ? () => {
+                setTimeout(() => complete());
+            } : () => {
+                complete();
+            };
+        }
+        const sink = super.subscribe(schedulerFn, errorFn, completeFn);
+        if (generatorOrNext instanceof Subscription) generatorOrNext.add(sink);
+        return sink;
+    }
+}
+
+class QueryList {
+    constructor() {
+        this.dirty = true;
+        this._results = [];
+        this.changes = new EventEmitter();
+        this.length = 0;
+    }
+    map(fn) {
+        return this._results.map(fn);
+    }
+    filter(fn) {
+        return this._results.filter(fn);
+    }
+    find(fn) {
+        return this._results.find(fn);
+    }
+    reduce(fn, init) {
+        return this._results.reduce(fn, init);
+    }
+    forEach(fn) {
+        this._results.forEach(fn);
+    }
+    some(fn) {
+        return this._results.some(fn);
+    }
+    toArray() {
+        return this._results.slice();
+    }
+    [getSymbolIterator()]() {
+        return this._results[getSymbolIterator()]();
+    }
+    toString() {
+        return this._results.toString();
+    }
+    reset(resultsTree) {
+        this._results = flatten(resultsTree);
+        this.dirty = false;
+        this.length = this._results.length;
+        this.last = this._results[this.length - 1];
+        this.first = this._results[0];
+    }
+    notifyOnChanges() {
+        this.changes.emit(this);
+    }
+    setDirty() {
+        this.dirty = true;
+    }
+    destroy() {
+        this.changes.complete();
+        this.changes.unsubscribe();
+    }
+}


4 tests failed, see above for diffs.
To update the expectations, run this command again with the --update flag:

  C:\Program Files\nodejs\node.exe D:\work\angular\integration\side-effects\node_modules\check-side-effects\bin\check-side-effects --test side-effects.json --pure-getters --update
```

**Comment by filipesilva** [comment]
@gkalpak I think it won't really make a difference for patch. Do you think patch should get it as well?

**Comment by gkalpak** [comment]
If possible, yes. If anything, it would avoid potential conflicts when cherrypicking other changes.

**Comment by filipesilva** [comment]
Done

**Review by kara — APPROVED** [review]
LGTM, thanks for adding some details!

**Pull request closed without merging**
