### PR TITLE
docs(aio): fix punctuation for clarity

### PR DESCRIPTION
**Pull request by strogonoff**
Removed confusing full stop in the middle of a sentence.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by strogonoff** [comment]
Travis build seems to be failing for unrelated reason, since this is purely a doc content change. Not sure if there’s a way to re-run the checks?

**Comment by strogonoff** [comment]
Are typo corrections like that welcome, by the way? Should contributors bunch multiple fixes in larger PRs instead of submitting these tiny ones?

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
The Travis failures are indeed unrelated to this PR.

@strogonoff, typo fixes are definitely welcome :smiley: Feel free to bunch them in larger PRs.

**Comment by alexeagle** [comment]
@kara this doesn't affect google3, merge away

**Pull request closed without merging**
