### PR TITLE
build: update minimum yarn version to 1.10.0

### PR DESCRIPTION
**Pull request by jasonaden**

### CODE REVIEW

**Review by gkalpak — CHANGES_REQUESTED** [review]
You also need to update some other files (e.g. [this][1], [this][2], [this][3] and [that][4]) and also make sure that the version of `ngcontainer` used provides an appropriate version (which it [probably doesn't][5]).

[1]: https://github.com/angular/angular/blob/5f95a1d6530dd0c52c7a665cc3ff4059ff844428/WORKSPACE#L114
[2]: https://github.com/angular/angular/blob/5f95a1d6530dd0c52c7a665cc3ff4059ff844428/aio/tools/examples/shared/package.json#L15
[3]: https://github.com/angular/angular/blob/5f95a1d6530dd0c52c7a665cc3ff4059ff844428/integration/bazel/WORKSPACE#L44
[4]: https://github.com/angular/angular/blob/5f95a1d6530dd0c52c7a665cc3ff4059ff844428/scripts/ci/env.sh#L38
[5]: https://github.com/angular/angular/blame/5f95a1d6530dd0c52c7a665cc3ff4059ff844428/tools/ngcontainer/README.md#L7

**Comment by IgorMinar** [comment]
yeah.. what @gkalpak said... the ngcontainer needs an update for this to affect circle.

**Comment by alexeagle** [comment]
FYI https://github.com/angular/angular/pull/26435/files might be good to include too?

**Comment by IgorMinar** [comment]
this PR is now obsolete. closing.

**Pull request closed without merging**
