### PR TITLE
feat(benchmarks): add angularjs 1.x largetable benchmark

### PR DESCRIPTION
**Pull request by jeffbcross**

### CODE REVIEW

**Comment by jeffbcross** [comment]
@tbosch let's take a look when you have some time. With some runs, I'm seeing sample numbers consistently alternate between a high value and low value every other run. i.e. 
Sample1: 100
Sample2: 50
Sample3: 100
Sample4: 50

At first I thought perhaps a sample was being collected for each of the two buttons clicked, but that is not the case. Whatever the reason, it's making it difficult to get stable numbers out of the more expensive variables to this benchmark.

**Comment by jeffbcross** [comment]
I didn't experience any of the jasmine timeouts reported by Travis locally. I probably just need to bad the custom timeout I'm providing to benchpress and jasmine, since benchpress's isn't a hard timeout.

**Comment by jeffbcross** [comment]
@tbosch I just removed the timeout logic and reduced the work in the benchmark (from 1000 rows in the table down to 100).

**Comment by jeffbcross** [comment]
@tbosch I just rebased and squashed (Travis was green).

How would you like to proceed? The benchmark is nearly identical to the implementation from angular/angular.js - should we change it to make it easier for apples to apples comparison with other angular versions?

**Comment by mhevery** [comment]
Closed by: bc8e517

**Pull request closed without merging**
