### PR TITLE
revert absolute URL changes (patch only)

### PR DESCRIPTION
**Pull request by CaerusKaru**
In 10.0.0-next.8, a change was introduced into Universal (platform-server) to support relative URL HTTP requests on the server. Previously, this was unsupported and browser-specific behavior (since there is no concept of current page/routing natively on the server). However, there were issues with the behavior, notably that the logic would execute before user's `HttpInterceptor`s, and thus constituted a breaking change. Adding a flag to revert back to the default for all users while allowing opt-in to the new behavior would constitute a public API change, but since we were already in the middle of the RC period, this was not considered the safe approach.

Therefore, the decision was made to revert these changes in the patch branch (10.0.x) and keep the changes plus the public API fix (#37539) in the main branch (10.1.x).

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by kyliau — APPROVED** [review]

**Comment by kyliau** [comment]
Caretaker: This PR targets patch branch, so there's no reason to run g3 presubmit.
@josephperrott Could you please confirm that presubmit is not needed for patch PRs?

**Comment by kyliau** [comment]
Copybara error when running presubmit:
```
Task: GitHub PR Origin: Resolving reference a937889c3b013ba3341d24eb3c74908fd6995a0e
ERROR: Cannot find last imported revision. Use --force if you really want to proceed with the migration
  CAUSED BY: Cannot find reference 'a937889c3b013ba3341d24eb3c74908fd6995a0e'
```

**Comment by josephperrott** [comment]
@kyliau Correct, no g3 presubmit is needed for non-master branch PRs

**Review by alan-agius4 — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Hi, it looks like @mhevery merged these changes to the patch branch, but since it's a patch-only PR, it was not closed automatically, so I'm closing it manually now. Feel free to reopen if needed. Thank you.

**Pull request closed without merging**
