### PR TITLE
docs(common): update ngForTrackBy error URL

### PR DESCRIPTION
**Pull request by LayZeeDK**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Error message refers to URL that is redirected to `https://angular.io/api/common/NgForOf#!#change-propagation`

Issue Number: N/A

## What is the new behavior?
Error message refers to `https://angular.io/api/common/NgForOf#change-propagation`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jbogarthyde** [comment]
The new URL is correct, so from a doc POV it's fine.
This is actually a code change, rather than a doc change (the error message itself is part of the definition and does not itself appear in the doc). So this needs code-owner approval as well as doc approval.

**Review by jbogarthyde — APPROVED** [review]
Doc URL is correct - thanks!

**Comment by LayZeeDK** [comment]
>This is actually a code change, rather than a doc change (the error message itself is part of the definition and does not appear in the doc)

Thanks, I was in doubt.

**Comment by LayZeeDK** [comment]
It would probably be better to create a g.co short URL in case the documentation URL changes again.

**Review by mhevery — APPROVED** [review]

**Pull request closed without merging**
