### PR TITLE
chore: cleanup polyfills by importing zone.js directly in angular.json

### PR DESCRIPTION
**Pull request by JeanMeche**
Since v15, polyfills can be passed directly into angular.json let use this opportunity to reduce the number of unecessary files.

## PR Type
- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [x] No

### CODE REVIEW

**Review by alan-agius4 — COMMENTED** [review]
You need to amend the tsconfig files not to include `polyfills.TS`

**Review by alan-agius4 — APPROVED** [review]

**Comment by alan-agius4** [comment]
Thanks for this

**Review by jessicajaniuk — APPROVED** [review]

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: size-tracking, integration-tests

**Comment by jessicajaniuk** [comment]
Looks like this doesn't merge cleanly into `15.0.x`. I can re-target to minor and land this in `main`. Feel free to create a patch PR targeting `15.0.x` if you want to land it there.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 279e7d4465c0c4eae04d99c0514b6681df373894.

**Pull request closed without merging**
