### PR TITLE
aio: add auto scroll

### PR DESCRIPTION
**Pull request by petebacondarwin**
Builds on top of #14941 and #15083

### CODE REVIEW

**Comment by petebacondarwin** [comment]
The best page for testing this out is the AOT one: https://pr15113-0c7b98486ef5d04cfea90492a55ecdc2306d3f11.ngbuilds.io/guide/aot-compiler

**Review by IgorMinar — APPROVED** [review]
good stuff!

**Comment by IgorMinar** [comment]
@petebacondarwin does this still need more work? it's marked as wip

**Comment by petebacondarwin** [comment]
@IgorMinar no - you added the WIP label because the PRs on which it was built needed work. But those PRs have been fixed and merged already.

**Pull request merged**
