### PR TITLE
docs: Webcomponents activated as of firefox 63

### PR DESCRIPTION
**Pull request by hariberry**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A
The docs are outdated, as firefox now supports webcomponents by default.

## What is the new behavior?
The docs are updated. Workaround for older versions is still mentioned.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by hariberry** [comment]
I signed it!

**Comment by trotyl** [comment]
Duplicate of https://github.com/angular/angular/pull/25818

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Thx, @hariberry 👍
Can you please rebase on master to make CI green?

**Comment by hariberry** [comment]
rebase done

**Pull request closed without merging**
