### PR TITLE
Backport of #28055 commits

### PR DESCRIPTION
**Pull request by petebacondarwin**
A back port of some of the commits from #28055

### CODE REVIEW

**Review by kyliau — APPROVED** [review]
LGTM for language service

**Review by ocombe — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]
lgtm but needs rebase. thanks

**Comment by petebacondarwin** [comment]
Rebased.

**Comment by AndrewKushnir** [comment]
Merged into 7.2.x branch.

**Pull request closed without merging**
