### PR TITLE
refactor(benchpress): delete broken code

### PR DESCRIPTION
**Pull request by wagnermaciel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The [firefox_extension](https://github.com/angular/angular/blob/master/packages/benchpress/src/firefox_extension/lib/main.ts#L9) has become outdated. It currently uses the `chrome` api which [has not worked since November 2017](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK/Tutorials/Chrome_Authority).

## What is the new behavior?
Remove it.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

**Comment by matsko** [comment]
presubmit looks to have some breakages = https://tap.corp.google.com/ui#id=OCL:300135810:BASE:300135849:1583864423273:1b843442

**Comment by jelbourn** [comment]
@matsko those failures all look super unrelated to me

**Comment by AndrewKushnir** [comment]
Hi, it looks like broken targets were removed from g3 (thus restarting them would not give a clear indication), so I [started a new presubmit](http://test/OCL:300368370:BASE:300368418:1583951120684:e642f575) and replaced "merge" label with "presubmit" to indicate that.

Also, according to the process we need approvals from all reviewers before we can proceed with merging. @alxhub could you please have a look at this PR when you get a chance?

Thank you.

**Review by alxhub — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@wagnermaciel just want to check if this PR should be merged into master and patch branches or master only? It looks like it removes some code (can someone technically depend on it?), so I'd assume it might be safer to land it in master only (to include it into 9.1.0), but PR also says that it's not a breaking change. Please let me know (I will put "cleanup" label for now to avoid merging it accidentally). Thank you.

**Comment by wagnermaciel** [comment]
@AndrewKushnir I think going with the safer route is good because there is still a lot that needs to be done before the full feature I’m adding gets finished anyways.

I should repeat here that I don't think this will break anything because the firefox_extension is severely outdated. It currently uses the chrome api [which has not worked since November 2017](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK/Tutorials/Chrome_Authority).

**Comment by AndrewKushnir** [comment]
@wagnermaciel, thanks for the reply. Given that we've just released `9.1.0-rc.0` and created a new patch branch (`9.1.x`), we can keep "master & patch" label, so that the changes are included into `9.1.0` release. Thank you.

**Pull request closed without merging**
