### PR TITLE
docs(aio): add app.module to changed documents code ISSUE ##23865

### PR DESCRIPTION
**Pull request by donoso-eth**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #23865

## What is the new behavior?
Include app.module.ts with Imporst from components

## Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```

### CODE REVIEW

**Comment by jenniferfell** [comment]
Thanks! This looks like the right fix. 

It looks like this steps updates app.module.ts, but we forgot to add app.module.ts to the files that were changes in this tutorial section. 

https://angular.io/tutorial/toh-pt3#make-the-herodetailcomponent

**Comment by jenniferfell** [comment]
@StephenFluin : Hi. This falls into your area for pull-approve, when you get a moment. Thanks!

**Review by StephenFluin — APPROVED** [review]

**Comment by StephenFluin** [comment]
Small typo in the commit message but otherwise looks good.

**Comment by ampgular** [comment]
Thanks @jenniferfell, @StephenFluin for reviewing it. Is awesome, although a really small contribution, is my first open source ever, and it feels really good!!!

**Pull request closed without merging**
