### PR TITLE
docs: add NG Rome MMXIX to Events resources

### PR DESCRIPTION
**Pull request by Zizzamia**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
This is the Events page, which needs to be manually updated from time to time.

Issue Number: N/A

## What is the new behavior?
I moved the conference already past in the correct table and added NG Rome in the upcoming one.
Plus there are some HTML formatting fixes.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Screen Shot 2019-09-08 at 3 37 31 PM

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Hey @Zizzamia would you be up to moving ngJapan into the table for past events?

**Comment by kapunahelewong** [comment]
Hey, @Zizzamia GitHub says there are conflicts. Can you rebase and tag me once the tests pass? No worries on the ngJapan entry if you'd rather stick with your own edit. :)

**Comment by Zizzamia** [comment]
@kapunahelewong Updated the Events with all latest dates, not sure why the **aio_preview** is failing.

**Comment by kapunahelewong** [comment]
Perfect, thank you, @Zizzamia! 🌟

**Pull request closed without merging**
