### PR TITLE
docs(aio): update resources - Add Compodoc - documentation tool

### PR DESCRIPTION
**Pull request by vogloblinsky**
I re-submit this pull-request, the previous one https://github.com/angular/angular/pull/17590 wasn't integrated by @juleskremer PR https://github.com/angular/angular/pull/17476.

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by juleskremer — APPROVED** [review]
*fixed language error

**Comment by matsko** [comment]
@vogloblinsky please fix up the commit message to match what circleci is requesting.

**Comment by vogloblinsky** [comment]
@matsko Done.

**Comment by vogloblinsky** [comment]
@matsko @juleskremer 
What is the release day of docs(aio) in production ? I didn't see the changes : https://angular.io/resources
Thanks

**Comment by matsko** [comment]
@vogloblinsky sorry I haven't yet pushed your doc changes to `4.2.x` (which is our current docs branch that updates automatically). Tomorrow morning I will push the change and then you can see the updates later in the afternoon.

**Comment by vogloblinsky** [comment]
@matsko Thanks. 👍

**Pull request merged**
