### PR TITLE
perf: optimize all aio images

### PR DESCRIPTION
**Pull request by jelbourn**
[Summary of optimizations](https://docs.google.com/spreadsheets/d/1X8nukOlMI6dsgTT34blfLpqOsa1Jo2z_a-2eLGa085k)

For this round of optimizations, I've use the `imagemin` tool with the default plugins, with the mozjpeg plugin, and the pngquant plugin:
```sh
find ./aio/ -type d -exec imagemin {}/* --out-dir={} \;
find ./aio/ -type d -exec imagemin {}/* --out-dir={} --plugin=mozjpeg \;
find ./aio/ -type d -exec imagemin {}/* --out-dir={} --plugin.pngquant.quality={0.1,0.2} \;
```

Different from previous optimization passes, this change:
* Uses lossy compression. I looked over most of the changes, only only saw one image where the output was noticeably _slightly_ lower quality.
* Optimizes jpeg, gif, and svg assets

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]

**Review by alan-agius4 — APPROVED** [review]

**Review by petebacondarwin — COMMENTED** [review]
The images used in general content look good to me.
But I think we need to be a bit careful about downsizing logos. In particular in:

* aio/src/assets/images/
* aio/content/images/marketing/concept-icons/

Since these are used, for example, in the press-kit, for downloading: https://pr34516-1eac818.ngbuilds.io/presskit

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
merge-assistance: global approval

**Comment by jelbourn** [comment]
@petebacondarwin I did scan through all the diffs, and they all looked the same to me. Other folks might have sharper eyes, though, so I wouldn't mind a second opinion.

**Comment by gkalpak** [comment]
FWIW, I do see slight differences in some images. E.g.:
- The contour or "A" looks slightly jaggy in https://github.com/angular/angular/pull/34516/files?file-filters%5B%5D=.png&short_path=111e2c3#diff-171f92657881686a3b6e2935ab9b56a9
- Same for https://github.com/angular/angular/pull/34516/files?file-filters%5B%5D=.png&short_path=111e2c3#diff-111e2c3d2aa93ceadec35f34eb149fc3
  It also looks like the dark blue (on the right half) "leaks" into the plae blue on the left.

I agree with Pete that we should be more careful with concept-icons which are part of our press kit.

##
I'll add the clean-up label and leave it up to you and @IgorMinar to decide if anything needs to be changed (feel free to just remove the `cleanup` label and add the `merge`/`merge-assistance` label back).

**Comment by StephenFluin** [comment]
I recommend we revert any changes to presskit / master copies of our logo.

**Comment by JoostK** [comment]
> * The contour or "A" looks slightly jaggy in https://github.com/angular/angular/pull/34516/files?file-filters%5B%5D=.png&short_path=111e2c3#diff-171f92657881686a3b6e2935ab9b56a9

@gkalpak Agreed, and also the dithering in the shadow is truly awful now. The original image does not have that problem.

**Comment by jelbourn** [comment]
I've reverted the changes to all the png files under marketing and logos

**Comment by jelbourn** [comment]
Closing because this got stale. Maybe next December.

**Pull request closed without merging**
