### PR TITLE
refactor(core): remove hack

### PR DESCRIPTION
**Pull request by JeanMeche**
Should be fine to be removed.

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM, but I think we should run a global presubmit. I have a vague memory that this was added to work around some internal tooling issue.

**Comment by dylhunn** [comment]
I will run a TGP on this.

**Comment by dylhunn** [comment]
TGP running: https://test.corp.google.com/OCL:572453644:BASE:572453486:1696998683887:dbec4bf7

**Comment by dylhunn** [comment]
A lot of "target failed during analysis" that look to be TAP issues running the tests. Otherwise looks good.

**Comment by atscott** [comment]
Removing merge label. @JeanMeche The commit message needs improvement. Please describe this change and why the code is being removed.

**Comment by JeanMeche** [comment]
@atscott I've reworded the commit. Since this change has no impact on the release, we can target the main only.

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
Sounds like G3 issues are unrelated. Merging.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 4ed6ff13c4fac8a128eb21577b30033c36337a84.

**Pull request closed without merging**
