### PR TITLE
docs: update aio in support for #BlackLivesMatter

### PR DESCRIPTION
**Pull request by mgechev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by StephenFluin** [comment]
Header isn't looking right for me.
image

**Comment by ericmartinezr** [comment]
How about #AllLivesMatter ?

**Comment by Splaktar** [comment]
> How about #AllLivesMatter ? That's way more inclusive, everyone's important, everyone matter ;)

That’s a white supremacist slogan.

**Comment by ericmartinezr** [comment]
Ok, let's change it a bit: #EveryHumanMattersNoMatterTheColorOfTheSkin, better?

**Comment by samjulien** [comment]
This is looking great. Any chance we can link to an external resource in the banner like https://blacklivesmatters.carrd.co/?

**Comment by Splaktar** [comment]
Perhaps https://eji.org?

**Review by IgorMinar — APPROVED** [review]
Looks great to me! #BlackLivesMatter ❤️✌🏻🖖🏻

**Comment by IgorMinar** [comment]
@samjulien @Splaktar we don't feel comfortable endorsing one single external resource without proper due diligence. Let's get the design change out without further delays caused by adding a link and we can continue the conversation about afterwards.

**Comment by IgorMinar** [comment]
@mgechev can you please send a separate PR targetting the 10.0.x branch so that we can push this to next.angular.io as well? thanks

**Comment by IgorMinar** [comment]
merge-assistance: since it's after COB in PDT timezone, I'll handle the merging of this as soon as the CI is done running.

**Comment by mgechev** [comment]
@IgorMinar here it is https://github.com/angular/angular/pull/37409

**Review by Splaktar — APPROVED** [review]
Sounds good. We certainly don't want to link to something that could be compromised. That's why I suggested the second link, but it makes sense to not block this on deciding the link.

LGTM on mobile

**Comment by IgorMinar** [comment]
I had to manually merge this change to the 9.1.x branch because our new merge script doesn't seem to recognize `target: LTS-only` label:

```
$ yarn ng-dev pr merge 37407
yarn run v1.22.4
$ ts-node --transpile-only -- dev-infra/cli.ts pr merge 37407
Executing: git diff-index --quiet HEAD
Could not merge the specified pull request.
No target branch could be determined. Please ensure a target label is set.
error Command failed with exit code 1.
```

The change was merged as 6855396449a289d1c74fc438a513c03fab488922 and is currently being deployed to angular.io via https://app.circleci.com/pipelines/github/angular/angular/16194/workflows/455edd98-d75b-4313-9ec2-833987a15412

**Pull request closed without merging**
