### PR TITLE
feat(angular1_router): Add ng-link-active class to active ng-link

### LINKED ISSUE #5286: feat(angular_1_router): Add class to active ng-link
Add a class to the ng-link when it is the current active route.

### PR DESCRIPTION
**Pull request by brandonroberts**
Closes #5286

### CODE REVIEW

**Comment by btford** [comment]
@brandonroberts :+1: this is a good addition.

@petebacondarwin – can you please help me review this? I cannot recall the best practice for efficiently dealing with watchers. I suspect there may be a slightly more efficient way of doing this.

**Comment by petebacondarwin** [comment]
I can't think of a more efficient watcher.
But I think we should be using ngAnimate to change the classes, right, so that the class changes can be animated... @matsko ?

**Comment by brandonroberts** [comment]
Do I need to do anything else with this one?

**Comment by petebacondarwin** [comment]
No, we just need to get it merged...

**Comment by vikerman** [comment]
TAP Green

**Pull request closed without merging**
