### PR TITLE
20114 reuse route strategy children fix

### PR DESCRIPTION
**Pull request by krzysztof-grzybek**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently, it's impossible to cache (detach/attach) parent route without caching child routes. This produces a bug, when navigating from `a/b` to `c`, then to `a/d`, where `a` route is cached. On the last navigation, we incorrectly restore `a/b` route instead of `a/d`.

Issue Number: https://github.com/angular/angular/issues/17333

## What is the new behavior?

If the route should be detached/attached, we do so, but we check also child routes recursively.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

The behaviour described above will probably break some user defined `ReuseRouteStrategies` if it does involve child routes caching (detaching/attaching). If we don't want to introduce such a breaking change, I think it should be a part of the new `ReuseRouteStrategy` (https://github.com/angular/angular/issues/27290).

### CODE REVIEW

**Comment by krzysztof-grzybek** [comment]
@googlebot I fixed it.

**Review by atscott — APPROVED** [review]
reviewed-for: size-tracking
reviewed-for: fw-router

**Review by atscott — APPROVED** [review]

**Comment by krzysztof-grzybek** [comment]
It seems that legacy unit tests are failing for unrelated reason, am I right?

**Comment by atscott** [comment]
@krzysztof-grzybek I believe that's correct. I'll restart them; they're known to be a bit flakey.

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: size-tracking

**Comment by atscott** [comment]
@krzysztof-grzybek Could you rebase and re-update the payload size? That's the only blocker for this at the moment.

**Review by atscott — APPROVED** [review]

**Comment by Carlosamouco** [comment]
I looked at the [CHANGELOG.md](https://github.com/angular/angular/blob/master/CHANGELOG.md) and this was not mentioned as a breaking change of version 13.0.0, but this ended up breaking my reuse strategy entirely. I assume that now I have to store each child route one by one from the point of the route tree that I want where previously I only needed to store that parent route. Is that correct?

**Comment by atscott** [comment]
@Carlosamouco In short, that would be correct. I'm curious about your use-case (would you be able to provide a stackblitz reproduction?), as it would have had to rely on either 

1. ensuring there was only a single path below the cached parent to prevent incorrect siblings being loaded from the cache.
or 
2. ensuring that each child path matches when restoring from the parent.

We did a lot of testing and determined that while, this did technically change the behavior, it was unlikely to break anyone due to how difficult and fragile it was to make it work correctly. 

Apologies if we missed your use-case. I would happily review an update to the changelog to note this as a breaking change.

**Comment by Carlosamouco** [comment]
@atscott thanks for the reply. I can't provide a stackblitz right now but I think my use case is easy to understand. 

Basically I have a tab system in the app that tries to mimic the behavior of browser tabs. Each tab is mapped to an URL and contains some "page content". When the user selects a tab, we trigger a navigation to the URL of that tab and we proceed to detach and store the "page content" of the previous selected tab in order to restore it whenever the user selects it back. 

When navigating between tabs, the tab URL matches exactly with the path of the nodes of the stored "page content", and that's why that restoring the parent node of the said "page content" was enough according to what you said.

I am not sure if my use case is an edge case or not, but since this is a change in the behavior of the reuse strategy I am guessing that It would be a good idea to mention this in the changelog?

As an aside, I found while debugging that when storing the state of a given node the DetachedRouteHandle still has the information about the state of it's children even though they are not reattached with their parent anymore.

**Comment by Carlosamouco** [comment]
I made a stackblitz example of my strategy working in version 12.
https://stackblitz.com/edit/angular-5nki9j

**Comment by atscott** [comment]
@Carlosamouco I reviewed your reproduction and I agree that this should be listed in the breaking changes. Your situation is reasonable. 

Just to clarify, this only works when there are no subtabs, right? There can only be a single pathway of route children under the tabs because the `Router` code could not previously store different children under a stored parent route. This being the case, you could also have `HelloComponent` as a child in the template of `PageAComponent` rather than a route child. I do imagine the example is oversimplified and you used child routes because `PageAComponent` is really re-used elsewhere with a different child?

**Comment by Carlosamouco** [comment]
@atscott Thanks for point out your findings. 

I don't have any subtabs in my app but with the changes in version 13 I think that it is now possible.

My example was over simplified. I was trying to build a scenario that contained routes with more than one child, only to point out that the descendants' state was also restored along with the parent in version 12.

In my app things are more complex, for instance I don't have a fixed amount of tabs like in the example and each tab URL is also not static.

**Pull request closed without merging**
