### PR TITLE
docs: remove old commits from CHANGELOG.md

### LINKED ISSUE #44953: CHANGELOG.md size over 1MB cannot be read with format through github
### Description

Angular CHANGELOG.md is a precious piece of info.
With the latest versions, the file size is now over GitHub md viewer limits, and the file can only be seen as raw
Even if markdown is not the worst human reading format in the world, this is way harder than rendered html.

Maybe the CHANGELOG.md could be splitted, only keeping the N more recent releases, and have linked follow-ups (CHANGELOG.x.md or CHANGELOG.yyyy.md, or any) in order to ensure readability.

### What is the affected URL?

https://github.com/angular/angular/blob/master/CHANGELOG.md

### Please provide the steps to reproduce the issue

Just go to https://github.com/angular/angular/blob/master/CHANGELOG.md

### Please provide the expected behavior vs the actual behavior you encountered

Seeing rendered HTML vs seeing raw markdown

### Please provide a screenshot if possible

_No response_

### Please provide the exception or error you saw

_No response_

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

_No response_

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit removes old DevTools-related commits that ended up in the CHANGELOG.md since the DevTools repo was merged into angular/angular one.

Closes #44953.

## PR Type
What kind of change does this PR introduce?

- [x] Documentation content changes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by AndrewKushnir** [comment]
Merge assistance: this PR is ready for merge (I can't remove extra reviewers via GitHub UI for some reasons...).

**Comment by dylhunn** [comment]
Targeting minor due to merge conflicts; feel free to send another PR and skip review if it must be rebased for patch.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 077593f3bcc2d82a20f202164e69a5b90c0d4b8a.

**Pull request closed without merging**
