### PR TITLE
Updating the UI components list with Ignite UI for Angular

### PR DESCRIPTION
**Pull request by kdinev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Ignite UI and JS Blocks are not present in the UI components list.
Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Updating the UI component reference list with Ignite UI and JS Blocks.

### CODE REVIEW

**Comment by Toxicable** [comment]
The Demos linked form the github's take a significant amount of time to load up, 24 seconds for this one http://139.59.168.161/demos for me.

**Comment by kdinev** [comment]
@Toxicable The demos you're looking at are being moved as we speak, because the current link is just a test shared server, thus the lack of domain name. This will be updated soon.

We will implement the suggestion about the separation of igniteui-angular into modules.

**Review by StephenFluin — APPROVED** [review]

**Comment by kdinev** [comment]
@Toxicable @StephenFluin I have updated the PR with the branch new release of Ignite UI for Angular. Please review again.

**Review by StephenFluin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
@kdinev please squash the commits, rebase on current master and fix the commit message to follow our required syntax: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Pull request closed without merging**
