### PR TITLE
docs: update decorators proposal stage and link in glossary

### PR DESCRIPTION
**Pull request by Lgt2x**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by dylhunn** [comment]
Why the desire to change the link from tc39 github?

**Comment by Lgt2x** [comment]
> Why the desire to change the link from tc39 github?

I'm changing the link from the legacy proposal repo [wycats/javascript-decorators](https://github.com/wycats/javascript-decorators) to the newer one on [TC39/proposal-decorators](https://github.com/tc39/proposal-decorators) to which it has been moved to

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit f5299a3b8fe2a9ddbfdadc1843fc41eb243dfc38.

**Pull request closed without merging**
