### PR TITLE
docs: spanish documentation added

### PR DESCRIPTION
**Pull request by AntonioCardenas**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Spanish official documentation added 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
this is possible thanks to the great work of the  [angularhispano community](https://github.com/angular-hispano/angular)

### CODE REVIEW

**Comment by geromegrignon** [comment]
Hey @AntonioCardenas, as described into the [contribution guide](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit) of this project, your commit messages must follow a given format. In order to pass the lint CI, you must update your commit message.

**Review by Splaktar — CHANGES_REQUESTED** [review]
Can you please squash your commits into a single commit that follows the commit message guidelines?

Thank you for your efforts on the Spanish translation and for adding this link here to let more people know about it!

**Review by Splaktar — APPROVED** [review]
LGTM

**Comment by Splaktar** [comment]
Btw, you still need to use interactive rebase to squash you commits.

[This gist](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) is very helpful for squashing and amending commits. Then you can force push your branch up to the remote.

**Comment by Splaktar** [comment]
Additionally the `ci/circleci: setup` task is telling you to get the latest config by rebasing your branch via:
```sh
          git fetch upstream master;
          git checkout master;
          git rebase upstream/master;
          git push --force-with-lease;
```

**Comment by AntonioCardenas** [comment]
I made a git mess up between this repo and angular hispano repo and i lost the access to this branch so a made a new pr with everything up to date and all comments in this pr sorry the new issue is #39502

**Pull request closed without merging**
