### PR TITLE
fix(platform-browser):KeyEventsPlugin should keep the same behavior

### LINKED ISSUE #45698: HostListener on specific keys negates effect of ngZoneEventCoalescing
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

We can use `ngZoneEventCoalescing` to group change detection cycles of events into an animationFrame
So if we have a listener like this on a component that appears multiple times in the dom

```
  @HostListener('document:keydown', ['$event'])
  onKeydown(event: KeyboardEvent) {
    ...
  }
```
there is only one change detection cycle triggered on each keydown event

but if we now specify the key, we loose this effect and there is one change detection cycle per component
```
  @HostListener('document:keydown.a')
  onKeydown() {
    ...
  }
```

I've provided a stackblitz link with both variations in the `BoxComponent` and added logging for the change detection cycles to the console.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-qza2cj?file=src%2Fmain.ts

### Please provide the exception or error you saw

_No response_

### Please provide the environment you discovered this bug in (run `ng version`)

_No response_

### Anything else?

I guess the key event manager plugin causes the cycles here 

https://github.com/angular/angular/blob/b5ab7aff433a67cddaa55e621d17b1a1b07b57c2/packages/platform-browser/src/dom/events/key_events.ts#L176-L182

if we activate the `ngZoneRunCoalescing` flag as well, then we have the desired behaviour again.
the question is if the event plugin should be modified so that it already applies to the `ngZoneEventCoalescing` flag like one would expect from the name.

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Close #45698

KeyEventsPlugin now has different behavior with EventsPlugin, it will always run inside ngZone with ngZone.runGuarded() no matter the component is initialized inside or outside of NgZone, this PR make sure KeyEventsPlugin bahave the same with other events.

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM!

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 2312eb53ef5862e0866c29d11dec2a9b7b6a064c.

**Comment by jessicajaniuk** [comment]
This has caused a test breakage in Google3. I'll revert this, and we'll have to run a TGP to see if this can land safely.

**Comment by JiaLiPassion** [comment]
Got it, Thank you @jessicajaniuk

**Comment by jessicajaniuk** [comment]
[TGP](https://fusion2.corp.google.com/presubmit/tap/515507925/OCL:515507925:BASE:515507971:1678419849349:9b30e0ee)

**Comment by JiaLiPassion** [comment]
Thank you @jessicajaniuk, if there are anything I can do, please let me know.

**Pull request closed without merging**
