### PR TITLE
docs: change doc for address form group in reactive forms guide

### PR DESCRIPTION
**Pull request by iliesaithamouda**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #29925

## What is the new behavior?
updated doc

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x ] No

### CODE REVIEW

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update git commit message to `docs: change doc for address form group in reactive forms guide`

**Comment by m-henderson** [comment]
@brandonroberts is the commit message the only thing holding up this PR?

**Comment by brandonroberts** [comment]
@m-henderson Yes. I usually give the author a chance first before I go update it.

**Comment by m-henderson** [comment]
> @m-henderson Yes. I usually give the author a chance first before I go update it.
Since it has been a few days and this is a small change, I went ahead and fixed the commit message in another PR. I tried to fix it on his/her PR but I did not have permission to push to their branch. 
#30030

**Comment by brandonroberts** [comment]
@m-henderson thanks, but we already coordinated the work with the author on this issue from #29925, so they'll get priority in this case. If you see something else, feel free to open a different PR.

**Review by brandonroberts — APPROVED** [review]

**Pull request closed without merging**
