### PR TITLE
docs: remove unused style guides.

### PR DESCRIPTION
**Pull request by JeanMeche**
Some example projects weren't used anymore by the styleguide, let's remove them. 

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes

### CODE REVIEW

**Review by dylhunn — APPROVED** [review]
LGTM with a question -- how did you determine conclusively that these are no longer used?

reviewed-for: public-api

**Comment by JeanMeche** [comment]
> LGTM with a question -- how did you determine conclusively that these are no longer used?
@dylhunn 
They were not used in `styleguide.md` anymore nor did I found any reference in the project.

**Review by jessicajaniuk — APPROVED** [review]
LGTM

reviewed-for: public-api

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 518cc630221289503da2a4ae60af2acbae7ac7b8.

**Pull request closed without merging**
