### PR TITLE
feat(core): add support for @Property and @Event decorators

### PR DESCRIPTION
**Pull request by vsavkin**
Example:

```
@Directive({selector: 'my-selector'})
class MyDirective {
  @Property() prop;
  @Property('el-prop') prop2;
  @Event() event;
  @Event('el-event') event2;
}
```

### CODE REVIEW

**Comment by gdi2290** [comment]
can we also get an Observable event?
`@ObservableEvent('mouseover') mouseover;`

**Comment by pkozlowski-opensource** [comment]
Yeeeeeesssssss!!! Thnx @mhevery  @vsavkin

**Comment by PascalPrecht** [comment]
This is really syntactic sugar right? We will still be able to use `properties: []` and `EventEmitter` constructor?

**Comment by thelgevold** [comment]
I like this idea and think it's an improvement over the current properties:[] syntax. Seems more clear to me.

**Comment by PascalPrecht** [comment]
@thelgevold yes, but if you'd write that in ES5, creating an annotation by hand everytime you wanna add a property is kinda huge.

**Comment by thelgevold** [comment]
@PascalPrecht Yes, I think that is a good point. I am guessing they will still support the current properties:[] along side this new idea. Probably just a new short notation like you pointed out above.

**Comment by gionkunz** [comment]
Simply awesome guys! :+1:

**Pull request closed without merging**
