### PR TITLE
style(playground): use single quotes consistently

### PR DESCRIPTION
**Pull request by gionkunz**
Assuming the desired quote style is single quotes, if just established some more consistency.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@gionkunz thnx for the PR. Could you please change the commit message to follow our conventions? Sth like `style(playground): use single quotes consistently` or similar.

**Comment by gionkunz** [comment]
@pkozlowski-opensource sure, I've changed the commit message. Cheers

**Comment by IgorMinar** [comment]
@jelbourn when merging can you please correct the commit message to follow our style guide? thanks

**Comment by jelbourn** [comment]
Closed via c7242a39d2b5798a6a987196ad8d2cb569c789f6

**Pull request closed without merging**
