### PR TITLE
docs(changelog): Remove duplicated breaking changes

### PR DESCRIPTION
**Pull request by lacolaco**
- **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  docs updates:

Remove duplicated sentences of CHANGELOG.md. `$router` renaming has been already announced in Beta.8.
- **What is the current behavior?** (You can also link to an open issue here)
  Duplicated changelog.
- **What is the new behavior (if this is a feature change)?**
  Fixed changelog
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
- **Other information**:

### CODE REVIEW

**Comment by laco0416** [comment]
cc/ @vikerman

**Comment by gunjanpatel** [comment]
@laco0416 it looks like that you have removed whole `### BREAKING CHANGES` block.

**Comment by laco0416** [comment]
@gunjanpatel Breaking changes of Beta.9 are already in Beta.8.

**Comment by gkalpak** [comment]
The weird thing about this is that there are indeed commits merged into `beta.9` that contain these breaking changes in their commit messages.

**Comment by gkalpak** [comment]
And even more strange, that there are commits in `beta.9` with identical commit messages (2548ce8, 1174473), that also match the commit message of a `beta.8` commit (edad8e3).

It seems that 2548ce8 and 1174473 (both in `beta.9`) mention the BC by accident, so the notice should be removed from `beta.9`'s changelog section. But they also seem to contain indentical changes (maybe the first was reverted ?), so one should probably be removed from the changelog as well.

**Pull request closed without merging**
