### PR TITLE
docs: refactored the markup tags

### PR DESCRIPTION
**Pull request by alkavats1**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by alkavats1** [comment]
Hi, @josephperrott can you review this PR?
Thanks

**Comment by jessicajaniuk** [comment]
@alkavats1 Thanks for the enthusiasm! There's no need to manually request us manually in a comment though. We're already pinged by our tooling.

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 9acc0e32c4656aaf8a50efde86d8888f2eb8adb9.

**Pull request closed without merging**
