### PR TITLE
ci(aio): Fix the payload script only check for changes in aio/scripts

### PR DESCRIPTION
**Pull request by tinayuangao**
## PR Checklist
Does please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Payload script doesn't catch the changes inside `aio/`
It only catch the changes inside `aio/scripts`

Issue Number: N/A

## What is the new behavior?
Payload script should update the data to firebase when there's a change in aio/

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Comment by gkalpak** [comment]
Can you add more info on what the issue is?

**Review by IgorMinar — APPROVED** [review]
please remove all the `pwd` and `echo` statements. otherwise lgtm

**Comment by tinayuangao** [comment]
Cleaned up and reverted the `:(exclude) content` changes. The Travis CI's git version is 1.8 which doesn't support `:(exclude)`

**Comment by petebacondarwin** [comment]
Cherry picked to 4.2.x as 408bb89e8f75bc811b7647a01225318f74006858

**Pull request merged**
