### PR TITLE
build: update to typescript 3.9.5

### PR DESCRIPTION
**Pull request by alan-agius4**
This TypeScript version contains the revert for the classes wrapped in IIFE change that was introduced in version 3.9.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

**Review by IgorMinar — APPROVED** [review]
LGTM! Thank you!

Reviewed-for: global-approvers

**Comment by IgorMinar** [comment]
@alan-agius4 this PR needs a rebase please.

**Comment by alan-agius4** [comment]
@IgorMinar rebased.

**Pull request closed without merging**
