### PR TITLE
Correct EventEmitter isBroadcast

### PR DESCRIPTION
**Pull request by grouma**

### CODE REVIEW

**Comment by grouma** [comment]
I signed it!

**Comment by PascalPrecht** [comment]
Hey @grouma could you elaborate on that change? Why is it needed? What problem does it solve? Has this been discussed somewhere? And despite everything else: I think we need tests to get this in.

**Comment by grouma** [comment]
I'm fixing a bug with the implementation of EventEmitter. Although under the hood it uses a broadcast stream it returns false for isBroadcast. This is causing issues with an Angular 2 application that I'm writing which needs to ensure streams are broadcast. Are you sure this minor change needs a test?

**Comment by PascalPrecht** [comment]
If it's a bug you're fixing, then we definitely need a test. I'm not super deep into the `EventEmitter` code, but it looks like you're adding a new API here too. Does it exist in TypeScript land?

**Comment by grouma** [comment]
I am not adding a new API. It extends from Stream which has a default implementation for isBroadcast. It's simply overriding that default behavior to the correct behavior.

**Comment by PascalPrecht** [comment]
You're totally right. Nevermind, only saw half of the picture.

**Comment by grouma** [comment]
Cool. Let me know what else you need from me. I'm not familiar with the Typescript facade but an analogous change is likely need there as well.

**Comment by PascalPrecht** [comment]
I think someone who has a better picture of what should happen to `EventEmitter` should take a look at this and decide if this change lands or not. Pinging @robwormald here. (Still think that this needs a test then though)

**Comment by robwormald** [comment]
RxJS Subjects (which is what EvE is in TS) are multicast by default. Curious if this is causing an issue in a Component itself, or if its causing issues with a standalone usage of EventEmitter - the latter is generally not recommended in favor of using Subject/Stream directly.

**Comment by grouma** [comment]
I'm building an interop layer for GWT and Angular 2 which constructs components dynamically using the dynamicComponentLoader. This interop layer allows communication through the standard component events by providing an interface for GWT to add a callback listener. Apparently Angular automatically listens on these event streams and thus I must ensure they are configured to broadcast. Since EventEmitter is often used for these event streams its causing an issue.

**Comment by natebosch** [comment]
External to the component we do treat this as a Stream - we are not dependent on the implementation being an EventEmitter.

We are dependent, however, on the Stream not lying about whether it is a broadcast stream. EventEmitter is a broadcast stream, but pretends it is not.

**Comment by mhevery** [comment]
This PR is stale (does not rebase; pass CI; had no activity for a while). It is probably our fault, and we are sorry. In an effort to keep our PR queue under control, and prevent us from taking too long to get back to you we are cleaning up the queue. Unfortunately this means that this PR is getting closed.

If you would like to resurrect this change, please rebase on master, make the tests pass and create a new PR.

**Pull request closed without merging**
