### PR TITLE
Rules nodejs 1.0 redo

### PR DESCRIPTION
**Pull request by gregmagolan**
Redo of https://github.com/angular/angular/pull/34589 which broke jasmine_node_test and was reverted.

Added a commit tests for this regression which will fail without the fix that is coming in rules_nodejs.

### CODE REVIEW

**Comment by gregmagolan** [comment]
Manually verified that a jasmine_node_test can fail:

```
greg@Air-Force-One angular (rules_nodejs_1.0_redo) $ yarn bazel test --config=ivy packages/core/test/acceptance
yarn run v1.21.1
$ bazel test --config=ivy packages/core/test/acceptance
INFO: Writing tracer profile to '/private/var/tmp/_bazel_greg/5e8f8a9cd1c6fbc1afd11e37ee1fe2e5/command.profile.gz'
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=243
INFO: Reading rc options for 'test' from /Users/greg/google/angular/.bazelrc:
  Inherited 'common' options: --experimental_allow_incremental_repository_updates
INFO: Reading rc options for 'test' from /Users/greg/.bazelrc:
  Inherited 'common' options: --announce_rc
INFO: Reading rc options for 'test' from /Users/greg/google/angular/.bazelrc:
  Inherited 'build' options: --symlink_prefix=dist/ --nolegacy_external_runfiles --incompatible_strict_action_env --define=angular_ivy_enabled=False
INFO: Reading rc options for 'test' from /Users/greg/google/angular/.bazelrc:
  'test' options: --nolegacy_external_runfiles --incompatible_strict_action_env --test_output=errors
INFO: Reading rc options for 'test' from /Users/greg/.bazelrc:
  'test' options: --test_output=errors
INFO: Found applicable config definition build:ivy in file /Users/greg/google/angular/.bazelrc: --define=angular_ivy_enabled=True
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Analyzed target //packages/core/test/acceptance:acceptance (304 packages loaded, 11869 targets configured).
INFO: Found 1 test target...
Target //packages/core/test/acceptance:acceptance up-to-date:
  dist/bin/packages/core/test/acceptance/acceptance.sh
  dist/bin/packages/core/test/acceptance/acceptance_loader.js
  dist/bin/packages/core/test/acceptance/acceptance_require_patch.js
INFO: Elapsed time: 63.070s, Critical Path: 28.34s
INFO: 19 processes: 3 darwin-sandbox, 16 worker.
INFO: Build completed successfully, 20 total actions
//packages/core/test/acceptance:acceptance                               PASSED in 7.4s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 20 total actions
✨  Done in 63.29s.
greg@Air-Force-One angular (rules_nodejs_1.0_redo) $ yarn bazel test --config=ivy packages/core/test/acceptance
yarn run v1.21.1
$ bazel test --config=ivy packages/core/test/acceptance
INFO: Writing tracer profile to '/private/var/tmp/_bazel_greg/5e8f8a9cd1c6fbc1afd11e37ee1fe2e5/command.profile.gz'
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=243
INFO: Reading rc options for 'test' from /Users/greg/google/angular/.bazelrc:
  Inherited 'common' options: --experimental_allow_incremental_repository_updates
INFO: Reading rc options for 'test' from /Users/greg/.bazelrc:
  Inherited 'common' options: --announce_rc
INFO: Reading rc options for 'test' from /Users/greg/google/angular/.bazelrc:
  Inherited 'build' options: --symlink_prefix=dist/ --nolegacy_external_runfiles --incompatible_strict_action_env --define=angular_ivy_enabled=False
INFO: Reading rc options for 'test' from /Users/greg/google/angular/.bazelrc:
  'test' options: --nolegacy_external_runfiles --incompatible_strict_action_env --test_output=errors
INFO: Reading rc options for 'test' from /Users/greg/.bazelrc:
  'test' options: --test_output=errors
INFO: Found applicable config definition build:ivy in file /Users/greg/google/angular/.bazelrc: --define=angular_ivy_enabled=True
INFO: Analyzed target //packages/core/test/acceptance:acceptance (1 packages loaded, 72 targets configured).
INFO: Found 1 test target...
[140 / 141] [Prepa] Testing //packages/core/test/acceptance:acceptance

FAIL: //packages/core/test/acceptance:acceptance (see /private/var/tmp/_bazel_greg/5e8f8a9cd1c6fbc1afd11e37ee1fe2e5/execroot/angular/bazel-out/darwin-fastbuild/testlogs/packages/core/test/acceptance/acceptance/test.log)
INFO: From Testing //packages/core/test/acceptance:acceptance:
==================== Test output for //packages/core/test/acceptance:acceptance:
Randomized with seed 81737
Started
..............................................................................................................WARNING: sanitizing unsafe URL value javascript:alert("I am a h4xx0rz1!!"); (see http://g.co/ng/security#xss)
.WARNING: sanitizing unsafe URL value javascript:alert("haha, I am taking over your computer!!!"); (see http://g.co/ng/security#xss)
.................................................................WARNING: sanitizing unsafe URL value javascript:alert("haha, I am taking over your computer!!!"); (see http://g.co/ng/security#xss)
..........................................Angular is running in the development mode. Call enableProdMode() to enable the production mode.
......................................................................................F.....WARNING: sanitizing unsafe URL value javascript:true (see http://g.co/ng/security#xss)
...................................................................................................................*............................................................................................................................................................WARNING: sanitizing unsafe URL value javascript:alert(3) (see http://g.co/ng/security#xss)
.WARNING: sanitizing unsafe URL value javascript:alert(1.2) (see http://g.co/ng/security#xss)
.WARNING: sanitizing unsafe URL value javascript:alert(2.2) (see http://g.co/ng/security#xss)
.WARNING: sanitizing unsafe URL value javascript:alert(2.1) (see http://g.co/ng/security#xss)
.WARNING: sanitizing unsafe URL value javascript:alert(1.1) (see http://g.co/ng/security#xss)
.WARNING: sanitizing unsafe URL value javascript:alert(1) (see http://g.co/ng/security#xss)
.WARNING: sanitizing unsafe URL value javascript:alert(2) (see http://g.co/ng/security#xss)
.....................................................................................................................................................................................................................................................................................................................................................................................................

Failures:
1) attribute creation should create an element
  Message:
    Expected 'Hello' to equal 'FORCED FAIL'.
  Stack:
    Error: Expected 'Hello' to equal 'FORCED FAIL'.
        at <Jasmine>
        at UserContext.<anonymous> (packages/core/test/acceptance/attributes_spec.ts:26:23)
        at ZoneDelegate.invoke (packages/zone.js/lib/zone.ts:1135:20)
        at ProxyZoneSpec.onInvoke (packages/zone.js/lib/zone-spec/proxy.ts:129:33)
        at ZoneDelegate.invoke (packages/zone.js/lib/zone.ts:1132:26)
        at Zone.run (packages/zone.js/lib/zone.ts:814:35)
        at runInTestZone (packages/zone.js/lib/jasmine/jasmine.ts:173:28)
        at UserContext.<anonymous> (packages/zone.js/lib/jasmine/jasmine.ts:189:22)
        at <Jasmine>
        at ZoneDelegate.invokeTask (packages/zone.js/lib/zone.ts:1173:25)
        at Zone.runTask (packages/zone.js/lib/zone.ts:864:37)
        at drainMicroTaskQueue (packages/zone.js/lib/zone.ts:1365:23)
        at ZoneTask.invokeTask (packages/zone.js/lib/zone.ts:1271:11)
        at Immediate.ZoneTask.invoke (packages/zone.js/lib/zone.ts:1256:38)
        at Immediate.timer [as _onImmediate] (packages/zone.js/lib/common/timers.ts:34:21)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
Pending:

1) styling should not set inputs called class if they are not being used in the template
  Temporarily disabled with xit

977 specs, 1 failure, 1 pending spec
Finished in 6.648 seconds
Randomized with seed 81737 (jasmine --random=true --seed=81737)
================================================================================
Target //packages/core/test/acceptance:acceptance up-to-date:
  dist/bin/packages/core/test/acceptance/acceptance.sh
  dist/bin/packages/core/test/acceptance/acceptance_loader.js
  dist/bin/packages/core/test/acceptance/acceptance_require_patch.js
INFO: Elapsed time: 27.964s, Critical Path: 21.10s
INFO: 3 processes: 2 darwin-sandbox, 1 worker.
INFO: Build completed, 1 test FAILED, 3 total actions
//packages/core/test/acceptance:acceptance                               FAILED in 10.2s
  /private/var/tmp/_bazel_greg/5e8f8a9cd1c6fbc1afd11e37ee1fe2e5/execroot/angular/bazel-out/darwin-fastbuild/testlogs/packages/core/test/acceptance/acceptance/test.log

INFO: Build completed, 1 test FAILED, 3 total actions
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gregmagolan** [comment]
Windows CI verified green here: https://github.com/angular/angular/pull/34750

**Comment by gregmagolan** [comment]
Windows CI verified green here: https://github.com/angular/angular/pull/34750

**Review by josephperrott — APPROVED** [review]
LGTM, global approval

**Pull request closed without merging**
