### PR TITLE
Remove minimist and source-map from compiler-cli

### PR DESCRIPTION
**Pull request by alan-agius4**
**refactor(compiler-cli): remove `source-map` from dependencies**

`source-map` is only used during testing and therefore there is no need to list it as a dependency.
 
**refactor(dev-infra): remove dependency on minimist**

Refactor scripts to use `yargs`. The main motivation for this is to align and use a single parser.

**refactor(compiler-cli): remove dependency on minimist**

The compiler already has a dependency on another parser (`yargs`).

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
LGTM!

**Review by AndrewKushnir — APPROVED** [review]
👍

**Review by JoostK — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

(we should probably remove `goldens/public-api/manage.js` from the list of things that require `public-api` approval - it should probably be `dev-infra`)

**Comment by alan-agius4** [comment]
@AndrewKushnir, I agree with that. I can do a follow up PR.

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Comment by alxhub** [comment]
I propose we block this on @devversion's APF PR. This is affecting dependencies of compiler-cli, and Paul is working on major changes to how that package is bundled. This will almost certainly conflict with Paul's PR.

**Comment by alan-agius4** [comment]
Let’s do that @alxhub.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit bdc6ff465a5894a2bee51a144ec74cc922d7739c.

**Pull request closed without merging**
