### PR TITLE
[patch-only version of #41599] build: update to latest version of `rules_nodejs` v3.3.0

### PR DESCRIPTION
**Pull request by josephperrott**
Patch only version of #41599

### CODE REVIEW

**Comment by devversion** [comment]
@googlebot I consent.

**Review by devversion — APPROVED** [review]
LGTM. CI failures for the language service seem unrelated (by looking at the patch branch)

**Comment by zarend** [comment]
@josephperrott  I cannot merge this PR because it has merge conflicts with master and 12.0.x 😢 . Please rebase this PR.

**Comment by josephperrott** [comment]
It should only merge into `11.2.x`:

```
$ yarn ng-dev pr check-target-branches 41607
PR #41607 will merge into:
  - 11.2.x
```

**Comment by zarend** [comment]
Closed by commit 4d79c1d7dbd1cb1af4441d521e9eb7d2de91f984

**Comment by zarend** [comment]
Okay, I merged it into 11.2.x. ✔️

**Pull request closed without merging**
