### PR TITLE
Revert "test: create integration tests for Trusted Types support in Ivy"

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This PR reverts PR #39614 from the patch (11.0.x) branch, since it's causing problems with CI there, see https://github.com/angular/angular/pull/39614#issuecomment-730632379.

## PR Type
What kind of change does this PR introduce?

- [x] Other... Please describe: revert of a PR that is causing issues with CI in patch branch.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
cc @bjarkler

**Comment by bjarkler** [comment]
LGTM. Also see my comment in #39614.

**Review by IgorMinar — APPROVED** [review]
LGTM. Apologies for applying the wrong label.

**Comment by AndrewKushnir** [comment]
This PR is now merged into the patch (11.0.x) branch.

**Pull request closed without merging**
