### PR TITLE
build: fix formatting tasks (by downgrading `gulp-clang-format` to 1.0.23)

### PR DESCRIPTION
**Pull request by gkalpak**
The `gulp format*` tasks have been broken since 5eb7426. These include the `gulp format:enforce` task, which is what runs on CI to enforce consistent code style. Here is what (I believe) happened:

- I assume formatting was failing in 5eb7426 (moving `zone.js` into `angular/angular`). The reason must have been that [this glob pattern][1] matches `packages/zone.js/` (which is a directory) and passes it to `clang-format` claiming it is a file.
- I further assume that in an attempt to fix the issue, `gulp-clang-format` was updated to the latest version (1.0.27) in 5eb7426.
- `gulp format:enforce` stopped complaining, so everyone thought formatting was fine and moved on.
- Formatting still wasn't fine, but the task completed successfully nevertheless 😱
- The reason is that angular/gulp-clang-format@55b697c (and subsequent commits) changed the way the `done()` callback was called, leaving it to `clang-format` to call it (while previously it was also called when the associated stream ended).
- In the old version of `clang-format` that we are using (1.0.41), there is a bug (which has been fixed in angular/clang-format@4cce2c4):
  The callback is not called [unless the process exits with an error][2].

One can also see that the `gulp format:enforce` task is not completed in `gulp lint`. Example output from [build 374722][3]:

```
yarn gulp lint
...
Starting 'format:enforce'...
Starting 'validate-commit-messages'...
...
Finished 'validate-commit-messages' after 833 ms
Starting 'tools:build'...
Finished 'tools:build' after 1.75 s
Starting 'tslint'...
Finished 'tslint' after 19 s
Done in 21.82s.
```

Notice that all tasks have a corresponding "Finished X` log, except for `format:enforce`.

For reference:
The problem was originally reported by @ocombe on Slack ([discussion][4]).

---
This PR fixes the issues by downgrading `gulp-clang-format` to 1.0.23, ignoring the `zone.js/` directory from the files to format (only the directory itself; not its contents) and formatting all files to fix the linting failures.

[1]: https://github.com/angular/angular/blob/a8f3b317f/tools/gulp-tasks/format.js#L13
[2]: https://github.com/angular/clang-format/blob/b8c7df0b7/index.js#L95
[3]: https://circleci.com/gh/angular/angular/374722
[4]: https://angular-team.slack.com/archives/C042EU9T5/p1561480241191000

### CODE REVIEW

**Comment by gkalpak** [comment]
You can see the linting job (correctly) failing without the last commit [here][1].

[1]: https://circleci.com/gh/angular/angular/375166

**Review by josephperrott — APPROVED** [review]

**Review by devversion — APPROVED** [review]
💯

**Comment by kara** [comment]
@gkalpak Can you create another PR for patch? Changes don't apply cleanly

**Comment by gkalpak** [comment]
PR for patch: #31300

**Pull request closed without merging**
