### PR TITLE
fix(compiler): allow binding to autocomplete property on select and textarea elements

### LINKED ISSUE #39490: Language service tags autocomplete for textarea and select as errors.
# 🐞 bug report

### Affected Package
Compiler

### Is this a regression?

No

### Description
This is the error generated from ng build --prod
src/app/shared/user-input/user-input.component.html:5:7 - error NG8002: Can't bind to 'autocomplete' since it isn't a known property of 'textarea'.

5       [autocomplete]="config.autocomplete"
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/shared/user-input/user-input.component.ts:30:16
    30   templateUrl: './user-input.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component UserInputComponent.
src/app/shared/user-input/user-input.component.html:44:7 - error NG8002: Can't bind to 'autocomplete' since it isn't a known property of 'select'.

44       [autocomplete]="config.autocomplete"

## 🔬 Minimal Reproduction


## 🔥 Exception or Error



## 🌍  Your Environment

**Angular Version:**

**Anything else relevant?**

https://github.com/angular/angular/blob/master/packages/compiler/src/schema/dom_element_schema_registry.ts#L143,L156 doesn't list autocomplete as an attribute for select and textarea.

This pull in 2017 says the schema was generated from Chrome
https://github.com/angular/angular/pull/17858

Chrome didn't support autocomplete in textarea and select in 2017. Support was added in 2018

https://www.chromestatus.com/feature/5680387573415936

### PR DESCRIPTION
**Pull request by crisbeto**
Updates the schema to allow binding to the `autocomplete` property of a `textarea` or `select`.

Fixes #39490.

### CODE REVIEW

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:360228656:BASE:360228691:1614624921958:2b7cba8).

**Comment by AndrewKushnir** [comment]
@crisbeto FYI presubmits are successful for the changes in this PR. This PR should be ready for merge once there is a final approval from `language-service` group (cc @kyliau @atscott). Thank you.

**Review by atscott — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Merge assistance: this PR has received approvals from all the necessary groups, but PullApprove didn't pick up Jeremy's approval https://github.com/angular/angular/pull/40928#pullrequestreview-595688660, so it indicates that the `fw-security` review is needed.

**Review by jelbourn — APPROVED** [review]
I'll try again

Reviewed-for: fw-security

**Pull request closed without merging**
