### PR TITLE
docs: add deprecated-api-item class to deprecated items

### PR DESCRIPTION
**Pull request by ajitsinghkaler**
Fixes#31455

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Deprecated Items are not striked through

Issue Number: #31455
Deprecated Items are striked through

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Thanks @ajitsinghkaler - did you check methods and other doc types too?

**Comment by petebacondarwin** [comment]
Also I think you need a space between Fixes and #31455 in the commit message.

**Comment by ajitsinghkaler** [comment]
Can I know which other methods and other doctypes I need to check

**Comment by petebacondarwin** [comment]
Look through the API pages and think about what other things might be deprecated, such as methods.
It might be helpful to search the source code in https://github.com/angular/angular/tree/master/packages to find `@deprecated` tags and then check that those things are being displayed correctly in the site.

**Comment by ajitsinghkaler** [comment]
@petebacondarwin As I can see I 've checked only a 13 of 233 instances there are many instances where we are not striking through the deprecated elements. I'll try to check the rest of them later. If that is okay I'm attaching the images of the failed cases. Please have a look and tell me if we even need to strike through them.

Desktop screenshot (17)
Desktop screenshot (16)
Desktop screenshot (15)
Desktop screenshot (14)
Desktop screenshot (13)](https://user-images.githubusercontent.com/39260684/69750112-f35a9d00-1171-11ea-944d-50cb71cd8cb0.png)
ea-8182-97d259fff7e2.png)
Desktop screenshot (12)

**Comment by ajitsinghkaler** [comment]
Please tell me what we need to do with them.

**Comment by petebacondarwin** [comment]
Thanks for looking into this further. When I search the code-base I see that:

* All classes, consts, interfaces, types, etc  are already handled before this PR.
* All class properties and enum members are now being handled by this PR.
* Class method details are not handled. E.g. https://github.com/angular/angular/blob/17f7bdbd60708f43ea78bb1237268f6920448ba8/packages/core/src/testability/testability.ts#L103 - see https://pr34088-2ce91da.ngbuilds.io/api/core/Testability
* Individual overloads of a method are not handled. E.g. https://github.com/angular/angular/blob/86104b82b8af87efab46db50962e6b16f3724672/packages/core/src/di/injector.ts#L62 - see https://pr34088-2ce91da.ngbuilds.io/api/core/Injector
* Options on decorators are not handled. E.g. https://github.com/angular/angular/blob/1799f621b7773d41d5d3f74746cd01b44a492a1b/packages/core/src/metadata/directives.ts#L545 - see https://pr34088-2ce91da.ngbuilds.io/api/core/NgModule

So the templates that deal with these missing items are where we need to focus our attention.

If you want, we could mark this PR as merge, since it already improves the docs - and you could work on a 2nd PR for these other items.

**Review by petebacondarwin — APPROVED** [review]

**Comment by ajitsinghkaler** [comment]
Okay, we can merge this and I'll start working on the others later.

**Comment by ajitsinghkaler** [comment]
@petebacondarwin other items also work, in the same way, I just have to play on the deprecated property that it and please go ahead and merge this.

**Pull request closed without merging**
