### PR TITLE
perf(upgrade): unregister `$doCheck` watcher when destroying upgraded component

### PR DESCRIPTION
**Pull request by gkalpak**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Watchers registered on the parent scope for `$doCheck()` hooks on upgraded components, do not get unregistered when the component is destroyed (e.g. via a structural directive).

**What is the new behavior?**
All necessary watchers get unregistered when the upgraded component is destroyed.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by petebacondarwin — COMMENTED** [review]
LGTM

**Review by petebacondarwin — APPROVED** [review]
LGTM

**Comment by mhevery** [comment]
Please rebase on top of #14346

**Comment by gkalpak** [comment]
@mhevery: Done.

**Comment by gkalpak** [comment]
Hm...something went wrong. Fixing...

**Comment by gkalpak** [comment]
It should be fine now (I think).

**Comment by mhevery** [comment]
Sorry still can't merge due to conflict. Can you try again and this time on master?

**Comment by mhevery** [comment]
@gkalpak does not cherre-pick on 2.4.x, if you would like it on that branch, please cherry-pick.

**Pull request closed without merging**
