### PR TITLE
fix(core): typo in comment fixed

### PR DESCRIPTION
**Pull request by smartm0use**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
It fixes typo in using the word "multi".

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The word "multi" was written as "mutli".

## What is the new behavior?
The word "multi" is now written in the right way.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by Splaktar — APPROVED** [review]
The commit message does not follow the guidelines, but otherwise LGTM.

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
@smartm0use can you please update the commit message and force-push into your branch? the CI check is failing the lint step because your commit message is written in a invalid format (updating the PR description is not sufficient).

thanks!

more info: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by smartm0use** [comment]
I pushed again. Is it ok now?

**Comment by brandonroberts** [comment]
@smartm0use you need to squash down to one commit and update the commit message to provide more context, such as `docs(core): fix typo in style bindings comment`.

**Comment by brandonroberts** [comment]
Caretaker note: This is a docs only change and should not impact g3. Please run presubmit.

**Comment by matsko** [comment]
Please merge both commits into one and rename it to be a `docs` commit.

**Comment by smartm0use** [comment]
I think I did as you told me, but merge is currently blocked.

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Merge-assistance: this is only a docs change and so should not need a presubmit.

**Pull request closed without merging**
