### PR TITLE
docs: various deprecations for v13.2.0

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This PR contains a couple commits that deprecate a few symbols (the symbols are still available - they'll be removed in future versions).

## PR Type
What kind of change does this PR introduce?

- [x] Other... Please describe: deprecations of unused or no longer needed symbols.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:422820201:BASE:422820245:1642609656828:6784e4).

**Review by alxhub — APPROVED** [review]

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by alxhub — APPROVED** [review]
Reviewed-for: public-api

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 4e95a316cef35a771cd8168e3a744eb6bd7f1615.

**Pull request closed without merging**
