### PR TITLE
Revert "fix(compiler): shouldn't throw when Symbol is used as DI toke…

### PR DESCRIPTION
**Pull request by mhevery**

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]

**Comment by DzmitryShylovich** [comment]
@mhevery 
> This feature is not compatible with the `Injector.get` which now only 
takes `Type` or `InjectableToken`.

what about strings? string can be used as a DI token but it's nither a `Type` nor an `InjectionToken`
http://plnkr.co/edit/fsg8igP78pl5JKABPhqQ?p=preview

Victor [said](https://github.com/angular/angular/issues/13314#issuecomment-265869531) anything can be used as a DI token. is it no longer true?

**Comment by tbosch** [comment]
@DzmitryShylovich For JIT, anything can be used as DI token. But for AOT, only strings and OpaqueToken work...

**Comment by DzmitryShylovich** [comment]
@tbosch
> But for AOT, only strings and OpaqueToken work...

plus classes (Types) I guess.

ok, thanks.
shouldn't `Injector.get` signature be updated then?
```
get<T>(token: string|Type<T>|InjectionToken<T>, notFoundValue?: T): T
```

**Comment by DzmitryShylovich** [comment]
@tbosch maybe it also makes sense to update `Provider.provide` type? Currently it's `any`.
because it's always confusing that something works in jit but doesn't work in aot and there's still no official docs what is supported and what is not. Plus ngc throws not very helpful error messages https://github.com/angular/angular/issues/15188#issuecomment-287071581

**Comment by tbosch** [comment]
@DzmitryShylovich Using `string` in `get<T>(token: string|Type<T>|InjectionToken<T>, notFoundValue?: T): T` does not enforce a type. So we will probably change the other `get` method, which current takes `any` to `string`...

We can't make `provide` in `Provider` anything else than `any` as this would break users.

**Comment by tbosch** [comment]
@mhevery what do you think?

**Comment by mhevery** [comment]
Hi @DzmitryShylovich Yes we are tightening the type and `Injector.get` and it will soon not take `strings`. It will only support `Type` and `InjectionToken<Type>`. We have to wait until v5 to drop the rest.

Yes you are right, we should tighten the typings on `Provider` as well. Do you want to take a stab at it?

**Comment by DzmitryShylovich** [comment]
@mhevery 
>  Do you want to take a stab at it?

yeah. PR is here https://github.com/angular/angular/pull/15340

**Pull request closed without merging**
