### PR TITLE
docs: update link to post on redirects in router guide

### PR DESCRIPTION
**Pull request by HamzaDevz**
## PR Checklist

- [] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

In Routing and Navigation doc : (https://angular.io/guide/router)
The url of Victor savkin's url post on redirects is no longer accessible

Issue Number: N/A

## What is the new behavior?
Change victor savkin's url post on redirects to:
http://vsavkin.tumblr.com/post/146722301646/angular-router-empty-paths-componentless-routes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by HamzaDevz** [comment]
I signed it!

**Comment by HamzaDevz** [comment]
I add ci/circle

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update git commit message to `docs: update link to post on redirects in router guide`

**Comment by brandonroberts** [comment]
Thanks for the PR @HamzaDevz! I left you some feedback. Once the changes are made, the PR is reviewed and approved, and CI is green, its ready for merge.

**Comment by HamzaDevz** [comment]
@brandonroberts I edited my commit message

**Comment by HamzaDevz** [comment]
@brandonroberts It seems that there is still a problem with my PR ?

**Comment by HamzaDevz** [comment]
@brandonroberts Any news on this ?

**Comment by brandonroberts** [comment]
@HamzaDevz will you rebase this branch on master? The test failures were due to a problem with an external package.

**Review by brandonroberts — APPROVED** [review]

**Pull request closed without merging**
