### PR TITLE
refactor(ivy): don't create TNodes for native projectable nodes

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Before this commit we were creating a "fake" TNode for each and every
projectable node passed during dynamic component creation. This approach
had several problems:
- the existing TView structure had to be mutated to accomodate new TNodes and
it was very easy to "corrupt" TView / TNode data structures;
- TNodes are not really needed to fully support projectable nodes so we were
creating objects and updating existing data structures for nothing.

This commit changes the approach so we don't create "fake" TNodes for projectable
nodes but instead we process projectable nodes directly in the projection instruction.
As a result we've got less code, less object allocation and - as a bonus - we fix few
bugs where TView / TNode data structures were corrupted when using projectable nodes.

**NOTE A REVIEWER**: there is still one remaining test marked with FW-873 - this is because the root cause is _different_ to the one fixed in this PR (LView / TView corruption by TNodes created for projectable nodes). I've investigated the other root cause and I know what is going on plus I _think_ I know how to fix it. But the fix is not trivial so it will be done in a separate PR.

### CODE REVIEW

**Comment by petebacondarwin** [comment]
The legacy test failure looks legit! We are now adding an `ng-star-inserted` attribute to the projected node, right?

**Review by kara — APPROVED** [review]
LGTM

**Comment by kara** [comment]
@petebacondarwin I think the test failure you mentioned has been fixed. Can you take another look?

**Comment by pkozlowski-opensource** [comment]
@kara yep, the error @petebacondarwin mentioned was present only in the WIP version of this PR. So all is good here.

**Comment by kara** [comment]
[presubmit](http://test/OCL:230386129:BASE:230386268:1548188055127:34faf7d9)

**Comment by kara** [comment]
merge-assistance: global approval, since the test failure has been fixed and the only changes in upgrade are to turn on the tests.

**Pull request closed without merging**
