### PR TITLE
docs(router): Removed unneeded trailing text.

### PR DESCRIPTION
**Pull request by georgewilde**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by georgewilde** [comment]
I signed it!

**Comment by georgewilde** [comment]
The Travis CI build failure does not seem to be related to the code I have changed.

**Comment by brandonroberts** [comment]
@georgewilde we'll work on getting it green on CI. Once its green and approved it will be ready for merge.

**Comment by jenniferfell** [comment]
@brandonroberts I removed merge labels from this PR. Please coordinate review and approval with someone in the router pull-approval group. Thanks!

**Review by IgorMinar — APPROVED** [review]

**Pull request closed without merging**
