### PR TITLE
fix(docs-infra): remove extra anchor space in callouts

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
in callout elements if an empty anchor is set as the first
element of a callout it creates extra space, that is caused
by the anchor's margin, remove such margin to clear the extra space

note: this would also apply to non-empty anchors, but there should not be
any such anchors as the callout's first child (as that should be the
header)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

Invisible anchor elements cause ugly spaces in callout elements before the header:
Screenshot at 2021-10-16 22-40-07

## What is the new behavior?

The space is removed, the functionality remains the same (you can still use the anchor as before):
Screenshot at 2021-10-16 22-39-25

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other Information

As far as I can tell this only happens for the callouts [here](http://localhost:4200/guide/security#report-issues)
caused by these type of anchors: https://github.com/angular/angular/blob/1317e193787ba80a0571d8bf292afc7455007c3c/aio/content/guide/security.md?plain=1#L13

So I guess this could also be solved in the following way:
```diff
- {@a report-issues}
+ <div id="report-issues" tabindex="-1"></div>
...
- {@a best-practices}
+ <div id="best-practices" tabindex="-1"></div>
```

if this solution is preferred please let me know and I'll update the PR :slightly_smiling_face:

### CODE REVIEW

**Review by gkalpak — COMMENTED** [review]
Good catch, @dario-piotrowicz 😅

I am little torn on this one. Generally, I would argue that putting other content above the `<header>` should be expected to mess up the layout.  So, people should put any `{@a ...}` annotations above the callout `<div>`. 
On the other hand, `{@a ...}` annotations might be special in that people could think of it as metadata and not realize that they will result in actual HTML content.

If it is just these two occurrences in the security guide, I would lean towards just relocating the annotations above the `<div>`s. (If there are more occurrences, addressing it in CSS would make sense.

WDYT, @dario-piotrowicz?

**Comment by dario-piotrowicz** [comment]
> Good catch, @dario-piotrowicz sweat_smile
> 
> I am little torn on this one. Generally, I would argue that putting other content above the `<header>` should be expected to mess up the layout. So, people should put any `{@a ...}` annotations above the callout `<div>`. On the other hand, `{@a ...}` annotations might be special in that people could think of it as metadata and not realize that they will result in actual HTML content.
> 
> If it is just these two occurrences in the security guide, I would lean towards just relocating the annotations above the `<div>`s. (If there are more occurrences, addressing it in CSS would make sense.
> 
> WDYT, @dario-piotrowicz?

Yeah I totally agree with you and that's exactly my reasoning, since people could think of that as metadata we could have other occurrences of this bug happening again, but I do think that would be unlikely and that it should be noticed and fixed during development (I am surprised this wasn't noticed in the PR review anyways), so mine was a sort of cautious change to make sure that even if someone puts the`{@a ...}` there all would still be well and good (that being said, this would also suggest that this is the intended way to have the anchors for callouts, so could actually drive people to do it more :sweat_smile:)

So yeah, I agree that if it's just these two occurrences and we don't want `{@a ...}` to be put there, it does just make more sense to fix the two instead of making a global fix :slightly_smiling_face: 

But I actually thought that instead of using the `<div>`s as I suggested, I could just move the `{@a ...}`s above the callouts as you mentioned above (that would also be consistent with https://github.com/angular/angular/blob/bba683bb6865e667cb945a87d2a50419c6b73b56/aio/content/guide/router-tutorial-toh.md?plain=1#L291-L293, which as far as I can tell is the only other instance of a callout having an anchor)

would that be ok? :slightly_smiling_face:

**Comment by gkalpak** [comment]
SGTM :+1:

**Review by gkalpak — APPROVED** [review]
LGTM

Reviewed-for: global-docs-approvers

**Pull request closed without merging**
