### PR TITLE
fix(changelog): fix rxjs operator import paths

### PR DESCRIPTION
**Pull request by tamascsaba**
I have changed the wrong import folder.

### CODE REVIEW

**Comment by robwormald** [comment]
this was technically correct at the time this entry was added to the changelog, although your corrections now are correct :D - could you correct the commit message to say something like `fix(changelog): fix rxjs operator import paths`

**Comment by gkalpak** [comment]
Shouldn't ir rather be `docs(changelog): ...` ?

**Comment by tamascsaba** [comment]
Thanks :), I modified my commit and P.M title too.

**Comment by vicb** [comment]
@robwormald are the changes correct in the context of alpha 48 ?

**Comment by robwormald** [comment]
@vicb there was so much churn in the last few revs of ng2 and Rx i've honestly lost track :octocat: As far as i'm aware they were - these changes are valid for 52+

**Comment by vicb** [comment]
Not sure if I get your message ? (48 is < 52+).
Anyway feel free to add the lgtm label if this is ok.

**Comment by IgorMinar** [comment]
we should document the current state, so the PR is good. if someone cares about the instructions for a48 they can look at the old version of this file.

**Pull request closed without merging**
