### PR TITLE
Update adev README link to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by lamek**
Quick link fix

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by bencodezen — APPROVED** [review]
Good catch! Thank you!

**Comment by JeanMeche** [comment]
Hi, can you check our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit) and reword the commit message, thank you.

**Comment by bencodezen** [comment]
Hey @lamek! Thanks for the PR. It looks liek there's a commit conflict. Can you update and then squash to one commit? Appreciate it!

**Comment by JeanMeche** [comment]
Thanks for your contribution, in the meantime this has been fixed by #56581

**Pull request closed without merging**
