### PR TITLE
docs: migrate toh-pt1 to standalone

### PR DESCRIPTION
**Pull request by bencodezen**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Review by twerske — APPROVED** [review]

**Review by twerske — APPROVED** [review]

**Review by MarkTechson — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
@bencodezen Looks like this has CI failures. Once you fix those, I'll merge it.

**Comment by MarkTechson** [comment]
@bencodezen looks like a couple of tests are failing, can you please have a look?

**Comment by mvdluit** [comment]
@MarkTechson @twerske @bencodezen The tour of heroes tutorial on angular.io is in a weird state right now, generating a standalone application but still referencing modules (e.g https://angular.io/tutorial/tour-of-heroes/toh-pt1#appmodule). While on the discord server we are directing beginners to use the adev tutorials, a lot of people still run into this issue on the TOH tutorial.

This PR (and https://github.com/angular/angular/pull/51612 and https://github.com/angular/angular/pull/51613) seem to fix these issues. Can this please be looked at, because it's not a good look when you're pushing for the use of standalone and your own tutorial is causing confusion for beginners.

**Comment by bencodezen** [comment]
@mvdluit Thanks for expressing your concerns. I've gone ahead and closed this issue to help reduce confusion on this end.

**Pull request closed without merging**
