### PR TITLE
Revert "refactor(platform-browser): Throw tree-shakable errors. (#49341)

### PR DESCRIPTION
**Pull request by alxhub**
This reverts commit 80fe08be96633171567e30eb91dd1d23c60a2952. Reason: it causes failures in g3.

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api 
Reviewed-for: fw-core 
Reviewed-for: fw-security

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by alxhub** [comment]
Closing as this turned out not to be the culprit.

**Pull request closed without merging**
