### PR TITLE
docs: Update events.html

### PR DESCRIPTION
**Pull request by grant**
Updates outdated [events page](https://angular.io/events) by moving events that have already occurred to the list of past events.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The https://angular.io/events page contains outdated events.

## What is the new behavior?

The https://angular.io/events page correctly states events "where we'll be presenting".

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by brandonroberts — DISMISSED** [review]
Update git commit message to `docs: move past events on events page`

**Comment by brandonroberts** [comment]
Thanks for the PR @grant! I left you some feedback. After the changes are made, this PR gets reviewed, is approved, and is green on CI, its ready to merge.

**Comment by grant** [comment]
Updated git commit message to `docs: move past events on events page`.

**Review by IgorMinar — APPROVED** [review]
thanks!

**Pull request closed without merging**
