### PR TITLE
docs: describe your change...

### PR DESCRIPTION
**Pull request by Mwiku**
Make more readable by creating app without prompts with a single command

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by atscott — APPROVED** [review]
LGTM - adding @aikidave for docs approval

**Review by aikithoughts — COMMENTED** [review]
I don't object to this change, but I'm wondering: is the change in readability that significant? This seems very minor.

**Comment by petebacondarwin** [comment]
@Mwiku - before we can land this change we need you to sign the CLA.

**Comment by jelbourn** [comment]
Closing this due to lack of CLA

**Pull request closed without merging**
