### PR TITLE
fix(common): specify explicit locales dir in package.json

### PR DESCRIPTION
**Pull request by filipesilva**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Locale file directory is implicit in `@angular/common`.

## What is the new behavior?
Locale file directory is explicit in `@angular/common`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
@vicb @hansl @ocombe maybe some bikeshedding is in order about the property name.

### CODE REVIEW

**Comment by vicb** [comment]
I am usually :-1: for this kind of change as it does not bring enough added value:
- does not solve a current pb,
- I am pretty sure than anybody renaming the folder would miss to update the name here,

What about we live with what we have now and introduce this if needed later (if/when the folder gets renamed). Hopefully a renaming would trigger a test failure so that we don't release a broken CLI ?

**Comment by vicb** [comment]
closing for now.

**Comment by filipesilva** [comment]
I think it is important to get such a fix in sooner rather than later because not having breaks compatibility between Angular and CLI versions.

Imagine Angular 6 uses a different locale folder. CLI 1.5 and up (possibly a lot of versions) commands that use locales will be broken. I think this situation is preventable by not having a hardcoded path.

This sort of breakage is not easily tested for in the CLI side because it spans several versions. 

You expressed concern that the value in `package.json` would not be updated. Angular tests that use the locale paths should also draw it from `package.json`, and thus break if one is updated without the other.

**Comment by ocombe** [comment]
As long as I'm here I'll make sure that the CLI is in sync with Angular.
If we make any change it would probably be to move i18n to its own package,
and the package.json property would not fix that anyway...

Le ven. 8 déc. 2017 à 11:28, Filipe Silva <notifications@github.com> a
écrit :

**Comment by vicb** [comment]
@filipesilva I understand your concern. Feel free to re-open a PR when you have a test for the locale value.

**Comment by filipesilva** [comment]
@vicb I have opened a new PR (#21016) with a unit test for the locale value.

**Pull request closed without merging**
