### PR TITLE
feat(core): display warning when calling `detectChanges()` on the dynamic OnPush component.

### LINKED ISSUE #36667: ComponentRef Change detector doesn't trigger detecting for view
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Cannot say

### Description

 
**Component created by #ComponentFactoryResolver.**
ComponentFactoryResolver#createComponent returns ComponentRef that does have changeDetectorRef.   
**After any changes to component's input by code (not by template) and invocation of such ComponentRef#changeDetectorRef.detectChanges component's view won't be updated.**  

_example from repro: dynamic-wrapper.component.ts#createComponent._ 
> componentRef.changeDetectorRef.detectChanges()

This is root issue.

_To testing purposes ChangeDetectorRef was be added to component's constructor and invoked by 
consumer of this ComponentFactoryResolver. CDR from component's injector works as expected_ 

_example from repro: dynamic-wrapper.component.ts#createComponent_
> componentRef.instance.cdr.detectChanges()

## 🔬 Minimal Reproduction

 
[StackBlitz](https://stackblitz.com/github/RolginRoman/ng-dynamic-components-cdr-repro?file=src%2Fapp%2Fdynamic-wrapper%2Fdynamic-wrapper.component.ts)
  

GitHub repro repository:
https://github.com/RolginRoman/ng-dynamic-components-cdr-repro

## 🔥 Exception or Error
<pre><code>
No exception
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

 Angular version 9.1.0

</code></pre>

**Anything else relevant?**

Seems like browser, OS version or anything else doesn't matter

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Close #36667

Calling `componentRef.detectChanges()` sometimes does not work as expected.

```
@Component({
  selector: 'dynamic',
  template: `{{name}}`,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class Dynamic  {
  name = 'initial name';
}

const componetRef = cfr.createComponent(Dynamic);
componentRef.changeDetectorRef // host view
componentRef.injector.get(ChangeDetectorRef) // component view
componentRef.instance.cdRef // componentView

componentRef.instance.name = 'something new';
// componentRef.instance.cdRef.markForCheck();
componentRef.detectChanges(); // does not work without `markForCheck`
componentRef.changeDetectorRef.detectChanges() // Users expect that Bar gets refreshed.
componentRef.injector.get(ChangeDetectorRef).detectChanges()
componentRef.instance.cdRef.detectChanges()

// Example: https://stackblitz.com/edit/angular-drqzhw?file=src%2Fapp%2Fapp.module.ts
ngOnInit() {
    const cmptRef = this._cfr
      .resolveComponentFactory(Dynamic)
      .create(this._injector);
    this._vcRef.insert(cmptRef.hostView);

    setTimeout(() => {
      cmptRef.instance.name = "changed name";
      console.log("changing name");
      cmptRef.changeDetectorRef.detectChanges(); // does not work
    });

    setTimeout(() => {
      cmptRef.instance.name = "second changed name";
      console.log("changing name");
      cmptRef.injector.get(ChangeDetectorRef).detectChanges(); // works
    }, 2000);
}
```
For components which are `bootstrap`ed or are `dynamic` Angular must create `HostView` to install the Component `View` into. For dynamically created components `componentRef.changeDetectorRef` refers to `HostView` NOT the Component's `View`. When the Component is `OnPush` calling `changeDetectorRef.detectChanges()` has surprising consequence of not updating the Component`s `View. 

In this change we automatically mark the `HostView` as dirty when calling `changeDetectorRef.detectChanges()` on the Component `View`.

### CODE REVIEW

**Comment by JiaLiPassion** [comment]
@mhevery , @atscott , we discussed this issue earlier, and we can add some doc to explain the behavior instead of changing the `Change Detection` logic, but for this  specified case, I think we just need to update the logic a little bit  (only impact dynamic component creation) without impact the main part of the `Change Detection` logic. 
Please review, thank you.

**Comment by atscott** [comment]
👍  This seems like a reasonable compromise to me. Let's see how the presubmit results turn out and go from there.

**Review by mhevery — APPROVED** [review]
Fixup: c04659ea74

I agree that this is a reasonable compromise. 

I do have a concern that we are changing how Ivy works and may inadvertently make it harder for Ivy to roll out it `google3` So I would like to merge this after `google3` Ivy rollout.

Some test failures look suspicious. [deflake](https://test.corp.google.com/ui#id=OCL:357785086:BASE:360780852:1614816922514:6bc3b506)

**Comment by atscott** [comment]
@mhevery FWIW, there were quite a few failing tests when I ran the presubmit. I didn't do any more investigation for them because I have a few other v12 breaking changes to work through. I think this would likely be considered a breaking change and at that point, I wonder if we should scrap this change and roll it into the zone-less work like we had planned before. Maybe further investigation into those failures would reveal that this isn't as much of a concern.

**Comment by mhevery** [comment]
> @mhevery FWIW, there were quite a few failing tests when I ran the presubmit. I didn't do any more investigation for them because I have a few other v12 breaking changes to work through. I think this would likely be considered a breaking change and at that point, I wonder if we should scrap this change and roll it into the zone-less work like we had planned before. Maybe further investigation into those failures would reveal that this isn't as much of a concern.

I agree, I think we should stop fix this issue and just come up with better approach with zoneless given the amount of work to land this would be.

**Review by atscott — COMMENTED** [review]
I think that a warning could still be an issue, unfortunately. We tried to add a warning in the router a while back and had to revert it (https://github.com/angular/angular/issues/38804). The biggest reason the warning was problematic was that tests often set up code that wouldn't necessarily be used in a production application but _do_ accomplish a desired goal for a testing scenario. So the warning was popping up much to often.

For this change, the warning will happen if the test calls `createComponent` with an `OnPush` component directly (i.e. no wrapper component for the test) and then calls `autoDetectChanges` on the fixture. Calling `autoDetectChanges` is common practice in g3.

I don't think we can land this change, even as a warning.

**Comment by JiaLiPassion** [comment]
@atscott , Got it, thank you, I will close this one.

**Pull request closed without merging**
