### PR TITLE
feat(compiler-cli): use ts.compilerHost as moduleResolutionHost for tsickle.emitWithTsickle to support tsickle 0.33.1

### PR DESCRIPTION
**Pull request by delagen**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Compilation fails with exception of get directoryExists on undefined
```
TypeError: Cannot read property 'directoryExists' of undefined
    at Object.directoryProbablyExists
```
Because of moduleResolutionHost is undefined due TsickleHost created does not contain `host` property
Related lines:
https://github.com/angular/tsickle/blob/master/src/tsickle.ts#L172
https://github.com/Microsoft/TypeScript/blob/0a7c92864d628c02e450f23ab2547ed1f5954b56/src/compiler/utilities.ts#L4019

Issue Number: N/A

## What is the new behavior?
Compilation success.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by wbhob** [comment]
any update on this PR?

**Comment by maxi7587** [comment]
Is this going to be merged? I am upgrading to Angular 8 and cannot run ngc:
```
TypeError: Cannot read property 'directoryExists' of undefined
    at Object.directoryProbablyExists
```

**Comment by mariohmol** [comment]
Hi.. experiencing the same here https://travis-ci.com/jsGanttImproved/ng-gantt/builds/121972040

**Comment by AndrewKushnir** [comment]
Currently `tsickle` version is set as "0.38.1" in `package.json`, so this PR looks obsolete. Feel free to reopen if the problem still exists. Thank you.

**Pull request closed without merging**
