### PR TITLE
docs: fix missing information in createComponent guide

### LINKED ISSUE #51492: createComponent function example not work on 16.2.1
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

The document wrong: https://angular.io/api/core/createComponent
``` 
const componentRef = [createComponent](https://angular.io/api/core/createComponent)(HelloComponent, {host, environmentInjector});

host was change to hostElement, should become this
const componentRef = [createComponent](https://angular.io/api/core/createComponent)(HelloComponent, {hostElement, environmentInjector});

```

Btw it just not work.

### Please provide a link to a minimal reproduction of the bug

[this one work]
https://stackblitz.com/edit/angular-anxyrb?file=src%2Fmain.ts,src%2Findex.html 
[not work version]
https://codesandbox.io/p/sandbox/relaxed-feather-27fv8y?file=/src/app/app.component.ts:63,6

### Please provide the exception or error you saw

```true
NG0912: Component ID generation collision detected. Components 'HelloComponent' and 'HelloComponent' with selector 'hello-component' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912
```

### Please provide the environment you discovered this bug in (run `ng version`)

_No response_

### Anything else?

ng version result:

image

### PR DESCRIPTION
**Pull request by hiepxanh**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #51492

this should: Fixes #51492

## What is the new behavior?

just update docs

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
LGTM

**Review by AndrewKushnir — APPROVED** [review]

**Comment by hiepxanh** [comment]
I just added a new example with dynamic html, I think this will be really useful for a lot of developers trying to implement this feature since the dynamic render html is the most common case example.

**Comment by JeanMeche** [comment]
Hi, could you please squash your commits. This change should be a single commit !

**Comment by hiepxanh** [comment]
Yes that my bad, I'm sorry sir, I did squash into one commit

**Review by AndrewKushnir — COMMENTED** [review]
@hiepxanh the change in this PR that starts with "The example below demonstrates how to use the function to render component with dynamic HTML" is similar to the change in https://github.com/angular/angular/pull/51573 and I have a similar comment: https://github.com/angular/angular/pull/51573#discussion_r1310676438. We consider the `innerHTML` usage as a direct DOM manipulation, which is not supported by hydration logic (we strongly encourage using other APIs like NgComponentOutlet). Could you please revert the changes starting from "The example below demonstrates how to use the function to render component with dynamic HTML", so that we can complete the code review?

**Comment by hiepxanh** [comment]
I did force push again with clear content

**Comment by AndrewKushnir** [comment]
**Caretaker note**: no g3 presubmit is required, doc-only change.

**Comment by jessicajaniuk** [comment]
@hiepxanh looks like the lint is still failing.

**Comment by hiepxanh** [comment]
@jessicajaniuk  my bad to not lint before push. I do check again and force push

**Review by AndrewKushnir — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 5a323265cb05fede8a9ab97834d3cf140bc128e7.

**Pull request closed without merging**
