### PR TITLE
refactor(common): align tree shakable error messages to new format

### PR DESCRIPTION
**Pull request by ramthir**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Tree shakable error message has a long format with `errorMessage` variables.

Issue Number: N/A

## What is the new behavior?

Align tree shakable error messages are simplified with the new format introduced by @AndrewKushnir and remove `errorMessage` variables.

```ts
throw new RuntimeError(
  RuntimeErrorCode.INJECTOR_ALREADY_DESTROYED,
  ngDevMode && 'Injector has already been destroyed.');
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@ramthir thanks for the cleanup, the code looks great 👍

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:455186126:BASE:455186181:1655319468893:4c7f8e49).

**Review by jessicajaniuk — APPROVED** [review]
LGTM! Thank you!

**Comment by AndrewKushnir** [comment]
Merge-assistance: the change in this PR does **not** change any logic, it just refactors the code around the error messages (changing ternary -> `&&`) for consistency with other locations. Existing approvals should be sufficient.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit df1652e7d747a698a87a162f18717618422f4a43.

**Pull request closed without merging**
