### PR TITLE
Allow undefined for first and last

### PR DESCRIPTION
**Pull request by rahilpeerbits**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/angular/angular/issues/42563

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by dario-piotrowicz** [comment]
Your commit message isn't a valid one, please adhere to the correct format: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format

**Comment by dario-piotrowicz** [comment]
Also circleci lint and the tests are failing, did you run the lint check and the tests locally before opening the PR?

**Comment by jelbourn** [comment]
@rahilpeerbits the file you're editing is only a test golden. This file is automatically generated from the source code and does not affect any published code. To make this change, you'd have to update the source code and also regenerate this golden. 

Additionally, this change would be a significant breaking change for anybody that uses queries. At a minimum we wouldn't be able to land this outside of a major version. Changes like this are also very difficult for the team to roll out inside Google; we might ultimately decide to live with the type as-is if the rollout would be too time consuming.

**Comment by dario-piotrowicz** [comment]
@rahilpeerbits are you still looking into this one?
I was told that in a couple of weeks the window for v13 is going to be opened (https://github.com/angular/angular/pull/42608#discussion_r671823789) so this should be worked on sooner rather than later if we want to include it in v13

If you are not going to work on this anymore I will gladly take it off your hands :slightly_smiling_face:

**Comment by IgorMinar** [comment]
hey @rahilpeerbits, as @jelbourn mentioned this needs to be implemented in the source code under the `packages/core/` directory in addition to the golden file (the golden file is autogenerated by tooling). If you and @dario-piotrowicz wants to fix this bug (the bug is valid, but we need to ensure that its implemented in a way that doesn't break the world *too much*) then please open up a new PR. Thank you

**Comment by dario-piotrowicz** [comment]
> hey @rahilpeerbits, as @jelbourn mentioned this needs to be implemented in the source code under the `packages/core/` directory in addition to the golden file (the golden file is autogenerated by tooling). If you and @dario-piotrowicz wants to fix this bug (the bug is valid, but we need to ensure that its implemented in a way that doesn't break the world _too much_) then please open up a new PR. Thank you

Done :smiley: https://github.com/angular/angular/pull/43604

**Pull request closed without merging**
