### PR TITLE
refactor(core): remove duplicated WrappedValue class

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Before this refactoring we had the WrappedValue class in
2 separate places:
- packages/core/src/change_detection/change_detection_util.ts
- packages/core/src/util/WrappedValue.ts

This commit removes the duplicate, leaving the class that has
the deprecation notice.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@atscott would you mind reviewing / running pre-submit on this one, as you were poking around WrappedValue recently?

**Comment by atscott** [comment]
[presubmit](http://test/OCL:320006978:BASE:320007030:1594141811507:d067fb35)

**Review by atscott — APPROVED** [review]
LGTM - I don't see any references to this anywhere so I can't imagine there will be any issue with removing it.

**Comment by atscott** [comment]
caretaker note: marking as master and patch because this specific instance isn't used anywhere. It's marked as publicApi but not exported (the other one is).

**Pull request closed without merging**
