### PR TITLE
ci: validate commit messages correctly when not on master

### PR DESCRIPTION
**Pull request by petebacondarwin**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

When CircleCI tries to run the `lint` job the `validate-commit-messags` task can
look at the wrong set of commits as it always bases the commit range off `master`.

## What is the new behavior?

Now the commit range is computed by looking at the version in `package.json` and then
finding the most recent branch that matches this version.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Actually this isn't going to help if the build is not from a PR... :-(

**Review by IgorMinar — APPROVED** [review]
thanks!

**Comment by tbosch** [comment]
Should we also merge this into 4.4?

**Comment by petebacondarwin** [comment]
No there is a separate one for patch

**Comment by petebacondarwin** [comment]
No there is a separate one for patch

**Comment by petebacondarwin** [comment]
https://github.com/angular/angular/issues/19720

**Pull request closed without merging**
