### PR TITLE
feat(common): ngSwitchCase add array support

### PR DESCRIPTION
**Pull request by maxigimenez**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Not possible to set multiple values to `ngSwitchCase`

Issue Number: [14659](https://github.com/angular/angular/issues/14659)

## What is the new behavior?
Support array expression on `ngSwitchCase`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by maxigimenez** [comment]
`cla/google` signed

**Comment by Airblader** [comment]
This *is* a breaking change as has been discussed in the issue. What's the counter argument as to why this isn't breaking?

**Comment by maxigimenez** [comment]
> This _is_ a breaking change as has been discussed in the issue. What's the counter argument as to why this isn't breaking?

This is not a breaking change, as you can see in the tests/code *ngSwithCase with singular values still works without a problem.

**Comment by Airblader** [comment]
That's because none of the existing tests used arrays. This is a breaking change, because before this change when switching on an array there'd be a comparison between the references which has different behavior. This has been explained in the issue already and I see no reason why that argument isn't valid.

**Comment by jotatoledo** [comment]
Just to clarify @Airblader idea, following use cases will be broken by this change:

````typescript
@Component({
 template `
  <button (click)="toggle()">Toggle arrays</button>
  <ng-container *ngSwitch="current">
    <span *ngSwitchCase="first">First is active</span>
    <span *ngSwitchCase="second">Second is active</span>
    <span *ngSwitchDefault>Unknown state</span>
  </ng-container>
 `
})
export class FooComponent {
 first = [];
 second = [];
 current: any[];

 toggle(){
 	this.current = this.current === this.first ? 
   		this.second : this.first;
 }
}
````

**Pull request closed without merging**
