### PR TITLE
WIP: mostly broken karma integration

### PR DESCRIPTION
**Pull request by IgorMinar**
cc: @zzo, @alexeagle 

can you guys take it from here?

### CODE REVIEW

**Comment by IgorMinar** [comment]
the missing pieces are removing the karma preprocessor and making all the config changes that @zzo proposed last week in https://github.com/zzo/angular/commit/6007290c41e11a0905dca393909cc4c36ad58124

**Comment by zzo** [comment]
yep will check it out.
  Mark

**Comment by zzo** [comment]
yep will check it out

**Comment by alexeagle** [comment]
Thanks Mark!
Today I am busy fixing up the ES6 emit from TypeScript and whatever else I
have to do to make things work with the .es6 and .js files removed.

**Comment by alexeagle** [comment]
FYI I have https://github.com/angular/angular/pull/1597 out with a cleanup version. I de-scoped the browser_tree change so it's easier to make some progress.

**Pull request closed without merging**
