### PR TITLE
Inconsistent space after method name.

### PR DESCRIPTION
**Pull request by t3dodson**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Trivial I know but someone should make this change somewhere.

### CODE REVIEW

**Comment by vicb** [comment]
The code is automatically formatted using clang.

Please create an issue on angular/clang-format if the pb still exists the latest release

/cc @mprobst

**Comment by mprobst** [comment]
Haha, yeah, that seems like the pseudo keyword "delete" bites clang. Will fix.

**Comment by vicb** [comment]
Thanks Martin

**Comment by pkozlowski-opensource** [comment]
@mprobst I've seen similar issue when using RxJS `let` operator (`obs$.let(...)` gets formatted as `obs$.let (...)`). You can see it "live" here: https://github.com/ng-bootstrap/ng-bootstrap/blob/667833c7af0bfb465e547b65d9eadc15bdbcb218/src/typeahead/typeahead.ts#L145

Looks like the same issue / root cause so would be good to add a test for `let` if you planning to fix `delete`.

**Comment by mprobst** [comment]
Actually the `foo.let()` call was fixed a long time ago, that's probably
just an outdated clang-format version?

**Comment by vicb** [comment]
> outdated clang-format version

as discussed yesterday, we can not update now, right ? `a.b.c()` might be formatted as `a\n.b\n.c()`

**Comment by mprobst** [comment]
Only in overlong template strings, right?

>

**Comment by vicb** [comment]
yep

**Pull request closed without merging**
