### PR TITLE
docs(core): Document invalid multi token

### PR DESCRIPTION
**Pull request by atscott**
Add error page for invalid multi token runtime error

Note: Technically this error should also be thrown for APP_INITIALIZER but at the moment, it will just silently ignore it since `appInits.length` will be `undefined`. Newly throwing an error here could be considered a breaking change.

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api

**Comment by jessicajaniuk** [comment]
Caretaker: Failing G3 status is unrelated flakes.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit ff84c7360334792a9a422bd0fa0353e0cf670525.

**Pull request closed without merging**
