### PR TITLE
docs: change crisis to Crisis in CrisisDetailResolver (#34905)

### PR DESCRIPTION
**Pull request by babatundelmd**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Typo in CrisisDetailResolver description

Issue Number: #34905

## What is the new behavior?
Changed crisis to Crisis in Router README.MD
## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by babatundelmd** [comment]
@googlebot I signed it!

**Comment by kapunahelewong** [comment]
Thank you for this, @babatundelmd. Did you by chance see @ajitsinghkaler's comment in #34905 about it not needing to be capitalized because it's a model in this case? I'm not really sure and can't find it in the [style guide](https://developers.google.com/style/code-samples). I'd love to hear your and other people's thoughts on it. Maybe @aikidave and @jbogarthyde?

**Comment by babatundelmd** [comment]
@kapunahelewong yes. I had earlier seen @ajitsinghkaler's comment which didn't click at the time. But reading the docs all over again makes sense now.

**Comment by ajitsinghkaler** [comment]
@babatundelmd if you understand the reason of small c in crisis can you please close your issue and pull request

**Comment by babatundelmd** [comment]
close #35034

**Pull request closed without merging**
