### PR TITLE
docs(demo): fix typo in injected variable name

### PR DESCRIPTION
**Pull request by jtheoof**
The service injected is `ValueService`, however the name of the variable
does not reflect that. It's actually confusing since it's the name of
the `class` being created.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Simple typo in the docs of `angular.io`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
caretaker note: can you update this pr with commit message: "docs: ..." rather than "docs(demo): ..."

**Comment by jtheoof** [comment]
sure thing. Should I be worried about the ci failures ? They seem unrelated to my changes.

**Comment by jtheoof** [comment]
Rebased and fixed typo.

**Comment by IgorMinar** [comment]
thanks for the rebase. the ci is now green

**Pull request closed without merging**
