### PR TITLE
docs: Add first-app tutorial

### PR DESCRIPTION
**Pull request by MarkTechson**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently the first app tutorial is incomplete.

Issue Number: N/A

## What is the new behavior?
The first app tutorial is now complete

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Shout out to bob-watson for his work on this PR.

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@MarkTechson Looks like this has a rebase issue with an extra merge commit at the end. If you need assistance with the lint and test failures, let me know.

**Comment by twerske** [comment]
Yay! It's happening!

I did an initial review of just the documentation structure before I review content:

1. I think the navigation and page structure need to be updated? Currently the preview still shows `Tour of Heroes` - and the `angular.io/start` old content. Which one is this meant to replace? Currently it seems like an additional new tutorial?
Screenshot 2023-04-26 at 11 06 59 AM

2. The titles of each step are quite long (ie. "Introduction to Angular tutorial - the First Angular app", "First Angular app lesson 1 - Hello world")  - are these final?

3. Are the videos meant to be embedded before this merges?

4. The Before you start/After you finish get really repetitive and make the lessons look pretty daunting and long, is that needed for all 14 pages? Google's codelabs do this step once as an example: https://codelabs.developers.google.com/

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by alxhub** [comment]
This PR was merged into the repository by commit b83d84aba7c2bcaf892c041aacdff220fe143c19.

**Pull request closed without merging**
