### PR TITLE
Simplify ngtsc now that ngcc is gone

### PR DESCRIPTION
**Pull request by JoostK**
See individual commits for various simplifications in the compiler that have been unlocked with the removal of ngcc.

### CODE REVIEW

**Comment by devversion** [comment]
Nice cleanup! One thing just to note: Back then we thought `Object.assign` support for partiual evaluation might be useful regardless. See: https://github.com/angular/angular/pull/34661#issuecomment-572677710. I like the simplifcation though, but want to bring up this additional data point.

**Comment by JoostK** [comment]
> Nice cleanup! One thing just to note: Back then we thought `Object.assign` support for partiual evaluation might be useful regardless. See: [#34661 (comment)](https://github.com/angular/angular/pull/34661#issuecomment-572677710). I like the simplifcation though, but want to bring up this additional data point.

I was surprised my myself to find that `Object.assign` was only supported through ngcc. It's quite easy to make it work from ngtsc, but it would probably be done similarly to how `String.prototype.concat` is supported vs how it used to be implemented via `KnownDeclaration`, so removing that (for now) seems beneficial still.

**Comment by devversion** [comment]
@JoostK Ah, looks like we never "detected" `Object.assign` in the normal reflection host.

>It's quite easy to make it work from ngtsc, but it would probably be done similarly to how String.prototype.concat is supported vs how it used to be implemented via KnownDeclaration, so removing that (for now) seems beneficial still.

Yeah, I don't think it's strictly needed, especially if we haven't supported it for such a long time in ngtsc directly.

**Comment by alxhub** [comment]
> @JoostK Ah, looks like we never "detected" `Object.assign` in the normal reflection host.
> 
> > It's quite easy to make it work from ngtsc, but it would probably be done similarly to how String.prototype.concat is supported vs how it used to be implemented via KnownDeclaration, so removing that (for now) seems beneficial still.
> 
> Yeah, I don't think it's strictly needed, especially if we haven't supported it for such a long time in ngtsc directly.

And we actively don't want to encourage people to rely on our static analysis too heavily for metadata.

**Review by alxhub — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
@JoostK oh, looks like this PR somehow slipped through the cracks and didn't get merged... Looks like it needs a rebase now.

@alxhub is there is more work need on this PR or is it good to go?

**Review by alxhub — APPROVED** [review]
Caretaker: g3 failure is unrelated

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 6ca1a53a1941fdf59a62e31fce3d20c709f27b7f.

**Pull request closed without merging**
