### PR TITLE
fix(forms): At DOM update, remove FormControl from FormGroup if needed

### PR DESCRIPTION
**Pull request by H--o-l**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

## PR Type

- [x] Bugfix

## What is the current behavior?

Inside my application, since Angular 11.2.6, I have the following issue on one of the form:
1. Remove FormGroup B from inside a FormGroup A
2. Re-Add the same FormGroup B inside the FormGroup A
3. Repeat `1.` and `2.` 
4. Use `FormGroup.reset(..)` to set FormGroup B values
5. FormControl inside FormGroup B are empty inside the DOM
6. If I click inside one of FormGroup B FormControl, then I click outside, I get the following error:
    `There is no FormControl instance attached to form control element with path: 'individual -> first'` 

The code look like that:
```ts
export class AppComponent {
  form: FormGroup;
  subform: FormGroup;
  constructor() {
    this.subform = new FormGroup({titi: new FormControl('')});
    this.form = new FormGroup({});
    this.subform.reset({titi: "Hello 1"});
    this.form.addControl('subform', this.subform);
    this.form.removeControl('subform');
    this.subform.reset({titi: "Hello 2"});
    this.form.addControl('subform', this.subform);
    this.form.removeControl('subform');
    this.subform.reset({titi: "Hello 3"});
    this.form.addControl('subform', this.subform);
  }
}
```
But I have to be clear: I wasn't able to reproduce it in a new project or Plunkr, only inside my app, so there is something more going on that I haven't find.

## What is the new behavior?

FormControl inside FormGroup B have correct values (set by `FormGroup.reset(..)`)

## Does this PR introduce a breaking change?

I don't think so.

## Other information

I have found that the issue started with the following commit:
https://github.com/angular/angular/commit/60ac9643334b83b6b720afd1b7d7fadf02c4e7fc

I don't think my PR should be merged like that, I'm just sharing my finding, in case someone can help me, or in case someone has the same issue.

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
Hi @H--o-l, thanks for reporting the issue and proposing a fix.

Could you please try to create a demo using https://stackblitz.com and see if you can reproduce the issue there? You can update dependencies to the latest ones (11.2.6) using their UI (see the icon in the top right corner of the "DEPENDENCIES" section in the left panel) and test your scenario there. Please let us know the results.

We'll keep the PR open for now and once there is a repro, we can help with further debugging and the necessary fixes to the Forms code.

Thank you.

**Comment by H--o-l** [comment]
Hi @AndrewKushnir !
I try to reproduce the issue, directly from a newly create project with Angular, and the correct Angular version. I wasn't able to reproduce.

Inside my app there is more operations on the form, which is big. I think I will have a hard time reproducing it accurately. 
My hope is that there is other Angular users out here that will share the same finding, or someone which know this code deeply and can find a working reproduction from this commit.

**Comment by AndrewKushnir** [comment]
@H--o-l ok, thanks for the comment. I think it'd still be helpful to have a Stackblitz demo app that would mimic the structure that you have in the app (even if it'd not reproduce the issue), so that I can see if there is a potential for the mentioned error to happen under some circumstances.

In general, resetting the `control` property as you proposed can be done, but it seemed unnecessary while I worked on PR #40829, since the `control` property is only set on the `FormControl` instances and the actual destroy happens in a different place. It'd be great if we could come up with a scenario that can be used as a test, so we can check what the right fix should be.

Thank you.

**Comment by AndrewKushnir** [comment]
Also as a part of the process of debugging this issue, could you please add a debugger statement (or a breakpoint in a browsers) into this function and share the stack trace?

https://github.com/angular/angular/blob/655507012b7b59c83e27429349ce3ac10608a82d/packages/forms/src/directives/shared.ts#L282-L284

**Comment by H--o-l** [comment]
Hi @AndrewKushnir! Here is the stack trace I have:
```
Error: There is no FormControl instance attached to form control element with path: 'individual -> first'
    at _throwError (shared.ts:295)
    at _noControlError (shared.ts:283)
    at DefaultValueAccessor.noop (shared.ts:68)
    at DefaultValueAccessor_blur_HostBindingHandler (default_value_accessor.ts:86)
    at executeListenerWithErrorHandling (core.js:15204)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:15239)
    at HTMLInputElement.<anonymous> (dom_renderer.ts:66)
    at HTMLInputElement.wrapped (raven.js:376)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:28497)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask [as invoke] (zone.js:503)
    at invokeTask (zone.js:1671)
    at HTMLInputElement.globalZoneAwareCallback (zone.js:1697)
```

And here is a Stackblitz, as close as possible as what my application does (without recoding it entirely, I omitted a big part of the DOM).
Sadly the Stackblitz still doesn't reproduce the issue.
https://stackblitz.com/edit/angular-ivy-rqzfyx?file=src/app/app.component.ts

**Comment by AndrewKushnir** [comment]
Hi @H--o-l, thanks for sharing the stack trace. It looks like the `blur` event happens on an element which has a directive, for which the [cleanUpControl function](https://github.com/angular/angular/blob/master/packages/forms/src/directives/shared.ts#L77-L80) was called. I think the next step would be to put a debugger statement there (inside the `cleanUpControl` function) and for a given control (at `individual -> first` path) check where the call is coming from (stack trace). Could you please try debugging it further and share a stack trace? Thank you.

**Comment by AndrewKushnir** [comment]
Hi @H--o-l, I'm going to close this PR for now (since we can not move forward without additional information). If there is new information available, please create a ticket in the "Issues" section of the repository and refer to this PR. We'll perform further investigation and reopen this PR if needed. Thank you.

**Pull request closed without merging**
