### PR TITLE
WIP fix(forms): email validator should be usable on optional fields

### PR DESCRIPTION
**Pull request by divdavem**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

Validation with an email validator will fail if the field is left empty. It is not possible to use it on an optional email field.

**What is the new behavior?**

An empty email field will successfully pass the validation done by the email validator.

**Does this PR introduce a breaking change?** (check one with "x")
```
[x] Yes
[ ] No
```

**If this PR contains a breaking change, please describe the impact and migration path for existing applications:**

For email fields which are supposed to be mandatory, the required validator should be added in addition to the email validator.

**Other information**:

I am opening this PR to add consistency with other validators (minLength, pattern) which do a similar call to `isEmptyInputValue` before doing their own check so that it is possible to use them on optional fields.

### CODE REVIEW

**Comment by Toxicable** [comment]
Looks like you might need to change the integration tests.
Also if you don't mind using a WIP flag while working on the PR that would be awesome

**Comment by emreavsar** [comment]
please merge this PR

**Comment by pablo-martinez** [comment]
It's been 7 months since this pull request was opened.. It would be nice to have it.

**Comment by kara** [comment]
Given that tests are not passing, going with another fix PR with passing tests https://github.com/angular/angular/pull/20869

**Pull request closed without merging**
