### PR TITLE
docs(docs-infra): typo fix in aot-metadata-errors

### PR DESCRIPTION
**Pull request by architect254**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by architect254** [comment]
my first comment in my first open source contribution

**Comment by architect254** [comment]
made a change to a previous typo

**Review by AndrewKushnir — APPROVED** [review]
@architect254 thanks for improving Angular docs!

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 36c5a57a3c411ba4f4780b9022f44db67f11f82e.

**Pull request closed without merging**
