### PR TITLE
fix(platform-browser-dynamic): Rename CACHED_TEMPLATE_PROVIDER to RESOURCE_CACHE_PROVIDER

### LINKED ISSUE #9741: rename CACHE_TEMPLATE_PROVIDER
Final name TBD, maybe something like CACHED_RESOURCE_PROVIDERS

### PR DESCRIPTION
**Pull request by hansl**
See #10197.

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**Does this PR introduce a breaking change?** (check one with "x")

```
[X] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

Rename CACHED_TEMPLATE_PROVIDER to RESOURCE_CACHE_PROVIDER

**Other information**:

Also renamed XHR (and MockXHR, CachedXHR, ...) to `ResourceLoader`, as per [this comment](https://github.com/angular/angular/pull/10197#issuecomment-239889597).

Closes #9741

BREAKING CHANGE:

`CACHED_TEMPLATE_PROVIDER` is now renamed to `RESOURCE_CACHE_PROVIDER`

Before:

``` js
import {CACHED_TEMPLATE_PROVIDER} from '@angular/platform-browser-dynamic';
```

After:

``` js
import {RESOURCE_CACHE_PROVIDER} from '@angular/platform-browser-dynamic';
```

### CODE REVIEW

**Comment by hansl** [comment]
Adding A2 Blocking as this was on the original PR (#10197).

**Comment by IgorMinar** [comment]
@hansl holly cow! that's a big PR. thanks for finish this.

**Comment by matsko** [comment]
@hansl make sure the commit messages are formatted properly.

**Comment by hansl** [comment]
@matsko We're using a squash strategy AFAIK, so only the first commit needs to be formatted properly.

**Pull request merged**
