### PR TITLE
aio: withConfig replaced with withOptions for HttpClientXsrfModule

### PR DESCRIPTION
**Pull request by mmrath**
withConfig replaced with withOptions

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Doc change only

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by trotyl** [comment]
Duplicate of #18589

**Review by gkalpak — APPROVED** [review]
That's the problem with hard-coding the code snippets instead of extracting them from an actual app 😞

**Comment by gkalpak** [comment]
Thx for catching this, @mmrath 👍
Can you please change the commit message to follow [our guidelines][1]? E.g. something like:

> docs(aio): replace `HttpClientXsrfModule.withConfig` with `withOptions`

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by brandonroberts** [comment]
Thanks for the PR @mmrath! This change has already landed in master, but if you see something else, open a new PR.

**Pull request closed without merging**
