### PR TITLE
docs: fix broken link

### PR DESCRIPTION
**Pull request by shaharkazaz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

- There is a broken link in the [entry components guide page](https://angular.io/guide/entry-components#the-entrycomponents-array), the link to deprecations guide appears as the raw text (`[deprecations guide](guide/deprecations#entryComponents)`).
- `{@ ngc}` appears above the [ngc section](https://angular.io/guide/entry-components#the-entrycomponents-array) in the glossary.

Issue Number: N/A

## What is the new behavior?
Fixed the above issues.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Review by gkalpak — APPROVED** [review]
Thx, @shaharkazaz :+1:

Can you please update the commit message to not include `docs-infra`, i.e.: `docs: fix ...`.
(`docs-infra` is for the infrastructure/tooling used to generate and display docs.)

Reviewed-for: global-docs-approvers

**Comment by shaharkazaz** [comment]
@gkalpak done 🙂

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Review by atscott — APPROVED** [review]
Reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by shaharkazaz** [comment]
@atscott May I ask why wasn't this merged?

**Comment by petebacondarwin** [comment]
It was merged. See the "atscott closed this in aee2d3f" comment above. We use a separate tool to squash and rebase PRs, rather than the GH  merge button. So it does not look like they are merged in the UI

**Comment by shaharkazaz** [comment]
@petebacondarwin yes I should have clarified my question to "why it seems like it does not merge" 🙂  thanks for the clarification.

**Pull request closed without merging**
