### PR TITLE
docs(aio): remove warning when testing in the webpack guide

### PR DESCRIPTION
**Pull request by Foxandxss**

### CODE REVIEW

**Comment by petebacondarwin** [comment]
I don't know much about webpack. Can you walk me through this change a bit?

**Comment by Foxandxss** [comment]
Yes, it is a workaround for https://github.com/angular/angular/issues/11580

**Comment by petebacondarwin** [comment]
Yes, I understand that much :-)
What I wanted you to describe is how this obscure change to a pattern solves that problem.

**Comment by Foxandxss** [comment]
Previously on angular v2 you needed the former pattern to avoid the warnings but due a change on Angular v4, you need that new pattern. They will be gone when #11580 is fixed.

**Comment by petebacondarwin** [comment]
I'm going to talk your word for it :-)

**Review by petebacondarwin — APPROVED** [review]

**Pull request merged**
