### PR TITLE
remove unused npm dependencies + update some

### PR DESCRIPTION
**Pull request by IgorMinar**
read commit messages for more info

### CODE REVIEW

**Comment by IgorMinar** [comment]
@alexeagle hmm.. clang-format is failing on travis, but passes locally. both places uses 1.0.32. Have you seen this before?

**Comment by alexeagle** [comment]
Yes, someone on Slack ran into it in last couple days. Martin just recently released a new clang-format version, so you probably don't have it locally. I suspect blasting node_modules will fix it.

**Comment by alexeagle** [comment]
published gulp-clang-format@1.0.23 including your fix

**Comment by IgorMinar** [comment]
@alexeagle thanks!

**Comment by IgorMinar** [comment]
OMG, green build! BOOYAH!!!

**Pull request closed without merging**
