### PR TITLE
Changelog

### PR DESCRIPTION
**Pull request by stevemao**
~~**WIP**~~

Because in 0.0.x there was no cli, we needed a wrapper. But now since we now have cli and gulp wrapper, and because we are already using gulp, we can just use the gulp wrapper.
I'm not sure how to regenerate the npm-shrinkwrap.json. In fact I can't even get `npm install` working (I can't find any docs) so please help. 

Also please check if you like the regenerated CHANGELOG. I have tweaked the format a little bit. (the biggest change is the title. There is no `<a>` and the version is a clickable link to a compare view) Once you are happy I'll have to push a new release. Thanks.

### CODE REVIEW

**Comment by stevemao** [comment]
Quick link to the newly generated changelog: https://github.com/stevemao/angular/blob/changelog/CHANGELOG.md

**Comment by stevemao** [comment]
Please comment if the current changes look good. Thanks.

**Comment by IgorMinar** [comment]
Hi there, I have no background on any past conversation about this change. Have there been any? Who was the point of contact?

My comments (without having any background info):

1/ The switch to gulp-conventional-changelog is nice, but not really a huge improvement.

2/ I'm not too keen on the introduction of conventional-github-releaser. It requires github tokens to be setup for each user doing the release and in the end creates a github release that is not very useful for the end user (since the tarball and zip files contain source codes and not build artifacts). The differences in the generated changelog seem superficial.

Am I missing anything? Can you explain the motivation behind this change?

**Comment by stevemao** [comment]
Hi @IgorMinar , there is pretty much no one who has the background after I rewrote the module. I tried to ping the original authors from your team but everyones busy with angular2. 

> 1/

This is not supposed to be an improvement. Because you have a wrapper in your project and this is because the old version doesn't have a properly wrapper (such as cli). If I were to change your wrapper, I would end up writing the same thing again. 

> 2/

I understand.

I will have to keep maintaining `conventional-changelog` module as it's not an easy task. I've been closing issues in the past few months. It would be great if you guys could provide some input on it (as you guys are the original authors). Currently I'm not sure how you like the new templates. Thanks.

**Comment by stevemao** [comment]
I have updated the PR, please review

**Comment by tbosch** [comment]
Closing this for now as we are cleaning up the PR queue. Sorry that we didn't have time to work with you on this...

**Comment by IgorMinar** [comment]
@tbosch we'll get to this, it's just not a priority for now. can we keep the PR open?

**Comment by stevemao** [comment]
I have published a newer release with more bugs fixed.

**Comment by mhevery** [comment]
@IgorMinar any updates on this?

**Comment by stevemao** [comment]
Please work with me. This is not an extremely hard task. Thanks :)

**Comment by mhevery** [comment]
I am sorry @stevemao for such a long delay. We are always swamped with higher priority items. 

@IgorMinar Any reason why we should continue to have this open? Will close in the next few days unless, I get a strong argument why we should keep it around.

**Comment by IgorMinar** [comment]
@stevemao I'm sorry about the delay. 

I'm going to close this PR now because it's mostly obsolete. We are rebuilding are build infrastructure right now to catch up with all the repackaging changes we made recently. As a result of that we are considering moving away from gulp in the long term (even if we keep it for the immediate future).

Because of this and the fact that a good chunk of the change long has been hand-tweaked after it was generated it doesn't make sense to merge this PR as is.

I'm open to moving over to the standard CLI, so if you'd like to work on a PR for that, we'd merge it quickly.

to install npm make sure you have the right version of npm and node (listed under scripts/ci-lite/env.sh). to reshrinkwrap please use `./tools/npm/reshrinkwrap` command (see npm-shrinkwrap.readme.md for more instructions).

**Pull request closed without merging**
