### PR TITLE
refactor(router): Remove code to support relativeLinkResolution

### PR DESCRIPTION
**Pull request by atscott**
The public API for enabling this option has already been removed. This change updates the internal Router code to not include any logic to support it.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
🎉

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 99898f33703e46b7fec81babe83701705519af9e.

**Pull request closed without merging**
