### PR TITLE
fix(dev-infra): fix typo in ng-dev.js

### PR DESCRIPTION
**Pull request by eltociear**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
targetting -> targeting

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by JoostK** [comment]
CI is red though as the generated bundle needs to be updated as well:

```
yarn bazel run //dev-infra:ng-dev.update
```

**Comment by devversion** [comment]
The actual fix for CI is to update the sources. The PR currently just updates the generated bundle of `/dev-infra`.

This file needs to be updated too: https://github.com/angular/angular/blob/master/dev-infra/pr/check-target-branches/check-target-branches.ts#L33

**Comment by eltociear** [comment]
I tried this.
```sh
yarn bazel run //dev-infra:ng-dev.update
```

returned below.
```sh
ERROR: An error occurred during the fetch of repository 'npm':
```

Is there anything else I can do?

**Comment by gkalpak** [comment]
@eltociear, the error you describe sounds like a temporary network issue. Can you try again.
Also, (not sure if you have done it locally) make sure to first make the change in the [source file][1] (as mentioned in https://github.com/angular/angular/pull/42004#issuecomment-835875037) and _then_ run `yarn bazel run //dev-infra:ng-dev.update`.

[1]: https://github.com/angular/angular/blob/9bf8e5164d82ae5050c2cff28ccdbb71709952f7/dev-infra/pr/check-target-branches/check-target-branches.ts#L33

**Comment by AndrewKushnir** [comment]
@eltociear I'm closing this PR for now since it needs more changes according to https://github.com/angular/angular/pull/42004#issuecomment-835875037. Please reopen when you get a chance to look at it again. Thank you.

**Pull request closed without merging**
