### PR TITLE
style: align tslint with editorconfig for eof newline

### PR DESCRIPTION
**Pull request by alfaproject**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Other... Please describe:
```

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by alfaproject** [comment]
Sorry for the styling PRs, but I think it makes sense to have these things automatically checked and forced on all of us. ^_^

**Comment by vicb** [comment]
I think it would be overkill that lint enforces that (which could make the CI red and me angry at it) ?

**Comment by alfaproject** [comment]
Why would it make the CI red? Every editor has plugins for `.editorconfig`, and the rule is set there. I'd say it's just good etiquette. d:

**Comment by vicb** [comment]
> Every editor has plugins for .editorconfig

If devs were using that, this PR would not update 57 files !

I'm :-1: on this, will discuss with the team next week

**Comment by alfaproject** [comment]
Yes, that's even better. ^_^

**Pull request closed without merging**
