### PR TITLE
docs: fix typo in Pipes guide (aynchronous --> asynchronous)

### PR DESCRIPTION
**Pull request by aamanunin**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A
Fix grammatic error in pipes.md

## What is the new behavior?
No grammatic error in pepes.md

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by aamanunin** [comment]
@googlebot I signed it!

**Comment by aamanunin** [comment]
@googlebot I signed it

**Comment by aamanunin** [comment]
@googlebot I fixed it.

**Comment by aamanunin** [comment]
@googlebot I fixed it.

**Comment by aamanunin** [comment]
@googlebot I signed it!

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx, @aamanunin :+1:

Can you please update the commit message to more closely follow our [commit message guidelines](https://github.com/angular/angular/blob/1d9e56eba06958e37ef8062ae7b65afa85f90632/CONTRIBUTING.md#commit). (That would also make CI happy.)

For example:

> docs: fix typo in Pipes guide (aynchronous --> asynchronous)

**Pull request closed without merging**
