### PR TITLE
ci: add owners for zone.js to CODEOWNERS

### PR DESCRIPTION
**Pull request by gkalpak**
Follow-up to #30962.

### CODE REVIEW

**Comment by gkalpak** [comment]
This is blocked on creating the `@angular/zone.js` team on GitHub.

**Comment by gkalpak** [comment]
I have created the [fw-zones][1] team (but it is pending approval to be moved under [framework][2]).
I believe this PR is unblocked.

[1]: https://github.com/orgs/angular/teams/fw-zones
[2]: https://github.com/orgs/angular/teams/framework

**Comment by JiaLiPassion** [comment]
@gkalpak, thanks!

**Review by IgorMinar — APPROVED** [review]
thanks

**Pull request closed without merging**
