### PR TITLE
docs(core): showcase host listener support for specific keys in events

### PR DESCRIPTION
**Pull request by macjohnny**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

See this example: https://stackblitz.com/edit/angular-ivy-u23hez?file=src/app/app.component.ts

### CODE REVIEW

**Comment by macjohnny** [comment]
maybe we could add event more information about the keys supported. is there a pointer to the implementation?

**Comment by macjohnny** [comment]
moreover, some information could be added to https://angular.io/guide/binding-syntax and https://angular.io/guide/event-binding-concepts, since `<input (keydown.enter)="someHandler()" />` works as well

**Comment by macjohnny** [comment]
see also https://github.com/angular/angular/blob/master/packages/platform-browser/src/dom/events/key_events.ts#L23

**Review by AndrewKushnir — APPROVED** [review]
@macjohnny thanks for improving Angular docs 👍

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit f0d572eebfaae15462a0a4449b5198b481a27126.

**Pull request closed without merging**
