### PR TITLE
refactor(zone.js): change from scripts to modules

### PR DESCRIPTION
**Pull request by frigus02**
## PR Type

- [x] Refactoring (no functional changes, no api changes)

## What is the current behavior?

Some Zone.js TypeScript files are scripts, which means all type declarations are added to the global scope.

## What is the new behavior?

Make Zone.js compatible with moduleDetection:force by:

1. turning files that are currently incompatible from scripts into modules using an empty export statement
2. moving type definitions into a `declare global {}` block to make them explicitly global. If some of the types don't actually need to be global, they can be moved out of the global block one by one in follow-up PRs.

## Does this PR introduce a breaking change?

- [x] No

## Additional information

<details>
<summary<The following script checks with files are currently still scripts:</summary>

```
> const ts = require('typescript')
> const fs = require('fs')
> tsFiles = fs.readdirSync('packages/zone.js', {recursive: true}).filter(f => f.endsWith('.ts') && !f.endsWith('.d.ts')).map(f => `packages/zone.js/${f}`)
> tsFiles.filter(f => !ts.isExternalModule(ts.createSourceFile(f, fs.readFileSync(f, 'utf8'), ts.ScriptTarget.ESNext)))
[
  'packages/zone.js/test/browser_disable_wrap_uncaught_promise_rejection_setup.ts',
  'packages/zone.js/test/browser_shadydom_setup.ts',
  'packages/zone.js/test/browser_symbol_setup.ts',
  'packages/zone.js/test/main.ts',
  'packages/zone.js/test/node-env-setup.ts',
  'packages/zone.js/test/node_error_disable_policy.ts',
  'packages/zone.js/test/node_error_lazy_policy.ts',
  'packages/zone.js/test/test-env-setup-jasmine.ts',
  'packages/zone.js/test/test_fake_polyfill.ts',
  'packages/zone.js/test/ws-webworker-context.ts',
  'packages/zone.js/test/wtf_mock.ts',
  'packages/zone.js/test/zone_worker_entry_point.ts',
  'packages/zone.js/lib/browser/canvas.ts',
  'packages/zone.js/lib/browser/message-port.ts',
  'packages/zone.js/lib/browser/shadydom.ts',
  'packages/zone.js/lib/browser/webapis-media-query.ts',
  'packages/zone.js/lib/browser/webapis-notification.ts',
  'packages/zone.js/lib/browser/webapis-resize-observer.ts',
  'packages/zone.js/lib/browser/webapis-rtc-peer-connection.ts',
  'packages/zone.js/lib/browser/webapis-user-media.ts',
  'packages/zone.js/lib/common/fetch.ts',
  'packages/zone.js/lib/extra/bluebird.ts',
  'packages/zone.js/lib/extra/cordova.ts',
  'packages/zone.js/lib/extra/electron.ts',
  'packages/zone.js/lib/extra/jsonp.ts',
  'packages/zone.js/lib/extra/socket-io.ts',
  'packages/zone.js/lib/jasmine/jasmine.ts',
  'packages/zone.js/lib/jest/jest.ts',
  'packages/zone.js/lib/mocha/mocha.ts',
  'packages/zone.js/lib/testing/promise-testing.ts',
  'packages/zone.js/lib/zone-spec/async-test.ts',
  'packages/zone.js/lib/zone-spec/fake-async-test.ts',
  'packages/zone.js/lib/zone-spec/long-stack-trace.ts',
  'packages/zone.js/lib/zone-spec/proxy.ts',
  'packages/zone.js/lib/zone-spec/sync-test.ts',
  'packages/zone.js/lib/zone-spec/task-tracking.ts',
  'packages/zone.js/lib/zone-spec/wtf.ts',
  'packages/zone.js/test/browser/define-property.spec.ts',
  'packages/zone.js/test/browser/messageport.spec.ts',
  'packages/zone.js/test/browser/registerElement.spec.ts',
  'packages/zone.js/test/browser/requestAnimationFrame.spec.ts',
  'packages/zone.js/test/browser/shadydom.spec.ts',
  'packages/zone.js/test/common/microtasks.spec.ts',
  'packages/zone.js/test/common/promise-disable-wrap-uncaught-promise-rejection.spec.ts',
  'packages/zone.js/test/common/task.spec.ts',
  'packages/zone.js/test/extra/bluebird.spec.ts',
  'packages/zone.js/test/extra/cordova.spec.ts',
  'packages/zone.js/test/node/Error.spec.ts',
  'packages/zone.js/test/node/console.spec.ts',
  'packages/zone.js/test/node/crypto.spec.ts',
  'packages/zone.js/test/zone-spec/proxy.spec.ts',
  'packages/zone.js/test/zone-spec/clock-tests/enable-clock-patch.ts',
  'packages/zone.js/test/zone-spec/clock-tests/fake-async-patched-clock.spec.ts',
  'packages/zone.js/test/zone-spec/clock-tests/fake-async-unpatched-clock.spec.ts'
]
```

</details>

They all seem to be compatible with being modules, though. I didn't see any more errors when turning on `moduleDetection:force`.

### CODE REVIEW

**Review by dgp1130 — COMMENTED** [review]
Seems reasonable to me, but I suspect we won't know how viable this is until we actually try it. GitHub tests don't show any issues. I'm looking into run TAP for the change, seems like the patch is breaking the syncing process because it doesn't work this PR. Might also be worth running a full TGP for this just to make sure we aren't changing any global types which might break some downstream code.

Definitely would appreciate a look from @JiaLiPassion and @devversion to make sure there's no weird nuances I'm not aware of.

**Comment by dgp1130** [comment]
CARETAKER NOTE: Syncing this will fail due to it breaking an existing Zone.js g3 patch. cl/589243232 fixes the patch to be compatible with this PR.

**Review by devversion — APPROVED** [review]

**Comment by dgp1130** [comment]
I think I've ironed out all the blockers and [TGP seems to be green](http://test/OCL:590759242:BASE:596036912:1704481412359:2cf922d4), so I think we're ready to merge this. I'll follow up next week to coordinate and see if we can land this safely.

**Review by JiaLiPassion — APPROVED** [review]
LGTM! Thanks!

**Comment by atscott** [comment]
This PR was merged into the repository by commit acf1793d7b1da2a899ae6b1e753c6f8aa2667b4e.

**Pull request closed without merging**
