### PR TITLE
chore(lint): enforce no var keyword

### PR DESCRIPTION
**Pull request by alfaproject**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?**
`var` keyword is being used everywhere.

**What is the new behavior?**
No more `var`s unless explicitly needed.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

**Other information**:
I automated the process of converting the existing`var`s to `let`s and `const`s, and did some minor changes for false positives.

I realise that this PR is too big, but I didn't have any good idea of how to split it without actually enforcing the TSLint rule. If we are really interested in getting rid of `var`s, but prefer smaller PRs, maybe we can do this per module instead.

### CODE REVIEW

**Comment by vicb** [comment]
Thanks, that's something I wanted so badly instead of adding let/const in all my PR reviews !

Could you please update the PR as follow:
- 1 refactor commit with all the updates,
- 1 chore commit flipping the switch.

I'll merge as the PR is updated - it will make me SO happy !

**Comment by alfaproject** [comment]
@vicb done. (:

**Comment by vicb** [comment]
I'll merge when the CI gets green.

Thanks you !!

**Comment by vicb** [comment]
IT'S IN 
`var` 🔫

**Pull request merged**
