### PR TITLE
fix(EventEmitter): resolve onError and onComplete asynchronously

### PR DESCRIPTION
**Pull request by NathanWalker**
https://github.com/angular/angular/issues/4443

### CODE REVIEW

**Comment by robwormald** [comment]
@NathanWalker watch for #4893 as it will definitely impact this. the (annoyingly ugly) change will be that EventEmitter.subscribe() takes either `.subscribe(nextFn, errorFn, completeFn) ` or `.subscribe(observerObj)` where observerObj is ` { next(), error(), complete() }`

**Comment by NathanWalker** [comment]
@robwormald thanks for heads up :+1:

**Comment by robwormald** [comment]
while you're at it, i just found a nasty little hiccup, maybe have a look as you're in the guts of this right now:
``` js
//create a subject
var s = new Subject();

//subscribe to it via the ObservableWrapper, passing only a next fn
ObservableWrapper.subscribe(s, (val) => {});

//call next
s.next(1);
//call complete (throws!)
s.complete();

```

**Comment by NathanWalker** [comment]
I believe I have a solution for that @robwormald ... squashing and pushing again shortly.

**Comment by NathanWalker** [comment]
How about this:
https://github.com/NathanWalker/angular/commit/03209309a805e4f04f32c62d8d21972fd87642a9

**Comment by NathanWalker** [comment]
This should solve your issue above as well @robwormald. Have a look and let me know.

/cc @vsavkin

**Comment by NathanWalker** [comment]
As far as I can tell, `async.ts` does not have any unit tests. I could add some for this unless I'm missing something?

**Comment by robwormald** [comment]
specs are here https://github.com/angular/angular/blob/master/modules/angular2/test/core/facade/async_spec.ts

I have one locally that looks like that throws - this replicates what I mentioned above.
```js

it('should subscribe to Subjects', () => {
  let subject = new Subject();

  ObservableWrapper.subscribe(subject, (val) => {});

  subject.next(1);
  subject.complete();

})

```

**Comment by NathanWalker** [comment]
Ah ok. Lemme try that on my branch here.

**Comment by NathanWalker** [comment]
I have a fix coming (verified in isolation). Running locally all build/tests and will push the squashed commit shortly.

**Comment by NathanWalker** [comment]
I used the same approach the RxJS team did here:
https://github.com/ReactiveX/RxJS/blob/master/src/Subscriber.ts#L38

Also the unit test now includes yours with an expansion to verify different signatures would still work.

I'm just now seeing your comment... lemme see...

**Comment by robwormald** [comment]
otherwise tho, LGTM

**Comment by NathanWalker** [comment]
Good point. I updated the unit tests so it didn't look confusing. Not sure if there's anything we should do to prevent `.complete` from firing if `.error` had been called?  Probably best to rely on RxJS's underlying implementation for that? Thanks for the help and feedback :+1:

**Comment by robwormald** [comment]
Hmm, dart not loving that (the TS specs get xpiled to dart and executed as well) - might try calling using the wrapper there: 
```js
ObservableWrapper.callNext(e, 1);
```
etc

**Comment by NathanWalker** [comment]
Thanks I'll try that shortly.

**Comment by jeffbcross** [comment]
@NathanWalker can you add "closes #4443" in your commit message?

Also, could you shorten the title to "fix(EventEmitter): resolve onError and onComplete asynchronously"

This should also be noted as a breaking change, so a `BREAKING CHANGE:` section should be added to the body, explaining the previous behavior and new behavior.

**Comment by jeffbcross** [comment]
Meh, nm about breaking change.

**Comment by NathanWalker** [comment]
Thanks @jeffbcross @robwormald that should clear things up :+1:

**Comment by NathanWalker** [comment]
Well poop. Ok I'll look at that failure, I think it's dart issue with ObservableWrapper.

**Comment by NathanWalker** [comment]
Everything seems to pass except this one error. I've tried several things but to no avail. 
I need help with this dart error :(
```
Chrome 39.0.2171 (Linux 0.0.0) ObservableWrapper should subscribe to EventEmitters FAILED
	Caught 0
	null
```

**Comment by NathanWalker** [comment]
I added unit tests for async onError and onComplete and have everything passing now.
Should be clear now @robwormald

**Comment by robwormald** [comment]
@NathanWalker awesome. once https://github.com/angular/angular/pull/5302 lands, rebase and we should be good to go.

**Comment by NathanWalker** [comment]
5302 came, it saw, and landed; then this just dropped the re**bass**! take it away @robwormald :shipit:

**Comment by robwormald** [comment]
LGTM. failing test is dartdoc known issue.

**Comment by vsavkin** [comment]
Merged via https://github.com/angular/angular/commit/019cb41dd8f96ecdc801226bca8a1e4cbc1570a8

**Pull request closed without merging**
