### PR TITLE
Add missing metadata property in ViewChild examples

### PR DESCRIPTION
**Pull request by aldo94vp**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by aldo94vp** [comment]
@googlebot  I signed it!

**Review by mhevery — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Hi @aldo94vp, could you please rebase your PR and also squash commits into a single one? Please let us know (in this thread) when it's done, so we can proceed with merging your PR. Thank you.

**Comment by aldo94vp** [comment]
done, could you check it please?

**Comment by AndrewKushnir** [comment]
@aldo94vp, it looks like your PR now contains excessive/unrelated commits (3102 commits total), so probably rebase didn't complete correctly. I can try to rebase your PR, but I think it might be easier to re-create this PR from scratch. What do you think?

Also, I have a couple questions:
- could you please mention in the commit message why adding the `{ static: false }` is necessary
- is the `TODO` comment in the code required?

Thank you.

**Pull request closed without merging**
