### PR TITLE
fix(ngFor): update view values manually with track by

### LINKED ISSUE #6907: [ngFor] trackBy behaviour
Something surprised me as I was giving a try to the new `trackBy` feature.

In the following example, an array of users is generated every second with two users (always the same names) and a random score for each one.
The `ngFor` is used to display the list of user with their score.
`trackBy` can be useful here to track the user by their name rather than by their reference (which changes every second).

But if we do this in Angular 2 beta.3, the score is never updated.
Is it on purpose? AFAIK, in AngularJS 1.x, that was not the case (the score would be updated even if the `ngRepeat` was using a `trackBy`).

```typescript
@Component({
  template: `<div *ngFor="#user of users trackBy userByName">{{user.name}} -> {{user.score}}</div>`
})
class TestCmp {
  users: any;
  constructor() {
    window.setInterval(() => this.users = [
      {name: 'user1', score: Math.random()},
      {name: 'user2', score: Math.random()}], 
   1000);
  }

  userByName(index, user) {
    return user.name;
  }
}
```

cc @kara @mhevery

### PR DESCRIPTION
**Pull request by kara**
@vsavkin @mhevery Review?

Closes #6907

### CODE REVIEW

**Comment by mhevery** [comment]
Reviewed with Kara in person, will keep track of identity changes as a separate list.

**Comment by mhevery** [comment]
Very nice! LGTM

**Comment by jeffbcross** [comment]
Assigning to @IgorMinar for merge

**Comment by btford** [comment]
:clap: good work everyone

**Comment by cexbrayat** [comment]
I assume this fixes #6907 ?

**Pull request closed without merging**
