### PR TITLE
refactor: migrate common to prettier formatting

### PR DESCRIPTION
**Pull request by josephperrott**
Migrate formatting to prettier for common from clang-format

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@josephperrott Looks like this can't be merged into `17.1.x`.

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
@josephperrott Looks like this now has file conflicts. Let me know when that's resolved, and I'll land these before anything else to prevent further conflicts.

**Review by jessicajaniuk — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
Caretaker: No need for additional reviews as this is just formatting changes.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 0460a9dfafe3a7ebbff1b87e52048fb7416bba43.

**Pull request closed without merging**
