### PR TITLE
docs: fix typo in reactive forms guide

### PR DESCRIPTION
**Pull request by ghost**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/angular/angular/issues/25542

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by jinbeomhong** [comment]
I signed it!

**Review by kara — APPROVED** [review]
LGTM

**Review by brandonroberts — APPROVED** [review]

**Comment by jinbeomhong** [comment]
@kara @brandonroberts 
Could i commit more to this PR for additional typo i've found?

**Comment by kara** [comment]
@jinbeomhong Since this is already approved, it's probably better to create a separate PR.

**Comment by kara** [comment]
@jasonaden This PR has the same `aio-preview` issue that I had on my other PR. Can you help us merge?

**Pull request closed without merging**
