### PR TITLE
fix(ivy): injecting optional TemplateRef on element should not throw

### PR DESCRIPTION
**Pull request by kara**
This PR adds support for optional TemplateRefs, which previously would throw.

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by kara** [comment]
[presubmit](http://test/OCL:218259028:BASE:218259098:1540252676992:14471215)

**Comment by kara** [comment]
merge assistance: webhooks not working -> no circle CI builds

**Comment by alxhub** [comment]
https://github.com/angular/angular/pull/26684 is running CircleCI for this PR.

**Comment by kara** [comment]
@alxhub Thanks for setting that up! #26684 should be green now.

**Pull request closed without merging**
