### PR TITLE
feat(aio): boilerplate:add cleans (removes) before adding

### PR DESCRIPTION
**Pull request by wardbell**
`yarn boilerplate:add` cleans the example folders (as in `yarn boilerplate:remove`) before adding the boilerplate files and symlinks.

Small tool change.

### CODE REVIEW

**Review by Foxandxss — COMMENTED** [review]
I am not going to lie. I prefer the add to just add. Perhaps we could just preprend the :remove on the `setup`

**Comment by wardbell** [comment]
@Foxandxss I understand. It should be one or the other: either add also removes or setup removes. I think it is safer if add also removes. Let's see what @petebacondarwin thinks.

**Comment by petebacondarwin** [comment]
@Foxandxss when would you run `add` without wanting a clean slate to start from?

Perhaps the concerns are due to the naming (of course!!)? If we renamed the `add-example-boilerplate` and `remove-example-boilerplate` to `setup-example-boilerplate` and `clean-example-boilerplate` (or similar) then perhaps it would not feel so bad if the `setup` started by running `clean`?

**Comment by petebacondarwin** [comment]
So to be clear I am agreeing with @wardbell  that `add` should also `remove` but that we perhaps need a name change too.

**Review by petebacondarwin — APPROVED** [review]

**Pull request merged**
