### PR TITLE
fix(errors): better error reporting when parsing template expressions

### LINKED ISSUE #2041: Undebuggable error: "class" is not a valid (qualified) symbol name
I have a Angular2.dart app, which is throwing the error below in dart2js mode (not Dartium) only.
I am using the "debug" version of the reflector: ```import 'package:angular2/src/reflection/debug_reflection_capabilities.dart' show ReflectionCapabilities;```

The error is unhelpful in isolating the issue. Obvious questions:

"who is requesting ```class```"? e.g. what element is the ```ElementBinderBuilder``` processing?

"what object is ```class``` being requested on"? From the context and my recent changes, I assume ```NgClass```, but I would love an affirmation.

```
[ReflectionCapabilities(INFO)]: "annotations" requested for "NgClass".
[ReflectionCapabilities(INFO)]: "factory" requested for "NgClass".
[ReflectionCapabilities(INFO)]: "parameters" requested for "NgClass".
[ReflectionCapabilities(INFO)]: "getter" requested for "levelClass".
[ReflectionCapabilities(INFO)]: "setter" requested for "levelClass".
[ReflectionCapabilities(INFO)]: "setter" requested for "class".
main.dart.js:3972 Uncaught Uncaught Error: Invalid argument(s): "class" is not a valid (qualified) symbol name
Stack Trace:
Invalid argument(s): "class" is not a valid (qualified) symbol name
    at dart.wrapException (http://localhost:8080/main.dart.js:3972:15)
    at dart.Symbol0.static.Symbol_validatePublicSymbol (http://localhost:8080/main.dart.js:25220:17)
    at ReflectionCapabilities.dart.ReflectionCapabilities0.setter$1 (http://localhost:8080/main.dart.js:89048:74)
    at ReflectionCapabilities.dart.ReflectionCapabilities.setter$1 (http://localhost:8080/main.dart.js:88929:19)
    at Reflector.dart.Reflector.setter$1 (http://localhost:8080/main.dart.js:19346:44)
    at dart.setterFactory (http://localhost:8080/main.dart.js:22727:71)
    at ElementBinderBuilder.dart.ElementBinderBuilder.bindProperty$2 (http://localhost:8080/main.dart.js:23064:9)
    at PropertyBindingParser.dart.PropertyBindingParser._bindPropertyAst$4 (http://localhost:8080/main.dart.js:20173:31)
    at PropertyBindingParser_process_closure.dart.PropertyBindingParser_process_closure.call$2 (http://localhost:8080/main.dart.js:20259:24)
    at MapWrapper_forEach_closure.dart.MapWrapper_forEach_closure.call$2 (http://localhost:8080/main.dart.js:86206:34)
```

### PR DESCRIPTION
**Pull request by yjbanov**
Fixes #2041

### CODE REVIEW

**Comment by vsavkin** [comment]
This is required only for transformers. My understanding was that @kegluneq was going to rewrite transformers not to rely on this hack. So it is LGTM, but it should be removed soon.

**Comment by yjbanov** [comment]
I agree, just want to close #2041

**Comment by kegluneq** [comment]
At this point we are running all steps of the render compiler in the transformer. @vsavkin , this is the hack you added while I was in MTV to get your refactor working?

Everything may now function without this hack -- I don't have enough background on it to be sure though.

**Comment by yjbanov** [comment]
Let me see how it does without it.

**Comment by yjbanov** [comment]
#2082 is a better fix. Closing this PR.

**Pull request closed without merging**
