### PR TITLE
build: fix and document the symlinks scripts for Windows

### PR DESCRIPTION
**Pull request by marclaval**
Some more fixes, some commands are still broken and will require more work:

```
./test.sh tools
./test.sh node
```

### CODE REVIEW

**Comment by vicb** [comment]
@mlaval it's not clear to me what this fixes and if the PR is a WIP or ready to go ?

**Comment by fknop** [comment]
@vicb I know that when I made a PR, the create / remove symlinks did not work due to the `\r` at the end of the package name. Looks like the `::-1` operator removes the last character but I could not make it work on my Git Bash.

@mlaval What terminal are you using ?

**Comment by mlaval** [comment]
I'm using a recent version of Git Bash (2.6.2) and this PR fixes the issue you described with the '\r'.
Sorry for not explaining when I opened the PR.

@vicb: there are more things to fix on the platform, but this one allows to at least run tests in a browser.

**Comment by vicb** [comment]
> I did some research, looks like it's only available for latest versions of bash.

Is it to merge still ?

**Comment by mlaval** [comment]
I've updated the PR with the findings of @fknop so that the scripts also work in older bash.

The commit message is now more explicit.

It should be ok to merge.

**Comment by vicb** [comment]
When it's been :)

**Comment by vicb** [comment]
Green... Stupid phone!

**Comment by mlaval** [comment]
It is now, the e2e job went flaky.

**Comment by vicb** [comment]
Lgtm. Can not merge from the mobile UI. Feel free to merge

**Pull request closed without merging**
