### PR TITLE
docs: add Angular Global Summit to event pages

### PR DESCRIPTION
**Pull request by IEvangelist**
Adding [Angular Global Summit](https://angular.geekle.us/) to event pages, per @mgechev

### CODE REVIEW

**Comment by mgechev** [comment]
We can move forward and merge the PR once you sign the CLA.

**Comment by IEvangelist** [comment]
> We can move forward and merge the PR once you sign the CLA.

Signed it, now what - when does it propagate through?

**Comment by IEvangelist** [comment]
@googlebot I signed it!

**Comment by AndrewKushnir** [comment]
@IEvangelist, thanks for signing the CLA.

Could you please update the commit message (`git commit --amend`) and start it with the `docs:` scope, so the message may look like this (I've also added the `Angular Global Summit` mention into the message):
```
docs: add Angular Global Summit to event pages
```

Thank you.

**Comment by IEvangelist** [comment]
> @IEvangelist, thanks for signing the CLA.
> 
> Could you please update the commit message (`git commit --amend`) and start it with the `docs:` scope, so the message may look like this (I've also added the `Angular Global Summit` mention into the message):
> 
> ```
> docs: add Angular Global Summit to event pages
> ```
> 
> Thank you.

@AndrewKushnir Done, thank you for the guidance here.

**Review by mgechev — APPROVED** [review]

**Pull request closed without merging**
