### PR TITLE
fix(ivy): Renderer2 should not use a special injection fn

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Like #26064 but for `Renderer2`

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
I've verified that it fixes `Renderer2` injection under `TestBed` with ivy enabled.

**Comment by pkozlowski-opensource** [comment]
Note: CI failrue is a flake, see https://github.com/angular/angular/pull/26366

**Review by kara — APPROVED** [review]
LGTM

**Comment by kara** [comment]
[presubmit](http://test/OCL:216545911:BASE:216545924:1539190215421:3ea4b971)

**Comment by pkozlowski-opensource** [comment]
I'm flagging this one with merge-assistance as the TravisCI is failing for reasons unrelated to this PR (see #26366).

**Pull request closed without merging**
