### PR TITLE
fix: export top-level pipe factories as const

### PR DESCRIPTION
**Pull request by kevmoo**
Also appComponent(Ref|Type)Token

Related to https://github.com/angular/angular/issues/1485

[Review on Reviewable](https://reviewable.io/reviews/angular/angular/2713)

### CODE REVIEW

**Comment by kevmoo** [comment]
@mprobst Look good?

CC @yjbanov

**Comment by mprobst** [comment]
Looks good to me from a ts2dart side, but I cannot really comment on the Angular code itself.

@kevmoo out of curiosity, does the `const`ness have much of an impact on code size *after* `dart2js`?

**Comment by kevmoo** [comment]
`const` makes sure there is only one copy of a class created. It also provides great hints to `dart2js` that an associated field is never changed. This can inference in many cases – smaller, faster code.

It's also a **GREAT** hint to users that a specific field cannot be mutated. You could imagine a big app and a user accidentally changing one of these top-level lists – could break a lot of other features.

**Comment by mhevery** [comment]
Reviewed 8 of 8 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/angular/angular/2713)

**Comment by kevmoo** [comment]
Rebasing – once travis is clean, will merge.

**Comment by kevmoo** [comment]
Landed as 393f703a976d20cbee871f296c65568fb43d0025

**Pull request closed without merging**
