### PR TITLE
fix(docs-infra): scrolling experience in API Reference

### PR DESCRIPTION
**Pull request by 9kubczas4**
Fix scrolling experience in API Reference:
- set correct margin top for members container (right side) which is aligned with tabs (left side)
- prevent scroll on focus
- remove redundant blur calls

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thx for looking into this !!

**Comment by atscott** [comment]
This PR was merged into the repository by commit 8a8181a54dc13ff591f5c6759740a4e44dc5f41e.

**Comment by atscott** [comment]
@9kubczas4 Thanks for the fix! This is so much better now.

There's some visual oddity with the card focus styling when you click on a card. The focus outline flips back and forth between the previously selected card and the new card, I think until the scroll position reaches a point where the outline will stay on the new card. But this doesn't affect the actual behavior of the scrolling so it's much less important.

**Comment by 9kubczas4** [comment]
@atscott I'll try to fix it as well in the separate PR. Thank you ;)

**Pull request closed without merging**
