### PR TITLE
feat(router): update routerLink DSL to handle aux routes

### LINKED ISSUE #9659: Issues with using colon as value in ng2 rc3
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

...
 {
    path: 'relationships/:idValue',
    component: RelationshipsComponent
  }
...

// I want to navigate to /relationships/ab:cd but ng2 navigates to /relationships/cd instead

this.router.navigate(['/relationships', 'ab:cd' ]); 

**Expected/desired behavior**

navigating to /relationships/ab:cd

**Reproduction of the problem**

if the route parameter value contains colon, the router doesn't correctly navigate as shown above.

**What is the expected behavior?**

correctly routing to /relationships/ab:cd

**What is the motivation / use case for changing the behavior?**

Bug

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X

2.0.0-rc3
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
I've tried only on Chrome 51

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 

TypeScript

### PR DESCRIPTION
**Pull request by vsavkin**
Closes #9659

### CODE REVIEW

**Comment by kara** [comment]
LGTM

**Comment by ghetolay** [comment]
So I'm now able to navigate using router with something like : 

```
this.router.navigateByUrl( 
    this.router.createUrlTree([{ outlets: { aux:  'auxRoute' }}], {relativeTo: this.activatedRoute} )
);
```

Is it possible to do the same using ```routerLink``` directive ?

**Comment by pleerock** [comment]
@ghetolay have found how to create routes to aux links? Im trying to achieve it using [routerLink], but looks like there is a bug

**Comment by ghetolay** [comment]
@pleerock Well I didn't but since you asked I took a look at [create_url_tree()](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/create_url_tree.ts) and found out you have to pass and object like : 

```
{
    outlets: {
        outletName1: "value",
        outletName2: "value"
        ...
    }
}
```

So for example : 

```
[routerLink]=['./', {outlets: { menu: 'menu1'  } } ]
```

According to the [validation function](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/create_url_tree.ts#L37) the outlets object must be the last command on the array.

@vsavkin would be good to add an example somewhere on the docs.

**Pull request merged**
