### PR TITLE
build: add mhevery to bazel approvers

### PR DESCRIPTION
**Pull request by mhevery**

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]

**Comment by alexeagle** [comment]
No offense, but are you sure? I'd like to review Bazel PRs unless there's a reason to go to a secondary like Chuck. Remember this includes changes to .bzl bazel plugin code, not just BUILD files

**Comment by IgorMinar** [comment]
@alexeagle now that we changed the pull approve rules to allow self approval with lgtm from anyone this change is no longer necessary.

Should we require bazel readability for someone to be in the bazel group? I know that I'm barely qualified.

**Comment by alexeagle** [comment]
The concern here is that BUILD file changes are often mechanical (like
adding a dep[]) and it's annoying to get a bazel reviewer for such a change.

**Comment by IgorMinar** [comment]
Can we separate `.bzl` reviews from `.bazel` approvals? they required very different skillset and have very different impact. (i.e. a component owner should be able to approve changes to their .bazel files, but only a few people should be able to approve .bzl files)

**Comment by alexeagle** [comment]
@IgorMinar done, PTAL

**Review by IgorMinar — APPROVED** [review]

**Pull request closed without merging**
