### PR TITLE
docs: add NG-DE 2019 to events page

### PR DESCRIPTION
**Pull request by web-dave**
docs: add NG-DE 2019 to events page
I'm part of the Team and I want NG-DE to be listed there as well.

### CODE REVIEW

**Review by StephenFluin — COMMENTED** [review]
This page is limited to events where an Angular team member is speaking, so we can't accept this contribution at this time.

**Review by benlesh — CHANGES_REQUESTED** [review]
Please see Stephen's comment.

**Comment by web-dave** [comment]
We will have at least one of the Angular Team. I wait for the final official announcement. The team member has been notified.

**Comment by web-dave** [comment]
Ok. It's official. We have Manfred Steyer. He will be announced during the next days. He has been accepted and he has confirmed. So we fulfilled this. @StephenFluin is this Ok?

**Comment by robinboehm** [comment]
Hey @StephenFluin @benlesh,

our call-for-paper is open and I see not many contribution of the angular team so far.
I think only @manfredsteyer has submitted some.
Did you submit already any papers?

We would be super happy if more of the angular-team will speak at our conference <3 
The process very open to everyone and we'll create a diverse lineup with a blind-voting process.
Maybe you can drop this internally if someone is interested 🤩

We only asked 2 keynote speakers directly ... everybody else should apply for our CFP.
So we don't send out direct invites. 

It's officially ending this Sunday. But if you just missed it we could let it open for a few more day.

Looking forward to an awesome event hopefully with some of you there <3

**Review by gkalpak — APPROVED** [review]

**Pull request closed without merging**
