### PR TITLE
feat(core): expose onDestroy on ApplicationRef

### LINKED ISSUE #49087: ApplicationRef's onDestroy method should not be internal
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

When developing with NgModules we were able to do:

```
const moduleRef = await platformBrowserDynamic().bootstrapModule(AppModule);
moduleRef.onDestroy(() => { /* some logic */ });
```

The new `bootstrapApplication` now returns a `ApplicationRef`. Although the `onDestroy` method exists in `ApplicationRef`, it's marked as internal and not exposed.

### Proposed solution

Make `ApplicationRef.onDestroy` not internal and part of the public API. This makes sense as well because `.destroy()` and `.destroyed` are part of the public API.

### Alternatives considered

```
(applicationRef as any).onDestroy(() => {});
```

or getting the reference to the first component and using its `onDestroy`.

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
This change exposes the onDestroy callback on the ApplicationRef as the public API. It is useful for cases where people need to execute cleanup logic on application teardown.

Closes #49087

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM

reviewed-for: fw-core, public-api

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
👍

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit a5f1737d1c2435b1476c1277bdc9a6827377465f.

**Pull request closed without merging**
