### PR TITLE
build: make scripts for compatibility with Node.js 18.20+

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit enhances the ng-dev and other local scripts to ensure compatibility with Node.js 18.20+. This adjustment is essential for releasing this branch, as it would otherwise lack compatibility with that version.

### CODE REVIEW

**Comment by alan-agius4** [comment]
@josephperrott, the saucelabs failure seems not related to this change.

**Review by josephperrott — APPROVED** [review]
LGTM

Review-for: global-dev-infra-approvers

**Review by josephperrott — APPROVED** [review]
Reviewed-for: global-dev-infra-approvers

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 56e085f3f840290440a7fc32911160c21f231ba5.

**Pull request closed without merging**
