### PR TITLE
fix(core): drop mutate function from the signals public API

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
PR modifies the signals public API surface: drops the `.mutate` method and marks signal core APIs as stable.

### CODE REVIEW

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: fw-core, public-api

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-core, public-api

**Review by devversion — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
caretaker note: g3 failure is unrelated

**Comment by atscott** [comment]
This PR was merged into the repository by commit 5b88d136affdaa35e7015c00281b86cae040321b.

**Comment by roma2341** [comment]
Why you drop this function without any description? what are alternatives for dropped function ?

**Comment by pkozlowski-opensource** [comment]
@roma2341 description is provided as part of the commit message: https://github.com/angular/angular/pull/51821/commits/9ea54d47f50e2c6028fe9a70ff734fd455f75660

**Pull request closed without merging**
