### PR TITLE
fix(platform-browser): only add `ng-app-id` to style on server side

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit fixes an issue where it causes issues in G3 when we add `ng-app-id` on browser apps.

### CODE REVIEW

**Review by pkozlowski-opensource — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: size-tracking

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: size-tracking

**Comment by alan-agius4** [comment]
Presubmit https://fusion2.corp.google.com/presubmit/tap/517425516/OCL:517425516:BASE:517425563:1679068763282:970150dc/targets

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit c934a8e72bec9f96ccf1a1de1a3384d40dfd2731.

**Pull request closed without merging**
