### PR TITLE
docs: remove wrongly placed duplicate sentence

### PR DESCRIPTION
**Pull request by dwaxweiler**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The removed sentence was misplaced; It is a few lines later again at the right place.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Hey, good catch @dwaxweiler! Could you squash your commits and amend the commit message to:

```
docs: remove duplicate sentence in toh-pt5
```

That should get the PR passing. Then can you tag me so I can come back and approve? Thanks!!

**Comment by dwaxweiler** [comment]
@kapunahelewong Thanks for your feedback! It should be okay now. :)

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Please can you remove the ngcc changes from this PR?

**Comment by dwaxweiler** [comment]
@kapunahelewong @petebacondarwin :heavy_check_mark:

**Review by kapunahelewong — APPROVED** [review]

**Review by petebacondarwin — APPROVED** [review]

**Comment by kapunahelewong** [comment]
Thanks very much, @dwaxweiler!

**Pull request closed without merging**
