### PR TITLE
fix(router): Fix _lastPathIndex in deeply nested empty paths

### PR DESCRIPTION
**Pull request by adriensamson**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
See https://github.com/angular/angular/issues/13011#issuecomment-274414952 and https://github.com/angular/angular/issues/13011#issuecomment-364789825

When an empty path is deeply nested, its _lastPathIndex is too high and relative nagivation to its parent needs lot of additional '../'

Issue Number: #13011 

## What is the new behavior?
_lastPathIndex (computed from _segmentIndexShift) is correct and relative navigation works as expected

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Jordan-Hall** [comment]
@adriensamson This pull request appears to effect named outlet.  using RouterLink in a named outlet makes the URL (../../) and not up a level correctly. It appears only to go up on the routing tree. 

However it does fix the issue regarding primary routes

**Comment by djleonskennedy** [comment]
Any news ?

**Comment by jonrimmer** [comment]
Please, please, *please* merge this. I do not understand how something as fundamental as relative navigation can be left broken for years. The Angular docs [even recommend using pathless routes like this](https://angular.io/guide/router#child-route-configuration), and they do not work properly!?

**Comment by jasonaden** [comment]
[Presubmit](https://test.corp.google.com/ui#id=OCL:204043779:BASE:204147085:1531330162607:368bcb9b)

**Review by jasonaden — APPROVED** [review]
Looks good!

**Review by mhevery — APPROVED** [review]

**Comment by sarunint** [comment]
Just for my curious, has the named-outlet issue mentioned by @Jordan-Hall been solved?

**Comment by matsko** [comment]
@adriensamson please rebase so that it can land in `patch`.

**Comment by sarunint** [comment]
One more note, since @jasonaden refactored this to a flag in the router, shouldn't this be a `feat`, rather than a `fix`?

**Comment by adriensamson** [comment]
Thank you @jasonaden for your help.
@matsko I have just rebased and fixed conflicts with master.

**Comment by vicb** [comment]
http://test/OCL:205690608:BASE:205690658:1532369164802:f98bc7fd

**Comment by vicb** [comment]
@jasonaden @adriensamson This patch does not apply cleanly on the 6.0.x branch and the PR is marked as master + patch (6.0.x).

What I would suggest is to mark this PR as master only and create a new PR for 6.0.x with the conflicts resolved. They would both be merged at the same time.

Makes sense ?

**Comment by vicb** [comment]
merge-assistance: wainting on the PR for the patch branch to be ready before merging

**Comment by marcwhitbread** [comment]
I can't tell if this is in 6.0.x or not. Was the patch trashed?

**Comment by sarunint** [comment]
@marcwhitbread It's not in 6.0.x, since it touches the public API.

**Comment by marcwhitbread** [comment]
@sarunint thanks for the reply. I apologize in advance for another stupid question... How would i find out what version received this pr? 6.1? 7?

**Comment by sarunint** [comment]
It's 6.1.

**Comment by dirkluijk** [comment]
Added https://github.com/angular/angular/pull/25609 to make this the default for Angular 7.

**Comment by dirkluijk** [comment]
Seems to be broken in Angular 7: https://github.com/angular/angular/issues/26983.

I don't see how other recent changes could possibly interfere with this.

**Pull request closed without merging**
