### PR TITLE
fix(bundles): testing bundle should include browser platform

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by alexeagle** [comment]
cc @pkozlowski-opensource 
Not sure if any other stuff is missing from the bundles based on recent work?

**Comment by juliemr** [comment]
I think that this includes everything that's changed from the testing perspective. LGTM.

**Comment by alexeagle** [comment]
I confirmed with this fix that we can finally execute tests in google3.

**Comment by alexeagle** [comment]
got the ok to merge from caretaker.

**Pull request closed without merging**
