### PR TITLE
docs: update tagline

### PR DESCRIPTION
**Pull request by jesselpalmer**
Seems like the tagline has changed on the [Angular Twitter account](https://twitter.com/angular) and [angular.io](https://angular.io). This change makes this doc in line with those two resources.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by petebacondarwin** [comment]
Thanks @jesselpalmer - been a while!

**Review by IgorMinar — APPROVED** [review]
Thanks for catching this @jesselpalmer !

**Comment by jesselpalmer** [comment]
> Thanks @jesselpalmer - been a while!

Thanks, @petebacondarwin! Nice seeing you again :-)

> Thanks for catching this @jesselpalmer !

Happy to help @IgorMinar :-)

**Pull request closed without merging**
