### PR TITLE
build(docs-infra): upgrade lighthouse to 6.1.0

### LINKED ISSUE #35965: Update lighthouse in aio to v5.7.0
this version of lighthouse fixes the issue with `img[loading=lazy]`, see: https://github.com/angular/angular/pull/34900#issuecomment-594091352

### PR DESCRIPTION
**Pull request by sonukapoor**
To take advantage of lazy loaded images `img[loading=lazy]`, this commit
upgrades lighthouse to version 6.1.0.

Closes #35965

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #35965

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sonukapoor** [comment]
[Release notes](https://github.com/GoogleChrome/lighthouse/releases/tag/v6.0.0) of version 6.

The upgrade has dropped our score for the following areas:

### API accessibility from 100 to 98

Issue at https://angular.io/api

image

This is happening because of the icon used in the search input here:

image

### Docs accessibility from 100 to 98

Issue at https://angular.io/docs

image

This is happening because `h4` is being used here, the heading order seems to be incorrect. 

image

**Comment by sonukapoor** [comment]
@StephenFluin Can you check if my suggested colour above is OK to be used?

**Comment by StephenFluin** [comment]
@sonukapoor LGTM (I asked @sjtrimble too)

**Comment by sonukapoor** [comment]
@StephenFluin / @sjtrimble Actually, I think it would be better to change the colour for material icons to `$blue-grey-600 - #546E7A`. This will keep the current colours order contrast sequential, otherwise, you will end up with a darker colour in the middle of the other colours. See the below screenshot at line 39. 

image

Using `$blue-grey-600` seems to work well and passes the lighthouse audit is happy too. 

image

LMK

**Comment by gkalpak** [comment]
@googlebot I consent.

**Review by gkalpak — APPROVED** [review]
This is awesome! Thank you for figuring out and fixing the failures, @sonukapoor :100:
(FYI, I added a commit that updates our minimum a11y scores to match out current improved values.)

**Comment by sonukapoor** [comment]
> This is awesome! Thank you for figuring out and fixing the failures, @sonukapoor 💯
> (FYI, I added a commit that updates our minimum a11y scores to match out current improved values.)

Do we need to decrease the scores?

**Comment by gkalpak** [comment]
> Do we need to decrease the scores?

I am not following :grin:
I added a commit to increase the scores, because we seems to have improved a11y for some pages. 
(BTW, this is not directly related to updating Lighthouse to 6.1.0, but it is related to Lighthouse in general, so I piggy-backed on this PR :grin:)

**Comment by sonukapoor** [comment]
> > Do we need to decrease the scores?
> 
> I am not following 😁
> I added a commit to increase the scores, because we seems to have improved a11y for some pages.
> (BTW, this is not directly related to updating Lighthouse to 6.1.0, but it is related to Lighthouse in general, so I piggy-backed on this PR 😁)

Sorry, my bad. I misread the original comment.

**Review by StephenFluin — APPROVED** [review]

**Pull request closed without merging**
