### PR TITLE
fix(docs): export simple name and full name for doc alias

### LINKED ISSUE #2452: fix(docs): resolve warnings logged by gulp public_docs task
cc @naomiblack 

TODO:

 - [ ] Fix broken links in `annotations.ts`: PR #2475 
 - [x] Fix checkAnchorLinks service in Dgeni to url decode normalized urls when checking dangling links: ~~https://github.com/angular/dgeni-packages/pull/119~~ 
 - [x] Update dgeni-packages dependency PR #2489
 - [x]  Fix document names/ids to not include full heritage of classes: #2462 
 - [x] Merge #2499 to get rid of Ambiguous Link warnings caused by #2486

Opening an issue to track work to fix errors when running the `gulp public_docs` task. @petebacondarwin tells me time is better spent addressing these issues than the ones generated by the `gulp docs` task. Based on current master (ddd5a235c39477970b8db8c37a1a63a82a389357), here are the warnings logged when running `gulp public_docs`:

```log
warn:    Invalid link (does not match any doc): "QueryList" - doc "DirectiveAnnotation extends  Injectable" (class)  - from file "angular2/src/core/annotations_impl/annotations.ts"
warn:    Invalid link (does not match any doc): "QueryList" - doc "DirectiveAnnotation extends  Injectable" (class)  - from file "angular2/src/core/annotations_impl/annotations.ts"
warn:    Invalid link (does not match any doc): "DynamicChangeDetection" - doc "ChangeDetection" (class)  - from file "angular2/src/change_detection/interfaces.ts"
warn:    Invalid link (does not match any doc): "JitChangeDetection" - doc "ChangeDetection" (class)  - from file "angular2/src/change_detection/interfaces.ts"
warn:    Invalid link (does not match any doc): "DynamicChangeDetection" - doc "ChangeDetection" (class)  - from file "angular2/src/change_detection/interfaces.ts"
warn:    Invalid link (does not match any doc): "JitChangeDetection" - doc "ChangeDetection" (class)  - from file "angular2/src/change_detection/interfaces.ts"
warn:    Invalid link (does not match any doc): "JitChangeDetection" - doc "DynamicChangeDetection extends  ChangeDetection" (class)  - from file "angular2/src/change_detection/change_detection.ts"
warn:    Invalid link (does not match any doc): "DynamicChangeDetection" - doc "JitChangeDetection extends  ChangeDetection" (class)  - from file "angular2/src/change_detection/change_detection.ts"
warn:    Invalid link (does not match any doc): "QueryList" - doc "QueryAnnotation extends  DependencyAnnotation" (class)  - from file "angular2/src/core/annotations_impl/di.ts"
warn:    Invalid link (does not match any doc): "QueryList" - doc "QueryAnnotation extends  DependencyAnnotation" (class)  - from file "angular2/src/core/annotations_impl/di.ts"
warn:    Invalid link (does not match any doc): "ControlGroup" - doc "angular2/forms" (module)  - from file "angular2/forms.ts"
warn:    Invalid link (does not match any doc): "Control" - doc "angular2/forms" (module)  - from file "angular2/forms.ts"
warn:    Invalid link (does not match any doc): "Control" - doc "angular2/forms" (module)  - from file "angular2/forms.ts"
warn:    Invalid link (does not match any doc): "ControlGroup" - doc "Control extends  AbstractControl" (class)  - from file "angular2/src/forms/model.ts"
warn:    Invalid link (does not match any doc): "ControlArray" - doc "Control extends  AbstractControl" (class)  - from file "angular2/src/forms/model.ts"
warn:    Invalid link (does not match any doc): "Control" - doc "ControlGroup extends  AbstractControl" (class)  - from file "angular2/src/forms/model.ts"
warn:    Invalid link (does not match any doc): "Control" - doc "ControlGroup extends  AbstractControl" (class)  - from file "angular2/src/forms/model.ts"
warn:    Invalid link (does not match any doc): "ControlArray" - doc "ControlGroup extends  AbstractControl" (class)  - from file "angular2/src/forms/model.ts"
warn:    Invalid link (does not match any doc): "ControlArray" - doc "ControlGroup extends  AbstractControl" (class)  - from file "angular2/src/forms/model.ts"
warn:    Invalid link (does not match any doc): "Control" - doc "ControlArray extends  AbstractControl" (class)  - from file "angular2/src/forms/model.ts"
warn:    Invalid link (does not match any doc): "Control" - doc "ControlArray extends  AbstractControl" (class)  - from file "angular2/src/forms/model.ts"
warn:    Invalid link (does not match any doc): "ControlGroup" - doc "ControlArray extends  AbstractControl" (class)  - from file "angular2/src/forms/model.ts"
warn:    Invalid link (does not match any doc): "ControlGroup" - doc "ControlArray extends  AbstractControl" (class)  - from file "angular2/src/forms/model.ts"
warn:    Invalid link (does not match any doc): "Control" - doc "DefaultValueAccessor implements  ControlValueAccessor" (class)  - from file "angular2/src/forms/directives/default_value_accessor.ts"
warn:    Invalid link (does not match any doc): "Control" - doc "SelectControlValueAccessor implements  ControlValueAccessor" (class)  - from file "angular2/src/forms/directives/select_control_value_acces
sor.ts"
warn:    Invalid link (does not match any doc): "ControlGroup" - doc "FormBuilder" (class)  - from file "angular2/src/forms/form_builder.ts"
warn:    Invalid link (does not match any doc): "Control" - doc "FormBuilder" (class)  - from file "angular2/src/forms/form_builder.ts"
warn:    Invalid link (does not match any doc): "ControlGroup" - doc "FormBuilder" (class)  - from file "angular2/src/forms/form_builder.ts"
warn:    Invalid link (does not match any doc): "Control" - doc "FormBuilder" (class)  - from file "angular2/src/forms/form_builder.ts"
warn:    Dangling Links Found in "partials/modules/angular2/annotations/index.html":
 - /angular2/annotations/ComponentAnnotation extends  Directive,
 - /angular2/annotations/DirectiveAnnotation extends  Injectable
warn:    Dangling Links Found in "partials/modules//angular2/annotations/DirectiveAnnotation extends  Injectable/index.html":
 - QueryList,
 - QueryList,
 - annotations/onChange,
 - annotations/onDestroy,
 - annotations/onAllChangesDone,
 - pipes/keyValDiff
warn:    Dangling Links Found in "partials/modules/angular2/change_detection/index.html":
 - /angular2/change_detection/ASTWithSource extends  AST,
 - /angular2/change_detection/AccessMember extends  AST,
 - /angular2/change_detection/LiteralArray extends  AST,
 - /angular2/change_detection/ImplicitReceiver extends  AST,
 - /angular2/change_detection/DehydratedException extends  BaseException,
 - /angular2/change_detection/ExpressionChangedAfterItHasBeenChecked extends  BaseException,
 - /angular2/change_detection/ChangeDetectionError extends  BaseException,
 - /angular2/change_detection/DynamicProtoChangeDetector extends  ProtoChangeDetector,
 - /angular2/change_detection/JitProtoChangeDetector extends  ProtoChangeDetector,
 - /angular2/change_detection/DynamicChangeDetector extends  AbstractChangeDetector,
 - /angular2/change_detection/NullPipe extends  Pipe,
 - /angular2/change_detection/NullPipeFactory extends  PipeFactory,
 - /angular2/change_detection/DynamicChangeDetection extends  ChangeDetection,
 - /angular2/change_detection/JitChangeDetection extends  ChangeDetection,
 - /angular2/change_detection/PreGeneratedChangeDetection extends  ChangeDetection
warn:    Dangling Links Found in "partials/modules//angular2/change_detection/ChangeDetection/index.html":
 - DynamicChangeDetection,
 - JitChangeDetection,
 - DynamicChangeDetection,
 - JitChangeDetection
warn:    Dangling Links Found in "partials/modules//angular2/change_detection/DynamicChangeDetection extends  ChangeDetection/index.html":
 - JitChangeDetection
warn:    Dangling Links Found in "partials/modules//angular2/change_detection/JitChangeDetection extends  ChangeDetection/index.html":
 - DynamicChangeDetection
warn:    Dangling Links Found in "partials/modules/angular2/core/index.html":
 - /angular2/core/SelfAnnotation extends  Visibility,
 - /angular2/core/AncestorAnnotation extends  Visibility,
 - /angular2/core/ParentAnnotation extends  Visibility,
 - /angular2/core/UnboundedAnnotation extends  Visibility,
 - /angular2/core/QueryAnnotation extends  DependencyAnnotation,
 - /angular2/core/AttributeAnnotation extends  DependencyAnnotation,
 - /angular2/core/QueryList<T> extends  BaseQueryList<T>
warn:    Dangling Links Found in "partials/modules//angular2/core/QueryAnnotation extends  DependencyAnnotation/index.html":
 - QueryList,
 - QueryList
warn:    Dangling Links Found in "partials/modules/angular2/di/index.html":
 - /angular2/di/NoBindingError extends  AbstractBindingError,
 - /angular2/di/AbstractBindingError extends  BaseException,
 - /angular2/di/AsyncBindingError extends  AbstractBindingError,
 - /angular2/di/CyclicDependencyError extends  AbstractBindingError,
 - /angular2/di/InstantiationError extends  AbstractBindingError,
 - /angular2/di/InvalidBindingError extends  BaseException,
 - /angular2/di/NoAnnotationError extends  BaseException
warn:    Dangling Links Found in "partials/modules/angular2/forms/index.html":
 - ControlGroup,
 - Control,
 - Control,
 - /angular2/forms/Control extends  AbstractControl,
 - /angular2/forms/ControlGroup extends  AbstractControl,
 - /angular2/forms/ControlArray extends  AbstractControl,
 - /angular2/forms/ControlNameDirective extends  ControlDirective,
 - /angular2/forms/FormControlDirective extends  ControlDirective,
 - /angular2/forms/NgModelDirective extends  ControlDirective,
 - /angular2/forms/ControlGroupDirective extends  ControlContainerDirective,
 - /angular2/forms/FormModelDirective extends  ControlContainerDirective implements  FormDirective,
 - /angular2/forms/TemplateDrivenFormDirective extends  ControlContainerDirective implements
    FormDirective,
 - /angular2/forms/DefaultValueAccessor implements  ControlValueAccessor,
 - /angular2/forms/CheckboxControlValueAccessor implements  ControlValueAccessor,
 - /angular2/forms/SelectControlValueAccessor implements  ControlValueAccessor
warn:    Dangling Links Found in "partials/modules//angular2/forms/Control extends  AbstractControl/index.html":
 - ControlGroup,
 - ControlArray
warn:    Dangling Links Found in "partials/modules//angular2/forms/ControlGroup extends  AbstractControl/index.html":
 - Control,
 - Control,
 - ControlArray,
 - ControlArray
warn:    Dangling Links Found in "partials/modules//angular2/forms/ControlArray extends  AbstractControl/index.html":
 - Control,
 - Control,
 - ControlGroup,
 - ControlGroup
warn:    Dangling Links Found in "partials/modules//angular2/forms/DefaultValueAccessor implements  ControlValueAccessor/index.html":
 - Control
warn:    Dangling Links Found in "partials/modules//angular2/forms/SelectControlValueAccessor implements  ControlValueAccessor/index.html":
 - Control
warn:    Dangling Links Found in "partials/modules//angular2/forms/FormBuilder/index.html":
 - ControlGroup,
 - Control,
 - ControlGroup,
 - Control
warn:    Dangling Links Found in "partials/modules/angular2/pipes/index.html":
 - /angular2/pipes/PromisePipe extends  Pipe,
 - /angular2/pipes/UpperCasePipe extends  Pipe,
 - /angular2/pipes/LowerCasePipe extends  Pipe,
 - /angular2/pipes/ObservablePipe extends  Pipe,
 - /angular2/pipes/JsonPipe extends  Pipe,
 - /angular2/pipes/IterableChanges extends  Pipe,
 - /angular2/pipes/KeyValueChanges extends  Pipe
warn:    83 'unmatched links'
```

### PR DESCRIPTION
**Pull request by jeffbcross**
(Still needs fix to the dangling link warnings, possibly in the [dgeni-packages](https://github.com/angular/dgeni-packages) repo)

Fixes #2452

### CODE REVIEW

**Comment by petebacondarwin** [comment]
I don't really like this because it doesn't solve the problem that the id of the document should IMO include information (as a string) about the `extend` parentage of the class. I think the document's id should just be the class name prefixed by module.

We should expose the heritage in separate properties that can be consumed by the .d.ts processing.  This would keep the `readTypeScriptModules` processor decoupled from the final output format.

**Comment by jeffbcross** [comment]
@petebacondarwin I'm not following. You say "the id of the document should IMO include information (as a string) about the extend parentage of the class." And then you say, "the document's id should just be the class name prefixed by module." I think you used incorrect terminology in one of those sentences.

**Comment by jeffbcross** [comment]
In my commit, the id remains a string with parentage information, but additional aliases are added to include the full parentage and generic information, as well as a trimmed version.

**Comment by jeffbcross** [comment]
BTW, this is my first foray into Dgeni, so I'm kinda flying blind. When you say "consumed by the .d.ts processing," are you referring to the logic contained within the `readTypeScriptModules.js` module?

**Comment by jeffbcross** [comment]
(Updated the commit to include inline comment about the change, and to fix a link in annotations.ts)

**Comment by petebacondarwin** [comment]
Sorry I mean IMO "not" include that information.

You are flying straight and true - just don't let go of the stick.

What I am saying is that Alex Eagle's change was wrong, that it should be reverted and a different solution found.

**Comment by jeffbcross** [comment]
@petebacondarwin sounds good, I'll go ahead and revert it and push to this PR.

**Comment by jeffbcross** [comment]
Hmm, that commit does a lot of things. I'd rather not revert the commit, and I'm not sure the implications if I just remove parts of it.

How about I change my commit to set the `id` of the doc to the trimmed version, and keep the `name` as-is? Then existing links should be happy, and the templates would still be displaying the name with full heritage.

**Comment by petebacondarwin** [comment]
Working in it right now.

**Comment by jeffbcross** [comment]
Closed in favor of 659adf83dcaae2b42f03f315c7b68f3a43ef7164

**Pull request closed without merging**
