### PR TITLE
feat(aio): search results - show top 5 results and API icons

### PR DESCRIPTION
**Pull request by wardbell**
Separate commits in this PR tackle **two usability issues** with search results.

This is independent of PR #16443 which handles the "no search results" case. Depending on how these PRs are merged, we may have a small conflict to resolve.

### 1. List the top weighted search results

Search results (which arrive weighted) are shown sorted by title within area.
The alpha sort was easier on readers than the weighted.

But at least one reviewer pointed out a usability problem. When you look for a word/word-fragment that appears frequently, a word such as "component", there are too many matching pages. The most likely match page (by weight) sorts deep into the area results and requires considerable scrolling. That isn't intuitive.

This PR offers a solution. When the number of match pages in an area exceeds 10, the top 5 weighted results are shown _above_ the others, followed by a line, followed by the complete alpha list.

This PR also displays the number of matches in each area next to the area name.

Coincidentally DRYed up some tests

### 2. Add API Icons

@StephenFluin or @IgorMinar a while ago asked to see the same icons displayed for API results as on the API page.  

It was easy to add while making the first change and including it reduced probability of tiresome merge conflicts if it was in a separate PR. Added as a separate commit. 

<hr>

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]

**Review by petebacondarwin — APPROVED** [review]
Technically it looks great. So I am happy to approve this.
But I am not convinced by the use of the `hr`. I would ask for some feedback from the stakeholders for this.

**Comment by wardbell** [comment]
The `<hr>` was a placeholder. I replaced it in the 3rd commit with an ellipsis icon. The really important change is breaking one big UL into two because I noticed that an accurate LI count seems to matter for a11y.

Coincidentally, I got rid of the result type conversion of `let` and `var` to `const` ... which was a PITA ... by adding those two as valid API symbols, both presenting the "K" symbol for `const` as they should. That move eliminates the test I added to `search-results.component.spec.ts`.

Should be good to merge after your quick re-review.

**Comment by petebacondarwin** [comment]
> Coincidentally, I got rid of the result type conversion of let and var to const ... which was a PITA ... by adding those two as valid API symbols, both presenting the "K" symbol for const as they should. That move eliminates the test I added to search-results.component.spec.ts.

This SO makes my day. I really wanted to add that as a review comment but felt that it might be too pedantic :-)

**Comment by petebacondarwin** [comment]
I wonder if we should actually remove the distinction between these doc types (var, let and const) in the dgeni processing anyway?

**Review by petebacondarwin — APPROVED** [review]
LGTM

**Comment by wardbell** [comment]
Cleared expected merge conflict, rebased into 2 commits. Should be ready to merge.

**Review by gkalpak — APPROVED** [review]
Nice!

**Pull request merged**
