### PR TITLE
docs: add missing usage-notes

### LINKED ISSUE #54228: Documentation missing "Usage Notes" tab
### Describe the problem that you experienced

The "Usage Notes" tab of the HostListener page is missing.

Links:
- [angular.io page](https://angular.io/api/core/HostListener#usage-notes)
- [angular.dev page](https://angular.dev/api/core/HostListener?tab=usage-notes)

### Enter the URL of the topic with the problem

_No response_

### Describe what you were looking for in the documentation

_No response_

### Describe the actions that led you to experience the problem

_No response_

### Describe what you want to experience that would fix the problem

_No response_

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by hansireit**
Fixes #54228

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

Fixes the missing "Usage Notes" tab for the host-listener.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #54228

## What is the new behavior?

Usage notes tab is now present.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by hansireit** [comment]
Sorry for the messy commit history, should I create a new PR?

**Comment by danieljancar** [comment]
Make sure to squash the commits especially merge commits into a single descriptive commit to reduce commit history. 😉

**Comment by hansireit** [comment]
> Make sure to squash the commits, as soon as the pr is qualified for merge, especially merge commits into a single descriptive commit to reduce commit history. 😉

Is there a way around fore-pushing to the branch to squash the commits? Or what is the best way to squash commits in a branch where I already synced the fork?

**Comment by danieljancar** [comment]
I feel like force pushing is the easiest and most straightforward solution for our use-case. Never looked up a better solution. If you find one, hit me up. 🙈🧑‍💻

**Review by JeanMeche — APPROVED** [review]
LGTM

**Comment by JeanMeche** [comment]
Caretaker: This is a doc only change, my approval should be enough.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 5eda3bf5f0afb482de3c8333511f704d873afb64.

**Pull request closed without merging**
