### PR TITLE
docs: Fix syntax in interpolation example

### PR DESCRIPTION
**Pull request by justinsb**
Correcting a typo in the example.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

### CODE REVIEW

**Comment by justinsb** [comment]
I'm learning / new to angular - I apologize in advance if the original syntax is in fact correct!

**Review by petebacondarwin — APPROVED** [review]
You are absolutely correct @justinsb - good spot!

**Review by petebacondarwin — APPROVED** [review]
~~Reviewed-for: global-api-docs~~ Monday confusion :-)

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Pull request closed without merging**
