### PR TITLE
refactor(core): improve an error message when `ENVIRONMENT_INITIALIZER` is not a multi provider

### PR DESCRIPTION
**Pull request by AndrewKushnir**
Currently if the `ENVIRONMENT_INITIALIZER` token is not configured with `multi: true` flag, the code fails while trying to iterate over the value (see an error message in #46823). This commit checks whether the `ENVIRONMENT_INITIALIZER` token value type is an array and throws a helpful error message.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by atscott — APPROVED** [review]

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: fw-core, public-api

**Comment by AndrewKushnir** [comment]
@atscott @jessicajaniuk thanks for the reviews 👍

The CI is failing due to a missing semicolon in tests, I will get it fixed asap.

**Comment by AndrewKushnir** [comment]
This PR is now updated and should be ready for merge once CI is "green".

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 66e41223f31a1437bf6e7387bf20b940cd61ddff.

**Pull request closed without merging**
