### PR TITLE
Allow VmTurnZone to be overriden in bootstrap.

### LINKED ISSUE #1769: Bootstrap: The binding of bind(VmTurnZone) after resolved bindings is wrong behavior
Angular should insert the binding at the *top* of the list of bindings, not at the bottom.

Doing it at the top makes it possible to override VmTurnZone (for testing, for example).

### PR DESCRIPTION
**Pull request by matanlurey**
Closes #1769.

### CODE REVIEW

**Comment by vicb** [comment]
@matanlurey I think there should be a test for this change.

I think that the real "issue" here is that the `VmTurnZone` class is [hardcoded in application.js](https://github.com/angular/angular/pull/1799/files#diff-cf02ca47f1e825551356bfd97e748f4fR135).

I think that your change would allow overriding the zone value but it would not change the `VmTurnZone` instance which is used to run the angular code.

**Comment by matanlurey** [comment]
Ah, I see what you mean. I can try another approach for now:

if componentInjectableBindings contains a token for VmTurnZone, use it, otherwise, use default.

Thoughts?

**Comment by vicb** [comment]
> if componentInjectableBindings contains a token for VmTurnZone, use it, otherwise, use default.

You would have to create a new injector which only contains those bindings to instantiate a `VmTurnZone`. I guess it should work if there is no deps on any `__injectorBindings()`.

An other option would be to pass an instance of `VmTurnZone` as an (extra) optional parameter to bootstrap ?

**Comment by rkirov** [comment]
Later bindings do overwrite and we have a test for that -   https://github.com/angular/angular/blob/master/modules/angular2/test/di/injector_spec.js#L192

**Comment by matanlurey** [comment]
If everyone is OK with the approach, I'll temporarily modify bootstrap to allow a custom VmTurnZone.

This will unblock testing, and I'm sure can be done more elegantly when bootstrap is cleaned up.

**Comment by vicb** [comment]
> This will unblock testing, and I'm sure can be done more elegantly when bootstrap is cleaned up.

@matanlurey just curious on why you would need to override `VmTurnZone` for testing, do you have some code to share ? _(I think we can `fakeAsync` without overriding `VmTurnZone`)_

**Comment by matanlurey** [comment]
Here is my current code:

```dart
class TestBed<TC, TP> {
  /// Returns a future of a facade to work with the testing environment.
  /// Optionally switches [TC]'s template to use [html], if supplied.
  Future<TestFacade<TC, TP>> compile([String html]) {
    final rootElement = new Element.tag('test-component');
    final docFragment = document.createDocumentFragment()..append(rootElement);
    final testBindings = []
      ..addAll(_bindings)
      ..addAll([
        bind(appDocumentToken).toValue(docFragment),
        bind(ShadowDomStrategy).toClass(NativeShadowDomStrategy)
      ]);
    if (html != null) {
      final templateResolver = new MockTemplateResolver();
      templateResolver.setInlineTemplate(TC, html);
      testBindings.add(bind(TemplateResolver).toValue(templateResolver));
    }

    // This complicated bit of code *wraps* Angular's bootstrap in a fake zone
    // that we control (quiver.testing.async.FakeAsync). In the future, when
    // Angular's bootstrap allows you to specify your own implementation of
    // VmTurnZone, this may not be necessary.
    //
    // See: https://github.com/angular/angular/pull/1799
    Future<AcxTestFacade<TC, TP>> future;
    final fakeAsync = new FakeAsync()..run((fakeAsync) {
      future = bootstrap(
          TC,
          testBindings,
          (e, _) => throw e).then((componentRef) {
        return new AcxTestFacade<TC, TP>(componentRef, rootElement, fakeAsync);
      });
    });
    // We are going to return a future that will never resolve because the
    // .then's are queued in a fake zone. Here we schedule a microtask in the
    // "real" zone to flush to the "fake" one.
    scheduleMicrotask(fakeAsync.flushMicrotasks);
    return future;
  }
}
```

I'm running into some issues (future.then of bootstrap) never resolves in some (unknown) cases.

**Comment by vicb** [comment]
> I'm running into some issues (future.then of bootstrap) never resolves in some (unknown) cases.

Would it work if you call `scheduleMicrotask(fakeAsync.flushMicrotasks);` multiple times ? (it could help when there are multiple template fetched).

My idea about integrating the `fake_async` pkg (I was not aware of `quiver.testing.async.FakeAsync`) it to wrap the whole test fn into a "fake" zone. By doing this it should be possible to use the regular impl of `VmTurnZone` without having to override it - we would be closer to "real" code. _(Someting similar with what your current code does)_. I hope to be able to work on it tomorrow, if integrating zone 0.5 goes well.

**Comment by matanlurey** [comment]
Ok, I figured out my issue: TemplateLoader was trying to use the real Xhr implementation to load templates. Wrapping this all in fake async meant that the Xhr would load the template, but never deliver the events. I'll have a suggested (temporary fix shortly).

Do you have time to sync this week (maybe via VC)? This is essentially what I'm doing today, and it works great if you don't need to Xhr load anything :)

**Comment by vicb** [comment]
Great!

We can sync tomorrow via VC. I'm in CEST TZ for now and have mettings a 10-10:30 & 11-11:30 PST tomorrow. Any other time during your morning would work.

**Comment by vicb** [comment]
@matanlurey could you also send me a quick update on what you've done on testing zone (GH branch ?) at the end of your day so that we don't duplicate work on this - I could work on the JS impl if you've focused on Dart only for now. Thanks.

**Comment by matanlurey** [comment]
The code is all internal right now, but I can share it with you via VC. Email me at matanl@g.c.

**Comment by vicb** [comment]
removed the "!merge" label. I don't think the code is right as is.

**Comment by matanlurey** [comment]
I am closing this. We can revisit later.

**Pull request closed without merging**
