### PR TITLE
refactor(core): remove unused private APIs

### PR DESCRIPTION
**Pull request by alan-agius4**
Remove private code which is not used by the Framework.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@alan-agius4 thanks for the cleanup 👍

**Comment by AndrewKushnir** [comment]
@alan-agius4 we can probably target patch branch here as well?

**Comment by alan-agius4** [comment]
> @alan-agius4 we can probably target patch branch here as well?

Yes

**Comment by atscott** [comment]
This PR was merged into the repository by commit 7368ee1e5c0b0f10f5c02b856f7eddb96c052f45.

**Pull request closed without merging**
