### PR TITLE
WIP: fix(upgrade): ensure change detection works as expected

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Comment by mhevery** [comment]
I think using `broadcast` is not right because:

1. It is slow
2. It does not guarantee that the ng1 and ng2 change detection is interleaved in the right order.

Can we just autodect that we are in infinite loop and break out of it?

**Comment by petebacondarwin** [comment]
1. Broadcast is not so slow these days as we did some work to optimise it last year. The current approach can't be that fast in any case as we are triggering a full digest (via evalAsync) the same number of times that we would be sending the broadcast message. Moreover, currently, we are picking up the signal (i.e. the digest) to run the change detection, for every downgraded component inside a watcher (i.e. it is being called multiple times per digest turn) even when we are not wanting to signal a change detection.

2. I need to look into this statement further. I thought that scope digest and broadcast transmissions walked the scope tree in the same order. So I don't see why there would be a difference - although I accept that it might be that in both cases the ordering is not correct.

**Comment by mhevery** [comment]
A broadcast will notify all of the listeners together. What we want is to interleave CD of ng1 with the CD of NG2. Using broadcast for that would mean that all NG2 would happen either before or after ng1.

**Comment by petebacondarwin** [comment]
Right now we trigger a `$evalAsync` which in turn triggers `$apply`. And all scopes get "notified" together because they all have (pseudo-code) `scope.$watch(function() { cd.detectChanges(); })`

So I don't think there is any interleaving going on now either.

**Comment by mhevery** [comment]
The way the original code worked, is that wherever in ng1 we placed an ng2
component, at that location we would do

$scope.$watch(() => ng2View.detectChanges())

In this way the ng1 and ng2 have their change detection interleaved.

If the code does not work this way, then we should change it so it does.

On Thu, Dec 15, 2016 at 1:47 PM, Pete Bacon Darwin <notifications@github.com

**Comment by petebacondarwin** [comment]
@mhevery you are quite right. Closing this.

**Pull request closed without merging**
