### PR TITLE
refactor: make comment structure consistent in packages/core/index.ts, fix minor grammar mistakes in documentation

### PR DESCRIPTION
**Pull request by ejcheng**
Fixed second big blob of comments in packages/core/index.ts to use multiline comments
Fixed grammar mistakes in documentation throughout project

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
(Second and third checkboxes do not apply to this PR)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [X] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Thanks @import-brain for helping to make our docs better

I'm approving this but in general it would be great if PRs contains more significant improvements. Mostly, these additional commas are subjective and stylistic and one could argue they are not really needed.

One further thing to note for future changes. To strictly follow out guidelines, the commit message header should be in present tense rather than past. E.g. `docs: fix minor grammar mistakes in CONTRIBUTING`.

Reviewed-for: global-docs-approvers

**Comment by import-brain** [comment]
> Thanks @import-brain for helping to make our docs better
> 
> 
> 
> I'm approving this but in general it would be great if PRs contains more significant improvements. Mostly, these additional commas are subjective and stylistic and one could argue they are not really needed.
> 
> 
> 
> One further thing to note for future changes. To strictly follow out guidelines, the commit message header should be in present tense rather than past. E.g. `docs: fix minor grammar mistakes in CONTRIBUTING`.
> 
> 
> 
> Reviewed-for: global-docs-approvers

@petebacondarwin Ah I see, thanks for the help! I'll try to make more significant improvements next time, and thanks for informing me about the present tense rule, I didn't realize that! :)

**Review by devversion — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit b1c028677f45e704342e81d7957d024c137340ce.

**Pull request closed without merging**
