### PR TITLE
build: update babel dependencies

### PR DESCRIPTION
**Pull request by JoostK**
Manual submit of #47014 to account for a change in formatting of PURE markers.

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by alan-agius4** [comment]
@JoostK can you please rebase?

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]

**Comment by JoostK** [comment]
Targeting patch but this is likely to conflict, but let's see what happens.

**Comment by JoostK** [comment]
Yeah I was expecting that. Let me see how feasible it is to update Babel in v14, it might just be a matter of cherry-picking this over and fixing the lockfile conflicts.

RC for now is fine for this PR :+1:

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit f02eae61febefc94d42cef723c93732a529801d1.

**Comment by pkozlowski-opensource** [comment]
@JoostK OK, merged to `main` / `v15` branches. LMK if you want to take a stab at v14

**Pull request closed without merging**
