### PR TITLE
docs: Corrected spelling

### PR DESCRIPTION
**Pull request by Gourav102**
Corrected spelling of 'Properties'.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by Gourav102** [comment]
@petebacondarwin, thanks for approving the PR. I'm not an authorized user to merge it. Can you merge it please?

**Comment by petebacondarwin** [comment]
We have a process where a Googler will run a script to merge this to `master` and other appropriate branches - probably later today.

**Comment by Gourav102** [comment]
Perfect. Got it. Thanks!

**Pull request closed without merging**
