### PR TITLE
docs(aio): add Compodoc - documentation tool for Angular app

### PR DESCRIPTION
**Pull request by vogloblinsky**
## PR Checklist
Does please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by juleskremer** [comment]
Can you please edit the text of your submission to remove reference to "Angular 2" -> It's just Angular (ie., "This tool generates dedicated documentation for Angular applications.")

**Comment by vogloblinsky** [comment]
@juleskremer Done. I have just followed other tools description. Others references to "Angular 2" still exist, need an other pull request ?

**Comment by juleskremer** [comment]
Thanks, I have already done a PR for this #17476

**Comment by wardbell** [comment]
Closed by #17476

**Pull request closed without merging**
