### PR TITLE
docs: fix non-working example in the `Observables` section

### PR DESCRIPTION
**Pull request by arturovt**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently, this example doesn't work because of:
```js
const { next, error } = observer;
```

Since they will be invoked with the global context.

## What is the new behavior?
In the new behavior, those methods are invoked correctly with the `Subscriber` context.
I was thinking of something like:
```js
const next = observer.next.bind(observer);
const error = ...;
```
But I think that this will be complicated for readers.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — COMMENTED** [review]
Thx for submitting the PR, @arturovt! Can you please explain how your changes fix the example (i.e. wht was not working before)?

**Comment by arturovt** [comment]
> Thx for submitting the PR, @arturovt! Can you please explain how your changes fix the example (i.e. wht was not working before)?

If you run this code the browser will ask your geolocation. If you click "Block" or "Allow" you will see: `Uncaught TypeError: Cannot read property 'isStopped' of null` in the console.

**Comment by gkalpak** [comment]
Oh, I see. It is because `next` and `error` need to be called with `observer` as `this`. Thx for clarifying.

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
**merge-assistance:** Global approval for this docs-only change.

**Pull request closed without merging**
