### PR TITLE
feat(platform-browser): Allow `sms`-URLs

### LINKED ISSUE #31462: Allow `sms`-URLs
# 🚀 feature request

### Relevant Package
This feature request is for @angular/platform-browser, but the related code is located in @angular/core

### Description
The method `DomSanitizer#sanitize` should allow resource-urls starting with `sms`

### Describe the solution you'd like
The [SAFE_URL_PATTERN](https://github.com/angular/angular/blob/master/packages/core/src/sanitization/url_sanitizer.ts#L37) should be updated to allow `sms` in addition to `mailto`, `ftp`, `tel` and `file`.
Current: `/^(?:(?:https?|mailto|ftp|tel|file):|[^&:/?#]*(?:[/?#]|$))/gi`
Updated: `/^(?:(?:https?|mailto|ftp|tel|sms|file):|[^&:/?#]*(?:[/?#]|$))/gi`

### Describe alternatives you've considered
The current workaround is using `bypassSecurityTrustResourceUrl`. This is not a problem in my case, since the URL is not user-defined and definitely starts with `sms`.

### PR DESCRIPTION
**Pull request by santoshyadavdev**
Fixes #31462

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31462

## What is the new behavior?
Allow sms in url

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong,

Can you assign this for review to someone.

**Comment by kapunahelewong** [comment]
> Hi @kapunahelewong,
> 
> Can you assign this for review to someone.

Hi @santoshyadav198613 I'm on the docs team and not as versed in `comp: core`. I believe, however, the codeowners for this are @mhevery and @IgorMinar, and they are automatically requested for you upon your editing those particular files and submitting the PR, so this PR is currently in their queue. Hope this helps!

**Comment by santoshyadav198613** [comment]
No problem thanks for update 😊.

**Comment by Coooi** [comment]
Any updates on this one? 
It would be nice to have it available soon.

**Comment by kyliau** [comment]
Could you please update the commit message to describe why this change is needed and why `sms:` is considered safe? Please also link to Closure sanitization library mentioned in the comment. This link might be helpful: https://github.com/google/closure-library/blob/bb7ea653194b590711614fd79b0a88a38a600740/closure/goog/html/safeurl.js#L440-L454

**Comment by santoshyadav198613** [comment]
> Could you please update the commit message to describe why this change is needed and why `sms:` is considered safe? Please also link to Closure sanitization library mentioned in the comment. This link might be helpful: https://github.com/google/closure-library/blob/bb7ea653194b590711614fd79b0a88a38a600740/closure/goog/html/safeurl.js#L440-L454

I have updated the commit message, please check.

**Review by IgorMinar — APPROVED** [review]
LGTM. Thank you! This looks like a useful addition especially for PWA apps

Reviewed-for: fw-security

**Review by jelbourn — APPROVED** [review]
LGTM

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Comment by santoshyadav198613** [comment]
Is it failing due to test case? please let me know so I can add one.

**Comment by jelbourn** [comment]
The Google presubmit looks like a flake, I triggered a rerun

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM 

Reviewed for: fw-core

**Comment by jelbourn** [comment]
Caretaker: Google presubmit failure was just already-failing targets

**Pull request closed without merging**
