### PR TITLE
build: add a Git .mailmap with my new name

### PR DESCRIPTION
**Pull request by mgol**
In this way my past contribution is mapped correctly.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- ~~Tests for the changes have been added (for bug fixes / features)~~
- ~~Docs have been added / updated (for bug fixes / features)~~

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Git thinks I am two different people.

Issue Number: N/A

## What is the new behavior?

Git knows about my new name and maps the old one to the new one.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by mgol** [comment]
The Travis failures are unrelated to my PR.

**Comment by IgorMinar** [comment]
@mgol does this affect github ui in some way or only git commands like `shortlog`?

**Comment by mgol** [comment]
@IgorMinar GitHub ignores `.mailmap`, opting instead to association based purely on to whichever GitHub account a mail belongs.

`.mailmap` is used by `git shortlog` (see e.g. what `git shortlog -nse` prints) & `git blame`. By default it doesn't affect `git log` or `git show`, mainly for historical reasons (see http://git.661346.n2.nabble.com/git-log-to-use-mailmap-by-default-td7570862.html). It can be made so in two ways:

1. By adding a `--use-mailmap` option: `git log --use-mailmap` or `git show COMMIT_HASH --use-mailmap`
2. By configuring Git globally to respect the `.mailmap` for logging: `git config --global log.mailmap true`. When set, this option is also respected for `git show`.

`.mailmap` affects what lots of apps outside of the Web GitHub UI present (mainly because Git respects it in many places). For example, it changes what WebStorm shows when you use its "Annotate" feature - a visual representation of `git blame` inside of the editor.

If you'd like, I can spend a moment to map other people's data; see e.g. what I did in the AngularJS repo: https://github.com/angular/angular.js/commit/8166dd40e4a1b8bc3d682261eede798d0e0ad9b8.

**Review by IgorMinar — COMMENTED** [review]
ok. can you change the commit label to "build", it's a better fit than refactor. otherwise lgtm

**Comment by mgol** [comment]
@IgorMinar PR updated.

**Review by IgorMinar — APPROVED** [review]

**Pull request closed without merging**
