### PR TITLE
refactor(core): Replace non-null assertion operator with property initialization

### PR DESCRIPTION
**Pull request by kubk**
Replace non-null assertion operator with property initialization.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:299436256:BASE:299436294:1583533405016:b0421b8c)

**Comment by alfaproject** [comment]
This increases bundle size for no actual benefit as far as I can see? It seems like a valid use of this TypeScript functionality.

Either that, or it should be `| undefined` and then the code adjusted for that.

**Comment by kubk** [comment]
@alfaproject Changing type to `Function | undefined` would require more code because the function type should be narrowed from `Function | undefined` to `Function` using if statements. Before:
```
this.resolve();
```
After:
```
if (this.resolve) {
  this.resolve();
}
```
The same applies to `this.catch`. Removing non-null assertion operator might prevent runtime errors in the future. There is a TSLint rule that describes the cons of this operator: https://palantir.github.io/tslint/rules/no-non-null-assertion/
The similar commits were already merged in the past: https://github.com/angular/angular/commit/1b0580a9ec31d72097bde3d057abd6ca3b82559d#diff-6a59e357bd47ab780ce7fcf88e9dfc50

**Comment by matsko** [comment]
@kubk please rebase.

**Comment by alfaproject** [comment]
@kubk I mean generated code. Check the down-levelled version in ES5 (it also uses more memory, btw)

Not sure what's the problem in keeping the non-null assertion operator to keep it lean. It exists for a reason. I would just remove the TODO comments or replace them with a more descriptive comment of why it's ok to have it, but I'm not a maintainer d:

**Comment by AndrewKushnir** [comment]
Hi @kubk, thanks for rebasing your PR. It looks like the `integration_test` is failing with payload size checks (see https://circleci.com/gh/angular/angular/648028#tests/containers/2). Could you please update the file mentioned in the error message? Thank you.

**Comment by kubk** [comment]
@AndrewKushnir Done. Do you know how to fix the rest of the issues?

**Comment by AndrewKushnir** [comment]
Hi @kubk, it looks like CI errors are flakes, I've restarted failing CI jobs.

I've also added @kara as a reviewer for this PR, since it increases payload size limits.

Thank you.

**Comment by mhevery** [comment]
Closing in favor of https://github.com/angular/angular/pull/39730

**Pull request closed without merging**
