### PR TITLE
chore(examples): generate plunkers for each example

### PR DESCRIPTION
**Pull request by Foxandxss**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: Tooling change
```

**What is the current behavior?** (You can also link to an open issue here)

Examples can't be run on a plunker

**What is the new behavior?**

All the examples will have a corresponding plunker to run it and also to be listed inside the API Reference

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

**Other information**:

This is the first step in bringing dynamic plunker examples to the API Reference.

This first step is on the angular side, so let me explain how this work.

Say we want some examples for the animation API reference and in fact we have one [here](https://github.com/angular/angular/blob/master/modules/%40angular/examples/core/animation/ts/dsl/animation_example.ts) already.

What we need to do is to create a `plnkr.json` file inside that folder, as a sibling of the example itself. We would like to give it a description for the plunker and a serie of tags:

``` json
{
  "description": "Animation",
  "tags": ["animation", "triggers"]
}
```

(By default, we add other tags like `angular2`, `example`, `api`).

Then if we run:

```
$ gulp build-plunkers
```

We will get a `plnkr.html` file in that exact folder. If we double click it, we will get redirected to plunker and then we can see our example there.

How does this work? We provide a list of default files needed to run each example (tsconfig, systemjs config, the css we use at angular.io...). That way you just need to focus on the important bits.

If you need to override any of the default files, you are free to do so just by creating a new file on the example.

---

On the technical side I had to bring in two dependencies. We already use `glob` but I needed a multi pattern library so I put `globby`. I didn't see an easy way to do it with `glob` and since `globby` is a wrapper around `glob`, the other usages around the code base could be changed as well.

The tool is based on what we do at angular.io but more oriented to the needs that this repo has. Also ported the tool we have to remove the docregions that some examples contain.

That being said, as a next step, I could tune this up to generate -builds plunkers as well, that won't be a problem, we just need to agree on a good way to achieve both.

Cheers :)

### CODE REVIEW

**Comment by Foxandxss** [comment]
Just realized it would need a change with the folder structure, but since the folder structure is subject to change, we will leave this PR on hold until we agree on something.

**Comment by Foxandxss** [comment]
Due to #11296 We should discuss what conventions are the examples going to use so this tool can generate better plunkers.

**Comment by Foxandxss** [comment]
Closing since we don't need this in this side anymore. A PR will come soon for the angular.io side.

**Comment by IgorMinar** [comment]
thanks

**Pull request closed without merging**
