### PR TITLE
docs: Typo

### PR DESCRIPTION
**Pull request by brahimlippe**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by IgorMinar** [comment]
Hi @brahimlippe, thanks for the fix, can you please sign the CLA following the instructions above? 
This is required for us to be able for accept it. Thank you!

**Review by IgorMinar — APPROVED** [review]
lgtm, but needs CLA

**Comment by brahimlippe** [comment]
Hello,

I am afraid I am not seeing the instructions. I don't mind someone else pushing the pull request if it's easier.

Regards

Brahim

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by sonukapoor** [comment]
Fixed in https://github.com/angular/angular/commit/0c6f02682854e3488b269d5711acf2fd9b0dcfa6

**Pull request closed without merging**
