### PR TITLE
docs: update CSP section to mention Angular's minimum requirements

### LINKED ISSUE #21711: Feature Request : Add Support for Strict Content Security Policy
# 🚀 Feature request

### Command (mark with an `x`)

- [x ] build

### Description

Lighthouse now throws error if No CSP is found in enforcement mode.

`Ensure CSP is effective against XSS attacks`

`No CSP found in enforcement mode` with `High Severity`

### Describe the solution you'd like

My knowledge about CSP is limited and I was going through these guides on CSP:  

http://web.dev
https://web.dev/csp-xss/ 
https://web.dev/strict-csp/

Apparently Nonce-based CSP seems easy to implement for SSR, for example for scripts, after Angular returns the final html, we can use string replace function on server side, to replace "<script" with "<script nonce="RANDOM_NONCE"" add RANDOM_NONCE in CSP header and I believe it should work. 

But this string replace work will have to be done for each request.

On the other hand, in case of Hash-based strict CSP if Angular CLI calculates hashes and include these hashes in script tags at build time, this could save us the string replace work that has to be done for each request in case of nonce. But there's a tradeoff, we will have to sync these hashes with our Server Side App so that appropriate headers could be added for generated response. Alternatively CSP could be generated by Angular CLI and added as `Content-Security-Policy` meta tag.

### PR DESCRIPTION
**Pull request by dgp1130**
Closes angular/angular-cli#21711.
Refs #6361.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Documentation content changes

## What is the current behavior?

Issue Number: angular/angular-cli#21711

CSP documentation does not state anything meaningful about Angular's requirements. In particular about `style-src unsafe-inline;`.

## What is the new behavior?

CSP section now states Angular's minimal requirements (`default-src self; style-src unsafe-inline;`) and links to the relevant issue for style-src because users are likely to ask why that is necessary and if/when it can be removed.

## Does this PR introduce a breaking change?

- [X] No

## Other information

I'm assuming that `style-src unsafe-inline;` is always necessary. Adding @jelbourn, to keep me honest here in case it only applies to certain view encapsulation strategies.

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
LGTM 

Reviewed-for: fw-security

**Comment by reduckted** [comment]
Is it worth mentioning that `script-src unsafe-eval` is required if you compile using a development configuration? Unless I'm mistaken, the development configuration results in webpack using `eval()` statements.

**Review by Splaktar — COMMENTED** [review]
@dgp1130 I have some additional guidance that should be added to the Angular CSP docs in https://github.com/angular/angular/issues/37631.

Thank you for looking into this and helping improve this much neglected area of the docs!

**Comment by dgp1130** [comment]
@reduckted, I'm not seeing an issue on an `ng new` app, adding `<meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' 'unsafe-inline';">` works just fine and doesn't reject any styles. @clydin, is there any option we have that would cause Webpack to generate something (like `eval()`) that would require something more specific than `default-src 'self';`?

Thanks @Splaktar, I wasn't aware of that issue or the suggestions in it. To address each of them here:

> * We should clearly state that allowing `'unsafe-inline'` in `style-src` is required for Angular applications.

Already mentioned.

> * We should clearly state that `'self'` is required for `style-src` and `script-src` in Angular applications.

I have `default-src 'self';` included which I think is probably sufficient for this case. I guess we could be more specific with `script-src 'self'; style-src 'self';` but I think the value of that is minimal and probably more confusing than worth explaining.

> * We should recommend `upgrade-insecure-requests`.

I hadn't heard of this one. I agree it's good practice, but for now I think we should stay focused on Angular's requirements rather than going into a general "best practices of CSP". A separate blog post might be better venue for that kind of conversation since a) there's nothing Angular-specific there and b) this stuff updates pretty regularly.

On a related note, I was playing with the [CSP evaluator](https://csp-evaluator.withgoogle.com/) and they recommend adding `object-src 'none';`. I think I'll leave that out for the same reasons as `upgrade-insecure-requests` unless people feel strongly that we should be more opinionated about CSP setups.

> * We should document that `connect-src` must be configured with `'self'` and any other font, script, or style sources that are retrieved by `@angular/service-worker`.

I believe this is covered by `default-src 'self';` but I could definitely see some users getting confused here. "I included `script-src 'self';` but now I'm getting CSP errors when using the service worker!" My thought is that if you're being more specific than `default-src 'self';` you probably have a least a basic understanding of CSP and are directly pulling on the additional complexity that it requires. So I don't think we need to specifically call this out (and doing so would probably add confusion rather than reduce it).

I think most of this comes down to how I'm using `default-src 'self';` as the baseline. Let me know if you feel strongly that we should be more specific and I update this to call out `script-src 'self'; style-src 'unsafe-inline'; connect-src 'self';` instead.

I also noticed that the [CSP evaluator](https://csp-evaluator.withgoogle.com/) explicitly calls out `default-src 'self';` as "problematic" for Angular.

Screenshot from 2021-09-24 14-31-50

I'm not sure exactly what that's referring to, is there some other caveat I'm not aware that we should pointing out here?

**Comment by clydin** [comment]
> @clydin, is there any option we have that would cause Webpack to generate something (like eval()) that would require something more specific than default-src 'self';?

Webpack should not be injecting `eval` into the output when using the CLI.  If this has been encountered with the latest Angular CLI, please open an issue within the Angular CLI repository with steps to reproduce so that this can be corrected.

JIT mode would require `unsafe-eval` for `script-src` due to the nature of JIT. However, new projects use AOT for both development and production. JIT is also typically not recommended, especially for production.

The live-reload development server leverages web sockets which would also need to be accounted for in `connect-src` if attempting to use CSP during development.  Although, while possible, attempting to use CSP during active development (outside of testing) with the development server could become cumbersome and impede developer productivity due to the configuration complexity, the fluid nature of development setups (different port usage, proxies, docker setups, etc.), and the need to manage two (or more) different CSP configurations. As well as ensuring that development CSP configurations do not accidentally end up being deployed.

> I'm not sure exactly what that's referring to, is there some other caveat I'm not aware that we should pointing out here?

CSP Evaluator appears to be referring to `Angular.js` and not Angular here.  From the paper that formed the basis of the site, `Angular.js` (even in its CSP mode) can be used to bypass CSP protections.  We may want to consider contacting the author of the site and ask if it is possible to clarify the usage of the Angular name in this case.

**Comment by reduckted** [comment]
> @dgp1130 I'm not seeing an issue on an `ng new` app, adding `<meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' 'unsafe-inline';">` works just fine and doesn't reject any scripts.

Creating a brand new app, adding that element and using `ng serve` results in this:

image

core.js:5235 maps to this line:
https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/core/src/util/security/trusted_types.ts#L122

> @clydin Webpack should not be injecting eval into the output when using the CLI.

Looks like I mistakenly thought it was webpack that was using `eval`. From the link I posted above, it seems to be Angular (but only when using a development configuration).

**Comment by JoostK** [comment]
@reduckted That would correspond with #43494. The Angular runtime creates named arrays for internal datastructures for easier debugging, but only in development mode:

https://github.com/angular/angular/blob/f6d5cdfbd74f2712309f23c952915f4ac7d001d7/packages/core/src/util/named_array_type.ts#L27-L43

There is a fallback there so I suppose that the application still works correctly (?), but the browser may have reported the CSP violation regardless.

**Comment by dgp1130** [comment]
Ah, thanks for bringing that up @reduckted, I was only looking in the browser console, but it looks like some errors were only shown in the issues panel. Sounds like it should be handled in #43587 (thanks for the quick fix @JoostK!), so we probably don't need to document anything in this PR.

I also reached out to the owners of CSP evaluator, and it does appear that it was referring to Angular.js. Still trying to confirm to be to sure, but it seems like the text should be adjusted soon to clarify that point.

**Review by jelbourn — APPROVED** [review]

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Pull request closed without merging**
