### PR TITLE
Remove VE code from language service package

### PR DESCRIPTION
**Pull request by atscott**
This PR has two parts:

1. Remove the VE code from the language service package. We already do not bundle this since VE is not supported in v13+
2. Move the language service code out of the ivy subfolder. Since there is only 1 engine supported, we do not need to identify it with a unique name.

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by atscott** [comment]
This PR was merged into the repository by commit 670cd10e3062918fbd8d50640f6ead7fc04ed25c.

**Comment by dzhavat** [comment]
@atscott Will the removal of VE have an effect on how the "Angular Language Service" VS Code extension works? Meaning when a new version of the extension is released with this change in it and my project is not using Angular v13, will it matter?

**Comment by atscott** [comment]
@dzhavat For the Language Service extension in VSCode, we pull in the last version of `12.2` and use that to support older projects that are still using View Engine.

**Comment by dzhavat** [comment]
Thanks for the clarification.

**Pull request closed without merging**
