### PR TITLE
fix(platform-server): provide XhrFactory for HttpClient

### LINKED ISSUE #18199: Angular 4.3 HttpClient throws 'XMLHttpRequest is not defined' in Node environment (Angular Universal)
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Using HttpClient from `import { HttpClient } from '@angular/common/http'` throws `ReferenceError: XMLHttpRequest is not defined
 ` when rendered using `ngExpressEngine` from `import { ngExpressEngine } from '@nguniversal/express-engine'`

## Expected behavior

To not throw an error just like the original Http client.

## What is the motivation / use case for changing the behavior?

A temporary fix is to use this line of code at the top of the Node server:

`(global as any).XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;`

## Environment

<pre><code>
Angular version: 4.3.0

Browser:
- [x] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by alxhub**
Fixes #18199

### CODE REVIEW

**Review by vikerman — APPROVED** [review]

**Comment by JohnGalt1717** [comment]
When is this going to hit stable? HttpClient should never have been released with SSR broken given that this is a basic integrated set of functionality for Angular at this point.

**Comment by dottodot** [comment]
When is this fix going to be added? Still getting the error in rc.9

**Comment by vikerman** [comment]
Please provide a repro github. Can't reproduce this

**Comment by dottodot** [comment]
Seems the problem was due to ng-inline-svg, the latest version fixes the issue.

**Pull request merged**
