### PR TITLE
build(docs-infra): update Angular framework/Material/CLI to latest 11.x versions

### PR DESCRIPTION
**Pull request by gkalpak**
This PR updates the Angular framework, Angular Material and Angular CLI packages to the latest 11.x versions (namely 11.0.0-rc.2 for framework and CLI and 11.0.0-rc.1 for Material).

See the individual commits for more details.

### CODE REVIEW

**Comment by gkalpak** [comment]
I had to downgrade `karma` to version 5.1.1, because of a regression in version 5.2.0: karma-runner/karma#3560
It has been fixed with karma-runner/karma@05dc28801627e3ce7054ae548046714dc2cf7a5e on master, but the fix is not included in the latest release (v5.2.3).

**Comment by petebacondarwin** [comment]
Typos in 1st commit 😱 

```
The valuesa are take from these...
```
->
```
The values are taken from these...
```

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: size-tracking

Nice these updates actually bring the sizes down.

**Review by petebacondarwin — APPROVED** [review]
Perhaps create an issue to track the re-upgrade to karma when it gets fixed?

**Comment by gkalpak** [comment]
Thx, @petebacondarwin! Fixed the typos (and removed a bogus TODO: 9658cc66377fef2689a5ef9e1a88b66324c1488b).

I don't think we need a tracking ticket for `karma`, since it would be upgraded as part of the regular "upgrade CLI version" process (nor do we have a formal process for tracking these tracking issues for `docs-infra` anyway 😛).

**Comment by gkalpak** [comment]
I rebased on master and added two more commits to upgrade CLI/Framework/Material to latest 11.0.x versions.
(I kept the commits separate to be able to see how the payload sizes are affected by each version. Spoiler alert: There were some regressions in latest versions.)

**Review by IgorMinar — APPROVED** [review]
LGTM! Thank you!

Reviewed-for: global-approvers, size-tracking

**Pull request closed without merging**
