### PR TITLE
docs: fix attributes for 'label' and 'input' elements

### PR DESCRIPTION
**Pull request by huegogh**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by huegogh** [comment]
@googlebot I signed it!

**Review by petebacondarwin — APPROVED** [review]
Good spot @huegogh  - thanks.

Reviewed-for: global-docs-approvers

**Comment by petebacondarwin** [comment]
@huegogh - please can you amend the commit message to follow our [required syntax](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit) and then force-push your branch?
I would suggest simply adding `docs:` would be enough for this small fix:

```
docs: fix attributes for 'label' and 'input' elements
```

**Comment by huegogh** [comment]
@petebacondarwin Thank you for the feedback, amendment made to commit message. You also requested I force push my branch. I apologize but I do not know how to complete that request.

**Comment by petebacondarwin** [comment]
> @petebacondarwin Thank you for the feedback, amendment made to commit message. You also requested I force push my branch. I apologize but I do not know how to complete that request.

Can you try this?


```
git commit --amend -m"docs: fix attributes for 'label' and 'input' elements"
git push --force-with-lease
```

**Comment by petebacondarwin** [comment]
I'll do the rebase etc for you.

**Pull request closed without merging**
