### PR TITLE
feat(service-worker): add support for ignoring specific URLs

### LINKED ISSUE #20404: Feature request: ngsw navigation path exceptions
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The service worker isNavigationRequest() function assumes that any page navigation within scope is to be handled by the service worker. There are cases were this is not desired behavior.

## Expected behavior

Provide a means of configuring exception paths that are checked in isNavigationRequest().

## What is the motivation / use case for changing the behavior?

Example need: Hosting server services and authentication via Feathers.js expects to navigate to the path /auth/google to initiate an OAUTH2 authentication via Google; with completion of authentication directing back to /auth/google/callback. These requests must go through to the server. Currently ngsw-worker.js intercepts these requests and return the start page HTML.

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.10.1
- Platform:  Mac

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by gkalpak**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
```
[x] Feature
```

## What is the current behavior?
The ServiceWorker will redirect navigation requests that don't match any `asset` or `data` group to the specified index file. Yet, sometimes it is desirable to configure the SW to ignore specific URLs (even for navigation requests) and pass them through to the server.

Issue Number: #20404

## What is the new behavior?
This commit adds support for specifying an optional `ignoredUrlPatterns` list in `ngsw-config.json`, which contains URLs or simple globs (currently only recognizing `*` and `**`). Requests matching these URLs or patterns will not be handled by the SW.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Fixes #20404.

### CODE REVIEW

**Comment by gkalpak** [comment]
TODOs

- [ ] Update the [SW Config][1] guide.


TODECIDEs

- [ ] Should matching be case-insensitive?
    Does it make a difference or are URLs always lowercased by the browser for example?
    For reference, matching is case-sensitive in other places, such as asset-/data-groups.

- [ ] Do we need to support negated patterns?
    This would slightly complicate the implementation.
    Since ignored URLs should be the minority, not the norm, I think not supporting negatd patterns is probably fine.

- [ ] Do we want to support RegExps (instead of or in addition to globs)?
    The basic globbing we provide now is too limiting (and can be confusing for people expecting full glob support).
    I would love for us to support RegExps 🙏

- [ ] Do we want to support not handling such requests at all (i.e. do not call `event.respondWith(...)` at all)?
    Right now we do `scope.fetch(...)`, which (a) shows up as if the SW did handle the request and (b) is subject to SW limitations.
    See #23012 for a usecase.

cc @alxhub 

[1]: https://angular.io/guide/service-worker-config

**Review by alxhub — APPROVED** [review]

**Comment by gkalpak** [comment]
Oh, I didn't know `.respondWith()` should called synchronously 😞

**Comment by gkalpak** [comment]
@coryrylan wrote (in https://github.com/angular/angular/issues/20404#issuecomment-377438627):

Would a list of regexes be more flexible?
Workbox has a `navigateFallbackWhitelist` and `navigateFallbackBlacklist` properies to take a list of regexes to scope the service worker to. This is actually the feature that is keeping us on Workbox instead of migrating to @angular/service-worker. We use `navigateFallbackWhitelist` to only apply to the angular specific pages as we are converting a large enterprise app.

https://developers.google.com/web/tools/workbox/modules/workbox-build

**Comment by gkalpak** [comment]
I would love to have regexp support (as stated in https://github.com/angular/angular/pull/23025#issuecomment-376580968 :grin:).

Things to consider:
- Supporting only regexps , while other places support only globs, will be confusing (from a public API standpoint).
- Supporting both globs and regexps, will require a way to differentiate which is used (because both can look similar).
  Solutions (off the top of my head):
  1. `{type: 'regex', pattern: '...'}` vs `{type: 'glob', pattern: '...'}`.
      Pros: Clear. Extensible (e.g. we can easily add more types in the future (`prefix', `full`)).
      Cons: Verbose.
  2. `'re:...'` vs `glob:...`.
      Pros: Somewhat clear. Somewhat extensible. Somewhat not verbose.
      Cons: Somewhat idiomatic. Not as much extensible. Slightly more verbose.

@alxhub, WDYT?

**Review by IgorMinar — APPROVED** [review]
lgtm for public api changes

**Comment by gkalpak** [comment]
For future reference:
Discussed this with @alxhub and decided to implement the following:
1. Use one list for both positive and negative matches (more inline with the rest of the APIs). No RegExps for now.
2. Look into improving our globbing support (in a follow-up PR). Could build on top of [aio/tools/firebase-test-utils/FirebaseGlob.ts][1].

[1]: https://github.com/angular/angular/blob/5db9ab12c022886ff75f23e08dde75a4f0e6086b/aio/tools/firebase-test-utils/FirebaseGlob.ts

**Comment by gkalpak** [comment]
Alternative implementation (supporting both positive and negative patterns) in #23339.

**Comment by IgorMinar** [comment]
superseded by #23339

**Pull request closed without merging**
