### PR TITLE
docs(core): correct TypeScript version range for 17.0.x

### PR DESCRIPTION
**Pull request by LayZeeDK**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The TypeScript version range for Angular 17.0.x is listed as `>=4.9.3 <5.3.0` on [angular.io](https://angular.io/guide/versions) and [angular.dev](https://angular.dev/reference/versions).

Issue Number: N/A

## What is the new behavior?
The TypeScript version range for Angular 17.0.x is listed as `>=5.2.0 <5.3.0` on [angular.io](https://angular.io/guide/versions) and [angular.dev](https://angular.dev/reference/versions).

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- #51792 removed support for versions of TypeScript older than 5.2.0
- #52514 contributed the correct version range but was closed

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi Lars, can you do the same change on the adev file ?

**Comment by LayZeeDK** [comment]
Is `main` the correct target branch?

**Comment by JeanMeche** [comment]
Yes it’s the one we deploy from 👍

**Comment by JeanMeche** [comment]
@LayZeeDK Do you mind rebasing your commit on the latest one ? You currently have a conflict

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 0e150c4ae94c118966fc24b2021646e16352a0eb.

**Comment by LayZeeDK** [comment]
Thank you, @JeanMeche and @jessicajaniuk

**Pull request closed without merging**
