### PR TITLE
docs(animations): Removed erroneous bracket - Resolves issue: 33459

### PR DESCRIPTION
**Pull request by rkatka**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 33459
https://github.com/angular/angular/issues/33459

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by kapunahelewong — APPROVED** [review]
Perfect. Thank you @rkatka!!

**Comment by kapunahelewong** [comment]
merge assistance: global approval for docs changes

**Comment by kapunahelewong** [comment]
Hey @rkatka I'd like to mark this for merge but I just noticed the commit message. Could you amend it to:
```
docs: remove erroneous brack in animations guide

Fixes #33459 
```

That should automatically close that issue when it's merged. Here are [my notes on amending a commit](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) if you'd like them. Please tag me when you're ready or if you have any questions.

**Comment by rkatka** [comment]
@kapunahelewong - I just pushed the updated commit.

**Comment by kapunahelewong** [comment]
merge assistance: global approval for docs changes

**Pull request closed without merging**
