### PR TITLE
refactor(router): remove unused facade imports

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
I'm working on bundling and trying to see what / why router uses from facades. Spotted several unnecessary imports while doing this work, hence this PR.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
BTW, I thought that we've got automatic checks for this...

**Comment by gkalpak** [comment]
Apparently, the automated chcks use an opensource tool: @pkozlowski-opensource :stuck_out_tongue:

**Comment by pkozlowski-opensource** [comment]
@gkalpak yeh, we don't have those automatic checks in place now, but I was working on determining which facade APIs are used by http / router....

**Comment by btford** [comment]
@pkozlowski-opensource can you rebase?

**Comment by pkozlowski-opensource** [comment]
@btford rebased. PRs get bit-rotten in a matter of hours those days :-)

**Comment by pkozlowski-opensource** [comment]
Closing as it got bit-rotten.

**Pull request closed without merging**
