### PR TITLE
docs: add Dmytro Mezhenskyi to GDE resources

### PR DESCRIPTION
**Pull request by DMezhenskyi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by twerske — APPROVED** [review]
LGTM - welcome!

**Comment by twerske** [comment]
@DMezhenskyi looks like CircleCI is failing with `Error: The following pictures exceed maximum size limit of 30kb:` - can you reduce to image size?

**Comment by DMezhenskyi** [comment]
@twerske Hi! Just pushed a fix. Now it should be fine

**Comment by DMezhenskyi** [comment]
@twerske Hi! Just pushed a fix. Now it should be fine

**Comment by AndrewKushnir** [comment]
@DMezhenskyi thanks for updating the PR. It looks like CLA was not signed, so we can not proceed with the merge. Could you please have a look at the steps described in https://github.com/angular/angular/pull/43282#issuecomment-911620716 and let us know when it's done (by leaving a comment here), so we can merge the PR? Thank you.

**Comment by DMezhenskyi** [comment]
@googlebot I signed it!

@AndrewKushnir sorry, I didn't notice it. Now it should be fine

**Comment by DMezhenskyi** [comment]
@googlebot I fixed it

**Comment by AndrewKushnir** [comment]
@DMezhenskyi thanks for updating the PR. I'm adding it to the merge queue and it will be merged soon. Thank you.

**Comment by AndrewKushnir** [comment]
@DMezhenskyi I just noticed that there are 2 commits in this PR (the second one changes the avatar size). Could you please squash 2 commits into one?

**Comment by DMezhenskyi** [comment]
Hi @AndrewKushnir ! I thought that it would be squashed during the merge. Anyway, I just squashed those commits into one.

**Pull request closed without merging**
