### PR TITLE
fix(aio-searchbox): style correctly on safari

### PR DESCRIPTION
**Pull request by Haroenv**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

screen shot 2017-11-03 at 16 40 06

## What is the new behavior?

screen shot 2017-11-03 at 16 39 54

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Thx for spotting this. Looks much better now :smiley:
Can you please change the commit message to adhere to our [commit message guidelines][1] (and make CI happy). E.g. something like `fix(aio): style correctly on Safari`.

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by Haroenv** [comment]
updated @gkalpak, what was wrong with the first commit message, the `-` in the scope?

**Comment by gkalpak** [comment]
Thx @Haroenv ✨ 
As you can see [here][1], only specific values are allowed as scope (`aio` is one of them, `aio-searchbox` isn't :grin:).

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#scope

**Comment by Haroenv** [comment]
👌 thanks for merging @vicb

**Pull request merged**
