### PR TITLE
Fixing ! for #24571

### PR DESCRIPTION
**Pull request by vyom1611**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #24571

## What is the new behavior?
- removing "!" from multiple files and adding default initializers in the forms package

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@vyom1611 Looks like there's some issues with lint and tests. Can you rebase to upstream/main and squash your commits? Looks like you have a merge commit in there that needs to be removed.

**Comment by vyom1611** [comment]
Hey if you could tell me how to squash my commits, that would be really appreciated. I have tried squashing before but I end up messing the rebase.

**Comment by jessicajaniuk** [comment]
@vyom1611 To rebase and squash, do this: make sure to `git fetch upstream` to get the latest changes from the angular repository. Then in your branch run `git rebase main -i` to do an interactive rebase. This should allow you to fixup or drop any unnecessary commits. After you finish that rebase, force push using `git push [origin name] [branch name] --force`.

**Comment by vyom1611** [comment]
What do I do in the interactive rebase?

**Comment by jessicajaniuk** [comment]
In an interactive rebase, you'll see a screen showing each of the commits in your PR. You can drop (remove a commit from a PR, like an unwanted merge commit), fixup (squash the change into the previous commit dropping the commit message), re-order commits, reword commit messages, and a few other things. Once you're done, you should have a rebased set of commits you want to keep that you can force push.

**Comment by vyom1611** [comment]
So, in the rebase, do I need to pick the current branch(fixing_!_for_24571) and squash it into my main branch?

**Comment by jessicajaniuk** [comment]
@vyom1611 A rebase is basically saying "Hey git, bring all the latest of the other branch into mine and make that the new base of this PR". So it's pulling all the latest of main into your PR and starting from there instead of when you created the PR initially. So you're still working in _your_ branch. An interactive rebase allows you to adjust the history of your own branch / PR's commits. So pick your first commit to keep that, and then fixup everything else you want to keep into it. You can then drop everything else you don't want to keep. It would look something like this in an interactive rebase:

Screen Shot 2022-10-13 at 3 53 43 PM

**Pull request closed without merging**
