### PR TITLE
docs(Http Guide): update HttpClientXsrfModule use

### PR DESCRIPTION
**Pull request by dennis-johnson-dev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The configuration for the HttpClientXsrfModule is noted in the docs to have a `withConfig` method, when the actual method has a `withOptions` method - https://github.com/angular/angular/blob/54e02449549448ebab6f255f2da0b4396665c6f0/tools/public_api_guard/common/http.d.ts#L1010

Issue Number: N/A

## What is the new behavior?

Documentation reflects source code

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by vicb** [comment]
The commit message should be "docs(aio): update HttpClientXsrfModule use in the Http Guide".
Thanks

**Comment by songawee** [comment]
Gotcha, sounds good. I fixed the commit message.

**Comment by songawee** [comment]
@vicb, anything else I need to do for this pr to get it over the line?

**Comment by kapunahelewong** [comment]
@songawee Thank you for this - it was a good catch. I see though that #19202 was a duplicate and happened to get merged first. Would you be all right with closing this one out?

**Comment by songawee** [comment]
@kapunahelewong It doesn't look like that duplicate issue ever got merged, only closed? This looks like the real PR that fixed the issue - https://github.com/angular/angular/pull/21185. 

The angular.io docs - https://angular.io/guide/http#configuring-custom-cookieheader-names does show that the page has been updated so I'm good.

I'm okay with closing 👍. Thanks for reaching out.

**Comment by kapunahelewong** [comment]
@songawee ah yes, my mistake. Thank you! :)

**Pull request closed without merging**
