### PR TITLE
fix(core): hardening rules related to the attribute order on <iframe> elements

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit updates the logic related to the attribute order on <iframe>s and makes the rules more strict. There is a set of <iframe> attributes that may affect the behavior of an <iframe>, this change enforces that these attributes are applied before an `src` or `srcdoc` attributes are applied to an <iframe>, so that they are taken into account.

If Angular detects that some of the attributes are set after the `src` or `srcdoc`, it throws an error message, which contains the name of an attribute that is causing the problem and the name of a Component where an <iframe> is located. In most cases, it should be enough to change the order of attributes in a template to move the `src` or `srcdoc` ones to the very end.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:485451696:BASE:485451739:1667346370843:feec20b7).

**Note: this PR would also require a TGP.**

**Comment by AndrewKushnir** [comment]
[TGP](https://test.corp.google.com/OCL:485451696:BASE:485479210:1667356575745:43467f13).

**Review by alxhub — APPROVED** [review]
Reviewed-for: fw-core,fw-security,public-api,size-tracking

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api 
Reviewed-for: size-tracking
Reviewed-for: fw-core 
Reviewed-for: fw-security

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api
Reviewed-for: size-tracking
Reviewed-for: fw-core
Reviewed-for: fw-security

**Review by alxhub — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 2d08965b1a772609cea7f1fb2a11bce9c6337ea6.

**Pull request closed without merging**
