### PR TITLE
feat(core): Add `QueryList#forEach`

### LINKED ISSUE #6314: Add `forEach` to QueryList
Currently, the "best" way to loop through the result of a QueryList (as done in the ui-tabs sample at http://plnkr.co/edit/9E7T5XyLvn0SNQTOrVrJ?p=preview) is to use `.toArray().forEach()`. Here `.toArray()` copies the original array before allowing you to iterate through it. At least that's what I'm seeing when I'm running through the code.

Also, since it supports `map`, `reduce` and `filter` already, I think `forEach` should generally be available too.

### PR DESCRIPTION
**Pull request by lacolaco**
Add `forEach` to QueryList.

Close #6314

### CODE REVIEW

**Comment by jelbourn** [comment]
@vsavkin please review

**Comment by btford** [comment]
After rebasing, this fails: https://travis-ci.org/angular/angular/jobs/108405209#L1029-L1045

Looks like it should be added to the core API somewhere. @vsavkin can you please help @laco0416 make this change?

**Comment by vsavkin** [comment]
@laco0416 could you modify `public_api_guard/public_api_spec.js` and add `QueryList.forEach(fn:(item: T) => void):void` to CORE. You can run:

```
gulp build.js.cjs
gulp check-public-api
```

to check that it works.

**Comment by laco0416** [comment]
@vsavkin Thank you! I try to do it soon.

**Comment by laco0416** [comment]
@btford @vsavkin I've fixed it!

**Comment by matsko** [comment]
Landed as e7470d557df0400a812d84551524970cb5f12eee

**Comment by laco0416** [comment]
Thanks all!

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166513.
------------------------------------------------------------------------------------------------------------


[[bace2d55bb593c8359695965f12e46a66471ebbb-673073924]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166519.
------------------------------------------------------------------------------------------------------------


[[bf4943a9940794912b2ad7e21570df6ce738c9cb-673073937]]

**Pull request closed without merging**
