### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by mvetsch**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@mvetsch thanks for creating this PR and improving Angular docs. It looks like the CLA has not been signed yet, so we can not proceed with this PR. Could you please [follow the instructions here](https://github.com/angular/angular/pull/44535/checks?check_run_id=4576426441) to sign the CLA? Please let us know (by leaving a comment in this thread) when you sign the CLA, so we can proceed with the review. Thank you.

**Comment by alxhub** [comment]
Additionally, the commit message here is a bit too empty. Can you include a little extra detail (the file being edited and the particular typo change being made)?

**Review by Hossein13M — APPROVED** [review]
This pull request fixes a typo in documentation.

**Review by mgechev — APPROVED** [review]

**Comment by atscott** [comment]
Closing since the CLA issue hasn't been addressed for some time now. Please sign the CLA and open a new PR if you'd still like to contribute this fix! Thank you!

**Pull request closed without merging**
