### PR TITLE
docs(aio): Change HTTP interceptors which use State Transfer API

### PR DESCRIPTION
**Pull request by didyk**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks for the PR @didyk! Are you still interested in making this change?

**Comment by didyk** [comment]
@brandonroberts hello, sure

**Comment by brandonroberts** [comment]
Great. Will you rebase against master and provide more detail about what the example is doing?

**Comment by brandonroberts** [comment]
@didyk re-open this PR if you're still interested in making this change.

**Pull request closed without merging**
