### PR TITLE
feat_drop(core): drop `ChangeDetectionStrategy.OnPushObserve`

### PR DESCRIPTION
**Pull request by tbosch**
This feature was experimental it has
conceptual performance problems,
as setting up observables is slow.

Use `OnPush` instead.

### CODE REVIEW

**Comment by tbosch** [comment]
The failure is due to Saucelabs being flaky, so this is good to merge!

**Comment by vsavkin** [comment]
Merged via https://github.com/angular/angular/commit/f60fa147679cacca3a786be9851cbff7827dcb4b

**Comment by tejainece** [comment]
Why is this being dropped? What conceptual problems?

`OnPush` has very bad performance.

**Comment by tbosch** [comment]
We keep `OnPush`, but `OnPushObserve` has the problem that we need to subscribe to all objects that we see on the path, which turned out to be slow.

**Comment by tejainece** [comment]
Ok.

I looked into the code that makes OnPushObservable work, looks neat to me.

I have a huge MMO game built on Dart/Angular2. Works pretty well. But the issues i faced are:

1. **Default change detection**
Fires too often when there are too many bindings, it acts as if a heavy black hole is sitting in the middle of the processor, wrapping the space around and slowing the time down. Opps sorry for *Interstellar* analogy :D.

2. **OnPush**
Maybe, I don't yet know how to use it. Correct me if i am wrong. 

    1. Use **immutable and swap** the whole object when there is change
    This is because OnPush detects changes only on inputs. But the issue is easily evident, when you can't use immutables and change whole object when only part of it changes or just a field changes.
    2. Use **Streams/Observables** when object properties change and call `markForCheck()`. This works brilliantly well. But trust me there is nothing more boring than doing this for every component.

I think it is the job of the framework to do this. From what I have observed, `OnPushObservable` performs better than default and easy to setup/less bugs than OnPush. 

if you would like, I can make three demo versions of the game, each with different approaches mentioned above.

But i think the performance problem you are talking about is setting the observable up. I think the ease and performance we gain during runtime over-weights little higher set up times. I don't notice much difference in my game. And i think, it should be up to the developer to choose better application-specific trade off.

`ÒnPushObservable` are very good selling point both for Dart and Angular2.

**Comment by tejainece** [comment]
Are you guys still going with removing OnPushObserve?

**Pull request closed without merging**
