### PR TITLE
docs(changelog): fix typo AplicationRef => ApplicationRef

### PR DESCRIPTION
**Pull request by itamark**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[x ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
There was a typo.

**What is the new behavior?**
Typo in docs was fixed.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Fixing typo AplicationRef => ApplicationRef

### CODE REVIEW

**Comment by itamark** [comment]
I signed it!

**Comment by DzmitryShylovich** [comment]
Pls change commit msg according to https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by itamark** [comment]
Hi! Like this?
https://github.com/itamark/angular/commit/6a7a93f06cead7f550154f491691b399e46357de#commitcomment-20089971

**Comment by DzmitryShylovich** [comment]
yeah `docs(changelog): fix typo AplicationRef => ApplicationRef`

**Comment by alxhub** [comment]
Hi @itamark. Thanks for the PR. Please rewrite your commit message as @DzmitryShylovich suggests, before I merge this. Our changelog script uses those tags to properly generate the changelog, so we need it to be correct.

**Comment by DzmitryShylovich** [comment]
commit message not title :)

**Comment by itamark** [comment]
I know I'm trying to figure out how to change the msg. Might just go
another commit

**Comment by DzmitryShylovich** [comment]
Yeah, u can create a dummy commit then squash them.

**Comment by vicb** [comment]
`git commit --amend --no-edit -m 'new messageg'`

**Comment by itamark** [comment]
Okay - I just created a new one: https://github.com/angular/angular/pull/13284

**Pull request closed without merging**
