### PR TITLE
docs: fix typo in component overview

### PR DESCRIPTION
**Pull request by imkikus**
Fixes #[PR](https://github.com/angular/angular/issues/39424)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 39424

## What is the new behavior?
Fixed typo in tag name

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Hi @imkikus - thanks for sending in this PR to fix the typo you found.
In order to land this we need two things:

1. Sign the CLA as described above.
2. Fix the commit message format - it should look like `docs: fix typo in component overview`.

To change the commit message, you will need to amend the commit and force push to your branch on GH. Let me know if you need help with that.

**Comment by imkikus** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Comment by imkikus** [comment]
> Hi @imkikus - thanks for sending in this PR to fix the typo you found.
> In order to land this we need two things:
> 
> 1. Sign the CLA as described above.
> 2. Fix the commit message format - it should look like `docs: fix typo in component overview`.
> 
> To change the commit message, you will need to amend the commit and force push to your branch on GH. Let me know if you need help with that.

Hi @petebacondarwin 

1) I've signed the CLA
2) Fixed the commit message in the format you specified. Thanks for letting me now about that! Cheers!

**Review by petebacondarwin — APPROVED** [review]
Great! That is a quick turnaround. Thanks for that.

I see you also added a reference to your issue too! Nice. If you want to be even more efficient you can change the `Refer ...` to `Fixes ...` in the commit message and then the issue will be automatically closed (I believe) when we merge the PR.

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by imkikus** [comment]
> Great! That is a quick turnaround. Thanks for that.
> 
> I see you also added a reference to your issue too! Nice. If you want to be even more efficient you can change the `Refer ...` to `Fixes ...` in the commit message and then the issue will be automatically closed (I believe) when we merge the PR.

@petebacondarwin Addressed this one too :smile:

**Pull request closed without merging**
