### PR TITLE
build: Zone bazel refactor

### PR DESCRIPTION
**Pull request by JiaLiPassion**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

Some refactor about zone.js bazel build
1. remove non used code
2. refactor some complex code (such as remove sourcemap comment)

Add a new optional parameter `sourcemap` here, https://github.com/angular/angular/pull/34532/files#diff-653388f9d55f0ae80bba217809819c24R276

### CODE REVIEW

**Comment by JiaLiPassion** [comment]
@gregmagolan, could you help me to review this refactor PR, thanks.

**Review by gregmagolan — APPROVED** [review]
Nice cleanup.

You could probably remove the need for the genrule if you didn't go with the default.bzl rollup_bundle and just replicated in your zone_rollup_bundle macro the minimal steps that create the output name that you want. That being said, now that you've abstracted it into your zone_rollup_bundle that would be easy to do in a follow up PR as well.

**Comment by JiaLiPassion** [comment]
@gregmagolan, thank you for the review, 

> You could probably remove the need for the genrule if you didn't go with the default.bzl rollup_bundle and just replicated in your zone_rollup_bundle macro the minimal steps that create the output name that you want. That being said, now that you've abstracted it into your zone_rollup_bundle that would be easy to do in a follow up PR as well.

Got it, I will try to create another PR to make the refactor you suggested. Thanks.

**Comment by JiaLiPassion** [comment]
@josephperrott, could you take a look at this PR, if it is OK, I can continue to work on the follow up refactor PR for bazel of zone.js, thanks!

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by kara** [comment]
@JiaLiPassion Can you rebase this? Our merge script is complaining :)

**Comment by JiaLiPassion** [comment]
@kara, sure, I just rebased, please review, thanks!

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:296250508:BASE:296250554:1582225220667:db148467)

**Pull request closed without merging**
