### PR TITLE
refactor(docs-infra): remove unnecessary tsconfig.json file

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
the tsconfig.json file in aio/content/examples does not seem necessary
anymore as it was only used for tslinting and tslint has been removed
from the examples in PR #43592 and PR #43746

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Issue

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

 - as discussed [here](https://github.com/angular/angular/pull/43218#issuecomment-940198406)
 
 - @gkalpak :slightly_smiling_face:

### CODE REVIEW

**Comment by dario-piotrowicz** [comment]
@gkalpak I just removed the file, since I understood that we're pretty sure it is not needed, please let me know if you believe I need to check anything regarding this change :slightly_smiling_face:

**Review by petebacondarwin — APPROVED** [review]
I "think" this is OK, since the examples are mostly all CLI based now, which will contain their own tsconfig.json files.

**Review by gkalpak — APPROVED** [review]
Thx, @dario-piotrowicz :+1:

(NOTE: I have rebased this on master to make CI happy.)

**Comment by atscott** [comment]
This PR was merged into the repository by commit 68d18a0422fe4829967aa5bfd1fc82eb75587908.

**Pull request closed without merging**
