### PR TITLE
fix(router): export the RouterScroller class and the createRouterScro…

### PR DESCRIPTION
**Pull request by timstoddard**
…ller function from the @angular/router package

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] (N/A) Tests for the changes have been added (for bug fixes / features)
- [X] (N/A) Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

RouterScroller and createRouterScroller cannot be imported from @angular/router. When I tried to import them, my IDE (WebStorm 2018.2) created the following lines:
```
import { RouterScroller } from '@angular/router/src/router_scroller';
import { createRouterScroller } from '@angular/router/src/router_module';
```
but then I got the following errors
```
ERROR in ./src/oc/app/core/app-column-router/app-column-router.module.ts
Module not found: Error: Can't resolve '@angular/router/src/router_module' in 'C:\Code\stash\spaldingLabs\suite\clients\operation-center\src\oc\app\core\app-column-router'

ERROR in ./src/oc/app/core/app-column-router/app-column-router.module.ts
Module not found: Error: Can't resolve '@angular/router/src/router_scroller' in 'C:\Code\stash\spaldingLabs\suite\clients\operation-center\src\oc\app\core\app-column-router'
```

Issue Number: N/A

## What is the new behavior?
RouterScroller and createRouterScroller can now be imported from @angular/router

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by JoostK** [comment]
Hi @tomstoddard,

Could you elaborate on why you classify this as bug? At the moment this simply isn't considered public API so why do you believe it should have been?

Personally I would classify this as feature request, in which case you'd need to enlighten us about the use-cases you have. Remember, all public API must be supported and isn't really supposed to change, so keeping stuff internal allows for flexibility in the future.

**Comment by timstoddard** [comment]
@JoostK the company I work for is building an Angular app that uses a custom routing module (builds on the default RoutingModule) and so it constructs a custom list of providers in the `AppColumnRouterModule.forRoot` method. I need a way to provide the RouterScroller class as we want that functionality, but could not find a way to do it with the existing exports from @angular/router.

**Comment by trotyl** [comment]
@JoostK With `NgModule` concept itself becoming optional, I think it should be reasonable that every provider to be exported, otherwise an `NgModule`-less usage is impossible.

**Comment by IgorMinar** [comment]
Thanks for the PR but we really don't want to export these symbols for now because they have not been designed/reviewed for public use, so I suggest you create your custom router by delegating to the original router using this pattern: https://stackblitz.com/edit/router-delegate

**Pull request closed without merging**
