### PR TITLE
feat(router): helper functions to convert class guards to functional

### PR DESCRIPTION
**Pull request by atscott**
This commit introduces helper functions to easily convert `Injectable`s with functions compatible with `Route` guards to the corresponding guard functions. These functions will serve to aid in migrating off of the now deprecated class-based guards, but also provide an easy avenue to still defining guards as `Injectable` classes if that is desired.

Reviewer notes: Open to bikeshedding the API here. We could just have separate functions for each type of guard. I thought grouping them would help in discovery but maybe it's more confusing than the alternative.

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: dev-infra

**Review by dylhunn — APPROVED** [review]
reviewed-for: public-api, global-docs-approvers

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by destus90** [comment]
@atscott 
Does the Angular team plan to migrate existing code in favor to use these functions or should we do it ourselves?

**Comment by atscott** [comment]
@destus90  there will be a migration

**Pull request closed without merging**
