### PR TITLE
docs: add bower info to DEVELOPER.md

### PR DESCRIPTION
**Pull request by kwalrath**

### CODE REVIEW

**Comment by mhevery** [comment]
LGTM, but @kwalrath please double check @pkozlowski-opensource's [comment](https://github.com/angular/angular/pull/1310#commitcomment-10677501).

**Comment by kwalrath** [comment]
@pkozlowski-opensource I didn't have bower, so bower install didn't work. The build failed because polymer wasn't there, but bower's absence was the real problem.

**Comment by kwalrath** [comment]
To put it another way... Maybe we don't need the polymer item, just the bower one. I'll remove the polymer mention & item.

**Comment by pkozlowski-opensource** [comment]
@kwalrath exactly, this was my point: let's add the Bower bit and skip Polymer.

**Comment by kwalrath** [comment]
OK, done, @pkozlowski-opensource.

**Pull request closed without merging**
