### PR TITLE
docs: myHighlight -> appHighlight

### PR DESCRIPTION
**Pull request by ogmios-voice**
(Copy-and-paste antipattern fix?)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — CHANGES_REQUESTED** [review]
Good catch! Can you also change this one last remaining occurrence:

https://github.com/angular/angular/blob/c2f6ac14e8b1516d1a13eca52ddd2f5b2c5511b5/aio/content/examples/dependency-injection-in-action/src/assets/sample.css#L6

**Comment by ogmios-voice** [comment]
Thanks. Done.

**Comment by brandonroberts** [comment]
@ogmios-voice You must [Sign the CLA](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#cla) before this PR can move forward. You also need to squash the commits down to a single commit using your initial commit message.

**Comment by brandonroberts** [comment]
Reopen this PR if you're still interested in making this change.

**Pull request closed without merging**
