### PR TITLE
chore(build): remove the es6 output

### PR DESCRIPTION
**Pull request by alexeagle**
We don't rely on it for anything, so we can speed up the build and simplify

### CODE REVIEW

**Comment by IgorMinar** [comment]
lgtm, but you need to rebase it against master again.

**Comment by pkozlowski-opensource** [comment]
@alexeagle thnx for this PR, I saw that you've done some changes that I was planning to do as well (dropping traceur related transpilation). I've sent a follow-up PR #4502 to clean up some more stuff.

**Comment by IgorMinar** [comment]
@alexeagle what happened with this PR? can we get it in? :)

**Comment by alexeagle** [comment]
I am stuck on the cyclical dependency problem. I've spent quite a bit of
time trying a few approaches:
- drop the cycle check. But Marc says we still need it, because while CJS
has some loader shim to make it possible, it can introduce quirky behavior
that has cost us debugging time in the past
- check for cycles against the TS sources instead of the es6 emit. But
Madge doesn't work against our TS sources, I've spent a couple hours
tracking down the cause but haven't gotten it yet
- check for cycles against the es5 emit, but it's broken because we
actually do have cycles in the module dependency graph, which do not exist
in the symbol dependency graph. one fix would be
  - fix the module-level cycles. There are two, and one was fixable, but
the other is hard and Tobias said it should just stay that way.

**Comment by IgorMinar** [comment]
@alexeagle how is circular-dep check related to this PR? we currently run it on the es6 output anyway.

also, have you seen #5022?

**Comment by alexeagle** [comment]
It's related because if we remove the es6 output, we have to check for
circular dependencies on some other tree.
I had not seen that bug, but those are the same circular deps I observed. I
suspect you are seeing the same thing I described: these are
module-circular-deps but not symbol-circular-deps.

**Comment by mzgol** [comment]
Just one remark - many projects don't need to support IE or the Android Browser and such projects in a year may very well work only in ES6-capable browsers without transpilation (Edge already has almost 90% score in the kangax test so this is not a distant future). A pure ES6 build would be useful for such purposes.

People can always compile Angular themselves from TypeScript to ES6 although that's harder.

**Comment by vsavkin** [comment]
Closing as we decided to keep ES6 output for now.

**Pull request closed without merging**
