### PR TITLE
fix(BaseException): Change from class extend to interface implements 

### PR DESCRIPTION
**Pull request by Bogatinov**

### CODE REVIEW

**Comment by Bogatinov** [comment]
@vsavkin @tbosch @mprobst may I have some assistance?

Locally there is no formatting error when I run `gulp check-format`.
Unfortunately it shows in Travis CI that I have issues with formatting of `test-lib.ts`.

**Comment by tbosch** [comment]
Hi,
could you sqash your commits into two commits, one for changing the `extends` into `implements` and one for changing the imports using a `.d.ts` suffix?

Also, we also need to provide our own `toThrowError()` as the one from jasmine checks for `instanceof Error` (which is why Travis fails). Have a look at our [test_lib](https://github.com/angular/angular/blob/master/modules/angular2/src/test_lib/test_lib.ts#L236) where we already add some matchers.

**Comment by vsavkin** [comment]
@Bogatinov ping

**Comment by Bogatinov** [comment]
I'm unable to continue at this point as a result of exam month and will continue contributing after 23rd of June. This PR will be closed until I revisit this changes later this month.

**Pull request closed without merging**
