### PR TITLE
test(ivy): update table root causes

### PR DESCRIPTION
**Pull request by andrewseguin**
Updates two more tests for table root causes

### CODE REVIEW

**Review by kara — APPROVED** [review]
~~LGTM~~

**Review by kara — CHANGES_REQUESTED** [review]
Just noticed that the ticket was added to `error`, not `notes`, so this will be overwritten next time the tests run. Move to `notes`?

**Comment by andrewseguin** [comment]
Okay should be good to go now - thanks for catching that

**Review by kara — APPROVED** [review]
LGTM

**Comment by andrewseguin** [comment]
Closing in favor of https://github.com/angular/angular/pull/29177, bus + chromebook isn't playing nice and easier to make a new one

**Pull request closed without merging**
