### PR TITLE
9.1.x

### PR DESCRIPTION
**Pull request by mhevery**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by kara — CHANGES_REQUESTED** [review]
Can you amend the "di" commit so the scope adheres to our commit message guidelines? We probably want "docs(core)"

**Review by kara — APPROVED** [review]
Made the necessary changes

**Review by IgorMinar — APPROVED** [review]
LGTM assuming that the lint failures get resolved. Thank you!

Reviewed-for: global-approvers

**Comment by kara** [comment]
Closed by https://github.com/angular/angular/commit/9548c7cb9435c50c7f34b3c46b9315b75acc2fe3

**Pull request closed without merging**
