### PR TITLE
build: upgrade to bazel 2.0.0

### PR DESCRIPTION
**Pull request by gregmagolan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gregmagolan** [comment]
@josephperrott I avoided this upgrade before because of the docker issue with CircleCI but its probably time to deal with it----although I'm not sure where to begin on this one.

The 2 bazel-in-bazel integration tests will not work on OSX with the current version of Bazel as it can't handle spaces in the runfiles manifest which those two tests have due to their dependency on OSX chrome from rules_webtesting.

**Review by devversion — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM, yay!

**Comment by josephperrott** [comment]
LGTM, Global Approval

**Review by IgorMinar — APPROVED** [review]
thanks!

**Comment by AndrewKushnir** [comment]
Hi @gregmagolan, could you please rebase this PR, so we rerun all tests against the latest master? Since it's a pretty major upgrade, I just want to make sure master is still green. Thank you.

**Comment by gregmagolan** [comment]
@AndrewKushnir Rebased to msater & also turned on Windows CI here https://github.com/angular/angular/pull/34919 to make sure we're good there as well

**Pull request closed without merging**
