### PR TITLE
docs: remove redundant whitespaces and fix minor typos

### PR DESCRIPTION
**Pull request by thanhpd**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

- Redundant whitespace and new line characters in various files within angular aio docs
- Some minor typos

Issue Number: N/A

## What is the new behavior?
- Redundant whitespace characters are removed
- Some typos are corrected

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Thx, @thanhpd :tada:
Can you please change the commit message to `docs: ...` (i.e. remove the `docs-infra` part)?

**Comment by thanhpd** [comment]
Hi @gkalpak, I've updated the commit message. Please have a look.

**Comment by gkalpak** [comment]
**merge-assistance:** Global approval for this docs-only change.

**Comment by AndrewKushnir** [comment]
@thanhpd @gkalpak there was a conflict while merging these changes into patch branch, so I merged it to master only for now. Could you please create a separate PR with the necessary changes and target patch branch? Thank you.

**Comment by gkalpak** [comment]
Thx, @AndrewKushnir 👍 
@thanhpd, could you open another PR targetting the `8.2.x` branch?

**Pull request closed without merging**
