### PR TITLE
docs(Tools): update punctuation mark added

### PR DESCRIPTION
**Pull request by prashant-andani**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Other... Please describe: Update on the Docs for Tools.md
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by wardbell — APPROVED** [review]
lgtm

**Comment by matsko** [comment]
@prashant-andani please rebase and fix the circle ci issue.

**Comment by wardbell** [comment]
Rebased for him. Please try to merge again.

**Comment by gkalpak** [comment]
The commit message is still invalid (`Tools` is not a valid scope).

**Comment by matsko** [comment]
@prashant-andani please fix the commit message.

**Comment by matsko** [comment]
Merged as e47a77f941a7667735dc8d4042a82317b7d40449

**Pull request closed without merging**
