### PR TITLE
docs: fixed meetup URL

### PR DESCRIPTION
**Pull request by SerheyDolgushev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Meetup URL contains a quotation mark at the end.

## What is the new behavior?

The redundant extra quotation mark is removed from meetup URL.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by yousafnawaz** [comment]
@SerheyDolgushev , it seems that you haven't signed the CLA ([see here](https://github.com/angular/angular/pull/44585/checks?check_run_id=4667957403)). Note that this is necessary in order to accept any contribution.
Thank you.

**Comment by SerheyDolgushev** [comment]
@yousafnawaz  I just signed the CLA. can you please re-run CLA check? Thank you! :)

**Review by gkalpak — APPROVED** [review]
Thx, @SerheyDolgushev :+1:

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 62a5027482912d003ba6dab7ae4f15872ec0c36a.

**Pull request closed without merging**
