### PR TITLE
docs(router): fix router description

### LINKED ISSUE #32135: Router is an NgModule?
The angular docs states that the [Router is a NgModule](https://angular.io/api/router/Router), though it's marked as a class and to my knowledge an Injectable. The NgModule it's encapsulated in, is the RouterModule.
Correct me if I am wrong.

Thanks;

### PR DESCRIPTION
**Pull request by macjohnny**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: fixes #32135

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Thanks for this, @macjohnny! I've requested @jbogarthyde to review as she does lots of API docs work.

**Review by jbogarthyde — APPROVED** [review]
Good catch! Thanks.

**Comment by jbogarthyde** [comment]
This is doc only, should not require G3 - just code-owner approval. @kara ?

**Comment by AndrewKushnir** [comment]
@jbogarthyde this is a docs only change, I've merged this PR. Thank you.

**Pull request closed without merging**
