### PR TITLE
docs: add angular#bundler to Enforcing Trusted Types section

### PR DESCRIPTION
**Pull request by tomeustace**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — DISMISSED** [review]
Thx, @tomeustace :+1:

Can you please update the commit message to include `Fixes #44647` at the bottom (per out [commit message guidelines][1]).

[1]: https://github.com/angular/angular/blob/655507012b7b59c83e27429349ce3ac10608a82d/CONTRIBUTING.md#commit

**Comment by tomeustace** [comment]
> 

Thanks @gkalpak I've ammended the commit message.

**Review by josephperrott — DISMISSED** [review]
LGTM

Reviewed-for: fw-security

**Review by alxhub — DISMISSED** [review]
Reviewed-for: fw-security

A non-blocking request: please add additional context to the commit message, detailing _why_ we're adding this new entry to the list.

**Comment by jessicajaniuk** [comment]
@tomeustace If you can rebase this and resolve the conflicts, we can get this landed.

**Comment by tomeustace** [comment]
> 

@jessicajaniuk @alxhub  thanks, have performed rebase and updated commit message.

**Review by josephperrott — APPROVED** [review]
LGTM

reviewed-for: fw-security

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit adb21a2416a9303a792edb926b91c4a67f13a4fd.

**Pull request closed without merging**
