### PR TITLE
docs: modify the html tags

### PR DESCRIPTION
**Pull request by aanchal88**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@aanchal88 thanks for improving Angular docs!

**Comment by aanchal88** [comment]
Hii @AndrewKushnir , please merge the PR.
Thanks

**Comment by aanchal88** [comment]
Hii @AndrewKushnir , please merge the PR.
Thanks

**Comment by AndrewKushnir** [comment]
@aanchal88 FYI I've pushed a rebase to rerun the CI and will add this PR to the merge queue once CI is "green". Thank you.

**Comment by AndrewKushnir** [comment]
@aanchal88 it looks like the `aio/content/examples/ngmodules/e2e/src/app.e2e-spec.ts` file (and may be some other files too) also needs an update, since it uses a previous version in an element selector, see here:

https://github.com/angular/angular/blob/254023a03c3aaa26e2d01c02f9b9933b82fd971e/aio/content/examples/ngmodules/e2e/src/app.e2e-spec.ts#L14

**Comment by jessicajaniuk** [comment]
Closing this since there's been no updates and tests are still failing. Feel free to open a new PR if you'd like to see these changes land.

**Pull request closed without merging**
