### PR TITLE
ci: add Brandon Roberts as an aio approver

### PR DESCRIPTION
**Pull request by brandonroberts**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by IgorMinar** [comment]
I see you using our commit message conventions slightly incorrectly.

"docs(aio)" means - documentation for the angular.io infrastructure. 

"feat(aio)" or "fix(aio)" means feature or fix for angular.io infrastructure

however in this PR you want to say "ci: " because you are changing the CI configuration. 

lastly, by convention we don't capitalize the first letter of the commit message (and no periods at the end), so it should be "ci: add ...".

can you please update the commit? thanks!

**Review by IgorMinar — APPROVED** [review]
I'm going to approve this for now. please update the commit message, and then remove the cleanup label and add the merge label. thanks!

**Comment by IgorMinar** [comment]
also keep in mind that the PR subject doesn't matter to us that much. it's nice to have them in sync, but for historical/archival purposes the commit message and content in it are much much important.

**Comment by IgorMinar** [comment]
@brandonroberts once you have all the approvals you do need to remove the "cleanup" label and add the "merge" label. otherwise your PR will remain unmerged. I'm going to do that now, but in the future please do it yourself.

**Comment by brandonroberts** [comment]
@IgorMinar ok

**Pull request closed without merging**
