### PR TITLE
docs: Change definition of NgModules in Angular concepts guide

### PR DESCRIPTION
**Pull request by bampakoa**
My perception when working with the Angular framework is that it is component oriented. Thus, the basic building block should be the component. NgModules help us to organize our components and other Angular artifacts into separate functional domains easier.

Also with the advent of Ivy compiler, we may be able to render module-less components https://github.com/angular/angular/blob/1c85c24ed3ef7d220bf2de9f2cf8b08556547ff9/integration/cli-hello-world-ivy-minimal/src/main.ts in the future.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jbogarthyde — APPROVED** [review]

**Comment by jbogarthyde** [comment]
LGTM

**Review by jelbourn — COMMENTED** [review]
I think the idea of the change here is good; @aikidave probably have input on how to word it exactly.

**Review by aikithoughts — APPROVED** [review]
LGTM!

Reviewed-for: global-docs-approvers

**Comment by AndrewKushnir** [comment]
Hi @bampakoa, I've just rebased your PR to re-run tests on CI and it looks like the `lint` CircleCI job is failing due to the fact that the commit message body contains lines longer than 120 characters. Could you please amend the commit message to keep lines under 120 characters? Thank you.

**Comment by bampakoa** [comment]
Thanks @AndrewKushnir 🙏 This is ready now.

**Comment by AndrewKushnir** [comment]
Hi @bampakoa, thanks for updating the commit message. This PR is now merged. Thanks for improving Angular docs!

**Pull request closed without merging**
