### PR TITLE
fix(common): Cannot find module HttpUploadProgressEvent

### LINKED ISSUE #30814: Cannot find module '@angular/common/http/src/response after migrating to Angular 8
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/common/http

### Is this a regression?
 Yes, the previous version in which this bug was not present was: angular 7.0

### Description

after migrating to angular 8.0 using the command 
`ng update @angular/cli @angular/core`
building the application using `ng build --prod` gives the following error:

`error TS2307: Cannot find module '@angular/common/http/src/response'.`

I use this for importing the HttpUploadProgressEvent interface 👍 

import { HttpUploadProgressEvent  } from '@angular/common/http/src/response';

Should I import it from else where ?

## 🌍  Your Environment

Angular Version: 8..0

Angular CLI: 8.0.1
Node: 12.3.1
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cdk                      7.3.3
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

### PR DESCRIPTION
**Pull request by santoshyadavdev**
Fixes #30814

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #30814

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by santoshyadav198613** [comment]
Hi @gkalpak ,
Need some help here, not able to figure oy why tests are getting failed, it just says size is too big.

**Comment by gkalpak** [comment]
Thx for working on this, @santoshyadav198613. I don't see a size-related failure. The one I see (that matters) is about updating the public API guard golden file. You can look at the output in [CircleCI#346811][1] for more details.

Basically, since you have modified the public API for `@angular/common/http`, you need to also update the golden file: [tools/public_api_guard/common/http.d.ts][2]. Either by running `bazel run //tools/public_api_guard:common_http_api.accept` (if that works on your machine :grin:) or by manually making the following change:

```diff
+export interface HttpUploadProgressEvent extends HttpProgressEvent {
+    type: HttpEventType.UploadProgress;
+}
+
 export declare class HttpUrlEncodingCodec implements HttpParameterCodec {
```

[1]: https://circleci.com/gh/angular/angular/346811
[2]: https://github.com/angular/angular/blob/master/tools/public_api_guard/common/http.d.ts

**Review by gkalpak — APPROVED** [review]
Thx!

One minor comment:
Since the commit message will show up in the changelog, I think it would be more clear for the reader to mention what the commit did. E.g.:

> fix(common): expose the \`HttpUploadProgressEvent\` interface as public API

**Comment by santoshyadav198613** [comment]
> Thx for working on this, @santoshyadav198613. I don't see a size-related failure. The one I see (that matters) is about updating the public API guard golden file. You can look at the output in [CircleCI#346811](https://circleci.com/gh/angular/angular/346811) for more details.
> 
> Basically, since you have modified the public API for `@angular/common/http`, you need to also update the golden file: [tools/public_api_guard/common/http.d.ts](https://github.com/angular/angular/blob/master/tools/public_api_guard/common/http.d.ts). Either by running `bazel run //tools/public_api_guard:common_http_api.accept` (if that works on your machine ) or by manually making the following change:
> 
> ```diff
> +export interface HttpUploadProgressEvent extends HttpProgressEvent {
> +    type: HttpEventType.UploadProgress;
> +}
> +
>  export declare class HttpUrlEncodingCodec implements HttpParameterCodec {
> ```

Thanks @gkalpak ,

You are a savior I was struggling with this, worked now.

**Comment by santoshyadav198613** [comment]
> Thx!
> 
> One minor comment:
> Since the commit message will show up in the changelog, I think it would be more clear for the reader to mention what the commit did. E.g.:
> 
> > fix(common): expose the `HttpUploadProgressEvent` interface as public API

Done.

**Comment by gkalpak** [comment]
Thx, @santoshyadav198613 :+1: (Don't worry about the `codefresh` CI failure. It is unrelated to this PR.)
Now, we just need approval from @angular/fw-http and @angular/fw-public-api (cc @IgorMinar, @alxhub)

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
merge-assistance: code-fresh flake.

**Pull request closed without merging**
