### PR TITLE
docs(docs-infra): fix z-index issue on mobile

### LINKED ISSUE #56871: Unable to click on "Roadmap" in mobile device.
### Describe the problem that you experienced

In mobile devices when the user (me) clicks on the roadmap link from navbar it does not open. 

image

### Enter the URL of the topic with the problem

_No response_

### Describe what you were looking for in the documentation

Trying to open "Roadmap" on mobile

### Describe the actions that led you to experience the problem

Click on "Reference" > Roadmap 

and it doesn't open then

### Describe what you want to experience that would fix the problem

I want to open Roadmap on mobile device

### Add a screenshot if that helps illustrate the problem

As shown in the below image, if you right click and do inspect element on "Roadmap" it will not acutally show the "Roadmap" but another div on top of "Roadmap" which I believe is causing the problem
image

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by JeanMeche**
fixes #56871

### CODE REVIEW

**Comment by JeanMeche** [comment]
@bencodezen Can you confirm you see no visual regression on the menu with this change (particularly mobile & tablet).

**Comment by theharshitkumar** [comment]
Hi Jean, Thanks for the fix. It works for me.

**Comment by bencodezen** [comment]
Looks good to me @JeanMeche!

**Review by bencodezen — APPROVED** [review]
Thanks for fixing this @JeanMeche!

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit bafafb25c91787d11e0c4b6f3a1faa66da2b1328.

The changes were merged into the following branches: main, 18.1.x

**Pull request closed without merging**
