### PR TITLE
fix(devtools): change links to the angular repo

### PR DESCRIPTION
**Pull request by mgechev**
Update the link to the DevTools repository.

### CODE REVIEW

**Review by Hossein13M — APPROVED** [review]
This pull request has changed the URL from the archived repo to the new one.

**Review by sumitarora — APPROVED** [review]
LGTM :shipit:

**Review by twerske — APPROVED** [review]

**Comment by dylhunn** [comment]
Merging into minor due to conflicts with the patch branch. Please rebase and send me another copy of the PR if patch branch is needed, thanks!

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit bf428775a4c9bdd685e38ec91c533a773544bbc2.

**Pull request closed without merging**
