### PR TITLE
docs: Adding required and Transform args into the usage notes of Input decorator

### PR DESCRIPTION
**Pull request by sunilbaba**
Adding required and Transform args into the usage notes of Input decorator

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
https://github.com/angular/angular/issues/50840

Issue Number: https://github.com/angular/angular/issues/50840

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by AndrewKushnir — COMMENTED** [review]
@sunilbaba thanks for the PR.

I think a slightly better place for this information would be the following guide: https://angular.io/guide/inputs-outputs (which is also referenced in JSDoc). I think it makes sense to create a new section in that guide and add the necessary description and a couple examples.

Thank you.

**Comment by sunilbaba** [comment]
Sure @AndrewKushnir

**Comment by JeanMeche** [comment]
can you run `yarn lint` to fix the linting issues mentionned by the CI ?

**Comment by JeanMeche** [comment]
Can you squash your commits by the way ?

**Comment by sunilbaba** [comment]
Hi @JeanMeche 

Lint issue is fixed after squashing comments but still there are some failure in pipeline. Will you be able to help me out ?

**Comment by JeanMeche** [comment]
You need to rebase on main for the last job to pass !

**Comment by JeanMeche** [comment]
You did a merge, it should have a been a rebase to keep your single commit  !

**Comment by sunilbaba** [comment]
Sorry @JeanMeche , While Merging I have messed up the branch. So I have created a new pull request for same changes : https://github.com/angular/angular/pull/51173

**Pull request closed without merging**
