### PR TITLE
docs: change grammar in architecture guide

### PR DESCRIPTION
**Pull request by ghost**
grammer change for better understanding

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
Hi @kapunahelewong, could you please have a look at this PR? It doesn't require engineering review. Thank you.

**Comment by dishanfernando** [comment]
Hi Can you let me know what needs to be done.
Im new to contribution.

**Comment by kapunahelewong** [comment]
Hi, @dishanfernando. You're doing everything just right. We just have to process and move it through. Thank you for checking. 🙂

**Review by aikithoughts — APPROVED** [review]
Looks good to me.

**Comment by aikidave** [comment]
merge-assistance: Global approval for this docs-only change.

**Pull request closed without merging**
