### PR TITLE
fix(docs-infra): fix filtering in run-example-e2e.js

### PR DESCRIPTION
**Pull request by kapunahelewong**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

e2e tests for docs examples not running properly on master.

Issue Number: N/A

## What is the new behavior?

Change from `* ${filter} *` to `*${filter}*` (no spaces).

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

For context: [#28463](https://github.com/angular/angular/commit/99e3a04ea2c7cdecce3862b843bf68714f4d0caf)

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

**Review by gkalpak — APPROVED** [review]
Ooops!

The current commit messages makes it sound as if this is a formatting fix, not a bug fix. Can you, please, change it to something like:

> fix(doc-infra): fix filtering in \`run-example-e2e.js\`

**Comment by kapunahelewong** [comment]
> Ooops!
> 
> The current commit messages makes it sound as if this is a formatting fix, not a bug fix. Can you, please, change it to something like:
> 
> > fix(doc-infra): fix filtering in `run-example-e2e.js`

Fixed. Thanks for looking out @gkalpak. I feel so...pioneering!

**Comment by gkalpak** [comment]
Thx, @kapunahelewong! Can you also rebase on master to get CI green? 🙏

**Comment by kapunahelewong** [comment]
@gkalpak Done!

**Pull request closed without merging**
