### PR TITLE
ci: add myself as an aio reviewer

### PR DESCRIPTION
**Pull request by JeanMeche**
This is to allow myself to approve minor aio changes like redirections.

### CODE REVIEW

**Review by thePunderWoman — APPROVED** [review]

**Comment by thePunderWoman** [comment]
@JeanMeche I don't think this PR is necessary. Pullapprove rules are only relevant in `main`.

**Comment by JeanMeche** [comment]
I've reopened the PR since it appears that the branch does matter for the pullapprove rule check.

**Comment by thePunderWoman** [comment]
Caretaker note: mergeability always fails on PRs that target lts. So this is safe to merge.

**Comment by atscott** [comment]
This PR was merged into the repository by commit 45c132650f8fd8e55a714d234a6fc289dbe53aa1.

The changes were merged into the following branches: 17.3.x

**Pull request closed without merging**
