### PR TITLE
docs: fix issue #24571

### PR DESCRIPTION
**Pull request by anupwritescode**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
https://angular.io/api/core/OnChanges#usage-notes

Issue Number: 24571

## What is the new behavior?
Removes '!' from documentation of ngOnChanges

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

## Other information
angular

### CODE REVIEW

**Comment by anupwritescode** [comment]
@googlebot I signed it!

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Hi @anupwritescode - thanks for submitting this PR. Unfortunately, the fix is not just a matter of removing the `!`. This causes the example code to fail to typecheck. See the [failing CI job](https://app.circleci.com/pipelines/github/angular/angular/33982/workflows/f2c54915-a87a-4611-9d01-a65ddc7123a5/jobs/1003887).

```
packages/examples/core/ts/metadata/lifecycle_hooks_spec.ts:110:16 - error TS2564:
Property 'prop' has no initializer and is not definitely assigned in the constructor.

110       @Input() prop: number;
                   ~~~~
```

I think the actual solution, in this case, is to provide an initial value for this property. Perhaps `0`?

**Comment by petebacondarwin** [comment]
Also note that since you have touched this file, it will now need to be formatted. See this [failing CI job](https://app.circleci.com/pipelines/github/angular/angular/33982/workflows/f2c54915-a87a-4611-9d01-a65ddc7123a5/jobs/1003881).

**Comment by anupwritescode** [comment]
@petebacondarwin thanks for reviewing my PR. I did the requested changes, but I made a mistake in my one of my commit messages (doc instead of docs). I'll close this PR and raise another one.

**Comment by petebacondarwin** [comment]
Rather than creating a new PR, you can just update the commits and force-push this branch. It is better this way, since it keeps all the discussion in one place.

**Comment by petebacondarwin** [comment]
But I see you have deleted the branch on your fork, so you probably will need to create a new PR now.

**Pull request closed without merging**
