### PR TITLE
Added link to the developer channel for the Dart SDK.

### PR DESCRIPTION
**Pull request by Xesued**
There is not an easy way to navigate to the version of the Dart SDK.  Just one small step to aid in getting people to try out angular2.

### CODE REVIEW

**Comment by Xesued** [comment]
CLA Signed.

**Comment by vicb** [comment]
Already covered in https://github.com/angular/angular/pull/946/files#diff-597c97dd957ad32a76360ab955f7e608R23 ?

**Comment by Xesued** [comment]
Very nice.

**Comment by chalin** [comment]
@Xesued, FYI, the developer doc has been committed to master. I added explicit mention of the Dart download archive as a source for both the stable and dev channels.

**Comment by Xesued** [comment]
Good to hear!  It did take me a while to find the version needed, I think that will help others.

**Pull request closed without merging**
