### PR TITLE
docs: fix typo in lazy-load callout

### PR DESCRIPTION
**Pull request by acohenOT**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?
Fix typo

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by acohenOT** [comment]
@googlebot I signed it!

**Review by petebacondarwin — APPROVED** [review]
Thanks @acohenOT - the `docs-infra` target is only used for changes to the infrastructure of the docs website (i.e. the site or the tooling to generate it) not the content of the docs itself. For a file like this it is enough to miss out the target altogether.

Do you think you could amend the commit message to make the commit message `docs: fix type in lazy-load callout`?

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by acohenOT** [comment]
@petebacondarwin sure thing, I'll take care of it.

**Comment by acohenOT** [comment]
@petebacondarwin I amended the commit message and rebased. It added extra commits though and I'm not sure now to remove those. Is this acceptable?

**Comment by petebacondarwin** [comment]
Awesome. I see you managed to sort out the commit update and rebase. Marked for merge!

**Pull request closed without merging**
