### PR TITLE
Lifecycle recursion

### PR DESCRIPTION
**Pull request by marclaval**
This PR fixes FW-832.

### CODE REVIEW

**Comment by marclaval** [comment]
More details abput the fix. The integration test that is enabled here shows a very interesting property of the ViewEngine: the init hooks (OnInit, AfterContentInit, and AfterViewInit) are always executed once and only once, even if they recurse or throw.

In fact, this logic is documented here: https://github.com/angular/angular/blob/cabf1c71059140a2f7855790a9e8ea79b6745f3a/packages/core/src/view/provider.ts#L465-L507

In Ivy, we don't manage these cases at all.

- The recursion one can be easily solved by adding a few flags to guard against it.
- The throw one is more challenging. Within a view, the execution on all the init hooks is actually a sequence. If one of them throws, then the exception is not caught by the framework and the current change detection is stopped. During the next change detection, the sequence will resume where it stopped (and all the check hooks will be executed as usual). This means that:
   - the state of this sequence is kept in the view
   - init hooks may be executed in any view pass, not only the first one
   - collected ngOnInit, ngAfterContentInit, ngAfterViewInit are special hooks that needs to be flagged as such, as oppposed to ngDoCheck, ngAfterViewChecked, etc. Executing a special hook changes the state, while executing the other ones don't.

**Review by mhevery — APPROVED** [review]
Made some changes cda7b03993

**Comment by mhevery** [comment]
http://test/OCL:230818332:BASE:230818351:1548378384444:28a48373

**Comment by kara** [comment]
@mlaval Looks like this needs a symbol tests updated

**Comment by marclaval** [comment]
@kara I've updated the symbols, it should be good to go

**Pull request closed without merging**
