### PR TITLE
docs: fix template example

### PR DESCRIPTION
**Pull request by ruanha**
Fix a typo that prevents an example to show.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 46169

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@ruanha thanks for improving Angular docs!

**Comment by ruanha** [comment]
@AndrewKushnir Awesome!

What's the policy for closing the related issue (https://github.com/angular/angular/issues/46169)? Is it done automatically when merged?

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
This PR was merged into the repository by commit 3af2cd53069e884090859b852c0a06fa069b972a.

**Comment by AndrewKushnir** [comment]
@ruanha we usually add something like `Closes #xyz` to the commit message, in which case the mentioned issue would be closed once a PR is merged. This is a GitHub feature and more info can be found [here](https://github.blog/2013-01-22-closing-issues-via-commit-messages/).

**Pull request closed without merging**
