### PR TITLE
chore(http): remove unused properties from Request

### LINKED ISSUE #3339: chore(http): remove unused properties from Request and Response
There were some properties that were added to these objects that don't do anything right now (like credentials, mode, cache). These were added for consistency with the constructs defined in the Fetch spec. These should be removed until their behavior is designed.

### PR DESCRIPTION
**Pull request by 0x-r4bbit**
This removes properties mentioned in #3339

Closes #3339

### CODE REVIEW

**Comment by PascalPrecht** [comment]
@jeffbcross couldn't find those properties in `Response` though

**Comment by jeffbcross** [comment]
@PascalPrecht lookin' good! The properties should also be removed in `base_request_options`.

Don't worry about `Response`. It has some properties that aren't yet being used by `XHRBackend`, but they are more straightforward than these properties on `Request`.

Looks like you'll need to rebase against master before pushing again.

**Comment by PascalPrecht** [comment]
@jeffbcross done.

**Comment by jeffbcross** [comment]
@PascalPrecht sorry for dragging my feet on this! I fixed the formatting issue, and removed some enums/interfaces. Pushed to presubmit so hopefully it gets merged to master without issue! https://github.com/angular/angular/tree/presubmit-jeffbcross-pr-3823

**Comment by PascalPrecht** [comment]
@jeffbcross I think I can forgive you one last time, my friend.

**Pull request closed without merging**
