### PR TITLE
#58953 docs: update two-way binding example in documentation

### PR DESCRIPTION
**Pull request by PrajaktaB27**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]

**Comment by JeanMeche** [comment]
Could you please reword your commit to `docs: update two-way binding example in documentation`, thank you.

**Comment by PrajaktaB27** [comment]
> Could you please reword your commit to `docs: update two-way binding example in documentation`, thank you.

ah, I remade my commit and just now thought of asking if you mean the commit or the pr itself?

**Comment by JeanMeche** [comment]
Yes it was the commit, also we'd like this change to be a single commit. Can you please squash both commits into one, thank you.

**Comment by PrajaktaB27** [comment]
> Yes it was the commit, also we'd like this change to be a single commit. Can you please squash both commits into one, thank you.

I am not able to squash the commits after multiple tries so closing this pr and making a new one with one commit and the correct message. Apologies!

**Pull request closed without merging**
