### PR TITLE
refactor(core): extract `assertNotDestroyed` as function.

### PR DESCRIPTION
**Pull request by JeanMeche**
This will allow the mangling of the method name

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
Thanks for the optimization!

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:672136863:BASE:672136870:1725748281242:e05865c).

**Comment by JeanMeche** [comment]
Presubmit is green, is this ready to merge ?

**Comment by AndrewKushnir** [comment]
@JeanMeche yes, presubmit is "green", adding this PR to the merge queue!

**Comment by JeanMeche** [comment]
Mergeability came back red for `18.2.x`, let's target the `main` branch !

**Pull request closed without merging**
