### PR TITLE
refactor: remove unused parameters

### PR DESCRIPTION
**Pull request by DanielRuf**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

There are some method invocations which are called with more parameters then they use and consume.

Issue Number: N/A

## What is the new behavior?
The unused parameters are removed. No changes in the behavior.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kyliau** [comment]
@DanielRuf thank you for the contribution! Please run `yarn gulp format:changed` to fix the lint errors.

**Comment by DanielRuf** [comment]
> Please run yarn gulp format:changed to fix the lint errors.

Ok, will do so later.

**Review by petebacondarwin — APPROVED** [review]
LGTM - what tool did you use to find these unused parameters? You surely didn't look through the code line by line, right?

**Comment by petebacondarwin** [comment]
That's very interesting. I note that you did not exclude `node_modules` from the scan, so the results are rather skewed.

**Review by kyliau — APPROVED** [review]

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
I am using my global power to make it green but it is still red.

**Comment by DanielRuf** [comment]
> All checks have passed

> Code owner review required
> Waiting on code owner review from angular/fw-dev-infra

**Pull request closed without merging**
