### PR TITLE
refactor(compiler-cli): remove Ivy switch transform

### PR DESCRIPTION
**Pull request by JoostK**
Now that the core package has been cleaned up to no longer contain Ivy
switch code, the transform to switch the `PRE_R3` markers to become
`POST_R3` is deleted as well.

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
This PR is probably unblocked now (after landing #43884) :)

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by AndrewKushnir — APPROVED** [review]
@JoostK thanks for the cleanup! 🎉

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit d8e65776cb35b08c435335ffeac0f82789477532.

**Pull request closed without merging**
