### PR TITLE
docs: additional way for child component to send data to parent component

### PR DESCRIPTION
**Pull request by raghuraman1**
Added additional way for child component to send data to parent component.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by raghuraman1** [comment]
@alxhub Hi Alex. 
Its a very small PR. First time am here. I think I have signed the  Contributor License Agreement (CLA). Hope thats all god.
Pls suggest any improvements if needed.

**Comment by raghuraman1** [comment]
@alxhub 
Hi Alex,

I hope you are looking into this PR.
I am sharing this SO url for more context if needed.
https://stackoverflow.com/questions/73579453/child-to-parent-communication-without-emitting/

Please see if you can look into it.
let me know if I must do something about the ci/circleci: lint check. (Should I create a new PR?)

I hope we can merge the changes proposed.
Let me know if you need me to do any improvements.
Thanks.

R

**Comment by bob-watson** [comment]
@alxhub This needs a tech review by engineering. After that, I can review the text. Thanks!

**Comment by raghuraman1** [comment]
> @alxhub This needs a tech review by engineering. After that, I can review the text. Thanks!

Hi @bob-watson ,
Thanks for replying. let me know if you need anything from me.
R

**Comment by raghuraman1** [comment]
Hi @alxhub, @bob-watson
Maybe this can help- https://angularconcepts.github.io/emitconcept/
R

**Comment by JeanMeche** [comment]
We are looking at soon deprecating anguiar.io in favor or angular.dev. 

Did you have a look at the new content on that topic and if it satisfies you ? 
You can start at https://angular.dev/guide/components

**Pull request closed without merging**
