### PR TITLE
fix(shared-docs): remove unwanted styling on API page.

### LINKED ISSUE #54613: Flickering when changing API tabs
### Describe the problem that you experienced

When changing from description to Usage notes there is a slight flickering due do a layout shift 

Here is a screenshort exported from a performance audit (sorry for the low res).

image

### Enter the URL of the topic with the problem

https://angular.dev/api/core/afterNextRender

### PR DESCRIPTION
**Pull request by JeanMeche**
fixes: angular/angular#54613

Pending angular/dev-infra#1815

### CODE REVIEW

**Review by twerske — APPROVED** [review]
LGTM

**Comment by twerske** [comment]
Marking for merge - the CI failure looks false?

**Comment by pkozlowski-opensource** [comment]
@twerske yeh, the red CI was a flake - but this PR needs more reviews before it gets in

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit d2ec5b617889604ffb6667ba5b873de71fcff691.

**Pull request closed without merging**
