### PR TITLE
docs-infra: a couple of (pre-emptive) fixes

### PR DESCRIPTION
**Pull request by gkalpak**
This PR contains a couple of fixes for AIO. See the individual commits for details.

/cc @josmar-crwdstffng

### CODE REVIEW

**Comment by josmar-crwdstffng** [comment]
@gkalpak 

The changes match what we discussed offline. Thank you

LGTM

**Review by josmar-crwdstffng — APPROVED** [review]

**Review by dylhunn — APPROVED** [review]
reviewed-for: size-tracking

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: size-tracking

**Comment by jessicajaniuk** [comment]
@gkalpak This does not merge cleanly with the patch branch. I've updated to `target: minor`. Please create a patch PR.

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit b57f8bea61a0df28792c446ce2bc7be75308bd78.

**Comment by gkalpak** [comment]
Here is the PR for patch: #45563

**Pull request closed without merging**
