### PR TITLE
refactor(compiler): stricter types for HTML AST

### PR DESCRIPTION
**Pull request by thorn0**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?

It's a type-only change. A `Node` can only be an instance of one of the six classes. This relation can be more accurately expressed using a union type. This potentially gives better type inference.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by tartarza112244** [comment]
+1 Approve

**Comment by tartarza112244** [comment]
+1 Approve +1 Approve

**Comment by tartarza112244** [comment]
+1 Approve +1 Approve

**Comment by tartarza112244** [comment]
-1 Deny

**Review by JoostK — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:372390397:BASE:372390411:1620326751982:50c35d94).

**Comment by JoostK** [comment]
@thorn0 thank you!

**Pull request closed without merging**
