### PR TITLE
docs: fix links to Material examples

### PR DESCRIPTION
**Pull request by Maistho**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The links go to the wrong line numbers

## What is the new behavior?
The links go to the correct line numbers

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — COMMENTED** [review]
Good catch! Thx, @Maistho :+1:
I've left a minor suggestion.

**Comment by Maistho** [comment]
Good suggestion @gkalpak :)

I've squashed the commits into a single one and detailed the fixed hashes in the commit message.

**Review by gkalpak — APPROVED** [review]
Thx, @Maistho! The changes look good :+1:

Can you please update the commit message to more closely follow our [commit message guidelines](https://github.com/angular/angular/blob/1d9e56eba06958e37ef8062ae7b65afa85f90632/CONTRIBUTING.md#commit). More specifically, `a11y` is not an allowed scope. Just use `docs: ...` (without a scope).

That will fix the CI linting failures.

**Review by gkalpak — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by Maistho** [comment]
Updated the commit message and rebased on master :)

**Comment by kapunahelewong** [comment]
Hi, @Maistho could you rebase again to see if we can get circleci to pass? Please tag me when you're ready. Thank you!!

**Comment by Maistho** [comment]
Rebased again @kapunahelewong :)

**Pull request closed without merging**
