### PR TITLE
refactor(core): Remove attribute, char, and property values for Actio…

### PR DESCRIPTION
**Pull request by tbondwilkinson**
…nFlow.

These values are inlined in ActionFlow internally in google3, and are no longer used.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]

**Review by rahatarmanahmed — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by tbondwilkinson** [comment]
TESTED=[TGP](https://fusion2.corp.google.com/presubmit/646499882/OCL:646499882:BASE:647150409:1719473706762:9bae8574/targets)

**Comment by tbondwilkinson** [comment]
Need another stamp for public API autogenerated docs.

**Review by thePunderWoman — APPROVED** [review]
reviewed-for: public-api, primitives

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit 60a72af1633245af8673852d378db5e8af35e86f.

The changes were merged into the following branches: main, 18.0.x

**Pull request closed without merging**
