### PR TITLE
FW-887: four independent fixes for TestBedRender3

### PR DESCRIPTION
**Pull request by alxhub**

### CODE REVIEW

**Comment by alxhub** [comment]
Reviewers: please note the last two commits are the substance of this PR. The first commit is from #27860 which I expect to merge before this one, so I've based mine on it to avoid later conflicts.

**Comment by AndrewKushnir** [comment]
@alxhub PR #27860 that you based your PR on is now in master, so you can rebased from master branch. Thank you.

**Comment by alxhub** [comment]
@AndrewKushnir thanks, done.

**Review by mhevery — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
LGTM, thanks @alxhub!

**Pull request closed without merging**
