### PR TITLE
fix(bug): reflect Dart interfaces from superclass as well

### LINKED ISSUE #4221: Missing dart reflection of interfaces on superclass
pattern like this
`class AttachAware implements OnChanges`
`class MyComponent extends AttachAware`

we never call the event listener.

### PR DESCRIPTION
**Pull request by alexeagle**
fixes #4221

### CODE REVIEW

**Comment by mhevery** [comment]
Looks like you have a broken test.

**Comment by mhevery** [comment]
@alexeagle can you have a look?

**Comment by alexeagle** [comment]
yes, sorry, getting back to this...

**Comment by alexeagle** [comment]
I have no idea what is going on, the failures were in the js build and now they are in the dart build, look totally unrelated to what I did, and the build has been very flaky. But I've re-run a bunch of times and don't get a passing status. I think I need some help to get this merged.

**Comment by mhevery** [comment]
@alexeagle ping me when you get to your desk and I can help you repro this locally.

**Comment by alexeagle** [comment]
got a passing run from Travis PR just now. Looks like a whole lot of flakiness. Trying the presubmit again.

**Pull request closed without merging**
