### PR TITLE
docs: fix Redundant "See also:" link in ContentChild

### PR DESCRIPTION
**Pull request by jithil-kore**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
This changes removed Redundant "See also:" link in ContentChild Page. Which will re render the same page on click, 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently if the "See also:" link in ContentChild page will re render the ContentChild page again. 

Issue Number: #28318

## What is the new behavior?
The See Also link has been removed from the ContentChild Page.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks for the PR @jithil-kore! Will you rebase this down to a single commit?

**Comment by jenniferfell** [comment]
@jithil-kore : I also noticed that one commit has completely unrelated changes (yarn version upgrade), which should be in a separate PR. Maybe it's easiest to create two separate new PRs and close this one without merging?

**Comment by petebacondarwin** [comment]
This needs super level docs review from @jenniferfell - then we can apply merge label.

**Comment by jithil-kore** [comment]
> This needs super level docs review from @jenniferfell - then we can apply merge label.

@jenniferfell, could you please review this PR.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Caretaker note: This is a docs only change and should not impact g3. Please run presubmit.

**Pull request closed without merging**
