### PR TITLE
docs: add armen vardanyan to GDE resources

### PR DESCRIPTION
**Pull request by Armenvardanyan95**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
@Armenvardanyan95 - I approved the content from a technical point of view (i.e. I checked the github and twitter accounts).

Please can you fix the image size:

```
Error: The following pictures exceed maximum size limit of 30kb:
  - /home/circleci/ng/aio/content/images/bios/armen-vardanyan.jpg
```

**Review by twerske — APPROVED** [review]
LGTM once Pete's comments are fixed

**Comment by Armenvardanyan95** [comment]
@petebacondarwin thanks for guidance, done, now there is only one commit with the correct email ✔️

**Comment by petebacondarwin** [comment]
Thanks for sorting out the CLA problem @Armenvardanyan95. 
Can you do one final rebase on the upstream master to trigger the CI to run?
Thanks!

**Comment by Armenvardanyan95** [comment]
@petebacondarwin sorry I somehow missed your comment
I didn't quite get that, how I should do it?

**Comment by petebacondarwin** [comment]
Hi @Armenvardanyan95 - no problem. This is what I would recommend...

Let's assume that you have a "git remote" set up that points the main angular/angular repo called `upstream`.
Then you could do:

```
git fetch upstream master
git checkout docs/contributors-gde-armenvardanyan
git rebase upstream/master
git push --force-with-lease
```

Or if you wanted to also update your local `master` branch as well (and if it was already tied to the `upstream` remote) you could simply do:

```
git checkout master
git pull
git checkout docs/contributors-gde-armenvardanyan
git rebase master
git push --force-with-lease
```

**Comment by AndrewKushnir** [comment]
FYI, I've pushed a rebase and if the CI is "green", we should be able to proceed with the merge.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 130f06e6b5d132986b1cab39daca71b774457e40.

**Comment by Armenvardanyan95** [comment]
@AndrewKushnir thank you!

**Pull request closed without merging**
