### PR TITLE
docs(docs-infra): remove inactive resource from community page

### PR DESCRIPTION
**Pull request by MeAkib**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Remove and inactive resource from the community page

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

In [Community Page](https://angular.io/resources?category=community)
Currently, [Angular Experience (NgXP)](https://ngxp.show/) is not active and the website is down. 
Issue Number: N/A

## What is the new behavior?
All resources are active

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by akib1997** [comment]
Can you please look at it @twerske

**Comment by twerske** [comment]
@bravery08 Do you have thoughts here?

**Comment by bravery08** [comment]
Yea, that is correct. That show is no longer active and the link can be removed. I'm now on the Angular Plus Show with @pjlamb12 where we do the Dev Life episodes.

**Review by twerske — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit dc4db80f9a8c531dc97ef53765f616ed2072d20d.

**Pull request closed without merging**
