### PR TITLE
docs: Fix unnecessary Input in attribute directive docs example

### PR DESCRIPTION
**Pull request by pniedermeyer**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
There is a unnecessary input in the docs, that is confusing.
Issue Number: N/A

## What is the new behavior?
Input is removed and transferred to the correct file.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by pniedermeyer** [comment]
@googlebot I signed it!

**Comment by Navadeep7-co** [comment]
Please don’t send me emails

**Comment by pniedermeyer** [comment]
@googlebot I fixed it.

**Comment by pniedermeyer** [comment]
@googlebot I fixed it.

**Review by AndrewKushnir — APPROVED** [review]
@pniedermeyer the change looks good to me, thanks for improving Angular docs! 👍

**Pull request closed without merging**
