### PR TITLE
docs: remove unused attribute

### PR DESCRIPTION
**Pull request by geromegrignon**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
An used attribute has been added on a `h1` tag on part 5 of the tutorial.

Issue Number: #41210 

## What is the new behavior?
The attribute has been removed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by aikidave** [comment]
@kapunahelewong Can you have a look a this one?

**Review by gkalpak — CHANGES_REQUESTED** [review]
Good catch! Thx, @geromegrignon :+1:

Can you please update the commit message to reference the corresponding issue (per our [commit message guidelines](https://github.com/angular/angular/blob/1d9e56eba06958e37ef8062ae7b65afa85f90632/CONTRIBUTING.md#commit))? 🙏

> docs: remove unused attribute from example
>
> Fixes #41210

**Comment by geromegrignon** [comment]
> Good catch! Thx, @geromegrignon 👍
> 
> Can you please update the commit message to reference the corresponding issue (per our [commit message guidelines](https://github.com/angular/angular/blob/1d9e56eba06958e37ef8062ae7b65afa85f90632/CONTRIBUTING.md#commit))? 🙏
> 
> > docs: remove unused attribute from example
> > Fixes #41210

Done, thanks for the review

**Review by gkalpak — APPROVED** [review]
LGTM

Reviewed-for: global-docs-approvers

**Pull request closed without merging**
