### PR TITLE
docs: remove augury resource from docs, partially addresses #41030

### PR DESCRIPTION
**Pull request by SagarPandita0**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
https://github.com/angular/angular/issues/41030

Issue Number: #41030

## What is the new behavior?
Remove Augury from Documentation

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Partially addresses #41030.

### CODE REVIEW

**Comment by Splaktar** [comment]
The CI errors are very confusing for new contributors. I've started a discussion in Slack on improving this.

For the time being, 

1. This needs to be updated to `138937`:

    https://github.com/angular/angular/blob/c676ec1ce5d586d4bc46e0a18da805c44abd09de/goldens/size-tracking/integration-payloads.json#L6

1. This needs to be updated to `144899`:

    https://github.com/angular/angular/blob/c676ec1ce5d586d4bc46e0a18da805c44abd09de/goldens/size-tracking/integration-payloads.json#L24

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thank you, @SagarPandita0 :+1:
Great job finding and removing all those references in the templates :100:

(And thank you, @Splaktar, for helping out with the payload sizes changes ❤️)

Just a couple of comments:
- Could you remove the PNG file at [aio/content/images/marketing/concept-icons/augury.png][1] too?
- You also need to squash the commits into one. While you're at it, it would be great if you also added `Partially addresses #41030.` to the commit message body (to make it easier to find the issue from the commit in the future):
    > docs: remove augury resource from docs
    >
    > Partially addresses #41030.

(BTW, if you want to address review feedback in a new commit without having to squash commits together at the end, take a look [here][2] to learn about `fixup` commits.)

[1]: https://github.com/angular/angular/blob/2e67a6a5b82d71229d4aec5a596201fac6d237fe/aio/content/images/marketing/concept-icons/augury.png
[2]: https://github.com/angular/angular/blob/c676ec1ce5d586d4bc46e0a18da805c44abd09de/CONTRIBUTING.md#addressing-review-feedback

**Comment by SagarPandita0** [comment]
Hi @gkalpak can you please check if I squashed the commits correctly, I think I may have made a mistake.

**Review by gkalpak — APPROVED** [review]
Thx for making the changes, @SagarPandita0 :+1:
Something was indeed off with the squashing of commits. I fixed it for you, so everything looks fine now 🚀 

Reviewed-for: global-docs-approvers

**Review by Splaktar — APPROVED** [review]

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: size-tracking

**Comment by AndrewKushnir** [comment]
@SagarPandita0 @gkalpak this change had conflicts with the patch branch (`11.2.x`), so I merged the changes to the master branch only. Presumably the merge conflict was in `goldens/size-tracking/integration-payloads.json`. Could you please create a new PR that'd target patch branch? Thank you.

**Pull request closed without merging**
