### PR TITLE
docs: add discord link icon in nav menu

### PR DESCRIPTION
**Pull request by vidhihattar**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

No discord icon link available in navbar menu.

Issue Number: 56097

## What is the new behavior?
Discord icon link added to the navbar menu. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Screenshot 2024-05-28 at 7 37 24 PM

This is how it looks now. Please, let me know if there are any corrections or changes.

### CODE REVIEW

**Comment by JeanMeche** [comment]
Could you amend you commit and remove the changes to the yarn.lock, you didn't update any deps. Thank you.

**Review by JeanMeche — APPROVED** [review]
Change look good, thank you for this ! 
Please fix my previous comment so we can add this to the merge queue. Thank you.

**Comment by vidhihattar** [comment]
I have tried to do so, please have a look.

**Comment by vidhihattar** [comment]
I have done so, please check.

**Comment by JeanMeche** [comment]
Check https://github.com/angular/angular/pull/56129/commits, there are still 2 commits visible. One has unrelated changes.

**Comment by vidhihattar** [comment]
I was trying to fix what was happening in this but somehow this PR got closed. I'll open a fresh PR with correct changes for this. Sorry for the trouble.

**Comment by vidhihattar** [comment]
@JeanMeche I have created a new pull request, please take a look.
https://github.com/angular/angular/pull/56149

**Pull request closed without merging**
