### PR TITLE
docs: spanish documentation added 

### PR DESCRIPTION
**Pull request by AntonioCardenas**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Spanish official documentation added 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
this is possible thanks to the great work of the  [angularhispano community](https://github.com/angular-hispano/angular)

### CODE REVIEW

**Comment by AntonioCardenas** [comment]
@Splaktar sorry here 😅

**Comment by AntonioCardenas** [comment]
Hi @kapunahelewong Doc here

**Comment by Splaktar** [comment]
I brought in the labels from the other PR. Thank you for getting this cleaned up, CI looks good now.

**Review by aikithoughts — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Pull request closed without merging**
