### PR TITLE
fix(compiler): only sets viewDefinition absUrl if the view has either a template or templateUrl

### LINKED ISSUE #1326: "Maximum call stack size exceeded" when compiling component with no View template or templateUrl
Given

```javascript
@Component({
  selector: 'app'
})
@View({
})
class AppComponent {}

bootstrap(AppComponent);
```

Angular fails with

```
Uncaught TypeError: Cannot redefine property: onclick
Uncaught RangeError: Maximum call stack size exceeded
```

There's an [existing throw](https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/compiler/template_loader.js#L45) intended to handle views without a `template` or `templateUrl`, but it never gets hit because the `viewDefinition`'s `absUrl` property gets set in `Compiler#_buildRenderTemplate` regardless.

### PR DESCRIPTION
**Pull request by matthewjh**
fixes #1326

### CODE REVIEW

**Comment by tbosch** [comment]
Could you throw an exception instead?

**Comment by tbosch** [comment]
And please have a look at why Travis failed...

**Comment by matthewjh** [comment]
@tbosch:

There is already an exception thrown for this scenario in TemplateLoader: https://github.com/matthewjh/angular/blob/compiler-patch-mh/modules/angular2/src/render/dom/compiler/template_loader.js#L45

This PR just ensures that that line is reachable.

**Comment by matthewjh** [comment]
I'll take a look at the CI. Last time I did, though I couldn't figure out why the dart analyser was erroring.

**Comment by tbosch** [comment]
@matthewjh Ok, sounds good.

**Comment by mhevery** [comment]
any update on this?

**Comment by matthewjh** [comment]
Good to go. @mhevery @tbosch

**Comment by naomiblack** [comment]
@vicb this is good to go. Could you merge it in please?

**Pull request closed without merging**
