### PR TITLE
fix(compiler-cli): set tsickle convertIndexImportShorthand to false

### LINKED ISSUE #16152: AOT build fails with fesm modules and if modules import path's `index` omitted
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[*] feature request
[] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In my library's modult.ts,  we got an AOT compile issue, here is the example code:

``` typescript
// AOT not pass
import { MyDateModule } from './date';   // path without index
import { MyHttpService } from './http';   // path without index
export function MyHttpServiceFactory (_backend: XHRBackend, _option: RequestOptions) {
  return new MyHttpService(_backend, _option);
}
export const MY_HTTP_PROVIDERS = {
  provide: MyHttpService,
  useFactory: MyHttpServiceFactory,
  deps: [
    XHRBackend,
    RequestOptions
  ]
};
@NgModule({
  imports: [
    CommonModule,
    HttpModule,
    MyDateModule
  ],
  exports: [
    MyDateModule
  ]
})
export class MyModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: MyModule,
      providers: [
       MY_HTTP_PROVIDERS
      ]
    };
  }
}
```

Here is the aot build error message:

```
Unexpected value 'null' imported by the module 'MyModule in /Users/
naiteluo/Code/maid/dist/packages/demo-app/maid/typings/index.d.ts'
```

``` typescript
// AOT pass 
import { MyDateModule } from './date/index';
import { MyHttpService } from './http/index';
export function MyHttpServiceFactory (_backend: XHRBackend, _option: RequestOptions) {
  return new MyHttpService(_backend, _option);
}
export const MY_HTTP_PROVIDERS = {
  provide: MyHttpService,
  useFactory: MyHttpServiceFactory,
  deps: [
    XHRBackend,
    RequestOptions
  ]
};
@NgModule({
  imports: [
    CommonModule,
    HttpModule,
    MyDateModule
  ],
  exports: [
    MyDateModule
  ]
})
export class MyModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: MyModule,
      providers: [
       MY_HTTP_PROVIDERS
      ]
    };
  }
}
```

the index.ts files do exist, and both of the example above can pass the dev build. But without `index` in the import path, aot build fails.

**Expected behavior**

Module can be import without `index`.

**Minimal reproduction of the problem with instructions**

Using material2's repo can reproduce the problem:

1. clone material2:  https://github.com/angular/material2.git
2. edit `./material2/src/lib/module.ts`, remove some of the `index` in the import path, for example:
``` typescript
import {MdButtonToggleModule} from './button-toggle'; // remove index
import {MdButtonModule} from './button';  // remove index
import {MdCheckboxModule} from './checkbox/index';
import {MdRadioModule} from './radio/index';
```
3. run `gulp aot:build`, then build fails with error: `Unexpected value 'null' imported by the module 'MaterialRootModule in /Users/
naiteluo/Code/material2/dist/packages/demo-app/material/typings/index.d.ts'`

**What is the motivation / use case for changing the behavior?**

I am trying to build my own library and i choose use material2's project as the sketch of my own project so i can save my time configuring the project. I can't post my own code here, but the material library can reproduce the problem.

I meet the aot compile error but the original material2 library pass the aot compile. I have no idea what is going on. Then i try to compare my code with material2 library, i find out the import module with full path like `./autocomplete/index`, and in my own library i wrote with short path like `./my-own-module`

As usual I wrote import path without `index`, and the dev build works, but aot fails. It is a bug of angular-compiler that it fails to resolve import path without `index`?

More and more, it is really hard to understand aot build error. Much more clear error message (likes line number, file name) and additionally guide will be appreciated.

**Please tell us about your environment:**

mac os, node v6.9.5, npm 3.10.10, yarn v0.21.3

relative package version:

```
"@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "systemjs": "0.19.43",
    "zone.js": "^0.8.4"
"@angular/compiler-cli": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "^4.0.0",
"ts-node": "^3.0.0",
    "tslint": "^5.0.0",
    "tslint-no-unused-var": "0.0.6",
    "typescript": "~2.1.1",
```

* **Angular version:** 4.0.2

angular compiler version 4.0.2

---

Anybody knows what is going on? Hoping someone to point out.  Thank You!!

### PR DESCRIPTION
**Pull request by dherges**
Closes #16152

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: See #16152

## What is the new behavior?

See angular/tsickle#376

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by alexeagle** [comment]
Thanks! Ideally we should find a way to reproduce the issue, so that we don't have an accidental regression.

**Review by alexeagle — APPROVED** [review]

**Comment by dherges** [comment]
Hm hm ... would need to be an integration test I think that uses `ngc`. I have maybe one  ... 

tsconfig.json

```json
{
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "flatModuleId": "@org/components",
    "flatModuleOutFile": "components.js",
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true
  },
  "buildOnSave": false,
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "",
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "",
    "declaration": true,
    "sourceMap": true,
    "inlineSources": true,
    "skipLibCheck": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "dom",
      "es2015"
    ]
  },
  "exclude": [
    "node_modules",
    "dist",
    "**/*.ngfactory.ts",
    "**/*.shim.ts",
    "**/*.spec.ts"
  ],
  "files": [
    "public_api.ts"
  ]
}
```

TypeScript source:

```ts
import { Headers, Http, Response, URLSearchParams } from '@angular/http';
import { TranslateLoader } from '@ngx-translate/core';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/observable/combineLatest';
```

Generated JavaScript:
```js
import { Headers, URLSearchParams } from '@angular/http';
import { TranslateLoader } from '@ngx-translate/core/index';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/observable/combineLatest';
```

**Comment by LinBoLen** [comment]
aha, remind me there are convertIndexImportShorthand options.

dislike auto change import. prefer node resolve

**Comment by dherges** [comment]
@alexeagle where should the above test/repro be added? Is it good enough as reproduction?

Another repro can be found in [ngx-codemirror](https://github.com/avatsaev/ngx-codemirror/blob/master/.ng_build/ts/directives/codemirror.directive.js#L2) ... here it's more "deep-hidden" because [`"annotateForClosureCompiler": true`](https://github.com/avatsaev/ngx-codemirror/blob/master/.ng_build/ts/tsconfig.lib.json#L3) turns on tsickle and that results in the `convertIndexImportShorthand: true`.

**Comment by Frozen-byte** [comment]
any updates?
I'd like to see this changes taking action.

**Comment by alexeagle** [comment]
Sorry I lost this one. @chuckjaz made this change already I believe?

**Comment by alexeagle** [comment]
Yes, it was in https://github.com/angular/angular/commit/f24ea59f74552113f8e8586d2d69045254512aa1#diff-3153093ed4c8893b1a1c791b9ad85813

**Comment by chuckjaz** [comment]
This is not in `master` and in the `4.4.x` branches and will be in the next release of both the `5.0.0` RC and `4.4.5`.

**Comment by alexeagle** [comment]
I think s/not in/now in/ ?

**Comment by chuckjaz** [comment]
I fixed it on github just after the mail went out.

**Pull request closed without merging**
