### PR TITLE
build(docs-infra): upgrade cli command docs sources to 9e3aebbcc

### PR DESCRIPTION
**Pull request by gkalpak**
Updating [angular#11.0.x](https://github.com/angular/angular/tree/11.0.x) from [cli-builds#11.0.x](https://github.com/angular/cli-builds/tree/11.0.x).

##
Relevant changes in [commit range](https://github.com/angular/cli-builds/compare/4f756ce2f...9e3aebbcc):

**Modified**
- help/analytics.json
- help/build.json
- help/config.json
- help/e2e.json
- help/extract-i18n.json
- help/generate.json
- help/lint.json
- help/new.json
- help/serve.json
- help/test.json
- help/update.json

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
See https://github.com/angular/angular/pull/39943#issuecomment-738040058

**Review by petebacondarwin — APPROVED** [review]

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Comment by gkalpak** [comment]
Superceded by #39971.

**Review by atscott — APPROVED** [review]
Reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by gkalpak** [comment]
Superceded by #39986.

**Comment by gkalpak** [comment]
Superceded by #39992.

**Comment by gkalpak** [comment]
Superceded by #40001.

**Comment by mhevery** [comment]
Closed by commit 28bf4d1422c55a9700c3c815ff7a0192a3b88c90

**Pull request closed without merging**
