### PR TITLE
docs: lifecycle-hooks example - extract things (components, directive…

### PR DESCRIPTION
**Pull request by AlexElin**
…s) into their own files

Currently in this example there're 2 ways to place things into files: thing-per-file (peek-a-boo parent/child components) and all-in-one (others).
This change brings to thing-per-file way.
It is in line with Angular Style Guide rule 01-01
https://angular.io/guide/styleguide#style-01-01.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gkalpak** [comment]
@googlebot I consent.

**Review by gkalpak — APPROVED** [review]
Thx, @AlexElin!

I have pushed a commit with some minor changes (mostly to fix indendation).
The PR looks good to me, but marking with `action: cleanup` to give you a chance to look at my changes and confirm they look good to you too.

Reviewed-for: global-docs-approvers

**Comment by AlexElin** [comment]
@gkalpak LGTM

**Comment by AlexElin** [comment]
@googlebot I consent.

**Pull request closed without merging**
