### PR TITLE
docs(aio): update pipes for CLI

### PR DESCRIPTION
**Pull request by Foxandxss**
Part of #19510 

I was deciding between deleting the callout altogether or updating it.

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]

**Review by wardbell — APPROVED** [review]
LGTM and urgent to get aligned with v.5
We can do more polishing later

**Comment by vicb** [comment]
I'm not merging red PRs without comment

**Comment by IgorMinar** [comment]
I've changed the label to master&patch. we want this change to be cherry-picked into the 5.0.x branch

**Comment by IgorMinar** [comment]
I've restarted the failed job. looks like a flake of some sort. I haven't seen this failure before.

**Pull request merged**
