### PR TITLE
fix(router): ensure preactivation orders guards correctly (#12377)

### LINKED ISSUE #12377: Router: Guards fired out of order for reused-but-changed nodes
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When navigating between routes that reuse nodes (i.e. different URLs triggering the same route config branches), the guards are fired out of order. Specifically, the guards for the reused node are called before _any_ other guards are checked.

**Expected behavior**
The guard order should universally be deactivations from leaf to root and then activations from root to leaf.

**Minimal reproduction of the problem with instructions**
See http://plnkr.co/edit/TQjNmR?p=preview

When changing both nodes in a navigation (i.e. from /A/A to /B/B), the guards are called in the order:
- DEACTIVATE: branch
- ACTIVATE: branch
- DEACTIVATE: leaf
- ACTIVATE: leaf

The order should be:
- DEACTIVATE: leaf
- DEACTIVATE: branch
- ACTIVATE: branch
- ACTIVATE: leaf

**What is the motivation / use case for changing the behavior?**
Maintaining a consistent ordering of guards. Deactivating a service tied to a parent route before the service tied to the child could break programmers expectations about flow.

**Please tell us about your environment:**
Mac OSX, Atom, npm, webpack, served via webpack-dev-server (dev) & nginx (prod).
- **Angular version:** 2.0.X, 2.1.X (plunker demonstrates 2.1.0)
- **Browser:** Only tested in Chrome 53, but should be relevant to all
- **Language:** TypeScript 2.0.3, but should be relevant to all

### PR DESCRIPTION
**Pull request by tdhsmith**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)  _N/A -- fix brings behavior in line with the existing docs._

**What kind of change does this PR introduce?** (check one with "x")

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
#12377

**What is the new behavior?**
Reused nodes add their guards to the to-check list in a manner that maintains the overall order of (deactivations leaf-to-root, then activations root-to-leaf).

**Does this PR introduce a breaking change?** (check one with "x")

```
[X] Yes (sort-of??)
[ ] No
```

If anyone was dependent on the existing (_incorrect_ and _undocumented_) ordering, they could use guards to trigger a singular service which would enforce their desired behavior upon the operations, or for certain setups they may be able to restructure the route hierarchy to execute in the way they desire.

IMO, it seems highly unlikely anyone would be super dependent on the existing behavior though, because it is incongruous and defies the inherent hierarchy of the route configuration.

**Other information**:

Fixes #12377

### CODE REVIEW

**Comment by tdsmithATabc** [comment]
I've added my work email as an alternate email on my Google account, but I don't see any way to change/update the email I signed the CLA "as"?

**Comment by DzmitryShylovich** [comment]
git config email

**Comment by tdhsmith** [comment]
Oh just amend the commits and force push over these?

**Comment by tdhsmith** [comment]
Is there a code-based reason why TravisCI failed? Reading [the log](https://travis-ci.org/angular/angular/jobs/169286608), I only see warnings about failing to launch browsers...

**Comment by vsavkin** [comment]
I'd rather change `checkGuards` to have two separate passes over the checks array. Could you make this change?

**Comment by jasonaden** [comment]
@tdhsmith I'm going through past PRs on the router. It looks like your original issue is still open and this PR was never finished. Are you able to go in and rebase this PR so we can see if it'll pass Travis?

**Comment by tdhsmith** [comment]
Yep, I can revisit it sometime this week! Ended up not needing the fix for my work project and it fell off my checklist...

**Comment by jasonaden** [comment]
Closing as requested changes not addressed. Open a new PR is this is still needed.

**Pull request closed without merging**
