### PR TITLE
build: lock file maintenance

### PR DESCRIPTION
**Pull request by josephperrott**
Update the lock file.

### CODE REVIEW

**Comment by devversion** [comment]
do we know where the symbol golden diff is coming from? I can help investigate tomorrow

**Comment by josephperrott** [comment]
The symbol golden diff seemed to come about after I bumped the babel versions.

**Comment by devversion** [comment]
We should potenially try to see if this affects anything with tree-shaking, or why we see the diff

**Comment by JeanMeche** [comment]
I can reproduce this by only updating terser. (running `yarn && yarn upgrade terser@latest`)

**Comment by JoostK** [comment]
> I can reproduce the symbol changes by only updating terser. (running `yarn && yarn upgrade terser@latest`)

Then it's because of https://github.com/terser/terser/commit/33d53e0cf24fffeb935f720e1f84cc66b9c8bc3a, which was released in 5.19.4 which this change updates from. So it's likely that the code was always present, just inlined into their (single) usage sites.

**Comment by JeanMeche** [comment]
Yeah this is it, the functions added didn't look tree-shakable to me. 👍

**Comment by devversion** [comment]
Thanks @JeanMeche for verifying. Yeah, I suspected it being due to inlining. We had similar changes in the past, but want to make sure we are approving these golden changes with reasoning. Thx

**Review by devversion — APPROVED** [review]
LGTM

Reviewed-for: global-dev-infra-approvers

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 5269cae788abc4a95078b9c6e5d43af221a8a9cd.

**Pull request closed without merging**
