### PR TITLE
docs(aio): fix rxjs import

### LINKED ISSUE #20349: Issue with importing Observable from rxjs/Rx (import-blacklisted)
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I was following [this part of our official guide](https://angular.io/tutorial/toh-pt4#observable-heroservice).
```ts
import { Observable } from 'rxjs/Rx'; // this line rises a tslint err
import { of } from 'rxjs/observable/of';
```
import blacklisted

```
ERR: [tslint] This import is blacklisted, import a submodule instead (import-blacklist)
```
Please shed some light on this issue.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1  
- Platform:  Linux, Windows.

</code></pre>

## other info
Just in case if you are interested in my `tslint.json`. (same as generated by `ng new`)
```json
{
	"rulesDirectory": ["node_modules/codelyzer"],
	"rules": {
		"arrow-return-shorthand": true,
		"callable-types": true,
		"class-name": true,
		"comment-format": [true, "check-space"],
		"curly": true,
		"eofline": true,
		"forin": true,
		"import-blacklist": [true, "rxjs", "rxjs/Rx"], <<<<
		"import-spacing": true,
		"indent": [true, "tabs"],
		"interface-over-type-literal": true,
		"label-position": true,
		"max-line-length": [true, 140],
		"member-access": false,
		"member-ordering": [
			true,
			{
				"order": [
					"static-field",
					"instance-field",
					"static-method",
					"instance-method"
				]
			}
		],
		"no-arg": true,
		"no-bitwise": true,
		"no-console": [true, "debug", "info", "time", "timeEnd", "trace"],
		"no-construct": true,
		"no-debugger": true,
		"no-duplicate-super": true,
		"no-empty": false,
		"no-empty-interface": true,
		"no-eval": true,
		"no-inferrable-types": [true, "ignore-params"],
		"no-misused-new": true,
		"no-non-null-assertion": true,
		"no-shadowed-variable": true,
		"no-string-literal": false,
		"no-string-throw": true,
		"no-switch-case-fall-through": true,
		"no-trailing-whitespace": true,
		"no-unnecessary-initializer": true,
		"no-unused-expression": true,
		"no-use-before-declare": true,
		"no-var-keyword": true,
		"object-literal-sort-keys": false,
		"one-line": [
			true,
			"check-open-brace",
			"check-catch",
			"check-else",
			"check-whitespace"
		],
		"prefer-const": true,
		"quotemark": [true, "single"],
		"radix": true,
		"semicolon": [true, "always"],
		"triple-equals": [true, "allow-null-check"],
		"typedef-whitespace": [
			true,
			{
				"call-signature": "nospace",
				"index-signature": "nospace",
				"parameter": "nospace",
				"property-declaration": "nospace",
				"variable-declaration": "nospace"
			}
		],
		"typeof-compare": true,
		"unified-signatures": true,
		"variable-name": false,
		"whitespace": [
			true,
			"check-branch",
			"check-decl",
			"check-operator",
			"check-separator",
			"check-type"
		],
		"directive-selector": [true, "attribute", "app", "camelCase"],
		"component-selector": [true, "element", "app", "kebab-case"],
		"use-input-property-decorator": true,
		"use-output-property-decorator": true,
		"use-host-property-decorator": true,
		"no-input-rename": true,
		"no-output-rename": true,
		"use-life-cycle-interface": true,
		"use-pipe-transform-interface": true,
		"component-class-suffix": true,
		"directive-class-suffix": true,
		"invoke-injectable": true
	}
}
```
Related: https://github.com/angular/angular-cli/issues/7591

### PR DESCRIPTION
**Pull request by trotyl**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

importing from `rxjs/Rx` which is forbidden by codelyzer.

Issue Number: closes #20349

## What is the new behavior?

importing from `rxjs/Observable` for `Observable`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by suresh2018** [comment]
Yes

**Comment by gkalpak** [comment]
Have you checked whether there are changes necessary in prose?

**Review by gkalpak — APPROVED** [review]

**Comment by trotyl** [comment]
Searched for `rxjs` keyword, seems no specific path were used in prose.

**Comment by trotyl** [comment]
I guess the `closes #xxx` magic words should be added to commit instead of PR since Angular is using custom merge tool?

**Comment by gkalpak** [comment]
> Update: added closes #20349 to commit itself.

Most of the time having it on the PR decription is sufficient, but not always. Having it on the commit message is safest (and recommended - by me :grin:).

> Update: just found out I have never followed the commit guideline, no one complained that to me.

Are you sure you didn't? Your commit messages look fine to me 😄

**Comment by trotyl** [comment]
> Footer
> 
> The footer should contain any information about Breaking Changes and **is also the place to reference GitHub issues that this commit Closes**.

I mean I just found that in the guide, only knew about the first line previously 😄

**Pull request closed without merging**
