### PR TITLE
feat(router): extend support for lazy loading children

### LINKED ISSUE #10659: router: Add a factoryProvider field to router
Example of usage:

```typescript
function getThatThing() { return System.import('my/path/to/module').then(x => return x.MyClass); }

@NgModule({
  declarations: [ /* ... */ ],
  imports: [
    RouterModule.forRoot({
      { path: 'lazy', factoryProvider: getThatThing }
    })
  }
})
export class MyModule {}
```

Signature of function:

```typescript
interface ModuleFactoryProvider {
  (this: void) => ConcreteType | Promise<ConcreteType>;
}
```

This would be useful for webpack 1 and 2 lazy routes, as webpack does not understand `System.import()` that deep in the module resolver providers (with string parsing etc).

### PR DESCRIPTION
**Pull request by vsavkin**
Closes #10659

### CODE REVIEW

**Comment by robwormald** [comment]
LGTM

**Comment by hansl** [comment]
LGTM as well.

**Comment by sirajc** [comment]
@brandonroberts This will help in simplification of your AsyncNgModuleLoader, I think

**Comment by brandonroberts** [comment]
Yep. It actually removes the need for it which is great. Now you can
provide your bundlers method to import through a function that returns a
promise.

**Comment by vikerman** [comment]
TAP Blocked

**Comment by ocombe** [comment]
ohhh does this mean that we can use webpack to generate bundles on its own again with the router ?

**Comment by brandonroberts** [comment]
@ocombe yep. No longer need a custom loader for webpack support.

**Comment by seveves** [comment]
Can I see this in action anywhere?

**Comment by ocombe** [comment]
In webpack it's as simple as:

```ts
const routerConfig: Routes = [{
  path: '',
  loadChildren: () => System.import('./Home').then(({HomeModule}) => HomeModule)
}]
```

**Comment by seveves** [comment]
@ocombe thank you but now it says "System is not defined" ... do I need to do any changes to my webpack config?

**Comment by ocombe** [comment]
Ah my bad, System is only available in webpack 2, if you're using webpack 1 you can do:

```ts
const routerConfig: Routes = [{
  path: '',
  loadChildren: () => new Promise(resolve => require.ensure([], require => resolve(require('./Home').HomeModule)))
}]
```

**Pull request merged**
