### PR TITLE
build(devtools): Optimize prod build for Angular DevTools

### PR DESCRIPTION
**Pull request by AleksanderBodurri**
Uses `createEsbuildAngularOptimizePlugin` from dev-infra-private and passes in `GLOBAL_DEFS_FOR_TERSER_WITH_AOT` into a new esbuild prod configuration.

Notably, this removes references to `ngDevMode` from the final build and enables minification.

### CODE REVIEW

**Review by mgechev — APPROVED** [review]
LGTM from Angular DevTools side.

**Review by devversion — APPROVED** [review]
Yay, worth mentioning that the dev-infra `app_bundling` rule replicates the CLI pipeline, leveraging terser as well.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit b7fca648286585e0cd6d409b823d2055c380db13.

**Comment by AndrewKushnir** [comment]
There was a merge conflict with the 13.3.x branch, so this PR was merged into the main and 14.0.x branches only. Could you please create a new PR and target the 13.3.x branch if the change should be included there as well? Thank you.

**Pull request closed without merging**
