### PR TITLE
fix(router): child CanActivate guard should wait for parent to complete

### LINKED ISSUE #15670: CanActivate guards on child routes run before parent CanActivate guards finish
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When both a route and it's parent have an asynchronous `canActivate` guard, and the child is navigated to directly, both guards are run at same time.

**Expected behavior**
The parent's `canActivate` guard should run before the child's guard.  If the parent's guard is unsuccessful the child guard should not be run.  If a route defines multiple `canActivate` guards, those can/should be run in parallel.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/s4R0INS7qjuFnRpyD8eF?p=preview

Plunker has a nested route `/parent/child`.  Both have guards that simply wait and then return true.  Each guard logs its start/end as well as a tick once per second to a logging service that is displayed in the root component.

Click 'Go to Child` to trigger both the Parent Guard and the Child guard at the same time, and observe that they process simultaneously in the log.

**What is the motivation / use case for changing the behavior?**

In my athepp, `ParentGuard` checks to see if the user is authenticated and redirects accordingly, and `ChildGuard` loads protected data. Right now, my child guard cannot assume the user is logged in, so I have to duplicate logic from the authorization guard to wait for the user to be loaded. When I have a grandchild route, that has to duplicate logic from two parent guards.  I would like to be able to separate concerns more rather than duplicate auth logic in all my guards.

**Please tell us about your environment:**

* **Angular version:** 4.0.1

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Closes #15670

http://plnkr.co/edit/MY3XRClqXi2wwOWem4My?p=preview

### CODE REVIEW

**Comment by vicb** [comment]
LGTM, could you please add a test

**Review by vicb — CHANGES_REQUESTED** [review]
Please add a test

**Comment by DzmitryShylovich** [comment]
@vicb added a test. I'm afraid in this case I can't avoid playing with timings.

**Comment by nrgonzalez777** [comment]
@DzmitryShylovich I ran into the bug that this changeset is attempting to solve and I can confirm that this change does force the guards to activate in the correct order. However, this change seems to also cause a more subtle error to occur.

I have a guard defined that in the case of an error is supposed to navigate to the root of my application. Before making the change from mergeMap to concatMap the navigation on error seems to work fine. Unfortunately after swapping out the functions in the Angular source code the navigate no longer navigates back correctly. While it doesn't throw any errors, the root application page no longer renders.

```javascript
canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
        var success = false;
        var productId = route.params['productId'];

        success = this.ngRedux.getState().products.find(p => p.id === productId) !== undefined;

        if (success) {
            this.pageActions.updatePageState({ productId: productId });
        }
        else {
            this.router.navigate(['/']);
        }

        return success;
    }
```

**Comment by DzmitryShylovich** [comment]
@nrgonzalez777 can you please provide a small plunkr with the code that does work before the fix and doesn't work after? Because I can't reproduce.

**Pull request closed without merging**
