### PR TITLE
fix(zone.js): do not run stack formatting when the lazy stack frames policy is used

### PR DESCRIPTION
**Pull request by arturovt**
We don't have to read the `stack` property when the lazy stack frames policy is used.
The V8 triggers the stack trace serialization only when the `stack` property is read for
the first time within the `Accessors::ErrorStackGetter`. We want to avoid formatting the stack
trace when the lazy policy is used, and we don't need the stack until the `zoneAwareStack`
property is read.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type
- [x] Bugfix

## What is the current behavior?
Issue Number: #43240

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by arturovt** [comment]
@JiaLiPassion friendly ping :)

**Review by JiaLiPassion — APPROVED** [review]
LGTM! Thanks for the fix.

**Comment by arturovt** [comment]
@AndrewKushnir I know zones is not your scope (not sure who I should ping here), are you able to look why the presubmit is failing?

**Comment by AndrewKushnir** [comment]
@arturovt quick update: there is a number of failing targets in Google's codebase, which would take sizable time to investigate. Given that the original issue has no duplicates or upvotes, we may not be able to prioritize this investigation in the near future. We'll discuss this with the team early next week and I'll let you know.

**Comment by arturovt** [comment]
Closing since this breaks some tests internally, which would require some effort to investigate and land in g3.

**Pull request closed without merging**
