### PR TITLE
fix(bazel): speed up `d.ts` bundling by configuring worker

### PR DESCRIPTION
**Pull request by devversion**
Speeds up the `d.ts` bundling by configuring it as a Bazel
persistent worker. Also improve logging for the ng packager
rule to make it easier to spot which actions/bundles take
up significant time.

Type bundling will occur for every entry-point so for machines
with rather limited cores/threads, this will be useful to save
NodeJS boot and resolution time.

### CODE REVIEW

**Review by josephperrott — DISMISSED** [review]
LGTM

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by AndrewKushnir** [comment]
FYI, the NgBot was requesting a presubmit, but we were not syncing anything from those files into g3. I've created a PR to update NgBot config (based on the internal config): https://github.com/angular/angular/pull/45901. Thank you.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit a6b6590339013f9216d5691ebc413fa6fa250ea2.

**Pull request closed without merging**
