### PR TITLE
docs(core): fix typo for lifecycle hooks

### PR DESCRIPTION
**Pull request by dardarbinx**
changed 'hoooks' to 'hooks'

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks for the PR @dardarbinx! I left you some feedback. You will also need to sign the CLA before this can be merged.

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update the commit message to `docs(core): fix typo for lifecycle hooks`

**Comment by brandonroberts** [comment]
If you're still interested making this change, reopen this PR.

**Comment by alfaproject** [comment]
@brandonroberts he changed the commit message, so what was left to do here?

**Comment by brandonroberts** [comment]
@alfaproject sign the CLA.

**Pull request closed without merging**
