### PR TITLE
docs(docs-infra): Move tutorial click handler from li to button

### PR DESCRIPTION
**Pull request by martiansnoop**
I want to gauge interest in this change before fully implementing 
it, so that is why I have not checked the following boxes yet. I am
proposing this change for accessibility reasons.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The Tour of Heroes tutorial demonstrates click bindings by putting one
on an `li` element. This works but has some disadvantanges:

* `li` elements are not naturally in the tab order, so are
inaccessible to keyboard-only navigation
* click handlers on non-interactive elements is also problematic 
for screen readers

Issue Number: N/A

## What is the new behavior?

This commit places the contents of the `li` inside a button element in 
order to demonstrate accessible code to readers of the tutorial.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This commit is quick and dirty to illustrate what I want to change and
gauge interest from the angular team before continuing. A list of
further tasks is at the end of this commit message.

It makes sense that the Tour of Heroes tutorial is choosing to use
simple, short code to reduce the number of concepts that the reader needs
to be exposed to. However, click handlers on non-interactive elements is
a very common accessibility problem, so I think addressing it in a
popular tutorial could do some good.

If the direction of this PR is accepted, the following still need to be 
done:

[] update the css to style the button appropriately
[] update wording in the tutorial to reflect changes in code
[] change the code in all steps of the tutorial
[] learn how to build the documentation and make sure it looks right

### CODE REVIEW

**Comment by martiansnoop** [comment]
I signed it!

**Comment by jenniferfell** [comment]
@chembu Thoughts?

**Comment by chembu** [comment]
My two cents: From an accessibility point of view using an HTML <button> for click handler seems reasonable.  But from a tutorial perspective, we are showing users to create a list of heroes and using an HTML <li> seems to make more sense than having a list of buttons. I thinking engineers can have the final say on how they want to design the TOH app.

**Comment by martiansnoop** [comment]
Is it correct that the argument against making this change comes from wanting to keep the tutorial simple? I could definitely be missing some of the big picture here, as there's a lot I still need to learn about Angular and accessibility.

A bit of background: For a long time I didn't know that putting click handlers on elements that were not designed for clicking was the specific reason why some elements were invisible to a keyboard when tabbing through the page. I was just copying things I saw other people do with AngularJS/Angular in various tutorials. 

Due to some recent circumstances, a mouse is sometimes very inconvenient for me to use now, so I felt a little bit frustrated that I would need to do the tutorial differently if I wanted something that I could use. (I happen to know what to change, but I don't think every engineer learning Angular will necessarily know this.) So I think this change will make the TOH tutorial more accessible to more engineers, in addition to providing an example of accessible click handlers to sighted, mouse-using engineers.

**Comment by headquarters** [comment]
I support changing the tutorial to not add click handlers to HTML elements that are not naturally interactive with the keyboard. Unless full keyboard interactivity has been developed (tab focus, handling key presses, etc), then this particular step in the tutorial violates [WCAG 2.0 Guideline 2.1.1 for operability](https://www.w3.org/TR/WCAG20/#keyboard-operation).

**Comment by martiansnoop** [comment]
I started updating the CSS on step 2 of the tutorial (will propagate to other steps when/if the changes are agreed to be acceptable). Currently I've changed more lines than I think will be acceptable (though I am not sure and would appreciate opinions from the maintainers). 

The problem I had was that the badge and the text inside the `li` were marked with `position: relative` and adjusted by precise pixel values, and I was having a hard time updating them correctly, so as a first draft I removed the relative positioning to see if I could get it looking right without it. It seemed like unnecessary work to position those elements manually instead of letting the browser do it; however, I am doubtlessly missing context.

1. Is the move away from relative positioning acceptable for this tutorial?
    * reason for: tutorial CSS becomes simpler
    * reason against: I have missed something and the relative positioning is important to the functionality, or it is a standard convention that I don't know about
2. If the change is acceptable, should those changes be done in a different PR?

Thanks!

**Comment by kapunahelewong** [comment]
Hey @martiansnoop, I'm 100% supportive of making the examples accessible. I have another PR in for the Tour of Heroes that has some CSS changes. Would you want to continue on this one after mine (#28571) lands? It might be easier in terms of rebasing. Please feel free to tag me at any point in the process and I can help you with moving this through the process. Thank you tons for this!

**Comment by martiansnoop** [comment]
@kapunahelewong Yes, absolutely! I'll subscribe to updates from your PR so I know when it lands. And thanks for the commit message tip!

**Comment by martiansnoop** [comment]
Current status: I rebased, and tweaked the CSS a little bit more (added the same styles on focus as on hover for sighted keyboard users, and because of that, removed the focus outline as well). There are a few visual differences that I think are an improvement (the badge and the hero name now have the same font size and baseline so they're lined up vertically), but it'd be best if someone reviewed and gave a thumbsup before I propagate it to the other steps in the tutorial. 

I attached a screenshot below. The first button is the selected one, and the second button has focus/hover styles applied. Thanks!

Screenshot from 2019-08-17 22-19-31

**Comment by kapunahelewong** [comment]
@martiansnoop It's looking good! What do you think about the contrast on the selected and hover/focus states? I'm not well versed in it, so I used the [WebAIM contrast checker](https://webaim.org/resources/contrastchecker/) and it's cool! The pass/fail indicators are really handy as you choose different colors. Would you like to edit the colors too? I know your original intent was moving the click handler, so if you'd rather not, it's totally fine and I can try my hand after we get yours in. What do you think?

Btw, there isn't a particular design scheme in the examples, so it's not like we must use certain colors. We have a lot of flexibility.

**Comment by martiansnoop** [comment]
Thanks for the response/feedback! I have a hard time reading the colors as well, so I decided to take a look at that part. I'm not that skilled at design, so my first instinct was to make the text black since it's super simple. Screenshot of the three scenarios (selected+hover, selected, hover): 

Screenshot from 2019-08-20 21-33-37

The WebAIM contrast tool approves all 3 button bg+fg combos. One thing I'd be interested in is whether the "selected hover" blue looks visually acceptable with the black text -- it looks fine to me but my monitor isn't very well calibrated. 

Unrelated to the colors, there are a few issues I noticed in my changes:

1. There's a slightly weird behaviour currently where when you click one of the buttons, since it gains focus, it keeps the brightest blue background until you click somewhere else, or tab away. 
    a) maybe this is fine?
    b) perhaps the selected button shouldn't have a separate hover effect since clicking it will not change the page? I like the idea of using the bright shade of blue for "selected" because it looks very obviously selected to me, while the middle blue is a little more ambiguous.
    c) perhaps we should change the bg for selected+hover, but not selected+focus, and let the default focus outline indicate focus?
2. (not pictured) I initially removed the focus outline since we're applying our own focus styles, but I decided to put it back because it seems tricky to have 3 shades of button bg colors that are sufficiently different from a) the page background, b) each other, and c) and the button foreground to guarantee that a sighted keyboard user would be able to distinguish them.
    a) This does look a tiny bit weird since the button is custom and the focus ring is the browser default. Maybe we should change the focus ring to match the badge color or something as a cheap way to make it coherent? I'll experiment with that tomorrow or Thursday. It might make sense to just leave the focus ring as the default for simplicity, too.

**Comment by kapunahelewong** [comment]
Wow, thanks for all your work on this, @martiansnoop. The black color for the font looks good to me, and I'd have to rely on the WebAIM tests, too. 

Your questions are great, so I'm going to tap our resident expert, @jelbourn. @jelbourn, @martiansnoop is helping us make this example app more accessible and has some questions above. Could you share your thoughts on this with us? Thank you!

**Comment by jelbourn** [comment]
So I've never looked at this app before, but my immediate impression just from the code in this PR is that the interaction here should actually be a `role="listbox"` because it's selecting one or more options from a set of values. A regular list (`ul` or `ol`) is always non-interactive and should only contain non-interactive content. 

In Angular Material, we have four different variants of "list" for their different interaction patterns:
* Navigation list: this is a `role="navigation"` element that contains anchors (`<a>`)
* Action list: just a sequence of `<button>` elements
* Selection list: uses `role="listbox"`
* Plain list: no roles, user needs to add their own custom interaction

**Comment by martiansnoop** [comment]
> the interaction here should actually be a role="listbox"

Ah, that makes sense to me. I have what is perhaps a silly question for all involved here: Would it make sense to modify this code to use a select tag and ngModel instead of a custom listbox? So something like

```
<select size="{{heroes.length}}" ([ngModel])="selectedHero">
    <option *ngFor="let hero of heroes" etc> {{name}} </option>
</select>
```

The reason why I'm asking is because I read some documentation for listbox and there are a lot of extra keyboard interactions that would need to be implemented: https://www.w3.org/TR/wai-aria-practices-1.1/#listbox_kbd_interaction

**Comment by jelbourn** [comment]
Yes, a native `<select>` would be the best and most straightforward thing.

**Comment by petebacondarwin** [comment]
@martiansnoop - did you want to update the example to use a `select` as agreed with @jelbourn ?

**Comment by AndrewKushnir** [comment]
Closing this PR for now due to the lack of response. Please reopen if needed. Thank you.

**Pull request closed without merging**
