### PR TITLE
refactor(animations): remove unecessary interface

### PR DESCRIPTION
**Pull request by JeanMeche**
`Animation` is provided by `lib.dom`.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM

I think this should be fine in Google, but just to be safe I'll run a TGP.

**Comment by JeanMeche** [comment]
How did the TGP go ?

**Comment by JeanMeche** [comment]
@jessicajaniuk Can we move forward on this ?

**Comment by jessicajaniuk** [comment]
@JeanMeche Yes, but we still need to run the TGP. That's the hold up.

**Comment by jessicajaniuk** [comment]
[TGP](https://fusion2.corp.google.com/presubmit/553123731/OCL:553123731:BASE:553123759:1690982251382:20f55aef/targets)

**Comment by jessicajaniuk** [comment]
Caretaker: TGP is green. This is ready to merge.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 10bab47b4f67e38a4349b450efa6e63703096e7a.

**Pull request closed without merging**
