### PR TITLE
 docs(docs-infra): Inconsistency in bootstrapping application

### PR DESCRIPTION
**Pull request by MeAkib**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

Issue Number: 52048

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by santosant — APPROVED** [review]

**Comment by atscott** [comment]
@MarkTechson I feel like this entire guide should just be overhauled rather than updating a single sentence. What do you think?

**Comment by MarkTechson** [comment]
> @MarkTechson I feel like this entire guide should just be overhauled rather than updating a single sentence. What do you think? From what I can tell, this guide doesn't exist on angular.dev anyways.

Totally agree here. Is the next best step to open an an issue?

**Comment by atscott** [comment]
> Is the next best step to open an an issue?

I'm not totally sure on that one. Since I don't see this guide on angular.dev, I think there are two questions:

1. Is the "bootstrapping" process covered on angular.dev for standalone (with maybe a small note for how to do it with modules)?
2. What do we do with the outdated docs in angular.io?

**Comment by atscott** [comment]
Closing - our priority is angular.dev for docs content. Anything other than trivial sentence changes should be updated on angular.dev. This guide does not exist on angular.dev so this is effectively resolved already on the new docs site.

**Pull request closed without merging**
