### PR TITLE
feat(zone.js): initialize web extension extra bundle

### PR DESCRIPTION
**Pull request by spaceribs**
Adds in the extra/web-ext bundle and wraps:
- storage onchange notifications.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
zone.js does not listen to any web extension event emitters.

Issue Number: N/A

## What is the new behavior?
If extra/web-ext is loaded, the `(browser || chrome).storage.onChange` event will be properly wrapped as a macrotask

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Heres a list of the web extension events that should be patched:

- `alarm`
  - [ ] onAlarm
- `captivePortal`
  - [ ] onStateChanged
  - [ ] onConnectivityAvailable
- `contextualIdentities`
  - [ ] onUpdated
  - [ ] onCreated
  - [ ] onRemoved
- `cookies`
  - [ ] onChanged
- `downloads`
  - [ ] onCreated
  - [ ] onErased
  - [ ] onChanged
- `events`
  - [ ] onRequest
  - [ ] onRequestExternal
- `geckoProfiler`
  - [ ] onRunning
- `identity`
  - [ ] onSignInChanged
- `idle`
  - [ ] onStateChanged
- `management`
  - [ ] onDisabled
  - [ ] onEnabled
  - [ ] onInstalled
  - [ ] onUninstalled
- `networkStatus`
  - [ ] onConnectionChanged
- `notifications`
  - [ ] onClosed
  - [ ] onClicked
  - [ ] onButtonClicked
  - [ ] onPermissionLevelChanged
  - [ ] onShowSettings
  - [ ] onShown
- `permissions`
  - [ ] onAdded
  - [ ] onRemoved
- `proxy`
  - [ ] onRequest
  - [ ] onError
  - [ ] onProxyError
- `runtime`
  - [ ] onStartup
  - [ ] onInstalled
  - [ ] onSuspend
  - [ ] onSuspendCanceled
  - [ ] onUpdateAvailable
  - [ ] onBrowserUpdateAvailable
  - [ ] onConnect
  - [ ] onConnectExternal
  - [ ] onMessage
  - [ ] onMessageExternal
  - [ ] onRestartRequired
- `storage`
  - [ ] onChanged
- `theme`
  - [ ] onUpdated
- `userScripts`
  - [ ] onBeforeScript
- `webNavigation`
  - [ ] onBeforeNavigate
  - [ ] onCommitted
  - [ ] onDOMContentLoaded
  - [ ] onCompleted
  - [ ] onErrorOccurred
  - [ ] onCreatedNavigationTarget
  - [ ] onReferenceFragmentUpdated
  - [ ] onTabReplaced
  - [ ] onHistoryStateUpdated
- `webRequest`
  - [ ] onBeforeRequest
  - [ ] onBeforeSendHeaders
  - [ ] onSendHeaders
  - [ ] onHeadersReceived
  - [ ] onAuthRequired
  - [ ] onResponseStarted
  - [ ] onBeforeRedirect
  - [ ] onCompleted
  - [ ] onErrorOccurred
- `bookmarks`
  - [ ] onCreated
  - [ ] onRemoved
  - [ ] onChanged
  - [ ] onMoved
  - [ ] onChildrenReordered
- `browserAction`
  - [ ] onClicked
- `commands`
  - [ ] onCommand
- `devtools`
  - `inspectedWindow`
    - [ ] onResourceAdded
    - [ ] onResourceContentCommitted
  - `network`
    - [ ] onRequestFinished
    - [ ] onNavigated
  - `panels`
    - [ ] onThemeChanged
- `history`
  - [ ] onVisited
  - [ ] onVisitRemoved
  - [ ] onTitleChanged
- `contextMenus`
  - [ ] onClicked
  - [ ] onShown
  - [ ] onHidden
- `menus`
  - [ ] onClicked
  - [ ] onShown
  - [ ] onHidden
- `omnibox`
  - [ ] onInputStarted
  - [ ] onInputChanged
  - [ ] onInputEntered
  - [ ] onInputCancelled
- `pageAction`
  - [ ] onClicked
- `sessions`
  - [ ] onChanged
- `tabs`
  - [ ] onCreated
  - [ ] onUpdated
  - [ ] onMoved
  - [ ] onSelectionChanged
  - [ ] onActiveChanged
  - [ ] onActivated
  - [ ] onHighlightChanged
  - [ ] onHighlighted
  - [ ] onDetached
  - [ ] onAttached
  - [ ] onRemoved
  - [ ] onReplaced
  - [ ] onZoomChange
- `urlbar`
  - [ ] onBehaviorRequested
  - [ ] onQueryCanceled
  - [ ] onResultsRequested
  - `contextualTip`
    - [ ] onButtonClicked
    - [ ] onLinkClicked
- `windows`
  - [ ] onCreated
  - [ ] onRemoved
  - [ ] onFocusChanged

### CODE REVIEW

**Comment by spaceribs** [comment]
@JiaLiPassion whenever you get a chance, please review the basic structure and I'll continue to add more events from there

**Comment by JiaLiPassion** [comment]
@spaceribs, sure, thanks for the PR, could you post some more docs about the `webext` APIs usages, I am not familiar with `webext`, so if you can add more docs or some links here, I would like to check it.

**Comment by spaceribs** [comment]
Sure, here are the resources I know about:
1. The originating Blink spec: https://developer.chrome.com/extensions/devguide
2. The Mozilla planning documentation: https://wiki.mozilla.org/WebExtensions
3. The MDN WebExtension API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API
4. The web-ext devtool, which allows packaging/signing/debugging: https://github.com/mozilla/web-ext
5. The webextension-polyfill, allowing Firefox and Chrome to use the same global (essentially an alias for the `chrome` global, allowing extensions to be platform agnostic): https://github.com/mozilla/webextension-polyfill
6. The type definitions for `@types/firefox-webext-browser`, probably the most useful way to track which events should be wrapped: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/firefox-webext-browser/index.d.ts

**Comment by spaceribs** [comment]
As an important aside, there are 101 instances of `WebExtEvent` in the type definition above, from my testing it appears that there is no underlying prototype for these events to patch. We'll need to detect and patch each one separately.

**Comment by spaceribs** [comment]
@JiaLiPassion spent some time last night in the example repo trying to make sure everything was working correctly in a basic angular app. Unfortunately it seems like every event storage.OnChanged emits from `addListener` is emitted at `<root>` rather than under `angular` where I called it:

```typescript
  ngOnInit(): void {
    browser.storage.onChanged.addListener((changes) => {
      this.number += 1;
      console.log((window as any).Zone.current);
      console.log(NgZone.isInAngularZone());
    });

    setTimeout(() => {
      console.log((window as any).Zone.current);
      browser.storage.local.set({ test: this.number.toString() });
    }, 1000);
  }
```

Outputs the following in console:

```
Object { _parent: {…}, _name: "angular", _properties: {…}, _zoneDelegate: {…} }
app.component.ts:22:14
Object { _parent: null, _name: "<root>", _properties: {}, _zoneDelegate: {…} }
app.component.ts:17:14
false app.component.ts:18:14
```

And of course, change detection fails. Am I missing something in:
https://github.com/angular/angular/pull/36599/files#diff-7c5c8e763d04c09a6de685e90ffb0818R20

**Comment by spaceribs** [comment]
@JiaLiPassion bumping you on this, I created an inventory of the events I plan to cover, and also opened an issue to investigate and possibly update the `webextension-polyfill` with an underlying prototype for all these events being wrapped.

**Comment by JiaLiPassion** [comment]
@spaceribs, thanks, I will take a look next week!

**Comment by spaceribs** [comment]
@JiaLiPassion any word on this?

**Comment by jessicajaniuk** [comment]
This can be implemented as a polyfill patch for zones. We'll close this, but feel free to open a feature request, and if it gets enough upvotes, we can upstream the change.

**Pull request closed without merging**
