### PR TITLE
refactor(zone.js): remove onProp eventNames array to reduce the bundle size

### PR DESCRIPTION
**Pull request by JiaLiPassion**
This is the same PR with https://github.com/angular/angular/pull/40962 for the `13.2.x` patch branch.

Zone.js supports the google closure compiler in the advance optimization mode,
to prevent closure compiler modify the `onProperty` name such as `Element.prototype.onclick`,
Zone.js implements the `onProperty` patch logic by declaring all the
event names in the source code, this increases the bundle size and also require
updating the event names array to keep the information updated.

Now google closure compiler has the required event names defined in the built-in
externs files, so zone.js can use more simple implementation and decrease the bundle size
of zone.js (about 4k).

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
FYI, adding "PullApprove: disable" since it's a patch-only version of already approved PR (https://github.com/angular/angular/pull/40962).

**Comment by atscott** [comment]
@JiaLiPassion Can you retarget this for the `13.3.x` branch?

**Comment by JiaLiPassion** [comment]
@atscott , sure, I just rebased this PR to 13.3.x

**Comment by JiaLiPassion** [comment]
@dylhunn , the `Android` test at saucelab is failing, I am not sure why, still need some time to figure it out.

**Comment by dylhunn** [comment]
No worries, thanks!

**Pull request closed without merging**
