### PR TITLE
Update hero.service.ts

### PR DESCRIPTION
**Pull request by LuisEscamillaMartin**
Forgotten semicolon.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ericmartinezr** [comment]
I wouldn't say this is correct even though it is. In this [snippet](https://angular.io/tutorial/toh-pt6#get-heroes-with-httpclient) (note that is not necessary, see this [answer](https://stackoverflow.com/a/4002248/4933038)). 

Also that snippet is extended later on [here](https://angular.io/tutorial/toh-pt6#error-handling) and [here](https://angular.io/tutorial/toh-pt6#tap-into-the-observable) where those sentences are terminated with a semicolon.

**Comment by Airblader** [comment]
This change is incorrect and will cause a syntax error. There's a comment in between, but look at the second line after the return line.

**Comment by petebacondarwin** [comment]
I agree. We cannot break the actual code in the examples in order to make the code snippet look right in the docs. We must find another way...

**Comment by gkalpak** [comment]
IMO, we should leave it as is. Missing an (optional) semicolon in an intermediate code snippet is better than maintaining two copies of the same file (having to keep them in-sync, not being able to test both, etc.).

**Comment by petebacondarwin** [comment]
How about a compromise using a commented out block right next to the working code?

```ts
  // #docregion getHeroes
  /** GET heroes from the server */
  // #docregion getHeroes-2
  getHeroes(): Observable<Hero[]> {
    return this.http.get<Hero[]>(this.heroesUrl)
      .pipe(
        // #enddocregion getHeroes-2
        tap(_ => this.log('fetched heroes')),
        // #docregion getHeroes-2
        catchError(this.handleError<Hero[]>('getHeroes', []))
      );
  }
  // #enddocregion getHeroes, getHeroes-2
  // #enddocregion
  /*
    THIS COMMENT BLOCK IS TO HOLD THE getHeroes-1 docregion
  // #docregion getHeroes-1
    getHeroes(): Observable<Hero[]> {
      return this.http.get<Hero[]>(this.heroesUrl);
    }
  // #enddocregion getHeroes-1
    END OF COMMENT BLOCK
  */
  // #docregion
```

**Comment by gkalpak** [comment]
Not worth it imo, but not a hill I'll die on :wink:

**Comment by petebacondarwin** [comment]
Nor me 😁 
Perhaps we can let the docs-team (e.g. @kapunahelewong) take view.

**Comment by kapunahelewong** [comment]
Thank you for this, @LuisEscamillaMartin. Though it did appear to be a simple fix, as others point out, that snippet is pulled from the larger file and has to compile, so we can't put the semicolon there. While you could create a separate file or add a comment block as @petebacondarwin describes, yet another option is to edit the header of that snippet to say:

```
src/app/hero.service.ts (excerpt)
```

That would be in [the md file](https://github.com/angular/angular/blob/master/aio/content/tutorial/toh-pt6.md) and you'd change the `header` like this:

```
<code-example path="toh-pt6/src/app/hero.service.ts" header="src/app/hero.service.ts (excerpt)" region="getHeroes-1">
</code-example>
```

So, you could leave it as is, or try one of the options we've shared here. What are your thoughts?

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Closing as the PR is stale, no consensus was found on how to resolve the problem, and the OP did not sign the CLA.

**Pull request closed without merging**
