### PR TITLE
docs: add missing h1 to page for skip to main content on home page

### LINKED ISSUE #53015: Skip to Main Content Does not work creating severe accessibility issues
### Describe the problem that you experienced

Clicking the Skip to Main Content Button does not skip to main content. 

### Enter the URL of the topic with the problem

http://angular.dev

### Describe what you were looking for in the documentation

The skip to main content button should skip to the first non-repeated element. 

### Describe the actions that led you to experience the problem

Clicking the skip to content button. 

### Describe what you want to experience that would fix the problem

The skip to main content button should skip to the first non-repeated element. 

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by bencodezen**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #53015

## What is the new behavior?

Currently the skip-to-content button does not have an h1 element to jump to, so this PR should add a proper anchor for the skip to main content element.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Clicking on the "skip to main button" still doesn't do anything for me with this change.

**Comment by bencodezen** [comment]
@JeanMeche Forgot to push another change. Let me know if it's still not working on your end!

**Review by JeanMeche — APPROVED** [review]
LGTM

**Comment by atscott** [comment]
This PR was merged into the repository by commit d63706e9d680952ee1547ab6030ee82b903b3069.

**Pull request closed without merging**
