### PR TITLE
refactor(core): drop unused fields from the `RootContext`

### PR DESCRIPTION
**Pull request by AndrewKushnir**
The `RootContext` implementation contained a number of fields that were needed to support an experimental `renderComponent` function. The `renderComponent` function was removed, which allows us to cleanup the `RootContext` further.

The only field that remains on the `RootContext` is the list of bootstrapped components. This list is presumably mostly unused right now (it just contains the current component) and further refactoring can happen in a followup PR.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM for dev-infra

**Comment by AndrewKushnir** [comment]
@markostanimirovic thanks for the comment 👍

I think it should be possible to do the `RootContext` cleanup (which is the main goal of this PR) without dropping the `markDirty` function. I'll take a look at the code of the mentioned libraries and update the PR.

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM, this is great cleanup @AndrewKushnir

**Comment by pkozlowski-opensource** [comment]
@markostanimirovic thnx for the additional info. My understanding of the  [comment](https://github.com/angular/angular/pull/46709#issuecomment-1174873046) you've mentioned was that it was about `ng.*` public API. 

The `markDirty` API was always _very_ experimental and _very_ private so I'm surprised to see it being used. We really do _not_ believe that this API makes a good zone-less experience and we do plan to remove it (while working on the proper story for zone replacement).

We can delay this refactor a bit to give libraries time to migrate but I would suggest making changes sooner than later as the intention is to move forward with the `markDirty` removal.

**Comment by markostanimirovic** [comment]
Thank you, @pkozlowski-opensource.

> We really do not believe that this API makes a good zone-less experience

I'll appreciate it if you can share more info on this. Do you think it would be better to use a "local" rendering strategy in zone-less mode (`cdRef.detectChanges` + custom scheduling/coalescing mechanism)? The `markDirty` function is chosen over `cdRef.detectChanges` in the case of `@ngrx/component` because `cdRef.detectChanges` doesn't coalesce calls, so it can lead to bad performance when called multiple times synchronously. Another reason is to keep the rendering strategy consistent in both zone-full and zone-less modes.

> We can delay this refactor a bit to give libraries time to migrate but I would suggest making changes sooner than later as the intention is to move forward with the markDirty removal.

It would be great if you can share when you plan to merge this PR. :)

**Comment by AndrewKushnir** [comment]
@markostanimirovic as a possible replacement option, you can look into using cdRef.markForCheck + custom CD scheduling (potentially using the `requestAnimationFrame`, which was used under the hood in the `markDirty` function).

> It would be great if you can share when you plan to merge this PR. :)

I've looked at the code and I think we can do the following:
- Remove the scheduling logic (the `scheduleTick` function) from experimental `markDirty` function. The scheduling is a big contributing factor to the `RootContext` object. If we don't have it, we'd be able to proceed with further cleanup and drop the `RootContext` completely.
- Release this change (which would also drop scheduling from the `markDirty` function) in one of the upcoming patch releases (14.0.x or 14.1.x).
- Retain the `markDirty` (without scheduling) until the next major release. This should give some additional time to transition away from using the `markDirty` function. The tricky part here is that the lack of scheduling in a zone-less setup may result in stale UI state until the next CD cycle.
- Remove the `markDirty` function in v15.

@markostanimirovic would that work for the library that you maintain?

**Comment by markostanimirovic** [comment]
Thank you for your efforts to find a compromise solution @AndrewKushnir. Appreciate that!

I think it would be better to remove the `markDirty` function then. Because, without CD scheduling, it will break zone-less apps that use it without any errors/warnings.

**Comment by AndrewKushnir** [comment]
@markostanimirovic thanks for the reply. Please let us know once https://github.com/ngrx/platform/pull/3488 lands and the change is released, so that we can proceed with this cleanup.

**Comment by AndrewKushnir** [comment]
@markostanimirovic just wanted to check if you plan to land https://github.com/ngrx/platform/pull/3488, so that we can proceed with this cleanup without breaking the library. Thank you.

**Comment by markostanimirovic** [comment]
https://github.com/ngrx/platform/pull/3488 is merged. Thanks for waiting, @AndrewKushnir! :) You can proceed with this cleanup.

**Comment by AndrewKushnir** [comment]
@markostanimirovic thanks for the update. We'll be moving forward with this change and land it in v14.2.0.

**Comment by AndrewKushnir** [comment]
[Presubmit](https://test.corp.google.com/OCL:465460868:BASE:465460906:1659666353336:e6044d99).

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: size-tracking

**Comment by atscott** [comment]
This PR was merged into the repository by commit c1ad37d1618141255852d8b52d618af198b90d17.

**Pull request closed without merging**
