### PR TITLE
feat(forms): add AbstractControl.addValidators method

### LINKED ISSUE #10567: FormControl.setValidators...would like an addValidators
**I'm submitting a ...**  (check one with "x")

```
[x ] feature request

**Current behavior**
When creating a FormControl via TypeScript (following a model driven approach) we have our validations coming from a 'Questions' model (using the Angular2 dynamic form cookbook as an example). We use the setValidators method however we have 7 or 8 validators we apply but not for each question. 

As an example:

   new TextboxQuestion({
        key: 'phone',
        label: 'Phone',
        value: '',
        required: true,
        minLength: 9,
        maxLength: 12,
        order: 1
      }),

   new TextboxQuestion({
        key: 'email',
        label: 'Email',
        value: '',
        required: true,
        minLength: 0,
        maxLength: 0,
        order: 1
      }),

Using setValidators though...we would have to start to write a pretty complicated if statement to look for when we want to apply certain validators since setValidators does not add, just replaces. The below code will only set the last validator.

toFormGroup(questions: QuestionBase<any>[]) {
    let group: any = {};

    questions.forEach(question => {
      group[question.key] = new FormControl(question.value);

      if (question.required)
        (<FormControl>group[question.key]).setValidators([
          Validators.required
        ]);
      if (question.minLength > 0)
        (<FormControl>group[question.key]).setValidators([
          Validators.minLength(question.minLength)
        ]);
      if (question.maxLength > 0)
        (<FormControl>group[question.key]).setValidators([
          Validators.maxLength(question.maxLength)
        ]);
    });

**What is the motivation / use case for changing the behavior?**

It would be great if you had an ADD like 

toFormGroup(questions: QuestionBase<any>[]) {
    let group: any = {};

    questions.forEach(question => {
      group[question.key] = new FormControl(question.value);

      if (question.required)
        (<FormControl>group[question.key]).**addValidators**([
          Validators.required
        ]);
      if (question.minLength > 0)
        (<FormControl>group[question.key]).**addValidators**([
          Validators.minLength(question.minLength)
        ]);
      if (question.maxLength > 0)
        (<FormControl>group[question.key]).**addValidators**([
          Validators.maxLength(question.maxLength)
        ]);
    });


* **Angular version:** 2.0.0-rc.4

* **Browser:** [all ]

* **Language:** [all] 
```

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Fixes https://github.com/angular/angular/issues/10567

### CODE REVIEW

**Comment by igalil** [comment]
Hi there,
do you know if this will be integrated soon?
My team and I we really need this functionality.
Thanks a lot :)

**Comment by DzmitryShylovich** [comment]
@kara ping

**Comment by rafaelss95** [comment]
Will this be merged?

**Comment by dev054** [comment]
@DzmitryShylovich extending to this, It would be great if we could have the `removeValidator` method also.

**Comment by splincode** [comment]
What is the status of the task?

**Comment by kara** [comment]
Closing this as stale. If anyone wants to pick it up to refresh it, please feel free to open a new PR.

**Pull request closed without merging**
