### PR TITLE
fix(ng upgrade): do not compile ng2 components until after ng1 bootstrap

### LINKED ISSUE #9407: Protractor errors when bootstrapping the @angular/upgrade demo app
With the latest protractor and selenium-webdriver I get:

```
 Failed: Cannot assign to read only property 'stack' of Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"

```

### PR DESCRIPTION
**Pull request by sjelin**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

See #9407

**What is the new behavior?**

No bug

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Closes #9407 and angular/protractor#2944

### CODE REVIEW

**Comment by sjelin** [comment]
I would like someone who actually understand the bootstrap process in some detail to review this.  I feel like my fix is kinda dumb.  But maybe that's just because it's short.

**Comment by juliemr** [comment]
Isn't this what I tried in https://github.com/angular/angular/pull/9424? Can you turn on the test in modules/playground/e2e_test/upgrade/upgrade_spec.ts?

**Comment by youdz** [comment]
For what it's worth, there is a non-negligible refactor of the UpgradeAdapter sitting in #9538. It got an LGTM, but since it's tagged for Final it hasn't been merged yet.

It includes the same change you both tried, but I haven't been able to get the e2e test @juliemr mentions to pass. 

I'm just mentioning this because some other parts of the refactor might help, so maybe you want to look at it or work on top of it. I know I'll be trying to add additional fixes on top of it when I have the time.

**Comment by sjelin** [comment]
Hi, sorry for the slow update, but I've been doing a lot of digging:

1) This PR addresses a real bug and should be merged in.  @youdz, it sounds like your refactor also addresses this bug, so if you'd rather stick with that that works too.
2) The is a second bug Protractor side where Protractor gets confused and thinks hybrid apps are ng2 apps.  Basically, between now and rc2, a change has been made which causes Protractor to think hybrid apps are ng2 apps, which is why the test still fails.  BUT....
3) There also appears to be a third bug.  Still digging into this one.

Regardless, this PR (or youdz's) should be merged in, I'll add a feature for users to manually state in Protractor tests that they're accessing a hybrid app (after talking about this with @juliemr, we decided this was the best idea), and I will continue digging to uncover this (not totally confirmed) third bug.

**Comment by sjelin** [comment]
Ok, the third bug just turned out to be a bug in the test.  I've fixed the test now.  It's still commented out though because we're waiting for the protractor change (https://github.com/angular/protractor/pull/3403).  Anyway, this PR should be merged in.

**Pull request merged**
