### PR TITLE
chore(testing): update karma-jasmine and jasmine

### PR DESCRIPTION
**Pull request by juliemr**
Jasmine to jasmine-core 2.3.4.
Update tools tests using minijasminenode to directly use jasmine.

See #1860

### CODE REVIEW

**Comment by juliemr** [comment]
Note - I have not yet updated npm-shrinkwrap, since that may need to be re-done after other changes like https://github.com/angular/angular/pull/2044

Will update before committing.

**Comment by juliemr** [comment]
@vicb can you take a look at this one?

**Comment by IgorMinar** [comment]
lgtm, go ahead and merge

**Comment by juliemr** [comment]
Thanks, merged as 863eb3c559e8c175885ceb0e2d5b4e5c535bf467

**Comment by mlaval** [comment]
It seems that we even need a not yet released version of `karma-jasmine`, I just encountered the issue solved by https://github.com/karma-runner/karma-jasmine/commit/8a0d901ce85e96a451b3c41fa6f7a62505b7df8f when running Angular2 tests in Firefox

**Pull request closed without merging**
