### PR TITLE
Ts0.16.1

### PR DESCRIPTION
**Pull request by alexeagle**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by gregmagolan — CHANGES_REQUESTED** [review]
Golden files need updating & I think its conflicting with my rules_typescript 0.16.0 commits

**Comment by gregmagolan** [comment]
Failure on `test_ivy_aot` due to a recent commit. Only showed up when I rebased to angular head.

```
==================== Test output for //packages/compiler-cli/test/compliance:compliance:
Randomized with seed 26188
Started
F........*.................................*.......................

Failures:
1) compiler compliance: template should support local refs on <ng-template>
  Message:
    Failed: Incorrect template: Failed to find "null" after "        i0.ɵtemplate(0, Template_0, 1," in:
    'import { Component, NgModule } from '@angular/core';
    import * as i0 from "@angular/core";
    const _c0 = ["foo", ""];
    function Template_0(rf, ctx) { if (rf & 1) {
        i0.ɵtext(0, "some-content");
    } }
    export class MyComponent {
    }
    MyComponent.ngComponentDef = i0.ɵdefineComponent({ type: MyComponent, selectors: [["my-component"]], factory: function MyComponent_Factory(t) { return new (t || MyComponent)(); }, features: [i0.ɵPublicFeature], consts: 2, vars: 0, template: function MyComponent_Template(rf, ctx) { if (rf & 1) {
            i0.ɵtemplate(0, Template_0, 1,[<---HERE expected "null"] 0, null, null, _c0, i0.ɵtemplateRefExtractor);
        } } });
    export class MyModule {
    }
    MyModule.ngModuleDef = i0.ɵdefineNgModule({ type: MyModule, bootstrap: [], declarations: [MyComponent], imports: [], exports: [] });
    MyModule.ngInjectorDef = i0.defineInjector({ factory: function MyModule_Factory(t) { return new (t || MyModule)(); }, providers: [], imports: [] });
    '
  Stack:
    Error: Failed: Incorrect template: Failed to find "null" after "        i0.ɵtemplate(0, Template_0, 1," in:
        at <Jasmine>
        at Object.expectEmit (/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/sandbox/processwrapper-sandbox/211/execroot/angular/bazel-out/k8-fastbuild/bin/packages/compiler-cli/test/packages/compiler-cli/test/compliance/mock_compile.ts:83:9)
        at UserContext.<anonymous> (/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/sandbox/processwrapper-sandbox/211/execroot/angular/bazel-out/k8-fastbuild/bin/packages/compiler-cli/test/packages/compiler-cli/test/compliance/r3_view_compiler_template_spec.ts:401:5)
        at <Jasmine>
        at runCallback (timers.js:789:20)
        at tryOnImmediate (timers.js:751:5)
        at processImmediate [as _immediateCallback] (timers.js:722:5)
Pending:

1) compiler compliance elements should support namspaced attributes
  Temporarily disabled with xit


2) i18n support in the view compiler nested nodes should generate the placeholders maps
  No reason given

67 specs, 1 failure, 2 pending specs
Finished in 61.857 seconds
Randomized with seed 26188 (jasmine --random=true --seed=26188)
================================================================================
```

**Comment by gregmagolan** [comment]
Latest angular commit looks like it fixes the `test_ivy_aot` failure. Rebased again.

**Comment by gregmagolan** [comment]
PR also updates the bazel integration to build angular from source with bazel instead of using the angular bundles. This is now the recommended way for user's to build angular downstream in angular-bazel-example. Was done in this PR as building angular with bundles after updating to rules_typescript 0.16.0 broke the hello-world unit test in the integration test. Failure looked like this for future reference:

```
21 08 2018 07:09:18.313:INFO [HeadlessChrome 69.0.3488 (Mac OS X 10.13.6)]: Connected on socket qeJnZGicqB4_4PieAAAA with id 51133129
HeadlessChrome 69.0.3488 (Mac OS X 10.13.6) BannerComponent (inline template) should display original title FAILED
	Failed: Can't resolve all parameters for ApplicationModule: (?).
	Error: Can't resolve all parameters for ApplicationModule: (?).
	    at syntaxError (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:1093:21)
	    at CompileMetadataResolver._getDependenciesMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:11000:39)
	    at CompileMetadataResolver._getTypeMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10893:30)
	    at CompileMetadataResolver.getNgModuleMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10761:28)
	    at CompileMetadataResolver.getNgModuleSummary (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10571:39)
	    at eval (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10685:55)
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10673:53)
	    at CompileMetadataResolver.getNgModuleSummary (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10571:39)
	    at eval (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10685:55)
	Error: Can't resolve all parameters for ApplicationModule: (?).
	    at syntaxError (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:1093:21)
	    at CompileMetadataResolver._getDependenciesMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:11000:39)
	    at CompileMetadataResolver._getTypeMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10893:30)
	    at CompileMetadataResolver.getNgModuleMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10761:28)
	    at CompileMetadataResolver.getNgModuleSummary (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10571:39)
	    at eval (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10685:55)
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10673:53)
	    at CompileMetadataResolver.getNgModuleSummary (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10571:39)
	    at eval (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10685:55)
	TypeError: Cannot read property 'detectChanges' of undefined
	    at UserContext.eval (http://concatjs../../src/hello-world/hello-world.component.spec.ts:36:12 <- bazel_integration_test/src/hello-world/hello-world.component.spec.js:41:21)
	    at ZoneDelegate.invoke (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:388:26)
	    at ProxyZoneSpec.onInvoke (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:3334:39)
	    at ZoneDelegate.invoke (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:387:32)
	    at Zone.run (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:138:43)
	    at runInTestZone (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:3555:34)
	    at UserContext.eval (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:3570:20)
HeadlessChrome 69.0.3488 (Mac OS X 10.13.6) BannerComponent (inline template) should display a different test title FAILED
	Failed: Can't resolve all parameters for ApplicationModule: (?).
	Error: Can't resolve all parameters for ApplicationModule: (?).
	    at syntaxError (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:1093:21)
	    at CompileMetadataResolver._getDependenciesMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:11000:39)
	    at CompileMetadataResolver._getTypeMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10893:30)
	    at CompileMetadataResolver.getNgModuleMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10761:28)
	    at CompileMetadataResolver.getNgModuleSummary (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10571:39)
	    at eval (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10685:55)
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10673:53)
	    at CompileMetadataResolver.getNgModuleSummary (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10571:39)
	    at eval (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10685:55)
	Error: Can't resolve all parameters for ApplicationModule: (?).
	    at syntaxError (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:1093:21)
	    at CompileMetadataResolver._getDependenciesMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:11000:39)
	    at CompileMetadataResolver._getTypeMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10893:30)
	    at CompileMetadataResolver.getNgModuleMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10761:28)
	    at CompileMetadataResolver.getNgModuleSummary (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10571:39)
	    at eval (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10685:55)
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10673:53)
	    at CompileMetadataResolver.getNgModuleSummary (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10571:39)
	    at eval (http://concatjsbazel_integration_test/node_modules/@angular/compiler/bundles/compiler.umd.js:10685:55)
	TypeError: Cannot set property 'name' of undefined
	    at UserContext.eval (http://concatjs../../src/hello-world/hello-world.component.spec.ts:41:13 <- bazel_integration_test/src/hello-world/hello-world.component.spec.js:45:23)
	    at ZoneDelegate.invoke (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:388:26)
	    at ProxyZoneSpec.onInvoke (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:3334:39)
	    at ZoneDelegate.invoke (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:387:32)
	    at Zone.run (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:138:43)
	    at runInTestZone (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:3555:34)
	    at UserContext.eval (http://concatjsbazel_integration_test/node_modules/zone.js/dist/zone-testing-bundle.js:3570:20)
HeadlessChrome 69.0.3488 (Mac OS X 10.13.6): Executed 2 of 2 (2 FAILED) ERROR (0.059 secs / 0.048 secs)
```

**Review by gregmagolan — APPROVED** [review]

**Review by jasonaden — APPROVED** [review]

**Comment by matsko** [comment]
@alexeagle this fails in `patch`. Please fix.

**Pull request closed without merging**
