### PR TITLE
refactor(http): deprecated symbol used

### PR DESCRIPTION
**Pull request by SrdjanMilic**
Screenshot from 2022-01-02 20-37-23

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@SrdjanMilic Thanks for the PR. Looks like there's some issues with the tests and the commit message. Can you take a look at those?

**Comment by SrdjanMilic** [comment]
Hello Jessica,

No problem. I'll check all of those.

**Comment by alxhub** [comment]
The issue with the test seems to be that it uses the `json` pipe to serialize the error into a template (and then asserts against the resulting text in the test). This worked when the error was a `string`, but now it's an `Error` object, and `JSON.stringify(new Error('...'))` is the string `'{}'`. See: https://github.com/angular/angular/blob/master/aio/content/examples/http/src/app/config/config.component.ts

**Comment by SrdjanMilic** [comment]
OK. I've messed up something with the git. I suppose this branch is useless after all for you to merge it...
I've just created another pull request https://github.com/angular/angular/pull/44700
Hopefully, it will pass all the tests. Please sorry for the mess I have cause. 🙏

**Pull request closed without merging**
