### PR TITLE
build(compiler-cli): fix bazel deps rules for ngtsc testing packages

### PR DESCRIPTION
**Pull request by ocombe**
## PR Type
What kind of change does this PR introduce?

- [x] Build related changes

## What is the current behavior?

2 testing packages are missing from the bazel deps rules, which means that they are not included in the releases

## What is the new behavior?
They should be released with the next version of compiler-cli

## Does this PR introduce a breaking change?

- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]

**Review by devversion — APPROVED** [review]
LGTM for dev-infra. Should the commit message capture the motivation for having these testing packages published? My understanding is that those primarily exist for our internal usage and the compiler is not public API. Though apparently there are use cases, so for later reference, it would be good to capture the motivation.

**Comment by ocombe** [comment]
@devversion those packages are used by `@angular/localize` in private APIs that are actually not so private since they are used by `@angular/cli` (and by my library Locl, but I'll take responsibility if it breaks 😀).
Exporting those would help writing better tests (without needing to copy all of the code), according to @petebacondarwin they were meant to be available

**Comment by devversion** [comment]
@ocombe Thanks for providing context. Makes sense! Good that this is now captured in the PR :smile:

**Review by devversion — APPROVED** [review]

**Comment by devversion** [comment]
@petebacondarwin I've changed label to also `patch` branch. Any reason why you marked it as `master only`?

**Comment by petebacondarwin** [comment]
The stuff that @ocombe wants to use is only on `master`. Also the `logging` package was only moved over in `master` too.

**Review by alxhub — APPROVED** [review]

**Pull request closed without merging**
