### PR TITLE
[WIP] fix(common): do not re-initialize template when ngOutletContext changes

### LINKED ISSUE #13407: ngOutletContext causes template to re-initialize on data changes
https://plnkr.co/edit/mUXkCli6CUEyNlbn2PZV?p=preview

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Minimal reproduction of the problem with instructions**

```
     <template #chartsManagerTemplate let-data="data">
         <charts-manager data="data"></charts-manager>
    </template>
    
     <template [ngOutletContext]="{ data: chartsData }"
            [ngTemplateOutlet]="chartsManagerTemplate">
     </template>

```

In the component:

```
     this.loadChartsData().subscribe(data => {

          //this causes the template to re-instantiate, I believe it should not.
          this.chartsData = data; 
     });
```

**Current behavior**

When data passed into [ngOutletContext] changes, the template and its nested components are re-instantiated.

**Expected behavior**

The expected behavior is for the template to not be re-instantiated, similar to if a template was not used. For example, this:

```
     <template [ngOutletContext]="{ data: chartsData }"
            [ngTemplateOutlet]="chartsManagerTemplate">
     </template>
```

should behave the same as:

```
<charts-manager data="chartsData"></charts-manager>
```

and NOT re-instantiate

**What is the motivation / use case for changing the behavior?**
Nested component should have the ability to control when they redraw, rather than it being forced simply by the use of <template>. In my case, I would like to redraw charts with a transition.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Closes https://github.com/angular/angular/issues/13407

### CODE REVIEW

**Comment by mhevery** [comment]
Can you rebase on top of #13477

**Comment by petebacondarwin** [comment]
@mhevery I don't think you meant #13477 - perhaps another similar PR?

**Comment by mhevery** [comment]
Sorry, (and thanks @petebacondarwin for pointing it out) The correct PR is #13557

**Comment by pkozlowski-opensource** [comment]
@mhevery I've discussed this PR with @DzmitryShylovich and the proposed impl is _not_ good - it would potentially leave old keys in the context. Will add more details tomorrow but we should **NOT** merge it in this state.

**Comment by ghetolay** [comment]
@pkozlowski-opensource Then how do you think we should do it ?

I can see 2 options :

1. Add a setter to `ViewContainerRef.context` but don't really know what this may affect.
3. Use a Differ but seems heavy to use it here when what we really want is to override the context completely.

**Pull request closed without merging**
