### PR TITLE
refactor(platform-browser): specify return type of parseEventName

### PR DESCRIPTION
**Pull request by origin-master**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
`parseEventName`'s ReturnType is `{[key: string]: string} | null`

## What is the new behavior?
make it to `{fullKey: string, domEventName: string} | null`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
I, as Dean Lim (@origin-master), give up any copyright interest in this contribution/commit/PR and make it as public domain, instead of signing Google CLA. Here's a copyright wavier:

> Dean Lim Copyright Wavier
> 
> I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Although this does require a public API change, it seems like a reasonable improvement to me.
It allows the TS compiler to more accurately type check the usage of the return value of this function.
This is not a breaking change to the API, since the TS compiler is clever enough to consider `result['domEventName']` as being a valid way to access `result.domEventName`. See https://www.typescriptlang.org/play/#code/MYewdgzgLgBAbgQwDYFcCmMC8MDeMEBcMAjAAykA0MARkQEzkwC+A3AFCiSwJbzLoBtAOQIhAXXZA

You will need to sign the CLA before this change can land.
The file needs reformatting; and I expect that the public API golden files will need updating.
The other test failure was probably a flake - re-running.

Due to the public API change it would need to land in v11, I believe.

**Review by pkozlowski-opensource — APPROVED** [review]
The change LGTM but it requires cleanup and CLA as @petebacondarwin pointed out.
Approving and adding cleanup flag.

**Comment by sonukapoor** [comment]
@origin-master Are you able to make the requested changes? Happy to take the PR over if needed.

**Comment by sonukapoor** [comment]
Closing in favour of #38089

**Pull request closed without merging**
