### PR TITLE
docs: update the sentence to express its meaning

### PR DESCRIPTION
**Pull request by beloveddie**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The sentence's meaning isn't clear enough and makes the comprehension of the reader not so adequate.

Issue Number: N/A

## What is the new behavior?
The sentence's meaning is clearer and less verbose, hence making the reader's comprehension quicker and more adequate.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jessicajaniuk** [comment]
@Eddiebee Thanks for the contribution. You'll need to update your commit message to match lint requirements.

**Comment by AndrewKushnir** [comment]
@Eddiebee it looks like you've updated a PR description, could you please update the commit message as well (for example, but running `git commit --amend`)? Please add the `docs: ` at the very beginning of the commit message (and drop the "\Commit Type: docs" part), that will resolve the `lint` CI job failures. Thank you.

**Review by AndrewKushnir — APPROVED** [review]
@Eddiebee thanks for updating a commit message 👍 The change looks good and I'm adding this PR to the merge queue. Thank for improving Angular docs!

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit b37ba058040bfb43ae60174331e82c5f6bfc9783.

**Pull request closed without merging**
