### PR TITLE
docs: remove redundant whitespaces and fix minor typos

### PR DESCRIPTION
**Pull request by thanhpd**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

- Redundant whitespace and new line characters in various files within angular aio docs
- Some minor typos

Issue Number: N/A

## What is the new behavior?

- Redundant whitespace characters are removed
- Some typos are corrected

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information
This PR is created to target patch branch following the comment https://github.com/angular/angular/pull/33422#issuecomment-547571151

### CODE REVIEW

**Comment by thanhpd** [comment]
Hi @AndrewKushnir, I've created a new PR including the changes targeting `8.2.x` branch. Please have a look.

**Review by kapunahelewong — APPROVED** [review]
LGTM, this is great! Thank you, @thanhpd!

**Comment by kapunahelewong** [comment]
merge assistance: global approval for docs changes

**Comment by AndrewKushnir** [comment]
Thanks for creating a patch version of this PR @thanhpd.

@kapunahelewong I've merged this PR into patch branch, since the original one had conflicts with patch branch, see https://github.com/angular/angular/pull/33422#issuecomment-547571151. So now master and patch branches have the same set of changes.

Thank you.

**Pull request closed without merging**
