### PR TITLE
Restore animation child leave commits

### PR DESCRIPTION
**Pull request by matsko**

### CODE REVIEW

**Comment by IgorMinar** [comment]
@tbosch @matsko this PR is missing approval. Can you please ensure that all future PRs have an approval? thanks

**Comment by IgorMinar** [comment]
I'm assuming that either one of you reviewed this since you applied the labels.

**Comment by tbosch** [comment]
@IgorMinar These are just roll forwards of https://github.com/angular/angular/commit/ac50bd678ee37c4b222baccc8412cc153a1d5a20 and https://github.com/angular/angular/commit/9130505b57c10dc6f4cd9b12ca47e06c4f429b74.

But yes, I should have added the approval.

**Review by tbosch — COMMENTED** [review]
These are just roll forwards of ac50bd6 and 9130505.

**Comment by IgorMinar** [comment]
ok. thanks!

**Pull request closed without merging**
