### PR TITLE
docs(aio): Added resources link to ng2-semantic-ui

### PR DESCRIPTION
**Pull request by edcarroll**
Added a link to `ng2-semantic-ui` in the resources page. Also updated `ngSemantic` link to be more specific.

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

[https://angular.io/resources](https://angular.io/resources)

## What is the new behavior?

New resources link.
## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by edcarroll** [comment]
CLA signed.

**Comment by wardbell** [comment]
This PR requires marketing approval

**Comment by petebacondarwin** [comment]
@juleskremer - can you (dis)approve this one please?

**Comment by StephenFluin** [comment]
@edcarroll I've started with a [PR](https://github.com/StephenFluin/angular/tree/stephenfluin/semantic-ui) that goes even further than this one to try to keep things current and clear. Is there any way to rename "ng2" to "ngx" or something so that it is clear this will work with 4, 5, 6 and so on?

**Comment by edcarroll** [comment]
@StephenFluin I've considered renaming my project `ngx-semantic-ui` but to do this need to go through the npm appeals so may take some time - I'd be happy to come back with a new PR once the rename has gone through?

**Comment by StephenFluin** [comment]
@edcarroll that sounds great! Feel free to ping me on the next one.

**Comment by edcarroll** [comment]
To clarify, I was meaning merge with these changes (/ your ones) for now, then I make a new one when it happens - would that be ok?

**Pull request closed without merging**
