### PR TITLE
feat(common): expose getLocaleCurrencyCode publicly

### PR DESCRIPTION
**Pull request by cexbrayat**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

It was previously defined in core without being exposed publicly, whereas `getLocaleCurrencyName` and `getLocaleCurrencySymbol` were defined in common, and publicly exposed.

## What is the new behavior?

This commit now privately exposes `ɵgetLocaleCurrencyCode` from core, and reexports it publicly from common.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
`getLocaleCurrencyCode()` needs to be in core to support #34724 in v10.

**Comment by cexbrayat** [comment]
@petebacondarwin I refactored 👍

**Review by petebacondarwin — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]
lgtm. thanks!

**Comment by IgorMinar** [comment]
merge-assistance: global approval

**Comment by AndrewKushnir** [comment]
FYI, g3 presubmit is successful (updated "google3" status for this PR to "green"). Thank you.

**Comment by AndrewKushnir** [comment]
@cexbrayat @petebacondarwin there was a conflict while merging this PR to patch branch, so I merged it to master only. Could you please create a patch-only version of this PR? Thank you.

**Pull request closed without merging**
