### PR TITLE
feat(testability): implement findBindings

### PR DESCRIPTION
**Pull request by juliemr**
[Review on Reviewable](https://reviewable.io/reviews/angular/angular/1855)

### CODE REVIEW

**Comment by juliemr** [comment]
@tbosch could you take a look at this one?

**Comment by vicb** [comment]
please rebase on master (was failing at the time you've submitted the PR)

**Comment by juliemr** [comment]
Rebased.

**Comment by tbosch** [comment]
Julie, I think we should do this in a different way. Right now, you have to traverse the whole View tree whenever a test wants to select an element by a binding.

Let's think about how to bring the `ElementProbe` back, as this would help the testability API as well as the debugging story. Let's chat tomorrow...

**Comment by juliemr** [comment]
Yup, chatting sounds good. For the record here though, performance really doesn't matter for Testability unless it gets really slow. The webdriver command latency will overshadow it when it's used by Protractor, and if it's being used manually from the console it'll only be a problem if it gets long enough for humans to notice.

**Comment by tbosch** [comment]
Thought about this, and the right way would be as follows:

1. create a [CompileStep](https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/compiler/compile_step.ts) that takes all property bindings of the `CompileElement` and store them as normalized attributes on the element. The `CompileStep` should [run as last step](https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/compiler/compile_step_factory.ts#L30).
2. protractor can then use this normalized format to find elements via `document.querySelectorAll`

The `RenderCompiler` should only do this in dev mode. Right now, we check for dev mode in other places via [assertionsEnabled()](https://github.com/angular/angular/blob/master/modules/angular2/src/facade/lang.ts#L23), so let's use this here as well.

**Comment by mhevery** [comment]
Cleaning up PRs. This one has not been touched for a while. Please create new PR once ready.

**Pull request closed without merging**
