### PR TITLE
feat(language-service): Provide plugin to delegate rename requests to Angular

### PR DESCRIPTION
**Pull request by ivanwonder**
When the user wants to rename a symbol in the ts file VSCode
will ask the rename providers for the answer in turn. If the
first extension returns the result, the VSCode will break the
loop and apply the result. If the first extension cannot rename
the symbol, VSCode will ask the second extension in the
list (built-in TS/JS extension, Angular LS extension, etc.).
In other words, VSCode takes the result from only one rename provider
and the order depends on registration timing, scoring.

Because the built-in ts extension and Angular extension have the
same high score, if the built-in ts extension is the
first(depends on the time the extension was registered), the result
will be provided by the built-in extension. We want Angular to
provide it, so this plugin will delegate rename requests and reject
the request for the built-in ts server.

The Angular LS only provides the rename info when working within
an Angular project. If we cannot locate Angular sources in the
project files, the built-in extension should provide the rename info.

This plugin will apply to the built-in TS/JS extension and delegate
rename requests to the Angular LS. It provides the rename info only
when it is an Angular project. Otherwise, it will return info by the
default built-in ts server rename provider.

See [here][1] for more info.

[1]: https://github.com/microsoft/vscode/issues/115354

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by atscott — CHANGES_REQUESTED** [review]
Really cool solution to the problem. I also like that you made this plugin available in the `@angular/language-service` so it could theoretically be used by extensions other than VSCode. Thanks for the investigation!

Given the complicated nature of the solution, I think it's a good idea to add more documentation and comments than is usually necessary. Here are a few changes I would propose:

* Add the contents of the README as a comment at the top of the `factory`
* Potentially add a README file here as well
* I would consider renaming the `built_in_ts_plugin` to be more self-documenting in its name. Something like `override_rename_ts_plugin.ts` or `disable_native_ts_rename_plugin`
* Update the commit message header to describe the goal rather than the solution. i.e. `feat(language-service): Provide plugin to delegate rename requests to Angular` and then add the implementation details to commit message body

I think it would also be good to get another reviewer's perspective. @clydin and @devversion - I've added you two as reviewers based on your knowledge of the general tooling/js/ts ecosystem. Feel free to un-assign yourselves if you don't have any input here.

**Review by atscott — APPROVED** [review]
👍  LGTM with edits to the documentation text.

**Comment by ivanwonder** [comment]
I am not good at writing. Thanks for the suggestion.

You can review it again now.

**Review by devversion — APPROVED** [review]
LGTM for dev-infra.

**Comment by devversion** [comment]
@atscott I just saw that you pinged Charles and myself on this directly. Sorry for the late response. I think this conceptually makes a lot of sense to me. I unfortunately do not have low-level understanding of the language service yet, but as said, conceptually that seems very reasonable until the root cause/scoring is modified.

It would be cool if the doc would show an example of how this additional plugin can be wired up? or is that planned as a follow-up?

**Comment by ivanwonder** [comment]
> It would be cool if the doc would show an example of how this additional plugin can be wired up? or is that planned as a follow-up?

The follow-up PR is [here](https://github.com/angular/vscode-ng-language-service/pull/1589)

**Comment by atscott** [comment]
> @atscott I just saw that you pinged Charles and myself on this directly. Sorry for the late response. I think this conceptually makes a lot of sense to me. I unfortunately do not have low-level understanding of the language service yet, but as said, conceptually that seems very reasonable until the root cause/scoring is modified.

👍  Sounds good, thanks for taking a look! I think that's pretty much all I was looking for :) 

> It would be cool if the doc would show an example of how this additional plugin can be wired up? or is that planned as a follow-up?

As @ivanwonder mentioned, the follow-up PR for the extension is https://github.com/angular/vscode-ng-language-service/pull/1589.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 9d4af65e343e41b48cb9afd12c2b61d8ca61a9ac.

**Pull request closed without merging**
