### PR TITLE
docs: update creating-libraries.md add language="json"

### PR DESCRIPTION
**Pull request by s0h311**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, can you have a look an sign the [CLA](https://github.com/angular/angular/pull/56153/checks?check_run_id=25551469510) ? Thank you

**Review by bencodezen — APPROVED** [review]
Agreed! Thank you for the PR!

**Comment by JeanMeche** [comment]
The file has currently a conflict, do you mind rebasing the PR ? Thank you.

**Comment by s0h311** [comment]
> The file has currently a conflict, do you mind rebasing the PR ? Thank you.

Done

**Comment by JeanMeche** [comment]
You added a merge commit, we'd like this PR to be a single commit so please squash thoses 3 commits.

**Comment by JeanMeche** [comment]
Can you reword your commit to make it a `docs: ...` (like the the PR title for example), this will make the CI lint check happy. 
Thank you.

**Comment by s0h311** [comment]
> You added a merge commit, we'd like this PR to be a single commit so please squash thoses 3 commits.

Done, sry for the inconvenience... I see that `<docs-code language="json">` has already been added in the mean time. So in this PR I just make minor changes.

**Comment by JeanMeche** [comment]
You're right, I think the example doesn't need any change right now. 
We prefer to keep the elipsis character (`…` is semanticaly more correct than 3 consecutive dots). 

Thanks anyway.

**Pull request closed without merging**
