### PR TITLE
Make NgZone.onEventDone handle both type of callbacks

### PR DESCRIPTION
**Pull request by gfanzh**
Fix issue
https://github.com/angular/angular/issues/4106

### CODE REVIEW

**Comment by tbosch** [comment]
Could you add a test for this, and also the JS implementation in `ng_zone.ts`?

**Comment by tbosch** [comment]
@gfanzh ping?

**Comment by gfanzh** [comment]
The issue seems broader than my fix.
I think issue 4535 will handle this more comprehensively.
https://github.com/angular/angular/issues/4535

I'll delete this one once someone is on 4535.

**Comment by tbosch** [comment]
#4535 is closed now, closing this PR.

**Pull request closed without merging**
