### PR TITLE
Update validators.ts

### PR DESCRIPTION
**Pull request by zoltanzseli**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
It changes my regex pattern

**What is the new behavior?**
It doesn't chage my regex pattern

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Change the pattern validator to accept custom regex without any modification.

### CODE REVIEW

**Comment by ULTiMATE-pinGu** [comment]
I signed it!

**Comment by vicb** [comment]
Please follow the instruction in this issue message:
- update your commit message,
- squash the commits,
- add tests.

(IIRC `RegExp` on form inputsare anchored which is probably why we have `^/$` ?)

**Comment by awiseman** [comment]
I don't think that this is a good change.  The pattern validator is based on the pattern html5 attribute and so its behavior matches those semantics, which requires that the pattern match the entire input string.  If you change the pattern validator to only match the string that's passed, there will be a disconnect between the browser's interpretation of that attribute and Angular2's.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-pattern

**Comment by mhevery** [comment]
This PR is stale (does not rebase; pass CI; had no activity for a while). It is probably our fault, and we are sorry. In an effort to keep our PR queue under control, and prevent us from taking too long to get back to you we are cleaning up the queue. Unfortunately this means that this PR is getting closed.

If you would like to resurrect this change, please rebase on master, make the tests pass and create a new PR.

**Pull request closed without merging**
