### PR TITLE
chore(ddc): add e2e test infra + first test

### PR DESCRIPTION
**Pull request by yjbanov**
Also bumped error cap to 10 because the new version of DDC is reporting more errors.

### CODE REVIEW

**Comment by yjbanov** [comment]
This is currently blocked by https://github.com/angular/angular/issues/6846. Once the issue is resolved I can easily clean up this PR for review.

**Comment by vsmenon** [comment]
@IgorMinar This is the PR blocked on #6846.  Is there a way to rerun it on travis before submitting?

**Comment by yjbanov** [comment]
I'll rebase on top of @mlaval's PR #5393 and see.

**Comment by IgorMinar** [comment]
#6846 is fixed now so this PR should be unblocked

**Comment by vsmenon** [comment]
@yjbanov is this rebased or still failing on the latest?

**Comment by yjbanov** [comment]
This is failing with rebase on top of master after #6846 was submitted. I only gave it one attempt. Haven't looked at what's going on yet.

**Comment by mhevery** [comment]
Replaced by: #7725

**Pull request closed without merging**
