### PR TITLE
docs(aio): correct abbreviation

### PR DESCRIPTION
**Pull request by swseverance**
change abbreviation from 'ES' to 'ES2015'. the 'ES2015' abbreviation is used elsewhere in the tutorial.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: Fix to documentation
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by Toxicable** [comment]
Your need to re-generate the Docs

**Comment by gkalpak** [comment]
@Toxicable, not sure what you mean :confused:

**Comment by Toxicable** [comment]
@gkalpak Neither am I. The error in Travis said that the docs that the docs should be regnerated, so I was just reiterating that incase it was missed to try get this through since it's an easy one

**Comment by gkalpak** [comment]
The Travis failure was a flake :smiley: I restarted it and it's all good now.
This looks good to go (cc @wardbell).

**Comment by IgorMinar** [comment]
Unfortunately I don't think that this change is right. The `import` keyword is part of the ES (ECMAScript) spec, it just happened to be introduced in ES2015, but that's not really interesting to the reader. We should stay away from listing the versions of any kind anywhere (ES spec or Angular) unless we actually want to point out when that particular feature was introduced.

**Comment by swseverance** [comment]
If that's the case you may consider replacing the references to 'ES2015' found in toh-pt1.md & toh-pt4.md

**Review by wardbell — APPROVED** [review]

**Comment by wardbell** [comment]
@IgorMinar - @swseverance has a point.  We have called out ES2015 all over the place.

We can start a sweep to replace them all if you want.

**Pull request merged**
