### PR TITLE
feat(language-service): support to fix invalid banana in box

### LINKED ISSUE #44941: Extended diagnostics quick fix
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler-cli, language-service

### Description

Extended diagnostics often have a suggestion solution. This is by design, since they are intended to identify specific mistakes often made by developers with clear solutions or best practices. Since these fixes are so mechanical, we should give an easy, automated way to apply them to a diagnostic.

### Proposed solution

Extended diagnostics should be able to generate a set of possible "quick fix" transformations which IDE's can use to address the diagnostic. In the case of `invalidBananaInBox`, we could automate a change like:

```html
<div ([foo])="bar">Hello</div>
<!-- Fixes to... -->
<div [(foo)]="bar">Hello</div>
```

@danieltre23 came up with a prototype in https://github.com/danieltre23/angular/commit/52f6a7af6c36ee05eef0c67e159c5a8828a42bc3 and was able to demo the feature. It's a relatively small commit so I don't think this is a significant amount of effort. The work here is to define the "quick fix" data type in the compiler, we'll need something custom since we don't want to depend on VSCode / LSP types here (curious how `tsc` does this?). The language service / VSCode extension will then need to transform the "quick fix" type into VSCode-compatible "code actions", which the IDE can show and apply with a single click.

### Alternatives considered

N/A

### PR DESCRIPTION
**Pull request by ivanwonder**
The Angular compiler will report the invalid banana in box, this code fixes will try to fix the error and all the same errors in the selected file.

fixes https://github.com/angular/angular/issues/44941

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ivanwonder** [comment]
@dylhunn

**Review by Jeriko100 — APPROVED** [review]

**Comment by dylhunn** [comment]
Sorry, didn't see this. I'll review tomorrow morning.

**Comment by ivanwonder** [comment]
// cc @atscott

**Review by atscott — APPROVED** [review]
👌 Awesome. LGTM

Can you also add the "fixes #44941" note to the commit message?

**Review by dylhunn — APPROVED** [review]
reviewed-for: language-service

**Comment by dylhunn** [comment]
Looks like Andrew beat me to it. Thanks for implementing this :)

**Review by atscott — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit e7ee53c541da0a1f85c217354ec9901010ae0de9.

**Pull request closed without merging**
