### PR TITLE
docs: expand abbreviation in providers guide

### PR DESCRIPTION
**Pull request by sugoidesune**
expand abbreviation

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Documentation contained abbreviation.

Issue Number: N/A

## What is the new behavior?
Expanded abbreviation and added link.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

### CODE REVIEW

**Comment by sugoidesune** [comment]
@googlebot I signed it!

**Comment by kapunahelewong** [comment]
Thanks for this fix, @sugoidesune. Could you `git commit --amend` to update the commit message to be:

```
docs: expand abbreviation in providers guide 

The intro paragraph currently uses the DI abbreviation, 
but it is clearer with DI written out and linked to the DI guide.
```

Please tag me when you're ready. This is a good fix, thanks!

**Comment by sugoidesune** [comment]
@kapunahelewong should meet the requirements now.
Thank you for your message 😃

**Comment by kapunahelewong** [comment]
Perfect. Thanks, @sugoidesune. Could you rebase? As soon as it's newly rebased I'd like to help it through the next steps. 🌸

**Review by kara — APPROVED** [review]
LGTM

**Pull request closed without merging**
