### PR TITLE
refactor:i flag(ignore case) is not needed

### PR DESCRIPTION
**Pull request by kizashi1122**
This commit removes i flags from regular expressions without any alphabetical characters.

## PR Checklist

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kizashi1122** [comment]
@googlebot I signed it!

**Review by petebacondarwin — APPROVED** [review]

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Oh actually, we need to fix the formatting of the file that you changed.
Once you touch a file it must be formatted.

**Comment by petebacondarwin** [comment]
Great! Thanks for reformatting the file. Now we just need to get the commit messages in order.
The first commit message should be something like:

```
refactor(common): remove `i` (ignore case) regex flag where it is not needed
```

And the second commit should be a "fixup" commit so that our merge tool can squash the two commits into one.

```
fixup! refactor(common): remove `i` (ignore case) regex flag where it is not needed
```

Could you rebase your PR and change these commit messages, please?

**Comment by kizashi1122** [comment]
To be honest, I don't know why the tests failed on circle/ci.

I tried to hit the following command as instructed:

```
          git fetch upstream master;
          git checkout no-need-ignorecase-flag;
          git rebase upstream/master;
          git push --force-with-lease;
```

But nothing changed.
Please let me know what should I do next.

**Comment by petebacondarwin** [comment]
Hi @kizashi1122 - thanks for rebasing and fixing up the commit messages.
I suspect that what happened was that shortly after you rebased a new commit landed that your PR also needs rebasing on top of! Sorry! Can you try again?

**Comment by kizashi1122** [comment]
Hi @petebacondarwin - How should I do next?

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Great @kizashi1122 - we just need to get it tested against internal Google projects via `presubmit` and approved by `fw-core` then we are good to land this.

**Review by AndrewKushnir — APPROVED** [review]
@kizashi1122 thanks for the refactoring 👍 

I've started tests in Google's codebase ([internal-only link](http://test/OCL:335792961:BASE:335792931:1602047352052:3e3628b3)) and will update this thread once I have results.

Thank you.

**Comment by AndrewKushnir** [comment]
@kizashi1122 FYI, the tests in Google's codebase went well, so I'm adding this PR to the merge queue.

Thanks for contributing to Angular!

**Pull request closed without merging**
