### PR TITLE
docs(router): Update runGuardsAndResolvers documentation

### LINKED ISSUE #46001: runGuardsAndResolvers documentation doesn’t clearly describe when it’s used
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

The Documentation suggests that you can supply a function to [runGuardsAndResolvers ](https://angular.io/api/router/RunGuardsAndResolvers). The link will take you to the documentation where it gives the type.

So I supplied the following and saw that not only was my route guard still being run, but the console log was not output.
```
((from: ActivatedRouteSnapshot, to: ActivatedRouteSnapshot) => {
          console.log(from,to);

          return false;
})
```

It seems something is not working as described in the documentation. So either it's a bug or the documentation is misleading?

### Please provide a link to a minimal reproduction of the bug

I don't have time to do this. I'll figure out another solution if needed.

### Please provide the exception or error you saw

```true
There were no errors. The guards ran when they should not have.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.6
Node: 16.14.0
Package Manager: npm 8.3.1
OS: win32 x64

Angular: 13.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@angular/cdk                    13.3.6
@angular/cli                    13.2.6
@angular/flex-layout            13.0.0-beta.38
@angular/material               13.3.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
```

### Anything else?

I have seen runGuardsAndResolvers work in an older version of angular, but it was about a year and a half ago since I implemented that and it was for a different website.

### PR DESCRIPTION
**Pull request by ghost**
Resolves #46001
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by najmiehsa** [comment]
@atscott  I reponed another PR and still, there is no option to replace the email address. This is weird!

**Comment by najmiehsa** [comment]
one

two

**Comment by najmiehsa** [comment]
one

Here it shows that email should be a proton one. 

but here there is literary no option to switch into this email:
two

**Comment by atscott** [comment]
@najmiehsa If you created the PR from the same branch with the same commit, the same problem would have occurred.
If you just want to change the author of your last commit, you can do this:
```
Reset your email to the config globally: git config --global user.email example@email.com.
Now reset the author of your commit without edit required: git commit --amend --reset-author --no-edit.
```

**Comment by najmiehsa** [comment]
I update this a bit later. Formating is not passing.

**Comment by najmiehsa** [comment]
@atscott  I installed husky and did the configuration but I didn't change my angular clone package.json( therefore I'd get husky directory doesn't exist). 
I tried to configure the git hooks to format my commit before pushing. Once I try to format this commit, I'd get ``ng-dev not found.``

yar

I need a clue for how to get the format right and hopefully merge this PR.

**Comment by atscott** [comment]
@najmiehsa Have you installed all the packages with [`yarn install`](https://github.com/angular/angular/blob/main/docs/DEVELOPER.md#installing-npm-modules)? There's a pretty detailed guide to getting the environment set up [here](https://github.com/angular/angular/blob/main/docs/DEVELOPER.md).

**Comment by najmiehsa** [comment]
> @najmiehsa Have you installed all the packages with [`yarn install`](https://github.com/angular/angular/blob/main/docs/DEVELOPER.md#installing-npm-modules)? There's a pretty detailed guide to getting the environment set up [here](https://github.com/angular/angular/blob/main/docs/DEVELOPER.md).

Thank you for the source. Highly appreciate it.
Previously I installed the package but there should be a malfunctioning somewhere. I need to diagnose that.

**Comment by najmiehsa** [comment]
@atscott I've tried a good number of different approaches to resolve dependency conflicts while install angular developer package. 

Things like, adding resolutions and changing versions and requests prefixes. I even changed my OS to Ubuntu to resolve this conflict  `` An unexpected error occurred: "http://saucelabs.com/downloads/sc-4.7.1-linux.tar.gz: Request failed \"403 Forbidden\"".`` But there are no good resources on this specific topic and this particular error. 

It took me a good couple of days! I can comment this documentation to the issue so that someone else can submit a PR?

**Pull request closed without merging**
