### PR TITLE
docs(core): Fixed typo in Type JSdoc

### PR DESCRIPTION
**Pull request by imolorhe**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sonukapoor** [comment]
@imolorhe Could you please sign the CLA? You can find the instructions [here](https://github.com/angular/angular/pull/37930#issuecomment-653808508).

**Comment by imolorhe** [comment]
@googlebot I signed it!

**Comment by imolorhe** [comment]
@sonukapoor Done!

**Comment by sonukapoor** [comment]
Thanks @imolorhe - Could you rebase and push again? The commit message max chars have been reduced to 20.

**Comment by imolorhe** [comment]
@sonukapoor Isn't 20 an extremely small allowed length?

**Comment by gkalpak** [comment]
@imolorhe, this was obviously a typo. @sonukapoor meant that the _min_ length of the commit message body is 20 chars (but that does not affect `docs:` commits, which are usually self-explanatory and thus don't require a commit message body (just the header)).

See [CONTRIBUTING.md#commit][1] for more info on our commit message guidelines.

[1]: https://github.com/angular/angular/blob/66947cf9faafd4c039e2a0a958e741656b103788/CONTRIBUTING.md#commit

**Comment by sonukapoor** [comment]
> @sonukapoor Isn't 20 an extremely small allowed length?

It depends. For typo changes, there isn't much you can add to the commit message, so 20 chars make sense. For more complicated issues, I would expect a detailed message. It's up to the reviewer to ask the PR author to adjust the commit message depending on the complexity of the issue.

**Comment by sonukapoor** [comment]
> @imolorhe, this was obviously a typo 😁
> @sonukapoor meant that the _min_ length of the commit message body is 20 chars (but that does not affect `docs:` commits, which are usually self-explanatory and thus don't require a commit message body (just the header)).
> 
> See [CONTRIBUTING.md#commit](https://github.com/angular/angular/blob/66947cf9faafd4c039e2a0a958e741656b103788/CONTRIBUTING.md#commit) for more info on our commit message guidelines.

Yup. Thanks @gkalpak

**Comment by imolorhe** [comment]
The guide in CONTRIBUTING.md says the body is optional for docs commits though. I updated the commit message to include a body. Let me know if that's what you mean! 😊

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Hi @imolorhe, thanks for the fix!

I've rebased this PR to restart the CI (it indicated that the base commit was too old), so this PR should be ready for merge once CI run is completed successfully.

Regarding the commit body length: the requirement of 100 chars was updated to 20 chars for all commits except the docs commits (which are not required to have a commit body at all).

**Pull request closed without merging**
