### PR TITLE
docs: add alisa duncan to GDE resources

### PR DESCRIPTION
**Pull request by alisaduncan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Add Alisa Duncan to GDE contributors list

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
LGTM!

**Comment by alisaduncan** [comment]
Hi @petebacondarwin. I saw your message on Slack and checked out the PR reducing image sizes. Would you like for me to apply the same methodology to the image in this PR?

**Comment by petebacondarwin** [comment]
Hi @alisaduncan - don't worry. Your image is already nice and small. We are setting a 30Kb upper limit but yours appears to be only around 16Kb. So I think you are good.

**Review by twerske — APPROVED** [review]
LGTM - approved for GDEs, welcome Alisa!

**Pull request closed without merging**
