### PR TITLE
Cherry-pick #40694 to patch branch

### PR DESCRIPTION
**Pull request by alan-agius4**
Cherry-pick of https://github.com/angular/angular/pull/40694

//cc @kyliau 

Fix https://github.com/angular/vscode-ng-language-service/issues/1126

### CODE REVIEW

**Comment by kyliau** [comment]
@zarend this is a patch PR for https://github.com/angular/angular/pull/40694 so it doesn't require google3 presubmit.

**Review by zarend — APPROVED** [review]

**Comment by zarend** [comment]
Closed by commit e3ccd56567fdc7ca00f3a0c7c7e5033b2bece865

**Comment by JounQin** [comment]
@alan-agius4 It seems `readConfiguration` does not support nested `extends` while TypeScript will resolve `extends` recursively.

**Comment by alan-agius4** [comment]
Can you kindly find an issue with a reproduction? I'll look at it in the
coming weeks. Thanks.

**Comment by JounQin** [comment]
@alan-agius4 That's a different problem actually, see #41343

**Pull request closed without merging**
