### PR TITLE
chore(package.json): bump dgeni-packages version

### PR DESCRIPTION
**Pull request by jeffbcross**
(Also some clang fixes)

Partial fix to #2452

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Rather a lot of changes to `npm-shrinkwrap.clean.json`?

**Comment by jeffbcross** [comment]
@petebacondarwin I just followed the instructions to update in npm-shrinkwrap.readme.md. It's just matching the latest versions in npm that match the rules in package.json. Should I manually remove the entries that aren't related to dgeni-packages?

**Comment by jeffbcross** [comment]
@petebacondarwin tried again. Not sure what I did differently, but it's a smaller change (and clang didn't complain this time).

**Comment by jeffbcross** [comment]
Merged at d10bbf0cbc13d28f4ea9f722387a71d2f14d5a28

**Pull request closed without merging**
