### PR TITLE
docs(aio): fix a typo to improve readability

### PR DESCRIPTION
**Pull request by shioyang**
Remove a comma and space

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

There are unnecessary comma and space.
Issue Number: N/A

## What is the new behavior?
The line doesn't have unnecessary comma and space.
The readability is improved.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Thx for the PR 👍

Any chance you could update the commit message to follow our [guidelines][1]?
<sub>(E.g. use what you have on the PR title.)</sub>

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

**Review by brad — APPROVED** [review]

**Comment by shioyang** [comment]
Thank you for your comment. Yes, I will revise the commit message.

**Comment by shioyang** [comment]
@gkalpak I revised the commit message. Thanks!

**Comment by gkalpak** [comment]
The CI failure is unrelated to the PR.

**Pull request closed without merging**
