### PR TITLE
build: update to latest version of yarn

### PR DESCRIPTION
**Pull request by josephperrott**

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM. Should we update version ranges in the `package.json`? Adding `PR action: cleanup` so you can react to my feedback.

**Comment by josephperrott** [comment]
@devversion I updated them

I am unsure of how we should be handling this since yarn should be doing the vendoring for us now, but it doesn't hurt to update it.

**Comment by devversion** [comment]
@josephperrott Yeah, I'm not sure either. It sounds like we could just remove the range for `Yarn`.

**Comment by atscott** [comment]
@josephperrott - Is this ready to merge? If so, can you please remove Igor from the reviewers list and/or add the merge assistance label if pullapprove is still not happy?

**Pull request closed without merging**
