### PR TITLE
docs: fix typo in CLI overview

### PR DESCRIPTION
**Pull request by emccorson**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by santoshyadav198613** [comment]
Hi @emccorson ,
That's correct what we want to say is if you don't have rights on the directory , you won't be able to create the folder if you want you can add "''" which is missing in won't.

**Review by gkalpak — APPROVED** [review]
Ooops! Good catch 👍

**Comment by gkalpak** [comment]
**merge-assistance:** Global approval for this docs-only change.

**Comment by kapunahelewong** [comment]
Thanks for this, @emccorson 😊

**Pull request closed without merging**
