### PR TITLE
docs: fix appRoutes constant was not passed correctly to provideRouter

### PR DESCRIPTION
**Pull request by ShahriarMalik**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The `appRoutes` constant is not passed correctly to `provideRouter` in the `appConfig`, which may cause routing configuration issues.

Issue Number: N/A

## What is the new behavior?

The `appConfig` now correctly uses the `appRoutes` constant in the `provideRouter` function, ensuring proper routing configuration.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This fix improves the readability and maintainability of the routing configuration. It ensures that the `appRoutes` constant is correctly referenced, preventing potential routing issues.

### CODE REVIEW

**Comment by devversion** [comment]
LGTM, thank you! @ShahriarMalik can you please fix the commit message and sign the CLA?

* CLA: https://github.com/angular/angular/pull/57070/checks?check_run_id=27722140547
* Commit message: https://github.com/angular/angular/actions/runs/10031551605/job/27722149958?pr=57070. And https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by ShahriarMalik** [comment]
Thank you for the guidance, @devversion. I've updated the commit message to follow the correct format and signed the CLA.

**Comment by JeanMeche** [comment]
We would need that change to be a single commit, could you please squash those commits ? 
Also you only edited the PR title but not the commit message. As this is only a doc change, the commit should be `docs: fix ... `

**Comment by ShahriarMalik** [comment]
Hi @JeanMeche,

I have squashed my commits into a single one and updated the commit message to follow the required format. Thanks

**Review by devversion — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit d84d4073587547cb75b33127766010978d88aac8.

The changes were merged into the following branches: main, 18.1.x

**Pull request closed without merging**
