### PR TITLE
build: update parse5 to v3

### PR DESCRIPTION
**Pull request by vicb**

### CODE REVIEW

**Review by alxhub — APPROVED** [review]

**Review by vikerman — APPROVED** [review]

**Review by IgorMinar — CHANGES_REQUESTED** [review]
please update package.json of platform-server as well

**Comment by vicb** [comment]
Thanks @IgorMinar, good catch ! PTAL

**Comment by vikerman** [comment]
Hi - Can you put platform-server in the commit message. Thanks!

**Comment by vicb** [comment]
@vikerman how/why ? (seems like a build to me)

**Comment by IgorMinar** [comment]
@vicb `git commit --amend` allows you to rewrite the commit message.

**Comment by vicb** [comment]
`git` ? what's that !

```
$ git
-bash: git: command not found
```

**Comment by IgorMinar** [comment]
@vicb `brew install git`

**Review by IgorMinar — APPROVED** [review]

**Pull request merged**
