### PR TITLE
only call getUrlScheme with string of moduleId

### PR DESCRIPTION
**Pull request by mhamel06**
https://github.com/angular/angular/pull/10512/files and specifically the line below have caused an uncaught TypeError for the function componentModuleUrl.

https://github.com/jasonchoimtt/angular/blob/a5b544e8736d4e0fa40744ca610b682fff2eec07/modules/%40angular/compiler/src/url_resolver.ts#L263

Changing _split to use String.match instead of RegEx.exec has caused an error of `Uncaught TypeError: uri.match is not a function` when _split is called with something other than a string. 

This change will ensure that getUrlScheme is called with a string and subsequently _split is called with a string.

### CODE REVIEW

**Comment by jonathan-casarrubias** [comment]
+1 for this pull request

**Comment by kucharzyk** [comment]
+1 for this pull request

**Comment by Alex-Torres** [comment]
+1 for this pull request

**Comment by gdi2290** [comment]
check if it's isPresent and a string

**Comment by mhamel06** [comment]
@gdi2290 Updated

**Comment by davidmarquis** [comment]
+1

**Comment by phptuts** [comment]
+1

**Comment by kurtommy** [comment]
+1

**Comment by gregbown** [comment]
Jumping in here since this seems to be related to my issue in building Angular 2 rc5 with Material 2 alpha7-2.

The initial fix
`var scheme = getUrlScheme(moduleId.toString());`
corrected the issue I was having with Material 2 components not being recognized... until Material 2 removed module.id from all there components in alpha7-2, thenit broke the entire application.  I resolved this by adding back the module.id to the modules I was using.  I filed a bug with material 2 however they claim they are no seeing any issues?
I also tried the latest change made to this file 
`if (isPresent(cmpMetadata.moduleId) && typeof cmpMetadata.moduleId === 'string') {`
This did not resolve my issue and also broke the application?

I would appreciate any incite on the issue.
Thank you
Greg

**Comment by gdi2290** [comment]
I forgot to mention. For anyone using webpack and needs this to work please add this loader to `preLoaders`
https://github.com/AngularClass/angular2-seed/commit/84aacc18682bbe38631cd3c457d9e90944d6fd0e
```es6
       {
          test: /.js$/,
          loader: 'string-replace-loader',
          query: {
            search: 'moduleId: module.id,',
            replace: '',
            flags: 'g'
          }
       }
```
that will remove `moduleId: module.id,` from modules

**Comment by randyaa** [comment]
:+1:

**Comment by robertbaker** [comment]
You will need to change your commit msg to follow CONTRIBUTING.md

**Pull request closed without merging**
