### PR TITLE
Fix nav focus active styles

### LINKED ISSUE #33239: Top Menu highlight wrong item after click on browser back button
# 📚 angular.io bug
### Reproduction Steps**
1. Open angular.io page
2. Click on resources link on top
3. Click on docs link on top
4. Click on browser back button.
The docs link is highlighted while it should highlight resource link

### Expected vs Actual Behavior**
Browser back button does change the page back to the last page user on, and it should also the highlight item of current page. But it is not highlighting the correct menu item

### PR DESCRIPTION
**Pull request by sonukapoor**
Fixes #33239

Improved focus styles for topnav and footer including visible color.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #33239

## What is the new behavior?

Topnav:
header

Footer:
footer

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

This PR builds on top of https://github.com/angular/angular/pull/33255

### CODE REVIEW

**Comment by sonukapoor** [comment]
@googlebot I consent.

**Comment by sonukapoor** [comment]
@gkalpak The e2e tests are failing on circleci but running fine on my end. Can you take a look at that please?

**Comment by gkalpak** [comment]
As discussed "offline", this seems to be caused by difference in Chrome's rendering between Windows and Linux/macOS. @sonukapoor is looking into it.

**Comment by sonukapoor** [comment]
@gkalpak can we proceed with this?

**Pull request closed without merging**
