### PR TITLE
docs: Update Making HTTP requests best practices example

### PR DESCRIPTION
**Pull request by ankurinfoniti**
It should be this.userService.getPost() instead of userService.getPost(); in best practices example

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thanks for this. 

Can you please make sure to sign the CLA and reword your commit to follow our commit message guidelines. It should be a `docs: ...` commit.

**Comment by ankurinfoniti** [comment]
I have sign the CLA and reworded my commit message. Please check it now.

**Comment by JeanMeche** [comment]
You changed the PR title but not the commit message itself. Also, there is no new for a scope, you can drop the `docs-infra`.

**Comment by ankurinfoniti** [comment]
I have updated the commit message and pushed it with required email.

**Comment by ankurinfoniti** [comment]
Google CLA sign is also completed now. @JeanMeche Please check it now.

**Review by JeanMeche — APPROVED** [review]
Thanks for this !

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 9020a50e6d6f1c6bc6b4cb2ee60c1df6d7a6d7c6.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
