### PR TITLE
fix(zone.js): Closes #31626, zone-mix should import correct browser module

### LINKED ISSUE #31626: zone-mix: Cannot read property 'eventNames' of undefined
After upgrading from Angular 7 to Angular 8, our Electron builds break seemingly because of zone-mix:

```
polyfills.js:7635 Uncaught TypeError: Cannot read property 'eventNames' of undefined
    at eventTargetPatch (polyfills.js:7635)
    at polyfills.js:8003
    at Function.push../node_modules/zone.js/dist/zone-mix.js.Zone.__load_patch (polyfills.js:5274)
    at polyfills.js:8001
    at push../node_modules/zone.js/dist/zone-mix.js.performance (polyfills.js:5185)
    at Object../node_modules/zone.js/dist/zone-mix.js (polyfills.js:5187)
    at __webpack_require__ (runtime.js:84)
    at Module../src/polyfills-electron.ts (polyfills.js:8476)
    at __webpack_require__ (runtime.js:84)
    at Object.1 (polyfills.js:8551)
```

Taking a look at code, it is calling `api.getGlobalObjects()` and then accessing `.eventNames`, 

```
    var _a = api.getGlobalObjects(), eventNames = _a.eventNames, ...
```

but the definition in effect is from zone-mix.js:644

```
        getGlobalObjects: function () { return undefined; },
```

The polyfills file in use for our Electron builds are:

```
import 'core-js/es7/reflect';
import 'zone.js/dist/zone-mix';  // Included with Angular CLI.
import 'zone.js/dist/zone-patch-electron';
```

The installed version of zone.js is 0.9.1. 

I checked STANDARD-APIS.md and it does still recommend 'zone-mix' for Node-capable Electron builds (`nodeIntegration = true`). Tried removing `zone-patch-electron` but there's no change.

Is this still the recommended polyfills.ts setup for Angular apps running in Electron with Node integration turned on?

The error is not present if I opt for `zone.js/dist/zone` (the standard) as opposed to zone-mix, but I assume I'll only have Zone integration for browser APIs and not Node.js ones, so that's not ideal.

### PR DESCRIPTION
**Pull request by JiaLiPassion**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31626 

import `zone-mix` will cause error when patch `eventTargets`.

## What is the new behavior?
`zone-mix` will work fine.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
Why no test?

**Comment by JiaLiPassion** [comment]
@mhevery , you are right, I will add test here.

**Comment by JiaLiPassion** [comment]
@mhevery, I added a test to make sure `zone-mix` can be correctly loaded in `mixed` environment. please review, thanks.

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:259671087:BASE:259671091:1563942162577:9ea6229d)

**Pull request closed without merging**
