### PR TITLE
feat(compiler-cli): Directives, Components and pipes are standalone by default

### PR DESCRIPTION
**Pull request by JeanMeche**
With this commit, Directives, Components and Pipes are now standalone by default and don't require `standalone: true` anymore

See individual commits. 

BREAKING CHANGE: Directive, Components and Pipes are now standalone by default

### CODE REVIEW

**Comment by JeanMeche** [comment]
Note: the ADEV tests are currently red because they are run against the node_modules instead of the load packages. Currently investigating this but it shouldn't prevent from starting to review the PR.

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by jelbourn** [comment]
@JeanMeche would you mind splitting this up into separate PRs just to make it easier to review and sync? We could do one for setting `standalone: false` first, one for the changes to the framework/toolchain to change the default, and then another to clean up the obsolete `standalone: true`.

**Comment by JeanMeche** [comment]
I'll do this yes. 
Let me close this PR as is, and go with the 3 new PRs you mentionned.

**Pull request closed without merging**
