### PR TITLE
fix(compiler): Better error messages for missing let in ngFor directive

### PR DESCRIPTION
**Pull request by Math3v**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/angular/angular/issues/14641

**What is the new behavior?**
Introduced error message 'Can't bind to *ngFor since it's missing the let keyword.' for missing let keyword in *ngFor directive.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Math3v** [comment]
I signed the CLA.

**Comment by Math3v** [comment]
Could someone please take a look at this PR? Thanks!

**Comment by Toxicable** [comment]
This looks like a rather "hacky" way to fix this issue. Also it dosen't solve the wider problem. Being that `ngIf` directive also has the same issue

**Comment by Math3v** [comment]
@Toxicable Thanks for your review and response! I totally agree that this solution is rather hacky. Is there some compiler utility/function which I could integrate into this solution to provide less hacky error checking?

**Comment by vicb** [comment]
Closing as the compiler should not assume anything about directives

**Pull request closed without merging**
