### PR TITLE
refactor(dart/transform): Migrates tests to use package:test

### PR DESCRIPTION
**Pull request by kegluneq**
Our transformer unit tests currently use package:guinness, which uses
package:unittest under the covers. package:unittest has been updated and
renamed package:test, so for simplicity migrate test to use package:test
syntax.

### CODE REVIEW

**Comment by zoechi** [comment]
Love it! Much more darty :)
No offence meant for victors Guinnes package though.

**Comment by btford** [comment]
@kegluneq build went red: https://travis-ci.org/angular/angular/jobs/109734984

Can you investigate?

**Comment by kegluneq** [comment]
@vsmenon @jmesserly

This is almost certainly a change to ddc. I'll talk to the folks working on that project about it.

**Comment by vsmenon** [comment]
The DDC bot is complaining that there are more severe errors in the Dart code (was 6, now 11).  Should only be code reachable from samples - I'm surprised this is trigger - it's only changing tests?

**Comment by kegluneq** [comment]
Looks like it was ae275fa4e469f0b30142260f06f2a16511dcd071 causing the breakage.

The number of allowed ddc severe errors was upped in a7e9bc97f6a19a2b47b962bd021cb91346a44baa, so this should no longer be blocked.

**Comment by kegluneq** [comment]
@matsko, looks like the js.dev build is broken/flaky - what would you like me to do?

**Comment by vsavkin** [comment]
Merged via https://github.com/angular/angular/commit/28a78117ebfb65b66624b0ce6245c928c3df4198

**Pull request closed without merging**
