### PR TITLE
docs: fix typo of zone.js README.md

### PR DESCRIPTION
**Pull request by JiaLiPassion**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

Fix a typo of zone.js README, the `persentation.png` should use relative path.

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
@JiaLiPassion as a separate note, the `zone.js` folder should be added to a section in the `.github/CODEOWNERS` file so PRs gets assigned to the correct people for review. I don't know which group that is though. cc: @IgorMinar @mhevery

**Comment by JiaLiPassion** [comment]
@brandonroberts, thanks for the review.

> as a separate note, the zone.js folder should be added to a section in the .github/CODEOWNERS file so PRs gets assigned to the correct people for review. I don't know which group that is though.

I believe @gkalpak will create a PR to update the `CODEOWNERS` file. 
Thanks!

**Comment by IgorMinar** [comment]
yup. @JiaLiPassion you can go ahead and create the PR for codeowners yourself. Create a new rules for zone.js and add yourself and misko there as the owners + add global approvers. thanks

**Comment by kara** [comment]
@IgorMinar There is a PR already, just waiting for review

https://github.com/angular/angular/pull/31203

**Pull request closed without merging**
