### PR TITLE
Cross repo angular dependencies

### PR DESCRIPTION
**Pull request by alan-agius4**
Supersedes https://github.com/angular/angular/pull/51871

### CODE REVIEW

**Comment by alan-agius4** [comment]
FYI @AndrewKushnir, this also brings in all the changes in Domino.

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: global-approvers

**Comment by AndrewKushnir** [comment]
@alan-agius4 thanks for the update, I've closed my PR to update Domino separately (#51990)

**Review by AndrewKushnir — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit e9c3790b4ea7633c3a3242640210452ed1fd2a3e.

**Pull request closed without merging**
