### PR TITLE
refactor(http): rename enums to be singular

### PR DESCRIPTION
**Pull request by cexbrayat**
As seen with @jeffbcross in #5574

ReadyStates -> ReadyState
RequestMethods -> RequestMethod
ResponseTypes -> ResponseType

### CODE REVIEW

**Comment by jeffbcross** [comment]
Looks good! Would you mind adding a colon after `BREAKING CHANGE` in your commit message? I think our changelog script may require it.

**Comment by cexbrayat** [comment]
OK, it's done!

**Comment by jeffbcross** [comment]
@jelbourn mind merging this? It will be a no-op for sync.

**Comment by jeffbcross** [comment]
Thankx @cexbrayat!

**Pull request closed without merging**
