### PR TITLE
docs(docs-infra): fix broken links

### LINKED ISSUE #55442: Broken links on ng-template reference page
### Describe the problem that you experienced

Clicking links to "[Structural directives](https://angular.dev/guide/structural-directives)." and "[standard template variables](https://angular.dev/guide/template-reference-variables#how-angular-assigns-values-to-template-variables)" bring up the "Page No Found 🙃" page.

### Enter the URL of the topic with the problem

https://angular.dev/api/core/ng-template#mat-tab-content-108-0

### Describe what you were looking for in the documentation

_No response_

### Describe the actions that led you to experience the problem

_No response_

### Describe what you want to experience that would fix the problem

_No response_

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by vladboisa**
Add the missing folder's for links

Fixes #55442

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]

**Comment by JeanMeche** [comment]
Can you please squash your 2 commits into one ? Thank you.

**Comment by vladboisa** [comment]
> Can you please squash your 2 commits into one ? Thank you.

Yea, in prev commit 3rd link did not work. 
Done hotfix & squash

**Review by sonukapoor — APPROVED** [review]
LGTM

**Review by alxhub — APPROVED** [review]

**Review by alxhub — APPROVED** [review]
Reviewed-for: global-approvers

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 900b5e7dfd66ca7546d6f210ff921ab32002e827.

**Pull request closed without merging**
