### PR TITLE
Update doc for timezone param in DatePipe

### PR DESCRIPTION
**Pull request by WreckItRalph**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by ocombe** [comment]
Could you add some explanation as to why you want to change that?

**Review by jbogarthyde — APPROVED** [review]
Change looks good, but the line is too long, causing lint test to fail.
Split it onto a separate line (and make sure there is no trailing space). 

@ocombe The reason was given in https://github.com/angular/angular/pull/31285 - confusion over meaning of "default". Now the description is of the default *behavior*, when the  *value* defaults to "undefined".

**Comment by jbogarthyde** [comment]
Please mark for merge and merge-assist to get it green.
@mhevery Code-owner approval needed for this small API doc clarification.

**Review by ocombe — APPROVED** [review]

**Comment by WreckItRalph** [comment]
How to start the "ci-codefresh-bazel" build again ?

**Comment by alan-agius4** [comment]
caretaker: the CI failure is a flake.

**Pull request closed without merging**
