### PR TITLE
fix(ivy): always convert `rootDirs` to `AbsoluteFsPath` in `getRootDirs`

### LINKED ISSUE #29140: IVY doesn't working on Windows even in Angular 8.0.0-beta.7
# 🐞 bug report

### Affected Package
Angular IVY on Windows

### Description

I know there was a file path problem in Angular IVY compiler on Windows, but it seems that it has been fixed in Angular 8.0.0-beta.7 (https://github.com/angular/angular/pull/28752)

I tried compiling my project with latest version of Angular. ivy-ngcc postinstall script in package.json seem to be working fine. But it still doesn't recognizing the modules of the app and showing below error:

`ERROR in Unable to write a reference to MyDirective in D:/MyProject/src/app/shared/my-directive/my-directive.directive.ts from D:/MyProject/src/app/shared/my-directive/my-directive.module.ts`

I am following the instructions mentioned in https://next.angular.io/guide/ivy

I thought I could be missing something while updating my existing project. 

So I tried generating a new project using below command:

`ng new temp --enableIvy`

After generating the project I updated Angular to latest version Angular 8.0.0-beta.7.

When running npm install, I can see that after package installation ivy-ngcc postinstall script in package.json seem to be working fine.

But when I tried running the build command `ng build --prod`, it threw below error:

```
ERROR in Unable to write a reference to AppComponent in D:/MyProject/src/app/app.component.ts from D:/MyProject/src/app/app.module.ts
```

## 🔬 Minimal Reproduction

On windows machine generate a new project:

`ng new temp --enableIvy`

Update Angular to latest version i.e. Angular 8.0.0-beta.7

Run `npm install`

Then run `ng build --prod`

## 🔥 Exception or Error
<pre><code>
```
ERROR in Unable to write a reference to AppComponent in D:/MyProject/src/app/app.component.ts from D:/MyProject/src/app/app.module.ts
```

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.0-beta.4
Node: 8.11.4
OS: win32 x64
Angular: 8.0.0-beta.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.14.0-beta.4
@angular-devkit/build-angular     0.14.0-beta.4
@angular-devkit/build-optimizer   0.14.0-beta.4
@angular-devkit/build-webpack     0.14.0-beta.4
@angular-devkit/core              8.0.0-beta.4
@angular-devkit/schematics        8.0.0-beta.4
@angular/cli                      8.0.0-beta.4
@ngtools/webpack                  8.0.0-beta.4
@schematics/angular               8.0.0-beta.4
@schematics/update                0.14.0-beta.4
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.5
</code></pre>

### PR DESCRIPTION
**Pull request by alan-agius4**
tsc `getCurrentDirectory` directory doesn't return a posix separated normalized path. While `rootDir` and `rootDirs` should return posix separated paths, it's best to not assume as other paths within the compiler options can be returned not posix separated such as `basePath`

See: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/sys.ts#L635

This partially fixes #29140, however there needs to be a change in the CLI as well to handle this, as at the moment we are leaking devkit paths which is not correct.

Fixes #29140

### CODE REVIEW

**Comment by naveedahmed1** [comment]
> This partially fixes #29140, however there needs to be a change in the CLI as well to handle this, as at the moment we are leaking devkit paths which is not correct.

@alan-agius4 should I create an issue in Angular CLI repo as well?

**Comment by alan-agius4** [comment]
Let’s keep tracking the issues here.

So there is a single point of reference.

I’ll be doing the CLI soon.

**Comment by alan-agius4** [comment]
CI PR: https://github.com/angular/angular-cli/pull/13848

**Review by mhevery — APPROVED** [review]

**Comment by mhevery** [comment]
LGTM, is it possible to add a test? Or at least a comment

**Comment by alan-agius4** [comment]
@mhevery, comment added, though for a test at the moment, it's a bit redundant since there is no windows ci

**Comment by kara** [comment]
[presubmit](http://test/OCL:237797335:BASE:237797363:1552314282153:25d4c9d6)

**Pull request closed without merging**
