### PR TITLE
refactor(core): Remove unused import from the graph.ts

### PR DESCRIPTION
**Pull request by ChellappanRajan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by AndrewKushnir — COMMENTED** [review]
@ChellappanRajan thanks for the cleanup 👍

The change looks good, but the CI is failing due to a commit message format. Could you please update the commit message (`git commit --amend`) to include a body into the message, for example:

```
refactor(core): Remove unused import from the graph.ts

This commit updates the code to remove unused import of the `throwInvalidWriteToSignalError` symbol.
```

Thank you.

**Comment by ChellappanRajan** [comment]
> @ChellappanRajan thanks for the cleanup 👍
> 
> The change looks good, but the CI is failing due to a commit message format. Could you please update the commit message (`git commit --amend`) to include a body into the message, for example:
> 
> ```
> refactor(core): Remove unused import from the graph.ts
> 
> This commit updates the code to remove unused import of the `throwInvalidWriteToSignalError` symbol.
> ```
> 
> Thank you.

Thanks @AndrewKushnir  I have updated with commit message.

**Review by AndrewKushnir — APPROVED** [review]
@ChellappanRajan thank you!

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 4f5f4969c5bbc1ec9fa8d81480db37ab67114180.

**Pull request closed without merging**
