### PR TITLE
test: clean up more entryComponents usages

### PR DESCRIPTION
**Pull request by crisbeto**
Cleans up some more tests that were using `entryComponents`.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
@crisbeto thanks for the cleanup! 👍

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

**Comment by crisbeto** [comment]
Merge assistance: presubmit isn't necessary.

**Comment by atscott** [comment]
This PR was merged into the repository by commit 359103274bda7f999492822c2e6aa8b7fb9b93fb.

**Pull request closed without merging**
