### PR TITLE
docs: fix typo; remove wrong environment info

### PR DESCRIPTION
**Pull request by dharamgollapudi**

### CODE REVIEW

**Comment by dharamgollapudi** [comment]
I signed it!

**Comment by robwormald** [comment]
@dharamgollapudi thanks for the PR. could you update your commit message to conform to the commit message guidelines here please? https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

**Comment by dharamgollapudi** [comment]
@robwormald updated the commit message

**Comment by mhevery** [comment]
Duplicate of existing change d4565fdaf32d9d109b0b58a781c032f50fa202ab

**Pull request closed without merging**
