### PR TITLE
Revert "refactor(core): improve forwardRef typings (#53880)"

### PR DESCRIPTION
**Pull request by dylhunn**
This reverts commit af6f6e6448edffcd644b0bb6ce155c3ca4270971.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Comment by dylhunn** [comment]
disabling pullapprove -- this is just a rollback, 1 LGTM is fine

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]

**Comment by dylhunn** [comment]
This revert will require a patch-port as well.

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 4fd78a99d29010405264f980920cfeacac41b12c.

**Pull request closed without merging**
