### PR TITLE
docs: add Scully to resources.json

### PR DESCRIPTION
**Pull request by GuzmanPI**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

Adds Scully to the resources.

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]

**Comment by guzmanpi-ubroapps** [comment]
@googlebot I fixed it.

**Comment by guzmanpi-ubroapps** [comment]
@googlebot I consent.

**Comment by guzmanpi-ubroapps** [comment]
@googlebot I fixed it.

**Comment by guzmanpi-ubroapps** [comment]
@googlebot I fixed it.

**Review by IgorMinar — CHANGES_REQUESTED** [review]
Hi @GuzmanPI thanks for the PR, but unfortunately this PR contains lots of unrelated changes. Can you please clean it up & rebase it? thanks!

**Review by IgorMinar — CHANGES_REQUESTED** [review]
hmm.. I'm unsure why the bot re-requested my review. this PR still needs cleanup.

**Review by IgorMinar — CHANGES_REQUESTED** [review]
Hi @GuzmanPI thanks for the PR, but unfortunately this PR contains lots of unrelated changes. Can you please clean it up & rebase it? thanks!

(submitting my review feedback, one more try, this time without the `Reviewed-for: ` marker)

**Review by IgorMinar — CHANGES_REQUESTED** [review]
one last time... sorry about the noise...

Reviewed-for: global-approvers

**Review by IgorMinar — DISMISSED** [review]
Reviewed-for: docs-packaging-and-releasing, docs-cli, docs-libraries, docs-infra, public-api, code-ownership

**Comment by GuzmanPI** [comment]
Thx @IgorMinar I'll do the cleanup and rebase it.

**Comment by jelbourn** [comment]
@GuzmanPI it looks like the author field of your commit changed such that it now doesn't match your GitHub user, which makes the Google CLA bot unhappy

**Comment by GuzmanPI** [comment]
@googlebot I fixed it.

**Comment by guzmanpi-ubroapps** [comment]
@googlebot I fixed it.

**Comment by GuzmanPI** [comment]
Thx @jelbourn I'll check it out

**Review by aikithoughts — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by jelbourn** [comment]
The lint task is failing because the commit description is fewer than 100 characters, but I thought that was disabled for docs PRs

**Comment by GuzmanPI** [comment]
I could change the commit message, so it passes the lint

**Comment by AndrewKushnir** [comment]
Hi @GuzmanPI, could you please try to rebase your PR once again to make sure the branch history contains https://github.com/angular/angular/commit/c5b125b7db50914840849a8d86cbb3304d2f4e68 (which removes the min body length requirements for docs commits)? It also looks like there is an extra commit (`Merge branch 'master' of https://github.com/angular/angular into docs…`) that should not be present, could you please also remove it during the rebase? Thank you.

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by GuzmanPI** [comment]
Thx @AndrewKushnir I'm working on it

**Comment by AndrewKushnir** [comment]
Hi @GuzmanPI, thanks for updating the commit message.

It turned out that there was a typo in the config which prevented the updated check (that excludes `docs` commits from the body length validation) from being executed. The problem should be fixed in https://github.com/angular/angular/pull/37862, so you can either wait for that PR to land and rebase your PR or update the commit message to satisfy the 100 chars min length requirement (commit description is 96 chars now).

Thank you.

**Comment by GuzmanPI** [comment]
Thank you @AndrewKushnir ! I'll wait for #37862 to be merged.

**Comment by AndrewKushnir** [comment]
Merge assistance: it looks like we have approvals from the necessary set of reviewers.

**Pull request closed without merging**
