### PR TITLE
docs: fix broken link on the tutorial page

### PR DESCRIPTION
**Pull request by hozefam**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
The bottom link in the first page of [tutorials/learn-angular/](https://angular.dev/tutorials/learn-angular) is broken.

Issue Number:N/A

## What is the new behavior?
Link redirects correctly to the next page in the tutorial

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by danieljancar** [comment]
Hey @hozefam,
We use semantic versioning and therefore require a certain format for commit messages. For your commit type it would be 'docs: fix broken link on ...'.

**Comment by hozefam** [comment]
> Hey @hozefam, We use semantic versioning and therefore require a certain format for commit messages. For your commit type it would be 'docs: fix broken link on ...'. Please update accordingly, thanks. 😃

Updated

**Comment by danieljancar** [comment]
Hey, nearly there. Your commit message, which you can see [here](https://github.com/angular/angular/pull/54669/commits), also should be changed to the current title. The title doesn't have to be in semantic commit but the actual commit message(s) do. 🚀 
You can find more guide on this topic in the [CONTRIBUTING.md](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format)

**Comment by hozefam** [comment]
> Nearly there, your commit message, which you can see [here](https://github.com/angular/angular/pull/54669/commits), also should be changed to the current title. The title doesn't have to be in semantic commit but the actual commit message(s) do. 🚀 You can find more guide on this topic in the [CONTRIBUTING.md](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format)

Done. Thanks for the clarification.

**Review by JeanMeche — APPROVED** [review]
Thank you for helping us improve angular.dev !

**Pull request closed without merging**
