### PR TITLE
docs(common): fix mistakes in number pipe example

### PR DESCRIPTION
**Pull request by luffySAMA**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by luffySAMA** [comment]
I signed it!

**Review by vicb — APPROVED** [review]

**Comment by vicb** [comment]
- **CARETAKER** please fix the commit title
- circle fails because of the commit message, Travis fails because of the unpinned deps.

**Comment by luffySAMA** [comment]
@vicb Thank you for your suggestion, I have fixed the commit title

**Comment by vicb** [comment]
@luffySAMA the suggestion was actually for the "caretaker" (ie the person responsible for merging this PR) but you've beaten him to it. Thanks.

**Pull request closed without merging**
