### PR TITLE
fix(angular1-router): add missing wrapper methods

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Comment by brandonroberts** [comment]
Can you add the missing charCodeAt function to the StringWrapper also? See https://github.com/angular/angular/issues/6763

**Comment by petebacondarwin** [comment]
Will do

**Comment by petebacondarwin** [comment]
Added

**Comment by brandonroberts** [comment]
:+1:

**Comment by btford** [comment]
LGTM, merge.

**Pull request closed without merging**
