### PR TITLE
fix(router): fix Router's public API for canceledNavigationResolution

### PR DESCRIPTION
**Pull request by atscott**
The commit which made the `canceledNavigationResolution` property on the `Router`
public did not add the corresponding configuration in the `ExtraOptions`.
https://github.com/angular/angular/commit/3c6b653089837459809a370ebcaf8911c3bab9ed
This was a mistake and is being corrected in this commit. We should not
encourage changing the properties post-setup (i.e.
`inject(Router).canceledNavigationResolution = 'computed'`). This manner
of configuration makes the options non-tree shakeable because we have to
keep both implementations in case the value changes at runtime.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]
👍

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

Quick comment: while this change updates public API surface, it does it in a non-breaking way. This is clearly a fix for the API to add a capability to provide `canceledNavigationResolution` config option, which was missing during the initial implementation of the feature.

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

reviewed-for: public-api

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit e79e3cafec33b3681f44a00cc7ef9c9690024ab4.

**Pull request closed without merging**
