### PR TITLE
docs: update ivy opt-in flag

### PR DESCRIPTION
**Pull request by filipesilva**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?
Followup to https://github.com/angular/angular/pull/28569#issuecomment-467380883 and https://github.com/angular/angular-cli/pull/13773.

Note: this flag will only work on `@angular/cli@8.0.0-beta.3` (currently unreleased) and above.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by filipesilva** [comment]
@gkalpak it's odd that this file gets matched for Igor only as a reviewer.

According to the codeowners file this is a bug:
```
# ================================================
#  Default Owners
# (in case no pattern matches a path in a PR - this should be treated as a bug and result in adding the path to CODEOWNERS)
# ================================================

* @IgorMinar @angular/framework-global-approvers
```

It looks like each guide is currently assigned to specific groups. So I guess this guide should also be assigned to some specific group. @IgorMinar I was told you setup this list yourself. Who should be the codeowner for this guide?

**Comment by gkalpak** [comment]
BTW, I have a PR updating CODEOWNERS with missing guides etc: #28597 
Happy to update that (according to @IgorMinar's response :wink:).

**Comment by gkalpak** [comment]
FYI, I've added `ivy.md` to the "Framework/cli integration" CODEOWNERS section (which is owned by the `tools-cli` group) in [#28597#diff-5cfb934ca][1].

[1]: https://github.com/angular/angular/pull/28597/files#diff-5cfb934ca0ec4c1743905a51dc428b84R410

**Comment by filipesilva** [comment]
@gkalpak thanks, I rebased now and it should request a review from that group.

**Comment by filipesilva** [comment]
Hm, no.... it didn't reset the needed reviews... :/

**Comment by alexeagle** [comment]
Caretaker assist: this is just a trivial correction to a CLI flag, doesn't need the listed reviews (and we are having problems with Codeowners on this one)

**Review by hansl — APPROVED** [review]

**Comment by gkalpak** [comment]
> @gkalpak thanks, I rebased now and it should request a review from that group.

@filipesilva, the PR is not merged yet, so the changes will not take effect until it is :grin:

**Pull request closed without merging**
