### PR TITLE
docs: correct section header and text

### PR DESCRIPTION
**Pull request by SeanDemps**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

On Section 4 of Tour of Heroes tutorial, the [last section](https://angular.io/tutorial/toh-pt4#add-messages-to-hero-service) reads "Add messages to hero service" while the code extract demonstrates adding messages to the hero _component_. This PR updates the section header and text to reflect the code.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by pkozlowski-opensource** [comment]
I don't think that this change is correct. The [example in question](https://angular.io/tutorial/toh-pt4#add-messages-to-hero-service) is trying to illustrate the act of adding and reading messages to the `MessageService. Changing "service" to "component" would be misleading. 

Still, this documentation _is_ incorrect as the title mentions the `hero service` while the main main service interacted with is `MessageService`.

**Comment by SeanDemps** [comment]
> 

The code example directly below this section is showing how to add the message service to the heroes component though.

**Comment by JeanMeche** [comment]
I'm going to close this PR, the change has been made in #49208

**Pull request closed without merging**
