### PR TITLE
chore: Add license headers and lint check (#9380)

### PR DESCRIPTION
**Pull request by ScottSWu**
Added a tslint check to make sure all source files begin with a license
header (at the very beginning or after a `#!`).
Automatically added the header to most TypeScript files.

### CODE REVIEW

**Comment by vicb** [comment]
Could you please split tslint and the file update in two commits to ease the review.

Is there a way to automatically add the license header ?

Should the license be jsdoc ?

**Comment by vicb** [comment]
The PR message should contains ‘fixes #9380‘ so that GH automatically closes the issue when the pr gets merged. It should be in the body, usually on the first line. Thanks.

**Comment by ScottSWu** [comment]
Sure, I will split up the updates.

The automatic headers happens within tsc-wrapped, but relies on a forked version of TSLint, which is still being discussed. The forked check is identical to the one here, except that it also provides a fix to add the header).

I'm not sure what format the license text should be in - open to suggestions.

I didn't close the issue yet because this only covers files that were compiled in tsc-wrapped (and linted through gulp-tslint). The headers need to be added to dart and js files as well.

**Comment by vicb** [comment]
> I'm not sure what format the license text should be in - open to suggestions.

IMO it should start with `/*` instead of `/**`

> I didn't close the issue yet because this only covers files that were compiled in tsc-wrapped (and linted through gulp-tslint). The headers need to be added to dart and js files as well.

Then you can say "`relates to #xxxx`" in the body of the commit message.
`(#xxxx)` at the e/o the commit headline usually ref a PR rather than an issue.

**Comment by ScottSWu** [comment]
Got it, thanks!

Should it still have the `@license` tag at the beginning?

**Comment by vicb** [comment]
I would remove the leading `@`

**Comment by alexeagle** [comment]
Actually @vicb I think we should follow the convention that third_party dictates:
```
/**
 * @license
 * Copyright 2008 SomeThirdParty.
 * Here is the full license text and copyright
 * notice for this file. Note that the notice can span several
 * lines and is only terminated by the closing star and slash:
 */
```
see http://go/third-party-javascript#preserve-existing-license-and-copyright-info-with-an-license-tag

**Pull request merged**
