### PR TITLE
refactor(core): rename ngComponentDef to ɵcmp

### PR DESCRIPTION
**Pull request by kara**
Component defs are not considered public API, so the property
that contains them should be prefixed with Angular's marker
for "private" ('ɵ') to discourage apps from relying on def
APIs directly.

This commit adds the prefix and shortens the name from
`ngComponentDef` to `cmp`. This is because property names
cannot be minified by Uglify without turning on property
mangling (which most apps have turned off) and are thus
size-sensitive.

Note that the other "defs" (ngDirectiveDef, etc) will be
prefixed and shortened in follow-up PRs, in an attempt to
limit how large and conflict-y this change is.

### CODE REVIEW

**Comment by kara** [comment]
[VE presubmit](https://test.corp.google.com/ui#id=OCL:274085532:BASE:274085579:1570759103010:7c5bff4b)

[Ivy presubmit](https://test.corp.google.com/ui#id=OCL:274085532:BASE:274085848:1570759232562:820fe8b4)

**Review by mhevery — APPROVED** [review]

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

**Review by IgorMinar — APPROVED** [review]
I was hoping that this would make a dent in the payload size tracking, but it will take a larger app with many more components for this change to make a difference. I'm glad that we are cleaning up the public api though so that people don't depend on the shape of this type!

**Comment by kara** [comment]
@IgorMinar I expect to see a change when factory defs and directive defs are also shortened

**Comment by petebacondarwin** [comment]
Why would it make a difference to a compressed payload?

**Comment by kara** [comment]
@petebacondarwin Minified code would be smaller (which improves parsing time), and that would in turn make the compressed code smaller. The numbers Igor is referring to are the minified numbers in the tracker.

**Comment by petebacondarwin** [comment]
I get that minified would be smaller and yes that makes sense about parsing time.
But the compressed difference is going to be negligible, since `ngComponentDef` and `ɵcmp ` would both likely be mapped to a single token in the compressed file.

**Comment by kara** [comment]
Note: discussed offline. When we say it will improve payload size, we mean minified size (though compressed size should also benefit some).

**Comment by kara** [comment]
merge assistance: Ivy presubmit failures look unrelated to this change

**Pull request closed without merging**
