### PR TITLE
docs(12_zones.md) Change Angular to Angular2

### PR DESCRIPTION
**Pull request by lpww**
For clarity

### CODE REVIEW

**Comment by lpww** [comment]
I signed it!

**Comment by pkozlowski-opensource** [comment]
@naomiblack I guess we should clarify the "official" naming :-) Till now I was under the impression that we use the following naming:
* `AngularJS` = Angular 1.x for JS
* `AngularDart` = Angular 1.x for Dart 
* `Angular` = Angular 2.x for JS / TS / Dart

**Comment by mhevery** [comment]
Since this is Angular 2 documentation, there is no need to add `2` to every mention of angular.

Thanks for your initiative, but I think we will keep our current naming convention.

**Comment by lpww** [comment]
May I then recommend changing 'Angular 2' and 'Angular v2' (both of these names also appear in the document) references to just 'Angular'. It's the inconsistency that was bugging me more than the actual name.

**Pull request closed without merging**
