### PR TITLE
fix(docs-infra): parent max-height IDE error panel visibility

### PR DESCRIPTION
**Pull request by vladboisa**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Was: 
image

Issue Number: #52760

## What is the new behavior?
After adding overflow and max-height in percentage to parent container and, move to the bottom error box,
issue behavior was fixed
image

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, thanks for proposing a fix. 

With your fix, the origin issue still stands, the error message hides the issues (line 17 and 19 aren't visible). 
 
Screenshot 2024-01-28 at 18 47 16

**Comment by vladboisa** [comment]
> Hi, thanks for proposing a fix.
> 
> With your fix, the origin issue still stands, the error message hides the issues (line 17 and 19 aren't visible).
> 

Maybe the best way to remove this error box to the right-side, by removing left: 0.5 rem ?
image

**Comment by twerske** [comment]
We wouldn't want to shift the width, the height should be probably a percent of the box - cc @bencodezen

**Comment by vladboisa** [comment]
> We wouldn't want to shift the width, the height should be probably a percent of the box - cc @bencodezen

So, my solution is fine? Or need to calc the percentage

**Comment by bencodezen** [comment]
@vladboisa Your solution is a good start in terms of not letting the error messages take over too much of the editor.

That said, if the goal is to allow users to fix the errors while the popup is visible, this doesn't fix the issue. 

The additional piece we need on this is to modify the height of the editor so that users can see the errors in question while also seeing the error box.

Screenshot 2024-01-29 at 9 39 04 AM

This is a quick prototype I did by modifying the height of the editor, but I know it'll need more dynamic calculations based on whether the error popup has appeared or not. 

Let me know if you have any additional questions!

**Comment by vladboisa** [comment]
> @vladboisa Your solution is a good start in terms of not letting the error messages take over too much of the editor.
> 
> That said, if the goal is to allow users to fix the errors while the popup is visible, this doesn't fix the issue.
> 
> The additional piece we need on this is to modify the height of the editor so that users can see the errors in question while also seeing the error box.
> 
> This is a quick prototype I did by modifying the height of the editor, but I know it'll need more dynamic calculations based on whether the error popup has appeared or not.
> 
> Let me know if you have any additional questions!

I added the animation, and added a modification to the height of the editor, when the error box is appears

**Comment by vladboisa** [comment]
@bencodezen I have doubts about this solution, in case the editor only shows 1-2 error lines

**Comment by vladboisa** [comment]
> @vladboisa Your solution is a good start in terms of not letting the error messages take over too much of the editor.
> 
> That said, if the goal is to allow users to fix the errors while the popup is visible, this doesn't fix the issue.
> 
> The additional piece we need on this is to modify the height of the editor so that users can see the errors in question while also seeing the error box.
> Let me know if you have any additional questions!

@bencodezen @twerske 
I think now my solution is work's fine.
Thanks for your time and the opportunity to contribute in Angular community.

**Review by JeanMeche — APPROVED** [review]
Thanks for this !

**Comment by vladboisa** [comment]
> Thanks for this ! 
It's pleasure for me ;)
Thanks for your time and the opportunity to contribute in Angular community

**Comment by devversion** [comment]
This PR was merged into the repository by commit 681e1ec3bedc8d1a1ab4a940766e14e0e7e36fc1.

The changes were merged into the following branches: main, 18.2.x

**Pull request closed without merging**
