### PR TITLE
docs: fix typo in elements guide

### PR DESCRIPTION
**Pull request by volunux**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by volunux** [comment]
@googlebot I signed it!

**Comment by kapunahelewong** [comment]
Thanks for this PR, @volunux. Could you amend your commit message to the following:

```
docs: fix typo in elements guide
```

Please text me when you're ready.

**Comment by volunux** [comment]
I almost did but you did. Sorry for the lateness.

Internet connectivity is poor sometimes.

**Comment by kapunahelewong** [comment]
Your timeframe is just right, @volunux. 🙂I've rebased and amended the commit message for you (which is different from the title of the PR that I had indeed changed before). Could you double check that you signed CLA and that it was signed with the correct email? It looks like you tried but maybe it didn't pick it up. Once the CLA is happy, I think we'll be able to move forward. Please let me know if you have any questions. Thank you!

**Comment by volunux** [comment]
@googlebot I signed it!

**Comment by volunux** [comment]
I have already signed previously. I wanted to sign again but it says I
have signed already.

**Comment by kapunahelewong** [comment]
Hm, I'm labeling this for Engineering input so someone can help us out. Thank you, @volunux. :)

**Review by aikithoughts — APPROVED** [review]

**Comment by volunux** [comment]
Thank you.

**Comment by gkalpak** [comment]
Sorry we didn't get to this sooner, @volunux 😞
In the meantine, this seems to have been fixed by #37966.

**Pull request closed without merging**
