### PR TITLE
docs: fix typo from singular to plural spelling

### PR DESCRIPTION
**Pull request by boazrymland**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by kapunahelewong — CHANGES_REQUESTED** [review]
Good catch, @boazrymland! To get this passing, we just need to make sure the commit message meets the requirements. It should be like this:

```
docs: fix typo from singular to plural spelling

This commit fixes the spelling of the singular form of the word function to the plural spelling in packages/core/src/application_init.ts 

```


Here are my notes on [amending commits](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) and [rebasing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash), but if you need help with anything just let me know and I can help from this end.

Thank you!

**Comment by boazrymland** [comment]
@kapunahelewong thanks for suggesting assistance - I need it: I cloned the repo to my laptop but how the heck do I get the branch name? I think there's a prefix here with my username but I can't seem to simply get the branch name :-)

**Comment by petebacondarwin** [comment]
@boazrymland - can you check with repository you cloned? Was it your fork or the main Angular one?
I.E. did you run:

```sh
git clone https://github.com/boazrymland/angular
```

```sh
git clone https://github.com/angular/angular
```

If it was the second one then you probably need to add your own fork as a remote, for example:

```sh
git remote add boazrymland https://github.com/boazrymland/angular
```

Then you should be able to fetch the branch from that remote and switch to it:

```sh
git fetch boazrymland
git checkout patch-2
```

By the way you'll see that this file has been changed since you created your PR, but I think there is still an issue with the plural of `function` so still work fixing. Since it is such a small change it might be worth just checking out the angular/angular master and creating a new PR?

**Comment by kapunahelewong** [comment]
@boazrymland were you able to get it working with Pete's notes? If there are still issues, would you like me to try from this end?

**Comment by boazrymland** [comment]
> @boazrymland were you able to get it working with Pete's notes? If there are still issues, would you like me to try from this end?

@kapunahelewong apologize for my lack of responsiveness - we have a release at the office and I didn't have time to deal with this. I'll try (hopefully this weekend) and update.

**Comment by kapunahelewong** [comment]
It's ok, @boazrymland! We're on your timeline. Just know that we're here to help when you're ready. Good luck with the release!!

**Comment by boazrymland** [comment]
@kapunahelewong can you check now please?

**Comment by kapunahelewong** [comment]
Hi @boazrymland! It looks as though you already fixed this in https://github.com/angular/angular/pull/36586/commits/7f6247f15f06b94e0b9d4310145866649d79d379. When you reversed it showed that there were no changes now in this PR, which it first confused me but I think this is why. Should we close this one now? Thank you very much for your help in fixing this issue!

**Comment by boazrymland** [comment]
> Hi @boazrymland! It looks as though you already fixed this in [7f6247f](https://github.com/angular/angular/commit/7f6247f15f06b94e0b9d4310145866649d79d379). When you reversed it showed that there were no changes now in this PR, which it first confused me but I think this is why. Should we close this one now? Thank you very much for your help in fixing this issue!

No problem closing but was this introduced to master? Need I create another PR for this (tiny) change to be merged to master?

**Comment by kapunahelewong** [comment]
Never mind, @boazrymland. I got confused! The diff showed no changes, yet the issue was still there in master. Then I mistook the GitHub UI as saying that it had been merged into `angular/angular`. Anyway, I rebased and moved your changes into the current copy that is in that document. Part of the issue was that paragraph had been rewritten since your PR was submitted. Since the error was still there though, I just moved your correction into the new copy during the rebase. My apologies for the confusion. 

Now we just have to get it passing all the tests (I'll take care of that part for you) so we can merge it. Thanks a lot for working with me, @boazrymland!

**Comment by boazrymland** [comment]
@kapunahelewong sure thing. Thanks for your generous help!

**Comment by boazrymland** [comment]
where do i do this CLA signing?
I went [here](https://cla.developers.google.com/clas) and signed again (with same email I use to login to github)

**Review by kapunahelewong — APPROVED** [review]
LGTM! Thank you so very much, @boazrymland!

Reviewed-for: global-docs-approvers

**Pull request closed without merging**
