### PR TITLE
Amend inaccurate immutability definition

### PR DESCRIPTION
**Pull request by JoelLefkowitz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Immutability is being defined as "The ability to alter the state of a value after its creation."

Issue Number: N/A

## What is the new behavior?

Immutability should be defined as  "The inability to alter the state of a value after its creation."

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by petebacondarwin** [comment]
Thanks @JoelLefkowitz - I just noticed that the commit message is slightly inaccurate. It should be just `docs: ...` since `docs(docs-infra): ...` corresponds to docs about the docs infrastructure, such as the documentation generation or the angular.io website app.

If you get a moment could you amend that?

Otherwise I think this is good to go. Thank you for improving our documentation.

**Comment by JoelLefkowitz** [comment]
> Thanks @JoelLefkowitz - I just noticed that the commit message is slightly inaccurate. It should be just `docs: ...` since `docs(docs-infra): ...` corresponds to docs about the docs infrastructure, such as the documentation generation or the angular.io website app.
> 
> If you get a moment could you amend that?
> 
> Otherwise I think this is good to go. Thank you for improving our documentation.

Updated the message, thanks for spotting.

**Comment by atscott** [comment]
This PR was merged into the repository by commit ab423f5ee960d746b6b009b6f5c044035aa95802.

**Pull request closed without merging**
