### PR TITLE
docs: remove all references to Angular Console

### PR DESCRIPTION
**Pull request by Windvis**
Angular Console has been renamed and links no longer work. It has been decided to remove references to this third-party tool from the AIO documentation.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #37604

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by StephenFluin** [comment]
The product still exists. I recommend we just rename it to NX console in our listing.

**Comment by StephenFluin** [comment]
I'm not actually certain whether or not NX console requires nodeJS to be installed. If it does, then this recommend doesn't save users any work and it should be removed.

**Comment by Windvis** [comment]
[It looks like Node.js is required](https://nx.dev/angular/tutorial/01-create-application).

Apparently there is another reference to Angular Console in the docs (#37609). Should I remove that as well and update this MR?

**Comment by gkalpak** [comment]
@StephenFluin, my main consern is that "Nx Console" is no longer a standalone app; it is a VSCode extension. So, it is only useful for people using VSCode. (Plus it is a UI for the nx cli and I am not sure what this means for Angular CLI apps.)

**Comment by StephenFluin** [comment]
Removal everywhere sounds great to me. it cannot function in the original
way it was intended to in our documentation.

**Comment by Windvis** [comment]
I removed all the references I could find. Let me know if I need to reword anything, since English isn't my native language.

**Comment by Windvis** [comment]
It looks like the commit body isn't long enough, but I'm not sure what information I should add to reach that minimum requirement.

**Comment by jbogarthyde** [comment]
A reference needs to be removed from the CLI Overview, `aio/content/cli/index.md` -- see https://github.com/angular/angular/pull/37613

**Comment by Windvis** [comment]
@jbogarthyde I think I already removed that reference? Or did I miss something else on that page?

**Review by jbogarthyde — APPROVED** [review]
Thanks, that looks like all the references I know about.
BTW, this is not actually (docs-infra)  -- it is just doc content. You can use the second line of the commit message to add a long-winded description, up to the required 100 characters.
Perhaps: 
"docs: remove references to Angular Console

Angular Console has been renamed and the links no longer work. It has been decided to remove references to this third-party tool from the AIO documentation."

(Note the blank link between the short and long part of the commit message.)

**Comment by Windvis** [comment]
@jbogarthyde I updated the commit subject line and body according to your message. Should be ok now!

**Review by clydin — APPROVED** [review]

**Review by sonukapoor — APPROVED** [review]

**Review by StephenFluin — APPROVED** [review]

**Pull request closed without merging**
