### PR TITLE
docs: fix email field name

### PR DESCRIPTION
**Pull request by Vergil333**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe: fix name in code snippet

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sonukapoor** [comment]
Thank you for fixing this @Vergil333. Can you please amend the commit message to: `docs: fix email field name` and also accept the CLA?

**Comment by Vergil333** [comment]
> Thank you for fixing this @Vergil333. Can you please amend the commit message to: `docs: fix email field name` and also accept the CLA?

Done, should be fine now 👌

**Comment by sonukapoor** [comment]
@Vergil333 My bad. I didn't see that there was also a code change. In that case, your 2 commits were fine. Can you do the following:

1. Modify the current code commit and add a body to the message. That is required for the linter to pass. 
2. Add the doc commit back with the commit message you are using for the current commit.

**Comment by sonukapoor** [comment]
Ah - Sorry for the confusion on my end. No, don't do that. Keep them separate.  You can just change the commit message for this one to: This will hopefully pass the linter. 

```
fix: fix input name

This commit fixes the name of the input used for the email. 
```

**Comment by Vergil333** [comment]
@sonukapoor thank you for guidance, it's done :)

**Review by sonukapoor — APPROVED** [review]
Awesome 🥳 Good work 👍 

I would also set the title of this PR to match the commit title.

**Comment by JeanMeche** [comment]
@sonukapoor It should be the other way around ;) 

Could you please reword your commit to  `docs:  ...` as fix commit are mentionned in the changelog and this is not really a bugfix. Thank you.

**Comment by Vergil333** [comment]
@JeanMeche sure, it's not worth mentioning it in changelog 😁 Commit reworded

**Review by JeanMeche — APPROVED** [review]
LGTM, thank you for help us improve the docs !

**Comment by atscott** [comment]
This PR was merged into the repository by commit bc394de75aac553a11953f3d46eb972b5dc0a1f9.

**Pull request closed without merging**
