### PR TITLE
docs: add angular-in-depth to community curations

### PR DESCRIPTION
**Pull request by snehalbaghel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31167 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by santoshyadav198613** [comment]
Thanks @snehalbaghel for PR.

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong , can you assign this to someone for review.

**Review by StephenFluin — APPROVED** [review]

**Comment by santoshyadav198613** [comment]
Thanks @StephenFluin .

**Comment by santoshyadav198613** [comment]
Hi @kapunahelewong ,

can someone run the build and merge this.

**Comment by kapunahelewong** [comment]
Hey @santoshyadav198613 once everything is ready/green, we can add the `PR action: merge` label (as @gkalpak did), but there isn't an extra build step. 🎉 The closest thing would be the tests that run and that happens automatically when you push up. Hope this helps with transparency of the process. Thanks so much for your contributions. 😊

**Comment by santoshyadav198613** [comment]
Hi @snehalbaghel ,

Is it possible for you to merge the latest changes and push again.

**Comment by snehalbaghel** [comment]
@santoshyadav198613  Sorry my laptop was broken. I've merged upstream.

**Pull request closed without merging**
