### PR TITLE
docs: typo in Deployment section of getting started

### PR DESCRIPTION
**Pull request by ShubhrankR**
rename 'pane' to 'page' for better understanding among people

issue: 34400

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 34400

## What is the new behavior?
The 'pane' mentioned in the second line of the "Share Application" area in the "Deployment" page of the "Getting Started" section of the docs, might confuse non-native English speakers with the intent of the actual word. Therefore, updated it to 'page'.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Review by kapunahelewong — APPROVED** [review]
Very nice, thank you, @ShubhrankR!!

merge-assistance: Global approval for this docs-only change.

**Comment by ajitsinghkaler** [comment]
@kapunahelewong he has not referenced the issue it should be Fixes #34400 instead of issue 34400. @ShubhrankR Please change the commit message

**Comment by kapunahelewong** [comment]
Oh, thank you, @ajitsinghkaler! @ShubhrankR, you just have to [amend your commit](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) to be:

```
docs: typo in Deployment section of getting started

Fixes #34400 
```

Will you tag me when you're ready or if you have any questions? Thank you!!

**Comment by ShubhrankR** [comment]
@ajitsinghkaler Thanks for the check :)
@kapunahelewong Hi! I have made some changes and pushed them. Please check it and let me know.
Thanks!

**Comment by ajitsinghkaler** [comment]
@ShubhrankR you have to squash all your commits into one commit

**Comment by ShubhrankR** [comment]
Hi! @ajitsinghkaler @kapunahelewong 
I have merged my commits. Please look into it.
Thanks :)

**Comment by kapunahelewong** [comment]
Looks great! Thank you!

**Comment by kapunahelewong** [comment]
merge-assistance: Global approval for this docs-only change.

**Pull request closed without merging**
