### PR TITLE
docs(docs-infra): add version information element to the header

### PR DESCRIPTION
**Pull request by ferrorenan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently we do not have the current version available in the header for easy and quick viewing, we only have it in the footer.

Issue Number: [51548](https://github.com/angular/angular/issues/51548)

## What is the new behavior?
Add a new element in the header informing the current version, to make it easier for the user to quickly and easily view the current version available.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
The proposed solution work unfortunately. If you check the dom (the `ng-version` attribute) you'll see that angular.io uses currently a version 16.2.0 but the latest version is 16.2.5.

**Comment by ferrorenan** [comment]
Hey @pkozlowski-opensource @JeanMeche 

Do I need to do something else or just wait for approval?!

**Comment by H-dymitr** [comment]
@ferrorenan Hi, check commit message('version' is not an allowed scope.)

**Comment by ferrorenan** [comment]
@H-dymitr Yes, it's was wrong. I adjusted it, now just wait, thank you!

**Comment by ferrorenan** [comment]
Hey @AndrewKushnir 

Could you take a look so we can see what's missing and finalize this PR?

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev and suggestions shoud go toward the new site. 

Feel free to drop any PR for improvements on the new doc site, thank you.

**Pull request closed without merging**
