### PR TITLE
style(global): group multiple imports from same module

### LINKED ISSUE #7802: code style: multiple imports allowed from same module
We have a handful of files which do this:
```
import {a,b} from 'angular2/module';
...
import {c} from 'angular2/module';
```

Ideally we should tidy this up.
It also affects downstream tooling (see b/27877430 for motivation)

### PR DESCRIPTION
**Pull request by alexcastillo**
- **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  Only code style changes
- **What is the current behavior?** (You can also link to an open issue here)
  #7802
- **What is the new behavior (if this is a feature change)?**
  No
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
  No
- **Other information**:
  ✌️ 

Closes #7802

cc @alexeagle

### CODE REVIEW

**Comment by alexeagle** [comment]
Oops! I forgot I already wrote a fix for this but was waiting for a different PR to land first. It did, and I didn't come back to this one.

The issue is actually worded inaccurately. The root problem here is not the current imports, but that it is possible for developers to continue introducing more duplication. If the root problem remains, then after merging this PR we will soon be back in the same state.

See my PR https://github.com/angular/angular/pull/7859#issuecomment-208162645 for this.

Alternatively, @mprobst was working on organizing imports in clang-format as indicated in that comment.

Either way I'd prefer to add the enforcement mechanism at the same time we clean up the existing duplication.

**Comment by alexcastillo** [comment]
@alexeagle 

Got it. Feel free to close this PR if it doesn't apply anymore.

**Comment by mprobst** [comment]
It'll take a while to add import sorting to `clang-format`.

**Comment by alexcastillo** [comment]
Do we want to get this merged in the meantime, then?

**Comment by alexeagle** [comment]
Sure, this is still an improvement. Thanks for contributing!

**Comment by rkirov** [comment]
doesn't apply cleanly on g3_v2_0, merging to master only.

**Comment by rkirov** [comment]
merge conflict https://travis-ci.org/angular/angular/builds/125715456, you need to rebase on top of master

**Comment by alexcastillo** [comment]
@rkirov rebased!

**Pull request closed without merging**
