### PR TITLE
fix(platform-server): append TransferState earlier in the body

### LINKED ISSUE #20484: Avoid having to put the client bootstrap in DOMContentLoaded for TransferState to work properly
Currently the client of a SSR Angular app needs to wait for DOMContentLoaded to complete before bootstrapping so that TransferState can reliably get the contents of the transferred state from the DOM.

Need to investigate whether we can handle this more transparently without the user needing to bootstrap in a specific way on the client side.

### PR DESCRIPTION
**Pull request by CaerusKaru**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #20484

## What is the new behavior?

Appends the TransferState script object ahead of the script tags in the body to avoid the race condition at bootstrap.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

Fixes #20484 

cc @vikerman

### CODE REVIEW

**Comment by CaerusKaru** [comment]
Build failures seem unrelated to this PR (aio and e2e timeout)

**Comment by Toxicable** [comment]
The issue with doing this is that it will be render blocking for Universal content, which can be especially detrimental large json objects that need to be parsed

**Comment by CaerusKaru** [comment]
@Toxicable Excellent point. Changed it to insert before any script tags lingering in the body (which is where best practices dictate Angular scripts should go -- though this isn't guaranteed).

**Comment by Toxicable** [comment]
We have talked about this internally and this is one of the options that came up.
However the issue with this one is that it relies on the ordering of the script tag which is very fragile and could be broken by script re-ordering if some post process was done on the file, which can be common when working with other frameworks.
The ideal solution would be to handle this internally, making the get method async in some way, or delay the app bootstrapping via APP_INITIALIZER but either option here also has it's draw backs.

**Comment by CaerusKaru** [comment]
@Toxicable That's a great point, and one that I also considered, but it seems that this solution is ideal for two reasons. (1) I think the whole point of TransferState is so that SSR handles _all_ initial loading, so that when the client finally bootstraps, it's immediately ready, with no further waiting, and (2) this solution seems to fit the highest number of use cases (namely those not using other frameworks, and using the CLI to build their apps), and the DOMContentLoaded strategy exists to satisfy the remaining use cases (which is a small compromise considering that they would be operating outside the norm).

I'd be happy to change this PR if the thinking changes, but this was my motivation.

**Comment by CaerusKaru** [comment]
Closing this since it looks like the better solution is to hijack the app initialization process and delay it internally.

**Pull request closed without merging**
