### PR TITLE
build: depend on bazelisk rather than directly on Bazel

### PR DESCRIPTION
**Pull request by gregmagolan**
Based off of @alexeagle's PR https://github.com/angular/angular/pull/35153

This has a couple benefits:
- we now use a .bazelversion file rather than package.json to pin the version of bazel we want. This means even if you install bazel on your computer rather than via yarn, you'll still get a warning if your bazel version is wrong.
- you no longer end up downloading three copies of bazel due to bugs in both npm and yarn where they download all tarballs before checking the metadata to see which are usable on the local platform.
- bazelisk correctly handles the tools/bazel trick for wrapping functionality, which we want to use to instrument developer build latencies

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gregmagolan** [comment]
Updating to Bazel 2.2.0 and bazel_toolchains 2.2.0 produces
```
ERROR: An error occurred during the fetch of repository 'rbe_ubuntu1604_angular':
   Traceback (most recent call last):
	File "/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/external/bazel_toolchains/rules/rbe_repo.bzl", line 505
		validate_host(ctx)
	File "/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/external/bazel_toolchains/rules/rbe_repo/util.bzl", line 161, in validate_host
		fail(<2 more arguments>)
attribute Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
: Cannot run rbe_autoconfig as running '%s ps' returned a non 0 exit code, please check you have permissions to run docker. Error message: /usr/bin/docker
ERROR: /home/circleci/ng/tools/BUILD.bazel:16:1: //tools:rbe_ubuntu1604-angular depends on @rbe_ubuntu1604_angular//config:platform in repository @rbe_ubuntu1604_angular which failed to fetch. no such package '@rbe_ubuntu1604_angular//config': Traceback (most recent call last):
	File "/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/external/bazel_toolchains/rules/rbe_repo.bzl", line 505
		validate_host(ctx)
	File "/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/external/bazel_toolchains/rules/rbe_repo/util.bzl", line 161, in validate_host
		fail(<2 more arguments>)
attribute Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
: Cannot run rbe_autoconfig as running '%s ps' returned a non 0 exit code, please check you have permissions to run docker. Error message: /usr/bin/docker
ERROR: While resolving toolchains for target //modules/e2e_util:e2e_util: Target //tools:rbe_ubuntu1604-angular was referenced as a platform, but does not provide PlatformInfo
ERROR: Analysis of target '//modules/e2e_util:e2e_util_es5' failed; build aborted: Analysis failed
```
Which I've seen before when I first tried out 2.0.0 but it was fixed in a subsequent toolchain patch version.
Pinning bazel to 2.1.1 for now.

**Review by josephperrott — COMMENTED** [review]
LGTM, thanks for picking this up!

**Review by josephperrott — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
Hi @gregmagolan, would it make sense to run Windows CI jobs for these changes as well (like you did for other PRs)? Thank you.

**Comment by gregmagolan** [comment]
Yes it would. I'll make a PR.

**Comment by gregmagolan** [comment]
Windows CI running here: https://github.com/angular/angular/pull/36088

**Comment by AndrewKushnir** [comment]
Thanks @gregmagolan! 👍 I'll put the "blocked" label on this PR for now, feel free to remove it once Windows CI is completed successfully. Thank you.

**Comment by gregmagolan** [comment]
Thanks @AndrewKushnir . Windows CI green https://github.com/angular/angular/pull/36088.

**Comment by AndrewKushnir** [comment]
Thanks @gregmagolan 👍 I've just merged this PR into master (according to the `PR target` label). Do we need this change in patch branch as well or no?

**Comment by gregmagolan** [comment]
No. Patch branch is behind on Bazel changes due to an incompat with ts_library so only master until the next patch branch.

**Pull request closed without merging**
