### PR TITLE
Convert change detection unit tests to typescript

### PR DESCRIPTION
**Pull request by jeffbcross**
TODO:
- [ ] Split into logical commits

### CODE REVIEW

**Comment by jeffbcross** [comment]
@tbosch the previous issue with transpilation was that the "replace" pattern in node-tree was looking for "use-strict" at the top of the transpiled file, which traceur added, but TypeScript does not. Apparently the change_detection tests are the first transpiled library that require this module, so the fact that other tests did not have this patch went unnoticed.

https://github.com/angular/angular/blob/master/tools/broccoli/trees/node_tree.ts#L126

**Comment by mhevery** [comment]
I don'

**Comment by jeffbcross** [comment]
@mhevery SGTM, thanks.

**Comment by jeffbcross** [comment]
Merged at 9d9012846350fa23eaae42cb6d613fca69c94666

**Pull request closed without merging**
