### PR TITLE
build: upgrade `@types/jasminewd2` to 2.0.4

### PR DESCRIPTION
**Pull request by gkalpak**
This commit also removes the extra jasminewd2 typings, since the changes have been merged in the official typings with DefinitelyTyped/DefinitelyTyped#28957.

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
please rebase

**Comment by gkalpak** [comment]
@IgorMinar, rebased. I'm marking this for merge.

Note to caretaker: Requires g3 sync (unless it does not affect g3 - not sure).

**Comment by mhevery** [comment]
http://test/OCL:216871505:BASE:216871515:1539360655169:c4bc1da1

**Comment by mhevery** [comment]
@gkalpak This PR did not cleanly rebase on patch branch. Please create a separate PR for patch branch.

**Comment by gkalpak** [comment]
PR: #26432

**Pull request closed without merging**
