### PR TITLE
doc(directive): fixes incorrect example code

### PR DESCRIPTION
**Pull request by ipinak**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
- [x] Other... Please describe:
  The documentation of the directive was incorrect.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ipinak** [comment]
I signed it!

**Comment by vicb** [comment]
The commit author is set to `ioannis.pinakoulakis [[ at ]] betssongroup.com`, have you signed the CLA with this email ?

**Comment by ipinak** [comment]
No, I will fix it. Can you remove the previous comment to avoid spam?

**Comment by ipinak** [comment]
Should I close this PR and open a new one or change it?

**Comment by ipinak** [comment]
I signed it!

**Comment by vicb** [comment]
Changing it is fine

**Comment by ipinak** [comment]
I signed it!

**Comment by ipinak** [comment]
@vicb it seems that the CLA bot does not catch the "I signed it!" comment. Do I need to do something else?

**Comment by vicb** [comment]
You probably haven't signed the CLA with the correct email

**Comment by ipinak** [comment]
I signed it!

**Pull request merged**
