### PR TITLE
Initial implementation of `output()`

### PR DESCRIPTION
**Pull request by devversion**
This PR introduces the `output()` function. The function can be used to declare directive/component
outputs without the use of decorators. This allows for a more consistent and intuitive experience with
signal inputs, queries or upcoming model.

E.g.

```ts
class MyDir {
  firstName = input.required<string>();
  userChanged = output(); // OutputEmitter<void>

  bla() {
    this.userChanged.emit();
  }
}
```

**Note:** This PR is the initial implementation, laying the groundwork for output(). Points discussed below are not decided at all, and just additional considerations at this point

Current *idea of design* will return an `OutputEmitter` instead of an `EventEmitter` with the goals of:

* abstracting away RxJS and additional complexity introduced by `EventEmitter` implementing a `Subject`.
* improving the `.emit` signature. `EventEmitter#emit` currently takes `T`, but also can be called without a value. This is confusing and might cause subtle bugs (see for example: https://stackblitz.com/edit/stackblitz-starters-bvs1rn?file=src%2Fmain.ts)

An additional consideration is to not expose `.subscribe` publicly. Conceptually aligning with signal inputs,
where you can only write to outputs, while subscription is only possible for consumers via the template. A difficult question will be dynamically created components as those currently have no way to subscribe, unlike with signal inputs where users could reach for `ComponentRef#setInput`. This is something to explore. 

**Note**: We are still discussing design more closely and incorporating feedback from the RFC. This PR introduces the initial logic that we can re-use for changes we are making as part finalizing/discussing design.

### CODE REVIEW

**Comment by manfredsteyer** [comment]
#my2cents about dynamic component:
Similar to ComponentRef#setInput we could provide sth like ComponentRef#registerOutput

**Comment by alex-okrushko** [comment]
I think I'd prefer `output` to be able to take a signal, maybe similar to `computed`.

This would help to tie it to the state management parts, where a signal is computed within it and is provided to a component.

This would be similar to how an Observable is created today and then annotated with `@Output`.

If we stick with only `emit()` then I'd have to be passing this output property into state management, which would tighter couple things.

**Comment by devversion** [comment]
A signal would always require a value. I.e. we would need to have an initial value for outputs. I was also considering signals/computed and effects for programmatic "subscriptions", but at this point- I don't know if those are suitable.

These things are still subject to change. As noted, the PR is just laying the initial detection w/ some basic code for now, re-using `EventEmitter` with a more limited API surface. This is all useful feedback though, so keep it coming!

**Review by crisbeto — APPROVED** [review]

**Comment by jperezruiz** [comment]
Question here, why is `subscribe` hidden to the template only? It is very worth being able subscribing to an output from typescript. We use it for example when connecting components, we query a child with `ContentChild` and subscribe to the child's output.

**Comment by devversion** [comment]
Note: No need for Alex' review as we just added unit tests for language-service + an integration test (both groups pending)

**Pull request closed without merging**
