### PR TITLE
aio: more template refactoring

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Comment by sjtrimble** [comment]
@petebacondarwin We wouldn't want the copy button on these API code examples, right?

**Comment by petebacondarwin** [comment]
@sjtrimble - when you say code examples, what are you referring to?

I think you are right if you mean the tiny snippets that are generated for listing the API parts. But the examples that appear within the content, via triple-backticks or `{@example ...}/<code-example>` tags would expect to have copy buttons, IMO.

Having spent some time playing with this over the weekend I am a bit lost with where the templates are going. The mocks that Igor provided don't make much sense to me, in term of the information architecture.

I am happy to drop one or more of the commits from this PR. I purposefully tried to make each small, focussed and independent as I realised that I was making things up to a large extent.

I think the most effective approach would be to sit down with one or more of the stakeholders (say @IgorMinar and/or @juleskremer) and build up the templates for each document type in person.

The other alternative is to create an exact replica of the layout and information architecture for API docs in the current angular.io as a starting point to get us to a state where we can release, then iterate from there.

**Review by Foxandxss — COMMENTED** [review]
I don't know enough of dgeni but looks good.

**Comment by sjtrimble** [comment]
@petebacondarwin If you look at the member details for the NoopAnimationPlayer class, for example (https://pr16444-3b83f0f3fb032013afa7fbf1d61adfafe11c52d5.ngbuilds.io/api/animations/NoopAnimationPlayer), I'm not sure it adds value to provide a copy button for that. What do you think?

**Review by sjtrimble — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Right. We should make these `<code-example>` unless there is a way to turn off the copy button

**Comment by petebacondarwin** [comment]
BTW this layout is just wrong :-)
screen shot 2017-05-01 at 18 38 41

**Comment by sjtrimble** [comment]
@petebacondarwin Yes, I had a PR in place to make the table pretty based on the designs/info models that were shared with me, but @IgorMinar mentioned this should not be in a table so I will undo this separately. In summary, agreed on the format/layout being ugly and wrong :)

The copy-button is part of the aio-code template. We might need to have two separate templates based on if we want the copy button or not.

**Comment by petebacondarwin** [comment]
Check out the interface "overview". This is similar to what we had before and I think it is much more usable than the table.  https://pr16444-3b83f0f3fb032013afa7fbf1d61adfafe11c52d5.ngbuilds.io/api/forms/ControlValueAccessor

All the members are clickable and take you through to the detail for that member.

I think we should use the same idea for classes (and other things with members).

screen shot 2017-05-01 at 19 23 14

**Comment by sjtrimble** [comment]
Yes 100% - this is exactly what @IgorMinar wanted (to my understanding, as of April 27th) and makes much more sense now that I understand what the page is trying to accomplish (had a tutor session over the weekend from Mr. Fluin).

**Comment by petebacondarwin** [comment]
Closing in favour of another branch (yet to be pushed)

**Pull request closed without merging**
