### PR TITLE
build: remove legacy e2e tests job

### PR DESCRIPTION
**Pull request by devversion**
See individual commits for changes 

<sup>Though most lack of commit descriptions as there is not too much to write about..</sup>

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
thanks!

**Comment by IgorMinar** [comment]
http://test/OCL:233686636:BASE:233686675:1550036012078:3eae8642

**Comment by IgorMinar** [comment]
merge-assistance: the bot seems confused. this pr should be green.

**Comment by mhevery** [comment]
This PR does not apply cleanly to patch brach. Pleas break this up into a master PR and batch PR and ping for re-merge.

**Comment by devversion** [comment]
Here is the patch version of this PR: https://github.com/angular/angular/pull/28697

**Pull request closed without merging**
