### PR TITLE
docs: Handle binary images in examples

### LINKED ISSUE #50647: assets/example-house.jpg is missing from live and download examples
### Describe the problem that you experienced

In lesson 4, step 3 (https://angular.io/tutorial/first-app/first-app-lesson-04#step-3---create-a-test-house-for-your-app), a stub HousingLocation object is created with a photo attribute of 'assets/example-house.jpg'.

This attribute is used in lesson 7, but the image it refers to isn't in either the live or downloaded example.

### Enter the URL of the topic with the problem

https://angular.io/tutorial/first-app/first-app-lesson-07

### Describe what you were looking for in the documentation

A copy of the image to save in my local repo.

### Describe the actions that led you to experience the problem

Following the tutorial (see description).

### Describe what you want to experience that would fix the problem

Include example-house.jpg in the .zip for each step and in the StackBlitz environments.

### Add a screenshot if that helps illustrate the problem

lesson-7

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by JeanMeche**
Stackblitz doesn't not support sending binary files when we create the projects on the fly. 
Binary images are now hosted on aio, this commit adds an error when binary images are added to the example bundles. 

## PR Type
What kind of change does this PR introduce?

- [x] angular.io application / infrastructure changes

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM, but will want eyes from @MarkTechson.

**Review by jessicajaniuk — CHANGES_REQUESTED** [review]
After a bit more review, it looks like these SVG files are a significant increase in file size and that's a bit of a blocking problem. I think we'll need to revisit this and find a different solution.

**Review by MarkTechson — APPROVED** [review]
This is a good check to have. LGTM.

**Comment by JeanMeche** [comment]
@MarkTechson Since the change is breaking right now, I'll wait for your changes (the hosted images) to land to reopen this PR !

**Comment by JeanMeche** [comment]
Waiting for  to land : 
* #51014

**Review by jessicajaniuk — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 957541d5503a31cf975104847872b3918c51aabd.

**Pull request closed without merging**
