### PR TITLE
refactor: rewrite private export using the ɵ prefix

### PR DESCRIPTION
**Pull request by mhevery**

### CODE REVIEW

**Comment by mhevery** [comment]
@jasonaden Has taken over this PR as part of his mega-bundle

**Comment by vicb** [comment]
Could we use :key: instead of "ɵ"

**Comment by mhevery** [comment]
We could use any Unicode char. Chuck wanted a char which is in the lower
code.

**Comment by mhevery** [comment]
Thus is a private API. So we can change this at any time.

**Comment by chuckjaz** [comment]
There are several advantages to ɵ over 🔑:
1) Its UTF-8 encoding is smaller (2 bytes C9 B5) instead of 4 (F0 9F 94 91).
1) Its UTF-16 encoding is one code unit (0x0275) instead of two (0xD83D 0xDD11). That is because it is in the Unicode base plane where 🔑 is not.
1) Its code point's category is Ll (lower-case letter) instead of So (Other symbol) making it much more likely to be correctly treated as a identifier in JavaScript lexers (Ll is explicitly marked as having Unicode property ID_Start where it is unclear if 🔑 does).
1) It kind of looks like a no-entry sign (if you squint a bit and have the right font).

**Comment by DzmitryShylovich** [comment]
@mhevery btw I think it would be nice to add a note about this change somewhere that classes with `ɵ` are private and shouldn't be used by users. Because I already saw a suggestion to import `ɵgetDOM` for dom manipulations somewhere on github.

**Pull request closed without merging**
