### PR TITLE
Resolve differences between dev-infra files in master and patch

### PR DESCRIPTION
**Pull request by josephperrott**
After this PR, the dev-infra related files in master and patch should be identical.

See individual commits.

### CODE REVIEW

**Review by devversion — COMMENTED** [review]
Thanks for doing this!!

Did you consider using the actual commits from `master` so that it's easier to review/ see changes in the patch branch? Also looks like CI is red.

**Review by devversion — APPROVED** [review]

**Comment by devversion** [comment]
@googlebot Ping.

**Comment by devversion** [comment]
lol that was unexpected🤦‍♂️ I was hoping it would just refresh the failing Github status after the manual label override.

**Comment by devversion** [comment]
@googlebot I consent.

**Review by atscott — APPROVED** [review]

**Comment by gregmagolan** [comment]
@googlebot I consent.

**Review by kyliau — APPROVED** [review]

**Review by pkozlowski-opensource — APPROVED** [review]

**Review by alxhub — APPROVED** [review]

**Pull request closed without merging**
