### PR TITLE
fix(dart/transform): Relative uris in part files

### LINKED ISSUE #5587: Dart: urls in `part` files resolved relative to the compilation unit they are a `part of`
Example:

maindir/main.dart
```dart
library main;

part 'subdir/foo.dart';
```

maindir/subdir/foo.dart
```dart
part of main;

@Component(..., templateUrl: 'template.html')
class MyComponent {}
```

The transformer will look for template.html in maindir/, not maindir/subdir/

Workarounds:
* Do not place part files in subdirectories
* Use absolute uris to specify `templateUrl` / `styleUrls`

### PR DESCRIPTION
**Pull request by kegluneq**
Resolve relative uris in `part` files relative to the `part` (that is,
the `CompilationUnit`) rather than the `library`.

Closes #5587

### CODE REVIEW

**Comment by yjbanov** [comment]
Please mark the commit as breaking

**Comment by kegluneq** [comment]
@sigmundch , it looks like there is no implementation of `ClassMirror#location` for dart2js. Can you think of another way to do this?

**Comment by kegluneq** [comment]
It appears we have some tests that run on Dart > Js code but which do not use the transformer. Unfortunately, `ClassMirror#location` is not implemented in dart2js, so these tests are failing.

To resolve this, we could:

<ol>
<li> Abandon this change
<li> Update those tests to:
  <ol>
      <li> Use the transformer
      <li> Run in Dartium
  </ol>
<li> Implement in dart2js
</ol>

Re: 1 above, @sigmundch made the good point that currently the location of a `part` file does not affect the semantics of the code at all. This is one reason that `import` statements are not allowed in `part` files. Maybe we should maintain this for Angular2.

**Comment by yjbanov** [comment]
I'm ok with status quo. I think it would be sufficient to document how we resolve relative URLs. @kwalrath

**Comment by kegluneq** [comment]
Closing for now - the technical complexity here is not currently worth what it would enable.

**Pull request closed without merging**
