### PR TITLE
revert: @angular/elements PR #19469

### PR DESCRIPTION
**Pull request by IgorMinar**
This PR was merged without API docs and general rollout plan.

We can't release this as is in 5.1 without a plan for documentation, cli integration, etc.

### CODE REVIEW

**Comment by IgorMinar** [comment]
@gkalpak @mhevery sorry but we have to revert the elements PR. Without a plan how to bring this to production, this PR will only cause issues as we get close to the 5.1 release and the necessary prerequisites are note ready.

Please propose a full rollout plan that includes docs, cli integration, google3 integration - see the design doc template for all the requirements. We should also have a clear owner of this effort who could work with @manughub on rolling this out. This feature was originally planned for rollout in Q1 of next year, so unless we changed our mind about this, we should have a discussion about it.

**Comment by trotyl** [comment]
Could we just have one commit for the `elements-builds` repo first, so we can use that for demos or other explore works instead of all building our own 🙏

**Comment by IgorMinar** [comment]
there is at least one build in the elements-builds repo already:
https://github.com/angular/elements-builds

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
@IgorMinar, is it intentional that this PR does not reverts the whole original PR? All `packages/elements/*` files are still left behind.

**Comment by gkalpak** [comment]
And appear in the docs :grin:: https://pr20152-e22d4cd.ngbuilds.io/api?query=elements

**Review by gkalpak — CHANGES_REQUESTED** [review]
The PR was not properly reverted.

**Comment by IgorMinar** [comment]
Hmm. You are right. I'll redo the pr

**Comment by IgorMinar** [comment]
@gkalpak done

**Comment by IgorMinar** [comment]
lint check is failing because the revert removed support for "element" commit message scope. I think we should just ignore this as it won't affect anything after the revert is merged.

**Review by gkalpak — APPROVED** [review]
😢

**Review by mhevery — APPROVED** [review]

**Comment by IgorMinar** [comment]
sending this for merge. for explanation of the lint failure see: https://github.com/angular/angular/pull/20152#issuecomment-341826023

**Pull request merged**
