### PR TITLE
feat(Compiler): Make Compiler.buildRenderDirective() static.

### PR DESCRIPTION
**Pull request by scheglov**
The new analysis task model (on which analyzer plugin will be based) works in a way that requires preparing all the information about a resolved file, class, method, etc at the time when we have this resolved entity. Afterwards this resolved AST might be flushed from heap to save memory.

So, we need to build DirectiveMetadata(s) as we go.
To reuse the existing Angular implementation we need to make the method Compiler.buildRenderDirective() public and static.

### CODE REVIEW

**Comment by scheglov** [comment]
I have signed CLA already as a Google employee!
There was no email set, did it now locally.
How/should set it for this pull request?

**Comment by pkozlowski-opensource** [comment]
@scheglov I think that the pb with the CLA is due to the fact that there are commits from multiple authors in your PR. Looks like it needs rebasing.

**Comment by scheglov** [comment]
How can I rebase it?
  I executed:

git rebase master -i
git push -f


but there are still 3 commits.

On Thu, Apr 16, 2015 at 10:01 AM, Pawel Kozlowski <notifications@github.com>
wrote:

> @scheglov <https://github.com/scheglov> I think that the pb with the CLA
> is due to the fact that there are commits from multiple authors in your PR.
> Looks like it needs rebasing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular/pull/1398#issuecomment-93785346>.
>



-- 
Konstantin Scheglov
Software Engineer
Google, Inc.

**Comment by pkozlowski-opensource** [comment]
@scheglov looks like 00db1cba734edcd7d4bfd0e81d4e9cc204e986f9 is the culprit - this one was merged to master as e819e97f9a67344ea094e4a6d8078d115ae436e8 so not sure why you've got a different sha1 in your fork...

**Comment by scheglov** [comment]
Well, I don't know how to fix it.
I will try to recreate it.

**Pull request closed without merging**
