### PR TITLE
chore(gulpfile): remove references to old traceur-dart transpiler tests

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by kegluneq** [comment]
LGTM when LGTTravis

**Comment by IgorMinar** [comment]
@alexeagle is this PR alive? can you clean it up please?

**Comment by vicb** [comment]
@alexeagle could you please rebase ?

**Comment by alexeagle** [comment]
yes, yes, very soon now

**Comment by naomiblack** [comment]
@alexeagle is it can be maybe rebase tiem nao?

**Comment by mhevery** [comment]
Closing as stale.

**Pull request closed without merging**
