### PR TITLE
fix(router): lazy routing tries loading destroyed module

### PR DESCRIPTION
**Pull request by kewde**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
The router can lazy load modules. It doesn't check whether that module has been destroyed or not.

Issue Number: #24962

## What is the new behavior?
If it has been destroyed, it will create a new instance of it.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
I'm a complete noob to angular and I need this change :kissing_heart:

### CODE REVIEW

**Review by alxhub — CHANGES_REQUESTED** [review]
LGTM

Please squash down to 2 commits, with detailed and scoped commit messages for both. The first should add `destroyed()` in `core`, the second should make use of the feature in `apply_redirects.ts.

**Comment by kewde** [comment]
@JoostK Thanks, fixed.

**Comment by jasonaden** [comment]
Update on this issue: Overall this looks great. However, the change to the public API is a pretty big breaking change. It means any code implementing `NgModuleRef` needs to be updated. This is fine for the Angular repo of course, but it will break user code.

I'm looking at how we can get this rolled out so we can move forward and merge this PR. Thanks for the patience.

**Comment by kewde** [comment]
@jasonaden

Let me know if there is anything else I can do.

I don't like breaking user code either, if the general consensus is that this is not to be merged, then I would like to know an alternative proposals to fix this bug.

**Comment by jasonaden** [comment]
Discussed this one and it looks like we might be able to make this change by updating a couple internal Google users who are implementing this API. So I think we can move forward on this one. Doing internal testing here:

[Presubmit](http://test/OCL:214845773:BASE:214845826:1538087072180:a4a8fe8b)

**Comment by kewde** [comment]
@jasonaden Is there any plan moving forward? We have a feature that depends on this fix

**Comment by kewde** [comment]
@jasonaden @alxhub is there anything left for me to do here? Please let me know, I would like this bug fixed.

**Comment by kewde** [comment]
I've added a test commit as it is the only way to retrigger CI, I will force delete it and force push. 
The Travis PR only failed because ENOSPC (no space left).

**Comment by kewde** [comment]
Rebased the PR against the current master just to be a 100% sure.

**Comment by kewde** [comment]
Oh god, review hell.

I suppose it's not worth breaking the public API over this, so I think https://github.com/angular/angular/pull/28405 will also do the trick.

**Comment by petebacondarwin** [comment]
Closing in favour of #28405

**Pull request closed without merging**
