### PR TITLE
refactor(core): throw error when `provideZoneChangeDetection` is called in wrong context

### PR DESCRIPTION
**Pull request by arturovt**
This commit updates the implementation of the `provideZoneChangeDetection` function and checks whether the current platform is browser (where this code is executed). This function should not be called in server application config because this will lead to runtime errors.

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@arturovt which errors do you see on the server when this function is used?

**Comment by arturovt** [comment]
> @arturovt which errors do you see on the server when this function is used?

`delayChangeDetectionForEvents - cannot read properties of null (reading 'call')`.

**Comment by AndrewKushnir** [comment]
@arturovt thanks for additional info. Could you please create a minimal repro (in a form of a Github repository), so that we can take a look? I think it should be possible to make the `provideZoneChangeDetection()` call in both client and server environments, so we'd need to better understand what is the root cause for this behavior.

**Comment by arturovt** [comment]
> @arturovt thanks for additional info. Could you please create a minimal repro (in a form of a Github repository), so that we can take a look? I think it should be possible to make the `provideZoneChangeDetection()` call in both client and server environments, so we'd need to better understand what is the root cause for this behavior.

Ok. I initially thought to check whether the current platform is **not** `browser` and provide explicit `NgZoneOptions` in the following way:

```ts
inject(PLATFORM_ID) === 'browser' ? getNgZoneOptions(options) : getNgZoneOptions({ eventCoalescing: false, runCoalescing: false });
```

I'll provide a running example shortly.

**Comment by arturovt** [comment]
@AndrewKushnir 

```sh
$ git clone git@github.com:arturovt/provide-cd-ssr.git
$ cd provide-cd-ssr
$ yarn && yarn build:ssr && yarn serve:ssr
$ curl localhost:4000
```

**Comment by AndrewKushnir** [comment]
@arturovt thanks for additional information and a great repro 👍 The problem is that the `requestAnimationFrame` is used for batching in Zone.js when you enable coalescing (which is disabled by default) and we'd need to find an alternative solution for Node.js (or ignore that config option on the server). Could you please create a ticket (and include the repro), so that we can take a look at different options?

**Comment by AndrewKushnir** [comment]
@arturovt thanks for creating a ticket https://github.com/angular/angular/issues/50801. I think `setTimeout` (as you mentioned) or `queueMicrotask` might be a good option. We'll discuss this further and share an update. I'm closing this PR for now (since we want to keep the `provideZoneChangeDetection` compatible with both browser and server environments).

**Pull request closed without merging**
