### PR TITLE
docs(toh-pt3): fix HeroDetailComponent example

### PR DESCRIPTION
**Pull request by plr108-zz**
Fix input element syntax.

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks @plr108! This change has more impact as the ending slash is being used in other examples also. Will you explain why you want to make this change?

**Comment by plr108** [comment]
Hi @brandonroberts, the related part of the tutorial states to cut and paste this HTML from the `HeroesComponent` template.  However, the ending of the input element does not match the code for `HeroesComponent` presented in the previous tutorial page: 

https://github.com/angular/angular/blob/04cf4ef0c7985c6d1df7e203cfbef34d52402e3d/aio/content/examples/toh-pt2/src/app/heroes/heroes.component.html#L21

**Comment by brandonroberts** [comment]
@plr108 I see. Instead of removing the slash from toh-pt3, it should be added toh-pt2. toh-pt3 and forward have the ending slash already.

**Comment by plr108** [comment]
I attempted to push the fixes... if I did this incorrectly let me know and I can revert this (or open a new pull request)

**Comment by brandonroberts** [comment]
@plr108 yes, something went wrong with the merge. If you're using git locally, hard reset your branch to master and make the change again. Or you can open a new PR if you're editing from GitHub.

**Comment by brandonroberts** [comment]
And the git commit message should be `docs: add ending slash to input in TOH pt2 example`

**Comment by plr108** [comment]
@brandonroberts thank you for your help.  It was cleaner to create a new pull request; see #29176

**Pull request closed without merging**
