### PR TITLE
fix(router): canDeactivate guards should run from bottom to top

### LINKED ISSUE #15657: canDeactivate guard runs from top down to child routes
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

- navigate from `/root/branch/1` to `/root/branch/2`, canDeactivate guard runs from top down to the child
- navigate from `/root/branch/1` to `/`, canDeactivate guard runs from child to the top (which is as documented)

**Expected behavior**

As [documented](https://angular.io/docs/ts/latest/guide/router.html#!#guards), it should always run from child to top.
>The router checks the CanDeactivate() and CanActivateChild() guards first, from the deepest child route to the top.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/NxLmkAq1zTpWHjgH6S4C?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =   
6.9.5

### PR DESCRIPTION
**Pull request by royling**
Closes #15657.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
#15657

**What is the new behavior?**
canDeactivate guard runs in the consistent order: from the deepest child to top

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by vicb — DISMISSED** [review]
Please add a test

**Comment by royling** [comment]
@vicb test added.

Because there's a bug with canActivateChild bug (#15547), I could not merge this test case into the existing one. But we should merge them after the canActivateChild bug is fixed (see PR #15651), I think.

**Comment by jasonaden** [comment]
@royling See comment on #15651. Can we close this PR?

**Comment by royling** [comment]
@jasonaden actually #15651 is including this one, which fixes 2 issues (#15657 and #15547) though.
Initially I created only #15651 to fix both issues, but later suggested to split them. I also mentioned this above.

If you think it's OK to fix both in one PR, then please feel free to close this one.

**Comment by jasonaden** [comment]
Okay. So added a comment with the sequence on the other PR. But I guess this is the sequencing PR so I'll include it here as well:

`canActivate` top to bottom
`canActivateChild` top to bottom
`canDeactivate` bottom to top

Does that help? Was that your understanding as well?

**Comment by royling** [comment]
@jasonaden I've updated the other PR following the clarification.
And I intend to keep this PR only for fixing the order of `canDeactivate` guard (#15657), a test was specifically added for that.

**Review by jasonaden — APPROVED** [review]
LGTM

**Pull request merged**
