### PR TITLE
docs: removed repeated words "when"

### LINKED ISSUE #53827: docs: Repeated word `when`
### Describe the problem that you experienced

![image](https://github.com/angular/angular/assets/70423865/a37aa8bb-3e28-4cb2-b705-a36767645446
PixPin_2024-01-08_17-05-26

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/interceptors#configuring-interceptors

### Describe what you were looking for in the documentation

_No response_

### Describe the actions that led you to experience the problem

_No response_

### Describe what you want to experience that would fix the problem

_No response_

### Add a screenshot if that helps illustrate the problem

_No response_

### If this problem caused an exception or error, please paste it here

_No response_

### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

### PR DESCRIPTION
**Pull request by gleb-28**
Fixes #53827

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #53827

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by bencodezen — APPROVED** [review]
Thanks for helping to fix this typo!

**Comment by zxywftr** [comment]
Thank you~

**Comment by jelbourn** [comment]
@gleb-28 can you change your commit message to just `docs:` ? For us `docs-infra` means that the commit is related to the tools we use to build the documentation site, whereas just `docs` is for content.

**Review by jessicajaniuk — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 001c30defdab87a9ffc85f6126a7c8edf8b4de4a.

**Pull request closed without merging**
