### PR TITLE
Specialized error when depending on an Ivy-compiled NgModule, 10.2.x edition

### PR DESCRIPTION
**Pull request by alxhub**

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

(though I think that may not be needed, since it's a backport)

**Comment by alxhub** [comment]
Caretaker: this is a backport of #41534 to the `10.2.x` branch.

**Review by zarend — APPROVED** [review]

**Comment by zarend** [comment]
@josephperrott what's the processes for merging into the previous major version? Would I merge this like normal using `yarn ng-dev pr merge`, and when do we release `10.2.x`?

**Comment by josephperrott** [comment]
@zarend The merge tooling supports merging as normal into active LTS branches with the `target: lts` label.

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Comment by zarend** [comment]
Closed by commit f630f331de3781a2b3f43b23f10ef40d361888e8

**Pull request closed without merging**
