### PR TITLE
refactor(ivy): move di tests to acceptance

### PR DESCRIPTION
**Pull request by cexbrayat**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the new behavior?

This moves the tests from `di_spec.ts` (that use manually written Ivy instructions) to the `acceptance` tests (that use proper templates).

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I talked about this task with @kara in #29257 I'll start moving the other tests in `di_spec.ts` when this is merged.
cc @petebacondarwin as he wrote most of these tests

### CODE REVIEW

**Comment by petebacondarwin** [comment]
I don't think I wrote them :-) I just tweaked them most recently.

**Comment by petebacondarwin** [comment]
Not sure if this is a flake or a legit failure:

```
IE 10.0.0 (Windows 8.0.0) DeprecatedDatePipe supports should support numeric strings FAILED
	Expected function not to throw, but it threw SyntaxError: Syntax error in regular expression.
	    at <Jasmine>
	   at Anonymous function (Unknown script code:45:64)
	   at invoke (node_modules/zone.js/dist/zone.js:386:13)
	   at onInvoke (node_modules/zone.js/dist/zone-testing.js:288:13)
	   at invoke (node_modules/zone.js/dist/zone.js:386:13)
	   at run (node_modules/zone.js/dist/zone.js:138:17)
	   at runInTestZone (node_modules/zone.js/dist/zone-testing.js:509:13)
	   at Anonymous function (node_modules/zone.js/dist/zone-testing.js:524:13)
	    at <Jasmine>
	   at invokeTask (node_modules/zone.js/dist/zone.js:419:13)
	   at runTask (node_modules/zone.js/dist/zone.js:188:21)
	   at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:595:25)
	   at run (node_modules/core-js/client/core.js:6252:13)
	   at Anonymous function (node_modules/core-js/client/core.js:6269:30)
	   at flush (node_modules/core-js/client/core.js:2471:9)
```

I restarted it to see.

**Comment by cexbrayat** [comment]
@petebacondarwin Looks like it was a flake, thanks for restarting :+1:

**Review by petebacondarwin — APPROVED** [review]

**Comment by cexbrayat** [comment]
@kara I need your advice.

I migrated a few more tests from `render3/di_spec.ts` to `acceptance/di_spec.ts`.
As you can see in the CI results, some migrated tests are OK in aot/Ivy mode but not otherwise.

For example, the assertion that each TemplateRef instance should be unique [here](https://github.com/angular/angular/pull/29299/files#diff-881d964a81b3db8c8cb5311b8e3546ecR181) is OK in Ivy but not otherwise. Same thing with `ViewContainerRef`.

Is it normal and I should change the test to `modifiedInIvy` (or something like that), or is it a bug?

**Comment by kara** [comment]
@cexbrayat Yep, those are expected changes. It should be marked `onlyInIvy`, since the behavior doesn't occur in View Engine.

**Comment by cexbrayat** [comment]
@kara @petebacondarwin PR is up for review when you have time. I migrated all the tests I could based on Kara's answers.

Note that:
- IIUC, inline views are not yet supported by Ivy compiler. So the tests using `if(showing) %{ ... ` have not been migrated. I added a comment on top of them to explain why. I don't know if there is an issue to track the support of inline view that should be mentionned. I also added tests using `<ng-container *ngIf="">` as an approximation in `acceptance` in the meantime.
- some tests are migrated with `onlyInIvy` either because of a change in behavior, or because the error thrown has not the same message
- The remaining tests are not really possible to migrate because they are more like unit tests.

**Review by kara — APPROVED** [review]
LGTM

**Pull request closed without merging**
