### PR TITLE
chore(bundles): add http and router mocks to angular2-testing

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
The current paths we've got are pretty strange as we've got both a _file_ and a _folder_ named `http` (same for router) under `angular2`:

```
angular2
    http
        testing.ts
    ...
    http.js
```

Maybe we should rename one of those?

**Comment by pkozlowski-opensource** [comment]
@IgorMinar this is one of the changes we've identified yesterday

**Comment by jeffbcross** [comment]
> The current paths we've got are pretty strange as we've got both a file and a folder named http (same for router) under angular2

@pkozlowski-opensource does this present any practical problems? Or just potential user confusion?

**Comment by pkozlowski-opensource** [comment]
> does this present any practical problems?

Nope, not currently. Maybe I'm just paranoid :-)

**Comment by jeffbcross** [comment]
> Nope, not currently. Maybe I'm just paranoid :-)

That's not such a bad thing ;)

Is there an issue discussing this change?

**Comment by pkozlowski-opensource** [comment]
Nope, there is no specific issue for this particular item. We've just spotted a missing exports while reviewing things with @IgorMinar

**Pull request closed without merging**
