### PR TITLE
Fix typo in singleton-services doc

### PR DESCRIPTION
**Pull request by s001dxp**
wrong word use

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Thanks for this PR, @s001dxp! 

Two small points of note:

1. Make sure you sign the CLA.
2. Please amend your commit message to something similar to the following: `docs: fix typo in singleton-services guide`. Having the action of what we did in the PR is helpful when looking back.

Feel free to tag me with questions and when you're done so I can help it through the rest of the process.

**Review by kapunahelewong — CHANGES_REQUESTED** [review]
Requested changes above.

**Comment by jbogarthyde** [comment]
I took the liberty of changing the PR title, but the commit message still needs to change to something more descriptive.

**Comment by pkozlowski-opensource** [comment]
Looks like it was fixed already in #32330 - closing as a duplicate.

**Pull request closed without merging**
