### PR TITLE
feat(forms): expose updateTreeValidity method

### LINKED ISSUE #6170: Can't explicitly validate ControlGroup
It would be nice to have the possibility to explicitly call a **.validate()** method on a ControlGroup.
Starting with an invalid form just because the user still hasn't entered anything isn't always ideal.

In [your forms guide](https://angular.io/docs/ts/latest/guide/forms.html) it's quite convenient to start out with a populated model, hence you don't need to check !field.dirty or !field.touched in the view.

Please see my [video](https://youtu.be/T__VppOCk04) or check out my [ng2_play repo](https://github.com/ajtowf/ng2_play), it's always easier to show the problem.

### LINKED ISSUE #19820: Provide a validation function at ngForm
## I'm submitting requirement
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I must use loop to manual control the form validate in ts code .
```ts
if (this.tempForm.invalid) {
  Object.keys(this.tempForm.controls).forEach(k => {
    // this.tempForm.controls[k].updateValueAndValidity();
    this.tempForm.controls[k].markAsDirty();
  });
  return;
}
```
## Expected behavior
Provide a validate function.

```
// Want to use 
this.tempForm.forceValidate()
```

## Environment

<pre><code>
Angular version: 4.x

### PR DESCRIPTION
**Pull request by trotyl**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: Closes #6170, closes #19820.

## What is the new behavior?

Expose `AbstractControl#updateValueAndValidity()` to allow user force re-validate a `FormGroup`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Gerros** [comment]
ping :) would be awesome to have this functionality... working at the moment on a huge form and its really cumbersome to always have to manually iterate over nested forms to update validity or mark a larger part is dirty etc.

**Comment by hisham** [comment]
+1. Need this as well.

**Comment by ErazerBrecht** [comment]
+1

Would love to remove the 'forEach' / recursvie functions we now have to fix this.

**Comment by LeonardoVizzotto** [comment]
I searched in the contributing guidelines but haven't found anything about opening a PR for a feature that already has a PR associated with.

Since the last update on this one is from 2017, I was thinking about opening a new PR.

**Comment by mshehadeh** [comment]
What's the status with this? Did someone open a new PR?

**Comment by SamKamalesan** [comment]
This will be a nice to have functionality, which reduce tons of repeated code in app. Can you please release this functionality as soon as possible ?

**Comment by phantomsom** [comment]
+1

**Pull request closed without merging**
