### PR TITLE
Remove deprecated `CompilerOptions.useJit` and`CompilerOptions.missingTranslation` properties

### PR DESCRIPTION
**Pull request by JeanMeche**
`useJit` and `missingTranslation` properties have been deprecated since v13 and  are unused in Ivy. They can be safely removed. 

Migration is provided to handle the breaking changes. 

## Does this PR introduce a breaking change?

- [x] Yes

### CODE REVIEW

**Review by alxhub — APPROVED** [review]
Nice work!

**Comment by alxhub** [comment]
Marking as `blocked` for now (until we're in the merge window for v17).

**Review by dylhunn — APPROVED** [review]
reviewed-for: fw-core, fw-migrations, public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by alxhub** [comment]
@JeanMeche if we can rebase this, it can land in v17 :D

**Review by jessicajaniuk — APPROVED** [review]

**Comment by atscott** [comment]
This PR was merged into the repository by commit f0da7c2e44a29c5a71cf4880388989d129f4c6e8.

**Pull request closed without merging**
