### PR TITLE
docs (core): add circleci insights metrics widget

### PR DESCRIPTION
**Pull request by jerdog**
In addition to the existing badges which show the status of builds, etc., this new widget that shows the Insights metrics for your repo that shows how the default_workflow is performing. More info can be found at: https://discuss.circleci.com/t/try-insights-snapshot-in-your-gh-repo/43169/

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Regular build-related badges are displayed, but nothing to show how builds are performing over time

Issue Number: N/A

## What is the new behavior?
Display build stats on README

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jerdog** [comment]
@dylhunn here's the redone PR

**Comment by dylhunn** [comment]
I'm going to wait for CI to complete and then merge it!

merge-assistance: already approved in #45441

**Comment by jerdog** [comment]
ahh - good ol' lint messages - sorry about that space in the commit message - amending/fixing it @dylhunn

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit bdf57ab14a310f6e6811d9f990cbbd3612bde538.

**Pull request closed without merging**
