### PR TITLE
refactor: remove no longer used prompts utils

### PR DESCRIPTION
**Pull request by alan-agius4**
These utils are no longer used in Angular migrations.

### CODE REVIEW

**Review by devversion — APPROVED** [review]

**Comment by alan-agius4** [comment]
[Presubmit](https://fusion2.corp.google.com/presubmit/tap/457914378/OCL:457914378:BASE:457914417:1656489884914:21911742/targets)

**Review by jessicajaniuk — APPROVED** [review]
LGTM!

**Comment by dylhunn** [comment]
@alan-agius4 Did the presubmit on this complete?

**Comment by alan-agius4** [comment]
@dylhunn looks like there are failures which are not caused by this CL https://fusion2.corp.google.com/presubmit/tap/457914378/OCL:457914378:BASE:458000637:1656521829067:567be5da/targets

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 926de8c0a4250cfe667de9b23780ae2d1ed136b2.

**Pull request closed without merging**
