### PR TITLE
feat(forms): Added form related methods and tests

### PR DESCRIPTION
**Pull request by basvandenheuvel**
#### I DELETED THE PREVIOUS PR DUE TO SOME WEIRD ERRORS

@robwormald @vsavkin

Credits to @MarkPerryBV for helping out with this PR.
#### Changes in this PR

AbstractControl: 
- Added `markAsUntouched()`, `markAsPristine()`

ControlGroup: 
- Added `markAsPristine()`, `markAllAsPristine()`, `markAllAsDirty()`, `markAllAsTouched()`, `markAllAsUntouched()`, `markAllAsPending()`

ControlArray: 
- Added `markAsPristine()`, `markAllAsPristine()`, `markAllAsDirty()`, `markAllAsTouched()`, `markAllAsUntouched()`, `markAllAsPending()`

Tests:
- Added missing tests for "touched" part
- Added tests for all new methods

NG_COMMON:
- Added needed NG_COMMON values (ask permission? @mhevery)
#### Questions for the Angular team:
- Methods like "dirty" and "pristine" bubble up to the parent, the touched part doesn't. Is this intended? If the touched part should also bubble up i can create a PR for this, let me know.
#### Next PR
- For a next PR i'm going to look into stuff like `clear()` and `reset()` methods for the form.

Issues I (partly) solve with this PR: #4933, #5568

### CODE REVIEW

**Comment by 101100** [comment]
@basvandenheuvel This looks great!

**Comment by vsavkin** [comment]
What was the previous PR? I remember reviewing it but I don't remember the PR number.

Could you squash the commits in this PR?

**Comment by basvandenheuvel** [comment]
@vsavkin  https://github.com/angular/angular/pull/6679

**Comment by basvandenheuvel** [comment]
Can anyone help me witht he Squask? As you can see in my commits, there are 2 commits related to retrieving the newest version of the Angular 2 master because my PR branch was behind the master. 

In the past i tried to squash these commits as well resulting in A LOT of errors. How can i squash these 3 commits togheter?

Sorry this PR is taking so long, i've been very busy.

**Comment by robwormald** [comment]
here's a good article on squashing http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by ericmartinezr** [comment]
@basvandenheuvel what I do to avoid those "Merge remote-tracking ..." commits is the following

```
sudo git checkout master   // change to master branch
sudo git fetch upstream // bring the most recent head to my fork
sudo git merge upstream/master // merge my copy with the most recent head
sudo git checkout my-branch // change to the branch where I'm working on
sudo git rebase -i master // make the branch to be updated with master
```

When I `merge` in my branch is when I normally see those commits. Someone more experienced could confirm/deny/clarify what I'm saying. But that works me.

**Comment by basvandenheuvel** [comment]
@ericmartinezr  If you follow those steps, the damm merge commits won't be squashes but still shown as seperate commits? or will they be squashed without giving errors?

**Comment by ericmartinezr** [comment]
@basvandenheuvel I don't get any of them when doing like that, but if you already have them I have no idea how to remove them nor squash them, you should ready the article @robwormald posted anyway.

**Comment by MarkPerryBV** [comment]
I have assisted in squashing the commit into a single one. If someone could please review and let me know if I need to do anything else.

**Comment by MarkPerryBV** [comment]
@vsavkin Do I need to worry about those failing Travis tests?

**Comment by mhevery** [comment]
@MarkPerryBV Yes please look here: https://travis-ci.org/angular/angular/jobs/120564191#L3616 The issue is that structure of the types are not sound. Let me know if a specific error does not make sense.

**Comment by MarkPerryBV** [comment]
Looking into the CI errors I can see that one of them is a Dart analysis error regarding not having the "all"  (mark**All**AsPristine, mark**All**AsUntouched, mark**All**AsTouched, mark**All**AsDirty, mark**All**AsPending) methods on the `AbstractControl` base class.

The issue I have is that
`AbstractControl` acts as the base class for:

`Control` - Singular Form Controls

and

`ControlGroup`
`ControlArray` 
Which are containers for many `Control`'s.

It doesn't make sense for `AbstractControl` to have the `all` methods defined on it so I am a little stuck on how to proceed. One logical path would be to split out the abstract base call into two.

AbstractControl and AbstractControlContainer/Group/(?) 

As a windows developer I will also say that the barriers to contribution are quite high. I have spent over 4 hours trying to get the right versions of Node, NPM, gulp, python running on my dev machine to get the `npm install` to work to then be able to run the code formatting gulp package.

**Comment by zoechi** [comment]
@MarkPerryBV I posted a Dockerfile in https://github.com/angular/angular/issues/7938#issuecomment-206699184 which worked for me to build Angular. I think it would be quite handy to have an official one that can be use as instruction how to do it manually and which can be used to reproduce issues devs run into while building.

**Comment by mhevery** [comment]
Hi @MarkPerryBV Thanks for your hard work on this PR. Usually when the type system gives errors, it it trying to tell you that something is not self consistent. In your case I don't think you need both `markAllAsPristine` and `markAsPristine`, you just need `markAsPristine`.

In case of a leaf such as a `Control` `markAsPristine` will mark itself. In case of a group such as `ControlGroup` or `ControlArray` the `markAsPristine` should mark itself and all of the children. (Which is what `markAllAsPristine` is doing).

So there is no need for `markAllAsPristine`.  

Does that make sense?

**Comment by MarkPerryBV** [comment]
@mhevery Yeah, agreed I see what you mean. I'll re-do and try again.

**Comment by mhevery** [comment]
This PR is stale (does not rebase; pass CI; had no activity for a while). It is probably our fault, and we are sorry. In an effort to keep our PR queue under control, and prevent us from taking too long to get back to you we are cleaning up the queue. Unfortunately this means that this PR is getting closed.

If you would like to resurrect this change, please rebase on master, make the tests pass and create a new PR.

**Pull request closed without merging**
