### PR TITLE
build(devtools): Update manifestVersion to v3

### PR DESCRIPTION
**Pull request by vteotia9**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by vteotia9** [comment]
[46287](https://github.com/angular/angular/issues/46287)

https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#man-sw

**Comment by jessicajaniuk** [comment]
@vteotia9 Looks like you have lint issues related to the commit messages. Can you fix those so they conform to the required structure?

**Comment by vteotia9** [comment]
> @vteotia9 Looks like you have lint issues related to the commit messages. Can you fix those so they conform to the required structure?

I updated the commit message. How to re-run cicircle tests?

**Comment by jessicajaniuk** [comment]
> > @vteotia9 Looks like you have lint issues related to the commit messages. Can you fix those so they conform to the required structure?
> 
> I updated the commit message. How to re-run cicircle tests?

@vteotia9 It looks like you updated the PR title, but not the commit messages. You'll need to do an interactive rebase and reword the commits followed by a force push. Once that's done, the tests will automatically restart after they see the new push.

**Comment by AleksanderBodurri** [comment]
Closing. This will be addressed in #47575

**Pull request closed without merging**
