### PR TITLE
feat(common): add loader for sirv

### PR DESCRIPTION
**Pull request by IgorVaryvoda**
This PR adds a Sirv image loader for `ng_optimized_image`

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, can you please squash your commits ?

**Comment by IgorVaryvoda** [comment]
> Hi, can you please squash your commits ?

Hi, done.

**Comment by atcastle** [comment]
Hi @IgorVaryvoda, thank you for taking the time to submit this PR. In order to prevent the built-in image loaders from becoming a maintenance liability, we're being very conservative about which CDNs get added to the repo, and are generally trying not to expand the list at all, if possible.

So I'm suggesting we close this PR, and I would encourage you to instead publish `provideSIrvLoader` as a third-party package.

CC: @AndrewKushnir

**Comment by JeanMeche** [comment]
PR @atcastle

**Comment by JeanMeche** [comment]
Per @atcastle

**Pull request closed without merging**
