### PR TITLE
docs: fix typo in http.md

### PR DESCRIPTION
**Pull request by m-burst**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

There's a typo in the HttpClient docs.

Issue Number: N/A

## What is the new behavior?
Typo fixed

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Good catch! Thank you for submitting this PR. Would you amend the commit message to be "docs: fix typo in http.md" and tag me when you've done it so I can approve? Thank you!

**Comment by m-burst** [comment]
@kapunahelewong Done :)

**Review by kapunahelewong — APPROVED** [review]
LGTM! Thank you, @m-burst !!

**Comment by IgorMinar** [comment]
@kapunahelewong please add the merge label in the future as well, otherwise the caretaker will not see the pr. thanks

**Comment by kapunahelewong** [comment]
Oh thank you, @IgorMinar! Now I understand and will be sure to do it in the future.

**Pull request closed without merging**
