### PR TITLE
docs: update markdown and formatting

### PR DESCRIPTION
**Pull request by josmar-crwdstffng**
Update markdown and formatting in image-directive topic.

### CODE REVIEW

**Comment by josmar-crwdstffng** [comment]
@bob-watson 
This is a clean-up PR to fix broken formatting and remove an error that was falsely reported as a warning.

**Review by bob-watson — APPROVED** [review]
LGTM

**Comment by josmar-crwdstffng** [comment]
Removed forbidden label.

**Comment by AndrewKushnir** [comment]
@josmar-crwdstffng it looks like this PR has a conflict after merging some other PRs. Could you please rebase and resolve conflicts when you get a chance? Thank you.

**Comment by josmar-crwdstffng** [comment]
@AndrewKushnir 
The conflict was resolved. Please move this forward. Thank you.

**Pull request closed without merging**
