### PR TITLE
build(docs-infra): upgrade cli command docs sources to 6ccbc6b4c

### PR DESCRIPTION
**Pull request by gkalpak**
Updating [angular#main](https://github.com/angular/angular/tree/main) from [cli-builds#main](https://github.com/angular/cli-builds/tree/main).

##
Relevant changes in [commit range](https://github.com/angular/cli-builds/compare/23b229e89...6ccbc6b4c):

**Modified**
- help/build.json
- help/generate.json

##
Relevant changes in [commit range](https://github.com/angular/cli-builds/compare/22d1977c5...6ccbc6b4c) since PR #48018:

**Modified**
- help/build.json

##
Closes #48018

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit 79bd0f1e965d8e3265415e9ca117fd938418ed92.

**Comment by dylhunn** [comment]
This has a merge conflict with patch so I merged it into main only -- but please send me a patch port if needed, thanks!

**Comment by gkalpak** [comment]
This was supposed to get into `main` only :+1:
It seems that the bot failed to apply the labels for some reason 🤷‍♂️

**Pull request closed without merging**
