### PR TITLE
refactor(core): Move logic into early event contract files.

### PR DESCRIPTION
**Pull request by tbondwilkinson**
Also remove some dead a11y code, now that a11y is in `ActionResolver`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Comment by tbondwilkinson** [comment]
TESTED=[TGP](https://fusion2.corp.google.com/presubmit/652619772/OCL:652619772:BASE:652809645:1721177563240:467f03a2/targets)

**Review by thePunderWoman — APPROVED** [review]
LGTM

this looks great!

reviewed-for: fw-core, primitives, public-api

**Review by rahatarmanahmed — APPROVED** [review]

**Review by alxhub — APPROVED** [review]
Reviewed-for: public-api

**Comment by tbondwilkinson** [comment]
Caretaker note: cl/653324007 required to patch into the sync CL for internal BUILD rules.

**Comment by atscott** [comment]
This PR was merged into the repository by commit 425f44c1333f1007804012ffd428f65d869bad5e.

The changes were merged into the following branches: main, 18.1.x

**Pull request closed without merging**
