### PR TITLE
docs(dev-infra): fix typo in comment (arguements --> arguments)

### PR DESCRIPTION
**Pull request by eltociear**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Good catch! Thx, @eltociear :+1:

One minor request: Can you please change the commit message to `docs(dev-infra): ...`? For example:

> docs(dev-infra): fix typo in comment (arguements --> arguments)

**Comment by eltociear** [comment]
@gkalpak Thank you for your reviewing!

I'm change commit message and PR title. 
Is this all right?

**Comment by gkalpak** [comment]
@eltociear, it seems that you have added new commits instead of updating the original one. You need to squash all commits into one (via interactively rebasing - see [here][1] for a brief overview of the process). 

[1]: https://twitter.com/stephenfluin/status/1009904095073718275

**Comment by eltociear** [comment]
@gkalpak Thank you for teaching me!
I've squashed the commits with the way you told me.

**Comment by gkalpak** [comment]
Thx for taking care of it, @eltociear!
LGTM - marked for merging 🚀

**Comment by eltociear** [comment]
@gkalpak  I learned a lot, **thanks**!

**Pull request closed without merging**
