### PR TITLE
docs: fix sentence in router tutorial by adding missing word

### PR DESCRIPTION
**Pull request by volunux**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by atscott — CHANGES_REQUESTED** [review]
Hi @volunux, could you please update the commit message to conform to the requirements? Something like "docs: fix sentence in router tutorial by adding missing word" should work.

**Comment by geromegrignon** [comment]
@volunux The message required to be updated is the commit message, not the PR message.
As the format is checked by the CI, it fails with 'missing word'.
You find further information into the [contribution guide](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit).

By the way, you need to accept the CLA too, as described by the previous message.

**Comment by atscott** [comment]
@volunux - I went ahead and amended the commit message for you. You'll still need to accept the Google CLA before this can be merged.

**Comment by petebacondarwin** [comment]
Closing due to no CLA. @kapunahelewong - perhaps you could create a PR to fix this?

**Pull request closed without merging**
