### PR TITLE
docs(router): Update component testing docs to use RouterTestingHarness

### PR DESCRIPTION
**Pull request by atscott**
This commit updates the documentation on testing the
`Router` to use the `RouterTestingHarness` rather than stubs.

The stubs described in the previous form of this document actually
creates tests which are incapable of catching bugs related to the
component's interaction with the `Router`. In addition, managing the
stubs is more difficult than using the real `Router` classes.

Stubbing something like the `RouterLink` is quite harmful because it
neither tests the actual URL being created, nor the end result of the
navigation. There have been serveral bug fixes in the Router over the
years the would change the outcome of these but would not be caught by
tests which create a stub.

### CODE REVIEW

**Comment by trekladyone** [comment]
@atscott  An entry needs to be made in the .pullapprove.yml.

**Comment by atscott** [comment]
@trekladyone I'm not sure I follow what you mean. None of these documents are new so they should already be covered, right?

**Comment by trekladyone** [comment]
@atscott For some reason, the checks seem to be hanging up on the pullapprove.

**Review by trekladyone — APPROVED** [review]

**Review by MarkTechson — APPROVED** [review]
LGTM

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit e7948d30c5e90267e383e265e21afd03dc41df25.

**Pull request closed without merging**
