### PR TITLE
docs(forms): Remove unnecessary repeating periods

### PR DESCRIPTION
**Pull request by stasusov**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

^ not a bug or a feature, just a minor doc update ^

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Behaviour not changed.

Issue Number: N/A

## What is the new behavior?
Behaviour not changed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by stasusov** [comment]
@googlebot I signed it!

**Review by gabrielbussolo — APPROVED** [review]
For me it makes sense to remove.
:+1:

**Review by aikithoughts — APPROVED** [review]
Thanks for doing this!

**Review by kapunahelewong — APPROVED** [review]
Thank you @stasusov!!

EDIT: @stasusov, we just need https://github.com/angular/angular/pull/36487 to merge first. I'll come back in then and help this through. Thanks again!

**Review by AndrewKushnir — APPROVED** [review]
LGTM 👍

**Pull request closed without merging**
