### PR TITLE
fix(build): move fsevents into optionalDependencies

### LINKED ISSUE #13935: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
windows 10
node 5.12.0
npm 3.10.8

I'm trying to build an angular project from the sources based on [this instruction](https://github.com/angular/angular/blob/master/DEVELOPER.md). However, when running `npm install` I get the following error:

```
npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

```

### PR DESCRIPTION
**Pull request by lacolaco**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

non-Mac developers can not set up their environment because of explicitly dependency on `fsevents`.

**What is the new behavior?**

Mark `fsevents` as an optional dependency.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Fixes #13935, #12443

### CODE REVIEW

**Comment by laco0416** [comment]
My environment is Node 6.9.1, npm@3.10.10

I want to avoid this too large diff... what version should I use to generate shrinkwrap in?

**Comment by vicb** [comment]
> non-Mac developers can not set up their environment because of explicitly dependency on fsevents.

I'm curious what the pb is and on what platform angular build fails ? _I hadn't any problem with Ubuntu back when I was using it_

Notes:
- please try to avoid those `dev: true` all other the file which make the diff hard to read,
- I've noticed that some packages get updated while they should not (`@types/...`)

If you can not generate a correct file, I could generate it on my computer and amend the commit.

**Comment by vicb** [comment]
also add `fixes #<PR number>` if the commit fixes any issues (which seems to be the case)

**Comment by DzmitryShylovich** [comment]
> I'm curious what the pb is and on what platform angular build fails ?

windows :)

**Comment by laco0416** [comment]
@vicb thanks for your review. If possible, I'd like to ask you to generate shrinkwrap. My edit is only moving `fsevents` into optionalDependencies.

**Comment by petebacondarwin** [comment]
Because this removes fsevents from shrinkwrap it basically means that it is not included in any development environment even if it is supported, right?

**Comment by gkalpak** [comment]
Was this change necessary? My understanding was that tge issue was caused by an npm bug (introduced in v3.10.8).

See also [here][1].

[1]: https://github.com/angular/angular/blob/31d42d87c647a98889eb85391b2d8e8eb01e7e0c/scripts/ci-lite/env.sh#L8

**Pull request closed without merging**
