### PR TITLE
fix(docs):update input-output-diagram.svg

### PR DESCRIPTION
**Pull request by ocapuozzo**
Expression in the opposite direction in diagram !  so fixed here. 
"deleteRequest" is **source** of event (**not "target"**) and "crossOffITem" is one of **targets** of event (**not "source"**).
 
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ocapuozzo** [comment]
As said, diagram must be update. OutPut property is **target** (event emitter) not **source**...

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Sorry that this has sat unloved for almost a year @ocapuozzo. It seems it got lost in the mass of other PRs.
I have two suggestions:
1. I don't think that source and target are actually very useful terms to use regarding outputs. How about using "event" and "handler" instead?
2. Can you minify the SVG file similar to how it was before you modified it?

Thanks!

**Comment by ocapuozzo** [comment]
Bonjour,
Yes, "event" and "handler" are direct and better terms. 

I 'm doing the job, (your 1 and 2 point) but how commit now ?
Olivier  Le samedi 13 novembre 2021 à 10:11 -0800, Pete Bacon Darwin a
écrit :

**Comment by petebacondarwin** [comment]
Thanks for the update @ocapuozzo - would you mind doing some git magic on this PR?
Please rebase on the current upstream master, and squash the commits into one, updating the commit message to follow our required guidelines. E.g.

```
docs: clarify input-output diagram
```

**Comment by ocapuozzo** [comment]
I would have liked to have done this magic, but after a few attempts I
throw in the towel. 
When I try a rebase, I turn around with commits that are not mine ...
 If you could take the lead, feel free to do so.

Thank you

Olivier Capuozzo

**Comment by petebacondarwin** [comment]
@ocapuozzo - sorry you didn't get it working. Thanks for trying. I have rebased for you.

For you reference what I did was:

```
git fetch upstream master
git checkout patch-1
git rebase upstream/master -i
# squashed the commits and fixed the commit message
git push --force-with-lease
```

**Comment by ocapuozzo** [comment]
Perfect !
Thanks for the git commands sequence.

**Comment by petebacondarwin** [comment]
@ocapuozzo - I actually meant that we should change the heading of the boxes in the diagram from source and target to event and handler...

**Comment by ocapuozzo** [comment]
Pete Bacon Darwin I understand you, but in term of "data flow" (i.e
soure ->  target) the new diagram is correct, and non-redondant
naming. 

Note : Data flow is a concept used in this page.

If we change "source" (of new correct diagram) by "event", we loose
"data flow" concept and have 2 times "event" word :   "Event" fllowing
by ***@***.*** event from child"

Target side in new diagram, I have changed "method" by "handler"
(withholding your proposal).

**Comment by petebacondarwin** [comment]
OK I can live with that.

**Review by petebacondarwin — APPROVED** [review]

**Review by atscott — APPROVED** [review]

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit f44fa4be5d543961edc7f3b2ebdc7dec8c5a7228.

**Pull request closed without merging**
