### PR TITLE
fix(upgrade): prevent $digest from being called if it is already in progress

### PR DESCRIPTION
**Pull request by marjan-georgiev**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Calling rootScope.$digest causes a `$digest is already in progress` error when using upgrade along with @angular/flex-layout.

**What is the new behavior?**
`$digest` is not being called if it is already in progress.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
In a hybrid application, we are using @angular/flex-layout on different pages and when transitioning from a page to a new page the flex-layout invokes a zone.run which then triggers a digest, thus throwing this error.

### CODE REVIEW

**Comment by marjan-georgiev** [comment]
Screenshot of the stack trace:

image

**Comment by amcdnl** [comment]
This occurs in AngularJS 1.5 and 1.6 and Angular 2 and 4.

The issue is caused by flex layout forcing a `zone.run` here: https://github.com/angular/flex-layout/blob/master/src/lib/media-query/match-media.ts#L92-L95 and ngUpgrade is responding by running a digest here: https://github.com/angular/angular/blob/master/packages/upgrade/src/dynamic/upgrade_adapter.ts#L581-L582 .

Problem is the digest is already in progress, this safety check should address the digest already in progress race case.

If the team is interested in the stack trace, here is debug view of it:
- https://www.screencast.com/t/02lfzf9Y1
- https://www.screencast.com/t/PTXQRUI6DPEn 
- https://www.screencast.com/t/yzolX7Nrj

**Comment by gkalpak** [comment]
A minimal reproduction (e.g. using plnkr) would be much appreciated :wink:
BTW, has anyone tried this with `upgrade/static`?

**Comment by gkalpak** [comment]
I mean, it would probably not hurt to have "digest-in-progress" check, but identifying and evaluating the specific underlying issue with `flex-layout` might reveal a bug or something else that can be improved.

**Comment by amcdnl** [comment]
@gkalpak - We tried to make a demo reproduction, had no luck. Our toolchain is so complex and this is such an edge case it would be nearly impossible to simulate this issue outside of the environment. 

I don't think that flex-layout is doing anything wrong, it just happens to be the item raising the race case.

**Comment by amcdnl** [comment]
This is a blocker for me, is there any updates on this?

**Comment by gkalpak** [comment]
It is unfortunate that we can't get a reproduction, but this change is harmless, so if helps people I think we should get it in. @petebacondarwin WDYT?

**Comment by amcdnl** [comment]
Babel's async/await was causing the nested $digest cycles. Reference versions:


"babel-polyfill": "^6.22.0",
"babel-runtime": "^6.23.0",
"core-js": "^2.4.1",
"babel-polyfill": "^6.22.0",
"babel-runtime": "^6.23.0",
"babel-core": "^6.22.1",
"babel-loader": "^6.2.10",
"babel-plugin-external-helpers": "^6.22.0",
"babel-plugin-transform-runtime": "^6.22.0",
"babel-preset-angular2": "0.0.2",
"babel-preset-es2015": "^6.22.0",
"babel-preset-stage-0": "^6.22.0",

**Comment by petebacondarwin** [comment]
Ahah!! Great sleuthing @amcdnl and @marjan-georgiev

**Comment by geekchow** [comment]
How did u resolve this issue, I don't understand.

**Comment by jolafrite** [comment]
@amcdnl @marjan-georgiev Hi guys, how did you find out the async/await was the origin of your issue and how did you solve it ?

**Comment by petebacondarwin** [comment]
@geekchow - the resolution was not to use Babel `async` functions for writing async promise code.

**Comment by jolafrite** [comment]
@petebacondarwin thanks for your answer but this is not a solution for us as our project is mostly using async promises and would need a huge refactor.

**Comment by marjan-georgiev** [comment]
@jolafrite unfortunately, that is what we had to do to solve it. We had to refactor every async/await usage and replace it with a promise.

**Comment by petebacondarwin** [comment]
Just to be clear, promises are fine.
It is the use of Babel to transpile `async` and `await` syntax into vanilla promises, because the resulting transpiled code does not appear to work the same way as normal promises.

**Comment by jolafrite** [comment]
so change the babel async transformer should resolve the issue, I hope

**Pull request closed without merging**
