### PR TITLE
Adding my bio and picture for marketing section (Angular GDE's)

### PR DESCRIPTION
**Pull request by nirkaufman**
docs(aio): adding bio

adding information to the bio json

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
My GDE friends waiting for me to join..

## What is the new behavior?
I'm coming!

## Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```

### CODE REVIEW

**Comment by nirkaufman** [comment]
I signed it!

**Review by juleskremer — APPROVED** [review]

**Comment by petebacondarwin** [comment]
@nirkaufman - please can you fix the commit message. It is not following our guidelines (and hence failing the CircleCI test): https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by nirkaufman** [comment]
done. (hope so..)

On Sun, Jul 16, 2017 at 1:18 PM, Pete Bacon Darwin <notifications@github.com

**Comment by petebacondarwin** [comment]
You haven't pushed the fixed commit yet :-)

**Comment by nirkaufman** [comment]
I edit it in place on GitHub website (for the first time :) I will look for
the push button later today..




On Sun, Jul 16, 2017 at 5:47 PM, Pete Bacon Darwin <notifications@github.com

**Comment by petebacondarwin** [comment]
won't that create a new commit rather than amend the old one?

**Comment by nirkaufman** [comment]
I'm not sure...
usually, im doing my git stuff via the terminal.
But I'll check it out once I got home.

On Sun, Jul 16, 2017 at 6:29 PM, Pete Bacon Darwin <notifications@github.com

**Comment by petebacondarwin** [comment]
The terminal is our friend :-)

**Comment by petebacondarwin** [comment]
Nearly except that you didn't remove the old incorrect commit message. Can you squash the two commits please.

**Comment by petebacondarwin** [comment]
@nirkaufman - can you squash and fix the commit messages and rebase on master?

**Comment by nirkaufman** [comment]
done

On Fri, Aug 18, 2017 at 5:51 PM, Pete Bacon Darwin <notifications@github.com

**Review by juleskremer — APPROVED** [review]

**Comment by petebacondarwin** [comment]
Sorry @nirkaufman - you need to squash and rebase.

**Comment by petebacondarwin** [comment]
Sorry @nirkaufman - I gave up waiting for you to fix this PR. I tried rebasing it for you but since you did the changes on `master` it was not straightforward to push it back to your repository; and when I pushed it automatically closed this PR (and I cannot now re-open the PR nor push to your master branch any more, since it is not part of an open PR).

So I have recreated your commit on a PR of my own. See #19012

**Pull request closed without merging**
