### PR TITLE
docs: add a link to 'reactive forms' section

### PR DESCRIPTION
**Pull request by boazrymland**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by boazrymland** [comment]
I signed it!

**Review by brandonroberts — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
@boazrymland the table needs to be formatted correctly for the link to display. Will you take a look?

**Comment by boazrymland** [comment]
> @boazrymland the table needs to be formatted correctly for the link to display. Will you take a look?

Not sure I got it - what is still missing/wrong?
The change I introduced is very minimal.

**Comment by brandonroberts** [comment]
@boazrymland yes, but its not rendering correctly if you look at the preview https://pr27475-45787d6.ngbuilds.io/guide/frequent-ngmodules

**Comment by boazrymland** [comment]
@brandonroberts gotcha. I don't want to introduce another noise but how can I check something to see how its rendered before I commit?
Alternatively, if the above is not possible, I assume I can commit multiple more times to this branch and the PR will be updated automatically? (the last link you sent).

**Comment by brandonroberts** [comment]
@boazrymland you can run the docs locally to see changes.

```
git clone git@github.com:boazrymland/angular.git
cd angular
git checkout patch-1
cd aio
yarn setup
yarn serve-and-sync
```

You navigate to http://localhost:4200 to see the app
Once your done, you can commit the changes and push them up.

**Comment by boazrymland** [comment]
@brandonroberts thanks for the quick response. 

I've been able to run the code locally and played with it. Bottom line: no idea why the link isn't being rendered as it should. The syntax seems correct and used elsewhere successfully. 

More details: I've searched for a similar use case and and found in guide/module-types (module-types.md) a similar case with a table where in it there a 'td' that its content includes a link. I'm using the same syntax yet this still doesn't render the link properly. In fact, I've copied the link from that file to 'our file' (frequent-ngmodules.md) and it won't render the table correctly - rending the link from module-types.md incorrectly while markup is being rendered fine in its own URL.

Even more: I've put an 'a' tag instead of the markdown syntax and it was rendered fine:
`<td>When you want to build <a href='/guide/reactive-forms'>reactive forms</a></td>`

I'm assuming the problem is with some configuration elsewhere? 
I'm not familiar with this project (aio) so no idea where to start looking for, especially in light of the 'P.S' down below... :)

P.S.
What's the deal with the project size? It's HUGE. It took me almost 15 minute to clone and run (yarn) it locally on my MacBook Pro (2017). WebStorm is taking ages to index it.... :-\

**Comment by brandonroberts** [comment]
@boazrymland thanks for looking. It shouldn't take that long to clone the repo and get up and running, so I don't know what's going on there. We generate the links and verify that the internal URLs still exist, so we don't encourage using anchors for links.

**Comment by brandonroberts** [comment]
Will revisit once #26291 lands

**Pull request closed without merging**
