### PR TITLE
docs(aio): update AngularJS Quick Reference guide

### PR DESCRIPTION
**Pull request by markgoho**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

Cf. https://github.com/angular/angular/pull/19845#issuecomment-338612253 these are two changes that @gkalpak suggested making. The third one from this comment has a bad link.

### CODE REVIEW

**Comment by gkalpak** [comment]
I fixed the broken link in my comment, but since #19845 has been superseded my thrid point is not relevant any more. So, this PR is fine as it is 👍

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Can you change the commit message to something like:

> docs(aio): update AngularJS Quick Reference guide

**Comment by markgoho** [comment]
Sorry @gkalpak I'm trying `git commit --amend` but it keeps adding a merge commit with it each time.

**Comment by gkalpak** [comment]
No worries. I fixed it up and marked it for merge.

**Pull request closed without merging**
