### PR TITLE
docs: update example to reflect changes in Angular CLI version 15.

### PR DESCRIPTION
**Pull request by alan-agius4**
These changes include:
- Remove the usage of `enableProdMode`
- Remove `test.ts`, `polyfills.ts`, `karma.conf.js` and environment files which are no longer generated by default

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM

**Review by atscott — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Great cleanup, thanks @alan-agius4 👍

**Review by jessicajaniuk — APPROVED** [review]
LGTM!

**Review by pkozlowski-opensource — APPROVED** [review]

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Review by alxhub — APPROVED** [review]

**Review by alxhub — APPROVED** [review]
Reviewed-for: fw-security

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 32135b27a15c808336d8d70f14afde19f9c015d5.

**Comment by Flo0806** [comment]
Why environment variables are removed?

**Comment by alan-agius4** [comment]
> Why environment variables are removed? They are very useful for development (local server usage) and production (real server usage) as example.....

The environment files have been removed as they are no longer generated by default a new Angular CLI applications. Users however can still create them.

**Comment by Flo0806** [comment]
But I think this is a step backwards, isn't it? Every application use environment variables I think. And now i need to create it by my self, register it, create fileReplacement and so on... or am I missing something?
Basically, the functionality remains in Angular (i.e. how environment variables work)?

**Comment by alan-agius4** [comment]
No, not every application needs this. It’s also one less concept for new Angular users that they need to learn about immediately when they start experimenting with Angular.

It also depends on your use-cases, application and deployment strategy. 

Some users might choose a “promotion” style deployment pipeline were the app is built once and prompted from one environment to another. In this case the config would be retrieved during runtime.

**Comment by Flo0806** [comment]
> Nein, nicht jede Anwendung benötigt dies. Es ist auch ein Konzept weniger für neue Angular-Benutzer, das sie sofort lernen müssen, wenn sie anfangen, mit Angular zu experimentieren.
> 
> Es hängt auch von Ihren Anwendungsfällen, Ihrer Anwendung und Ihrer Bereitstellungsstrategie ab.
> 
> Einige Benutzer entscheiden sich möglicherweise für eine Bereitstellungspipeline im „Promotion“-Stil, bei der die App einmal erstellt und von einer Umgebung zur anderen aufgefordert wird. In diesem Fall würde die Konfiguration zur Laufzeit abgerufen werden.

Ok, I understand. So thx for your time and your answer! :-)

**Pull request closed without merging**
