### PR TITLE
docs: api pages improvements

### LINKED ISSUE #52641: docs: Add GitHub link to API details pages
The goal of the task is to add a button that opens the GitHub page of a given API.
According to the design, the button should be located in the header of the API Details Page.

Use `github-icon.tsx`.

### LINKED ISSUE #55196: Not all API documentation is visible
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

The information in JSDoc tags is not available in the API reference page. It appears that only the main documentation is presented. 

image
The APIs are deprecated but the description of why is not visible
image

image
`navigateByUrl` is missing the `@usageNotes` information
image

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

_No response_

### Please provide the environment you discovered this bug in (run `ng version`)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JeanMeche**
docs: improvements for API pages 

* add link for source files 
* add deprecation message for methods
* add usage notes for methods

Fixes #55196
Fixes #52641

Demo : 

* https://ng-dev-previews-fw--pr-angular-angular-55388-adev-prev-el9mru6m.web.app/api/router/Router
* https://ng-dev-previews-fw--pr-angular-angular-55388-adev-prev-el9mru6m.web.app/api/core/@defer

### CODE REVIEW

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by bencodezen — APPROVED** [review]

**Comment by bencodezen** [comment]
Thanks for adding the deprecation notice back in!

**Comment by bencodezen** [comment]
Going to wait for @atscott's review before setting it to merge state!

**Review by twerske — APPROVED** [review]

**Review by atscott — APPROVED** [review]
🥇

**Pull request closed without merging**
