### PR TITLE
refactor(core): Remove RootViewRef<T> because it is the same as ViewRef<T>

### PR DESCRIPTION
**Pull request by atscott**
Refactors that reworks some internal interfaces

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
👍

**Review by AndrewKushnir — APPROVED** [review]
Thanks for the cleanup 👍

**Comment by alxhub** [comment]
This PR was merged into the repository by commit a3028e23402a041527928eafdd3328ba6f08bc73.

**Comment by atscott** [comment]
blocked by [internal fix](cl/579228296)

**Comment by atscott** [comment]
This PR was merged into the repository by commit 33da677eccb65a2b3beac6435ec6a503c1cd16a2.

**Pull request closed without merging**
