### PR TITLE
test: remove bower and polymer benchmarks

### PR DESCRIPTION
**Pull request by IgorMinar**
the polymer benchmarks are super old and not relevant any more

and these benchmarks were the only reason why we needed bower at all

so long, bower. thanks for all the fish.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by gkalpak — COMMENTED** [review]
Commit message: _"bower and remove polymer benchmarks"_ --> _"remove bower and polymer benchmarks"_ ??

Also, if bower is no longer needed, why not remove it from `package.json`, `yarn.lock`, `DEVELOPER.md`, `.bowerrc`?

**Comment by IgorMinar** [comment]
thanks @gkalpak I'll fix that now

**Comment by IgorMinar** [comment]
@gkalpak PTAL

**Review by gkalpak — APPROVED** [review]
:tada: LGTM (as soon as CI is green)

**Comment by IgorMinar** [comment]
http://test/OCL:227874516:BASE:227874540:1546625817795:a422c8a7

**Comment by IgorMinar** [comment]
merge-assistance note: sauce flaked

**Pull request closed without merging**
