### PR TITLE
refactor(ViewPort): @Template -> @Viewport, ViewPort -> ViewContainer

### LINKED ISSUE #595: Rename @Template -> to @Viewport
Rename:
- `@Template` -> `@Viewport`
- `ViewPort` -> `ViewContainer`

Needed for: #596

### PR DESCRIPTION
**Pull request by vicb**
fixes #595

I have tried to not miss any reference to `@Template` & `ViewPort` in the code base and docs but I might have forgotten a few of them.

### CODE REVIEW

**Comment by vicb** [comment]
@tbosch When I try to run the benchmarks locally I get the following error:

```
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.0.20:49861/wd/hub
Started
F

## BENCHMARK js.ng2.changeDetection.jit
sample size 20
run id 4c8fa120-b2ba-11e4-8a59-ff6f428a1e35
params [
  {
    "name": "numberOfChecks",
    "value": 900000
  }
]
       index |      forceGc |       script |       render |     gcAmount | gcAmountInScript
        ---- |         ---- |         ---- |         ---- |         ---- |         ----
```

and then no more output.

However this also happens on master, any hint on what could go wrong ?

**Comment by vicb** [comment]
@mhevery I have been able to run the benchmarks thanks to @tbosch (the trick was not to use a bleeding edge of Chrome where protocal has changed). Nothing is broken !

Could you please review the PR ?

**Comment by mhevery** [comment]
Just FYI, for the docs we have decided to do editor wrap rather than column wrap. The reason for this is when you are adding and removing words you don't have to reflow the line breaks which than generates hard to read diffs.

**Comment by vicb** [comment]
@mhevery makes sense

**Pull request merged**
