### PR TITLE
docs: Add BootstrapOptions to publicApi

### PR DESCRIPTION
**Pull request by atscott**
`BootstrapOptions` is exposed through `PlatformRef#bootstrapModule` but
is not included in the public API so you cannot find it on angular.io.
This commit simply marks the interface as public API (as it should be).

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: fw-core, public-api

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api 
Reviewed-for: fw-core

**Comment by pkozlowski-opensource** [comment]
@atscott this LGTM although CI is unhappy (size tracking) - probably needs a rebase.

**Comment by atscott** [comment]
This PR was merged into the repository by commit 1f563206824b0e43e9b2353fa8f5e4e2b100a139.

**Pull request closed without merging**
