### PR TITLE
docs(aio): Add UpgradingAngularJS to education resources

### PR DESCRIPTION
**Pull request by samjulien**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[X] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information
Per discussion with @robwormald

### CODE REVIEW

**Review by StephenFluin — CHANGES_REQUESTED** [review]
Tiny little micro nit then happy to approve.

Can you replace the ’ (fancy single quote) character with the ' (normal single quote) character? I want to make sure this entry renders well in all browsers / locales, etc.

**Comment by samjulien** [comment]
Ah good catch! Fixed -- hopefully I did the rebase correctly!

**Review by StephenFluin — CHANGES_REQUESTED** [review]
Hrm. I don't think the rebase was successful, or what you intended. There should be just 1 commit, and there should be just 4-6 lines changes. Right now it looks like all of the resources have been touched (+177 -85).

Can you take another look and squash the commits?

**Comment by samjulien** [comment]
Done!

**Review by StephenFluin — APPROVED** [review]

**Comment by vicb** [comment]
@StephenFluin as a reviewer please add the "merge assistance" label when the CI is red but the PR still should be merge. Thanks.

**Pull request closed without merging**
