### PR TITLE
fix(router): update the location before activating components

### LINKED ISSUE #10909: Router: location.path is old URL during all component hooks. Updates after a tick.
**I'm submitting a ...**  (check one with "x")
```
[x] bug report 
[ ] feature request
[ ] support request 
```

**Current behavior**

The `location.path()` value remains the old URL after a component's Lifecycle Hooks have been called.

After a tick, the `location.path()` value becomes the current URL.

Have been told that this change arrived within the last few RCs.

**Expected/desired behavior**

Expect `location.path()` to become the new URL at least by `ngOnInit`. By that time, the navigation is complete and all components should be in the DOM.

**Reproduction of the problem**

http://plnkr.co/edit/WUbTMlukBIYJF3WXYVIj?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [all ]

### PR DESCRIPTION
**Pull request by vsavkin**
Closes #10909, #10845, #10827, #10704, #10930, #11004

### CODE REVIEW

**Comment by brandonroberts** [comment]
Can this PR be updated to fix the RouterLink that's not on anchor elements to be updated when a navigstion ends? It currently only updates in the RouterLinkWithHref

**Comment by vicb** [comment]
@brandonroberts could you take care of that & rebase ?

**Comment by vicb** [comment]
@vsavkin any chance you can rebase before our tomorrow ?

**Comment by vicb** [comment]
CI fixed in #11102

**Pull request closed without merging**
