### PR TITLE
docs(aio): Split the long router guide into separate pages

### PR DESCRIPTION
**Pull request by wardbell**
Effort approved by @juleskremer. The result ... we'll see what you think.

<hr>

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by juleskremer** [comment]
can you please remove the numbered sections; that was for the tutorial; not ready for this with fundamentals sections.

**Comment by wardbell** [comment]
@juleskremer Done.

**Comment by petebacondarwin** [comment]
@wardbell can you check that the new docs have the same changes that I put into the original document as part of my image sweep? Otherwise they might get lost in the rebase. See https://github.com/angular/angular/pull/16609/files#diff-8aadef410e1b120ea8201253373fe1e5

**Comment by splincode** [comment]
@wardbell what is the status of your pull request? is it still relevant? please fix conflicts if they exist

**Comment by brandonroberts** [comment]
Closing PR as lots of the additional pages have changed, but keeping for reference in future router guide updates.

**Pull request closed without merging**
