### PR TITLE
Additional fixes for webcontainer stackblitz examples

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
LGTM

Reviewed-for: global-approvers

**Review by aikithoughts — APPROVED** [review]
Looks good to me. Thanks.

Reviewed-for: global-docs-approvers

**Comment by petebacondarwin** [comment]
Caretaker: saucelabs failures are unrelated to this docs-infra change.

**Comment by atscott** [comment]
This PR was merged into the repository by commit b39fd5fe5012cdca14116055db17791a9c774e63.

**Pull request closed without merging**
