### PR TITLE
docs: New HTTP client - Handle request errors doc

### PR DESCRIPTION
**Pull request by trekladyone**
New doc extract from the original HTTP doc which is to be retired.

### CODE REVIEW

**Comment by trekladyone** [comment]
This doc is a part of the Gummybears project.

**Review by atscott — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
@trekladyone More dangling links:
```
Dangling links: 1 unmatched links. The following docs have links to URLs that do not exist
       - doc "guide/http-handle-request-errors" (content)  - from file "guide/http-handle-request-errors.md"
         - guide/http-handle-request-errors#config-service
```

**Comment by jessicajaniuk** [comment]
@trekladyone Can you squash these commits into one commit?

**Comment by trekladyone** [comment]
Deleted broken links because the correct links are to docs that are not yet merged. After merging all HTTP docs, the links can be updated.

**Review by jessicajaniuk — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 557ae661edf02b5f38371a4a0f338b7ea6fbdfac.

**Pull request closed without merging**
