### PR TITLE
feat(zone.js): add jest fakeTimers support

### LINKED ISSUE #38851: Add ability to fake date in jest tests or make `fakeAsync` work with `jest.useFakeTimers('modern')` and `jest.setSystemTime`
# 🚀 feature request

### Relevant Package
This feature request is for zone.js

### Description
I want to use fake dates in my jest tests (just like `jasmine.clock`), while using `fakeAsync` when I'm testing async functions. 

A recent addition to jest is the modern fake timers, which uses Sinon's fake timers that allows (among other things) to fake `date.now`.

### Describe the solution you'd like
I think we should write a patch for jest's `useFakeTimers`, or add the ability to fake the date natively in zone (by exposing `FakeDate` somehow and manipulating it). 

### Describe alternatives you've considered
I wrote it in the section above - 2 ways to solve this problem - patch jest's `setSystemTime` or expose a way to set a fake date manually by zone.js

Thanks!

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Close #38851, support `jest` fakeTimers APIs' integration with `fakeAsync()`.
After enable this feature, calling `jest.useFakeTimers()` will make all test
run into `fakeAsync()` automatically.

```
beforeEach(() => {
    jest.useFakeTimers('modern');
  });
  afterEach(() => {
    jest.useRealTimers();
  });

  test('should run into fakeAsync() automatically', () => {
    const fakeAsyncZoneSpec = Zone.current.get('FakeAsyncTestZoneSpec');
    expect(fakeAsyncZoneSpec).toBeTruthy();
  });
```

Also there are mappings between `jest` and `zone` APIs.

- `jest.runAllTicks()` will call `flushMicrotasks()`.
- `jest.runAllTimers()` will call `flush()`.
- `jest.advanceTimersByTime()` will call `tick()`
- `jest.runOnlyPendingTimers()` will call `flushOnlyPendingTimers()`
- `jest.advanceTimersToNextTimer()` will call `tickToNext()`
- `jest.clearAllTimers()` will call `removeAllTimers()`
- `jest.getTimerCount()` will call `getTimerCount()`

### CODE REVIEW

**Review by mhevery — APPROVED** [review]

**Comment by ahnpnl** [comment]
I like this 👍 

- Regarding to mapping between `jest` and `zone` APIs, that can be added to `jest-preset-angular` README so users don't always have to look into this PR.

- Regarding to detail usage, maybe `jest-preset-angular` can add to `README` as well for convenience.

**Comment by JiaLiPassion** [comment]
@ahnpnl , thanks, and this feature will not affect current zone.js integration with jest. So we can keep the backward compatibility for jest version `<27`, and also since jest use kind of `sandbox` for every test file, so I have to use a new test environment https://github.com/angular/angular/pull/39016/files#diff-90d0b342f3b5fa57a61adfc412606ddc to do the monkey patch, I will create a PR in `jest-angular-preset` to do it.

And since I am planning to add a new doc for `jest integration` later, so I will create doc in another PR.

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:334838066:BASE:334838099:1601571947945:f2844e02)

**Review by IgorMinar — APPROVED** [review]
lgtm, but I have to admit that I don't have the domain knowledge to thoroughly review some parts of this PR.

**Pull request closed without merging**
