### PR TITLE
fix(http): headers should be case-insensitive. spec at https://tools.…

### PR DESCRIPTION
**Pull request by asnowwolf**
**Please check if the PR fulfills these requirements**
- [x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

Could not get http headers by it's lowercase, etc.

**What is the new behavior?**

Convert header's key/name to lowercase before save it to internal map, so that it's case-insensitive. It's same as NodeJS. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Spec at https://tools.ietf.org/html/rfc2616

### CODE REVIEW

**Comment by asnowwolf** [comment]
I signed it

**Comment by asnowwolf** [comment]
I've signed the CLA for a long time, but the CLA check is failed, what's up?

**Comment by vicb** [comment]
Seems like you set me as the commit author for some reason. Try to amend the commit and set yourself as the author.
Also CI seems to fail, you might find help in the contributor doc at the root of the repo.
Finally what about storing normalized names in the map to make read access fast ? (I haven't checked the code in details)
Thanks

**Comment by asnowwolf** [comment]
Ok, thank you! It's my first PR. I'll try it again.

Normalize is a good idea, similar to NodeJS. but it broken many of unit tests.

**Comment by vicb** [comment]
Check the doc I mentioned and GH help for PR. Feel free to ask any question of you need.

**Pull request closed without merging**
