### PR TITLE
Rollback 20819

### PR DESCRIPTION
**Pull request by IgorMinar**

### CODE REVIEW

**Comment by IgorMinar** [comment]
FYI: @kara and @JLHwung  :-(

Kara can you please follow up on the failures and work with @JLHwung to recreate a corrected PR?

**Review by alxhub — APPROVED** [review]

**Review by kara — APPROVED** [review]
LGTM

**Comment by JLHwung** [comment]
> breaks google3 see http://cl/223526995

@kara I am not a Googler I don't know what is going on here. Could you brief it so I can work on a fix? Thank you.

**Comment by kara** [comment]
I haven't had a chance to look yet, but here is the error if you want to get started:

```ts
TypeError: this._validator is not a function

    at PatternValidator.validate (packages/forms/src/directives/validators.ts&l=420)
    at ../../../packages/forms/src/directives/normalize_validator.ts?l=14
    at ../../..//packages/forms/src/validators.ts?l=387
    at Array.map (<anonymous>)
    at _executeValidators (packages/forms/src/validators.ts&l=387)
    at ../../../packages/forms/src/validators.ts?l=350
    at ../../../packages/forms/src/validators.ts?l=387
```

**Comment by JLHwung** [comment]
Thanks for a quick update in a Friday afternoon. :D

`this._validator` is [created](https://github.com/angular/angular/blob/1439071b7eca045c668167089c55c9fc9da22502/packages/forms/src/directives/validators.ts#L414) in the `ngOnChanges` lifecycle method. The test failure should be resulted from that either `ngOnChanges` is not invoked or `pattern` is not in the `SimpleChanges`.

On the first hypothesis I recognize that there is a [`fixmeIvy`](https://github.com/angular/angular/blob/1439071b7eca045c668167089c55c9fc9da22502/packages/core/test/directive_lifecycle_integration_spec.ts#L34) test wrapper around the lifecycle method. If the lifecycle integration of `TestBed` is not working and the test `google3` is broken while Ivy mode is on, it would explain why `this._validator` is not a function.

On the second hypothesis, I learn that once the `pattern` input is set, the `onChanges` should be called with the values. This behavior is proved in both [Ivy mode](https://github.com/angular/angular/blob/1439071b7eca045c668167089c55c9fc9da22502/packages/core/test/render3/lifecycle_spec.ts#L2019) and [render2](https://github.com/angular/angular/blob/1439071b7eca045c668167089c55c9fc9da22502/packages/core/test/view/provider_spec.ts#L479). I believed this hypothesis can be rejected if both tests are green.

@kara Do I miss anything? What do you think?

**Comment by kara** [comment]
@JLHwung Ivy mode is not currently turned on in google3, so any issues in google3 would not be related to Ivy.

**Comment by JLHwung** [comment]
@kara If `ngOnChanges` lifecycle is invoked but `this._validator` is undefined, there lefts only the case when there is error thrown in `Validators.pattern`. If google3 is breaking on pr/20819, it could be the case where a string regex fails to be constructed when applied with an unicode flag.

I construct an example on [stackblitz](https://stackblitz.com/edit/angular-invalid-regex-error?file=src%2Fapp%2Fapp.component.ts) where the regex `/\a/u` throws an error and generates stacks resembling yours. Note that `/\a/` is equivalent to `/a/` when unicode flag is not set. In this case, there should be an error like `Invalid regular expression:` before the error stacks you listed.

**Comment by IgorMinar** [comment]
obsolete

**Pull request closed without merging**
