### PR TITLE
style(buildElementPropertyBindings): improve error message when binding to an known property

### PR DESCRIPTION
**Pull request by nosachamos**
Currently we alert the user that no such property exists for the given element,
but we could indicate that if user is attempting to bind to an attribute then
the attr. prefix should be used.

Part of #4385

### CODE REVIEW

**Comment by mgechev** [comment]
I guess your VS Code have removed `.settings/settings.json`, probably you should keep it.

**Comment by todoubaba** [comment]
VS Code 0.8 renames `.settings`. to `.vscode`.

**Comment by nosachamos** [comment]
@mgechev is it cool to keep the file's new location (under the .vscode folder) since I think most folks will be migrating to VS Code 0.8.0 or you guys prefer me to move it back to the root and update?

**Comment by nosachamos** [comment]
BTW, this is on me now to fix the clang formatting issue. Will do later tonight and update.

**Comment by pkozlowski-opensource** [comment]
@nosachamos I appreciate that you've bumped into this error while trying to bind to an attribute, but there are other cases: property not found, misspelled property etc. So I'm not sure how I feel about adding this attribute-specific hint here...

**Comment by nosachamos** [comment]
@pkozlowski-opensource I see, you have a point for sure. A hint here would have saved me some time since this is a special syntax one must learn in order to bind to attributes, but I suppose if the docs were completed I could have easily found that info over there. So not much of a benefit for GA.

**Comment by mhevery** [comment]
Closing, as pointed out here: https://github.com/angular/angular/pull/4396#issuecomment-143852898 Reopen new one if you have a better solution.

**Pull request closed without merging**
