### PR TITLE
docs: call interval methods explicitly from window

### PR DESCRIPTION
**Pull request by douglasdnzcarvalho**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

When running code examples on StackBlitz the TS compiler is not able to identify that the methods **setTimeout** and **clearTimeout** come  from *lib.dom.ts* and not from *@types/node*, and when you try to assign the return value from **setTimeout** to a number variable it complains with the message: Type 'Timer' is not assignable to type 'number'.

Issue Number: N/A

## What is the new behavior?

The TS Compiler on StackBlitz stop complaining.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by douglasdnzcarvalho** [comment]
> Calling `windows` directly would make the code non-SSR compliant. See [#48048](https://github.com/angular/angular/pull/48048#pullrequestreview-1179549187)

You got a good point, But I noticed that in the [style guide](https://angular.io/guide/styleguide) the window object is used, wouldn't it be interesting to remove the use of window in this section to standardize the documentation?

**Comment by jessicajaniuk** [comment]
It's probably better to update the style guide in this case as we don't want to break SSR compatibility.

**Comment by pkozlowski-opensource** [comment]
@douglasdnzcarvalho it sounds like the consensus here is that we do _not_ want to make the change in the examples but updated the style guide instead? I'm going to close this PR based on the discussion.

Still, there is a problem of stackblitz that you've described:

> When running code examples on StackBlitz the TS compiler is not able to identify that the methods setTimeout and clearTimeout come from lib.dom.ts and not from @types/node, and when you try to assign the return value from setTimeout to a number variable it complains with the message: Type 'Timer' is not assignable to type 'number'.

Could you please open an issue for this so we can find the best possible solution? Thnx!

**Comment by douglasdnzcarvalho** [comment]
> @douglasdnzcarvalho it sounds like the consensus here is that we do _not_ want to make the change in the examples but updated the style guide instead? I'm going to close this PR based on the discussion.
> 
> Still, there is a problem of stackblitz that you've described:
> 
> > When running code examples on StackBlitz the TS compiler is not able to identify that the methods setTimeout and clearTimeout come from lib.dom.ts and not from @types/node, and when you try to assign the return value from setTimeout to a number variable it complains with the message: Type 'Timer' is not assignable to type 'number'.
> 
> Could you please open an issue for this so we can find the best possible solution? Thnx!

@pkozlowski-opensource I've created this PR to update the style guide and keep all examples SSR compliant: #48480,
What do you think?

And about the StackBlitz problem, I think that the most reasonable solution is just type all interval variables as **any**  and make a comment to remember the reason.

**Pull request closed without merging**
