### PR TITLE
feat(service-worker): allow specifying maxAge for entire application

### PR DESCRIPTION
**Pull request by henry-alakazhang**
This commit adds an `applicationMaxAge` to the service worker configuration. When set, it will only assign a cached version to clients within the maxAge. Afterwards, it will ignored any expired application versions and fetch exclusively from the network. The default is `undefined`, for which the behaviour is the same as it currently is.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Issue Number: #39266

The index file (and therefore all application navigations) are cached indefinitely by the service worker.

## What is the new behavior?
An optional `applicationMaxAge` field in the service worker ignores the cache for all requests for versions older than that age.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

(field is optional)

### CODE REVIEW

**Comment by henry-alakazhang** [comment]
Wasn't sure exactly what API to use / where to put it - I've put it in the `AppVersion` fetch, but the logic could live the `driver.ts` as well.

Linked issue could also be solved by setting `maxAge` on asset groups, I think, but that felt a bit roundabout for dealing with navigation requests, and it also would require a lot of refactoring / duplication because the logic already exists for data groups.

**Comment by henry-alakazhang** [comment]
Hmm, I've realised that this doesn't work properly if the service worker process is shut down, as it will recreate the state and reset `installTime`. Instead this probably needs to use the manifest `timestamp` or persist the `lastUpdateCheck` to the DB

**Review by magyargergo — APPROVED** [review]

**Comment by thePunderWoman** [comment]
@henry-alakazhang Sorry this never got a code review. We think it's a reasonable change. Can you rebase? I'll take a look after you're able to do that.

**Comment by henry-alakazhang** [comment]
Sure, PR has updated (hopefully I rebased everything correctly and these things are all still in the right place).

**Comment by henry-alakazhang** [comment]
Hi @thePunderWoman, would you be able to take a look at this now?

**Review by thePunderWoman — APPROVED** [review]
LGTM! Thanks for your contribution!

**Comment by thePunderWoman** [comment]
Caretaker note: this is safe to merge with current approvals as it was discussed during a triage meeting.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 8ddce80a0bab4ebbd0f7db1c85ee27e4f0249db9.

The changes were merged into the following branches: main

**Pull request closed without merging**
