### PR TITLE
docs: correct first sentence of marketing docs.

### PR DESCRIPTION
**Pull request by NachmanBerkowitz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jenniferfell** [comment]
@NachmanBerkowitz : This is a good improvement. After you sign the CLA (instructions above), we can help you get this reviewed and merged. Thanks for contributing!

**Comment by NachmanBerkowitz** [comment]
I signed it!

**Comment by NachmanBerkowitz** [comment]
I signed it!

**Comment by NachmanBerkowitz** [comment]
I'm seeing that my CLA hasn't registered yet. I made this commit on Github and my email is marked private. Is that a problem? Do I have to pull locally and push?

**Comment by brandonroberts** [comment]
Does the email you used to sign the CLA match your GitHub email?

**Comment by NachmanBerkowitz** [comment]
I signed it!

**Comment by NachmanBerkowitz** [comment]
Thanks. I checked that cla and noticed I had an extra space in my user
name. Now it was exceptd.

**Comment by StephenFluin** [comment]
The original wording is correct in that Angular lets developers use web technologies (HTML, JavaScript, CSS) to build applications for a multitude of platforms, including the web, but also including desktop and mobile.

**Pull request closed without merging**
