### PR TITLE
docs: add awade jigsaw into resources

### PR DESCRIPTION
**Pull request by rdkmaster**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

[Jigsaw](https://github.com/rdkmaster/jigsaw) provides a set of web components based on Angular. It provides 35 components, 5 containers, 5 services, 4 directives in the current version and the list is increasing.

It is supporting the development of all applications of Big Data Product of [ZTE](http://www.zte.com.cn). There are more than 50 web applications are built based on Jigsaw, most of them have been deployed in our customers' servers all around the world. We got lots of praises from these customers.

### CODE REVIEW

**Comment by kara** [comment]
@brandonroberts Did you mean to approve this?

**Comment by brandonroberts** [comment]
@kara no, @StephenFluin usually provides approvals for things being added to the resources page.

**Review by StephenFluin — CHANGES_REQUESTED** [review]
As the site is in chinese, we should let users know. Can you add `(Chinese)` or the Chinese language characters to the title?

**Comment by rdkmaster** [comment]
@StephenFluin I've added `(Chinese)` into the title, can you review again please, thanks

**Review by StephenFluin — APPROVED** [review]

**Pull request closed without merging**
