### PR TITLE
docs: update resource.md

### PR DESCRIPTION
**Pull request by jesusreal**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

N/A

## What is the new behavior?

N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

While reading this documentation page: https://angular.dev/guide/signals/resource, I identified a couple of improvements and this PR applies them.

### CODE REVIEW

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by thePunderWoman** [comment]
@jesusreal Looks like lint is failing due to the commit message. Can you change it to just `docs: update resource.md` instead? The `(core)` part is unnecessary.

**Comment by jesusreal** [comment]
Thanks for your feedback, @thePunderWoman 🫶 
I didn't find a way to re-run the check. Hope you can do it for me 🙏

**Comment by thePunderWoman** [comment]
@jesusreal it looks like you just changed the github PR header. You'll actually need to change the commit header, which is different. To do this, in terminal in the branch you have, run `git commit --amend` and then change the commit message to `docs: update resource.md`, and then once you're done force push that change. You can do that with `git push origin patch-2 --force-with-lease`.

**Comment by jesusreal** [comment]
@thePunderWoman this should be ready to go now.

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit 753e6f49e184f8c65f612b40efae331b375b1146.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
