### PR TITLE
feat(router):add mergeQueryParams option to routerLink

### PR DESCRIPTION
**Pull request by dejour**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines:      https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
#13806

**What is the new behavior?**
merge new query params with current when mergeQueryParams present

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by vicb** [comment]
I'm not sure if we want this (breaking) behavior by default. 
We should probably add an extra option.

**Comment by dejour** [comment]
is this sauceLab's problem?

**Comment by DzmitryShylovich** [comment]
yeap

**Comment by dejour** [comment]
@vicb I changed this feature to option.

**Comment by paramsingh88** [comment]
Why is this PR open?? Please merge it. It's really needed @dejour

**Comment by dejour** [comment]
@paramsingh88  you need to ping @vicb

**Comment by paramsingh88** [comment]
@vicb Please merge it man.

**Comment by vicb** [comment]
```ts
@Input() preserveQueryParams: boolean;
@Input() mergeQueryParams: boolean;
```

I don't like to have this 2 overlapping `@Input`

What about
- deprecating `@Input() preserveQueryParams: boolean;`
- introducing `@Input() queryParamsHandling: string; // (preserve|merge|'')`

**Comment by DzmitryShylovich** [comment]
`queryParamsOptions`

**Comment by dejour** [comment]
I agree with  `queryParamsHandling`

**Comment by laco0416** [comment]
`queryParamsBehavior` / `queryParamsStrategy` / `queryParamsMode`

**Comment by dejour** [comment]
close this because of ugly commit

**Pull request closed without merging**
