### PR TITLE
fix(aio): transitions between pages

### LINKED ISSUE #20996: aio heading flashes during page transitions
I'm not sure what introduced this but as of recently (last day?) I noticed the following flashing/transition when loading the aio homepage:
aio-home-flash

as well as when transitioning between pages:

aio-home-flash-2

The problem is especially visible when navigating from Resources to Docs:
aio-home-flash-3

### PR DESCRIPTION
**Pull request by gkalpak**
- Avoid unnecessary animations, style transitions, repositioning on initial rendering.
- Better handle transitioning from/to Home page (which is the only page with transparent top-menu).
- Better coordinate sidenav and hamburger animations with page transitions.
- Improve fade-in/out animations.
- (Slightly re-organize/clean up top-menu CSS.)

Fixes #20996.

### CODE REVIEW

**Comment by IgorMinar** [comment]
wow.. that's a lot of changes. This looks like a major improvement. Do you think that we could make the transitions shorter? especially transitions between various marketing pages seem to take a bit too long.

**Comment by IgorMinar** [comment]
I'm sorry to be annoying but here is a detail that allows me to tell apart any web app from a polished native app: when a screen renders, every element should be positioned only once without things being reposition and re-layout again and again as more resources are downloaded.

Let's take an look at how we render the homepage and break it down into 5 steps:

Step 1: we render the top header with the menu items:

screen shot 2017-12-17 at 8 49 58 pm

Step 2: the Angular logo used in the header comes in and pushes all the menu items to the right causing them to reposition:

screen shot 2017-12-17 at 8 50 12 pm

At this point we also rendered the slanted hero background but for some reason the very left part is cut off.

Step 3: the slanted hero backround is now fully rendered but it's position has shifted just a bit - it's not as high as in step 2. Also the "One framework. ..." header has jumped up (and if I'm not crazy the font that we use to render the header has changed 🔎👀).

screen shot 2017-12-17 at 8 50 22 pm

Step 4: The hero background and the "news banner" font & button changed color - maybe this is a transition of some sort. (if it is we should try to disable it since most transition during the initial rendering are only causing visual distraction). Also notice that the header background is very different from the hero background causing a weird visual discrepancy between the two neighboring areas.

screen shot 2017-12-17 at 8 50 41 pm

Step 5: The header background finished it's transition to the same color as the hero background finalizing the initial rendering.
screen shot 2017-12-17 at 8 50 56 pm
----

Could you please try to change the stylesheets so that as the page renders and various resources are downloaded all the renderings are additive and don't cause re-positioning and re-layout of various visual elements? Thanks! 

----
The screenshots above were extracted from a profile I captured via chrome dev tools. You can inspect the profile by loading it via this file:
[Profile-20171217T204302.txt.gz](https://github.com/angular/angular/files/1566645/Profile-20171217T204302.txt.gz)

**Comment by gkalpak** [comment]
> wow.. that's a lot of changes.

:grin: 90% of the changes are just refactoring (moving things around, cleaning up) or adding tests.

> Do you think that we could make the transitions shorter? especially transitions between various marketing pages seem to take a bit too long.

All transitions use the same duration (333ms fade-out + 333ms fade-in). Changing the durations is simple, but having different duration for different pages will need some work. (It is not much work, but I don't want to end up with a mini-`@angular/animations` over time. I was hoping to switching to the real `@angular/animations` at some point, since we are bundling it already (for Material) and it is so many features.)

##
WRT profile screenshots:

- **step 1**: Fixed.
- **step 2**/**step 3**:  Fixed the left offset and slight movement issue. What header fonts are you referring to? The ones in the top-menu? (I don't think we change fonts there.)
- **step 4**:  I couldn't reproduce the "news banner font & button changed color". Nor do I see a style that would affect them after it is rendered.
  Regarding the top-menu background, that's the best I could come up with (given its current transparent background on Home page) :grin: Let's discuss in the next meeting.

##
@IgorMinar, PTAL. Once we are happy with the changes, I will add/update tests.

**Comment by IgorMinar** [comment]
The latest version looks amazing!

I don't see the font change any more. Maybe it was just a visual illusion because everything was moving around too much.

Could you please change all the fade-in and fade-out transitions to last just 200ms on both.

Otherwise this is good to go. ❤️

**Review by IgorMinar — APPROVED** [review]
Please decrease the duration of transitions to 200ms otherwise lgtm

**Comment by gkalpak** [comment]
- [x] Decrease duration to 200ms.
- [x] Add/Update tests.
- [x] Split up into separate commits.
- [x] Rebase on master.
- [ ] Pass on Travis.
- [ ] Add the `merge` label.
- [ ] Profit.

**Comment by IgorMinar** [comment]
The CI is still not passing. It looks like either a legit error or a flake. I'm restarting the job now to see which one it is.

**Pull request merged**
