### PR TITLE
docs: add missing Oxford comma in styleguide

### PR DESCRIPTION
**Pull request by simonua**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Good catch, @simonua. Could you amend the commit message to something with a little more specific info such as:

```
docs: add missing Oxford comma in styleguide
```

For anyone curious about our writing style choices and specifically comma-delineated opinions 😁, check out https://developers.google.com/style/commas

Thanks for this PR, @simonua. Please tag me when you're ready and I'll help move this PR through the process.

**Comment by simonua** [comment]
Hi @kapunahelewong, I rewrote the commit message. Does this work now?

**Comment by kapunahelewong** [comment]
Yes, that's good, @simonua, but I forgot to mention...could you squash too? We only want one commit per PR (Sorry I hadn't mentioned it before!). Thanks for working with me. 😊

**Comment by simonua** [comment]
Hi @kapunahelewong, thank you for your guidance. I squashed and force-pushed since it's ok to rewrite history on origin here. If this looks good to you, I will see to the other PRs.

**Comment by kapunahelewong** [comment]
Good thinking, @simonua. It squashed all right, there's only one little thing to clear out and that's easily achieved on your end with a `git commit --amend`. This part should be deleted:
Screen Shot 2019-08-08 at 11 27 45 AM

Usually we put extra info like [this](https://github.com/angular/angular/pull/31949/commits) in the commit message (click on the three dots to see it expanded). Or, in the case of something like a typo, there's usually nothing.

**Comment by simonua** [comment]
That's my bad, @kapunahelewong. I updated the commit now.

**Review by kapunahelewong — APPROVED** [review]
Thanks for all your help, @simonua! LGTM 😊

**Comment by kapunahelewong** [comment]
Caretaker, this is a docs only change. Please let me know if there's anything else I can do to help this through. Thank you!

**Comment by kapunahelewong** [comment]
Hey @simonua, I've restarted the tests that I could in these PRs. If they still fail, could you rebase? Sometimes it's just a flake and re-running can sort it out, but if it doesn't we may have to rebase. It seems like you know how to do it, but if you have any questions, just tag me. I'm happy to help out. :)

**Comment by simonua** [comment]
Hi @kapunahelewong, I'd be happy to do it but what do I need to rebase. I am up to date with origin at this time and just have this single commit. Are you just looking for a bump? Would a `git commit --amend` and a slightly different commit message suffice otherwise?

**Comment by kapunahelewong** [comment]
Ah you're right. You're up-to-date, @simonua. You're good. I'll keep an eye on these and see how the tests go. I think if anything fails it's nothing you've done. We'll see how the tests go. 🤞🏼

**Comment by kapunahelewong** [comment]
Caretaker, this is a docs only change and the failures appear unrelated. If there's anything I can do to help get this green, please let me know. Thank you!

**Pull request closed without merging**
