### PR TITLE
Add Feature Routing to style guide

### PR DESCRIPTION
**Pull request by akilisosa**
docs(style-guide): Add feature routing to style guide

This request follows #34805 and suggests some best practices when adding feature routing.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #34805

Currently there is no mention of feature routing

## What is the new behavior?

This proposes some best practices when using the routing module

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jelbourn** [comment]
@mgechev could you provide input on whether you think this is a good fit for the style guide?

**Comment by mgechev** [comment]
Sorry for missing this notification. I'd consider this as a good practice.

**Comment by atscott** [comment]
@mgechev - I rebased this PR and updated the commit message. PTAL.

**Comment by mgechev** [comment]
Reading at the practice again, I'm not convince we should recommend it. Routing modules add more complexity and a little bundle size overhead without bringing much value.

We had a style guide discussion about a year ago where we agreed to discourage them.

**Pull request closed without merging**
