### PR TITLE
use gulp-watch instead of gulp.watch

### PR DESCRIPTION
**Pull request by IgorMinar**

### CODE REVIEW

**Comment by alexeagle** [comment]
what's the difference? does this fix one of our issues?

**Comment by IgorMinar** [comment]
it uses only one FD per `watch` invocation as opposed to one FD per watched directory and any subdirectory.

**Comment by IgorMinar** [comment]
I improved the commit message with the explanation

**Comment by alexeagle** [comment]
oh, that sounds like fewer FDs. Sorry I couldn't help Yegor today :)

**Comment by IgorMinar** [comment]
landed as 5e4fa5cf078db667a7b45dcf2e45b9a9f46b2690

**Pull request closed without merging**
