### PR TITLE
chore(package): bump reflect-metadata version

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by IgorMinar** [comment]
hi there. you will also need to update the `npm-shrinkwrap.json` and `npm-shrinkwarp.clean.json`.

see the instructions here: https://github.com/angular/angular/blob/master/npm-shrinkwrap.readme.md

**Comment by douglasduteil** [comment]
Oh sorry.
I don't have a MacOs but I will try this out...

**Comment by douglasduteil** [comment]
... The installation has failed dramatically multiple times
I'm proposing a new commit with what you might be expected from this PR.
Is it enough ?

**Comment by IgorMinar** [comment]
yeah. lgtm

**Comment by douglasduteil** [comment]
Great :D

**Pull request closed without merging**
