### PR TITLE
docs(aio): Updating the Essential JS 2 UI Components for Angular.

### PR DESCRIPTION
**Pull request by hariharanjv**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Essential JS 2 UI Components are not present in the UI components list.

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Adding Essential JS 2 UI Components for Angular on the resources file.

### CODE REVIEW

**Comment by 4kochi** [comment]
The demo app is broken.

`http://ej2.syncfusion.com/demos/#/form-validator/default.html`

```
Uncaught TypeError: Cannot read property 'samples' of undefined
    at T (index.min.js:19)
    at _ (index.min.js:19)
    at o.execute (index.min.js:7)
    at s.dispatch (index.min.js:7)
    at s.dispatch (index.min.js:7)
    at Object.init (index.min.js:19)
    at index.min.js:19
    at Object.<anonymous> (index.min.js:19)
    at Object.495 (index.min.js:19)
    at r (common.min.js:1)
```

**Comment by hariharanjv** [comment]
We have fixed the broken demo links. You can check now.

**Comment by YogeshwaranRam** [comment]
@4kochi can you merge pull request?

**Comment by 4kochi** [comment]
@YogeshwaranRam no, i cannot merge it. I am no maintainer of this repo.

**Comment by bharathm03** [comment]
@petebacondarwin Can you please merge this request?

**Comment by petebacondarwin** [comment]
We need someone like @StephenFluin  to approve this.

**Review by StephenFluin — CHANGES_REQUESTED** [review]
The URL linked to doesn't seem Angular specific. I found a couple pages such as http://ej2.syncfusion.com/home/angular.html or the Angular-specific demos, but we require that you link directly to a page that is targeted for Angular developers, so that it's easy for them to install and get started without having to search around for the Angular wrappers.

**Comment by bharathm03** [comment]
@petebacondarwin and @StephenFluin Thank you for suggestion. We will look for landing page specific to Angular and update the pull request.

**Comment by bharathm03** [comment]
@petebacondarwin we have updated angular specific product page for Essential JS 2. Can you please approve the changes?

**Review by petebacondarwin — APPROVED** [review]
LGTM

**Review by StephenFluin — APPROVED** [review]

**Pull request closed without merging**
