### PR TITLE
refactor(ivy): name LQuery object for easier memory allocation tracking

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
This is similar to the `TView` refactoring done in https://github.com/angular/angular/pull/30542

### CODE REVIEW

**Review by kara — APPROVED** [review]
LGTM

**Comment by kara** [comment]
Needs presubmit

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:249894669:BASE:249894681:1558731572401:1da349f7)

**Comment by AndrewKushnir** [comment]
Merge assistance: Codefresh is flaky.

**Pull request closed without merging**
