### PR TITLE
[WIP] feat(benchpress): rewrite benchpress in AtScript

### PR DESCRIPTION
**Pull request by tbosch**

### CODE REVIEW

**Comment by mhevery** [comment]
@tbosch should this be close/merged?

**Comment by tbosch** [comment]
Reviewed with @yjbanov

**Comment by yjbanov** [comment]
Woohoo! Can I push it to pub? LMK

**Comment by tbosch** [comment]
Not yet. We need some changes as Chrome will change their perfLog protocol
in 2 releases...

**Pull request merged**
