### PR TITLE
refactor(core): Remove stop propagation behavior.

### PR DESCRIPTION
**Pull request by tbondwilkinson**
This removes stop propagation behavior from `EventContract` and removes the associated stop propagation logic.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Stop propagation can be requested from `EventContract`.

Issue Number: N/A

## What is the new behavior?
Stop propagation is not allowed in `EventContract`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by tbondwilkinson** [comment]
Tested with [TGP](https://fusion2.corp.google.com/presubmit/626482081/OCL:626482081:BASE:627019292:1713828051592:abeef7ce/targets)

**Review by thePunderWoman — APPROVED** [review]
LGTM

**Review by rahatarmanahmed — APPROVED** [review]

**Comment by tbondwilkinson** [comment]
Caretaker note: Test failures are pre-existing and unrelated to this PR.

**Review by alan-agius4 — APPROVED** [review]
This is great!

**Review by tbondwilkinson — COMMENTED** [review]
TESTED=[TGP](https://fusion2.corp.google.com/presubmit/626482081/OCL:626482081:BASE:627019292:1713828051592:abeef7ce/targets)

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 4bf3d89dae513d8e46bf2f3b2c447bfa98e9c23a.

**Pull request closed without merging**
