### PR TITLE
docs: rename AngularConsole and provide new link

### PR DESCRIPTION
**Pull request by NickHodges**
The link https://angularconsole.com no longer works.
The project has been renamed Nx Console, and this change reflects that new name and new link.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [X ] No

### CODE REVIEW

**Review by petebacondarwin — COMMENTED** [review]
Why the additional formatting changes (e..g changing bullet points from `*` to `-` and changing italicised text from `*some*` to `_some_`?

**Comment by NickHodges** [comment]
Pete --

OMG -- a lack of attention to detail on my part is why -- Visual Studio
Code's Markdown plugin did that. I apologize.

I'll work on fixing that.

Nick

**Comment by pkozlowski-opensource** [comment]
My understanding is that the current plan is to remove all references to the angularconsole.com as the  Nx Console is not the direct replacement, see https://github.com/angular/angular/pull/37608

**Comment by NickHodges** [comment]
Pawel -

Ah, okay.

I guess at this point I'll just withdrawal this current PR.....

Nick

**Comment by pkozlowski-opensource** [comment]
> I guess at this point I'll just withdrawal this current PR.....

@NickHodges yeh, this would be my understanding based on the dev rel position https://github.com/angular/angular/pull/37608#issuecomment-644803669

**Comment by NickHodges** [comment]
Thanks guys -- Lessons learned:

1.  Don't use VS Code for editing *.md files
2.  Do a bit more research before getting excited that you found a bad
link.  ;-)

Nick

**Pull request closed without merging**
