### PR TITLE
build: update karma-sauce-launcher to latest version with heartbeat to prevent idle timeout

### PR DESCRIPTION
**Pull request by devversion**
Updates the `karma-sauce-launcher` to the latest version that comes with
the heartbeat implemented. Whenever we create an instance of a browser
in Saucelabs, we need to send a Selenium command every X seconds as otherwise
Saucelabs will terminate the session due to it thinking the session is already
unused. This is especially a problem for Karma unit tests as there is no
selenium command at all, except for the initial one loading the Karma site.

The latest version of the launcher has implemented an interval that
dispatches a noop selenium command every X seconds to notify Saucelabs
that the instance is still active.

The current version of the launcher does not do that. This is likely
the source of some disconnects because after 10-13min, the SL browser
is terminated but Karma still waits some minute after realizing the
browser is actually disconnected.

We (the Angular team), contributed to that version in the past since
the heartbeat was very flaky.. and we removed it (with the requirement
that tests need to override the Saucelabs `idleTimeout`; which is limited nowadays
limited to 10min; which previously was allowed to be 15min IIRC).

With the new version a lot has changed, the underlying Selenium client has changed
so it's worth trying again with the heartbeat re-implemented; it worked pretty
well so far in the COMP repo).

### CODE REVIEW

**Review by alxhub — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
@devversion could you please rebase this PR when you get a chance? There is some instability/flakiness in 12.2.x branch due to Saucelabs timeouts and this PR might improve the situation.

// @dylhunn

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by dylhunn** [comment]
This PR does not merge cleanly into 12.2.x, mind doing a rebase?

**Comment by atscott** [comment]
This PR was merged into the repository by commit 116877b4edf14411716b75eddea67a66cddd1af6.

**Pull request closed without merging**
