### PR TITLE
docs: added the alt attribute to the imag tag and replaced the i tag with the em tag

### PR DESCRIPTION
**Pull request by alkavats1**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by alxhub** [comment]
Hi @alkavats1,

A couple questions:

* Can you squash these commits down into a single update? Currently there are 3 commits, 2 of which share the same title.
* Why are we dropping `alt` attributes on ``? Apologies if I don't have the right context here. We should also add a description of why we're making these changes on the commit itself.

**Comment by alkavats1** [comment]
> Hi @alkavats1,
> 
> A couple questions:
> 
> * Can you squash these commits down into a single update? Currently there are 3 commits, 2 of which share the same title.
> * Why are we dropping `alt` attributes on ``? Apologies if I don't have the right context here. We should also add a description of why we're making these changes on the commit itself.

Hi @alxhub, I have updated the commit message. 
And for the second ques, The alt attribute provides alternative information for an image if a user for some reason cannot view it (because of a slow connection, an error in the src attribute, or if the user uses a screen reader).
Please review now, Thanks

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Review by alxhub — APPROVED** [review]
Reviewed-for: fw-core,fw-security

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit ec9ee9e5bf0b0671a04808d3a1844ecf68b0d842.

**Comment by alkavats1** [comment]
> This PR was merged into the repository by commit [ec9ee9e](https://github.com/angular/angular/commit/ec9ee9e5bf0b0671a04808d3a1844ecf68b0d842).

Hi @pkozlowski-opensource  Could you merge this PR and then close it?
Thanks

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 5dc7a99393aadd5a32d943f1d87e3b5e4b6dba97.

**Pull request closed without merging**
