### PR TITLE
docs: correct typo

### PR DESCRIPTION
**Pull request by jaysonacosta**
Service worker card contains typo 'us' when it should be 'use.'

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jessicajaniuk — APPROVED** [review]
LGTM :cookie:

**Comment by jaysonacosta** [comment]
I followed the steps, I think everything should be good now.

**Comment by AndrewKushnir** [comment]
@jaysonacosta thanks for improving Angular docs!

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit d183e7d736beff06ec9789543e8a955a2540b7c7.

**Pull request closed without merging**
