### PR TITLE
docs: add younes jaaidi to GDE resources

### PR DESCRIPTION
**Pull request by yjaaidi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]

**Comment by petebacondarwin** [comment]
Sorry @yjaaidi - please rebase on the latest master to resolve the CircleCI job failures: https://app.circleci.com/pipelines/github/angular/angular/38344/workflows/b13dc895-051f-4e83-9593-d28a274a6279/jobs/1067360

**Comment by yjaaidi** [comment]
✅ Done!

Sorry for the noise Pete! I thought it would be faster to make the change on the github web UI 😅

**Review by petebacondarwin — APPROVED** [review]

**Review by twerske — APPROVED** [review]
LGTM

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit e78c7cc239d2c2c14f5eb1636902d727b227ffa9.

**Pull request closed without merging**
