### PR TITLE
docs(docs-infra): handle the long API names in the API cards

### PR DESCRIPTION
**Pull request by Ahmed-Hakeem**
I've added elipsis to address any overflow occurs in the card's header.

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
image

## What is the new behavior?
image

### CODE REVIEW

**Comment by JeanMeche** [comment]
Hi, we're going to change the design a bit with #58610, so we won't need that change.

**Comment by Ahmed-Hakeem** [comment]
> Hi, we're going to change the design a bit with #58610, so we won't need that change.

Thank you for the hint

The new design will definitely handle it in the tablet and desktop sizes .... but I think we still need this to handle the mobile size view

**Comment by Ahmed-Hakeem** [comment]
image

**Comment by JeanMeche** [comment]
In this case we should probably go for an elipsis isn't of adding a scrolling zone. It would make for a better UX.

**Comment by Ahmed-Hakeem** [comment]
How about doing the same behavior in the SubNavigation list of the API ref pages  .... I see the same issue happened there.
I believe in the subnav items we need a tooltip appears on hover to show the full text or something similar

image

**Review by JeanMeche — APPROVED** [review]

**Comment by JeanMeche** [comment]
Yes we could improve that too in a follow-up PR !

**Review by pkozlowski-opensource — APPROVED** [review]

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit 6da74c6bbbb2a03c7af391e84b5e102ab049641d.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
