### PR TITLE
feat(core): drop support for TypeScript 4.4 and 4.5

### PR DESCRIPTION
**Pull request by crisbeto**
Drops support for TypeScript older than 4.6 and removes some workarounds in the compiler.

BREAKING CHANGE:
TypeScript versions older than 4.5 are no longer supported.

### CODE REVIEW

**Comment by alan-agius4** [comment]
Shouldn’t we just drop support for TypeScript 4.5 3P like we did in similar cases previously? Otherwise we’d need to support 4.5 until v15.

We can still support 4.5 in G3 until the update is completed.

**Comment by crisbeto** [comment]
I wanted to keep the integration test so that's why I didn't drop it. It's likely that g3 will be on 4.6 before we hit feature freeze so we can drop it then.

**Comment by alan-agius4** [comment]
You can still keep the integration test, as that uses TSC and not NGC. 

But it’s your call.

**Review by JoostK — COMMENTED** [review]
I'd also prefer to drop both TS 4.4 and TS 4.5 at the same time, and just keep the typings tests around for g3. It would be a single breaking change instead of two, resulting in cleaner release notes (or we'd have to manually update those when the release is cut)

**Comment by crisbeto** [comment]
Good point that the integration test only covers 3P, I've removed it in addition to bumping the minimum version to 4.6.

**Review by JoostK — APPROVED** [review]
LGTM

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Review by josephperrott — APPROVED** [review]
LGTM

**Comment by dylhunn** [comment]
This PR was merged into the repository by commit c9d566ce4b6e9097d9eceb7ac3964a0b25c404ad.

**Pull request closed without merging**
