### PR TITLE
bug(upgrade): ensure upgraded ng1 components are compiled before down…

### LINKED ISSUE #7525: UpgradeAdapter throws "Error: Expecting HostViewFactoryRef..." when downgrading a ng2 component
Downgrading ng2 components crashes when mixing ng1 and ng2 components to a certain level of complexity. "ng1 app" -> "ng2 comp" -> "ng1 comp" -> "inner ng2 comp"

http://plnkr.co/edit/5yVFDBOcRHIwGrWwewrV?p=preview

I've seen #7027, but I'm definitely not bootstrapping before downgrading.

Tested on 
- Angular version: 2.0.0-beta.9
- Browser: Chrome, Firefox, Edge

### PR DESCRIPTION
**Pull request by kvantetore**
- **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [?] Docs have been added / updated (for bug fixes / features)
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  Bug fix for interleaved ng1 and ng2 components using angular2/upgrade. Ensures that upgraded ng1 components are compiled before downgrading ng2 components. 

Before this fix, upgraded ng1 components containing downgraded ng2 components would fail to compile.

Fixes https://github.com/angular/angular/issues/7525

### CODE REVIEW

**Comment by mhevery** [comment]
Apologies for getting so long to get to this. I have been trying to merge this in, but I am not having much success. Can I ask you to rebase to the latest master, and get the tests to run? I will then merge it in ASAP.

**Comment by mhevery** [comment]
@hannahhoward could I trouble you to help me get this PR rebased on master and ready to merge in?

**Comment by hannahhoward** [comment]
@mhevery I will take a look but I believe this is no longer neccesary after #8949 and also I tried this fix while working on this PR and it broke other tests (ironically cause not having NG1 components upgraded already breaks downgraded ng2 components that need ng1 upgraded compenents. But I will rebase and give it a shot.

**Comment by mhevery** [comment]
@hannahhoward  If you don't think it is necessary, then we can just close it. What do you think?

**Comment by hannahhoward** [comment]
I think this is best, unless there is a specific need I'm not aware of.

**Pull request closed without merging**
