### PR TITLE
chore(build): opt-in analytics

### PR DESCRIPTION
**Pull request by joshperry**
To easily enable for CI processes: https://docs.npmjs.com/files/package.json#config

### CODE REVIEW

**Comment by IgorMinar** [comment]
hi there. what are you trying to solve with this change?

the analytics is in place so that we know how the angular team uses our tooling, track latency of common workflows, find bottlenecks that slow us down and then address those.

**Comment by joshperry** [comment]
The use of analytics for the team seems like it provides a lot of benefits, and I think that's important, and great.

However, there are those of us that are not part of the Angular team who would prefer not to have a bunch of HTTP requests logging our information in your GA account every time we initiate a build.

This is a privacy matter and should be a choice.

I'm open to suggestions for better ways to handle this. Opting in through an npm or environment config variable seemed like a pretty low-impact change.

**Comment by IgorMinar** [comment]
thanks for rising this. we are discussing this. we'll post updates here and we'll resolve this issue by beta.1 the latest.

**Comment by joshperry** [comment]
Sounds good. Thanks, Igor.

**Comment by mhevery** [comment]
@IgorMinar what is your plan with this? Will close in a week if no progress is made.

**Comment by mhevery** [comment]
This PR is stale (does not rebase; pass CI; had no activity for a while). It is probably our fault, and we are sorry. In an effort to keep our PR queue under control, and prevent us from taking too long to get back to you we are cleaning up the queue. Unfortunately this means that this PR is getting closed.

If you would like to resurrect this change, please rebase on master, make the tests pass and create a new PR.

**Pull request closed without merging**
