### PR TITLE
feat(docs-infra): white background and corresponding figure updates

### PR DESCRIPTION
**Pull request by sjtrimble**
- Update layout background to white for improved legibility
- Update figure styles to be more visually appealing and easily identifiable in new white background (similar to Google Material Design documentation site examples)

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #23983

## What is the new behavior?
- White background on general layout where reading text can be found
- Figures now have a gray lightbox to be more easily identifiable and its images sit within a card to match the Material Design guidelines / styles

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sjtrimble** [comment]
Updated figures style for reference:
aio-figures

Format requires:
`<figure class="lightbox">...`
  ` <div class="card">...`
  `   ...`

FYI @jenniferfell

**Comment by IgorMinar** [comment]
If I run accessibility test against the homepage preview of this pr at web.dev I still get the following warning:
screenshot_20190127-201214

**Comment by IgorMinar** [comment]
Can you please take a look and test the preview urls on web.dev? Thanks!

**Comment by sjtrimble** [comment]
Yes I'll take a look. I'm not sure why it's saying that because a lot of the colors meet WCAG AAA requirements.

**Comment by sjtrimble** [comment]
I ran a check on several of the elements - see the color contrast scores. I did update the footer to meet WCAG AA requirements.

aio-accessibility-color-review

**Comment by petebacondarwin** [comment]
Accessibility report looks pretty good now: https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://pr28396-fe5094c.ngbuilds.io/

**Review by petebacondarwin — APPROVED** [review]

**Comment by petebacondarwin** [comment]
@sjtrimble I think you will need to rebase to fix the CI build failure.

**Comment by sjtrimble** [comment]
@petebacondarwin I just rebased and pushed, hopefully that fixes the build failure. I will work on the other accessibility items separately and work through replacing the figures with the new layout throughout the site.

**Comment by petebacondarwin** [comment]
re-ran jobs a few times but this seems to fail consistently

screenshot 2019-02-13 at 10 19 39

**Comment by sjtrimble** [comment]
@petebacondarwin This never got merged, right? What do we need to do to move it forward (besides rebasing)?

**Comment by petebacondarwin** [comment]
Can you endure that the e2e tests pass please.

**Comment by sjtrimble** [comment]
@petebacondarwin Ready for you to review/approve, tests are now passing

**Review by petebacondarwin — APPROVED** [review]

**Pull request closed without merging**
