### PR TITLE
docs: include svg files in example zipper

### LINKED ISSUE #31537: Live example broken
# 📚 Docs or angular.io bug report

### Description

https://angular.io/guide/template-syntax
There is a live example from the official doc thats not working: https://angular.io/generated/live-examples/template-syntax/stackblitz.html

The live example error says:
Import error, can't find file: ./svg.component.svg

If I download the example and npm install it, I got the error:
ERROR in ./src/app/svg.component.ts
Module not found: Error: Can't resolve './svg.component.svg' in 'C:\Users\Elias\Desktop\New folder\src\app'

### What's the affected URL?**
https://angular.io/generated/live-examples/template-syntax/stackblitz.html

## 🔥 Exception or Error
<pre><code>

Import error, can't find file:
./svg.component.svg

</code></pre>

### PR DESCRIPTION
**Pull request by santoshyadavdev**
Fixes #31537

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
Included svg files in example zipper.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31537

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
Thx for the fix, @santoshyadav198613 💯
Have you checked whether there is an SVG file in one of the other examples, that would be unintentionally included? (I doubt that will be the case, but it never hurts to double-check :wink:)

**Comment by santoshyadav198613** [comment]
> Thx for the fix, @santoshyadav198613 
> Have you checked whether there is an SVG file in one of the other examples, that would be unintentionally included? (I doubt that will be the case, but it never hurts to double-check )

There is one svg which is mentioned here https://angular.io/guide/template-syntax#event-binding-event

**Comment by gkalpak** [comment]
Thx for taking a look, @santoshyadav198613. It seems like that SVG file should be included (i.e. it was a bug that it was not included), so this PR will fix that as well.

I, also, noticed there is another SVG file, [built-in-directives/src/assets/potted-plant.svg][1], which doesn't seem to be used. Can you add another commit removing this unused file (actually the whole [built-in-directives/src/assets/][2] directory)?

Finally, I also noticed that [event-binding/src/assets/teapot.svg][3] is still not included in the online, stackblitz example. Can you look into fixing that as well (in addition to the fix you did for the zipper)? 🙏 

[1]: https://github.com/angular/angular/blob/c529be9f2427d7bd1b0fded23dca58019634f8cd/aio/content/examples/built-in-directives/src/assets/potted-plant.svg
[2]: https://github.com/angular/angular/blob/c529be9f2427d7bd1b0fded23dca58019634f8cd/aio/content/examples/built-in-directives/src/assets
[3]: https://github.com/angular/angular/blob/c529be9f2427d7bd1b0fded23dca58019634f8cd/aio/content/examples/event-binding/src/assets/teapot.svg

**Comment by santoshyadav198613** [comment]
> Thx for taking a look, @santoshyadav198613. It seems like that SVG file should be included (i.e. it was a bug that it was not included), so this PR will fix that as well.
> 
> I, also, noticed there is another SVG file, [built-in-directives/src/assets/potted-plant.svg](https://github.com/angular/angular/blob/c529be9f2427d7bd1b0fded23dca58019634f8cd/aio/content/examples/built-in-directives/src/assets/potted-plant.svg), which doesn't seem to be used. Can you add another commit removing this unused file (actually the whole [built-in-directives/src/assets/](https://github.com/angular/angular/blob/c529be9f2427d7bd1b0fded23dca58019634f8cd/aio/content/examples/built-in-directives/src/assets) directory)?
> 
> Finally, I also noticed that [event-binding/src/assets/teapot.svg](https://github.com/angular/angular/blob/c529be9f2427d7bd1b0fded23dca58019634f8cd/aio/content/examples/event-binding/src/assets/teapot.svg) is still not included in the online, stackblitz example. Can you look into fixing that as well (in addition to the fix you did for the zipper)?

Done, added the svg files for stackblitz as well.

**Comment by gkalpak** [comment]
Thx, @santoshyadav198613. Can you also update the commit message to reflect the content of the PR?

**Comment by santoshyadav198613** [comment]
> Thx, @santoshyadav198613. Can you also update the commit message to reflect the content of the PR?

Done, let me know if it looks fine.

**Comment by gkalpak** [comment]
Looks great 👍 Thx, @santoshyadav198613!

**Comment by gkalpak** [comment]
**merge-assistance:** Global approval for this docs-only change.

**Comment by kapunahelewong** [comment]
Thanks so much for this, @santoshyadav198613!

**Pull request closed without merging**
