### PR TITLE
Make Ivy the default in Angular!

### PR DESCRIPTION
**Pull request by alxhub**
🍃

### CODE REVIEW

**Review by kara — APPROVED** [review]
LGTM

**Review by IgorMinar — APPROVED** [review]
lgtm but I wish you left a note why the tsc passthrough option was removed - I suspect that it's because we implemented it initially to make Ivy JIT testing easier but then realized that we don't need it and we should just use tsc proper instead. Can you please clarify? thanks!

**Comment by alxhub** [comment]
@IgorMinar I've been focused on getting the tests in the repo fixed - I still need to go back and add proper commit messages. Doing that now!

**Comment by AndrewKushnir** [comment]
- [VE Presubmit](http://test/OCL:264483531:BASE:264483556:1566340867699:73e3de41)
- [Ivy Presubmit](http://test/OCL:264483531:BASE:264483712:1566340920680:6f633947)

**Comment by alxhub** [comment]
Caretaker: I restarted a flaky CI test (`test_docs_examples_ivy`), but just in case it flakes again I'm adding `merge-assistance`.

**Comment by AndrewKushnir** [comment]
FYI, Ivy and VE presubmits look normal.

**Pull request closed without merging**
