### PR TITLE
feat(ngFor): Support convenience view local in ngFor

### PR DESCRIPTION
**Pull request by gionkunz**

### CODE REVIEW

**Comment by gionkunz** [comment]
I know this is as easy as index === 0 but it just feels better to use a convenience view local `first` instead of expressions within my templates.

**Comment by PascalPrecht** [comment]
@gionkunz Would be cool if this gets a test too! :)

**Comment by gionkunz** [comment]
@PascalPrecht Yeah, I wanted to check the reaction first before I spend more time on this ;-)

**Comment by tbosch** [comment]
Yes, this would be nice. But we need tests :-)

**Comment by gionkunz** [comment]
Sure, I'll come up with the tests shortly.

**Comment by gionkunz** [comment]
@tbosch should be fine on the testing side

**Comment by gionkunz** [comment]
@tbosch any updates on this? Do I need to rebase to the latest and greatest?

**Comment by alxhub** [comment]
Rebased for merge as #8013.

**Pull request closed without merging**
