### PR TITLE
build: fall back on default version number if there the .git directory is not found

### PR DESCRIPTION
**Pull request by i3anaan**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
The build script fails when git log fails, for example because it cannot access the .git directory.
`./build.sh`
`fatal: Not a git repository (or any of the parent directories): .git`

## What is the new behavior?
A warning is shown that says the current version cannot be determined and a placeholder (invalid) version would be used, but the build finishes.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
I was unsure where/if documentation updates need to be made, because of this I left the checkbox open

### CODE REVIEW

**Comment by i3anaan** [comment]
Updated description to better clarify that depending on the command `git` is fine, but depending on the `.git` folder is not fine in my (and my colleagues) opinion

**Comment by i3anaan** [comment]
Also do note that this changes the current behaviour when angular is a git submodule: It will pretty much always fail to find the .git directory in the current context, therefore defaulting to the placeholder version. This would be different than before, where the folder where the .git file points to is accessed.

I know realise this might be an important change, and that therefore this fix might need to solve the issu in a different way than is currently proposed. I am eager to hear other opinions

**Comment by robwormald** [comment]
We're in the process of migrating away from the mega-build.sh, and it seems odd you'd want to use this extremely-specific-to-this-repo build machinery? Could you clarify your use case?

**Comment by i3anaan** [comment]
@robwormald My use case is as follows;
We have a repository for which angular is a submodule, we then wanted to add the angular source files into a docker container to have an environment to build and test. This failed because we only copied the submodule into the docker container, and not the entire repository (which is where the .git folder is located).
It might be very specific, and we did find a workaround.

I am really interested to hear you are in the process of replacing the build.sh file though, is there anywhere I can see a preview or documentation/design on this?

**Comment by alexeagle** [comment]
`build.sh` is now outdated and replaced by `bazel build`

**Pull request closed without merging**
