### PR TITLE
fix/refactor(common): prevent duplicate URL change notifications from `SpyLocation` and use `TestBed.inject` in the `Location` test suite

### PR DESCRIPTION
**Pull request by LayZeeDK**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
1. `SpyLocation` emits duplicate notifications to URL change listeners when multiple are registered.
1. `Location` uses the `private` acces modifier for the private `_urlChangeSubscription` member.
1. `location_spec.ts` uses the weakly typed `inject` to resolve dependencies.

Issue Number: As discussed in #37404

## What is the new behavior?
1. `SpyLocation` only emits one URL change notification to all listeners.
1. `Location` use `@internal` JSDoc annotations for all private members.
1. `location_spec.ts` uses the strongly typed `TestBed.inject` to resolve dependencies.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Cc @atscott

### CODE REVIEW

**Comment by LayZeeDK** [comment]
Hey @atscott,

I've tried different things to get around this, but several other tests are broken by switching from `@internal` annotations to `private` access modifiers because of weirdness when using `MyClass implements MyOtherClass`.

```
packages/router/test/integration.spec.ts:1225:27 - error TS2352: Conversion of type 'Location' to type 'SpyLocation' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
 

 
1225          const location = TestBed.inject(Location) as SpyLocation;
 
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
packages/router/test/integration.spec.ts:1252:27 - error TS2352: Conversion of type 'Location' to type 'SpyLocation' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
 

 
1252          const location = TestBed.inject(Location) as SpyLocation;
 
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
packages/router/test/integration.spec.ts:1318:25 - error TS2352: Conversion of type 'Location' to type 'SpyLocation' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
 
  Type 'Location' is missing the following properties from type 'SpyLocation': urlChanges, _history, _historyIndex, setInitialPath, and 3 more.
 

 
1318        const location = TestBed.inject(Location) as SpyLocation;
 
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
```

This will break a lot of userland tests as well as `SpyLocation` is the most important stub for working with the `RouterTestingModule`.

What do we do? TypeScript suggests to use `SpyLocation extends Location` instead. We could do that, but it seems odd and might introduce additional work.

**Comment by LayZeeDK** [comment]
🏎️ Here we go, @atscott

**Review by atscott — APPROVED** [review]
Great, thanks so much for working on this!

**Review by AndrewKushnir — APPROVED** [review]
LGTM 👍

**Pull request closed without merging**
