### PR TITLE
Feature/date string.pipe

### PR DESCRIPTION
**Pull request by laskoviymishka**
- [+] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [+] Tests for the changes have been added (for bug fixes / features)
- [+] Docs have been added / updated (for bug fixes / features)

Implement feature ISO string support on date pipes (issue #3261)
Here is sample compare to current behaivior with modified pipe (DatesPipe is modified one).
_http://plnkr.co/edit/NmEvlURlpG9b8COUOjtn?p=preview_

This is small PR which not contains any breaking change.

### CODE REVIEW

**Comment by laskoviymishka** [comment]
I signed it!

**Comment by laskoviymishka** [comment]
Sorry for this mess, i'll close this PR and create new one with squashed changes.

**Comment by MattDHill** [comment]
What is the status of this feature? Timeframe?

**Comment by laskoviymishka** [comment]
@MattDHill this feature already closed via different PR (see _https://github.com/angular/angular/pull/7794_) 
It provide pretty much same implementation, but was opened earlier

**Comment by MattDHill** [comment]
I'm still getting the same error. The pipe will not accept "1464042935120" or "2014-11-20T05:11:03.277+00:00". Do I need to update something? I'm currently using rc-1

**Comment by laskoviymishka** [comment]
This pr was merged couple hours ago, do most probably it still not published. I think it will be a part of rc2

**Pull request closed without merging**
