### PR TITLE
docs(http): fixed unit test for error catching

### LINKED ISSUE #19499: Documenation issue - MockBackend
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Documentation for MockBackend contains an error for unit test:
https://angular.io/api/http/testing/MockBackend

```js
it('getHeroes() while server is down', fakeAsync(() => {
       let result: String[];
       let catchedError: any;
       this.heroService.getHeroes()
           .then((heroes: String[]) => result = heroes)
           .catch((error: any) => catchedError = error);
       this.lastConnection.mockRespond(new Response(new ResponseOptions({
         status: 404,
         statusText: 'URL not Found',
       })));
       tick();
       expect(result).toBeUndefined();
       expect(catchedError).toBeDefined();
     }));
```
The above code should test the service when the backend application is not available, by providing a mock error response. Although, the test will fail as the mock response from the server is valid (it does not simulate a error response, but valid response with an error status 404).

## Expected behavior
Instead of using mockRespond it should use mockError.

```js

it('getHeroes() while server is down', fakeAsync(() => {
       let result: String[];
       let catchedError: any;
       this.heroService.getHeroes()
           .then((heroes: String[]) => result = heroes)
           .catch((error: any) => catchedError = error);
       this.lastConnection.mockError(new Response(new ResponseOptions({
         status: 404,
         statusText: 'URL not Found',
       })));
       tick();
       expect(result).toBeUndefined();
       expect(catchedError).toBeDefined();
     }));
```

## Minimal reproduction of the problem with instructions
Simply, run unit tests from Angular documentation:
https://angular.io/api/http/testing/MockBackend

## What is the motivation / use case for changing the behavior?
Documentation should provide correct examples.
It might take a while for new developers to find an issue with failing tests.

## Environment

<pre><code>
Angular version: 4 & 5

Browser:
N/A for documentation issue.
 
For Tooling issues:
N/A for documentation issue.

Others:
This issue exists in Angular 5 page as well: https://next.angular.io/api/http/testing/MockBackend
</code></pre>

### PR DESCRIPTION
**Pull request by Bartosz-D3V**
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
The example unit test for MockBackend should test the service when the backend application is not available, by providing a mock error response. Although, the test will fail as the mock response from the server is valid (it does not simulate a error response, but valid response with an error status 404).
This merge request fix this issue by replacing MockResponse with MockError.

Issue Number: 19499

## What is the new behavior?
Example source code for testing the MockBackend with error thrown, works as expected after replacing MockResponse with MockError.

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information
Fixes #19499

### CODE REVIEW

**Comment by Bartosz-D3V** [comment]
CLA signed.

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
LGTM, but someone from the `http` owners needs to approve as well.
(There is also the CLA thing that didn't seem to work. Are you using the same email on GitHub and on git commits?)

BTW, adding `Fixes #19499` on your commit message (or on the PR description) will ensure that the associated message will be closed when the PR is merged.

**Comment by Bartosz-D3V** [comment]
I've edited my email to correct one.
Will edit the commit message as well to include Fixes #19499.

**Comment by brandonroberts** [comment]
@Bartosz-D3V are you still interested in landing this PR? If so, you need to sign the CLA. Once CI is green we should be good to go.

**Comment by Bartosz-D3V** [comment]
Hi @brandonroberts 
I had an issue with CLA as I used old email address when creating this merge request.
I opened a new one: https://github.com/angular/angular/pull/25306 with CLA signed.
I am sorry for confusion and opening double merge request - I hope it is not a big problem.

**Comment by brandonroberts** [comment]
Not a problem at all. We'll get the new one through CI so it can it land.

**Pull request closed without merging**
