### PR TITLE
build(aio): make plunker works with rxjs operators

### PR DESCRIPTION
**Pull request by Foxandxss**
Interestingly it was working on my demos, now it can't find that operators. Luckily, an easy fix.

Also updated TS to 2.4.2 for plunkers.

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Waiting for Travis to pass before marking this for merging.

**Comment by sarunint** [comment]
This will break in `rxjs@5.5.3` since the file will be gone.

Reference: ReactiveX/rxjs#3025

**Comment by mlc-mlapis** [comment]
... we are also waiting for https://github.com/ReactiveX/rxjs/pull/3025

**Comment by petebacondarwin** [comment]
@mlc-mlapis  Good to know but since this PR locks down the version to 5.5.2, this should not break unexpectedly. We can revisit it once 5.5.3 is released.

**Pull request merged**
