### PR TITLE
docs(aio): fix typo in attribute-directives

### PR DESCRIPTION
**Pull request by panakour**

### CODE REVIEW

**Comment by panakour** [comment]
I signed it!

**Comment by trotyl** [comment]
Your commit message is invalid, please have a look at [Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit).

Likely: `docs(aio): fix typo in attribute-directives`.

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
Thx for the PR 👍

Could you update the commit message as @trotyl suggested?
Also, the CLA doesn't seem to be signed. You need to ensure that you have signed the CLA using the same email that appears on your commit.

**Comment by panakour** [comment]
ok now I think it's ok

**Comment by trotyl** [comment]
Commit message is not the title of this PR...

**Comment by panakour** [comment]
@trotyl ok I just amend my commit :)

**Comment by gkalpak** [comment]
Thx @panakour.
In case you are curious, you can read more about the commit message guidelines [here][1] :grin:

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Pull request closed without merging**
