### PR TITLE
fix(localize): Copy same plural rules from sr-Cyrl.ts

### PR DESCRIPTION
**Pull request by TrickMist**
These are the same rules that need to be used for all sr languages

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Function for plural rules always returns 5, instead of returning correct number.

Issue Number: N/A

## What is the new behavior?
Rules are copied from Serbian Cyrilic.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x ] No

### CODE REVIEW

**Comment by TrickMist** [comment]
@googlebot I signed it!

**Comment by petebacondarwin** [comment]
I'm very sorry @TrickMist but as you can see here https://github.com/angular/angular/blob/aabc87cd1061a2e415e0f293c85a7fc2e11effc8/packages/common/locales/sr-Latn-ME.ts#L9-L10 this file is generated and so we must not modify it manually.

If you feel that there is a bug in the locale data then it must be taken up with the CLDR project at http://cldr.unicode.org/index/bug-reports

Closing as this is not actionable by us.

**Comment by TrickMist** [comment]
Thanks, @petebacondarwin . I haven't noticed that, sorry.

**Comment by TrickMist** [comment]
@petebacondarwin , can you help me?
I opened the ticket as suggested:
https://unicode-org.atlassian.net/browse/CLDR-14234

It seems that they also cannot do much, as this is expected behaviour on their side.

What can be done so that we have correct plural rules for every locale we are going to use?

**Comment by petebacondarwin** [comment]
You can try providing your own locale data files, and just register them manually with ['registerLocaleData()`](https://angular.io/api/common/registerLocaleData).

Something like:
```
import { registerLocaleData } from '@angular/common';
import srLatnMe from './app-locales/sr-Latn-ME';
registerLocaleData(srLatnMe, 'sr-Latn-ME');
 ```

**Pull request closed without merging**
