### PR TITLE
build: update yarn version

### PR DESCRIPTION
**Pull request by alexeagle**
Some engineers were already on Yarn 0.10.x which was permitted by the range in our package.json#engines
However this introduced 'integrity sha512' lines into the yarn.lock files.
Then when engineers use yarn 0.9 (in particular, Bazel did this) then the lock files get tons of meaningless edits.
We could force everyone back to yarn 0.9 but this commit chooses to instead advance everyone past 0.10

### CODE REVIEW

**Comment by ocombe** [comment]
Can you lock yarn version to 1.12.x in package.json to avoid this kind of errors in the future?

**Review by ocombe — APPROVED** [review]

**Comment by ocombe** [comment]
Sounds good, once the tests pass

**Review by IgorMinar — CHANGES_REQUESTED** [review]
Where does yarn that is installed on circleci come from? based on the CI errors we run 1.10.x on circle, which causes CI to fail.

In the past it came from the docker image but now I don't see where it's installed. Do we rely on yarn being provided by the default docker image? that seems wrong.

**Comment by alexeagle** [comment]
@IgorMinar yes we pick up a yarn version from docker circleci/node:10.12 (which is already 1.10.1)
We could manually install a different yarn, as we used to do. I looked through the history of the dockerfile but didn't find it.
It's much easier to make the yarn range `>=1.10.1 <1.13.0` - this works with our current docker image as well as the defaults supplied by rules_nodejs

**Comment by IgorMinar** [comment]
how about we add an additional step to our CI jobs that will install the exact version of yarn based on the variable set in https://github.com/angular/angular/blob/master/.circleci/env.sh ?

**Comment by alexeagle** [comment]
sounds great but I think we should merge this to fix the breakage and do a fancier setup later

**Review by IgorMinar — APPROVED** [review]
don't we need to also relock the files?

**Comment by alexeagle** [comment]
@IgorMinar this commit also updates to latest rules_nodejs, where Bazel will no longer touch your lock file.

**Comment by IgorMinar** [comment]
Awesome! Thanks

**Pull request closed without merging**
