### PR TITLE
docs: update links to the calling-compilecomponents section

### PR DESCRIPTION
**Pull request by amayer42**
## PR Type
What kind of change does this PR introduce?

- [x] Documentation content changes

## What is the current behavior?

Clicking on links to the [Calling compileComponents()](https://angular.dev/guide/testing/components-scenarios#calling-compilecomponents) section do not apply the correct fragment. Instead of "calling-compilecomponents" they set the fragment to "compile-components".

Issue Number: N/A

## What is the new behavior?

I have updated links to the section to use "calling-compilecomponents" as the fragment instead of "compile-components".

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
LGTM

**Comment by atscott** [comment]
@amayer42 could you please rebase this PR? Looks like there are conflicts with other things that got merged

**Comment by amayer42** [comment]
@atscott hoping that I did it right, never really used rebase before. The commits look right to me now though, so fingers crossed.

**Comment by amayer42** [comment]
@atscott @JeanMeche , is there anything else that I need to do on this? Or does this just need @alxhub 's approval at this point? I just want to make sure that I'm not missing something.

**Review by atscott — APPROVED** [review]

**Comment by atscott** [comment]
This PR was merged into the repository by commit 2eb83c6e86ce54c27c0fa845e6e077192547a7b9.

**Pull request closed without merging**
