### PR TITLE
docs: Remove outdated Webpack guide and example

### LINKED ISSUE #23937: Webpack guide should be deprecated/removed
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

The Webpack guide is outdated, but still available through direct links and search results. Since we're promoting use of the CLI, we should add a deprecation warning to the top of the guide or remove it.

### PR DESCRIPTION
**Pull request by brandonroberts**
A supporting Webpack guide will be introduced as part of the guidance
for ejecting from the Angular CLI.

Closes #23937

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

cc: @StephenFluin @jenniferfell @filipesilva

### CODE REVIEW

**Review by StephenFluin — APPROVED** [review]
LGTM

**Comment by jenniferfell** [comment]
@petebacondarwin @gkalpak Hi. Could we ask one of you for a favor? We need a pull-approve from angular.io team. What is this PR you ask? We're removing outdated webpack doc and examples, per direction from Brad and his leadership team. Stephen has approved from that team. We just need the bots to be fed, and they demand an approval from angular.io team. :-) Thanks!

**Review by gkalpak — APPROVED** [review]
LGTM
I think you can also remove [these scripts][1] and probably some dependencies from `tools/examples/shared/package.json` (such [this][2], [that][3], etc.).

[1]: https://github.com/brandonroberts/angular/blob/79aa3477f550d478949510de6c5da5f47f912427/aio/tools/examples/shared/boilerplate/systemjs/package.json#L29-L31
[2]: https://github.com/brandonroberts/angular/blob/79aa3477f550d478949510de6c5da5f47f912427/aio/tools/examples/shared/package.json#L61
[3]: https://github.com/brandonroberts/angular/blob/79aa3477f550d478949510de6c5da5f47f912427/aio/tools/examples/shared/package.json#L63

**Comment by gkalpak** [comment]
> We just need the bots to be fed, and they demand an approval from angular.io team.

Smart bots. Give them a pat in the back. They did a good job here 💯 

##
<sub>
> Could we ask one of you for a favor?

Now you owe me one 😛 
</sub>

**Pull request closed without merging**
