### PR TITLE
docs(service-worker): fix example

### PR DESCRIPTION
**Pull request by gkalpak**
## PR Checklist
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] ~~Tests for the changes have been added (for bug fixes / features)~~
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
- [x] Documentation content changes

## What is the current behavior?
The ServiceWorker example is broken.

## What is the new behavior?
The ServiceWorker example is fixed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Related to #27332.

### CODE REVIEW

**Review by IgorMinar — APPROVED** [review]
The first commit has no tests and from the commit description it's absulutely unclear what you are fixing. Can you please clarify the commit message and add a test if reasonable? The second commit looks good. Thanks

**Comment by gkalpak** [comment]
I made some changes to `run-example-e2e.js`, so that it is possible to test the kind of things that my former 1st (now 3rd) commit fixes.

The setup is not ideal - at some point we should rethink/refactor our docs examples testing infra/tooling (e.g. run unit tests, build in production mode, have meaningful tests for all examples, etc.). But this requires more time than I was willing to spend atm (with other higher priority items pending), so I did the minimum required changes to be able to run other kinds of tests on a per-example basis.

LMK what you think, @IgorMinar, @petebacondarwin.

**Comment by petebacondarwin** [comment]
Typo in 2nd commit message:

```
Previously, cli-based docs examples where tested using `yarn e2e ...`.
```

where -> were

**Review by petebacondarwin — APPROVED** [review]

**Comment by cexbrayat** [comment]
We got bitten by this bug yesterday without getting why, so this PR is 👍 

If I may, the situation is even tricker: *any* `setInterval` in the application will prevent the `isStable` observable to emit `true` (for example if there is a polling process somewhere).

I added a note in the documention to warn about that in this PR #28102

**Comment by gkalpak** [comment]
Yeah, this is pretty nasty. We have #21842 to provide more options wrt to SW registering. Hoping to get it in soon.

**Pull request closed without merging**
