### PR TITLE
docs(aio): update resources to include NinjaCodeGen Angular CRUD gene…

### PR DESCRIPTION
**Pull request by chauey**
…rator

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ x ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ x ] No
```

### CODE REVIEW

**Comment by chauey** [comment]
I signed it!

**Comment by StephenFluin** [comment]
@chauey I'm having a lot of issues when I visit the page. See the attached gif. Things seem to randomly jump and move around.

9bmzzqjxna

**Comment by chauey** [comment]
@StephenFluin thanks for the review and report! I believe it's related to the sorting codes, which is not very reliable. Will look into correcting that now; not super easy to reproduce. (That landing page we created in the 48hr angular attack hackathon 😝)

**Comment by chauey** [comment]
@StephenFluin I believe this has been corrected. I pushed/deployed. If it still has a problem please let me know what environment. Thanks! 😄

**Comment by Toxicable** [comment]
Just re-checked this and the home page is still very much stutters around.
Also commits need rebasing

**Comment by chauey** [comment]
@Toxicable much thanks for the review/report/info. We will check again. I had replaced the orderBy codes and was not able to reproduce any minor problem. The major problem above we never have been able to reproduce. The only thing we have seen so far is just 2 of the rows switching places when scrolling or adding a record, but the page does not jump around so badly. We have been testing on chrome, edge, firefox on Windows 10 and changing window size and zoom. Let us know if any other details to help. Will continue to look into it and the rebase. Thanks! BTW, my birthday today, can't think of what to do yet. 🍻 cheers!

**Comment by chauey** [comment]
i had issues with the rebase interactive squashing, but hopefully i corrected it. Let me know otherwise, and may need tips. 

still not able to reproduce the website issue. is that on Mac and chrome? Any other details? Tried to ask a couple of friends on mac and some remote cross-browser test services but no luck yet.

thx!

**Comment by StephenFluin** [comment]
Is the website open source? I could take a look at the source code. Right now the chart isn't jumping for me, but I can't scroll because the scroll event is recalculating the whole page or something using up 100% of my CPU?

**Comment by chauey** [comment]
@StephenFluin That would be awesome and much appreciated! My CPU for chrome sits at under 2%. I'm on Windows 10.

Yes the website is open sourced. https://github.com/NinjaCodeGen/angular-landing-page

and replaced the orderBy pipe with the code from here: https://github.com/FuelInteractive/fuel-ui/blob/master/src/pipes/OrderBy/OrderBy.ts

I will poke around the scrolling codes but not sure how to reproduce.. May just need to remove it?

**Comment by Toxicable** [comment]
Just took a few minutes to check over your site and this line here
https://github.com/NinjaCodeGen/angular-landing-page/blob/master/src/app/navbar/navbar.component.ts#L16
Is what's causing poor performance, which I was able to reproduce on both Mac and Windows using Chrome 60.
That line is causing your entire app to rerun Change Detection very often which can be very slow in your case.

**Comment by chauey** [comment]
@StephenFluin @Toxicable Huge thanks for the help and guidance. We have commented out that code of the landing page and redeployed (the header menu background does not change color now; we're not able to reproduce any noticeable performance issue before). Anything other action items? thx!

**Comment by Toxicable** [comment]
Awesome, that's a whole lot better now.

**Review by StephenFluin — APPROVED** [review]

**Pull request closed without merging**
