### PR TITLE
docs: remove duplicated link to aio/content/guide/inputs-outputs.md in navigation sidebar (#42652)

### PR DESCRIPTION
**Pull request by looshch**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #42652

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by sonukapoor — APPROVED** [review]

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx, @looshch! Can you please update the commit message (to make it a little more clear) to something like:

> docs: remove duplicate link to \`guide/inputs-outputs.md\`
>
> When you click on \`Understanding Angular > Components > Sharing data between child and parent directives and components\` in the navigation sidebar, another item gets selected: \`Understanding Angular > Templates > Inputs and Outputs\`
> Both of them are linked to the same guide but the view cannot handle situations when several entries point to the same guide.
>
> This commit fixes it by removing the second entry.
>
> Fixes #42652

##
Other than that lgtm :+1:

**Comment by gkalpak** [comment]
Thx for updating the commit message, @looshch :+1:
It seems you missed one change: Updating the commit message header from `docs(docs-infra): ...` to just `docs: ...` :smiley:

**Comment by looshch** [comment]
yep, missed it, thanks. Fixed now. Please, check again, @gkalpak

**Review by gkalpak — APPROVED** [review]
LGTM :+1:

Reviewed-for: global-docs-approvers

**Pull request closed without merging**
