### PR TITLE
WIP(compiler): fix #19878, can config zone/once/passive/capture in template/HostListener decorator

### LINKED ISSUE #19878: HostListener should have option to always run in ngZone
## I'm submitting a...

<pre><code>[x] Feature request</code></pre>

## Current behavior

`@HostListener` runs function in whatever zone it was in during creation

## Expected behavior

`@HostListener` should allow an optional zone to be specified or a Boolean parameter to always run in `NgZone`

Alternately, provide zone creation context for component creators such as `NgForOf`. This may be easier to implement and more general purpose.

## Minimal reproduction of the problem with instructions

Create component with a `@HostListener` event outside of `NgZone`. Every time that event is fired, it will be run in the zone it was created in.

## What is the motivation / use case for changing the behavior?

Creating a virtual scroller and during creation of virtual components, the component's `@HostListener`'s will register in the zone it was created in (not ngZone). It looks very ugly to have all events wrapped in `zone.run` functions. It would be nice to have a way to bind the function call to a particular zone declaratively.

### PR DESCRIPTION
**Pull request by JiaLiPassion**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #19878

### not easy to config use ngzone or nozone with HostListener

user need to explicitly call `runOutsideOfAngular` to make sure  `eventhandler` run outsideof`ngZone` 

```javascript
@HostListener('window:resize', ['$event.target'])
  onResize(target: any) {
    this.ngZone.runOutsideOfAngular(() => {
       console.log('resize triggered');
    });
  }
```
or call `ngZone.run` explicitly make sure `eventhandler` run into `ngZone`.

```javascript
@HostListener('window:resize', ['$event.target'])
  onResize(target: any) {
    this.ngZone.run(() => {
       console.log('resize triggered');
    });
  }
```

### not easy to run event handler outsideOfAngular in template

```javascript
<div (mouseover)="mouseover();"></div>
```

```javascript
mouseover() {
  this.ngZone.runOfAngular(() => {
    ...
  });
}
```

## What is the new behavior?
Can config which `zone` will event handler will run into in `@HostListener` decorator.

### can config `passive`, `capture`, `once` parameters to `addEventListener`.
- in template, can config those parameter like below.

```javascript
<div (mouseover.capture.once.passive)="mouseover();"></div>
```

### can config `ngzone` which will guarantee eventhandler run in `ngZone` even the handler was 
added not in `ngZone`.

```javascript
 @HostListener('window:resize.ngzone', ['$event.target'])
  onResize(target: any) {
    console.log('resize triggered');
  }
```

- can config `nozone` which will guarantee eventhandler run outside of  `ngZone` even the handler was added  in `ngZone`. **and if config `outsideOfAngular`, DOMEventManager will bypass zone.js and directly use native addEventListener to improve performance.**

And it can also work with #20672 to get better performance.

```javascript
 @HostListener('window:resize.nozone', ['$event.target'])
  onResize(target: any) {
    console.log('resize triggered');
  }
```
## Does this PR introduce a breaking change?
```
[] Yes
[x] No
```

### CODE REVIEW

**Comment by devoto13** [comment]
@JiaLiPassion I use [custom](https://gist.github.com/devoto13/a1663506728212481cdb4f301002b1d4) `EventManager` implementation in my project to tackle same problem. The idea is pretty similar to what is done here. But weakly typed. I would be very interested to have a built-in way to control zone for an event subscription.

**Comment by JiaLiPassion** [comment]
@devoto13, thank you for the information. It is the same idea, and `built-in` one is faster than `runOutsideOfAngular` because it will bypass `zone` totally.

**Comment by ericmartinezr** [comment]
Wouldn't be a "true" or "false" be simpler? `true` for running inside angular's zone (on by default), and `false` for running outside angular's zone.

**Comment by JiaLiPassion** [comment]
@ericmartinezr , yeah, `true/false` will be more clearer when we only need `in ngZone or not`. 

I use `string` becasue there are other options, for example, the `default`, in fact, current `@HostListener` behavior is not `in ngZone`, it is `default`, that means, the event handler will run in the zone where it is created.

**Comment by JiaLiPassion** [comment]
I just saw the discussion here, https://github.com/angular/angular/issues/11200.
About
-  `event` (such as `<button (click)="onClick($event)"></button>) 
- `@HostListener`

There are lot of options need to be extended in the future.
- `capture`
- `passive`
- `zone`
- ...

I am not sure which design is better.
I saw two designs have been discussed here.

1. add a object options. just like the design here, https://github.com/angular/angular/issues/8866#issuecomment-223221443

```javascript
<button (click: {passive: true})="onClick($event)"></button>
```
2. use a `magic prefix`. About the design here by @DzmitryShylovich  https://github.com/angular/angular/issues/11200#issuecomment-266244515

```javascript
~click => capture: true
-scroll=> passive: true
#scroll=> zone: ngzone
$scroll=> zone: nozone
```

I prefer the second one, the first one need user to write more code and will need to modify more codes of `core/complier`, the second one is more friendly. 

@mhevery , please review, and I will try to modify this PR with the second one first to see is there any risk, thank you.

**Comment by mhevery** [comment]
http://test/OCL:183446602:BASE:183446652:1517006128574:ee8ce8f8

**Comment by mhevery** [comment]
/cc @IgorMinar It would be great if you add your opinion.

@JiaLiPassion 

1. Your current PR is nice but it only solves it for `@HostListener` Using a prefix would solve it globally. I would much rather have a solution which would be global (for all kinds of listeners).
2. I like the idea of encoding it into the string but the suggestion you have is that it does not differentiate between DOM events and component events. (For example if you have a component which has `open` output than `capture`, `passive` are meaningless.)
3. We already have `keydown.control.shift.enter` listeners see https://github.com/angular/angular/blob/master/modules/playground/e2e_test/key_events/key_events_spec.ts and this feature is for DOM events only. Could we take this approach and extend it?


What I have in mind is something like this.
```
<div (click)="..."
     (click.nozone.passize.capture)="...">
```

I am open for suggestions as how to make it better... What do you think.

**Review by IgorMinar — CHANGES_REQUESTED** [review]
I just skimmed through and I'm not sure yet if we want to do this at all, but if we do go forward, we should change the api to use an object literal config object rather than string literal. This would allow us to also support passive listeners (see #8866) and other options.

**Comment by IgorMinar** [comment]
I'll review this in more detail next week, just wanted to provide quick feedback on the API.

**Comment by mhevery** [comment]
@IgorMinar I agree that current implementation is not what we want, but what about my proposal as described in the comment https://github.com/angular/angular/pull/21681#issuecomment-360931320

**Comment by JiaLiPassion** [comment]
@mhevery , @IgorMinar , thank you for the review.

> We already have keydown.control.shift.enter listeners see https://github.com/angular/angular/blob/master/modules/playground/e2e_test/key_events/key_events_spec.ts and this feature is for DOM events only. Could we take this approach and extend it?
> What I have in mind is something like this.
> 
> <div (click)="..."
>      (click.nozone.passize.capture)="...">
> I am open for suggestions as how to make it better... What do you think.

Yes, you are right, I forget we already have the syntax like `keydown.control.shift.enter`, I agree
```
<div (click)="..."
    (click.nozone.passive.capture)="...">
``` 
is a better and consistent solution.

**Comment by JiaLiPassion** [comment]
@mhevery , @IgorMinar , I have updated this PR, it is still `WIP`, please review it is ok or not, I will continue to add test cases and document. Thank you!

basically the options below can be configured.

- EventListenerOptions
  - capture
  - passive
  - once
- Zone Options
  - ngzone
  - nozone

And those options can be configured  in 

- template 

```javascript
<div (mouseover.capture.once.passive)="mouseover();"></div>
```

- HostListeners

```javascript
 @HostListener('window:resize.nozone', ['$event.target'])
  onResize(target: any) {
    console.log('resize triggered');
  }
```

The order of `capture/once/passive/nozone/ngzone` is not relevant.
And it can also work with existing event syntax like `keypress.ctrl.nozone.capture`.

**Comment by okhobb** [comment]
@JiaLiPassion Is it the case that it's assumed passive is false unless included in the list? Per https://bugs.webkit.org/show_bug.cgi?id=182521#c3 (causing issues like https://github.com/mapbox/mapbox-gl-js/issues/6095 -- not an Angular project but illustrates why some apps are broken) it is now the case that it defaults to true on window and document events. Thus, users may explicitly need to configure it to be false in some cases.

**Comment by CollinGraf314** [comment]
This is something I would really like to be able to use. Is there any news on whether or not .nozone, .ngzone, and the like will implemented?

**Comment by ahnpnl** [comment]
Hi, 

Any new updates on this ? This feature is very nice and useful for developers.

**Comment by JiaLiPassion** [comment]
Close this one and open a new PR https://github.com/angular/angular/pull/38236

**Pull request closed without merging**
