### PR TITLE
docs(core): Remove repeated example

### PR DESCRIPTION
**Pull request by niknbr**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Example 1 and Example 3 for ViewChild decorator are the same.

Issue Number: N/A

## What is the new behavior?
Remove Example 3.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by nikz99** [comment]
I signed it!

**Review by jbogarthyde — APPROVED** [review]
Good catch.

**Review by AndrewKushnir — APPROVED** [review]
LGTM, thanks for the fix @nikz99

**Comment by AndrewKushnir** [comment]
Merge assistance: minor changes to code comments, low risk to google3.

**Pull request closed without merging**
