### PR TITLE
docs(router): minor typo

### PR DESCRIPTION
**Pull request by LayZeeDK**
docs(router): minor typo

Fix a minor typo in the description of a router spec.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Toxicable** [comment]
Your commit message does not fix the require format, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit for more info

**Comment by LayZeeDK** [comment]
If this is not the required format, I have no idea how to fix it:

```
docs(router): minor typo

Fix a minor typo in the description of a router spec.
```

**Comment by Toxicable** [comment]
>docs(router): minor typo

This should be in the commit message not in the description

**Comment by LayZeeDK** [comment]
See https://github.com/angular/angular/pull/18225

**Pull request closed without merging**
