### PR TITLE
docs: fix the selector in component interaction guide

### PR DESCRIPTION
**Pull request by yuvgeek**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Thanks for this fix.

Please can you tweak the commit message. The `docs:infra` is not correct since that is for the infrastructure that generates and renders the docs, rather than the docs content.

It would enough to change it to:

```
docs: fix the selector in component interaction guide

The selector for the `CountdownTimerComponent` is `app-countdown-timer`
not `countdown-timer`.
```

**Comment by yuvgeek** [comment]
> Thanks for this fix.
> 
> Please can you tweak the commit message. The `docs:infra` is not correct since that is for the infrastructure that generates and renders the docs, rather than the docs content.
> 
> It would enough to change it to:
> 
> ```
> docs: fix the selector in component interaction guide
> 
> The selector for the `CountdownTimerComponent` is `app-countdown-timer`
> not `countdown-timer`.
> ```

You are welcome. I have updated the commit message & pushed it!

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Comment by yuvgeek** [comment]
> Reviewed-for: public-api

I think you can now remove the `action: cleanup` label.

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Pull request closed without merging**
