### PR TITLE
feat(common): ngComponentOutlet should emit create/destroy events

### LINKED ISSUE #15360: There is no way to access inputs or outputs of Components created by NgComponentOutlet
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is no way to set @Inputs or subscribe to @Output events of the Component created by NgComponentOutlet.

**Expected behavior**
I expect some to set values and to subscribe events.

**What is the motivation / use case for changing the behavior?**
At least, we should have the same level of functionality as ViewContainerRef.createComponent() which is roughly the programatic equivalent of NgComponentOutlet. That function returns a ComponentRef<any> which provides an instance property that allows direct access to the class instance of the Component. The original feature request for NgComponentOutlet defined an event on the directive that would fire and pass this ComponentRef object after creation. This did not make it into the current implementation and I see no other alternatives to access inputs/outputs.

Supporting only Components with no inputs or outputs severely limits the usefulness of NgComponentOutlet.

* **Angular version:** 4.0.0-rc.1

### PR DESCRIPTION
**Pull request by DzmitryShylovich**
Closes #15360

### CODE REVIEW

**Comment by dereklin** [comment]
@DzmitryShylovich Does this mean any changes to the parent component will re-create the dynamic component?

I am thinking of create a d3 chart wrapper.  like this:
```
<d3-wrapper [options]="chartOptions" [data]="chartData$ | async"></d3-wrapper>
```
Based on the chartOptions, I will dynamically create a chart component: line, pie, etc.

When chartData changes, I will re-render the chart, but I don't want to destroy and re-create

Do you think I can still do that with your commit?

**Comment by xealot** [comment]
I swapped this in for the std-lib version and it creates two components instead of one.

**Comment by xealot** [comment]
Is there a reason destroy isn't emitted when ngOnDestroy is called?

It seems like destroy should also emit the component. If you're trying to do any accounting on the outside using create/destroy it's helpful.

**Comment by splincode** [comment]
@DzmitryShylovich what is the status of your pull request? is it still relevant? please fix conflicts if they exist

**Comment by smasala** [comment]
+1

**Comment by mhevery** [comment]
Closing this PR because we don`t have syntax for registering to events with `*` i.e. <div *nComponentOutlet="exp">` There is no place to put `(create)` listener. This should be more thought out with proper syntax before we implement something like this.

**Pull request closed without merging**
