### PR TITLE
docs: fix dynamic-component-loader example for Adblock Plus + EasyList

### PR DESCRIPTION
**Pull request by dennisameling**
Reported issue in angular#18138 is due to EasyList being selected in ABP. It injects display:none in elements with the ad-banner class name. Changing the class name to ad-banner-example fixes the issue in this case.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Please see issue https://github.com/angular/angular/issues/18138

Issue Number: 18138

## What is the new behavior?
AdBlock Plus (in combination with EasyList) no longer blocks displaying the sample ads in the given example.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
@dennisameling, it also seems to be blocking the image at the bottom of the [Dynamic Component Loader][1] guide (which is named `ads.gif`).
Could you fix it as well (since _that_ is what #18138 is mainly about :grin:)

[1]: https://angular.io/guide/dynamic-component-loader

**Review by gkalpak — CHANGES_REQUESTED** [review]
@dennisameling, it also seems to be blocking the image at the bottom of the [Dynamic Component Loader][1] guide (which is named `ads.gif`).
Could you fix it as well (since _that_ is what #18138 is mainly about :grin:)

[1]: https://angular.io/guide/dynamic-component-loader

**Comment by dennisameling** [comment]
@gkalpak thanks for checking! You're right, this fixes the Stackblitz example but not the image at the bottom of the guide. Will add an additional commit for that soon!

**Comment by gkalpak** [comment]
Also, please, make sure you add `Fixes #18138` to the bottom of the commit message (per our [commit message guidelines][1]).

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by dennisameling** [comment]
@gkalpak done :)

**Comment by jenniferfell** [comment]
@dennisameling Thanks for providing this fix!
@gkalpak Thanks for keeping this moving. When you are happy with the results, go ahead and mark for merge. LGTM so I approved to get past one required pull approve group.

**Review by jenniferfell — APPROVED** [review]

**Review by gkalpak — APPROVED** [review]

**Pull request closed without merging**
