### PR TITLE
docs(aio): updated wrong property name

### PR DESCRIPTION
**Pull request by GuillaumeUnice**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
In the [Reactive Forms](https://angular.io/guide/reactive-forms#from-address-to-secretlairs) section there is a property name mistake in the explanation.

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

It's ask to change the formArrayName="address"
`
In hero-detail.component.html change formArrayName="address" to formArrayName="secretLairs".
`
Nevertheless the current property is formGroupName="address"

Issue Number: N/A

## What is the new behavior?
So just change to the current property
`
In hero-detail.component.html change formGroupName="address" to formArrayName="secretLairs".
`

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by GuillaumeUnice** [comment]
I signed it!

**Comment by GuillaumeUnice** [comment]
Why Travis abort?

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
thanks!

**Comment by matsko** [comment]
It looks like this fails to rebase with either `master` or `6.0.x`. Can you have a look and/or fix it?

**Comment by vicb** [comment]
Seems like this is already fixed in master

**Pull request closed without merging**
