### PR TITLE
fix(router): allow UrlMatcher to return null

### PR DESCRIPTION
**Pull request by adriensamson**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
A route url matcher cannot return null in strict mode.

Issue Number: N/A

## What is the new behavior?
A route url matcher can return null in strict mode as stated in the doc.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by adriensamson** [comment]
CLA emails updated

**Comment by DustinJSilk** [comment]
Any update on this?

**Comment by bitjson** [comment]
Was just about to work on this myself, but it looks like there are already 2 PRs for this issue.

 It looks like PR #22898 also fixes the issue and adds a test – can this be closed in favor of that PR?

**Comment by adriensamson** [comment]
@bitjson good catch, closing in favor of #22898

**Pull request closed without merging**
