### PR TITLE
fix(docs-infra): change `app-list-item` to `app-item-list`

### LINKED ISSUE #35598: Improve Template Syntax code + documentation
# 📚 Docs or angular.io bug report

### Description

 
Copied @gkalpak's [comments ](https://github.com/angular/angular/pull/35433#pullrequestreview-358870910)from PR #35433

> This change looks good on its own (it's an improvement over the current state), but I believe a bigger change is needed to make the example more intuitive. Things I noticed that are confusing:
> 
> A component named ListItemComponent that lists items. AFAICT, such components usually have List as a suffix, not a prefix; i.e. ItemListComponent.
> AppComponent has a property called currentItem (implying a single item) that holds a list of items (even if it happens to have only one item, it is still a list).

Originally reported issue: #35368

### What's the affected URL?**
[https://angular.io/guide/template-syntax#return-the-proper-type](https://angular.io/guide/template-syntax#return-the-proper-type)

@kapunahelewong / @gkalpak Please assign this to me, as I am already working on it.

### PR DESCRIPTION
**Pull request by sonukapoor**
The `app-list-item` component sounds like it is used for a single
item, however it renders a list of items. There were also
several changes in the documentation, where it was becoming
confusing if the `app-list-item` is using a single item or multiple
items. This commit fixes this issue. It renames the component and its
respective properties to make sure that the intention is very clear.

Closes #35598

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #35598

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by sonukapoor** [comment]
@gkalpak Can you review this?

**Comment by gkalpak** [comment]
@sonukapoor, this already has assigned reviewers 😉
Happy to take a look too, but first we should ensure that the content is OK (i.e. correct and makes sense for the concepts we are trying to get across), for which @kapunahelewong is much more qualified than me :grin:

**Review by kapunahelewong — APPROVED** [review]
LGTM, thank you very much, @sonukapoor!!

**Comment by kapunahelewong** [comment]
merge-assistance: Global approval for this docs-only change.

**Comment by sonukapoor** [comment]
@aikidave Can we get this merged?

**Review by kara — APPROVED** [review]
LGTM

**Review by aikithoughts — APPROVED** [review]

**Pull request closed without merging**
