### PR TITLE
docs: Add some zoneless documentation

### PR DESCRIPTION
**Pull request by atscott**
Probably needs more work, but it's a start

### CODE REVIEW

**Comment by JeanMeche** [comment]
For the doc to be accessible, we'll need at least to add it to `adev/src/app/sub-navigation-data.ts`.

**Review by bencodezen — APPROVED** [review]
Thanks for getting this in @atscott! I think this is a great start. 🙌 

We'll look into how to best put it in the nav for better exposure, but I don't want to hold up having this content be available for people to reference. Let's ship it!

**Comment by JeanMeche** [comment]
@bencodezen fwiw the doc is not accessible if no route is defined for it.

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit 5a52facef74ed0c14100b27d7cbb0d20e3eeb6db.

**Pull request closed without merging**
