### PR TITLE
fix(RouteRegistry): normalize path for init load

### PR DESCRIPTION
**Pull request by PatrickJS**
BREAKING CHANGES:

previously '/home' now 'home'
due to [router.js#L242](https://github.com/angular/angular/blob/5db89071d408c2e5b2e26b3d7b00e02e164c197f/modules/angular2/src/router/router.js#L242) 
`this.navigate(location.path());` doesn't work since `Location.path` normalize the path while `RouteRegistry.config` doesn't

example:
https://github.com/angular-class/angular2-webpack-starter/commit/e2163180ebdfab5018e28187b5a407458dbed431

### CODE REVIEW

**Comment by gdi2290** [comment]
this would be simpler if we just use the raw `BrowserLocation.path()`

**Comment by tbosch** [comment]
@btford could you review this?

**Comment by gdi2290** [comment]
I also have to update the test etc for Travis but also wanted to get your feedback before moving forward since it is adding a dependency to `RouteRegistry`. I did mention the quick fix was using `BrowserLocation.path()` or at least allow `Location` to expose the path without normalizing it. As I mentioned above you can see the problem (reload isn't navigating to the correct route) in the seed repo and my fix.

**Comment by btford** [comment]
@jeffbcross is working on TS-ifying the router; can we wait until that's in to rebase and merge this?

**Comment by gdi2290** [comment]
@btford yeah, after it's converted I can rebase and update the tests etc for RouteRegistry to use normalized url.

**Comment by tbosch** [comment]
Blocked on https://github.com/angular/angular/issues/2001

**Comment by vsavkin** [comment]
@gdi2290 can you rebase?

**Comment by btford** [comment]
This is actually now fixed in master, thanks to the work of @matsko last week. @gdi2290 if you run into the issue again can you open a new ticket? Thanks!

**Pull request closed without merging**
