### PR TITLE
refactor(browser): remove deprecated transfer state APIs

### PR DESCRIPTION
**Pull request by alan-agius4**
BREAKING CHANGE: Deprecated `StateKey`, `TransferState` and `makeStateKey` have been removed from `@angular/platform-browser`, use the same APIs from `@angular/core`.

### CODE REVIEW

**Review by thePunderWoman — APPROVED** [review]
reviewed-for: fw-core, public-api

**Comment by atscott** [comment]
Haven't we historically provided migrations for something like this?

**Comment by alan-agius4** [comment]
@atscott, a migration was already done in v17 https://github.com/angular/angular/tree/17.3.x/packages/core/schematics/migrations/transfer-state

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Comment by alxhub** [comment]
This PR was merged into the repository by commit cba336d4f1badd601b24a58fc51bde995f45682d.

**Pull request closed without merging**
