### PR TITLE
Update SECURITY.md to improve grammar

### PR DESCRIPTION
**Pull request by CodeMaster7000**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by devversion** [comment]
Thank you for this PR. Can you propose the same changes in https://github.com/angular/.github/blob/main/SECURITY.md? That would be the canonical place where the change would need to be made.

**Comment by CodeMaster7000** [comment]
@devversion I believe I have proposed these changes at the correct place.

**Comment by devversion** [comment]
If you change it in `angular/.github`, then the change will automatically be propagated to all repositories (like this one, the components repo, the angular cli etc.)

**Comment by devversion** [comment]
The change has been merged in the .GitHub repo and has propagated into this repo too. This can be closed. Thx again

**Pull request closed without merging**
