### PR TITLE
docs: minor typo fix in the bazel documentation

### PR DESCRIPTION
**Pull request by sonukapoor**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by sonukapoor** [comment]
@gkalpak It seems, there is something with `CI` - some of the tests that have nothing to do with my code changes are failing.

**Comment by josephperrott** [comment]
I was able to retrigger the failing `components-repo-unit-tests` job and it looks like it was a flake that now passes.

The lint failure on the other hand appears to correctly be a failure as the commit message does not have a body.

**Comment by sonukapoor** [comment]
> I was able to retrigger the failing `components-repo-unit-tests` job and it looks like it was a flake that now passes.
> 
> The lint failure on the other hand appears to correctly be a failure as the commit message does not have a body.

Thanks, @josephperrott - I have added an additional message, however, I feel it was completely unnecessary.

**Review by josephperrott — APPROVED** [review]
LGTM, thanks!

**Pull request closed without merging**
