### PR TITLE
docs: update link for language service config for neovim

### PR DESCRIPTION
**Pull request by ZhiliangGong**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently the link of the issue points to a page which informs the move of the old page to a new link.

Issue Number: N/A

## What is the new behavior?
The updated link goes to the correct section of the newly moved page.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
lgtm

**Comment by thePunderWoman** [comment]
@ZhiliangGong your commit message header is using an incorrect scope. Can you fix that and re-push your commit? `git commit --amend` and then just remove `(adev)` from the commit header. Then force push. Once you do that, this is green and ready to merge.

**Comment by ZhiliangGong** [comment]
@thePunderWoman - thanks, done!

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit 3e2851b8205dc1c800fa3006d21ab46b098ed81a.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
