### PR TITLE
Fix typo in dependency-injection-navtree.md

### PR DESCRIPTION
**Pull request by obenjiro**
Fixing Doc Typo

## PR Checklist
Please check if your PR fulfills the following requirements:

- [] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
Hi @obenjiro, thanks for creating this PR and fixing a typo!

The `lint` CircleCI job indicates that the commit message doesn't have the right format, [see CI output here](https://circleci.com/gh/angular/angular/665326). The problem is that the "scope" is missing in the commit message. Could you please update commit message to something like this:

```
docs: fix typo in Dependency Injection guide
```

Please let me know (in this thread) once commit message it updated, so we can proceed further with this PR.

Thank you.

**Review by AndrewKushnir — CHANGES_REQUESTED** [review]
Hi @obenjiro, thanks for creating this PR and fixing a typo!

The `lint` CircleCI job indicates that the commit message doesn't have the right format, [see CI output here](https://circleci.com/gh/angular/angular/665326). The problem is that the "scope" is missing in the commit message. Could you please update commit message to something like this:

```
docs: fix typo in Dependency Injection guide
```

Please let me know (in this thread) once commit message it updated, so we can proceed further with this PR.

Thank you.

**Comment by obenjiro** [comment]
@AndrewKushnir tnx. Fixed commit message. Can you look at PR ones more?

**Review by AndrewKushnir — APPROVED** [review]
LGTM, thanks @obenjiro!

**Pull request closed without merging**
