### PR TITLE
perf: pngcrush all pngs

### PR DESCRIPTION
**Pull request by jelbourn**
This is the result of running
```sh
find ./ -iname "*.png" -exec pngcrush -brute -ow --  {} \;
```

[Summary of size reductions](https://docs.google.com/spreadsheets/d/12Qgx7DfKabWw0PJza6ozC1kCHTofi6wyBLWGtwLW7G4/preview)

Last done in July, 2017 in #18243

### CODE REVIEW

**Comment by StephenFluin** [comment]
@jelbourn Any reason not to use pngquant instead?

**Review by andrewseguin — APPROVED** [review]
LGTM (at least for Elements)

**Comment by jelbourn** [comment]
@StephenFluin never heard of it before. I'll try that when I do this again in 2021.

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
merge-assistance: please accept my global approval for this PR and get it in before it goes stale. thank you!

**Review by matsko — APPROVED** [review]

**Pull request closed without merging**
