### PR TITLE
feat(forms): add the submitted flag to NgForm and NgFormModel directives

### LINKED ISSUE #2960: Add the submitted flag to the Forms API
We need to implement something similar to $submitted in Angular 1, so we can do the following:

```
<form #f="form">
  <div *ng-if="f.submitted && !f.valid">Fix the form!</div>
</form>
```

### PR DESCRIPTION
**Pull request by antonmoiseev**
Closes #2960

### CODE REVIEW

**Comment by antonmoiseev** [comment]
Only public API check currently fails.

[Originally](https://github.com/antonmoiseev/angular/commit/7cbf2e2231d9eaac6719d97f5df65e6f4967cfc4#diff-10322624f4472f7d87993d1f0120c9dfR49) I also added `submitted` field to the `Form` interface, but TS doesn't allow specifying whether it should be a getter, a setter or both. Implementation assumes it's a read-only property, so `NgForm` and `NgFormModel` implement it as a getter. However Dart works differently and complains that setter should be implemented as well. What do you do in this situation? Do you implement it as a method? Do you have a special ts2dart complier flag that hints the field should be a getter in the Dart interface?

**Comment by IgorMinar** [comment]
@antonmoiseev please update the public api spec, it's ok to update it, but it's not ok to merge the changes to that file without the review by people mentioned in that file.

**Comment by vsavkin** [comment]
@antonmoiseev could you update the spec?

**Comment by vsavkin** [comment]
Closing this due to inactivity

**Comment by binarious** [comment]
@vsavkin Could you please explain what needs to be done so others can take over?

**Pull request closed without merging**
