### PR TITLE
feat(compiler-cli): add extended diagnostic for non-nullable optional…

### LINKED ISSUE #44870: Warn on non-nullable optional chain
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler-cli

### Description

Optional chaining is a great way to safely access properties that might be `null` or `undefined`, for example:

```typescript
import {Component, Input} from '@angular/core';

@Component({
  template: `
    <span>Hello, {{ user?.name ?? 'guest' }}!</span>
  `,
})
export class Greeter {
  @Input() user?: User;
}

interface User {
  name: string;
}
```

But things can easily change and make the optional chain useless, such as:

```diff
  export class Greeter {
-   @Input() user?: User;
+   @Input() user: User;
  }
```

This change means that the optional chain `user?.name` is no longer useful because `user` will never be `null` or `undefined`. This leads to confusion and tricks readers of the code into thinking that there is a case where "Hello, guest!" is displayed, when that actually isn't the case. If the default "guest" string comes from somewhere else, it could lead to dead code and possibly result in excess bundle size.

### Proposed solution

We should consider an extended diagnostic to identify and warn developers in this situation. We already have [a diagnostic to warn about useless nullish coalescing operators `??`](https://angular.io/extended-diagnostics/NG8102), so it makes sense to have a similar check for optional chaining.

### Alternatives considered

N/A

### PR DESCRIPTION
**Pull request by JoostK**
… chains

This commit adds an extended diagnostics check that is similar to the nullish
coalescing check, but targeting optional chains. If the receiver expression
of the optional chain is non-nullable, then the extended diagnostic can report
an error or warning that can be fixed by changing the optional chain into a
regular access.

Closes #44870

### CODE REVIEW

**Comment by JoostK** [comment]
Historically these operators have been called "safe navigation" in Angular (as they precede optional chain syntax in ECMAScript) but I feel like it's less confusing to be using the ECMA names for this check instead of "safe navigation".

**Review by atscott — APPROVED** [review]
🥇

**Review by atscott — APPROVED** [review]
reviewed-for: public-api

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Pull request closed without merging**
