### PR TITLE
Revert "refactor(core): Use `ActionResolver` in `Dispatcher`. (#56369)"

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This reverts commit 4ebd2853fa7a9b47c71ff19b5a6a819502905508.

Reason for rollback: the change breaks some g3 code.

### CODE REVIEW

**Review by thePunderWoman — APPROVED** [review]
reviewed-for: fw-core, public-api, primitives

**Comment by thePunderWoman** [comment]
TESTED= Pure Rollback

**Comment by AndrewKushnir** [comment]
TESTED=Already rolled back in g3 (via [this CL](http://cl/643069869)).

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository by commit fca57645646e8733c3cef62c3f4dc7d2e5da658b.

The changes were merged into the following branches: main, 18.0.x

**Pull request closed without merging**
