### PR TITLE
fix(ng-zone) Use instance instead of type

### PR DESCRIPTION
**Pull request by ciriarte**
I'm getting an undefined error on this line, it looks like we were meant to use the instance instead of the type identifier.

### CODE REVIEW

**Comment by ciriarte** [comment]
@vsavkin My build failed, but it looks like it fails on deprecated ng-zone specs:

```sh
Chrome 39.0.2171 (Linux 0.0.0) NgZone long stack trace should produce long stack traces FAILED
	Expected 1 to be greater than 1.
	    at /home/travis/build/angular/angular/dist/js/dev/es5/angular2/test/core/zone/ng_zone_DEPRECATED_spec.js:58:70 <- angular2/test/core/zone/ng_zone_DEPRECATED_spec.ts:85:41
```

This line was affecting our app in > alpha.53 up to beta.0

Please let me know if there's anyone else I should refer this issue to.

**Comment by vicb** [comment]
You should load the [lts script](https://github.com/angular/zone.js/blob/master/dist/long-stack-trace-zone.js) when using long stack traces

**Comment by ciriarte** [comment]
Makes sense. I'll close my PR before it creates more confusion.

**Comment by vicb** [comment]
https://github.com/angular/angular/pull/6008 has more details on what needs to be loaded (note that lts is included in `angular2-polyfills.js`)

**Comment by towa48** [comment]
check for long-stack-trace-zone.js
```javascript
if (enableLongStackTrace && zone.longStackTraceZone) {
    errorHandling = collection_1.StringMapWrapper.merge(zone.longStackTraceZone, { onError: function (e) { ngZone._notifyOnError(this, e); } });
}
```

**Pull request closed without merging**
