### PR TITLE
docs(forms): add docs for emitEvent flag

### PR DESCRIPTION
**Pull request by cexbrayat**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thank you for this !

**Review by sonukapoor — APPROVED** [review]
LGTM - Thank for making these doc changes. 👍

**Review by AndrewKushnir — APPROVED** [review]
Thanks for the update!

**Comment by AndrewKushnir** [comment]
**Caretaker note**: docs-only change, no presubmit is required, this PR is ready for merge.

**Comment by atscott** [comment]
This PR was merged into the repository by commit 9c776d6802d15fcb93401d525638307b9bb8737d.

**Pull request closed without merging**
