### PR TITLE
docs(aio): clean up frequent ng-modules

### PR DESCRIPTION
**Pull request by alan-agius4**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
clean up docs

Issue Number: #24017

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by jenniferfell — APPROVED** [review]

**Comment by jenniferfell** [comment]
Thank you. This is more consistent.

**Comment by alan-agius4** [comment]
Bump!

**Review by gkalpak — APPROVED** [review]

**Comment by alan-agius4** [comment]
@gkalpak, the I changed the `closes`

**Comment by alan-agius4** [comment]
@gkalpak, I changed the `closes`.

JFYI: It does support it https://help.github.com/articles/closing-issues-using-keywords/

> For example, to close an issue numbered 123, you could use the phrase "Closes #123" or "Closes: #123" in your pull request description or commit message. Once the branch is merged into the default branch, the issue will close.

**Comment by gkalpak** [comment]
Cool! I didn't know it supported that 😇

**Pull request closed without merging**
