### PR TITLE
Ng class cleanup

### PR DESCRIPTION
**Pull request by mhevery**
Ignore noImplicitAny changes they will be merged with https://github.com/angular/angular/pull/7030 and are all green. The failure seems to come from the `ng_class.ts` changes, but I don't see a reason why.

### CODE REVIEW

**Comment by mhevery** [comment]
@juliemr / @jelbourn can you help me debug https://travis-ci.org/angular/angular/jobs/110646029#L1275 There is an end 2 end test failing and I am not sure as to why. (Ignore the first SHA, it passes here: https://travis-ci.org/angular/angular/builds/110551804) The only relevant change is ngClass file here: https://github.com/mhevery/angular/commit/5fbd2537d69fc243ea80d68162f221f843e1e6c9#diff-2d9cd73c23ec9bc747111f8bf4caed4bL1

**Comment by mhevery** [comment]
@juliemr  / @jelbourn never mind, the issue magically fixed itself. :-)

**Comment by mhevery** [comment]
@vsavkin please review.

**Comment by mhevery** [comment]
@vsavkin LGTMed

**Comment by vikerman** [comment]
TAP Green

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166547.
------------------------------------------------------------------------------------------------------------


[[75447eb31ee03f1640988f88270c5b4d4f1e9364-673074177]]

**Pull request closed without merging**
