### PR TITLE
feat(http): add HttpTestingModule

### PR DESCRIPTION
**Pull request by cexbrayat**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Currently, setting up a test of a class that uses the Http service is really verbose

```typescript
beforeEach(() => TestBed.configureTestingModule({
  providers: [
    MockBackend,
    BaseRequestOptions,
    {
      provide: Http,
      useFactory: (backend, defaultOptions) => new Http(backend, defaultOptions),
      deps: [MockBackend, BaseRequestOptions]
    },
    UserService
 ]
}));
```

**What is the new behavior?**

This PR introduces `HttpTestingModule`, a very simple module that can be imported in tests.
We discussed the idea with @robwormald at ngEurope.
This is a naive first try, let me know if the idea still interest the team and how I can improve it if needed.

The PR allows to set up the previous test like:

```typescript
beforeEach(() => TestBed.configureTestingModule({
  imports: [HttpTestingModule],
  providers: [UserService]
}));
```

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by cexbrayat** [comment]
Would it be possible to have some feedback on this?

I'm still highly motivated to see this landing :)

**Comment by cexbrayat** [comment]
@vicb Rebased and fixed conflicts. Is there anything else I can do to help?

**Comment by DzmitryShylovich** [comment]
I think http module for testing will be a part of the new http module in 4.0 anyway

**Comment by cexbrayat** [comment]
@DzmitryShylovich Is there somewhere we can track the progress of the new http module? I don't think I've seen a plan for http in 4.0 discussed publicly, but that would be great if this PR is merged (or another one) for 4.0 :)

This is a small addition that would cut a lot of boilerplate.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/pull/14334
https://docs.google.com/document/d/1C_wzuuQEjIktJxrTlUTjTCDEZR8YduGTfbpe4WsNfNk/edit#heading=h.xgjl2srtytjt

**Comment by cexbrayat** [comment]
@DzmitryShylovich Thanks! 

As the PR mentioned is closed for now, can this PR be considered for 4.0? Or should I close it? (cc @mhevery @IgorMinar )

**Comment by DzmitryShylovich** [comment]
> can this PR be considered for 4.0?

it's a new feature so yeah, it will go in 4.x only (to maintain semver)

**Comment by cexbrayat** [comment]
@DzmitryShylovich I know that but thanks. My question was more: will it be considered at all, and can it be considered in time for 4.0?

**Comment by cexbrayat** [comment]
Closing as this is no longer really useful with the landing of #17143.
People interested by this issue should migrate to the new `HttpClientModule`.

**Pull request closed without merging**
