### PR TITLE
fix(ivy): tokenize escaped new lines in inline templates

### PR DESCRIPTION
**Pull request by cexbrayat**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #28843

## What is the new behavior?

The PR introduces two new tests to reproduce the issue found, and a fix/workaround.
I'm not sure this is the ideal way to fix the issue, @petebacondarwin will know better.
But I included the workaround I found to give a little more context about the issue.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
I love the tests. Nice work @cexbrayat.

I worry that this fix is more of a hack to work around something more serious wrong in the lexer.
I think that instead there should be a fix in the `_attemptCharCodeUntilFn` or `_advance` methods...

**Comment by cexbrayat** [comment]
@petebacondarwin Yes, that's what I think as well, but I'm not sure what should be the proper way to fix it... `_processEscapeSequence` is consuming the first `\` (here https://github.com/angular/angular/blob/master/packages/compiler/src/ml_parser/lexer.ts#L537), so `this._attemptCharCodeUntilFn(isNameEnd)` does not stop until the `$LF` just after...

**Comment by petebacondarwin** [comment]
Yes. The `index` should stay at the start of the character. We need to change the _processEscapeSequence method so that we only update that index when we move to the next char.

Also the fix you have would not help for longer escape sequences like variable Unicode ones.

**Comment by cexbrayat** [comment]
@petebacondarwin I *think* I understand what you mean and attempted a proper fix. The amended commit now has a dedicated index to track the advanced during escape sequences, and the index only catches up when needed.

**Comment by cexbrayat** [comment]
Superseeded by #28978

**Pull request closed without merging**
