### PR TITLE
docs: add Testing Angular Applications to resources

### PR DESCRIPTION
**Pull request by raer6**
Hi there,

I thought this title might be good add to your list of Angular resources.

Cheers,

Radmila.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks for the PR @raer6! You must [sign the CLA](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#cla) before this PR can move forward.

**Comment by brandonroberts** [comment]
@raer6 are you still interested in making this change?

**Comment by raer6** [comment]
Hi Brandon,

yes I am. Actually I thought I made it, didn't I?

Could you please assist me on this one, your help is much appreciated!

Thank you and talk to you soon,

Radmila Ercegovac
Manning Publications-Marketing
raer@manning.com

**Comment by brandonroberts** [comment]
@raer6 Sure. You must Sign the CLA first, https://github.com/angular/angular/blob/master/CONTRIBUTING.md#cla. Then once it gets reviewed and approved, it will be ready for merge. The PR git commit message needs to be updated also, but I can handle that for you if necessary.

**Comment by raer6** [comment]
Hi,

thanks for your help. I just signed it.

I am ready to proceed,

Radmila Ercegovac
Manning Publications-Marketing
raer@manning.com

**Comment by brandonroberts** [comment]
@raer6 reply with "I signed it!" so the bot can verify.

**Comment by raer6** [comment]
Could you now add Testing Angular Applications to your list of resources about Angular?

Thanks,

Rada.

**Review by StephenFluin — CHANGES_REQUESTED** [review]
I believe this entry might be categorized wrong. It looks like it should be in "books"?

**Comment by brandonroberts** [comment]
@raer6 move the entry to the `books` section and verify your commit email and the email you signed the CLA with match. Thanks

**Comment by brandonroberts** [comment]
Re-open this PR if you're still interested in landing this change.

**Pull request closed without merging**
