### PR TITLE
docs(aio): Added resource link to amexio-ng-extensions [duplicate of #17785]

### PR DESCRIPTION
**Pull request by ketan-gote**
docs(aio): Added resource link to amexio-ng-extensions

Amexio UI Widget Library added.

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Added new resource link

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by pratikthecook** [comment]
Can anyone suggest as to why travis build is failing?? As the changes(Addition of resource) are just in a single file aio/content/marketing/resources.json ?? 
Following is the log of travis


```
error:   Missing example file... relativePath: "docs-style-guide/src/tsconfig.json". - doc "guide/docs-style-guide" (content)  - from file "guide/docs-style-guide.md" - starting at line 1
error:   Example files can be found in: examples, examples
```

... then later

```
Error while verifying upload for PR 17790: User 'ketan-gote' is not an active member of any of the following teams: angular-core, aio-contributors
HTTP_CODE: 403
error Command failed with exit code 1.
The command "./scripts/ci/build.sh" exited with 1.
0.02s$ ./scripts/ci/test.sh
The command "./scripts/ci/test.sh" exited with 1.
0.03s$ ./scripts/ci/deploy.sh
The command "./scripts/ci/deploy.sh" exited with 1.
0.03s$ ./scripts/ci/angular.sh
The command "./scripts/ci/angular.sh" exited with 1.
0.02s$ ./scripts/ci/cleanup.sh
```
P.S the previous version i.e duplicate (#17785) where travis build passes! Strange!

**Comment by gkalpak** [comment]
The aio failure is a bug in the preview server. Will be fixed by #17747.

**Comment by pratikthecook** [comment]
@glalpak @mary-poppins thanks the preview looks great, i just have one question will this PR be reviewed?

**Comment by pratikthecook** [comment]
@gkalpak can this pr please be processed further for review. Thanks.

**Comment by gkalpak** [comment]
cc @juleskremer

**Comment by pratikthecook** [comment]
@juleskremer  can this pr please be processed further for review. Thanks.

**Comment by juleskremer** [comment]
@pratikthecook please edit your listing to remove the Angular version number from the listing description.

**Comment by pratikthecook** [comment]
@juluskremer edited the listing and removed Angular version.

**Comment by pratikthecook** [comment]
@juleskremer can u please move forward the PR for review process?
Thanks

**Comment by pratikthecook** [comment]
Still awaiting a response, can someone move this PR forward? @gkalpak @mary-poppins @juleskremer

**Review by StephenFluin — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]

**Pull request merged**
