### PR TITLE
fixed your broken example for ngOnChanges 

### PR DESCRIPTION
**Pull request by SGatInviewAds**

### CODE REVIEW

**Comment by SGatInviewAds** [comment]
I signed it!

**Comment by skreborn** [comment]
As per the [docs](https://angular.io/docs/ts/latest/api/core/index/Input-var.html), changing `my-prop` to `myProp` shouldn't make a difference, as the two are the same from Angular's perspective. Did you actually see a difference with this change?

Example from the docs:

    @Component({
      selector: 'bank-account',
      template: `
        Bank Name: {{bankName}}
        Account Id: {{id}}
      `
    })
    class BankAccount {
      @Input() bankName: string;
      @Input('account-id') id: string;
      // this property is not bound, and won't be automatically updated by Angular
      normalizedBankName: string;
    }
    @Component({
      selector: 'app',
      template: `
        <bank-account bank-name="RBC" account-id="4747"></bank-account>
      `,
      directives: [BankAccount]
    })
    class App {}
    bootstrap(App);

**Comment by gfrSE** [comment]
> As per the docs, changing my-prop to myProp shouldn't make a difference, as the two are the same from Angular's perspective. Did you actually see a difference with this change?

@skreborn maybe the docs are wrong..
See this [plunker](http://plnkr.co/edit/dRISElsaZPF5xCBGV0VR).
Example code taken from the docs page won't work!

changing `bank-name` to `bankName` will work.

**Comment by skreborn** [comment]
@gfrSE You are right, it does make a difference. If and when this goes through, it may be a good idea to fix the `Input` docs as well.

**Comment by vicb** [comment]
outdated, no cla

**Pull request closed without merging**
