### PR TITLE
docs: add martina kraus to GDE resources

### PR DESCRIPTION
**Pull request by martinakraus**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Review by StephenFluin — CHANGES_REQUESTED** [review]
The website looks wrong 'website": "http://http://martina-kraus.io",' and can you resize the image to be around 20kb? Thanks!

**Review by StephenFluin — APPROVED** [review]
Content looks good, you may need to squash and for push the commits so there's only a single one.

**Comment by kapunahelewong** [comment]
This is very cool, @martinakraus! In case you'd like a reference, here are [my steps in squashing](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-squash) that I like to share with contributors. 

Also be sure to sign the CLA.

Will you tag me when you're ready? I'd like to help you get this through. :)

**Comment by jbogarthyde** [comment]
@martinakraus Checking back - do you need help signing the CLA and rebasing/squashing?

**Comment by martinakraus** [comment]
Hi together, im so so sorry 
I messed up some things in this fork, since its been already some time ago I just
created a new one and created a new PR on it:

https://github.com/angular/angular/pull/33719

**Pull request closed without merging**
