### PR TITLE
build: remove unused rollup.config.js files

### PR DESCRIPTION
**Pull request by devversion**
Since we build and publish the individual packages using Bazel and
`build.sh` has been removed, we can safely remove the `rollup.config.js`
files which are no longer needed because the `ng_package` bazel rule
automatically handles the rollup settings and globals.

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
Um, wait, I don't think any of the `rollup.config.js` files are used anymore, I think they were only referenced by build.sh. They ought to be deleted.

**Comment by devversion** [comment]
Good point hmm. I will double-check that tomorrow.

**Comment by IgorMinar** [comment]
@devversion please apply the merge label when you are ready - it seems that you want to check on the config before merging.

**Comment by devversion** [comment]
@IgorMinar @alexeagle I've updated this PR. We should be able to safely remove the `rollup.config.js` files.

can you please have another look? (I need a global approval/or review from all packages 😄)

**Pull request closed without merging**
