### PR TITLE
fix(compiler): update element schema

### LINKED ISSUE #47545: 'hgroup' is not a known element
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

My issue is identical to #38831 which was closed because "the hgroup element has been removed from the HTML5 (W3C) specification".

Except that the latest HTML5 standard, i.e. [HTML 5.3](https://www.w3.org/TR/2021/NOTE-html53-20210128/), has been retired since January 28, 2021.
The latest HTML standard includes the [hgroup element](https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element) and all major browsers [support it](https://caniuse.com/?search=hgroup).

Can hgroup be added to the list of known elements?

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

_No response_

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.2.2
Node: 16.17.0
Package Manager: npm 8.19.2 
OS: linux x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1402.2 (cli-only)
@angular-devkit/core         14.2.2 (cli-only)
@angular-devkit/schematics   14.2.2 (cli-only)
@schematics/angular          14.2.2 (cli-only)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by crisbeto**
Updates the DOM element schema to add the `hgroup` element and to include some properties that weren't supported the last time the schema was updated.

Fixes https://github.com/angular/angular/issues/47545.

### CODE REVIEW

**Review by pkozlowski-opensource — COMMENTED** [review]
@crisbeto as discussed, the content of the files if auto-generated, instructions in: https://github.com/angular/angular/blob/main/packages/compiler/test/schema/dom_element_schema_registry_spec.ts#L194-L197

We should run this scrip to see if maybe there are other tags that we are missing. It will also require security review: https://github.com/angular/angular/blob/6a88bad0192516f26a5a008c0634b73456b9447c/packages/compiler/src/schema/dom_element_schema_registry.ts#L65-L74

**Comment by crisbeto** [comment]
I've run the script and pushed the changes in the fixup commit.

**Review by koto — APPROVED** [review]

**Comment by crisbeto** [comment]
For context, the review above is from the internal security team. @alxhub I've updated the PR description.

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Review by josephperrott — APPROVED** [review]
LGTM

Reviewed-for: fw-security

**Review by alxhub — APPROVED** [review]

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 48b354a83e6d94735a03eebb3a52c5698e7a0f44.

**Comment by jessicajaniuk** [comment]
Reverting. This caused a breakage in Google3.

**Comment by crisbeto** [comment]
For future reference: there was an app using the now-deprecated `content` element which was removed when I ran the script.

**Comment by crisbeto** [comment]
I've resolved the issue that caused the change to be reverted and [I've run a TGP just in case](http://test/OCL:480324913:BASE:480370153:1665503889478:63eed366).

**Comment by jessicajaniuk** [comment]
This PR was merged into the repository by commit 39b72e208b46d80f1d9a802cebf043c2ccf3c5f2.

**Pull request closed without merging**
