### PR TITLE
fix(Headers): serializable toJSON

### LINKED ISSUE #6073: HTTP Headers .toJSON() only returns values (not keys) of the headers
The current implementation of toJSON() of the Headers class only returns a JSON-Object containing all values.:

```
[
  [
    "no-cache"
  ],
  [
    "application/json; charset=utf-8"
  ],
  [
    "no-cache"
  ],
  [
    "-1"
  ]
]
```

IMO this should return a JSON Object mapping keys to values.

### PR DESCRIPTION
**Pull request by PatrickJS**
fixes #6073

### CODE REVIEW

**Comment by hansl** [comment]
Could you rebase this CL over master please?

**Comment by hansl** [comment]
LGTM, with the caveat that the dart_ddc test passes.

**Comment by gdi2290** [comment]
@hansl I rebased, I'm not sure why dart_ddc fails

**Comment by hansl** [comment]
Okay Dart DDC just passed. I'm going to stamp this. Good work!

**Comment by gdi2290** [comment]
kool, thanks

**Pull request closed without merging**
