### PR TITLE
docs: add new key/value option syntax in CLI

### PR DESCRIPTION
**Pull request by hybrist**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Documents the new supported syntax for CLI options.

This PR likely shouldn't land until the new CLI feature has landed (and/or is released): https://github.com/angular/angular-cli/pull/28362

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jkrems** [comment]
Checked rendered content on https://ng-dev-previews-fw--pr-angular-angular-57699-adev-prev-1p9ipm97.web.app/tools/cli and it looks like this worked.

**Review by josephperrott — APPROVED** [review]
LGTM

**Review by alan-agius4 — APPROVED** [review]
LGTM

**Comment by thePunderWoman** [comment]
This PR was merged into the repository by commit 9c5b4664b66f50a790f5047d81ad987e73d6340f.

The changes were merged into the following branches: main

**Pull request closed without merging**
