### PR TITLE
fix(core): add support for ES2015 constructor delegation

### PR DESCRIPTION
**Pull request by ts2do**
The change adds better support for native ES2015 targets. The previous
behavior didn't detect parameter delegation of constructor-less classes
containing at least one inline property initialization before
compilation.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

The following TypeScript code would incorrectly discard `Parent`'s ctorParameters when compiled targeting ES2015, causing a runtime error when instantiated. See issue [Dependency injection does not work with es2015 target](https://github.com/angular/material2/issues/8284) in angular/material2.
```
class Parent {
  constructor(protected dep: Dep) { }
}
class Child extends Parent {
  x = 10;
}
```

## What is the new behavior?

The above case should now be handled properly.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by trotyl** [comment]
Relates to https://github.com/angular/angular/pull/22642, https://github.com/angular/angular/pull/24014.

Better to land https://github.com/angular/angular/pull/22642 first as it's the real fix.

**Comment by petebacondarwin** [comment]
Hi @ts2do - are you interested in working more on this PR to get it merged? I see that your repository has disappeared so I guess that you may not be working with Angular any more?
In the meantime, I will take your changes and fix up the conflicts into a new PR.

**Comment by mbenna** [comment]
@petebacondarwin this problem may have been resolved in angular 8 at around beta 9 or thereabouts. Best to re-test with one if the 8 rc's before devoting too much time to it.

**Comment by petebacondarwin** [comment]
Yeah, I believe this fixed it https://github.com/angular/angular/pull/29232

**Pull request closed without merging**
