### PR TITLE
refactor(bazel): remove @angular/bazel protractor rule now provided by @bazel/protractor

### PR DESCRIPTION
**Pull request by gregmagolan**
Waiting on https://github.com/angular/components/pull/16989.

PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [x] Other... Please describe: protractor_web_test_suite has been moved to @bazel/protractor (code is now in https://github.com/bazelbuild/rules_nodejs) so it can be safely removed from this repository

## What is the current behavior?
@angular/bazel npm package provides npm_angular_bazel bazel repository which contains the protractor_web_test_suite rule.

## What is the new behavior?
protractor_web_test_suite removed from @angular/bazel npm package (and npm_angular_bazel bazel repository). This rule is now provided by the @bazel/protractor npm package which provides the npm_bazel_protractor repository that now contains the protractor_web_test_suite

The upgrade to the latest rules_nodejs is unblocked by this as well. https://github.com/angular/angular/pull/32151

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

BREAKING CHANGE:
Angular bazel users using protractor_web_test_suite from @angular/bazel npm package should now switch to the @bazel/protractor npm package

This should impact very few users and the user's that are impacted have a very easy upgrade path to switch to fetching the protractor_web_test_suite rule via the @bazel/protractor npm package.

### CODE REVIEW

**Comment by gregmagolan** [comment]
@jelbourn https://github.com/angular/components/pull/16980 got merged (thanks!) but this is still failing on material-unit-test so I assume material is not being tested from head. Does this PR need to wait until angular updates to the next material release?

**Comment by JoostK** [comment]
@gregmagolan Angular's does indeed not run Material tests from HEAD, but rather a specific commit hash. Required changes are show-cased in #32243.

**Comment by gregmagolan** [comment]
Thanks @JoostK !

**Review by alexeagle — APPROVED** [review]

**Comment by gregmagolan** [comment]
@devversion @jelbourn Can you TAL the material-unit-tests failure on CI? It looks unrelated to the protracotr remove. Something in `<mat-menu>` changed since the last commit?

**Comment by jelbourn** [comment]
Nothing has changed related to that, and everything builds locally when I run on master

**Comment by devversion** [comment]
@googlebot I consent.

**Comment by devversion** [comment]
@gregmagolan I pushed to this PR. There were two issues that surfaced due to the commit update:

1) The dev-app has been restructured and some targets were accidentally built in the `material-unit-tests` job.
2) Some gesture tests have been re-enabled on the components repository, but they need to be added to the blocklist here because there is a breaking change for HammerJS in `angular#master`.

**Comment by gregmagolan** [comment]
Thanks @devversion !

**Comment by gregmagolan** [comment]
caretaker: `ci/angular: size` failing but looks like its happening on all PRs presently

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
merge-assistance: global approval. the core/todo/bundle size increase seems bogus. is this a problem on master?

**Comment by gregmagolan** [comment]
> merge-assistance: global approval. the core/todo/bundle size increase seems bogus. is this a problem on master?

AFAIK yes. Pawel saw it here as well https://github.com/angular/angular/pull/32510.

**Pull request closed without merging**
