### PR TITLE
fix(core): add needed closure compiler warning suppression

### PR DESCRIPTION
**Pull request by alexeagle**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by alexeagle** [comment]
note, it's needed because tsickle adds a @type annotation in a syntactic location closure doesn't like:
```
throw errors_1.expressionChangedAfterItHasBeenCheckedError(types_1.Services.createDebugContext(view, nodeDef.index), `Query ${ /** @type {?} */((nodeDef.query)).id} not dirty`, `Query ${ /** @type {?} */((nodeDef.query)).id} dirty`, (view.state & 1 /* BeforeFirstCheck */) !== 0);
```

**Comment by tbosch** [comment]
So this is a workaround for a bug in tsickle? Could you file one and link it in the commit?

**Comment by alexeagle** [comment]
Added the comment pointing to https://github.com/angular/tsickle/issues/497

**Review by tbosch — APPROVED** [review]

**Comment by IgorMinar** [comment]
@alexeagle should this be marked for merge?

**Comment by alexeagle** [comment]
As far as I can tell we should still do this, the closure bug is not fixed. Not sure why we weren't forced to merge it sooner.

**Comment by IgorMinar** [comment]
Please apply the tag then. thanks

**Pull request merged**
