### PR TITLE
Correcti first sentence of marketing docs.

### PR DESCRIPTION
**Pull request by NachmanBerkowitz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by brandonroberts — CHANGES_REQUESTED** [review]
Update the git commit message to `docs: correct first sentence of marketing docs.`

**Comment by brandonroberts** [comment]
Thanks for the PR @NachmanBerkowitz! I left you some feedback. You must also [sign the CLA](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#cla) before this PR can move forward.

**Comment by brandonroberts** [comment]
Thanks @NachmanBerkowitz! Will you squash the commits down to a single commit with the git commit message `docs: correct first sentence of marketing docs.`

**Comment by NachmanBerkowitz** [comment]
Any tips on how I would do that?

**Comment by brandonroberts** [comment]
Sure. Here is a link to a previous comment with instructions. https://github.com/angular/angular/pull/26671#issuecomment-435064904

Alternatively you can close this PR and open a new one with the correct git commit message. If you need additional help, let me know.

**Comment by gkalpak** [comment]
Or as @StephenFluin would say: https://twitter.com/stephenfluin/status/1009904095073718275 😄

**Comment by NachmanBerkowitz** [comment]
Thank you for your help. I opened a new PR. I got an automated response
about signing a CLA. I already signed one for the previous PR.

**Comment by brandonroberts** [comment]
Did you use the same email address?

**Comment by NachmanBerkowitz** [comment]
Yes.

**Pull request closed without merging**
