### PR TITLE
docs(aio) Fix erroneous <a> tag to correct <div> tag

### PR DESCRIPTION
**Pull request by histamineblkr**
Fix an erroneous `<a>` tag that does not work in the "Select a dashboard hero" section. The faulty code is: 
`<a *ngFor="let hero of heroes"  [routerLink]="['/detail', hero.id]"  class="col-1-4">`
and should be:
`<div *ngFor="let hero of heroes"  [routerLink]="['/detail', hero.id]"  class="col-1-4">`

## PR Checklist
Does please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
There are no guidelines for finding erroneous documentation and how the project would like it fixed.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features): Changes the documentation

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

When using the `<a>` tag the console produces this error: 
`"Template parse errors:↵Unexpected closing tag "div" ("↵      <h4>{{hero.name}}</h4>↵    </div>↵  [ERROR ->]</div>↵</div>↵"): DashboardComponent@6:2↵Unexpected closing tag "div" ("↵    </div>↵  </div>↵[ERROR ->]</div>↵"): DashboardComponent@7:0"`

Issue Number: N/A

## What is the new behavior?
By changing it back to a `<div>` tag, everything functions correctly and as expected. Also, the `<code-example>`, path=, and picture will need to be updated accordingly.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
I apologize I can't create a better pull request since I don't have access to everything and can't really change everything properly. This is the code that needs to be fixed and then a description of what should be fixed. I tried to word it close to how the tutorial was written but it should probably be read over and examined. Also, please note that the <code-example>, path=, and picture will need to be updated accordingly.

### CODE REVIEW

**Comment by Gillespie59** [comment]
Personally I do not like routerLink on unfocusable HTML element. For a11y purpose.

**Comment by histamineblkr** [comment]
I have no opinion of the routerLink personally. I only wanted to fix the documentation that currently doesn't work for the Heroes Tutorial.

**Comment by wardbell** [comment]
Thanks for your consideration but his change is incorrect, both because it recommends a bad practice and because the actual code runs just fine without the error described above. You can confirm that easily by running the plunker for that tutorial.

We would not make this change even if there were an error. We would find and fix the root cause that prevented use of `[routerLink]` with `<a>`

Closing.

**Comment by histamineblkr** [comment]
Sorry, but your tutorial code does not work. How are you going to tell me it doesn't work and just close it?

**Pull request closed without merging**
