### PR TITLE
integration test for #35095

### PR DESCRIPTION
**Pull request by IgorMinar**
mimics:

```
ng new ngcc-cleanup
yarn add @angular/{animations,common,compiler,core,forms,platform-browser,platform-browser-dynamic,router,compiler-cli,language-service}@9.0.0-rc.12
ng add @angular/material@next
ng generate @angular/material:nav my-navigation
ng generate @angular/material:dashboard my-dashboard
ng build
ng update @angular/core@next
ng build
```

### CODE REVIEW

**Comment by IgorMinar** [comment]
I can't reproduce the issue for some reason. @cyrilletuzi can you please take a look at https://github.com/angular/angular/pull/35101/files#diff-52db63aae44ee042dbf0c1ff4536cd0eR8-R9 and check if I missed something.

**Comment by gkalpak** [comment]
In #35095, @cyrilletuzi mentioned this happens when updating to rc.13 while `ng serve` is running (so it might be the case that `ng build` is not affected). Could it be that the CLI (or ngtsc) is caching some files during `ng serve`, so they do not see the updated content after ngcc cleaning up?

**Comment by cyrilletuzi** [comment]
@IgorMinar I can definitely reproduce the issue:
- with your steps in PR message
- with your PR git strategy (rollback `package.json` and install again).

The only difference is that I use npm (I don't have yarn). So I would suspect that `yarn install` does more cleaning that `npm install`? 

@gkalpak Nope, I can reproduce with `ng build` too.

Doing a reproduction repo right now, I'll post it in a few seconds.

**Comment by cyrilletuzi** [comment]
Repro: [https://github.com/cyrilletuzi/ngcc-cleanup](https://github.com/cyrilletuzi/ngcc-cleanup)

To reproduce:
```bash
git clone https://github.com/cyrilletuzi/ngcc-cleanup
cd ngcc-cleanup
npm run issue
```

Steps done to generate project:
```bash
ng new ngcc-cleanup
cd ngcc-cleanup
ng add @angular/material@next
ng generate @angular/material:nav my-navigation
git add -A
git commit -m "test"
```

**Comment by elvisbegovic** [comment]
Hm If we consider this https://github.com/angular/angular/issues/35082#issuecomment-579823144 Pete’s comment Yarn doesn’t have the problem but npm yes.

**Comment by cyrilletuzi** [comment]
@elvisbegovic Yeah I think it's the issue.

**Comment by cyrilletuzi** [comment]
Note that it only affects projects which are upgrading from v8 with Ivy or v9-beta/rc, ie. experimental scenarios. So it's a blocker for a 9.0.1 release but for the 9.0.0 release it's not that critical.

About the issue:  how does #35079 detect which packages must be cleaned up? Is that possible that librairies need to be rebuilt with the very last rc to be detected and cleaned up?

**Comment by IgorMinar** [comment]
As was already mentioned, it just hit me this morning that I have to use npm and not yarn to repro this because yarn discards and resets node_modules during each `install` or `add/remove`.

**Comment by gkalpak** [comment]
@IgorMinar, I added a quick (and hacky) test in the `ngcc` integration project in #35106.
We can add a proper integration test (featuring `ng build`) in a follow-up PR.

**Comment by IgorMinar** [comment]
@gkalpak added a sufficient integration test in #35106 so I'm going to close this PR.

**Pull request closed without merging**
