### PR TITLE
docs(aio): fixed typo

### PR DESCRIPTION
**Pull request by cristifilip**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
Fixed typo: htttp to http
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by IamManchanda — APPROVED** [review]
ofcourse CLA for merge but looks good

**Comment by IamManchanda** [comment]
But you should update your commit message 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Comment by cristifilip** [comment]
I signed it!

**Comment by Foxandxss** [comment]
Thanks, but we are not yet authoring in this repo so all fixes should go in the other repo.

But this one is already fixed ;)

**Pull request closed without merging**
