### PR TITLE
Bump rxjs to 5.0.0-rc.2

### PR DESCRIPTION
**Pull request by SamuelMarks**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
beta.12

**What is the new behavior?**
rc.2

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by vicb** [comment]
See the `npm-shrinkwrap.readme.md` to lock the deps.

@robwormald could you further comment / review ?

Thanks

**Comment by SamuelMarks** [comment]
Good point @vicb, fixed up my commit with:
```
find -type f -exec sed -i 's/5.0.0-beta.12/5.0.0-rc.1/g' {} \;
```

**Comment by vicb** [comment]
The CI issue was a flake.

LGTM nut waiting for @robwormald to chime in.

**Comment by robwormald** [comment]
LGTM 👍

**Comment by vikerman** [comment]
@SamuelMarks , @robwormald , @vicb  -  rxjs rc.2 is out. Do we still need this PR - Or should rxjs be updated to rc.2 directly?

**Comment by robwormald** [comment]
Let's bump to rc2 💪

**Comment by vicb** [comment]
@SamuelMarks could you please update the PR ?

**Comment by vicb** [comment]
_we will try to merge it before the next RC is out ;)_

**Comment by SamuelMarks** [comment]
Updated

**Comment by vicb** [comment]
@SamuelMarks Not sure how you installed the pkg but it fails. You can follow the instructions in the shrinkwrap readme.

**Comment by vicb** [comment]
@SamuelMarks do you have time to update or should I take the PR over ? Thanks

**Comment by SamuelMarks** [comment]
@vicb - Got distracted with my own things, anyway was this the only error?
> Error at /home/travis/build/angular/angular/node_modules/rxjs/observable/dom/AjaxObservable.d.ts:1:1: Cannot find type definition file for 'chai'.

**Comment by vicb** [comment]
can't remember exactly, you should be able to figure out by looking at the Travis logs.

**Comment by SamuelMarks** [comment]
Can you reopen so the CI does its thing?

**Comment by ciesielskico** [comment]
RC4 is out :)

**Comment by gdi2290** [comment]
a futture rxjs version is needed to fix this issue https://github.com/angular/angular/issues/13029 and https://github.com/ReactiveX/rxjs/issues/2134 following this PR https://github.com/ReactiveX/rxjs/pull/2135

**Pull request closed without merging**
