### PR TITLE
fix(platform-server): support svg elements with namespaced attributes

### LINKED ISSUE #15034: bug(platform-server) setAttributeNS is not implemented
```
[x] bug report
```

**Current behavior**
If a component is using an SVG name-spaced attribute such as `xlink:href` – regardless of whether it is bound to data or not – causes server side rendering to fail. This is because the `setAttributeNS` method for `Parse5DomAdapter` is not implemented. https://github.com/angular/angular/blob/master/modules/@angular/platform-server/src/parse5_adapter.ts#L469

```
Error: Uncaught (in promise): not implemented
    at resolvePromise (/ng-universal-demo-master/dist/main.js:57920:31) [angular]
    at resolvePromise (/ng-universal-demo-master/dist/main.js:57896:17) [angular]
    at /ng-universal-demo-master/dist/main.js:57956:17 [angular]
    at Object.onInvokeTask (/ng-universal-demo-master/dist/main.js:5563:41) [angular]
    at ZoneDelegate.invokeTask (/ng-universal-demo-master/dist/main.js:57639:36) [angular]
    at Zone.runTask (/ng-universal-demo-master/dist/main.js:57443:47) [<root> => angular]
    at drainMicroTaskQueue (/ng-universal-demo-master/dist/main.js:57806:35) [<root>]
    at Server.ZoneTask.invoke (/ng-universal-demo-master/dist/main.js:57697:25) [<root>]
    at emitTwo (events.js:106:13) [<root>]
    at Server.emit (events.js:191:7) [<root>]
    at parserOnIncoming (_http_server.js:562:12) [<root>]
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23) [<root>]
```

**Expected behavior**
Platform-server should be able to render any SVG markup in templates.

**Minimal reproduction of the problem with instructions**
I have recreated this issue in a forked version of @robwormald 's demo: https://github.com/winkerVSbecks/ng-universal-demo/blob/master/src/app.ts#L15

You should be able to recreate this by using this component in an app using platform-server:
```ts
@Component({
    selector: 'icon',
    template: `<svg viewBox="0 0 20 20">
      <use xlink:href="#clear"></use>
    </svg>`,
})
export class IconComponent {}
```

**What is the motivation / use case for changing the behavior?**
To be able to use SVG in component templates when using platform-server. 
In my specific case I am using it to implement an icon system using the sprite technique. 
The issue can be fixed with the following implementation of `setAttributeNS`. If that seems reasonable I can submit a PR:

```ts
function(element, ns, attribute, value) {
    if (ns) {
      element.attribs[attribute] = value;
    }
  };
```

**Please tell us about your environment:**
macOS 10.12.3
NPM & Yarn
Express

* **Angular version:** 4.0.0-rc.2
 
* **Language:** TypeScript 2.2.1

* **Node (for AoT issues):** `node --version` =   v7.4.0

### PR DESCRIPTION
**Pull request by vikerman**
Fixes #15034

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
SVG element with namespace elements would throw an exception

**What is the new behavior?**
Treat namespaces attributes as normal attributes and don't throw an exception.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Review by alxhub — APPROVED** [review]

**Comment by istiti** [comment]
Does this merge will fix this issue too : https://github.com/angular/angular/issues/14865 ? 

Because I get: 
```
Failed to execute 'setAttributeNS' on 'Element': '' is an invalid namespace for attributes.
EXCEPTION: Failed to execute 'setAttributeNS' on 'Element': '' is an invalid namespace for attributes.
EmulatedEncapsulationDomRenderer2.DefaultDomRenderer2.setAttribute 
...
```

**Comment by DzmitryShylovich** [comment]
@istiti please, don't spam everywhere :)

**Comment by istiti** [comment]
@DzmitryShylovich it helpedlol  when I put your code my app compile with svg correctly  ! donno how but it did !

**Comment by DzmitryShylovich** [comment]
@istiti https://github.com/angular/angular/pull/14874 for browser

**Pull request merged**
