### PR TITLE
fix(aio): invalid formatting in architecure.md

### PR DESCRIPTION
**Pull request by cooperka**
Fixes the formatting by removing an extra underscore. Introduced in https://github.com/angular/angular/commit/e110a80cafb4d8677d13a51e3c7e967a577ca6d1#diff-9ac9c6a9277eea9856d75249a7c0a40aL127.

### CODE REVIEW

**Comment by cooperka** [comment]
CLA signed!

**Review by Foxandxss — APPROVED** [review]

**Comment by alxhub** [comment]
@Foxandxss I removed the merge label as this needs AIO approval first.

**Comment by Foxandxss** [comment]
not really. It needs my permission. That is a bug that @petebacondarwin fixes in a different PR

**Comment by Foxandxss** [comment]
More here https://github.com/angular/angular/pull/18122

**Review by petebacondarwin — APPROVED** [review]

**Pull request merged**
