### PR TITLE
fix(router): fix anchor scrolling

### LINKED ISSUE #29099: Anchor scrolling only works first time it is clicked and not on subsequent clicks.
# 🐞 bug report

### Affected Package

"@angular/router": "^7.2.5",

### Description
In attached stackblitz.

1. Click 'scroll to A'. Page correctly scrolls to anchor A.
2. Scroll the browser window back to top of page.
3. Click 'scroll to A'. Page does not correctly scroll to anchor A.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-q641ci

## 🌍  Your Environment
  "dependencies": {
    "@angular/common": "^7.2.5",
    "@angular/compiler": "^7.2.5",
    "@angular/core": "^7.2.5",
    "@angular/forms": "^7.2.5",
    "@angular/platform-browser": "^7.2.5",
    "@angular/platform-browser-dynamic": "^7.2.5",
    "@angular/router": "^7.2.5",
    "core-js": "^2.6.5",
    "rxjs": "^6.4.0",
    "zone.js": "^0.8.29"
  }

### PR DESCRIPTION
**Pull request by s-gbz**
Fixes #29099

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by s-gbz** [comment]
Hello there @jasonaden! I finally got around to deal with the long standing issue of "not being able to scroll to the same anchor multiple times".

As you suggested I checked all methods in `viewPort.ts` & `routerScroller.ts` - they seem to be fine.
After further digging I noticed that the instance denying multiple navigations to the same anchor is located in [router.ts](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L476):

```typescript
private setUpNavigations(...):
    ...
               // SPECIFICALLY HERE
                const processCurrentUrl =
                    (this.onSameUrlNavigation === 'reload' ? true : urlTransition) &&
                    this.urlHandlingStrategy.shouldProcessUrl(t.rawUrl);

                if (processCurrentUrl) {
                     // Issue resolved if navigation is allowed here
                      ...
```
The [current state](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L553) is that navigations to the same target end up here: 

```typescript
private setUpNavigations(...):
    ...
              } else {
                   /* When neither the current or previous URL can be processed, do nothing other
                    * than update router's internal reference to the current "settled" URL. This
                    * way the next navigation will be coming from the current URL in the browser.
                    */
                    this.rawUrlTree = t.rawUrl;
                    this.browserUrlTree = t.urlAfterRedirects;
                    t.resolve(null);
                    return EMPTY;
                  }
```
___
**Questions**: 

1.) Where in the method would you suggest implementing a check on "legit same anchor navigation"?
- processCurrentUrl
- process PreviousUrl
- a totaly different place?

2.) How should such a check look like?

3.) How would you go about testing the case?
- I saw a similiar [example](https://github.com/angular/angular/pull/20030/files#diff-10959aa4f134e9550f6bf0392be784cdR58), but I'm not quite sure how to test the "actual scrolling".

Thanks a lot for patience and support! ❤️

**Comment by gkalpak** [comment]
cc @atscott (as he's the current `@angular/router` owner).

**Comment by s-gbz** [comment]
Sorry to bother @atscott - is there someone else I could refer to if things are a little busy right now? :)

**Comment by s-gbz** [comment]
Hey there @kapunahelewong!
Is there any chance you could refer this issue to someone to take a look?
I've been dragging it to long and think we're almost done here :)

Please excuse in case I am too unpatient!

**Comment by mgechev** [comment]
Hey @s-gbz, we really appreciate the time you've spent in exploring the solution. At that time, we wouldn't be able to provide you with a guidance to move forward with the fix. Since the PR is still in a very early stage, I'd recommend closing it for now.

If you're looking for a way to contribute, I'd encourage you to check out our [hotlist:community-help](https://github.com/angular/angular/issues?q=is%3Aopen+is%3Aissue+label%3A%22hotlist%3A+community-help%22) label. There you can find issues that are a better fit for a community contributions - with fewer unknowns and better scoped.

**Pull request closed without merging**
