### PR TITLE
build: remove unreferenced tsconfig-build.json files

### PR DESCRIPTION
**Pull request by alexeagle**
These are no longer needed since Bazel generates a tsconfig for each compilation

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
:tada:

**Review by petebacondarwin — APPROVED** [review]
CodeFresh failed because of a Docker problem. Probably a flake. An amended commit should kick it off again.

**Comment by ocombe** [comment]
Are you sure that we're not using `packages/common/locales/tsconfig-build.json` anymore?

**Comment by alexeagle** [comment]
@ocombe I can't find any reference, and the CI is green. anything else you want to check before merging?

**Comment by alexeagle** [comment]
Caretaker assist: Not windows-sensitive, ran into this morning's Codefresh outage

**Pull request closed without merging**
