### PR TITLE
Fixing typo error

### PR DESCRIPTION
**Pull request by KianYang-Lee**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Missing space between words.

Issue Number: N/A

## What is the new behavior?
Fixed the typo.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@KianYang-Lee thanks for improving Angular docs.

Could you please [sign the CLA](https://github.com/angular/angular/pull/48891/checks?check_run_id=11012764569) so that we can proceed with the review? Also it looks like the CI is failing (likely due to the commit message), could you please take a look when you get a chance? Thank you.

**Comment by KianYang-Lee** [comment]
@AndrewKushnir I've done the necessary. Let me know if you still need anything. Thank you.

**Review by AndrewKushnir — APPROVED** [review]
@KianYang-Lee thanks for improving Angular docs!

**Comment by atscott** [comment]
This PR was merged into the repository by commit 57d0c03e17cf8eabac0a344610fbdc1e22f90088.

**Pull request closed without merging**
