### PR TITLE
docs: replace image with one containing correct text

### PR DESCRIPTION
**Pull request by petebacondarwin**
The previous image referred to "Mr IQ". The example application
(and the content of the referring guide) actually uses "Dr IQ".

Closes #34823

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
What happened to the red rectangle around `<no name set>`? :grin:
I assume it was intentionally left out. LGTM either way.

**Review by gkalpak — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by petebacondarwin** [comment]
Merge-assistance - for some reason I am not able to remove the review requests for @AndrewKushnir, which are not needed.

**Comment by petebacondarwin** [comment]
> What happened to the red rectangle around `<no name set>`? 😁
> I assume it was intentionally left out. LGTM either way.

Uhh, yeah. To be honest it doesn't seem to be very important.

**Pull request closed without merging**
