### PR TITLE
Update code to match example image

### PR DESCRIPTION
**Pull request by v-ivywalobwa**
Update code in guide to match the example image below it.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
`Dr IQ` is used in a number of other places too (including the comment in the file changed by this PR). Either we need to change all these instances consistently or perhaps it might be simpler to update the image instead?

**Review by mhevery — APPROVED** [review]

**Review by mhevery — COMMENTED** [review]
We need CLA signed.

**Comment by Ivy-Walobwa** [comment]
@googlebot I signed it!

**Comment by petebacondarwin** [comment]
@Ivy-Walobwa - are you able to update the other places where `Dr IQ` is used too?

**Comment by petebacondarwin** [comment]
Replacing with https://github.com/angular/angular/pull/40022 due to no response here.

**Pull request closed without merging**
