### PR TITLE
Docs: Update installation.md

### PR DESCRIPTION
**Pull request by NathanJohnNJ**
Corrected grammar/spelling error.

## PR Checklist
Please check if your PR fulfills the following requirements:
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A
## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeanMeche — APPROVED** [review]
Thanks for this !

**Comment by JeanMeche** [comment]
Could you please reword your commit and make it a `docs: ...` commit. This would satisfy the linting job and follow [our guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit). Thank you.

**Comment by NathanJohnNJ** [comment]
I think that should be done now, do I need to do anything else for the tests to run again?

**Comment by JeanMeche** [comment]
You actually changed the title of the PR, but the commit itself hasn't changed.

**Comment by NathanJohnNJ** [comment]
Ah sorry! I actually changed the commit at first, then checked the docs and decided to do the title instead because I thought that's what the docs said 🙈 I'll try again now, sorry about this!

**Comment by NathanJohnNJ** [comment]
I hope that's done now, I managed to add a second commit on with the correct heading. Wasn't sure whether to add the same comment again but since it's linked to the same PR I have just added a simple comment.  Sorry for all this fuss for a minor grammatical error, and thanks for the work put in to Angular, I'm enjoying getting to grips with it and trying out some new code!

**Comment by JeanMeche** [comment]
We wanted this change to be a single commit, you can do that be shashing them into one with a interactive rebase !

**Comment by NathanJohnNJ** [comment]
I'm sorry I can't do it. I've looked into what an interactive rebase is, and it needed me to perform some commands on the CLI, so I tried to clone the repository so I could go into my branch and run the commands, but every time there is an error whilst checking out. I then tried to download as .zip and thought it would work the same as if I had cloned it from git, which it did not. 
I'm going to just close this request down, at least you are aware of the correction needed now, so if you want to implement it on a future commit of your own then you can ☺️ 
Sorry for all the bother for such a minor correction, and sorry for my delayed responses, I've been moving house, probably not the best time to try and contribute to something so big for the first time haha!

**Pull request closed without merging**
