### PR TITLE
style(ExceptionHandler): Update code example in comment block to correct syntax error.

### PR DESCRIPTION
**Pull request by nickraphael**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:  Updated commented code example.
```

**What is the current behavior?** (You can also link to an open issue here)
Incorrect code sample in comment block.

**What is the new behavior?**
Correct example code in comment block

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

Fixed example code to bootstrap a custom exception handler.

### CODE REVIEW

**Comment by vicb** [comment]
> The commit message follows our guidelines:

Sure ?

**Comment by nickraphael** [comment]
Yes, it's pretty simple fix.  It was just a bit confusing when I was copy-n-pasting from that section of the comments.

**Comment by vicb** [comment]
It does not

**Comment by nickraphael** [comment]
The current comment looks like this...

bootstrap(MyApp, {provide: ExceptionHandler, useClass: MyExceptionHandler}])

You can see there is a ] but no opening [.  That's what this pull request will correct.

**Comment by vicb** [comment]
see https://github.com/angular/angular/pull/10026#issuecomment-232260211

**Pull request closed without merging**
