### PR TITLE
docs: add ngrx book to the docs

### PR DESCRIPTION
**Pull request by softchris**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

only one reference to NGRX

Issue Number: N/A

## What is the new behavior?

This is a brand new book covering the latest in NGRX and Angular

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Comment by jasonaden** [comment]
Thanks. Looks like this needs a bit of cleanup. I'll ask for a review.

**Comment by petebacondarwin** [comment]
@jasonaden the `comp: aio` label is for the docs infrastructure (e.g. doc-gen, previews, doc-viewer application) not for content.

**Review by StephenFluin — CHANGES_REQUESTED** [review]
It looks like this is in the wrong category. Can we move it to the books section?

**Comment by brandonroberts** [comment]
@softchris will you move this to the appropriate category and amend the commit message to: `docs: add book on building apps with ngrx`

**Review by StephenFluin — APPROVED** [review]

**Comment by brandonroberts** [comment]
Caretaker: For some reason the pullapprove didn't get added to the checks.

**Review by StephenFluin — APPROVED** [review]

**Pull request closed without merging**
