### PR TITLE
docs(common): clean up comment

### PR DESCRIPTION
**Pull request by johnnygerard**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by johnnygerard** [comment]
The [//integration/cli-signal-inputs:test](https://github.com/angular/angular/actions/runs/8466609539/job/23195731940?pr=55088#step:6:583) failed.

**Comment by bencodezen** [comment]
@johnnygerard Is there a reason to delete the comment? It seems like it was meant to be a new line, but maybe I'm missing some context here?

**Comment by johnnygerard** [comment]
> @johnnygerard Is there a reason to delete the comment? It seems like it was meant to be a new line, but maybe I'm missing some context here?

I'm assuming this is an editing error that happened while copy pasting.

We can compare both properties:

```typescript
  /**
   * For responsive images: the intrinsic width of the image in pixels.
   * For fixed size images: the desired rendered width of the image in pixels.
   */
  @Input({transform: numberAttribute}) width: number | undefined;
```

```typescript
  /**
   * For responsive images: the intrinsic height of the image in pixels.
   * For fixed size images: the desired rendered height of the image in pixels.* The intrinsic
   * height of the image in pixels.
   */
  @Input({transform: numberAttribute}) height: number | undefined;
```

If this is intentional, I don't understand the purpose of this extra sentence and the asterisk.

**Review by bencodezen — APPROVED** [review]
Thanks for catching this!

**Pull request closed without merging**
