### PR TITLE
docs: change "comprises" to "consists of" in getting started

### PR DESCRIPTION
**Pull request by AMDphreak**
per Google Guidelines.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #33234 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Excellent choice of words, @AMDphreak  😊

Ok, so to get it to pass, try amending your commit message to something like this:

```
docs: change comprises to consists of in getting started" 
```

You just want to make sure you have `docs:` and follow it, ideally with the verb and object. It looks like you're already familiar with the process, but I share [my own notes for my workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#how-to-amend-a-commit) with everyone. Please feel free to tag me with questions or when you're ready.

**Comment by dannyskoog** [comment]
@AMDphreak please format your commit(s) according to https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

Thanks

**Comment by AMDphreak** [comment]
I signed the CLA, but I provided my personal email address, instead of the one that shows up on my web-based commits (AMDphreak@users.noreply.github.com). The CLA form from Google won't let me change the email or sign a new CLA with the right email. They have a link to add alternate emails to my Google account, but this doesn't work because the github email is a no-reply email.

**Comment by AMDphreak** [comment]
@googlebot I signed it!

**Comment by kapunahelewong** [comment]
Hey @AMDphreak, don't forget to amend the commit message. If you change it to 
```
docs: change "comprises" to "consists of" in getting started
```
and rebase, I think it should pass. In case you're interested, I have my [own notes](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca) of my own workflow you can check out. If you have any questions, just tag me. Will you let me know when you're ready so I can help land this? Thanks! 😊

**Comment by AndrewKushnir** [comment]
Closing this PR since the `aio/content/start/index.md` file was updated and the mentioned section was rewritten.

**Pull request closed without merging**
