### PR TITLE
feat(forms): Add in toggle for enable/disable

### PR DESCRIPTION
**Pull request by MathewBerg**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

To run disable/enable for a control based on a variable something like the following may exist:

`enabled ? control.enable({ emitEvent: false }) : control.disable({ emitEvent: false }). `

Or

```
if(enabled){
  control.enable({ emitEvent: false })
}
else{
  control.disable({ emitEvent: false })
}
```

Or

`(enabled ? control.enable : control.disable)({ emitEvent: false })`

## What is the new behavior?

This introduces a new api toggle that can be used like this:

`control.toggle(enabled, { emitEvent: false })`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I'm not sure if toggle is the best name for the api. I also defaulted the value to be: "enabled" instead of "disabled".

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
@MathewBerg thanks for creating this PR. From the API perspective, I don't think the "enabled" argument is expected in the `toggle` function. Instead, the current state can be detected internally in the `toggle` function and switched to the opposite value. However, if we add more logic into the `FormControl`, we'll start hitting the issue with a non-tree-shakable code described in #39640.

Given the fact that this helper method can be implemented outside of the Forms package and adding it (with auto detection of the current state) will result in some extra code being added to app bundles, I'm closing this PR. It will be linked from #39640 and we can come back to the enable/disable helper methods once #39640 is resolved.

**Comment by MathewBerg** [comment]
@AndrewKushnir thanks a ton for responding. I completely understand the hesitation to add this at the moment. As for calculating the internal state I'm not sure if that's what I was intending with this feature. I don't want to constantly have it flip if I call toggle repeatedly. Instead my intent was to be able to pass a value that can either make it enabled or disabled all at once. In my example:

`(enabled ? control.enable : control.disable)({ emitEvent: false })`

enabled would come from an outside source of the form.

**Comment by AndrewKushnir** [comment]
@MathewBerg thanks for additional information.

I think you can also consider using a "boxed" value if you have a state info before creating a FormControl:

```
const isDisabled = false; // received from an external source
const control = new FormControl({value: 'some-value', disabled: isDisabled});
```

If you get the value later (after control creation), you can probably create a helper method using the code that you've mentioned.

**Comment by MathewBerg** [comment]
While I'm fine with a helper method (that's what we have now) we have 100s of these all over the codebase and so having it built right in would really help reduce that duplication.

**Pull request closed without merging**
