### PR TITLE
Update package.json for @angular/upgrade to point to correct UMD bundle entry point

### LINKED ISSUE #11249: @angular/upgrade package.json points to the wrong UMD bundle entry point
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
@angular/upgrade for rc.6 module's package.json does not point to the correct `bundles/upgrade.umd.js` entry point, which causes webpack builds to break. It currently points to `bundles/core.umd.js`

**Expected/desired behavior**
The "main" entry point in the package.json should point to the upgrade modules `bundles/upgrade.umd.js`

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

1. `npm install @angular/upgrade@2.0.0-rc.6`
2. Import the `UpgradeAdapter` from @angular/upgrade and use the constructor.
3. In a normal webpack build, I receive a 

> Uncaught SyntaxError: Unexpected token export

It appears that since it isn't pointing to the umd entry point, webpack is  bundles the ES2015 export statement directly into the bundle. Therefore the source that causes the browser exception looks like this:

```
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
/**
 * @module
 * @description
 * Entry point for all public APIs of the upgrade package.
 */
export * from './src/upgrade';
//# sourceMappingURL=index.js.map


/*****************
 ** WEBPACK FOOTER
 ** ./~/@angular/upgrade/index.js
 ** module id = 107
 ** module chunks = 0
 **/
```

If you change the package.json entry point to the correct UMD bundle, the webpack build behaves as expected

**What is the expected behavior?**
The expected behavior is a working webpack bundle that follows the package.json import

**What is the motivation / use case for changing the behavior?**
Utilizing the @angular/upgrade module

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [TypeScript X.X ]

### PR DESCRIPTION
**Pull request by Polvista**
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

**Other information**:
Fixes https://github.com/angular/angular/issues/11249

### CODE REVIEW

**Comment by Polvista** [comment]
@googlebot I signed it!

**Comment by IgorMinar** [comment]
thanks!

**Comment by moff** [comment]
@googlebot I thought it'll be fixed in RC7 since [it was already reported](https://github.com/angular/angular/issues/11249) and I've been waiting for this to be applied - fixing that manually after each `npm install` is awkward.

**Comment by vicb** [comment]
@moff don't expect an answer from @googlebot - that's a stupid bot !

**Comment by moff** [comment]
@vicb oops, I thought it's moderated by a real person, hehe!

**Pull request merged**
