### PR TITLE
Fix typo in binding.md

### PR DESCRIPTION
**Pull request by twittwer**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by bencodezen — APPROVED** [review]
Thanks for catching this!

**Comment by JeanMeche** [comment]
Hi, do you mind rewording your commit to follow our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit), thank you ?

**Comment by twittwer** [comment]
> Hi, do you mind rewording your commit to follow our [commit message guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit), thank you ?

Yes, I will do it during the weekend, as soon as I'm at a computer to check it out locally or is this possible with the web IDE as well?

**Comment by twittwer** [comment]
> Thanks for catching this!


@bencodezen Thx for the nice guide in the first place 👍

**Comment by JeanMeche** [comment]
You'll need to do it on a computer with git yes.

**Comment by twittwer** [comment]
Sorry, for the delay, but now it should match the style guide

**Pull request closed without merging**
