### PR TITLE
Mark provider interfaces as public

### PR DESCRIPTION
**Pull request by jbogarthyde**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:  #29830, #29963

## What is the new behavior?
Makes doc for DI provider interfaces available, fixes broken links in API docs

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jbogarthyde** [comment]
@alxhub This is failing tests because, now that `ValueSansProvider` is exported, it turns out the intended doc example doesn't exist. It needs to be added to `examples/core/di/ts/provider_spec.ts`, along with the other provider examples. Can you provide a suitable example, or refer me to someone else who can?

**Comment by jbogarthyde** [comment]
@alxhub Please provide an example or confirm that it doesn't need one.
I also need someone to add these two interfaces to the golden file - they may not need actual doc, but the automatic links need to not break.

**Comment by jbogarthyde** [comment]
@alxhub Please provide an example or confirm that it doesn't need one.
I also need someone to add these two interfaces to the golden file - they may not need actual doc, but the automatic links need to not break.

**Comment by jbogarthyde** [comment]
@alxhub Please provide an example or confirm that it doesn't need one.
I also need someone to add these two interfaces to the golden file - they may not need actual doc, but the automatic links need to not break.

**Comment by jbogarthyde** [comment]
Thanks @brandonroberts , for fixing the golden file.
I still need someone to provide the referenced example or confirm that it doesn't need one.

**Comment by brandonroberts** [comment]
@jbogarthyde I went back and looked through older versions of that spec file and `ValueSansProvider` didn't exist. I think its safe to remove that example as you won't use it directly.

**Comment by jbogarthyde** [comment]
Needs code-owner approval

**Review by IgorMinar — APPROVED** [review]

**Comment by brandonroberts** [comment]
Caretaker note: This is a docs only change that includes additions to the public API, but should not impact g3. Please run presubmit.

**Pull request closed without merging**
