### PR TITLE
docs: fix crisis-list component file selection

### PR DESCRIPTION
**Pull request by FrederikSchlemmer**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #27187

## What is the new behavior?

Changed one HTML-File with the correct TS-File.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
👌

**Comment by FrederikSchlemmer** [comment]
@jenniferfell I think the PR's ready so far, don't you? I'd do a rebase if necessary.

**Comment by gkalpak** [comment]
Closed and reopen in the hope of re-triggering CI stauses (for example `buildkite` has been temporarily removed), but that didn't work that well :grin:
@FrederikSchlemmer, could you rebase (maybe that'll help).

**Comment by FrederikSchlemmer** [comment]
@gkalpak I made a rebase, but I don't know why new changed files were added... I took the following steps:

1. Checkout and pull down latest master from upstream (git checkout master) (git pull upstream master)

2. Rebase your branch on top of master with the updated commit message (git checkout FixRoutingNavigation) (git rebase master -i)

3. Push your branch back up (git push origin --force-with-lease FixRoutingNavigation)

**Comment by gkalpak** [comment]
Not sure what might have gone wrong (it sounds like your local master had deviated from `upstream/master`).
In any case, I just realized this PR is a duplicate of #27025, so let's go woth that (since it came first).

**Pull request closed without merging**
