### PR TITLE
Set type assertion to the recommended way

### PR DESCRIPTION
**Pull request by kroeder**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

The doc for *User Input* uses 
```
this.values += (<HTMLInputElement>event.target).value + ' | ';
```
Angular CLI generates a `tslint` that uses `tslint:recommended` by default and the recommended type assertion value is `"no-angle-bracket-type-assertion": true,`

Issue Number: N/A

## What is the new behavior?

Set 
```
this.values += (<HTMLInputElement>event.target).value + ' | ';
```
to
```
this.values += (event.target as HTMLInputElement).value + ' | ';
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by kroeder** [comment]
Accidentally copy pasted the wrong commit message. I'll fix that

**Comment by kroeder** [comment]
If you agree with this change I can also scan for more places in the documentation that use the previous syntax and fix those as well. Just let me know! 🙂

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
thank you for the contribution @kroeder !

**Comment by IgorMinar** [comment]
merge-assistance: global approval

**Pull request closed without merging**
