### PR TITLE
docs: fix broken link @ /guide/forms/reactive-forms#reactive-forms-api-summary

### PR DESCRIPTION
**Pull request by DanNisenson**
fix link @ /guide/forms/reactive-forms#reactive-forms-api-summary 
prev: /api/forms
current: /api#forms

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Broken link

Issue Number: [#56846](https://github.com/angular/angular/issues/56846)

## What is the new behavior?
working link

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JeanMeche** [comment]
Can you please revert all those format changes, we'd like this change to be the link update only.

**Review by JeanMeche — APPROVED** [review]
Thanks for this !

**Comment by JeanMeche** [comment]
Can you squash both commits into a signle one, we'd like the change to be a single one, thank you.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit e7da8c2b02ae454f377cfa8a854f669cbdde034c.

The changes were merged into the following branches: main, 18.0.x, 18.1.x

**Pull request closed without merging**
