### PR TITLE
docs(core): fixes minor typo in initNgDevMode function docs

### PR DESCRIPTION
**Pull request by sonukapoor**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: global-docs-approvers

**Comment by AndrewKushnir** [comment]
Hi @sonukapoor, thanks for creating this PR 👍 

I just noticed that the commit message says `fix(core)`, so this change will be included into the changelog for the next release. I believe we should change commit message to `docs(core)`, so that we avoid including it (as we do for other docs-related commits). Could you please update the commit message when you get a chance?

Thank you.

**Comment by AndrewKushnir** [comment]
Merge assistance (note to Caretaker): this PR was created based on the branch in `angular/angular` repo, so the `deploy_aio` CircleCI job fails (it expects PRs created from the forks only). This is a docs-only low-risk change, so we can merge it as is.

**Comment by sonukapoor** [comment]
> Merge assistance (note to Caretaker): this PR was created based on the branch in `angular/angular` repo, so the `deploy_aio` CircleCI job fails (it expects PRs created from the forks only). This is a docs-only low-risk change, so we can merge it as is.



> Hi @sonukapoor, thanks for creating this PR 👍
> 
> I just noticed that the commit message says `fix(core)`, so this change will be included into the changelog for the next release. I believe we should change commit message to `docs(core)`, so that we avoid including it (as we do for other docs-related commits). Could you please update the commit message (may be also include additional information on the fix like `docs(core): fixes minor typo in initNgDevMode function docs`) when you get a chance?
> 
> Thank you.

All done @AndrewKushnir

**Comment by AndrewKushnir** [comment]
Thanks @sonukapoor 👍

**Pull request closed without merging**
