### PR TITLE
refactor(common): use `transform` functions in NgOptimizedImage inputs

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit refactors the code of NgOptimizedImage directive to switch from getter/setter approach to convert inputs to use the `transform` function instead.

## PR Type
What kind of change does this PR introduce?

- [x] Refactoring (no functional changes, no api changes)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api 
Reviewed-for: fw-common

**Review by jessicajaniuk — APPROVED** [review]
reviewed-for: public-api

**Comment by crisbeto** [comment]
@AndrewKushnir I'll take a look tomorrow. Interesting that this didn't come up in the router PR though https://github.com/angular/angular/pull/50589

**Comment by crisbeto** [comment]
The error will be fixed by https://github.com/angular/angular/pull/50600.

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:539531956:BASE:539531965:1686541262054:93175e0b).

**Comment by AndrewKushnir** [comment]
**Caretaker note**: presubmit is "green", this PR is ready for merge.

**Comment by pkozlowski-opensource** [comment]
This PR was merged into the repository by commit cefa3de3de09c4d89d660bb7797285b02c43163e.

**Pull request closed without merging**
