### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by JelleBruisten**
fixed a typo: equaivalent to equivalent

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
Thanks for spotting this.

Reviewed-for: global-docs-approvers

**Comment by petebacondarwin** [comment]
Would you please fix the commit message to match our required syntax. Perhaps:

```
docs: fix typo in the README
```

**Comment by JelleBruisten** [comment]
> docs: fix typo in the README

Hey, I changed the commit message like you asked.

**Comment by petebacondarwin** [comment]
Unfortunately we have ended up with 4 commits:

Screenshot 2021-11-04 at 15 37 03

Could you rebase and squash all the commits into one please?

**Comment by JelleBruisten** [comment]
I had some troubles squashing them into one commit, but managed to do it now. Can you verify?

**Comment by petebacondarwin** [comment]
Perfect! Thanks @JelleBruisten .

**Review by gkalpak — APPROVED** [review]
Thx, @JelleBruisten :+1:

<sub>(FYI, I updated the commit message to say `CHANGELOG` instead of `README` :smiley:)</sub>

**Comment by atscott** [comment]
Updating this to merge to master only since it conflicts with the `13.0.x` branch. Please open a new PR that targets that branch if you would like this merged there as well.

**Comment by atscott** [comment]
This PR was merged into the repository by commit 64af4b9c1b33f59e1b811b1863ef3e27a6d7390d.

**Pull request closed without merging**
