### PR TITLE
docs: Add Human Coders trainings in resources.json

### PR DESCRIPTION
**Pull request by camilleroux**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Add trainings made by Human Coders (France)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by camilleroux** [comment]
I signed it!

**Comment by camilleroux** [comment]
I signed it!

**Review by ocombe — APPROVED** [review]

**Comment by ocombe** [comment]
Tiens salut Camille, c'est marrant de te voir faire une PR ici :)

I can vouch for Camille, we can approve that PR

**Comment by camilleroux** [comment]
@ocombe Je ne m'attendais pas à faire un commit sur Angular non plus ^^
Merci pour ton message 👍

**Review by StephenFluin — APPROVED** [review]

**Pull request closed without merging**
