### PR TITLE
refactor(core): allow passing passive option to addEvent

### PR DESCRIPTION
**Pull request by jeantimex**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
This PR makes event library's `addEventListener()` calls `EventTarget.addEventListener()` with `options` instead of `useCapture`. This allows us to pass or override `passive` option for improving scroll performance in future PRs.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
 - Passing `options` to `EventTarget.addEventListener` is not supported in IE11
 - `removeEventListener()` doesn't recognize `passive` option
 - This PR is created because I messed up https://github.com/angular/angular/pull/58198 :)

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Review by rahatarmanahmed — APPROVED** [review]

**Comment by rahatarmanahmed** [comment]
Can you link the passing TGP rerun?

**Review by pkozlowski-opensource — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Comment by jeantimex** [comment]
> Can you link the passing TGP rerun again?

Sure, here is the new [result](https://fusion2.corp.google.com/presubmit/688699245/OCL:688699245:BASE:689080301:1729714804668:1508a7f6;groups=Pending/targets), all passed.

**Comment by AndrewKushnir** [comment]
TESTED=[Green TGP](https://fusion2.corp.google.com/presubmit/688699245/OCL:688699245:BASE:689080301:1729714804668:1508a7f6;groups=Pending/targets).

**Comment by AndrewKushnir** [comment]
**Caretaker note**: TGP is "green", this PR is ready for merge.

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 2aa9f8b071a64b412e66b3a6bbc0cb374752c8ac.

The changes were merged into the following branches: main, 19.0.x

**Pull request closed without merging**
