### PR TITLE
docs(changelog): remove reverted fix from 6.1.10 changelog

### PR DESCRIPTION
**Pull request by JoostK**
This fix was reverted in 7466a99dda68cbfada4bc986a9bca80b87e05702

### CODE REVIEW

**Comment by JoostK** [comment]
Please also cherry-pick into patch, if that applies cleanly.

**Comment by JoostK** [comment]
@IgorMinar could you have a look, thanks. Travis/CircleCI is red for unrelated reasons, I can rebase if needed but doesn't seem that useful.

**Review by IgorMinar — APPROVED** [review]
thanks for the update. the ci was flaky.

caretaker note: please rebase unless @JoostK beats you to it. thanks!

**Comment by JoostK** [comment]
Rebased onto master, which is red atm so this PR is red as well 😅

**Comment by JoostK** [comment]
@IgorMinar I think the `PR target` label should include `master`, as that's the main up-to-date location of the changelog. As `patch` now targets 7.0.x (it does, right?) it may not make a lot of sense to include this in 7.0 but not in 6.1.x. Your call what's best here.

**Pull request closed without merging**
